### ISSUE TITLE
第一个

### ISSUE THREAD

**Issue by myronliu347** [iview/iview#1]
先问几个正经的问题吧：
1. 这个支持vue2么？
2. 设计风格是啥，感觉很熟悉？
3. 浏览器的兼容版本是啥啊

然后呢
 我觉得这个组件图挺好看的，在哪话的呀。

最后，点个赞

**Comment by icarusion** [comment]
1.目前还不支持2.0；
2.UI目前主要借鉴自Bootstrap和Ant.Design，会在此基础上进行优化；
3.文档中有写，IE9+

思维导图用的是MindNode
