### ISSUE TITLE
Cascader 优化在 trigger: hover 加 change-on-select 模式下的体验

### ISSUE THREAD

**Issue by XXLeeS** [iview/iview#1001]
### iView 版本号
2.0.0-rc.14

### Vue 版本号
2.2.3

### 问题现象，以及你期望的结果是怎样的?
希望在 trigger: hover 及 change-on-select 的模式下
能够增加点击parent选单就收起的设定
用起来的体验会比较像一般浏览网站的导航列

**Comment by icarusion** [comment]
Update to the latest version.
