### ISSUE TITLE
Cascader 增加自定义配置数据结构字段名称的建议

### ISSUE THREAD

**Issue by Ivorzk** [iview/iview#1002]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
Cascader 能否增加数据结构的自定义配置，比如
`[{
                    value: 'beijing',
                    label: '北京',
                    children: [
                        {
                            value: 'gugong',
                            label: '故宫'
                        },
                        {
                            value: 'tiantan',
                            label: '天坛'
                        },
                        {
                            value: 'wangfujing',
                            label: '王府井'
                        }
                    ]
                }]`
这段数据中，我的服务端下来的数据，是这样的，
`[{
                    _key_: 'beijing',
                    name: '北京',
                    children: [
                        {
                            _key_: 'gugong',
                            name: '故宫'
                        },
                        {
                            _key_: 'tiantan',
                            name: '天坛'
                        },
                        {
                            _key_: 'wangfujing',
                            name: '王府井'
                        }
                    ]
                }]`

字段名字不同，但是结构是符合Cascader 所需要的数据结构的，这种情况能否向element-ui 学习一下增加自定义配置data的props 增加一个定义比如
`

### 问题现象，以及你期望的结果是怎样的?
`defaultProps = {
  label: 'name',
  value: '_key_'
}`

这块element-ui 里面是支持这种功能的，而且使用也比较频繁！这个配置可以减少我每次请求数据出来都要对数据进行重新遍历添加字段的问题！
希望能得到解决！感谢！

**Comment by icarusion** [comment]
暂无此计划。
