### ISSUE TITLE
tree实现前端模糊查询

### ISSUE THREAD

**Issue by xcodebin** [iview/iview#1006]
### iView 版本号

2.0.0-rc.14 
### 操作系统/浏览器 版本号

Chrome 56
### Vue 版本号

^2.2.6

**Comment by xiaozhang98** [comment]
能实现tree实现前端模糊查询功能吗

**Comment by xiaozhang98** [comment]
不能实现就改用ztree了

**Comment by bluesky59** [comment]
> 不能实现就改用ztree了

能实现啊

**Comment by wangchengnan** [comment]
项目怎么运行起来
