### ISSUE TITLE
【Notice】 the global method is invalid

### ISSUE THREAD

**Issue by haixu777** [iview/iview#1009]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/JNzMGb

### 问题现象，以及你期望的结果是怎样的?
调用Notice的全局方法无效
`this.$Notice.close(key)`
`this.$Notice.destroy()`

**Comment by icarusion** [comment]
@lcx960324 回头有空帮忙看看这个吧，我记得修复过一次？

**Comment by lcx960324** [comment]
@icarusion 之前修复的是 Message 的全局 Destroy 方法，我试一下能不能用相同的方法修复这个问题吧。

**Comment by lcx960324** [comment]
Fixed @icarusion #1054
