### ISSUE TITLE
关于Tabs的创建与销毁的问题

### ISSUE THREAD

**Issue by IrvingZhao** [iview/iview#1012]
编辑一下：下面有一个概念错了，不是溢出，是泄露

===========================

能问一下，关于tabs这个组件的 tab-panel  页签加载完成事件以及销毁时的标签页错乱问题
` Tabs(type="card",closable,@on-tab-remove="handleTabRemove",:value="tabActiveName")`
`                template(v-for="tab in tabs")`
`                    Tab-pane(:name="tab.pageId",:label="tab.label",closable="true")`
`                        div(:id="tab.pageId")`
`                            tab-page`

tab-page 是其他的一个自定义组件

现在出现的问题是
1. 无法监听到  单个标签页添加的事件，所以无法简便的渲染 额外的组件，只能通过定时器获得节点后渲染
2. 在页面销毁时，当标签页删除时，tabs数组中的值的数量与实际展示的数量不一致，如果删除的话，则会导致页签再次减少一个，如果不删除的话，会有内存溢出的风险

**Comment by lvqingan** [comment]
个人经验，通常tabs删除错乱都跟v-for的:key有关

**Comment by IrvingZhao** [comment]
@lvqingan 但是有一个问题就是，如果不用 v-for 的话  怎么动态添加页签呢

**Comment by yt286** [comment]
我也遇到了类似问题，根据api的handleTabRemove方法关闭tab页，只是删除了nav里的dom，content里的dom没有删除，导致了错乱，有解决方法么？

**Comment by lvqingan** [comment]
试试在`$nextTick`里调用`updateNav()`

**Comment by icarusion** [comment]
使用 v-for 时需要设置正确的 key，销毁逻辑是自己控制的，Vue 2 不允许内部销毁，操作文档相关示例。

**Comment by linjackson78** [comment]
我也是用 v-for 来渲染 Tab-pane，也遇到数组已经改动（例如 Array.splice）但是 Tabs 和 Tab-pane 没有响应地跟着一起改动的情况。

在如下调用之后，才正常：

```js
this.$nextTick(function () {
    this.$refs.tabs.updateNav();
});
```

或许 iview 的 Tabs 应该再完善一些，使用者不应该需要主动调用 `updateNav()`。

**Comment by OwnGhy** [comment]
请问是怎么解决的？没明白updateNav()是什么方法？可以贴下代码么？😢

**Comment by KrishnaPG** [comment]
User should not be needed to keep the data in sync with the UI. The tab should user `v-model` to keep the data in sync.
The method `on-tab-remove` is called with a number as argument. User will be forced to maintain the array and keep managing the position. Instead `on-tab-remove` method should supply the key or ID of the tab as parameter

**Comment by tristan-tsl** [comment]
I also meet this problem, thank your answer

**Comment by tristan-tsl** [comment]
link the issue: https://github.com/iview/iview/issues/2100
this problem is also exist in latest version, thank you
