### ISSUE TITLE
table在使用v-if时的bug，以及修复建议

### ISSUE THREAD

**Issue by caomulaodao** [iview/iview#1016]
### iView 版本号
2.0.0-rc.14 

### 复现步骤
tab page中的子组件使用了v-if，子组件中包含table，切换tab时候table出现报错。

###代码截图
tab组件中子组件使用了v-if
![tab组件](http://7xraih.com1.z0.glb.clouddn.com/QQ20170526-0.png)
子组件包含table组件
![子组件](http://7xraih.com1.z0.glb.clouddn.com/QQ20170526-1.png)

抱歉没使用在线演示，如果不好理解我在搞一下在线演示。

###报错截图
![tab组件](http://7xraih.com1.z0.glb.clouddn.com/QQ20170526-2.png)

### 你估计可能的原因是什么（选填）？
研究了下，错误出现在table组件的handleResize方法中，因为tab切换的时候，table会因为v-if而被销毁。
table被销毁后，异步的handleResize函数执行的时候使用了_this.$refs.tbody.$el会找不到元素，所以报错了。
https://github.com/iview/iview/blob/2.0/src/components/table/table.vue#L316

所以，我建议在handleResize中首先判断_this.$refs.tbody的存在，在执行。
目前我在handleResize函数中加了这行代码可以解决报错问题
 if(!_this.$refs.tbody){return false}

**Comment by chouchou900822** [comment]
+1

**Comment by ihuguowei** [comment]
试试 v-show 作临时解决方案呢？

**Comment by chow-xiang** [comment]
应该是tabs.vue引起的。
[https://github.com/iview/iview/blob/2.0/src/components/tabs/tabs.vue#L234](https://github.com/iview/iview/blob/2.0/src/components/tabs/tabs.vue#L234)

activeKey值变换时，`this.broadcast('Table', 'on-visible-change', true);`
所以，我想到的方案是，在组件mounted时，$off掉这个事件。
比如：
`this.$refs.versions.$off('on-visible-change')`

**Comment by icarusion** [comment]
Update to the latest version.
