### ISSUE TITLE
关于input type为textarea的 autofocus问题

### ISSUE THREAD

**Issue by boxshadow** [iview/iview#1017]
### iView 版本号
2.0.0-rc.14

### 操作系统/浏览器 版本号
Ubuntu 16.04 LTS/Chrome 58

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://tsplus.zhibocloud.cn/web

### 复现步骤
进入列表，点击回复图标，弹出回复输入框 无法自动获取焦点

### 你估计可能的原因是什么（选填）？
我看一下 input.vue的源码， textarea 并没有实现 autofocus
`<textarea
            v-else
            ref="textarea"
            :class="textareaClasses"
            :style="textareaStyles"
            :placeholder="placeholder"
            :disabled="disabled"
            :rows="rows"
            :maxlength="maxlength"
            :readonly="readonly"
            :name="name"
            :value="value"
            @keyup.enter="handleEnter"
            @focus="handleFocus"
            @blur="handleBlur"
            @input="handleInput">
        </textarea>`

不知道是什么原因没有实现textarea的autofocus

**Comment by icarusion** [comment]
应该是漏了
