### ISSUE TITLE
Table的render函数在jsx写法下的诸多问题

### ISSUE THREAD

**Issue by chenfengjw163** [iview/iview#1018]
1.很多组件并没有提供i-xxxx的小写模式，导致使用jsx时大写组件名被识别为对象名，报错！
2.组件中的事件在jsx下无法绑定on-xx事件，jsx中onxxx无法识别

**Comment by lvqingan** [comment]
事件是能监听的，就是写的有点丑，譬如on-change，需要写成
```javascript
onOn-change={() => {/*your code here*/}}
```
**注意大小写**

**Comment by icarusion** [comment]
这与 iView 一开始定的 API 有关，后续会将所有事件的 `on-` 去掉。

**Comment by YikaJ** [comment]
确实在 render 模式下 JSX 的写法会出很多问题，特别像 Icon ，会被直接认为是 undefined。render 在非 JSX 下的写法确实挺丑的。希望大家可以一起解决。

**Comment by icarusion** [comment]
#476

**Comment by luckymore** [comment]
Another year over... come on

**Comment by woshilaoge** [comment]
yeah , come on

**Comment by Ryan724** [comment]
come on...

**Comment by Hank-tku** [comment]
9012, come on
