### ISSUE TITLE
表单上的样式小建议

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1022]
![image](https://cloud.githubusercontent.com/assets/1802631/26517406/56d1d3ea-42ca-11e7-8589-0d58513e51fe.png)

![image](https://cloud.githubusercontent.com/assets/1802631/26517427/cd6550a4-42ca-11e7-8791-a4c10b787729.png)

官网上的表单.ivu-form-item设置了margin-bottom:24px,如果表单校验出现 error的时候是没有问题的。

但是如果我把.ivu-form-item设置为12PX(24间距太大了)，出现error的时候错误信息就会给遮住。

建议：.ivu-form-item-error设置一个margin-bottom:24px

这样就可以自适应了

**Comment by icarusion** [comment]
这是有设计规范的。https://ant.design/docs/spec/introduce-cn
