### ISSUE TITLE
table 组件中，render 方法不能正确渲染组件

### ISSUE THREAD

**Issue by rochesk** [iview/iview#1023]
### iView 版本号
2.0.0-rc.14

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
昨天升级后，table 组件中，render 方法不能正确渲染组件
` render: (h, params) => {
            return h("div", [
                h('button', {
                    props: {
                        type: 'primary',
                        size: 'small'
                    }
                }, '查看'),
            ]);
        }`
以上代码只会渲染`<button>查看</button>`

**Comment by icarusion** [comment]
注意大小写

**Comment by rochesk** [comment]
是我打错了，Button还是不会渲染

**Comment by icarusion** [comment]
提供在线示例

**Comment by rochesk** [comment]
我更新了依赖项就可以了
多谢兄台！
