### ISSUE TITLE
Select 在单选 remote 模式下，v-model选中项显示的值为 value 而不是 label

### ISSUE THREAD

**Issue by snailMa** [iview/iview#1025]
### iView 版本号
2.0.0-rc.14 

### 操作系统/浏览器 版本号
win10 chrome

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://runjs.cn/detail/ahmghqlu

**Comment by icarusion** [comment]
阅读 Select 文档的 label 字段
