### ISSUE TITLE
input组件绑定名字为“number”时验证失败

### ISSUE THREAD

**Issue by wploey** [iview/iview#1027]
### iView 版本号

1.0-2.0
### 操作系统/浏览器 版本号

macOS
### Vue 版本号

1.0-2.0
### 问题现象，以及你期望的结果是怎样的?
Input组件或者iview的i-input组件都会出现此问题。使用双向绑定，并且数据三层结构，如requestData[param.in][param.name]；，指定验证类型为“integer”；并且数据对应的键名为“number”，如前例中的param.name为number时，表单验证会失败，提示没有填入数据，但通过chrome的vue Devtools查看发现数据已经存在，并且动态改变，填入字母change后验证成功，却在提交时验证失败。而验证类型同为“integer”的其他项目可以正常验证。后取消Input的“Number” props，并且使用async-validator的transform手动转化为number后才得以验证成功。
### 你估计可能的原因是什么（选填）？
不知道是我用法有问题还是“number”名字冲突？？

**Comment by icarusion** [comment]
type: 'number'
