### ISSUE TITLE
$Modal.confirm的ok事件里面如果再调用Model弹出其他框，会被一闪就关闭

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1030]
### iView 版本号

2.0.0-rc.14
### 操作系统/浏览器 版本号

Chromium53
### Vue 版本号

2.3.0
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/GmbrGJ
(这在线编辑器真不知道怎么用，将就写了个demo)
### 复现步骤
1.点击按钮弹出confirm窗口
2.点击ok
### 问题现象，以及你期望的结果是怎样的?
执行$Modal.confirm弹出让用户点击继续执行操作，还是取消操作，
如果点击了ok，在ok里面做一些逻辑，例如检测表单是否符合提交要求，如果不符合，则弹出提示框，
如果这个弹出提示框用的是$Modal.error的话，
这个弹出的窗口会一闪就消失。
### 你估计可能的原因是什么（选填）？
应该是confirm的ok事件里执行了关闭窗口的脚本，连同这个error的Model也一起关闭了，
我的解决方案是延迟1秒再执行onOK的事件。

**Comment by zxyling** [comment]
加定时器延迟调用

**Comment by icarusion** [comment]
The answer above is correct

**Comment by coolerTang** [comment]
点确认按钮的时候，触发了关闭事件，加延迟执行能解决
