### ISSUE TITLE
tab页过多时没有向左右滑动的按钮

### ISSUE THREAD

**Issue by marxy** [iview/iview#1031]
# iview效果
![tabs](https://cloud.githubusercontent.com/assets/12171912/26583372/8b270f3e-4577-11e7-8376-549ee6ed5e65.png)

# element-ui效果
![tabs_issue](https://cloud.githubusercontent.com/assets/12171912/26583217/e1b510c2-4576-11e7-93ec-5babb5b10bd4.png)
如图，tab页过多的时候没有像element-ui一样的可以向左右滑动的按钮

## iView 版本号
2.0.0-rc.14

### 操作系统/浏览器 版本号
macOS/Chrome 58

### Vue 版本号
2.2.6

### 问题现象，以及你期望的结果是怎样的?
希望能有向左右滑动的按钮

**Comment by icarusion** [comment]
https://github.com/iview/iview/projects/3

**Comment by xkcoding** [comment]
@marxy 您好，我现在有个类似左侧是导航，右侧是 tab 的需求，您可以把这个 demo 发我参考下吗。导航和 tab 的联动有些懵。谢谢。。

**Comment by gosongs** [comment]
@xkcoding http://element.eleme.io/#/zh-CN/component/tabs

**Comment by icarusion** [comment]
#2156
