### ISSUE TITLE
table render创建元素不能添加href属性

### ISSUE THREAD

**Issue by GodFaker** [iview/iview#1035]
我打算用iview中的icon按钮替代button,但是icon中不能添加事件。因此我就在外边又包了一层div。此时div中可以添加事件。但是我又发现render函数中创建的元素无法自由的添加html属性。例如href:'javascript'。这样用户体验会差一些。如图
<img width="1034" alt="2017-05-31 10 51 09" src="https://cloud.githubusercontent.com/assets/15864363/26613791/1430d9a0-45ef-11e7-84e9-cb65d91b8252.png">

**Comment by icarusion** [comment]
查阅 Vue 文档 Render 函数
