### ISSUE TITLE
Message能否对duration类型进行判断，如果是function就做为onClose

### ISSUE THREAD

**Issue by liyahui** [iview/iview#1036]
### iView 版本号

2.0.0-rc.14

### 复现步骤
![image](https://cloud.githubusercontent.com/assets/6090747/26614755/bb8347e2-45f4-11e7-8815-1d3f676069ab.png)

```js
this.$Message.success('success', () => {
  console.log('onClose')
})
```

### 问题现象，以及你期望的结果是怎样的?
能否对`duration`类型进行判断，如果是`function`就做为`onClose`，因为很多时候，我需要`onClose`，并不需要重新设置`duration`。

**Comment by icarusion** [comment]
后面会扩展 Message 等功能，参数会改为对象

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/e0bd31a64c8ea0452dba1c3e6b4f9a40594f587a
