### ISSUE TITLE
upload上传图像

### ISSUE THREAD

**Issue by lunhuihan** [iview/iview#1037]
上传图像功能中，上传前获取不到图像的本地地址，导致一个问题，用户看到图像上传成功可是图像没有很及时的变调，因为成功后要向后台获取，时间比较长。

**Comment by icarusion** [comment]
有file对象

**Comment by wei236611** [comment]
但是这个file对象有问题，我想拿到上传图片的base64地址，使用new FileReader().readAsDataURL(file)这个方法获取有问题
