### ISSUE TITLE
首页背景图

### ISSUE THREAD

**Issue by liuzhibin123** [iview/iview#1043]
https://www.iviewui.com/  我想知道  你这个首页背景3d动图是怎么做的？

**Comment by icarusion** [comment]
github.com/iview/iview-doc

**Comment by liuzhibin123** [comment]
？ 不管怎样  给个方向 思路啊

**Comment by Cydmi** [comment]
@liuzhibin123 treeJs 实现的 给你个地址[ 给你个地址](http://www.css88.com/archives/5996/comment-page-1)

**Comment by liuzhibin123** [comment]
@Cydmi three.js太大了，我看到他们这个很小 应该是做过切割提取。不知道这应该怎么做?

**Comment by icarusion** [comment]
详见github.com/iview/iview-doc，用的 three 25版本

**Comment by TrendAlan** [comment]
代码拔出来了，例子在这里了 https://jsfiddle.net/oep9bnuq/
