### ISSUE TITLE
table中用render函数，然后用vuex进行数据处理，this实例指向当前state而非当前vue

### ISSUE THREAD

**Issue by liufeics** [iview/iview#1048]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
按照新版的render函数如果想对数据在vuex处理，vue中的所有定义都无法被调用，实例无法被传输
### 你估计可能的原因是什么（选填）？
在实现dom的时候，table中的this先被创建在整个页面加载之前，所以，vue中的所有实例方法无法调用

**Comment by lcx960324** [comment]
关于 Table 的 this binding 的问题在 iView 2.0.0 rc.12 之后已经解决了，请升级一下自己的框架版本。

**Comment by H5futurehreohanshuo** [comment]
能说一下怎么做吗
