### ISSUE TITLE
select 远程搜索 示例输入Alabama 然后删除 鼠标离开后 又出现了

### ISSUE THREAD

**Issue by yangchao313** [iview/iview#1049]
### iView 版本号

2.0.0-rc.15 
### 操作系统/浏览器 版本号

 win7/Chrome 56 
### Vue 版本号

2.2.1 
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://www.iviewui.com/components/select     
### 复现步骤
远程搜索单选  先输入Alabama  然后删除后  鼠标离开后  又显示在输入框里面

**Comment by icarusion** [comment]
清空有清空的方法
