### ISSUE TITLE
Date-picker里daterange校验一直不通过

### ISSUE THREAD

**Issue by iamgaohui** [iview/iview#1051]
### iView 版本号

 2.0.0-rc.15 
### 操作系统/浏览器 版本号

Windows 10 /Chrome
### Vue 版本号

2.2.1
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/ZyzzqY

### 复现步骤
选择日期后，校验一直不通过
### 问题现象，以及你期望的结果是怎样的?
选择日期后校验通过
### 你估计可能的原因是什么（选填）？
选择日期后返回的值是一个数组，我估计校验的时候只校验了字符串

**Comment by iamgaohui** [comment]
大神们不解决一下吗？

**Comment by icarusion** [comment]
要指定验证类型，去看[async-validator](https://github.com/yiminghe/async-validator)文档

**Comment by jiaotangsnow** [comment]
指定验证类型后报错 value.getTime is not a function，请问能提供解决的方案吗

**Comment by lvangorysky** [comment]
需要制定类型type: "array",如
dateRange: [
          { required: true, type: 'array' ,message: '请选择上下线时间', trigger: 'change' },
        ]
但是这样会有另外一个问题
第一次不输入的时候 可以校验成功
但是如果第二次清空第一次输入的内容时，datePicker返回的值为["",""]
此时则会通过校验

**Comment by qbunia** [comment]
When it will be fixed?

**Comment by icksky** [comment]
```json
{
    "daterange": [
        {
            "required": true,
            "type": "array",
            "trigger": "change",
            "fields": {
                "0": {
                    "type": "date",
                    "message": "日期不能为空",
                    "required": true
                },
                "1": {
                    "type": "date",
                    "message": "日期不能为空",
                    "required": true
                }
            }
        }
    ]
}
```

**Comment by just-wkj** [comment]
谢谢,解决了我的问题
