### ISSUE TITLE
Form表单内使用select，ivu-select-dropdown定位不准导致显示不出来，不使用From包装，select能正常使用

### ISSUE THREAD

**Issue by lzming1989** [iview/iview#1053]
### iView 版本号
2.0.0-rc.5 

### 操作系统/浏览器 版本号
win10/Chrome 56

### Vue 版本号
2.2.1

**Comment by lcx960324** [comment]
请提供代码样例，谢谢~

**Comment by xiaoyyang123** [comment]
刚也遇到了 `ivu-select-dropdown` 定位不准这个问题，我想他说的问题应该是这个 #818，我的解决办法是利用 `v-transfer-dom` 指令将 `<div v-transfer-dom class="ivu-select-dropdown" :style="styles"><slot></slot></div>`这一块给直接添加到`body`下面，这样就不会跟父级样式起冲突了。

**Comment by lzming1989** [comment]
我描述缺失不准，是 #818 这个问题，添加如下代码解决

> 
.ivu-select-dropdown
 {
    position: absolute !important;
}
