### ISSUE TITLE
Form-item validateStatus prop has wrong type

### ISSUE THREAD

**Issue by ozeebee** [iview/iview#1055]
### iView 版本号

2.0.0-rc.15

### 操作系统/浏览器 版本号

macOS/Chrome 56
### Vue 版本号

2.3.3
### 问题现象，以及你期望的结果是怎样的?

Form-item's `validateStatus` prop is declared as boolean:
```
            validateStatus: {
                type: Boolean
            },
```
but the watch function copy its value in the `validateState` which is supposed to be a String:
```
        watch: {
            ...
            validateStatus (val) {
                this.validateState = val;
            }
        },

```

Solution: declare the `validateStatus` prop as a String or test the boolean value to set the `validateState` property to either `'error'` or `'success'`

**Comment by icarusion** [comment]
`validateState` is not a prop, it is a data.

**Comment by ozeebee** [comment]
`validateState` is a data and is expecting a String
but `validateStatus` is a prop and is declared as a Boolean

![image](https://cloud.githubusercontent.com/assets/1236583/26716541/1b8b5072-477a-11e7-874d-c1938fb5a6e2.png)
