### ISSUE TITLE
upload 上传default-file-list 在mount函数中赋值无效？

### ISSUE THREAD

**Issue by denghp** [iview/iview#1061]
### iView 版本号

2.0.0-rc.15
### 操作系统/浏览器 版本号

macOS/Chrome 56
### Vue 版本号

2.2.1
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

官方demo,自定义上传列表

```
mounted () {
      this.mockData() // 后台接口获取相关数据，然后设置默认上传的图片列表
      this.defaultList = [
        {
          'name': 'a42bdcc1178e62b4694c830f028db5c0',
          'url': 'http://desmao.oss-cn-hangzhou.aliyuncs.com/default/20170525/59268af652f62.jpg'
        },
        {
          'name': 'bc7521e033abdd1e92222d733590f104',
          'url': 'https://o5wwk8baw.qnssl.com/bc7521e033abdd1e92222d733590f104/avatar'
        }
      ]
    }
```

**Comment by gggllm** [comment]
确实没有用，filelist里的对象如果在外部有引用似乎就会引起filelist重置为新的数组，导致bug。

**Comment by liufeics** [comment]
给你一个暂时的解决方案,先对upload控件进行v-if隐藏或者说让dom不渲染，然后对default-file-list 赋值,当赋值成功以后让upload控件渲染出来 这样可以达到你要对效果。

**Comment by gggllm** [comment]
我的方案是缓存当前list看和之前的list是否相同，不同的话就把当前的list与之前的list合并。

**Comment by hazeFlame** [comment]
我用v-if控制没效果呀

**Comment by C-qilong** [comment]
有人解决了这个问题吗？

**Comment by wjjshine** [comment]
同用v-if无效果，应该怎么解决呢？

**Comment by needou** [comment]
v-if试过无效，有个比较贱的方法，直接处理uploadList ，异步获取数据后赋值uploadImgList.push({
                                    url:‘url’ ,
                                    showProgress:false,
                                    status : 'finished'
                                });
上传成功后回调也直接uploadImgList.push({
                                    url:‘url’ ,
                                    showProgress:false,
                                    status : 'finished'
                                });，基于这个变量来处理是可以的

**Comment by dyq086** [comment]
在mount 中模拟异步，因为DOM 还未更新，所以你拿不到数据
        setTimeout(() => {
            this.defaultList = [{
                    'name': 'a42bdcc1178e62b4694c830f028db5c0',
                    'url': 'https://o5wwk8baw.qnssl.com/a42bdcc1178e62b4694c830f028db5c0/avatar'
                },
                {
                    'name': 'bc7521e033abdd1e92222d733590f104',
                    'url': 'https://o5wwk8baw.qnssl.com/bc7521e033abdd1e92222d733590f104/avatar'
                }
            ]
            this.$nextTick(() => {

                this.uploadList = this.$refs.upload.fileList;
            })


        }, 1000)

**Comment by dyq086** [comment]
在mount 中模拟异步，因为DOM 还未更新，所以你拿不到数据
setTimeout(() => {
this.defaultList = [{
'name': 'a42bdcc1178e62b4694c830f028db5c0',
'url': 'https://o5wwk8baw.qnssl.com/a42bdcc1178e62b4694c830f028db5c0/avatar'
},
{
'name': 'bc7521e033abdd1e92222d733590f104',
'url': 'https://o5wwk8baw.qnssl.com/bc7521e033abdd1e92222d733590f104/avatar'
}
]
this.$nextTick(() => {
            this.uploadList = this.$refs.upload.fileList;
        })
    }, 1000)

**Comment by SugarTiger** [comment]
可以解决：
`this.$nextTick(() => {
this.uploadList = this.$refs.upload.fileList;
})`

**Comment by xiaomizhou66** [comment]
做这个上传图片不成功，请问有人可以提供一个完整的例子么，官网的实在看不懂

**Comment by 1393983569** [comment]
用props传入default-file-list的值一直报错 有遇到的吗 
Error in callback for watcher "value": "Value should be trueValue or falseValue."

**Comment by SunXinFei** [comment]
> v-if试过无效，有个比较贱的方法，直接处理uploadList ，异步获取数据后赋值uploadImgList.push({
> url:‘url’ ,
> showProgress:false,
> status : 'finished'
> });
> 上传成功后回调也直接uploadImgList.push({
> url:‘url’ ,
> showProgress:false,
> status : 'finished'
> });，基于这个变量来处理是可以的

可以解决问题
