### ISSUE TITLE
Modal loading 在一种情景需要重置

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1067]
当我们弹出modal的时候，按确定触发loading请求数据，然而有一种失败的场景，需要重置loading而不关闭modal。

目前好像没有这功能。

**Comment by dean5277** [comment]
loading应该变成计算属性。

**Comment by icarusion** [comment]
自己控制 loading

**Comment by xiaoxiemagic** [comment]
这个“自己控制loading”有点无语，如果是试用render不能slot的情况下，怎么“自己控制”？？
