### ISSUE TITLE
Collapse 通过v-for生成的Panel,无法通过v-model来设置默认展开的panel

### ISSUE THREAD

**Issue by yhuaqiang** [iview/iview#1070]
<Collapse v-model="pid" accordion @on-change="changePage">
          <Panel v-for="(p,i) in pages" :name="i+''" :key="i">
            <div class="panel_header">
              <span>{{p.name}}</span>
            </div>
            <div slot="content">
              
            </div>
          </Panel>
        </Collapse>

export default {
   data() {
       return {
         pid: '0',
       }
  }
}

运行不会打开第一个panel, 但是如果Collapse是hardcode, 则运行正常.
这是个bug吧??

**Comment by icarusion** [comment]
亲测可以。
```html
<template>
    <div style="width: 400px;margin: 200px;">
        <Collapse v-model="v1" accordion>
            <Panel v-for="item in list" :name="item">{{ item }}</Panel>
        </Collapse>
    </div>
</template>
<script>
    export default {
        props: {},
        data () {
            return {
                v1: 'b',
                list: ['a','b','c']
            };
        },
        computed: {},
        methods: {}
    };
</script>
```

**Comment by william807803** [comment]
我的也无法通过v-model来设置默认展开的panel ， 数据是从ajax里获取的

**Comment by Tilang** [comment]
异步数据需要在数据请求完成后设置v-model值，用来触发collapse的watch；

**Comment by yiludege** [comment]
异步ajax请求，获取到list之后，再用```this.$nextTick(() => { this. pid = XXX})```或者挂到下一个```then ( () => { this.pid = XXX} )```才可生效
