### ISSUE TITLE
下拉菜单。IE9下点击 报错

### ISSUE THREAD

**Issue by hlerenow** [iview/iview#1072]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
win7/ie9

### Vue 版本号
2.2.1

### 复现步骤
![image](https://cloud.githubusercontent.com/assets/13299648/26749367/bdb6e610-483b-11e7-8517-13e3ee037098.png)

### 问题现象，以及你期望的结果是怎样的?
点击下拉菜单项，ie9浏览器报错，

### 你估计可能的原因是什么（选填）？
root.performance.now()函数不支持，建议try catch

**Comment by icarusion** [comment]
未来不支持 ie9
