### ISSUE TITLE
tab内用tab用不了

### ISSUE THREAD

**Issue by hanzoz** [iview/iview#1073]
![screen shot 2017-06-03 at 9 13 07 am](https://cloud.githubusercontent.com/assets/835436/26749441/4761ec24-483d-11e7-8a8c-d199d126de33.png)

如图，tab内用tab时，用不了，没反应。是不是bug?

iView 

2.0.0-rc.14

操作系统/浏览器 版本号

macOS/Chrome 58

Vue 版本号

2.2.1

**Comment by itpretty** [comment]
建议选用其它 Tab 插件，个人最终选用了 jQuery UI 中的 Tab，因为有些复杂的 Tab 方法 iviewUI 支持得有限。期待 iviewUI 的 Tab 逐渐强大起来！

**Comment by SergioCrisostomo** [comment]
@hanzoz can you please provide a example of this behaviour? 

使用下面的在线链接可以快速创建示例 
https://codepen.io/anon/pen/BWwVoy
