### ISSUE TITLE
动态创建的menu 无法初始化展开

### ISSUE THREAD

**Issue by liufeics** [iview/iview#1074]
### iView 版本号
2.0.0-rc.15

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://jsfiddle.net/fei_liu/uv7q8xyt/11/

### 问题现象，以及你期望的结果是怎样的?
初始化的时候展开相信的menu

**Comment by itpretty** [comment]
应该是 :open-names="[1]" 而不是 :open-names="[‘1’]"
你在定义 code 时，值用的是 int

**Comment by icarusion** [comment]
The answer above is correct
