### ISSUE TITLE
form中使用Cascader，表单验证为必输，总是提示该字段为空

### ISSUE THREAD

**Issue by xuechaogit** [iview/iview#1075]
### iView 版本号
2.0.0-rc.5 

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

**Comment by itpretty** [comment]
在官方“表单验证”的演示例子中，只有类似原生的表单控件，其它扩展的酷炫的表单控件并没有展示。试过 inputNumber，slider 等，表单 reset 时也并不能恢复原值。这些在验证时，估计也会有问题，没有试过。

另外，没有复现问题的在线示例，不会得到任何官方回复的。切记！

**Comment by Demon2** [comment]
{ required: true, message: '请选择XX', trigger: 'change' }  选择后验证不通过
修改过为：
{ required: true,  type: 'array',message: '请选择XX', trigger: 'change' }  成功验证
