### ISSUE TITLE
Select 选择器和Tree 树形控件的两个小问题

### ISSUE THREAD

**Issue by 68zch** [iview/iview#1076]
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/zhoou/yu3m6uy2/

### 问题现象，以及你期望的结果是怎样的?
1、自己写了一个清空节点选中状态的函数（见示例），发现当一级菜单下面没有全选的时候会有‘－’号，不知道如何去除，建议Tree属性添加一个清空节点选中状态的函数。

2、Select 选择器多选的时候高度会变大，有时候会影响布局，建议出一个不换行出省略号的属性
这样还可以避免选项换行导致选不准的问题（不知道为什么在jsFiddle网站多选下拉菜单不起作用，因此没有演示）

**Comment by xcodebin** [comment]
支持此需求，另外你们前端不需要模糊查询功能吗？也希望支持这个。

**Comment by itpretty** [comment]
直觉判断：因为每次点选有动画效果，很多触发有延迟，可能在渐隐动画结束时触发改变相关 vm 中的属性值。而你的三层 $.each 是一口气直接循环完成，在所有节点改为 false 后，某些动画结束时才会触发相关改变，所以异常又变成非 false 状态。

**Comment by icarusion** [comment]
更新至最新版。
1. 维护好你的数据。
2. 暂无此计划。
