### ISSUE TITLE
发现表格有2个bug以及提一个建议

### ISSUE THREAD

**Issue by xuelabi123** [iview/iview#1078]
### iView 版本号
2.0.0-rc.5 

### 操作系统/浏览器 版本号
 win10/Chrome 58

### Vue 版本号
2.8.1

### 复现步骤
1、使用render函数显示图片时，img标签的src属性没法添加
2、在表格内使用Poptip 组件，当触发方式为‘click’时，点击表格行时展开的内容不会自动消失

建议：
希望给列添加一个显示与隐藏的属性，hide

### 你估计可能的原因是什么（选填）？
click问题是不是表格行绑定了其他处理事件，阻止了展开的内容隐藏事件？

**Comment by icarusion** [comment]
Update to the latest version.
