### ISSUE TITLE
Select 组件 api文档完善

### ISSUE THREAD

**Issue by eightHundreds** [iview/iview#1081]
https://www.iviewui.com/components/select
底部api处没有说明key的作用,但是在前文范例代码中有用`:key`

**Comment by itpretty** [comment]
发现同样问题，同意楼主建议。

**Comment by liuyongwei0** [comment]
key到底怎么用啊，还有在on-change事件里面怎么获取key

**Comment by ihuguowei** [comment]
这是 `vue 2.0` 自己的 API https://cn.vuejs.org/v2/guide/list.html#key
