### ISSUE TITLE
table render 图片 显示问题

### ISSUE THREAD

**Issue by bulolo** [iview/iview#1083]
发现render升级了，旧版render不可用,如何直接在表格中渲染出图片？
尝试了下
```
                    {
                        title: 'banner图片',
                        key: 'bannerImg',
                        width: 200,
                        render: (h, params) => {
                            return h('div', [
                                h('img',params.row.bannerImg)  //如何设置图片src 的地址？
                            ]);
                        }
                    }
```
![image](https://cloud.githubusercontent.com/assets/10026498/26760595/f61771b8-494f-11e7-9649-0171fc802858.png)

**Comment by icarusion** [comment]
看 Vue 文档

**Comment by bulolo** [comment]
就是把文档table看了后，发现table render不清晰，难道去看付费那个教程才有？

**Comment by kanongtc** [comment]
arrs: {
  src : '1.png'
}

**Comment by kanongtc** [comment]
attrs: {
  src : src
}

**Comment by llccing** [comment]
[vue文档](https://vuejs.org/v2/guide/render-function.html#ad)

**Comment by xifengxx** [comment]
> {
        title: '广告封面',
        width: 130,
        key: 'cover',
        render:(h,params) => {
          return h('img', {
             attrs: {
                src: params.row.cover,
              },
              style: {
                display:'inline-block',
                width: '100%'
              },
            })
        }
      }
