### ISSUE TITLE
input的textarea的autosize问题

### ISSUE THREAD

**Issue by xugege** [iview/iview#1084]
### iView 版本号
最新代码构建

### 操作系统/浏览器 版本号
windows&chrome

### Vue 版本号
2.*

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
http://sandbox.runjs.cn/show/lj7rxjec

### 复现步骤

打开在线列子，在textarea中的输入内容，内容会被清除掉

### 问题现象，以及你期望的结果是怎样的?
1.如果Input的type=textarea，数据模型绑定的是一个不存在的属性，则会出现上面的情况

`
new Vue({
   data:{
      entity:{},
  }
})
<Input type="textarea" v-model="entity.content" :autosize="true"/>

> 这种情况就会出现上面输入的内容会被清除的问题

2.如果v-model绑定的是一个存在的数据属性，则没有问题，代码如下
new Vue({
   data:{
      **entity:{content},**
  }
})
<Input type="textarea" v-model="entity.content" :autosize="true"/>
`

**Comment by lcx960324** [comment]
在线示例并没有复现您提到的问题。
其次，为啥要绑定一个不存在的数据属性= =

**Comment by xugege** [comment]
@lcx960324 
因为一个表单会有很多属性，会存在一个场景，就是我会从后台加载一个数据对象，可以直接赋值给entity。不需要再js代码中构造一个entity的空对象，空对象包含表单对应的每个属性，

**Comment by lcx960324** [comment]
首先从 Vue 数据绑定的角度，绑定不存在的数据对象，本身就是不合法的行为。
我不知道是我误解了您的表述还是别的原因。v-model 本身是不能够绑定不存在的对象的。

**Comment by xugege** [comment]
@lcx960324 
Vue的文档中提到，data的root属性不支持动态添加，次级属性是可以支持动态增加的
https://cn.vuejs.org/v2/guide/reactivity.html

并且其他表单组件也是支持的，这个只是我的建议

**Comment by lcx960324** [comment]
@xugege 
可能是我理解错您的意思了。
我看不到 runjs 上的代码，同时也没有在您提供的页面中复现这个 bug 。
麻烦粘贴以下代码，谢谢

**Comment by xugege** [comment]
@lcx960324 
在浏览器右键，查看源码是可以看到源码的

源码如下

`<script>new Vue({
	el:"#app",
        template:"<Input v-model=\"entity.content\" type=\"textarea\"  :autosize="\{minRows:6,}\" placeholder=\"请输入...\"/>"
	data:{
		entity:{}
	}
});</script>`

**Comment by xugege** [comment]
@lcx960324 你可以重新打开试试，
http://sandbox.runjs.cn/show/lj7rxjec

**Comment by kiddkyd1412** [comment]
确实是有问题

**Comment by rijn** [comment]
Please read the [Vue doc](https://vuejs.org/v2/guide/forms.html#Multiline-text) about form input bindings.

@icarusion Could you please close this issue.

**Comment by gefangshuai** [comment]
有问题啊

**Comment by gefangshuai** [comment]
@lcx960324 如果你的说法成立，那为什么不加`autosize`却可以呢？明显代码上是有问题的，烦请处理。
@icarusion

**Comment by kiddkyd1412** [comment]
@gefangshuai 这问题在NumberInput控件上也一样。不预先设置好二级属性，会导致值被重置。

**Comment by lcx960324** [comment]
https://jsfiddle.net/nxx66vz2/

How could we support a feature that Vue doesn't support?
@gefangshuai 
@xugege 
@kiddkyd1412 

I kindly suggest you to write a demo to verify your thought before doubting on me. @gefangshuai

**Comment by lcx960324** [comment]
Sorry, I made a mistake. I'll check it again.

**Comment by gefangshuai** [comment]
@kiddkyd1412 所以我直接将iview源码引到项目中，作者修复不及时，项目又赶进度，只能自己来咯

**Comment by lcx960324** [comment]
We've found the bug & it'll be fixed in the next version. Sorry for all.
