### ISSUE TITLE
Cascaer的changeOnSelect的问题

### ISSUE THREAD

**Issue by xugege** [iview/iview#1085]
### iView 版本号
最新代码构建

### 操作系统/浏览器 版本号
windows & chrome

### Vue 版本号
2.*

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
http://sandbox.runjs.cn/show/tj0gepgt

#### 业务描述
1.使用了Cascader的动态加载数据和changeOnSelect
2.在Cascader使用v-model绑定初始值

####期望现象

1.希望Cascader会根据v-model绑定的初始值默认选中并显示到Cascader的输入框中
即选中"北京/百度"

####实际现象

2.只会选中第一个节点 “北京”

### 可能原因
因为打开了changeOnSelect了后，cascader在初始化时，首先会选中第一个值“北京”，触发了数据模型的改变，导致只会选中第一个值

**Comment by lcx960324** [comment]
绑定初始值的时候，应当按照级联顺序进行绑定。
比如：假设北京 /  百度 对应的 value 是 'beijing' / 'baidu' ，那么 北京 / 百度 的 v-model 应当为 ['beijing', 'baidu']

**Comment by xugege** [comment]
@lcx960324 
你看看我提供的在线demo，我是按照["beijing","baidu"]设置的v-model

**Comment by lcx960324** [comment]
@xugege 我这边只能看到运行结果，看不到源代码，麻烦 markdown 贴一下，谢谢~

**Comment by xugege** [comment]
`
new Vue({
	el:"#app",
	template:"<Cascader :data=\"data4\" :load-data=\"loadData\" v-model=\"initData\" :changeOnSelect=\"true\"></Cascader>",
	data :function(){
            return {
                data4: [
                    {
                        value: 'beijing',
                        label: '北京',
                        children: [],
                        loading: false
                    },
                    {
                        value: 'hangzhou',
                        label: '杭州',
                        children: [],
                        loading:false
                    }
                ],
				initData:["beijing","baidu"]
            }
    },
    methods: {
            loadData :function(item, callback) {
                item.loading = true;
                setTimeout(function(){
                    if (item.value === 'beijing') {
                        item.children = [
                            {
                                value: 'talkingdata',
                                label: 'TalkingData'
                            },
                            {
                                value: 'baidu',
                                label: '百度'
                            },
                            {
                                value: 'sina',
                                label: '新浪'
                            }
                        ];
                    } else if (item.value === 'hangzhou') {
                        item.children = [
                            {
                                value: 'ali',
                                label: '阿里巴巴'
                            },
                            {
                                value: '163',
                                label: '网易'
                            }
                        ];
                    }
                    item.loading = false;
                    callback();
                }, 1000);
            }
        }

});
`

**Comment by lcx960324** [comment]
可以考虑使用以下方法解决：
```
            loadingData (item, callback) {
                item.loading = true
                setTimeout( () => {
                    if (item.value === 'beijing') {
                        item.children = [{
                            value: 'baidu',
                            label: '百度'
                        }]
                        this.model4.push('baidu')
                    }
                    item.loading = false
                }, 2000)
            }
```
这个问题我们会继续跟进分析的。

**Comment by icarusion** [comment]
Update to the latest version.
