### ISSUE TITLE
input与button的圆角值可设置

### ISSUE THREAD

**Issue by ckdlbc** [iview/iview#1086]
### iView 版本号

2.0.0-rc.16
### 操作系统/浏览器 版本号

macOs/Chrome 56
### Vue 版本号

2.3.3

### 问题现象，以及你期望的结果是怎样的?
现状：input得在非scoped下去修改border-radius
           button可以直接通过class修改
结果：希望input和button能够通过props更改border-radius
### 你估计可能的原因是什么（选填）？
无

**Comment by icarusion** [comment]
自定义主题
