### ISSUE TITLE
Steps 步骤条动态赋值后样式错乱的bug

### ISSUE THREAD

**Issue by Blackloser** [iview/iview#1088]
### iView 版本号
 2.0.0-rc.16

### 操作系统/浏览器 版本号
windows10

### Vue 版本号
2.2.3

### 问题现象，以及你期望的结果是怎样的?
动态给步骤条赋值后 样式错乱，我期望步骤条动态赋值后仍可以展现出原有的样式。

### 你估计可能的原因是什么（选填）？
不能再动态赋值之后绑定上相应的属性
![step1](https://cloud.githubusercontent.com/assets/26319882/26776463/d33b86f4-4a0b-11e7-9ba6-4df27d8f7547.png)
![step2](https://cloud.githubusercontent.com/assets/26319882/26776466/d80c1dba-4a0b-11e7-9120-8347069585a3.png)
![step3](https://cloud.githubusercontent.com/assets/26319882/26776471/daa9c702-4a0b-11e7-9fbc-0dd251fadfe7.png)

**Comment by starmarker** [comment]
我也遇到过这个问题，暂时不知道原因。Steps里面的Step会先检测里面的数量。因为我的Step是v-for出来的，然后会处理成只有一个，之后再循环。就会出现一个问题，每个Step都独占了一行。楼主这里出现的情况，我猜测应该是，首先检测出了三个Step，然后每个Step是按照1/3的长度在进行循环！
——————————————————————
这个问题不知道在什么情况下会出现。我自己写的测试demo的时候，是完全没有问题的。而我在Modal中使用，就出现了这个问题。

**Comment by starmarker** [comment]
早上发现这个问题，直到现在解决了这个问题，还是发上来说一下解决的办法。
失败的尝试就不说了。直接说正确的解决思路吧
因为我是在modal弹窗中使用这个步骤条组件的。它不能实现动态赋值，比如里面只有一个step在循环的时候，组件先一步取steps的数量，也就是还未循环的时候就取了steps的数量，造成step占据100%的宽度的问题。
但是在解决的过程中，我发现，我修改一下current，触发了热重载，然后居然就正常了……这是什么鬼情况？既然热重载能够更新，那我手动也能强制更新，然后我想到了$forceUpdate()方法。
在什么时候强制更新呢？我试了各个生命周期，除了beforeUpdate和updated整出俩死循环卡死之外，其他并没有什么卵用！
然后我想到了$nextTick();
再获取完所有步骤列表（用于循环，显示step）之后，开始this.$nextTick(()=>{
this.$refs.XXXX.current=2;//设置current的值
this.$forceUpdate();//强制更新DOM
});
然后，貌似就行了！

**Comment by Blackloser** [comment]
@starmarker 我也想到了  这是很久之前就提出了的  其实是一直希望官方给更新一下  这样自己写就不用那么麻烦了  现在model中的很多组件都需要$nextTick()去更新它的dom才能正常加载，用着很不舒服

**Comment by App1905** [comment]
try
```
this.$nextTick(()=>{
     this.$refs.XXX.updateChildProps()
})
```
