### ISSUE TITLE
表单控件size选项问题

### ISSUE THREAD

**Issue by tylerchen** [iview/iview#1091]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
MacOS

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

无

### 复现步骤
无

### 问题现象，以及你期望的结果是怎样的?
对于可以设置size选项的表单控件，size的值不能很好通过绑定来设置其大小，因为验证中只提供了['small', 'large']两个选项，也就是如果我通过绑定方式设置大小的话，我就不能设置默认大小。

### 你估计可能的原因是什么（选填）？
因为代码只提供两个选项，无默认大小选项：
            size: {
                validator (value) {
                    return oneOf(value, ['small', 'large']);
                }
            }

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/f00a037cd4613797f5853dc0bd840db9c6ec6301
