### ISSUE TITLE
建议官方文档添加上一节，下一节的链接

### ISSUE THREAD

**Issue by caiweiming** [iview/iview#1093]
官方文档写得很详细，这点很赞。只是体验上有一点点小瑕疵，就是每次读完文档要阅读下一篇时，都要滚动到顶部去选择章节，希望能在每个章节结尾处增加“下一节”的链接，方便阅读。

感谢iview带来的便捷。

**Comment by SergioCrisostomo** [comment]
@caiweiming thank you for you feedback! 

I will close this issue here. But if you feel there are improvements to the docs please use this other project page: https://github.com/iview/iview-doc
