### ISSUE TITLE
关于 Render 函数的兼容性问题

### ISSUE THREAD

**Issue by ckryo** [iview/iview#1094]
目前使用过程中发现 iview 调整后的render 函数存在某些问题；

在`table`组件的`expand`功能使用过程中，发现`expand`的中的组件`没有完整的生命周期，不能被正常销毁`;

在代码中发现，几乎还是原来render 的 `new Vue` 方式实现兼容。

希望间保持兼容过程中采用类型判断，使 iview 的 render 函数 支持完整的render功能与实现。

**虽然说这个问题并不能带来致命影响，但是对于render重度依赖的地方，就很棘手**

* 这种方式的 `render` 能够更有效的解决组件内的生命周期

![image](https://cloud.githubusercontent.com/assets/10364500/26813130/9ee76c62-4aae-11e7-81f6-8c79d6d3737c.png)
![616613be-82df-43a7-9dd5-75a1a2c529fb](https://cloud.githubusercontent.com/assets/10364500/26814735/5e5e0fe6-4aba-11e7-865a-d6aa54511fb5.png)

![image](https://cloud.githubusercontent.com/assets/10364500/26814110/8788fee4-4ab5-11e7-85ad-128e48b700a9.png)

* `iview`的方法不能完全支持 `table expand` 的 生命周期

![image](https://cloud.githubusercontent.com/assets/10364500/26813076/563e5d9a-4aae-11e7-8ebe-7ffa16e07e6d.png)

**Comment by icarusion** [comment]
contribution welcome

**Comment by gggllm** [comment]
意思是创建一个新的组件吗？

**Comment by icarusion** [comment]
https://github.com/iview/iview/pull/1111
