### ISSUE TITLE
日期选择器 confirm 模式不点确认一样会修改时间

### ISSUE THREAD

**Issue by moodmass** [iview/iview#1095]
日期选择器在 confirm 模式下不点确认按钮时间一样会回写到输入框中。那加确认按钮也没意义吧？element在这上面就有区分。
提一点建议，日期选择器在type为带range时，左边显示的是当前月的，右边显示的下一月的，这在售卖机票场景中比较适合，像查询历史记录使用场景中，更好的体验是左边是上月，右边是当月，建议加一个参数，用户可自行选择。

**Comment by lcx960324** [comment]
Bug report accepted. Thx.

关于建议我们会考虑的~

**Comment by lcx960324** [comment]
由于目前 `DatePicker` 的实现比较复杂，关于 `confirm` 的问题暂时难以解决。可以尝试使用我们提供的回调事件手动解决这个问题。
Sorry for that.
