### ISSUE TITLE
ssr 支持 (window is not defined)

### ISSUE THREAD

**Issue by lcsoftware** [iview/iview#1098]
今天看了一下咱们的官网，发现有更新，而且已经可以支持ssr， 请问要做哪些设置？因为我试了下还是不能直接使用的。

**Comment by lcx960324** [comment]
确实存在 `window is not defined` 的问题。

SSR 正在测试中，会在正式版发布前解决这些问题，敬请耐心等候更新，谢谢~

**Comment by lcsoftware** [comment]
谢谢，非常期待

**Comment by coffee8coding** [comment]
大大 能否大概估算下正式版发布的时间？
我们公司之前有个项目用vue1.0写的 ，一个月前我用iview升级到了2.0，但是最近公司又为了优化SEO想做成服务端渲染，尝试了几天，会出现：
1、iview设置在服务端渲染，会导致window undefined错误。
2、iview设置在客户端渲染，会导致客户端与服务端内容不一致的报错（这个可能是自定义标签的问题）
我实在不想放弃美妙的iview，万分期待iview的SSR，同时也非常期待iview解决SSR的思路。
所使用的SSR渲染框架是：nuxt

**Comment by andyhu** [comment]
非常期待支持SSR，不知道现在主要问题在哪里，如果有时间的话也可以考虑贡献PR，我主要用在nuxt.js里

**Comment by lcx960324** [comment]
目前正在对组件进行逐一测试，因为平时还有其他工作，进度比较慢。
等测试并完成Bugfix之后就能上线了~
正式版预计会完整支持SSR，敬请期待吧。

**Comment by andyhu** [comment]
好的，非常感谢，这个iView感觉做的很不错，我先测试下如果有问题也会及时发上来

**Comment by andyhu** [comment]
我现在简单的补丁了下，好像可以凑合用了，代码如下：
```js
if (typeof window === 'undefined' && typeof global === 'object') {
  global.window = {};
}
```
好像能用，能看下是不是有什么问题吗？

**Comment by lcsoftware** [comment]
我这边试过了，还是不行，还是同样的问题。





在 2017-06-15 16:25:47，"andyhu" <notifications@github.com> 写道：


我现在简单的补丁了下，好像可以凑合用了，代码如下：

if (typeofwindow==='undefined'&&typeofglobal==='object') {
  global.window= {};
}

好像能用，能看下是不是有什么问题吗？

**Comment by andyhu** [comment]
@lcsoftware 你加到哪里了？我是直接加到 `~/dist/iview.js` 里，测试可以和Nuxt.js搭配起来用

**Comment by lcsoftware** [comment]
我也是加在这个文件中的。请问是加在最后的位置吗？或者你告诉我要添加的行号，我再试试。

在 2017-06-15 18:19:59，"andyhu" <notifications@github.com> 写道：


@lcsoftware 你加到哪里了？我是直接加到 ~/dist/iview.js 里，测试可以和Nuxt.js搭配起来用

**Comment by andyhu** [comment]
我加到第一行了。另外想请教下<Breadcrumb>和其他的带<a>的标签没有直接渲染出SSR用的href标记，手动加@href报错，这个有办法解决吗？

**Comment by lcsoftware** [comment]
我刚才测试了一下。加到第一行。似乎可以用了。关于没有直接渲染出ssr用的href，我还没有测试。因为前面一直在用elementui，这几天也测试一下iview，看使用过程中有没有问题。非常感谢。

在 2017-06-16 10:04:48，"andyhu" <notifications@github.com> 写道：


我加到第一行了。另外想请教下和其他的带的标签没有直接渲染出SSR用的href标记，手动加@href报错，这个有办法解决吗？

**Comment by chenfengjw163** [comment]
还有组件中document的使用导致也无法用于ssr

**Comment by lcsoftware** [comment]
对的。我也遇到该问题

**Comment by hodgevk** [comment]
非常希望能尽早支持ssr，现在rc版还是不能正常服务器端渲染

**Comment by PierreRambaud** [comment]
Having the same problem, but don't understand what you said :)

**Comment by prestanesia** [comment]
I had same problem, but setting ssr to false in nuxt.config.js solve the problem (not sure thou since the docs said iview support ssr.): 

`plugins: [{ src: 'plugins/iview.js', ssr: false }],`

plugins\iview.js
`
import Vue from 'vue'
import iView from 'iview'
import locale from 'iview/src/locale/lang/en-US'

Vue.use(iView, { locale })
`

**Comment by icarusion** [comment]
#1339
