### ISSUE TITLE
有没有完整的项目demo

### ISSUE THREAD

**Issue by qxl1231** [iview/iview#11]
由于只有部分代码片段,不太好整合,最好是能给个完整的demo 参考

**Comment by qxl1231** [comment]
我已经把后端,包括vue,vuerify, babel 等 包括类似webpack类似的run,build脚本写好,只缺前端代码...
能否麻烦作者辛苦一下写1 个demo,如何集成你的代码片段 成为一个完整的demo样例

github地址:**https://github.com/qxl1231/iview_loopback**

**Comment by icarusion** [comment]
使用下面的工程，另外，认真阅读文档，里面介绍的很详细了
https://github.com/icarusion/vue-vueRouter-webpack

**Comment by qxl1231** [comment]
@icarusion 我要的不是跟webpack集成的..我要的是解耦的..比如vue官方文档里面,单独的文件可以使用的哈

**Comment by icarusion** [comment]
目前只支持.vue单位件模式
