### ISSUE TITLE
能不能提供个类似Bootstrap的Navbar？

### ISSUE THREAD

**Issue by iVanilla** [iview/iview#1100]
现在的导航是Menu，所有的菜单项都在左边，但有些组件，比如搜索框，登录/注册链接，用户头像等适合放在右边。
Bootstrap的Navbar组件就做得很好，但过于复杂，希望iView的Menu能支持把某些菜单项放到右边，或者另外搞个专门的Navbar组件。

**Comment by lcx960324** [comment]
自己搞也很简单的呀，只要在Menu 外层包裹 div 然后做一个悬浮靠右的块放想要的组件就行了。

**Comment by iVanilla** [comment]
@lcx960324 这样不优雅 (
另外能不能搞个Bootstarp的List? 类似
```
<div class="list-group">
    <div class="list-group-item"></div>
</div>
```
因为我不想用表格显示帖子列表等信息
