### ISSUE TITLE
导航菜单开启手风琴模式（accordion设置为true），on-open-change事件函数返回值错误

### ISSUE THREAD

**Issue by StanleyYechen** [iview/iview#1102]
导航菜单开启手风琴模式（accordion设置为true），触发on-open-change事件的函数返回值：当前展开的 Submenu 的 name 值数组里应该只有一个元素，这里并没有生效，还是和accordion设置为false时一样，会有多个元素

**Comment by lcx960324** [comment]
Bug report accepted. Thx.
