### ISSUE TITLE
为什么modal框的属性不设置一个height？只有一个width？

### ISSUE THREAD

**Issue by WebSF** [iview/iview#1104]
按照官网文档，modal的style属性值 传递object，
<Modal title="购买确认" v-model="modalsr" :mask-closable="false" :style="modalSrStyle" :closable="false" >
<tk-modal :tkData="tkData"></tk-modal>
	<div slot="footer">
<Button type="error" class="sureBtn" @click="sureBuy">确认购买</Button>
<Button type="error" class="returnBtn" @click="cancelBuy">取消</Button>
	</div>
</Modal>
data(){
			return{
				modalSrStyle: {
					width:700,
					height:410
				}
			}
		},	

style 我传递的是object 但是 并没有生效，这个object我应该怎么传？

**Comment by dean5277** [comment]
styles

**Comment by lcx960324** [comment]
抱歉，是文档写错了，应该使用 styles 属性。

**Comment by WebSF** [comment]
希望最好可以更新下官方文档，要不还会有人不知道这个错误的 ，==！

**Comment by icarusion** [comment]
https://github.com/iview/iview-doc/commit/e8c59cb690cd2be3947ee3d519edc247cd197f68
