### ISSUE TITLE
table render显示图片的问题

### ISSUE THREAD

**Issue by tangwei766** [iview/iview#1105]
"iview": "^2.0.0-rc.16",
"vue": "^2.2.6",

每当npm run dev启动后，第一次访问时图片都不显示，重新刷新页面之后才显示
{
              title: '轮播图片',
              key: 'imageUrl',
              className: 'table-column-img',
              render: (h, params) => {
                return h('img', {
                  attrs: {
                    class: 'default-img',
                    src: params.row.imageUrl == '' ? 'default-head-photo.jpg' : params.row.imageUrl
                  }
                })
              }
            },

**Comment by icarusion** [comment]
按要求提问
