### ISSUE TITLE
Select dropdown clipped when inside a Collapse and Form

### ISSUE THREAD

**Issue by ozeebee** [iview/iview#1108]
### iView 版本号

2.0.0.rc16
### 操作系统/浏览器 版本号

macOS/Chrome 58
### Vue 版本号

2.3.3
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/gRaYYV

### 你估计可能的原因是什么（选填）？

The content of the Select dropdown is clipped (cannot be seen outside the Collapse panel) as show below:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1236583/26882327-5449bc68-4b9a-11e7-856f-2d13f59f161f.png">

Code:
```
    <div>
      <Alert show-icon banner type="warning">
        Select dropdown in Collapse/Form/FormItem problem
      </Alert>
      <Collapse>
        <Panel name="some-panel">
          My Panel
          <div slot="content">
            <Form>
              <Form-item label="Select">
                <Select>
                  <Option v-for="item in 10" :key="item" :value="item">Item #{{ item }}</Option>
                </Select>
              </Form-item>
            </Form>
          </div>
        </Panel>
      </Collapse>
    </div>
```

**Comment by ozeebee** [comment]
My current work-around is to add a class to the Panel and force the `.ivu-collapse-content` to overflow (which is hidden by default):
```
/* allow select dropdown to be visible outside the Collapse panel */
.panel-with-dropdown .ivu-collapse-content {
  overflow: visible;
}
```

**Comment by lcx960324** [comment]
Personally I think it's a reasonable design for we cannot change Collapse's style to fit dropdown list only. In most case, we need to hide overflow contents. So I think it's fine to overwrite CSS for such case.

**Comment by ozeebee** [comment]
Ok, I can understand this is an edge case and I don't see how you could technically allow an exception for the dropdown without changing the whole Collapse component (and breaking other stuff).
Now, for the record, this issue can help other people find a solution to this problem. I guess I won't be the only one to be using a dropdown/select in a Collapse component.

**Comment by lcx960324** [comment]
Thank you a lot for your understanding. XD
