### ISSUE TITLE
非 template/render 模式下 i-table render 函数内的组件的this指向问题

### ISSUE THREAD

**Issue by archx** [iview/iview#1109]
非 template/render 模式下 i-table
`render: function (h, params) {
                        return h('div', [
                            h('Button', {
                                props: {
                                    type: 'primary',
                                    size: 'small'
                                },
                                style: {
                                    marginRight: '5px'
                                },
                                on: {
                                    click: function () {
                                        this.show(params.index)
                                    }
                                }
                            }, '查看'),
                            h('Button', {
                                props: {
                                    type: 'error',
                                    size: 'small'
                                },
                                on: {
                                    click: function () {
                                        this.remove(params.index)
                                    }
                                }
                            }, '删除')
                        ]);
                    }`

其中的render里按钮单击事件中的 this 指向了window,  如何才能指向vue实例呢？

**Comment by llccing** [comment]
[problem and resolve](https://jsfiddle.net/lcf33123/t5r1dm87/3/)

**Comment by archx** [comment]
@llccing thks
