### ISSUE TITLE
【问题】关于分页组件的提问

### ISSUE THREAD

**Issue by gongph** [iview/iview#1110]
Hi， @LekisS @yinheli @willnewii @stenote @Baoyx007  
目前的分页组件 `<Page>` 有上下分页功能吗？ 即，如果我在表格组件上下都设置一个 分页组件，点击其中一个分页组件的页码，另一个是否能监听并同步页码？

---
:cn: 在线等~

**Comment by stenote** [comment]
https://www.iviewui.com/components/page

`on-change`  的时候，可以考虑触发

**Comment by Baoyx007** [comment]
对啊，两个组件用同一个数据源就可以了

**Comment by yinheli** [comment]
@gongph 对啊，共用分页的数据即可，写了一个例子供参考：
https://jsfiddle.net/yinheli/dchs07o6/2/

**Comment by gongph** [comment]
已解决，感谢各位提供思路！
