### ISSUE TITLE
select无法转换选中的html字符实体

### ISSUE THREAD

**Issue by zwzw911** [iview/iview#1112]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
win7/firefox53.0.3

### Vue 版本号
2.2.2

select的option中，lable如果是html字符实体（例如$gt;），option中能正常显示为>，但是选中后，在select中，显示的还是字符实体$gt;
![untitled](https://user-images.githubusercontent.com/12762470/26908666-a23b62ca-4c2e-11e7-9cbc-18c32a92b206.png)

**Comment by lcx960324** [comment]
Bug report accepted. Thx.
