### ISSUE TITLE
IE9 下 Input 按下删除键后无法删除，value 还在

### ISSUE THREAD

**Issue by cobish** [iview/iview#1115]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
Win7 / IE9

### Vue 版本号
2.1.10

### 能够复现问题的在线示例
https://jsfiddle.net/cobish/xdgghvyz/

### 复现步骤
在 Form表单中的输入框输入值，然后按下键盘的 **Backspace** 或 **Delete**，输入框 blur 后值依然还在。

![tim 20170608101317](https://user-images.githubusercontent.com/8475099/26909454-8a0d2648-4c33-11e7-8989-fa88fa676a52.png)

![tim 20170608101325](https://user-images.githubusercontent.com/8475099/26909456-8c73af38-4c33-11e7-91a5-36a0082079d2.png)

### 问题现象，以及你期望的结果是怎样的?

IE9 在按下 **Backspace** 或 **Delete** 时 value 应该会变化

### 你估计可能的原因是什么（选填）？

IE9 删除时无法触发 Input 组件的 **@input**

**Comment by icarusion** [comment]
请提供在线示例

**Comment by cobish** [comment]
@icarusion 好的

**Comment by cobish** [comment]
@icarusion 已添加在线示例，但是我不知道怎么模拟 IE9

**Comment by move132** [comment]
我也碰到一样的问题了， 请问楼主解决了吗？

**Comment by cobish** [comment]
@move132 目前的项目没有用到 iView，不好意思哈。当初是研究它的源码过来的，目前公司项目的组件库已经解决这个问题，毕竟要兼容 IE9

**Comment by icarusion** [comment]
未来将不支持 IE9
