### ISSUE TITLE
table怎么设置默认排序呢？

### ISSUE THREAD

**Issue by xiaobanglong** [iview/iview#1121]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
Chrome 56

### Vue 版本号
 2.2.1

问题：
table怎么设置默认的排序，比如加载的时候就按指定列按指定顺序排序，然后再渲染表格

**Comment by lcx960324** [comment]
可以把数据放到 computed 里，然后用JS进行排序。

**Comment by xiaobanglong** [comment]
多谢兄弟的回复，这是一种很好的做法，我将采用。不过我期待的是作为表格这样一个组件的完整性，如果给出直接能够指定默认排序的功能，将是对表格能力的一个令人惊喜且非常实用的完善。

**Comment by melon** [comment]
用JS排序是可以的，但是似乎没有提供api来手动设置排序标识（上下箭头）的高亮状态。业务上如果有需求高亮默认排序标识，因为缺少api，通过hack的方式去实现还是挺繁琐的
