### ISSUE TITLE
Form怎么设置action等属性？

### ISSUE THREAD

**Issue by iVanilla** [iview/iview#1124]
文档没提到这个，难道你们的Form不需要把数据提交到后端？？？
还是说这个部分是由Vue来写的？

**Comment by zwzw911** [comment]
通过action提交表单是html原生from的功能（古老的功能）。
iview的From的主要功能是收集并验证数据，提交数据是通过axios(vue2.0)完成。

**Comment by iVanilla** [comment]
@zwzw911 这是一个Ajax请求吗？
或者我在Form中写明action是否有效？

**Comment by zwzw911** [comment]
axios是一个封装了post/get等请求的模块。是vue作者推荐的，适用于vue2.0。  
你说的action是html原生form的一个属性，用于将form中包含的表单信息传送到action指定的地址，这是很早以前提交表单的方式。  
iView的Form不提供这个属性，如果要发送Ajax请求，使用axios。

**Comment by iVanilla** [comment]
@zwzw911 也就是说post提交数据的URL是自己用axios写代码来指定的？

**Comment by zwzw911** [comment]
是的，参见https://github.com/mzabriskie/axios

**Comment by iVanilla** [comment]
@zwzw911 也就是说也可以通过其他JavaScript框架来提交？(这就跟iView无关了)

因为我用的Laravel框架“钦定”了Vue，但我偏向使用更轻量级的mithril框架。
