### ISSUE TITLE
table组建的rander函数 使用this不起作用

### ISSUE THREAD

**Issue by wangy09** [iview/iview#1125]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
Chrome 56 

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
html如下
` <Card style="width:100%">
        <p slot="title">我的文章</p>
        <Row type="flex" justify="space-around" class="code-row-bg">
          <Col span="7">
          <Card>
            <p slot="title">
              <Icon type="heart"></Icon> 受欢迎文章</p>
            <Table height="235" :columns="columns2" :data="commentData"></Table>
          </Card>
          </Col>
        </Row>
      </Card>`

rander 如下：
` render: (h, params) => {
        return h('div', [
            h('Button', {
                props: {
                    type: 'text',
                    size: 'small'
                },
                on: {
                    click: () => {
                        this.LookArtic(params.index)
                    }
                }
            }, params.row.name),
        ]);
    }`

### 复现步骤
点击的时候报错
       `Uncaught TypeError: _this.LookArtic is not a function
    at click (index.vue:259)
    at VueComponent.invoker (vue.runtime.esm.js:1733)
    at VueComponent.Vue.$emit (vue.runtime.esm.js:2202)
    at VueComponent.handleClick (iview.js:7521)
    at boundFn (vue.runtime.esm.js:164)
    at HTMLButtonElement.invoker (vue.runtime.esm.js:1733)`
### 问题现象，以及你期望的结果是怎样的?
我用的是最新版本的iview,我看其他人提问说已经在 2.0.0-rc.13以后解决了这个问题，是不是我的用法不对？需要注意哪些地方？

**Comment by wangy09** [comment]
问题很奇怪，`this.default.methods.LookArtic(params.index)` 就可以成功调用到方法

**Comment by lavenkin** [comment]
上下文问题，在Table组件中添加context属性 `:context=self` 在data中设置`self=this`

**Comment by areyouse7en** [comment]
这问题解决了吗？我还是获取不到this啊，照着文档写的，this是null啊

**Comment by xinlong0918** [comment]
this指向不对
