### ISSUE TITLE
multiple select在Firefox线样式出错

### ISSUE THREAD

**Issue by flute** [iview/iview#1127]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
macOS/Firefox 53.0.3

### Vue 版本号
2.3.3

### 复现问题
https://www.iviewui.com/components/select
Firefox下样式问题
![default](https://user-images.githubusercontent.com/5842406/26958274-4707beb6-4cfc-11e7-9c26-bb3b60b72763.png)

### 问题现象，及期望结果
multiple 多选模式下，选中后显示的对号跟现象不垂直居中，应该是垂直居中。

### 可能的原因
兼容问题。修复方法：
```
.ivu-select-multiple .ivu-select-item-selected{
	display: flex;
	display: -ms-flexbox;
	justify-content: space-between;
	-ms-justify-content: space-between;
	align-content: center;
	-ms-align-content: center;
	line-height: 24px;
}
```

**Comment by SergioCrisostomo** [comment]
fixed in #1262
