### ISSUE TITLE
DatePicker 日期插件disabled状态下还能点开

### ISSUE THREAD

**Issue by lavenkin** [iview/iview#1128]
### iView 版本号
2.0.0-rc.14

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 复现步骤
时间选择器disabled状态还是可以点开，要点最右边那个icon
### 问题现象，以及你期望的结果是怎样的?
点开后，导致可以修改时间，希望disabled状态不能有任何交互

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/f1f0206c70d1a16ee4f7abdd786162cc10bec454
