### ISSUE TITLE
form-item：使用默认的async-validator进行数值验证，总是报错

### ISSUE THREAD

**Issue by zwzw911** [iview/iview#1129]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
win7/firefox53.0.3

### Vue 版本号
2.2.2

### 问题现象，以及你期望的结果是怎样的?
使用form-item提供的默认async-validator进行验证时：    

如果input对应的rule设置为 :rules='[{"type":**"float"**,"min":0,"message":"报销金额的值不能小于0","trigger":"blur"}]，则此input无论输入什么值（或者不输入值），都会报错。 
 
如果input对应的rule设置为 :rules='[{"type":**"text"**,"min":0,"message":"报销金额的值不能小于0","trigger":"blur"}]，则input会根据输入的内容正常的验证。  

html如下：  
`                  <Form class="" :model="getQueryFieldInputValue" >
                         <Form-item  prop="amount"  :rules='[{"type":"float","min":0,"message":"报销金额的值不能小于0","trigger":"blur"}]'>
                        <Input  placeholder="输入查询值" type="text" v-model="getQueryFieldInputValue['amount']"  ></Input>
                      </Form-item>
                  </Form>`

### 你估计可能的原因是什么（选填）？
看了下async-validator的/src/rule/type.js， type为float时，代码如下，怀疑iview将input的值传给async-validator时，是以字符串的格式传递的，导致async-validator验证type时，总是返回false，导致验证失败。  
但是将input的tpye从text改成number，vue会报错：[Vue warn]: Invalid prop: custom validator check failed for prop "type". 
(found in <Input>)  

`float(value) {
    return types.number(value) && !types.integer(value);
},
number(value) {
    if (isNaN(value)) {
      return false;
    }
    return typeof (value) === 'number';
},`

**Comment by starmarker** [comment]
此前的版本就有这个问题，我也遇到了……真是一个悲伤的故事。只要设置必填，数值，下拉之类的就无法通过验证。字符串则没有问题！正在找解决的办法

**Comment by starmarker** [comment]
我知道你的这个的问题了，应该是如果是数字，需要给Input组件加上number属性。我这边用的给整个表单设置验证规则模式，需要把type和required写在一个对象中！

**Comment by zwzw911** [comment]
@starmarker: 条件限制，rules必须要设置在Form-item上。  
Input的type设置成number后，在firebug的console中，会报如下错误
`[Vue warn]: Invalid prop: custom validator check failed for prop "type". 
(found in <Input>)`  
同时，rules中，type和require写在一个object，还是会报错：  
`<Form-item  prop="amount"  :rules='{"type":"float","required":false,"message":"报销金额不能为空","trigger":"blur"}'> `
上例中，required设为false，当input不输任何值，blur发生的时候，还是会显示错误信息。

**Comment by liuxian1990** [comment]
我也遇到同样的问题.  只有开发环境才打印出来
![image](https://user-images.githubusercontent.com/4145946/32100747-9c8ecd9c-bada-11e7-8323-8f358ccca696.png)

例子:[https://codepen.io/liuxian2014/pen/MOgPmN](url)
