### ISSUE TITLE
import { 组建名} from “iview/src/index.js” 并不能真正的实现按需加载

### ISSUE THREAD

**Issue by taoeer** [iview/iview#113]
[https://www.iviewui.com/docs/guide/start#按需引用](url)
```javascript
import { Page, Slider, Cascader } from 'iview/src/index.js'
```
并不能真正的实现按需加载，因为当前import是babel模拟实现的，不是真正的es6import
要想真的做到按需加载，如下
```javascript
import Checkbox from 'iview/src/components/checkbox/checkbox';
```

**Comment by jingsam** [comment]
你的说法是对的

**Comment by icarusion** [comment]
对的，我更新下文档

**Comment by sally2015** [comment]
@icarusion 现在的文档也还是
![image](https://user-images.githubusercontent.com/14807468/38918631-e15a420c-4320-11e8-8888-851b7576789d.png)
就是说还是减少不了体积吗

**Comment by taoeer** [comment]
注意看文档，有个前提条件 ``借助插件 babel-plugin-import可以实现按需加载组件``
