### ISSUE TITLE
Dropdown @click="dropdownHandler" 事件不触发

### ISSUE THREAD

**Issue by ShiYun1985** [iview/iview#1131]
### 复现步骤
<Dropdown  @click="dropdownHandler" class="user-info">
                            <img src="../images/access-user.png" height="24" width="24">
                            <a href="javascript:void(0)">
                                {{userName}}
                                <Icon type="arrow-down-b"></Icon>
                            </a>
                            <Dropdown-menu slot="list">
                                <Dropdown-item name="modifypass">修改密码</Dropdown-item>
                                <Dropdown-item name="logout" divided>退出登录</Dropdown-item>
                            </Dropdown-menu>
                        </Dropdown>
### 问题现象，以及你期望的结果是怎样的?
我希望能够触发dropdownHandler

**Comment by guigui730** [comment]
使用 @on-click
