### ISSUE TITLE
Affix放到Modal中无效

### ISSUE THREAD

**Issue by gefangshuai** [iview/iview#1132]
### 复现步骤
Affix放到Modal中无效
### 问题现象，以及你期望的结果是怎样的?
Affix放到Modal中无效
### 你估计可能的原因是什么（选填）？
Affix放到Modal中生效

**Comment by wildviolin** [comment]
Affix 在 普通视图中确实没问题，在Modal中试了很多方法论都无法生效，不知是设计如此，还是issue，楼主有解决方案么，在线等。

**Comment by itpretty** [comment]
很多控件放到 Modal 中也会表现异常，比如表单验证在 Modal 中触发，Select 控件会始终验证不通过。

**Comment by gefangshuai** [comment]
有法解决吗

**Comment by icarusion** [comment]
暂时无法支持。
