### ISSUE TITLE
Input-number 的max没有实时生效

### ISSUE THREAD

**Issue by yhuaqiang** [iview/iview#1134]
当给:max设置一个变量时, 如果这个变量的值变化了, 组件的max没有及时生效.
主要是因为this.upDisabled 只有在changedVal之后才会判断. 并没有对max的实时变化进行判断
`changeVal (val) {
                if (isValueNumber(val) || val === 0) {
                    val = Number(val);
                    const step = this.step;

                    this.upDisabled = val + step > this.max;
                    this.downDisabled = val - step < this.min;
                } else {
                    this.upDisabled = true;
                    this.downDisabled = true;
                }
            }`

**Comment by fruitSandwich** [comment]
也需要这个特性
