### ISSUE TITLE
当表格进行前台分页时，排序和筛选只能针对当前页，并不是针对所有数据

### ISSUE THREAD

**Issue by xiaobanglong** [iview/iview#1135]
### iView 版本
2.0.0-rc.16

### 操作系统/浏览器 版本号
Chrome 56

### Vue 版本号
 2.2.1

### 能够复现问题的在线示例
当表格进行前台分页时，排序和筛选只能针对当前页，并不是针对所有数据
建议针对所有数据，可用性要强一些。

**Comment by lavenkin** [comment]
要实现所有数据排序必须有后台服务才可以的
