### ISSUE TITLE
可以提供Axure Components或psd等设计资源为方便设计师产出原型

### ISSUE THREAD

**Issue by karllo** [iview/iview#1148]
iview的ui效果个人觉得真的甩过Element，但Element提供了几个资源更方便设计师与开发者的沟通
![image](https://user-images.githubusercontent.com/9446682/27065137-2b46e244-502e-11e7-8533-b938139f3d67.png)

**Comment by DuLerWeil** [comment]
可以去找ant desgin。原型没必要太一致，像回事就够了

**Comment by zkcode** [comment]
that is a good idea

**Comment by icarusion** [comment]
#304
