### ISSUE TITLE
datepicker组件的弹窗子组件select-dropdown的样式生成定位不应该使用position: absolute

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1152]
![qq 20170613165213](https://user-images.githubusercontent.com/16515026/27074349-64b990fa-5059-11e7-9b88-70aff7b24e44.png)
datepicker组件的弹窗子组件select-dropdown的样式生成定位不应该使用position: absolute,因为被遮挡,或者添加一个属性设置position,根据position展示位置,建议用fixed

**Comment by jackzhcai** [comment]
遇到同样的问题

**Comment by yangdan8** [comment]
/**
             * 日期组件下拉或者收起后执行
             * @param isOpen 下拉为true,收起为false
             */
            changeTimeListOpen(isOpen: boolean) {
                if (!isOpen) {
                    return;
                }
                //修改日期组件的位置
                setTimeout(() => {
                    const $dropdown = $('.ivu-date-picker>.ivu-select-dropdown:eq(0)');
                    $dropdown.css({
                        position: 'fixed',
                        top: $dropdown.offset().top - 109,
                        left: $dropdown.offset().left - 181
                    });
                }, 0);
            },

**Comment by yangdan8** [comment]
#1567
