### ISSUE TITLE
下拉菜单的菜单项on-click事件不能触发

### ISSUE THREAD

**Issue by kengqiangxia** [iview/iview#1153]
Dropdown 下拉菜单的菜单项，使用官网所说的on-click事件，并不能触发，是bug么，还是需要注意什么问题么？

`<Dropdown-item on-click="function">……</Dropdown-item>`

换用@click也不能触发。

**Comment by JD-Wang** [comment]
Dropdown events

**Comment by YJZ-S** [comment]
请问iview中的Dropdown events怎么获取Dropdown-item 的 name 值？@on-click='doMore()';
点击事件可以触发，但不知道怎么获取name值

**Comment by umeitime** [comment]
> 请问iview中的Dropdown events怎么获取Dropdown-item 的 name 值？@on-click='doMore()';
> 点击事件可以触发，但不知道怎么获取name值

这个解决了 吗？
