### ISSUE TITLE
form组件的label-width,自定义单位

### ISSUE THREAD

**Issue by Teddy-Zhu** [iview/iview#1158]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.6

### 问题现象，以及你期望的结果是怎样的?
form组件的label-width, 目前只支持px,能否允许自定义rem,em等其他单位.
看源码里面写死了px,入参number.希望可以支持自定义

**Comment by Teddy-Zhu** [comment]
在忙也回复一下吧,为什么直接关闭了?

**Comment by ishidai** [comment]
label-width就是个笑话

**Comment by okool** [comment]
很多组件不支持自定义单位,比如:百分比,vh,rem
个人项目用iview,幸好公司项目用react,可以任意设置组件.
