### ISSUE TITLE
tree组件，半选状态展示有问题

### ISSUE THREAD

**Issue by xcodebin** [iview/iview#1159]
### iView 版本号
2.0

### 操作系统/浏览器 版本号
win64

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/xcodebin/pen/WOGwBe

### 复现步骤

点击清空按钮

### 问题现象，以及你期望的结果是怎样的?

tree组件，通过ajax获取的原始数据中有一部分被选中（不是全选）；这时候我将根节点底下的所有节点通过js操作数据，将checked全部改成false，这时根节点还处于半选中状态，这不对。

### 你估计可能的原因是什么（选填）？

未监听数据改变。另外希望暴露半选状态api

**Comment by 68zch** [comment]
tree组件有时候点击没有响应不知道你有没有遇到过

**Comment by icarusion** [comment]
直接修改 `data`
