### ISSUE TITLE
table 组件 sortable: true 开启后， 数据较多的情况下 反复 排序 报错

### ISSUE THREAD

**Issue by tkaven** [iview/iview#1164]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
win/Chrome 58.0.3029.81

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
![image](https://user-images.githubusercontent.com/4628730/27034772-8cbd720e-4fb1-11e7-921c-fd1f8ee80636.png)

### 复现步骤
多次点击 排序

### 问题现象，以及你期望的结果是怎样的?
 [Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.

**Comment by 68zch** [comment]
我也遇到这个问题了，不知道怎么处理，有的报错有的不报错，有的点几次排序按钮才会报错，报错之后页面点击就没有响应了，必须刷新

**Comment by 68zch** [comment]
这里有示例：https://jsfiddle.net/zhoou/5duojpu6/

**Comment by itpretty** [comment]
这个问题也遇到过，原因是：左边有冻住的列。通常把 fixed: left 那列解冻就好了。如果还不好，就再去掉有筛选的那列的筛选属性。这样只是暂时避开这个问题，最终还是要等官方修复。

**Comment by 68zch** [comment]
@itpretty  确实是有冻住的列，多谢提醒

**Comment by 68zch** [comment]
@itpretty 确实是有冻住的列，多谢提醒
另外你有没有遇到过tree树形控件点击没有反应的情况？

**Comment by itpretty** [comment]
@68zch 项目要求对 tree 的操作比较复杂，最终还是选用了 ztree

**Comment by likeaijiaqi** [comment]
临时解决办法：排序中会出现 asc , desc，normal 这个三个字段；多次排序是出现normal，可以记录上一次排序的order,然后判断是否是normal，如果是则把上一次的值复制给本次查询。还是希望官方能尽快解决

**Comment by itpretty** [comment]
从报错信息上看，症结还是在 duplicate keys 上。冻住列的实现思路是“复制列，隐藏原列”，DOM 中存在完全相同的两个列，不知是不是这里引起的问题？因为取消 fixed 列，就不会有这个问题。

**Comment by chewel611** [comment]
我没有做冻结列也是不行的，请教下那个sortMethod方法怎么用

**Comment by icarusion** [comment]
Update to the latest version.If there is any problem, please open another issue
