### ISSUE TITLE
希望table里的render能改变button的属性

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#1165]
### iView 版本号
 2.0.0-rc.17 

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
 2.2.1/2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/mwrRqZ

### 复现步骤
点击按钮

**Comment by rijn** [comment]
What issue did you face when using render? Or what update you want?

**Comment by icarusion** [comment]
The description is not clear, so I close this issue.
