### ISSUE TITLE
和nuxt一起使用问题

### ISSUE THREAD

**Issue by heiyeliuying** [iview/iview#1166]
我在使用 iview+nuxt 的开发过程中,一切都非常的顺利.
但是当我想把代码部署到服务器时,却出现了问题. 我通过 nuxt generate 命令将代码生成了静态文件,然后将静态文件放到服务器下时,发现页面能够正常打开,但是里面的很多样式都乱掉了.请问,这和针对 iview 的使用有关系吗?

之前做过 vue2 cli 形式的代码,通过 npm build 之后,将 dist 文件夹放到服务器下,是没有任何问题的.

**Comment by icarusion** [comment]
#1098
