### ISSUE TITLE
Select 选择器组件带有remote属性时无法默认选中

### ISSUE THREAD

**Issue by 68zch** [iview/iview#1169]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
window7/firefox45

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://jsfiddle.net/zhoou/07LdL6p3/

### 问题现象，以及你期望的结果是怎样的?
我希望的结果是示例中上面那种展示效果，这样我可以根据选择的ID默认显示名称而不是出现一串ID

**Comment by icarusion** [comment]
看 Select API 的 label

**Comment by 68zch** [comment]
能说的详细点吗？我加了label还是没有出现名称
`<i-select remote multiple v-model="selectedIds" style='margin-bottom:20px;'>
        <i-option v-for="option in list" :value="option.id" :key="option.id" :label='option.label'></i-otion>
    </i-select>`

`var app=new Vue({
	el:'#app',
	data:{
		list:[
			{name:'语文',id:'201701011046',label:'语文'},
			{name:'数学',id:'201701011145',label:'数学'},
			{name:'英语',id:'201701061244',label:'英语'},
			{name:'几何',id:'201701041343',label:'几何'},
			{name:'政治',id:'201701031442',label:'政治'},
			{name:'化学',id:'201701011541',label:'化学'}
		],
		selectedIds:['201701011145']
	}
});`

**Comment by chenyo2691** [comment]
@68zch 初始化list为label,value的键值对就行了。
                   this.list=this.list.map(item => {
                        return {
                            value: item.id,
                            label: item.name
                        };
                    });

**Comment by BoleLee** [comment]
```
<Select 
      v-model="id"
        :label="name"
        filterable
        remote
       :remote-method="search"
       :loading="loading"
      placeholder="请输XX名字进行搜索">
    <Option v-for="item in list" :value="item.id" :key="item.id" :label="item.name>{{ item.name }}</Option>
</Select>
```
以上配置，已设置select的label 为Option的label值，测试发现初始搜索请求一直使用的是select 的 value进行搜索，导致搜索得出的list为空

**Comment by BoleLee** [comment]
#3897

**Comment by laienliang** [comment]
怎么解决的？

**Comment by ahuang** [comment]
同遇到这个问题
iview v2版本
多选+远程搜索
默认值无法显示

https://jsfiddle.net/zhoou/07LdL6p3/
![1](https://user-images.githubusercontent.com/730550/67657349-6e713d80-f991-11e9-8839-6d98c27bd751.png)

找的解决办法是：使用$nextTick
![2](https://user-images.githubusercontent.com/730550/67657266-379b2780-f991-11e9-8d7c-3e224d52e152.png)
