### ISSUE TITLE
table 组件 多次点击排序功能报错

### ISSUE THREAD

**Issue by 68zch** [iview/iview#1170]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
window7/firefox45

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/zhoou/5duojpu6/

### 复现步骤
多次点击 合计、排名、班级折算、班级等表头上的排序功能就会报错，错误内容为：
[Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key. 
console.error("[Vue warn]: " + msg + " " + (
vue.js (第 569 行)
TypeError: vnode1 is undefined
vnode1.key === vnode2.key &&

**Comment by icarusion** [comment]
Vue 版本升级试试
