### ISSUE TITLE
导航菜单 open-names设置无效

### ISSUE THREAD

**Issue by StanleyYechen** [iview/iview#1177]
Menu导航菜单 设置open-names数组时 没有触发DOM变化（数组中的对应name的Submenu没有打开），这个问题是在开启手风琴模式下发现的（accordion = true）， 初始化的时候是没问题的，v-bind绑定到dataModel，改变dataModel的数组时不触发DOM

**Comment by zjjEcho** [comment]
同问。。。一样的问题。

**Comment by laichuangchong** [comment]
same problem
