### ISSUE TITLE
table样式能不能增加不换行的自适应，超过长度的自动隐藏显示省略号...

### ISSUE THREAD

**Issue by zhihuihu** [iview/iview#118]
table样式能不能增加不换行的自适应，超过长度的自动隐藏显示省略号...，

**Comment by icarusion** [comment]
fixed

**Comment by GITleonine1989** [comment]
看提交的代码是加了ellipsis属性，但是如果自动省略的话最好能补一个title，这样鼠标悬停的话可以查看全部的内容

**Comment by rijn** [comment]
使用table的render和Tooltip即可

**Comment by GITleonine1989** [comment]
恩，render 当然可以

**Comment by rijn** [comment]
[Source](https://github.com/iview/iview/blob/master/src/components/table/cell.vue#L7) 也可以用span自己加个title

**Comment by GITleonine1989** [comment]
请问 下个版本什么时候发，我准备用在项目上了

**Comment by icarusion** [comment]
明天

**Comment by GITleonine1989** [comment]
给力 666

**Comment by hanfengcan** [comment]
@rijn 可否给个例子，我在render加了tooltip后，效果不理想

```
      render: (h, params) => {
        return h('Tooltip', {
          props: {
            placement: 'top', content: params.row.record2_diagnose, transfer: true
          }
        }, params.row.record2_diagnose)
      }
```

**Comment by qints** [comment]
@icarusion 现在表格有拖动鼠标来调整列宽的功能吗？如果有这个功能，也可以不用titile显示内容

**Comment by leixu2txtek** [comment]
希望表格行内容可以配置增加 title 显示 不然设置了 ellipsis 标题不显示全，就很尴尬，不能每个都 写 render 吧
