### ISSUE TITLE
在table组件中，render了一列action,使用poptips提示时，会出现多个提示

### ISSUE THREAD

**Issue by meihuasannong** [iview/iview#1180]
_

### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
windows/Chrome 58 

### Vue 版本号
2.2.2 

### 问题现象，以及你期望的结果是怎样的?
在table组件中，render了一列action,当点击删除按钮，使用poptips组件的时候，会弹出多个
期望点击一个按钮的时候，另外的poptips会关闭。页面上只能出现一个poptips
代码部分：       
![Image of Yaktocat](http://139.196.201.140/20170615140739.png)

目前效果：
![Image of Yaktocat](http://139.196.201.140/1497506487(1).png)

**Comment by huangjuanjuan** [comment]
同问 怎么解决

**Comment by icarusion** [comment]
Use `transfer` prop.
