### ISSUE TITLE
select远程搜索的时候无法显示选中值

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1181]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Chrome版本 59.0.3071.86

### Vue 版本号
2.3.4

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/7tbewkrm/

### 问题现象，以及你期望的结果是怎样的?
控制器报类型错误，可是实际上是字符串类型
![image](https://user-images.githubusercontent.com/1802631/27172054-6b4db624-51e6-11e7-8357-fbfdc9ae26ec.png)

**Comment by icarusion** [comment]
用法不对。

**Comment by dean5277** [comment]
知道了，v-modal这里
