### ISSUE TITLE
Page 分页的页数选择，下拉方向可以设置吗？

### ISSUE THREAD

**Issue by shaode** [iview/iview#1185]
### iView 版本号

2.0.0-rc.17
### 操作系统/浏览器 版本号

window / ubunut
### Vue 版本号

2.2.6
### 复现步骤
1.页面的overflow：hidden； 
2.page 分页在最下面，选择每页行数时，下拉列表在下面被挡住，无法选择
### 问题现象，以及你期望的结果是怎样的?
希望可以设置下拉列表方向，或者自动检测，提供对应的方向最好
### 你估计可能的原因是什么（选填）？
下拉列表的方向固定，页面不滚动导致覆盖了

**Comment by itpretty** [comment]
仔细阅读文档，有这个配置选项。

**Comment by shaode** [comment]
@itpretty 多谢多谢，自以为确认文档里没有才来问，是自己不细心，对不住了
