### ISSUE TITLE
自定义主题一直编译报错，要崩溃了

### ISSUE THREAD

**Issue by shaode** [iview/iview#1186]
### iView 版本号

2.0.0-rc.17
### 操作系统/浏览器 版本号

window
### Vue 版本号

2.2.6
### 复现步骤
在src/theme/global/index.less中写：
 `@import '~iview/src/styles/index.less';
@primary-color: #8c0776;`

在main.js 中引入，然后编译就报错，要疯
error 信息：
 ERROR in ./~/autoprefixer-loader!./~/less-loader!./src/theme/global/index.less
 Module parse failed: C:\**\workspace\font-end\iviewtest\test2\node_modules\autoprefixer-loader\index.js!C:\***\workspace\font-end\iviewtest\test2\node_modules\less-loader\index.js!C:\***\workspace\font-end\iviewtest\test2\src\theme\global\index.less Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | .ivu-load-loop {
    |   -webkit-animation: ani-load-loop 1s linear infinite;
    |           animation: ani-load-loop 1s linear infinite;

而且我试过，用iview-theme-cli工具编译成css文件引入就可以用，但是引入css样式后，有些地方显示不正常，最终还是放弃，希望能用less的方式
### 问题现象，以及你期望的结果是怎样的?
希望能用less的方式

**Comment by freew01f** [comment]
我也是 不知道什么鬼~

**Comment by freew01f** [comment]
我是原生脚手架建立项目 然后加入iview 然后定制 一致就没成功
{
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          use: ['css-loader', 'autoprefixer-loader', 'less-loader'],
          fallback: 'style-loader'
        })
      },
也加入了 
就是不行

**Comment by dean5277** [comment]
我也是没成功过。

**Comment by chenhaizano** [comment]
是 2.0.0-rc.17 有这个问题么？我现在用的 2.0.0-rc.16 没这个问题。弄得都不敢升级

**Comment by shaode** [comment]
@chenhaizano 不知道和版本有没有关系，我之前从 2.0.0-rc.13 - 16 都有这个问题，现在用的是 2.0.0-rc.16版本，昨晚升17也不灵，我用的是iview提供的base project ，是不是官方提供的demo有问题

**Comment by freew01f** [comment]
哎 急死人

**Comment by shaode** [comment]
@freew01f 哎

**Comment by val00147** [comment]
参考：#900、我搞定了。

**Comment by shaode** [comment]
@val00147 Thanks, 搞定了. @freew01f 可以试下 #900

**Comment by shaode** [comment]
@icarusion 希望官方尽快更新demo，避免新手入坑，谢谢，辛苦啦，加油

**Comment by val00147** [comment]
辛苦啦，加油，加油
