### ISSUE TITLE
Modal => Tabs => Tab => Select，下拉菜单被遮挡

### ISSUE THREAD

**Issue by lvqingan** [iview/iview#1187]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
macOS/Chrome 61

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[https://codepen.io/anon/pen/eRBMZz](https://codepen.io/anon/pen/eRBMZz)

### 复现步骤
组件包含顺序: Modal => Tabs => Tab => Select

### 问题现象，以及你期望的结果是怎样的?
Select直接放Modal里没有问题，但是如果放在Modal的Tabs里下拉就会被遮挡，希望能够正常显示下拉菜单

**Comment by YYQ8023** [comment]
.ivu-dropdown-menu {
    position: absolute !important;
}
试试这个。

**Comment by lvqingan** [comment]
@YYQ8023 不行，你的解决方案是处理#818的错位问题的，而我的跟#844是同一个问题，下拉没有错位是被遮挡了

**Comment by itpretty** [comment]
加上 .ivu-modal-body .ivu-tabs{overflow:visible;} 就可以看到了，但下拉菜单似乎有错位。

**Comment by itpretty** [comment]
加上这两行
`.ivu-tabs .ivu-select-dropdown{top:auto;}
.ivu-tabs .ivu-tabs-tabpane{position:relative;}`
修复下拉菜单错位

**Comment by lvqingan** [comment]
@itpretty 只有一个tabpane时是有效的，但是如果有多个tabpane的话，所有的tabpane都显示出来了

**Comment by hellomrbigshot** [comment]
对，是有这个问题。楼主解决没

**Comment by lvqingan** [comment]
@hellomrbigshot 没有呢，目前暂时是给tab加了个高度，但是很丑

**Comment by hellomrbigshot** [comment]
@lvqingan 主要是点select组件点三下会出现，让人摸不着头脑。并且在chrome58、59的新版本上没有这个问题。

**Comment by lvqingan** [comment]
@hellomrbigshot 点三下？你说的跟我不像同一个问题，我的是下拉菜单显示不全，跟点多少下没关系

**Comment by ChaoLeer** [comment]
这个在里面放置时间选择器也会有问题，所以还是用了min-height暂时处理

**Comment by liufeics** [comment]
由于在tab中用了overflow这个属性，所以当超出当部分会被隐藏 如果 没有横向当切换的话overflow可以设置为visible但是有横向的切换的话 最好的办法只能是设置pading或者height了，不然会出现滚动条，暂时没找到更好的解决办法
