### ISSUE TITLE
model上面添加v-if报错

### ISSUE THREAD

**Issue by mayunlong** [iview/iview#1190]
![image](https://user-images.githubusercontent.com/10611797/27213390-12c9a086-5299-11e7-9703-d9e0ecdd2d8c.png)
![image](https://user-images.githubusercontent.com/10611797/27213431-5e6bcdb6-5299-11e7-8eea-052aebdea184.png)

value ！==false的判断的原因，value总是undefined造成的

**Comment by SergioCrisostomo** [comment]
@mayunlong can you provide a example of this problem please?

使用下面的在线链接可以快速创建示例
https://codepen.io/anon/pen/BWwVoy
