### ISSUE TITLE
checkbox,radio只支持boolean类型,建议支持1和非1来判断,已经给出示例希望能更新到新版本

### ISSUE THREAD

**Issue by BluecatWu** [iview/iview#1191]
### checkbox修改示例
 `

    name: 'Checkbox',

    mixins: [Emitter],

    props: {
        disabled: {
            type: Boolean,
            default: false
        },

        value: {
            type: [Number, Boolean],
            default: false
        },
        label: {
            type: [String, Number, Boolean]
        },
        indeterminate: {
            type: Boolean,
            default: false
        }
    },

    data() {
        return {
            model: [],
            currentValue: this.value,
            group: false,
            showSlot: true,
            parent: findComponentUpward(this, 'CheckboxGroup')
        };
    },

    computed: {
        wrapClasses() {
            return [
                `${prefixCls}-wrapper`,
                {
                    [`${prefixCls}-group-item`]: this.group,
                    [`${prefixCls}-wrapper-checked`]: this.currentValue,
                    [`${prefixCls}-wrapper-disabled`]: this.disabled
                }
            ];
        },

        checkboxClasses() {
            return [
                `${prefixCls}`,
                {
                    [`${prefixCls}-checked`]: this.currentValue,
                    [`${prefixCls}-disabled`]: this.disabled,
                    [`${prefixCls}-indeterminate`]: this.indeterminate
                }
            ];
        },

        innerClasses() {
            return `${prefixCls}-inner`;
        },

        inputClasses() {
            return `${prefixCls}-input`;
        }
    },

    mounted() {
        this.parent = findComponentUpward(this, 'CheckboxGroup');
        if (this.parent) this.group = true;
        if (!this.group) {
            this.updateModel();
            this.showSlot = this.$slots.default !== undefined;
        }
    },

    methods: {
        change(event) {
            if (this.disabled) {
                return false;
            }

            const checked = event.target.checked;
            this.currentValue = checked;
            if (typeof(this.value) === 'boolean') {
                this.$emit('input', checked);
            } else if (typeof(this.value) === 'number') {
                this.$emit('input', checked ? 1 : 2);
            } else {
                this.$emit('input', checked);
            }
            if (this.group) {
                this.$parent.change(this.model);
            } else {
                this.$emit('on-change', checked);
                this.dispatch('FormItem', 'on-form-change', checked);
            }
        },
        updateModel() {
            if (typeof(this.value) === 'boolean') {
                this.currentValue = this.value;
            } else if (typeof(this.value) === 'number') {
                this.currentValue = this.value === 1
            } else {
                this.currentValue = this.value;
            }
        }
    },
    watch: {
        value() {
            this.updateModel();
        }
    }`

**Comment by william807803** [comment]
支持1和非1来判断？ 你这个建议太不合理了吧？那有人需要支持0和非0怎么办？岂不要把iview的作者忙死 .

**Comment by BluecatWu** [comment]
element就有这个功能,
true-label,false-lable
checkbox和radio都有

**Comment by BluecatWu** [comment]
很多后台都是用1和非1来做判断,true跟false很容易造成bug

**Comment by WebSF** [comment]
老哥，感觉你这个需求iview官方不会给你改的，iview这么设计没毛病

**Comment by kurtcn** [comment]
很多业务系统的数据采用0、1作为状态位

**Comment by lenxeon** [comment]
很有必要的，强烈建议增加
