### ISSUE TITLE
有人成功在Tomcat上运行吗？

### ISSUE THREAD

**Issue by shaode** [iview/iview#1192]
### iView 版本号

2.0.0-rc.16
### 操作系统/浏览器 版本号

tomcat 
### 复现步骤
npm run build ==> 放在tomcat的webapp下，无法正常访问

**Comment by YYQ8023** [comment]
tomcat首页能进吗？会报什么错吗？就不能说具体点，按照要求提问题？

**Comment by lcx960324** [comment]
tomcat 上可以运行。
多半是你的 Webpack 配置的时候资源文件使用了绝对路径（vue-cli 默认是绝对路径），访问的时候网站不在一级目录下，导致路径文件404了。
