### ISSUE TITLE
page 分页（电梯类型），输入框的触发事件是按下回车

### ISSUE THREAD

**Issue by WebSF** [iview/iview#1193]
有没有事件能监听分页输入框的事件 或者 增加个确定按钮 触发输入框事件，现在只有按下回车键，才好使

**Comment by itpretty** [comment]
按下回车再跳转，基本是惯例的设计了。如果是keyup/keydown触发的话，当要跳到2位或2位以上数字的页码时，永远跳不过去。

**Comment by WebSF** [comment]
@itpretty 这个可以增加一个确定按钮来触发跳转事件吗？

**Comment by YikaJ** [comment]
#1209 这个自己在外部添加按钮就可以了。
