### ISSUE TITLE
Page 方向定为top，有错位

### ISSUE THREAD

**Issue by shaode** [iview/iview#1194]
### iView 版本号

2.0.0-rc.16
### 操作系统/浏览器 版本号

chrome 59
### Vue 版本号

2.2.3
### 复现步骤
Page 方向定为top，有错位如图：
![image](https://user-images.githubusercontent.com/4277051/27222131-b5f7ad9c-52bd-11e7-977d-28a19f98339e.png)
### 问题现象，以及你期望的结果是怎样的?
这个错位算是个bug吗？

**Comment by icarusion** [comment]
请按要求提问
