### ISSUE TITLE
展开Table的任意一行后，在行间移动鼠标，系统会大量重复调用expand列的render函数

### ISSUE THREAD

**Issue by lvqingan** [iview/iview#1195]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
macOS/Chrome 61

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[https://codepen.io/anon/pen/eRBxzX](https://codepen.io/anon/pen/eRBxzX)

### 复现步骤
1）打开Console控制台
2）点击任意一行展开
3）在表格间任意移动鼠标
4）观察控制台的输出

### 问题现象，以及你期望的结果是怎样的?
鼠标每经过一行（即使没有展开），都会触发render的调用

**Comment by icarusion** [comment]
测试确实有输出日志，但 render 的组件应该没有重复渲染。@ckryo 怎么看？

**Comment by ckryo** [comment]
最近比较忙。刚看到消息，我等下就看看。
