### ISSUE TITLE
select远程搜索,下拉框会出现错位

### ISSUE THREAD

**Issue by BluecatWu** [iview/iview#1196]
### Vue 版本号

￼

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 
<img width="786" alt="qq20170616-182425 2x" src="https://user-images.githubusercontent.com/19888913/27222991-28dbd0d8-52c1-11e7-8ece-3db86e62c785.png">

##
￼# 复现步骤

**Comment by BluecatWu** [comment]
刚更新的2.0.0-rc.17

**Comment by 41339** [comment]
请问你找到解决的方法了吗？

**Comment by 41339** [comment]
请问你找到解决的方法了吗？
