### ISSUE TITLE
多处变量名称与系统保留变量冲突

### ISSUE THREAD

**Issue by aaron0713** [iview/iview#120]
Menu 导航菜单：
vue.common.js?e881:509
[Vue warn]: "key" is a reserved attribute and cannot be used as component prop. 
(found in component <Submenu>)

iView初始化
Do not use built-in or reserved HTML elements as component id: Circle 
Do not use built-in or reserved HTML elements as component id: Switch

**Comment by javaMumu** [comment]
I also met the same problem...

**Comment by arronf2e** [comment]
是的，请问这个有解决吗。

**Comment by ejfrancis** [comment]
+1 this leads to linting errors
