### ISSUE TITLE
tabs组件animated=false并且tab初始化是隐藏状态再切换为显示时标题底部横条不显示

### ISSUE THREAD

**Issue by lifeforfun** [iview/iview#1200]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Win7 64bit/ Chrome 58.0.3029.81 (64-bit)

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[codepen](https://codepen.io/HugeWorld/pen/ZpJrvp)

### 复现步骤
页面初始化时tab组件是隐藏状态并且设置了**animated=false**来禁用动画，点击按钮来切换tab显示

### 问题现象，以及你期望的结果是怎样的?
期望的结果是active的标签标题下面应该显示滑条，但结果并没有显示，只能再切换其他标签才能显示

### 你估计可能的原因是什么（选填）？
mounted钩子里给滑条加入active状态即可

**Comment by mansonchor** [comment]
+1，我也遇到了，请尽快修复~~~

**Comment by icarusion** [comment]
Use `v-if`
