### ISSUE TITLE
iView 脚手架工具报错 the babel package has been deprecated in favor of babel-cli.

### ISSUE THREAD

**Issue by CGerAJ** [iview/iview#1201]
MacBook-Pro:iview user$ npm install
npm WARN deprecated babel@6.23.0: In 6.x, # **the babel package has been deprecated in favor of babel-cli.** Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Unexpected end of input at 1:219614
npm ERR! bel-core","version":"6.1.17","dependencies":{"babel-code-frame":"^6.1
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-06-17T13_41_56_136Z-debug.log
### 操作系统/浏览器 版本号
 macOS/Chrome 59 

### Vue 版本号
2.2.1 

### 问题现象，以及你期望的结果是怎样的?
请求修复官方ti提供的脚手架工具 现在我只能用vue-cli了
### 你估计可能的原因是什么（选填）？
babel - cli的支持已被弃用。

**Comment by icarusion** [comment]
请到iview-cli提问
