### ISSUE TITLE
上传图片到七牛时, 有时候出现错误

### ISSUE THREAD

**Issue by williambao** [iview/iview#1202]
### iView 版本号
2.0.0-rc.7

### 操作系统/浏览器 版本号
 macOS/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
在点击上传选择文件时, 有时候会出现错误. 如下图一样. 
点击错误定位到下图2位置. 时不时的出现, 
我前台页面, 未调用progress相关函数或功能.
<img width="936" alt="1" src="https://user-images.githubusercontent.com/779521/27253707-e2fdb464-53ab-11e7-803c-f8bc0d25c53a.png">
<img width="780" alt="2" src="https://user-images.githubusercontent.com/779521/27253818-423fcb9a-53ae-11e7-99f2-c8a274b1df46.png">

**Comment by williambao** [comment]
找到原因. 我在页面有用到<Spin />控件.
```
<Spin size="large" fix v-if="isLoading"></Spin>
```
其中的`isLoading`的值会在开始上传时设置为`true`. 当上传成功时改回`false`. 
这时就会出现我原先发的错误.

**Comment by shauvet** [comment]
求教楼主upload组件如何添加七牛的token的？谢谢
