### ISSUE TITLE
表格里如果用了fixed:left,且有一行不设置宽度的话，缩小，不设置宽度那列给覆盖

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1204]
### iView 版本号
rc17

### 操作系统/浏览器 版本号
59.0.3071.104（正式版本） （64 位）

### Vue 版本号
2.3.4

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/7tbewkrm/4/

### 复现步骤
产品的表头不见了，下面的列和买家的重叠了。

![image](https://user-images.githubusercontent.com/1802631/27267682-e364186c-54dc-11e7-875d-bc8bf15f4390.png)

### 问题现象，以及你期望的结果是怎样的?
希望如果不设置宽度，应该有个占位宽度。

**Comment by dean5277** [comment]
或者应该加上最小宽度的一个属性。

**Comment by likeaijiaqi** [comment]
对，同样出现这个问题

**Comment by icarusion** [comment]
Update to the latest version.If there is any problem, please open another issue.
