### ISSUE TITLE
table固定表头列之后右边的滚动条被遮挡

### ISSUE THREAD

**Issue by rongxingsun** [iview/iview#1206]
### iView 版本号

2.0.0-rc.17
### 操作系统/浏览器 版本号

windows 7/Chrome 56
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://jsfiddle.net/3feecwmp/
### 复现步骤
固定表头及右边的列，右边的滚动条被右边的固定列给遮挡了
### 问题现象，以及你期望的结果是怎样的?
固定表头及右边的列能看到竖向滚动条

**Comment by butong-dev** [comment]
iview 版本号 2.3.2， 操作系统 Windows 7/chrome 61,IE 11 下面出现该问题，操作系统 macOS Sierra/chrome 61, safari 10 均可以正常显示滚动条

**Comment by icarusion** [comment]
#3178

**Comment by AceHe** [comment]
我遇到同样的问题：当表格设置固定高度，有横向滚动条且没有竖向滚动条，那么固定列下方的横向滚动条就会被遮挡（能看见滚动条但鼠标移上去不能拖拽）。原因是此时的固定列【ivu-table-fixed-body】自动计算了一个默认高度遮挡住了滚动条。如果同时存在横向和竖向的滚动条则不会有此问题。
