### ISSUE TITLE
Modal 中 form 里的 select 验证异常

### ISSUE THREAD

**Issue by itpretty** [iview/iview#1207]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Win7/Chrome 50

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/itpretty/pen/MopaZK

### 复现步骤
1、打开 Modal
2、点击提交
3、选择一个城市，仍显示“请选择城市”

### 问题现象，以及你期望的结果是怎样的?
Modal 中 form 里的 select 验证正常

### 你估计可能的原因是什么（选填）？
估计验证下拉菜单时，混淆了“字串型数字”和“数字型数字”

**Comment by itpretty** [comment]
解决办法：凡是用于 i-option 的 value，如果是数字型，转成 string

**Comment by dytsun** [comment]
默认校验数据为string类型的，然而你这个select用的value是number类型的,修改如下
rules="[{type: 'number', required: true, message: '', trigger: 'change'}]"

**Comment by rijn** [comment]
@itpretty Could you please close this issue if it has been resolved. Thanks.
