### ISSUE TITLE
Page分页组件可以自定义增加一个跳转按钮？

### ISSUE THREAD

**Issue by WebSF** [iview/iview#1209]
分页组件能否自定义增加一个跳转按钮？

**Comment by WebSF** [comment]
@willnewii

**Comment by dean5277** [comment]
本来就有啊
![image](https://user-images.githubusercontent.com/1802631/27280580-fcdc9bfa-551a-11e7-907d-350a05f4612d.png)

**Comment by YikaJ** [comment]
自己在Page外部加一个就可以了呀。处理好 current 后，传进去就可以了。
