### ISSUE TITLE
Select输入框中特殊字符会被转义

### ISSUE THREAD

**Issue by JuZiSang** [iview/iview#1211]
### iView 版本号
**最新版**

### 操作系统/浏览器 版本号
windows10/Chrome 56

### Vue 版本号
**最新版**

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[https://jsfiddle.net/juzisang/hvcvbycv/](https://jsfiddle.net/juzisang/hvcvbycv/)

### 问题现象，以及你期望的结果是怎样的?
![](http://odlhbbkmh.bkt.clouddn.com/17-6-19/43368753.jpg)
### 你估计可能的原因是什么（选填）？
未对特殊字符进行处理，使用v-html解决

**Comment by rijn** [comment]
`:label="item"`
