### ISSUE TITLE
子组件ISelect中model值错误

### ISSUE THREAD

**Issue by xuxia2013** [iview/iview#1212]
### iView 版本号

"iview": "^1.0.1",
### 操作系统/浏览器 版本号

win10 chrome 58
### Vue 版本号

"vue": "^1.0.7",
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/xuxia2013/pen/eRvzYq
### 复现步骤
有一个父组件
<Creator :creator="creator" :change="changeCreator"></creator>
子组件：
  <i-select :model.sync="creator" clearable @on-change="change" placeholder="全部用户" v-on>
    <i-option v-for="item in allUsers" :value="item._id" :key="new Date()">{{ item.name }}</i-option>
  </i-select>

### 问题现象，以及你期望的结果是怎样的?
关闭模态框后，值初始化后，prop值已经改变， 但是子组件ISelect中model值却还是历史值

**Comment by dean5277** [comment]
用v-if去控制组件重新生成

**Comment by icarusion** [comment]
不再对1.x维护了。
