### ISSUE TITLE
select 远程搜索动态赋值问题

### ISSUE THREAD

**Issue by Blackloser** [iview/iview#1215]
### iView 版本号
2.0.0-rc.16

### 操作系统/浏览器 版本号
windows10/Chrome 56

### Vue 版本号
2.2.3

### 复现步骤
![select](https://user-images.githubusercontent.com/26319882/27313452-79396be4-55a0-11e7-8bb7-8d8b770d6bcd.png)

### 问题现象，以及你期望的结果是怎样的?
  从vuex的state中拿值后调用远程搜索方法option中值已远中  但是框内扔没有值
### 你估计可能的原因是什么（选填）？
select框的dom节点没有动态去更新

**Comment by icarusion** [comment]
按要求提问

**Comment by simple-stupid** [comment]
我也遇到了这个问题，v-model动态绑定值到select， select框内不能显示文本值，只有页面第一次加载时就设置好初始值才会显示，调试了下也是dom没有更新。
`<script>
    export default {
        data () {
           return {
              selectModel: 'AAA'  // select可以显示绑定的文本值
           }   
        },
        methods: {
            setSelectValue () {
                this.selectModel = 'BBB'; // select不能显示更新的文本值
            }
        }
    }
</script>`
