### ISSUE TITLE
菜单不能实现hover，右边显示子菜单问题

### ISSUE THREAD

**Issue by xugege** [iview/iview#1216]
1.我后台管理框架，需要做一个导航菜单可以折叠的功能

2.菜单折叠后，子菜单不能显示，希望能实现成hover父菜单，子菜单可以右边漂浮显示

![1xxxx](https://user-images.githubusercontent.com/10491416/27313576-1c7d9dca-55a1-11e7-9505-170bd4591cda.png)

**Comment by icarusion** [comment]
使用 Poptip、Dropdown 等自己实现
