### ISSUE TITLE
Table's first column set fix and render option cause apperance issue

### ISSUE THREAD

**Issue by xiiiAtCn** [iview/iview#1217]
iView version:iview@2.0.0-rc.17
Operation/Browser version: win10/chrome 58.0.3029.110
Vue version: Vue.js v2.3.0
online sample:https://codepen.io/XiiiAtCn/pen/QgpJNJ
reproduce:when dataSource is an array with 0 element, the table's header doesn't show the first column with fix and render option
what expected?
Show the full table's header even if dataSource is an array with 0 element

**Comment by YikaJ** [comment]
@icarusion It's a bug

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/548eac43fe9a510649fc85e86e9279ebaa969ad4

after this commit, you can set a width to fixed column that will be ok, but auto width is not ok now.
