### ISSUE TITLE
#BUG#Table 列数太多 表格初始化高度有问题, 表格高度错位

### ISSUE THREAD

**Issue by shaode** [iview/iview#1219]
### iView 版本号

2.0.0-rc.16
### 操作系统/浏览器 版本号

windows
### Vue 版本号

2.2.6
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/shaode/pen/EXwdNW
![image](https://user-images.githubusercontent.com/4277051/27317851-cdb6c1e2-55bb-11e7-9ed5-797a0f31e52f.png)

### 问题现象，以及你期望的结果是怎样的?
我在tabs里面放一个表格，表格默认的tr高度和table高度不一致，导致数据显示出来也和表格不一致
我切换下tab页，表格就好了，这个怎么解决，求指教，现在很被动
### 你估计可能的原因是什么（选填）？
由于列数太多导致的，宽度超过一个范围导致的，希望尽快修复

**Comment by shaode** [comment]
这个问题有人遇到，或者解决过吗？在线等呀~~

**Comment by shaode** [comment]
@icarusion 找到问题了，由于列数太多导致错位，应该是一个bug

**Comment by dean5277** [comment]
试过40列也不存在这问题

**Comment by shaode** [comment]
@dean5277 我超过宽度1列，就会有问题了

**Comment by YikaJ** [comment]
请提供在线示例，不然根本不知道你的代码大概是怎么写的呀

**Comment by shaode** [comment]
@YikaJ https://codepen.io/shaode/pen/EXwdNW
在tab下，切换下tab就好了，我写了最简单的情况，就是一个tab，很多列，你看看

**Comment by shaode** [comment]
@icarusion 这个问题有临时解决办法吗？

**Comment by YYQ8023** [comment]
@shaode 为什么要给表格一个初始高度呢？去掉那个高度，表格高度会自适应你的内容高度。设了高度酒会固定那么高，无论内容多少。

**Comment by shaode** [comment]
@YYQ8023 考虑到整体布局，初始要有个高度，让整个界面看着舒服，既然提供了可以设置高度的参数，出现了错位，就是个bug吧，项目要上线的，真心希望紧急修复呀！！！！
毕竟数据展示表格还是很多的

**Comment by gggllm** [comment]
我也有这个bug，随着列数减少，高度会缓慢恢复。

**Comment by icarusion** [comment]
Update to the latest version.If there is any problem, please open another issue.

**Comment by yunfengsay** [comment]
这个bug也草草的关了？

**Comment by king7329178** [comment]
我想问下  这个问题最后是怎么 解决的
