### ISSUE TITLE
table的排序是否可以增加点击列名，就排序

### ISSUE THREAD

**Issue by codeskyblue** [iview/iview#122]
现在需要点击那个很小的 按钮
![image](https://cloud.githubusercontent.com/assets/3281689/21125818/3ffdef42-c123-11e6-877f-083f6881556a.png)

操作很不方便

**Comment by imac8t** [comment]
@codeskyblue 进来正想吐槽这个 哈哈

**Comment by Scrooge6792** [comment]
排序交互改成点击表头字段进行reverse操作感觉会比较简便
