### ISSUE TITLE
date-picker日期datetimerange格式化错误

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#1220]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
windows/Chrome 56

### Vue 版本号
2.2.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/GEWzPW

### 复现步骤
选择日期
### 问题现象，以及你期望的结果是怎样的?
期望：[date1, date2] ，date1 - date2
### 你估计可能的原因是什么（选填）？
type === 'daterange' || type === 'timerange'，应该是判断的type类型写错了

**Comment by ChaoLeer** [comment]
2017-11-14 00:00:00 - 2017-11-24 00:00:00

**Comment by webproblem** [comment]
现在date-picker日期datetimerange的值时数组形式 `[date1, date2]`,但是没有考虑到兼容以前的版本写法 `date1 - date2`，在项目更新iview版本时，由于新版本不兼容以前的写法，导致必须修改项目中所有涉及的代码。
