### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by nieyulin112** [iview/iview#1221]
打包的时候报这个问题
ERROR in static/js/vendor.6cb8570731583c9b326b.js from UglifyJs
Unexpected token: operator (>) [./~/iview/src/mixins/emitter.js:2,0][static/js/vendor.6cb8570731583c9b326b.js:44067,34]

**Comment by shaode** [comment]
@nieyulin112 我也遇到了，好惨差点把项目搞砸了

**Comment by Refunzhan** [comment]
这个怎么解决

**Comment by SergioCrisostomo** [comment]
@Refunzhan I cannot reproduce this problem, `iview` compiles without problems.

If you have a problems compiling iView please open a issue with code to reproduce your problem.

**Comment by Refunzhan** [comment]
@SergioCrisostomo  Thanks for you to reply my question ,when I npm run build my program ,I met follow question ,is any problem with es5 and es6 ??

**Comment by Refunzhan** [comment]
@SergioCrisostomo Thanks for you to reply my question ,when I npm run build my program ,I met follow question ,is any problem with es5 and es6 ??

ERROR in static/js/vendor.6cb8570731583c9b326b.js from UglifyJs
Unexpected token: operator (>) [./~/iview/src/mixins/emitter.js:2,0][static/js/vendor.6cb8570731583c9b326b.js:44067,34]

**Comment by icarusion** [comment]
@Refunzhan more info can be found in https://stackoverflow.com/questions/39329867/uglifyjs-throws-error-unexpected-token-operator and you can search through stackoverflow

**Comment by GoldenNotebook** [comment]
@Refunzhan Do you solve it? I meet this problem too. (sad)
