### ISSUE TITLE
DatePicker组件BUG,第二次选择时间，时分秒会默认变为当前时间。

### ISSUE THREAD

**Issue by justnowanna** [iview/iview#1223]
如题，
DatePicker组件BUG,第二次选择时间，时分秒会默认变为当前时间。第一次选择的时间是
`2017-06-18 00:00:00 - 2017-06-19 00:00:00`，
然后清空，再次选择会变为
`2017-06-18 13:41:45 - 2017-06-19 13:41:45`，
以后每次都会是当前时间，导致作为查询条件的时候查不出数据，需要手动选择时间，使用上会麻烦一点。
望在未来能修复
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Win10/Chrome 56

### Vue 版本号
^2.3.0

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/galence/p69go9rc/3/

### 复现步骤
如题
### 问题现象，以及你期望的结果是怎样的?
如题
### 你估计可能的原因是什么（选填）？
如题

**Comment by SergioCrisostomo** [comment]
@justnowanna can you check if this is still a problem? I cannot reproduce this problem anymore in version `2.2.0`.
