### ISSUE TITLE
火狐浏览器下select多选出现样式问题

### ISSUE THREAD

**Issue by jinghh** [iview/iview#1224]
### iView 版本号

官方网上的例子
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://www.iviewui.com/components/select
![image](https://user-images.githubusercontent.com/18163968/27326326-b984b072-55dd-11e7-9214-98247af28722.png)

### 复现步骤
选择选项，右侧的对勾掉到了下一行，
### 问题现象，以及你期望的结果是怎样的?
火狐下样式不出错
### 你估计可能的原因是什么（选填）？
根据审查发现是应为火狐下after伪类元素继承了父级.ivu-select-item的white-space:nowrap属性，造成了该样式问题

**Comment by icarusion** [comment]
#1143
