### ISSUE TITLE
Input建议增加中文输入法支持

### ISSUE THREAD

**Issue by henrylu** [iview/iview#1225]
Input的on-change事件目前没有考虑到中文输入的情况，也就是说中文或日方等文字在还没选择好字词时就会触发onchange事件，但等到选定好中文文字上屏后又会再触发一次onchange事件。期望的是当使用中文输入法，在浏览器里有直接的文字输入时，才会触发onchange事件。

## 参考：
- [中文输入法与React文本输入框的问题与解决方案](https://segmentfault.com/a/1190000008023476)
- [input 事件兼容处理以及中文输入法优化](http://frontenddev.org/article/compatible-with-processing-and-chinese-input-method-to-optimize-the-input-events.html)

**Comment by MarvinWilliam** [comment]
vue本身是有一个directive是处理中文字符输入的,[directives/model](https://github.com/vuejs/vue/blob/4acc8c8be1971112be45e0feb7fb7eddbfc9d247/src/platforms/web/runtime/directives/model.js)
在中文处理的时候通过compositionstart, compositionend, 最后再来trigger('input')

iview的Input组件on-change是在监听input事件向上传递的
```
 handleInput (event) {
    let value = event.target.value;
    if (this.number) value = Number.isNaN(Number(value)) ? value : Number(value);
    this.$emit('input', value);
    this.setCurrentValue(value);
    this.$emit('on-change', event);
 },
```

不太明白你是什么情况下遇到选词问题的.

**Comment by lifedever** [comment]
这个问题为什么关了？难道不是bug吗？
