### ISSUE TITLE
this.$modal.confirm里面的render嵌套Select ，开启了 multiple 属性后报错

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1227]
### iView 版本号
rc17

### 操作系统/浏览器 版本号
chrome  59.0.3071.104

### Vue 版本号
2.3.4

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/zxa55wu9/2/
https://jsfiddle.net/zxa55wu9/3/

开启了 multiple  属性后报错

### 复现步骤
点击下拉框，选择值，报错

![image](https://user-images.githubusercontent.com/1802631/27374148-5e72866c-569d-11e7-9119-b439f3c0472b.png)

### 你估计可能的原因是什么（选填）？
render并不提供v-model的指令，这个指令要自己配置。

**Comment by johnfanyong** [comment]
我也有这个问题，我是在table里面使用Select多选。

**Comment by johnfanyong** [comment]
https://jsfiddle.net/zxa55wu9/5/
props里面增加value:[]可以不报错，但是不会同步更新model

**Comment by dean5277** [comment]
这问题到底有没有解决的方法？没办法我就不再用这方法了

**Comment by angrytoro** [comment]
@dean5277 你传的值不对吧，如果是数组的话是不会报错的，试过了。

**Comment by icarusion** [comment]
Wrong use in `v-model`, please read Vue doc. [Render function v-model](https://cn.vuejs.org/v2/guide/render-function.html#v-model)

**Comment by dean5277** [comment]
看了文档半天，我才知道用input重新设置值。。。。太隐藏了。。。。
