### ISSUE TITLE
Select组件的BUG远程搜索模式下，设置disabled或者readonly仍然可以输入文字

### ISSUE THREAD

**Issue by justnowanna** [iview/iview#1228]
如题

### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
 2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/galence/p69go9rc/4/

### 复现步骤
如题
### 问题现象，以及你期望的结果是怎样的?
如题
### 你估计可能的原因是什么（选填）？
如题

**Comment by SergioCrisostomo** [comment]
Thank you for reporting this. I think this has been fixed since `2.0.0-rc.17`. 

Please check again with current version `2.2.0`: https://jsfiddle.net/Sergio_fiddle/p69go9rc/9/
