### ISSUE TITLE
DatePicker在Modal form里，打开后click其他区域不能关闭

### ISSUE THREAD

**Issue by larryu** [iview/iview#1229]
### iView 版本号
2.0.0-rc.14

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
DatePicker在Modal form里，打开后click其他区域不能关闭，普通form没有问题。

**Comment by icarusion** [comment]
已知问题

**Comment by larryu** [comment]
@icarusion 在最新版本已经修复了吗？

**Comment by larryu** [comment]
@icarusion我在rc18版本里试了下，还是有同样问题，其实不光是datapicker， select, cascade都有同样的问题。

**Comment by iceuncle** [comment]
遇到同样问题，点击其他区域，需要点击两次才会消失。
