### ISSUE TITLE
日期控件能不能添加一个选月范围和周范围的

### ISSUE THREAD

**Issue by fanyonglong** [iview/iview#1231]

**Comment by dean5277** [comment]
本来就有啊
![image](https://user-images.githubusercontent.com/1802631/27421044-2af28fee-575b-11e7-96eb-d1bee3cecf1f.png)

**Comment by fanyonglong** [comment]
不是这种，像daterange 类型这种，但是只显示周或月的

**Comment by YikaJ** [comment]
月也不一定要 daterange 的形式吧，就分开两次点开就好了，一个开始月，一个结束月。
周估计就没那么好弄了。

**Comment by fanyonglong** [comment]
本来是用两个分开的，但是作日期验证范围验证就不好弄，比如：限定在三个月内，那我在选择的时候就要验证，如果是分开两个的话，你就不不知道，用户具体什么时候确定最终选择

**Comment by YikaJ** [comment]
@fanyonglong 那肯定是两个都有值的时候进行验证呗。你的两个 datepicker 都绑上 onChange，判定两个v-model 都有值的时候就行验证就好啦。

**Comment by fanyonglong** [comment]
场景可能我没有描述清楚，就是两个月份不为空的情况，比如默认：startDate 2017-03 endDate 2017-06不能让他们相差月份不能超过三个月。那要是超过三个月，进行提示。如果这种情况下，用户要选2017-01 到2017-03，无论先选哪一个都会超过3个月而且提示。我现在的做法是利用两个月份控件放在弹出层里面，变相的组成一个范围选择器，下面加了一个确定按钮，来进行最终选择和验证。要是换成daterang 这种，没必要这么麻烦了。可以在onChange 后进行就行了

**Comment by Peterlhx** [comment]
https://github.com/iview/iview/pull/691 我改写了一个月份的范围选择器组件

**Comment by xiebanglong** [comment]
为什么不支持一下这个功能呢，感觉很常用啊
