### ISSUE TITLE
建议图片上传可以提供手动上传的设置，现在只有自动上传

### ISSUE THREAD

**Issue by hlerenow** [iview/iview#1232]

**Comment by icarusion** [comment]
支持，看文档

**Comment by hlerenow** [comment]
![image](https://user-images.githubusercontent.com/13299648/27418347-2c240446-574d-11e7-878d-5ef1eb157184.png)
文档里面我看见有一个可以终止上传的事件，但是没有函数可以触发上传，只能用户选择图片或文件后出发

**Comment by lzwzzy** [comment]
同问，确实没有手动上传的api
