### ISSUE TITLE
难道iview必须使用webpack来打包使用？

### ISSUE THREAD

**Issue by JSW5297** [iview/iview#1233]
难道iview必须使用webpack来打包使用？
我通过CDN使用时一些组件都打不到预期的效果，样式没了。
换到webpack使用时就都好了

**Comment by JSW5297** [comment]
还有你们的组件命名规则到的是什么？
是html原生有的就前面加一个'i-'？
例如Button就变成i-button ？
但是你们的例子中使用webpack打包的话又是直接写成Button

**Comment by icarusion** [comment]
仔细看文档

**Comment by JSW5297** [comment]
文档写的有点烂。。真的，并不是在喷

**Comment by JSW5297** [comment]
就比如一个Grid栅格，Row就是写Row，Col缺要写i-col
