### ISSUE TITLE
select组件，Option 的label 默认读取 slot 无法解析html标签

### ISSUE THREAD

**Issue by webees** [iview/iview#1236]
iview版本2.0.0-rc.17

文档说的Option 的label 默认会显示slot ，实际上却是显示的字符串，而不是自定义模板。

**Comment by dean5277** [comment]
rc17

**Comment by webees** [comment]
@dean5277 就是最新版。

**Comment by dean5277** [comment]
自定义的模板用render尝试下

**Comment by webees** [comment]
没法，刚看了源代码。
```
            <Select v-model="d_select_price" size="large" @on-change="showPriceTips" :disabled="d_select_disabled" placeholder="【未设置】选择框默认文字">
                <Option v-for="item in d_price_list" :value="item.planid" :key="item" :label="item.desc_info">
                    <span v-text="item.desc_info"></span>
                    <span class="unit_price" v-text="'$' + item.month_price + ' /Month'"></span>
                </Option>
            </Select>
```
如上代码片段

ivu-select-item中会正常显示 <li class="ivu-select-item"><span>3 Months</span> <span class="unit_price">$79.99 /Month</span></li>

但是ivu-select-selected-value中却是<span class="ivu-select-selected-value">&lt;span&gt;3 Months&lt;/span&gt; &lt;span class="unit_price"&gt;$79.99 /Month&lt;/span&gt;</span>

**Comment by dean5277** [comment]
你的意思是说<span>3</span>是字符串？

**Comment by dean5277** [comment]
用jsfiddle把代码挂上来才好判断

**Comment by webees** [comment]
感谢你的回复，这里是用到select的自定义模板，当没有在Option中使用label属性的时候，结合上面的代码片段，选项显示内容（选择一个下拉选项后显示的的内容）会显示类似“&lt;span&gt;3 Months&lt;/span&gt; &lt;span class="unit_price"&gt;$79.99 /Month&lt;/span&gt;”。然而我们希望渲染成<span>3 Months</span> <span class="unit_price">$79.99 /Month</span>

**Comment by dean5277** [comment]
https://jsfiddle.net/ks60s2k5/  感觉不存在这问题

**Comment by webees** [comment]
@dean5277 multiple和filterable删除

**Comment by webees** [comment]
这里的渲染是插入指标签<span>而不插入字符串`&lt;span&gt;`

**Comment by dean5277** [comment]
也是可以的啊

**Comment by dean5277** [comment]
![image](https://user-images.githubusercontent.com/1802631/27430178-23df2cca-577a-11e7-9181-246bd3a67ca0.png)

**Comment by lcx960324** [comment]
#1112

**Comment by lcx960324** [comment]
确实是个 Bug，不过目前没找到合适的解决方案。有进展一定第一时间更新。

**Comment by zhonglianicon** [comment]
请教如何在table 里面 通过 render 方式 添加  带有 “开启” “关闭” 的自定义文字 switch 组件？

**Comment by webees** [comment]
升级到2.3.2，依然存在该问题
