### ISSUE TITLE
tabs动态添加后，如果从中间开始关闭，会出大问题

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1237]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
QQ浏览器，chromium53.0.278.104

### Vue 版本号
2.3.0

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/anon/pen/EXXmeO

### 复现步骤
1.点击添加标签1
2.点击添加标签2
3.关闭标签1
4.关闭标签2
### 问题现象，以及你期望的结果是怎样的?
在3关闭标签1之后（则从中间开始关闭标签），标签是关闭了，但是下方的panel内容没有随之消失，此时再关闭标签2，就会出错。
但是如果是从右往左逐个关闭，就没问题。
### 你估计可能的原因是什么（选填）？
暂时没想法

**Comment by lvqingan** [comment]
给每个tabpanel加上一个key属性用以区分

**Comment by itpretty** [comment]
遇到过同样问题，后来换用了 jQuery UI 的 Tab 插件。也是为了避免 iViewUI 组件嵌套层数太多，层数太多会导致一些无法预测的问题。
