### ISSUE TITLE
非 template/render 模式下，组件名称不统一。

### ISSUE THREAD

**Issue by RainingNight** [iview/iview#1239]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Win10/Chrome 58

### Vue 版本号
2.3.0

### 问题现象，以及你期望的结果是怎样的?

示例：

```html
<div id="app">
    <i-button @click="show">Click me!</i-button>
    <Modal v-model="visible" title="Welcome">欢迎使用 iView</Modal>
</div>
```

非 template/render 模式下，有些组件使用*i-xxx*模式，有些组件还是使用大写名称，不够统一，导致代码看起来非常乱！！！

**Comment by xiaomizhou66** [comment]
请教下 什么叫非 template/render 模式，从饿了么过过来的，感觉不会用iview
