### ISSUE TITLE
建议把css扩展做灵活点例如:label-size="14"

### ISSUE THREAD

**Issue by MrHanPm** [iview/iview#1240]
### 问题现象，以及你期望的结果是怎样的?
有很多地方特殊，需要调整字号等样式。你这外部样式覆盖不进去。建议思考一下扩展例如:label-size="14"等。或者携带特殊的符号覆盖原有的class

**Comment by lcx960324** [comment]
外部样式可以覆盖。

**Comment by MrHanPm** [comment]
嗯。了解了。只能调用src下的文件并且在单文件覆盖。不能直接在组件开发中局部覆盖。谢谢您的回答

**Comment by rijn** [comment]
hum. You can add another class to the component to override style of it.

```
<Icon class="my-icon"></Icon>

<style>
.my-icon {
    size:...
}
</style>
```
