### ISSUE TITLE
table 组件能不能加一个复杂表头的，多列头这种

### ISSUE THREAD

**Issue by fanyonglong** [iview/iview#1249]
就是有colspan rowspan 这种列

**Comment by fanyonglong** [comment]
希望能看到。这种功能真的在后台管理系统里面，特别是统计之类的table 时候，很常见的功能，

**Comment by dean5277** [comment]
[#492](https://github.com/iview/iview/pull/492)

**Comment by fanyonglong** [comment]
计划什么时候可以更新这个功能，我看了源码，以这种方式做的冻结列和列头，增加复杂表头，不会影响什么

**Comment by icarusion** [comment]
#1249
