### ISSUE TITLE
page组件问题

### ISSUE THREAD

**Issue by dai875939260** [iview/iview#1252]
pager组件里的元素都是浮动，能不使用浮动，使用inline-block替代，不然组件都没办法居中

![image](https://user-images.githubusercontent.com/6057326/27568244-483b98e0-5b23-11e7-9fc9-01eecf053cac.png)

**Comment by dean5277** [comment]
外层包一个，居中，这种很灵活。

**Comment by dai875939260** [comment]
你确定可以么。。浮动元素好像没办法居中把

**Comment by ruofeng086** [comment]
same question.

wrap给多少宽度？这样的设计真的很low...

**Comment by 16Free** [comment]
真的，这个page的设计真的很low，无法很好的居中

**Comment by ihuguowei** [comment]
@16Free 可能当初未考虑剧中的场景，至于说 low 大可不必，自己改完提个 PR 即可。

**Comment by 16Free** [comment]
@ihuguowei 没有恶意，只是针对这个居中的问题来说，别过度理解语义

**Comment by 16Free** [comment]
@ihuguowei 可能我用的语言不是很好~，我改。。。。

**Comment by 16Free** [comment]
@ihuguowei  刚刚去看了一下。发现2.0里面已经修复了
