### ISSUE TITLE
table的on-current-change事件执行顺序在render里面按钮点击之后的问题

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1253]
用render在table某一列里面写了一个button，
button点击的时候想获得选中行的数据，
但是由于click事件比table的on-current-change执行更快，
需要在click里面用settimeout来延迟才能正常获得选中行的数据。

不知道作者能不能通过某些手段，让这个执行顺序可以调整一下？

**Comment by fanyonglong** [comment]
你可以往上到下冒泡

**Comment by kiddkyd1412** [comment]
@fanyonglong 新手，一脸懵逼。。。。
