### ISSUE TITLE
webpack中使用externals方式引入iview报错

### ISSUE THREAD

**Issue by mantutu** [iview/iview#1254]
### iView 版本号

2.0.0-rc.16

### 操作系统/浏览器 版本号

window 7.0 / Chrome 最新

### Vue 版本号

2.0+

### 问题
在html中以cdn的方式引入iView
在webpack中使用externals的方式引入iView：
```
externals: {
 'iView': 'iview'
}
```
之后使用date-picker和time-picker的时候会报错
报一个s.default is not constructor的错误
我认为是new Vue的时候报的一个错误，，不知道怎么解决

**Comment by huixisheng** [comment]
是否是`iView `的大小写问题？ 
```
externals: {
 iview: 'iview'
}
```
如果不是是否可以提供相关的demo?

**Comment by SergioCrisostomo** [comment]
@mantutu can you provide a example of this behaviour?

使用下面的在线链接可以快速创建示例
