### ISSUE TITLE
Select 在remote 模式下初始化渲染问题

### ISSUE THREAD

**Issue by a731740204** [iview/iview#1255]
![_20170628095914](https://user-images.githubusercontent.com/29743501/27617363-5e9fbcf4-5be8-11e7-9a4e-1357e86009fd.png)
Select 在remote 模式下，用mounted初始化渲染数据的情况下，设置的label 无法显示在Select框内，并且初始化的数据是无法选取的

**Comment by zhouzgang** [comment]
解决了吗？

**Comment by lavenkin** [comment]
这就关闭了？我也是遇到这样的问题啊

**Comment by icarusion** [comment]
按要求提问

**Comment by BoleLee** [comment]
#3897
