### ISSUE TITLE
【BUG】Tab标签的Tab-pane设置v-if或者v-show无效

### ISSUE THREAD

**Issue by justnowanna** [iview/iview#1257]
初始化的设置是有效的，后面通过其他方式改变`v-if`或者`v-show`的值是无效的。已提供在线实例。

### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/galence/p69go9rc/5/

**Comment by icarusion** [comment]
只能通过Tab自带的关闭功能来关闭。
自己关闭，要调用 handleRemove 方法，具体看源码。
