### ISSUE TITLE
上传控件点击上传按钮右侧也会触发上传功能

### ISSUE THREAD

**Issue by caozhengchn** [iview/iview#1258]
### iView 版本号

2.0.0-rc.17 

### 操作系统/浏览器 版本号

window7/Chrome 56
### Vue 版本号

2.3.3
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

官网也会有此问题 https://www.iviewui.com/components/upload
### 复现步骤
使用Upload控件，在按钮右侧点击鼠标右键
### 问题现象，以及你期望的结果是怎样的?
期望结果：无任何响应，只有点击上传参数的按钮时才会弹出上传的窗体
实际结果：弹出上传的窗体

**Comment by huixisheng** [comment]
确实存在这个问题。建议给`Upload`设置容器制定宽度同时设置`hidden`
