### ISSUE TITLE
this.$Modal.confirm 后调用this.$Modal.error error对话框会随着消失

### ISSUE THREAD

**Issue by lijing666** [iview/iview#1259]
### iView 版本号
2.0.0-rc.16 

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.2

### 复现步骤
```
iview$Modal.confirm(...);
iview$Modal.error(...);
```
第一个确定后，第二个自动关闭了，原因是由于两个modal是同一个instance，第一个点击确定后会在300毫秒自动清除实例，所以第二个对话框也消失了。
来自src/modal/confirm.js
```
remove () {
                setTimeout(() => {
                    this.destroy();
                }, 300);
            },
```
### 问题现象，以及你期望的结果是怎样的?
第一个对话框关闭后，弹出第二个对话框不应该自动关闭

### 你估计可能的原因是什么（选填）？
src/modal/index.js中构造对话框实例不应该存储为局部变量，每次应该newInstance才对，建议去掉局部变量modalInstance或者默认是newInstance，给定一个参数控制是否需要缓存modalInstance，个人觉得没有必要缓存modalInstance，因为每次使用完有定时器自动清理的，如上面的remove代码
```
function getModalInstance (render = undefined) {
    modalInstance = modalInstance || Modal.newInstance({
        closable: false,
        maskClosable: false,
        footerHide: true,
        render: render
    });

    return modalInstance;
}
```

**Comment by icarusion** [comment]
Modal 的设计初衷是全局只能有一个。要开启第二个，需在第一个销毁后。

**Comment by lijing666** [comment]
但是对于pc端的场景，同时弹出多个对话框是很正常和普通的功能，希望能支持，通过增加一个配置开关设置也可以啊，谢谢

**Comment by lijing666** [comment]
@icarusion iview 官网没看到怎么贡献代码的规范，或许是我没找到链接，如果我要提送自己的代码上去，要怎么走流程，谢谢告知一下

**Comment by l2999019** [comment]
我也碰到了这个问题, 有什么好的解决方案么?

**Comment by l2999019** [comment]
@icarusion  我也找到了你说的源码的位置:
            remove () {
                this.closing = true;
                setTimeout(() => {
                    this.closing = false;
                    this.destroy();
                }, 300);
            },
我完全搞不明白为什么这里要延迟30毫秒来关闭confirm提示
大概有个临时的解决方案,在OK回调里面 设置延迟的时间比他长1毫秒就可以如下:
 iview.Modal.confirm({
                title: '系统提示',
                //loading: true,
                content: '<p>' + content + '</p>',
                onOk: async () => {

                    if (okcallback != null) {

                        setTimeout(() => {
                            okcallback();
                            
                        }, 310);
                    }
                },
                onCancel: () => {
                    if (cancelcallback != null) {
                        setTimeout(() => {
                            cancelcallback();

                        }, 310);
                       
                    }
                }
            });

- [ ]

**Comment by lijing666** [comment]
> @icarusion 我也找到了你说的源码的位置:
> remove () {
> this.closing = true;
> setTimeout(() => {
> this.closing = false;
> this.destroy();
> }, 300);
> },
> 我完全搞不明白为什么这里要延迟30毫秒来关闭confirm提示
> 大概有个临时的解决方案,在OK回调里面 设置延迟的时间比他长1毫秒就可以如下:
> iview.Modal.confirm({
> title: '系统提示',
> //loading: true,
> content: '
> 
> ' + content + '
> 
> ',
> onOk: async () => {
> ```
>                 if (okcallback != null) {
> 
>                     setTimeout(() => {
>                         okcallback();
>                         
>                     }, 310);
>                 }
>             },
>             onCancel: () => {
>                 if (cancelcallback != null) {
>                     setTimeout(() => {
>                         cancelcallback();
> 
>                     }, 310);
>                    
>                 }
>             }
>         });
> ```
> 
> * [ ]

@l2999019 iview的作者 icarusion 已经离开了，他新起了项目https://github.com/view-design/ViewUI，现在两个是不同的公司维护
