### ISSUE TITLE
Tooltip包裹的元素没有了栅格布局！

### ISSUE THREAD

**Issue by xieyangds** [iview/iview#1260]

**Comment by huixisheng** [comment]
没看懂什么意思，能否提供详细的描述

**Comment by itpretty** [comment]
换用 Poptip 试下 @xieyangds 

> Poptip 与 Tooltip 类似，具有很多相同配置，不同点是 Poptip 以卡片的形式承载了更多的内容，比如链接、表格、按钮等。

> Poptip 还 confirm 确认框，与 Modal 不同的是，它会出现在就近元素，相对轻量。

**Comment by icarusion** [comment]
请按要求提问。
