### ISSUE TITLE
Modal onOk不起作用

### ISSUE THREAD

**Issue by johnfanyong** [iview/iview#1261]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
 macOS/Chrome 58 

### Vue 版本号
2.3.4

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://jsfiddle.net/zxa55wu9/10/
### 复现步骤
按照文档添加自定义ok回调方法“ onOk”
### 问题现象，以及你期望的结果是怎样的?
onOk未触发
### 你估计可能的原因是什么（选填）？
看了源码，onOk应该是事件on-ok，并不是onOk属性
修改为@on-ok=""解决

**Comment by icarusion** [comment]
用法
