### ISSUE TITLE
iview table 排序自定义排序的sortMethod方法什么用，返回的是什么样的数据，文档里面没找到相关的例子

### ISSUE THREAD

**Issue by chewel611** [iview/iview#1273]

**Comment by rijn** [comment]
If your data have a column called `age`

```
sortMethod: (a, b, type) => type === 'asc' ? a.age > b.age : a.age < b.age;
```

**Comment by chewel611** [comment]
按照这种方式处理【sortMethod: (a, b, type) => type === 'asc' ? a.age > b.age : a.age < b.age;】，解决多次排序的问题，但是每次排序结果都不一样
![1](https://user-images.githubusercontent.com/8287814/27757955-2a141222-5e3c-11e7-8a76-05c009952b76.png)
![2](https://user-images.githubusercontent.com/8287814/27757957-2a2302e6-5e3c-11e7-984f-74c91d91d371.png)
![3](https://user-images.githubusercontent.com/8287814/27757956-2a1f9c50-5e3c-11e7-9fda-4b62ef4a127f.png)
![4](https://user-images.githubusercontent.com/8287814/27757958-2a2e3756-5e3c-11e7-943b-4b1ad93356ff.png)

**Comment by rijn** [comment]
It couldn't be a bug since we're using build-in sort method. [https://github.com/iview/iview/blob/69e0ef5d0c25fe29ec8589c6b9f1d274517c9213/src/components/table/table.vue#L479-L481](https://github.com/iview/iview/blob/69e0ef5d0c25fe29ec8589c6b9f1d274517c9213/src/components/table/table.vue#L479-L481)

**Comment by 18boys** [comment]
为什么要关闭? 现在的文档也没有对此说明呀?

**Comment by huanggm** [comment]
猜测你没有在column中指定key，根据 @rijn 提供的源码可以看出是一定需要key的。

@rijn @icarusion 建议源码中不依赖key更好，直接把row当作参数，因为表格的某一列的排序并不一定只依赖一个参数，可能是多个参数比较的结果。

修改为 `return this.cloneColumns[index].sortMethod(a, b, type);`

**Comment by smartwange** [comment]
sortable  'custom'

**Comment by mark009** [comment]
> 按照这种方式处理【sortMethod: (a, b, type) => type === 'asc' ? a.age > b.age : a.age < b.age;】，解决多次排序的问题，但是每次排序结果都不一样
> ![1](https://user-images.githubusercontent.com/8287814/27757955-2a141222-5e3c-11e7-8a76-05c009952b76.png)
> ![2](https://user-images.githubusercontent.com/8287814/27757957-2a2302e6-5e3c-11e7-984f-74c91d91d371.png)
> ![3](https://user-images.githubusercontent.com/8287814/27757956-2a1f9c50-5e3c-11e7-9fda-4b62ef4a127f.png)
> ![4](https://user-images.githubusercontent.com/8287814/27757958-2a2e3756-5e3c-11e7-943b-4b1ad93356ff.png)

三目运算需要返回 1 or -1 。
比如 sortMethod: (a, b, type) => type === 'asc' ? (a.age > b.age ? 1 : -1) : (a.age < b.age ? 1 : -1);

**Comment by Samele-QoQ** [comment]
搞不懂欸，我连console.log(xxx)都打印不了，让我怀疑他都没运行欸
![QQ截图20240515185421](https://github.com/iview/iview/assets/73659744/8f135715-0553-4141-86bb-fa61f159f4d0)
版本问题嘛？
感觉这个组件问题真的很多

**Comment by 18boys** [comment]
已收到,稍候会处理best wish~

**Comment by Samele-QoQ** [comment]
求，之前版本的自定义排序的方法如何调用，这边遇到任务需求点击文字不让排序






| |
镜默语
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年5月15日 18:57 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [iview/iview] iview table 排序自定义排序的sortMethod方法什么用，返回的是什么样的数据，文档里面没找到相关的例子 (#1273) |
已收到,稍候会处理best wish~
