### ISSUE TITLE
select多选的重新赋值时会导致出现重复

### ISSUE THREAD

**Issue by marxy** [iview/iview#1274]
select多选的重新赋值时会导致出现重复。比如我有2个选择框，一个单选框，一个多选框。多选框内容会根据我的单选框选择动态加载，加载后会默认选择一项，多次选择单选框切换内容，结果会导致多选框里出现2个重复的默认项

![select-bug](https://user-images.githubusercontent.com/12171912/27736991-1263f902-5dd9-11e7-9c55-76faf3961ed8.png)

### iView 版本号

最新版

### 操作系统/浏览器 版本号

chrome 58

### Vue 版本号

最新版

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/marxy/pen/QgQJPE

### 复现步骤
在上面事例中的单选框切换选择可看到效果

### 问题现象，以及你期望的结果是怎样的?
不要出现重复

**Comment by itpretty** [comment]
JS 第 45 行改写成：
`var vm = this;
    setTimeout(function(){
        vm.model2 = ['beijing'];
},0);`

**Comment by marxy** [comment]
这是为什么呢？

**Comment by rijn** [comment]
```
this.$nextTick(() => {
  this.model2 = ['beijing'];
});
```

**Comment by itpretty** [comment]
要等 i-option 重新渲染完后，才好去做“选中”的操作。否则，没得选，程序内部可能就“自造”了一个多余的。 @marxy

**Comment by marxy** [comment]
好的，谢谢各位
