### ISSUE TITLE
iview table远程排序，设置table的on-sort-change时，无法执行监听的方法

### ISSUE THREAD

**Issue by chewel611** [iview/iview#1275]
### 复现步骤
![1](https://user-images.githubusercontent.com/8287814/27758263-a7d2b05a-5e42-11e7-8327-d050e3bef801.jpg)
![2](https://user-images.githubusercontent.com/8287814/27758264-a7d34196-5e42-11e7-9d01-961b8e58a4c0.jpg)
![3](https://user-images.githubusercontent.com/8287814/27758265-a7d8a4a6-5e42-11e7-8ab1-53991cdeb831.jpg)

### 问题现象，以及你期望的结果是怎样的?
点击排序没有效果，
期望可以执行到监听的方法内容

**Comment by liufeics** [comment]
@on-sort-change="sortOrder"

**Comment by icarusion** [comment]
The answer above is correct

**Comment by hesenkang** [comment]
key，order  为什么打印出来是空的？那我怎么判断点击的是降序还是升序呢？
