### ISSUE TITLE
Radio-group v-model使用computed的数据时，无法选择

### ISSUE THREAD

**Issue by klgd** [iview/iview#1278]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Win7 / Chromium 58.0.3029.110

### Vue 版本号
2.3.4

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/0a131h8o/2/

### 复现步骤
 金斑蝶、爪哇犀牛、印度黑羚 点击没有任何反应（假如点击了印度黑羚），而这时点击Apple、Android、Windows中的任意一个，印度黑羚也同时会出现选中

**Comment by ramonmata** [comment]
There is a bug in your code:
- Model does not exist `<Radio-group v-model="info.animal">`

Change it to `<Radio-group v-model="animal">`
✌️

**Comment by klgd** [comment]
@ramonmata   
I'm sorry   
my first example is wrong, the `info` from `computed`  
I has edit this issue   

PS: my English is poor

**Comment by klgd** [comment]
用错方法了，没问题了

**Comment by kernnel** [comment]
@klgd  我也遇到同样的问题，你是怎么解决的，能分享一下么

**Comment by klgd** [comment]
@kernnel [https://cn.vuejs.org/v2/guide/components.html#使用自定义事件的表单输入组件](https://cn.vuejs.org/v2/guide/components.html#使用自定义事件的表单输入组件)   
[https://cn.vuejs.org/v2/guide/computed.html#计算属性](https://cn.vuejs.org/v2/guide/computed.html#计算属性) 
你看一下手册就明白了，我不太会描述其中的原理
