### ISSUE TITLE
打包生产使用UglifyJs报错

### ISSUE THREAD

**Issue by gefangshuai** [iview/iview#1279]
### 复现步骤
执行
```sh
npm run build
```
### 问题现象，以及你期望的结果是怎样的?
报错如下：
```
ERROR in static/js/vendor.0c3d1d37ce9c9f59d4dc.js from UglifyJs
Unexpected token: operator (>) [./~/._iview@2.0.0-rc.17@iview/src/components/base/notification/index.js:4,0][static/js/vendor.0c3d1d37ce9c9f59d4dc.js:82084,84]
```
### 你估计可能的原因是什么（选填）？
请问怎么解决呢？

**Comment by huixisheng** [comment]
你是用`vue-cli`初始化的项目，`iView`当做模块去构建吗？如何是这样，`iView`已经用`babel`转换过了，需要在配置用忽略；如果不是，麻烦提供具体的描述。

**Comment by doudouyoutangtang** [comment]
@huixisheng 同打包报错，如何在配置用忽略？

**Comment by doudouyoutangtang** [comment]
vue-cli初始化的项目，iView当做模块构建的，iveiw的assist.js没有转es5，导致报错——版本2.0.0-rc.13

**Comment by doudouyoutangtang** [comment]
vue-cli初始化的项目，iView当做模块构建的，报iveiw的assist.js没有转es5——版本2.0.0-rc.18

**Comment by doudouyoutangtang** [comment]
开发没问题，打包就不行 @huixisheng

**Comment by doudouyoutangtang** [comment]
@gefangshuai 大哥解决没有

**Comment by gefangshuai** [comment]
@dspangenberg 没解决

**Comment by doudouyoutangtang** [comment]
@gefangshuai 我是手动去吧assist.js改成es5的，才打包起

**Comment by dspangenberg** [comment]
@gefangshuai Sorry, I don't understand Mandarin. Could I help you?

**Comment by q313729286** [comment]
@gefangshuai 同问题，使用的是iview单组件的按需引入，babel配置也按照文档的添加了，报上面的错误，发现es6代码并没有被转换为es5，导致UglifyJs压缩混淆出错。亲测去掉iview组件的引入则编译通过
module: {
    rules: [
        { test: /iview.src.*?js$/, loader: 'babel' },
        { test: /\.js$/, loader: 'babel', exclude: /node_modules/ }
    ]
}

**Comment by gefangshuai** [comment]
@q313729286 请问在哪个文件里改？

**Comment by huixisheng** [comment]
可以在这里`.babelrc`添加配置

```
{
 ...
 "ignore": [
    "iview.js"
 ]
}
```

@gefangshuai 
或者@q313729286 提到的配置应该在`build/webpack.base.conf.js` 中

**Comment by gefangshuai** [comment]
@huixisheng 谢谢，我已经将view的src通过源码的方式放到项目中，感觉这样更可控一些

**Comment by q313729286** [comment]
@gefangshuai @huixisheng 因为使用iview单组件，不想整个引入iview，所以必须使用iview的src代码，但是src目录下的但是都是es6的写法，所以babel配置肯定需要，所以ignore配置肯定不行。另外测试发现按照官方的配置，在部分服务器上编译没问题，在我本地的mac上也没问题，但是在QA服务器上编译不通过，iview的组件代码没有被转换为es5语法，导致UglifyJs压缩混淆错误。而且发现另外一个问题，编译不通过的服务器编译出来的文件跟本地mac环境和其他服务器环境不一致，vendor.js没有生成，先后在QA的两台服务器上测试，都是同样的问题，系统为centos。

**Comment by q313729286** [comment]
@gefangshuai @huixisheng 而且测试发现使用vue.use(iview)的方式引入iview的话，会导致打包后的文件特别大。
使用import Switch from 'iview/src/components/switch';单组件引入方式：
![image](https://user-images.githubusercontent.com/5163839/28099491-786ec33e-66ef-11e7-8c47-fee8f7b6549d.png)
使用vue.use(iview)方式（压缩后的完全版iview不也才70+kb的大小吗？）：
![image](https://user-images.githubusercontent.com/5163839/28099550-c0317af4-66ef-11e7-8e20-a76bb46a4a4d.png)

**Comment by huixisheng** [comment]
@q313729286  可以尝试在QA的服务器上删除`node_modules`，重新安装依赖。多出`344kb`，没有`gzip`的`iview`有`344,699B`。`70+kb`是gzip的，所以打包后台的大小是正常的

**Comment by q27488** [comment]
最近我在vue-cli项目部署线上在IE浏览器下直接白屏，报语法错误，找了很多方法，怀疑到了 npm run build中的 iview打包出错，看上面各位Gay友的回复，就更确定了： iview按需引入导致iview的组件为能将es6打包成es5导致， 那么问题来了，该怎么解决！！？

**Comment by q27488** [comment]
**承接上一个问题，如何解决：**
**首先问题**：
用了 iview UI库，但是是按需加载的，然后默认的vue-cli无法对 按需加载的iview的js库进行 babel语法转意。 所以一到低版本浏览器就白屏（报语法错误）  
解决方法如官网所示：

```
module: {
    rules: [
        { test: /iview.src.*?js$/, loader: 'babel' },
        { test: /\.js$/, loader: 'babel', exclude: /node_modules/ }
    ]
}
```
但这个官网用的babel现在的已经不支持，应该用这个：
```
//使用iview部分插件
      { test: /iview.src.*?js$/, loader: 'babel-loader' },
      { test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ }
```
