### ISSUE TITLE
table中的数据重新赋值之后，排序和筛选都被重置

### ISSUE THREAD

**Issue by codeskyblue** [iview/iview#128]
虽然数据更新了，但是还是希望排序和筛选都能保留下来。

**Comment by icarusion** [comment]
改变data，是保留过滤和排序状态的，你写个在线demo看一下

**Comment by docikaci** [comment]
@icarusion  点击筛选某一项后， 在页面最上面有个搜索（全局）  怎么重置表格的筛选呢？ 谢谢

**Comment by sunyizhe** [comment]
@icarusion 请问清空Table筛选的方法是什么？

**Comment by sunyizhe** [comment]
@docikaci 我调用了table.handleFilterReset(1)
