### ISSUE TITLE
Modal中Table 里render里绑定的方法报Property or method "XXX" is not defined

### ISSUE THREAD

**Issue by guanly** [iview/iview#1280]
### iView 版本号
 2.0.0-rc.8 

### 操作系统/浏览器 版本号
windows/Chrome 56 

### Vue 版本号
 2.2.6 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/guanly/pen/gReEQq

### 问题现象，以及你期望的结果是怎样的?
点击 打开Modal  在模态框里点击 测试按钮，应该弹出alert，实际控制台报错：
[Vue warn]: Property or method "testFunc" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by huixisheng** [comment]
修改后的demo https://codepen.io/huixisheng/pen/EXEMJv。
官网`Table`的`render`有明确的说明文档 https://www.iviewui.com/components/table#自定义列模板：

> 通过给 columns 数据的项，设置一个函数 render，可以自定义渲染当前列，包括渲染自定义组件，它基于 Vue 的 Render 函数。
render 函数传入两个参数，第一个是 h，第二个是对象，包含 row、column 和 index，分别指当前单元格数据，当前列数据，当前是第几行。

> **以下只适用于 rc.13 以前的版本，未来将废弃，请勿过多依赖旧用法。**
旧用法必须设置 context 。
render 函数本质返回的是字符串，Table 组件在内部对其进行了编译，如果使用了自定义组件，需要特别注意上下文，编译后的自定义组件，默认的上下文是 Table 所在的上下文，如果想让组件在指定的实例下编译，可以给 Table 设置属性 context 来指定上下文，比如本例指定当前路由页为上下文。一般情况不需要此配置，但如果你把 Table 作为一个 slot 封装在其它组件里，这时 context 属性就很有用，比如父级是 $parent，根组件 $root。

**Comment by guanly** [comment]
@huixisheng 好的，了解了，不过你这demo打不开哦
