### ISSUE TITLE
Table组件的highlight-row属性疑惑 

### ISSUE THREAD

**Issue by wingyiu** [iview/iview#1284]
2.0.0 rc18
highlightRow到底是高亮选中呢？还是控制单选呢？

在有checkbox列时，测试结果是两种效果都没有。

个人建议高亮和控制单复选还是分开两个属性比较好

**Comment by icarusion** [comment]
仔细看文档

**Comment by wingyiu** [comment]
highlight“即单选”，呵呵

**Comment by wingyiu** [comment]
我想问，再有checkbox列的情况下，怎么控制只能单选？
