### ISSUE TITLE
Select 远程搜索  给v-model动态赋值后 Option选中但Select并未显示出来选中的值

### ISSUE THREAD

**Issue by Blackloser** [iview/iview#1286]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Windows10/Chrome 56

### Vue 版本号
 2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/Blackloser/pen/PjePwR

### 问题现象，以及你期望的结果是怎样的?
![selecto](https://user-images.githubusercontent.com/26319882/27789255-63d1c674-601e-11e7-9a79-08336ce8f1f4.png)
![selectt](https://user-images.githubusercontent.com/26319882/27789256-63d25fbc-601e-11e7-9435-a07ecf2ec952.png)

### 你估计可能的原因是什么（选填）？
没有根据赋值的v-model去动态刷新节点

**Comment by Blackloser** [comment]
@icarusion

**Comment by docikaci** [comment]
同求

**Comment by YikaJ** [comment]
同样的问题，希望能解决

**Comment by duandun** [comment]
同求

**Comment by weeuwee** [comment]
同求

**Comment by Blackloser** [comment]
@icarusion 望解决

**Comment by icarusion** [comment]
using `label` in next iView version

**Comment by chaegumi** [comment]
同https://github.com/iview/iview/issues/1637 解决

**Comment by shiwuhao** [comment]
@blacklisten 能否详细说下如何解决的 我添加了 label还是没有效果

**Comment by alonesmall** [comment]
@blacklisten  帮忙说一下具体的解决办法吧，我也是添加了label没有任何效果。
