### ISSUE TITLE
select下拉框联动 只有一个option时候会出现选项出现问题

### ISSUE THREAD

**Issue by Tangjianren** [iview/iview#1287]
### iView 版本号
2.0.0-rc.17 

### 操作系统/浏览器 版本号
macOS/Chrome 59

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/eRrdeG#anon-login

### 复现步骤
选择第一个下拉框的谷物再选择第二个下拉框的大米却显示的是香蕉
下拉框联动如果下拉框只有一个选项，选项与select上的文字不对应
### 问题现象，以及你期望的结果是怎样的?
我希望解决bug

**Comment by Blackloser** [comment]
你可以把value绑定成唯一的试试  所有的select的value都不重复  不然你就手动去清空之前已经绑定上的value

**Comment by Tangjianren** [comment]
这是我在项目中会遇到的我手动清空了之后还是会出现同样的问题。而我在项目中的value必须要重复，我的解决办法是给option中添加一个display:none的的option的就行了

**Comment by icarusion** [comment]
Update to the latest version and set correct `key`. If there is any problem, please open another issue.
