### ISSUE TITLE
iview upload组件，一次选择多个文件上传，却只有一次success回调

### ISSUE THREAD

**Issue by doopcl** [iview/iview#1288]
### iView 版本号
2.0.0-rc.18

### 操作系统/浏览器 版本号
macOS/Chrome 56

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
暂无示例

### 复现步骤
前提，使用upload组件，设置了mutiple模式，设置on-success , on-progress 并监听其回调
1，点击上传文件按钮
2，选择多个文件并上传
3，检测文件上传及成功时的回调

### 问题现象，以及你期望的结果是怎样的?
文件可以正常上传到服务器上，服务端上传接口也正确返回了200 ok，但是前端组件只接收到了一次on-success回调并正确处理，其他任务虽然成功，在回调的fileList中可以看到，percentage=100，但是showProgress始终为true，file.response也不存在。按说应该每个文件上传成功之后都应该触发回调

**Comment by qq447665722** [comment]
遇到同样问题

**Comment by rijn** [comment]
could you plz provide an online jsfiddle.

**Comment by gniria** [comment]
@doopcl, 跟你同样的版本，也遇到这个问题，原因略显蛋疼，因为我是上传图片，需要提供预览，所以定义个一个数组uploadList方便遍历，并将该数组和this.$refs.upload.fileList绑定，同时上传多张图片时也是出现同样的问题，对比了一下官方示例，发现我把Upload的参数default-file-list="uploadList"， 把该参数的值指向其它数组之后就好了，翻了下源码发现 src/components/upload/upload.vue有这么一段：
`
watch: {
            defaultFileList: {
                immediate: true,
                handler(fileList) {
                    this.fileList = fileList.map(item => {
                        item.status = 'finished';
                        item.percentage = 100;
                        item.uid = Date.now() + this.tempIndex++;
                        return item;
                    });
                }
            }
        },
`
所以问题来了。。。，这里动态监听了default-file-list的值，由于第一个上传完毕后触发onSuccess，导致fileList被更新，与之绑定的upLoadList也被更新，而uploadList绑定到defaultFileList，然后fileList后面的数据就被覆盖了。

**Comment by p2ng** [comment]
目前在2.8.0还存在如题问题。
上传多张图片，除了第一张之后的都会有这个报错。
```
Uncaught TypeError: Cannot set property 'percentage' of null
    at VueComponent.handleProgress (iview.js?4b49:34142)
    at VueComponent.boundFn [as handleProgress] (vue.esm.js?5425:189)
    at Object.onProgress (iview.js?4b49:34107)
    at XMLHttpRequestUpload.progress (iview.js?4b49:34419)
```

简单看了下源码，是this.getFile(file);的时候，返回为null。但是file里面的对象是正确的。 
```
        handleProgress: function handleProgress(e, file) {
            var _file = this.getFile(file);
            this.onProgress(e, _file, this.fileList);
            _file.percentage = e.percent || 0;
        },
```

**Comment by coderew** [comment]
我也碰到同样的问题，看issue的时间，是去年提的，到现在还没有解决。。。

**Comment by 18832057259** [comment]
您好，请问这个问题是如何解决的呢？在线等，谢谢

**Comment by ghost** [comment]
一样的问题。有解决办法么？各位亲

**Comment by guowangsheng** [comment]
gniria 的作法就可以了，default-file-list绑定一个无关的数组，在on-success里面可以看到filelist 处理自己的业务。我的版本是2.14.2

**Comment by tian7503067** [comment]
人人框架图片批量上传插件 可正常批量上传
<template>
  <div>
    <el-upload :action="$http.adornUrl(`/sys/oss/upload?token=${this.$cookie.get('token')}`)"
               :multiple="multiple" :on-change="handleChange" list-type="picture-card" :before-upload="handleBeforeUpload" 
               :on-preview="handlePreview" :on-remove="handleBeforeRemove" :data="imagesData" :accept="accept" 
               :on-success="handleSuccess" :on-error="handleError" :file-list="lisd" :class="`img-upload-${size}`" 
               :limit="limit" :on-exceed="handleExceed">
      <i class="el-icon-plus"></i>
    </el-upload>
    <el-dialog :visible.sync="dialogVisible" :width="imagesData.width+50+'px'" :center="true">
      <img :width="imagesData.width" :src="dialogImageUrl" alt="">
    </el-dialog>
  </div>
</template>
<script>
export default {
  data() {
    return {
      lis: 0,
      lisd: [],
      kes: '',
      accept: 'image/*',
      imagesData: {
        width: 400,
        height: 400,
        token: this.$cookie.get('token')
      },
      dialogImageUrl: '',
      dialogVisible: false
    }
  },
  props: ['value', 'size', 'limit', 'multiple'],
  computed: {
    fileList: function() {
      if (Array.isArray(this.value)) {
        var result = this.value.map(function(value, index, array) {
          alert("1")
          return {
            url: value
          }
        })
        return result
      } else {
        return [
          {
            url: value
          }
        ]
      }
    }
  },
  watch:{
    value (val) {
      if (Array.isArray(val)) {
        var result = val.map(function(value, index, array){
          return {
            url: value
          }
        })
        if(result.length != 0 && this.lis === 0){
          var tis = this
          tis.lisd = []
          result.forEach(function(valt,indt){
            tis.lisd.push(valt)
          })  
          console.log(this.lisd)
        }
      } else {
        this.lisd = val
      }
    }
  },
  mounted() {
  },
  methods: {
    init() {
      let size = this.size.split('x')
      this.imagesData.width = parseInt(size[0])
      this.imagesData.height = parseInt(size[1])
    },
    handleChange(file, fileList) {
      this.lis = 1
    },
    handleBeforeUpload(file) {
      if (
        file.type !== 'image/jpg' &&
        file.type !== 'image/jpeg' &&
        file.type !== 'image/png' &&
        file.type !== 'image/gif'
      ) {
        this.$message.error('只支持jpg、png、gif格式的图片！')
        return false
      }
    },
    handleBeforeRemove(file, fileList) {
      this.$emit('input', this.getValue(fileList))
    },
    handlePreview(file) {
      this.dialogImageUrl = file.url
      this.dialogVisible = true
    },
    handleSuccess(response, file, fileList) {
      const index = fileList.indexOf(file)
      if (response.code !== 0) {
        this.fileList.splice(index, 1)
        this.$message.error(response.msg)
      } else {
        fileList[index].url = response.url
        this.$nextTick(() => {
          this.lis = 0
          // alert(this.lis)
        })
        this.$emit('input', this.getValue(fileList))
      }
      
    },
    getValue(fileList) {
      return fileList.map(function(value, index, array) {
        return value.url
      })
    },
    handleError(err, file, fileList) {
      this.fileList.splice(fileList.indexOf(file), 1)
      this.$message.error('上传失败')
    },
    handleExceed(files, fileList) {
      this.$message.error(`图片最多上传${this.limit}张`)
    }
  },
  created() {
    this.init()
  }
}
</script>
<style>
.img-upload-400x400 .el-upload-list__item {
  width: 148px;
  height: 148px;
}
.img-upload-400x400 .el-upload--picture-card {
  width: 148px;
  height: 148px;
}
.img-upload-400x200 .el-upload-list__item {
  width: 296px;
  height: 148px;
}
.img-upload-400x200 .el-upload--picture-card {
  width: 296px;
  height: 148px;
}
.img-upload-400x160 .el-upload-list__item {
  width: 370px;
  height: 148px;
}
.img-upload-400x160 .el-upload--picture-card {
  width: 370px;
  height: 148px;
}
</style>

**Comment by zhangwei1011** [comment]
> gniria 的作法就可以了，批量上传后，push进另外一个数组，还是会报Cannot set property 'percentage' of null，大佬能看下具体代码吗

**Comment by hcdyl** [comment]
2021年了 Cannot set property 'percentage' of null还是有这个毛病

**Comment by sinhang** [comment]
使用两个上传组件：
`<div class="seller-upload-images">
        <el-upload
            class="avatar-uploader content-uploader content-uploader-show"
            :on-remove="handlerUploadRemove"
            :file-list="images"
            :action="upload_url"
            list-type="picture-card">
        </el-upload>
        <el-upload
            class="avatar-uploader content-uploader"
            style="display: inline-block"
            :file-list="imageList"
            list-type="picture-card"
            :action="upload_url"
            :data="{token: upload_token}"
            :show-file-list="false"
            :on-remove="handlerUploadRemove"
            :on-error="uploadError"
            :on-success="handleUploadSuccess"
            :limit="limit"
            multiple
            :before-upload="beforeUploadUpload">
            <i class="el-icon-plus content-uploader-icon"></i>
        </el-upload>
    </div>`
第一个用于展示，第二个用于上传。
在上传成功回调的时候做一下去重处理即可：
`handleUploadSuccess(val) {
                let append = true
                for (let i in this.images) {
                    if (this.images[i].name == val.hash) {
                        append = false
                        break
                    }
                }
                if (append) {
                    var image = {
                        name: val.hash,
                        url: `${process.env.VUE_APP_IMAGES_BASE_URL}${val.hash}`
                    }
                    this.$emit("setImage", image)
                }
            }`

效果如下：
![image](https://user-images.githubusercontent.com/8141859/181866163-86f02d3f-acbe-4cbe-a8aa-ef0cfd1f6eb1.png)

**Comment by hcdyl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
