### ISSUE TITLE
tbale在窗口缩放之后重新计算宽度

### ISSUE THREAD

**Issue by c5ms** [iview/iview#1289]
### iView 版本号

2.0.0-rc.18 
### 操作系统/浏览器 版本号

windows/chrome59  windows/firefox54
### Vue 版本号

2.2.1
### 复现步骤
table表格在窗口缩小之后不能重新计算宽度.导致页面变形.

### 问题现象，以及你期望的结果是怎样的?
tbale在窗口缩放之后重新计算宽度.

**Comment by daigaobin** [comment]
这个需要自己触发resize事件 更改表格的height的值就可以实现啦

**Comment by icarusion** [comment]
Future optimization is planned.
