### ISSUE TITLE
Table 表格组件，如果左右菜单有折叠效果，会有样式问题

### ISSUE THREAD

**Issue by QinFeiFei** [iview/iview#1292]
### iView 版本号
2.0.0-rc.18

### Vue 版本号
2.2.1

Table   @@表格组件有样式问题，我后台是仿阿里云，做了左侧菜单的折叠效果。但是折叠后，Table出现空白，如下

![tim 20170704203142](https://user-images.githubusercontent.com/19926579/27830293-5415d9b6-60f8-11e7-9f9c-64b8b1477155.png)

**Comment by dean5277** [comment]
这个问题普遍存在。已经有很多issues了

**Comment by shixuev5** [comment]
还有一个设定表格宽度后，当没有数据时，表头最后一列宽度显示不正确的问题。

**Comment by komaedaXnagito** [comment]
同上

**Comment by icarusion** [comment]
这是因为你的列总宽度不够导致的吧。
