### ISSUE TITLE
Select 组件选中项目不能切换语言

### ISSUE THREAD

**Issue by brandonccx** [iview/iview#1293]
### iView 版本号
2.0.0-rc.12 

### 操作系统/浏览器 版本号
macOS/Chrome 59

### Vue 版本号
2.2.3

### 复现步骤
1. 按官方文档配置好i18n和iview
2. 调用Page组件，开启show-sizer
3. 切换语言

### 问题现象，以及你期望的结果是怎样的?
Page组件的sizer select的input中的选中值不能切换语言，
希望和Drop options中一样能切换语言，如中英切换：10 页/条 -> 10 /page

### 你估计可能的原因是什么（选填）？
https://github.com/iview/iview/blob/2.0/src/components/select/select.vue#L259

vue devtool中发现select组件的options属性中的label值没有随语言变化。如图：

![bug](https://user-images.githubusercontent.com/6195470/27833783-bd449266-6106-11e7-8d71-24c6ea2166e0.png)

**Comment by icarusion** [comment]
https://www.iviewui.com/components/page-en
文档并没有问题

**Comment by lihongxun945** [comment]
@icarusion  我确定是有BUG的，当页面加载完成之后，动态修改 `i18n.locale`，发现 翻页组件中选中的条目并不会改变语言

**Comment by bogerv** [comment]
![question](https://user-images.githubusercontent.com/22518653/31043835-9032824a-a5f5-11e7-94e0-d2ac0717f066.gif)
同样的问题, 除非重新加载页面

**Comment by otaku1951** [comment]
@icarusion 问题别关了，我也遇到分页如 @bogerv 说的了，你发的那个链接是因为你刷新页面重新设置vue.config.lang了，除了这个就没辙了么？555555555555

**Comment by SergioCrisostomo** [comment]
Please provide a example so we can see the problem.

**Comment by icarusion** [comment]
谁没事一直点切换语言啊，选完长期就不会变了，所以刷新并没有什么问题。
