### ISSUE TITLE
分页组件不显示电梯，如何用代码切换到某一页

### ISSUE THREAD

**Issue by wangzy123** [iview/iview#1297]
### 问题现象，以及你期望的结果是怎样的?
分页组件给current绑定一个变量，代码中修改这个变量后页码不跳转

### 你估计可能的原因是什么（选填）？
没有监听current的值去调用页码变化的回调函数

**Comment by rijn** [comment]
[https://github.com/iview/iview/blob/2.0/src/components/page/page.vue#L138](https://github.com/iview/iview/blob/2.0/src/components/page/page.vue#L138)

**Comment by itpretty** [comment]
@wangzy123 直接更改 vm 中 currentPage 属性的值即可

**Comment by Tang-Ni** [comment]
@itpretty 怎么拿到page组件下的currentPage
