### ISSUE TITLE
关于单页面路由去掉#，重新刷新时能访问

### ISSUE THREAD

**Issue by weiluxia1988** [iview/iview#13]
正常情况下，通过设置history为true，可以去掉#，页面重新刷新时会出现Cannot GET /exercises/types错误提示。
我看到你们的官网也是单页面路由，但是没有#，而且刷新也没有报错，所以想问下，你们是如何做处理的？

**Comment by icarusion** [comment]
后端配置路由，都指向同一个文件

**Comment by weiluxia1988** [comment]
然后前端再根据地址，手动路由跳转，是吧？

**Comment by icarusion** [comment]
vue-router

**Comment by weiluxia1988** [comment]
是用vue-router，不需要是用router的接口go方法去跳转吗？

**Comment by icarusion** [comment]
不用

**Comment by weiluxia1988** [comment]
好的，谢谢你
