### ISSUE TITLE
Cascader 组件在使用时候通过Vuex的commit更改value,页面上显示的值不刷新

### ISSUE THREAD

**Issue by fsl1001** [iview/iview#130]
### iView 版本号
 0.9.9-rc-5

### 操作系统/浏览器 版本号
macOS/Chrome 54

### Vue 版本号
1.0.26
### vuex 
 2.0.0 

### 复现步骤
1.初始化
2.在下拉菜单选择值
3.通过vuex commit 方法修改value 值
4.页面显示的值没有变，但是通过{{}}获取的是修改后的值
### 问题现象，以及你期望的结果是怎样的?
页面显示的是最新的选择的值

**Comment by icarusion** [comment]
value有使用.sync吗？
iview先升级到最新版

**Comment by fsl1001** [comment]
刚升到了 0.9.10 问题依然存在 
使用了 .sync 
我再源码里 watch 了下value  然后 this.updateSelected();

**Comment by icarusion** [comment]
你先不用 vuex，普通方法尝试是否有效

**Comment by fsl1001** [comment]
额  不用vuex 确实能解决这个问题 但是。。。

**Comment by fsl1001** [comment]
看错了 是依然不行 不加watch的话

**Comment by icarusion** [comment]
写一个在线demo发来看下

**Comment by icarusion** [comment]
确实有此问题，改变value，不会立即更新，点击一下才会更新。
感谢，正在修复
