### ISSUE TITLE
<Date-picker type="datetimerange" />清除时间之后，时间由默认的00:00:00变成了current时间

### ISSUE THREAD

**Issue by lizziejc** [iview/iview#1301]
### iView 版本号
2.0.0-rc.5 

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例
https://www.iviewui.com/components/date-picker

### 复现步骤
1. 选择日期，时间默认为所选时间当天的00:00:00
2. 点击清除按钮或者输入框内的（X）
3. 再次选择日期，时间默认为当前时间，比如14:01:03

### 问题现象，以及你期望的结果是怎样的?
清除日期操作，应该不会引起时间默认值的改变，即，只选择日期的情况下，时间默认值应为00:00:00

### 你估计可能的原因是什么（选填）？
清除操作影响了 datePicker 的默认值

**Comment by JD-Wang** [comment]
@icarusion 确实有这个隐秘的bug，造成了一个线上查询出错，希望能fix
