### ISSUE TITLE
【table组件】是否可以增加重置筛选条件的方法？

### ISSUE THREAD

**Issue by docikaci** [iview/iview#1305]
需求是这样的：
点击表头的筛选某一项后， 在页面最上面有个搜索（全局）， 怎么重置表格的筛选呢？ 谢谢

**Comment by docikaci** [comment]
![image](https://user-images.githubusercontent.com/7788102/27939607-a6482a5c-62f8-11e7-9357-b28d536789d6.png)

**Comment by icarusion** [comment]
Read doc.

**Comment by docikaci** [comment]
@icarusion 文档没有找到对应的方法，才来这里问下呢  直接关了呀？

**Comment by sunyizhe** [comment]
@docikaci 我也遇到相同问题，请问问题解决了吗？

**Comment by sunyizhe** [comment]
@docikaci 看了下源码，我采用这样的方法table.handleFilterReset(1)
