### ISSUE TITLE
Select在Modal弹窗中错位问题（有例子）

### ISSUE THREAD

**Issue by areyouse7en** [iview/iview#1306]
### iView 版本号
2.0.0-rc.18

### 操作系统/浏览器 版本号
win10/Chrome 59

### Vue 版本号
2.3.4

### 能够复现问题的在线示例
https://codepen.io/anon/pen/owPbQE

### 复现步骤
点击show modal
随便输入什么，下拉框出现，随便选一个，然后点取消，弹框关闭
再点show modal
再随便输点什么

### 问题现象，以及你期望的结果是怎样的?
这时候下拉框内容跑到页面左边去了，错位了。
不使用clearable的时候没问题，因为这里想要在弹框消失的时候重置掉表单项，select没有办法通过resetForm重置，只能用clear。

### 你估计可能的原因是什么？
下拉框内容并没有清空

#### 1.remote模式下的select也能支持click事件
有场景需要我第一次点击还没有输内容的时候就进行第一次搜索并出现下拉内容。

#### 2.Select能否支持懒加载
即便是remote，有时候result也很多，上百条的乃至更多，全部显示显然不太好。
最好能滚一点加载一点

**Comment by icarusion** [comment]
已知问题

**Comment by areyouse7en** [comment]
那是已解决还是？ 下一版rc19发布？

**Comment by icarusion** [comment]
没解决

**Comment by areyouse7en** [comment]
我估计是select的清空动作，又触发了一遍Option里poper的实例化，同时Modal消失，导致poper的定位出现了问题，而poper实例仍旧存在，下一次Modal再显示，点击select的时候，直接触发了poper的update，而不是new。

不改变源码的解决方案是，在modal的oncancel事件里，加个setTimeout
```javascript
resetForm() {
      setTimeout(()=> {
        this.$refs["formSelect"].clearSingleSelect();
        this.options = [];
       }, 300)  
    }
```

**Comment by icarusion** [comment]
#1099

**Comment by justnowanna** [comment]
同楼上，也遇到这个问题。最简单的办法是在select组件上使用v-if，每次都重新渲染，可以解决。
另外page的分页也有个问题，current设置不生效的问题，不知道有没有人遇到过
