### ISSUE TITLE
overflow:hidden + position:relative 元素内的dropdown无法全部显示

### ISSUE THREAD

**Issue by xszh** [iview/iview#1308]
### iView 版本号
2.0.0-rc.18

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2+

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/qjMRRe

### 复现步骤
点击select控件

### 问题现象，以及你期望的结果是怎样的?
dropdown无法全部显示，希望能popup出来

### 你估计可能的原因是什么（选填）？
overflow:hidden+position:relative元素会使内部absolute元素被overflow:hidden裁剪

### 建议
将popover放在body里而非父节点内：
/src/components/select/dropdown.vue：update方法内
在new Popper(...)后执行：
document.body.appendChild(this.$el)
最后在beforeDestroy内remove掉就行
可能会有未知影响

**Comment by ihuguowei** [comment]
我建议您可以把 dropdown 做绝对定位展示，也能实现你的需求，无需修改 `iview`代码。

**Comment by xszh** [comment]
@ihuguowei 谢谢，请问如何把dropdown做绝对定位展示？看了下文档内没有找到=。=

**Comment by ihuguowei** [comment]
@xszh 这个是 `CSS`基础啦，主要是你父元素`overflow:hidden`，自然你内部子元素超出部分就无法展示了。
