### ISSUE TITLE
关于Dropdown有两个子集时的显示Bug

### ISSUE THREAD

**Issue by oicuivu** [iview/iview#1311]
### iview版本
http://unpkg.com/iview/dist/iview.min.js

### 操作系统/浏览器 版本号
 win7/58.0.3029.14 (64-bit) 

### Vue 版本号
v2.3.0

### 复现步骤
1.给Dropdown添加多个Item
2.其中有两个Item有子项
3.并且这两个有子项的Item先后排序
4.显示列表时发现整个列表的宽度增加很多，如果将带有子项的列表分割开来排序，则显示正常

### 问题现象，以及你期望的结果是怎样的?
希望列表宽度自适应

### 可能原因
通过检查元素，可以看到.ivu-dropdown的属性为display:inline-block，而子项也会应用这个样式。
最后同过覆盖样式解决.ivu-dropdown .ivu-dropdown{display:block}

**Comment by icarusion** [comment]
provide online code
