### ISSUE TITLE
Nuxt.js and iview

### ISSUE THREAD

**Issue by StasB93R** [iview/iview#1315]
I was just wondering if you can make iview work for nuxt.js?on your website it says SSR supported, and nuxt becoming more the largest framework for vue to make SSR
Do yo have any plans on doing this? nuxt.js is growing pretty fast, at the end of this month they will release a new vasersion that is more stable. I like iview i think its one of the best design tool, but i cant use it for nuxt.js ;(( so was hpping to get some feedback

**Comment by rijn** [comment]
We do not have that plan yet. I don't know too much about nuxt.js. We need to have a discussion about this. @icarusion

**Comment by StasB93R** [comment]
its fast growing thing, and more and more people will start using it overtime. Your framework is really really good and at some point more people will ask that question. I have opened similar issue on nuxt.js github https://github.com/nuxt/nuxt.js/issues/1049 as well as on vuejs forum https://forum.vuejs.org/t/iview-in-nuxt-js/14024/4 

At one point Evan You spoke about your framework as well as he spoke about nuxt.js. The tendency that we see is that people will tend to use it more and more. So would be really nice to get it working together.

**Comment by uptownhr** [comment]
@StasB93R `I was just wondering if you can make iview work for nuxt.js`, i believe it is up to the library maintainers to be make their lib SSR friendly. There is no way nuxt can handle this for all possible libraries out there.

**Comment by uptownhr** [comment]
There might be others but here's an example of a component that is not SSR friendly in iview, https://github.com/iview/iview/blob/2.0/src/components/loading-bar/loading-bar.js

**Comment by icarusion** [comment]
@StasB93R Thanks for your suggestion. This is my fault that say iView support SSR, it just support `runtime`, some problem have been plane to resolve. We will support Nuxt.js finally

**Comment by icarusion** [comment]
We plane to support SSR and Nuxt.js in 2.0.0-rc.19 version.

**Comment by uptownhr** [comment]
Hmm sorry guys. Completely misunderstood this ticket. Didn't even realize this was the iview repo

**Comment by icarusion** [comment]
Hi, @StasB93R I just push a commit https://github.com/iview/iview/commit/a68c11a56566bcfdc5fd669997f640aa644a74c0 and it can run with Nuxt.js now, can you have time to test deeply, because I haven't used Nuxt.js before.

[download iview file to replace node_modules/iview/dist]

http://7u2ka3.com1.z0.glb.clouddn.com/ssr/iview.js
http://7u2ka3.com1.z0.glb.clouddn.com/ssr/iview.min.js

**Comment by icarusion** [comment]
#1339
