### ISSUE TITLE
menu 的on-select点击的时候不触发

### ISSUE THREAD

**Issue by webKity** [iview/iview#1317]
### iView 版本号
2.0.0-rc.18

### 操作系统/浏览器 版本号
window7/Chrome 58

### Vue 版本号
vue 2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/anon/pen/mwzNRm

### 复现步骤
点击菜单按钮，但是不会触发on-select事件

**Comment by rijn** [comment]
`on-select` is a event of `Menu` not `Menu-Item`

**Comment by webKity** [comment]
think you！

**Comment by thuanystuart** [comment]
Thank you! This saved me some time.
