### ISSUE TITLE
Modal组件如何去除两条线，我需要自定内容；或者$modal实例化的时候我可以控制其跳出的位置？

### ISSUE THREAD

**Issue by xumiaojun** [iview/iview#1319]
### 问题现象，以及你期望的结果是怎样的?

Modal组件如何去除两条线，我需要自定内容；或者$modal实例化的时候我可以控制其跳出的位置？
如何让iview的Modal 像element的Dialog一样，可以用户内容自定义？很多情况下是不需要横线的！
$modal实例化，没有属性可以调整它的位置！

**Comment by rijn** [comment]
Removing `header` can drop the upper line. But the lower line can only be removed by overriding the default style.
