### ISSUE TITLE
Upload组件相对element的组件少一个属性auto-upload，暂存的手动上传,并不清楚iview是否能实现手动上传，或者可以手动上传API中对此没有任何解释

### ISSUE THREAD

**Issue by xumiaojun** [iview/iview#1320]
### 问题现象，以及你期望的结果是怎样的?

Upload组件相对element的组件少一个属性auto-upload，暂存的手动上传,并不清楚iview是否能实现手动上传，或者可以手动上传API却中对此没有任何解释

**Comment by rijn** [comment]
Return `false` in `before-upload`.

**Comment by rijn** [comment]
We do not have a method to trigger `upload` yet.
