### ISSUE TITLE
select 选择选项为空字符时显示逻辑不正常

### ISSUE THREAD

**Issue by lpreterite** [iview/iview#1321]
### iView 版本号

2.0.0-rc.18

### 操作系统/浏览器 版本号

随意

### Vue 版本号

2.3.2

### 复现步骤
1. 选项值为空字符
2. 已选择值为空字符的选项

### 问题现象，以及你期望的结果是怎样的?
选择了选项为空字符也应当在已选框中显示选项的内容

### 你估计可能的原因是什么（选填）？
`computed` showPlaceholder 应该先判断存是否为已选择状态下再作后续判断。

**Comment by SergioCrisostomo** [comment]
@lpreterite could you add a example to reproduce this problem?

使用下面的在线链接可以快速创建示例
https://codepen.io/anon/pen/KvJJdw

**Comment by icarusion** [comment]
Why empty
