### ISSUE TITLE
Table组件的数据传递问题

### ISSUE THREAD

**Issue by wangweida** [iview/iview#1323]
### Vue 版本号

table组件中选中某一行传递当前行数据时，所有的数据都是深拷贝过来的。这样我要修改某一行其中的一些数据的话就要去遍历一遍寻找到原数据找到那一项后再去更改，很麻烦，而且性能还低，不知道为什么要这样，感觉传递一个index就够了，这样不管是拿到数据展示还是修改都没什么问题

**Comment by xcodebin** [comment]
作者深拷贝是为了给所有数据添加_checked,_disabled这种数据，并且还要不影响外部数据。但是其实这么写确实用起来挺难受的

**Comment by wangweida** [comment]
你说的对，我没考虑到这点，但就是这样也可以传递一个index啊，并不影响给数据添加_checked。我现在遇到的麻烦的是初始某一行有_highlight这个属性，我点击某一行高亮然后修改那行属性整个列表就重新渲染了，然后当前选中的高亮的行就又跑到默认行去了。所以我现在只能点击的时候先把原先行数据中的_highlight删了，然后再向当前行中加上_hightlight这个属性，这样要循环两遍，数据量一大就卡了

**Comment by starrysky90** [comment]
也遇到同样的问题
