### ISSUE TITLE
能否在iView的datepicker组件中添加多选日期的type？

### ISSUE THREAD

**Issue by shoyuf** [iview/iview#1324]
### iView 版本号

2.0.0

类似插件kalendae.js的multiple mode

**Comment by YikaJ** [comment]
这个我觉得是小众需求，我觉得你可以把现在 iview 从 node_modules 拖出来，自行在 Datepicker 实现比较好。

**Comment by Neo-J** [comment]
感觉这个并不小众，现实业务中应该有不少需要选择多个指定日期的那种需求

**Comment by icarusion** [comment]
赞无此计划
