### ISSUE TITLE
在IE9中tabs的面板中的内容会同时显示出来，建议IE9强制设置animated为false

### ISSUE THREAD

**Issue by webKity** [iview/iview#1325]
### iView 版本号

2.0.0-rc.18

### 操作系统/浏览器 版本号

window 7/IE 9

### Vue 版本号

2.3.3

### 问题现象，以及你期望的结果是怎样的?
问题：在IE9中tabs如果选择使用动画面板中的内容会同时显示出来
建议：建议IE9强制设置animated为false，因为关闭动画后面板的显示是正确的

**Comment by icarusion** [comment]
未来将不支持 ie9
