### ISSUE TITLE
Date-picker获取时间后是：2017-07-10T16:00:00.000Z，后面多了一串T16:00:00.000Z

### ISSUE THREAD

**Issue by ttflowerboys** [iview/iview#1326]
### 当我使用`Date-picker`选择日期：2017-07-11
![image](https://user-images.githubusercontent.com/13741211/28059848-169d522a-6658-11e7-90f8-9819e26bb215.png)

### 发送请求时，时间后面多了一串 `T16:00:00.000Z`
![image](https://user-images.githubusercontent.com/13741211/28059945-62a48ee0-6658-11e7-9f0c-4111e146602c.png)

我只想得到单纯的: `2017-07-11`，这个要怎么处理？

**Comment by rijn** [comment]
`toLocateString`

**Comment by icarusion** [comment]
read doc seriously, use `on-change` event

**Comment by ttflowerboys** [comment]
ok,thanks

**Comment by yukidei** [comment]
请问你这个解决了吗

**Comment by guowangsheng** [comment]
同样的问题啊 返回的是UTC日期，很多地方用到，总不能每个地方都用on-change吧
