### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set property '_isHover' of null

### ISSUE THREAD

**Issue by anthonyli** [iview/iview#1328]
### Vue 版本号1.0.21

按需加载了 table组件，在DEV的模式下是不报错的，通过官网提供的 loader build 的时候 就会报错
Uncaught (in promise) TypeError: Cannot set property '_isHover' of null
麻烦帮忙看下 非常急 ，万分感谢。

**Comment by anthonyli** [comment]
import iTable from 'iview/src/components/table';

Vue.component('iTable', iTable);

**Comment by rijn** [comment]
I use table as the following way

```
import Table from 'iview/src/components/table';

export default {
    components: { iTable: Table }
};
```

Could you check your webpack config? Did you add a loader to it?

**Comment by NAN0916** [comment]
2.13.1 table 也出现同样的问题
