### ISSUE TITLE
input-number输入框无法应用rules

### ISSUE THREAD

**Issue by mydaoyuan** [iview/iview#1330]
### iView 版本号
 2.0.0-rc.12 

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/daoyuan/pen/xrmxbY

**Comment by rijn** [comment]
Please read the doc carefully. You need to call `validate` by yourself.

**Comment by mydaoyuan** [comment]
是我组件写的有问题吗，我修改了一下，可以再看看

**Comment by rijn** [comment]
The document has provided a piece of sample code. You must call `validate` method by yourself. It will not be triggered by default.

[Form_methods](https://www.iviewui.com/components/form#Form_methods)

```
        methods: {
            handleSubmit (name) {
                this.$refs[name].validate((valid) => {
                    if (valid) {
                        this.$Message.success('提交成功!');
                    } else {
                        this.$Message.error('表单验证失败!');
                    }
                })
            },
            handleReset (name) {
                this.$refs[name].resetFields();
            }
        }
```
