### ISSUE TITLE
When i close the modal , the value attr of Modal can't change automatic

### ISSUE THREAD

**Issue by percy507** [iview/iview#1335]
@icarusion 

### 版本号

```json
{
    "iview": "^2.0.0-rc.18",
    "vue": "^2.1.10"
}
```
### 

![image](https://user-images.githubusercontent.com/18365078/28108804-5c5f93b4-671f-11e7-8603-b6cd1de5e3cc.png)

![image](https://user-images.githubusercontent.com/18365078/28109264-0a7f5258-6721-11e7-86bc-8633270c228e.png)

![image](https://user-images.githubusercontent.com/18365078/28109548-02e4d2ce-6722-11e7-9b1a-9ef87edec571.png)

**As what  i say , when i click the right-top button to close the modal , while the `value` attr of the Modal component not change to `false` automaticly.**

**Is this is a bug?**

**Comment by icarusion** [comment]
You need add `@on-cancel` in Modal, and set `value` to false **or** using `v-model` like this:
```
<Modal v-model="isShowModel">
```

**Comment by percy507** [comment]
I choose the second method, and it works. 

But it is strange when i use `:value="isShowModel"` and this one not works.  😄

Whatever, the problem has been killed.

**Thanks.**

**Comment by icarusion** [comment]
Read about Vue one-way-data-flow
https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow

**Comment by percy507** [comment]
Thanks so much.

But i think maybe i should also read this one. 😊

https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events
