### ISSUE TITLE
对话框Modal 添加loading=true时 无法控制按钮loading状态

### ISSUE THREAD

**Issue by Estelle00** [iview/iview#1336]
### iView 版本号
2.0.0-rc.18

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号

问题代码 路径：src/components/modal/modal.vue
此文件内第168行起  点击确定按钮执行回调后不还原按钮状态；必须要关闭modal窗口才能还原
```js
ok () {
    if (this.loading) {
       this.buttonLoading = true;
    } else {
       this.visible = false;
       this.$emit('input', false);
    }
    this.$emit('on-ok');
   this.buttonLoading = false;//fix 此处添加按钮状态还原代码修改
 }
```

**Comment by icarusion** [comment]
https://github.com/iview/iview/issues/597#issuecomment-292422473
