### ISSUE TITLE
Talk about SSR and Nuxt.js

### ISSUE THREAD

**Issue by icarusion** [iview/iview#1339]
Here to talk iView support SSR and Nuxt.js.
Now, I tested all component using nuxt.js, it worked. 
Any question of SSR and Nuxt.js can discuss here.

[Download the following two files and replace  node_modules/iview/dist]
https://file.iviewui.com/ssr/v1/iview.js
https://file.iviewui.com/ssr/v1/iview.min.js

https://github.com/iview/iview/issues/1098
https://github.com/iview/iview/commit/a68c11a56566bcfdc5fd669997f640aa644a74c0#commitcomment-23045429

----------
How to use nuxt.js:

nuxt.config.js:
```js
plugins: [
        { src: '~plugins/iview', ssr: true }
]
```
plugins/iview.js:
```js
import Vue from 'vue'
import iView from 'iview'

Vue.use(iView)
import 'iview/dist/styles/iview.css'
```

**Comment by prestanesia** [comment]
It works. thanks.
However , when using the en locale in plugins/iview.js:

```
import Vue from 'vue'
import iView from 'iview'
import locale from 'iview/src/locale/lang/en-US'

Vue.use(iView, { locale })
```

i get this error:

```
Nuxt.js Error:

D:\Projects\iviewui\node_modules\iview\src\locale\lang\en-US.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (D:\Projects\iviewui\node_modules\vue-server-renderer\build.js:5812:16)
    at Object.<anonymous> (webpack:/external "iview/src/locale/lang/en-US":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 28b2d9910241a2df8d1b:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:1719:86)
    at __webpack_require__ (webpack:/webpack/bootstrap 28b2d9910241a2df8d1b:25:0)
    at Object.<anonymous> (.nuxt/index.js:25:14)
    at __webpack_require__ (webpack:/webpack/bootstrap 28b2d9910241a2df8d1b:25:0)
```

set the ssr to false will rid above warning.

```
plugins: [ { src: '~plugins/iview', ssr: false } ],
```

**Comment by Phatza** [comment]
Well done !

Thanks

**Comment by icarusion** [comment]
@prestanesia I tried it for a day but was still unresolved. More detail visit https://github.com/nuxt/nuxt.js/issues/1080

**Comment by StasB93R** [comment]
Is there a work around to make english as a default language for the time being? or somehow tell npm that you are using english version e.g (npm install iview-eng --save). What would i need to do to have something like that?

**Comment by icarusion** [comment]
@StasB93R in next iView version(will release next week), we will build language to support AMD/CMD/CommonJS.

**Comment by StasB93R** [comment]
Is there a way to have options like destroyed(), beforeDestroy() on modals? because im trying to emit an event when modal shuts down and to set a property to false again. I talked about this problem a bit more on vue forum https://forum.vuejs.org/t/problem-with-mutating-prop-noob-question/14359/12
.
Plus it keeps giving this warning about changing props, but everything has already changed in a parent component so quite hard for me to grasp what is causing that warning

**Comment by chenfengjw163** [comment]
部分组件中使用了mounted等生命周期在vuessr中只有beforeCreate和created会在服务端被调用，比如card组件中初始化是否显示head的逻辑就不会被执行，导致服务端渲染出的样式和客户端样式不统一！

**Comment by chenfengjw163** [comment]
另外，在loadingBar实例化代码中仍然出现了document.body.appendChild(component.$el); 这种代码。我用的这个issues中提供的iviewjs和iviewminjs，看来这个版本还是不支持SSR

**Comment by icarusion** [comment]
@chenfengjw163 If you set nuxt config using my code above, it worked.

**Comment by chenfengjw163** [comment]
没有使用nuxt框架哦。按照vue ssr官方文档搭建的ssr。

**Comment by icarusion** [comment]
@chenfengjw163 Can you provide a duplicate repo? 
@lcx960324 Please test using iView 2.0.0-rc.19 and Vue 2.4.1 again

**Comment by icarusion** [comment]
@prestanesia we compile language files to dist, in next version, you can import from `dist`.

**Comment by chenfengjw163** [comment]
@icarusion https://github.com/chenfengjw163/iview-ssr.git 这个仓库，可以复现document is not defined

**Comment by lcx960324** [comment]
Thanks for your feedback. I'll deal with it soon.

**Comment by lcx960324** [comment]
@chenfengjw163 Thank you for your demo code & feedback. I've already targeted the problem that causes rendering error on LoadingBar.  But I didn't see the problem you mentioned about Card in your demo or my demo. Could you provide a more detailed description about the problem? Thx.

**Comment by chenfengjw163** [comment]
@lcx960324  Card在服务端渲染结果和客户端结果不一致。原因是服务端没有执行Card组建的mount周期钩子，导致部分数据状态没有被正确初始化。在我的代码中已经更新了Card的演示，删除掉loadingbar的代码服务端可以正确输出，你可以对比看看服务端渲染的card的dom和客户端渲染的dom差异。

**Comment by lcx960324** [comment]
@chenfengjw163 
I see. In fact they are same. The bug is that there is a delay executing `mounted()` function in server rendered component. So you'll see the header disappears after a slight delay. I've moved the logic into `created` hook and it works. Thx.

**Comment by icarusion** [comment]
@chenfengjw163 It worked that change the `created` to `mounted`.

**Comment by lcx960324** [comment]
@chenfengjw163 
Hello, we've rewritten our test case without Nuxt.js, and we are now sure that components like `LoadingBar` work fine under SSR. Just follow @icarusion 's suggestion to edit your `app.js` and it will works fine.
Our test project repo: https://github.com/iview/iview-ssr-test

**Comment by chenfengjw163** [comment]
thx！
@icarusion 把$Loading.start从created中移到mounted中确实解决问题，因为ssr服务端不会执行mounted自然就不会执行$Loading.start了。如果这样iview的组件就不是完全兼容ssr了。我们开发时使用的iview组件就需要考虑某些组件的方法不能在服务端执行。
@lcx960324 loadingbar参考@icarusion 的建议已经ok，但是card组件头部问题还是没有解决哦。

**Comment by StasB93R** [comment]
while installing iview in nuxt.js i have this "UNMET PEER DEPENDENCY vue@^2.4.1" What is it? is it gonna affect any work?

**Comment by gamebody** [comment]
nuxt中可以按需引用么？
![image](https://user-images.githubusercontent.com/15389880/29019390-d25f1f8c-7b90-11e7-98e7-1d718519b9ad.png)
![image](https://user-images.githubusercontent.com/15389880/29019415-f0f559ca-7b90-11e7-8784-6fb6bf16e420.png)
![image](https://user-images.githubusercontent.com/15389880/29019424-fb6c028c-7b90-11e7-8ae8-182c2ed1d44b.png)
报错了

**Comment by gamebody** [comment]
nuxt如何按需引用呢？

**Comment by shawon1220** [comment]
使用table组件ssr时，使用nuxt-link无刷新跳转没有问题，但是f5手动刷新当前页面出现如下错误：The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by RexkentZheng** [comment]
在Nuxt中按需引用iview，本地运行没有任何问题，但是部署到github_page上出现了没有样式表的情况，这让我很困惑。
iview.js
```
import Vue from 'vue'
import 'iview/dist/styles/iview.css';
import { Layout, Submenu, Menu, MenuItem, Sider, Content, Icon, Button, Input, Message } from 'iview'

if (process.BROWSER_BUILD) {
  require('iview')
}

Vue.component('Layout', Layout);
Vue.component('Menu', Menu);
Vue.component('MenuItem', MenuItem);
Vue.component('Sider', Sider);
Vue.component('Content', Content);
Vue.component('Icon', Icon);
Vue.component('Submenu', Submenu);
Vue.component('Button', Button);
Vue.component('Input', Input);
Vue.component('Message', Message);
```

nuxt.config.js
```
plugins: [
    { src: '~plugins/ui-view', ssr: false}
  ],
 babel: {
      "plugins": [["import", {
        "libraryName": "iview",
        "libraryDirectory": "src/components"
      }]]
    },
vendor: ['axios','lodash','iview'],
```
我的github仓库是：
https://github.com/RexkentZheng/test-nuxt
部署在默认的gh-pages分支上，请帮忙看下，谢谢
