### ISSUE TITLE
select远程搜索组件获取到远程数据后，依然显示 “无匹配数据”

### ISSUE THREAD

**Issue by zhouzgang** [iview/iview#1340]
### iView 版本号

 2.0.0-rc.13

### Vue 版本号

 2.2.6

**Comment by zhouzgang** [comment]
尝试解决中

**Comment by mcxu2333** [comment]
请问这个问题可解决了？

**Comment by mcxu2333** [comment]
问题出 在select 的 loading 属性上
将loading 属性设为 true 远程查询后 再将loading 属性改为 false

**Comment by LiPinghai** [comment]
莫名其妙的，如果remote-method是同步的，还得特地写成异步
