### ISSUE TITLE
table中渲染多个select，点击另外一个select无法收起

### ISSUE THREAD

**Issue by ChaiXiangguo** [iview/iview#1342]
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/smokeMonkey/pen/rmzvLr
### 你估计可能的原因是什么（选填）？
原因我找到了，是table组件添加了click.stop事件，导致clickOutside函数没有触发，但是不知道怎么解决
--

**Comment by wobushirunning** [comment]
我也遇到此BUG，请大神们帮帮忙！在线等，急。

**Comment by ChaiXiangguo** [comment]
这个需要iview的开发者修改一下这个bug

**Comment by Blackloser** [comment]
我也遇见了，有一个不合理的方式  就是暴漏出源码中select展开时的属性。然后在整个页面写判断，每次只能有一个展开。因为表格的td是分行的，所以这个问题解决起来很棘手。还望官方修复。

**Comment by ChaiXiangguo** [comment]
######在npm上还是没有修复 github已经修复了
