### ISSUE TITLE
Tabs标签页的value

### ISSUE THREAD

**Issue by Estelle00** [iview/iview#1344]
### iView 版本号
2.0.0-rc.18

### Vue 版本号
2.3.4
```js
var App = new Vue({
  data:{
      tabs:1
  },
  template: `
    <Tabs type="card" class="tabs" v-model="tabs">
        <Tab-pane :name="1" label="标签一"/>
        <Tab-pane :name="2" label="标签二"/>
    </Tabs>`
});
```

### 复现步骤
当tabs为数字时，控制台会出现警告信息

### 问题现象，以及你期望的结果是怎样的?
干掉警告

### 你估计可能的原因是什么（选填）？
TabPane组件的props中name的type值只写了String 未添加Number

**Comment by rijn** [comment]
I prefer to use `name="1"` instead.
