### ISSUE TITLE
modal中的datepicker在打开的状态下关闭modal，datepicker会出现错位

### ISSUE THREAD

**Issue by dogrod** [iview/iview#1346]
### iView 版本号

2.0.0-rc.18

### 操作系统/浏览器 版本号

macOS 10.12.5
Chrome 61.0.3153

### Vue 版本号

2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

codepen 无法显示modal，下面是我本地代码的精简，在本地能重现问题
```
var App = new Vue({
  template: `
    <Button type="primary" @click="handleClick">显示modal</Button>
    <Modal
        v-model="modal1"
        title="普通的Modal对话框标题">
        <p>对话框内容</p>
        <Date-picker type="daterange" placeholder="选择日期" style="width: 200px"></Date-picker>
    </Modal>
  `,
  data() {
    return {
      modal1: true,
    }
  },
  methods: {
    handleClick() {
      this.modal1 = true
    }
  }
});
App.$mount('#app');
```

### 复现步骤

使用iview的modal组件，并在内部使用datepicker组件。在datepicker弹出后不选择时间直接关闭modal（点击外部区域或点击关闭按钮）

### 问题现象，以及你期望的结果是怎样的?

在modal关闭的过程中，datepicker出现错位，会跳动至屏幕中央
期望datepicker不跳动

### 你估计可能的原因是什么（选填）？

可能为在modal关闭的过程中，datepicker相对定位的元素发生了变化

**Comment by icarusion** [comment]
Use `transfer` prop.
