### ISSUE TITLE
升级了所有package iview 2.0.0-rc.18 # table 有报错信息这是怎么回事呢?

### ISSUE THREAD

**Issue by boss870101** [iview/iview#1347]
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

![image](https://user-images.githubusercontent.com/18266465/28158125-4d000ba2-67eb-11e7-9084-f5390c114925.png)

**Comment by jackzhcai** [comment]
vue2.x v-for的key理想值是每项都有唯一的 id。
把 table-body.vue 中 :key="row"改成 :key="index" 就可解决。

**Comment by icarusion** [comment]
#1353

**Comment by boss870101** [comment]
vue@2.4.1会出现这问题，降为vue@2.3.4这问题就没了，是什么原因呢？

**Comment by icarusion** [comment]
已修复

**Comment by seminelee** [comment]
还是报错 版本号iview@2.0.0-rc.19
