### ISSUE TITLE
<TableBody> 报错，Avoid using non-primitive value as key, use string/number value instead

### ISSUE THREAD

**Issue by zrain** [iview/iview#1350]
iview 版本 2.0-r.18

vue 版本 2.3.4

报错

![image](https://user-images.githubusercontent.com/6274220/28165935-8d7818c4-6808-11e7-86d2-dff3277923e8.png)
![image](https://user-images.githubusercontent.com/6274220/28165965-abb5b06c-6808-11e7-9c48-17d4cb4c4bfe.png)

**Comment by rijn** [comment]
#1347 Could you please close this issue
