### ISSUE TITLE
表格出现大量错误提示 Avoid using non-primitive value as key

### ISSUE THREAD

**Issue by EY5740** [iview/iview#1353]
基于vue.js最新版本，iview表格渲染 出现大量警告提示 
'Avoid using non-primitive value as key,'use string/number value instead.'

提示来源于vue.js 3717 行

> // warn against non-primitive key
>   if (process.env.NODE_ENV !== 'production' &&
>     isDef(data) && isDef(data.key) && !isPrimitive(data.key)
>   ) {
>     warn(
>       'Avoid using non-primitive value as key, ' +
>       'use string/number value instead.',
>       context
>     );
>   }

**Comment by rijn** [comment]
#1347

**Comment by zrain** [comment]
这个 bug 影响翻译比较广，不知道什么时间可以发布新版？ ，或者可以降级到哪个版本可以暂时避免这个问题

**Comment by icarusion** [comment]
下个版本修复，可以先降低vue版本

**Comment by icarusion** [comment]
fixed under Vue 2.4.1.

**Comment by melon** [comment]
更新至iview 2.0.0-rc.19之后，仍旧发现使用Tabs时会报这个错误

**Comment by icarusion** [comment]
@melon provide your code.

**Comment by melon** [comment]
@icarusion 我先自己定位一下问题

**Comment by melon** [comment]
@icarusion 定位到是个人业务代码里使用的问题，请忽略

**Comment by dongyang03** [comment]
请问这个bug fixed了么？

**Comment by niugm** [comment]
这应该不是一个bug，`<Option  :value="item.id" :key="item">{{ item.name }}</Option>`，select组件里，这样使用就会出这个警告，问题在  :key="item" 这里。

解决办法：
` <template v-for="item in xxxx">
        <Option :value="item.id">{{ item.name }}</Option>
   </template>`

**Comment by stanNo1** [comment]
我就想看看 为什么element-ui有这个bug， i-view也报这个bug了

**Comment by rosethorn999** [comment]
```
let stateList= [
        { value: -1, caption: 'locked' },
        { value: 0, caption: 'waiting' },
        { value: 1, caption: 'accected' }
      ]

//before
<option :value="item.value" v-for="item in stateList" v-bind:key="item">{{item.caption}}</option>
//after
<option :value="item.value" v-for="item in stateList" v-bind:key="item.value">{{item.caption}}</option>
```

@niugm You got it, here is my log in my case
The main point is "item of stateList is a object", but vue.js wish you should v-bind:key with string/number.
[ref](https://github.com/vuejs/vue/issues/5804)

**Comment by Five-Chen** [comment]
v-for="(item, index) in XXXX" :key='index' ,就可以了，因为key只认 number／string

**Comment by 108day** [comment]
> 这应该不是一个bug，`<Option :value="item.id" :key="item">{{ item.name }}</Option>`，select组件里，这样使用就会出这个警告，问题在 :key="item" 这里。
> 
> 解决办法：
> ` <template v-for="item in xxxx"> <Option :value="item.id">{{ item.name }}</Option> </template>`

确实是可以解决这个bug
