### ISSUE TITLE
Feature Request: Provide render support on Table's header.

### ISSUE THREAD

**Issue by lcx960324** [iview/iview#1357]
There are cases that we need to customize Table's header with Vue components. But now table can only directly pass raw HTML tag and let bowser resolve it. 

I think we need such feature to let user customize Table's header if necessary.

This isssue is contribute-welcome & I'll work on it.
Thx. XD

**Comment by melon** [comment]
desperately request this feature

**Comment by icarusion** [comment]
Old `renderHeader` replace a Render function
