### ISSUE TITLE
当Vue>=2.3.0，Table组件中使用Switch的问题

### ISSUE THREAD

**Issue by chenhaizano** [iview/iview#1359]
### iView 版本号

2.0.0-rc.18

### 操作系统/浏览器 版本号

Chrome 56

### Vue 版本号

2.3.0

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://runjs.cn/code/6buyuusb

### 问题现象，以及你期望的结果是怎样的?
当使用vue>=2.3.0时，switch组件不能正常使用，不管值是true/false都一直在灰色状态

vue<=2.2.6则正常

**Comment by icarusion** [comment]
your code is funny

**Comment by chenhaizano** [comment]
@icarusion 忘记发布了，麻烦您重新看下。
