### ISSUE TITLE
Table组件render模板及Page组件分页值改变问题

### ISSUE THREAD

**Issue by yajore** [iview/iview#136]
### iView 版本号
0.9.10

### 操作系统/浏览器 版本号
WIN10/Chrome 55

### Vue 版本号
1.0.26

### 能够复现问题的在线示例

https://codepen.io/anon/pen/woNeMq

### 复现步骤
具体看codepen

**Comment by icarusion** [comment]
首先，你这里就写错了：
```
//这里官方文档的有问题,官方写法无法显示
//return  '<Icon type="person"></Icon<strong>${row.name</strong>';
```
这里用的是`不是'，具体查看 ES6 文档；

另外，Page的`pageSize`是可以`.sync`的，目前没有给出自定义事件，后面加一下

**Comment by yajore** [comment]
3Q,
