### ISSUE TITLE
【需求】tree的使用不够灵活，建议也做成element-ui的tree控件一样

### ISSUE THREAD

**Issue by wainguo** [iview/iview#1360]
之前用element-ui，后来看到iview感觉ui挺舒服，用法也差不多，但用到tree控件，感觉不够方便，建议也能类似element-ui的tree控件一样的用法。http://element.eleme.io/#/zh-CN/component/tree

1.tree的数据应该来源灵活，不需要显式的做两次数据格式转换，这个element-ui tree 通过props做到
2.tree node渲染的内容不灵活，这个element-ui tree 通过自定义的render来做到
3. element-ui tree还提供了filter，getCheckedKeys，setCheckedKeys，setCheckedNodes等方便控制的方法

以上建议，祝好！

**Comment by wainguo** [comment]
我又理解了下iview的代码，好像是我的错，我先入为主陷入了固有的思维模式，感觉iview的方式好像更简单，把控制权全交给使用者了。
1.渲染前做一次数据转换，也是必须的，只是iview把这个工作交给了使用者，想想也挺灵活的。
2.原来title是通过v-html来支持自定义内容的。
3.filter这个也是可以在数据上做。set系列方法也是直接对数据做动作就可以达成了。

**Comment by wainguo** [comment]
目前仍然有一个问题，就是title自定义的内容如果想放几个按钮，针对节点做些操作，这个好像满足不了

**Comment by icarusion** [comment]
We will set a render function in the future

**Comment by liumanwei** [comment]
tree上可以支持右键的操作

**Comment by roronoaxyz** [comment]
> tree上可以支持右键的操作

怎么支持啊？？ 有代码吗，谢谢
