### ISSUE TITLE
Vue>=2.3.0，Table组件columns:render中使用switch、input时，v-model不能正常使用

### ISSUE THREAD

**Issue by chenhaizano** [iview/iview#1361]
### iView 版本号

2.0.0-rc.18

### 操作系统/浏览器 版本号

Chrome 56

### Vue 版本号

2.3.0

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

1、Iview:Table中使用render
http://runjs.cn/code/6buyuusb

2、普通组件中使用render
http://runjs.cn/code/vuw8oayz

### 问题现象，以及你期望的结果是怎样的?
当使用vue>=2.3.0时，Table组件columns:render中使用switch、input时，v-model不管用

vue<=2.2.6则正常

**Comment by caozhengchn** [comment]
将domProps改为props试试

**Comment by chenhaizano** [comment]
@caozhengchn 改为props没问题了， 谢谢
