### ISSUE TITLE
Modal 点了OK后他自己就关了，很多时候是要处理完相应事情，然后在回调方法中把model置为false来关闭。

### ISSUE THREAD

**Issue by lichuangang** [iview/iview#1363]

**Comment by lichuangang** [comment]
Modal 点了OK后，不要直接就关掉。太草率了

**Comment by wainguo** [comment]
如果不想要这样的默认行为，可以自定义footer

**Comment by chenhaizano** [comment]
https://www.iviewui.com/components/modal
异步关闭

**Comment by chenhaizano** [comment]
https://www.iviewui.com/components/modal#异步关闭

**Comment by jeffywin** [comment]
<div slot="footer">
            <i-button type="error" size="large" long >删除</i-button>
   </div>
