### ISSUE TITLE
Any plan to support RTL?

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [iview/iview#1364]
Hi

I want to know, do you have plan to support RTL (right to left) layout?

**Comment by rijn** [comment]
We do not have that plan yet.

**Comment by miladmeidanshahi** [comment]
please think about that we have many user and project that need rtl support

**Comment by OsamaAbbas** [comment]
Hi guys,

You can use this tool for now: http://rtlcss.com/ .

**Comment by miladmeidanshahi** [comment]
@OsamaAbbas style source should be `RTL`
http://rtl.css i't not good practice.

**Comment by zakariaf** [comment]
Any plan to support RTL (right to left) layout?
