### ISSUE TITLE
需求：page分页添加当前页数功能

### ISSUE THREAD

**Issue by lyhdahaoren** [iview/iview#1365]
### iView 版本号

2.0.0
### 操作系统/浏览器 版本号

win10 chorme59
### Vue 版本号

2.2.1
### 问题现象，以及你期望的结果是怎样的?
希望给page分页添加当前页数功能（current-page）

**Comment by lcx960324** [comment]
Please read the API Doc carefully.

![image](https://user-images.githubusercontent.com/9768245/28260343-2df9d312-6b0d-11e7-832d-f350e585ea2a.png)
