### ISSUE TITLE
Modal disappearance AVOID mutating prop

### ISSUE THREAD

**Issue by StasB93R** [iview/iview#1368]
I'm working with modals for the last couple of days and i faced a few problems. For example if a user doesnt press any cancel buttons or ok onces but rather presses out of the modal. Following this logic the modal will dissapear, but how to get rid of the the vue-warrning AVOID MUTATING PROPS etc, i have given the code here
 https://forum.vuejs.org/t/props-modal-changing-value/14387

In that example the code works good to show the modal, but once i want to close it its giving me that warning about AVOIDING mutating props like that, despite the fact that i have put a watcher to check for any changes. Is it me that dumb or there is something wrong with the modal

EDIT: if i put console.log(this.modal1), when the modal shows up its giving me true, but once its gone its giving me undefined

**Comment by StasB93R** [comment]
found a solution https://stackoverflow.com/questions/45131532/vuejs-modal-avoid-changing-props-nuxt-js-iview/45132309#45132309
can close this issue

**Comment by lcx960324** [comment]
I still suggest you to control Modal's display in the component which owns it.
If you have no choice, you can use computed to control the display, which returns your `modal1` prop. and you can emit an event to let its parent to update it in computed's `set` property.

**Comment by icarusion** [comment]
Update to the latest version.If there is any problem, please open another issue.
