### ISSUE TITLE
 Badge props dot bug

### ISSUE THREAD

**Issue by xumiaojun** [iview/iview#1369]
### 复现步骤

 <Badge dot count='0'>
        <Icon type="ios-bell-outline" size="26"></Icon>
    </Badge>  徽标不显示红点，是正常
以下Bug：
<Badge dot :count='countNumber'>
        <Icon type="ios-bell-outline" size="26"></Icon>
  </Badge>  当count为绑定数据时，countNumber初始为0，徽标红点还是存在

### 问题现象，以及你期望的结果是怎样的?

使用Badge，运用在消息提示上，props的count数量决定 徽标红点是否显示。

**Comment by icarusion** [comment]
Please ask questions as requested.
