### ISSUE TITLE
Badge dot Bug

### ISSUE THREAD

**Issue by xumiaojun** [iview/iview#1370]
### 复现步骤
在使用badge时，在count为一个双向绑定数据时，即使绑定的值为0，徽标红点还是存在。

### 问题现象，以及你期望的结果是怎样的?

 <Badge dot :count='countNumber'>
        <Icon type="ios-bell-outline" size="26"></Icon>
 </Badge>
badge props count 绑定 countNumber 初始化为 0，徽标红点还是存在！

**Comment by icarusion** [comment]
#1369
Do not ask questions repeatedly, read issue guide carefully.
