### ISSUE TITLE
Table > highlight-row没有提供取消高亮的方法

### ISSUE THREAD

**Issue by henrylu** [iview/iview#1372]
Table添加highlight-row后，想在某个方法里把选中的行的高亮取消掉，但Table文档里没有看到如何可以取消高亮的方法或属性。

**Comment by lcx960324** [comment]
You can bind `highlight-row` prop with a boolean variable like `:highlight-row="highlight"` If you want to disable highlight, just set this prop to false.

**Comment by icarusion** [comment]
会在文档补充
