### ISSUE TITLE
Table组件响应式

### ISSUE THREAD

**Issue by eeve** [iview/iview#1373]
请问Table组件有支持响应式的计划吗？

**Comment by lcx960324** [comment]
We think that responsive layout is not what a UI toolkit should provide. So we are now not going to do anything on responsive component except `Grid`.

**Comment by YikaJ** [comment]
@eeve you can trigger window resize event by yourself, here are the code.
`js
const e = document.createEvent('HTMLEvents')
e.initEvent('resize', true, true)
window.dispatchEvent(e)
`

**Comment by eeve** [comment]
当我尝试改变浏览器宽度，或者移动端查看的时候，table组件的某些列会发生变形。这个问题目前有现成的解决方案吗。

![](https://ws1.sinaimg.cn/mw690/83280e47gy1fhroqat0etj20aa054aa2.jpg)
