### ISSUE TITLE
table中使用异步加载动态列将导致固定列太高遮住横向滚动条

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1378]
### iView 版本号
2.0.0-rc.18 

### 操作系统/浏览器 版本号
Chrome 59

### Vue 版本号
2.3.4

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/54b026vv/1/

**Comment by icarusion** [comment]
#1206
