### ISSUE TITLE
向时间选择器和日期选择器中输入空格，当失去焦点的时候，会报错！

### ISSUE THREAD

**Issue by ningzhanqi** [iview/iview#1381]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
win10/ Chrome 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

![image](https://user-images.githubusercontent.com/26369769/28296717-7c91e0f2-6b9c-11e7-9cc3-f56218ee8ac5.png)

### 问题现象，以及你期望的结果是怎样的?
如果向时间选择器和日期选择器中输入空格，当失去焦点的时候，会报错！
### 你估计可能的原因是什么（选填）？
缺少对输入内容的判断和处理！

**Comment by icarusion** [comment]
Provide online code
