### ISSUE TITLE
Breadcrumb 无法给href赋值

### ISSUE THREAD

**Issue by gavinfuu** [iview/iview#1383]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
Chrome 59

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/gavinfuu/pen/zzQNMB

### 复现步骤
生成的<a>链接没有href属性,r5是正常的

**Comment by rijn** [comment]
We do not assign `href` of hyperlink but dynamically replace router with the string you provided

**Comment by icarusion** [comment]
Update to the latest version and try again.
