### ISSUE TITLE
Input控件在v-model显示错误

### ISSUE THREAD

**Issue by bao2314483** [iview/iview#1385]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
VsCode开发工具

### Vue 版本号
Vue2.4.1

代码
<Input type="text" v-model="LoginForm.UserName" placeholder="账号"></Input>
错误提示
[vue-language-server] 'v-model' directives aren't supported on <Input> elements

在vscode里面开发代码提示红线,但是直接运行不会报错,有人遇到这种问题吗?我用element-ui是不会有这种提示,我估计是iview问题

**Comment by icarusion** [comment]
It seems to have something to do with vscode

**Comment by bao2314483** [comment]
我已经解决了,在单文件下,input控件,必须要使用i-input

**Comment by icarusion** [comment]
`i-input` is needed if not under template/render mode. So, you can use `Input`.
