### ISSUE TITLE
InputNumber输入任何东西都会自动恢复原来的默认值

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1386]
### iView 版本号

2.0.0-rc.19
### 操作系统/浏览器 版本号

QQ浏览器 9.6.2
### Vue 版本号

 2.4.1
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

 https://codepen.io/anon/pen/jwoGgK
### 复现步骤
输入其他数值，点击其他地方
### 问题现象，以及你期望的结果是怎样的?
数字自动回复到1，按上下按钮无法增加里面的数值
期望结果是保留输入的数值。

**Comment by lvqingan** [comment]
加上v-model

**Comment by kiddkyd1412** [comment]
@lvqingan 其实我之前就是写了
v-model="form.num"
并且data里面定义了form
只是没有定义到二级属性num

之前明明没问题的，最近更新后就不行了。

具体在线例子我已经更新了

**Comment by lvqingan** [comment]
@kiddkyd1412 你codepen里加了v-model后我执行是正常的
![image](https://user-images.githubusercontent.com/2076441/28348397-6e694572-6c02-11e7-89cc-6508b7620958.png)

**Comment by kiddkyd1412** [comment]
@lvqingan 
噢。。说错。。你把data里的form:{num:3}改成form:{}，就不行了。以前是可以的。其他input控件都可以这样写。

**Comment by icarusion** [comment]
#1400
