### ISSUE TITLE
select异步请求label数据，但无法渲染

### ISSUE THREAD

**Issue by lavenkin** [iview/iview#1388]
### iView 版本号

2.0.0-rc.17
### 操作系统/浏览器 版本号

macOs/CHrome
### Vue 版本号

2.2.1
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://jsfiddle.net/lavenKin/fbwtzaL6/7/
### 复现步骤
异步请求label数据，无法渲染
### 你估计可能的原因是什么（选填）？
发现`currentLabel`为空
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fhphuk5xc0j30vm0ag402.jpg)
源码中`currentLabel = this.label`
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fhphz5iknaj30xq0l6acg.jpg)

**Comment by lcx960324** [comment]
Your `setTimeout`'s callback function didn't bind any `this` context. Please change it to arrow function: 

```
setTimeout(() => {
    	this.selectedIds = ['201701011046', '201701011145'],
        this.defaultLabel = ['语文', '数学']
}, 1000)
```

**Comment by lavenkin** [comment]
@lcx960324 Yet , but when my `list` is empty , it render failure.
```
data:{
    list:[],
    selectedIds: [],
    defaultLabel: [],
},
```
https://jsfiddle.net/lavenKin/fbwtzaL6/10/

**Comment by lcx960324** [comment]
？？？

`list` 都是空的了，难道我要变出数据填进去吗= =

**Comment by lavenkin** [comment]
@lcx960324 但我想初始化这个select，却实现不了啊

**Comment by lcx960324** [comment]
就算是初始化，也应该是先从后端把列表抓取过来，再去指定默认选中项吧。`list` 是空的，指定默认选中项，当然不会显示了。

**Comment by lavenkin** [comment]
@lcx960324 但这是个搜索，假如后端数据量太大不就挂逼了吗

**Comment by lcx960324** [comment]
所以你认为的逻辑是，这个组件应该把你指定的默认值显示出来，无论你的 `Option` 是否包含这个选项？

**Comment by lavenkin** [comment]
@lcx960324 按照你的说法，应该要给list赋值
https://jsfiddle.net/lavenKin/fbwtzaL6/12/

**Comment by lcx960324** [comment]
https://jsfiddle.net/vq0x8q9s/

**Comment by lavenkin** [comment]
@lcx960324 原来如此 ，这个回调机制可以加到组件源码内吗？要不然发现问题要找半天
