### ISSUE TITLE
table组件on-select-change事件没有触发

### ISSUE THREAD

**Issue by yajore** [iview/iview#139]
### iView 版本号
 0.9.10 

### 操作系统/浏览器 版本号
WIN10 chrome54

### Vue 版本号
 1.0.26 

### 能够复现问题的在线示例
https://codepen.io/anon/pen/woNeMq

### 问题现象，以及你期望的结果是怎样的?
看看我写的例子是不是有问题,不对的地方请指出,谢谢!
问题导致无法准确判断用户取消了什么选项,如果是bug,最好能再给一个row参数,用于知道用户取消了哪一行

**Comment by icarusion** [comment]
on-select是选中一项时触发，会返回row；
on-select-change是只要选项发生变化就触发，返回已选的所以项；
详见文档API

**Comment by yajore** [comment]
关键目前on-select-change事件根本没有触发

**Comment by icarusion** [comment]
非常抱歉，文档写错了，应该是`on-selection-change`
