### ISSUE TITLE
升至vue2.4.1 使用$Modal.confirm报错，使用DatePicker报错，控制台里可以看到。

### ISSUE THREAD

**Issue by 188007803** [iview/iview#1391]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
win7/qq 浏览器最新版

**Comment by kiddkyd1412** [comment]
我试过没问题哦。环境和你一样

**Comment by icarusion** [comment]
https://www.iviewui.com/components/modal
There is no problem
