### ISSUE TITLE
Card绑定click事件无效

### ISSUE THREAD

**Issue by hegoku** [iview/iview#1392]
### iView 版本号
2.0.0-rc.5 

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例

https://codepen.io/anon/pen/dRBGEg

### 问题现象，以及你期望的结果是怎样的?

给Card标签加上 `@click="show"` ，运行时候点击Card，并没有触发或者调用设置的click事件

**Comment by rijn** [comment]
`v-on:click.native`

**Comment by hegoku** [comment]
@rijn 谢谢

**Comment by calchen** [comment]
@rijn 正解，谢谢

**Comment by fireroundgithub** [comment]
为啥得加@click不行，@click.native可以
