### ISSUE TITLE
Transfer不能设置或者自适应高度

### ISSUE THREAD

**Issue by bao2314483** [iview/iview#1398]
Transfer组件属性上没有height来设置高度
然而通过局部css覆盖也是无法设置高度
<style scoped>
.ivu-transfer-list{
    height: 300px;
}
</style>

**Comment by lcx960324** [comment]
![image](https://user-images.githubusercontent.com/9768245/28397061-c08d3248-6d31-11e7-9ab8-d2d0105e050e.png)

**Comment by bao2314483** [comment]
thanks
