### ISSUE TITLE
table组件hover 高亮有个动画效果，希望可以配置不要动画效果

### ISSUE THREAD

**Issue by lightColour** [iview/iview#1402]
表格滚动条很长的情况，滚动时，hover 的**动画渲染效果会使滚动动作卡卡的**。

目前我的解决办法是使用 disable-hover 禁用 hover 鼠标悬停时的高亮，然后自己通过 css 设置 hove r样式:
 .ivu-table-row:hover td{
      background-color: #BFCBD9!important;
}

瞬间感觉滚动流畅了许多
所以希望能够有个取消动画效果的配置

**Comment by icarusion** [comment]
Use `disabled-hover` prop
