### ISSUE TITLE
[Feature] 希望Table组件中提供某一列的默认排序的功能

### ISSUE THREAD

**Issue by 634750802** [iview/iview#1403]
### 需求
某一列的`sortable`属性为`"custom"`时，提供某一列的默认排序方法。

### 目前情况
每次刷新`column`数据时，会重置每一列的`_sortType`为`"normal"`。然而在更新`column`的某些属性时（比如标题），并不会影响现有数据，所以会出现数据已经排序，但是表头ui更新为未排序状态。

### 解决方案
`column`数据中新增加可选`sortType`属性，在`column`数据刷新时覆盖默认的`"normal"`值。

**Comment by 634750802** [comment]
神速🎉

**Comment by luogan210** [comment]
弱弱的问一下，好像写了没有用啊
