### ISSUE TITLE
tabs的on-click事件中删除tabs对应的数据数组后tabs不会刷新

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1404]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
win10/Chrome 59

### Vue 版本号
2.4.0

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://jsfiddle.net/3feecwmp/3/

### 复现步骤
单击tab,检测剩余tab数量,与界面显示的数量

**Comment by icarusion** [comment]
删除是 @on-tab-remove

**Comment by yangdan8** [comment]
我要click时也remove

**Comment by rijn** [comment]
Use `$forceUpdate` to rerender manually

```vue
<Tabs ref="tabs">...</Tabs>
```

```js
// In the method
this.$refs.tabs.$forceUpdate();
```

**Comment by yangdan8** [comment]
不是数据驱动的吗?这里的watch是否有问题呢?

**Comment by rijn** [comment]
What's the result you wish?

**Comment by yangdan8** [comment]
希望得到删除数据后,页面应该根据应该减少tab.
现在删除第一个可以,删除第二个不行,也就是点击按钮两次

**Comment by yangdan8** [comment]
或者你看这个例子就更明显了
https://jsfiddle.net/3feecwmp/6/

**Comment by rijn** [comment]
emmm. You could use `this.$refs.tabs.handleRemove(1);` by then. sorry about that

**Comment by yangdan8** [comment]
使用this.$refs.tabs2.handleRemove(1);可以临时达到效果
https://jsfiddle.net/3feecwmp/10/

**Comment by rijn** [comment]
@yangdan8 We do not watch the children currently, so the internal tabs would not be updated if you modified this data.

**Comment by yangdan8** [comment]
如果是不watch子对象,那么在三个自对象的时候又为什么正常呢?请看这个例子
https://jsfiddle.net/3feecwmp/3/
