### ISSUE TITLE
Table组件以及Select组件的性能问题

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [iview/iview#1405]
### iView 版本号
 2.0.0-rc.19

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.4.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

因为Table卡顿的原因，改成了自己用table来实现，结果Select组件还是卡顿。
```html
<tr v-for="(item,index) in data1" >
    <td>{{index+1}}</td>
    <td>{{item.xm}}</td>
    <td style="text-align:left">[{{item.kcdm}}]{{item.zwmc}}</td>

    <td><Input style="width:40px" v-model="item.needNum"></Input></td>
    <td>
        <Input style="width:40px" v-model="item.realNum"></Input>
    </td>
    <td style="position:relative;">
        <Select v-model="item.lessonPlanGrade">
            <Option v-for="item1 in lessonGradeList" :value="item1.value" :key="item1">{{item1.label}}</Option>
        </Select>
    </td>
    <td>
        <Input class="inpWidth_1" v-model="item.lessonPlanProblem"></Input>
    </td>
    <td>
        <Input class="inpWidth_2_2" v-model="item.lessonPlanReform"></Input>
    </td>
</tr>
```

### 复现步骤
Table组件掺杂大量Input组件就会卡顿
以及Select组件多了也容易卡顿，在一个原生table里做Select组件列表也避免不了卡顿

### 问题现象，以及你期望的结果是怎样的?
![示例图](https://user-images.githubusercontent.com/6437400/28396974-4a4188d2-6d31-11e7-836d-402d337e56da.png)
当Table组件嵌套大量的Input组件时，对Input组件进行操作的卡顿感明显，数据量大约70多条，Select组件点击大约近一秒才会弹出来，不知道怎么回事

### 你估计可能的原因是什么（选填）？
可能是Input组件的双向绑定数据v-model造成的，不知道这是不是vue本身难解决的问题。同样的需求，用easyUI就很流畅。

**Comment by hh-in-zhuzhou** [comment]
首先感谢iView团队的付出和努力。iView团队可否说明一下是不是不太适合做这种需求，还是说我的写法有问题，写写

**Comment by icarusion** [comment]
Update to the latest version and try again.

**Comment by physicsLoveJava** [comment]
就是渲染组件太多的问题，我也遇到这样的问题，最后还是后面加按钮，点击弹框进行修改

**Comment by Gilbert5210** [comment]
然后有解决方案了吗
