### ISSUE TITLE
建议给Page组件加上一个刷新的按钮

### ISSUE THREAD

**Issue by pengpan** [iview/iview#1406]
iView 版本号

2.0.0-rc.17

操作系统/浏览器 版本号

Chrome 58

Vue 版本号

2.2.3

建议楼主给Page组件加上一个刷新的按钮，我们这有客户反馈分页内容有更新没地方刷新，他们就习惯按F5 麻烦，希望分页底部能提供一个刷新便捷按钮；

**Comment by icarusion** [comment]
You can add it yourself
