### ISSUE TITLE
Slow site

### ISSUE THREAD

**Issue by develar** [iview/iview#1410]
Hi, often site https://www.iviewui.com is loading very slowly (Germany). Maybe you can host it on http://netlify.com/ (free for opensource)? To make site more faster for Europe :)

**Comment by yundmb** [comment]
@develar Can you speak Chinese?

**Comment by develar** [comment]
@yundmb Nein, я из России. For now I just built site locally as workaround.

**Comment by yundmb** [comment]
@develar Sprichst du Englisch?

**Comment by develar** [comment]
@yundmb if you have  related to issue questions, feel free to use Chinese or another convenient for you language.

**Comment by rijn** [comment]
This board is only for issue discussion, guys.

We do not have plan for changing server yet. It is managed by @icarusion.

**Comment by SergioCrisostomo** [comment]
@develar maybe the more we are accessing from Europe the better it will get with caching and stuff. I'm in Sweden and it works ok, maybe it was worse when you opened this issue?

Closing this for now. Regards from the north 👍

**Comment by mudin** [comment]
recently it became very slow in South Korea, I cannot read the docs anymore. Is there any other site where I can check the docs?

**Comment by mudin** [comment]
I found this link https://iview.github.io/ for 2.x, it is quite fast. It would be nice if there is 3.x version  of this link on github. Or is there any way that I can use my localhost?

**Comment by matiaslopezd** [comment]
### English:
Guys the iView site is extremely slow! I try access from South America. I saw in devtools that have a very big JS file. Try separate in chunks if is possible!

### Chinise (中文):
大家好，iView網站很慢！我試圖從南美進入。我在devtools中看到了一個非常大的JS文件。如果可能的話.

Screenshot:
![image](https://user-images.githubusercontent.com/23618492/60764202-22e9fb00-a053-11e9-9730-6ea43e8ba082.png)
