### ISSUE TITLE
select组件使用render渲染，动态修改optionList的值，发现select选中项无法显示

### ISSUE THREAD

**Issue by LL89757** [iview/iview#1411]
### iView 版本号

2.0.0-rc.14
### 操作系统/浏览器 版本号

版本 2.6.5.52 (Chromium 58.0.3029.110)
### Vue 版本号

2.3.4
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/LL89757/pen/VWoaxN
### 复现步骤
选中第一个select框，第二个select框的选中无法显示
### 问题现象，以及你期望的结果是怎样的?
两个组件的联动效果，第一个组件触发时间，修改第二个select组件的option列表，发现修改完之后选中值无法显示。修改方法：直接赋值或者先清空再push这两种清空都存在问题，直接push的话是可以正常显示
预期是希望能正常显示，
### 你估计可能的原因是什么（选填）？
看了源码，感觉主要问题还是在于select组件updateOptions方法没有触发，option属性没有更新
单独对option属性进行push操作可以触发，直接赋值无法触发

**Comment by hh-in-zhuzhou** [comment]
我发现只要是联动的话，修改Option绑定的数组，这时候去选择Option，选中的value打印出来是对的，可是显示的值却是之前的数组的相应索引的值。

**Comment by hh-in-zhuzhou** [comment]
<img width="156" alt="issue" src="https://user-images.githubusercontent.com/6437400/28500133-3e67245a-6ff6-11e7-91c8-09bf993fcee3.png">
请看这个图，命名选中的是“数字媒体专业”，上头显示的却是计算机网络技术。。。。

**Comment by LL89757** [comment]
@hh-in-zhuzhou 你那个问题我是没有碰到，我这边修改值都是正常的，但是有种情况，就是如果你修改的下拉选项只有两项，选中值是不会显示的

**Comment by icarusion** [comment]
Update to the latest version and try again.
