### ISSUE TITLE
Menu-nuxt.js with transitions not working

### ISSUE THREAD

**Issue by StasB93R** [iview/iview#1412]
If you use one of your menus and do the folllowing code:

       <nuxt-link to='about'>
      <Menu-item name="2">
        <Icon type="ios-people"></Icon>About us
      </Menu-item>
      </nuxt-link>

it doesnt do transitions when leaving the page and when loading the new page, if i remove the menu at all and just have nuxt-links then it works perfectly. Im afraid the same logic might apply if you wrap any of  iview elements in nuxt-link. So is there a way to fix it?

But if you do 

       <Menu-item name="4">
          <nuxt-link to='settings'>
          <Icon type="settings"></Icon>
          Settings
          </nuxt-link>
        </Menu-item>

then it works fine, but you will need to increase the size of the link itself so that it fits the menu layout. Its not so much of a problem but for the convience purposes i think it would be better if you can just wrap it in my first example coz it automatically removes the link colors etc. So if there is something u can do about it would be good.

**Comment by icarusion** [comment]
iView Menu component can not work with router-link(it amount to nuxt-link?), you can route page through Menu event `on-select`.

**Comment by StasB93R** [comment]
that is one of the ways to get around, i will try

**Comment by StasB93R** [comment]
but how would it look like, for example if i need 

        <Menu-item name="2">
          <Icon type="ios-people"></Icon>About us
         </Menu-item>

to link it to about?

**Comment by icarusion** [comment]
```
<Menu @on-select="handleSelect">

handleSelect (name) {
    this.$router.push(name);  //  name is '2'
}
```

**Comment by StasB93R** [comment]
i did
            <Menu-item name="main" @on-select="handleSelect">
             <Icon type="ios-people"></Icon>Show courses
            </Menu-item>
and in my methods:

          handleSelect(name) {
             this.$router.push(name);
          }

i understand the logic and that it should work but it doesnt by some reason

**Comment by icarusion** [comment]
No, add @on-select in Menu, not MenuItem

**Comment by StasB93R** [comment]
thats right, right after i posted my response i realised it :) brain works better under pressure. It works now thanks a lot:)

**Comment by andyhu** [comment]
Is there any way to support fully functional `nuxt-link`? It's not just a simple `a` tag, but there's also some functionality which is defined in `router-link`.

**Comment by andyhu** [comment]
I've refactored `BreadcrumbItem` a bit so it could work better with something like `nuxt.js` or `router-link`. I'm not sure if it worths it, but is it possible to modify the original code so the parameters can be more aligned with those standard libraries for better integration?
```js
<template>
  <span>
    <nuxt-link v-if="to" :class="linkClasses" :tag="this.tag" :exact="exact" :append="append" :replace="replace" :activeClass="activeClass" :exactActiveClass="exactActiveClass" :event="event">
      <slot></slot>
    </nuxt-link>
    <span v-else :class="linkClasses">
      <slot></slot>
    </span>
    <span :class="separatorClasses" v-html="separator" v-if="!showSeparator"></span>
    <span :class="separatorClasses" v-else>
      <slot name="separator"></slot>
    </span>
  </span>
</template>
<script>
const prefixCls = 'ivu-breadcrumb-item';

export default {
  name: 'NuxtBreadcrumbItem',
  props: {
    to: {
      type: [String, Object]
    },
    tag: {
      type: String,
      default: 'a'
    },
    exact: Boolean,
    append: Boolean,
    replace: Boolean,
    activeClass: String,
    exactActiveClass: String,
    event: {
      type: eventTypes,
      default: 'click'
    },
  },
  data() {
    return {
      separator: '',
      showSeparator: false
    };
  },
  computed: {
    linkClasses() {
      return `${prefixCls}-link`;
    },
    separatorClasses() {
      return `${prefixCls}-separator`;
    }
  },
  mounted() {
    this.showSeparator = this.$slots.separator !== undefined;
  },
};
</script>
```
