### ISSUE TITLE
select数据清空的问题

### ISSUE THREAD

**Issue by nieyulin112** [iview/iview#1417]
select多选后用js清空已选数据， 页面选择框里已选数据没有被清空，绑定循环在option的数组清空了，绑在select的数组也清空了，结果输入框中依然有值！

**Comment by mansonchor** [comment]
+1

**Comment by rijn** [comment]
It would be better to provide a jsfiddle.

**Comment by rijn** [comment]
It works for me if using `this.data = []`.

**Comment by nieyulin112** [comment]
依然不行哦

**Comment by lqcool** [comment]
依然不行
