### ISSUE TITLE
组件标签问题

### ISSUE THREAD

**Issue by wangchenhao** [iview/iview#1419]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
macOS/Chrome 56

### 复现步骤
iview的组件标签 开头大写 不符合 HTML 规范 官方有计划修改嘛，有些组件不支持 i 前缀。
### 问题现象，以及你期望的结果是怎样的?
希望有统一的标签前缀支持。

**Comment by rijn** [comment]
You can rename it by yourself.

```
import { Rate as iRate } from ...
```

**Comment by wangchenhao** [comment]
我用的是全局引入没用按需引入，所以希望官方可以从实现上统一。
