### ISSUE TITLE
异步加载的select如何验证非空

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1420]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号

QQ浏览器9.6.2
### Vue 版本号
2.4.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/qjeLVr

### 复现步骤
异步加载好数据后，选择任何一项
### 问题现象，以及你期望的结果是怎样的?
选了东西后，依然提示验证为空。
期望结果是不要再次提示

**Comment by rijn** [comment]
Use exactly the same name in both `formData` and `ruleValidate`.

e.g.
```
form: {
    productType: null
},
ruleValidate: {
    productType: [
        { required: true, message: '分类不能为空', trigger: 'change' }
    ]
}

<Form-item label="分类" prop="productType">
    <i-select v-model="form.productType" placeholder="请选择">
        <i-option v-for="i in productTypeData" :value="i.id" :key="i.id">{{ i.name }}</i-option>
    </i-select>
</Form-item>
```

And, please be careful with your indent. It's really hard to read.

**Comment by kiddkyd1412** [comment]
@rijn 然而并不行
https://codepen.io/anon/pen/PKZYKj

**Comment by rijn** [comment]
@kiddkyd1412 If you read the async-validator doc carefully, you will find why this happened.

The default type of the validator to use is string, but you passed number to it. So, there're two solutions to this issue.

1. Change your validator to type number

```
{ type: "number", required: true, message: '分类不能为空', trigger: 'change' }
```

2. Change the data to string

```
      that.productTypeData = [
        { 'id': '1', 'name': 'a' },
        { 'id': '2', 'name': 'b' }
      ];
```

Hope this would be helpful.

**Comment by beyondverage0908** [comment]
> @kiddkyd1412 If you read the async-validator doc carefully, you will find why this happened.
> 
> The default type of the validator to use is string, but you passed number to it. So, there're two solutions to this issue.
> 
> 1. Change your validator to type number
> 
> ```
> { type: "number", required: true, message: '分类不能为空', trigger: 'change' }
> ```
> 
> 1. Change the data to string
> 
> ```
>       that.productTypeData = [
>         { 'id': '1', 'name': 'a' },
>         { 'id': '2', 'name': 'b' }
>       ];
> ```
> 
> Hope this would be helpful.

thank, you help me
