### ISSUE TITLE
Tabs 关闭问题

### ISSUE THREAD

**Issue by PlueWhiteStory** [iview/iview#1421]
### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
win7/chrome56

### Vue 版本号
2.33

### tabs组件问题。
当给一个tabs组件props设置 type="card"  :animated="false"  .tab-pane 组件props 设置:closable="true" 时。当关闭一个tab-pane时。会出现tab标签删除，但是内容没有删除的情况。导致所有其他tab都会出现删除页的内容。

**Comment by rijn** [comment]
please provide jsfiddle

**Comment by PlueWhiteStory** [comment]
我尝试住还原了这个问题，可以在https://jsfiddle.net/3q1wc1Lk/查看。你也可以自己还原这个问题。
这是问题代码：
<div id="app" style="height:400px">
        <Tabs value="name1" type="card" :animated="false" >
        <Tab-pane label="标签一" name="name1" :closable="true">标签一的内容</Tab-pane>
        <Tab-pane label="标签二" name="name2" :closable="true">标签二的内容</Tab-pane>
        <Tab-pane label="标签三" name="name3" :closable="true">标签三的内容</Tab-pane>
    </Tabs>
</div>
问题重现：
选择任意tab，然后关闭该tab。

**Comment by rijn** [comment]
Please read the doc carefully. You need to use `@on-tab-remove` to close the tab manually.
