### ISSUE TITLE
Model中使用Select远程搜索，关闭model再次输入文本查询，提示列表会跑到页面最左边

### ISSUE THREAD

**Issue by stevenwu2016** [iview/iview#1424]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
Windows10/Chrome 56

### Vue 版本号
2.3.4

### 复现步骤
1.select中输入文本，点击其中一个选项
2.关闭model
3.继续select输入文本

### 你估计可能的原因是什么（选填）？
关闭model后动态添加的fixed导致列表偏移了
`<div class="ivu-select-dropdown" style="width: 408px; transform-origin: center top 0px; position: fixed; left: 0px; top: 33px; display: none;" x-placement="bottom"><ul class="ivu-select-not-found" style="display: none;"><li>无匹配数据</li></ul> <ul class="ivu-select-dropdown-list"></ul> <ul class="ivu-select-loading" style="display: none;">加载中</ul></div>`

**Comment by icarusion** [comment]
fixed

**Comment by justnowanna** [comment]
已经解决了吗？@icarusion

**Comment by icarusion** [comment]
waiting for next version

**Comment by justnowanna** [comment]
@icarusion 谢谢，项目下周就要上线了，今天一直在研究这个问题，看到3小时之前说fixed，简直不要太高兴。现在测试提的bug还摆在禅道。。。。

**Comment by justnowanna** [comment]
@icarusion 再次感谢，顺便再提一个Page组件的bug，有在线实例
https://jsfiddle.net/p69go9rc/7/
先点击第50页，再点击按钮设置到第一页，再点击第50页，然后点击按钮设置到第一页就不生效了。

**Comment by icarusion** [comment]
Use event `on-change`

**Comment by justnowanna** [comment]
@icarusion 感谢回复，解决了。。。是我自己的使用问题。Thanks very much!!!
