### ISSUE TITLE
table的滚动条带来的问题点太多,请考虑添加设置禁用所有滚动条属性

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1425]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
IE11

### Vue 版本号
2.4.0

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

建议添加禁用滚动条属性,然后用以下插件来实现,
或者参考这个插件来实现虚拟滚动条
http://noraesae.github.io/perfect-scrollbar/

**Comment by icarusion** [comment]
There is no such plan now.
