### ISSUE TITLE
希望upload组件能在beforeUpload中动态改变上传action(url)的值

### ISSUE THREAD

**Issue by starding** [iview/iview#1430]
### iView 版本号
2.0.0-rc.17

### Vue 版本号
2.3.4

### 能够复现问题的在线示例

不算个bug，算是特性支持

### 问题现象，以及你期望的结果是怎样的?

在当前的upload组件设计中，上传的url需要提前定义好，没办法根据上传文件类型动态地在 beforeUpload中切换不同的url。

期望能在beforeUpload中动态切换url

### 你估计可能的原因是什么（选填）？

因为js单线程的原因，在beforeUpload钩子中动态改变action的时候，数据并没有立刻被同步到Upload组件的action上，导致action用的仍是改变之前的值。

ajax请求跟dom渲染不一样，在dom渲染中，父组件数据没有及时同步到子组件一般不会遇到大问题。但是如果数据是当做ajax的请求条件，不及时更新就存在严重问题了。

### 解决办法

可以直接把Upload组件的ajax请求放到 nextTick中执行，这个时候beforeUpload中改变的数据都已经同步到子组件，所以ajax请求的时候用的是最新的数据。

**Comment by starding** [comment]
ha?
how?  it seems that I have to change the source code to solve this problem

**Comment by starding** [comment]
这问题下文了呀... 求问有没有其他人遇到这个问题，怎么解决的

**Comment by rijn** [comment]
You can process the file path by passing a promise to `beforeUpload`.  [Source code](https://github.com/iview/iview/blob/2.0/src/components/upload/upload.vue#L192)

**Comment by icarusion** [comment]
You can try to solve it according to the above answers.

**Comment by lixiaobin-bjhl** [comment]
beforeUpload () {
                var deferred = $.Deferred();
                this.action = 'XXX';
                this.$nextTick(()=> {
                    deferred.resolve();
                });
               return deferred
    }

返回一个promise 处理
