### ISSUE TITLE
Select超出底部边界问题，能否做到自适应呢？

### ISSUE THREAD

**Issue by gefangshuai** [iview/iview#1434]
### 复现步骤
就是如果一个select距离底部很近，滑出Popover被屏幕盖住，能否做到自适应呢？规则：优先取用户设置的placement，如果超出屏幕（屏幕上方或下方）则上滑或下滑
### 问题现象，以及你期望的结果是怎样的?
![](https://ws4.sinaimg.cn/large/006tNc79ly1fhsh013a6rj30n60jugn5.jpg)

**Comment by gefangshuai** [comment]
目前的解决方法是修改`dropdown.vue`中`update`方法。
原理：如果超出边界，则计算超出的高度，主动设置popover的最大高度为：popover高度-超出的高度，这样就可以出现滚动条，用户至少可以滚动选择。
使用了jQuery，实现代码如下：

```
this.$nextTick(() => {
   let $el = _$(this.$el);
   let h = $el.offset().top + $el.height();
   let wHeight = _$(document).height();
   $el.css('max-height', $el.height() - (h-wHeight) -50)
 });
```

![](https://ws2.sinaimg.cn/large/006tNc79ly1fhsix8vbl4j31b810qdmf.jpg)

**Comment by gefangshuai** [comment]
![](https://ws1.sinaimg.cn/large/006tNc79ly1fhsiy64266j30l60gajs7.jpg)

**Comment by icarusion** [comment]
There is no good solution for the moment.
