### ISSUE TITLE
table中的Poptip 如何防止冒泡

### ISSUE THREAD

**Issue by hellomrbigshot** [iview/iview#1436]
### 问题现象，以及你期望的结果是怎样的?
table每一行有一个点击事件，但是每行都有几格绑了poptip气泡框。
若用以下代码阻止冒泡则气泡框失效。
```
 <Poptip title="提示标题" content="提示内容">
        <Button @click.stop="">click 激活</Button>
  </Poptip>
```
### 你估计可能的原因是什么（选填）？
阻止气泡框事件冒泡。

**Comment by hellomrbigshot** [comment]
现在的方法是在poptip外层阻止冒泡。

**Comment by icarusion** [comment]
Update to the latest version and try again.

**Comment by ysyfff** [comment]
@hellomrbigshot ButtonGroup中的Button使用.stop同样不生效，在ButtonGroup外面一层使用就生效了。。。
