### ISSUE TITLE
多个Select组件rc.19版在联动时显示错误，每次必现

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [iview/iview#1437]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
macOS/Chrome 59

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/BWwVoy

### 复现步骤
每次必现。选中一级菜单，在联动的二级菜单随意选取一个选项。然后在一级菜单中另外选值，这时二级菜单刷新，二级菜单下拉显示正确，任意选择一个，显示的则为之前的数据相应索引的值(如果值一样的话)。见图：
<img width="156" alt="issue" src="https://user-images.githubusercontent.com/6437400/28500241-4c3d9b76-6ff7-11e7-90c6-16e67f1fa515.png">

### 问题现象，以及你期望的结果是怎样的?
显示和选项不一致。

### 你估计可能的原因是什么（选填）？
Select组件的bug

**Comment by hh-in-zhuzhou** [comment]
不好意思，才发现是这个 :key导致的，key的复用机制。显示已经正常了。

**Comment by lamking** [comment]
大哥 能说一下是怎么解决的吗
