### ISSUE TITLE
select组件下拉选项显示位置问题

### ISSUE THREAD

**Issue by qinshenxue** [iview/iview#144]
![1111111111111](https://cloud.githubusercontent.com/assets/10354498/21449850/54f86628-c92c-11e6-8b4a-76e42e9c99c2.gif)
如图所示，当select组件位置处于浏览器底部时，选项应该在上方展示，而不是在下方展示。

系统：windows 7
浏览器：chrome 55
iview版本：官网演示地址

**Comment by icarusion** [comment]
已知问题，目前对 popper.js 的处理上有问题

**Comment by qinshenxue** [comment]
ok

**Comment by YikaJ** [comment]
求此问题的进度是如何呢？

**Comment by baihe** [comment]
看样子是 drop 组件锚定到了 body，是准备要把 boundariesElement: "body" 去掉么？
不太理解锚定到 body 的原因。

**Comment by jinchuanchen** [comment]
不知道作者修复这个BUG没有。
原本想直接对原文件进行修改，然后想想还是等作者来吧。
然后自己用了一个土方法，代码如下：
`$("body").on("click", ".ivu-select-cm", function() {`
`var that = this;`
`setTimeout(function() {`
`var dropdown = $(that).find(".ivu-select-dropdown");`
`dropdown.css({"top": "auto", "bottom": "30px"});`
`}, 1);`
`});`
ivu-select-cm是定义在<i-select>上的class；这样子就可以使底部标记的i-select由上方展示。

希望作者能尽快修复这个BUG。加油~ 💪💪

**Comment by chenhaizano** [comment]
+1

**Comment by chenhaizano** [comment]
@jinchuanchen 为何不用CSS的方式

.ivu-select-cm .ivu-select-dropdown {
	top: auto !important;
	bottom: 30px !important;
}

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/f89dd9c28740685deb98ec9fe3f6b144decc4d76
目前增加了 placement 来手动控制展开方向

**Comment by baihe** [comment]
手动控制不算是个解决方案吧。

**Comment by TonyLuo** [comment]
在版本2.4.0里，设置placement="top"，没有改变pageSize时，pageSize选项位置显示正常，
![image](https://user-images.githubusercontent.com/3250305/31216702-2be691ae-a97a-11e7-98fd-3b9f7591d0c3.png)
当把pageSize改变后，页面数据增多时，pageSize选项位置显示不正常。
![image](https://user-images.githubusercontent.com/3250305/31216820-85b48b78-a97a-11e7-972f-b7f8479266c5.png)


<Page :total="100" :current="1"
              @on-change="changePage"
              @on-page-size-change ="changePageSize"
              placement="top"
              show-total show-sizer>
</Page>

**Comment by gefangshuai** [comment]
另外ElementUI的select是支持监听边界自动判断弹出位置的，希望作者能考虑加进来
@icarusion
