### ISSUE TITLE
layout左侧导航隐藏造成table列宽自适应失效

### ISSUE THREAD

**Issue by echodis** [iview/iview#1440]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
 2.4.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

// 因涉及到两个组件以及具体样式，附上仓库代码
https://github.com/echodis/iview-demo

### 复现步骤

1.刷新页面 -> 2.点击折叠左侧导航icon -> 3.查看table布局

![image](https://user-images.githubusercontent.com/12342645/28506840-c68ed70a-7060-11e7-9c4c-9410a4173b12.png)

### 问题现象，以及你期望的结果是怎样的?

**现象**： 在同时引用layout组件和table组件的情况下，左侧导航的隐藏导致table 布局width的增大，但table各列的宽度并未按比例增加。在对窗口resize后，table各列宽度才按比例正常显示。

**期望结果**：隐藏和展开导航时，table的宽度会随着所在content的宽度整体按比例放大或缩小。

### 你估计可能的原因是什么（选填）？

查看源码发现，计算table width时只监听了window的resize事件，似乎未考虑到layout组件造成的table布局的改变。个人开发时，通过增加`table {width: 100% !important}` 修复了这个bug。

为了更好地产品体验，还是希望开发同学可以关注这个问题。

**Comment by stevenwu2016** [comment]
是有这个问题，我手动触发了window.resize让他自动布局的

**Comment by Tilang** [comment]
同样的问题。望解决

**Comment by zbacao** [comment]
单独增加table {width: 100% !important}，并不能完全解决该bug，收缩时能重新定位table大小，但是点击恢复时，table大小还是会出问题。。

**Comment by kuerbb** [comment]
同样的问题，望解决

**Comment by zbacao** [comment]
已经解决了，如上面楼主说的，给全局添加table {width: 100% !important}即可，至少可以解决大部分的问题。

**Comment by icarusion** [comment]
#690
