### ISSUE TITLE
Date-picker的点击事件和直接编辑返回日期存在时区差距

### ISSUE THREAD

**Issue by liuyanshi** [iview/iview#1441]
### iView 版本号

2.0.0-rc.19
### 操作系统/浏览器 版本号

 macOS/Chrome 59
### Vue 版本号

v2.3.3
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/gesanghuayuan/pen/mMdOKa
### 复现步骤
 1. 先点击，比如选择2017-07-11, 输入框内提示是+8时区了，得到是 2017-07-11T00:00:00.000Z
 2. 但是在输入框中直接修改的时候， 也就是把2017-07-10改成2017-07-11的时候，得到的结果却是："2017-07-10T16:00:00.000Z
### 问题现象，以及你期望的结果是怎样的?
1. 希望点击的结果和直接编辑的结果是相同的
2. 因为无法捕获用户输入事件和点击事件（因为组件内部Input已经封装了），暂时没有想到更好的办法解决， 或者问下，如何覆盖组件内部的Input事件呢？
### 你估计可能的原因是什么（选填）？
1. 在picker.vue 里面的handleInputChange， 应该与点击处理相同， 希望点击和直接编辑返回的时区信息相同
2. 非常感谢

**Comment by hellomrbigshot** [comment]
貌似用v-model绑定的数据才有这个问题吧。别用v-model了呗

**Comment by icarusion** [comment]
Please update to the latest version first. If you have any questions, then open another issue.
