### ISSUE TITLE
Chrome浏览器export csv文件，文件内容过大下载失败

### ISSUE THREAD

**Issue by daigaobin** [iview/iview#1442]
### 问题现象，以及你期望的结果是怎样的?
export csv文件，文件内容过大，下载失败，希望能够正常导出
### 你估计可能的原因是什么（选填）？
export-csv.js文件中发现有以下代码：
![image](https://user-images.githubusercontent.com/11908263/28511538-3da5c6fe-7080-11e7-8309-826c5e9ea8c0.png)
其中增加了对浏览器类型的判断，只有Safari浏览器能够使用Blob二进制流导出，其他浏览器都不可以，如果文件内容过大，通过url导出的方式会失败，因为浏览器有长度限制，希望修改这里的判断的逻辑

**Comment by liuyanshi** [comment]
确实存在这样的问题， 我们现在的做法是先把作者的这部分逻辑抽取出来，这部分还是相对独立的。下载的时候调用抽取出来的代码。不过还是希望作者修正吧

**Comment by icarusion** [comment]
@liuyanshi 为什么不提交 pr 呢

**Comment by liuyanshi** [comment]
@icarusion 因为不会pr，这是实话，下次遇到问题，一定pr

**Comment by liuyanshi** [comment]
@icarusion 我来测试下，其他浏览器，因为还有IE之类的，没有测试。如果测试通过， 我会发起一次pr

**Comment by daigaobin** [comment]
chrome是可以用Blob下载的

**Comment by xiwadai** [comment]
同样遇到这样的问题，导出数据不到20M提示下载失败，谷歌也是
