### ISSUE TITLE
Table  render: (h, params) 找不到methods 里面的方法

### ISSUE THREAD

**Issue by mrerhuo** [iview/iview#1443]
### iView 版本号

2.0.0-rc.18
### 操作系统/浏览器 版本号

Chrome 59
### Vue 版本号
2.3.3

### 问题现象，以及你期望的结果是怎样的?
Table  render: (h, params) 找不到methods 里面的方法 不设置context 就没法获取methods的方法。但是，你们官网的例子又能获取到方法。我就纳闷了，你们这个到底搞啥？给的例子复制到本地测试，就不行。必须设置context,你们API又说废弃。好矛盾。

**Comment by icarusion** [comment]
Please ask questions as requested
