### ISSUE TITLE
按需引入-特别提醒-文档错误？

### ISSUE THREAD

**Issue by twolun** [iview/iview#1445]
### iView 版本号
2.0.2

### 操作系统/浏览器 版本号
Chrome 56

### Vue 版本号
2.2.3

### 能够复现问题的在线示例
![image](https://user-images.githubusercontent.com/11350403/28549075-8192a9e2-710a-11e7-90aa-23ca80953941.png)

### 问题现象，以及你期望的结果是怎样的?
```js
module: {
    rules: [
        { test: /iview\/src\/\.*?js$/, loader: 'babel' },
        { test: /\.js$/, loader: 'babel', exclude: /node_modules/ }
    ]
}

```

### 你估计可能的原因是什么（选填）？
不知道是不是vue版本、node版本的问题

**Comment by rijn** [comment]
it should have no problem
