### ISSUE TITLE
Select option标签中包含回车或空格，导致Select无法正常使用

### ISSUE THREAD

**Issue by stevenwu2016** [iview/iview#1448]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
 windows 8/Chrome 56

### Vue 版本号
2.3.4

### 复现步骤
这样没问题
`<Option v-for="option in storeForm.optionList" :value="option.id" :key="option.id">{{option.name}}</Option>`
这样就会出问题
`<Option v-for="option in storeForm.optionList" :value="option.id" :key="option.id">`
`{{option.name}}`
`</Option>`
![image](https://user-images.githubusercontent.com/22366480/28557000-79736940-713c-11e7-918a-b7d86978e5fe.png)

![image](https://user-images.githubusercontent.com/22366480/28557022-af032668-713c-11e7-9581-717d8fdfa1ee.png)

### 你估计可能的原因是什么（选填）？
select选择事件中应该过滤掉首尾的回车和空格

**Comment by SergioCrisostomo** [comment]
@stevenwu2016 version `2.3.2` is out. Is this still a problem? 
Can you provide a jsFiddle or Codepen example if the problem still exists?
