### ISSUE TITLE
Time-picker在单文件中加上 v-model 页面就会假死

### ISSUE THREAD

**Issue by ShiYun1985** [iview/iview#1454]
### iView 版本号

2.0.0-rc.19
### Vue 版本号

2.2.6
### 复现步骤
在线示例无法复现，只有在单文件中才会复现
`<Time-picker  v-model="dutyTimes" format="HH:mm" type="timerange" placeholder="选择时间"></Time-picker>`
### 问题现象，以及你期望的结果是怎样的?
在单页面组件中使用Time-picker,如果加上v-model 页面会假死
希望使用v-model也能够正确渲染
### 你估计可能的原因是什么（选填）？
我在控制台会看到一个TypeError: dateStr.search is not a function 的报错

**Comment by ShiYun1985** [comment]
今天早上试了一下又好了，好像是动态监听的值类型问题，应该是数组而不是字符串

**Comment by sunjincai** [comment]
不使用v-model也会报错，费解
渲染是能渲染出来，但是点选时间的时候，就会报这个错

**Comment by zhengxiaodong502** [comment]
我还是报那个错啊  dateStr.search is not a function 的报错 如何解决
