### ISSUE TITLE
iview 在exportCsv导出数据时，在都是数字的字符串时，会用科学计数法显示

### ISSUE THREAD

**Issue by xiwadai** [iview/iview#1456]
vm.$refs.table.exportCsv({
	filename: '渠道转化率数据',
	columns:vm.columns4,
	data: vm.exportitem
	});
### iView 版本号

2.0.0-rc.13
### 操作系统/浏览器 版本号

Windows
### Vue 版本号

2.2.2
### 问题现象，以及你期望的结果是怎样的?
iview 在exportCsv导出数据时，在都是数字的字符串时，会用科学计数法显示，期望不要按计数法显示，身份证号码，这些大的数字。

**Comment by stupidWall** [comment]
我也遇到这个问题，怎么解决

**Comment by liuyanshi** [comment]
参见 #1460

**Comment by liuyanshi** [comment]
@xiwadai @icarusion 麻烦 Close issuse
