### ISSUE TITLE
分页组件 bug 改变总条数 没有回到第1页

### ISSUE THREAD

**Issue by StanleyYechen** [iview/iview#1458]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
Windows/Chrome 58

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/StanleyYechen/pen/eEmXBv

### 复现步骤
分页组件初始化时当前不是第1页， 改变total总条数

### 问题现象，以及你期望的结果是怎样的?
分页组件初始化时当前不是第1页， 当改变total总条数时候  分页器没有回到第1页
应该回到第1页

### 你估计可能的原因是什么（选填）？
可能组件没有重新渲染

**Comment by Sciuridae** [comment]
我也遇到相同的问题，请问怎么解决？

**Comment by StanleyYechen** [comment]
手动把当前页重置成1就行了
https://codepen.io/StanleyYechen/pen/eEmXBv

**Comment by StanleyYechen** [comment]
在issue下回复了 你看下

发自我的 iPhone

**Comment by rijn** [comment]
#1562

**Comment by rijn** [comment]
@icarusion plz close this issue
