### ISSUE TITLE
分页组件 bug  current无效（重现步骤见示例）

### ISSUE THREAD

**Issue by StanleyYechen** [iview/iview#1459]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
Window/Chrome 58

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/StanleyYechen/pen/WEbmLo

### 复现步骤
详见示例

### 问题现象，以及你期望的结果是怎样的?
详见示例

**Comment by echodis** [comment]
因为changeTotal()中指定current为8啊...
改成下面就OK
```js
changeTotal() {
      this.current = Math.floor(Math.random()*8) +1;
}
```

**Comment by ChaoLeer** [comment]
ref获取page组件,然后直接设置currentPage = 8;

**Comment by icarusion** [comment]
@on-change
