### ISSUE TITLE
table组件导出csv文件, 如何设置excel单元格格式为文本？

### ISSUE THREAD

**Issue by stupidWall** [iview/iview#1460]

**Comment by liuyanshi** [comment]
> CSV （逗号分隔值文件格式
> 逗号分隔值（Comma-Separated Values，CSV，有时也称为字符分隔值，因为分隔字符也可以不是逗号），其文件以`纯文本形式(!!!)`存储表格数据（数字和文本）
> 摘自 [百度百科](https://baike.baidu.com/item/CSV/10739?fr=aladdin)

话句话说，导出的内容其实就是纯文本内容了

**Comment by stupidWall** [comment]
谢谢问答。我碰到的问题是这样的。导出的表格内容， 30420726094445466单号变成科学计数法形式， 数据就不对了， 想问一下有没有解决方案?

**Comment by liuyanshi** [comment]
1. 可以在调用this.$refs.table.exportCsv()的时候，对数据做一下toString()的处理
2. 科学计数法出现的原因有两种: (1)数值的小数点前面的数字超过21位 (2)小数点后面的数字超过5位
3. 30420726094445466这个数字长度没有超过21位, 我尝试了下，下载得到的csv用sublime或者记事本打开是没有用科学计数法显示的,仍然是30420726094445466。(记事本打开效果))
    > ![image](https://user-images.githubusercontent.com/12668546/28617706-12224ed4-7234-11e7-9667-7c7497f5dac1.png)

4. 但是在excel中打开就会显示科学计数法，所以这就是excel的问题了，需要设置下excel相关内容 (Excel 2007 打开效果)
    > ![image](https://user-images.githubusercontent.com/12668546/28617765-57a2b962-7234-11e7-9e19-a3b5b52ab13f.png)

5. 在(mac numbers) 打开却没有用科学计数法显示，所以excel的锅
   > ![image](https://user-images.githubusercontent.com/12668546/28617857-995eb6a8-7234-11e7-832e-b0d5453bbdf8.png)

**Comment by stupidWall** [comment]
赞，感谢分析，有了新的解决思路

**Comment by liuyanshi** [comment]
@stupidWall 麻烦 Close issuse

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/48965062-c882b980-eff0-11e8-9a91-d7ee03dd55c4.png)
![image](https://user-images.githubusercontent.com/8703951/48965064-e2bc9780-eff0-11e8-8ab0-efceec3ca646.png)
求解

**Comment by 531431988** [comment]
> ![image](https://user-images.githubusercontent.com/8703951/48965062-c882b980-eff0-11e8-9a91-d7ee03dd55c4.png)
> ![image](https://user-images.githubusercontent.com/8703951/48965064-e2bc9780-eff0-11e8-8ab0-efceec3ca646.png)
> 求解

设置了EXCEL格式显示为文本，同样的效果，双击显示如下
![image](https://user-images.githubusercontent.com/8703951/48965066-0e3f8200-eff1-11e8-884e-9ed6184154ed.png)

数据都错了？

**Comment by 531431988** [comment]
this.$refs.tableCsv.exportCsv({
quoted:true,
separator: ',=',
filename: '数据记录',
});
quoted是加双引号的意思
separator中加了 = 
根据其他网友 介绍 =“00001” csv文件会显示 00001

**Comment by 531431988** [comment]
加这个就解决了

**Comment by wjfengLove** [comment]
separator 中能设置多种符号么，导出的数据中有时候有空格，有时候有逗号，还有换行符，默认情况下，导出会位置错乱
