### ISSUE TITLE
折叠面板全部打开时，第一次点击无法折叠面板

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#1461]
### iView 版本号
2.0.0-rc.19 

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/YxPoEd

### 复现步骤
点击折叠面板
### 问题现象，以及你期望的结果是怎样的?
折叠面板全部打开时，随意点击一个面板，此时面板应当关闭，但是并没有反应，需要点击第二下，面板才会正常折叠与打开。

**Comment by icarusion** [comment]
Use `v-model`
