### ISSUE TITLE
upload组件的不足，建议把on-progress，on-success，on-error，on-preview，on-remove...改成事件，props有些时候，满足不了复杂需求

### ISSUE THREAD

**Issue by legend-li** [iview/iview#1464]
### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
 macOS/Chrome 56 

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

暂无！

### 复现步骤
暂无！
### 问题现象，以及你期望的结果是怎样的?
需求是：要求有多个（个数未知）上传组件，没个上传组件上传的图片/文件要提交到后台。
问题是：upload组件的on-success钩子不支持接受参数，因为是props，所以局限性很大。我没办法把当前循环到的upload组件的index传递到on-success钩子触发执行的函数中，那么我就没法把上传成功后的图片/文件地址回填到相应的data字段数据中。antd组件库的upload组件的on-success就是事件，可以接受参数，这样弹性空间更大，开发者可以更好的来处理上传成功后返回的数据。目前，我只能在点击upload组件的时候，把index记录到一个固定的变量中，不过这样只是最次的解决办法（而且容易出现问题，除非我自己写个上传组件，没时间写啊！！！吐血！！！）。要是把on-success改成事件，而不是props，就好弄多了。

**Comment by icarusion** [comment]
There is no such plan now.

**Comment by kingconan** [comment]
+1
确实是个问题。场景大概是 banner管理界面~

**Comment by lbcNewLife** [comment]
+2  同样遇到这个情况，我现在也是得我写个全局的来处理 很难受
