### ISSUE TITLE
Tabs导航不对应的BUG

### ISSUE THREAD

**Issue by 188007803** [iview/iview#1465]
### iView 版本号
2.0.0-rc.19

### 操作系统/浏览器 版本号
 win7/Chrome 56

### Vue 版本号
2.4.2

### 问题现象，以及你期望的结果是怎样的?
我的tabs 里的 tab-pane 是用 v-for 来渲染一个数组实现的。第一次渲染是正常的，但是更改数组后，tab-pane 也能跟着改变，但是相应的 tab-nav 是错的。 tab-nav 并没有跟着改变。

### 你估计可能的原因是什么（选填）？
我看了一下源码：

tabs.vue  里有这个方法，
```
   getTabs () {
           return this.$children.filter(item => item.$options.name === 'TabPane');
   },
```

updateNav 是根据这个方法来更新的，但是  this.$children 的顺序不一定是 tab-pane 的顺序，在devtools里都可以看出来，所以会导致nav和pane不对应的情况。

希望解决一下。

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
