### ISSUE TITLE
DatePicker输入无效日期字符报错

### ISSUE THREAD

**Issue by SamShiyun** [iview/iview#1466]
### iView 版本号

2.0.0-rc.19
### 操作系统/浏览器 版本号

macOS/Chrome 59
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

官网例子：
https://www.iviewui.com/components/date-picker
### 复现步骤
在DatePicker type='date'时中随意输入非日期字符串控制台报错

### 问题现象，以及你期望的结果是怎样的?
填入非法字符应该同daterange一样清空
### 你估计可能的原因是什么（选填）？
on-input-change事件
![default](https://user-images.githubusercontent.com/1575562/28656898-fba01b5c-72d6-11e7-8ab7-1a9bfd9b474f.png)

这里判断不是日期对象后，i 赋值了undefined，下一步parseDate的时候就会取长度失败报错

**Comment by CGerAJ** [comment]
input 加上readonly 即可解决 亲测可用~

**Comment by SergioCrisostomo** [comment]
@SamShiyun could you recheck if this is still a problem in `2.3.2`? In that case please provide a example.

**Comment by SergioCrisostomo** [comment]
I think this is same as fixed in https://github.com/iview/iview/pull/2002.
If not please provide example and reopen.
