### ISSUE TITLE
一名前端新人给iview团队的一点小小的建议

### ISSUE THREAD

**Issue by Xmb-form** [iview/iview#147]
### Vue 版本号

首先很感谢iview团队，我非常喜欢这一套年轻的UI框架，这是我第一次使用vue，配合一套UI框架，觉得很不错。在使用过程中我遇到了一些问题
我们的官方版本出来的datepicke及时更新了，我刚好赶上了，但是我作为一名新手，一：觉得在时间 daterange 类型上没有示例告知新手如何取值，二：还没有精确到时分秒。个人愚见，莫怪。

**Comment by icarusion** [comment]
Thx.
