### ISSUE TITLE
tabs的on-click方法没有生效

### ISSUE THREAD

**Issue by xxliud** [iview/iview#1470]
@on-click方法并没有进入方法

**Comment by xxliud** [comment]
![image](https://user-images.githubusercontent.com/8509171/28660166-8e0a1d32-72e4-11e7-8ca8-09d25a2017bb.png)

**Comment by xxliud** [comment]
![image](https://user-images.githubusercontent.com/8509171/28660194-a0ff30ee-72e4-11e7-962b-aade769b3669.png)

**Comment by rijn** [comment]
provide online jsfiddle

**Comment by MinWest** [comment]
我遇到了同样的问题，请问怎么解决的

**Comment by jennyliang220** [comment]
+1
