### ISSUE TITLE
DateTime 建议增加位置自适应

### ISSUE THREAD

**Issue by zrain** [iview/iview#1471]
（ 这条不是 BUG, 只是建议 ）
建议：datetime 在位置选项中可以增加 auto,  在判断显示位置的时候会自动适应来选择合适的显示位置。
增加理由：表单筛选项基本都会 row/col的自适应布局，很容易位置就会移动，设定的固定好的显示效果在不同的位置很难全部适用。

**Comment by icarusion** [comment]
#144
