### ISSUE TITLE
下拉菜单被走马灯的箭头按钮挡住了

### ISSUE THREAD

**Issue by chavyleung** [iview/iview#1477]
### iView 版本号
v2.0.0 Leo's Fortune

### 操作系统/浏览器 版本号
win10/Chrome 59

### Vue 版本号
2.4.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/chavyleung/pen/JyYEBM

### 问题现象，以及你期望的结果是怎样的?
现象：
    下拉菜单被走马灯的箭头按钮挡住了
期望：
   下拉菜单展开时应该挡住走马灯的箭头按钮
![image](https://user-images.githubusercontent.com/29748519/28698959-4a3e9e3a-7379-11e7-878e-11cc00c34a35.png)

### 你估计可能的原因是什么（选填）？
z-index?

**Comment by CGerAJ** [comment]
自己写z-index 就好了~ 增加组件内的定位 修改一个层级可能会导致出现更多的问题  我觉得你提的这个问题这个就不是问题

**Comment by lipuyu** [comment]
我没有找到这个调节z-index的方法
