### ISSUE TITLE
Checkbox 多选框不支持动态渲染的选项吗

### ISSUE THREAD

**Issue by yajore** [iview/iview#148]
### iView 版本号
0.9.10

### 操作系统/浏览器 版本号
WIN10/Chrome 55

### Vue 版本号
1.0.26

### 能够复现问题的在线示例
https://codepen.io/anon/pen/woNeMq

### 复现步骤
写了一个事例,2中情况区分开的,一种是写死check选项,一种是模拟ajax请求,返回数据之后动态渲染的选项
### 问题现象，以及你期望的结果是怎样的?
能否支持?

**Comment by icarusion** [comment]
fixed in 0.9.11

**Comment by yajore** [comment]
我用的就是圣诞前发布的版本,事例换成了0.9.11

**Comment by icarusion** [comment]
说错了，是在0.9.11（圣诞版）的下一个版本发布，问题以及修复。

**Comment by yajore** [comment]
你的意思是在0.9.12版本这个问题会解决吗?

**Comment by icarusion** [comment]
是的，本周会发一个新版

**Comment by icarusion** [comment]
原因是，CheckboxGroup 内的 Checkbox 动态使用时，无法识别为 group

**Comment by yajore** [comment]
感谢,你们的速度我一直很钦佩
