### ISSUE TITLE
iview的树形控件checkbox可以在被禁用掉的情况下被勾选上

### ISSUE THREAD

**Issue by misakamaiyako** [iview/iview#1483]

**Comment by misakamaiyako** [comment]
刚刚又试了一下，只要是在checkbox周围鼠标变成not-allowed的时候都有这个现象

**Comment by Hasyou99** [comment]
同样的问题，项目中用到，被测试提成了bug，正在看源码，寻找解决方案 @

**Comment by Fridolph** [comment]
在有问题的那个checkbox  disabled样式的那个， 加上pointer-events: none; 就好了~ 已提pr
不过这个属性不支持IE10及以下~  需要兼容的话可以加js判断
