### ISSUE TITLE
[建议]：表格导入

### ISSUE THREAD

**Issue by Uluer** [iview/iview#1485]
是不是能给表格加入导入excel表格的功能？

**Comment by Yunkou** [comment]
为什么会有这样的想法呢？好奇～
我能想到的是现实是
1. 上传控件上传 excel／csv 上传给服务器
2. 服务器解成业务需要的数据结构，持久化存储
3. 通过接口返回json 数据格式
4. 前端展示

在这个过程中 excel／csv to json 的过程 大部分和业务耦合。
1 4 环节和前端打交道 2 3 需要服务端完成 已经超出前端框架的范畴。

**Comment by Yunkou** [comment]
建议管理员关闭 issues

**Comment by YikaJ** [comment]
导入excel交给服务器做的 
就是 Yunkou 说的那样

**Comment by ChaoLeer** [comment]
可以试用一下xlsx,不过这个对表格文件的要求比较多,如果表格单行这种,可以一用
