### ISSUE TITLE
移动端访问官网出现错位

### ISSUE THREAD

**Issue by venter-zhu** [iview/iview#1486]
### 手机及其系统
型号：魅蓝5s 
系统：Flyme6.7.7.25beta
浏览器：系统自带浏览器

### PC系统及其浏览器
系统：win10
浏览器：chrome 59.0.3071.115 (64位)
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

![手机](https://user-images.githubusercontent.com/13394441/28709463-001e1756-73b3-11e7-8454-7ae4873f1d41.jpg)

![chrome](https://user-images.githubusercontent.com/13394441/28709506-29c63958-73b3-11e7-8533-b427abbeb488.jpg)

### 复现步骤
移动端访问 [https://www.iviewui.com/cli](https://www.iviewui.com/cli)，侧边栏直接呼出，占了半个屏幕
chrome访问以上网址，将浏览器左右缩放值手机大小也出现同样问题
### 问题现象，以及你期望的结果是怎样的?
div 重叠，各个块没有工作好？
### 你估计可能的原因是什么（选填）？
JS略懂皮毛，我也不知道啊。但我觉得应该是BUG

**Comment by DuLerWeil** [comment]
本来就不是为移动端准备的网站
