### ISSUE TITLE
select组件不支持change方法

### ISSUE THREAD

**Issue by Wells-coffee** [iview/iview#1488]
Select组件的文档中只有说有一个on-change事件，但是并没有说明怎么用，直接写在select标签中也并不能监听到change事件。

**Comment by songhlc** [comment]
@Wells-coffee  <Select @on-change='yourmethods'>

**Comment by luatnd** [comment]
Yes for anyone jumps straight into Vuejs like me, the document is not clear enough.
Even after I read [Vuejs documentation](https://vuejs.org/v2/guide/events.html), I still confuse how to use it, so I tried bruteforce to find the usage :smile: 
```html
v-on:change="handleRegionChange" 
@change="handleRegionChange"
v-on:on-change="handleRegionChange" 
@on-change="handleRegionChange"
```
It take time :-1: 
Anyway, many thanks for the great UI kit you have done.
