### ISSUE TITLE
table组件如何解决td是input输入框且为双向绑定

### ISSUE THREAD

**Issue by yajore** [iview/iview#149]
### iView 版本号
 0.9.11

### 操作系统/浏览器 版本号
WIN10/Chrome 55

### Vue 版本号
1.0.26

### 能够复现问题的在线示例
https://codepen.io/anon/pen/woNeMq

### 复现步骤
输入表格年龄,同时会改变表格的行数据
### 问题现象，以及你期望的结果是怎样的?
实现动态绑定

**Comment by icarusion** [comment]
你这里`:value.sync="${row.age}`的上下文是错误的，所以无法同步data

**Comment by yajore** [comment]
我并不是很理解上下文,如果有错,应该如何修改?

**Comment by icarusion** [comment]
render里的vue语句，都是所在的父组件作用域，你这里`${row.age}`是字符串。多看一下文档，介绍的很详细

**Comment by yajore** [comment]
ok,明白了,用了表格的data,加index,解决了,十分感谢
