### ISSUE TITLE
feature request:能否添加为Tag组件自定义颜色的功能

### ISSUE THREAD

**Issue by longfangsong** [iview/iview#1490]
现在Tag组件只有四种颜色（'blue', 'green', 'red', 'yellow'），觉得不是很够用。
能否让Tag可以自定义颜色（最好能使用CSS颜色表示法）?
（feature request和版本什么的无关吧……我就不提供版本号了，抱歉）
__________
Now the component Tag has only 4 colours（'blue', 'green', 'red', 'yellow'），I don't think that's enough。
Can the colour be customised（Had better use the colour system used by css）?
（I don't think this feature request has many thing to do with the version. So excuse me for not offering you my version code.）
PS. Excuse me for my broken English.

**Comment by icarusion** [comment]
update to new version.
