### ISSUE TITLE
请问form表单水平横向多行排列，如何验证里面的组件

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1492]
form表单虽然是可以指定水平排列，在一行满之后会自动换行。
我想控制一行有几格。
目前虽然是可以在form-item里用row栅格来控制数量，
但是这样就不知道怎么逐个来验证row里面的控件了，
因为form-item的验证是写在属性prop里面的

**Comment by zhougangnj** [comment]
里面再嵌套form-item，好像文档里有样例

**Comment by kiddkyd1412** [comment]
谢了，看了下文档确实是可以嵌套。但是这样写起来，感觉很别扭啊。
就好像在ul里写的不是li的感觉。。。你看


`<i-form ref="myForm" :model="form" :rules="ruleValidate" :label-width="100">
        <Row>
            <i-col span="8">
                <Form-item label="订单编号" prop="code">
                    <i-input v-model="form.code" placeholder="请输入"></i-input>
                </Form-item>
            </i-col>
            <i-col span="8">
                <Form-item label="订单编号" prop="projectCode">
                    <i-input v-model="form.projectCode" placeholder="请输入"></i-input>
                </Form-item>
            </i-col>
            <i-col span="8">
                <Form-item label="项目名称">
                    <i-input v-model="form.projectName" placeholder="请输入"></i-input>
                </Form-item>
            </i-col>
        </Row>
        <Row>
            <i-col span="8">
                <Form-item label="供应商" prop="supplier">
                    <i-input v-model="form.supplier" placeholder="请输入"></i-input>
                </Form-item>
            </i-col>
            <i-col span="8">
                <Form-item label="供应商联系人" prop="supplierUserName">
                    <i-input v-model="form.supplierUserName" placeholder="请输入"></i-input>
                </Form-item>
            </i-col>
            <i-col span="8">
                <Form-item label="供应商电话" prop="supplierMobile">
                    <i-input v-model="form.supplierMobile" placeholder="请输入"></i-input>
                </Form-item>
            </i-col>
        </Row>
        <Form-item label="备注">
            <i-input v-model="form.remark" type="textarea" :rows="2" placeholder="请输入"></i-input>
        </Form-item>
    </i-form>`
