### ISSUE TITLE
Tab标签页动态添加删除的问题

### ISSUE THREAD

**Issue by zhougangnj** [iview/iview#1493]
Tab标签页，根据数组数据动态加载情况

通过添加数据到数组，Tab标签页能动态刷新

但删除数组中某数据，Tab标签页并没有没有自动刷新减少

是我代码问题，还是tab标签页的bug？

代码大概如下：
        <Tabs size="small" type="card" v-model="reward" >
    
            <Tab-pane v-for="(r,index) in form.Rewards" :key="index" :label="'tab' +  index )" >    
            </Tab-pane>
            <span slot="extra">
                <Button title="减少" type="ghost" size="small" icon="minus" @click="minusPrize"></Button>
                <Button title="增加" type="ghost" size="small" icon="plus" @click="addPrize"></Button>
            </span>
        </Tabs>

minusPrize/addPrize里是调用数组的pop或push方法

**Comment by zhougangnj** [comment]
补充：
后来想用可关闭标签暂时绕过去，但也有问题
:closable="index == form.Rewards.length-1"

加了这个属性，可删除最后一个标签，初始加载时可以删除最后一个标签，但删除后，前一个标签上不出现删除图标（按上面条件应该要出现）

**Comment by SalonKrY** [comment]
是有这个问题。不要用源生的tab,自己写一个类样式的。删除数组某一个元素，tab标签页的样式没有自动删掉。

**Comment by rijn** [comment]
provide online jsfiddle

**Comment by pollux2015** [comment]
同样发现此问题

**Comment by pollux2015** [comment]
https://jsfiddle.net/pollux2017/ehyy9vo5/?utm_source=website&utm_medium=embed&utm_campaign=ehyy9vo5

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
