### ISSUE TITLE
iview导航刷新后失去当前高亮

### ISSUE THREAD

**Issue by bltbbb** [iview/iview#1494]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
 windows/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/prgoav

### 复现步骤
点击导航后 刷新当前高亮消失 
### 问题现象，以及你期望的结果是怎样的?
不能保存当前高亮状态 使用了vue-router中的router-link将导航文字包起来 刷新后即丢失状态 但该导航下组件状态还在

**Comment by bltbbb** [comment]
额
关闭吧
我自己的问题
抱歉~

**Comment by zhuanyongxigua** [comment]
@bltbbb 哥们你这个问题后来怎么解决的
