### ISSUE TITLE
Change switch color 

### ISSUE THREAD

**Issue by Goblenus** [iview/iview#1496]
Is there any way to change switch open-close color?

**Comment by YikaJ** [comment]
[here](https://www.iviewui.com/docs/guide/theme-en)

**Comment by Goblenus** [comment]
@YikaJ Thanks for your reply. Yep I miss this doc page. But It is not what i'm looking. I want to change open-close color at one switch element, not at all elements in my proj. I noticed that it uses background-color and border-color prop in .ivu-switch-checked class, and I think it may be changed by replacing by style prop, but it is not the right way.

**Comment by YikaJ** [comment]
@Goblenus Maybe you could give the i-switch a class, and then make your own css like this.

```
<template lang="html">
  <i-switch class="my-switch"></i-switch>
</template>
<style lang="css">
  .my-switch.ivu-switch-checked {
    border-color: red;
    background-color: red;
  }
</style>
```

**Comment by Goblenus** [comment]
@YikaJ No it's the wrong way. If I do this, I'll have all time red switch. At this way I need to catch switch event to change style props. I think it's a decision.

But maybe (only maybe) need to add type-open and type-close props to i-switch to have an opportunity to change colors.

**Comment by YikaJ** [comment]
nope..do you ensure you have write the classname right ? I can give you an example, and it only be red when it truns on, and grey when it truns off.
https://codepen.io/anon/pen/zdrgMW

**Comment by Goblenus** [comment]
@YikaJ Ow...my bad, yep you're right. But I also need to change switch close color.

**Comment by YikaJ** [comment]
@Goblenus Just use css level to cover, it works.[demo](https://codepen.io/anon/pen/zdrgMW)

```css
.my-switch.ivu-switch {
    border-color: blue;
    background-color: blue;
}
.my-switch.ivu-switch.ivu-switch-checked {
    border-color: red;
    background-color: red;
 }
```

**Comment by Goblenus** [comment]
@YikaJ Oh...great! Thanks a lot.
