### ISSUE TITLE
vue 2.4.x下 $Modal 弹出框报警告, DatePicker 弹出报警告。

### ISSUE THREAD

**Issue by 188007803** [iview/iview#1498]
### iView 版本号
2.0.0

### 操作系统/浏览器 版本号
 QQ浏览器最新版

### Vue 版本号
2.4.2

### 复现步骤
```
<i-button @click="$Modal.info({title: 'info', content: 'info'})">弹出Info</i-button>
<i-button @click="$Modal.confirm({title: 'confirm', content: 'confirm'})">弹出confirm</i-button>
<Date-picker v-model="testDate"></Date-picker>
```

### 问题现象，以及你期望的结果是怎样的?
这三个组件在点击时，在vue2.3.4下没有问题，但在vue2.4.1/2.4.2下，会报警告：
截图如下：
弹出info
![modal info](https://user-images.githubusercontent.com/10063364/28753343-988a2110-7566-11e7-9530-170734df3fca.png)
弹出confirm
![modal confirm](https://user-images.githubusercontent.com/10063364/28753344-a77be0be-7566-11e7-8736-b286fb877988.png)
datepicker
![datepicker](https://user-images.githubusercontent.com/10063364/28753346-acd599f6-7566-11e7-8349-07ea1de529e0.png)

### 你估计可能的原因是什么（选填）？
估计和 vue 2.4.x 版本的 $attrs 功能有一定冲突。

**Comment by ArcherDing** [comment]
me too.

**Comment by icarusion** [comment]
提供能够复现问题的在线链接

**Comment by 188007803** [comment]
我在codepen里用试了，没有出现问题，我发现是这个原因，如果用<script>标签引入iview就是正常的，但是用webpack打包就会出现以上情况。

**Comment by icarusion** [comment]
provide online code or repo please

**Comment by fjonas** [comment]
这个问题是存在的, 建议reopen等重现repo

**Comment by dingyiming** [comment]
2.7.3 依然有这个问题，
