### ISSUE TITLE
iview icon打包问题

### ISSUE THREAD

**Issue by prpr2012** [iview/iview#1499]
iview 打包之后 找不到自带的icon图片，而且路径重复

**Comment by prpr2012** [comment]
iview 打包之后 找不到自带的icon图片，而且路径重复

**Comment by snowy520** [comment]
包的路径应该是/static/css/ionicons.05acfdb.woff
但实际路径是/static/css/static/fonts/ionicons.05acfdb.woff
应该怎么解决？

**Comment by rijn** [comment]
I believe it's due to your webpack config.
