### ISSUE TITLE
iview是否可以以单文件的方式进行引入？

### ISSUE THREAD

**Issue by anshengme** [iview/iview#15]
就像引入`vuejs`那样，

`<script src="//cdn.bootcss.com/vue/1.0.28/vue.js"></script>`

另外是否有QQ或者微信群呢？

**Comment by icarusion** [comment]
后面有将每个组件编译为独立js来使用的计划，不过暂时还没有精力写。

**Comment by anshengme** [comment]
目前的使用方式是怎样的呢？需要用到那些栈，刚入手vuejs，看到这个UI特别喜欢，我是后端的，so，前端一些自动化构建的东西还不是太懂。

**Comment by icarusion** [comment]
https://www.iviewui.com/docs/guide/start 看下文档这里有详细的介绍

**Comment by anshengme** [comment]
thx
