### ISSUE TITLE
强烈建议增加更多级菜单，不然只能使用Menu Group,连收起和展开都做不到，一旦子菜单多了，很长很长

### ISSUE THREAD

**Issue by sunfaces** [iview/iview#1500]
### 你估计可能的原因是什么（选填）？

![e3dfed8f-00ce-4738-a333-2833fcbf847b](https://user-images.githubusercontent.com/7036754/28760913-732c57a4-75dd-11e7-9f1c-e63f0b0a9e9d.png)

如图，当系统列表中的系统越来越多时，Openapm的子系统就无法收缩起来，会非常非常长

**Comment by blacksunset** [comment]
+1

**Comment by icarusion** [comment]
已知
