### ISSUE TITLE
iview 日期插件Date-picker 禁止disabledDate月份 结果错误

### ISSUE THREAD

**Issue by Jaction** [iview/iview#1503]
iview 日期插件Date-picker 禁止disabledDate月份 结果错误
![image](https://user-images.githubusercontent.com/17811893/28762187-ed533b02-75e6-11e7-8ea5-2d19b8ae22b7.png)
![image](https://user-images.githubusercontent.com/17811893/28762191-fa2ee8f8-75e6-11e7-9b65-88fdac6b3c89.png)

**Comment by SergioCrisostomo** [comment]
@Jaction can you please provide a example so we can test this problem?

使用下面的在线链接可以快速创建示例
https://codepen.io/anon/pen/KvJJdw
