### ISSUE TITLE
望 checkbox 增加 size 属性

### ISSUE THREAD

**Issue by iduma** [iview/iview#1507]
希望官方在 checkbox 控件里增加 size 属性，这样有利于统一外观样式。
感谢！

**Comment by SergioCrisostomo** [comment]
@icarusion, @rijn: Would it be interesting to have 3 sizes for the checkbox like with the buttons? 
(Large, Medium, Small)

If this is a interesting feature I could send a PR proposal.

**Comment by rijn** [comment]
@SergioCrisostomo I believe it would be a good idea. But before you start, you probably wish to talk to @icarusion since we have some UX/UI persons who have designed the whole project. We wish to keep this consistency. =)

**Comment by icarusion** [comment]
@SergioCrisostomo sorry for reply now. I will talk about with our UI designers in next week, and I will reply you again.

**Comment by icarusion** [comment]
I discussed it with the designer and concluded that both the Checkbox and Radio should have two sizes, default(now) and small, corresponding to the 14px and 12px text font-size.
Here is the design: 
![image](https://user-images.githubusercontent.com/5370542/29595530-9a10c912-87ea-11e7-8340-e3986be044c6.png)

** But I think 12px(small) size is too small, So I think there can be three sizes: small, default(now), large,  corresponding to 12px 14px 16px font-size. **
@SergioCrisostomo what do you think?

**Comment by icarusion** [comment]
77f1cc2
4d54542
