### ISSUE TITLE
表单元素不能设置只读吗

### ISSUE THREAD

**Issue by bltbbb** [iview/iview#1508]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
win10/Chrome 56

### Vue 版本号
 2.2.1

### 复现步骤
表单元素没有设置readonly的api
### 问题现象，以及你期望的结果是怎样的?
表单元素可以设置readonly

**Comment by HHH1994** [comment]
可以设置disabled吧

**Comment by YikaJ** [comment]
大兄弟，是没看文档么？
https://www.iviewui.com/components/input#API，readonly 找找看
