### ISSUE TITLE
建议，基础 表单元素希望都加上 Name 属性

### ISSUE THREAD

**Issue by qmdx** [iview/iview#1509]
场景， 很多时候不希望挨个去拿到组件值，希望 form serialize 就可以搞定， 如果不支持 name 属性会引入很多麻烦的取值。

 https://www.npmjs.com/package/form-serialize

**Comment by JD-Wang** [comment]
```
formValidate: {
    name: '',
    mail: '',
    city: '',
    gender: '',
    interest: [],
    date: '',
    time: '',
    desc: ''
},
```
喏，你把formValidate提交上去不就好了

**Comment by YikaJ** [comment]
你的组件思路不对，如果写对了，怎么会挨个取呢？组件值你都存在this.data的某个属性上，比用 dom 去取清晰多了。


```
export default {
  data() {
    return {
      formData: {
        name: '',
        email: ''
      }
    }
  },
  methods: {
    submit() {
      const data = serialize(this.formData)
      ajaxPost(data)
    }
  }
}
```

**Comment by qmdx** [comment]
@JD-Wang @YikaJ  二位要定义 formData 其实会涉及到不用定义直接序列化更方便

**Comment by YikaJ** [comment]
不定义formData，就不能让 input 的值和 UI 其它地方与该值有联动的地方实时变化。既然定义了，就可以直接将 formData 序列化后提交，无需再根据 name 去取值了。
当然简单UI有简单做法，既然已经有很好的解决方法了，我个人觉得就不需要为表单提供 name 属性了。

**Comment by qmdx** [comment]
@YikaJ  举个例子：搜索条  不需要联动， 直接拿到输入 select radio 等序列化的结果 提交，没有必要用一个临时变量去存取

**Comment by qmdx** [comment]
@YikaJ  如下直接拿 搜索 数据 合并翻页参数提交即可，不希望维护一堆临时变量和各种 on-change 方法

```
_searchParams() {
        var data = this.$serialize('search-form');
        return this.$extend(data, this.pageParams);
      },
```

**Comment by YikaJ** [comment]
Oh ,now your data are both in your dom and your javascript, Good luck to maintain it.

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
