### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by KIDJourney** [iview/iview#1510]
### iView 版本号
2.0.0-rc.17

### 操作系统/浏览器 版本号
MaxOs/Chrome 59.0.3071.115

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://www.iviewui.com/components/form#表单控件

### 复现步骤
在表单控件这部分，switch组件使用了`<Switch>`这个标签，但是这个标签在代码中是不可使用的。

### 问题现象，以及你期望的结果是怎样的?
我期望文档中的标签是`<i-switch>`

### 你估计可能的原因是什么（选填）？
文档错误

垃圾后端第一次写前端，有错轻喷。

**Comment by ChaoLeer** [comment]
注意：非 template/render 模式下，需使用 i-form。

**Comment by icarusion** [comment]
Thx.

**Comment by KIDJourney** [comment]
@icarusion 我以为是我用错了= =就给关了。。
