### ISSUE TITLE
建议，增加可编辑Table的功能

### ISSUE THREAD

**Issue by dusdong** [iview/iview#1513]
做表单式窗口经常会用到可编辑Table，请问是否有这方面的计划？

**Comment by rijn** [comment]
`render`

**Comment by blacksunset** [comment]
+1

**Comment by icarusion** [comment]
暂时还不太考虑iView支持单元格编辑功能。

**Comment by Neo-J** [comment]
写一个自定义组件，双击变成Input，然后通过render渲染到table的col中，监听修改事件同步修改table的data就可以了

**Comment by Gxiaomin** [comment]
经常会用到可编辑Table，建议增加表格编辑

**Comment by Gxiaomin** [comment]
@icarusion

**Comment by lison16** [comment]
可参考iview-admin可编辑表格

**Comment by Javebean** [comment]
@icarusion @lison16  iview-admin那个太烦了。可以考虑加一下表格编辑功能吗？

**Comment by tristan-tsl** [comment]
在写大量重复性的表单时发现可编辑表格确实能提高开发效率、节省时间

**Comment by xiaogu-space** [comment]
建议增加编辑表格功能
