### ISSUE TITLE
Select 选择器开启远程搜索后，默认值不显示label而显示value

### ISSUE THREAD

**Issue by waney** [iview/iview#1514]
如题。
非remote 模式正常。

### iView 版本号
 2.0.0

### 问题现象，以及你期望的结果是怎样的?
``Select v-model="1" filterable remote :remote-method="remoteMethod" :loading="loading"

Option v-for="item in List" :value="item.value" :key="item.label">{{ item.label }}</Option

List: [{value: 1, label: 'aaaa'}]``

Select默认值显示1而不是 aaaa，非remote 模式正常。

**Comment by 2hz4917** [comment]
this problem has solved?

**Comment by shiwuhao** [comment]
问题解决了吗?我也遇到你了该问题了
