### ISSUE TITLE
您好，请问upload组件怎么获得当前上传的文件 

### ISSUE THREAD

**Issue by wangzy123** [iview/iview#1515]

**Comment by ihuguowei** [comment]
`before-upload` ：上传文件之前的钩子，参数为上传的文件，若返回 false 或者 Promise 则停止上传
https://www.iviewui.com/components/upload
请善用文档，另外不建议在 issues 中提问使用困惑。

**Comment by waney** [comment]
befor-upload里返回的file是
`File {name: "a.jpg", lastModified: 1476928557653, lastModifiedDate: Thu Oct 20 2016 09:55:57 GMT+0800 (中国标准时间), webkitRelativePath: "", size: 170095…}
lastModified
:
1476928557653
lastModifiedDate
:
Thu Oct 20 2016 09:55:57 GMT+0800 (中国标准时间)
name
:
"a.jpg"
size
:
170095
type
:
"image/jpeg"
webkitRelativePath
:
""
__proto__
:
File`

**Comment by waney** [comment]
真的是不知道怎么搞好，用IView的都是前后端分离的，这样在开发的时候要POST提交到这个Action，如果不走Ajax真没想到办法。

**Comment by rijn** [comment]
I'm using [form-data](https://github.com/form-data/form-data) currently.

**Comment by ssibre** [comment]
@waney Upload默认用的form-data提交，API接口里面不用参数，.Net里面使用 HttpContext.Current.Request.Files接收。翻了1天的baidu才研究明白。

**Comment by p2ng** [comment]
下午我也想尝试通过`this.$refs.upload.$refs.input`获取input的DOM对象，但是其实`iView`已经封装好返回的数据格式了。
本意是获取上传图片的路径，然后
```
let img = new Image()
img = this.$refs.upload.$refs.input.value

img.width
img.height
```
进行一些业务判断的，但其实并不生效。最终只能靠上传到后端来判断。并且每次上传前通过header传入自定义参数。够恶心的。

**Comment by qiqingfu** [comment]
为什么通过手动上传,通过before-upload钩子中的参数获取到file文件。然后手动提交post请求将file作为参数。请求中请求头携带的数据`file成了空对象{}`, 有遇到过这种情况的朋友吗? 怎么解决
