### ISSUE TITLE
form表单中rules校验不通过时error信息显示异常

### ISSUE THREAD

**Issue by Estelle00** [iview/iview#1517]
示例中radio切换到2输入一个不满足条件的数据，然后切换radio到3 error信息不消失
在线示例链接
https://codepen.io/Estelle00/pen/vJKjXR

**Comment by rijn** [comment]
I suggest you use `v-show` instead.

**Comment by Estelle00** [comment]
你好 这样form表单校验的时候回对其做验证 怎么处理呢
