### ISSUE TITLE
Select v-model 与 on-change 事件冲突

### ISSUE THREAD

**Issue by zrain** [iview/iview#1520]
多选时不设置 v-model 当修改 select 选项时候报错 
：_this5.model.push is not a function
当时设置 v-model ，绑定 on-change事件，在事件处理中动态修改数据，将导致无限触发on-change事件导致死循环

**Comment by huanglei1991** [comment]
我的情况是用vuex 然后每次给vuex值的时候都去了引用,然后新的数组引用 还会触发回调....然后就死循环了

**Comment by songhlc** [comment]
@zrain 我使用方式是在on-change事件里 先判断v-model绑定对象的length和onchange事件参数返回的值length是否一样，不一样才动态修改数据，这样就不会死循环了

**Comment by xxliud** [comment]
刚发现的问题，绑定了v-model on-change事件触发了8次

**Comment by qxl1231** [comment]
我也遇到了这个问题,谁有好的办法?
![image](https://user-images.githubusercontent.com/8305742/35954926-5b45cd2e-0cc7-11e8-8e30-a8185db71001.png)

**Comment by sowork** [comment]
@qxl1231 请问解决了么？
