### ISSUE TITLE
iview单文件组件写class不能正确应用样式，及scrollbar的样式bug

### ISSUE THREAD

**Issue by Fridolph** [iview/iview#1522]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
windows/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/anon/pen/mMEgeX

## 问题现象，以及你期望的结果是怎样的?

1. 我在模版里给了 class="demo" 样式直接写能生效，但在我的单文件组件里直接写 样式不能生效，滚动条样式没有变化
（想问下是不是scoped的原因）

2. 这里的scrollbar样式是生效的…  只给了4px的宽， 但iview里的 table宽度依然是 默认scrollbar的宽度？

**Comment by rijn** [comment]
1. Yes, this problem is caused by `scoped`.
2. Your demo looks good to me, i.e. the scroll bar width has been changed. What do you want to ask?

**Comment by zjafei** [comment]
只能不加scope么
