### ISSUE TITLE
Select remote data

### ISSUE THREAD

**Issue by agungjk** [iview/iview#1523]
How to set selected data on remote select component?

**Comment by rijn** [comment]
use `v-model` to bind `value`

**Comment by agungjk** [comment]
Not working for remote data @rijn

**Comment by rijn** [comment]
What kind of remote data do you wish to use? Can you provide the jsfiddle?

**Comment by agungjk** [comment]
Fix, using setQuery method on select component. Thanks for reply 🥇 @rijn

**Comment by Lee-xiang** [comment]
Actually, still not working with v-model
