### ISSUE TITLE
Form 没有宽度自适应

### ISSUE THREAD

**Issue by GwYL** [iview/iview#1526]
![image](https://user-images.githubusercontent.com/25656592/28903462-8ffb0eaa-7837-11e7-80f9-93d78c968958.png)

**Comment by shoyuf** [comment]
当 table 的 width 发生改变(隐藏侧边栏)的时候表格里面的 columns 的宽度没有做出自动适应,浏览器 window 的宽度改变的时候(调整窗口大小)却做了自适应

**Comment by shixuev5** [comment]
window.dispatch(new Event('resize'));

**Comment by no5no6** [comment]
临时解决方案
```
html:
<Table ref='tableData' :columns="table.columns" :data="table.data" ></Table>

js:
window.onresize = event => {
  this.$refs.tableData.handleResize();
}
```

**Comment by shaonq** [comment]
```
/** css **/
.ivu-table-auto table{
    table-layout: auto; 
    width: 100% !important;
  }
```
```
<!--  html  -->
<Table class="ivu-table-auto"></Table>
```
再不改变原来代码的基础上扩展了一个class来修复这个问题。

**Comment by GwYL** [comment]
@shaonq 嗯，用这种方法才可以。

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。

**Comment by xiaohaiH** [comment]
@shaonq  看了很多 issues, 就你这个行, 感谢分享~
