### ISSUE TITLE
在modal打开新modal给父级modal遮盖问题

### ISSUE THREAD

**Issue by bao2314483** [iview/iview#1528]
在modal打开新modal给父级modal遮盖问题
我看了modal统一样式css  z-index:1000
请问怎样在modal打开新modal可设置z-index属性,或者自动递增z-index来解决父modal遮盖子modal的问题

**Comment by icarusion** [comment]
提问请到 sf，github 不接受提问。

**Comment by bao2314483** [comment]
sf是什么意思?

**Comment by aamis520** [comment]
sf:https://segmentfault.com/news
