### ISSUE TITLE
栅格的占位格数为0时 col的display却是block

### ISSUE THREAD

**Issue by zovlqa** [iview/iview#153]
### iView 版本号

"iview": "^0.9.10"

### 操作系统/浏览器 版本号

macOS/Chrome 54
### Vue 版本号

"vue": "^1.0.26",
### 能够复现问题的在线示例

http://codepen.io/Ryzi/pen/RoXGVN
### 问题现象，以及你期望的结果是怎样的?

设置栅格的占位格数后，能实现相应的设置
### 你估计可能的原因是什么（选填）？
属性设置未生效

**Comment by icarusion** [comment]
Thanks

**Comment by zovlqa** [comment]
@icarusion 感谢快速响应及修复，我现在应该怎么获取最新的修复版本，npm update 还是需要自己丛源码编译一次？
