### ISSUE TITLE
[建议] select远程过滤可添加context输入,传入其他select的值参与过滤

### ISSUE THREAD

**Issue by leopard7777777** [iview/iview#1531]
例如 第一个 select 选择了 color
第二个 select 传入 color 的 id, 查询的结果都是 color 的属性值

第一个 select 选择了 size 
第二个 select 传入 size 的 id, 查询的结果都是 size 的属性值

这样就不单纯只根据query来过滤记录

**Comment by icarusion** [comment]
iView 只是提供基础组件，业务相关的需要自己实现。
另，你的需求应该使用 Cascader 而不是 Select。
