### ISSUE TITLE
Tabs从中间删除一个标签页再增加一个标签页会出现bug

### ISSUE THREAD

**Issue by wangweida** [iview/iview#1532]
http://jsbin.com/duxigejiqi/1/edit?html,js,console,output

增加两页从中间删除在增加会出现bug

**Comment by wangweida** [comment]
看了看其他答案，可以把key变成new Date解决问题，但是这只是理论上的，因为增加删除tab的时候所有tab是整个重新渲染生成的，没有一点复用，类似你有5个tab，只删除了最后一个，但是前4个全都重新生成了一遍，如果里面只有文字什么的还好，但是一旦稍微复杂了就不行了，而且更麻烦的是一旦tab的父组件update之后，就算tab组件没有变化依然全部重新生成，明显能看到卡顿。

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
