### ISSUE TITLE
在实现   Select   多级联动时，二级，三级回显BUG，更换一级二也更换了，但是在显示的时候依然显示的是上一次的Lable，

### ISSUE THREAD

**Issue by lazyyman** [iview/iview#1536]

**Comment by zrain** [comment]
遇到了同样的问题，联动lable显示错误问题，没人看么 ？

**Comment by lazyyman** [comment]
@zrain 并没有人看，然后我就用原生的select ，就不会出这个问题

**Comment by zrain** [comment]
@lazyyman 我刚找了一个处理方式，我没有去看它的源代码，不过我尝试改变了 :key 的值不再是index,而是其他值比如 item.value 现在动态切换好使了。我参考的是官网远程搜索的例子，不过如果 key=index 的情况下还是不好使，希望对你有所帮助。

**Comment by lazyyman** [comment]
@zrain 好的，我待会试试

**Comment by icarusion** [comment]
Why not provide an online example

**Comment by forwardZhang** [comment]
@zrain     感谢，解决了问题，

**Comment by Zefeng666** [comment]
> @lazyyman 我刚找了一个处理方式，我没有去看它的源代码，不过我尝试改变了 :key 的值不再是index,而是其他值比如 item.value 现在动态切换好使了。我参考的是官网远程搜索的例子，不过如果 key=index 的情况下还是不好使，希望对你有所帮助。

太牛了，搞了一晚上没搞成，太感谢了
