### ISSUE TITLE
更新后modal里面的select下拉框错位，如果页面有滚动条就会出现

### ISSUE THREAD

**Issue by yangchao313** [iview/iview#1537]
错误示例：

https://codepen.io/anon/pen/EvNymG

**Comment by yangchao313** [comment]
![error](https://user-images.githubusercontent.com/28328549/28955060-eb5edefa-7915-11e7-9ff0-fce7ffce35a8.png)

**Comment by lily920416** [comment]
我也有这个问题，不知道该如何解决？我看到.ivu-modal .ivu-select-dropdown {
    position: absolute!important;
}，把这个去掉就可以了，但是不知道该怎么去掉，作者加了!important，想覆盖都覆盖不了

**Comment by icarusion** [comment]
Use `transfer` prop.

**Comment by lenxeon** [comment]
@icarusion 请问我这种情况呢？https://codepen.io/lenxeon/pen/QqryXy
