### ISSUE TITLE
Table in Collapse

### ISSUE THREAD

**Issue by zhangxyjack** [iview/iview#1539]
在折叠面板中使用Table表格组件，会使得表格默认不是填充100%
https://codepen.io/anon/pen/vJyyxQ

**Comment by zhangxyjack** [comment]
![image](https://user-images.githubusercontent.com/21165482/28956931-13622d2e-7922-11e7-8432-398f95369273.png)

**Comment by zhangxyjack** [comment]
![image](https://user-images.githubusercontent.com/21165482/28959097-8dd48da0-792b-11e7-8a45-c4e6eb27a264.png)
给table设置height，如果表格内容大于此值，会被隐藏，不能滚动

**Comment by icarusion** [comment]
Update to the latest version.

**Comment by zhangxyjack** [comment]
@icarusion 
![image](https://user-images.githubusercontent.com/21165482/28959750-66aaf586-792e-11e7-947a-29383cb83ca2.png)

My version is the latest version of 2.0.0

**Comment by ysneo** [comment]
最新版还是有同样的问题
