### ISSUE TITLE
不知道可否加个Calendar组件？另外，时间选择器format无法显示中文 星期“几"（大写），给的都是基于数字

### ISSUE THREAD

**Issue by Ncare** [iview/iview#1540]
RT， 非DatePicker.

**Comment by rijn** [comment]
to ur second problem, I suggest to do it yourself. It's pretty simple to remap the value.

**Comment by SergioCrisostomo** [comment]
Closing as dup of https://github.com/iview/iview/issues/1910

**Comment by shichzh** [comment]
@Ncare 请问您是怎么实现的？我在on-change事件中处理完之后，页面上的datePicker组件不显示内容了
