### ISSUE TITLE
select not working on tab key

### ISSUE THREAD

**Issue by agungjk** [iview/iview#1542]
Error when focus on select using tab, but working normally using focus on click
![vhz0s5npye](https://user-images.githubusercontent.com/6745353/28966871-b7fcb29e-7942-11e7-8af8-5578131fe152.gif)

**Comment by thearabbit** [comment]
+1, the same as `date, time picker, checkbox, radiobox`

**Comment by agungjk** [comment]
i try to fix this issue, please review my code @icarusion 
#1614

**Comment by thearabbit** [comment]
did fix already?
👍

**Comment by icarusion** [comment]
#764
