### ISSUE TITLE
Page has a bug with dynamic calculate

### ISSUE THREAD

**Issue by YikaJ** [iview/iview#1543]
demo: https://codepen.io/anon/pen/mMOZNO
version: iview-2.0.0

page 动态计算时有个 bug。
重现方法：点击 -1，会出现页码为 1 2 3 2。
期望是：当前 current 页变为2，且第三页消失，页码为 1 2

**Comment by liufeics** [comment]
page-size这个参数你要加上去，而且你动态修改数据的时候最好把current设置为1，不然数据会错乱。这确实是一个bug
