### ISSUE TITLE
Table 固定首尾列, 列数过多时, 滚动条解析有问题, 列对应不齐

### ISSUE THREAD

**Issue by LenPing** [iview/iview#1544]
![image](https://user-images.githubusercontent.com/7878398/28996825-af28a874-7a39-11e7-895c-0fdb89887de1.png)

官方例子, 仅增加了数据和列数, 代码如下:

[dataview.zip](https://github.com/iview/iview/files/1202498/dataview.zip)

**Comment by LenPing** [comment]
代码文件附上
[dataview.zip](https://github.com/iview/iview/files/1202497/dataview.zip)

**Comment by LenPing** [comment]
width="100%" 导致, 可考虑是否修正.

**Comment by icarusion** [comment]
width 暂不支持百分比，请使用像素，如还有问题，请另开一个issues，并附上在线示例链接。
