### ISSUE TITLE
弹窗的表单没有用户操作出错中断功能，点击确定都会直接关闭

### ISSUE THREAD

**Issue by ZhuLiangT** [iview/iview#1545]

**Comment by liufeics** [comment]
建议自定义button这样你就可以控制modal是否关闭了，原来的ok好像是先关闭再执行代码

**Comment by rijn** [comment]
We'll support promise soon

**Comment by alvin198761** [comment]
问下这问题解决掉了没有啊，我想买刚刚开始，不要让我推了,这个功能很严重啊，我表单验证失败，居然给我自动关闭了，苦逼啊

**Comment by alvin198761** [comment]
有没有别的替代方案啊，这个成了一个大问题了，

**Comment by BengBu-YueZhang** [comment]
我也是

**Comment by alvin198761** [comment]
楼上的,我被逼换回element ui 了,哎,..耽误我几天时间
