### ISSUE TITLE
Select 开启filterable,在disabled情况下可以输入

### ISSUE THREAD

**Issue by warriorg** [iview/iview#1547]
看了下 Select的源码，Input的部分没有应用 Disabled

**Comment by warriorg** [comment]
`<input
                type="text"
                v-if="filterable"
                v-model="query"
                :class="[prefixCls + '-input']"
                :placeholder="showPlaceholder ? localePlaceholder : ''"
                :style="inputStyle"
                @blur="handleBlur"
                @keydown="resetInputState"
                @keydown.delete="handleInputDelete"
                ref="input">`

**Comment by warriorg** [comment]
select 双向绑定中，清理v-model的值，Select中还是之前的。虽然已经没有选中任何值了

**Comment by lwyj123** [comment]
还是我来提供个在线的吧。这个issues看到过两次了
https://codepen.io/lwyj123/pen/dzRaZX

**Comment by icarusion** [comment]
@lwyj123 thanks.

**Comment by kiddkyd1412** [comment]
@icarusion 提个意见，在选了一个选项后，如果想“从中间开始”修改这个选项，貌似是不行的。
因为鼠标一点击下拉列表，就会自动全选这个选项，光标无法移动，光标无法定位到已选项的某一个位置。

最恐怖的是，如果用户双击多几次，导致取消了全选文字状态，这时候，一般用户以为可以删除部分文字重新搜索，而按了“退格”键，页面就会整个后退。。。


另外，似乎开启了搜索功能后，下拉列表在空数据源的情况下，无法对v-model强制修改数值？这个迟点我上个demo。
