### ISSUE TITLE
page problem

### ISSUE THREAD

**Issue by Sciuridae** [iview/iview#1548]
![image](https://user-images.githubusercontent.com/24518170/29011442-af6d21d4-7b65-11e7-8abb-d74c5194e6e8.png)
iview 分页 比如我搜索后有45页的数据， 然后我在次按其他条件搜索只有13页数据， 这里就会出现如图一一样的效果，试过了重新设置current 还是一样的。 有什么解决方案吗?

**Comment by liufeics** [comment]
把current设置为1，这样就没问题了，因为current和数据长度不匹配，希望下个版本解决

**Comment by rijn** [comment]
#1543

**Comment by Sciuridae** [comment]
我把 current 写死为 1 或 动态改为 1 ，都没有用啊
