### ISSUE TITLE
添加Tab-pane时，Tabs不会联动！

### ISSUE THREAD

**Issue by weijj0528** [iview/iview#155]
<Tabs type="card" closable :active-key="activeKey" >
       <Tab-pane v-for="item in tabs" :label="item.title" :key="item.key" class="self-adaption"{{item.content}}
       </Tab-pane>
</Tabs>

updateNav () 更新 Tabs 方法只是在初始化完成与关闭Tab-pane 时有调用，临时解决是在 activeKey 改变时增加调用！
watch: {
            activeKey () {
                this.updateNav();
                this.updateBar();
            }
        }

**Comment by shuimuyian** [comment]
this.updateNav();
this.updateBar();
应该怎么写
