### ISSUE TITLE
表格单元格使用v-html渲染数据

### ISSUE THREAD

**Issue by crystalray1984** [iview/iview#1550]
在渲染表格的单元格内的内容时，数据使用的是v-html渲染，这个有一定的安全风险。可否改成内部文本渲染或者提供一个类型选项？

找到的源码如下
`<template v-if="renderType === 'normal'"><span v-html="row[column.key]"></span></template>`

**Comment by icarusion** [comment]
建议后端对尖括号转义，或使用 render

**Comment by crystalray1984** [comment]
事实上，如果后端对尖括号做转义，在其他组件中使用{{}}输出文字时又需要处理转义，默认行为不一致会导致很多的转义操作。用render也是同理，无端端多出来不少编码工作，又容易出错。
现在我的做法只能是直接修改你们的源码，但终究不是长久之计。
恳请考虑一下我的提议。
