### ISSUE TITLE
分页show-sizer能否像element那样根据当前位置自动变换位置

### ISSUE THREAD

**Issue by 452486035** [iview/iview#1551]
http://element.eleme.io/#/zh-CN/component/pagination
当分页栏在浏览器底部时，分页sizer自动在分页栏上面，否则sizer在分页栏下面显示。
没有此自动功能，当分页栏在浏览器底部时，会将页面撑开，导致出现滚动条，

**Comment by rijn** [comment]
we've known this bug. #144
