### ISSUE TITLE
关于Table组件的宽度自适应

### ISSUE THREAD

**Issue by GwYL** [iview/iview#1552]
上次说成了Form组件了，抱歉，打错字了
可能我没有说清楚，我再描述一遍：
    当我点击这个左侧导航的折叠按钮的时候，
    右侧的Table组件会出现宽度自适应的问题
          其表现为： class为ivu-table-header的div宽度自适应了，但div里面的table没有自适应
    请问这个要怎么解决呢？

**Comment by no5no6** [comment]
临时解决方案：
学习了源码，发现iview的table本身是有resize事件的，只是没有暴露出来，可以通过ref找到iview的table组件，并触发他内部的resize方法，table就可以在窗口大小改变时候调整成相应的宽度了。
```
html:
<Table ref='tableData' :columns="table.columns" :data="table.data" ></Table>

js:
window.onresize = event => {
  this.$refs.tableData.handleResize();
}
```

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
