### ISSUE TITLE
[建议]统一 i-component 和 Component 的写法

### ISSUE THREAD

**Issue by yuri2peter** [iview/iview#1556]
大部分组件都在文档的第一行写了   注意：非 template/render 模式下，需使用 i-input。
然而有的组件并不能使用i-的形式，如Tabs和Modal。
请统一都用首字母大写或i-开头，或者最起码不要有的要改开头有的不要改。

**Comment by icarusion** [comment]
此类问题已经解释过多次了，不再回答，去搜历史issues
