### ISSUE TITLE
Date-picker初始值为字符串时，首次变更结果不合预期

### ISSUE THREAD

**Issue by KIDJourney** [iview/iview#1560]
复现样例： https://jsfiddle.net/KIDJourney/owns3jah/3/

问题现象：在第一次修改时间时，date的值为字符串，后续修改时间时，date的指为`Date object.`

期望现象： 在第一次修改时间时，date的值为`Date object`

![2017-08-08 18 17 30](https://user-images.githubusercontent.com/5558574/29067734-59e84dea-7c66-11e7-8c3d-30faa2dfd776.png)

**Comment by rijn** [comment]
`:value="time"`

**Comment by rijn** [comment]
> 注意：value 使用 v-model 时，值是 Date 类型，可以配合 @on-change 使用

**Comment by KIDJourney** [comment]
@rijn 我觉得这句话有歧义，我的理解是

> 在value使用v-model，并且值是Date类型时，可是配合@on-change使用

而不是

> value使用v-model是，值应该是Date类型，并且需要配合@on-change使用。

**Comment by mrerhuo** [comment]
@KIDJourney 解决了没？我用最新版本都有问题。

**Comment by mrerhuo** [comment]
@icarusion 新版本还是有这个问题。

**Comment by mrerhuo** [comment]
@KIDJourney 加验证才有这个bug。不加验证没有这个bug.
@icarusion

**Comment by SergioCrisostomo** [comment]
@mrerhuo please use `new Date()` as initial value. https://jsfiddle.net/Sergio_fiddle/owns3jah/5/
