### ISSUE TITLE
Problem use key tab on Form (Select, Date...)!

### ISSUE THREAD

**Issue by thearabbit** [iview/iview#1564]
Problem when using `Key Tab` on Form object `select, date, check`
![image](https://user-images.githubusercontent.com/4495160/29100010-0f06b196-7cd3-11e7-8495-f572e79d2249.png)

**Comment by icarusion** [comment]
Can you describe the problem in more detail?
Maybe you can use `transfer` in Select, Date or other components with dropdown

**Comment by icarusion** [comment]
#1542
