### ISSUE TITLE
table几个关于ui的严重bug，关于空数据时标题肥大，列丢失，滚动条丢失等

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1566]
在线例子
https://codepen.io/anon/pen/oeWXPe

出现的问题和原因都已经在例子里写明

**Comment by dean5277** [comment]
![image](https://user-images.githubusercontent.com/1802631/29108814-2365970c-7d13-11e7-8560-31cc5634db46.png)
是个BUG

**Comment by zg091418** [comment]
ui有问题，你用最复杂了那个表格，会出现莫名的横线。。。。。。

**Comment by icarusion** [comment]
前两个case我这里一切正常。第三个case是一直问题了。

**Comment by kiddkyd1412** [comment]
@icarusion 你用的什么浏览器前2个没问题？你显示器分辨率多少
我1080P分辨率
浏览器试过chrome60，QQ浏览器9.6.4极速内核，火狐55

**Comment by dryqiao** [comment]
同样出现第一个问题，col宽度计算出错了
