### ISSUE TITLE
datepicker组件的弹窗子组件select-dropdown的样式生成定位不应该使用position: absolute

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1567]
https://jsfiddle.net/nsw24dzn/2/

临时解决方案：
/**
* 日期组件下拉或者收起后执行
* @Param isOpen 下拉为true,收起为false
*/
changeTimeListOpen(isOpen: boolean) {
if (!isOpen) {
return;
}
//修改日期组件的位置
setTimeout(() => {
const $dropdown = $('.ivu-date-picker>.ivu-select-dropdown:eq(0)');
$dropdown.css({
position: 'fixed',
top: $dropdown.offset().top - 109,
left: $dropdown.offset().left - 181
});
}, 0);
},

**Comment by yangdan8** [comment]
#1152

**Comment by icarusion** [comment]
Use `transfer` prop.
