### ISSUE TITLE
使用官方脚手架创建项目时报错 Unexpected token name «i», expected punc «;»

### ISSUE THREAD

**Issue by shoyuf** [iview/iview#1571]
```
Unexpected token name «i», expected punc «;» [./~/iview/src/utils/assist.js:5,0][static/js/0.d142aca547feef5ff50a.js:50,13]
```
版本:2.0.0
之前没有出现过这个问题,之后不知道新引用了哪个组件就开始报错,在`webpack.base.conf.js`
中加入
```
resolve('node_modules/iview/src/utils/assist.js')
```
没能解决问题

**Comment by zezic** [comment]
Same problem for me.

**Comment by shoyuf** [comment]
webpack.bae.conf.js 
add
```
{
   test: /iview.src.*?js$/,
   loader: 'babel-loader'
}
```

**Comment by zezic** [comment]
@shoyuf I use Nuxt.js and in base.config.js I already have this:
```
        {
          test: /\.js$/,
          loader: 'babel-loader',
          exclude: /node_modules/,
          query: defaults(this.options.build.babel, {
            presets: ['vue-app'],
            babelrc: false,
            cacheDirectory: !!this.dev
          })
},
```
i'm adding next section to my `nuxt.config.js`:
```
  build: {
    extend (config) {
      config.module.rules.push(
        {
          test: /iview.src.*?js$/,
          loader: 'babel-loader'
        }
      )
    }
  },
```
but this doesn't help.
It's because this rule can't beat /node_modules/ exclude from previous rule?

**Comment by zezic** [comment]
Temporary fixed by editing `node_modules/nuxt/dist/nuxt.js` and replacing this
```
        exclude: /node_modules/,
```
with this
```
        exclude: /node_modules\/(?!(iview)\/).*/,
```

**Comment by l619534951** [comment]
@shoyuf I have solved the problem with you answer, thank you, Could you please explain the code's mean? 
 i'm a student who is learning backend language. 好吧，我还是说中文吧，那个我是学后台这一块的，现在准备写毕业设计，然后准备用使用vue，来写前台，用到了iview，然后遇到这个问题，第一次接触前端模块化开发，不太清楚，你那个代码是什么意思呢？我只知道那个是webpack的配置文件。指教一下，谢谢

**Comment by shoyuf** [comment]
uglifyJS 不支持 ES6导致的打包 iview 工具报的错


原始邮件
发件人:沙滩上de水瓶notifications@github.com
收件人:iview/iviewiview@noreply.github.com
抄送:Shoyuffanxiangyu2014@gmail.com; Mentionmention@noreply.github.com
发送时间:2017年9月9日(周六) 14:17
主题:Re: [iview/iview] 使用官方脚手架创建项目时报错 Unexpected token name «i», expected punc «;» (#1571)


@shoyuf I have solved the problem with you answer, thank you, Could you please explain the code's mean?
 i'm a student who is learning backend language. 好吧，我还是说中文吧，那个我是学后台这一块的，现在准备写毕业设计，然后准备用使用vue，来写前台，用到了iview，然后遇到这个问题，第一次接触前端模块化开发，不太清楚，你那个代码是什么意思呢？我只知道那个是webpack的配置文件。指教一下，谢谢

**Comment by shiasn** [comment]
I edited the config in the extend and seemed to solve it with your way
```
extend (config, ctx) {
  config.module.rules.forEach((rule, i, rules) => {
    if (rule.loader === 'babel-loader') {
      rule.exclude = /node_modules\/(?!(iview)\/).*/
    }
  })
}
```
@zezic
