### ISSUE TITLE
page简洁模式跳转输入为空返回NaN

### ISSUE THREAD

**Issue by HOBERHUNTER** [iview/iview#1575]
![66](https://user-images.githubusercontent.com/23202246/29151790-145bb7c0-7db6-11e7-8e5e-027a861afba0.png)
分页简洁模式没有做为空的判断，回车后会返回NaN。上一页和 下一页也会失效。
other：分页在pc端不做回车提示用户也不知道是回车才跳转，且回车才跳转在手机页面不够好。可以考虑增加个跳转按钮。

**Comment by HOBERHUNTER** [comment]
自己加跳转按钮还不好加，page提供一个on-change事件，是要在回车后才触发。按钮无法获取输入的值，

**Comment by rijn** [comment]
How about adding an `on-before-change` event or a validator?

**Comment by HOBERHUNTER** [comment]
good idea. current prop try changing into a two-way binding

**Comment by LucaLJX** [comment]
@HOBERHUNTER 你on-change调用的方法里面给对应参数赋值，然后直接调用获取数据的方法不行么？

**Comment by LucaLJX** [comment]
@HOBERHUNTER 刚刚去试了一下，确实不行。。。

**Comment by hgcoder** [comment]
if (isNaN(val) ){
        val = 1
        var timer = setTimeout(function() {
          document.getElementsByClassName('ivu-page-simple-pager')[0].childNodes[0].value = 1
        }, 10)
      }
      var numRe = /^[0-9]+.?[0-9]*$/;
      if (!val || !numRe.test(val)){
        this.$Message.warning('页码输入有误！');
        return
      }

**Comment by 2lei** [comment]
@hgcoder 老哥，markdown啊，这不清真！！
