### ISSUE TITLE
日期组件快捷选项功能与禁用功能冲突

### ISSUE THREAD

**Issue by 68zch** [iview/iview#1577]
## bug再现地址
https://jsfiddle.net/zhoou/bf2j9u70/

## 问题描述
上面例子中禁用了2017-09-01之前的日期，但是点击快捷选项中的今天（2017-08-10）还是能选中

## 希望如何改变
点击快捷选项时判断是否与禁用的日期冲突，如果冲突就不能选中

**Comment by icarusion** [comment]
需自己实现逻辑
