### ISSUE TITLE
"[Vue warn]: Invalid prop: type check failed for prop 'value'. Expected Array, got String.  (found in <Cascader>)"

### ISSUE THREAD

**Issue by angusjiang** [iview/iview#1578]
使用vue 开发版本，console有个警告
在线demo
https://codepen.io/angusjiang/pen/qXmGVN?editors=1111

**Comment by dean5277** [comment]
value1:[]

**Comment by angusjiang** [comment]
tks

**Comment by xingyemeng** [comment]
![image](https://user-images.githubusercontent.com/20105414/45675768-abe68300-bb62-11e8-9857-155daa203138.png)
看错误就是，组件需要的是数组，但是接收到时是字符串，按照上图修改就可以了
