### ISSUE TITLE
Inline form items into a vertical form

### ISSUE THREAD

**Issue by sylvaincaillot** [iview/iview#1579]
Hello, 
I would need to have select, datepicker and inputs to be grouped by 2 or 3 on a single row.
My complete form would be then composed of several rows.

What would be the best practices in this situation?

Thank you

S.

**Comment by rijn** [comment]
We have an [example](https://www.iviewui.com/components/form-en#Form Control) for putting multiple inputs in a single row.

**Comment by icarusion** [comment]
you can also edit CSS style in some components.
