### ISSUE TITLE
怎么方便设置iview整体字号整体大一号？

### ISSUE THREAD

**Issue by docikaci** [iview/iview#1582]
想把大部分字号比如表格，modal等等调成14px，但是现在base是14px不能调成16px吧，small是12px，也没毛病，
调哪里呢？ 谢谢

![image](https://user-images.githubusercontent.com/7788102/29166515-38602226-7df9-11e7-8371-fbbf9138711c.png)

**Comment by lwyj123** [comment]
https://www.iviewui.com/docs/guide/theme
可以定制主题

**Comment by docikaci** [comment]
@lwyj123  
https://www.iviewui.com/docs/guide/theme
这个地址 我知道的，上面截图就是所有变量。
但是现在是改  base 改成16？    small改成12？  不科学吧

base是14px  但是表格，modal字体都是12px？
那我岂不是要把 small改成14px？
