### ISSUE TITLE
tree控件ui逻辑的bug

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1586]
https://codepen.io/anon/pen/qXjKqE

当一个父级有一个孩子没有checked中的时候，
同时，这个父级下面有一个同级别的父级是全选状态的时候。

上面那个父级的图标不会出现半选logo。而是空选logo。
如果这个时候你点击展开上面那个父级，那么这个父级的半选logo又会突然出现。

--------------------------------
目前解决方案是删除下面的父级数据，
或者让下面的父级数据不要全选中。

**Comment by icarusion** [comment]
看了一下，是初始化给的数据有逻辑问题，你的第二项数据是：
```js
{
    title: '其他',
    checked: false,
    children: [
        {
            title: '其他孩子',
            checked: true
        },
        {
            title: '其他孩子2',
            checked: true
        }
    ]
}
```
两个其他孩子都是 true，那其他也应该是true。
要么其他是true，其他孩子至少有一个得是false。
所以建议先修改数据保证数据的逻辑正确。

**Comment by wangkaiwen** [comment]
这个问题依然存在，当结构有3级以上的时候，第三级的元素没有全选时，其父元素不是半选而是空

**Comment by wangkaiwen** [comment]
![image](https://user-images.githubusercontent.com/12029207/29610307-67d0ce92-882c-11e7-825d-929af3e93003.png)

**Comment by kiddkyd1412** [comment]
我根据作者说的checked的问题，把父级那个checked:false注释掉，确实可以解决问题。
但是我想的是。。。既然子级全部都checked了，父级应该无论如何都要checked中才对。

**Comment by wangkaiwen** [comment]
目前 我解决的方案是  `this.$set(this.treeData, 0, this.treeData[0]`.随便替换一下子元素数据
