### ISSUE TITLE
select bug

### ISSUE THREAD

**Issue by vivinbear** [iview/iview#159]
### iView 版本号

0.9.12
### 操作系统/浏览器 版本号

Chrome 54
### Vue 版本号

1.0.25
### 能够复现问题的在线示例

https://codepen.io/anon/pen/BpaNjp
### 复现步骤
设置了filterable属性后,select并不会显示预期的value值,而是显示空,点击之后,才会显示
### 问题现象，以及你期望的结果是怎样的?
不伦设置什么属性,都应该显示对应的value值

**Comment by icarusion** [comment]
Thx.
