### ISSUE TITLE
select: multiple + remote + label-in-value 输入关键字查询导致原来已选的label值为空

### ISSUE THREAD

**Issue by songhlc** [iview/iview#1590]
组件 select:
参数：multiple + filterable + remote + label-in-value 
多次选择+输入关键字查询，第二次查询出的结果不包含第一次 ，则导致原来已选的label值为空

**重现地址：**
[https://codepen.io/songjl/pen/EvXeWR](https://codepen.io/songjl/pen/EvXeWR)

操作步骤，先选择选项一，然后输入1 获得新的查询结果，再选择选项三，则原来选择的选项label变成空了(如果输入2 返回的是全集则没有这个问题)

分析：源码中补充label好像是从findChild中补充，但原来选择过的不在重新查询出的列表中导致返回数据的时候只有value没有label

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
