### ISSUE TITLE
表单验证的时候prop动态绑定报错，动态渲染的表单prop肯定不是写死的啊

### ISSUE THREAD

**Issue by Tsite2007** [iview/iview#1592]
![2](https://user-images.githubusercontent.com/24953630/29202601-6494021a-7e9c-11e7-86a1-bc61a09bbd3f.png)

![1](https://user-images.githubusercontent.com/24953630/29202598-5aa73fd8-7e9c-11e7-9390-1d0f7f6782de.png)
 需要验证的字段有几百个，动态渲染进去的时候 prop 只能是写死的字符串吗  怎么一直报错

**Comment by kernnel** [comment]
仔细看文档好么，Form有prop这个属性？

**Comment by Tsite2007** [comment]
@kernnel    仔细看代码好吗  我的prop是加在form-item上的      api上没有？？？？？？？？？？

**Comment by kernnel** [comment]
噢，看错了

**Comment by liuyanshi** [comment]
[文档](https://www.iviewui.com/components/form)里面说明prop类型是String类型，而使用v-for循环时候的key的类型是number，因此需要你做下类型转换，或者pull request添加类型支持
