### ISSUE TITLE
表单验证的BUG

### ISSUE THREAD

**Issue by 13720271559** [iview/iview#1595]
表单验证如果表单里面有时间，并且加载的时候就给时间动态查询赋值了，表单验证就会报Uncaught TypeError: t.getTime is not a function，不能提交表单

**Comment by liuyanshi** [comment]
demo呢？

**Comment by icarusion** [comment]
provide your online code

**Comment by luyin0311** [comment]
我也遇到了同样的问题

**Comment by mrerhuo** [comment]
验证的时候，验证错误了，然后时间会自动加1天
