### ISSUE TITLE
<Modal></Modal>对话框的确认和取消按钮建议可以控制显示或者不显示

### ISSUE THREAD

**Issue by sunyifeng520** [iview/iview#1596]
在使用弹出层的时候，有时候我需要自己定义按钮来提交我的数据，而自带的按钮做提交，还需要把数据从子组件传到父组件，这样很麻烦，所以希望那两个按钮可以自己控制是否显示

**Comment by rijn** [comment]
slot="footer"

**Comment by sunyifeng520** [comment]
明天试试，谢谢





发自网易邮箱大师
在2017年08月15日 01:07，Rijn Bian 写道：

slot="footer"

**Comment by sunyifeng520** [comment]
不起作用



在 2017-08-15 01:07:14，"Rijn Bian" <notifications@github.com> 写道：


slot="footer"

**Comment by icarusion** [comment]
use slot footer
