### ISSUE TITLE
Tree在大数据量时渲染慢的解决办法

### ISSUE THREAD

**Issue by jumpdog** [iview/iview#1597]
使用中发现当tree节点数大时，渲染较慢，
研究后发现，tree会一次性渲染所有节点，
而实际只有expand节点才需要渲染，
因此可以在node.vue 的Tree-node 参数中加入 “ v-if='data.expand' ”实现条件渲染，
经测试，渲染速度、节点收折速度大幅提升

**Comment by lazyyman** [comment]
学习了

**Comment by LucaLJX** [comment]
还有这种操作？mark学习了

**Comment by XingxingLIU123** [comment]
刚好遇到这个问题，学习了

**Comment by suiyi8760** [comment]
不错，学习了

**Comment by BengBu-YueZhang** [comment]
Thanks

**Comment by SergioCrisostomo** [comment]
@jumpdog could you provide a example for this?
Is it something that should be better in iview's code? would e great to get a Pull Request with a fix, or some notes in the docs on how to avoid this problem.

Thanks for sharing
