### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by hmdeng110** [iview/iview#16]
1，下载了文档中介绍的vue-vueRouter-webpack项目；
2，在package的dependencies中加入"iview": "^0.9.2"；
3，webpack.base.config的loaders中加入 { test: /iview\/.*?js$/, loader: 'babel' }
4，最后在页面冲尝试引用组件import Message from 'iview'  注册组件 components: {Message}, ready中使用组件
5，编译正常，但浏览时，报错；应该是babel编译没到位，不是很理解问题出在哪

**Comment by icarusion** [comment]
import { Message } from 'iview'

**Comment by hmdeng110** [comment]
写法没有问题，一样的报错

**Comment by icarusion** [comment]
把webpack配置文件发到JSFiddle

**Comment by hmdeng110** [comment]
https://jsfiddle.net/6ut84rme/
配置和文档里介绍的那个项目一样的，改动如issue描述

**Comment by icarusion** [comment]
<img width="687" alt="qq20161005-0 2x" src="https://cloud.githubusercontent.com/assets/5370542/19112394/2e593746-8b37-11e6-9e9a-a1f003018639.png">
我这边重头安装了一遍，是没有问题的

**Comment by hmdeng110** [comment]
那只剩下一个可能，我的npm版本是3.8.9；是一致的么

**Comment by icarusion** [comment]
npm2.15.1
node4.4.3

**Comment by hmdeng110** [comment]
我已尝试降级到官方稳定版，npm 2.15.9; node 4.6.0;仍常存在一样的问题；无法解决

**Comment by abcdGJJ** [comment]
我也遇到了同样的问题，使用vue-cli生成webpack-simple#1.0
webpack：

https://jsfiddle.net/fukmyrap/

.babelrc：

```
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

App.vue：

```
<template>
    <Row>
        <i-col>
            <Button size="large" @click="clickBtn">一个按钮</Button>
        </i-col>
    </Row>
</template>
<script>
    import { Row, Col, Button } from 'iview';
    
    export default {
        components: {
            Row,
            iCol: Col,
            Button
        },
        methods: {
            clickBtn () {
                console.log('click!');
            }
        }
    }
</script>

```
npm2.15.1
node4.4.3

http://7xjnh2.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161005220936.jpg

http://7xjnh2.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161005220954.jpg

**Comment by abcdGJJ** [comment]
@F2EStone 并没有

**Comment by anshengme** [comment]
我也遇到同样的问题“Uncaught SyntaxError: Unexpected token import“，请问楼上是否已解决呢？

**Comment by zhenizhui** [comment]
the same problem

node version: v 4.4.7
npm version: v 3.10.7

**Comment by icarusion** [comment]
由于我这边和同事电脑都正常，无法复现，具体原因需要继续查，如果大家有解的话，可以直接贴出来

**Comment by liuhao1025** [comment]
这样配置 `loader` 试试
```javascript
{
  test: /iview\\.*?js$/,
  loader: 'babel'
}
```
之前配 `loader` 的 `exclude` 属性时发现，用于匹配的路径里，分隔符是 `\` 而不是 `/` ，查了一下，应该是操作系统的问题，上面几个没问题的用的是 Linux 吗？

**Comment by icarusion** [comment]
尝试了下，在Mac下是报错的。

**Comment by hmdeng110** [comment]
我的是window平台，实测 @liuhao1025 的解法有效

**Comment by zhenizhui** [comment]
请问是怎么解决的？我用的是win10，vue-vueRouter-webpack（楼主推荐的模板），

index.vue
```
<style>
    #hello {
        color: rosybrown;
        background-color: #28a7e1;
    }
</style>
<template>
    <h2 id="hello">{{msg}}</h2>
    <Page :current="1" :total="100"></Page>
</template>
<script>
    import Page from 'iview';
    export default {
        data () {
            return {
                msg: "Hello Vue WebPack!"
            }
        },
        components: {Page}
    }
</script>
```
在`webpack-base.config.js`中，

使用`{ test: /iview\/.*?js$/, loader: 'babel' },// for Mac`，报`Uncaught SyntaxError: Unexpected token import`

使用` { test: /iview\\.*?js$/, loader: 'babel' },// for Windows`，报`Uncaught Error: Cannot find module "./button.vue"` 然后还有一堆错误 :(

```
...

// 加载器
    module: {
        loaders: [
            { test: /\.vue$/, loader: 'vue' },
            { test: /iview\\.*?js$/, loader: 'babel' },// for win
            { test: /\.js$/, loader: 'babel', exclude: /node_modules/ },
            { test: /\.css$/, loader: 'style!css!autoprefixer'},
            { test: /\.scss$/, loader: 'style!css!sass?sourceMap'},
            { test: /\.(gif|jpg|png|woff|svg|eot|ttf)\??.*$/, loader: 'url-loader?limit=8192'},
            { test: /\.(html|tpl)$/, loader: 'html-loader' }
        ]
    },

...
```

**Comment by zzm1988** [comment]
我的报错和zhenizhui完全一样，求解决。

**Comment by jingsam** [comment]
@zhenizhui 要使用 import {Page} from 'iview';

**Comment by zzm1988** [comment]
@jingsam 使用了。还是报错

**Comment by jingsam** [comment]
@zhenizhui 最好再开一个issue，详细描述你的错误信息。

**Comment by zzm1988** [comment]
@jingsam  我的QQ：165112316，求帮忙解决。

**Comment by zzm1988** [comment]
@jingsam 我的问题和  https://github.com/iview/iview/issues/18  一样的。

**Comment by jingsam** [comment]
或许你可以新建一个github repo，上传一个最简单的项目，我可以帮你看看

**Comment by zzm1988** [comment]
![image](https://cloud.githubusercontent.com/assets/4548167/19878689/ded0f27c-a026-11e6-970d-6cf229816227.png)

**Comment by icarusion** [comment]
在多台电脑上测试，已经解决了这个问题，大家试一下，目前github已更新，npm在下个版本时更新，解决步骤：
1.webpack编译iview不再区分windows和mac，直接使用下面通用的配置
```javascript
module: {
    loaders: [
        { test: /iview.src.*?js$/, loader: 'babel' },
        { test: /\.js$/, loader: 'babel', exclude: /node_modules/ }
    ]
}
```
2.将项目下的node_modules/iview/node_modules下的`vue`目录删除

这样就可以了

**Comment by zzm1988** [comment]
@icarusion 浏览器访问还是不行。
![image](https://cloud.githubusercontent.com/assets/4548167/19881542/9ecd6f32-a041-11e6-9b63-070163ff8058.png)

**Comment by icarusion** [comment]
把你代码打个包发过来，不要node_modules

**Comment by zzm1988** [comment]
@icarusion

**Comment by icarusion** [comment]
在多台电脑，windows和mac都测试，没有问题，不过是用的iview@0.9.7-rc-1。
你把iview的版本号改成0.9.7-rc-1，重装一下试试。

**Comment by zzm1988** [comment]
@icarusion 
哦，我试试，另外我是用cnpm安装依赖的，有影响吗？

**Comment by icarusion** [comment]
@zzm1988 可能有影响，我们没在cnpm上试过

**Comment by zhenizhui** [comment]
@icarusion @jingsam 

it works ! thx !

```
module: {
    loaders: [
        { test: /iview.src.*?js$/, loader: 'babel' },
        { test: /\.js$/, loader: 'babel', exclude: /node_modules/ }
    ]
}
```

**Comment by lin-xin** [comment]
我的是window7平台，实测 @liuhao1025 的解法有效

**Comment by justnowanna** [comment]
ERROR in js/vendor.3919d08aac700d0a836d.js from UglifyJs
Unexpected token: operator (>) [./~/iview/src/components/base/notification/index.js:4,0][js/vendor.3919d08aac700d0a836d.js:48616,84]
@icarusion 打包时遇到这个是什么原因呢？困扰了很久了
