### ISSUE TITLE
Component does not work in the content property of the modal component

### ISSUE THREAD

**Issue by hya-1995-5-21** [iview/iview#160]
### 能够复现问题的在线示例

this.$Modal.confirm({
		                    title: '确认对话框标题',
		                    content: '<p>一些对话框内容</p><p>一些对话框内容</p><i-button>自定义按钮文字</i-button>',
		                    okText: 'OK',
		                    cancelText: 'Cancel'
		                });
### 问题现象，以及你期望的结果是怎样的?
Modal 这个组件content属性里iview组件不生效，我认为Modal不仅仅只是提示文字，还应该做很多事，比如在Modal里写一个表单用来做一些操作。

**Comment by icarusion** [comment]
`$Modal`用途就是便捷提示，类似于 `window.confirm`，自定义内容使用 `Modal`

**Comment by rijn** [comment]
* 通过html动态载入组件不符合Vue的设计原则 [vue directives in v-html directive #1468](https://github.com/vuejs/vue/issues/1468)
* 实在需要服务器渲染可以通过[Partial](http://v1.vuejs.org/api/#partial)
