### ISSUE TITLE
Collapse + Table 显示问题

### ISSUE THREAD

**Issue by lazyyman** [iview/iview#1601]
![387iz 4rdyzyb qh lrrq](https://user-images.githubusercontent.com/26090698/29239191-d8a371c0-7f7a-11e7-86fe-90538727109b.png)
上图是显示的效果，下图是代码
![3n h u s 7u9qzttq 2vj](https://user-images.githubusercontent.com/26090698/29239199-0c89040a-7f7b-11e7-9191-f8bb1a6841bb.png)

**Comment by zhangxyjack** [comment]
可以通过v-if当Collapse打开当前项时，在将table显示出来。但是显示效果会差一点。

**Comment by lazyyman** [comment]
@zhangxyjack 好的，我试试
