### ISSUE TITLE
layout组件

### ISSUE THREAD

**Issue by roughsoft** [iview/iview#161]
ant design新推出了layout组件，iview有没有类似的计划。

**Comment by vivinbear** [comment]
iview有layout的组件呀

**Comment by icarusion** [comment]
后面会给出布局建议的

**Comment by rijn** [comment]
Ant Design似乎叫Grid。感觉Layout更像是Sider、Footer之类的部件。
[Ant Design Layout](https://ant.design/components/layout/)

**Comment by icarusion** [comment]
是的，设计组已经给出了布局，但是还没有加。未来 iView 可能也会改名为 Grid

**Comment by roughsoft** [comment]
目前iview支持的grid；ant design在grid布局的基础上，增加了一个layout。
@icarusion ，期待推出，最近iview更新挺快的，加油！

**Comment by JohnKeng** [comment]
為什麼<template>內的內容都顯示不出來？

**Comment by icarusion** [comment]
已在0.9.18文档中更新。
