### ISSUE TITLE
Poptip 组件开启transfer时样式异常

### ISSUE THREAD

**Issue by Estelle00** [iview/iview#1612]
Poptip 组件开启transfer和confirm 后
渲染后ivu-poptip ivu-poptip-confirm 两个class消失
造成CSS样式丢失

猜测是transfer-dom.js文件操作DOM节点引起

示例
https://codepen.io/Estelle00/pen/PKJWwO

**Comment by wiladog** [comment]
thanks for fixed

**Comment by New-girlfriend** [comment]
酷
