### ISSUE TITLE
upload图片上传

### ISSUE THREAD

**Issue by hazeFlame** [iview/iview#1616]
上传upload 默认图片列表，后台来的数据defaultList里面可以放数据，数据进不了uploadList里面
如果写死一个数组放在defaultList里面，才可以显示默认的图片，，，，这个问题可以解决吗

**Comment by lazyyman** [comment]
有效果图吗？

**Comment by hazeFlame** [comment]
后台来的数据显示不了效果，用v-if控制了下还是不行

**Comment by maxonly** [comment]
我也遇到这个问题

**Comment by yajore** [comment]
我以为就我碰到了这个bug

**Comment by C-qilong** [comment]
我也遇到了，怎么解决？

**Comment by hazeFlame** [comment]
我自己写了一个图片上传，没用他的组件

**Comment by 531431988** [comment]
@hazeFlame  快共享出来

**Comment by yl40611** [comment]
接口数据返回后用
`this.defaultlist = res.data;
this.$nextTick(() => { this.uploadList= this.$refs.upload.fileList})`
解决

**Comment by 617450941** [comment]
@yl40611 怎么继续上传图片添加不了
