### ISSUE TITLE
model实例写法render获取值会触发两次

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1619]
https://jsfiddle.net/1tu1cmjd/4/

![image](https://user-images.githubusercontent.com/1802631/29304246-a23d5a64-81c4-11e7-96a6-25447dd27d89.png)

**Comment by dean5277** [comment]
https://jsfiddle.net/1tu1cmjd/6/  放到render后就会执行两次 

![image](https://user-images.githubusercontent.com/1802631/29304843-ea27f5a2-81c7-11e7-957e-c2215e85e61b.png)

**Comment by dean5277** [comment]
现在不敢用实例写法了，直接改成template写法了

**Comment by lenxeon** [comment]
还有就是render后的this对象拿不到this.$store了

**Comment by dean5277** [comment]
render的this箭头函数指向函数本身，你要在外面重新定义this

**Comment by lenxeon** [comment]
@dean5277 您好，有没有示例可以看一下，不会这种写法就卡在这儿两天了。

**Comment by dean5277** [comment]
![image](https://user-images.githubusercontent.com/1802631/29350168-e5c90136-828f-11e7-98d4-be7527151449.png)

**Comment by lenxeon** [comment]
这个我明白，问题是怎么让render对象里的this有外面的$store,可以看看这个问题的描述。
https://github.com/iview/iview/issues/1618

**Comment by MrKiven** [comment]
这个issue依旧存在，为何关闭了？

**Comment by BlankC** [comment]
这个issue依旧存在，希望作者能够修复。 @icarusion

**Comment by hongdaDu** [comment]
这个issue依旧存在，希望作者能够修复。 @icarusion

**Comment by Bigdongdongqiang** [comment]
这个issue依旧存在，希望作者能够修复。 @icarusion
