### ISSUE TITLE
单选框的原型原则按钮样式会随着屏幕的缩放而变化

### ISSUE THREAD

**Issue by shanyanwt** [iview/iview#1625]
单选框的原型原则按钮样式会随着屏幕的缩放而变化，感觉很诧异，主打样式的ui,这个应该调整调整，有什么解决办法可以回复我，解燃眉之急！抱拳了老铁
https://www.iviewui.com/components/form

**Comment by ihuguowei** [comment]
针对屏幕尺寸作`media query`，自己动手非衣足食。老铁～～
