### ISSUE TITLE
关于table的问题

### ISSUE THREAD

**Issue by sunyifeng520** [iview/iview#1628]
我在modal里面使用table    数据取到了  但是无论如何第一次弹出modal的时候  表格无法渲染  但是只要我修改了代码   然后保存   页面自动刷新了   数据就会出来

**Comment by JohnNiang** [comment]
可能是你绑定数据的时机不对

**Comment by sunyifeng520** [comment]
已经解决了  组件加载的时间顺序不一样导致的
