### ISSUE TITLE
tab组件使用vfor展示tab,删除绑定某个数组不能删除对应tab

### ISSUE THREAD

**Issue by bao2314483** [iview/iview#1631]
在线展示:https://codepen.io/anon/pen/qXpRpE

**Comment by bao2314483** [comment]
简单来说tab组件不能双向绑定数据

**Comment by sevenT** [comment]
+1

**Comment by bao2314483** [comment]
怎么没人理我的呢

**Comment by icarusion** [comment]
先更新到最新版

**Comment by pollux2015** [comment]
请问"iview": "^2.4.0"支持双向绑定??
向绑定的数组里面PUSH没有问题, 
点击TAB关闭按钮也没有问题, 
通过其他方法移除数组某个值后, tab没有消失
