### ISSUE TITLE
table height 并不兼容百分比字符串

### ISSUE THREAD

**Issue by xcodebin** [iview/iview#1633]
table的height不兼容百分比，那这里就不该写支持字符串类型。
table源码里
            fixedHeader () {
                if (this.height) {
                    this.$nextTick(() => {
                        const titleHeight = parseInt(getStyle(this.$refs.title, 'height')) || 0;
                        const headerHeight = parseInt(getStyle(this.$refs.header, 'height')) || 0;
                        const footerHeight = parseInt(getStyle(this.$refs.footer, 'height')) || 0;
                        this.bodyHeight = this.height - titleHeight - headerHeight - footerHeight;
                    });
                } else {
                    this.bodyHeight = 0;
                }
            },
这个方法
prop传进来的height可能是100%这个字符串，这时候用this.height计算就会出问题,，未考虑百分比的情况，希望作者修复。
问题展示链接：
https://codepen.io/xcodebin/pen/KvZWVY

**Comment by icarusion** [comment]
暂不支持百分比
