### ISSUE TITLE
Translations for the issue submit rules?

### ISSUE THREAD

**Issue by SergioCrisostomo** [iview/iview#1634]
When I try to open a issue as a non-chinese speaker I see:

    
    
    
    

Would the translation be this (see under)?:

    
    
    
    

And can we use both languages like this (see under)?

    
    
    
    

(If the issues would be submitted in English, then non-chinese speakers could help in bug fixing and avoiding duplicates)

**Comment by icarusion** [comment]
Thank you, but these are mainly for Chinese people, because of China have many free rider.
And I will write an issue submit system in the future.
