### ISSUE TITLE
Default value for Select with remote-method 

### ISSUE THREAD

**Issue by SergioCrisostomo** [iview/iview#1636]
When a Select has `remote-method` what should be the default value for
 - empty value, nothing selected
 - pre-selected value
?

In the case we initiate the select with nothing selected, a empty string `''` blocks the select and doesn't open the dropdown ([see jsFiddle](https://jsfiddle.net/Sergio_fiddle/tu220dpy/1/)). But if I use `null` as value then it works as expected. If I pass a empty object the placeholder gets `[object Object]`.

**Question `#1` (not-selected initiation):** I think `null` is OK for default empty value. Can we add that to the docs?

In case of pre-selected value, if I pass only the `value` as a _string_ it will not display the `label` (expected since options are async). If I pass a object like `{value: 11, label: 'Some label'}` [i get `[object Object]`](https://jsfiddle.net/Sergio_fiddle/tu220dpy/2/) in the placeholder. I could pass `label` in the `props` but since the select knows the method that gets the values, `value` should be enough.

**Question `#2` (pre-selected initiation):** Can we have a object with `value` and `label` as default value, or should we use a string (the `value` key)  and make the select call the `remote-method` and do a `.find()` on the selected option?

---

**Vue.js:** v2.4.0
**iView:** v2.1.0
**jsFiddle:** [here](https://jsfiddle.net/Sergio_fiddle/tu220dpy/1/)

**Comment by icarusion** [comment]
1.  just use `value` and `label` in remote method.
2. default is empty `''`

**Comment by SergioCrisostomo** [comment]
@icarusion:
Did you see [my jsFiddle](https://jsfiddle.net/Sergio_fiddle/tu220dpy/1/) where the dropdown doesn't open when I give by default `value: ''`?   
Is it a bug or bad setup from me?

**Comment by icarusion** [comment]
Under remote method, you should set some word in search input, and the Dropdown will be displayed.

**Comment by icarusion** [comment]
You can have a try with `selectValue: 'hangzhou'`

**Comment by SergioCrisostomo** [comment]
@icarusion
So the problems are: 
 - `selectValue: ''`: dropdown doesn't open (bug?)
 - `selectValue: 'hangzhou'`: that just shows the `value`. Do I need to set the `label` also myself?, or should we have a call to the `remote-method` on initiation to get the proper `label` for that `value`

**Comment by icarusion** [comment]
It is not a bug. Because the `remote` method is for remote ** search **, if you want to show default dropdown list, I think you should use `Searchable` demo, not `Remote Search`

**Comment by SergioCrisostomo** [comment]
If I understand correct `Searchable` is sync and `Remote Search` is async. I need to use `Remote Search` because my dropdown options are async. I think the problems I bring up here are relevant.

**Comment by icarusion** [comment]
I'll think again about the ability to add a default list, thank you.

**Comment by icarusion** [comment]
Please review this demo, is it can resolve your problem
https://codepen.io/Aresn/pen/brLYqq

**Comment by SergioCrisostomo** [comment]
@icarusion thank you for feedback. 

Question `#1` is clear. 

About question `#2`: we could have a `select` with `remote` and not `filter` that would call the remote method when focused.
But this is also possible to do outside the component with not much code.

So I close this for now. 👍

**Comment by vdcrea** [comment]
Personally, I used the placeholder to display the selected value, clearly not perfect but at least user can see what is the default value. I wont use the searchable only because it's a country list and don't want too many options mounted in the DOM.  
My two cents
