### ISSUE TITLE
Tabs内部嵌套Form，tab键切换焦点导致界面错乱

### ISSUE THREAD

**Issue by mu-yu** [iview/iview#1638]
`Tabs>(Tab-Pane>Form>(Form-items>Input)*2)*3`类似这样的嵌套结构，按tab键切换焦点时会导致页面错乱，显示下个Tab-Pane的内容

效果截图：
![image](https://user-images.githubusercontent.com/3822774/29405486-a0f11eb8-8370-11e7-9bef-66ed30a17c2e.png)

链接地址：http://jsbin.com/mejehonoco/edit?html,js,output

**Comment by mu-yu** [comment]
临时解决方案：在Tab-Pane加v-show=“Tabs的[v-model] === Tab-Pane的[name]”

**Comment by LucaLJX** [comment]
jsbin上面显示效果不是很全，我本地用代码测试了一下，并没有发现你说的问题啊

**Comment by mu-yu** [comment]
![bug](https://user-images.githubusercontent.com/3822774/29597719-10475fa4-87f7-11e7-9417-d66deb899c8c.gif)
 录了一个gif…可以看在tab a按下tab键，会导致页面一部分显示tab a的内容，一部分显示tab b的内容。

手动复现方法：
焦点在tab a的输入框内，有节奏的按<kbd>tab</kbd>键或<kbd>shift</kbd>+<kbd>tab</kbd>

**Comment by LucaLJX** [comment]
刚刚去看了一下iview的官方文档，里面并没有说支持键盘事件。。。会不是因为这个原因

**Comment by mu-yu** [comment]
你这么说倒是提醒我了，可以把input的tab键屏蔽掉来临时解决这个问题…

可是在填写表单的时候按tab切换到下一项是很常见的操作…

**Comment by LucaLJX** [comment]
这种情况我在项目中的案例是Modal中嵌套form表单，form表单中的某一个form-item中用到了tabs，然后在form-tiem之间的input用tab切换是一切正常，而且并没有触发tabs的tab效果。。

**Comment by Teemwu** [comment]
同样遇到这个问题：[https://codepen.io/nooby/pen/vJqeGX?editors=1010](url)

**Comment by icarusion** [comment]
可能会在 3.0 时对键盘事件统一处理。
