### ISSUE TITLE
table组件data数据清除BUG

### ISSUE THREAD

**Issue by yajore** [iview/iview#164]
### iView 版本号
 0.9.12

### 操作系统/浏览器 版本号
WIN10、chrom355

### Vue 版本号
 1.0.26 

### 能够复现问题的在线示例
https://codepen.io/anon/pen/QdWKOE

### 复现步骤
点击清除数据按钮，表格没有清空

### 问题现象，以及你期望的结果是怎样的?
请尽快修改发布

**Comment by icarusion** [comment]
你的数据有问题，{{ items | json }}

**Comment by yajore** [comment]
没懂，我的例子想表达，我给表格的data赋值了一个空数组（或者用splice删除数组），结果，表格还是存在2行数据，按照vue的情况，是不是应该显示一个没有数据的的table？

**Comment by rijn** [comment]
* iView对传入的html进行$compile挂载在table下
* 如果在render里实现双向绑定，Vue会建立一个data的Watcher [Source](https://github.com/vuejs/vue/blob/1.0/dist/vue.js#L6523-L6537)
* 这时，如果你删除了Array里的一个Entry，data到vm的Watcher先Update，就会导致value报错

把render改成如下，先检验`items[${index}]`是否有效，就可以避免warning
```
render (row, col, index) {
   return `<Input-number :value.sync="items[${index}] && items[${index}].age"></Input-number>`;
}
```

**Comment by icarusion** [comment]
你把 {{ items | json }} 显示出来看，你点清空时，数据并没有清空，只是部分字段清空了

**Comment by NsNe** [comment]
@rijn 现在维护一个老项目，就查到了这里，但是出现如下错误。在网上也没有找到解决该问题的方法
Cannot bind two-way prop with non-settable parent path
