### ISSUE TITLE
[bug] Tree 动态更新 data 出现奇怪的 bug

### ISSUE THREAD

**Issue by Baoyx007** [iview/iview#1640]
[https://codepen.io/Baoyx007/pen/OjzOyb](https://codepen.io/Baoyx007/pen/OjzOyb)

一直点 click 会导致 data 会变. 而且点击 checkbox, 结果完全乱了

可能和 `nodeKey` 有关

**Comment by Baoyx007** [comment]
Tree 的 data 重制就会出现问题

**Comment by LucaLJX** [comment]
这个问题是因为你点击checkbox勾选的时候iview会给对应的treeNode添加selected:tree or false属性，然后你动态更行tree的data的时候，会影响iview对节点selected属性的判断，所以会乱掉

**Comment by Baoyx007** [comment]
@LucaLJX 节点的selected属性难道不应该以我新传入的数据为准么?

**Comment by ptk941114** [comment]
遇到差不多的问题，我想实现点击node同时选中checkbox，但是通过selected修改checked属性之后会导致节点动画联动失效

**Comment by LucaLJX** [comment]
@Baoyx007 刚刚又去看了一下你的例子，在初始化的时候，你用的是iview给定的数据，click的时候你是自己构造的数据，你自己构造的数据有一个问题，就是当父节点有子节点的时候，你手动给父节点添加了check属性，这样子节点的check属性变化的时候，父节点的check属性就会发生错乱。
iview的做法应该是如果父节点有子节点，那么父节点就不手动给他添加check属性，全部交由最底层的子节点的check属性来决定，这样就不会错乱。

**Comment by ptk941114** [comment]
@LucaLJX 那你自己没有尝试一下把子节点的checkbox属性删掉吗 ？？刚我试了还是有问题

**Comment by LucaLJX** [comment]
`this.baseData=[
        {
          expand: true,
          title: "parent 1",
          children: [
            {
              title: "parent 1-0",
              expand: true,
              disabled: false,
              children: [
                {
                  title: "leaf",
                  disableCheckbox: true
                },
                {
                  title: "leaf"
                }
              ]
            },
            {
              title: "parent 1-1",
              expand: true,
              checked: true,
              children: [
                {
                  title: '<span style="color: red">leaf</span>'
                }
              ]
            }
          ]
        }
      ]
    }`
我把你click里面改变的data数据中所有父组件的checked属性删掉了，测试是ok的

**Comment by Baoyx007** [comment]
但是当时文档里是这么写的:

![image](https://user-images.githubusercontent.com/1262198/29655846-e8ec994e-88e4-11e7-8ead-dacabf94ee3f.png)

父节点如果 checked, 那么子节点全部选中

**Comment by LucaLJX** [comment]
@Baoyx007 如果父节点给了checked，子节点已经全部选中，然后你就不用再手动给子节点赋checked属性，避免影响父节点的checked状态

**Comment by Baoyx007** [comment]
事实上这两种方法都会出错:
1. 只设置 parent: [https://codepen.io/Baoyx007/pen/OjzOyb?editors=0010](https://codepen.io/Baoyx007/pen/OjzOyb?editors=0010)

2. 只设置 children [https://codepen.io/Baoyx007/pen/MvBXLM?editors=0010](https://codepen.io/Baoyx007/pen/MvBXLM?editors=0010)

**多点几次 click** , 在点击 CheckBox, 选中的节点就会变乱

**Comment by Yansor** [comment]
@Baoyx007 最终解决了吗?

**Comment by Baoyx007** [comment]
没有, 可以看下这个 issue #1717

**Comment by SergioCrisostomo** [comment]
Can someone test this problem in `iview@2.6.0`? Tree received much love in this release, maybe this problem is fixed.

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
