### ISSUE TITLE
switch  表单校验  选了还是报错

### ISSUE THREAD

**Issue by lwx333921** [iview/iview#1643]
![image](https://user-images.githubusercontent.com/29451507/29448052-668a4f26-8427-11e7-8fa1-f27e387bcfe2.png)

**Comment by lwx333921** [comment]
只是在rules=ruleValidate里面,加了指向这个字段 props=formValidate.status，没有其他的校验

**Comment by LBC100** [comment]
哥们，解决了吗

**Comment by LBC100** [comment]
遇到同样的问题
