### ISSUE TITLE
动态生成的Menu，active、open默认值无效

### ISSUE THREAD

**Issue by A-PASSER-BY** [iview/iview#1645]
动态生成的Menu，active、open默认值无效，怎么才能展开导航条及高亮选中的列表，求解啊！

**Comment by LucaLJX** [comment]
这种情况我也遇到过一次，不过我的menu不是动态生成的，当时的情况是页面刷新的时候默认选中某个选项，且其对应的submenu打开。
排查问题之后发现，默认赋值openNames属性是在mounted里面进行操作的，而事实上应该在created钩子里面进行操作。
iview在实现默认打开某个选项是先判断openNames的值，然后给对应的html添加样式，然后再挂载html，所以顺序错了，就达不到对应的效果。

**Comment by Rudy24** [comment]
@LucaLJX 我的也是动态生成Menu，然后再设置active，open，接口请求是放在created里面，得出的值是有效的，不过Menu还是没有展开

组件---》
<Menu :accordion="true" :theme="'dark'" :active-name="activeMenu" :open-names="openName" width="auto">

方法---》
created() {
    //获取用户信息
    this.getUserInfo();
    this.activeMenu = this.getActiveMenu();
    this.openName = this.getOpenName();
  }

**Comment by Rudy24** [comment]
@LucaLJX 我的也是动态生成Menu，然后再设置active，open，接口请求是放在created里面，得出的值是有效的，不过Menu还是没有展开

组件---》
<Menu :accordion="true" :theme="'dark'" :active-name="activeMenu" :open-names="openName" width="auto">

方法---》
created() {
//获取用户信息
this.getUserInfo();
this.activeMenu = this.getActiveMenu();
this.openName = this.getOpenName();
}

**Comment by Rudy24** [comment]
@LucaLJX 我的也是动态生成Menu，然后再设置active，open，接口请求是放在created里面，得出的值是有效的，不过Menu还是没有展开

组件---》
Menu :accordion="true" :theme="'dark'" :active-name="activeMenu" :open-names="openName" width="auto"
方法---》
created() {
//获取用户信息
this.getUserInfo();
this.activeMenu = this.getActiveMenu();
this.openName = this.getOpenName();
}

**Comment by zhangwei900808** [comment]
我也遇到 相同的问题，都没解决，怎么issue就关闭了，奇怪！

**Comment by icarusion** [comment]
没按要求提问。
