### ISSUE TITLE
[Feature Request] tab index support for inputs for accessibility

### ISSUE THREAD

**Issue by ejfrancis** [iview/iview#1647]
Support for the [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) property is essential for any commercial website to enable accessibility for people who are blind or use screen readers, as well as power users who navigate primarily via keyboard. 

For instance I've built a simple form with two text inputs and a checkbox, and it's impossible to navigate to the checkbox with the keyboard, so a blind person wouldn't be able to use this form's checkbox.

Each input and button element should be able to accept a `tabindex` property that it passes down to its real HTML input element. For example,

```html
<Input type='text' html-tabindex='1'>
```

Should yield HTML similar to this:

```html
<div class="ivu-input-wrapper ivu-input-type ivu-input-group">
  <input type="text" tabindex="1">
</div>
```

I believe the following components should all accept this property and apply it to their html element:
* `<Input>`
* `<Radio>`
* `<Checkbox>`
* `<Switch>`
* `<Select>` 
* `<Slider>` 
* `<Button>`
* `<DatePicker>` 
* `<TimePicker>`

**Comment by SergioCrisostomo** [comment]
@ejfrancis do you time/possibility to help on this one? If you cannot let me know and I put it up in my priorities, but would be great to get a hand getting this fixed in iView.

Cheers

**Comment by ejfrancis** [comment]
@SergioCrisostomo not at the moment but in the next week or two, yes. Is there a time window for this to be done?

**Comment by SergioCrisostomo** [comment]
@ejfrancis there is no timeframe, just the wish to ship it in the next release. Its great you brought up the issue, who fixes is something else :)

If I get time before I can fix this. If we need to move it to another release its life :)

**Comment by thearabbit** [comment]
Fixed already?

**Comment by SergioCrisostomo** [comment]
@thearabbit not yet. Contributions are welcome. I am happy to help also, just having a lot of work right now.

**Comment by MicroDreamIT** [comment]
@SergioCrisostomo dropdown is not opening on tab index. is it possible to open dropdown on select item using table or down arrow?

**Comment by Xotic750** [comment]
Date/Time picker keyboard control will be dealt with in the pending refactor. https://github.com/iview/iview/pull/2861

**Comment by SergioCrisostomo** [comment]
🎉 🎉 🎉 🎉 

Closing this as fixed!
Thank you @ejfrancis for bringing this up, and everyone that helped to get this fixed.

The next release (2.14) will have the latest improvements and maybe we still find some bugs, but closing this since all components did get the upgrade needed.

🚀 🚀 🚀 🚀

**Comment by ejfrancis** [comment]
Awesome! great work 😄

**Comment by Zalasanjay** [comment]
can anyone help me out for syntax of this feature and how i can use it?

**Comment by sanozie** [comment]
A quick question on this issue:
The documentation for iView form components does not have tabindex listed as a prop (either 3x and 4x). Will this be updated anytime soon?
