### ISSUE TITLE
Table可展开行，如果原行有fixed列，则fixed列下会重复一次模板数据源

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1648]
https://codepen.io/anon/pen/QMmNWR

直接点击展开扩展行，会看到最右侧的“操作”列下会出现重复数据
QQ浏览器9.6.4极速内核

最后一列删除 fixed: 'right',属性可以暂时修复该问题。

**Comment by onlinc888** [comment]
我也遇到这样的问题 ，希望作者可以在下个版本给出解决方案。
