### ISSUE TITLE
table中设置input控件丢失焦点

### ISSUE THREAD

**Issue by yajore** [iview/iview#165]
### iView 版本号
0.9.12

### 操作系统/浏览器 版本号
WIN10/Chrome 55

### Vue 版本号
 1.0.26 

### 能够复现问题的在线示例
https://codepen.io/anon/pen/QdWKOE

### 复现步骤
点击“NAME” 列 input，删除文本框的文字，删除一个文字就失去文本框焦点了

### 问题现象，以及你期望的结果是怎样的?
达到正常效果

**Comment by icarusion** [comment]
你不能绑定到data里的值，这样会导致重绘，应该用临时值

**Comment by yajore** [comment]
怎么使用临时值？我使用data的值就是为了要实现双向绑定，不然有什么好的方法

**Comment by rijn** [comment]
新建一个Array，通过和data绑定相同的index等方式同步数据。

**Comment by icarusion** [comment]
楼上正解

**Comment by yajore** [comment]
@rijn 我使用你说的方式，貌似不起作用，还是丢失焦点（重绘了），具体可以看示例[https://codepen.io/anon/pen/jyPGMV]，如果写的有问题，请指出，谢谢

**Comment by rijn** [comment]
@yajore 你还是用了同一个list。
```
for (let i=0; i < _psize; i++) {
    items.push({
        id: i+1
    })
    items2.push({
        name: i,
        age: 10
    })
}
```

**Comment by yajore** [comment]
@rijn  谢谢，犯了低级错误，数组是引用类型。
再请教一个问题，现在我要更新选中的数据，但是iview返回的是选中的row，没有给定索引，我除了用数据row.id循环匹配 副本的data.id，还有什么更好的方式解决呢

**Comment by rijn** [comment]
@yajore 
```
items.push({
    _id: items.length
})
```
