### ISSUE TITLE
Form表单，在非 template/render 模式下， i-form，Col加载失效

### ISSUE THREAD

**Issue by biyaqian** [iview/iview#1651]
Form表单，在非 template/render 模式下， i-form中Col加载失效

**Comment by biyaqian** [comment]
<i-form :label-width="80">
                <Row>
                    <Col span="8">
                    <Form-item label="选择日期：">
                        <Row>
                            <Col span="11">
                            <Date-picker
                                    format="yyyy-MM-dd HH:mm:ss"
                                    ref="startDate"
                                    type="datetime"
                                    placeholder="选择日期"
                                    style="width: 200px;float: left;" ></Date-picker>
                            </Col>
                            <Col span="2">-</Col>
                            <Col span="11">
                            <Date-picker
                                    format="yyyy-MM-dd HH:mm:ss"
                                    ref="endDate"
                                    type="datetime"
                                    placeholder="选择日期"
                                    style="width: 200px;float:left;"></Date-picker>
                            </Col>
                        </Row>
                    </Form-item>
                    </Col>
                    <Col span="8">
                    <Form-item label="输入1：">
                        <i-input  placeholder="输入1" style="width: 300px;float: left;"></i-input>
                    </Form-item>
                    </Col>
                    <Col span="8">
                    <Form-item label="输入2：">
                        <i-input  placeholder="输入2" style="width: 300px;float: left;"></i-input>
                    </Form-item>
                    </Col>

                </Row>
                <Row>
                    <Col span="8">
                    <i-button type="primary">按钮1</i-button>
                    <i-button type="primary">按钮2</i-button>
                    <i-button type="primary">按钮3</i-button>
                    </Col>
                    <Col span="8"></Col>
                </Row>
            </i-form>

**Comment by icarusion** [comment]
[组件使用规范](https://www.iviewui.com/docs/guide/start#组件使用规范)
