### ISSUE TITLE
Table组件在无数据并且设置了height的情况下最后一列标题不显示

### ISSUE THREAD

**Issue by zhdwwf** [iview/iview#1652]
Table组件在数据为空时如果设置了height属性，表格最后一列显示不全
在线示例
[http://output.jsbin.com/purawaf/1](http://output.jsbin.com/purawaf/1)

**Comment by xiaochang** [comment]
请问这个问题你解决了吗？我也遇到同样的问题，感谢

**Comment by zhdwwf** [comment]
@xiaochang 给最后一个字段设置一个固定宽度后可以显示，但是自适应还是不行

**Comment by yangxfan** [comment]
我也是这样的问题，目前也是最后一个字段加一个固定宽度，因为是弹框里的表格，所以没考虑自适应，我测试 iview 2.0.0 和最新版 2.3.0 都有这个问题，先这么解决吧

**Comment by zazaluMonster** [comment]
我也有这问题

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/30586207-cd890a02-9d61-11e7-8222-41618f6704b0.png)
The example you provide don't seem to be a problem.

**Comment by zhdwwf** [comment]
Can you provide your browser version?
I test it with chrome and firefox,the result is:
chrome 60
![image](https://user-images.githubusercontent.com/564279/30623591-1bab5206-9deb-11e7-8cf2-4a170b2d01e3.png)
firefox 55
![image](https://user-images.githubusercontent.com/564279/30623617-494f9d48-9deb-11e7-9b95-5653bc0717d6.png)

**Comment by wangweida** [comment]
有这个问题，这么草率的就close了是否不妥当
