### ISSUE TITLE
select / option 严重性能问题

### ISSUE THREAD

**Issue by Alan110** [iview/iview#1653]
### iView 版本号

2.0.0-rc.9
### 操作系统/浏览器 版本号

macOS/Chrome 57
### Vue 版本号

2.2.2
### 示例代码

![image](https://user-images.githubusercontent.com/7564425/29509994-c8b9458c-868c-11e7-8d7e-101c08e79a41.png)

### 问题现象，以及你期望的结果是怎样的?

现象 ： 点击页面任意处，都会触发select 的option的事件，而且有几百个之多
期望 ： 别触发那么多事件吧，devtool都卡死了。。。

**Comment by icarusion** [comment]
#873

**Comment by Alan110** [comment]
我的option 才 30条都没有，也得用远程加载？ 这不合理吧。。。 这就把issue给关了？

**Comment by icarusion** [comment]
看不懂吗，#873

**Comment by icarusion** [comment]
类似的问题都会 reference 到以前的 issue，维护社区是一件成本很高的事情。
另，如果你有能力，为什么不贡献你的代码呢。

**Comment by icarusion** [comment]
开源项目是需要大家一起来维护的，尤其是 issue 社区，中国开发者衣来伸手饭来张口，拿来主义严重。所以请善待 GitHub，如果您不认可这种协同方式，大可选择其它开源项目。

**Comment by Alan110** [comment]
是大家一起维护啊，但你别搞得像大家欠你啊，我给你提issue就已经是在对你支持了，你解决不了，你把问题抛出来啊，从上到下我没见你说一句去解决问题的话

**Comment by icarusion** [comment]
都说了，类似的问题会 reference 到已有的 issue，不理解吗

**Comment by Alan110** [comment]
你作为维护人员，你有在推动问题的解决吗？

**Comment by icarusion** [comment]
那你有为开源社区贡献过什么呢

**Comment by Alan110** [comment]
是你还这里和我bb 好吗？

**Comment by icarusion** [comment]
你要不 watch 一下 iView 的项目，看看一周会收到多少邮件来处理。
回到问题本质，你的 issue 与 #873 类似，所以直接 reference 过去及 close，这点明白了吗？

**Comment by Alan110** [comment]
你在纠结什么呢？ 我是在跟你纠结issue吗？ 我是反感你在873中说的话，我们可以贡献代码，维护社区，但你别觉得这是理所当然。

**Comment by icarusion** [comment]
没解决的问题有很多，但需要我用时间来一个一个解决好吧。
如果社区都是你这种负能量、抱怨，那谁又能做出好的开源产品来呢，谁又愿意来做开源呢。

**Comment by Alan110** [comment]
我提出我的问题，给你现场，就是我贡献，我希望你们完善，或者给广大有识之士提供信息，但你们是这个项目的管理者，你们不站出来推动问题，要我来么？呵，我负能量，你就不是负能量？我没花我的时间？

**Comment by airyland** [comment]
@Alan110 
1. 已经有重复 issue，而你创建 issue 前并没有搜索。
2. 既然有重复 issue，关闭掉后面创建的重复的 issue 没有任何问题。
3. 既然前面已经存在的 issue 还处于 open 状态，说明作者还在关注解决中，只是 issue 比较多没那么快解决，或者优先级相对低。作为项目作者有权力决定先解决哪些问题。**每一个开启的 issue 对作者都是精神压力。**
4. 既然使用到该项目，那么有能力贡献代码，提供思路解决问题当然更好，我没看出作者哪里觉得理所当然了。倒是觉得你认为作者24小时解决所有问题是理所当然的。
5. 把在这里 bb 的时间拿来写代码吧。最好能开源一个类似的并且随时解决用户问题的项目给大家用。

**Comment by Alan110** [comment]
@airyland 

1. 请问你看到我哪句话里说了要作者立即解决所有问题？
2. 请问你如何得知我没有搜索？我搜性能，搜select，并没有找到
3. 请你去看看873 issue好吗？前面那么多人给了修改意见，作者有回复？有讨论? 是选择视而不见吧，等着别人写好代码填坑吗？就算如此，没问题，开源项目是自由的，但作者说的那句话什么意思？开发者天生应该给你提代码吗？人家给了那么多意见，你好歹回复一下不行？至少让人知道可不可行，是不是这儿的问题，你让我们这些后来发现这个问题的人怎么做？再重新来一遍吗？项目的管理者不推动问题的解决，不组织起维护者来，难道我们天生心灵相通？效率及其的低下，到头来不还是只有你们自己去解决问题吗？然后又来埋怨我们不去解决问题，不给建设性意见，这是管理上巨大问题好吗。

为什么别的项目那么多人贡献？ 请正视问题好吗，是谁在抱怨？

**Comment by icarusion** [comment]
不想再继续浪费 405 人的时间来接受这些负能量，所以请 @Alan110 兄台，放弃使用 iView，强烈建议你自己开发一套组件库来用，为了社区，拜托了。

@airyland 抱歉把 VUX 作者也卷进来，无意间又给您添加了负面情绪。
