### ISSUE TITLE
 Modal 建议加个是否显示遮罩属性，虽然自己可以加，但框架后期更新就坑了

### ISSUE THREAD

**Issue by 531431988** [iview/iview#1657]

**Comment by icarusion** [comment]
模态框的设计规范如此，为的就是阻止其它操作，聚焦在 Modal 上，所以遮罩层是必须有的。

**Comment by 531431988** [comment]
不是应该给个参数，让用户自由配置吗？默认是显示，可以自由设置隐藏

**Comment by icarusion** [comment]
不是的，是必须要有。

**Comment by 531431988** [comment]
好吧，没有layer智能，强制要求有，有点不人性了，那我自己加吧，相信有这个需求的不会是少数人

**Comment by icarusion** [comment]
# Modal 对话框
## 何时使用
需要用户处理事务，又不希望跳转页面以致打断工作流程时，可以使用 Modal 在当前页面正中打开一个浮层，承载相应的操作。

**Comment by icarusion** [comment]
https://ant.design/components/modal-cn/

**Comment by icarusion** [comment]
我们建议遵循设计规范来使用组件库。

**Comment by icarusion** [comment]
https://ant.design/docs/spec/stay-cn

**Comment by 531431988** [comment]
规定都是死的，人是活的，有的时候就是需要这种效果，一个组件就能完成的，非要去在写一个组件
![image](https://user-images.githubusercontent.com/8703951/29545876-7d8bc67e-8723-11e7-8949-71218db771eb.png)

**Comment by icarusion** [comment]
不，规范就是用来约束的。

**Comment by icarusion** [comment]
如果你非要如此，建议用 CSS 把遮罩层 hidden 掉，但我们不期望这样做。
