### ISSUE TITLE
想在row 和 col两个标签之间插入一个vue-draggable的draggable标签，实现拖拽功能

### ISSUE THREAD

**Issue by huangyanyang** [iview/iview#1661]
想在row 和 col两个标签之间插入一个vue-draggable的draggable标签，实现拖拽功能，但是由于col组件的上层组件是draggable而不是row，就会报this.$parent.updateGutter is not a function这样的错误，请问这个怎么解决？

**Comment by huangyanyang** [comment]
@Evan You

**Comment by huangyanyang** [comment]
@yyx990803

**Comment by icarusion** [comment]
兄弟，你 @ 错了人了。
Row 和 Col 是必须连用的，所以不能分离。你可以用 div 来代替 Col。

**Comment by huangyanyang** [comment]
用div来代替col的话就不能自适应了

**Comment by icarusion** [comment]
恩，所以你需要取舍。

**Comment by huangyanyang** [comment]
其实如果没有用到这个gutter这个属性的话，为什么一定要在row组件执行gutter的那个方法呢，我觉得你们需要优化一下

**Comment by huangyanyang** [comment]
其实之间去ivew的源码中去把那个方法那一行注释掉就不会报那个错了，但是你上传到git上他是不会修改node_module里面的东西的，别人npm install下来还是会报错的
