### ISSUE TITLE
Page 分页组件同时改变current与page-size的值的时候会自己跳转到第1页并触发on-change事件

### ISSUE THREAD

**Issue by su1924** [iview/iview#1662]

**Comment by rijn** [comment]
plz provide jsfiddle

**Comment by lavenkin** [comment]
我重述下@rijn的问题应该是当触发on-page-size-change事件时，会自动触发on-change事件，这个复现很简单，先触发on-change事件到任何一页，接着触发on-page-size-change事件，会发现自动触发了on-change事件

**Comment by matisha001** [comment]
![image](https://user-images.githubusercontent.com/19816700/39042485-84d38a04-44bd-11e8-9958-4e9a41bd3838.png)

大兄弟，这么搞就会只会请求一次数据

**Comment by zjafei** [comment]
我觉得这个明显就是iview组的api写的不好
我就是要单纯的change page size 你非要给我整合一个当不是第一页我给你同时来个change page 到第一页
这个明显就是业务耦合了
我有在需求我自己会在需要的时候加上 change page
一个接口最好只做一件事情 除非业务上就是强耦合的
以上是我的个人意见

**Comment by matisha001** [comment]
我已经给你提供了解决的办法，iview的api写的不好，但是按照我提供的那种方式完全可以解决你这问题

**Comment by matisha001** [comment]
建议iview研发小组，多看看ant-design的api接口。没错是ant-design。如果有技术问题，我可以提供技术支持
