### ISSUE TITLE
建议增加input悬浮标签

### ISSUE THREAD

**Issue by libing-cheer** [iview/iview#1665]
1. 在做手机端的时候，如果有很多input，看的时候有时候会比较混乱；

2. 不易给用户造成混淆。

input悬浮代码示例：
http://runjs.cn/code/9qv4zmvx

input悬浮相关文章：
http://mp.weixin.qq.com/s/8912iP2VEWa1aTPASmz7DQ

**Comment by icarusion** [comment]
iView 是一套基于 Vue.js 的开源 UI 组件库，主要服务于 PC 界面的中后台产品。所以不考虑对移动端的支持。
