### ISSUE TITLE
affix的left值是固定的吗

### ISSUE THREAD

**Issue by huangyanyang** [iview/iview#1666]
![image](https://user-images.githubusercontent.com/19208961/29594274-779ec94a-87e2-11e7-916c-459e33a73569.png)
大兄弟，为什么图钉是固定left值为50，而且是像素，这样在移动端很不好看啊，是我哪里写错了吗
![image](https://user-images.githubusercontent.com/19208961/29594302-b47a302a-87e2-11e7-8130-de4a52f87bb8.png)

**Comment by icarusion** [comment]
使用前请先阅读 iView 文档规范。
iView 是一套基于 Vue.js 的开源 UI 组件库，主要服务于 PC 界面的中后台产品。所以并不支持移动端。

**Comment by huangyanyang** [comment]
都做了自适应栅格系统还不支持移动端，伤心

**Comment by cuizhangxiao** [comment]
我想去掉left值应该在哪里操作？没找到位置
