### ISSUE TITLE
[Feature Request] table中的td添加title属性

### ISSUE THREAD

**Issue by mizhiwu** [iview/iview#1667]
你好。

当table中使用ellipsis属性时，字段很常时将显示。。。
可否在td中添加title属性让用户能看到完整内容？
查看了下源码，即使我用render方法也无法修改td的内容。

可否添加title属性到下面代码中(未安装程序进行测试)
table-body.vue
`<td v-for="column in columns" :title="row[column.key]" :class="alignCls(column, row)">`

谢谢

**Comment by cn-xufei** [comment]
对啊，超出隐藏的配置都出来了，很需要title属性 +1🙃

**Comment by mizhiwu** [comment]
@icarusion 可以告知下为什么关闭吗？

**Comment by leixu2txtek** [comment]
同样存在该问题，如果 通过 render 来实现的话，就太多需要写render 的地方了。。。。
默认增加 title 会比较合适

**Comment by leixu2txtek** [comment]
#3334

**Comment by mizhiwu** [comment]
@leixu2txtek 
目前我是用render来解决该问题的。当然个人觉得不是很理想的解决方案。
`render: (h, params) => {
    return h('div', [
        h('Tooltip', {
            props: {
                content: params.row.factoryCode,
                placement: 'top'
            },
        }, params.row.factoryCode)
    ]);
}`

@icarusion 
首先感谢您开源这个项目，收益良多。
您也可否花几分钟给科普下为什么排斥title而推崇用tooltip解决呢？
我的页面因为数据叫多，明显比不加render的要慢一些。

当然如果你同意的话，我可以添加这部分功能让您review

**Comment by leixu2txtek** [comment]
@mizhiwu  作者承诺了在  3.0 版本中增加配置来实现该功能，但是应该还是推荐 tooltip 吧。

数据量有多大讷你们？ 不分页吗？

**Comment by leixu2txtek** [comment]
@mizhiwu  都用 render  简直是噩梦 😀

**Comment by rocky-191** [comment]
同样的问题，不想用render
