### ISSUE TITLE
使用this.$modal.confirm进行二次触发时会出现第二个对话框闪退的问题

### ISSUE THREAD

**Issue by huangyanyang** [iview/iview#1668]
![image](https://user-images.githubusercontent.com/19208961/29603650-82df3c4c-8817-11e7-8370-87ad27f4d495.png)

**Comment by jijihome** [comment]
好似不支持嵌套吧

**Comment by angrytoro** [comment]
@huangyanyang 看源码是全局只保存一个实例，如果旧的实例没有销毁，马上再创建新实例，肯定是会报错的。

**Comment by icarusion** [comment]
You can use `$nextTick`

**Comment by yangxiyangxi** [comment]
setTimeout延时300毫秒。再调用就不会闪退了
