### ISSUE TITLE
iview中的下拉菜单Dropdown如何获取其子级Dropdown-item的name值？

### ISSUE THREAD

**Issue by YJZ-S** [iview/iview#1673]
![image](https://user-images.githubusercontent.com/26481272/29610605-4aad84b2-882d-11e7-8b61-92789451f120.png)

点击事件可以触发，但是name值不知如何获取

**Comment by icarusion** [comment]
```
methods: {
    doMore (name) {
        console.log(name);
    }
}
```

**Comment by YJZ-S** [comment]
我是这么写的，但是打印出来是undefined

**Comment by icarusion** [comment]
provide your online demo

**Comment by YJZ-S** [comment]
[demo.zip](https://github.com/iview/iview/files/1245104/demo.zip)

**Comment by icarusion** [comment]
Use jsfiddle or codepen, do not use file please.

**Comment by YJZ-S** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>iview example</title>
    <link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
    <script type="text/javascript" src="http://vuejs.org/js/vue.min.js"></script>
    <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>
</head>
<body>
<div id="app">
    <Dropdown class='drop-menu' trigger="click" @on-click='doMore()' style="width: 100%;">
			<a href="javascript:void(0)">档位选择
				<Icon type="ios-arrow-down"></Icon>
			</a>
			<Dropdown-menu slot="list">
				<Dropdown-item name='gear1' class='fontsizes'><span>599 - 999</span><i>◎</i></Dropdown-item>
				<Dropdown-item name='gear2' class='fontsizes'><span>999 - 1999</span><i>◎</i></Dropdown-item>
				<Dropdown-item name='gear3' class='fontsizes'><span>1999 - 2999</span><i>◎</i></Dropdown-item>
				<Dropdown-item name='gear4' class='fontsizes'><span>2999 - 3999</span><i>◎</i></Dropdown-item>
				<p class='unit-money'>单位：rmb</p>
			</Dropdown-menu>
		</Dropdown>
</div>
<script>
    new Vue({
        el: '#app',
        data: {
            visible: false
        },
        methods: {
            doMore (name) {
				console.log(name)
            }
        }
    })
  </script>
</body>
</html>

**Comment by YJZ-S** [comment]
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>iview example</title>
    <link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
    <script type="text/javascript" src="http://vuejs.org/js/vue.min.js"></script>
    <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>
</head>
<body>
<div id="app">
    <Dropdown class='drop-menu' trigger="click" @on-click='doMore()' style="width: 100%;">
			<a href="javascript:void(0)">档位选择
				<Icon type="ios-arrow-down"></Icon>
			</a>
			<Dropdown-menu slot="list">
				<Dropdown-item name='gear1' class='fontsizes'><span>599 - 999</span><i>◎</i></Dropdown-item>
				<Dropdown-item name='gear2' class='fontsizes'><span>999 - 1999</span><i>◎</i></Dropdown-item>
				<Dropdown-item name='gear3' class='fontsizes'><span>1999 - 2999</span><i>◎</i></Dropdown-item>
				<Dropdown-item name='gear4' class='fontsizes'><span>2999 - 3999</span><i>◎</i></Dropdown-item>
				<p class='unit-money'>单位：rmb</p>
			</Dropdown-menu>
		</Dropdown>
</div>
<script>
    new Vue({
        el: '#app',
        data: {
            visible: false
        },
        methods: {
            doMore (name) {
				console.log(name)
            }
        }
    })
  </script>
</body>
</html>`

**Comment by YJZ-S** [comment]
这样吗？

**Comment by YJZ-S** [comment]
https://gist.github.com/anonymous/85adac9fba0d79b235094675f5e6c67c

**Comment by YJZ-S** [comment]
Like this?

**Comment by YJZ-S** [comment]
https://codepen.io/jiexiansen/pen/jLKmpo?editors=1111

**Comment by icarusion** [comment]
```
@on-click='doMore'
```
不带括号

**Comment by YJZ-S** [comment]
Ok, thank you very much!

**Comment by YJZ-S** [comment]
that's very nice of you!

**Comment by YJZ-S** [comment]
不好意思打扰一下，Dropdown点击事件触发之后可以获取当前点击元素（Dropdown-item）中的其它内容吗？还是只能获取name值？

**Comment by ihuguowei** [comment]
@YJZ-S RTFM:
https://www.iviewui.com/components/dropdown#Dropdown_events
just kidding!

**Comment by YJZ-S** [comment]
Still not very understanding
