### ISSUE TITLE
下拉菜单没有根据自身位置自动向上或者向下展开，只有向下，当在页面底部点击时出现下拉框撑到屏幕外

### ISSUE THREAD

**Issue by Cannylcn** [iview/iview#1678]

**Comment by Cannylcn** [comment]
下拉菜单没有根据自身位置自动向上或者向下展开，只有向下，当在页面底部点击时出现下拉框撑到屏幕外

**Comment by SergioCrisostomo** [comment]
@Cannylcn can you provide a example for this problem?

使用下面的在线链接可以快速创建示例 
https://codepen.io/anon/pen/BWwVoy
