### ISSUE TITLE
使用分页方案解决Select在大数据量时卡顿的问题

### ISSUE THREAD

**Issue by OXOYO** [iview/iview#1679]
在使用select时遇到数据量上千的情况，目前实现的一种优化方案就是分页。
这样可以有效的控制可见的option数量。

其他同学如有其他方案，欢迎讨论。

![qq 20170824185543](https://user-images.githubusercontent.com/5074207/29663478-e60eb6d0-88fd-11e7-906c-162daef00afa.png)

**Comment by kiddkyd1412** [comment]
分页是解决思路，但是一般如果单页有100行以上的选项，基本都是不具备可选择性的吧？

**Comment by OXOYO** [comment]
@kiddkyd1412 我们实现的是搜索加分页，分页量50，可以做到性能和体验均衡。

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
