### ISSUE TITLE
[Dropdown bug] 在 fixed 元素下使用Dropdown组件有bug

### ISSUE THREAD

**Issue by DeepenLau** [iview/iview#1682]
## 描述
在出现竖向滚动条和横向滚动条的时候，拖动横向滚动条时并且document.body.scrollTop 为0时，dropdown 组件定位会跟着移动，document.body.scrollTop 不为0 则正常
## gif：
![iviewdropdownbug](https://user-images.githubusercontent.com/14030995/29696671-00e026f4-897d-11e7-8d8a-d3d87894aca1.gif)

## 在线演示
https://codepen.io/anon/pen/eEjpRB

**Comment by DeepenLau** [comment]
一个月了，希望有人答复一下，谢谢

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
