### ISSUE TITLE
iview 有类似 treetable 的组件吗？

### ISSUE THREAD

**Issue by rhymax** [iview/iview#1689]

**Comment by zhdwwf** [comment]
iview自身不带，这有一个其他人基于iview实现的可以参考
[https://github.com/huanglong6828/vue-tree-grid](https://github.com/huanglong6828/vue-tree-grid)

**Comment by rhymax** [comment]
OK 谢谢

**Comment by guiguoershao** [comment]
为啥iview组件里面不整个tabletree呢？ 感觉这个用的场景很多啊！

**Comment by Ludidi** [comment]
@guiguoershao 请问这个功能怎么写，能请教下吗
