### ISSUE TITLE
使用table组件带分页，切换分页时会很慢，我的表格列比较多，数据比较大，这个大概是什么原因啊

### ISSUE THREAD

**Issue by mickeyzhou** [iview/iview#169]

**Comment by icarusion** [comment]
已知性能问题，后续会优化

**Comment by vivinbear** [comment]
我也遇到了,就是不加分页,一个表格有上千条数据,直接卡个5 6分钟,有可能会内存溢出,有可能不溢出

**Comment by joe434200** [comment]
itable卡顿这个问题，已经得到改善了吗？

**Comment by icarusion** [comment]
建议升级到 2.0 吧，Table 的性能提升2倍多。但是如果你的数据庞大，建议做分页，即使你单独渲染几千个 Vue 示例，那也同意会卡。

**Comment by cdmin207078** [comment]
100条数据，一切正常
500条数据，cpu 就已经 30%, 内存 400m ,鼠标滚轴滚动有卡顿感
1000条数据  cpu 50%, 内存 600M  chrome 卡死。

**Comment by rijn** [comment]
@cdmin207078 Please use Page if you have too many data. Displaying hundreds even thousands of lines of data in one page, i.e. rendering all of them at the same time, is not a normal usage.

**Comment by w3cmark** [comment]
@icarusion 
table卡顿不只是是在数据多的情况出现，200条数据，当鼠标hover在table上面时滚动页面会很卡，当鼠标移到table外面时，滚动页面就正常，感觉是table的hover效果性能问题，建议hover效果可以设置开启关闭。
版本：2.0.0-rc.10

**Comment by zfdai** [comment]
我Select Option 数据到300多条的时候，用v-for遍历，大概有将近2s 的页面卡死。。。

**Comment by Aleczhang1992** [comment]
@mickeyzhou [根据这里说明 height props](https://help.sap.com/saphelp_nw73/helpdata/en/49/803210c6242221e10000000a42189d/frameset.htm)
iview的table组件，当设置height属性时，表头固定，body会放在iframe中显示，然后会导致iframe不断重绘，数据一多，就会卡顿，产生性能问题，很不友好的设计，解决方法，自己外层加个div设置下就好。
![image](https://user-images.githubusercontent.com/15828753/33013338-a0ae91e4-ce1e-11e7-8652-9687c6296341.png)

**Comment by Kunkka0229** [comment]
我也是固定了高度，做了分页一页10条，但是列有四五十条，每次查询都要卡上几秒钟，而且左右滑动会感觉很卡，我把高度去掉感觉不是很明显啊

**Comment by baixiaoji** [comment]
固定了高度，分页展示150条数据，交互已经卡顿到3秒以上反应了，已经升级到了3.0了，但是我还没用分页，在点击选中已经出现了卡顿现象了

**Comment by physicsLoveJava** [comment]
在内存较少的电脑上，容易卡顿，并且会出现崩溃情况（js客户端）,换成别的table组件不会出现这样的问题

**Comment by pomestyle** [comment]
100条数据, 字段大概20个，中间还进行了一些计算，后端接口最慢1s-2s 响应数据，基本都在1s内返回，100条基本渲染 最快 2 -4s  最慢 4s以上了，有时候会卡死

**Comment by Liang-classmate** [comment]
> 100条数据, 字段大概20个，中间还进行了一些计算，后端接口最慢1s-2s 响应数据，基本都在1s内返回，100条基本渲染 最快 2 -4s 最慢 4s以上了，有时候会卡死

表格列配置有用到render渲染吗？大量使用render会影响table组件的性能。

**Comment by pomestyle** [comment]
是的，有大量的render渲染，我也发现了这个问题，解决：1 从业务角度优化 2 后端提前计算好部分结果，前台减少计算。
