### ISSUE TITLE
Tree组件

### ISSUE THREAD

**Issue by jeremysnake** [iview/iview#1693]
对于提供的Tree组件，如果树的层级为3级，第一次点击最里面的第三级的一个复选框。出现的问题 : 最外面的第一级会被选中（正常），可是第二级的却没有被选中。这是一个很严重的bug。

**Comment by SergioCrisostomo** [comment]
@jeremysnake could you provide a example for this behaviour please?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/
