### ISSUE TITLE
Table组件columns里的title怎么绑定数据？

### ISSUE THREAD

**Issue by joenil** [iview/iview#1697]
感谢iview给开发者带来这么好的UI组件库，但是我在开发中碰到这样一个场景：
``` javascript
{
     title: '报名人', // 这里的值不是固定的，我想绑定一个model
     width: 260,
     ...
}
```
请问有办法实现吗？

**Comment by joenil** [comment]
目前想到的解决方法是watch一个切换场景的属性，然后赋给colums[1].title不同的值，但是如果title支持赋值一个vnode，是不是就可以动态绑定数据了？

**Comment by zhdwwf** [comment]
可以给整个columns绑定一个model
示例：[http://output.jsbin.com/gidonuk](http://output.jsbin.com/gidonuk)

**Comment by joenil** [comment]
@zhdwwf 谢谢！不过我的columns数据比较复杂，里面还包含了每个cell的render函数。我找到了一种更加合理的解决方案：
```
renderHeader: () => {
  return <span>{this.userTypeText}</span>
}
```
