### ISSUE TITLE
[Feature Request] Checkbox 可以加个选项禁用勾选时的渐变效果吗

### ISSUE THREAD

**Issue by didikeke** [iview/iview#1698]
如果在勾选或取消checkbox后，根据checkbox数据变化执行耗时比较多的运算时，checkbox的渐变会让勾选效果看起来好久没反应或者卡顿。 即便使用Vue.nextTick去调用运算也没有用。

为了避免卡顿，目前只好在checkbox数据变化之后 setTimout大概300ms后去执行计算。

如果能有个禁用checkbox渐变效果的选项就好了。感谢～

**Comment by didikeke** [comment]
不只是checkbox数据变化后有运算，checkout的勾选状态会卡。只要有运算时。勾选checkout的渐变都回卡顿的让用户以为没点上，然后来回按几次。

**Comment by selma-li** [comment]
I also encountered this problem. Then I use `<input type="checkbox">` instead of the `Checkbox` component and fix the problem.
```
<div id='example-3'>
  <input type="checkbox" id="jack" value="Jack" v-model="checkedNames">
  <label for="jack">Jack</label>
  <input type="checkbox" id="john" value="John" v-model="checkedNames">
  <label for="john">John</label>
  <input type="checkbox" id="mike" value="Mike" v-model="checkedNames">
  <label for="mike">Mike</label>
  <span>Checked names: {{ checkedNames }}</span>
</div>
```
