### ISSUE TITLE
poptip在transfer模式下，冒泡出来的东西一点击就消失了。

### ISSUE THREAD

**Issue by xcodebin** [iview/iview#1700]
问题： poptip在transfer模式下，冒泡出来的东西一点击就消失了。非transfer模式的冒泡出来的东西可以操作。

复现：直接看源码example /router/ poptip的例子就有这个问题。transfer模式冒泡出来的内容完全无法进行操作。
原因分析：问题应该是搬到Body之后v-clickoutside被触发了。

**Comment by mcc108** [comment]
这样问题怎么解决？@icarusion

**Comment by philipyao** [comment]
同样遇到这个问题，怎么解决的？@xcodebin

**Comment by mcc108** [comment]
@icarusion @SergioCrisostomo

**Comment by victorting** [comment]
@xcodebin 请问你反应的问题解决了吗现在？ 我也遇到这样的问题，不知道怎么处理
