### ISSUE TITLE
inputNumber组件可以去掉默认值吗？

### ISSUE THREAD

**Issue by blankxf** [iview/iview#1701]

**Comment by hangzhouwjh** [comment]
值设置成null就是空的了

**Comment by GloryXia** [comment]
如果设置默认值为null的话，我的输入的值就会变成默认值，如果手动按delete键把那个值删除掉，组件一blur，值就会变回我后来输入的那个值，不得不说这个组件的特性挺让人无语的

**Comment by Rainnut** [comment]
是的，我现在也遇到一样的问题，你们知道怎么解决吗？
