### ISSUE TITLE
Poptip 无法触发 on-popper-show 事件

### ISSUE THREAD

**Issue by 0604hx** [iview/iview#1702]
**问题描述**

 对 `Poptip `设置 `@on-popper-show` 事件回调，当 `Poptip `显示时并没有正常调用

**可能原因**

查看源码，发现并没有 `on-popper-show` 相关的事件冒泡

**Comment by mashakulaye** [comment]
你需要更新iview  (npm update iview)
2.1.0 版本修复了这个问题

**Comment by icarusion** [comment]
try to update `2.2.0`
