### ISSUE TITLE
Poptip如果带日历控件的话，日历控件渲染高度不正确

### ISSUE THREAD

**Issue by yaakua** [iview/iview#1703]
代码的结构是在Poptip里面有一个DatePicker组件，这样导致这个DatePicker组件无法正确渲染高度。
如下图：
![wx20170828-135100](https://user-images.githubusercontent.com/1543846/29760804-5d8929aa-8bf8-11e7-91c6-98947655d84b.png)

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
