### ISSUE TITLE
请教之前的项目使用了iview-rc12版本,现在如何在npm install 下载对应的老版本

### ISSUE THREAD

**Issue by ChaoLeer** [iview/iview#1706]
请教使用了iview-rc12版本,现在重新install,就变成2.2.0,也就意味着整个项目的table render不能正常工作,现在在tag标签里找到了rc-12版本,需要手动下载然后替换Node-modules里的相应代码才可以吗?

**Comment by icarusion** [comment]
去查询 npm 的基本用法
