### ISSUE TITLE
form-item.vue实现的验证,v-for生成的输入框实现验证要拆开太复杂

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1707]
form-item.vue实现的验证,v-for生成的输入框实现验证要拆开太复杂。
多个form-item无法指向同一个rule,只能用自运行函数去生成Validator对象。
https://jsfiddle.net/j0q12fsh/11/

**Comment by icarusion** [comment]
iView validate based on https://github.com/yiminghe/async-validator
