### ISSUE TITLE
tabs中的tab由隐藏变成显示后显示顺序不正确

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1709]
tabs中的tab由隐藏变成显示后显示顺序不正确
https://jsfiddle.net/j0q12fsh/14/

**Comment by rijn** [comment]
You have to use `v-show`.

**Comment by rijn** [comment]
You have to use `v-show` in this case. We're using `$children` currently which will not keep a consistent order.

**Comment by yangdan8** [comment]
v-show在tabs中根本没有办法使用,你试试就知道了

**Comment by rijn** [comment]
Sorry about that. But we cannot guarantee the order since it's from Vue directly. You could rerender all tabs when necessary. Probably we could provide the visibility option later.

**Comment by yangdan8** [comment]
v-show在tabs中根本没有办法使用,这个issue就关了?

**Comment by rijn** [comment]
@yangdan8 I know that. It's my mistake. You cannot use `v-show` in Tabs. What I suggest is you could call rerender the whole Tabs component when you going to insert tabs.

**Comment by jiafeilu** [comment]
@yangdan8  同样遇到这个问题，你的解决了吗

**Comment by tracybug** [comment]
同样遇到这个问题，解决了么？

**Comment by ljjandx** [comment]
我也遇到了这个问题，用v-for渲染tab列表，tab列表变化时没按我定义的顺序来，结果今天误打误撞地突然好了，最后发现是因为把之前写的 `:key = "v.label"` 写错了，写成`:key = "v.lebel"`了，顺序就对了。。。。。。
是的，你没看错！写错了！然后就对了！感觉发现了新世界。。。
