### ISSUE TITLE
当Tabs的animated=“false”,Tab-pane里的i-table组件除了第一个有宽度，其他都没有没有

### ISSUE THREAD

**Issue by hya-1995-5-21** [iview/iview#171]
### 问题现象，以及你期望的结果是怎样的?
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>iview example</title>
    <link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
    <script type="text/javascript" src="http://v1.vuejs.org/js/vue.min.js"></script>
    <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>
</head>
<body>
<div id="app">
		<Tabs type="card" :animated="false">
			<Tab-pane label="tab1" icon="ios-compose-outline">
				<i-table border :content="self" :columns="columns7" :data="data6"></i-table>
			</Tab-pane>
			<Tab-pane label="tab2" icon="ios-compose-outline">
				<i-table border :content="self" :columns="columns7" :data="data6"></i-table>
			</Tab-pane>
		</Tabs>
</div>
<script>
    new Vue({
        el: '#app',
          data () {
            return {
                self: this,
                columns7: [
                    {
                        title: '姓名',
                        key: 'name',
                        render (row, column, index) {
                            return `<Icon type="person"></Icon> <strong>${row.name}</strong>`;
                        }
                    },
                    {
                        title: '年龄',
                        key: 'age'
                    },
                    {
                        title: '地址',
                        key: 'address'
                    },
                    {
                        title: '操作',
                        key: 'action',
                        width: 150,
                        align: 'center',
                        render (row, column, index) {
                            return `<i-button type="primary" size="small" @click="show(${index})">查看</i-button> <i-button type="error" size="small" @click="remove(${index})">删除</i-button>`;
                        }
                    }
                ],
                data6: [
                    {
                        name: '王小明',
                        age: 18,
                        address: '北京市朝阳区芍药居'
                    },
                    {
                        name: '张小刚',
                        age: 25,
                        address: '北京市海淀区西二旗'
                    },
                    {
                        name: '李小红',
                        age: 30,
                        address: '上海市浦东新区世纪大道'
                    },
                    {
                        name: '周小伟',
                        age: 26,
                        address: '深圳市南山区深南大道'
                    }
                ]
    }
            },
        methods: {
            show (index) {
                this.$Modal.info({
                    title: '用户信息',
                    content: `姓名：${this.data6[index].name}<br>年龄：${this.data6[index].age}<br>地址：${this.data6[index].address}`
                })
            },
            remove (index) {
                this.data6.splice(index, 1);
            }
        }
    })
  </script>
</body>
</html>

**Comment by rijn** [comment]
内部iTable加v-if="active-key"即可。强制在切换到该tab时才开始绘制。

```
<template>
    <Tabs :active-key.sync="activeKey" type="card" :animated="false">
        <tab-pane label="标签一" key="key1">
            标签一的内容
            <i-table v-if="activeKey === 'key1'" :columns="columns" :data="data"></i-table>
        </tab-pane>
    </Tabs>
</template>
<script>
    export default {
        data () {
            return {
                activeKey: 'key1',
                columns: [],
                data: []
            }
        }
    }
</script>
```

**Comment by hya-1995-5-21** [comment]
现在好了 谢谢
