### ISSUE TITLE
需求：InputNumber增加slot="prepend"和slot="append"

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1710]
需求：InputNumber增加slot="prepend"和slot="append"
能否按照input一样增加这个选项?

**Comment by max-boy** [comment]
我也有这个需求，有时间提个PR吧！

**Comment by Bloom2036** [comment]
为什么这个被关了而没有解决方法呢？？？？

**Comment by mrerhuo** [comment]
@icarusion why closed?

**Comment by icarusion** [comment]
https://www.iviewui.com/new-issue
到这里按要求提交
