### ISSUE TITLE
Date-picker 组件双击绑定的是Date对象

### ISSUE THREAD

**Issue by dingsk** [iview/iview#1714]
Date-picker 组件双击绑定的是Date对象，非格式化后的日期格式字符串。同理在from嵌套绑定的也是Date对象？

**Comment by songlipeng2003** [comment]
输入的可以是字符串，但是输出的肯定是date对象，最好使用momentjs格式化一下

**Comment by SergioCrisostomo** [comment]
@dingsk the DatePicker has received many fixes. Please check again with the current code on master.

If your problem still exists please add a exemple so we can check. Thanks

使用下面的在线链接可以快速创建示例
https://codepen.io/anon/pen/KvJJdw
