### ISSUE TITLE
Collapse 折叠面板 使用v-for 展开全展开 关闭全关闭

### ISSUE THREAD

**Issue by gh81997167** [iview/iview#1716]
Collapse 折叠面板 使用v-for 展开全展开 关闭全关闭

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>iview example</title>
    <link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
    <script type="text/javascript" src="http://vuejs.org/js/vue.min.js"></script>
    <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>
</head>
<body>
<div id="app">
    <i-button @click="show">Click me!</i-button>
    <Modal v-model="visible" title="Welcome">欢迎使用 iView</Modal>

	<template>
    <Collapse accordion  v-model="value1111">
        <Panel name="{{rank.name}}" v-for="rank in rankingLists" @change="aaaaa">
            {{rank.title}}
            <p slot="content">{{rank.detail}}</p>
        </Panel>
    </Collapse>
</template>

</div>
<script>
    new Vue({
        el: '#app',
        data: {
            visible: false,
            value1111:"aaa",
            rankingLists: [{
						id: 1,
						src: "img/game.png",
						title: "欢乐斗地主1",
						detail: "1个人玩过",
						name:"aaa"

					},
					{
						id: 2,
						src: "img/game.png",
						title: "欢乐斗地主2",
						detail: "2个人玩过",
						name:"bbb"

					},
					{
						id: 3,
						src: "img/game.png",
						title: "欢乐斗地主3",
						detail: "3个人玩过",
						name:"ccc"

					},
					{
						id: 4,
						src: "img/game.png",
						title: "欢乐斗地主4",
						detail: "4个人玩过",
						name:"ddd"

					},
					{
						id: 5,
						src: "img/game.png",
						title: "欢乐斗地主5",
						detail: "5个人玩过",
						name:"eee"

					},
					{
						id: 6,
						src: "img/game.png",
						title: "欢乐斗地主6",
						detail: "6个人玩过",
						name:"fff"
					},
					{
						id: 7,
						src: "img/game.png",
						title: "欢乐斗地主7",
						detail: "7个人玩过",
						name:"ggg"

					}]

        },
        methods: {
            show: function () {
                this.visible = true;
            },
            aaaaa: function () {
            	alert(1)

            }
        }
    })
  </script>
</body>
</html>

**Comment by zhdwwf** [comment]
name="{{rank.name}}" 这种用法不对，特性上不能用{{}}，应该是v-bind:name="rank.name"或者:name="rank.name"

**Comment by gh81997167** [comment]
好的 谢谢
