### ISSUE TITLE
Tree控件半选状态无勾选问题

### ISSUE THREAD

**Issue by CharleySc** [iview/iview#1717]
通过js设置子树的checked=true时，假设有2个子树节点，只设置1个子树节点为勾选时 父级节点并无半勾选状态，即使是半勾选状态，此checked也不等于true。这样是不合逻辑的吧 ？子节点有其中一个true，父节点勾选不理应也为true？只是UI显示为半选而已。
![image](https://user-images.githubusercontent.com/19809888/29806446-d6328dc8-8cc1-11e7-805c-83351695f2f8.png)

**Comment by joneqian** [comment]
我也遇到了这个问题

**Comment by CharleySc** [comment]
## **希望作者能够看到。iview 1.0 是没这个问题的。**

**Comment by Gzoye** [comment]
很尴尬  一样被这问题纠结了一天

**Comment by Gzoye** [comment]
getCheckedNodes: function getCheckedNodes() {
            let ok = false;
            let result; //
            let tmparr=[];
            var nodes = (0, _assist.findComponentsDownward)(this, 'TreeNode');         
            return nodes.filter(function (node) {
                return node.data.checked;
            }).map(function (node) {
                console.log(node)
                // return node.data
                tmparr.push(node.data.id);
                let item = node;
                //xiugaipart
                while (!ok) {
                    console.log('=======================')
                    console.log(item.$parent)
                    if (!item.$parent.data || !item.$parent.data.id) {
                        result = tmparr;
                        ok = true;
                        return
                    }
                    item = item.$parent;
                    tmparr.push(item.data.id);
                };
                console.log(result)
                // return result;
                
            });

今天起来改了下源码 通过节点去遍历查找吧 = =、

**Comment by CharleySc** [comment]
@Gzoye 唉 这个项目我没用组件式开发，是传统.html页面开发的，我目前用到这个tree控件的页面单独换成1.0版本临时解决问题。等作者修复后再换回来2.0酱紫

**Comment by Baoyx007** [comment]
遇到同样的问题.

但是, @CharleySc 
> 子节点有其中一个true，父节点勾选不理应也为true

是不对的. 

父节点为 true, 那么子节点应该都为 true; 反过来不成立.

**Comment by CharleySc** [comment]
@Baoyx007 你看少了一个问号了吧 我这是反问句啊

**Comment by Baoyx007** [comment]
找到个解决方法, js设置子树的checked后, 调用下面的代码,  父级节点就能获得半勾选状态.

```
      this.$nextTick(() => {
        this.$refs.tree.updateData(false);
        this.$refs.tree.broadcast('TreeNode', 'indeterminate')
      });
```

**Comment by hjpyh-ybxrz** [comment]
这段代码解决了显示问题，但是还是期望组件自带参数控制半选
