### ISSUE TITLE
分页组件设置placement=top 点击分页条数设置下拉框 下拉框向下显示

### ISSUE THREAD

**Issue by zxgaoray** [iview/iview#1719]
前置条件：
Page组件设置placement="top" show-sizer
复现步骤：
1.点击条数选择按钮，弹出条数选择，此时向上弹出
2.快速点击两次条数选择按钮，此时条数选择向下弹出

**Comment by icarusion** [comment]
popper 是在 300ms 后移除的，所以不能快速点击。

**Comment by 2010178081** [comment]
难道就没有解决方案了吗？
