### ISSUE TITLE
ie11下显示异常

### ISSUE THREAD

**Issue by HarryPoint** [iview/iview#1725]
![image](https://user-images.githubusercontent.com/19555586/29826008-b619d400-8d08-11e7-9931-8d01b94cb125.png)

# 见上图

**Comment by SergioCrisostomo** [comment]
@HarryPoint what component where you using? Can you see where in the code if you open the developer tools?

**Comment by HarryPoint** [comment]
在线示例![https://codepen.io/HarryPoint/pen/ZJmoRB]

**Comment by HarryPoint** [comment]
在文件 iview/src/components/tabs/tabs.vue
```js
```

**Comment by HarryPoint** [comment]
iview/src/utils/assist.js
# 76行
```js
const computed = document.defaultView.getComputedStyle(element, '');
```
ie 11 下获取的宽度不包含 padding 值（此时已经设置为box-sizing:border-box）

**Comment by icarusion** [comment]
https://github.com/iview/iview/pull/1546

**Comment by HarryPoint** [comment]
thanks!
