### ISSUE TITLE
Date-picker的 type="daterange"时， 清空数据后还保留2个null值

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#1730]
https://codepen.io/anon/pen/KvrREM

第一次点击按钮，弹出是空数组，
选择了数据后，在点击那个x，清空数据，再点击按钮，弹出[null,null],

清空后，不是应该返回空数组吗？
----------------------------------------------
这问题我好像明白了，控件的默认值不应该写[]，而是写null，
这样控件在空选的时候，会返回["",""]，
但是为何在清空后，不是返回["",""]，而是返回[null,null]？

**Comment by jerexyz** [comment]
同样碰到了这个问题
