### ISSUE TITLE
DatePicker的on-change事件所带参数与组件绑定到的数据不一致

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1745]
DatePicker的onchange事件所带参数与组件绑定到的数据不一致
为了做对比,我用了input的on-change事件来做比较,
input的on-change算比较符合逻辑,
而DatePicker的onchange事件时组件绑定到的数据实际并未修改,
只是dom上修改了input的值.
![qq 20170831102517](https://user-images.githubusercontent.com/16515026/29903506-cb9b1062-8e36-11e7-8a6b-87a21676d538.png)

https://jsfiddle.net/j0q12fsh/19/
![555555](https://user-images.githubusercontent.com/16515026/29903514-d4babbd4-8e36-11e7-94c0-5293f5edbc83.png)

**Comment by SergioCrisostomo** [comment]
Not sure this is a bug... @icarusion what do you think?
Should `on-change` fire after the `v-model` is updated?

**Comment by yangdan8** [comment]
https://jsfiddle.net/j0q12fsh/40/

**Comment by zhongxl19911006** [comment]
同样遇到这个问题。

**Comment by reallysix** [comment]
怎么解决这个问题呢???

**Comment by EPSON-LEE** [comment]
我认为这是一个bug
## 问题的原因： 
datepicker组件通过v-model进行双向绑定会触发这个组件中的input事件 (vue中自定义v-model指令的实现方式)，但是iview的datepicker组件里的文档没有列出input这个api，所以我们传到datepicker里的数据实际上都被这个组件篡改了。

https://jsfiddle.net/2fezrcgt/7/

## 解决方法： 
1. v-model更换为value，用on-change、input事件同时监听数据的变化。
1. v-model传入数据，时间的格式改为 new Date()，使用on-change监听数据变化。

-----------------------------------------------------
I think it's a bug
## reason： 
In datepicker component, two way binding in v-model directive will fire input event, (you could search how to use  v-model directive when registing a component).But in iview document, it don't list the input event. So our data passing to datepicker component is tampere.
## solutions： 
1. you could pass props to datepicker by 'value',and listen to the data change by using on-change and input event.
2. if you insist on using v-model directive, change the type to Date type.
