### ISSUE TITLE
Table columns with selection, set all data` _disabled` to `false`, the Checkbox all will be checked.

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1751]
Table组件数据行_checked全部为false且_desabled全部为true时全选框显示状态错误
全选框应该为未选中状态并非选中状态

https://jsfiddle.net/j0q12fsh/20/
![9999999](https://user-images.githubusercontent.com/16515026/29910263-cffdff3c-8e5b-11e7-827f-2121ad51ea47.png)

**Comment by leixu2txtek** [comment]
![image](https://user-images.githubusercontent.com/5109966/41084774-9e24879a-6a67-11e8-8e0b-b0057c7da1d8.png)

当表格复选框设置为 disabled 时并且都全选时，表头的全选并未选中
