### ISSUE TITLE
Table在注销的时候调用handleResize报错bug

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#1752]
我只能提供图片,在线实例无法重现,但在调用$refs时确实应该检测是否underfined
![77777777](https://user-images.githubusercontent.com/16515026/29910270-d856a634-8e5b-11e7-9a5d-831bce76a80d.png)

**Comment by icarusion** [comment]
Please update to version 2.2.0. If there is any problem, please reopen this issue.
