### ISSUE TITLE
Table 固定列的高度计算，应该减去横向滚动条的高度

### ISSUE THREAD

**Issue by linghucq** [iview/iview#1753]
![tim 20170831151948](https://user-images.githubusercontent.com/16009657/29911433-7087b52a-8e60-11e7-8d51-44997ec83c50.png)

**Comment by linghucq** [comment]
table.vue，285行：let height = this.bodyHeight + this.scrollBarWidth - 1;
这里是否应该是减去滚动条宽度？

**Comment by sampanxin** [comment]
这个问题有解决吗?  现在更新2.4.0 还是有这个问题
