### ISSUE TITLE
Collapse组件在采用ajax请求数据和v-for渲染Panel的时候设置的默认展开项不生效

### ISSUE THREAD

**Issue by ricosmall** [iview/iview#1763]
**iView 版本号**

2.2.0

**操作系统/浏览器 版本号**

macOS 10.12.6/Chrome 60

**Vue 版本号**

2.4.0

**能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）**

[bug复现在线示例](https://codepen.io/ricosmall/pen/ZJwGLe)

**复现步骤**

Panel采用v-for渲染，数据使用ajax异步请求获取。

**问题现象，以及你期望的结果是怎样的?**

1. 问题现象

Collapse组件的数据如果是ajax异步请求回来的话，那么设置的默认展开项不会生效。且第一次点击非默认设置展开的Panel的时候，默认设置为展开的那个Panel会一起打开。

如果数据是写死在data里面，则表现正常。

2. 期望结果

ajax请求数据的情况下，设置的默认展开项依然正常默认展开。

**你估计可能的原因是什么（选填）？**

我尝试过很多方法，有一个是有用的。示范如下：

修改前：

```javascript
new Vue({
  el: "#app",
  data() {
    return {
      showPanel: "1",
      list: []
    };
  },
  mounted() {
    this.getData();
  },
  methods: {
    getData() {
      axios
        .get("https://www.easy-mock.com/mock/59a7bf944006183e48ee7bfe/list")
        .then(result => {
          this.list = result.data.list;
        });
    }
  }
});
```

修改后：

```javascript
new Vue({
  el: "#app",
  data() {
    return {
      showPanel: "1",
      list: []
    };
  },
  mounted() {
    this.getData();
  },
  methods: {
    getData() {
      axios
        .get("https://www.easy-mock.com/mock/59a7bf944006183e48ee7bfe/list")
        .then(result => {
          this.list = result.data.list;
          this.showPanel = ""; // 把showPanel原来的值去掉
          setTimeout(() => { 
            this.showPanel = "1";  // 如果上面没有把showPanel的值改掉，此处取值和原来的showPanel一样，那么也不会生效。
          }, 0);
        });
    }
  }
});
```

[在线示例](https://codepen.io/ricosmall/pen/brzdKE)

我怀疑默认展开项设置的代码执行的时机不对。能力、时间有限，没有把源码翻出来修改调试。

**Comment by ricosmall** [comment]
@icarusion 这个bug会修复么？

**Comment by webrocom** [comment]
<Panel v-for="bank_update in banks" :key="bank_update.id" v-bind:name="bank_update.id">

Its woks

**Comment by xusenlin** [comment]
今天，这个问题也被我遇到了。
