### ISSUE TITLE
Tabs按照官网示例代码不能正常显示，已反复验证确实不行。

### ISSUE THREAD

**Issue by ILAOHE** [iview/iview#1764]
Tabs按照官网示例代码不能正常显示，已反复验证确实不行。

**Comment by ILAOHE** [comment]
cdn方式引用的，没有使用单文件组件。

**Comment by ILAOHE** [comment]
已解决。官方文档中Tabs里面的内容页是TabPanel，实际上用Tab-panel才行，这是cdn使用时的方式，webpack的还不知道什么情况，忘文档里面要说明这个问题。

**Comment by ILAOHE** [comment]
已解决。官方文档中Tabs里面的内容页是TabPanel，实际上用Tab-panel才行，这是cdn使用时的方式，webpack的还不知道什么情况，忘文档里面要说明这个问题。

**Comment by icarusion** [comment]
Thanks.
