### ISSUE TITLE
关于tree无法获取到半选节点的解决方案

### ISSUE THREAD

**Issue by Gzoye** [iview/iview#1767]
直接修改了下iview的getCheckedNodes方法 ， 思路是通过节点的$parent属性不断去查找上级节点 = =。暂时解决这个问题吧。  也是忧伤的 目前也没想到其他的方法。有其他建议可以交流。个人觉得最好的方法还是在半选状态的方法，设置其为true。或者作者加个可配置属性

    getCheckedNodes: function getCheckedNodes() {
      let ok = false;
      let result; //
      let tmparr = [];
      var nodes = (0, _assist.findComponentsDownward)(this, 'TreeNode');
      return nodes.filter(function(node) {
        return node.data.checked;
      }).map(function(node) {
        tmparr.push(node.data.id);
        let item = node;
        //xiugaipart
        while (!ok) {
          if (!item.$parent.data || !item.$parent.data.id) {
            result = tmparr;
            ok = true;

          } else {
            item = item.$parent;
            tmparr.push(item.data.id);
          }
        };
        console.log('=======================')
        console.log(result)
        return result;
      });

    },

**Comment by CharleySc** [comment]
很用心 先点个赞哦

**Comment by swit1983** [comment]
自己加了个方法
```
function findIviewTreeData(context,fn){
    const nodes = findComponentsDownward(context,"TreeNode");
    if(!fn){
        fn = node => node.data.checked||node.indeterminate;
    }
    return nodes.filter(fn).map(node => node.data);
};
```
