### ISSUE TITLE
iview 2.0.0版本，Table固定表头，内容纵向滚动条bug

### ISSUE THREAD

**Issue by mei1992** [iview/iview#1768]
原版本为iview@2.0.0-rc.17，更新为iview@ 2.0.0版本后，Table固定表头，内容纵向滚动条：.ivu-table-wrapper 和 .ivu-table-body 高度差异常（下方出现空白高度差区域），退回iview@2.0.0-rc.17版本后，恢复正常。

**Comment by fzz14hao** [comment]
这个问题在 "view-design": "^4.2.0",依然存在
