### ISSUE TITLE
Tab和Table相互嵌套的时候，table中栏目添加的按钮事件提示事件不存在

### ISSUE THREAD

**Issue by y80x86ol** [iview/iview#177]
### iView 版本号
0.9.13

### 操作系统/浏览器 版本号
Windows10/Chrome 53

### Vue 版本号
1.0.26

### 复现步骤
添加Tab，Tab中添加Table，渲染后，Table中的按钮事件提示找不到该方法

但是如果不添加Tab，直接使用Table，按钮事件就是正常的

### 问题现象，以及你期望的结果是怎样的?
希望修复一下这个BUG，十分感谢

**Comment by yajore** [comment]
你可以看下官方文档，有没有设置:content 属性

**Comment by y80x86ol** [comment]
哦，感谢，我看到的确文档有对content的描述。我看了示例，添加:content="self"，还是一样的错误。麻烦指正一下我的错误。

以下是文档描述：

“设置单元格内渲染自定义组件时的上下文。比如父级是 $parent，根组件是 $root，当 i-table 作为一个 slot 封装在其它组件里时，会很有用”

**Comment by icarusion** [comment]
@y80x86ol 给出能够复现问题的在线代码

**Comment by yajore** [comment]
@icarusion 看到我提的bug #175 了么，有没有临时解决方法
@y80x86ol 你的self变量在Vue的data中定义了么

**Comment by huanglong6828** [comment]
打扰一下 如果你itable 如果不设置宽度 是不是不能自动自适应  还要就是 你在itabs里嵌套 Date-picker 日期选择定位有没有偏移
