### ISSUE TITLE
关于iviwe文档对于一些API的用法说明存在的问题

### ISSUE THREAD

**Issue by webproblem** [iview/iview#1770]
对于近期iview文档的更新，发现存在一些细节问题，比如在一些API的用法说明下，都会有一些注意事项提醒用户在template/render 模式和非 template/render 模式等不同模式下使用不同的API，比如input输入框：
`注意：非 template/render 模式下，需使用 i-input。`
而在某些API用法文档中并没有类似这样的提示（比如radio单选框，checkbox多选框等），这样对于一些还不太熟悉iview规则的同学，很容易在使用过程中产生一些困扰。为避免减少对新手的一些困扰，还望对iview文档细节方面处理得更仔细，给用户一份更加完美的使用文档！

**Comment by SergioCrisostomo** [comment]
@webproblem thank you for your feedback!

If you have some specific suggestion you are welcome to send a fix suggestion, or just separate them out in separate issues. If its documentation related please open a issue here: https://github.com/iview/iview-doc/issues
