### ISSUE TITLE
建议更改默认标签名为中划线模式

### ISSUE THREAD

**Issue by liunewshine** [iview/iview#1771]
毕竟中划线模式是官方推荐模式。
目前的写法很多标签名和html默认标签名相同，比如Col，Input
但是这些标签在html中是不闭合的，就是不能`<input>test</input>`这么写
这就导致在`<Input>test</Input>`这种写法在webstorm和Intellij中会报错
![image](https://user-images.githubusercontent.com/7698511/29969008-dc6750d4-8f50-11e7-83df-881025a36082.png)

**Comment by yangpengfei369** [comment]
这种怎么处理啊, 像Col标签还是报错呀
