### ISSUE TITLE
Input上加上type="email"，会出现警告

### ISSUE THREAD

**Issue by zwz** [iview/iview#1772]
```
    <i-form ref="user" :model="user" :rules="userValidate">
        <i-form-item prop="email">
          <i-input type="email" v-model="user.email" placeholder="邮箱">
          </i-input>
        </i-form-item>
   <i-form>
...
   data () {
       return {
       ...
       userValidate: {
          email: [
            { required: true, message: '邮箱不能为空', trigger: 'blur' },
            { type: 'email', message: '邮箱格式不正确', trigger: 'blur' }
          ]
       }
       }
   }
```
大致如上这样的代码，console中会出现警告：
Invalid prop: custom validator check failed for prop "type".

去掉type，或者改成text，则警告消失

**Comment by zhdwwf** [comment]
iview的input type类型不支持email，只支持'text', 'textarea', 'password'

**Comment by zwz** [comment]
这样啊，这个文档里似乎没有写的样子

**Comment by icarusion** [comment]
https://www.iviewui.com/components/input#API
![image](https://user-images.githubusercontent.com/5370542/30000046-b1550eb8-9090-11e7-8114-1f6c77b60700.png)

**Comment by zwz** [comment]
哦哦，感谢
有点疑惑，为什么不支持email这样的类型，手机端输入时岂不是键盘不大友好

**Comment by zhdwwf** [comment]
个人观点：iview表单验证使用的[async-validator](https://github.com/yiminghe/async-validator)已经支持email验证了，没有重复实现的必要吧
另：手机端不在iview支持的范围，官网有说明

**Comment by zwz** [comment]
嗯，是的。谢谢
不过，如果能够尽量和标准（支持email, tel, url ...）保持一致，可能更便于使用
（刚接触iview，没看过代码实现，纯粹从使用者角度来说的）
