### ISSUE TITLE
table中金额等数字在表格中的体验不太友好

### ISSUE THREAD

**Issue by Moriarty93** [iview/iview#1774]
当要展现金额时，目前只有换行和超出省略，没有考虑到数字这种在表格中应该自动撑开宽度，或者能有个最小宽度属性

**Comment by icksky** [comment]
我也遇到这种情况。设置了宽度，数字显示不完整。不设置的话，换行显示也很不友好。表格列宽不能根据内容自动适应么？Sad...

**Comment by Moriarty93** [comment]
不知道能不能出个min-width

**Comment by icksky** [comment]
我现在临时解决方案是遍历数据，算出当前列最宽的一条数据作为列的宽度。内部系统 就只能先忽略性能了
