### ISSUE TITLE
分页组件，为什么每次on_change后，current都是1呢

### ISSUE THREAD

**Issue by xxliud** [iview/iview#1779]

**Comment by zhdwwf** [comment]
代码，示例贴一下啊，这么问别人怎么回答，我用的分页就是正常的

**Comment by xxliud** [comment]
![image](https://user-images.githubusercontent.com/8509171/30009831-d767a3e0-915d-11e7-9130-e7e6cf7addae.png)
![image](https://user-images.githubusercontent.com/8509171/30009834-dd7c29ae-915d-11e7-8717-106791c61cfc.png)
每次触发on-change方法，我都打印了下 current   但是都是1，刚才github样式刷不出来，没法上传附件

**Comment by icarusion** [comment]
use `.sync`

**Comment by xxliud** [comment]
问题解决了. 绑定current.sync解决
![image](https://user-images.githubusercontent.com/8509171/30011133-a6a6c6be-9167-11e7-86b2-9062bf5c7710.png)
