### ISSUE TITLE
建议更改table render的实现方式

### ISSUE THREAD

**Issue by liunewshine** [iview/iview#1780]
render看似牛逼,实则超级难用.
如果单元格的内容需要嵌套多层组件,又有很多事件,比如实现单元格内form表单,可以想象代码有多复杂.

**Comment by zhdwwf** [comment]
render灵活性最强，vue官方推荐用法，不觉得有更换的必要，如果觉得直接使用js复杂，可以用jsx语法，render也是支持的，参考文档：
[https://cn.vuejs.org/v2/guide/render-function.html](https://cn.vuejs.org/v2/guide/render-function.html)

**Comment by liunewshine** [comment]
@zhdwwf 了解

**Comment by weihongyu12** [comment]
可否在官网教程增加一下JSX的使用文档，感觉使用的频率蛮高的

**Comment by weihongyu12** [comment]
建议在官网加一下教程，感觉使用频率蛮高
