### ISSUE TITLE
tabs标签中套dropdown

### ISSUE THREAD

**Issue by 531431988** [iview/iview#1786]
如题，是否有考虑，
![image](https://user-images.githubusercontent.com/8703951/30019650-e1eac686-9193-11e7-8fe6-b1d0af38739b.png)
 编辑后结果显示不对， .ivu-dropdown-menu应该在 .ivu-select-dropdown里面，好像是slot=list没生效？求指点
![image](https://user-images.githubusercontent.com/8703951/30019668-f1fa1996-9193-11e7-9049-9c34ba9a58ff.png)

**Comment by icarusion** [comment]
用法不对，请阅读 Vue 文档 Render 函数用法。

**Comment by ihuguowei** [comment]
@531431988 可以用`render`一个自定义组件，自定义组件中套用iVew取代`render`的嵌套写法，简单好维护。

**Comment by 531431988** [comment]
@ihuguowei 小白一个，求个举子，我写的那个不知道哪套错了，能否给个tabs标签中套个dropdown的例子

**Comment by zhdwwf** [comment]
@531431988 slot与props是并列关系，不是嵌套，所以说要看vue render文档，文档能解决的尽量不要浪费别人时间
[https://cn.vuejs.org/v2/guide/render-function.html](https://cn.vuejs.org/v2/guide/render-function.html)
深入data object参数

**Comment by 531431988** [comment]
@zhdwwf  早上已经搞定谢谢

**Comment by zxblyy** [comment]
> @zhdwwf 早上已经搞定谢谢

您好，请问您这个是怎么解决的，可以回复我一下吗。谢谢
