### ISSUE TITLE
Table组件resize的问题

### ISSUE THREAD

**Issue by ChaoshengZhang** [iview/iview#1788]
后台管理系统，展开收缩左侧菜单后，table出现横线滚动条，宽度是足够的，看源码并没有给我们提供一个事件来让我们resize   table的宽度，只有在浏览器窗口改变大小的时候，才会resize；
大大如果能看懂我说的问题，希望你们花点时间解决一下。

**Comment by xieweijv** [comment]
遇到同样的问题，页面加载后table不是100%宽度

**Comment by asd8510678** [comment]
全局覆盖样式就可以解决
.table-panel {
    width: 100%;
  }

table{
    width: 100% !important;
    table-layout: auto;
  }

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
