### ISSUE TITLE
【需求】选择器Select控件希望添加默认选中某选项的api或通过Option能动态控制选项选中

### ISSUE THREAD

**Issue by zhyjNaruto** [iview/iview#1790]
如题，希望Select下拉框组件，能有默认选中某选项的api，或者可以通过Option的props添加selected属性，用来控制选项的选中

**Comment by zhyjNaruto** [comment]
好像是自己使用的方式不对，关闭....请无视

**Comment by xifengxx** [comment]
我也遇到这个问题，添加selected属性不起作用

**Comment by DayThink** [comment]
`            <FormItem>
                <Select v-model="query_form.current_plan" placeholder='预案' @on-change="plan_info_by_plan_name" ref="ref_sel_plan" clearable filterable style="width: 120px">
                    <template v-for = "item in query_form.plan_list">
                        <Option v-if = "item.status === 1" :value="item.value" selected>{{item.label}} <Icon size="20" type="md-checkmark" style="color: red; margin-left: 5px" /></Option>
                        <Option v-else :value="item.value" >{{item.label}}</Option>
                    </template>
                </Select>
            </FormItem>`
selected默认选中咋不起作用呢？
