### ISSUE TITLE
Tabs组件发现BUG

### ISSUE THREAD

**Issue by yumengyuan0825** [iview/iview#1791]
版本 v2.2.0  
1. Tabs v-model 数据双向绑定无效
2. on-click 事件无效？ 

很奇怪，为什么会出现此类低级BUG，是我使用不当吗？ 贴上源码
组件使用：

     <Tabs @on-click="handleTabClick">
                <TabPane label="全部" name="name1">
                    <keep-alive>
                        <stock-vehicle-all v-if="tab === 'ALL'"></stock-vehicle-all>
                    </keep-alive>
                </TabPane>
                <TabPane label="待售车辆" name="name2">
                    <keep-alive>
                        <stock-vehicle-for-sale v-if="tab === 'SALE'"></stock-vehicle-for-sale>
                    </keep-alive>
                </TabPane>
                <TabPane label="待审核车辆" name="name3">
                    <keep-alive>
                        <stock-vehicle-check v-if="tab === 'CHECK'"></stock-vehicle-check>
                    </keep-alive>
                </TabPane>
     </Tabs>

事件：

    methods: {
            ...mapMutations('stock', ['changeState']),

            handleTabClick(name) {
                this.changeState({
                    tab: name
                });
            }

        }

另外使用数据双向绑定v-model完全失效

**Comment by zhdwwf** [comment]
建议贴上在线代码，同样使用的2.2.0，Tabs未发现问题

**Comment by EryouHao** [comment]
数据双向绑定时，直接 tabs中不使用`value`而是直接`v-model="current"`就可以了,current指data中定义的变量
