### ISSUE TITLE
模态框中的下拉框选择器出现位置错位

### ISSUE THREAD

**Issue by kengqiangxia** [iview/iview#1792]
![image](https://user-images.githubusercontent.com/10960290/30041858-e4f33a2a-921f-11e7-8ec3-409fc251bafe.png)

iview 2.0.0 在Modal中使用Select，第一次点击会出现如图错位，第二次之后正常。

检查发现是fixed布局计算left和top两次不同，下图第一个是错位，第二个是正常显示在模态框的下拉框下面。

![image](https://user-images.githubusercontent.com/10960290/30041921-57884b7a-9220-11e7-883d-b9d0baec718f.png)

您好，请问是否是bug？还是在使用时需要CSS设置？

**Comment by ChaoshengZhang** [comment]
:transfer='true'

**Comment by kengqiangxia** [comment]
![image](https://user-images.githubusercontent.com/10960290/30044114-ffc7b1ec-922d-11e7-8bdd-46324f9a7d71.png)
@ChaoshengZhang 您好，感谢您的回答，在Select 上添加了，依然错位？

**Comment by ChaoshengZhang** [comment]
:transfer="true"   冒号

**Comment by kengqiangxia** [comment]
@ChaoshengZhang 代码中加了冒号的，element里不显示

**Comment by ChaoshengZhang** [comment]
那只有看代码了~你好好看看

**Comment by xusenlin** [comment]
我也遇到你的这种情况，不知道解决了没有
