### ISSUE TITLE
看官网的响应式布局不太行啊，是排版的问题还是框架的问题？

### ISSUE THREAD

**Issue by l619534951** [iview/iview#1794]
最近在学vue，然后在选一款响应式的基于vue的 UI框架，但是目前发现比较好的框架是element和ant，但是ant是react的，通过ant官网找到了iView，但是发现iView的官方的响应式布局很乱啊，手机上面根本没法看，所以想问一下，这个是框架的问题还是官网排版的问题。

**Comment by zhdwwf** [comment]
![image](https://user-images.githubusercontent.com/564279/30045281-dbbdd1fc-9235-11e7-8302-c52d93a9475c.png)
iview不支持移动端的
