### ISSUE TITLE
Switch组件在Poptip中切换会使Poptip消失

### ISSUE THREAD

**Issue by ab690257072** [iview/iview#1796]
在Poptip组件中，使用Switch组件，当Switch组件中设置了文字如“是/否”，当点击文字时，Poptip会随之关闭

**Comment by wenzhucjy** [comment]
render: (h, { row }) => {
            return h(
              "Poptip",
              {
                props: {
                  confirm: true,
                  title: "你确定要吗?",
                  transfer: true
                },
                on: {
                  "on-ok": () => {
                    
                  }
                }
              },
              [
                h("i-switch", {
                  props: {
                    type: "primary",
                    value: row.activeState === 1
                  },
                  on: {
                    "on-change": value => {
                      this.changeActiceState(row.id, value ? 1 : 0);
                    }
                  }
                })
              ]
            );
          }
=====
render 函数，触发 switch开关，会使Poptip消失
