### ISSUE TITLE
tabs里面嵌套Date-picker问题

### ISSUE THREAD

**Issue by huanglong6828** [iview/iview#180]
### iView 版本号
0.9.13

### 操作系统/浏览器 版本号
macOS/Chrome 55

### Vue 版本号
1.0.28

### 复现步骤
  tabs里面嵌套Date-picker  无法出现日期选择 tabs里面嵌套的自己写的组件 Date-picker日期选择定位会出错

**Comment by huanglong6828** [comment]
![image](https://cloud.githubusercontent.com/assets/19216952/21795140/0cfd2c24-d73b-11e6-81c1-1b42b14c8fe0.png)

**Comment by icarusion** [comment]
给出能复现问题的在线示例，便于调试

**Comment by fengxueye** [comment]
**change**  .pop-select-dropdown { position: fixed }  **To**   .pop-select-dropdown{ position: absolute !important; }，
