### ISSUE TITLE
Tabs: removal of the tab and its content must be with in one tick?

### ISSUE THREAD

**Issue by EternCoder** [iview/iview#1800]
**iView version**

2.0.0-rc.10

**OS / Electron**

window 7/  electron: ^1.3.1

**Vue version**

"2.2.6"

**codepen link**

https://codepen.io/faithgg/pen/PKgNBV

**procedure to repeat this** 

click the close tag (x)

**problem description**

I am working to develop a desktop editor using Electron and Vue and iView. And I am using Tabs component to hold the edit area, if the area is not saved and the user wants to close the tab, it's common to show a dialog for user to chose whether to save the area or not before closing. But the tab is closed before (or as long as, I am not sure) the dialog, and the content of the tab is still there. 

**what do I expect ?**

It seems to me that iView does not support this kind of operation.

**Comment by icarusion** [comment]
Please update iView to the latest version first.
`Tabs` use event `on-tab-remove` to trigger close, but it just emit an event. More detail can view [https://www.iviewui.com/components/tabs-en#Closable](https://www.iviewui.com/components/tabs-en#Closable)

**Comment by icarusion** [comment]
I think you can use `this.$Modal.confirm`, and close `Tab` when user click OK.

**Comment by EternCoder** [comment]
@icarusion Sorry to bother, but as far as I can tell, each tab consists of two parts, the label and the content, and iview will delete the label no matter what in the next update if the user click the (X) tag, users do not have control over the label part.
check this codepen: https://codepen.io/faithgg/pen/vJMbNJ
In the above example, the event handler of "on-tab-remove" did nothing, but the label is deleted anyway.
It should be up to the user to decide when to delete the label and the content all together.
I hope this is not dumb question.

**Comment by icarusion** [comment]
Ok, I see what you mean, Currently, using the native feature with Tabs, it does close Tabs directly. Maybe we will optimize it or add `before-close` event.

Now, you can use `Render Function` of `Tabs` to add a close button, so you can control it.

**Comment by icarusion** [comment]
[https://www.iviewui.com/components/tabs-en#Custom tab](https://www.iviewui.com/components/tabs-en#Custom tab)

**Comment by EternCoder** [comment]
Thanks a lot!
By the way, iview really helped me a lot!
Again, really grateful for you work!

**Comment by JohnXi029** [comment]
Thanks a lot!
