### ISSUE TITLE
2.3.0 版本 select 渲染问题

### ISSUE THREAD

**Issue by hnjzczf** [iview/iview#1804]
多个select 使用时，延时加载数据（实际为ajax），会出现选项不显示问题（实际选择是对的），2.2.0版本没有此问题
样例代码如下：
[test.txt](https://github.com/iview/iview/files/1280534/test.txt)

**Comment by icarusion** [comment]
v-for 用数组。

**Comment by max-boy** [comment]
@icarusion ， 我也遇到同样的问题，v-for用数组也不行

**Comment by icarusion** [comment]
Provide online code.

**Comment by hnjzczf** [comment]
换成数组一样有问题啊
[test.txt](https://github.com/iview/iview/files/1283473/test.txt)

**Comment by hnjzczf** [comment]
换成数组一样有问题啊
[test.txt](https://github.com/iview/iview/files/1283473/test.txt)

**Comment by aamis520** [comment]
`<Modal
	        v-model="addTitleModal"
	        width="900"
	        title="添加表格表头"
	        @on-ok="setTable"
	        @on-cancel="cancelTable">
	        
	        <Row>
	        	<Col span="12" offset="1">
	        		
			        <div style="padding: 20px 0;">
			        	<Row>
		        			<Col span="8" style="text-align: right;">
		        				请选择流程：
		        			</Col>
		        			<Col span="15" offset="1">
		        				 <Select v-model="showonmodal.flowid" style="width:200px" @on-change="changetableflowid(showonmodal.flowid)">
							        <Option v-for="item in flowList" :value="item.flowid" :key="item.flowid">{{item.name}}</Option>
							    </Select>
		        			</Col>
		        		</Row>
		        		<div style="width: 100%;height: 20px;"></div>
		        		<Row>
		        			<Col span="8" style="text-align: right;">
		        				请选择节点：
		        			</Col>
		        			<Col span="15" offset="1">
		        				 <Select v-model="showonmodal.nodeid" style="width:200px" @on-change="changetablenodeid(showonmodal.nodeid)">
							        <Option v-for="item in nodeList" :value="item.nodeid" :key="item.nodeid">{{item.nodeid}}</Option>
							    </Select>
		        			</Col>
		        		</Row>
			        </div>
			        
	        		<div style="padding-bottom: 20px;">
	        			<Transfer
				        	style="max-width: 100%;margin: 0 auto;"
					        :data="resourceData"
					        :titles = "resourceName"
					        :target-keys="resourceKeys"
					        :render-format="titleRender"
					        @on-change="titleChange">
				        </Transfer>
	        		</div>
	        		
	        		<div>
	        			<Button type="primary" @click="addcountcolunm">新增统计列</Button>
	        		</div>
			        
	        	</Col>
	        	<Col span="10" offset="1">
		        	<div  style="border: 1px dashed #ddd;padding: 5px;margin-bottom: 15px;">
		        		<p>设置按钮</p>
		        		<div>
		        			<div>
		        				<Row>
		        					<Col span="9">
		        						<Checkbox v-model="isViewBtn" style="padding-bottom: 15px;">是否有查看按钮</Checkbox>
		        					</Col>
		        					<Col span="15">
		        						<Checkbox v-model="showonmodal.viewinmodal" v-show="isViewBtn" style="padding-bottom: 15px;">是否在模态框中显示　
		        							<span v-show="!showonmodal.viewinmodal" style="font-size: 12px;color: red;">否</span>
		        							<span v-show="showonmodal.viewinmodal" style="font-size: 12px;color: red;">是</span>
		        						</Checkbox>
		        					</Col>
		        				</Row>
		        			</div>
			        		<div v-show="isViewBtn">
			        			<Row>
			        				<Col span="6" style="font-size: 14px;line-height: 30px;">
			        					选择页面
			        				</Col>
			        				<Col span="17" offset="1">
			        					<Select v-model="viewpageid" style="width:200px;margin-bottom: 15px;">
									        <Option v-for="item in tablePageList" :value="item.pageid" :key="item.pageid">{{ item.pagename }}</Option>
									    </Select>
			        				</Col>
			        			</Row>
			        		</div>
		        		</div>
		        		<div>
		        			<div>
		        				<Row>
		        					<Col span="9">
		        						<Checkbox v-model="isEditBtn" style="padding-bottom: 15px;">是否有编辑按钮</Checkbox>
		        					</Col>
		        					<Col span="15">
		        						<Checkbox v-model="showonmodal.editinmodal" v-show="isEditBtn" style="padding-bottom: 15px;">是否在模态框中显示　
		        							<span v-show="!showonmodal.editinmodal" style="font-size: 12px;color: red;">否</span>
		        							<span v-show="showonmodal.editinmodal" style="font-size: 12px;color: red;">是</span>
		        						</Checkbox>
		        					</Col>
		        				</Row>
		        			</div>
		        			<div v-show="isEditBtn">
			        			<Row>
			        				<Col span="6" style="font-size: 14px;line-height: 30px;">
			        					选择页面
			        				</Col>
			        				<Col span="17" offset="1">
			        					<Select v-model="editpageid" style="width:200px;margin-bottom: 15px;">
									        <Option v-for="item in tablePageList" :value="item.pageid" :key="item.pageid">{{ item.pagename }}</Option>
									    </Select>
			        				</Col>
			        			</Row>
			        		</div>
		        		</div>
		        	</div>	
	        		
	        		
	        		<div style="border: 1px dashed #ddd;padding: 5px;margin-bottom: 15px;">
	        			<div>
	        				<Checkbox v-model="showonmodal.isdelbtn" style="padding-bottom: 15px;">是否有删除按钮</Checkbox>
	        			</div>
	        		</div>
	        		
	        		
	        		<div style="border: 1px dashed #ddd;padding: 5px;margin-bottom: 15px;">
	        			<div>
	        				<Checkbox v-model="showonmodal.isapprovalstatus" style="padding-bottom: 15px;">是否有审批状态</Checkbox>
	        			</div>
	        		</div>
	        		
	        		<div style="border: 1px dashed #ddd;padding: 5px;margin-bottom: 15px;">
	        			<div>
	        				<Checkbox v-model="showonmodal.isonlyshowchilddata" style="padding-bottom: 15px;">是否只显示子数据</Checkbox>
	        			</div>
	        		</div>
	        		
	        		<div style="border: 1px dashed #ddd;padding: 5px;margin-bottom: 15px;">
	        			<p>设置统计列</p>
	        			
	        			
	        			
	        			<div>
	        				<Checkbox v-model="showonmodal.iscountBtn" style="padding-bottom: 15px;">是否设置统计列</Checkbox>
	        			</div>
	        			<div v-show="showonmodal.iscountBtn">
		        			<Row>
		        				<Col span="6" style="font-size: 14px;line-height: 30px;">
		        					设置统计列表头：
		        				</Col>
		        				<Col span="17" offset="1">
		        					<Input placeholder="请输入..." v-model="showonmodal.countTitle" @on-change="countTitleChange"></Input>
		        				</Col>
		        			</Row>
		        		</div>
	        			<div v-show="showonmodal.iscountBtn">
		        			<Row>
		        				<Col span="6" style="font-size: 14px;line-height: 30px;">
		        					选择主列
		        				</Col>
		        				<Col span="17" offset="1">
		        					<Select v-model="showonmodal.countColumnStart" style="width:200px;margin-bottom: 15px;">
								        <Option v-for="item in countColumnData" :value="item.key" :key="item.key">{{item.title}}</Option>
								    </Select>
		        				</Col>
		        			</Row>
		        		</div>
		        		<div v-show="showonmodal.iscountBtn">
		        			<Row>
		        				<Col span="6" style="font-size: 14px;line-height: 30px;">
		        					选择计算方式
		        				</Col>
		        				<Col span="17" offset="1">
		        					<Select v-model="showonmodal.countColumnCalculation" style="width:200px;margin-bottom: 15px;">
								        <Option v-for="item in countColumnCalculations" :value="item.value" :key="item.key"></Option>
								    </Select>
		        				</Col>
		        			</Row>
		        		</div>
		        		<div v-show="showonmodal.iscountBtn">
		        			<Row>
		        				<Col span="6" style="font-size: 14px;line-height: 30px;">
		        					选择被动列
		        				</Col>
		        				<Col span="17" offset="1">
		        					<Select v-model="showonmodal.countColumnEnd" style="width:200px;margin-bottom: 15px;">
								        <Option v-for="item in countColumnData" :value="item.key" :key="item.key">{{item.title}}</Option>
								    </Select>
		        				</Col>
		        			</Row>
		        		</div>
		        		
	        		</div>
	        		
	        		
	        		<div style="border: 1px dashed #ddd;padding: 5px;margin-bottom: 15px;">
	        			<p>过滤条件:</p>
	        			<div>
	        				<Checkbox v-model="showonmodal.isfilterBtn" style="padding-bottom: 15px;">是否设置过滤条件</Checkbox>
	        			</div>
	        			<div v-show="showonmodal.isfilterBtn">
		        			<Row>
		        				<Col span="6" style="font-size: 14px;line-height: 30px;">
		        					选择过滤条件列
		        				</Col>
		        				<Col span="17" offset="1">
		        					<Select v-model="showonmodal.filterkey" style="width:200px;margin-bottom: 15px;">
								        <Option v-for="item in countColumnData" :value="item.key" :key="item.key">{{item.title}}</Option>
								    </Select>
		        				</Col>
		        			</Row>
			        		<div>
		        				<Checkbox v-model="showonmodal.filterchoosesystemsk" style="padding-bottom: 15px;">选择过滤条件</Checkbox>
		        			</div>
			        		<div v-show="showonmodal.filterchoosesystemsk">
			        			<Row>
			        				<Col span="9" style="font-size: 14px;line-height: 30px;">
			        					选择系统关键字
			        				</Col>
			        				<Col span="14">
			        					<Select v-model="showonmodal.filtervaluebychoose" style="width:200px;margin-bottom: 15px;">
									        <Option v-for="item in systemsks" :value="item.key" :key="item.key">{{item.value}}</Option>
									    </Select>
			        				</Col>
			        			</Row>
			        		</div>
			        		<div v-show="!showonmodal.filterchoosesystemsk">
			        			<Row>
			        				<Col span="9" style="font-size: 14px;line-height: 30px;">
			        					输入过滤条件的值
			        				</Col>
			        				<Col span="14">
			        					<Input placeholder="请输入..." v-model="showonmodal.filtervaluebyfill" @on-change="countTitleChange"></Input>
			        				</Col>
			        			</Row>
			        		</div>
			        	</div>	
        			</div>
        			
	        		
	        		<div>
	        			<div>
	        				<Checkbox v-model="showonmodal.isshowflowdata" style="padding-bottom: 15px;">是否显示流程数据</Checkbox>
	        			</div>
        			</div>
	        	</Col>
	        </Row>
	    </Modal>`

数据都是ajax 请求回来的。。。
类似这种复杂的结构 ，下拉框就会出现选择的数据是对的，但是显示的是空白或者为其他下拉框的值
