### ISSUE TITLE
Select组件不能动态更新数据

### ISSUE THREAD

**Issue by inobelieve** [iview/iview#1805]
<template>
  <div>
    <Button @click="switchFuc">label+1</Button>
    <Select v-model="model1" style="width:200px">
      <Option v-for="item in cityList" :value="item.value" :key="item.value" :label="item.label"></Option>
    </Select>
  </div>
</template>
<script>
  export default {
    data () {
      return {
        cityList: [
          {
            value: 'beijing',
            label: '北京市'
          },
          {
            value: 'shanghai',
            label: '上海市'
          },
          {
            value: 'shenzhen',
            label: '深圳市'
          },
          {
            value: 'hangzhou',
            label: '杭州市'
          },
          {
            value: 'nanjing',
            label: '南京市'
          },
          {
            value: 'chongqing',
            label: '重庆市'
          }
        ],
        model1: ''
      }
    },
    methods: {
      switchFuc: function () {
        for (let i in this.cityList) {
          this.cityList[i].label += 1
        }
      }
    }
  }
</script>
// 点击lable+1按钮之后下拉菜单能够更新，但是重新选择的映射label仍旧为原值，

**Comment by Nancyzou** [comment]
我也遇到同样问题，请问怎么解决
