### ISSUE TITLE
table 组件 的【csv】下载问题

### ISSUE THREAD

**Issue by NickBang** [iview/iview#1806]
data中默认插入的数据是可以下载的。凡是经过render处理过得数据。下载csv之后表格为空，API中说明的columns 和 data 也没有较详尽的例子。所以不太明白这里该如何使用。有劳了

**Comment by icarusion** [comment]
查看导出自定义数据的示例

**Comment by NickBang** [comment]
您好，导出自定义数据的示例 只是控制需要下载的行列过滤器。
![qut o 5 0 intnv0jl nlx](https://user-images.githubusercontent.com/20419087/30207280-8d7fa9b4-94c1-11e7-8d3a-8a9af4335266.png)
Data是一个多维数组，所以并不能填写key。而且我的每一列都需要render处理加工，下载的csv便不包含。

**Comment by David-Tsui** [comment]
@NickBang 請問此issue有解了嗎?
最近也剛好遇到，exportCsv方法中的data都是原始資料不管有沒有設original: false都會是原始data，
網頁上導出csv範例也未用到render處理資料，此issue實在關得倉促。

**Comment by David-Tsui** [comment]
@NickBang 
請問此問題有解嗎，我覺得只要export中的data有辦法取得表格上顯示的數據就能解決，但目前API似乎未支援。

**Comment by zhangjv** [comment]
今天也查到了这个问题，去看了下源码处理导出数据的部分：https://github.com/iview/iview/blob/2.0/src/utils/csv.js

显然没有处理render的情况，目前的解决办法应该是在传给exportCsv的时候特殊处理一遍列，或者参照iview代码自己实现导出方法。

**Comment by David-Tsui** [comment]
@zhangjv 恩恩，後來我也是暫時這麼做

**Comment by yidag** [comment]
貌似和 render 没有关系，要 data(自定义导出的行数据) 里有值，下载的csv里就有值

**Comment by ghrace** [comment]
@zhangjv 有示例吗

**Comment by NickBang** [comment]
看大家都有这样的问题。我说一下我之前解决的方法吧。比较笨，就是对请求回来的data遍历判断（实现自己的逻辑就可以），tableData拿到的初始值就是自定义的。下载的时候就没什么问题了。

**Comment by woaihuoying** [comment]
@zhangjv 我想知道是怎么做特殊处理呢，“传给exportCsv的时候特殊处理columns和data”，望解答

**Comment by chenmengying1996** [comment]
> @zhangjv 恩恩，後來我也是暫時這麼做

请问您是怎么解决这个问题的呀
