### ISSUE TITLE
 [Bug Report]多个Select组件，在页面首次渲染时，只有第一个可以正常选择

### ISSUE THREAD

**Issue by zhyjNaruto** [iview/iview#1807]
该bug为2.3.0引入的问题，回退到2.2.0后不再复现。
代码结构大致如下（具体数据值可自行填充）：
![image](https://user-images.githubusercontent.com/12232035/30106655-c334dcee-932e-11e7-8147-48910d3012be.png)
`<Row type="flex" align="middle">
                <Col span="4"><span>{{currentPageTypeText}}读权限：</span></Col>
                <Col span="14">
                    <Select :key="'read-select'" v-model="currentModal.pageReadAuthorityId" placeholder="请选择页面读权限" clearable>
                        <Option v-for="permission in currentModal.permissionList" :value="permission.authorityId" :key="'read'+ permission.authorityId">{{ permission.name + ' (' + permission.description + ')' }}</Option>
                    </Select>
                </Col>
            </Row>
            <br>
            <Row type="flex" align="middle">
                <Col span="4"><span>{{currentPageTypeText}}写权限：</span></Col>
                <Col span="14">
                    <Select :key="'write-select'" v-model="currentModal.pageWriteAuthorityId" placeholder="请选择页面写权限" clearable>
                        <Option v-for="permission in currentModal.permissionList" :value="permission.authorityId" :key="'write' + permission.authorityId">{{ permission.name + ' (' + permission.description + ')' }}</Option>
                    </Select>
                </Col>
            </Row>`
![image](https://user-images.githubusercontent.com/12232035/30106700-d7d87b10-932e-11e7-9f59-ff87b6d876c6.png)
如图，在2.3.0版本，页面初始化时只有第一个Select会选中，而第二个Select标签无论怎么操作都无法选中（如果此时利用webpack-server热更新，修改某个dom后，恢复正常）。但回退到2.2.0版本未出现该问题。

**Comment by zhyjNaruto** [comment]
起初怀疑是key的问题，特地将两个Select里的Option起了独立的key名，但是似乎还是无效，看了下更新日志有一条是关于Select控件的性能优化，怀疑是否与该更新有关

**Comment by SergioCrisostomo** [comment]
@zhyjNaruto could you set up this codepen please? 

https://codepen.io/sergiocrisostomo/pen/ayrZvy

**Comment by max-boy** [comment]
我在页面同时渲染同样的select组件时，只有第一个可以选择。

**Comment by icarusion** [comment]
Provide online code.

**Comment by max-boy** [comment]
```
<Form-item label="用户1" prop="designer_id">
    <Select v-model="form.designer_id">
	<Option v-for="item in users" :value="parseInt(item.id)" :key="item.id">
	    {{ item.name }}
	</Option>
    </Select>
</Form-item>
<Form-item label="用户2" prop="maker_id">
    <Select v-model="form.maker_id">
	<Option v-for="item in users" :value="parseInt(item.id)" :key="item.id">
	    {{ item.name }}
	</Option>
    </Select>
</Form-item>
```
users是一个数组ajax获取的：数据格式如下：
```
[{"id":1,"name":"a1"},{"id":2,"name":"a2"}]
```
导致的结果就是第一个可以选中，第二个选择了也显示空白
但是我把iview的版本降到2.2以后，就正常了，谢了。

**Comment by icarusion** [comment]
https://codepen.io/sergiocrisostomo/pen/ayrZvy
到这里在线复现问题，我本地都是ok 的

**Comment by max-boy** [comment]
@icarusion 
在线地址如下：
https://codepen.io/max-boy/pen/YxbjrJ

**Comment by icarusion** [comment]
Hi，@SergioCrisostomo 
When write data asynchronously, it does trigger this problem, the second Select can not display the 
selected value.
I'm trying to find out what's wrong with it ：）

```vue
<template>
    <div>
        <Select v-model="model10" multiple style="width:260px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
        <Select v-model="model11" multiple style="width:260px">
            <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
        </Select>
    </div>
</template>
<script>
    export default {
        data () {
            return {
                cityList: [],
                model10: [],
                model11: []
            }
        },
        mounted () {
            setTimeout(() => {
                this.cityList = [
                    {
                        value: 'beijing',
                        label: '北京市'
                    },
                    {
                        value: 'shanghai',
                        label: '上海市'
                    },
                    {
                        value: 'shenzhen',
                        label: '深圳市'
                    },
                    {
                        value: 'hangzhou',
                        label: '杭州市'
                    },
                    {
                        value: 'nanjing',
                        label: '南京市'
                    },
                    {
                        value: 'chongqing',
                        label: '重庆市'
                    }
                ];
            }, 1000);
        }
    }
</script>
```

**Comment by SergioCrisostomo** [comment]
@max-boy thank you for taking this up and for the example.

@icarusion I'm happy to fix this. Good we have example so we can add tests for this. Today and tomorrow I will be at [Nordic.js](http://nordicjs.com/) conference. But after that I will send in the fix for this.

**Comment by icarusion** [comment]
https://github.com/iview/iview/blob/1f41c9ca2c45a13747b5fa8201c4e4481f409a36/src/components/select/utils.js#L12

**Comment by icarusion** [comment]
@SergioCrisostomo thanks !

**Comment by zhyjNaruto** [comment]
@icarusion 多谢帮忙复现该问题
@max-boy 感谢帮忙提供示例
@SergioCrisostomo sorry for seeing your msg late. Fortunately,max-boy put the example and  trigger this problem.

**Comment by icarusion** [comment]
#1828
