### ISSUE TITLE
日期表单如果动态赋值，那么无法做表单验证，提交时报错

### ISSUE THREAD

**Issue by luyin0311** [iview/iview#1808]
<template>
    <Form ref="formValidate" :model="formValidate" :rules="ruleValidate" :label-width="80">
        <FormItem label="姓名" prop="name">
            <Input v-model="formValidate.name" placeholder="请输入姓名"></Input>
        </FormItem>
        <FormItem label="选择日期">
            <Row>
                <Col span="11">
                    <FormItem prop="date">
                        <DatePicker type="date" placeholder="选择日期" v-model="formValidate.date" @on-change='changeDate'></DatePicker>
                    </FormItem>
                </Col>
            </Row>
        </FormItem>
        <FormItem>
            <Button type="primary" @click="handleSubmit('formValidate')">提交</Button>
            <Button type="ghost" @click="handleReset('formValidate')" style="margin-left: 8px">重置</Button>
        </FormItem>
    </Form>
</template>
<script>
    export default {
        created () {
            this.formValidate.date='2017-09-22';
        },
        data () {
            return {
                formValidate: {
                    name: '',
                    date: ''
                },
                ruleValidate: {
                    name: [
                        { required: true, message: '姓名不能为空', trigger: 'blur' }
                    ],
                    date: [
                        { required: true, type: 'date', message: '请选择日期', trigger: 'change' }
                    ],
                }
            }
        },
        methods: {
            handleSubmit (name) {
                this.$refs[name].validate((valid) => {
                    if (valid) {
                        this.$Message.success('提交成功!');
                    } else {
                        this.$Message.error('表单验证失败!');
                    }
                })
            },
            handleReset (name) {
                this.$refs[name].resetFields();
            },
            changeDate(date) {
                console.log(date,typeof(date));
            }
        }
        
    }
</script>

**Comment by luyin0311** [comment]
vue.esm.js?71e4:479 [Vue warn]: Error in event handler for "click": "TypeError: value.getTime is not a function"

**Comment by OXOYO** [comment]
需要初始化值的话，new Date 下，转成日期类型。
