### ISSUE TITLE
Datepicker (First day of week)

### ISSUE THREAD

**Issue by dspangenberg** [iview/iview#1809]
Hi,

in Germany and some other countries, a week starts on Monday instead of Sunday. Have you planned some further options?

**Comment by benjycui** [comment]
> in Germany and some other countries, a week starts on Monday instead of Sunday.

It is part of l10n @icarusion

In [antd](https://ant.design):

```jsx
import { DatePicker } from 'antd';
import moment from 'moment';
moment.locale('zh-cn');

// Weeks start on Monday
ReactDOM.render(<DatePicker value={moment()} />, mountNode);
```

```jsx
import { DatePicker } from 'antd';
import moment from 'moment';
moment.locale('en');

// Weeks start on Sunday
ReactDOM.render(<DatePicker value={moment()}  />, mountNode);
```

**Comment by icarusion** [comment]
Thanks @benjycui , but iView doesn't use moment, so it's likely to be supported in the future.

**Comment by jamiegau** [comment]
I need to display start of the week on Thursday.
How is that done?
