### ISSUE TITLE
InputNumber 添加输入属性

### ISSUE THREAD

**Issue by iminif** [iview/iview#1810]
需求：InputNumber 添加输入属性，可以过滤小数（只允许输入整数:正整数或负整数...）

**Comment by zhdwwf** [comment]
step设为1不就是只能输入整数
![image](https://user-images.githubusercontent.com/564279/30144309-027a5ac6-93bd-11e7-956e-f9132e78ba29.png)

**Comment by icarusion** [comment]
https://github.com/react-component/input-number/pull/67/files

**Comment by iminif** [comment]
如果先输入小数（比如 2.25），步长设为整数1，那么点击步进箭头时输入框会变为 3.25，还得我自己使用 parseInt 方法进行更多处理。

**Comment by zhdwwf** [comment]
@iminif  明白你意思了，之前是我理解的有误
