### ISSUE TITLE
upload 组件如何清除已上传的文件显示？

### ISSUE THREAD

**Issue by CharleySc** [iview/iview#1814]
想问一下如何用js清除我已经上传的文件集？ 
看了api有个clearFiles的方法，但是不知道如何使用，有大腿在吗？求救
<img width="568" alt="wx20170907-140339 2x" src="https://user-images.githubusercontent.com/19809888/30148300-5f24328e-93d5-11e7-9fcf-64e193d895ef.png">

**Comment by icarusion** [comment]
查询 Vue 文档 ref 用法
