### ISSUE TITLE
对比测试发现iview使用nuxt做服务端渲染时会报如下警告！页面无法正常显示。

### ISSUE THREAD

**Issue by mqhe2007** [iview/iview#1816]
> There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
*E:\web\qingjinblog\node_modules\Vue\dist\vue.runtime.esm.js
    Used by 1 module(s), i. e.
    E:\web\qingjinblog\node_modules\babel-loader\lib\index.js??ref--1!E:\web\qingjinblog\node_modules\eslint-loader\index.js!E:\web\qingjinblog\plugins\iview.js
*E:\web\qingjinblog\node_modules\vue\dist\vue.runtime.esm.js
    Used by 27 module(s), i. e.
    multi vue vue-router vue-meta vuex axios marked iview

一切都是最新版，使用方法遵循nuxt的组件引入方法，复现的话重新生成一个新nuxt项目测试即可测试，饿了么的UI框架能够正常支持的，但是饿了么的组件太少，就是想用iview。

**Comment by icarusion** [comment]
还没有在最新版的 Nuxt.js 上做过测试，之后我再看看吧

**Comment by mqhe2007** [comment]
@icarusion 响应如此迅速，赞一个！那我宁愿等你也不想用饿了。

**Comment by icarusion** [comment]
@mqhe2007 着急可以先用之前版本的 Nuxt, 都是测试过的

**Comment by mqhe2007** [comment]
@icarusion 又重新npm install 了两次又好了……不知道是什么情况，目前看起来正常了。
