### ISSUE TITLE
Table的列能否添加隐藏的属性？

### ISSUE THREAD

**Issue by 452486035** [iview/iview#1820]
我们在做Table的时候经常会点击查看详细，因此需要向详情页中传入当前行的ID，但是这个ID是不作为列展示的，需要进行隐藏。因此是否可以提供这样一个显示隐藏的属性，能够设置某列是隐藏的？？

个人感觉这个功能还是很有必要的，而且是经常用的，如果现在已有其他方式希望能够告之一下

**Comment by 452486035** [comment]
这个跟#1052的还不一样，并非直接从columns中去掉，还是需要在columns中有这一列的，只是这一列是hide的

**Comment by zhdwwf** [comment]
可以通过table column render函数实现，示例如下：
[http://output.jsbin.com/wekoyas](http://output.jsbin.com/wekoyas)

**Comment by zouhuigang** [comment]
+1 希望能直接控制显示和隐藏

**Comment by xieyucan** [comment]
+1 希望能直接控制显示和隐藏

**Comment by BruceAn1978** [comment]
up

**Comment by BruceAn1978** [comment]
同时大家支持一下这个功能：https://github.com/iview/iview/issues/4023

**Comment by zhangbuding** [comment]
> 可以通过table column render函数实现，示例如下：
> http://output.jsbin.com/wekoyas

说tm什么吊玩意

**Comment by qwasnm789** [comment]
现在解决了吗？怎么隐藏根据需求隐藏列，我想用v-if的 但是不知道怎么写
