### ISSUE TITLE
Form-item 无法单独清除 :error 错误状态

### ISSUE THREAD

**Issue by lslzl3000** [iview/iview#1822]
项目中遇到问题: https://codepen.io/anon/pen/qXzQqj
Formitem `:error` 无论传入什么值都会触发 `validateState = 'error'`，无法单独清除`validateState`：
```
    watch: {  
        error (val) {
                this.validateMessage = val;
                this.validateState = 'error';
            }
    ...
   }
```
 是否应该判断一下val的值，如果是`null, undifined, ''`等情况，把`validateState`也清空：
```
    watch: {  
        error (val) {
                this.validateMessage = val;
                this.validateState = val ? 'error' : '';
            }
    ...
   }
```

**Comment by lslzl3000** [comment]
Simple demo: [https://codepen.io/anon/pen/qXzQqj](https://codepen.io/anon/pen/qXzQqj)

**Comment by icarusion** [comment]
本来就是这么设计的。
你可以在 rule 里定义错误提示。
![image](https://user-images.githubusercontent.com/5370542/30239077-57ee8af6-9587-11e7-9fc6-5a58eebaaf8c.png)

**Comment by lslzl3000** [comment]
@icarusion 我知道这么设计的，问题是如何关闭单个item的错误显示，我不想用reset把整个form都清空，我认为清空error的话，应该把错误状态也关闭掉

**Comment by derekhsu** [comment]
@lslzl3000 發現一個隱藏的方法，沒有在文件中註明的。

```vue
<FormItem :validate-status="errors.has('email')? 'error': 'success'"></FormItem>
```

這樣就能改變`validateState`的狀態了！
