### ISSUE TITLE
Cascader级联组件，clearable属性导致iview报错

### ISSUE THREAD

**Issue by z448401921** [iview/iview#1827]
**<Cascader placeholder="请选择地址" :data="pickData" :load-data="getCityData" v-model='pickValue' trigger="click" @on-change="pickChange" change-on-select :clearable="false" filterable></Cascader>
**
您好，我在使用级联组件时遇到这问题，代码报错位置在iview.js文件。引用代码如上，效果如下图。

![1](https://user-images.githubusercontent.com/9210994/30198380-f97be1e0-949f-11e7-887f-57b813784d73.png)
![2](https://user-images.githubusercontent.com/9210994/30198384-00137ef0-94a0-11e7-8ecc-04db48115849.png)

**Comment by icarusion** [comment]
change-on-select 不能与 异步搜索混用
