### ISSUE TITLE
级联控件设置change-on-select属性，导致动态绑定的value设置无效

### ISSUE THREAD

**Issue by yajore** [iview/iview#183]
### iView 版本号
 0.9.13

### 操作系统/浏览器 版本号
WIN10/chrome55

### Vue 版本号
 1.0.26 

### 能够复现问题的在线示例
https://codepen.io/anon/pen/BpjaZp

### 复现步骤
查看事例

**Comment by LordRobert** [comment]
现在依然有这个问题。
