### ISSUE TITLE
建议：垂直侧边栏菜单增加左右折叠功能

### ISSUE THREAD

**Issue by ae86jung** [iview/iview#1831]
建议垂直菜单栏增加左右折叠。折叠效果是折叠后只剩下图标。

**Comment by EryouHao** [comment]
示例中已经有这种实现了：https://www.iviewui.com/docs/guide/layout

**Comment by EryouHao** [comment]
@ae86jung 示例中已经有这种实现了：https://www.iviewui.com/docs/guide/layout
