### ISSUE TITLE
关于iview table 组件 下载【csv】数据为空的再次提问。抱歉。

### ISSUE THREAD

**Issue by NickBang** [iview/iview#1833]
![qut o 5 0 intnv0jl nlx](https://user-images.githubusercontent.com/20419087/30207280-8d7fa9b4-94c1-11e7-8d3a-8a9af4335266.png)
Data是一个多维数组，所以并不明白该如何填写二维数组中的key。还是说table 组件的data 参数 仅支持一维数组，需要使用者把数据整理为一维数组，而并不能仅用render 处理数据之后再下载。

**Comment by NickBang** [comment]
如果是使用render 处理过的数据，这个key 并没办法填写。不填写便导致下载之后没有数据。

**Comment by icarusion** [comment]
Table 可以导出自定义数据，仔细看文档。另，提问请到 SegmentFault，GitHub 只接受 bug report 和 feature request
