### ISSUE TITLE
关于重置Page组件我还是没明白。

### ISSUE THREAD

**Issue by kiven1989** [iview/iview#1834]
业务需求是：
分页组件和表格搭配使用，现在场景是新请求了数据，此时分页器已经切换到了某一页，这时候就需要重置Page组件的显示状态，但没成功（我已经采用了双向数据绑定，将总页数：total，每页条数：page-size，当前页码：current，当重置时就将他们回复初始值 ）

**Comment by zhdwwf** [comment]
使用 current.sync绑定
