### ISSUE TITLE
Modal模态框无法垂直区中

### ISSUE THREAD

**Issue by l619534951** [iview/iview#1835]
试过下面issues这个，没有用，官网的那个也试过，没有用，都不能够垂直区中显示，请问该怎么解决呢？
#70 **modal窗口垂直居中显示**
[代码图1](https://github.com/l619534951/book-iview/blob/master/6.png)
[代码图2](https://github.com/l619534951/book-iview/blob/master/7.png)

**Comment by BiggerKai** [comment]
给Modal加个class  <Modal class="vertical-center-modal">
然后用他给的样式可以解决，记得去掉scope
.vertical-center-modal {
  .ivu-modal-wrap {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  &.ivu-modal-hidden{
      display: none;
  }
  .ivu-modal{
      top: 0;
  }
}
