### ISSUE TITLE
modal confirm instance 未支持className

### ISSUE THREAD

**Issue by lenxeon** [iview/iview#1839]
![image](https://user-images.githubusercontent.com/251825/30243173-ca068342-95d6-11e7-83e0-265eccf93149.png)

图中sg配置无效
![image](https://user-images.githubusercontent.com/251825/30243180-df1ab29e-95d6-11e7-9f80-4960459f6de7.png)

**Comment by icarusion** [comment]
`class-name` 是给 Modal 用的，不是$Modal

**Comment by EasonYou** [comment]
@icarusion 为何$Modal不可支持自定义style 类名等Modal支持的属性呢？

**Comment by threetown** [comment]
@icarusion 建议下个版本中给 `$Modal` 加上 `className` 属性呢

**Comment by scarcoco** [comment]
@icarusion 建议下个版本中给 $Modal 加上 className 属性呢

**Comment by scarcoco** [comment]
@icarusion  要不然只能修改全局的效果，建议添加一个 className 支持吧
