### ISSUE TITLE
ivu-select-selected-value 的 html 标签没有被渲染

### ISSUE THREAD

**Issue by webees** [iview/iview#1849]
版本号 2.3.2

如图，一看就懂，我是想添加样式，使选中后的样式与下拉框中的保持样式一致，但是发现不设置label会被过滤html，设置了却是……
![_20170911153946](https://user-images.githubusercontent.com/5155291/30263529-d34aba7c-9707-11e7-95de-63171ae4040e.png)

**Comment by SergioCrisostomo** [comment]
@webees please add a jsFiddle or Codepen to reproduce your problem.
