### ISSUE TITLE
在tabs标签页中，dropdown下拉菜单被遮挡

### ISSUE THREAD

**Issue by lauber00** [iview/iview#1850]
在tabs标签页中，dropdown下拉菜单被遮挡，超出tab页的部分看不到。
这个是因为tabs设置了overflow: hidden的原因。
有没有workaround呢？让dropdown下拉菜单正常显示。

**Comment by icarusion** [comment]
use `transfer`

**Comment by lauber00** [comment]
@icarusion 多谢，没注意到这个更新。
