### ISSUE TITLE
DatePicker 的 Type 无法动态改变

### ISSUE THREAD

**Issue by SHISME** [iview/iview#1851]
DatePicker 的 Type 动态修改后，前端选择器类型不会变

**Comment by SergioCrisostomo** [comment]
@SHISME please provide a jsFiddle or Codepen.

**Comment by SHISME** [comment]
Sorry i think it is my fault

**Comment by SHISME** [comment]
https://codepen.io/SHISME/pen/WZegre?editors=1111

the selected  dateType item change ,but the DatePicker type dosen't change

**Comment by SHISME** [comment]
![image](https://user-images.githubusercontent.com/17661313/30306084-df345dba-97a8-11e7-97e7-6b1e39c831dd.png)
