### ISSUE TITLE
slider是否可以增加多个标记点特性

### ISSUE THREAD

**Issue by hainuo** [iview/iview#1852]
类似下面的
![image](https://user-images.githubusercontent.com/421861/30267827-636fb882-96a9-11e7-9d6a-f476cbd1a48e.png)

在我们的实际业务中会遇到  制定多个业绩目标，  这几个业绩目标要展示在同一个进度条上 通过 在进度条上设置点来标记进度是否完成，不知道是否其他人这种开发需求，我这边感觉倒是实际生活中有很多

**Comment by icarusion** [comment]
`Slider` 无此计划，你可以考虑是否用 `Steps` 组件代替。
