### ISSUE TITLE
[Feature Request] dropdown 下拉菜单增加button group

### ISSUE THREAD

**Issue by lauber00** [iview/iview#1853]
dropdown 下拉菜单加入一个按钮，有点击事件，点击右侧箭头显示下拉菜单项。如下图：
![image](https://user-images.githubusercontent.com/18366608/30305213-3cff66ba-97a4-11e7-9723-a5ccff2dbef1.png)
![image](https://user-images.githubusercontent.com/18366608/30305248-63560396-97a4-11e7-93c8-65a1c62ee318.png)

element.io的组件下拉菜单就有这种形式。

**Comment by thearabbit** [comment]
👍

**Comment by icarusion** [comment]
事实上本来就可以用，需要一点技巧。
```vue
<Dropdown trigger="click">
    <ButtonGroup>
        <Button @click.native.stop>菜单</Button>
        <Button icon="arrow-down-b"></Button>
    </ButtonGroup>
    <DropdownMenu slot="list">
        <DropdownItem>驴打滚</DropdownItem>
        <DropdownItem>炸酱面</DropdownItem>
        <DropdownItem disabled>豆汁儿</DropdownItem>
        <DropdownItem>冰糖葫芦</DropdownItem>
        <DropdownItem divided>北京烤鸭</DropdownItem>
    </DropdownMenu>
</Dropdown>
```

**Comment by lauber00** [comment]
试了一下，确实可以，非常感谢。
不过还个有问题，我这边是用render函数渲染的dropdown，在render函数里面不知道怎么写。。。

`render: (h, params) => {
            return h('Dropdown', {
              props: {
                placement: 'bottom-start',
                trigger: 'click',
                transfer: true
              },
              on: {
                'on-click': (item) => {
                  switch (item) {
                    case 'delete':
                      this.selectedBackup = params.row
                      this.deleteConfirm(true)
                      break
                    case 'restore':
                      break
                  }
                }
              }
            }, [
              h('ButtonGroup', {
                props: {
                  size: 'small'
                }
              }, [
                h('Button', {
                  on: {
                    'click.native.stop': true
                  }
                }, this.$t('dbscale.restoreBackup')),
                h('Button', {
                  props: {
                    icon: 'arrow-down-b'
                  }
                })
              ]),
              h('Dropdown-menu', {
                slot: 'list'
              }, [
                h('Dropdown-item', {
                  props: {
                    name: 'restore'
                  }
                }, [
                  h('Icon', {
                    props: {
                      type: 'ios-cloud-download-outline'
                    },
                    style: {
                      marginRight: '8px'
                    }
                  }),
                  h('span', this.$t('dbscale.restoreBackup'))
                ]),
                h('Dropdown-item', {
                  props: {
                    name: 'delete'
                  }
                }, [
                  h('Icon', {
                    props: {
                      type: 'trash-a'
                    },
                    style: {
                      marginRight: '8px'
                    }
                  }),
                  h('span', this.$t('dbscale.deleteBackup'))
                ])
              ])
            ])`

**Comment by lauber00** [comment]
@icarusion 自己试着写出来了，不用麻烦您了，谢谢！
