### ISSUE TITLE
分页bug

### ISSUE THREAD

**Issue by needou** [iview/iview#1854]
点击分页跳转到到第二页，然后搜索从后台拿去新的数据，吧总数和页码再次传给分页主键，分页组件下面当前页面不会变，理论上会回到指定的页码

![qq 20170912112434](https://user-images.githubusercontent.com/18343113/30306824-ff16c916-97ac-11e7-82c0-2bdd6ebb3713.png)

**Comment by zhdwwf** [comment]
使用 :current.sync='' 绑定

**Comment by icarusion** [comment]
.sync

**Comment by gapsaras** [comment]
```
<Page :current.sync="currentPage" :total="keywordNum" @on-change="handlePageChange"></Page>
```
```
handlePageChange(pageNum) {
      this.currentPage = 1;
}
```

求助，按照上面的写法，Page组件的当前页还是点击哪个就变成了哪个。如何重置当前页为第一页呢？

**Comment by Suzichen** [comment]
@gapsaras 你好，请问这个问题解决了吗
