### ISSUE TITLE
select控件搜索问题

### ISSUE THREAD

**Issue by yajore** [iview/iview#186]
### iView 版本号
 0.9.13

### 操作系统/浏览器 版本号
WIN10/chrome55

### Vue 版本号
1.0.26

### 能够复现问题的在线示例
https://codepen.io/anon/pen/VPeBzo

### 复现步骤

select中搜索“上海”，该关键字在“其它城市”分组中不存在，但是“其它城市”还显示在刷选结果中

### 问题现象，以及你期望的结果是怎样的?

“其它城市”分组没有查询结果应不显示

**Comment by icarusion** [comment]
Thx.
