### ISSUE TITLE
遨游或360急速模式下assist.js报错

### ISSUE THREAD

**Issue by zoesusu** [iview/iview#1862]
![tim 20170912154923](https://user-images.githubusercontent.com/29087026/30314281-d5fb7d12-97d2-11e7-898c-7be73cbd2262.png)

![tim 20170912154914](https://user-images.githubusercontent.com/29087026/30314400-3468a898-97d3-11e7-928e-600dbb08899f.png)

如图
 iview 版本2.0.0

**Comment by SergioCrisostomo** [comment]
@zerooverture you need to use webpack to compile the code. That file uses [default function parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) and give error if compiled in old versions of Node.js or without webpack/babel transpiler.

I'm closing this. If you still have problems please post a link to the repository or check in Stackoverflow about compiling/transpiling ES6 code.
