### ISSUE TITLE
自定义主题提示主题变量文件找不到

### ISSUE THREAD

**Issue by xionggen** [iview/iview#1864]
![image](https://user-images.githubusercontent.com/16712701/30317390-92ea6768-97dc-11e7-8852-249047986491.png)
我按照官网上定制主题的第一种方式修改的主题变量来覆盖，但一直提示文件找不到，检查了路径应该没有问题，请问是什么原因？上面是配置截图

**Comment by icarusion** [comment]
可能是 less 配置的不对，参照这里的配置 https://github.com/iview/iview-project 如有问题再 reopen

**Comment by xiaoliangsu** [comment]
求问题主解决了么？我也遇到了一样的问题，想知道怎么解决的，谢谢

**Comment by Sinexs** [comment]
我已开始也是这个错误，安装了less-loader就好了
`npm install --save-dev less-loader less`
