### ISSUE TITLE
[Bug Report] Select remote bug

### ISSUE THREAD

**Issue by sishen0112** [iview/iview#1865]
选择器远程搜索Bug, 输入某个字符后选择其中一项, 再选择文本框后, **不按退格键**直接输入其他字符替换文本框文字后出现选项, 点选某一项时所显示的选项和所选择的选项不一致.

**Comment by icarusion** [comment]
Translation:
`Select`  `remote` search Bug, choose one after input a character, then select an item, do not press the backspace key, direct input other characters appear after replacing textbox text options, click on the one shown when the options do not match the selected options.

The example on the official website can be restored
