### ISSUE TITLE
有考虑过增加可编辑的表格吗

### ISSUE THREAD

**Issue by Su9Tail** [iview/iview#1866]
这两天在用render函数，发现自己对render函数的了解还是不大透彻，看过iview的实战讲座，还是一知半解。想问下有没有计划做一个可编辑的表格，即在表格内嵌套表单。

因为是询问类问题，所以没按照要求提Issue， 见谅。

**Comment by icarusion** [comment]
暂时还无此计划，可以基于 Render 自己实现。
