### ISSUE TITLE
提交表单后提示表单信息有误

### ISSUE THREAD

**Issue by asxu** [iview/iview#187]
如图(验证码只是示例)，想实现提交整个表单之后，后台响应某个数据字段有误，前端准确提示到该数据字段，烦请了解的朋友指点
![image](https://cloud.githubusercontent.com/assets/15623549/21844484/beeecea8-d829-11e6-9457-23ef4135835d.png)

新人，可能提的问题有点低级，希望大家理解

**Comment by icarusion** [comment]
[自定义验证](https://www.iviewui.com/components/form#自定义验证)

**Comment by asxu** [comment]
自定义验证都是在表单提交之前验证的吧，我想要的不是做验证，而仅仅是提示信息，，类似如下，不过没有找到示例，不知道怎么绑定

[[`地址`]](https://www.iviewui.com/components/form#FormItem_props)
> error	表单域验证错误信息, 设置该值会使表单验证状态变为error，并显示该错误信息	String	-

**Comment by icarusion** [comment]
仔细看年龄验证的逻辑
