### ISSUE TITLE
【bug】Modal instance

### ISSUE THREAD

**Issue by webees** [iview/iview#1871]
vue版本：2.4.2
iview版本：2.3.2
Browser：electron 1.7.6

使用方式：
```
                this.$Modal.confirm({
                    title: '确认对话框标题',
                    content: '<p>一些对话框内容</p><p>一些对话框内容</p>',
                    onOk: () => {
                        this.$Message.info('点击了确定');
                    },
                    onCancel: () => {
                        this.$Message.info('点击了取消');
                    }
                });
```

报错如下：
`[Vue warn]: $listeners is readonly.`
`Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "width"`

**Comment by SergioCrisostomo** [comment]
@webees can you provide a example in jsFiddle or codepen when this behaviour happens?

使用下面的在线链接可以快速创建示例
https://codepen.io/anon/pen/KvJJdw

**Comment by marxy** [comment]
you can fix this problem by upgrade to vue2.4.4.

**Comment by webees** [comment]
@SergioCrisostomo Sorry, I can't repeat it. But my specific code is as follows:
![_20170917221213](https://user-images.githubusercontent.com/5155291/30521651-99458a80-9bf5-11e7-8083-226fb0e2c79b.png)
![_20170917221243](https://user-images.githubusercontent.com/5155291/30521652-99601882-9bf5-11e7-8c59-355878d90a33.png)
![_20170917221323](https://user-images.githubusercontent.com/5155291/30521653-99af1a04-9bf5-11e7-8345-acc300ebaa6c.png)

**Comment by webees** [comment]
@marxy Thank you very much for your reply. I have been upgraded to 2.4.4. But problems remain.

**Comment by SergioCrisostomo** [comment]
@alex374 can you provide a jsFiddle or codepen reproducing the problem?

**Comment by alex374** [comment]
@SergioCrisostomo , I fix this after re-compiled my project. Sorry about the wrong comment.
