### ISSUE TITLE
[Bug Report] DatePicker手动输入问题

### ISSUE THREAD

**Issue by Sasha-XS** [iview/iview#1872]
手动输入删除或者输入的数据不符合规则时，失焦后控件的现实值直接变回上一次选择的日期，然后hover的时候日期控件的输入框显示的是新输入的内容，导致取到的实际值与显示的值不相符，是否可以多提供一个手动输入后的回调

**Comment by SergioCrisostomo** [comment]
@Sasha-XS can you please add a code example so we can see the problem live?

使用下面的在线链接可以快速创建示例
https://codepen.io/sergiocrisostomo/pen/JrjBNd

**Comment by qq986063761** [comment]
![image](https://user-images.githubusercontent.com/18366007/30473402-eede270a-9a32-11e7-8672-94bce75b57a0.png)
上图中先选择一个正确的日期，之后手动输入到只有年份（这里我格式应该yyyy-MM-dd才正确，那输入只剩年份的时候应当算输入格式有问题），当我失去焦点或者按下enter之后，数据会还原成前一次正确的格式，这本来没有问题，但是当什么也不做，然后将鼠标再次hover回到输入框内的时候，值又变回了错误值。
![image](https://user-images.githubusercontent.com/18366007/30473986-c0bd0754-9a34-11e7-9355-901f8be45933.png)
不是已经之前失去焦点之后校正过了么，为何再hover回来的时候又变回了错误值呢。。。。可能需要微调一下；
