### ISSUE TITLE
Modal垂直居中失效

### ISSUE THREAD

**Issue by abielzhang** [iview/iview#1874]
按照官网的demo写的 不能垂直居中
https://codepen.io/abielzhang/pen/VMwVpj
![image](https://user-images.githubusercontent.com/21165482/30369164-15e24d1a-98a6-11e7-8c09-46e22a30833b.png)

**Comment by icarusion** [comment]
没写 css

**Comment by VYuLinLin** [comment]
我也遇到这个问题，把scoped去掉，官网css改为下面这样就可以了：
<style lang="less">
    .vertical-center-modal{
        display: flex;
        align-items: center;
        justify-content: center;
        .modal{
            top: 0;
        }
    }
</style>
