### ISSUE TITLE
升级后几个优化建议

### ISSUE THREAD

**Issue by alvinjstu** [iview/iview#1875]
1、Autocompelete 控件，下拉数据比较多情况下，选择就会出现问题，通常选不上
2、upload 控件在上传后显示list   .ivu-upload-list这个项最好加个 postion:absolute
3、molda在升级后，里面的样式已经不太好控制，这样的情况，在badge等控件中好像也出现了

**Comment by icarusion** [comment]
建议单独拆分来提交 issue https://www.iviewui.com/new-issue
