### ISSUE TITLE
table中render使用Dropdown显示问题

### ISSUE THREAD

**Issue by kilng** [iview/iview#188]
iView 版本号

0.9.13

操作系统/浏览器 版本号

WIN10/Chrome 55

Vue 版本号

1.0.26

能够复现问题的在线示例

https://codepen.io/bruto/pen/bgpewp

复现步骤

dropdown控件显示不正常，被下一行覆盖。

问题现象，以及你期望的结果是怎样的?

达到正常效果

你估计可能的原因是什么（选填）？

**Comment by icarusion** [comment]
Thx.

**Comment by GITleonine1989** [comment]
额，我也遇到这个问题，但是我更新到0.9.15， 问题貌似还在

**Comment by icarusion** [comment]
@GITleonine1989 提供一下在线代码

**Comment by icarusion** [comment]
@GITleonine1989 https://codepen.io/Aresn/pen/xgEWPP

**Comment by GITleonine1989** [comment]
@icarusion 我的情况有点特殊，字段比较多，出现横向滚动的时候，下拉选项的的定位就出现了问题，在线示例：http://jsbin.com/bireguwinu/6/edit?html,css,js

**Comment by icarusion** [comment]
已经解决，但要在0.9.16版本。

**Comment by GITleonine1989** [comment]
@icarusion thx
