### ISSUE TITLE
Tree组件在初次渲染时，组件渲染有错位

### ISSUE THREAD

**Issue by Gscdae** [iview/iview#1880]
https://codepen.io/anon/pen/xXbpPq

Tree组件在页面初次渲染时，会加载  collapse-transition 的动画组件，影响了TREE组件本身的渲染，
具体表现是   每个节点的行高（或是padding）会先变大，再恢复原有的样子

初次渲染，若父节点没有children时，点击选择框，也会有 该现象

**Comment by hjpyh-ybxrz** [comment]
那有没有解决方案呢

**Comment by zazaluMonster** [comment]
我也有遇到这个问题，不知道是不是自己写的时候出问题。

**Comment by HejinYo** [comment]
我也遇到这个问题了，话说iview的tree组件功能也太少了，用的人不多么？

**Comment by SergioCrisostomo** [comment]
@Gscdae, @hckhanh, @zazaluMonster , @hjpyh-ybxrz 

can some of you explain in english so I can help fix this? I can see the Codepen but not sure what I should be looking for. What browser did you test?

**Comment by icarusion** [comment]
thanks @SergioCrisostomo , i tested and it seems to be a problem. It will shake when initializing, you can refresh page multiple times.
After you re-write Tree component, I can also continue to improve it. : )

**Comment by BruceLpc** [comment]
我也遇到这个问题，然后在data数据中加了selected:false就好了， 但如果修改data数据 比如新增 或者删除一个节点就又出现这个问题，看源码好像updateData 方法会造成所有树重新渲染，可以优化下吗？

**Comment by SergioCrisostomo** [comment]
@BruceLpc did you test version `2.6.0` and problem is still there?

**Comment by BruceLpc** [comment]
thanks @SergioCrisostomo 更新最新版，问题解决了!~!
