### ISSUE TITLE
建议Message组件的提示框采用瀑布队列模式而非覆盖模式

### ISSUE THREAD

**Issue by ricosmall** [iview/iview#1881]
需求：Message提示框采用瀑布队列模式。

![image](https://user-images.githubusercontent.com/18362949/30418781-b8a8e868-9966-11e7-925f-08faaf53c4fe.png)

[在线示例](https://codepen.io/ricosmall/pen/eGmVpW)

当前的Message提示框采用的是覆盖式，如下图：

![image](https://user-images.githubusercontent.com/18362949/30418842-eb2701c6-9966-11e7-9aea-554a18036182.png)

问题：不方便查看连续产生的堆栈错误。

**Comment by icarusion** [comment]
@ricosmall You can replace it with Notice. The Message is not designed for this purpose.

**Comment by icarusion** [comment]
@SergioCrisostomo AntDesign update it's Message design:
https://ant.design/components/message

Maybe we can optimize it as a new feature in 2.4.0.

**Comment by icarusion** [comment]
#1789

**Comment by ricosmall** [comment]
But I think it is appropriate to add this as an optional `props`. Because the Notice is aside the screen, sometimes it is not obvious enough. When I decide to use the Message to show stack error, I have no choice.

**Comment by ricosmall** [comment]
@SergioCrisostomo @icarusion I compared the Message component of AntDesign and the same component of [AT-UI](https://at-ui.github.io/at-ui/#/zh/docs/message), I found that the animation of the latter one is more smoother than the former one, just FYI. The browser of mine is Chrome 60 on Mac.

**Comment by webees** [comment]
我想说这个所谓的优化给我带来了bug，我就需要覆盖式的比如我这有个场景，一打开一个弹窗就会有个加载message，这个时候你操作一些东西可能有其他message，而不会销毁这个加载message，这个弹窗叫做充值（需要不断轮询充值结果，所以有个一直转圈的message告诉用户正常检查充值结果，而一些操作错误也需要显示出来）。这里希望有些开关来控制是否覆盖还是只是显示一次。
