### ISSUE TITLE
Chart图表的问题

### ISSUE THREAD

**Issue by 12522611705** [iview/iview#189]
要是这个框架自带echarts图形功能就完美了。
我看这个项目也是有规划这个图形组件的，真心想知道这个什么时候可以做完。 
目前手里有一个项目想用这个框架。
有没有什么方便一点的渠道 可以让我更好的关注这个项目的进度。  比如QQ群之类的。

**Comment by icarusion** [comment]
watch，并经常关注官网的更新日志。
iview 的charts不会使用echarts，你可以自己用echarts。

**Comment by yssnet** [comment]
怎么用自己的echarts?
