### ISSUE TITLE
renderHeader无效

### ISSUE THREAD

**Issue by PerttyZhan** [iview/iview#1893]
iview版本2.32
columns: [
					{
						key: 'created_at',
						title: '上传时间'
					},
					{
						key: 'file_name',
						title: '视频名称'
					},
					{
						key: 'file_size',
						title: '视频大小'
					},
					{
						key: 'file_time',
						title: '视频时长'
					},
					{
						key: 'status',
						renderHeader (h, params) {
							return h('Tooltip', {
								content: '转码后的视频才能查看'
							}, '状态')
						}
					},
					{
						key: 'file_time',
						title: '操作',
						render (h, params) {
							return h('div', [
								h('Button', {
									props: {
                            			type: 'text',
                            			size: 'small'
                            		}
								}, '删除')
							])
						}
					}
				],

提示h is not a funciton, 难道是我用法用错了吗

**Comment by zhdwwf** [comment]
renderHeader:(h,params)=>{}
