### ISSUE TITLE
引入这个组件后，压缩报错

### ISSUE THREAD

**Issue by diguage** [iview/iview#1896]
基本环境：

- "vue": "^2.2.2",
- "iview": "^2.3.2",
- "webpack": "^2.2.1",

压缩时报错，错误日志如下：

```
ERROR in static/js/vendor.909e5eec05e8eeb9e899.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/iview/src/utils/assist.js:5,0][static/js/vendor.909e5eec05e8eeb9e899.js:69041,13]
```

**Comment by SergioCrisostomo** [comment]
@diguage this is not iview library related, its more webpack/babel config.

You can check duplicated issues for this [here (link)](https://github.com/iview/iview/search?q=UglifyJS&state=closed&type=Issues&utf8=%E2%9C%93), specially [this one](https://github.com/iview/iview/issues/1279),  or check out Stackoverflow.
