### ISSUE TITLE
get event about DatePicker 

### ISSUE THREAD

**Issue by cyzeng-Luca** [iview/iview#1898]
hi,  i have to get event object to do something in "on-open-change",but i find it return Boolean for us ,i try many way to get event object,but it didn't work.
     how can i get event object in  "on-open-change" ?

**Comment by rijn** [comment]
`on-open-change` only returns whether the picker is open. Could you specify why you need to use the event in your application?

**Comment by cyzeng-Luca** [comment]
Because i want to use "disabledDate" of DatePicker options. I find a strange phenomenon, i use two DatePicker like this
`
<DatePicker type="date" :options="optionsStart" placeholder="startTime"></DatePicker>
<DatePicker type="date" :options="optionsEnd" placeholder="startEnd"></DatePicker>
`
   and i will dynamic update " optionsStart" or "optionsEnd" for disabledDate  in "on-change" event, because i want to make startTime <= startEnd  eternally.

    but i find it's not init timely except i click something in this dropMenu like date(of course, if the dropMenu use v-if will solve this problems but it use props "display").So, i try to trigger it by myself like use jquery. I find i should trigger <em></em> click event will solve it  like $('em').onclick(),but i should have event object to confirm which is right <em>.   i use vm.$el to comfirm now,but i think it;s not good idea.
    may you have good idea for me ?

**Comment by rijn** [comment]
It seems like you're going to select a range of date, so why don't you use `type="daterange"` directly? If you check out the demo here [Date Picker](https://www.iviewui.com/components/date-picker-en#Basic Usage). I believe the right one in the basic usage demos is what you want.

**Comment by cyzeng-Luca** [comment]
twice DatePicker are  what we want,. according to our data, consumer accept it's better, so we hava to do it like not use type="daterange"

**Comment by icarusion** [comment]
3.0 will unify event management
