### ISSUE TITLE
不支持vue2?

### ISSUE THREAD

**Issue by istommao** [iview/iview#190]
![image](https://cloud.githubusercontent.com/assets/5070879/21874651/4bf514ec-d8b1-11e6-876d-8f2e59c3d5aa.png)

**Comment by evolutionjay** [comment]
官网都说了目前只支持 vue 1 但你能切换到 2.0分支。 但。。。我看了一下2.0分支，好久没更新，好失望， vue1 接口写得好混乱，根本不想用。  但作者又在vue1 上努力着。。。所以我也是看着等作者出 vue2 的版本再看吧，目前先star。 可惜 ant design 又只原生支持 react

**Comment by istommao** [comment]
@evolutionjay 哎本来还想用下的结果不资词vue2
