### ISSUE TITLE
可编辑情况下的日期输入问题

### ISSUE THREAD

**Issue by qq986063761** [iview/iview#1901]
![image](https://user-images.githubusercontent.com/18366007/30509223-99fccbdc-9add-11e7-9740-e327f6625b01.png)
上图中先选择一个正确的日期，之后手动输入到只有年份（这里我格式应该yyyy-MM-dd才正确，那输入只剩年份的时候应当算输入格式有问题），当我失去焦点或者按下enter之后，数据会还原成前一次正确的格式，这本来没有问题，但是当什么也不做，然后将鼠标再次hover回到输入框内的时候，值又变回了错误值。
![image](https://user-images.githubusercontent.com/18366007/30509220-9306f00a-9add-11e7-9c59-2e676e40beb7.png)
不是已经之前失去焦点之后校正过了么，为何再hover回来的时候又变回了错误值呢。。。。可能需要微调一下；

**Comment by icarusion** [comment]
#1872
