### ISSUE TITLE
为什么Select 的value用比较符号的时候会给替换成HTML代码？

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1902]
https://jsfiddle.net/1tu1cmjd/8/

有没有办法显示 ><

**Comment by dean5277** [comment]
如果是做了过滤，那么&gt;这些应该转换回来才对吧

**Comment by rijn** [comment]
`<i-option value=">" label=">"></i-option>`

**Comment by icarusion** [comment]
#1690
