### ISSUE TITLE
请问在单击表格行时on-row-click, 怎么实现选中前面的多选复选框??

### ISSUE THREAD

**Issue by pollux2015** [iview/iview#1903]
请问在单击表格行时on-row-click, 怎么实现选中前面的多选复选框??
![image](https://user-images.githubusercontent.com/11935278/30510054-0a4633d0-9af0-11e7-8e8f-f20d01790bd0.png)

**Comment by lqdechina** [comment]
同问

**Comment by icarusion** [comment]
仔细看文档

**Comment by dreamcatcher081210** [comment]
this.$refs.selection.toggleSelect(index)
