### ISSUE TITLE
在render 模式下 JSX语法 Radio 组件  使用<Radio></Radio> 或者 <i-radio></i-radio>报错 

### ISSUE THREAD

**Issue by fengyaogit123** [iview/iview#1908]
问题:在render模式下 jsx 使用Radio 组件会报如下错误: 

Error in render function: "ReferenceError: Radio is not defined"
不使用jsx语法 h('Radio',null,'')是可以的
期望:  使用jsx语法 Radio组件的正确使用方式是什么？ 查阅相关文档  并没有说到Radio组件

**Comment by Baoyx007** [comment]
需要 import ``import { Radio } from 'iview'

**Comment by fengyaogit123** [comment]
是在table 的render模式下 ,iview是全局导入的  
原来代码
{
                    title: "选择",
                    key: "1",
                    render:(h, {row})=>{
                        return <Radio></Radio>
                    }
                },  报错
然后我发现  解析 把Radio解析成了变量而不是字符串 于是我改成这样
{
                    title: "选择",
                    key: "1",
                    render:(h, {row})=>{
                        let Radio='Radio';
                        return <Radio></Radio>
                    }
                },  就可以了

**Comment by zhouxianjun** [comment]
如下也可以： @fengyaogit123 
```jsx
import iView from 'iview';
{
    render: h => <iView.Radio></iView.Radio>
}
```

**Comment by xgqfrms** [comment]
# shit docs

https://www.iviewui.com/components/radio

https://github.com/iview/iview/tree/2.0/src/components

```vue
<template>
    <div>
      <RadioGroup v-model="postType">
          <Radio label="form">form data</Radio>
          <Radio label="json">JSON</Radio>
      </RadioGroup>
      <i-radiogroup v-model="postType">
          <i-radio label="form">form data</i-radio>
          <i-radio label="json">JSON</i-radio>
      </i-radiogroup>
    </div>
</template>
<script>
    export default {
        data () {
            return {
                buttonSize: 'large',
                postType: "form",
            }
        },
    }
</script>


```

![image](https://user-images.githubusercontent.com/7291672/56110016-80573a00-5f85-11e9-903d-d157d49f6752.png)

**Comment by coder-stan-lv** [comment]
> 

想问下如果是引入自己的自定义组件（该组件不是全局定义）该怎么写？
