### ISSUE TITLE
Select级联选择，第一次下拉选择正常，切换值后，选择显示的文本还是上一次的

### ISSUE THREAD

**Issue by tangsj** [iview/iview#1915]
第一个选择框 选择后， 会改变Select2的选项，   选择select2时  显示文本不正确。
示例：
https://codepen.io/tangsj/pen/PJPryz

**Comment by aamis520** [comment]
附加问题：有时候还会显示空白

**Comment by tangsj** [comment]
找到原因了，    options　key设置问题， 改成一个唯一的id 就好了
https://codepen.io/tangsj/pen/PJPryz
