### ISSUE TITLE
table中render使用i-select不弹出下拉框

### ISSUE THREAD

**Issue by kilng** [iview/iview#192]
iView 版本号

0.9.13

操作系统/浏览器 版本号

WIN10/Chrome 55

Vue 版本号

1.0.26

能够复现问题的在线示例

https://codepen.io/bruto/pen/bgpewp

复现步骤

table中render使用i-select不弹出下拉框

问题现象，以及你期望的结果是怎样的?

能正常弹出

你估计可能的原因是什么（选填）？

**Comment by icarusion** [comment]
Thx.
