### ISSUE TITLE
select 内容过长时，删除符号消失

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1921]
https://jsfiddle.net/1tu1cmjd/9/
之前地址没update。。。

这个应该不算BUG，算是一个该优化的需求，如果内容过长时，应该省略号代替后面内容。

**Comment by dean5277** [comment]
https://jsfiddle.net/1tu1cmjd/10/

把ivu-tag的固定高度删掉就好

**Comment by SergioCrisostomo** [comment]
@dean5277 could you add also a explanation in English so more people can read ad help with your issue?  

Thank you!

**Comment by dean5277** [comment]
@SergioCrisostomo 

if option content is too long,the select text area  can not display all and the close icon spill over the gray area.
