### ISSUE TITLE
级联选择器在trigger为hover的模式下时的Bug

### ISSUE THREAD

**Issue by lockontan** [iview/iview#1922]
![e b r ikna btspoh e3](https://user-images.githubusercontent.com/16314619/30580455-221330ec-9d4f-11e7-9f9f-4b9db811ddc9.png)
当鼠标移动到 北京 这个一级选项时，会自动选择北京这个选项，导致菜单浮动框消失。

**Comment by lockontan** [comment]
https://codepen.io/lockontan/pen/JrGmjX
@iview-bot

**Comment by BengBu-YueZhang** [comment]
= =

**Comment by BengBu-YueZhang** [comment]
@lockontan
