### ISSUE TITLE
table 中的expand 如何监听事件？ on 无效

### ISSUE THREAD

**Issue by yunfengsay** [iview/iview#1924]
![image](https://user-images.githubusercontent.com/15527378/30584186-950f57a4-9d5b-11e7-9990-a5a343776545.png)

如图
要监听 on-expand 事件 但是这些写法都不生效   
版本 "iview": "^2.1.0"； vue: 2.3.3

**Comment by wenbohan** [comment]
不能在render的组件中监听, 需要在Table中监听事件
```
<Table @on-expand="dealExpand(row, status)"></Table>
```
