### ISSUE TITLE
头像AVATAR，和菜单MENU。一起使用不能很好兼容

### ISSUE THREAD

**Issue by liweiyuVIE** [iview/iview#1926]
![qq 20170919202428](https://user-images.githubusercontent.com/20943221/30593367-e417bdd4-9d7c-11e7-9512-d8f55d22c1cf.png)

**Comment by SergioCrisostomo** [comment]
@liweiyuVIE can you create a example online with this problem? 
Please use this https://codepen.io/anon/pen/KvJJdw and change it to reproduce the problem.
