### ISSUE TITLE
2.3.2 版本中, Grid 布局的 Col 元素会自动加padding

### ISSUE THREAD

**Issue by easyfrog** [iview/iview#1927]
2.3.2 版本中, Grid 布局的 Col 元素会自动加16px 的 padding-left 和 padding-right

![qq20170919-213320](https://user-images.githubusercontent.com/10724325/30594923-3c488f6a-9d82-11e7-9a00-b425e160c2a3.png)

如果就是这么设计的话. 如何才能整体的将 padding-left padding-right都设置为0px呢?

**Comment by Wkan** [comment]
可以参考这个例子 https://codepen.io/wkan/pen/QOdyEv ，在Col中使用的Row，定义gutter并没有效果，好像是使用了上层的gutter。
