### ISSUE TITLE
table样式bug

### ISSUE THREAD

**Issue by vivinbear** [iview/iview#193]
### iView 版本号

0.9.13
### 操作系统/浏览器 版本号

Chrome 55
### Vue 版本号

1.0.26
### 能够复现问题的在线示例

https://codepen.io/anon/pen/vgGdov
### 复现步骤
当表格设置高度后,内容并没有充满时,右侧会有滚动条的位置,但是并没有滚动条
### 问题现象，以及你期望的结果是怎样的?
应该没有那块留白

**Comment by icarusion** [comment]
无法复现此问题，请确认代码示例中的iview版本号

**Comment by icarusion** [comment]
windows 10

**Comment by w874981121** [comment]
table  引入一直报错。 未找到函数和注意组件命名关键字
