### ISSUE TITLE
Datepicker should close on blur

### ISSUE THREAD

**Issue by dspangenberg** [iview/iview#1930]
After leaving a datepicker input field the datepicker should close 

![image](https://user-images.githubusercontent.com/166466/30608113-9765b70c-9d77-11e7-80e7-8826f970bcdc.png)

Or is there a workaround?

**Comment by SergioCrisostomo** [comment]
@dspangenberg check this fiddle: https://jsfiddle.net/Sergio_fiddle/a7v7pm5h/

When I focus by clicking on the input it opens the date-picker.
When I click outside the date-picker it closes.

I just noticed that tab focus opens the picker, but tab-navigate away from the input does not.
Can you specify better your actions an what is not working?

**Comment by dspangenberg** [comment]
@SergioCrisostomo It's exactly this behavior: "Tab focus opens the picker, but tab-navigate away from the input does not".

**Comment by SergioCrisostomo** [comment]
@dspangenberg ok, thanks. yeah, that's bug that needs to be fixed!
