### ISSUE TITLE
Modal加了滚动条后，select、Date、DatePick的选择框都往上偏移

### ISSUE THREAD

**Issue by mrerhuo** [iview/iview#1932]
Modal加了滚动条后，select、Date、DatePick的选择框都往上偏移
https://codepen.io/anon/pen/ZXWXOd

**Comment by icarusion** [comment]
使用 `transfer` 并且不建议做内部滚动

**Comment by mrerhuo** [comment]
@icarusion 不只是一个组件是这样，是select date datepick AutoComplete TimePicker  Cascader ColorPicker 反正modal带了滚动条，这些都滚动条下面的地方都会偏移。你喊做transfer直接要命嘛。

**Comment by AC-YoY** [comment]
我也碰到了一模一样的问题，非常头疼，加上transfer完美解决了

**Comment by mrerhuo** [comment]
@AC-YoY 怎么加？

**Comment by AC-YoY** [comment]
@mrerhuo 当作标签的属性 <select  transfer></select>

**Comment by AC-YoY** [comment]
@mrerhuo 当作标签的属性
```
<select transfer></select>
```

**Comment by mrerhuo** [comment]
@AC-YoY 谢谢
