### ISSUE TITLE
Transfer 穿梭框 搜索栏 filter-method建议增加支持异步搜索

### ISSUE THREAD

**Issue by wokill** [iview/iview#1933]
iView 版本号

2.x

操作系统/浏览器 版本号

Chrome 60

Vue 版本号

2.4

问题现象，以及你期望的结果是怎样的?

使用自定义 filter-method 方法后进项过滤搜索项，因为数据量比较大，需要动态从服务器上搜索商品，此时会报请求错误，希望增加在搜索时可以远程搜索数据；或者增加搜索框相关事件方法。

**Comment by icarusion** [comment]
暂无此计划
