### ISSUE TITLE
关于Tabs组件的默认关闭事件

### ISSUE THREAD

**Issue by Shruan** [iview/iview#1935]
<Tabs type="card" closable v-if="$store.state.topTab.length > 0" :value='$store.state.topTab.length-1' @on-tab-remove.prevent="handleTabRemove" @on-click='openTab' class="tab-style">
            <TabPane :label="item.name" v-for="item in $store.state.topTab"></TabPane>
          </Tabs>

我将tabs的closeable开启 添加上关闭标签的事件 但是关闭标签的事件为空并没有相关操作，但是操作标签上的X时却把标签关闭掉了  这个关闭要如何阻止

**Comment by icarusion** [comment]
#1800
