### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by elviskudo** [iview/iview#1936]
Hi,
This is awesome product
and i wanna start develop with this, but i found error in npm run dev

YError: Too many arguments provided. Expected max 2 but received 3.

How can i fixed?
Thanks

**Comment by SergioCrisostomo** [comment]
@elviskudo could you try upgrading webpack to 3.6.0? Looks like this is a recent bug [and that will fix it](https://github.com/webpack/webpack-dev-server/issues/983#issuecomment-329224980).

If it works good, add it to `package.json` in `devDependencies` and send a pull request. Maybe the other `webpack-` dependencies could bump up also :)

Thanks for pointing it out!

**Comment by elviskudo** [comment]
thanks, but i found another error

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8081
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1343:14)
    at listenInCluster (net.js:1391:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1500:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by SergioCrisostomo** [comment]
@elviskudo I think that is because you have 2 servers running. Try closing all consoles and start just one server. Does the error persist?

**Comment by elviskudo** [comment]
so, must be in 8080?
other server is stopped now, but error still coming
