### ISSUE TITLE
How do we add multiple inputs on a modal?

### ISSUE THREAD

**Issue by Muchwat** [iview/iview#1940]

**Comment by SergioCrisostomo** [comment]
@Muchwat nice that you are using iview! Please post support questions like these in Stackoverflow. I keep an eye there.
 
This Github repository is for bug reports.

Cheers,
Sérgio

**Comment by Muchwat** [comment]
ok

**Comment by SergioCrisostomo** [comment]
@Muchwat please use [the `iview-ui` tag](https://stackoverflow.com/questions/tagged/iview-ui). Btw check this https://jsfiddle.net/Sergio_fiddle/ckgjzrf5/, otherwise see you in Stackoverflow :)

**Comment by Muchwat** [comment]
Thank you Sergio
