### ISSUE TITLE
Anybody know how to integrate iview with nuxt?

### ISSUE THREAD

**Issue by rlam3** [iview/iview#1942]
Anybody know how to ingegrate iview with nuxt?
I'm having a difficult time getting the modules to work. Would love to see an example of configuration and tutorial. Thanks!

**Comment by sainf** [comment]
Hi.

I'm using with nuxt and it works very well.

Most of the info that you need is already where in the issue, but I'll try to resume.

`yarn add iview
`

Create a /plugins/iview.js
```
import Vue from 'vue'
import iView from 'iview'
import locale from 'iview/dist/locale/pt-PT' // Change locale, check node_modules/iview/dist/locale 

Vue.use(iView, {locale})
```

in nuxt.config.js
...
```
build: {
  vendor: [
    'iview'
  ]
}

plugins: [
  { src: '~/plugins/iview.js', ssr: true }
]
```
...

And then you need the css...
For this you have some options:

Import in your nuxt main css like (asset/css/main.css)
@import '../../node_modules/iview/dist/styles/iview.css";

Or use the less files,
check: node_modules/iview/src/style/index.less

Or even compile the less with our own template...

One tip because the size of the css I'm using the iview css in the app.html, it a lot faster to compile.

**Comment by rlam3** [comment]
@sainf Thanks. I'm having difficulty in getting this to build in bitbucket pipelines... any ideas on why I'm getting the following error?


```
ERROR in multi vue vue-router vue-meta vuex iView axis
Module not found: Error: Can't resolve 'iView' in '/opt/atlassian/pipelines/agent/build'
 @ multi vue vue-router vue-meta vuex iView axis
ERROR in ./plugins/iView.js
Module not found: Error: Can't resolve 'iView' in '/opt/atlassian/pipelines/agent/build/plugins'
 @ ./plugins/iView.js 3:0-26
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
Error: Webpack build exited with errors
    at /opt/atlassian/pipelines/agent/build/node_modules/nuxt/lib/builder/builder.js:498:27
    at emitRecords.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/opt/atlassian/pipelines/agent/build/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/opt/atlassian/pipelines/agent/build/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/opt/atlassian/pipelines/agent/build/node_modules/webpack/lib/Compiler.js:354:15)
    at /opt/atlassian/pipelines/agent/build/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/opt/atlassian/pipelines/agent/build/node_modules/async/dist/async.js:998:13)
    at /opt/atlassian/pipelines/agent/build/node_modules/async/dist/async.js:906:16
    at /opt/atlassian/pipelines/agent/build/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by sainf** [comment]
@rlam3 I'm new to bitbucket, but here's an repo that I'm using to test a bug.
bit: https://bitbucket.org/sainf/iview-nuxt
git: https://github.com/sainf/nuxt-iview-bug

**Comment by rlam3** [comment]
@sainf Thanks!

**Comment by rlam3** [comment]
Also I'd like to also know if there is a way to integrate iview-loader with nuxtjs

https://www.iviewui.com/docs/guide/iview-loader-en

@sainf Any chance you have used this too? Or have you just stuck with plugins only? Thanks!

**Comment by icarusion** [comment]
@rlam3 iview-loader work with webpack, so i think it worked, but i have no test.

**Comment by sainf** [comment]
It's easy, you answer is in https://nuxtjs.org/faq/extend-webpack. 

Here's a full nuxt.config.js with iview and iview-loader (tested)

```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'my-project',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  css: [
    'iview/dist/styles/iview.css'
  ],
  /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  build: {
    vendor: [
      'iview'
    ],
    // iview-loader
    extend (config) {
      config.module.rules.push({
        test: /\.vue$/,
        loader: 'iview-loader',
        options: {
          prefix: false
        }
      })
    }
  },
  plugins: [
    { src: '~/plugins/iview.js', ssr: true }
  ]
}
```

**Comment by rlam3** [comment]
@sainf Thanks! 
Is there a difference between eslint-loader and iview-loader and why we would pick one over the other and not have both??

**Comment by sainf** [comment]
Sorry @rlam3 but you must google more.
I think the main question is solved.

**Comment by Mudin** [comment]
@sainf Is the repo deleted? or moved?

**Comment by sainf** [comment]
It was deleted, it was only to test a bug.

But the info posted here is still valid for the nuxt 1.4.
Use: https://github.com/nuxt-community/starter-template and just add the... https://github.com/iview/iview/issues/1942#issuecomment-331660718

**Comment by Mudin** [comment]
@sainf Thanks a lot!
