### ISSUE TITLE
select中若选中的option过长出现左右滚动，option内容被截断无法正常显示

### ISSUE THREAD

**Issue by hellomrbigshot** [iview/iview#1945]
示例：
http://jsbin.com/yiqufok/edit?html,js,output
当选中超过select宽度的选项时时，下拉栏中的该选项左右滚动显示不完全。被蓝色截断。

**Comment by SergioCrisostomo** [comment]
related: https://github.com/iview/iview/issues/1921

**Comment by hellomrbigshot** [comment]
@SergioCrisostomo no, these two questions are different, the related question is the select's display, but mine is the option's. In my example, when the longer option is selected, you click the select, that longer option displays in error in the options list. Sorry my English is poor and i hope you can understand.

**Comment by SergioCrisostomo** [comment]
@hellomrbigshot ok, thanks! My mistake, sorry my chinese :)

**Comment by gefangshuai** [comment]
what?

**Comment by icarusion** [comment]
fixed
