### ISSUE TITLE
this.$Modal系列方法报错

### ISSUE THREAD

**Issue by supermanLS** [iview/iview#1949]
![image](https://user-images.githubusercontent.com/18274376/30686699-a95227aa-9eeb-11e7-995f-504ab861b860.png)
显示正常，但是render函数不能使用，样式会乱掉
![image](https://user-images.githubusercontent.com/18274376/30686748-cb4fc48e-9eeb-11e7-9b65-bdf4a4c31479.png)
![image](https://user-images.githubusercontent.com/18274376/30686761-d3f3340e-9eeb-11e7-915f-a20129572ab8.png)
如上图，input样式乱掉
日期选择器也有这个错误，但是可以正常使用，不知道为啥

**Comment by supermanLS** [comment]
@iview-bot 这是我的代码
![image](https://user-images.githubusercontent.com/18274376/30689028-5387dab6-9ef2-11e7-861d-0eb9aaa3b93a.png)
![image](https://user-images.githubusercontent.com/18274376/30689050-65f520e6-9ef2-11e7-8cc7-b9d142c5c698.png)

**Comment by supermanLS** [comment]
@iview-bot 我提交之前特意试过，老版本的iview我这段代码是没有报错的， 升级到最新的iview之后，就报错了

**Comment by SergioCrisostomo** [comment]
Hi @supermanLS. I don't think the bot will answer you because its is just a simple robot :)

It would be very useful if you can provide a jsFiddle or codepen. Please make a example online that reproduces the problem you describe.

**Comment by icarusion** [comment]
Document sample is ok, so may be your problem, please check carefully, if not yet, please provide the online sample and reopen this issue :)

**Comment by beileixinqing** [comment]
I have the exact same problem，and datepick components also have the problem.Now I‘m very anxious.
