### ISSUE TITLE
当card和tab一起使用时,内部如果有需要定位的部件,比如datepicker会有bug

### ISSUE THREAD

**Issue by vivinbear** [iview/iview#195]
### iView 版本号

0.9.13
### 操作系统/浏览器 版本号

Chrome 54
### Vue 版本号

1.0.26
### 能够复现问题的在线示例

https://codepen.io/anon/pen/OWNvXJ
### 复现步骤
不应该无法显示datepicker的日历

**Comment by icarusion** [comment]
目前的解决方案是给Tab足够的高度
