### ISSUE TITLE
Scope some styles

### ISSUE THREAD

**Issue by aleksanderd** [iview/iview#1950]
Hi!

Thank you for good work!

I using vue/iview for a browser extension and there is a widget which running over any page loaded in a browser's tab. All ok, but there is some global styles which breaks original page markup :(

For example, https://github.com/iview/iview/blob/2.0/src/styles/common/base.less

What the best way to solve this?

I planned to override iview's style by replacing base.less and including all other from iview.
I created less file with:
```
@import "~iview/src/styles/index";
```
but have an webpack error:
```
Webpack is watching the files…

Error: EACCES: permission denied, mkdir '/var/node_modules'
    at Error (native)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rext@1.0.0 watch: `cross-env NODE_ENV=development webpack --watch --config build/webpack.dev.js`
npm ERR! Exit status 1
```

Thank you!

**Comment by SergioCrisostomo** [comment]
@aleksanderd you need to give permission to the user running webpack to the `/var/node_modules`  folder. 

Please check this thread `https://github.com/bower/bower/issues/2262`

I don't think this is a iview bug, so I'm closing this here. But do check in Stackoverflow if this link ☝️ doesn't solve your problem.
