### ISSUE TITLE
Table第一次渲染会js定宽，动效滑动左侧菜单时，表格宽度不会自适应。

### ISSUE THREAD

**Issue by xiaoyu214** [iview/iview#1952]
Table第一次渲染会js定宽，通过js写效果滑动隐藏左侧菜单时，表格宽度依旧不变，而表格外的div却变大了。因此表格右侧会有几百像素空白的地方。Table宽度能否自适应容器？而不是第一次就定死了宽度。

**Comment by icarusion** [comment]
#690
