### ISSUE TITLE
Table 控件 在列多的情况下出现高度计算错误（底部有空白）

### ISSUE THREAD

**Issue by liuqiangzh163** [iview/iview#1960]
Table 控件 在列多的情况下出现高度计算错误（底部有空白）

具体请看：http://115.28.8.188/Test/Test/TableTest.html

**Comment by liuqiangzh163** [comment]
列越多 空白部分越高

**Comment by zhdwwf** [comment]
@liuqiangzh163 看上去是你给tabel设置了height的原因，body部分高度与table的不一致
![image](https://user-images.githubusercontent.com/564279/30769474-a6462dc0-a04b-11e7-93e8-79a5cc4b5165.png)

**Comment by liuqiangzh163** [comment]
@zhdwwf  我是这样使用控件的【        <i-table :width="InstructionSheet.width" border :height="InstructionSheet.height" :data="InstructionSheet.TableData" :columns="InstructionSheet.TableColumns" stripe ></i-table>
】 然后没有设置其他，  body部分高度应该是控件自动计算的，但不确定为什么会计算成这样，所有提交到这里 看看大家有没有碰到，怎样解决的

**Comment by liuqiangzh163** [comment]
![Uploading image.png…]()




[](url)

**Comment by liuqiangzh163** [comment]
好像会影响好几个地方的计算，目前我使用该方法来重新计算他 ，临时解决
1.给Table 加了一个ID
`<i-table id=“table1” :width="InstructionSheet.width" border :height="InstructionSheet.height" :data="InstructionSheet.TableData" :columns="InstructionSheet.TableColumns" stripe ></i-table`
2.添加了一个延时处理去重新设置高度
`setTimeout(function () {
       var iveTheight = VueData.InstructionSheet.height - $("#table1 .ivu-table-header").height();
       var iveBheight = $("#table1 .ivu-table-body").height() - $("#table1 .ivu-table-fixed-body").height();
       $("#table1").height(VueData.InstructionSheet.height);
       $("#table1 .ivu-table-body").height(iveTheight);
       $("#table1 .ivu-table-fixed-body").height(iveTheight - iveBheight);
}, 600)`
