### ISSUE TITLE
Col Span 0

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [iview/iview#1961]
Sorry for the bad Issue report, just a quick thing

If I set :span:"0" in a <col> it doesnt set the class ivu-col-span-0, which is what I was looking for, is this expected? the ivu-col-span-0 set display to none, which is kinda expected when you're settings to span 0

**Comment by SergioCrisostomo** [comment]
Hi @diego-lipinski-de-castro, please setup a codepen or jsFiddle with a example.
Note that `:span:"0"` is invalid sintax, it should be `:span="0"`

**Comment by diego-lipinski-de-castro** [comment]
Hello, yeah here it is, https://codepen.io/maxorhd/pen/OxbVKz

Note that, the <i-menu-item> tag isnt rendering properly in the pen but thats not the problem, the problem is that, when I toggle, it sets the span to 0, and instead of applying the class "ivu-col-span-0" (that sets display to none) it leaves with just "ivu-col" class.

Is this an expected behavier? Because I think it makes more sense to set display none when i want to span 0, or then set width to 0px

**Comment by icarusion** [comment]
Your demo can not repro. and you should use `menu-item`, you can read doc carefully. thank you
