### ISSUE TITLE
Table  render Input on-blur method   is invalid

### ISSUE THREAD

**Issue by dean5277** [iview/iview#1965]
https://jsfiddle.net/1tu1cmjd/12/

是我使用方式有问题吗？

**Comment by SergioCrisostomo** [comment]
@dean5277 the iview event is called `on-blur` so you should use `'on-blur': function() {`like this:  https://jsfiddle.net/Sergio_fiddle/1tu1cmjd/14/

**Comment by dean5277** [comment]
THX
