### ISSUE TITLE
【建议】表单回车提交

### ISSUE THREAD

**Issue by chavyleung** [iview/iview#1968]
目前只能监听input的回车事件来提交表单（当然前提焦点得在input里）
如果焦点不在input就没法回车提交了

举个场景：登录
输完账号、密码，勾选“记住密码”，这样就没法回车提交了

jQuery有个方法可以监听某个dom内的键盘事件（前提焦点也要dom内）
表单能否也提供个类似的事件？

**Comment by icarusion** [comment]
I think this is not a good idea.
