### ISSUE TITLE
dialog组件问题

### ISSUE THREAD

**Issue by fightingm** [iview/iview#197]
建议在dialog组件watch visible时如果为true，清空定时器，不然在关闭dialog的同时再次打开dialog会出现显示bug。
data: function data() {
	        return {
	            timer: null
	        };
	    },
watch: {
            visible: function visible(val) {
	            var _this = this;
	            if (val === false) {
	                this.buttonLoading = false;
	                this.timer = setTimeout(function () {
	                    _this.wrapShow = false;
	                    _this.removeScrollEffect();
	                }, 300);
	            } else {
	            	clearTimeout(this.timer);
	                this.wrapShow = true;
	                this.addScrollEffect();
	            }
	        }
}

**Comment by icarusion** [comment]
Thx.

**Comment by fightingm** [comment]
spin组件好像也有这个问题，解决方案建议在data中添加一个timer，show方法中判断
show () {
            if(this.timer) {
                clearTimeout(this.timer);
            }
            spin.visible = true;
        },
remove (cb) {
            spin.visible = false;
            this.timer = setTimeout(function() {
                spin.$parent.$destroy();
                document.body.removeChild(document.getElementsByClassName('ivu-spin-fullscreen')[0]);
                cb();
            }, 500);
        }

**Comment by yangzhixiao** [comment]
@fightingm 会闪一下，这个怎么解决呢？

**Comment by fightingm** [comment]
@yangzhixiao  你说的是哪个组件，有demo吗？
