### ISSUE TITLE
value.getTime in Form validation with DatePicker and NUXT

### ISSUE THREAD

**Issue by sainf** [iview/iview#1971]
Hi.

This error occurs in validation of the DatePicker, it return the error: value.getTime is not a function

Note: This error only appears when the page is server loaded, if is loaded in client the validation work's fine!

The code is a new nuxt with basic template and only added the Form, DatePicker and validation.

```<template>
  <section class="container">
    <div>
      <h2>{{mode}}</h2>
      <Row>
        <Form ref="fm" :model="fm" :rules="fmRules" label-position="top">
          <formItem label="Ano" prop="year">
            <DatePicker v-model="fm.year" type="year" style="width: 200px"></DatePicker>
          </formItem>
        </Form>
      </Row>
      <Button type="success" @click="fmSubmit('fm')">Validate</Button>
      <h1 class="title">
        my-project
      </h1>
      <h2 class="subtitle">
        Nuxt.js project
      </h2>
      <div class="links">
        <a href="https://nuxtjs.org/" target="_blank" class="button--green">Documentation</a>
        <a href="https://github.com/nuxt/nuxt.js" target="_blank" class="button--grey">GitHub</a>
      </div>
    </div>
  </section>
</template>

<script>
import Logo from '~/components/Logo.vue'

export default {
  components: {
    Logo
  },
  asyncData () {
    return {
      mode: process.server ? 'Im from server' : 'Im from client',
      fm: {
        year: new Date('1977')
      },
      fmRules: {
        year: { required: true, type: 'date', message: 'Necessário', trigger: 'blur' }
      }
    }
  },
  methods: {
    fmSubmit (name) {
      this.$refs[name].validate(async (valid) => {
        this.$Message.success('Im Valid!')
      })
    }
  }
}
</script>

<style>
@import "../node_modules/iview/dist/styles/iview.css";

.container {
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
}

.title {
  font-family: "Quicksand", "Source Sans Pro", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; /* 1 */
  display: block;
  font-weight: 300;
  font-size: 100px;
  color: #35495e;
  letter-spacing: 1px;
}

.subtitle {
  font-weight: 300;
  font-size: 42px;
  color: #526488;
  word-spacing: 5px;
  padding-bottom: 15px;
}

.links {
  padding-top: 15px;
}
</style>
```

**Comment by SergioCrisostomo** [comment]
@sainf (Oi Carlos!) 

do you have a repository we can test? Would be nice to have a smooth integration with Nuxt.

**Comment by sainf** [comment]
Hi.

Sure: https://github.com/sainf/nuxt-iview-bug

thanks

**Comment by SergioCrisostomo** [comment]
@sainf  thanks for the demo, it really helped understand the problem.

So the challenge here is that Nuxt serialises the Dates, and `DatePicker` gets a _String_ as input value. The DatePicker can survive that but the validator cannot. 

I [sent a fix suggestion](https://github.com/iview/iview/pull/1994) for this that we need to test. Please test it also.

Another possible fix is locally calling a change in the DatePicker:

	mounted() {
		this.$refs.datepicker.value = new Date(this.$refs.datepicker.value)
	}

<details>
  <summary>
    full code from your example:
  </summary>

      <template>
        <section class="container">
          <div>
            <h2>{{mode}}</h2>
            <Row>
              <Form ref="fm" :model="fm" :rules="fmRules" label-position="top">
                <formItem label="Ano" prop="year">
                  <DatePicker ref="datepicker" v-model="fm.year" type="year" style="width: 200px"></DatePicker>
                </formItem>
              </Form>
            </Row>
            <Button type="success" @click="fmSubmit('fm')">Validate</Button>

          </div>
        </section>
      </template>

      <script>
      export default {
    	asyncData() {
    		return {
    			mode: process.server ? 'Im from server' : 'Im from client',
    			fm: {
    				year: new Date('1977')
    			},
    			fmRules: {
    				year: {required: true, type: 'date', message: 'Necessário', trigger: 'blur'}
    			}
    		}
    	},
    	methods: {
    		fmSubmit(name) {
    			this.$refs[name].validate(async valid => {
    				this.$Message.success('Ei, Valid!')
    			})
    		}
    	},
    	mounted() {
    		this.$refs.datepicker.value = new Date(this.$refs.datepicker.value)
    	}
    }
    </script>

      <style>
      .container {
        min-height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
      }
      </style>

</details>

**Comment by sainf** [comment]
@SergioCrisostomo Thanks for the commit, just tested and it works perfectly.
But giving the values in mounted doesn't works...

Thanks for all!

Note:
TimePicker Validation and NUXT work perfectly
Unfortunately with all this test and find out a new bug with DatePicker/TimePicker that breaks NUXT #1995
