### ISSUE TITLE
Form组件里的Input，无法正确绑定on-enter事件

### ISSUE THREAD

**Issue by weihongyu12** [iview/iview#1976]
iView 版本号
2.2.1

操作系统/浏览器 版本号
Windows/Chrome 61

Vue 版本号
2.4.2

能够复现问题的在线示例（重要）
```
<Form ref="formValidate" :label-width="80" :rules="ruleValidate" :model="formValidate">
  <Form-item label="流水号" prop="serialNumber">
    <Input placeholder="请输入流水号按回车搜索" size="large" v-model="formValidate.serialNumber"
           @on-blur="handleGetPayBillsInfo('formValidate')" @on-enter.stop="handleGetPayBillsInfo('formValidate')"></Input>
  </Form-item>
</<Form>
```

复现步骤
直接在键盘上按Enter，不会触发绑定事件，而会触发原生的表单的submit事件

问题现象，以及你期望的结果是怎样的？
1. 按Enter时，不触发form的submit事件
2. 为`Form`增加`on-submit`事件

你估计可能的原因是什么（选填）？
1. 按Enter时，事件冒泡了

**Comment by weihongyu12** [comment]
我在官方文档和issue都没能找到相关的资料，可以在这里给我一些参考资料吗？

**Comment by jackzhcai** [comment]
https://github.com/iview/iview/pull/1837
