### ISSUE TITLE
請問input能不能支援keypress事件?

### ISSUE THREAD

**Issue by infixman** [iview/iview#198]
### iView 版本号
0.9.14

### 操作系统/浏览器 版本号
win7/Chrome 55

### Vue 版本号
1.0

### 问题现象，以及你期望的结果是怎样的?
請問input能不能支援keypress事件?

**Comment by icarusion** [comment]
暂时不支持keydown事件，修改了 on-form-change 事件触发的时机，但返回的参数是 value，不是 event
