### ISSUE TITLE
Table component: Constantly getting resizer error on Chrome

### ISSUE THREAD

**Issue by iSunRise** [iview/iview#1985]
Hi guys,
Thank you for great product!
Unfortunately I'm getting issue every time I use the Table component, the issue looks like:
```
Uncaught Error: Element is not detectable by this strategy.
    at Object.addListener (iview.js?0536:28107)
    at onElementDetectable (iview.js?0536:27536)
   .....

  | addListener | @ | iview.js?0536:28107
  | onElementDetectable | @ | iview.js?0536:27536
  .....
  | mounted | @ | iview.js?0536:26295
  | callHook | @ | vue.js?e1b2:2705

```
I found that this message is generated by "element-resize-detector" and you use it [in table component](https://github.com/iview/iview/blob/2.0/src/components/table/table.vue#L733) without any init params. Error appears on last Chrome (61.0.3163.100), Firefox works good.
This plugin [has issues](https://github.com/wnr/element-resize-detector/issues/81) when initialized by default and its author recommends to use `{strategy: "scroll"}` parameters on initialization as a solution.

Could you consider adding these params into resize detector inside table component?

Best Regards
Alexander

P.S. tried to reproduce this bug, but it just doesn't work: https://codepen.io/anon/pen/Nadgee

**Comment by icarusion** [comment]
thanks for feedback, we'll check.

**Comment by iSunRise** [comment]
Can I somewhow help you with it?

**Comment by iamzhangjinpeng** [comment]
![image](https://user-images.githubusercontent.com/13995613/31607596-87407b18-b29f-11e7-8b07-5a61d51824e0.png)

I have the same problem in ivew@2.4.0, but it work well in iview@2.3.2

**Comment by icarusion** [comment]
Please update to `2.6.0` and try again, if the problem still exists, you can submit a new issue in https://www.iviewui.com/new-issue - thank you!

**Comment by loveWct** [comment]
when i use iview with nuxt@2.5.1,I got the  problem in iview@3.3.3,
![image](https://user-images.githubusercontent.com/26271505/55457979-30d84c00-561e-11e9-98b1-1004442afb8d.png)
and my chrome version 
![image](https://user-images.githubusercontent.com/26271505/55457940-130ae700-561e-11e9-8d61-212018ab20c9.png)
