### ISSUE TITLE
timeline 不能使用在CDN 下面

### ISSUE THREAD

**Issue by fumeiyu** [iview/iview#1987]
CDN下不能正常运行
timelineitem 不能被识别

**Comment by SergioCrisostomo** [comment]
Can you provide a example with jsFiddle or codepen?

使用下面的在线链接可以快速创建示例
https://codepen.io/anon/pen/KvJJdw

**Comment by fumeiyu** [comment]
已创建
https://codepen.io/anon/pen/RLpMNW?editors=1111
但是显示不了 时间轴
参考的内容
https://www.iviewui.com/components/timeline

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/30904605-0e5048f8-a338-11e7-9d6a-c16f693d25e7.png)

**Comment by fumeiyu** [comment]
Thanks ,解决了
