### ISSUE TITLE
iview中的table调用 exportCsv() 方法在ie9下没有排列

### ISSUE THREAD

**Issue by lzb543041962** [iview/iview#1989]
你好，我在使用iview中的table调用 exportCsv() 方法时发现ie9下导出的csv用excel打开，会丢失排列。
用的是官网实例：https://www.iviewui.com/#/components/table
![image](https://user-images.githubusercontent.com/11659727/30845874-e9977eac-a2c7-11e7-963b-9eb7aa599cc8.png)
请问这是因为什么原因，有没有什么解决方法？

**Comment by ly525** [comment]
@lzb543041962 丢失排列？还是丢失排序？还是丢失列？？

**Comment by lzb543041962** [comment]
@ly525 行没问题，只剩下一列，里面是整行的数据。
![image](https://user-images.githubusercontent.com/11659727/30850759-241aed82-a2d9-11e7-8747-ae093898b08a.png)
源码里采用的好像是另存为的形式。

**Comment by ly525** [comment]
@lzb543041962 你说是一行一行地显示数据，而不是按照逗号分隔是吗？
这样出现的原因是你需要设置你的excel的分隔符为逗号。参见 #1460

**Comment by SergioCrisostomo** [comment]
@lzb543041962 please provide a live example for this.

使用下面的在线链接可以快速创建示例
https://codepen.io/pen/WZpqGZ

**Comment by RainSnowSnow** [comment]
exportCsv   带有render的渲染的数据，单数不添加key值输出的为空，怎么解决啊
