### ISSUE TITLE
单独引入cascader 报错

### ISSUE THREAD

**Issue by yhZhouYh** [iview/iview#199]
### Vue 版本号

template syntax error Component template should contain exactly one root element:

<ul v-if="data && data.length" :class="[prefixCls + '-menu']">
    <Casitem
        v-for="item in data"
        :prefix-cls="prefixCls"
        :data.sync="item"
        :tmp-item="tmpItem"
        @click.stop="handleClickItem(item)"
        @mouseenter.stop="handleHoverItem(item)"></Casitem>
</ul><Caspanel v-if="sublist && sublist.length" :prefix-cls="prefixCls" :data.sync="sublist" :disabled="disabled" :trigger="trigger" :change-on-select="changeOnSelect"></Caspanel>

If you are using v-if on multiple elements, use v-else-if to chain them instead.

ERROR in ./~/.10.0.2@vue-loader/lib/template-compiler.js?id=data-v-3795307f!./~/.10.0.2@vue-loader/lib/selector.js?type=template&index=0!./~/.0.9.14@iview/src/components/input/input.vue
template syntax error <input :type="type" v-model="value">:
v-model does not support dynamic input types. Use v-if branches instead.

**Comment by icarusion** [comment]
show me the code.

**Comment by yhZhouYh** [comment]
// ],
        loaders: [{
                test: /\.vue$/,
                loader: 'vue'
            },
            { test: /iview.src.*?js$/, loader: 'babel' },

import Cascader from 'iview/src/components/cascader';

**Comment by icarusion** [comment]
亲测没有任何问题，check your code.

**Comment by yhZhouYh** [comment]
是我vue版本的问题么"vue": "2.1.8"

**Comment by rijn** [comment]
暂不支持Vue2

**Comment by yhZhouYh** [comment]
不好意思。。。 都没看清
