### ISSUE TITLE
【建议】Select、Dropdown、DatePicker等浮层placement自适应

### ISSUE THREAD

**Issue by xiaoxin0818** [iview/iview#1990]
在使用的时候，发现iview有浮层操作的组件，如Select、Dropdown、DatePicker、TimePicker等有浮层交互的组件，浮层朝向不能自适应，当组件在容器边界时展开，浮层会出现溢出容器的情况，这种交互本应该是自适应根据当前视窗位置，自适应placement朝向，比如element的浮层的组件都会有自适应处理。
作为一个ui组件库，这类浮层组件应该提供自适应的浮层，而不是只是提供了placement配置参数让使用者自行处理。

**Comment by SnowWinterMaye** [comment]
这个需要他们升级 popper的版本

**Comment by tweet** [comment]
我发现去掉这个options `boundariesElement: "body" `就可以了，不知道作者 @icarusion 加这个属性的缘由是啥，升级popper.js到1.2版本后去掉此配置项也是没问题的
