### ISSUE TITLE
【建议】：table 固定列滚动优化

### ISSUE THREAD

**Issue by qq986063761** [iview/iview#1991]
现在好像鼠标放在table固定列上滚动，似乎不会整体内容滚动，因为设置了overflow：hidden；我看到react 的ant框架中table这个部分似乎处理的还不错，感觉表格有固定列后，鼠标在固定列上滚动应该也生效可能会比较好，因为需求中如果固定列的宽度比较大的时候，大块区域中都不能滚动应该会被测试提bug

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
