### ISSUE TITLE
Page分页组件在ie10及ie9报错问题

### ISSUE THREAD

**Issue by chaseEternity** [iview/iview#1992]
![image](https://user-images.githubusercontent.com/32295244/30853356-2c694120-a2e1-11e7-8695-27a414e3f44d.png)
在实际项目中报错，后来直接进ivew官网进行测试，发现ivew官网的例子也是报Error in directive transfer-dom inserted hook: "TypeError: 无法获取未定义或 null 引用的属性“transfer”"类似的错误
环境：
系统：win10
浏览器：ie11
测试环境：ie11模式下的ie10和ie9

**Comment by gitzhangfugui** [comment]
@chaseEternity 这个是用到这个指令应该都有问题transfer-dom，我已经提交过一个了，ie兼容问题，还没解决....

**Comment by icarusion** [comment]
未来不支持低版本 ie

**Comment by chaseEternity** [comment]
谢谢
