### ISSUE TITLE
Tree组件不能更新(重渲染)结点(Node)的问题

### ISSUE THREAD

**Issue by easyfrog** [iview/iview#1993]
按例子创建了一个Tree组件.没有问题. 
但问题是创建之后. 我使用代码 . 向 baseData中的一个节点中 加入children并添加了几个结点.. 但界面中的Tree组件 没有任何变化, 只有再使用鼠标点击那个节点的时候. 才会更新(重渲染).  

请问这是Bug吗? 还是有什么解决方法?

**Comment by bitqiang** [comment]
tree 感觉bug还是比较多的。。其实你可以尝试用v-if销毁组件。可能会好用些

**Comment by Zaveon** [comment]
功能太少了
