### ISSUE TITLE
在线演示功能

### ISSUE THREAD

**Issue by Shruan** [iview/iview#1998]
在使用ivew组件实例的时候都没有办法直接编辑及测试，挺麻烦的 
希望iview官网在组件后面能新增一个icon，能快速链接到组件实例上，方便测试和使用

**Comment by Shruan** [comment]
![image](https://user-images.githubusercontent.com/28869029/30892017-ead5f044-a2fb-11e7-9430-bb0303b682f6.png)
在饿了么UI的官网上貌似就有这样的功能，可以参考一下

**Comment by icarusion** [comment]
added
