### ISSUE TITLE
npm淘宝镜像

### ISSUE THREAD

**Issue by saint3347** [iview/iview#20]
npm淘宝镜像是不是没有iview？？安装失败了

**Comment by icarusion** [comment]
应该没有

**Comment by hmdeng110** [comment]
实查有，第一个就是
![qq 20161009154319](https://cloud.githubusercontent.com/assets/15642931/19218851/24ecaaf0-8e37-11e6-8ceb-40cc296c1ba1.png)

**Comment by saint3347** [comment]
![image](https://cloud.githubusercontent.com/assets/7347133/19218879/df4d070a-8e37-11e6-9c6c-45634553fda2.png)
第二次执行npm install iview --save可以啦~\(≧▽≦)/~
