### ISSUE TITLE
TabPane: Content with Select, and Datepickers hidden

### ISSUE THREAD

**Issue by CassianoViana** [iview/iview#2008]
I have a form with a DatePicker inside Form into a TabPane.
As you can see the bottom of the DatePicker is hidden by the foreground.
The same occurs with select (I have the options 1,2,3 in the example).

![screenshot from 2017-09-27 09-31-57](https://user-images.githubusercontent.com/6260991/30913541-f82f9c7a-a366-11e7-9492-33e920d52645.png)

![screenshot from 2017-09-27 09-37-11](https://user-images.githubusercontent.com/6260991/30913692-7bbeea1e-a367-11e7-95d5-478942a0728e.png)

The fullscreen:
![screenshot from 2017-09-27 09-45-21](https://user-images.githubusercontent.com/6260991/30914143-f271e3c2-a368-11e7-9281-e557ef4eec12.png)

My code is:
`<Tabs value="termosUso">
			<TabPane label="Detalhes" name="detalhes">
				<CursoFormDetalhes></CursoFormDetalhes>		
			</TabPane>
                      ...other TabPanes
		</Tabs>`

In CursoFormDetalhes i have a Form with rows and the FormIten with de Select/DatePicker..

I'll appreciate any help

**Comment by SergioCrisostomo** [comment]
@CassianoViana please provide a codepen that reproduces your problem.
(https://codepen.io/anon/pen/KvJJdw)

**Comment by CassianoViana** [comment]
Thanks @SergioCrisostomo I reproduce here (https://codepen.io/anon/pen/VMbBoj)

**Comment by SergioCrisostomo** [comment]
If we remove `overflow: hidden;` from `.ivu-tabs` it works good: https://codepen.io/sergiocrisostomo/pen/RLVvzX

@icarusion do you see any problem with that change?

**Comment by icarusion** [comment]
Sorry to reply now, many components using dropdown like `Select`, `DatePicker`,`Cascader`.. can set `transfer` property, you can find more details on doc.

**Comment by qbunia** [comment]
This should be somewhere in docs. I spent more than 30 minutes to figure out why my tab pane cuts my select popup.
