### ISSUE TITLE
TabPane: Go to next tab' input by pressing tab key.

### ISSUE THREAD

**Issue by CassianoViana** [iview/iview#2009]
I have two tabs (A, B):

![screenshot from 2017-09-27 09-54-21](https://user-images.githubusercontent.com/6260991/30914592-9b8760c6-a36a-11e7-8a4f-9c547f2f74e0.png)

When i hit tab key (the first A's input is focused), then the B's input is gain the focus.
The TabPane title disapear:

![screenshot from 2017-09-27 09-54-48](https://user-images.githubusercontent.com/6260991/30914634-be47378a-a36a-11e7-9422-1851e5a10545.png)

My code is:
`<Tabs value="A">
			<TabPane label="A" name="A">
				<input placeholder="AAA">
			</TabPane>
            <TabPane label="B" name="B">
				<input placeholder="BBB">
			</TabPane>
		</Tabs>`

Thanks, I'll appreciate any help!

**Comment by SergioCrisostomo** [comment]
Oi @CassianoViana! Can you please create a codepen to reproduce the problem?

Use this as starting point: https://codepen.io/anon/pen/KvJJdw

**Comment by icarusion** [comment]
This feature is not currently supported.
