### ISSUE TITLE
[Help] How to properly implement iview with vue-notification? 

### ISSUE THREAD

**Issue by rlam3** [iview/iview#2011]
How do we properly implement iview with vue-notification in a NuxtJS app? 
I'm looking for a simple way to trigger a `notice` upon a index page on first visit.

Thanks! Really appreciate your help! 

Reference: https://www.iviewui.com/components/notice-en

**Comment by lcx960324** [comment]
Sorry but I don't understand what the question is about. Is there any problem using iView's `Notice` in Nuxt.js ?

**Comment by rlam3** [comment]
@lcx960324 I'm trying to implement vue-notification with iview component notice on index page load in a NuxtJS App. Any tutorial on how to do this? Thanks!

**Comment by icarusion** [comment]
using `this.$Notice` when mounted
