### ISSUE TITLE
iview 的select组件中，在和v-model绑定时，展示其value值，绑定对应的id提交后台

### ISSUE THREAD

**Issue by xiwadai** [iview/iview#2020]
1.这是让用户看到的
![image](https://user-images.githubusercontent.com/24467843/30961439-c9bfdc52-a478-11e7-83f5-8838379c3d13.png)

2.提交后台的是其对应的id
![image](https://user-images.githubusercontent.com/24467843/30961503-f92beecc-a478-11e7-8a7a-e1f84b376a66.png)

3.代码
![image](https://user-images.githubusercontent.com/24467843/30961628-5d419664-a479-11e7-8904-e2afed6a16fa.png)

4.期望解决：展示给用户的是value，怎样提交后台的是id,

**Comment by lcx960324** [comment]
https://www.iviewui.com/components/select
可以参考 Select 的第一个示例，在 Option 中自定义展示的内容，然后把 value 赋值为想要传递的值。

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
