### ISSUE TITLE
建议可补充一些控件

### ISSUE THREAD

**Issue by sadenwang** [iview/iview#2023]
小小的建议，iview的控件已经很多了，但是还不够丰富和深入，建议参考一下http://www.uileader.com/quickui/system/main/main.jsp
,虽然感觉U做的不如IVIEW，但是控件种类和使用的定制化方面考虑的很全面实用，作为菜鸡，贡献不了代码，只能寄希望于大神了

**Comment by 954053260** [comment]
<i-table :columns="columns" :data="data.records" :loading="true"></i-table>
我发现table组件这样使用，loading加载不出来

**Comment by SergioCrisostomo** [comment]
Thank you!
