### ISSUE TITLE
Menu菜单的z-index与Dropdown下拉菜单的z-index冲突

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview#2024]
# 版本：iview 2.4
###  原因menu菜单与dropdown使用的同一个样式.ivu-select-dropdown，造成冲突。查阅文档发现，最近修改过menu的z-index #823 。建议规划整理一下z-index，以保证其他不出现问题。

谢谢官方一直对iview的支持。希望iview越来越好。

![qq 20170929120856](https://user-images.githubusercontent.com/30425581/31000614-808673ec-a50f-11e7-9514-68f34586a22d.png)

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
