### ISSUE TITLE
InputNumber当precision为0时，无法精确为整数

### ISSUE THREAD

**Issue by tvolitt** [iview/iview#2026]
源码223行：
if (this.precision) val = Number(Number(val).toFixed(this.precision));
是否应该加上对this.precision === 0的判断？
如：if (this.precision === 0 || this.precision) val = Number(Number(val).toFixed(this.precision));

**Comment by SergioCrisostomo** [comment]
@tvolitt why did you close the issue? 
I sent a fix for it, but its not merged yet :) maybe better to keep it open until its in master.
