### ISSUE TITLE
[Bug Report] select中的option label动态加载时，select默认值没有显示label中的值

### ISSUE THREAD

**Issue by abcdGJJ** [iview/iview#2028]
## 问题描述

select组件，默认值和option下面的label值都是动态设定的。设定完成后，select样式显示已选定，但是没有出现动态设定的label值

## 在线示例

https://codepen.io/abcdGJJ/pen/qPjbpa

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
