### ISSUE TITLE
checkbox组件支持排序

### ISSUE THREAD

**Issue by webproblem** [iview/iview#2037]
添加checkbox组件支持按顺序返回value值。
目前的checkbox组件在CheckboxGroup组合下，得到勾选的值是按照勾选时的顺序排列的，比如有A，B，C，D几个多选框，可能勾选的顺序是B->A->C->D，返回的value值就是["B","D","C","A"]，但是在一些应用场景下需要得到的是按照多选框的顺序来排列的value值，比如考试系统的题目选项等。

**Comment by SergioCrisostomo** [comment]
related: https://github.com/iview/iview/pull/2021

**Comment by BengBu-YueZhang** [comment]
你可以自己排序，不是框架的问题

**Comment by icarusion** [comment]
https://github.com/iview/iview/pull/2021#issuecomment-335063240
