### ISSUE TITLE
form-item表单验证BUG

### ISSUE THREAD

**Issue by xecrom** [iview/iview#2040]
由于vue的组件更新策略，导致form内的form-item在删除时，并不会触发组件的destroyed方法，导致表单验证有BUG。如下：
https://jsfiddle.net/xecrom/yyrzhm46/1/

我的临时处理方式是，在form-item 外面套一层div,暂时解决

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
