### ISSUE TITLE
support mobile usage with touch/swipe events

### ISSUE THREAD

**Issue by mkhanal** [iview/iview#2044]
Currently with components like carousel and scroll, iview does not support touch/swipe events.
This is a huge hurdle in using it for a mobile-first platform. This is even more relevant as more and more development is moving away from native to PWA s.

**Comment by SergioCrisostomo** [comment]
@mkhanal good point, specially taking into account PWAs. 
This could be a long term goal and people like you and me would help identify and fix the needed issues.

@icarusion can we add it to the wish list and improve where needed?

**Comment by icarusion** [comment]
I am not very recommend using iView on mobile. Many of iView's designs are not compatible with mobile. It is not like [Quasar Framework](http://quasar-framework.org/).

For click events, I recommend using [fastclick](https://github.com/ftlabs/fastclick).

**Comment by mkhanal** [comment]
@icarusion : Does this mean iView is supposed to be used only for desktop sites (that don't open on mobiles)? Since it is responsive, I'd assume it would also be fit for tablets and mobiles (not as apps, but on browsers). And if it, we should honour the interaction patterns for those devices.

**Comment by icarusion** [comment]
Currently, some components do not support mobile devices, and maybe we will optimize when iView 3.0, but the workload is huge.
