### ISSUE TITLE
tabs从中间删除会错乱的问题 提了好长时间也没人答 有复现demo

### ISSUE THREAD

**Issue by wangweida** [iview/iview#2049]
http://jsbin.com/bihiliwuho/edit?html,js,console,output

1. 先点两下添加
2. 删除标签页2
3. 再点下增加

**Comment by wangweida** [comment]
不明白哪描述不清楚了，在线的bug的demo也有，复现总共也就3步。
知道做开源不易，但是也不用一直关issue吧。

**Comment by icarusion** [comment]
你先更新到最新版再试试吧。
