### ISSUE TITLE
layout布局使用异常

### ISSUE THREAD

**Issue by markflyfly** [iview/iview#2052]
1.iview和vue版本
![image](https://user-images.githubusercontent.com/15846359/31335310-9663b3ba-ad24-11e7-932c-cbff7456c8ea.png)
2.错误提示
![image](https://user-images.githubusercontent.com/15846359/31335329-aae2777c-ad24-11e7-835b-4b634d017183.png)
3.代码结构【基本与示例代码相同】
![image](https://user-images.githubusercontent.com/15846359/31335345-b940a19a-ad24-11e7-83d0-57e8f3148399.png)

**Comment by icarusion** [comment]
[https://www.iviewui.com/docs/guide/start#组件使用规范](https://www.iviewui.com/docs/guide/start#组件使用规范)

**Comment by markflyfly** [comment]
@icarusion 必须要在webpack环境下使用吗，我是使用script标签引入的
