### ISSUE TITLE
Modal 中的 Dropdown 加了transfer 后的问题

### ISSUE THREAD

**Issue by lenxeon** [iview/iview#2053]
演示地址
https://codepen.io/lenxeon/pen/QqryXy

加了transfer 后的结果
![wechatimg1724](https://user-images.githubusercontent.com/251825/31361021-cba06856-ad16-11e7-9b9d-dfb284794e3a.jpeg)
不加了transfer 会有滚动问题
<img width="817" alt="wx20171010-062648 2x" src="https://user-images.githubusercontent.com/251825/31361156-87772a88-ad17-11e7-9e75-8f47a946e6d3.png">

**Comment by icarusion** [comment]
你的demo问题
https://jsfiddle.net/Aresn/0xsagwt1/

**Comment by lenxeon** [comment]
@icarusion 在您的demo里，模拟modal超过一定高度，需要滚动的时候一样能复现这个问题。您这个例子中modal的高度还没有到需要滚动的时候所以没有问题。当modal里的内容很多造成需要滚动的时候，只要一滚动了，select的错位问题就复现了。
