### ISSUE TITLE
多选日期组件的临时解决方案

### ISSUE THREAD

**Issue by BengBu-YueZhang** [iview/iview#2055]
iView目前没有多选的功能

**Comment by BengBu-YueZhang** [comment]
我目前的解决方案是自己按照iview的样式，自己写了一个有多选功能的日期组件，不是在iview基础上改的。
首先声明我是菜b，所以代码写得很烂，请各位不要介意

**Comment by BengBu-YueZhang** [comment]
<template>
  <div class="multiselect-time-wrapper">
    <div class="time-input">
      <Input :icon="iconType" placeholder="选择日期" style="width: 200px" v-model="times" ref="input" 
      @mouseover.native="mouseOver"
      @mouseout.native="mouseout"
      @on-focus="isShowTimeMenu = true"
      @on-blur="timesBlur"
      @on-click="clearInput"></Input>
    </div>
    <transition name="multiselect">
      <div class="time-menu" v-if="isShowTimeMenu">
        <div class="time-menu-title">
          <div class="time-menu-title-operation-left">
            <a href="javascript:;" @mousedown="prevYear($event)" class="time-btn">
              <i class="ivu-icon ivu-icon-ios-arrow-left"></i><i class="ivu-icon ivu-icon-ios-arrow-left"></i>
            </a>
            <a href="javascript:;" @mousedown="prevMonth($event)" class="time-btn">
              <i class="ivu-icon ivu-icon-ios-arrow-left"></i>
            </a>
          </div>
          <div class="time-menu-title-content">
            <a href="javascript:;" @mousedown="quickSelectionYear($event)">{{currentTimeYear}}年</a>
            <a href="javascript:;" @mousedown="quickSelectionMonth($event)">{{currentTimeMonth}}&nbsp月</a>
          </div>
          <div class="time-menu-title-operation-right">
            <a href="javascript:;" @mousedown="nextMonth($event)" class="time-btn">
              <i class="ivu-icon ivu-icon-ios-arrow-right"></i>
            </a>
            <a href="javascript:;" @mousedown="nextYear($event)" class="time-btn">
              <i class="ivu-icon ivu-icon-ios-arrow-right"></i><i class="ivu-icon ivu-icon-ios-arrow-right"></i>
            </a>
          </div>
        </div>
        <div class="time-menu-content">
          <div class="week-list">
            <span>日</span>
            <span>一</span>
            <span>二</span>
            <span>三</span>
            <span>四</span>
            <span>五</span>
            <span>六</span>
          </div>
          <div class="time-list">
            <a href="javascript:;"
              v-for="(item, index) in dateList"
              :key="index"
              :class="{
                'no-current-month': currentTimeMonth != item.month,
                'current-month': currentTimeMonth == item.month && !item.isChoice
              }"
              @mousedown="choiceDate($event, item)">
              <i class="current-day-icon" v-if="toDay == item.day && toMonth == item.month && toYear == item.year"
                :class="{'selected-current-day-icon': currentTimeMonth == item.month && item.isChoice}">
              </i>
              <em :class="{'selected-day': currentTimeMonth == item.month && item.isChoice}">
                {{item.day}}
              </em>
            </a>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
import R from 'ramda'

const TotalNumberOfDays = 42
const timeReg = /^\d{4}(\-)\d{1,2}\1\d{1,2}$/g

window.timeReg = timeReg

export default {
  props: {
    // 默认选中的日期
    'date-list-default': {
      type: Array,
      default () {
        return []
      }
    }
  },

  data () {
    return {
      // icon类型
      iconType: 'calendar',
      // 多选的字符串
      times: '',
      // 发生改变以前的多选字符串
      oldTimes: '',
      // 显示日期多选框
      isShowTimeMenu: false,
      // 显示清空按钮
      isShowClearBtn: false,
      // 日期表时间对象
      time: null,
      // 日期表时间对象的月份
      currentTimeMonth: 0,
      // 日期表时间对象的年份
      currentTimeYear: 0,
      // 日期表时间对象渲染的列表
      dateList: [],
      // 当前的时间对象
      toDate: null,
      // 当天的天
      toDay: 0,
      // 当前的月
      toMonth: 0,
      // 当前的年
      toYear: 0,
      // 选中的日期列表
      choiceDateList: []
    }
  },

  watch: {
    times (val, oldVal) {
      this.oldTimes = oldVal
    },

    isShowTimeMenu (val, oldVal) {
      if (val) this.init()
    },

    choiceDateList: {
      handler: function (val, oldVal) {
        this.times = ''
        val.forEach((item, index) => {
          let timeString = `${item.year}-${this.supplementZero(item.month)}-${this.supplementZero(item.day)}`
          index + 1 == val.length ? this.times += `${timeString}` : this.times += `${timeString},`
        })
        this.$emit('changeDate', val)
      },
      deep: true
    }
  },

  created () {
    this.toDate = new Date()
    this.toDay = this.toDate.getDate()
    this.toMonth = this.toDate.getMonth() + 1
    this.toYear = this.toDate.getFullYear() 
    if (this.dateListDefault.length) {
      this.dateListDefault.forEach((item) => {
        if (!item.isChoice) item.isChoice = true
      })
      this.choiceDateList = [...this.choiceDateList, ...this.dateListDefault]
    }
  },

  mounted () {
    // 添加获取当前月的天数的原型方法
    Date.prototype.getMonthNumber = function () {
      let year = this.getFullYear()
      let month = this.getMonth() + 1
      let date = new Date(year, month, 0)
      return date.getDate()
    },

    // 获取本月第一天的是周几的方法
    Date.prototype.getNowMonthOneDayWeek = function () {
      let year = this.getFullYear()
      let month = this.getMonth() + 1
      let date = new Date(year, month - 1, 1)
      let day = date.getDay()
      return  day == 0 ? 7 : day
    }
  },

  methods: {

    /**
     * 初始化
     */
    init () {
      if (!this.time) this.time = R.clone(this.toDate)
      this.renderingCalendar(this.time)
    },

    /**
     * 渲染日历
     * @param {Date} 日期对象  
     */
    renderingCalendar (date) {
      let week = date.getNowMonthOneDayWeek()
      let currentMonthLength = date.getMonthNumber()
      let currentMonth = this.currentTimeMonth = date.getMonth() + 1
      let currentYear = this.currentTimeYear = date.getFullYear()
      let prevMonth = 0
      let prevMonthLength = 0
      let prevYear = 0
      let nextMonth = 0
      let nextMonthLength = 0
      let nextYear = 0
      let currentList = []
      let prevList = []
      let nextList = []
      let prevMonthShowLength = 0
      if (week == 7) {
        prevMonthShowLength = 0
      } else {
        prevMonthShowLength = week
      }
      let nextMonthShowLength = TotalNumberOfDays - currentMonthLength - prevMonthShowLength
      switch (currentMonth) {
        case currentMonth == 12:
          prevMonth = currentMonth - 1
          prevYear = currentYear
          nextMonth = 1
          nextYear = currentYear + 1
          break
        case currentMonth == 1:
          prevMonth = 12
          prevYear = currentYear - 1
          nextMonth = currentMonth + 1
          nextYear = currentYear
          break
        default:
          prevMonth = currentMonth - 1
          prevYear = currentYear
          nextMonth = currentMonth + 1
          nextYear = currentYear
      }
      prevMonthLength = new Date(prevYear, prevMonth - 1, 1).getMonthNumber()
      nextMonthLength = new Date(nextYear, nextMonth - 1, 1).getMonthNumber()
      for (let i = 0; i < currentMonthLength; i++) {
        let day = {
          year: currentYear,
          month: currentMonth,
          day: i + 1,
        }
        let isChoiceIndex = this.findChoiceDateList(day)
        isChoiceIndex == -1 ? day.isChoice = false : day.isChoice = true
        currentList.push(day)
      }
      for (let i = 0; i < prevMonthShowLength; i++) {
        let day = {
          year: prevYear,
          month: prevMonth,
          day: prevMonthLength - prevMonthShowLength + i + 1,
        }
        let isChoiceIndex = this.findChoiceDateList(day)
        isChoiceIndex == -1 ? day.isChoice = false : day.isChoice = true
        prevList.push(day)
      }
      for (let i = 0; i < nextMonthShowLength; i++) {
        let day = {
          year: nextYear,
          month: nextMonth,
          day: i + 1,
        }
        let isChoiceIndex = this.findChoiceDateList(day)
        isChoiceIndex == -1 ? day.isChoice = false : day.isChoice = true
        nextList.push(day)
      }
      this.dateList = [...prevList, ...currentList, ...nextList]
    },

    /**
     * 清空按钮
     */
    clearInput () {
      // 清空
      this.times = ''
      this.iconType = 'calendar'
      this.isShowClearBtn = false
    },

    /**
     * 鼠标移入input
     */
    mouseOver () {
      // 这么做是为了模拟iView的交互效果
      if (this.isShowClearBtn) this.iconType = 'close-circled'
    },

    /**
     * 鼠标移出input
     */
    mouseout () {
      this.iconType = 'calendar'
    },

    /**
     * 前一年
     */
    prevYear (ev) {
      event.preventDefault()
      this.time = new Date(this.currentTimeYear - 1, this.currentTimeMonth - 1, 1)
      this.renderingCalendar(this.time)
    },

    /**
     * 前一月
     */
    prevMonth (ev) {
      event.preventDefault()
      if (this.currentTimeMonth == 1) this.time = new Date(this.currentTimeYear - 1, 11, 1)
      else this.time = new Date(this.currentTimeYear, this.currentTimeMonth - 2, 1)
      this.renderingCalendar(this.time)
    },

    /**
     * 下一年
     */
    nextYear (ev) {
      event.preventDefault()
      this.time = new Date(this.currentTimeYear + 1, this.currentTimeMonth - 1, 1)
      this.renderingCalendar(this.time)
    },

    /**
     * 下一个月
     */
    nextMonth (ev) {
      event.preventDefault()
      if (this.currentTimeMonth == 12) this.time = new Date(this.currentTimeYear + 1, 0, 1)
      else this.time = new Date(this.currentTimeYear, this.currentTimeMonth, 1)
      this.renderingCalendar(this.time)
    },

    /**
     * 选择日期
     * @param {Object} item 每一天对应的对象
     */
    choiceDate (ev, item) {
      event.preventDefault()
      if (item.isChoice) {
        item.isChoice = false
        let index = this.findChoiceDateList(item)
        this.choiceDateList.splice(index, 1)
      } else {
        item.isChoice = true
        this.choiceDateList.push(item)
      }
      // 如果点击的不是当前月份, 跳转到点击的月份
      if (item.month != this.currentTimeMonth) {
        this.time = new Date(item.year, item.month - 1, 1)
        this.renderingCalendar(this.time)
      }
    },

    /**
     * 快捷选择年
     */
    quickSelectionYear () {

    },
    
    /**
     * 快捷选择月
     */
    quickSelectionMonth () {
      
    },

    /**
     * 补0
     * @param {Number, String} val 月,日
     */
    supplementZero (val) {
      return parseInt(val) < 10 ? `0${val}` : val
    },
    
    /**
     * 查询是否是已选择的天数
     * @param {Object} data 每一天对应的对象
     */
    findChoiceDateList (data) {
      let index = this.choiceDateList.findIndex((val) => { 
        return val.year == data.year && val.month == data.month && val.day == data.day
      })
      return index
    },

    /**
     * 修改Input的内容, 通过正则匹配生成新的表达式
     */
    timesChange () {
      let oldDateList = this.oldTimes.split(',')
      let newDateList = this.times.split(',')
      newDateList.forEach((item, index) => {
        // 正则搜索位归0, 不符合正则规则用原有的值代替
        timeReg.lastIndex = 0;
        if (!timeReg.test(item)) {
          if (oldDateList[index]) {
            newDateList[index] = oldDateList[index]
          } else {
            newDateList.splice(index, 1)
          }
        }
      })
      this.choiceDateList = []
      newDateList.forEach((item, index) => {
        let specificDateList = item.split('-')
        let time = new Date(specificDateList[0], specificDateList[1] - 1, specificDateList[2])
        let year = time.getFullYear()
        let month = time.getMonth() + 1
        let day = time.getDate()
        this.choiceDateList.push({
          year: year,
          month: month,
          day: day,
          isChoice: true
        })
      })
    },

    /**
     * 失去焦点
     */
    timesBlur () {
      this.isShowTimeMenu = false
      this.timesChange()
    }
  }
}
</script>

<style scoped>
.multiselect-time-wrapper {
  position: relative;
}

.time-menu {
  position: absolute;
  left: 0;
  top: 35px;
  z-index: 9999;
  width: 218px;
  height: 250px;
  box-sizing: border-box;
  border: 1px solid #eaeaea;
  border-radius: 5px;
  box-shadow: 0 0 5px #eaeaea;
  background-color: #fff;
  transition: all 200ms;
  opacity: 1;
}

.time-menu-title {
  display: flex;
  width: 100%;
  height: 32px;
  box-sizing: border-box;
  border-bottom: 1px solid #e9eaec;
  justify-content: space-between;
  align-content: center;
  align-items: center;
  font-size: 12px;
  line-height: 31px;
  color: #495060;
}

.time-menu-title-operation-left {
  font-size: 14px;
  padding-left: 15px;
}

.time-menu-title-operation-left a:nth-child(1) {
  padding-right: 10px;
}

.time-menu-title-operation-right {
  font-size: 14px;
  padding-right: 15px;
}

.time-menu-title-operation-right a:nth-child(2) {
  padding-left: 10px;
}

.time-menu-title-operation-right a, .time-menu-title-operation-left a{
  transition: 300ms;
  color: #c1c3cf;
}

.time-menu-title-content a {
  color: #495060;
  transition: 300ms;
}

.time-menu-title-operation-right a:hover, .time-menu-title-operation-left a:hover, .time-menu-title-content a:hover{
  color: #719af3;
}

.week-list {
  display: flex;
  justify-content: space-around;
  align-content: center;
  align-items: center;
  padding: 10px 10px 0 10px;
  box-sizing: border-box;
}

.week-list span {
  font-size: 12px;
  line-height: 28px;
  color: #bbbec4;
}

.time-list {
  display: flex;
  justify-content: flex-start;
  align-content: center;
  align-items: center;
  flex-wrap: wrap;
  padding: 0 10px;
}

.time-list a {
  position: relative;
  display: inline-block;
  width: 28px;
  height: 28px;
  font-size: 12px;
  line-height: 24px;
  color: #495060;
  text-align: center;
  border-radius: 5px;
}

.time-list a em {
  display: inline-block;
  width: 24px;
  height: 24px;
  font-style: normal;
  margin: 2px 0 0 2px;
  border-radius: 5px;
}

.time-list .current-month:hover {
  background-color: #e1f0fe;
}

.time-list .no-current-month {
  color: #bbbec4;
}

.time-list .selected-day {
  color: #fff;
  background-color: #2d8cf0;
}

.current-day-icon {
  position: absolute;
  top: 3px;
  right: 3px;
  display: inline-block;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background-color: #2d8cf0;
}

.selected-current-day-icon {
  background-color: #fff;
}

.multiselect-leave-active, .multiselect-enter {
  opacity: 0;
  height: 0;
}
</style>

**Comment by BengBu-YueZhang** [comment]
[多选日期组件](https://github.com/BengBu-YueZhang/Check-the-date)

**Comment by BengBu-YueZhang** [comment]
有bug，请提

**Comment by SergioCrisostomo** [comment]
@BengBu-YueZhang thank you for making work that can help others!

(related: https://github.com/iview/iview/issues/1324)
