### ISSUE TITLE
ie10中有滚动条下transfer指令的相关问题

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview#2057]
早前ie10控制台报错
`[Vue warn]: Error in directive transfer-dom inserted hook: "TypeError: 无法获取未定义或 null 引用的属性“transfer”"`
（note：使用了transfer指令都会报错），经检查以及查找资料，得知是ie10不支持dateset导致（见图）
![default](https://user-images.githubusercontent.com/30425581/31368637-a03b2890-adb1-11e7-824b-49cc6c9801be.png)
采用网友提供的方法 #1599 sharpfeel 的解决方案
`
//兼容 transfer-dom.js中 使用了 dataset 的问题

if (window.HTMLElement) {
    if (Object.getOwnPropertyNames(HTMLElement.prototype).indexOf('dataset') === -1) {
        Object.defineProperty(HTMLElement.prototype, 'dataset', {
            get: function () {
                var attributes = this.attributes; //获取节点的所有属性
                var name = [],
                    value = []; //定义两个数组保存属性名和属性值
                var obj = {}; //定义一个空对象
                for (var i = 0; i < attributes.length; i++) { //遍历节点的所有属性
                    if (attributes[i].nodeName.slice(0, 5) == 'data-') { //如果属性名的前面5个字符符合"data-"
                        // 取出属性名的"data-"的后面的字符串放入name数组中
                        name.push(attributes[i].nodeName.slice(5));
                        //取出对应的属性值放入value数组中
                        value.push(attributes[i].nodeValue);
                    }
                }
                for (var j = 0; j < name.length; j++) { //遍历name和value数组
                    obj[name[j]] = value[j]; //将属性名和属性值保存到obj中
                }
                return obj; //返回对象
            }
        });
    }
}
`

使用后，控制台正常，但是有滚动条情况下，组件还是会出现偏移的情况（已使用transfer指令，并且只有ie出现）
![default](https://user-images.githubusercontent.com/30425581/31368815-8eb1bf8e-adb2-11e7-88aa-40871001c458.png)

现在直接导致在ie10中，使用transfer指令所有组件都可能偏移
我的天，怎么给领导交代
请问大神，这个有解决方案吗（急），谢谢

**Comment by icarusion** [comment]
未来不支持低版本ie

**Comment by longzhaobi** [comment]
想来想去，感觉还是ant design好！领导说必须完美兼容ie9以上，不知道emlementUi兼容怎么样。必须饿了么ui是一个团队，而iview是个人项目，估计问题要少点

**Comment by longzhaobi** [comment]
我刚刚看了我用那个代码虽然不报错了，带下拉的内容也是错位的，但我把body的overflow给隐藏后居然就正常了。

**Comment by gitzhangfugui** [comment]
@longzhaobi 低版本我也很抵触，但是领导非要支持，比如富文本，我们只能用KindEditor，bug一堆好久没人维护了，集成也比较困难。我觉得选择还是主要看公司技术栈，如果有能力可以考虑antd，毕竟还是比较成熟的。ele ui和iview相差不多，iview其实也很不错了，但是还是需要努力。

**Comment by gitzhangfugui** [comment]
@longzhaobi 你这个我还真没试过，我一般只要容器大小够（transfer的层），不使用transfer就行。只是有一些固定定位的tooltip类的，不跟着走，很烦人。

**Comment by longzhaobi** [comment]
@gitzhangfugui  iview永远是超不了antd的，虽然都开源，毕竟iview属于个人项目，只有模仿，探索不出什么东西的。估计也没时间去解决兼容问题，ie9完全不可用。

**Comment by limodou** [comment]
最低应该支持ie9，否则很多人可能会放弃。

**Comment by lison16** [comment]
兼容ie的教程有很多，如果有需求就自己做兼容处理
