### ISSUE TITLE
InputNumber无法被表单验证规则验证

### ISSUE THREAD

**Issue by hangzhouwjh** [iview/iview#2060]
![qq 20171010164226](https://user-images.githubusercontent.com/19630100/31377274-106bd768-adda-11e7-97eb-d6e87038f89d.png)
![qq 20171010164235](https://user-images.githubusercontent.com/19630100/31377275-10a26ec2-adda-11e7-8ef0-22d1d30d5ffa.png)
![qq 20171010164245](https://user-images.githubusercontent.com/19630100/31377278-10ec689c-adda-11e7-9fb6-679cf6a4d569.png)

**Comment by hangzhouwjh** [comment]
https://jsfiddle.net/29nnjygo/5/

**Comment by tvolitt** [comment]
![_20171011112723](https://user-images.githubusercontent.com/18397319/31420986-58c83400-ae77-11e7-8abb-32c816a6e4c0.png)

**Comment by hangzhouwjh** [comment]
多谢 tvolitt  知道咋回事了，原本想一个输入框多个验证规则，好像type都要写上的！

**Comment by tvolitt** [comment]
@hangzhouwjh 
type不写默认为'string'
这里是因为通过input-number组件输入的值为数字类型，所以无法通过type为'string'的验证
