### ISSUE TITLE
Radio的value为何要改为label呢?

### ISSUE THREAD

**Issue by rchlz** [iview/iview#2064]
2.0.0-rc.2的更新日志有一条：
Radio value 改为了 label，使用 v-model，废弃 checked。

为什么要将Radio的value改为label呢？

实际需要以下的这种情况，本来sex我是用0和1标识的，前端展现为男女，可这时sex取到的值也是男女
`<RadioGroup v-model="sex">
    <Radio label="男" value="1"></Radio>
    <Radio label="女" value="0"></Radio>
</RadioGroup>`

**Comment by chenxing890** [comment]
遇到同样的问题,  研究了一下,  正确的使用方法如下:
`
<RadioGroup v-model="sex"> 
     <Radio :label="1" >男</Radio> 
     <Radio :label="0" >女</Radio>
 </RadioGroup>
`
