### ISSUE TITLE
CheckboxGroup v-model 绑定了label属性，建议改成绑定value，大部分使用场景是label用作外显，value用作逻辑处理

### ISSUE THREAD

**Issue by shenopkss** [iview/iview#2065]
CheckboxGroup v-model 绑定了label属性，建议改成绑定value，大部分使用场景是label用作外显，value用作逻辑处理
感谢

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
