### ISSUE TITLE
bug，select多选情况下，选择值后，更改v-model双向绑定数组，多选标签没有清空

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview#2066]
可以看到，v-model值已清空了，但是标签对应的selectedMultiple还没有清空
![default](https://user-images.githubusercontent.com/30425581/31422488-950c4e98-ae80-11e7-928c-9ac75d1bcfbd.png)

**Comment by gitzhangfugui** [comment]
@iview-bot 
Sorry.
This is the bug code.
[Url](https://jsfiddle.net/47d78e8b/3/)

**Comment by fooke1** [comment]
我也遇到同样的问题，不知怎样解决的？

**Comment by gitzhangfugui** [comment]
@fooke1 this.$refs.select.selectedMultiple = [] 暂时可以手动清空该数组

**Comment by fooke1** [comment]
谢谢了。有用。
