### ISSUE TITLE
选择器组件 中会自动插入undefined

### ISSUE THREAD

**Issue by pskishere** [iview/iview#2081]
https://jsfiddle.net/yyrzhm46/

**Comment by sadenwang** [comment]
额，我刚刚升级到vue2.4.1也遇到这问题了

**Comment by grapewheel** [comment]
急！新版本我重编译了node_modules后也遇到了

**Comment by Yyyyp** [comment]
更新后也遇到了这个

**Comment by sadenwang** [comment]
我把vue和iview退回了版本，仍然有这个错，而且还有别的问题，啊啊啊啊啊啊啊

**Comment by erniu** [comment]
你们试试把Vue的版本回滚到2.5以前吧，经测试只有Vue2.5才会重现这个问题

**Comment by pollux2015** [comment]
我也遇到同样问题

**Comment by icarusion** [comment]
已知了，更新到 Vue 2.5 后的问题，下周将发布新版本解决，暂时先不要升级。

**Comment by SergioCrisostomo** [comment]
This is a bug in Vue.js, not iView.

related https://github.com/iview/iview/issues/2084

**Comment by Yyyyp** [comment]
vue和vue-template-compiler 都使用2.4.1版本的，暂时可以规避这个bug```

**Comment by sadenwang** [comment]
我发现不管退到哪个版本都还是这个问题，不知道怎么回事，已经退到 vue2.2.2，iview2.0.0，vue-template-compiler2.2.4，我最早正常页面的版本，没升级包，现在不升级重新下载包，就会遇到这个问题

**Comment by icarusion** [comment]
Vue 2.5.1 has released.
