### ISSUE TITLE
tabs中的tab-pane无法自动同步

### ISSUE THREAD

**Issue by grey-zeng** [iview/iview#2083]
示例 http://jsbin.com/posasatibi/edit?html,js,output

有个需求是能**动态**更改tabs中的tab-pane列表，但是发现tabs无法自动的同步tab-pane的变更。

初始状态显示两个tab：
![image](https://user-images.githubusercontent.com/10265042/31534992-c6ffb474-b02b-11e7-9553-51fe73ba40bc.png)

点击关闭按钮后，a应该隐藏，但a还是显示：
![image](https://user-images.githubusercontent.com/10265042/31535036-0301389e-b02c-11e7-93c6-40739688a58e.png)

目前我的解决方法是：`this.$nextTick(this.$refs.tabs.updateNav);`

希望后续可以优化下。

**Comment by icarusion** [comment]
fixed in #2100
