### ISSUE TITLE
vue 2.5 复合型输入框 出现undefined问题 - 有重现地址

### ISSUE THREAD

**Issue by chavyleung** [iview/iview#2084]
升级vue 2.5后出现，2.4没问题。
重现地址：https://codepen.io/chavyleung/pen/eGLNqR

**Comment by 634750802** [comment]
https://github.com/vuejs/vue/commit/1f84dd1c2488d12ef144d4b548b0e80647f9403c vue的bug，已经修复了

**Comment by icarusion** [comment]
Vue 2.5.1 has released
