### ISSUE TITLE
当需要动态维护FormItem时，改变表单项位置后，rules未能同步更新[官网Demo可重现]

### ISSUE THREAD

**Issue by h1orz** [iview/iview#2086]
以官网[Demo](https://www.iviewui.com/components/form#动态增减表单项)为例：
Git的链接好像打不好中文锚点，复制链接可访问：
```
https://www.iviewui.com/components/form#动态增减表单项
```

![tim20171013175738](https://user-images.githubusercontent.com/18734825/31541045-074686b6-b040-11e7-8078-f6231fe8f800.png)
在触发第二项错误提示后，删除第一项。
错误提示并没有更新为第一项，而是继续保持在了第二项上，此时应更新错误提示到第一项。
项目中遇到了同样的问题，验证官方Demo后得出一致结论。

**Comment by h1orz** [comment]
经过不断尝试，最终得出使用不同form将动态表单项和静态表单项分开的方法绕过去了。
本质上还是$ref.form对象中存储的rules未能和变化的form项同步，希望官方重视。

**Comment by skyame** [comment]
遇到的问题一样

**Comment by icarusion** [comment]
看了一下，问题是在于 v-for 里面的 prop 不对，是业务的问题。
https://jsfiddle.net/Aresn/vs05Ljgn/

**Comment by h1orz** [comment]
jsfiddle中使用如下方法隐藏了校验项，虽然可以从一定程度上缓解动态校验的问题。
```javascript
this.formDynamic.items[index].status = 0;
```
但是，如果使用数组splice方法，错误提示并未同步。
```javascript
this.formDynamic.items.splice(index, 1);
```
现象如下图所示：
![tim 20171108142047](https://user-images.githubusercontent.com/18734825/32534321-0f0aa1ac-c490-11e7-8e75-7f1fc52a73a3.png)

**Comment by icarusion** [comment]
所以需要你业务上自己维护好 prop 绑定的数据啊，你现在绑定 index，当然会变

**Comment by h1orz** [comment]
怪我没仔细验证，iView动态维护FormItem没有问题。
经过仔细验证，是我的Vue版本(2.2.6)太老了引起的，更新Vue版本后已解决。
官方Demo的逻辑没有问题。
提BUG的时候，刚好和我的问题表象相似，就直接提交了...😭

**Comment by waiaan** [comment]
> 怪我没仔细验证，iView动态维护FormItem没有问题。
> 经过仔细验证，是我的Vue版本(2.2.6)太老了引起的，更新Vue版本后已解决。
> 官方Demo的逻辑没有问题。
> 提BUG的时候，刚好和我的问题表象相似，就直接提交了...😭

请问你的问题是怎么解决的？
