### ISSUE TITLE
select 默认 ’undefined‘ bug 并且样式错位

### ISSUE THREAD

**Issue by luguoeryi** [iview/iview#2092]
``<Select style="width:200px">
        <Option value="beijing">北京市</Option>
        <Option value="shanghai" disabled>上海市</Option>
        <Option value="shenzhen">深圳市</Option>
    </Select>

**Comment by SergioCrisostomo** [comment]
Duplicate of https://github.com/iview/iview/issues/2084

**Comment by tt0226** [comment]
undefined 问题   直接把node_modules  删了  重新install 下  就好了
