### ISSUE TITLE
different colors (new feature)

### ISSUE THREAD

**Issue by StasB93R** [iview/iview#2095]
Hey, what i want to say is more of a suggestion of a new feature rather than an issue.
Would be nice to be able to control colors for each component. Like for navigation components, its not enough to have just 3 colors and if u want to change it, you have to go inside of repo and add new colors manually.  Another thing would be good is to be able to resize the borders, like to round them or sharpen them depending on what you need. 
Just curious to get a feedback from you.

**Comment by icarusion** [comment]
As a set of front-end UI specifications, iView has its own features, mainly using primary color in color usage.
