### ISSUE TITLE
关于Table控件各种UI问题，第二弹

### ISSUE THREAD

**Issue by kiddkyd1412** [iview/iview#2096]
https://jsfiddle.net/op9x99ar/1/

关于宽度不足，表头肥大，列丢失等问题，demo里已经写了详细描述。

-------------
这个问题之前也问过，但是你说你试过没问题，我就纳闷了。
请使用这个新的demo网站再试一遍。

另外其他朋友如果打开demo网站，能看到bug的话，希望打个call。难道只是我的chrome有问题？

**Comment by zhdwwf** [comment]
chrome 61版本下存在问题，如果窗口resize后，列丢失问题会正常
![image](https://user-images.githubusercontent.com/564279/31590995-ebdcceb2-b24c-11e7-934d-0ac490d38043.png)

**Comment by angelzou** [comment]
![image](https://user-images.githubusercontent.com/3369173/31610577-1ea04af0-b2ab-11e7-803c-49f6d73ccf79.png)
因为这里将最后一个列的col的宽度设置为父级了scrollerbar的宽度导致的，我将table-head.vue文件中的第四行，true改为false就好了。iview成员看看怎么改。
![image](https://user-images.githubusercontent.com/3369173/31610786-f684cdf6-b2ab-11e7-97b8-ea5718f1b719.png)

**Comment by agileago** [comment]
@angelzou  刚好手头一个要上线的项目，在本地一直都是用的最新版的chrome测试没问题，谁知道测试那边测出来table这个表头的问题，果然设置成false就行了

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
