### ISSUE TITLE
Select 控件 multiple bug

### ISSUE THREAD

**Issue by viewweiwu** [iview/iview#2098]
当存在两个 Select 控件
一个是 multiple，一个非 multiple
切换到非 multiple 时，label 不该被显示。
切来切去现象很奇怪...
在线示例： [https://codepen.io/viewweiwu/pen/JrmWLP?editors=1010](url)

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
