### ISSUE TITLE
无法动态删除 tab-panel

### ISSUE THREAD

**Issue by dear-lizhihua** [iview/iview#2100]
只能动态新增 tab-panel，无法动态删除 tab-panel
示例
https://jsfiddle.net/hbyLnbbn/1/

**Comment by tristan-tsl** [comment]
maybe i think i temp deal with this problem,
diff:

html/vue-template:

                    <Tabs 
                          closable
                          :before-remove='beforeRemove'
                    >


js:


            beforeRemove(index) {
                const component = this;
                return new Promise(function (resolve, reject) {
                    let real_index = 0;
                    let index_increment = index;
                    component._data.tab_pane_cur = -1;
                    for (const index in component._data.tab_pane) {
                        const item = component._data.tab_pane[index];
                        if (item['visible']) {
                            if (0 == index_increment) {
                                real_index = index;
                            } else if (-1 == index_increment) {
                                component._data.tab_pane_cur = parseInt(index);
                                break;
                            }
                            index_increment--;
                            continue;
                        }
                    }
                    component._data.tab_pane[real_index].visible = false;
                    reject(index);
                })
            },




            OnClickDirectory(service_type, directory) {
                const _id = directory["id"];
                const name = directory["name"];
                // set breadcrumb
                const breadcrumb_list = [name];
                this._data.directory.cur_id = _id;
                let parent = directory["parent"];
                while (parent) {
                    breadcrumb_list.push(parent["name"]);
                    if (parent["parent"]) parent = parent["parent"];
                    else parent = null;
                }
                breadcrumb_list.pop();
                this._data.breadcrumb.list = breadcrumb_list.reverse();

                const cur_service_type = this._data.menu_active_name;
                let label = name;
                const tab_panel_id = cur_service_type + _id;
                this._data.tab_panel_cur_id = tab_panel_id;
                for (const index in this._data.tab_pane) {
                    const item = this._data.tab_pane[index];
                    if (item['name'] == tab_panel_id) {
                        // is_not_exist = false;
                        this._data.tab_pane_cur = parseInt(index);
                        this._data.tab_pane[index].visible = true;
                        return;
                    }
                    if (label == item['label']) {
                        label = breadcrumb_list.join(" / ");
                    }
                }
                  let icon = 'md-albums';
                  if (cur_service_type == 'logic') {
                      icon = 'md-cog';
                  }
                  this._data.tab_pane.push({
                      'type': cur_service_type,
                      'name': tab_panel_id,
                      'directory_id': _id,
                      'breadcrumb_list': breadcrumb_list,
                      'label': label,
                      'visible': true,
                      'icon': icon,
                  });
                  this._data.tab_pane_cur = this._data.tab_pane.length - 1;
            },
