### ISSUE TITLE
希望iview的table可以支持多级表头

### ISSUE THREAD

**Issue by YuuyaRin** [iview/iview#2101]
希望iview的table可以支持多级表头
比如几个子表头上方有一个总的分类表头
不知道用现有的iview的table有没有办法实现

**Comment by melon** [comment]
同急需该功能，请求支持

**Comment by sadenwang** [comment]
支持一下，虽然现在也可以实现多表头，但很麻烦，希望增加导出EXCEL表头和表尾的导出excel

**Comment by icarusion** [comment]
#676
