### ISSUE TITLE
table设置fixed后，滚动列表后出现行错位

### ISSUE THREAD

**Issue by 359257840** [iview/iview#2102]
![image](https://user-images.githubusercontent.com/11308580/31595568-4a7f55f8-b26f-11e7-98d9-6ddd2072955d.png)

**Comment by yangdan8** [comment]
这个问题提了很久了,一直没有解决

**Comment by xiao6zi** [comment]
[https://jsfiddle.net/xiao6zi/1L6vasve/#&togetherjs=wjIVpDDK3I](https://jsfiddle.net/xiao6zi/1L6vasve/#&togetherjs=wjIVpDDK3I)

The official website of the example to remove the width of the property
官网的例子 去掉width 属性

**Comment by songning0605** [comment]
把border设为false，每一列都设置固定宽度，并且需要适当的设置scroll={{ x: 2000 }}中x的宽度，可以解决这个问题。[![2018-05-20_170506.png](https://s31.postimg.cc/tahlc4917/2018-05-20_170506.png)](https://postimg.cc/image/80tz19sqf/)

**Comment by fangchaolong** [comment]
在mac下还是有问题

**Comment by show110695** [comment]
> 
设置scroll={{ x: 2000 }}中x的宽度是什么意思啊
