### ISSUE TITLE
Dropdown组件连续点击多次，会报错

### ISSUE THREAD

**Issue by hank2718** [iview/iview#2103]
报错信息
![image](https://user-images.githubusercontent.com/7368299/31596965-63609514-b20b-11e7-98c5-eca1e3bbc356.png)

**Comment by hank2718** [comment]
代码：
        <Dropdown trigger="click">
          <a href="javascript:void(0)">
            <Icon :type="item.icon"></Icon>{{ item.label }}
          </a>
          <DropdownMenu slot="list" v-if="item.children">
            <DropdownItem v-for="sub in item.children" :key="sub.value" @click.native="changeStar(item)">{{ sub.label }}</DropdownItem>
          </DropdownMenu>
        </Dropdown>

**Comment by hank2718** [comment]
官网例子也有个问题  连续点击多次弹出菜单位置会变
![image](https://user-images.githubusercontent.com/7368299/31597080-17d6ed5e-b20c-11e7-900e-ec576bb70a5c.png)
![image](https://user-images.githubusercontent.com/7368299/31597090-213eecf2-b20c-11e7-961d-e0b9887e3513.png)

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。

**Comment by hejiayuan** [comment]
遇到相同问题
