### ISSUE TITLE
 [Bug Report] 在Modal中使用Form表单,Form表单中有select组件造成下拉样式错乱

### ISSUE THREAD

**Issue by javady** [iview/iview#2104]
iView 版本号

2.4.0

操作系统/浏览器 版本号

Chrome 版本 61.0.3163.100（正式版本)

Vue 版本号

2.4.2

能够复现问题的在线示例（bug 相关不提供在线示例将直接 close
在线示例:https://jsfiddle.net/rad7rL2u/

问题现象，以及你期望的结果是怎样的?
之前的issues提到过[#1099](https://github.com/iview/iview/issues/1099),
是老版本没有这样的问题?还是修复过了在新版本又重现了?

**Comment by icarusion** [comment]
Use `transfer`, and read doc **carefully**.
