### ISSUE TITLE
checkboxGroup 发现的两个问题问题

### ISSUE THREAD

**Issue by anyongchao** [iview/iview#2105]
CheckboxGroup v-model 绑定了label属性，建议改成绑定value，大部分使用场景是label用作外显，value用作逻辑处理
上面这个问题，我看到又人已经提过了，但是没有回应，
第二个问题：
当checkboxGroup有其中一个或者多个为disabled选项的时候，在做全选的时候将把不能选中的去掉。否则在有disabled选项的时候，全选就会有bug

**Comment by icarusion** [comment]
1. 文档写的很清楚，不多解释了。
2. iView 本身并没有全选的功能，逻辑是业务控制的。
