### ISSUE TITLE
csv有bug

### ISSUE THREAD

**Issue by RyomaZheng** [iview/iview#2109]
当table数据里面有空格或者英文逗号的时候，导出来的数据会变了，求A神修一哈

**Comment by SergioCrisostomo** [comment]
@RyomaZheng can you please add a example to your problem?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by RyomaZheng** [comment]
![image](https://user-images.githubusercontent.com/31764370/31618093-8f258282-b2c3-11e7-9f9a-8abb73bfd1fc.png)
![image](https://user-images.githubusercontent.com/31764370/31618105-97ef3606-b2c3-11e7-9ced-4dc8ce3edc86.png)

**Comment by SergioCrisostomo** [comment]
@RyomaZheng can you share that table data so we can understand the problem better?

**Comment by RyomaZheng** [comment]
columns1: [{
          title: '姓名',
          key: 'name'
        }, {
          title: '年龄',
          key: 'age'
        }, {
          title: '地址',
          key: 'address'
        }],
        data1: [{
          name: '王小明',
          age: 18,
          address: '北京市朝\n阳区芍药居'
        }, {
          name: '张小刚',
          age: 25,
          address: '北京市海,淀区西二旗'
        }, {
          name: '李小红',
          age: 30,
          address: '上海市浦东\r新区世纪大道'
        }, {
          name: '周小伟',
          age: 26,
          address: '深圳市南山区深南大道'
        }]

**Comment by RyomaZheng** [comment]
如果数据是这样的话，导出csv是有问题的=-=

**Comment by SergioCrisostomo** [comment]
@RyomaZheng thank you!
https://jsfiddle.net/Sergio_fiddle/4h20xswk/
