### ISSUE TITLE
i-select 组件设置filterable之后，设置默认值不能正确显示

### ISSUE THREAD

**Issue by GITleonine1989** [iview/iview#211]
### iView 版本号
0.9.15

### 操作系统/浏览器 版本号
Win10/chrome 55

### Vue 版本号
1.0.26

### 能够复现问题的在线示例
http://jsbin.com/vepicemari/edit?html,css,js,output

### 复现步骤
定义一个iselect组件，添加 filterable clearable  两个属性，
设置 默认值 ，结果select 组件不能正常显示出默认选中的值，点击一下之后又能正确显示
### 问题现象，以及你期望的结果是怎样的?
能够正确的显示出我设置的默认值
### 你估计可能的原因是什么（选填）？
不加filterable 就正常，加了就有问题，问题应该在这

**Comment by icarusion** [comment]
Thx.

**Comment by GITleonine1989** [comment]
神速啊，666
