### ISSUE TITLE
Page 组件与 Table 组件合并

### ISSUE THREAD

**Issue by lauber00** [iview/iview#2110]
现在Page组件和Table组件的使用比较麻烦，建议把Page组件合并到Table组件里面，可以传入pageSize、total、currentPage等值实现表格的分页。
谢谢。

**Comment by Licoy** [comment]
为什么要合并呢？我认为单独组合是比较灵活方便的

**Comment by lauber00** [comment]
@Licoy 因为做项目的时候，有很多地方都用到了Table组件，每次都要写一遍分页、翻页的逻辑，有很多重复的代码。建议Page组件灵活的独立存在，但是Table组件中加入分页的功能，避免写很多重复代码。

**Comment by SoyMeng** [comment]
@lauber00 这个建议自己来创建一个组件，官方只提供基础功能是没问题的

**Comment by icarusion** [comment]
暂无此计划。
