### ISSUE TITLE
可收起展开的侧边导航

### ISSUE THREAD

**Issue by neohuan176** [iview/iview#2112]
布局那里：可收起的侧边导航栏，收起的时候，如果有二级菜单，再打开，二级菜单的布局混乱。希望可以解决一下。

**Comment by SergioCrisostomo** [comment]
@neohuan176 could you provide a example of the behaviour your have?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by icarusion** [comment]
Layout 只是建议，具体要自己去写。
