### ISSUE TITLE
[Feature Request] tag标签可选择

### ISSUE THREAD

**Issue by zhougangnj** [iview/iview#2115]
[Feature Request] tag标签可选择，类似于
https://ant.design/components/tag-cn/
Tag.CheckableTag 功能

**Comment by daiyanze** [comment]
刚刚推上去一个branch，基本能达到antd那样的效果。

**Comment by icarusion** [comment]
#2124

**Comment by xythree** [comment]
https://github.com/iview/iview/pull/2124
无语，触发事件给的是on-check，源码里却是on-change,文档里却什么也没有提
