### ISSUE TITLE
建议：希望能够提供Select和Cascader的dropdown样式API

### ISSUE THREAD

**Issue by daiyanze** [iview/iview#2117]
目前下拉菜单的最小宽度为100px，在使用日语文字作为菜单项目的时候出现“文字覆盖尖头符号”的问题，
建议把下拉菜单的样式API（比如，icon(箭头图标) width 什么的）也抛出来
![2017-10-17 19 32 25](https://user-images.githubusercontent.com/14920529/31660912-f24eaad6-b373-11e7-9ea9-794c96bea295.png)

谢谢

**Comment by icarusion** [comment]
Select 的宽度是随父级的，Cascader 的宽度是设置过 `min-width` 的，所以会根据文本自动扩充，看你的截图，像是自己加了居中导致的吧。建议提交在线示例。
