### ISSUE TITLE
 [Feature Request] <Input> spellcheck 无法关闭

### ISSUE THREAD

**Issue by zytim** [iview/iview#2118]
Input应可配置拼写检查，现在是默认打开

**Comment by SergioCrisostomo** [comment]
@zytim if you can would be great to send a pull request for this.

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。

**Comment by SergioCrisostomo** [comment]
@zytim a fix for this was released today in `2.7.0` 🎉

**Comment by zytim** [comment]
@SergioCrisostomo thank u
