### ISSUE TITLE
4个建议

### ISSUE THREAD

**Issue by 188007803** [iview/iview#2121]
1、能不能在源码中给v-for 都加上 key，或者给一个key的prop，让用户将key传进去，不然有时会出错。
我简单查了一下，源码中至少有十几处都需要加 key。
![vfor](https://user-images.githubusercontent.com/10063364/31697907-f1858bf0-b3ec-11e7-9e7d-1bcc9def3e32.png)

2、AutoComplete 组件在我打汉字的时候，每敲一个键就开始搜索了，这不对，因为我敲五笔，在汉字打出来之前，搜索敲入的字母毫无意义，而Select组件的搜索就没有这样的问题。

3、级联选择器，能否加上多选功能，就像Select组件支持多选一样，这个很有用的，目前我是看iview的源码自己实现了一个，但还是官方支持最好。
![gif](https://user-images.githubusercontent.com/10063364/31698451-4c2c6a9e-b3f0-11e7-9a09-a0db2f1f8c87.gif)

4、Tree组件，能否加上一个控制节点显示的属性，我目前是在源码 (iview2.4)上作一丁点改动来实现。
   修改31207行
    visible": _vm.data.expand 改为 visible": _vm.data.expand &&  item.show !== false
   修改31231行
   "visible": "" 改为 "visible": item.show !== false

**Comment by SergioCrisostomo** [comment]
@188007803 hi! Can you provide examples for these issues?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by daiyanze** [comment]
能否把 3 级联选择器的代码提交上来让我们讨论学习一下

**Comment by 188007803** [comment]
我放到我的github仓库里了，你下载看看。

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
