### ISSUE TITLE
360安全浏览器极速模式下datepicker  type=daterange 时 无法选择

### ISSUE THREAD

**Issue by maysoft** [iview/iview#2122]
360安全浏览器9.1.0.356  极速模式 内核版本：55
无论是daterange 还是datetimerange 都无法选择范围，官网例子也是，切换edge浏览器正常

**Comment by SergioCrisostomo** [comment]
@maysoft can you provide a example of the problem? 

 使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by hjw0968** [comment]
chrome 57 也是无法选择,更新前正常

**Comment by zsedcbm** [comment]
试一下将vue版本改为 2.4.4 ,我更换版本后可用,具体bug不知道怎么调试.

**Comment by maysoft** [comment]
"dependencies": {
    "axios": "^0.15.3",
    "clipboard": "^1.5.12",
    "countup": "^1.8.2",
    "echarts": "^3.7.2",
    "html2canvas": "^0.5.0-beta4",
    "iview": "^2.5.0-beta.1",
    "js-cookie": "^2.1.3",
    "rasterizehtml": "^1.2.4",
    "simplemde": "^1.11.2",
    "sortablejs": "^1.6.1",
    "tinymce": "^4.7.1",
    "vue": "^2.5.2",
    "vue-i18n": "^5.0.3",
    "vue-router": "^2.8.1",
    "vuex": "^2.5.0"
  },

**Comment by maysoft** [comment]
我是2.5.2的 还是无法选择

**Comment by zsedcbm** [comment]
我的意思是改成2.4 版本的
2.5版本的无法选择.
你更换一下试试看

**Comment by icarusion** [comment]
@maysoft 升级到61吧，问了一圈没人用55的。

**Comment by maysoft** [comment]
360浏览器最新版只到55。。。

**Comment by qq986063761** [comment]
我认为这个问题确实比较严重，官网本身vue和iview版本是匹配的在360急速也有这个选中不是很不灵活的bug

**Comment by maysoft** [comment]
那现在没有办法了，vue说是iview问题，iview说让你升内核版本，可360浏览器最新版本内核只到55，不知道其他国内浏览器内核是多少，但是目前来看360浏览器在国内用户还是不少的，为了能正常使用，现在只能按你说的降低vue版本到2.4.4了。

**Comment by jerexyz** [comment]
暂时只能将vue 降级为2.4.4了

**Comment by SergioCrisostomo** [comment]
Is this still a problem with Vue 2.5.2?

**Comment by xovel** [comment]
QQ浏览器路过，一样的问题。Chrome 内核比 360 的还要古老一些。53的。做的产品的用户有很大一部分人用的就是QQ浏览器或者360浏览器，没有办法啊。

**Comment by ihuguowei** [comment]
该问题还是挺影响公司内部产品的，希望我们自身能够去解决掉。

**Comment by icarusion** [comment]
@ihuguowei 暂时只能对 Vue 版本进行降级到 2.4.x，问题是由 Vue 升级造成的，具体原因还得调研

**Comment by ihuguowei** [comment]
@icarusion 加油，也可以给思路我们帮忙排查，辛苦了。
