### ISSUE TITLE
[bug] Modal组件没有onOpen事件，我认为不科学

### ISSUE THREAD

**Issue by pandora-y** [iview/iview#2123]
我有一个界面，有2个按钮，一个按钮点击打开新增图片界面。一个按钮点击，打开查询图片界面。

没有onOpen事件，我进入主界面，就加载了dialog窗口里的查询方法。

而且新增图片后，我还需要手动调用查询界面的查询方法。

**Comment by SergioCrisostomo** [comment]
Can you provide a example of the problem?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by icarusion** [comment]
You can watch `value` of Modal component.
