### ISSUE TITLE
date-picker校验为必填的时候校验失败后，再次添写后失焦不会校验

### ISSUE THREAD

**Issue by zlwtp** [iview/iview#2125]
当点了提交后，校验失败再填写失焦后校验失败不消失
例子
https://jsfiddle.net/tonyWe/56uovjo8/6/

**Comment by icarusion** [comment]
https://github.com/iview/iview/blob/7053de4e78bb0cbf6371ec0969c4523b91f5e92b/src/components/input/input.vue#L193-L195

DatePicker 不支持 blur，只能用 change
