### ISSUE TITLE
Table组件的on-select-all事件触发问题

### ISSUE THREAD

**Issue by ChiHai-Chuck** [iview/iview#2127]
https://jsfiddle.net/vr4L24j0/

Table组件有一个on-select-all事件，用于在多选模式下，点击全选按钮时触发，可是这个事件只有在点击全选是全中全部的时候才会触发，取消全部选中时却不会触发。
我觉得应该提供一个点击全选按钮是取消全部选中时的事件，或者只要点击全选按钮就触发on-select-all事件。

**Comment by kuailingmin** [comment]
我也需要这样的问题，iview取消全选怎么处理呢？请开发团队能回答一下吗？

**Comment by cbyniiaii** [comment]
where is the documentation for explained. I can't find it.
