### ISSUE TITLE
Tree动态修改Data的children时，视图中children的父级不能及时更新选中状态，必须进行点击之后才会再次渲染。

### ISSUE THREAD

**Issue by lgl1993** [iview/iview#2128]

**Comment by SergioCrisostomo** [comment]
Hi @lgl1993!
I'm not sure I understand your problem. Can you provide a example?

使用下面的在线链接可以快速创建示例 
https://jsfiddle.net/yyrzhm46/ 

Please try also https://github.com/iview/iview/pull/2090 and see if that fix solves your problem.
