### ISSUE TITLE
iview range 不支持移动滑动？

### ISSUE THREAD

**Issue by qzmly100** [iview/iview#2129]
可以修改源码吗？

**Comment by SergioCrisostomo** [comment]
@qzmly100 can you provide a example of the problem? (Google translate makes your question unclear to me not Chinese speaker)

**Comment by daiyanze** [comment]
@qzmly100 你Fork到自己的仓库里，然后就可以修改了。如果有什么好的想法和功能，发个pull request过来就行。

**Comment by icarusion** [comment]
@qzmly100 iView 的组件暂时不会对移动端事件做处理，它的定位还是在 PC 上。

**Comment by qzmly100** [comment]
ok,Thanks you!
