### ISSUE TITLE
iview 官方网站上的code区代码高亮怎么实现的？

### ISSUE THREAD

**Issue by MrNsfocus** [iview/iview#2131]

**Comment by SergioCrisostomo** [comment]
@MrNsfocus [check highlightjs here ](https://github.com/iview/iview-doc/blob/master/package.json#L21) and https://github.com/iview/iview-doc/blob/97d48683a0b09b01170a161f9dfd0d61cea536c1/src/components/code.vue#L104-L109.

If you need more help I suggest you check StackOverflow.

**Comment by MrNsfocus** [comment]
thank you

**Comment by k8scat** [comment]
Links lost~ 404~
