### ISSUE TITLE
树形控件Tree建议增加节点右键属性

### ISSUE THREAD

**Issue by Licoy** [iview/iview#2133]
给每个节点设置右键属性，弹出小菜单然后可以“删除节点”，“增加子节点”，并且其title可以自定义。

**Comment by xiongdada233** [comment]
希望tree添加右键事件

**Comment by daiyanze** [comment]
添加右键事件会覆盖BOM原有API，可以考虑在项目上绑定双击菜单或者在项目右侧追加下拉菜单。
