### ISSUE TITLE
Select 

### ISSUE THREAD

**Issue by tt0226** [iview/iview#2134]
Select  下拉选择 会多个undefied

**Comment by daiyanze** [comment]
估计是你数据里有个undefined。debug一下，应该能找到

**Comment by tt0226** [comment]
好的谢谢

**Comment by tt0226** [comment]
没有，完全把iview 重新试了下 还是在
![image](https://user-images.githubusercontent.com/21094920/31758760-56cc3e7e-b4e1-11e7-9f0f-90e09de33f33.png)

**Comment by daiyanze** [comment]
能把代码发上来让我帮你看看吗

**Comment by tt0226** [comment]
![image](https://user-images.githubusercontent.com/21094920/31759522-3ef90658-b4e4-11e7-8adc-b3c0c8d31e0c.png)
用的就是官网的一样的代码

**Comment by daiyanze** [comment]
我测试了一下，结果很正常。所以我一直在怀疑你的数据可能存在问题，尤其途中可能不小心发生变化或者sysName不存在等等。你debug一下value="jszx"的item数据里面是否有sysName这个prop。
你那个index如果不用的话可以不用写在里面，先看看把index去掉之后会不会好点。

**Comment by tt0226** [comment]
谢谢你  不过 我把数据写成死的还是有  ，哈哈
![image](https://user-images.githubusercontent.com/21094920/31762123-d331ff48-b4ec-11e7-8ce3-acae63814b59.png)
![image](https://user-images.githubusercontent.com/21094920/31762160-ee45f83e-b4ec-11e7-859c-825ac089566d.png)

**Comment by tt0226** [comment]
有的电脑就没问题

**Comment by daiyanze** [comment]
天气不好，那台电脑可能要罢工

**Comment by tt0226** [comment]
哈哈

**Comment by tt0226** [comment]
解决了  吧node_modules  删了 重新install 一下

**Comment by icarusion** [comment]
update Vue to `2.5.2`
