### ISSUE TITLE
新增的scroll控件滚动到底部或顶部时无法触发加载事件

### ISSUE THREAD

**Issue by NothinkingGao** [iview/iview#2135]
打开iview官网就有，本地也有
![default](https://user-images.githubusercontent.com/3362951/31758000-330b5a40-b4de-11e7-97dc-f7e1f339140e.png)

**Comment by SergioCrisostomo** [comment]
@NothinkingGao thank you for reporting this. What browser are you using?

**Comment by SoyMeng** [comment]
chrome 62.0.3202.62
访问官网[https://www.iviewui.com/components/scroll](https://www.iviewui.com/components/scroll)
无法看到效果

**Comment by daiyanze** [comment]
的确，火狐浏览器上有这个问题。。。

**Comment by NothinkingGao** [comment]
@SergioCrisostomo firefox,the question same with chrome

**Comment by SergioCrisostomo** [comment]
Thank you guys! The `event` was missing. Added a PR for it now.

**Comment by NothinkingGao** [comment]
@SergioCrisostomo  thank you

**Comment by dayORday** [comment]
@SergioCrisostomo  滚动组件还是不能使用？官网上也不能使用？

**Comment by dayORday** [comment]
@SergioCrisostomo  可以使用,是我使用方式不对,我以为是操作滚动条。

**Comment by NARUTOne** [comment]
特难用，不灵敏

**Comment by NARUTOne** [comment]
win10  chrome67
