### ISSUE TITLE
full-screen-loading的功能

### ISSUE THREAD

**Issue by rendq** [iview/iview#2139]
iView目前的LoadingBar还不能满足许多需求，是否能增加full-screen-loading的功能，这样能保证加载的过程中，用户不能去操作页面上的组件，最大程度地保证数据能够一致。

**Comment by ihuguowei** [comment]
这简单的需求自己实现好了。

**Comment by icarusion** [comment]
`Spin` 组件有 `$Spin` 的用法

**Comment by rendq** [comment]
@icarusion 有线程的demo么？参考下！

**Comment by rendq** [comment]
@ihuguowei 主要考虑到代码规范问题，尽量用公共组件。

**Comment by rendq** [comment]
@icarusion 刚才看了2.4.0里面支持$Spin,我从2.0升级上来会不会有兼容性问题。
