### ISSUE TITLE
Table的固定列高度在没数据情况下高度错误问题

### ISSUE THREAD

**Issue by dunizb** [iview/iview#214]
### iView 版本号
0.9.15

### 操作系统/浏览器 版本号
Chrome 54

### Vue 版本号
1.0.21

### 能够复现问题的在线示例
[示例（最大化查看）](http://runjs.cn/code/pu38trd6)

### 在没有数据时，设置了固定列`fixed: 'left',width: 90`，固定列高度计算错误
![图示](http://upload-images.jianshu.io/upload_images/68937-7e777134653bd56b.png?imageMogr2/auto-orient/strip%7CimageView2/2)

### 你估计可能的原因是什么（选填）？
CSS浮动问题，浮动后脱离原来的文档流

**Comment by icarusion** [comment]
请提供在线示例

**Comment by dunizb** [comment]
@icarusion http://runjs.cn/code/pu38trd6

**Comment by rijn** [comment]
unfixed element white-space的影响
