### ISSUE TITLE
Customize Theme Not Working

### ISSUE THREAD

**Issue by gijo-varghese** [iview/iview#2147]
I was trying to customize the variables of iview using this guide: https://www.iviewui.com/docs/guide/theme-en (by overriding variables). I've followed the steps correctly, but it's giving me an error:
```
ERROR  Failed to compile with 1 errors                                 09:20:38

 error  in ./my-theme/index.less

Module build failed: 

@import "./animation/index";
@import "./components/index";
^
Can't resolve './components/index' in '/var/workspace/tuxedo/node_modules/iview/src/styles'
      in /var/workspace/tuxedo/node_modules/iview/src/styles/index.less (line 5, column 0)

 @ ./my-theme/index.less 4:14-135 13:3-17:5 14:22-143
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

Right now I'm using the 'By Tool' method. It's working fine. But the first method is easy to work with.

Again, thanks a lot for such an amazing library :+1:

**Comment by Ele-Cat** [comment]
I try to use the other issues's answer, but it's still not working, and I have to use theme tool to modification the theme.

**Comment by icarusion** [comment]
Did you setting `less` in your webpack options?

**Comment by icarusion** [comment]
You can watch this setting https://github.com/iview/iview-project/blob/2.0/webpack.base.config.js

**Comment by Ele-Cat** [comment]
I can write 'less grammar' in my project, but I can't use [@import '~iview/src/styles/index.less';], when I import this in my project, boom. My head also boom. And I saw your setting just now, tell the truth,I can't understand it.

**Comment by icarusion** [comment]
maybe you can use `iview-project` instead :)

**Comment by gijo-varghese** [comment]
@icarusion tried that webpack config file. Its giving me the following errors:

```
These relative modules were not found:

* ./src/vendors in multi ./build/dev-client ./src/vendors
* ./App in ./src/main.js
* ../my-theme/index.less in ./src/main.js
> Listening at http://localhost:8081
```

**Comment by hefengxian** [comment]
Hi everyone, I think i found solution, this error because of `iview` has omitted `.less` extension. so we can change webpack config, please locate `webpack.base.conf.js` then found line
```js
// ...
  resolve: {
    // add .less
    extensions: ['.js', '.vue', '.json', '.less'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src')
    }
  },
// ...
```
and add `.less` then compile will success.

**Comment by Ele-Cat** [comment]
@hefengxian Hi, Brother, is there has git address can refer to?thx

**Comment by hefengxian** [comment]
@Ele-Cat I build a test repository for you, I'm use vue-cli initialize the project. you can clone the repository then follow the readme.md to test it.

I was modified this line [webpack.base.conf.js#L23](https://github.com/hefengxian/iview-test/blob/master/build/webpack.base.conf.js#L23). then I'm change the primary color to `#58b956` and i got this 
![image](https://user-images.githubusercontent.com/4338497/31921179-74859cfe-b8a0-11e7-900d-4d725d637187.png)

**Comment by Ele-Cat** [comment]
@hefengxian wow, it's works well, thx so much, wish you all the best with your work, thx again.

**Comment by hefengxian** [comment]
@Ele-Cat :smirk:

**Comment by Ele-Cat** [comment]
@hefengxian 吓，被发现了[冷汗脸]

**Comment by gijo-varghese** [comment]
@hefengxian Thanks a lot. Its now working. Adding 'less' to webpack didn't solve the problem. I was using the vue-cli to create the project. Here is the solution:

1) Import the less file to `main.js` as per the documentation
2) Add `.less` to the extensions in `webpack.base.conf.js`
3) Install less loader using: `npm install --save-dev less-loader less`
