### ISSUE TITLE
表格对象  @on-expand 方法返回的对象没有__ob__对象

### ISSUE THREAD

**Issue by luoruiqing** [iview/iview#2150]
表格对象  @on-expand 方法会返回俩个参数 一个row(行对象) 一个status(表示扩展开关状态).
但这个row对象是没有__ob__对象的 所以我不能获得数据的双向绑定,例如我要表格内新增一行的情况,数据不能更新上去. 
场景: 扩展插件内添加一个文本框用来修改任意一个字段的内容
实际情况: 表格展现的数据确实会根据变化而修改,但是当我通过on-expand 指向的方法来获得更新后的数据时候,该对象就会脱离绑定,而且返回的对象值是插入时候的初始值,并不会返回发生改变后的对象,这样我也不能通过循环data9 来找到这个对象.即便这个对象是我在有变量引用的情况下,也不会发生变化.
![image](https://user-images.githubusercontent.com/10202760/31805196-9a632330-b524-11e7-9b9f-e40b1207604e.png)
![image](https://user-images.githubusercontent.com/10202760/31805200-a4cc8db6-b524-11e7-8fdd-c03f95cbe2cb.png)

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
