### ISSUE TITLE
 table中i-select下拉框宽度不正确 和 i-select model绑定数组，选择器选择后，table前单（多）选取消问题

### ISSUE THREAD

**Issue by kilng** [iview/iview#216]
iView 版本号

0.9.15

操作系统/浏览器 版本号

WIN10/Chrome 55

Vue 版本号

1.0.26

能够复现问题的在线示例

http://codepen.io/bruto/pen/YNpwpb

复现步骤

table中使用i-select，下拉框宽度错误。

table选单选或多选，再i-select选择，table单多选取消

问题现象，以及你期望的结果是怎样的?

你估计可能的原因是什么（选填）？

**Comment by icarusion** [comment]
已经解决，查看#188

**Comment by kilng** [comment]
@icarusion  i-select :mode.syncl绑定的是数组，table多选全部选中，select选择后，选中的会取消，好像是刷新了，我的示例里也有这个问题。
