### ISSUE TITLE
Modal 1里面再调用Modal2， modal2会被modal1遮挡

### ISSUE THREAD

**Issue by TonyLuo** [iview/iview#2160]
Modal 1里面再调用Modal2， modal2会被modal1遮挡着不出现
https://jsfiddle.net/yyrzhm46/41/

**Comment by icarusion** [comment]
Modal 放置位置不对。

**Comment by zhougangnj** [comment]
楼主的这种场景还是有的，如第2对话框在另外的一个组件里，这个组件又只能放到第1对话框里面
这种情况不知道应该怎么处理，目前我们遇到这种情况，只能把组件拆出来做或者用全局对话框

**Comment by TonyLuo** [comment]
Modal嵌套的场景不是很常见吗？比如说，在打开的Modal里，再打开一个modal去显示显示图片，这样图片就被第一个modal挡住了

**Comment by icarusion** [comment]
Modal 放置要同级，后面的会覆盖签名, like
```
<Modal v-model="modal1"></Modal>
<Modal v-model="modal2"></Modal>
<Modal v-model="modal3"></Modal>
```

**Comment by asd8510678** [comment]
同样遇到这样的问题

**Comment by TonyLuo** [comment]
Modal嵌套的场景还是比较常见的。
modal都要同级，这样会限制了组件的封装，有些组件要暴露调用modal的接口，违反了低耦合高内聚的设计原则。
比如@zhougangnj 提到的例子，本来modal应该是组件B内部调用的，但要把组件B的modal抽取出来，放到组件A里才能满足Modal 放置要同级的要求

**Comment by asd8510678** [comment]
楼上说的对，我本来封装好的组件 用solt 来扩展，因为这个问题，我得把弹出框放外层，再写一次相关代码。。。
