### ISSUE TITLE
Tree属性BUG

### ISSUE THREAD

**Issue by panxch** [iview/iview#2162]
Tree：如果使用watch给data赋值，发现tree控件节点点击事件错误

**Comment by SergioCrisostomo** [comment]
@panxch can you create a example of the problem?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by SergioCrisostomo** [comment]
@panxch today we released `2.6.0`. Please test this problem in this new version and comment here if the problem is still there.

**Comment by SergioCrisostomo** [comment]
@panxch I think this was fixed in `2.6.0`. Please comment if the problem is still there. Closing for now.
