### ISSUE TITLE
Spin 的一个坑

### ISSUE THREAD

**Issue by zhaotoday** [iview/iview#2165]
https://github.com/iview/iview/blob/2.0/src/components/spin/spin.js#L45
这里设了定时器，会造成一些问题，比如：
我对 Ajax 请求做了统一处理，请求开始时 show spin，结束时 hide spin，如果有多个连续或者并行的请求，会有问题。
目前，我处理两个连续请求的方法是：第 1 个请求完成后，等待 500 ms 再进行第 2 个：
https://github.com/zhaotoday/iview/blob/master/src/app/Articles/List/index.vue#L152
iView 是否可以对这种场景做下优化？

**Comment by icarusion** [comment]
建议你自己优化业务逻辑。

**Comment by zhaotoday** [comment]
@icarusion 
好的，谢谢哈，我自己再优化下。
