### ISSUE TITLE
Questions about the new Tree component collection

### ISSUE THREAD

**Issue by icarusion** [iview/iview#2166]
About #2090 , i tested and found some questions:
- about `indeterminate`, do you think it need to automatically detect its value when you initialize it (or when the data is modified)?[discussion]
- when change some data, the Tree won't be updated, look following demo:
https://jsfiddle.net/Aresn/7wnysqbL/ 
this demo used iView version `2.5.1`, need to change to #2090 to restore the problem. When click `update` button, you can see the difference.

**Comment by SergioCrisostomo** [comment]
@icarusion:

 - about `indeterminate`: I think its better code to take decision and show how check/uncheck works. Otherwise check/uncheck behaves like select. 
What do you think?

 - about jsFiddle example I was copying the nodes so we could change the tree from outside, but I sent a commit to restore/fix that now.

**Comment by icarusion** [comment]
I think `indeterminate` should be responsive, and it will automatically change based on the `checked` state of `data`.

**Comment by SergioCrisostomo** [comment]
@icarusion if I understand correct you prefer Tree to start without calculating `indeterminate` state and just do that when user changes some checked box. Is it correct?

**Comment by icarusion** [comment]
I think `indeterminate` should be controlled by iView not users, so it should automatically respond whether you are initializing or changing the data, i think.

**Comment by SergioCrisostomo** [comment]
fixed in https://github.com/iview/iview/pull/2090
