### ISSUE TITLE
Table组件，在windows上面，出现table一直计算宽度，宽度一直增加?

### ISSUE THREAD

**Issue by xjccc** [iview/iview#2167]
我是在html中引用了
<link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
 <script type="text/javascript" src="http://vuejs.org/js/vue.min.js"></script>
 <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>

使用i-table
<i-table height="520" style="margin: 0 auto;border-collapse: collapse;white-space: 0;" border :columns="columnData" :data="tableData" @on-selection-change="tableSelectChange"></i-table>

数据结构：
columnData: [
          {
            type: 'selection',
            width: 60,
            align: 'center'
          },
          {
            title: 'id',
            key: 'id',
            align: 'center'
          },
          {
            title: '广告位名称',
            key: 'name',
            align: 'center',
            render: (h, params) => {
              return h('div', [
                  h('a', {
                    style: {
                      color: '#0000FF'
                    },
                    on: {
                      click: () => {
                        console.log(params);
                      }
                    }
                  }, params.row.name)
              ])
            }
          },
          {
            title: '尺寸',
            key: 'size',
            align: 'center'
          },
          {
            title: '类型',
            key: 'type',
            align: 'center'
          },
          {
            title: '价格 / 每天',
            key: 'price',
            align: 'center'
          },
          {
            title: '使用情况',
            key: 'used',
            align: 'center'
          },
          {
            width: 280,
            title: '操作',
            key: 'operations',
            align: 'center',
            render: (h, params) => {
              return h('div', [
                h('Button', {
                  props: {
                    type: 'primary',
                    size: 'small'
                  },
                  style: {
                    marginRight: '5px'
                  },
                  on: {
                    click: () => {
                      this.operator(params.index)
                    }
                  }
                }, '排期管理'),
                h('Button', {
                  props: {
                    type: 'warning',
                    size: 'small'
                  },
                  style: {
                    marginRight: '5px'
                  },
                  on: {
                    click: () => {
                      this.edit(params.index)
                    }
                  }
                }, '编辑'),
                h('Button', {
                  props: {
                    type: 'success',
                    size: 'small'
                  },
                  style: {
                    marginRight: '5px'
                  },
                  on: {
                    click: () => {
                      this.report(params.index)
                    }
                  }
                }, '报告'),
                h('Button', {
                  props: {
                    type: 'error',
                    size: 'small'
                  },
                  style: {
                    marginRight: '5px'
                  },
                  on: {
                    click: () => {
                      this.remove(params.index)
                    }
                  }
                }, '删除')
              ]);
            }
          }
        ],
        tableData: [
          {
            id: 1213,
            name: '通栏1-1000X60',
            size: '1000X60',
            type: '固定',
            price: 9100,
            used: '使用中'
          },
          {
            id: 1215,
            name: '通栏2-1000X60',
            size: '1000X60',
            type: '浮层',
            price: 9100,
            used: '空闲'
          },
          {
            id: 1214,
            name: '通栏3-1000X60',
            size: '1000X60',
            type: '轮播',
            price: 9100,
            used: '20日后有上线'
          }
        ]

在windows电脑上发生，计算出现bug，宽度一直增加

图片链接[https://github.com/xjccc/error-pic/blob/master/iview-table.png](url)

**Comment by xjccc** [comment]
layout布局后。
`<div class="layout-content">
        <div class="ad-left-slider"></div>
        <div class="header-select">
          <div class="table-data">
            <i-table height="520" style="border-collapse: collapse;white-space: 0;" border :columns="columnData" :data="tableData" @on-selection-change="tableSelectChange"></i-table>
          </div>
        </div>
</div>`
想要layout-content实现左右布局使用display:flex;flex-direction:row的时候。在windows上，table会一直计算宽度，从而宽度无限增长。

**Comment by AricZhu** [comment]
我也遇到这个bug了，问下解决了吗
