### ISSUE TITLE
Tabs 能否支持使用代码关闭某个 tab panel页面

### ISSUE THREAD

**Issue by GITleonine1989** [iview/iview#217]
### iView 版本号
0.9.15

### 操作系统/浏览器 版本号
Win10/chrome 55

### Vue 版本号
1.0.26

### 复现步骤
Tab设置为closeable 之后，期望某个tab panel页面里的操作完成之后，比如表单提交完了之后在代码里直接关闭当前的tab 页
### 问题现象，以及你期望的结果是怎样的?
期望提供一个方法（传入key值）用来关闭tab 页

**Comment by icarusion** [comment]
[https://github.com/iview/iview/blob/master/src/components/tabs/tabs.vue#L178](https://github.com/iview/iview/blob/master/src/components/tabs/tabs.vue#L178)

这种问题要学会看源代码

**Comment by GITleonine1989** [comment]
@icarusion 哦，知道了，瞄了一下 没注意到这个方法，谢谢
