### ISSUE TITLE
Table组件，多选和折叠效果同时使用BUG，折叠会清空已选中的行

### ISSUE THREAD

**Issue by YuuyaRin** [iview/iview#2173]
使用Table组件，使用type: 'selection'，并render了expand后，触发expand的展开和收起，都会清空Table已选中行的checkBox
不知是我使用不当还是有这个bug，望解答or修复
非常感谢~~~
加油~~

**Comment by YuuyaRin** [comment]
写项目被这个问题卡住了~~~求助~~

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
