### ISSUE TITLE
Table组件导致浏览器刷新按钮闪烁

### ISSUE THREAD

**Issue by roc-young** [iview/iview#2174]
有Table组件的页面加载时，浏览器的刷新按钮和网页title图标会闪烁，表格越多闪烁越多，当页面有多个表格严重影响用户体验。

**Comment by icarusion** [comment]
https://www.iviewui.com/components/table 打开 iView 文档呢

**Comment by roc-young** [comment]
打开文档不闪，但iview-admin会闪

**Comment by icarusion** [comment]
那你去 iview-admin 提交 issue 吧。

**Comment by roc-young** [comment]
已提交
