### ISSUE TITLE
Menu的click事件不会冒泡

### ISSUE THREAD

**Issue by luogan210** [iview/iview#2176]
如题，使用Poptip时，点击外面poptip的弹出框会消失，但是点击Menu的时候不会，注册一个document的click事件，点击Menu的时候，document的click事件并不会出发，Menu的item是不是禁止冒泡了？

**Comment by daiyanze** [comment]
menuItem的li标签的点击事件绑定了stopPropagation
[点这里看代码](https://github.com/iview/iview/blob/2.0/src/components/menu/menu-item.vue#L2)
```vue
<li :class="classes" @click.stop="handleClick"><slot></slot></li>
```

**Comment by hellomrbigshot** [comment]
在 menu on-select 方法里放一个 document.querySelector('xxx').click()
