### ISSUE TITLE
RadioGroup  互斥绑定问题

### ISSUE THREAD

**Issue by maysoft** [iview/iview#2177]
<RadioGroup v-model="userInfo.IsLock" >
                              <Radio  :value="0" label="正常"></Radio>
                              <Radio :value="1" label="禁用"></Radio> 
 </RadioGroup>

userInfo.IsLock 返回的0和1 为什么这样绑定不行呢 没有一个选中的

**Comment by maysoft** [comment]
`   <RadioGroup v-model="userInfo.IsLock" >
                              <Radio  :value="0" label="正常"></Radio>
                              <Radio :value="1" label="禁用"></Radio> 
                          </RadioGroup>`

**Comment by daiyanze** [comment]
> value 只在单独使用时有效。可以使用 v-model 双向绑定数据

这时候需要用label来绑定数据
```vue
<RadioGroup v-model="userInfo.IsLock" >
  <Radio label="0">正常</Radio>
  <Radio label="1"> 禁用 </Radio>
</RadioGroup>
```

**Comment by maysoft** [comment]
好的 谢谢

**Comment by miaoyuxinbaby** [comment]
@daiyanze  如果把label="0"改成label=0就不行了。即使userInfo.IsLock = 0。
但是如果:label=0就可以。这是为什么？
