### ISSUE TITLE
iview项目 clone下来修改组件不支持=()=>import()语法

### ISSUE THREAD

**Issue by tkggusraqk** [iview/iview#2179]
clone iview项目，修改/添加组件，用 const Index = () => import('./components/Index') 异步引用组件时，编译报错：
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./examples/app.vue
Module build failed: SyntaxError: D:/WorkProject/weuivue/examples/app.vue: Unexpected token (31:20)

  29 | //
  30 |
> 31 | const Index = () => import('./components/Index')
     |                     ^
  32 |
  33 | module.exports = {
  34 |   data: function () {

 @ ./examples/app.vue 9:0-123
 @ ./examples/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8082 webpack/hot/dev-server ./examples/main

请教下这个该怎么解决

**Comment by SergioCrisostomo** [comment]
@tkggusraqk do you have a example github repository with this problem?

**Comment by daiyanze** [comment]
感觉一个ui的库正常情况下应该用不上异步组件吧😄
试试用babel的插件来看看能不能解决
[参考下vue-router的懒加载](https://router.vuejs.org/zh-cn/advanced/lazy-loading.html)

**Comment by FourLeafClover** [comment]
@daiyanze  最近我们也用Iview自己搭建了一个后台框架。关于楼主提到的UI库正常试用下不需要异步加载。其实感觉还有必要实现的。Vue-router的懒加载是基于页面级别的。我之所以用懒加载只是不想，我所有后台页面的vue和service层的js都打包到一个app.js里面。这样随着页面增加业务量增多app.js就越来越大。 但是当我选择懒加载的时候。我发现Vue-router是基于页面级别的按需加载 。譬如，我后台系统有20多个页面。每个页面都有用到Row,Input,Table。 我会发现其实每个页面单独压缩后的JS。都会包含Row,Input,Table的Iview源码。因为我在这些页面都单独import进来了的。可是我不想这样。我想的是只是我的service层的js和页面vue代码按需加载。里面所引用的View组件还是都统一引用一个chunk.js。 如果iview支持异步加载。那么我可以再vue页面引用iview的所有组件全部chunk到一个js里面。那么我所有页面其实都引用改JS。 就不会存在每个页面编译后的js里面包含了引用的view组件源码。 整个项目其实就只需要加载一次Iview代码。

**Comment by daiyanze** [comment]
@FourLeafClover 
估计要让iview完美支持异步加载得等好一阵子了。。。
不知道用cdn是不是可以解决你的问题？iview.min.js大概20kb左右。

**Comment by FourLeafClover** [comment]
@daiyanze   很抱歉。可能是我的webpack配置问题。我的vue页面里面已经可以成功异步加载View插件了。:)
