### ISSUE TITLE
【钉钉】升级到2.5+版本后 DatePicker 的 daterange 模式无法正常工作

### ISSUE THREAD

**Issue by 0604hx** [iview/iview#2186]
## 问题描述

之前用 `2.3.2` 版本，使用 DatePicker 在 Chrome、钉钉（代码与浏览器是一致的，只是在钉钉内置浏览器打开） 下都正常使用，我的代码如下：

```html
<Date-picker :transfer="true" :value="[t.startDate,t.endDate]" type="daterange" @on-change="selectDateDo"
                                         @on-open-change="current=$index"
                                         :placement="placement" placeholder="选择日期"></Date-picker>
```

今天升级到了 `2.5.1` ，浏览器正常，钉钉下就出现无法选择日期的问题
![2017-10-25_09-42-25](https://user-images.githubusercontent.com/3523216/31976305-4e84b14c-b969-11e7-95e9-d1a95489c600.gif)

## 可能原因

应该是 `daterange` 模式在钉钉环境下，点击事件有误

**Comment by icarusion** [comment]
#2122
