### ISSUE TITLE
Table异步加载列将导致横向滚动条消失

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#2188]
https://codepen.io/yangdan8/pen/veqaJB
![111](https://user-images.githubusercontent.com/16515026/31977265-b307e8be-b96e-11e7-9668-2a969e30fe43.png)

**Comment by kiddkyd1412** [comment]
厉害，大开眼界。异步添加列。作者又得忙死。。

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。

**Comment by icebluesky2666** [comment]
解决了吗？
