### ISSUE TITLE
Table固定行高和列宽后数据未达到需要滚动条的情况下表头宽度依然计算了滚动条宽度

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#2189]
https://codepen.io/yangdan8/pen/veqadE
![111](https://user-images.githubusercontent.com/16515026/31977149-075282d6-b96e-11e7-8ef6-912bf4f3e41c.png)

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
