### ISSUE TITLE
select 搜索  建议问题

### ISSUE THREAD

**Issue by huanglong6828** [iview/iview#219]
一直在项目中使用iview select搜索这个功能是使用的最多的 但是我在搜索时未搜到想要的值却想使用input框的值 select没有返回这个值 希望能返回这个值

**Comment by rijn** [comment]
select和input的功能不同，不应该返回不属于dataset中的值。之后会扩展出autocomplete组件。

**Comment by sherllochen** [comment]
感觉这个功能很有用，比较常用的场景就是监听input的值，提交ajax请求，获取相应结果来填充select的options。

**Comment by icarusion** [comment]
Select 应该增加远程搜索功能

**Comment by l86110** [comment]
select 远程搜索功能使用场景还是比较多的，希望在2.0里面有😝

**Comment by 670444337** [comment]
Select如果能增加远程搜索功能就太太太太太好了！

**Comment by maxid** [comment]
建议增加Asynchronous select组件
https://monterail.github.io/vue-multiselect/#sub-getting-started

**Comment by dean5277** [comment]
我也很喜欢Asynchronous select

**Comment by icarusion** [comment]
已支持远程搜索
