### ISSUE TITLE
select选中后文本被转码（下拉没转码）

### ISSUE THREAD

**Issue by wanglyaaa** [iview/iview#2191]
原内容：游戏->页游
![image](https://user-images.githubusercontent.com/28591510/31986856-89d0ec06-b99c-11e7-993a-2d2979cf7f80.png)
看源码应该是受到innerHtml影响（innerHtml会把某些字符转码）
![image](https://user-images.githubusercontent.com/28591510/31986797-5d8e8f40-b99c-11e7-8f92-e3601e7dfdf3.png)

**Comment by SergioCrisostomo** [comment]
@wanglyaaa can you provide a example of the problem?

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by wanglyaaa** [comment]
https://jsfiddle.net/yyrzhm46/47/

**Comment by wanglyaaa** [comment]
@SergioCrisostomo 
demo如下：
https://jsfiddle.net/yyrzhm46/47/

**Comment by SergioCrisostomo** [comment]
@wanglyaaa that was fixed already. You should use a more recent version than 2.0.0
https://jsfiddle.net/Sergio_fiddle/yyrzhm46/48/

**Comment by wanglyaaa** [comment]
@SergioCrisostomo 嗨，发现加了filterable属性后还是有问题哈
https://jsfiddle.net/yyrzhm46/49/

**Comment by SergioCrisostomo** [comment]
@wanglyaaa thanks for the demo! Looks like a bug, will re-open this and investigate.

**Comment by wanglyaaa** [comment]
@SergioCrisostomo 好的，能否知道大概什么时候会修复

**Comment by wanglyaaa** [comment]
@SergioCrisostomo 
修复在2.0.0？？但是2.0.0貌似也不行：https://jsfiddle.net/yyrzhm46/56/
能否修复在最新版？我们现在已更新到2.5.1

**Comment by icarusion** [comment]
@wanglyaaa merged, will be updated in 2.6.0

**Comment by wanglyaaa** [comment]
@icarusion  ok,thank you
