### ISSUE TITLE
Table组件table.vue中的handleResize方法中的$el可能为undefined

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#2192]
beforeDestroy调用了handleResize方法,而handleResize中是在$nextTick中去执行,
而$nextTick执行的时候可能table已经Destroied,所以可能获取不到$el导致报错,
请修改$nextTick中的代码检测$el是否为undefined再执行后续代码.
![111](https://user-images.githubusercontent.com/16515026/31990871-e4dc0e3a-b9a8-11e7-98d2-de21cb2bee36.png)
![22222](https://user-images.githubusercontent.com/16515026/31990897-fc4cbff6-b9a8-11e7-8821-865c4e11c1f4.png)

**Comment by icarusion** [comment]
welcome to contribute code :)

**Comment by icarusion** [comment]
#2195
