### ISSUE TITLE
运行webpack报错了，什么情况？

### ISSUE THREAD

**Issue by GreatBoy** [iview/iview#22]
![image](https://cloud.githubusercontent.com/assets/11404895/19225602/f8fde526-8ed1-11e6-9af8-f1e123a428e7.png)
这是什么情况

**Comment by hmdeng110** [comment]
vue-loader有加载么

**Comment by GreatBoy** [comment]
加载了，版本是你的package的版本

**Comment by GreatBoy** [comment]
其他的没问题，就是加载iview就有问题了。

**Comment by GreatBoy** [comment]
是不是我的版本不对？

**Comment by icarusion** [comment]
babel 配置编译 iview 了吗

**Comment by GreatBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/11404895/19225657/f2428f60-8ed2-11e6-8698-867f30ae8170.png)

按照文档配置的。

**Comment by icarusion** [comment]
更新了，如果是windows的话，查看 #16

**Comment by GreatBoy** [comment]
我是mac电脑，很奇怪了。

**Comment by GreatBoy** [comment]
找到问题了，是配置的问题，文档你可以改一下，就是linux和window的路径不一样，换成下面的就可以了。
       {
            test: /iview\\.*?js$/,
            loader: 'babel'
        }

**Comment by GreatBoy** [comment]
不对，这样编译没报错，但是貌似iview的没打包进来。。。。 说明还是iview编译有问题。

**Comment by GreatBoy** [comment]
我找到问题了，是我配置有问题。非常感谢你

**Comment by liuhao1025** [comment]
`vue-loader` 那边你配置了 `exclude` 把 `node_modules` 排除了，所以要像处理 `js` 文件一样额外配置一下。

**Comment by jiandao7114** [comment]
@GreatBoy 问题最后是怎么解决的，我这边也碰到了一样的问题。用的官方vue-cli搭的项目，直接添加iview出现上面的问题。

**Comment by zhenizhui** [comment]
@liuhao1025 请问，额外配置一下是怎么配置？

**Comment by zzm1988** [comment]
@liuhao1025 请问，额外配置一下是怎么配置？
