### ISSUE TITLE
itable 数据量较大时的性能问题

### ISSUE THREAD

**Issue by GITleonine1989** [iview/iview#220]
### iView 版本号
0.9.16

### 操作系统/浏览器 版本号
Win10/chrome 55

### Vue 版本号
1.0.26

### 能够复现问题的在线示例
数据比较少的示例
http://jsbin.com/lelomukisa/1/edit?html,css,js,output
数据比较多的示例
http://jsbin.com/lihiquracu/1/edit?html,css,js,console,output
### 复现步骤
在遇到数据比较多，且数据列也较多的情况下，发现itable 的渲染数据很慢，有时甚至页面卡死
### 问题现象，以及你期望的结果是怎样的?
期望能够优化这里的性能问题

**Comment by icarusion** [comment]
#169

**Comment by herist** [comment]
这个问题比较影响使用，希望能够尽快解决
