### ISSUE TITLE
Select组件multiple, remote, filterable模式，如果两次搜索都产生一个选项，第二次产生的选项自动被选中

### ISSUE THREAD

**Issue by ZEROKISEKI** [iview/iview#2202]
[https://codepen.io/ZEROKISEKI/pen/POYQRB](https://codepen.io/ZEROKISEKI/pen/POYQRB)

### 问题描述：

关于select组件多选模式支持远程和搜索模式的, 如果搜索出来只有一个选项，选择了该选项之后立刻输入，此时如果第二次出现的选项只有一个，那么该选项会变成选中状态。

如图, 选择了"A"，之后搜索"B"，此时跳出的B是自动被选中的状态，点击选项无反应:

![问题截图](http://oyfn84vnv.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-10-27%2012.20.20.png)

**Comment by icarusion** [comment]
@SergioCrisostomo I tried to solve the problem but failed, could you have a look, the example is :
https://jsfiddle.net/Aresn/nexbfjv6/ 
Repetition steps:
- enter 'a' and select 'a'
- enter 'b', then problem is 'b' is selected

**Comment by PIJI** [comment]
搜索词改变时先清空选项列表再远程查询，可以解决这个问题

**Comment by icarusion** [comment]
fixed in 2.14.0

**Comment by just-wkj** [comment]
我遇到这个问题,如上面所说在远程搜索之前清空options可以解决
```

remoteMethod3 (query) {
          this.options3 = [];  //添加此行即可
          if (query !== '') {
              this.loading3 = true;
              setTimeout(() => {
                  this.loading3 = false;
                  this.options3 = this.list2.filter(item => item.label.indexOf(query) > -1);
              }, 200);
          } else {
              this.options3 = [];
          }
}
```
