### ISSUE TITLE
DatePicker无法动态改变type

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#2204]
https://codepen.io/yangdan8/pen/POYOmr

**Comment by SergioCrisostomo** [comment]
@yangdan8 you can use a trick, to give `:key="..."` to the component and change it. Vue will think its a different component and render it again, as `date`.

https://codepen.io/sergiocrisostomo/pen/ooNXZY

**Comment by SergioCrisostomo** [comment]
@yangdan8 please try my suggestion, it solves your problem, if you need help let me know.
I close this for now.
