### ISSUE TITLE
建议Transfer组件的目标列表支持上下移动，及优先级功能

### ISSUE THREAD

**Issue by QJX** [iview/iview#2206]

**Comment by daiyanze** [comment]
能稍微具体描述一下 “上下移动“ 和 ”优先级“ 的效果不

**Comment by QJX** [comment]
如下图，支持右侧列表里的项可进行上下移动，因为有这种场景需要知道这些项的位置。
![bcf048ed8591a32d2e32da175975a686](https://user-images.githubusercontent.com/12379009/32150801-1fe2eb1e-bd52-11e7-9d64-da58038fd23c.png)

**Comment by icarusion** [comment]
你可以在 slot 里完成逻辑

**Comment by QJX** [comment]
右边怎么slot，又不支持
