### ISSUE TITLE
good

### ISSUE THREAD

**Issue by benfeng** [iview/iview#2207]
公司或组织：理德物联网
链接：无
![8](https://user-images.githubusercontent.com/1662310/32086052-3d831d50-bb05-11e7-9c60-411d81154f00.png)
![7](https://user-images.githubusercontent.com/1662310/32086053-3dd14660-bb05-11e7-86ef-174052750b09.png)

**Comment by SergioCrisostomo** [comment]
@benfeng can you please add this here -> https://github.com/iview/iview/issues/2143

It would be great! 👍
