### ISSUE TITLE
iview 的Select 选择器下拉列表可否添加分页？

### ISSUE THREAD

**Issue by xkcoding** [iview/iview#2208]
类似效果比如这个 https://terryz.oschina.io/selectpage/index.html
@icarusion

**Comment by daiyanze** [comment]
目前的select下拉菜单是使用固定的dropdown。希望能像AutoComplete一样添加slot来自定义下拉菜单。
@icarusion 

我修改一下试试

**Comment by icarusion** [comment]
@daiyanze AutoComplete 是源自 Select 的，所以在 Select 里是预留了 slot，这个需求是有的，方便的话，创建一个 feature request 吧。

**Comment by icarusion** [comment]
@xkcoding Select 里是 slot，你直接写一个 Page 先试试看吧。
