### ISSUE TITLE
the position of table in TabPane had changed

### ISSUE THREAD

**Issue by llccing** [iview/iview#2210]
when tabs has sub element, such as table ,when toggle tabPane，the position of table had changed, please tech me how to resolve this , thanks
[question](https://jsfiddle.net/lcf33123/gp37kfzk/)

**Comment by daiyanze** [comment]
我这里看着好像没有问题啊，你有截图没
It looks fine to me anyway (tested on Safari 11.0 12604.1.38.1.7).

<img width="795" alt="2017-10-27 11 17 16" src="https://user-images.githubusercontent.com/14920529/32108595-295303be-bb6d-11e7-8143-e0dd27746265.png">

**Comment by SergioCrisostomo** [comment]
@llccing I also tested, in Chrome, and looks good to me. Can you explain more? what browser do you use? is the video under correct?

![2210](https://user-images.githubusercontent.com/5614559/32110919-3a28fb8c-bb39-11e7-8382-4d6b984fc188.gif)

**Comment by llccing** [comment]
@daiyanze @SergioCrisostomo thanks

chrome version 61.0.3163.100（32 bit）
![tabs](https://user-images.githubusercontent.com/12945329/32130009-610aa2da-bbc2-11e7-9412-f247d86433e9.gif)

this question also happen in my colleague‘s pc, my pc is thinkpad t470, i don't know if because of the pc zoom ratio is 125% ,of course, i will try immediately

**Comment by llccing** [comment]
eh…，i find the problem , because of my pc zoom ratio 125%, if i change zoom ratio setting to 100%，the problem disappear.

but the people to  using this project is all my colleague, their pc's zoom ratio is 125%, what's should I do.  

one solution( from my new colleague) is add padding to tabPane , or should i create tabs by myself

**Comment by llccing** [comment]
problem disappear
![tabs is good](https://user-images.githubusercontent.com/12945329/32130158-6fc6cc10-bbc5-11e7-8bae-4acc76e37b6a.gif)

**Comment by llccing** [comment]
when i change content to company project content , this question also happen, uh... , now i think may be shouldn't use tabs, just write a component by self ......


![tabs not good](https://user-images.githubusercontent.com/12945329/32151415-aa1e03ae-bd57-11e7-936e-39c24902d9f8.gif)

**Comment by daiyanze** [comment]
I think it might be the problem of "cell-width". The first column cell took up all of the width by breaking the line so that the whole table becomes wider than it was. Therefore, the end of the right side of the block turns into borderless.

It seems that you are using card layout to wrap a whole table content. I think the table's got its width and the card's padding took some space of the table. Please debug your table's element style with chrome devtools.

**Comment by llccing** [comment]
@daiyanze ,may you are right , but i don't know what's todo whit iview/tabs , i finda an component [vue-tabs-component](https://github.com/spatie/vue-tabs-component) , it works for me

**Comment by daiyanze** [comment]
@llccing Well, the design is a little bit different from iview. Anyway, as long as it works.
