### ISSUE TITLE
width和height自适应问题

### ISSUE THREAD

**Issue by mengqinWu** [iview/iview#2211]
一个不成熟的小意见，我用了几个组件，觉得很方便，可是存在一个不方便，就是总是要通过js来获取width和height，才可能达到屏幕自适应，我喜欢用rem，或者是flex布局，我很建议高度随父级元素的高宽来适应就非常完美了

**Comment by daiyanze** [comment]
能否告诉我是哪几个组件需要自适应化？

**Comment by icarusion** [comment]
请到 https://www.iviewui.com/new-issue 这里，按要求提交 issue。
