### ISSUE TITLE
【建议】对面包屑等组件增加命名路由的支持。

### ISSUE THREAD

**Issue by 634750802** [iview/iview#2214]
【问题】
目前面包屑支持href方式跳转，而我在项目中大量使用命名路由。用@click.native还需要考虑到hover样式等问题，不是很方便。

【解决方式】
Breadcrumb使用类似Menu的方式监听点击操作，同时也可兼容href。

**Comment by 634750802** [comment]
可以考虑使用router-link代替href(对于使用了router的情况)，监听事件可能没有太大必要。

**Comment by SergioCrisostomo** [comment]
@634750802 if you have time to send a pull request for this it would be great!
