### ISSUE TITLE
Datepicker组件on-change事件在第一次clear的时候不会触发

### ISSUE THREAD

**Issue by zerolbsony** [iview/iview#2215]
Datepicker组件，指定一个默认值，定义on-change事件，第一次点击清除按钮时，on-change事件不会触发。但是如果改动过组件的值，点击清除按钮时会触发on-change事件并且$event为空字符串。

期望行为：不论是否第一次点击清除按钮，均触发on-change事件

复现代码：https://jsfiddle.net/m243d8p9/1/

**Comment by sandysong** [comment]
遇到同样的问题

**Comment by icarusion** [comment]
translation: 
in DatePicker, the `on-change` event will not be triggered when click `clear` icon at first time, and then it can be triggered.

**Comment by lily0310chen** [comment]
这个挺重要的，因为项目中大量用到了
