### ISSUE TITLE
Modal中onOk方法中执行 this.$Modal，新的modal一闪而过

### ISSUE THREAD

**Issue by caozhengchn** [iview/iview#2217]
详情见：http://jsfiddle.net/L8px8572/3/
点击click me 点击确定后，弹出新的modal，但一闪即消失

**Comment by daiyanze** [comment]
`this.$modal`是全局对话框，一般情况下用来解决简单对话逻辑的。
当你想要在里面加载其他内容的时候，modal仅仅是把里面的东西换了。但是你点击ok的事件被提交了，所以全局对话框的visible属性变为false，这时候就成了modal先改变内容然后关闭的效果了。
解决方法很简单，把你的对话框逻辑拆分成两个modal就好了。

**Comment by icarusion** [comment]
正如楼上所说， 你可能是误用了 Modal。可以结合 Message、Notice 去实现交互。
