### ISSUE TITLE
Modal框在tabs页里的显示问题

### ISSUE THREAD

**Issue by GITleonine1989** [iview/iview#222]
### iView 版本号
0.9.16

### 操作系统/浏览器 版本号
win10/chrome55

### Vue 版本号
1.0.26

### 能够复现问题的在线示例
http://jsbin.com/kayonotipe/7/edit?html,css,js,output

### 复现步骤
使用tabs创建两个标签页，
在第二个标签页面里有个modal框，弹出款显示的时候显示到第一个标签页了，
虽然将modal 移出到 tab 组件外可以解决这个问题，但是，有时候第二个标签页里面是封装好的组件，组件里包含了modal框，所以这时候modal框就不方便拿到tab也外面了

**Comment by icarusion** [comment]
Modal本来就是全局的，当然要放在外面。

**Comment by GITleonine1989** [comment]
嗯，我也是这样认为，但有人把modal写到组件里面去了，然后在tab页里面引入了组件，导致了modal跑到tab页里面去了 @icarusion

**Comment by jefferyE** [comment]
可以给tab下的modal设置样式解决这个问题， style="transform: translateX(0%) translateZ(0px); height: 100%"
