### ISSUE TITLE
Cascader能否添加当清空内容时候的一个event

### ISSUE THREAD

**Issue by www295686243** [iview/iview#2220]
Cascader在有默认值的时候(:value="parent") ,点击清空，能否加个监听，我好让data上的parent为空

**Comment by daiyanze** [comment]
可以在你的component里加一个watch，来观察parent的变化。
```vue
export default {
   ...
  watch () {
  }
}
```

**Comment by icarusion** [comment]
You can use `v-model` to bind data. So when you clear, your parent data will be cleared also.

**Comment by www295686243** [comment]
@daiyanze 我所说的点击清空是指 当Cascader的props中的clearable设置为true时，选择后右边会出现小叉叉，点击小叉叉会清空表单的内容，但并没有监听清空事件。
@icarusion 而我使用v-model的时候，会有bug，比如当绑定了parent，parent有默认值，你再去改变层级会偶现表单无法显示内容的bug
