### ISSUE TITLE
FormItem 中使用 <Input type="number"></Input> 报错 Invalid prop: custom validator check failed for prop "type".

### ISSUE THREAD

**Issue by liuxian1990** [iview/iview#2221]
FormItem 中使用 Input type="number" 时会报错:

 `[Vue warn]: Invalid prop: custom validator check failed for prop "type".`

只有vue.js 使用未压缩时才出现.

![image](https://user-images.githubusercontent.com/4145946/32101214-e9f67088-badc-11e7-90a4-c36e7d5927d9.png)

![image](https://user-images.githubusercontent.com/4145946/32100747-9c8ecd9c-bada-11e7-8323-8f358ccca696.png)

例子:[https://codepen.io/liuxian2014/pen/MOgPmN](https://codepen.io/liuxian2014/pen/MOgPmN)

**Comment by daiyanze** [comment]
你的Input type不是api提供的合法类型。图三告诉你合法类型有`text` `textarea` `password`
详情请看API文档
<img width="1098" alt="2017-10-28 10 16 15" src="https://user-images.githubusercontent.com/14920529/32129924-4b723eea-bbc9-11e7-9887-6762a7e1f566.png">

@icarusion @SergioCrisostomo 可以close

**Comment by naughtyGitCat** [comment]
<Button icon='plus' type="warnings" @click="getUsers">测试</Button>

Button按钮也有这个问题啊

**Comment by jarvan4dev** [comment]
@daiyanze @icarusion 为什么屏蔽掉原来h5支持的 number 类型？

**Comment by IngridFanfan** [comment]
没有屏蔽number类型，只是列了一个单独的input-number标签。详情参看Document

**Comment by daiyanze** [comment]
@jarvan4dev 
谢邀～
我个人感觉H5的 `type=“number”` 其实不是很好用，因为这个h5的api包含了科学计数E，所以不能输入纯字。如果想用number类型的input，请使用`InputNumber`。
https://www.iviewui.com/components/input-number

**Comment by yangxiyangxi** [comment]
用inputNumber也报这个错，我数字类型是默认的数字

**Comment by yangxiyangxi** [comment]
用inputNumber也报这个错，我数字类型是默认的数字

**Comment by yangxiyangxi** [comment]
怎么屏蔽number类型

**Comment by yangxiyangxi** [comment]
找到解决办法了，在inputNumber外套用i-form 和Form-item标签，设置默认值，如
<i-form  :model="formInline"  >
					<Form-item prop="InTotalLimit">											
						<InputNumber class="ModalInput3"  :min="0" v-model="formInline.passRate"  ></InputNumber>				
					 </Form-item>
					</i-form> 
再设置绑定的值formInline:{
					InTotalLimit: null,					
					passRate:null,
				},
就不会再报类型错误了，并且初始值可以为空

**Comment by yangxiyangxi** [comment]
找到解决办法了，在inputNumber外套用i-form 和Form-item标签，设置默认值，如
<i-form  :model="formInline"  ><Form-item prop="InTotalLimit">										<InputNumber class="ModalInput3"  :min="0" v-model="formInline.passRate"  ></InputNumber>				
 </Form-item></i-form> 
再设置绑定的值formInline:{
					InTotalLimit: null,					
					passRate:null,
				},
就不会再报类型错误了，并且初始值可以为空

**Comment by yangxiyangxi** [comment]
找到解决办法了，在inputNumber外套用i-form 和Form-item标签，设置默认值，如
<i-form  :model="formInline"  ><Form-item prop="InTotalLimit">											
						<InputNumber class="ModalInput3"  :min="0" v-model="formInline.passRate"  ></InputNumber>				
 </Form-item></i-form>
再设置绑定的值formInline:{
					InTotalLimit: null,					
					passRate:null,
				},
就不会再报类型错误了，并且初始值可以为空

**Comment by yangxiyangxi** [comment]
![image](https://user-images.githubusercontent.com/25736231/44828203-5c8af200-ac49-11e8-8f87-ad07c730cc99.png)

**Comment by TTYuLi** [comment]
> 你的Input type不是api提供的合法类型。图三告诉你合法类型有`text` `textarea` `password`
> 详情请看API文档
> <img alt="2017-10-28 10 16 15" width="1098" src="https://user-images.githubusercontent.com/14920529/32129924-4b723eea-bbc9-11e7-9887-6762a7e1f566.png">
> 
> @icarusion @SergioCrisostomo 可以close
怎么样才能设置一个合法的类型呢，比如给button 添加一个其他的类型样式，使用自定义 type

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/17087920/56190893-d697ac00-605d-11e9-9053-e2c570591434.png)

@daiyanze 版本 3.1.5，`tel` `number` 都是合法的值，但是 `type="tel"` `type="number"` 都报错
