### ISSUE TITLE
table 中 highlight-row 的 bug

### ISSUE THREAD

**Issue by chy2z** [iview/iview#2224]
table 开启显示间隔斑马纹（stripe）和支持高亮选中的行（highlight-row），单击选中奇数行，显示的是鼠标移动的颜色，必须鼠标移走才显示选中的颜色。 偶数行就不会。

**Comment by daiyanze** [comment]
@chy2z 能否提供一下demo

使用下面的在线链接可以快速创建示例
https://jsfiddle.net/yyrzhm46/

**Comment by chy2z** [comment]
https://jsfiddle.net/yyrzhm46/62/

**Comment by chy2z** [comment]
@daiyanze    demo   https://jsfiddle.net/yyrzhm46/62/

**Comment by daiyanze** [comment]
这个属于hover效果吧，无论选中与否都跟鼠标悬停效果的逻辑无关。我觉得这里应该不算bug。
如果你觉得这种效果影响体验，可以手写css class覆盖table样式，也可以推一个pr上来。
@icarusion

**Comment by icarusion** [comment]
默认的效果，建议使用 prop `disabled-hover` 禁用鼠标滑过，或者就是 css 覆盖。
