### ISSUE TITLE
【Bug】分页组件Page的page_size小于10时显示异常

### ISSUE THREAD

**Issue by boboyan** [iview/iview#2225]
![image](https://user-images.githubusercontent.com/32193417/32131891-c3801952-bb7e-11e7-9b52-2a009b55c473.png)

如上图，total=12，size=5，但是默认还是选在10上。

![image](https://user-images.githubusercontent.com/32193417/32131895-d2f81fb0-bb7e-11e7-8ee0-ebe66a450cb1.png)
通过下拉选择后才正常

![image](https://user-images.githubusercontent.com/32193417/32131911-0c1b763e-bb7f-11e7-807b-58a8d4450f6c.png)
应该是page_size小于10的时候就不生效

**Comment by daiyanze** [comment]
你的 `:page_size` 应该写成 `:page-size`

**Comment by boboyan** [comment]
尴尬😓  谢谢
