### ISSUE TITLE
您好，请问在用upload 上传文件的时候 提交带有其他的参数 该如何使用呢？能给个例子吗？

### ISSUE THREAD

**Issue by JoanZhu** [iview/iview#2235]

**Comment by JoanZhu** [comment]
那疑惑的问题该在哪里提交询问呢？

**Comment by p2ng** [comment]
@JoanZhu 
目前我通过提供的`header`进行自定义入参的，
在每次`:before-upload`钩子里面设置`this.headers['device-type'] = this.deviceType`进行操作
