### ISSUE TITLE
Carousel 

### ISSUE THREAD

**Issue by aoqizhonghua** [iview/iview#2238]
Carousel lantern is first loaded into 0 width window changes when it is revealed in the width of rolling is normal but in Firefox is normal

**Comment by Ele-Cat** [comment]
我也遇到这个问题了

**Comment by aoqizhonghua** [comment]
@iview-bot 
https://jsfiddle.net/yyrzhm46/71/

**Comment by wufangjian** [comment]
I have the same problem. @iview-bot 

![Uploading image.png…]()
