### ISSUE TITLE
Modal对话框的问题， 关闭时互相干扰

### ISSUE THREAD

**Issue by chy2z** [iview/iview#2239]
关闭一个同时把另外的也关闭了。比如，我先弹出 this.$Modal.confirm，然后点击确定后，在弹出this.$Modal.warning，发现 同时关闭了。

**Comment by chy2z** [comment]
我现在采用，延时的方法，才能不互相干扰
` setTimeout(() => {
                                  this.$Modal.warning(config)
                                }, 1000);`

**Comment by daiyanze** [comment]
你的这个问题跟 #2217 很像，都是使用了全局Modal对话框。全局对话框的隐藏和显示都公用一个实例变量。最好把不同逻辑的Modal对话框拆分开使用。
