### ISSUE TITLE
UNMET PEER DEPENDENCY vue@2.1.10

### ISSUE THREAD

**Issue by Sun-Liu** [iview/iview#224]
@icarusion @willnewii @jingsam @icarusion @rijn 

![image](https://cloud.githubusercontent.com/assets/24770162/22107942/a759422e-de8b-11e6-9c76-b8e040835a13.png)

**Comment by rijn** [comment]
iView only supports Vue@1 currently.

**Comment by Sun-Liu** [comment]
什么时候才能支持 vue@ 2

**Comment by icarusion** [comment]
2017 Q1~Q2
