### ISSUE TITLE
Tag不能触发click事件

### ISSUE THREAD

**Issue by zema1** [iview/iview#2245]
`Tag`本身不具有click事件，但之前可以给`Tag`外套个`a`标签或`button`，通过`a`或`button`来变相click。但不知道哪次更新这么用就不行了， 
在线示例[https://jsfiddle.net/njaq1aq2/](https://jsfiddle.net/njaq1aq2/)。

希望`Tag`能加上Click事件或求一种解决办法～

**Comment by p2ng** [comment]
还真果然是啊，，，有一个项目定在了2.4.0的时候还是可用的。。。
目前最新2.8.0不可用了。
参考https://github.com/iview/iview/issues/2412，这个可用了。

**Comment by zema1** [comment]
恩 是的 用`.native`修饰下即可，之前没好好看文档。。
