### ISSUE TITLE
select 在multiple模式下同时使用 size='small' 样式没变小

### ISSUE THREAD

**Issue by liuxian1990** [iview/iview#2256]
### Environment
iview@2.6.0

### Reproduction link
[https://codepen.io/liuxian2014/pen/MOgPmN?editors=1010](https://codepen.io/liuxian2014/pen/MOgPmN?editors=1010)

### Steps to reproduce
在multiple模式下同时使用 size='small' 

### What is expected?
支持size='small' 

### What is actually happening?
size='small' 尺寸没变化

---
.ivu-select-multiple.ivu-select-small .ivu-select-selection  系列样式没有加上

**Comment by icarusion** [comment]
Select 在多选时，暂不能使用小尺寸，里面的 tag 放不下。今后再优化。

**Comment by icarusion** [comment]
fixed
