### ISSUE TITLE
建议Select组件当没有选择项的时候设置为不可点，避免没有数据时出现的空下拉列表

### ISSUE THREAD

**Issue by gaoxuan** [iview/iview#2260]
Select组件没有下拉选择项的时候也可以点，当点击后会出现一个空的下拉列表，不是很好看，最好改成没有选择项的时候就不能点

**Comment by fekata** [comment]
是不是可以增加类似 `not-found-text` 的配置
例如 `not-item-text` 默认值：没有选项

**Comment by SergioCrisostomo** [comment]
@fekata, @gaoxuan please open a issue in https://www.iviewui.com/new-issue
