### ISSUE TITLE
[Bug Report]Select中option的值为空是不显示label

### ISSUE THREAD

**Issue by LoverMaker** [iview/iview#2270]
### Environment
操作系统：MacOS 10.12.6 (16G29) 浏览器 Chrome 61 Vue: 2.4.4

### Reproduction link
[https://jsfiddle.net/yyrzhm46/75/](https://jsfiddle.net/yyrzhm46/75/)

### Steps to reproduce
选择 不限，Select中不显示不限，而是显示的空

### What is expected?
在实际使用中，表单中有可能使用空值来代表不限，特别是搜索，这时候就需要显示 不限这个label

### What is actually happening?
选择不限，Select中为空

**Comment by daiyanze** [comment]
option 的 value 必须为 string 或者 number，不填的话会默认为undefined。最好先赋一个值，然后通过计算得出需要的结果。

@icarusion 可关闭

参考链接：
https://github.com/iview/iview/blob/2.0/src/components/select/option.vue#L15

**Comment by LoverMaker** [comment]
我是传的字符串空值，空值字符串也可以匹配吧。在element ui里是支持的，当select为多

**Comment by LoverMaker** [comment]
我是传的字符串空值，空值字符串也可以匹配吧。在element ui里是支持的，我换成IView就不行了。如果select是多选的，是可以匹配的，框里也有不限二字。

**Comment by houzihua** [comment]
我这里也是啊，传空字符串就不行，我只好传了-1，后面再把-1转成空。。。

**Comment by lovanya** [comment]
在 select.vue 中有这一段代码：

![image](https://user-images.githubusercontent.com/16385444/47075846-f75a8280-d22f-11e8-9612-9ea7669fa25a.png)

![image](https://user-images.githubusercontent.com/16385444/47076029-66d07200-d230-11e8-93ad-1f1f966424f4.png)

![image](https://user-images.githubusercontent.com/16385444/47076057-72bc3400-d230-11e8-94c4-acfdeed857f3.png)


值为空字符串时，清空了 values，导致 publicValue 为 undefined，触发input 和 on-change 事件，值又变成 undefined了，这显然有问题吧。

**Comment by hqzh** [comment]
@icarusion 原生是可以绑定的啊

**Comment by ryanzhouff** [comment]
> 我这里也是啊，传空字符串就不行，我只好传了-1，后面再把-1转成空。。。

我也是这么干的，因为项目中有时候查询列表的需要用到空字符串。
