### ISSUE TITLE
[Bug Report]/date-picker double date cannot be used


### ISSUE THREAD

**Issue by longwang1995** [iview/iview#2286]
### Environment
windows 7，vue2

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
<DatePicker type="daterange" confirm placement="bottom-end" placeholder="选择日期" style="width: 200px"></DatePicker>

直接选择一段日期，无法选中

### What is expected?
选中，并在 日期输入框显示

### What is actually happening?
实际上，无法选中。

**Comment by daiyanze** [comment]
你好，能否给我们留个重现手段？

https://jsfiddle.net/yyrzhm46/

**Comment by xLong1029** [comment]
360浏览器（安全或者极速）都无法选中，谷歌和火狐浏览器可以

**Comment by icarusion** [comment]
#2122

**Comment by longwang1995** [comment]
是浏览器的原因，我更新到最新的谷歌就可以使用了
