### ISSUE TITLE
In the [Feature Request]tree component show-checkbox mode, the parent node sets checked to true, and the child node sets checked to false invalid


### ISSUE THREAD

**Issue by MichaelWangC** [iview/iview#2288]
### What problem does this feature solve?
主要解决菜单权限配置和显示的问题。目前tree组件选中一个子菜单，父菜单并不是选中状态。导致数据存储时没父菜单数据，在显示时无父菜单。如果设置父菜单的checked为true，而子菜单中的checked为false则无效。

### What does the proposed API look like?
我希望，设置父菜单的checked为true，子菜单可以设置checked为false。

**Comment by icarusion** [comment]
不合逻辑，看文档。
