### ISSUE TITLE
Dropdown 下拉菜单

### ISSUE THREAD

**Issue by frincel** [iview/iview#229]
不知道 Dropdown 下拉菜单 是否可以增加多选并且分组显示的功能？

**Comment by rijn** [comment]
divided可以显示分割线。为什么dropdown需要多选？用Select？

**Comment by frincel** [comment]
因为业务需要，有时需要对一对多的数据建立关系，并且多的那一边也就是希望在Dropdown中显示的数据本身也是有层级关系的。它们是根据父级进行分组的。所以这样的也不适合用checkbox解决

**Comment by rijn** [comment]
或许树形组件更合适一点？个人感觉Dropdown更适用于一对一单次点击的场景。

**Comment by frincel** [comment]
但是我个人觉得这个功能也许在Dropdown中是可以兼容的？可以增加一个是否多选的标志。但是这样对于关闭的判定就需要修改。

**Comment by icarusion** [comment]
Dropdown 是一个很灵活的组件，如果用到 DropdownItem，那它就是单选，以及级联单选（嵌套使用），如果不使用 DropdownItem，那里面是什么，完全可以自定义，多复杂的都可以自己实现。所以你可以参照文档 custom 触发方式来自己封装需要的业务组件。
