### ISSUE TITLE
[Bug Report]Select set filterable=true, Select can not form reset

### ISSUE THREAD

**Issue by chy2z** [iview/iview#2290]
### Environment
window 7、Google Chrome，Vue.js v2.5.1，iview v2.6.0

### Reproduction link
[https://jsfiddle.net/7zbug7ug/1/](https://jsfiddle.net/7zbug7ug/1/)

### Steps to reproduce
 this.$refs[name].resetFields()

### What is expected?
Select can reset

### What is actually happening?
Select can not form reset

**Comment by chy2z** [comment]
When I find that the value is numeric type，I found it written  city:undefined  ，And then reset it 。But the other is not, this should be under the unified style of writing。

**Comment by daiyanze** [comment]
After going through your example code, I found some errors on it. Anyway they are minor issues. I think the source code about `Form` and `Select` is working finely on `filterable` set. However the biggest problem is that the `formValidate.city` shouldn't be a `null`. If you use a blank quote instead it will automatically work out.

Please have a look at my fixes.
https://jsfiddle.net/7zbug7ug/3/

Good luck!

**Comment by SergioCrisostomo** [comment]
I suppose @daiyanze 's suggestion solved this issue. Closing.
If I'm wrong please comment or re-open.
