### ISSUE TITLE
The value property of the [Feature Request]Select-Option component adds the Boolean type, or removes the constraint


### ISSUE THREAD

**Issue by ethan-luo** [iview/iview#2295]
### What problem does this feature solve?
现在的Select-Option组件的value属性只接受String/Number，这种限制是无意义的且会在使用时导致很多问题。
因为业务需要使用下拉框选择boolean等其他类型数据，此时需要在字符串和Boolean类型之间转来转去十分蛋疼！！！

比如：某个字段需要boolean类型数据，但是非必填可以为null，Switch组件没有null状态，而Select又不支持Boolean！
false!==null/undefind

### What does the proposed API look like?
去掉Option的Type约束，或者加上Boolean、Date

**Comment by daiyanze** [comment]
的确有很多情况下我们需要 boolean 或者 date类型的数据，不过这两种类型其实都可以转换为字符串。
但是约束select-option的value属性应该不是没有意义，因为在filterable的情况下需要在input当中获取用户输入的字符串再进行与data（有可能需要类型转换）的比较。这个时候用户输入的内容就存在合法与否的不确定性，因而filter结果比较容易出error。
所以我觉得这是没有更好的办法时的办法，哈哈😄。

@icarusion 你觉得追加类型对filterable那部分影响大不？

**Comment by icarusion** [comment]
为什么不直接使用 Radio、Checkbox、Switch 呢，它们更适合这样的场景，而 Select 不是。
