### ISSUE TITLE
[Bug Report]Error display multiple Select controls when setting up multiple

### ISSUE THREAD

**Issue by viewweiwu** [iview/iview#2296]
### Environment
win10 / chrome 60.0.3112.101 / vue

### Reproduction link
[https://codepen.io/viewweiwu/pen/JrmWLP?editors=1010](https://codepen.io/viewweiwu/pen/JrmWLP?editors=1010)

### Steps to reproduce
点击切换 Checkbox 两次就会出现。

### What is expected?
正常的显示 Select

### What is actually happening?
Select 框之外显示 ‘请选择’

**Comment by daiyanze** [comment]
确实会出现所说的状况，不过貌似可以用如下的方法解决
The strange situation has been confirmed. It seems that the '请选择' phrase wouldn't go away after switching to another ``` <i-select></i-select>``` tag. But you may follow my solution below for a quick solution.
https://codepen.io/daiyanze/pen/qVOQOE

**Comment by icarusion** [comment]
You can set a `key`:
```vue
<Select v-if="show" key="a" v-model="model10" multiple>
    <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
</Select>
<Select v-else key="b" v-model="model1">
    <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
</Select>
```
