### ISSUE TITLE
限制高度的table在modal中最后一行被遮住

### ISSUE THREAD

**Issue by yajore** [iview/iview#231]
### iView 版本号
0.9.16

### Vue 版本号
1.0.26

### 能够复现问题的在线示例

https://codepen.io/anon/pen/QdWKOE

### 复现步骤

modal弹出的table，最后一行没有显示

**Comment by rijn** [comment]
iTable加个
```
v-if="modal1"
```
modal显示后再渲染

**Comment by icarusion** [comment]
@rijn 不建议在 Modal 内的 slot 加 v-if，这样在其它情况下，是会闪动的，体验不好。应当是开发者来控制 slot 的逻辑。
