### ISSUE TITLE
[Bug Report]select in the pop-up box, if the pop-up box causes the page to have the scroll bar, the scroll bar will lead to the select drop-down box dislocation after scrolling


### ISSUE THREAD

**Issue by gexiaoyun** [iview/iview#2311]
### Environment
VUE2.0

### Reproduction link
[https://codepen.io/gexiaoyun/pen/JOGLMo](https://codepen.io/gexiaoyun/pen/JOGLMo)

### Steps to reproduce
在modal模块中置入多个select控件，让页面出现滚动条，然后滚动滚动条后再点击select，会出现select下拉框错位，select会随着滚动条滚动而变换top位置

### What is expected?
select滚动条位置固定

### What is actually happening?
select滚动条位置错位

**Comment by yanjunz** [comment]
I got the same issue with 2.6.0. But there is no problem in 2.0.0-rc.17

https://jsfiddle.net/dx8n19mn/1/

**Comment by daiyanze** [comment]
估计是最近新加的功能引起的一些css效果改变。加transfer之后应该可以解决。


> transfer | 是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果

```vue
<Select v-model="visitForm.rvTypeFir" transfer style="width: 130px"> 
   <Option value="yes" key="0">满意</Option>
   <Option value="no" key="1">不满意</Option>
</Select>
```

**Comment by yanjunz** [comment]
这是加了transfer才会有的问题，估计是popup的窗体滚动之后，Select的dropdown位置由于是transfer到父级才可能出现计算位置不对的问题，如果没有transfer到父级则不会受父级滚动影响。

**Comment by daiyanze** [comment]
我是觉得加了transfer这时候transfer的position变为absolute，才可以让dropdown正确地追随父级滚动。不过，正常情况下，最好还是不要让modal滚动为好。而且，经个人测试，select过多并且数据量稍微上来了之后会产生性能瓶颈（毕竟目前iView是以桌面为主）。
话说回来，你提供的例子里面木有transfer。

**Comment by SergioCrisostomo** [comment]
@daiyanze if you could add  a jsFiddle using `transfer` would be great. I also think that fixes this issue.
