### ISSUE TITLE
[Bug Report]The Page component of simple mode problem

### ISSUE THREAD

**Issue by totchina** [iview/iview#2314]
### Environment
win7      chrome:57.0.2987.110      Vue2.5.2    iview2.6

### Reproduction link
[https://codepen.io/totchina/pen/GOoXRQ?editors=1010#0](https://codepen.io/totchina/pen/GOoXRQ?editors=1010#0)

### Steps to reproduce
在simple模式下，删除input框中内容，回车翻页，input中出现NaN，且无法使用左右箭头翻页，
而在普通模式下，会自动跳转到第一页

### What is expected?
不出现NaN,跳转到第一页

### What is actually happening?
input中出现NaN，且无法使用左右箭头翻页

**Comment by icarusion** [comment]
#1575
