### ISSUE TITLE
[Bug Report]Error in directive transfer-dom inserted hook: "TypeError: cannot obtain attributes that are undefined or referenced by null" transfer""


### ISSUE THREAD

**Issue by z736830300** [iview/iview#2315]
### Environment
win7/ie10/vue 2.3.3

### Reproduction link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
页面加载就出现bug

### What is expected?
支持transfer属性

### What is actually happening?
不支持

**Comment by icarusion** [comment]
未来不支持低版本 ie

**Comment by limodou** [comment]
多少算低？ie9算吗？
