### ISSUE TITLE
[Bug Report] on the QQ browser 9.6.5 version of the DatePicker component could not be used


### ISSUE THREAD

**Issue by xulei131401** [iview/iview#2320]
### Environment
windows7/QQ浏览器9.6.5/vue2.2.6

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
打开https://www.iviewui.com/components/date-picker，点击任意一个示例组件使用，发现日期无法被选择

### What is expected?
期望能正常使用该组件

### What is actually happening?
不能使用

**Comment by icarusion** [comment]
#2122

**Comment by xulei131401** [comment]
主要是日期范围组件不能使用，单个日期组件是可以的

**Comment by woleicom** [comment]
我也碰到了相同的问题 ，然后我把iview升级到最新后可以了，但不知道是不是这个问题  感觉跟浏览器也有关，只是我修复过程没有记录，不确定是内核问题还是框架版本问题，因为我中途换了好多版本
