### ISSUE TITLE
[Feature Request] Responsiveness: roadmap and ideas

### ISSUE THREAD

**Issue by SergioCrisostomo** [iview/iview#2323]
iView team has been doing a lot of good work fixing and improving the iview components.
`2.6.0` is the latest shiny version 🎉 

We didn't have much time to handle other aspects like responsive design. This issue is a discussion for gathering ideas about that. 

What are your ideas about this? Welcome to comment on what steps you would like to see being taken and what components have responsive problems so we can make a roadmap and go fix it together! Some things are maybe simple fixes. Other things we need to discuss and plan with time.

Some related issues that might have important feedback: #632, #816, #1373, #1607, #1891, #2130

We are very happy to have help from you!

**Comment by ejfrancis** [comment]
I'm glad this is being officially discussed, iView has potential to be a very solid cross-device toolkit.

There are a couple things I think would be required to create a nice responsive development experience similar to other frameworks:

### Responsive Visiblity
As outlined in #1607 iView already supports responsive grid widths across screen sizes with this options:
```html
<Col :xs='24' :md='12'>
``` 
A similar syntax to toggle visbility across screen sizes could look something like this:
```html
<div v-hidden-xs>
   I'm hidden on xs        
</div>
<div v-hidden-lg>
   I'm hidden on lg
</div>
```

### Responsive Navigation
#2318 proposes creating a set of layout components, which is a definite upgrade over the [hand-built layout examples](https://www.iviewui.com/components/layout-en). This provides an opportunity to ensure new predefined layout components play nicely with mobile devices.

I think a couple basic responsive layouts, such as the classic [collapsing top menu](https://i.ytimg.com/vi/TTbYFzAz-Lg/maxresdefault.jpg) 

![image](https://user-images.githubusercontent.com/3171352/32454901-6f00a3ca-c2d5-11e7-982c-9060f8c4a7fb.png)

and [collapsing side drawer menu](https://cdn.dribbble.com/users/12758/screenshots/1113525/trunk.js_dribbble.png). 

![image](https://user-images.githubusercontent.com/3171352/32454922-80fae90a-c2d5-11e7-8c64-e46d96fb60d0.png)

Perhaps this could be handled with an API via the layout components like this?

```html
<Layout>
  <Header />
  <NavigationDrawer />
  <Content />
  <Footer />
</Layout>
```

or

```html
<Layout>
  <Header />
  <Navigation :type='drawer' />
  <Content />
  <Footer />
</Layout>
```

**Comment by SergioCrisostomo** [comment]
So, with `2.7.0` out today we added this to the next release. 

About components that might need responsive adjusting, a first suggestion/discussion:

CSS:

 - Table (needs to be tested and decide what to fix, mobile viewport limits complex tables, so maybe we just support desktop and tablet?)

Touch events:

 - Slider (fix suggested in #2393)
 - Carousel 
 - Scroll (already implemented but needs testing/fine tuning)

**Comment by MRZMUH001** [comment]
- date picker will need adjustments

**Comment by SergioCrisostomo** [comment]
@MRZMUH001 can you be more specific? Please point out specific things you see there is a need to fix/improve.

**Comment by duythang** [comment]
@SergioCrisostomo: Do you have plan to implement collapsing for top menu ? Thanks
