### ISSUE TITLE
[Bug Report]I18n broken on iView website

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [iview/iview#2326]
### Environment
Ubuntu, Chrome Latest

### Reproduction link
[https://www.iviewui.com/overview-en](https://www.iviewui.com/overview-en)

### Steps to reproduce
1. Visit the iView website https://www.iviewui.com
2. Make your language as English
3. Goto the overview page https://www.iviewui.com/overview-en
4. Click on color

### What is expected?
All the content should be in English

### What is actually happening?
Only the sidebar is in English and the main content is in Chinese.

**Comment by SergioCrisostomo** [comment]
@ankitsinghaniyaz good catch! Could you please open a issue with this in the website repository (https://github.com/iview/iview-doc)? That would be great.

All help we can get making the website more friendly are very welcome!

Cheers
