### ISSUE TITLE
[Feature Request]use input in table

### ISSUE THREAD

**Issue by dengqianyi** [iview/iview#2328]
### What problem does this feature solve?
like excel,use it to input many data in one row of table.

### What does the proposed API look like?
能实现即可

**Comment by daiyanze** [comment]
可以考虑在table里面直接添加input，追加一个eventListener，当你点击（聚焦）格子的时候会变成input或者textarea让你输入内容。不过说实话table的一旦数据量上来了交互速度可能不是特别理想。
