### ISSUE TITLE
[Bug Report]Fatal Bug of TimePicker time selector in IE browser (all versions IE)

### ISSUE THREAD

**Issue by HogoZhang** [iview/iview#2330]
### Environment
所有操作系统，所有ie版本，所有vue版本

### Reproduction link
[https://segmentfault.com/q/1010000011873429?_ea=2790633](https://segmentfault.com/q/1010000011873429?_ea=2790633)

### Steps to reproduce
#TimePicker 下拉框中的时间选择滚动条在所有版本的IE浏览器下都无法点击拖动，一点击下拉框马上消失

### What is expected?
可点击，可拖动，可参考element ui的成功

### What is actually happening?
可点击，可拖动，公司业务不允许这样的明显bug

---
很明显的bug,第一次操作就能明显感觉出来，既然有滚动条就能让人拖动，要么你就不要出现滚动条

**Comment by SergioCrisostomo** [comment]
@HogoZhang hi!

I'm happy to check this out. Can you make a jsFiddle or CodePen that has problems and I can use to test?

**Comment by HogoZhang** [comment]
Code similar to iview's official website.You can go to the official website and see the modules on the TimePicker。the web is “https://www.iviewui.com/components/time-picker“。
Scroll bars cannot be clicked and dragged.
All the frameworks I've used before can do that.

**Comment by HogoZhang** [comment]
Please test with IE browser

**Comment by HogoZhang** [comment]
If you have found the problem, please reply me. Thank you

**Comment by SergioCrisostomo** [comment]
Ok! Will check, thanks.

**Comment by HogoZhang** [comment]
The problem seems to be too short to be fixed. But the company is urging me to fix this bug. So for now, I can only find a third-party plugin to solve this requirement.

**Comment by sayhei** [comment]
这个没有解决啊，目前的iview官网上的例子在ie上仍然是没法拖动
