### ISSUE TITLE
[Bug Report]DatePicker daterange seems to be only used in Google browser, other browsers (360, QQ) latest version can not be used.


### ISSUE THREAD

**Issue by DoctorWei** [iview/iview#2332]
### Environment
windows

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
选择时间段无响应

**Comment by SergioCrisostomo** [comment]
@DoctorWei  please click "save" in the jsFiddle and repost the link here. The jsFiddle you posted is empty.
