### ISSUE TITLE
[Bug Report]Collapse folding panel using V-for traversal slot part of the content can not be displayed


### ISSUE THREAD

**Issue by kerwin58** [iview/iview#2334]
### Environment
windows10/chrom  61.0.3163.100（正式版本）/ vue 2.8.2

### Reproduction link
[https://jsfiddle.net/yyrzhm46/83/](https://jsfiddle.net/yyrzhm46/83/)

### Steps to reproduce
<div id="app">
  <Collapse v-model="value2" accordion>
    <Panel
           :name="index"
           v-for="index in 3">
      <span>{{'列表'   index}}</span>
      <p slot="content">出不来</p>
    </Panel>
  </Collapse>
</div>

<script>
export default {
  data () {
    return {
      value2: 2
    }
  }

### What is expected?
<p slot="content">出不来</p> 这部分可以显示

### What is actually happening?
<p slot="content">出不来</p> 不能显示

**Comment by icarusion** [comment]
name 字段是 String，不是 Number

**Comment by belongwqz** [comment]
String也不行，把“:name”去掉，且value2改为String数组才行，那“:name”就不能用了，这个issue关的太草率了吧。
