### ISSUE TITLE
我使用2.6文档中相同的tree 树形控件案例，在本地无法完全渲染，也不报错，请问怎么解决？

### ISSUE THREAD

**Issue by Drop-DISK** [iview/iview#2335]
![image](https://user-images.githubusercontent.com/29188164/32451410-ab681ede-c351-11e7-9782-720f2e1cf2bc.png)
![image](https://user-images.githubusercontent.com/29188164/32451582-1fe79c26-c352-11e7-86f2-08b098749884.png)
![image](https://user-images.githubusercontent.com/29188164/32451598-29197e2c-c352-11e7-9c2b-9a5333d3966d.png)
图中使用的代码与官网文档完全相同

**Comment by huqiliang** [comment]
我也遇到这个问题了 @Drop-DISK 请问解决了么？

**Comment by Drop-DISK** [comment]
没有

**Comment by huqiliang** [comment]
升级就行了@Drop-DISK
