### ISSUE TITLE
[Bug Report]why the issue was closed by robot, while the issue was ceated in 'https://www.iviewui.com/new-issue', and it has no similar issues.

### ISSUE THREAD

**Issue by coolriver** [iview/iview#2347]
### Environment
win7

### Reproduction link
[https://github.com/iview/iview/issues/2344](https://github.com/iview/iview/issues/2344)

### Steps to reproduce
1. Search for the existed issue and can not find.
2. Create issue in https://www.iviewui.com/new-issue
3. Submit issue (https://github.com/iview/iview/issues/2344)
4. Issue was closed immediately by the robot.

### What is expected?
The issue can be opened and fixed

### What is actually happening?
The issue was closed immediately

**Comment by icarusion** [comment]
文档介绍的很详细，仔细看[https://www.iviewui.com/docs/guide/start#组件使用规范](https://www.iviewui.com/docs/guide/start#组件使用规范) 不要重复提交

**Comment by coolriver** [comment]
明白了，是我没有仔细看文档。谢谢提供的文档链接！ @icarusion
