### ISSUE TITLE
纵向菜单 固定宽度240px影响响应式布局

### ISSUE THREAD

**Issue by jarvan4dev** [iview/iview#235]
iview/src/components/menu/menu.vue 菜单的默认宽度好像是240px，这就导致使用Row的时候并不具备响应式，所以希望把这个去掉，或者能不能自己在vue的生命周期函数中删掉这个style="width: 240px;"，请教下这个怎么删？

**Comment by icarusion** [comment]
与业务冲突的，都建议局部覆盖css

**Comment by luckymore** [comment]
@jarvan4dev 自己覆盖不就好了

**Comment by jarvan4dev** [comment]
@luckymore 使用 !important 覆盖？
