### ISSUE TITLE
[Bug Report]Table filter, when no filter results, Vue warning: TypeError: Cannot read property'children'of undefined

### ISSUE THREAD

**Issue by lyz7805** [iview/iview#2352]
### Environment
OS：WIN 10；Browser：Chrome；Vue：2.5.0

### Reproduction link
[https://jsfiddle.net/lyz7805/uu649vm8/1/](https://jsfiddle.net/lyz7805/uu649vm8/1/)

### Steps to reproduce
1. 根据官方案例将 `data5` 中 `age` 大于25的全部修改为小于25的；
2. 然后运行；
3. 打开浏览器开发者工具；
4. 筛选数据，选择大于25的；
5. Oh！Warn！

### What is expected?
期望结果“无筛选结果”

### What is actually happening?
实际结果就是“暂无筛选结果”
**但是：**
`[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'children' of undefined"`

**Comment by 853612777** [comment]
I've had this problem, too

**Comment by YangQii** [comment]
render函数写法是否存在问题，我也遇见过这样的问题，最后发现是我的render函数写法问题

**Comment by adam-zou** [comment]
@lyz7805 the problem in the table component 'handleResize' function, [https://github.com/iview/iview/blob/d649c177e38f50ece1c1b96bc211c1fbe8161849/src/components/table/table.vue#L357](url)

**Comment by adam-zou** [comment]
@lyz7805 the problem in the table component's 'handleResize' function, [https://github.com/iview/iview/blob/d649c177e38f50ece1c1b96bc211c1fbe8161849/src/components/table/table.vue#L357](url)
