### ISSUE TITLE
[Feature Request] creates an instance of Modal using loading, such as this.$Modal.confirm, which cannot get the instance object and cannot modify the button state of the button


### ISSUE THREAD

**Issue by h330894169** [iview/iview#2359]
### What problem does this feature solve?
里面的option配置了{loading:true},想拿到实例对象，设置loading为false,重置按钮状态，

### What does the proposed API look like?
返回实例对象

**Comment by SergioCrisostomo** [comment]
duplicate of https://github.com/iview/iview/issues/2364
