### ISSUE TITLE
[Bug Report]Select components are not bound to views when they are searched for the results while grouping the data (using OptionGroup) while performing remote search


### ISSUE THREAD

**Issue by ProEditor** [iview/iview#2360]
### Environment
Windows 10 / Chrome 61.0.3163.100（正式版本） （64 位）/ Vue 2.5.2

### Reproduction link
[https://jsfiddle.net/db5tan3g/](https://jsfiddle.net/db5tan3g/)

### Steps to reproduce
1:Html中构建Select和OptionGroup(远程请求的相关属性肯定是有设置的)
2.在methods定义执行请求
3.更新data中的执行属性(各个分组的清单数据)

### What is expected?
使用多个数组保存不同的分组数据,在执行完搜索之后,能够立即在列表中体现不同分组的数据

### What is actually happening?
获取到搜索结果后,没有更新列表清单

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
