### ISSUE TITLE
[Feature Request]Modal: Escape should close the popup or trigger cancel for confirm modales

### ISSUE THREAD

**Issue by slaout** [iview/iview#2362]
### What problem does this feature solve?
Pressing Escape on a Modal does nothing.  
It should close it.  
For confirm modals, it should trigger a Cancel.

### What does the proposed API look like?
No new API: just a new UX feature.

**Comment by icarusion** [comment]
do you mean `$Modal`? the Modal component has supported ESC key to close.

**Comment by slaout** [comment]
Ah, yes, you are right: <Modal/> has working Escape key, but not $Modal.anyMethod(...)

**Comment by icarusion** [comment]
ok, will add in 2.8.0, thanks for your suggestion

**Comment by slaout** [comment]
Thanks very much for your quick reply!
