### ISSUE TITLE
[Feature Request]Message: add a render function

### ISSUE THREAD

**Issue by slaout** [iview/iview#2363]
### What problem does this feature solve?
I'd like to put a clickable link in a message.  
Eg. "The user _myself_ has been created successfully.".  
When clicking the link "myself", I'd call the VueJs router to redirect to the given user view.

### What does the proposed API look like?
this.$Message.success({  
  render: ... // Like in Table cells: this "render" will replace "content" if provided  
})

**Comment by icarusion** [comment]
finished in 2.8.0

**Comment by slaout** [comment]
Thanks very much!
