### ISSUE TITLE
请给tree增加一个属性嘛。类似element-ui的check-strictly

### ISSUE THREAD

**Issue by mrerhuo** [iview/iview#2365]
请给tree增加一个属性嘛。类似element-ui的

check-strictly
在显示复选框的情况下，是否严格的遵循父子不互相关联的做法，默认为 false

因为在做角色授权的时候，如果选中父级，子集就全部选中，这样授权的时候，我只能去做子集，然后去判断父级是否存在list里面，如果不存在，我就要把父级加进去，存在则不加。
如果加了这样的属性，我则不用判断了。选择啥就给啥功能。

**Comment by mrerhuo** [comment]
@icarusion

**Comment by yedegesong** [comment]
同求新增这个功能点
