### ISSUE TITLE
[Bug Report] now I want to add a autocomplete input box to the table, but there's no way to change the options for this input box


### ISSUE THREAD

**Issue by stduolc** [iview/iview#2366]
### Environment
62.0.3202.62 (正式版本) （64 位） (cohort: 62_62_win)

### Reproduction link
[https://jsfiddle.net/stduolc/thnqsz43/4/](https://jsfiddle.net/stduolc/thnqsz43/4/)

### Steps to reproduce
参考jsfiddle.我尝试用render来加入一个AutoComplete组件给一个table的cell.但是.这个填充的备选数组是从ajax获取的.也就是我用setTimeout模拟的那部分.实际上.只能在第一次新建vnode的时候.props可以生效.后面我变更props的data属性.并不能生效.

### What is expected?
后面我变更props的data属性.并不能生效.我希望他生效

### What is actually happening?
不生效.

**Comment by stduolc** [comment]
at last, I implemented it like this [use AutoComplete component in table cell](https://jsfiddle.net/stduolc/thnqsz43/10/)

**Comment by SergioCrisostomo** [comment]
@stduolc If I understand you correct this issue was fixed this week and will come with next release: https://github.com/iview/iview/commit/c17c5ad6cbe281eff4f606289f4c6013c75e867a

I close this now. Let me know if I understand you wrong.
