### ISSUE TITLE
[Bug Report] components Slider is not dragable in  mobile terminals

### ISSUE THREAD

**Issue by misakamaiyako** [iview/iview#2367]
### Environment
windows 7 64bit OS,IOS 8.2/chrome v62.0.3202.62/Vue.js v2.5.2

### Reproduction link
[https://www.iviewui.com/components/slider](https://www.iviewui.com/components/slider)

### Steps to reproduce
Change the explore to moblie mode or use phone to use slider,try to drag the button or click on the bar.

### What is expected?
The button is dragable or set to the value which I have clicked.

### What is actually happening?
The slider's button is not dragable ,and when I click the bar the button will move randomly.

**Comment by icarusion** [comment]
yeah, not support mobile now. #2323

**Comment by SergioCrisostomo** [comment]
I will check this out. It might be a fast fix.
