### ISSUE TITLE
The bug of the [Bug Report] date selector


### ISSUE THREAD

**Issue by stick-yi** [iview/iview#2369]
### Environment
win10 64/ie11/vue 2.4

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
时间选择器里面在选择具体时间的时候无法点击滚动条，点击后滚动条后选择时间的那个盒子会消失

### What is expected?
可以点击选择具体时间里面的那个滚动条

### What is actually happening?
时间选择器里面在选择具体时间的时候无法点击滚动条，点击后滚动条后选择时间的那个盒子会消失

---
链接是官方文档，请在ie浏览器中打开

**Comment by SergioCrisostomo** [comment]
@stick-yi this is fixed in https://github.com/iview/iview/pull/2358. It will came in the next release. Welcome to test the fix.
