### ISSUE TITLE
在model内的table宽度不一样

### ISSUE THREAD

**Issue by simple-hui** [iview/iview#237]
### 复现步骤
i-model内有个i-table table宽度不对
### 问题现象，以及你期望的结果是怎样的?
打开model的时候table正常显示
### 你估计可能的原因是什么（选填）？
初始化加载的时候计算的table的宽度 然而初始化的时候model是false的，当click事件打开model 的时候不进行计算table宽度了

**Comment by rijn** [comment]
#231
