### ISSUE TITLE
[Bug Report]Table control, after setting the height attribute, if there is no data, it will appear the width of the header style problem


### ISSUE THREAD

**Issue by tyzh** [iview/iview#2374]
### Environment
WIN7 64 / Chrome 62 / vue 2.5.3 / iView 2.6.0

### Reproduction link
[https://jsfiddle.net/q6pof6b3/](https://jsfiddle.net/q6pof6b3/)

### Steps to reproduce
在Table组件设置height，data数据为空数组[]时，出现最后一列的列宽问题

### What is expected?
等比的列宽

### What is actually happening?
最后一列消失，且样式出现问题

**Comment by icarusion** [comment]
it's not a bug.

**Comment by tyzh** [comment]
so , why is this displayed?

**Comment by tyzh** [comment]
@icarusion  so,the disappeared column is right when no data?

**Comment by Cheese-Yu** [comment]
遇见了同样的问题，加上height，header的最后一列会多出15px。应该是为了滚动条准备的，但是没有滚动条的时候，也会多出15px，会有点奇怪。
