### ISSUE TITLE
[Bug Report]modal：  modal certain size close icon didnit click in the upper right corner

### ISSUE THREAD

**Issue by sqdqiushao** [iview/iview#2376]
### Environment
iview 2.0

### Reproduction link
[https://github.com/sqdqiushao](https://github.com/sqdqiushao)

### Steps to reproduce
make modal  size close to the size of the client
.ivu-modal {     width: 92%  }   .ivu-modal-body {     height: 630px;   } }

### What is expected?
can click

### What is actually happening?
can not click

**Comment by icarusion** [comment]
example wrong
