### ISSUE TITLE
文件上传不带Cookie

### ISSUE THREAD

**Issue by bulecode** [iview/iview#2378]
上传文件的时候设置了withCredentials为true也设置了headers "Content-Type":"multipart/form-data" ，但是发送请求的时候依然是一个复杂请求会先发送OPTIONS请求，并且没有附带cookie。
`          <div class="inline-button" style="height: 20px;" title="上传文件">
            <Upload :action="_getHost() + '/assets/leadingIn'" :withCredentials= 'true' :headers="{
        "Content-Type":"multipart/form-data"
      }">
              <Icon type="upload"></Icon>
            </Upload>`

点击上传以后 得到的响应如下：
`Request URL:https://10.11.1.11:8443/assets/leadingIn
Request Method:OPTIONS
Status Code:302 
Remote Address:10.11.1.11:8443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Content-Length:0
Date:Thu, 09 Nov 2017 13:43:39 GMT
Location:https://10.11.1.11:8443/login.html
Set-Cookie:uiwebId=70a04128-472a-4ca1-b06b-b14d94d08886; Path=/; HttpOnly
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Method:POST
Connection:keep-alive
DNT:1
Host:10.11.1.11:8443
Origin:http://10.11.1.11:9090
Referer:http://10.11.1.11:9090/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36`

**Comment by hexb0307** [comment]
@bulecode 你好，我这边遇到了同样的问题，想请问一下你这个问题解决了吗？
同样的设置了:withCredentials= 'true' 但是看chrome里面还是缺少cookie

**Comment by ricpi** [comment]
@bulecode @hexb0307 问题解决了吗，同样也是设置了withCredentials缺少cookie
