### ISSUE TITLE
The performance of [Bug Report]DatePicker and TimePicker in FormItem is inconsistent with the performance of Input and other components (not 100% width display)


### ISSUE THREAD

**Issue by HarryPoint** [iview/iview#2380]
### Environment
vue 2.6.0

### Reproduction link
[https://codepen.io/HarryPoint/pen/LOxKaB?editors=1010](https://codepen.io/HarryPoint/pen/LOxKaB?editors=1010)

### Steps to reproduce
```
<Form>
<FormItem label="Input展示">
       <Input></Input>
</FormItem>
<FormItem label="修正前">
         <DatePicker  type="date" placeholder="Select date"></DatePicker>
</FormItem>
<FormItem label="修正后">       
         <DatePicker class="ivu-input-wrapper" type="date" placeholder="Select date"></DatePicker>
</FormItem>
</Form>
```

### What is expected?
表现尽量实现一致

### What is actually happening?
可以实现，需要添加类名处理

---

**Comment by daiyanze** [comment]
datepicker的宽度是固定的`@date-picker-cells-width: 196px;`，因为多数逻辑业务上不需要它沾满整行，而是需要它可以容易地使用inline或者flex来进行布局。
如果希望它沾满整行，可以覆盖它的class。
```css
.ivu-date-picker-cells {
  width: 100%; 
}
```

@icarusion datepicker长度固定是设计原则吧？

**Comment by icarusion** [comment]
是的
