### ISSUE TITLE
[Bug Report]DatePicker V-modal data will not be updated immediately

### ISSUE THREAD

**Issue by DougFlands** [iview/iview#2386]
### Environment
Chrome(62.0.3202.89),最新up to date

### Reproduction link
[https://codepen.io/Flands/pen/eevpJp?editors=1010](https://codepen.io/Flands/pen/eevpJp?editors=1010)

### Steps to reproduce
选择第一个日期
选择第二个日期
第一个日期下拉菜单不会刷新
Choose the first date
Choose the second date
The first date drop-down menu does not refresh

### What is expected?
第一个日期下拉菜单自动刷新
The first date drop-down menu automatically refreshed

### What is actually happening?
第一个日期下拉菜单不会刷新
The first date drop-down menu does not refresh

**Comment by d378935454** [comment]
同遇到这个问题，感觉是因为只有触发on-change事件，选中日期的样式才会变

**Comment by DougFlands** [comment]
突然发现，把原先绑定的数据清空再赋值，就可以了
