### ISSUE TITLE
纵向菜单不支持响应式

### ISSUE THREAD

**Issue by jarvan4dev** [iview/iview#239]
### iView 版本号
0.9.2

生成代码如下：

```
<div class="ivu-menu-submenu-title">
        <i _v-73b22949="" class="ivu-icon ivu-icon-ios-paper"></i><!--v-component-->
            内容管理
        <i class="ivu-menu-submenu-title-icon ivu-icon ivu-icon-ios-arrow-down"></i><!--v-component-->
    </div>
```

无法自己复写css来支持响应式

最好能支持响应式，并且能手动折叠

**Comment by icarusion** [comment]
简单的覆盖css即可实现，另外 iView 的 Layout 已支持响应式，可以配合使用。

**Comment by rijn** [comment]
```
<Menu class="my-menu">
</Menu>
```

**Comment by jarvan4dev** [comment]
@icarusion @rijn 不是啊，我想像阿里云那样，当屏幕缩小时，把左侧菜单变窄

展开时：
![image](https://cloud.githubusercontent.com/assets/9948677/22254741/70714eec-e290-11e6-94e8-655b267a658d.png)

收缩时：
![image](https://cloud.githubusercontent.com/assets/9948677/22254780/8649d784-e290-11e6-9987-eacdafec02c3.png)

我想收缩时通过css隐藏菜单项的text，但是好像不行啊

**Comment by rijn** [comment]
自定义menu-item class

**Comment by rijn** [comment]
[https://codepen.io/rijn/pen/qRXWGQ](https://codepen.io/rijn/pen/qRXWGQ)
