### ISSUE TITLE
[Bug Report]select component: multiple remote label-in-value input keyword query, resulting in the original selected label value is empty


### ISSUE THREAD

**Issue by songhlc** [iview/iview#2397]
### Environment
链接里有了 都能重现 

### Reproduction link
[https://codepen.io/windknow/pen/zPwJGw](https://codepen.io/windknow/pen/zPwJGw)

### Steps to reproduce
操作步骤，先选择选项一，然后输入1 获得新的查询结果，再选择选项三，则原来选择的选项label变成空了(如果输入2 返回的是全集则没有这个问题)

### What is expected?
选项label不为空

### What is actually happening?
之前选择的label变空了

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
