### ISSUE TITLE
[bug report] Tabs: TypeError: Cannot read property 'disconnect' of undefined

### ISSUE THREAD

**Issue by whwstart** [iview/iview#2401]
isInsideHiddenElement: function isInsideHiddenElement() {
            var parentNode = this.$el.parentNode;
            while (parentNode) {
                if (parentNode.style.display === 'none') {
                    return parentNode;
                }
                parentNode = parentNode.parentNode;
            }
            return false;
 }

beforeDestroy: function beforeDestroy() {
        this.observer.removeListener(this.$refs.navWrap, this.handleResize);
        this.mutationObserver.disconnect();
}
这两个函数会报TypeError，这是没有做好错误处理吧，parentNode已经寻找至最外层，没有Style属性了

**Comment by BengBu-YueZhang** [comment]
同样是这个报错
