### ISSUE TITLE
引用tabs 组件有问题报了异常

### ISSUE THREAD

**Issue by flytangyu** [iview/iview#2404]
您好，直接引用iview官网 tabs组件报了下面异常
Error in mounted hook: "TypeError: Cannot read property 'display' of undefined"

**Comment by flytangyu** [comment]
您好，直接引用iview官网 tabs组件报了下面异常
Error in mounted hook: "TypeError: Cannot read property 'display' of undefined"

**Comment by BengBu-YueZhang** [comment]
同样是这个问题，估计是组件内部的报错

**Comment by YikaJ** [comment]
@icarusion

**Comment by icarusion** [comment]
更新到 2.7.2
