### ISSUE TITLE
[Feature Request]Support for Custom Colors in Tag 

### ISSUE THREAD

**Issue by gijo-varghese** [iview/iview#2406]
### What problem does this feature solve?
The tags plugin works really cool. However, it's lacking a feature that would make it great. Can we add support for custom colors in props?

Currently, it only supports blue, green, red and yellow

### What does the proposed API look like?
```
<Tag  color="#F8AF82" closable>Hello</Tag> 
<Tag  color="#FAFAFA" closable>Hello World</Tag>
```

**Comment by gijo-varghese** [comment]
@SergioCrisostomo  @icarusion what are your thoughts?

**Comment by SergioCrisostomo** [comment]
I think its a good functionality. Maybe using the iView colors https://www.iviewui.com/components/color-en.

@icarusion what do you think?

**Comment by gijo-varghese** [comment]
My use case, I want to assign tags for each user in a chat dashboard. So if each tag its own color that would be great!

@SergioCrisostomo I think the restriction of 4 colors is for UI consistency. If we use iviewui colors, it also has a few colors right?

![screenshot from 2017-11-14 07-53-10](https://user-images.githubusercontent.com/23092846/32759754-25ed8c88-c911-11e7-901a-d9d7d88ae2fa.png)

**Comment by icarusion** [comment]
will support in 2.8.0

**Comment by gijo-varghese** [comment]
@icarusion can I expect it soon? Any approximate date?

**Comment by icarusion** [comment]
maybe 2-3 weeks

**Comment by gijo-varghese** [comment]
Awesome. Thanks :)

**Comment by gijo-varghese** [comment]
@icarusion one more doubt in Tag component. How can I add a click event to a Tag? 

For e.g.:
`<Tag color="blue" @click="addTag('hello')">Hello</Tag>`

**Comment by SergioCrisostomo** [comment]
@icarusion maybe we should add `on-click` and `on-change` also?

**Comment by SergioCrisostomo** [comment]
Oh, `on-change` is already implemented, just no documented.

**Comment by gijo-varghese** [comment]
@icarusion what does `on-change` do? Trigger an event when the content of the `Tag` change?

**Comment by icarusion** [comment]
You can use `.native` like
```vue
<Tag @click.native="handle">
```

**Comment by gijo-varghese** [comment]
Awesome. Thanks

**Comment by gijo-varghese** [comment]
@icarusion I can't find it in docs, is it ready?

**Comment by Cookizza** [comment]
It seems like an oversight that the Tag component now accepts custom background colors, but we have no way to influence the text color. Any chance of this being added?
