### ISSUE TITLE
The [Bug Report]Select component when there is no choice, drop down is a thin, no prompt text.


### ISSUE THREAD

**Issue by fekata** [iview/iview#2408]
### Environment
mac 2.60

### Reproduction link
[https://jsfiddle.net/yyrzhm46/89/](https://jsfiddle.net/yyrzhm46/89/)

### Steps to reproduce
看重现链接

### What is expected?
不是可以增加类似 not-found-text 的配置，
例如  not-item-text   默认值：无数据

### What is actually happening?
当Select组件当没有选择项，点击之后，下拉选项是一个细条（刚开始以为是bug）

**Comment by huziyang410** [comment]
同样遇到这个问题了

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
