### ISSUE TITLE
你们不应该在$Modal弹出对话框的时候给body添加css样式

### ISSUE THREAD

**Issue by ChiHai-Chuck** [iview/iview#241]
$Modal弹出对话框时，会给body增加了两个样式：padding-right: 17px; overflow: hidden;

这样会引起一些问题，例如网页上原先就有一个全屏的半透明遮罩和一个fixed的悬浮层，然后弹出对话框，这时会因为body增加了padding-right: 17px;样式，而导致原先的悬浮层发生一次17px的位移。

而实际上添加这两个样式的目的是为了防止鼠标可以进行网页拖动和滚动，这个完全可以做为可选，因为有些情况下，往body直接添加样式是很不明智的。或者可以改为禁用body的mousewheel和scroll默认事件。

**Comment by rijn** [comment]
Adding padding to body or html is the most efficient way to prevent scrolling. We would add a property to make it selectable.

**Comment by icarusion** [comment]
@rijn suggest change `scrolling` to `scrollable`
