### ISSUE TITLE
[Bug Report]input-number precision error


### ISSUE THREAD

**Issue by fordongu** [iview/iview#2417]
### Environment
WIN10/Chrome/62.0.3202.62 / VUE-2.7.2

### Reproduction link
[https://jsfiddle.net/Lzqnnkor/](https://jsfiddle.net/Lzqnnkor/)

### Steps to reproduce
设置 input-number 精度为2，在文本框输入100

### What is expected?
能够正常的输入

### What is actually happening?
在输入第2位的时候文本框变成了10.00

**Comment by SergioCrisostomo** [comment]
@fordongu  I think in this case the behaviour is expected.

Since you have `:max="10"` numbers above `10` will not be accepted. And is you have invalid number, like `10.000` it will format correct when the `change` event happens.

I'm closing this but please comment i you think I'm wrong.

**Comment by leopen-hu** [comment]
why not try to change the max? it works error still.

**Comment by fifteenzhang** [comment]
@SergioCrisostomo 
Even if remove the limit,the error still exist.Just Input 100

**Comment by fifteenzhang** [comment]
#2920
