### ISSUE TITLE
[Feature Request]Hope to provide form error message interface

### ISSUE THREAD

**Issue by fghpdf** [iview/iview#2422]
### What problem does this feature solve?
---
I noticed the document's code point user the error by `this.$Messgae.error('email error || pass error')`

But I hope to change form item's error to touch off the error message rather than alert

Like this
[![FsDDn.md.png](https://s1.ax2x.com/2017/11/15/FsDDn.md.png)](https://simimg.com/i/FsDDn)

**Not this**

![FsBpE.png](https://s1.ax2x.com/2017/11/15/FsBpE.png)

I found the form code is watch error change to display error message

Maybe you can offer an interface to display error message without validate

### What does the proposed API look like?
---
`this.$refs[name].displayError(userName, 'error message')`

first parameter is form item name,

secone parameter is the error message you want to display

**Comment by imanhodjaev** [comment]
@fghpdf I think you can set `:error` property for `FormItem`, did you try it?

**Comment by fghpdf** [comment]
@imanhodjaev like this `this.$refs.loginForm.$children[0].error = 'hahah'` ?

it can work

But this way is not recommended by Vue
