### ISSUE TITLE
Select display dislocation in [Bug Report]modal


### ISSUE THREAD

**Issue by 531431988** [iview/iview#2423]
### Environment
WIN10 / 最新谷歌 / vue 2.5.2

### Reproduction link
[https://jsfiddle.net/tcmL0j9x/](https://jsfiddle.net/tcmL0j9x/)

### Steps to reproduce
弹窗打开后，滚动窗口滚动条，然后打开下拉就错位，在浏览器边缘都可能错位，下拉显示后，滚动滚动条也会出错这种问题

### What is expected?
位置不变

### What is actually happening?
下拉位置可到处变动

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/32815494-505a32ee-c9ef-11e7-942f-2defa93a2118.png)

**Comment by icarusion** [comment]
It runs perfect in my computer, can you try to use `transfer` prop to `Select`? You can have a try and if there are still have problem, please reopen this issue.
