### ISSUE TITLE
Dropdown display error in fixed layer

### ISSUE THREAD

**Issue by rijn** [iview/iview#243]
### iView 版本号
0.917

Style top of dropdown would be changed when scrolling. This feature should be disabled when it is under a fixed layer.

**Comment by rijn** [comment]
![image](https://cloud.githubusercontent.com/assets/6976367/22481798/1ed167a8-e7bc-11e6-87e6-43aaa921c001.png)

**Comment by icarusion** [comment]
Can you show me a demo to debug?
