### ISSUE TITLE
[Bug Report]InputNumber 数字输入框，设置最小值

### ISSUE THREAD

**Issue by zixuzhang** [iview/iview#2431]
### Environment
ubuntu/chrome/vue2.5.3

### Reproduction link
[https://jsfiddle.net/oyasdnez/2/](https://jsfiddle.net/oyasdnez/2/)

### Steps to reproduce
点击数字输入框的增长箭头

### What is expected?
期望数值从设置的最小的值开始增长

### What is actually happening?
实际上数值还是1开始增长

**Comment by icarusion** [comment]
用法不对。
