### ISSUE TITLE
关于文档一点点排版问题

### ISSUE THREAD

**Issue by hmdeng110** [iview/iview#244]
不好意思，我只是有点强迫症；浏览器：版本 55.0.2883.87，屏幕分辨率：1600*900

    我发现文档点组件的表格，

1，右侧有个目录，鼠标放上去后会出现个目录框，当滚动条在最顶上的时候，这个目录框比左侧的内容区高了一个像素；我觉得原先设计的想法应该大概可能是想对齐的；

2，同样是该目录显示；“目录”两字在表格组件是横向排列的，当切换到比如输入框组件中的时候，“目录”两字却是竖排的，鼠标放上去的时候才会横排；我尝试了一下，或许可以考虑将“目录”两字的容器替换为文本容器span；

3，同样是该目录显示组件，未能设置一个合适的z-index值，导致在部分页面会和左侧区域的内容发生遮挡现象，具体可以参照一下按钮页面
![image](https://cloud.githubusercontent.com/assets/15642931/22617058/66b07d06-eaf6-11e6-835e-8663b348ea7e.png)

3，在表格组件页面的API上面有个高级示例，有三个按钮，任意一个点进去后，鼠标放置在中间滚动，黑色背景会被滚出当前显示区域，我觉得原先设计的想法应该不滚动的；很抱歉，能力有限，我看不出可能是什么原因造成的，看起来是用了弹窗组件，如果是的话是不是当弹窗组件都有可能遇到这个问题
![image](https://cloud.githubusercontent.com/assets/15642931/22617075/a7b53a76-eaf6-11e6-83cf-d80899494ce5.png)

**Comment by icarusion** [comment]
貌似是浏览器的问题。
