### ISSUE TITLE
After [Feature Request]Tree uses render, how to define the class attribute of elements under render


### ISSUE THREAD

**Issue by Gzoye** [iview/iview#2440]
### What problem does this feature solve?
做系统多版本皮肤切换控制的时候  需要用class控制tree下元素的样式。看api上的方法，只能定义元素的style属性

### What does the proposed API look like?
增加如何修改class的说明

**Comment by SergioCrisostomo** [comment]
This is [Vue.js API](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth), not iView. You can use `class: ['class1', 'class2']` or objects with boolean values, in the render function. 
Example: https://jsfiddle.net/vfns2qu2/

**Comment by Gzoye** [comment]
domProps:{
   className:"ivu-btn-primary",
}
can solve the problem in this way ~
