### ISSUE TITLE
[Feature Request]Suggesting add visible function in Collapse.

### ISSUE THREAD

**Issue by B1anker** [iview/iview#2442]
### What problem does this feature solve?
When I add a Select in the Collapse and I click the Select, the Select's options will be hidden.So in some conditions, it will be useful for Collapse being visible.

### What does the proposed API look like?
<Collapse>
     <Panel :visible="true"></Panel>
</Collapse>

**Comment by SergioCrisostomo** [comment]
@B1anker can you add a jsFiddle example for this behaviour?

**Comment by B1anker** [comment]
@SergioCrisostomo https://jsfiddle.net/yyrzhm46/107/
I created a demo but it looked like parse error.
Could you resolve the error?

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
