### ISSUE TITLE
After [Bug Report] is set up, datepicker can not be used and I18N is wrong!


### ISSUE THREAD

**Issue by jarden-liu** [iview/iview#2445]
### Environment
macOS High Sierra 10.13.1/chrome 55.0.2883.87/Vue@2.5.4

### Reproduction link
[https://jsfiddle.net/jardenliu/Lzy33zb9/](https://jsfiddle.net/jardenliu/Lzy33zb9/)

### Steps to reproduce
点开链接，进入调试。run，点击时间选择器，即可在控制台看到报错

### What is expected?
正常使用选择器

### What is actually happening?
报错，无法正常使用

**Comment by SergioCrisostomo** [comment]
Why do you have

```
Vue.locale = function (){
 
};
```
?

**Comment by icarusion** [comment]
文档漏写了一句
`iview.i18n((key, value) => i18n.t(key, value))`
，完整的示例应该是:
```js
Vue.locale = () => {};
    const messages = {
        en: Object.assign({ message: 'hello' }, iview.langs['en-US']),
        zh: Object.assign({ message: '你好' }, iview.langs['zh-CN'])
    };

    const i18n = new VueI18n({
      locale: 'en', // set locale
      messages, // set locale messages
    })

    iview.i18n((key, value) => i18n.t(key, value))

    new Vue({
        el: '#app',
        i18n: i18n,
        data: {
            visible: false,
            date: ''
        },
        methods: {
            show: function () {
                this.visible = true;
            }
        }
    })
```

**Comment by jarden-liu** [comment]
console error: iview.i18n is not a function

**Comment by jarden-liu** [comment]
@icarusion console error: iview.i18n is not a function

**Comment by jarden-liu** [comment]
@icarusion 在 Webpack 中如何引用呢？

**Comment by jarden-liu** [comment]
@icarusion 已解决，万分感谢

**Comment by jarden-liu** [comment]
@icarusion 找到设置方法了，感谢~
```javascript
Vue.use(iView, {
    i18n: (key, value) => i18n.t(key, value)
});
```

**Comment by melon** [comment]
文档应该最好尽早更新，找了好久才找到这个问题的解决方式..

**Comment by inroam** [comment]
我也是找了好久才找到解决办法~~，感谢~~~

**Comment by jarden-liu** [comment]
你们算幸福啦，能找得到。我当初还看了一遍源码！希望大腿能及时更新文档

**Comment by Xotic750** [comment]
I had this issue when using `Select`.

https://jsfiddle.net/Xotic750/9gz3opr7/

This fixed the problem:

`iview.i18n((key, value) => i18n.t(key, value))`

I don't know why as I can't understand Chinese?

I don't see this in the docs?

https://www.iviewui.com/docs/guide/i18n-en

**Comment by jarden-liu** [comment]
@Xotic750 emm..   Because the author forgot  to write the key code in docs.

**Comment by SergioCrisostomo** [comment]
@jarden-liu if you are aware of missing information in the docs you are really welcome to send a PR 😺 
This is a community project and together we are strong 👍

**Comment by jarden-liu** [comment]
@SergioCrisostomo yoo~~ If I had free time, I would do it. I think iView is a amazing project，I hope it's getting better and better. At same time, why iView does not have a mobile version ??

**Comment by suntao9108** [comment]
我发现如果DatePicker shortcuts 的text 使用了this.$t('key') 切换国际化不会改变，必须F5刷新才改变，有没有好的办法可以不刷新？

**Comment by zhoujiamin** [comment]
赶紧补充文档，谢谢
