### ISSUE TITLE
Select组件在filterable的时候工作异常

### ISSUE THREAD

**Issue by billxc** [iview/iview#246]
### iView 版本号
官网Demo版本

### 操作系统/浏览器 版本号
win10/Chrome 54

### Vue 版本号
官网Demo版本

### 能够复现问题的在线示例

https://www.iviewui.com/components/select
在线Demo的最后一个filterable 的Select

### 复现步骤
在初始情况下，在一个filterable Select中选择一个值，
再次点开Select

### 问题现象，以及你期望的结果是怎样的?
Select 的可选选项只有一个，是当前用户选择的值
在输入的地方删除现有内容后，可选选项恢复正常
![bug](https://cloud.githubusercontent.com/assets/5867141/22627040/76656b6c-ebf5-11e6-86ea-366830c1f46c.gif)

### 你估计可能的原因是什么（选填）？
Select 组件使用了当前用户选择的值作为过滤条件进行了搜索

**Comment by icarusion** [comment]
就是这样的。
