### ISSUE TITLE
[Bug Report]Form cannot verify the NumberInput component properly. The NumberInput component enters an exception, and the click event can still be triggered in the DropdownMenuItem disabled state


### ISSUE THREAD

**Issue by aaron0713** [iview/iview#2476]
### Environment
win10/chrome62.0.3202.89/vue 2.4

### Reproduction link
[https://jsfiddle.net/yyrzhm46/113/](https://jsfiddle.net/yyrzhm46/113/)

### Steps to reproduce
如连接所示，
Form可以通过简单的rule验证input组件，但是无法正常验证numberInput组件，需要手动写验证方法。

NumberInput组件无法正常输入，在输入第二个数字时候，光标定位到末端，由于小数位数限制，无法继续输入。需要手动重新定位光标。

DropdownMenuItem再disabled状态下依然可以触发click事件

### What is expected?
Form可以验证
NumberInput组件输入优化
DropdownMenuItem再disabled状态下不触发Click事件

### What is actually happening?
如上描述

**Comment by luffyzhao** [comment]
加一个 type:'number' 就Ok了 
[jsfiddle](https://jsfiddle.net/yyrzhm46/1788/)
