### ISSUE TITLE
[Bug Report]transfer component : check all doesn't trigger the "on-selected-change" event

### ISSUE THREAD

**Issue by QJX** [iview/iview#2478]
### Environment
all

### Reproduction link
[https://www.iviewui.com/components/transfer](https://www.iviewui.com/components/transfer)

### Steps to reproduce
...

### What is expected?
when check all should trigger the "on-selected-change" event

### What is actually happening?
 doesn't trigger the "on-selected-change" event

**Comment by yjk0306** [comment]
2323
