### ISSUE TITLE
[Bug Report]AutoComplete on-change event is not working

### ISSUE THREAD

**Issue by nikitam747** [iview/iview#2489]
### Environment
ubuntu 16.04, Version 61.0.3163.100(chrome)

### Reproduction link
[https://jsfiddle.net/nikita747/89kb1emm/](https://jsfiddle.net/nikita747/89kb1emm/)

### Steps to reproduce
*** AutoComplete on-change event is not working ***

### What is expected?
every time whenever input or option change the event called and get result

### What is actually happening?
event only called at first time after that its not calling

**Comment by Superman379** [comment]
Do not use v-model when u need use on-change event.
it has a bug.

**Comment by fengluhome** [comment]
Please upgrade to the latest version.
