### ISSUE TITLE
[Bug Report]table set height , last column render height error

### ISSUE THREAD

**Issue by llccing** [iview/iview#2491]
### Environment
windows7 / chrome  62.0.3202.94 （64 位）/ latest

### Reproduction link
[https://jsfiddle.net/lcf33123/8y95ad2h/3/](https://jsfiddle.net/lcf33123/8y95ad2h/3/)

### Steps to reproduce
on jsfiddle

### What is expected?
if i don't set last column width , the table render normal

### What is actually happening?
last column height error, and table height error

**Comment by icarusion** [comment]
fixed in new version
