### ISSUE TITLE
[Bug Report]select and page components drop-down selection bottom can not automatically change to automatic pull down


### ISSUE THREAD

**Issue by EnoND** [iview/iview#2492]
### Environment
2.7.3

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
把select组件滚动至屏幕底端，点击选择，不能自动向上伸展，无法选择全部

### What is expected?
可以触底 向上弹出

### What is actually happening?
不能向上弹出

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
