### ISSUE TITLE
[Feature Request]select can't be displayed up to the bottom of the screen


### ISSUE THREAD

**Issue by suntao9108** [iview/iview#2493]
### What problem does this feature solve?
显示select的时候每次都是固定往下显示，特别是在分页的时候显示加载就会出问题.

### What does the proposed API look like?
加入自动上下显示数据

**Comment by wanglyaaa** [comment]
+1

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
