### ISSUE TITLE
[Bug Report]Change carousel v-model can't change the carousel-item

### ISSUE THREAD

**Issue by mokeyjay** [iview/iview#2494]
### Environment
Win10 x64 1703 / Chrome 62 / Vue2.5.8

### Reproduction link
[https://jsfiddle.net/mokeyjay/b5cjpbeh/6/](https://jsfiddle.net/mokeyjay/b5cjpbeh/6/)

### Steps to reproduce
- Add `Carousel`
- Add some `CarouselItem` to `Carousel`
- Add `v-model` attr to `Carousel`
- Change the `v-model` value
- value and dots is changed, but `CarouselItem` not

### What is expected?
`CarouselItem` change with value and dots

### What is actually happening?
value and dots is changed, but `CarouselItem` not

**Comment by icarusion** [comment]
fixed
