### ISSUE TITLE
通过链接进入后台，无法将相对应的menu-item激活！

### ISSUE THREAD

**Issue by jarvan4dev** [iview/iview#250]
### Vue 版本号

通过链接进入后台，无法将相对应的menu-item激活！比如说我有一个菜单项是个人中心，我通过‘/person’进入，希望此事menu-item激活。

**Comment by icarusion** [comment]
需要自行判断路由，设置activity-key

**Comment by jarvan4dev** [comment]
@icarusion 请问下这个activity-key如何动态设置？

**Comment by rijn** [comment]
Add a watcher to $router

**Comment by jarvan4dev** [comment]
@rijn 我已经过去了路径了，但是不清楚如何更新key

**Comment by rijn** [comment]
```
<Menu :active-key="activeKey">
```

```
export default {
    data () {
        return {
            activeKey: ''
        };
    },
    watch: {
        '$router': ...
    }
};
```

Make sure your version is 0.9.17 or later. It was a bug that has been patched in 0.9.17.

**Comment by jarvan4dev** [comment]
@rijn 不是特别明白，比较笨，为什么要监听$router啊

**Comment by rijn** [comment]
It depends. I inserted a router-container at the same level of the menu, thus every time the router changes, the menu can be changed automatically.

**Comment by jarvan4dev** [comment]
what means same level?  in the same component？or in two components which are at same level?

**Comment by rijn** [comment]
I used router like this way
```
<Menu :active-key="pageKey">...</Menu>
<router-view></router-view>
```
Then It would be easy to set up a watcher for router
```
watch: {
    '$route': {
        deep: true,
        handler: function (to, from) {
            this.pageKey = to.path;
        }
    }
}
```

**Comment by seminelee** [comment]
`<Menu mode="horizontal" :active-key="activeKey">`

```
import {router} from './../routes';

export default{
        ready(){
            this.activeKey = router._currentRoute.path;
        },
        data(){
            return{
                crawlerKey: ''
            }
        }
}
```

**Comment by qinghua5453** [comment]
难以理解这点。上面说的watch 我没法监听到路由变化 来改变menu 的active，一次都监听不到，但如果不是路由监听，就只是data里面的一般属性，绑定到input里面去，只要v-model里面内容有变化，watch就能监听到。so，感觉router这里是难点。另外，我用的是嵌套路由，所有mounted只会执行一次，不会执行多次。
