### ISSUE TITLE
[Bug Report] looks like the MENU function, and the Sub submenu cannot be deployed under the mobile QQ browser or UC browser.


### ISSUE THREAD

**Issue by liweiyuVIE** [iview/iview#2500]
### Environment
oppo r9s 安卓手机QQ浏览器，vue2.5.2

### Reproduction link
[https://itwkw.com/article/4](https://itwkw.com/article/4)

### Steps to reproduce
好像MENU功能，在手机QQ浏览器，UC浏览器下面Sub子菜单无法展开。

### What is expected?
手机QQ浏览器可以展开子菜单，https://itwkw.com/article/4 如登陆窗口无法展开子菜单。我进入https://www.iviewui.com/components/menu，也是无法展开子菜单的。当使用手机QQ浏览器或UC的时候。PS:但是使用微信里面可以展开。

### What is actually happening?
menu可以兼容QQ浏览器

**Comment by myxingke** [comment]
可以展开呀iview不适用于移动端呀！

**Comment by liweiyuVIE** [comment]
希望可以兼容移动端啦。还有Breadcrumb好像也有点问题，Breadcrumb的separator在手机QQ浏览器，UC浏览器下面没有显示。
