### ISSUE TITLE
The selected value of the [Bug Report]select component label generation will not change


### ISSUE THREAD

**Issue by luffyzhao** [iview/iview#2507]
### Environment
Vue.js v2.5.1

### Reproduction link
[https://jsfiddle.net/hzfpyvg6/206/](https://jsfiddle.net/hzfpyvg6/206/)

### Steps to reproduce
label的选中值没有改变！！

### What is expected?
label的选中值会和label列表值一样

### What is actually happening?
label的选中值会和label列表值一样

---
label的选中值没有改变！！

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
