### ISSUE TITLE
select可搜索下赋值无效

### ISSUE THREAD

**Issue by huanglong6828** [iview/iview#251]
### iView 版本号
0.9.17

### 能够复现问题的在线示例
http://runjs.cn/code/m2fhsphf

**Comment by YikaJ** [comment]
看了源码，发现问题了。 在 [commit：d509d2b2af0870b708805137e569ddd59d93c83d](https://github.com/iview/iview/commit/d509d2b2af0870b708805137e569ddd59d93c83d#diff-c8ad2c3a7f97eb9228d5f461e5eb59c1) 中，作者把 ready 函数改成了 vue2.0 的compiled 函数，导致初始化失效。
