### ISSUE TITLE
[Feature Request]PopTip

### ISSUE THREAD

**Issue by StanislavBerezin** [iview/iview#2511]
### What problem does this feature solve?
The suggestion is basically to add an opportunity to add dynamic data to popTip. For example you can put an entire CARD with images and text inside of the popTip. So that it can allow you to have dynamic data. The problem with current poptip is that u need to manually put everything like title="here" and content in the same way. Would be nice to have some that feature

### What does the proposed API look like?
For example imagine you want to purchase a product and then when you hover over that product it gives you a description, another images, creator, date published etc. Can be used in many scenarios

**Comment by icarusion** [comment]
It supports slot
