### ISSUE TITLE
使用this.$Modal报大堆警告

### ISSUE THREAD

**Issue by needou** [iview/iview#2513]
直接使用guangfang官方实例
 this.$Modal.confirm({
                    title: '删除确认',
                    content: "<div>确定要删除该条记录</div>",
                    onOk:() => {

                    }
                });
未放置任何其他代码，报如下警告，之前没有，升级2.7.3后出现

vue.common.js:478 [Vue warn]: $attrs is readonly.

found in

---> <Modal>
       <Root>
warn @ vue.common.js:478
(anonymous) @ vue.common.js:4152
reactiveSetter @ vue.common.js:991
updateChildComponent @ vue.common.js:2790
prepatch @ vue.common.js:4033
patchVnode @ vue.common.js:5766
patch @ vue.common.js:5937
Vue._update @ vue.common.js:2625
updateComponent @ vue.common.js:2743
get @ vue.common.js:3086
run @ vue.common.js:3163
flushSchedulerQueue @ vue.common.js:2929
(anonymous) @ vue.common.js:1794
flushCallbacks @ vue.common.js:1715
vue.common.js:478 [Vue warn]: $listeners is readonly.

found in

---> <Modal>
       <Root>
warn @ vue.common.js:478
(anonymous) @ vue.common.js:4155
reactiveSetter @ vue.common.js:991
updateChildComponent @ vue.common.js:2791
prepatch @ vue.common.js:4033
patchVnode @ vue.common.js:5766
patch @ vue.common.js:5937
Vue._update @ vue.common.js:2625
updateComponent @ vue.common.js:2743
get @ vue.common.js:3086
run @ vue.common.js:3163
flushSchedulerQueue @ vue.common.js:2929
(anonymous) @ vue.common.js:1794
flushCallbacks @ vue.common.js:1715
vue.common.js:478 [Vue warn]: $attrs is readonly.

found in

---> <Button>
       <Root>
warn @ vue.common.js:478
(anonymous) @ vue.common.js:4152
reactiveSetter @ vue.common.js:991
updateChildComponent @ vue.common.js:2790
prepatch @ vue.common.js:4033
patchVnode @ vue.common.js:5508
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
patch @ vue.common.js:5668
Vue._update @ vue.common.js:2462
updateComponent @ vue.common.js:2576
get @ vue.common.js:2919
run @ vue.common.js:2996
flushSchedulerQueue @ vue.common.js:2762
(anonymous) @ vue.common.js:700
nextTickHandler @ vue.common.js:647
vue.common.js:478 [Vue warn]: $listeners is readonly.

found in

---> <Button>
       <Root>
warn @ vue.common.js:478
(anonymous) @ vue.common.js:4155
reactiveSetter @ vue.common.js:991
updateChildComponent @ vue.common.js:2791
prepatch @ vue.common.js:4033
patchVnode @ vue.common.js:5508
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
updateChildren @ vue.common.js:5416
patchVnode @ vue.common.js:5519
patch @ vue.common.js:5668
Vue._update @ vue.common.js:2462
updateComponent @ vue.common.js:2576
get @ vue.common.js:2919
run @ vue.common.js:2996
flushSchedulerQueue @ vue.common.js:2762
(anonymous) @ vue.common.js:700
nextTickHandler @ vue.common.js:647
vue.common.js:478 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "type"

found in

---> <Button>
       <Root>

**Comment by needou** [comment]
找到原因了，升级vue版本和vue-loader即可

**Comment by 617450941** [comment]
升级到哪个版本 我这升级了还是报错

**Comment by webees** [comment]
@needou 怎么解决的，我几个月了还没有解决。

**Comment by ddcouples** [comment]
同样出现大量问题

**Comment by BoleLee** [comment]
@needou @ddcouples 请问是什么原因，需要什么版本的vue和vue-loader?

**Comment by ddcouples** [comment]
@BoleLee 兄弟解决了么，好像换了还是会的呀，我项目里全部用的import Vue from 'vue';只有在webpack.base.conf.js中resolve配置的是 'vue$': 'vue/dist/vue', 依然是会有Vue warn!

**Comment by BoleLee** [comment]
@ddcouples 我的问题解决了，改了` import Vue from 'vue'` 后就没有警告了，具体原因我也还没有深入了解

**Comment by classLfz** [comment]
这个似乎是 `webpack` 编译时候的问题？我是在 `electron-vue` 的项目里边使用 `iview` 的 `$Modal.confirm()`，也是有这个问题，但是编译打包之后就不会出现了。似乎是把 `.electron-vue` 下边的 `webpack.render.config.js` 里边的 25 行 `let whiteListedModules = ['vue']` 改为 `let whiteListedModules = ['vue', 'iview']` 就可以了？似乎有点类似于添加到白名单的味道...

**Comment by IceApriler** [comment]
@classLfz 很有用，赞 👍

![image](https://user-images.githubusercontent.com/29689307/43533331-278db740-95e7-11e8-9a32-01ebc63608d7.png)

原文：
## .electron-vue/webpack.renderer.config.js
Targets electron's renderer process. This configuration handles your Vue application, so it includes vue-loader and many other configurations that are available in the official vuejs-templates/webpack boilerplate.

### White-listing Externals
One important thing to consider about this config is that you can whitelist specific modules to not treat as webpack externals. There aren't many use cases where this functionality is needed, but for the case of Vue UI libraries that provide raw *.vue components they will need to be whitelisted, so vue-loader is able to compile them. Another use case would be using webpack aliases, such as setting vue to import the full Compiler + Runtime build. Because of this, vue is already in the whitelist.
