### ISSUE TITLE
The [Feature Request]select component click event manually select option and update option silent selection will all trigger


### ISSUE THREAD

**Issue by yuhonyon** [iview/iview#2515]
### What problem does this feature solve?
更新数据会触发select的click事件, 导致一些原本要在监控数据变化时执行的代码要放到click方法里,代码变的不清晰

### What does the proposed API look like?
希望添加个change事件保持都触发,click事件只触发手动选择

**Comment by icarusion** [comment]
change 只有主动选择才触发，手动修改数据不触发。
