### ISSUE TITLE
The [Feature Request]select component returns the value of label and value only when the label-in-value is set up only in the return value of the on-change


### ISSUE THREAD

**Issue by Sawyer-china** [iview/iview#2518]
### What problem does this feature solve?
select 组件 在设置了 label-in-value 的时候 只有在on-change的返回值中才会把  label和value的值一同返回，但是v-model中绑定的值依然是value，而不是 label和value的值，后期取值相当麻烦

### What does the proposed API look like?
期望设置了该属性后再v-model绑定的之中也相对应的加上 label和value的值，这样方便在其他地方取值

**Comment by icarusion** [comment]
No such plan now.
