### ISSUE TITLE
[Feature Request]select requests to join the page initialization because V-model has a value triggered event


### ISSUE THREAD

**Issue by Link-X** [iview/iview#2521]
### What problem does this feature solve?
select 在页面初始化时候如果v-model有值的话，on-change 将被触发，无法与on-change 分别。有的时候业务在初始化时不允许在页面初始化的时候触发select的change事件。

### What does the proposed API look like?
希望加入一个事件 让如elementUI select 的 visible-change ，只有当我主动 触发change时才触发 绑定的事件

**Comment by zeus-jen** [comment]
I also have the same problem, looking forward to solve

**Comment by pihc** [comment]
@Link-X @zeus-jen 我也遇到了这个问题，请问你们解决了吗 😄

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
