### ISSUE TITLE
[Bug Report]select value cannot select value empty option for empty space


### ISSUE THREAD

**Issue by yuhonyon** [iview/iview#2524]
### Environment
select value 不能为空   为空时不能选择value为空的option

### Reproduction link
[https://www.iviewui.com/new-issue](https://www.iviewui.com/new-issue)

### Steps to reproduce
select value 不能为空   为空时不能选择value为空的option

### What is expected?
select value 能为空

### What is actually happening?
select value 不能为空   为空时不能选择value为空的option

**Comment by ilovemyboys** [comment]
这个问题有解决方案吗？
