### ISSUE TITLE
Tabs中select下拉选项不显示

### ISSUE THREAD

**Issue by yajore** [iview/iview#253]
### iView 版本号
 0.9.117

### 操作系统/浏览器 版本号
WIN10/Chrome 555

### Vue 版本号
 1.0.26 

### 能够复现问题的在线示例

https://codepen.io/anon/pen/QdWKOE

**Comment by icarusion** [comment]
Tabs高度不够

**Comment by rijn** [comment]
@icarusion I think we should remove overflow-hidden.
