### ISSUE TITLE
The bug of the [Bug Report] date selector


### ISSUE THREAD

**Issue by xiaziheng** [iview/iview#2539]
### Environment
win7/chrome62.0.3202.94（正式版本） （32 位）/vue2.0

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
选择日期，然后往里输入内容，日期下拉框取消后内容消失，但是鼠标移入进去输入信息还在

### What is expected?
鼠标移入没有输入的信息

### What is actually happening?
鼠标移入进去输入信息还在

**Comment by SergioCrisostomo** [comment]
@xiaziheng I cannot reproduce this problem. Could you please check if its still there and explain the steps to reproduce more?
Thank you!
