### ISSUE TITLE
table组件在初始化渲染时，column属性不能置为空数组

### ISSUE THREAD

**Issue by YikaJ** [iview/iview#254]
### iView 版本号

最新
### Vue 版本号

1.0.26
### 能够复现问题的在线示例

https://codepen.io/anon/pen/LxJdRa
### 复现步骤
1. 初始化 i-table 时，将 column 属性置为空数组
### 问题现象，以及你期望的结果是怎样的?
报 Reduce of empty array with no initial value
我希望初始化置空，可动态更新 column
### 你估计可能的原因是什么（选填）？
对 column 初始化时没有考虑周全。

**Comment by joe434200** [comment]
我觉得动态更新column也是很有必要的~

**Comment by liumanwei** [comment]
实际开发中确实也遇到了这样的需求，目前是先默认给一列，然后再重新赋值，希望可以得到解决

**Comment by Peterlhx** [comment]
可以判断column的长度，当长度不为0时，才渲染表格，用v-if="column.length !== 0"

**Comment by icarusion** [comment]
fixed in 2.3.0
