### ISSUE TITLE
[Bug Report]Tabs puts Inputs down, and if you use the tab key to switch the focus, it causes the wrong UI location


### ISSUE THREAD

**Issue by chavyleung** [iview/iview#2542]
### Environment
win10, vue2.5.3, iview2.7.4

### Reproduction link
[https://codepen.io/chavyleung/pen/gXZXJw](https://codepen.io/chavyleung/pen/gXZXJw)

### Steps to reproduce
1. 把焦点放在Input内
2. 然后多次按“Tab”键，会定位到标签二的input中，但位置是错误的
3. 会定位到标签二的input中，但位置是错误的

### What is expected?
定位正确或禁止定位到当前tab以外的input

### What is actually happening?
会定位到标签二的input中，但位置是错误的

**Comment by ptk941114** [comment]
同BUG，我上个月就提了 ，https://github.com/iview/iview/issues/2424    (┬＿┬)

**Comment by chunminggg** [comment]
有解决方案吗

**Comment by icarusion** [comment]
@2424
