### ISSUE TITLE
[Feature Request] can not add a calendar component, similar to the Google calendar


### ISSUE THREAD

**Issue by hiwjcn** [iview/iview#2549]
### What problem does this feature solve?
想做一个schedule的应用，发现ant.design里有这种组件，想iview中也有一个
参考：
https://ant.design/components/calendar-cn/#components-calendar-demo-notice-calendar

### What does the proposed API look like?
参考：
https://ant.design/components/calendar-cn/#components-calendar-demo-notice-calendar

**Comment by coldstone** [comment]
这个可以有，支持。

**Comment by SergioCrisostomo** [comment]
Closing as duplicate of https://github.com/iview/iview/issues/1910
