### ISSUE TITLE
[Feature Request]How to add the display content in the render function?

### ISSUE THREAD

**Issue by EPCbee** [iview/iview#2569]
### What problem does this feature solve?
The official website of the Switch only provide a slot to add text prompts support, how to add the display content in the render function?
 官网上 Switch 只提供slot的方式添加文本提示支持，如何在render函数中添加显示内容呢？

### What does the proposed API look like?
The official website of the Switch only provide a slot to add text prompts support, how to add the display content in the render function?
 官网上 Switch 只提供slot的方式添加文本提示支持，如何在render函数中添加显示内容呢？

**Comment by hq262866869** [comment]
同问

**Comment by LuGuojing** [comment]
同问

**Comment by LuGuojing** [comment]
// 如果组件是其他组件的子组件，需为插槽指定名称
  slot: 'name-of-slot'
