### ISSUE TITLE
tabs组件下使用Modal组件的问题

### ISSUE THREAD

**Issue by lwfsky** [iview/iview#257]
### iView 版本号
0.9.16 

### 操作系统/浏览器 版本号
window/Chrome 

### Vue 版本号
1.0.26

### 复现步骤

在不是第一个tab页面里面调用Modal组件，modal组件会在第一个tab页面里面展示

### 问题现象，以及你期望的结果是怎样的?

希望在本tab页面展示Modal组件

**Comment by icarusion** [comment]
Modal应置于全局
