### ISSUE TITLE
[Bug Report]Table fixed height, head deformation


### ISSUE THREAD

**Issue by gavinfuu** [iview/iview#2579]
### Environment
window10 / chrome 60 / 2.7.4

### Reproduction link
[https://codepen.io/gavinfuu/pen/jaoONd](https://codepen.io/gavinfuu/pen/jaoONd)

### Steps to reproduce
https://codepen.io/gavinfuu/pen/jaoONd

### What is expected?
表头跟有数据的时候一致

### What is actually happening?
表头跟有数据的时候不一致

**Comment by Bimbaloo** [comment]
@gavinfuu
同样的问题。临时解决方案：最后一列设置width。

**Comment by icarusion** [comment]
Please check the documentation and update to the latest version, if you have any questions, you can submit a new issue
