### ISSUE TITLE
The use of fixed combined with minWidth in the [Bug Report]table component causes an error in the minWidth column


### ISSUE THREAD

**Issue by attacking** [iview/iview#2589]
### Environment
chrome52 mac

### Reproduction link
[https://codepen.io/yummy/pen/OOewJj?editors=1010](https://codepen.io/yummy/pen/OOewJj?editors=1010)

### Steps to reproduce
小屏幕下横向滚动

### What is expected?
最后一列能出现

### What is actually happening?
最后一列并未在小屏幕下出现，只在宽度足够的情况下才会出现

---
另一个bug是minWidth不能定义在中间列中，会导致样式错乱。

**Comment by icarusion** [comment]
#3284
