### ISSUE TITLE
[Feature Request]Input component's type type please support number


### ISSUE THREAD

**Issue by chingxuds** [iview/iview#2594]
### What problem does this feature solve?
有时不需要将输入转化成数字，而仅仅是想让浏览器给出数字键盘，否则部分场景下用户输入字符而组件转化成数字后无法检测到非法输入

### What does the proposed API look like?
无

**Comment by bjcharlesy** [comment]
html和vue本身就支持number类型，比如vue给的例子如下:
<input v-model.number="age" type="number">
不支持number，感觉就像把input阉割了一样。
用正则匹配以数字开头的部分转化为数字怎么样呢？ 如123adc -> 123, ### -> undefine, 123## -> 123, asdf123 -> undefine, 123daf123 -> 123。

**Comment by icarusion** [comment]
仔细看文档
