### ISSUE TITLE
[Bug Report]The project of Vue  iview again npm install, all errors

### ISSUE THREAD

**Issue by YJZ-S** [iview/iview#2615]
### Environment
windows/chrome 62.0.3202.94/vue 2.3.3、2.5.2、2.5.9

### Reproduction link
[https://github.com/YJZ-S/iview-warn-demo](https://github.com/YJZ-S/iview-warn-demo)

### Steps to reproduce
1.vue-cli搭建项目
vue init webpack...
2.main.js文件中引入iview
 import iView from 'iview';
 import 'iview/dist/styles/iview.css';
 Vue.use(iView);
3.npm install
4.[Vue warn]: Do not use built-in or reserved HTML elements as component id: Table

### What is expected?
解决报错

### What is actually happening?
报错

---
我原来新建的项目，重新npm install也会报这个错误，vue降级依然如此

**Comment by zhaozhe0831** [comment]
我也遇到了同样的问题。

![image](https://user-images.githubusercontent.com/12945873/37448537-b7d248d2-2861-11e8-8cb5-286665298e6a.png)
