### ISSUE TITLE
[Bug Report]The project of Vue + iview again npm install, all errors

### ISSUE THREAD

**Issue by YJZ-S** [iview/iview#2616]
![_20171213231300](https://user-images.githubusercontent.com/26481272/33947801-5142761c-e060-11e7-8e25-ad7994fc4b4b.jpg)

### Environment
windows/chrome 62.0.3202.94/vue 2.3.3、2.5.2、2.5.9

### Reproduction link
[https://github.com/YJZ-S/iview-warn-demo](https://github.com/YJZ-S/iview-warn-demo)

### Steps to reproduce
1.vue-cli搭建项目
vue init webpack...
2.main.js文件中引入iview
 import iView from 'iview';
 import 'iview/dist/styles/iview.css';
 Vue.use(iView);
3.npm install
4.[Vue warn]: Do not use built-in or reserved HTML elements as component id: Table

### What is expected?
解决报错

### What is actually happening?
报错

---
我原来新建的项目，重新npm install也会报这个错误，vue降级依然如此

**Comment by jingsam** [comment]
首先这是警告不是错误，不影响使用。产生的原因是上游的vue最近对组件名校验引入了breaking change,我们会跟进此事，争取尽快解决。如果不想看到此错误，应该降级vue，降级iview是没用的

**Comment by YJZ-S** [comment]
嗯好，降级管用的，之前自己这里出错了，谢谢。

**Comment by ddcouples** [comment]
那如果vue一直采用这种报错机制，iview如果简单的更新组件名称，如果改掉了注册的名称，项目里之前写的组件名称岂不是要全部改掉，这个工程量很大啊

**Comment by jingsam** [comment]
https://github.com/vuejs/vue/issues/7237

**Comment by coopercoder** [comment]
vue.esm.js?efeb:576 [Vue warn]: Do not use built-in or reserved HTML elements as component id: **Circle**
vue.esm.js?efeb:576 [Vue warn]: Do not use built-in or reserved HTML elements as component id: **Switch**

VUE升级到2.5.11版本后，好一些了，但是还是有这两个警告。 

这个下一步iview会处理吗？

**Comment by hemant4524** [comment]
Do not use built-in or reserved HTML elements as component id: Circle give same error. What is the solution for this issue?

**Comment by jingsam** [comment]
https://www.iviewui.com/docs/guide/start#%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E8%A7%84%E8%8C%83

![image](https://user-images.githubusercontent.com/1522494/34190543-61009ef0-e57c-11e7-9f95-681a29b9d611.png)

**Comment by icarusion** [comment]
`Circle` 和 `Switch` 的警告问题已解决，在 iView 2.8.0 更新。

**Comment by scottdao** [comment]
在新版vue中引入iview时，引入css样式时报错，问一下怎么引入才是则是正确的呀？

**Comment by web-chenke** [comment]
这网站是个人写的，维护起来非常慢,他不像elementui,这样的框架有团队维护，他自己这么多问题，改到猴年马月了
