### ISSUE TITLE
[Bug Report]DatePicker returns wrong date

### ISSUE THREAD

**Issue by allochi** [iview/iview#2629]
### Environment
OSX, Chrome 63.0.3239.84, Vue 2.5.9, iView 2.7.4

### Reproduction link
[https://jsfiddle.net/ebjvpddj/](https://jsfiddle.net/ebjvpddj/)

### Steps to reproduce
1. add `<date-picker type="date" v-model="date"></date-picker>` to any page/form
2. add `date` property to data
3. add `{{date}}` to the template body
4. Select a date
5. Check the selected date against the date printout (if you are a head of GMT it will be wrong)

### What is expected?
DatePicker should return the same date selected by the user.

### What is actually happening?
Returns the date in GMT based on the time zone, I'm one hour a head of GMT, so if I choose `2017-12-15` it returns `2017-12-14T23:00:00.000Z `

---
This could have bee avoided if `date-picker` returns date without time as a string instead of a Date instance, but since we won't break the implementation, it should just return the right selected date without consideration of time zones.

**Comment by allochi** [comment]
Just to add, I tried to test if the browser settings play any role by replacing 
```
<date-picker type="date" v-model="date"></date-picker>
```
 with
```
<input type="date" v-model="date" />
```

And the returned dates from the native `input` are correct but not the `date-picker`.

**Comment by Xotic750** [comment]
From what I can see, iview is doing the correct things with it's API. The problem you have described seems to be with how vue is transforming the template into a render function. Normal coercion of a date to a string used `toString`, but vue seems to detect your `{{date}}` as being a date object and chooses to use `toISOString` instead of `toString`. However the date and time are correct as an object and you can choose how the date object is stringified. i.e `{{date && date.toString()}}`

**Comment by Xotic750** [comment]
Basically you are passing an object to the template. It is detected as an object and then is `JSON.stringified` which calls `toISOString`. Yous should controll the conversion yourself and output a string to the template rather than an object.

**Comment by allochi** [comment]
@Xotic750 Thanks for your reply, your suggestion is what I'm doing now as a workaround, but this means I can't use `DatePicker` with `v-model`, since it converts the **date** into **datetime**, this effect get sent to the database and the database get filled with the wrong dates. I would expect `DatePicker` of type **date** to return the date picked, if I wanted a **datetime** then this is a different story and I would pass `DatePicker` type **datetime**.

I hope this explains my logic.

**Comment by allochi** [comment]
Basically, every time I use `DatePicker` of type **date**, I have to use it this way

```html
<Date-picker type="date" 
:value="document.publication_date" 
@on-change="(value) => document.publication_date=value.toString()">
</Date-picker>
```

**Comment by allochi** [comment]
Just to add to my point, if I'm using `DatePicker` of type **daterange**, it will return an array with two strings that contains only the selected date :).

Anyway, I'm thankful for `iView` team, you are doing great work with the library.

**Comment by SergioCrisostomo** [comment]
@allochi the `v-model` returns Date object(s), not strings. Even if `type="daterange"` the `v-model` offers you `Date` objects. Keep in mind that `.toISOString()`, .toLocaleString()` and `.toString()` are all different representations of the same date.

Please check this jsFiddle: https://jsfiddle.net/Sergio_fiddle/st034ag9/ and use it if you still have a problem and reproduce the problem.

**Comment by allochi** [comment]
@SergioCrisostomo Thanks for the clarification.

@Xotic750 and @SergioCrisostomo thanks both for your help.
