### ISSUE TITLE
The value of the [Bug Report]InputNumber input box is deleted. The value of the input box is not empty after the focus is lost, and it is still the last value.


### ISSUE THREAD

**Issue by xifengxx** [iview/iview#2630]
### Environment
chrome

### Reproduction link
[https://jsfiddle.net/Lzqnnkor/4/](https://jsfiddle.net/Lzqnnkor/4/)

### Steps to reproduce
输入框输入123，显示123，用键盘键"Backspace"删除输入的数字，输入框失焦后，输入框值value为1，实际应为空。

### What is expected?
当输入框输入值后，删除输入的值，输入框此时的值应为空

### What is actually happening?
当输入框输入值后，删除输入的值，输入框此时的值为上一次改变的值。

**Comment by lyh3173** [comment]
!isEmptyString 这个逻辑怪怪的， 空的话不是应该为 0 吗，全部删除都不能删了 现在的逻辑
if (!isNaN(val) && !isEmptyString) {
                this.currentValue = val;

                if (event.type == 'input' && val < min) return;
                if (val > max) {
                    this.setValue(max);
                } else if (val < min) {
                    this.setValue(min);
                } else {
                    this.setValue(val);
                }
            } else {
                event.target.value = this.currentValue;
            }

**Comment by fekata** [comment]
能不能加一个判断，如果组建存在min属性，文本清空，失焦后输入框的值为min的值，否则输入框的值为上一次值。

**Comment by daiyanze** [comment]
感兴趣的话可以参考一下这个帖子：https://github.com/iview/iview/issues/2829
我提交了一个PR，当`:empty="true"`时，支持输出为`NaN`的结果。
@fekata
> 能不能加一个判断，如果组建存在min属性，文本清空，失焦后输入框的值为min的值，否则输入框的值为上一次值。
我挺赞同你的想法，失焦后的值应该以最小值（或者初设值）为基准。貌似目前element也是以最小值为基准的。

**Comment by icarusion** [comment]
#3174
