### ISSUE TITLE
Can the [Bug Report]table expand column always expand only one


### ISSUE THREAD

**Issue by Xiongzhenyu** [iview/iview#2637]
### Environment
macOS 10.13

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
重现地址是官网的demo ， demo 看起来就有一些问题.. 

### What is expected?
希望只能展开一行数据的效果

### What is actually happening?
实际能展开多行

**Comment by dweep119** [comment]
Same problem I have faced.
Is there any solution for this, to table expand only one row at a time like **Accordion**??

**Comment by lyseky** [comment]
我也有这个问题，原来是bug

**Comment by icarusion** [comment]
自己控制。
