### ISSUE TITLE
[Bug Report]cascader document error

### ISSUE THREAD

**Issue by smartymoon** [iview/iview#2638]
### Environment
chrome

### Reproduction link
[https://www.iviewui.com/components/cascader](https://www.iviewui.com/components/cascader)

### Steps to reproduce
在 cascader 文档中，关于props部分，`change-on-select` 的类型为 Function 默认值为 value

### What is expected?
`change-on-select` 的类型为 Boolean 默认值为 false

### What is actually happening?
`change-on-select` 的类型为 Function 默认值为 value

**Comment by DoJustForlove** [comment]
看了下 iview的源码
![image](https://user-images.githubusercontent.com/18435678/34092768-13fbfa3c-e400-11e7-8c8f-87f81dde978e.png)
是这样的定义的，应该是官网的类型写错了吧
