### ISSUE TITLE
建议：提供 Modal 控制 buttonLoading 的方法

### ISSUE THREAD

**Issue by YikaJ** [iview/iview#264]
有一个需求是这样的。模态框的确认是异步操作，提交错误时，需要把 Modal 内部的 buttonLoading 置为 false，但模态框并不关闭，并可再次提交。现在的问题是无法控制 buttonLoading ，导致无法二次确认。

建议：提供可控制 buttonLoading 的属性或者方法。thank you ~~

**Comment by icarusion** [comment]
查看 `自定义页头和页脚` 的示例。
