### ISSUE TITLE
[Bug Report]An incorrect description in the document

### ISSUE THREAD

**Issue by TestMsr** [iview/iview#2641]
### Environment
All

### Reproduction link
[https://github.com/iview/iview-doc/blob/master/src/code/table.js#L1015](https://github.com/iview/iview-doc/blob/master/src/code/table.js#L1015)

### Steps to reproduce
In the line 1015 of [table.js](https://github.com/iview/iview-doc/blob/master/src/code/table.js#L1015)
the file name `expand-row.vue` should be [table-expand.vue](https://github.com/iview/iview-doc/blob/master/src/views/components/table-expand.vue)

### What is expected?
\/\/ table-expand.vue

### What is actually happening?
\/\/ expand-row.vue

---
it has been fixed in the [pr](https://github.com/iview/iview-doc/pull/31)

**Comment by SergioCrisostomo** [comment]
@TestMsr I close this issue here because its related to docs. 
Thank you for opening a PR in the docs repository!
