### ISSUE TITLE
[Feature Request]table里的不button按钮没有办法根据条件控制显示隐藏

### ISSUE THREAD

**Issue by Panamer** [iview/iview#2648]
### What problem does this feature solve?
用户会根据不同的情况做不同的操作，没必要的button也显示了

### What does the proposed API look like?
0.

**Comment by Jame0527** [comment]
你可以写render函数去控制显示隐藏

**Comment by Jame0527** [comment]
你可以写render函数去控制显示隐藏@Panamer

**Comment by dingshaomiao** [comment]
请问在render函数中如何判断显示跟隐藏?
