### ISSUE TITLE
按需加载Submenu失败

### ISSUE THREAD

**Issue by zhaojh329** [iview/iview#2649]
### Environment
Ubuntu 17

### Reproduction link
[https://github.com/zhaojh329/vuci/tree/master/vuci-ui-base/src](https://github.com/zhaojh329/vuci/tree/master/vuci-ui-base/src)

### Steps to reproduce
执行npm install
然后执行npm run dev                                                            

### What is expected?
无错误

### What is actually happening?
This dependency was not found:

* iview/src/components/submenu in ./src/main.js

To install it, you can run: npm install --save iview/src/components/submenu

**Comment by icarusion** [comment]
已在下个版本解决

**Comment by renyuns** [comment]
单页面 html 中使用 iview ,能实现按需加载吗
