### ISSUE TITLE
Vue.use(iView); 之后有错误

### ISSUE THREAD

**Issue by xinghui928** [iview/iview#2650]
vue.esm.js?efeb:576 [Vue warn]: Do not use built-in or reserved HTML elements as component id: Circle

vue.esm.js?efeb:576 [Vue warn]: Do not use built-in or reserved HTML elements as component id: Switch

是2017.12.18日下载的最近版本。什么都没有做，引入之后跑起来会报这两个错误。是vue-cli刚下的脚手架，啥都没写进去，就加了个iView。

**Comment by icarusion** [comment]
下个版本修复

**Comment by xinghui928** [comment]
好的，谢谢
