### ISSUE TITLE
Form 表单报错

### ISSUE THREAD

**Issue by PassionZale** [iview/iview#266]
### iView 版本号
0.9.17

### 操作系统/浏览器 版本号
Chrome 54

### Vue 版本号
1.0.26

### 问题现象
项目中有配置了多个v-router，在切换router的时候，出现报错：iview.js?5654:11085 Uncaught TypeError: Cannot read property 'model' of null
``` javascript
fieldValue: {
    cache: false,
    get: function get() {
    var model = this.form.model;
    if (!model || !this.prop) {
        return;
    }
    var path = this.prop;
    if (path.indexOf(':') !== -1) {
        path = path.replace(/:/, '.');
    }
    return getPropByPath(model, path).v;
    }
},
```

### 猜测原因
几个报错的router里，我都使用了Form表单这个组件，我的prop都有赋值，不太清楚是不是这个原因造成的，尤其是使用LoadingBar 加载进度条后，会造成路由来回不断的切换，最终只能关闭浏览器当前tab页面才行。

**Comment by rijn** [comment]
Same problem with loading bar here. I thought it is the bug in Vue. =(

**Comment by PassionZale** [comment]
###vue-router 版本号
0.7.13
请问以前遇到这种问题，有人解决过嘛？我使用的vue-router版本号如上。

我有去查看vue&vue-router的相关issuses，作者给出的解释是，components中，data()方法return为空，但是我的components中均返回了相关对象，不存在return {}的组件

**Comment by icarusion** [comment]
应该是你哪里使用不当，最好能给出复现示例

**Comment by yanghdx** [comment]
我也碰到了这个问题。代码没动，重启浏览器后没有复现。不知是否找到具体原因？

**Comment by Qsnh** [comment]
我也遇到这个问题，我开始的环境和楼主一模一样，但是我换个浏览器突然就好了 ^-^。这是什么原因呢？
