### ISSUE TITLE
The width problem of the column set in [Bug Report]Table


### ISSUE THREAD

**Issue by zzl4883a** [iview/iview#2663]
### Environment
操作系统：win7    浏览器chrom: 62.0.3202.89 

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
前提：将Table中的所有列的列宽设置为非默认的Number型，设置为字符串型。步骤：1.最后一列不设置宽度时，表格才会显示，但显示也有问题：最后一列的列头不显示。2.当最后一列设置宽度时，表格不能完整显示。

### What is expected?
1.当设置字符串类型的列宽时，不要正常计算列宽。如果正常计算列宽，会给用户一种可以使用字符串型列宽的错觉。
2.或者可以使用字符串型列宽，但修复以上问题。

### What is actually happening?
无

**Comment by icarusion** [comment]
Please check the documentation and update to the latest version, if you have any questions, you can submit a new issue
