### ISSUE TITLE
[Bug Report]Duplicate keys detected is prompted when using the Table filters option

### ISSUE THREAD

**Issue by chuangker** [iview/iview#2666]
### Environment
macOS 10.13.2 / Chrome 63.0.3239.84（正式版本）（64 位）/ Vue.js v2.5.13

### Reproduction link
[https://jsfiddle.net/qxorvppr/](https://jsfiddle.net/qxorvppr/)

### Steps to reproduce
打开控制台查看警告信息

### What is expected?
无警告

### What is actually happening?
Duplicate keys detected

**Comment by lyz7805** [comment]
我也遇到这类问题了，主要问题就在你是否设定数据过滤是否多选，如果为单选的话就不会有问题，如果为多选就会出现此问题。
我怀疑是在设定多选情况下，TableHead组件内部通过v-for循环出来多选框，没有加key属性导致vue警告。

**Comment by chuangker** [comment]
确实是 `filterMultiple` 引起的这个问题。

**Comment by chuangker** [comment]
`v2.7.4` 已经修复该问题。

**Comment by lyz7805** [comment]
是`v2.8.0`
