### ISSUE TITLE
[Bug Report]annoying vue warn: Do not use built-in or reserved HTML elements as component id: Circle/Switch

### ISSUE THREAD

**Issue by 0xffff00** [iview/iview#2671]
### Environment
Win10/Chrome 57/ Vue 2.5.13/ iView 2.7.4

### Reproduction link
[https://jsfiddle.net/21ppddLp/](https://jsfiddle.net/21ppddLp/)

### Steps to reproduce
just click run on https://jsfiddle.net/21ppddLp/ and watch the chrome console

### What is expected?
no any errors in chrome console

### What is actually happening?
two errors in n chrome console:
> [Vue warn]: Do not use built-in or reserved HTML elements as component id: Circle
> [Vue warn]: Do not use built-in or reserved HTML elements as component id: Switch

**Comment by prestanesia** [comment]
I have that warning as well while using latest vue (2.5.13). To get rid the warning just stick with vue 2.5.9 at the moment.

**Comment by 0xffff00** [comment]
@prestanesia thanks for reply.
I found probable related issues:
#120
 [组件名称校验错误](https://github.com/vuejs/vue/issues/7237)

**Comment by icarusion** [comment]
fixed in 2.8.0
