### ISSUE TITLE
Cascader 级联选择,是否可以增加支持选择第一个时触发接口，获取下一级数据，并且能继续选择

### ISSUE THREAD

**Issue by tianxinli** [iview/iview#268]

**Comment by tianxinli** [comment]
Cascader 级联选择组件，是否可以增加支持选择第一个时触发接口，获取下一级数据，并且能继续选择

**Comment by tianxinli** [comment]
Cascader 级联选择组件,是否可以增加支持选择第一个时触发接口，获取下一级数据，并且能继续选择

**Comment by larryu** [comment]
Hi @tianxinli, have you figured out a way to do that? Or a new api has been added to the latest version?
