### ISSUE TITLE
[Bug Report]Form component dynamic control of the content of the form, FormItem will be "reuse ', not according to the rules that required the asterisk check


### ISSUE THREAD

**Issue by ShujiaWu** [iview/iview#2682]
### Environment
Win10 / Chrome  63.0.3239.84（正式版本）（64 位）/ v2.5.13 

### Reproduction link
[https://jsfiddle.net/yyrzhm46/149/](https://jsfiddle.net/yyrzhm46/149/)

### Steps to reproduce
点击 ‘Add item’ 添加多几个条目，然后点击‘Delete’ 删除第二个条目，新的第二个条目是非必选的（校验规则中index<3的条目是必填的），但是会被打上星号。

### What is expected?
根据校验规则正确显示必填与非必填

### What is actually happening?
动态修改后，控件好像会被‘复用’，而导致显示错误。

**Comment by RookieZoe** [comment]
@ShujiaWu 
是`v-for` 中 `:key`的问题，具体原因可以去看看vue的文档。
修正如下：
```
<form-item v-for="(item, index) in formDynamic.items" v-if="item.status" :key="item.index" :label="'Item ' + index" :prop="'items.' + index + '.value'" :rules="{required: item.index < 3, message: 'Item ' + item.index +' can not be empty', trigger: 'blur'}">
```

[https://jsfiddle.net/Rookie_Zoe/2LyLvckp/3/](https://jsfiddle.net/Rookie_Zoe/2LyLvckp/3/)

**Comment by ShujiaWu** [comment]
@RookieZoe 谢谢提醒，那天竟然没有想到这个问题。
