### ISSUE TITLE
[Feature Request]SideNav, SideBar or Drawer

### ISSUE THREAD

**Issue by natxocc** [iview/iview#2689]
### What problem does this feature solve?
iView is wonderfull, but I have a lot of troubles to have a decent app to desktop and mobile hybrid. A new component like Drawer would be welcome to this great framework. The layouts we have need a lot of refactoring to work decently on hybrids devices.

### What does the proposed API look like?
Something like a drawer can be very usefull to have menus visible on desktop and mobiles devices.

**Comment by zhaojh329** [comment]
The next version already contains the components you want.

**Comment by natxocc** [comment]
I have test the new sider but it's not really a drawer or sidenav. The height of the sider always is the same of the content, and this is not practical. You can have a content but not necessary scroll all the content with a different sider options. I thik the concept must be independent from content to sider, as, in mobiles is not practical.

**Comment by KrishnaPG** [comment]
To add further, `Sider` should show an "expand" or "scroll" option when all menu items are not visible on the screen.

When the Sider height is less than the number of menu items, then some menu items are becoming invisible. In such cases, Sider should automatically display a "scroll" button above/below, or "scroll bar", to make the hidden menus accessible.

**Comment by madisvain** [comment]
Just wanted to add this here as an addition. Antd recently implemented a drawer component like this:
https://ant.design/components/drawer/

It's very useful for all sorts of use cases.

**Comment by icarusion** [comment]
#4352

**Comment by lvchaoin** [comment]
same request : Sider should show an "expand" or "scroll" option when all menu items are not visible on the screen. Thank you !

**Comment by douglasg14b** [comment]
Agreed. This is a fairly basic/common feature these days, to have a sidebar that is scrollable separate from the rest of the page.
