### ISSUE TITLE
IE11报错

### ISSUE THREAD

**Issue by ChiHai-Chuck** [iview/iview#269]
### iView 版本号
0.9.17

### 操作系统/浏览器 版本号
IE11

### Vue 版本号
1.0.28

### 问题现象，以及你期望的结果是怎样的?
在IE11会报错，有时是“调用的对象无效”，有时是querySelectorAll()方法不存在。
调用的对象无效时的出错代码在iview.js第2889行：

```
height: {
    type: [String, Number],
    default: 'auto',
    validator: function validator(value) {
        return value === 'auto' || toString.call(value) === '[object Number]';
    }
}
```

此处的return value === 'auto' || toString.call(value) === '[object Number]';

### 你估计可能的原因是什么（选填）？
兼容性

**Comment by icarusion** [comment]
请给出能复现问题的在线示例

**Comment by ChiHai-Chuck** [comment]
@icarusion 已经可以确定错误发生在Carousel组件，我把一个使用Carousel实现轮播图的代码注释，就正常了，问题的原因应该是IE不支持toString.call()这样的写法，必须是Object.prototype.toString.call()

**Comment by icarusion** [comment]
@rijn If you have time, please have a look

**Comment by rijn** [comment]
I will check this and back to you soon.
