### ISSUE TITLE
[Feature Request] provides table drag sorting


### ISSUE THREAD

**Issue by weihongyu12** [iview/iview#2690]
### What problem does this feature solve?
在一些场景下，需要使用表格自定义排序，拖拽功能能够很好的做这项工作，像jQuery UI的[sortable](https://jqueryui.com/sortable/)一样

### What does the proposed API look like?
```
<Table :columns="columns1" :data="data1" draggable></Table>
```
Table组件增加一个`draggable`属性，使表格支持拖拽排序

**Comment by CuteDeng** [comment]
请问，我加了这个属性，并且也将iview版本升级到了3.3.0，但是没有生效，这是什么原因？
