### ISSUE TITLE
The [Bug Report] upgrade to more than 2.7 is no longer supported by IE9 browsers, which can be supported in previous versions


### ISSUE THREAD

**Issue by 15931436344** [iview/iview#2699]
### Environment
IE9 windows

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
增大iview的版本到2.7以上，webpack打包为2.0，则打包后浏览器ie9不能正常加载了，报js错误，之前的版本是可以的

### What is expected?
继续支持ie9，因为Vue支持ie9

### What is actually happening?
目前不支持ie9

**Comment by icarusion** [comment]
未来将不再支持低版本IE
