### ISSUE TITLE
[Feature Request]iview table selection

### ISSUE THREAD

**Issue by moonshine42** [iview/iview#2701]
### iView 版本号
2.7.4
### Vue 版本号
2.5.13
### What problem does this feature solve?
1、当列表所有checkbox全部都是勾选且禁用的状态，表头的checkbox也应变成勾选且禁用的状态。 but，在切换分页的时候需要重新根据新的数据的状态，改变表头checkbox的状态（即：若切换分页后，数据没有全部勾选禁用，需放开表头checkbox的禁用跟勾选状态）
2、有on-select-all事件，应该也要有取消全部的事件，on-cancel-all。 目前项目中有该需求
3、表头checkbox提供设置_disabled、_checked的方法
4、表头checkbox提供on-change事件

### What does the proposed API look like?
1、增加on-cancel-all事件。主要场景：取消当个复选框勾选会触发on-select-cancel后，再触发on-selection-change事件，并且无法通过stop阻止冒泡。看了源码，是先后emit两个事件，除非改源码否则没法阻止。 要阻止on-selection-change的理由，究根结底是为了知道全部取消的动作。 因为，当前取消表头的checkbox只触发了on-selection-change，但是on-select-cancel跟on-selection-change又不能同时监听，因为on-select-cancel跟on-selection-change会同时触发。所以，要么on-select-cancel不继续触发on-selection-change，要么提供on-cancel-all事件
2、表头checkbox提供设置_disabled、_checked的方法
3、表头checkbox提供on-change事件

**Comment by xpin1509** [comment]
the first problem solved ?

**Comment by moonshine42** [comment]
no...

**Comment by icarusion** [comment]
Please check the documentation and update to the latest version, if you have any questions, you can submit a new issue
