### ISSUE TITLE
[Bug Report] import the iView component IE browser to execute the error


### ISSUE THREAD

**Issue by FontEndArt** [iview/iview#2704]
### Environment
win10 ie-All vue2.5.2 iview2.8.0 webpack 3.6.0

### Reproduction link
[https://github.com/FontEndArt/chinacourt](https://github.com/FontEndArt/chinacourt)

### Steps to reproduce
npm install
npm run dev
打开ie   输入本地网址  空白报错
控制台：
SCRIPT1014: 无效字符
app.js (4219,1)
4218 "use strict";
4219 eval("/* harmony export

问题是vue-cli生成的项目直接引入'iview'在ie运行会出问题

### What is expected?
希望得到解决方式
可以在npm install之后可以直接import而不用担心vue-cli生成的东西编译问题

### What is actually happening?
可能需要修改源码或者修改webpack的配置   然而我不太会配置。。还在找解决办法中

**Comment by llz383455526** [comment]
问题怎么解决的呢？ @FontEndArt

**Comment by FontEndArt** [comment]
参照官网的webpack配置

**Comment by simplenjoy** [comment]
@llz383455526 
在loader中添加
{
  test: /iview.src.*?js$/,
  loader: 'babel-loader'
 },
