### ISSUE TITLE
css覆盖问题

### ISSUE THREAD

**Issue by jarvan4dev** [iview/iview#271]
### iView 版本号
0.9.17

### 操作系统/浏览器 版本号
macOS/Chrome 54

### Vue 版本号
1.0.26

![image](https://cloud.githubusercontent.com/assets/9948677/22916866/4793c36a-f2bc-11e6-85c5-83a1c0746e05.png)

想让分页标签右浮动，html如下：

```
<div class="page clearfix">
       <Page :total="100"></Page>
</div>
```

css如下：

```
.page {
    margin-top: 10px;
  }
  div.page .ivu-page {
    float: right !important;
  }
```

加了 !important仍然无法覆盖，请问是什么原因呢？

**Comment by icarusion** [comment]
试试外层div浮动

**Comment by jarvan4dev** [comment]
@icarusion 外层浮动当然可以，但是我不是特别清楚为什么不能覆盖css，有时候有些组件并不能加外层div啊

**Comment by rijn** [comment]
You used `scoped` in style tag.

You can assign a class to `<Page>` like this way.
```
<Page class="my-page">
```

**Comment by jarvan4dev** [comment]
@rijn 没有效果

**Comment by rijn** [comment]
[https://codepen.io/rijn/pen/egxXmY](https://codepen.io/rijn/pen/egxXmY)

**Comment by jarvan4dev** [comment]
@rijn thx, but I wonder that why we need add a new class for the Page, why we can't use the class from iView? For example, can we do like this?

<div class="page">
<Page>
</div>
.page .ivu-page {
    float: right;
  }

you know we can not add a new class for some component, like <Menu-group>

**Comment by jarvan4dev** [comment]
@rijn thx, but I wonder that why we need add a new class for the Page, why we can't use the class from iView? For example, can we do like this?
'''
<div class="page">
<Page>
</div>
.page .ivu-page {
    float: right;
  }
'''

you know we can not add a new class for some component, like '<Menu-group>'

**Comment by rijn** [comment]
Since some components are child, you cannot overwrite its style under scoped tag.
[](https://github.com/vuejs/vue/issues/4298)

**Comment by jarvan4dev** [comment]
@rijn thx, but I wonder that why we need add a new class for the Page, why we can't use the class from iView? For example, can we do like this?

```
<div class="page">
<Page>
</div>
.page .ivu-page {
    float: right;
  }
```
you know we can not add a new class for some component, like `<Menu-group>`
