### ISSUE TITLE
[Feature Request]DateTimePicker

### ISSUE THREAD

**Issue by alphabetaxz** [iview/iview#2710]
### What problem does this feature solve?
Iview now only has DatePicker and TimePicker separately, sometime, we need DatePicker and TimePicker combined into one component just like DateTimePicker of element-ui

### What does the proposed API look like?
return utc or local format data

**Comment by icarusion** [comment]
```vue
<DatePicker type="datetime" placeholder="Select date and time" style="width: 200px"></DatePicker>
```
