### ISSUE TITLE
使用 babel-plugin-import 在ie中会报错导致不显示页面

### ISSUE THREAD

**Issue by fanilly** [iview/iview#2714]
只要在组件中加入下图标识的一行就报错，仅限于ie中（ie所有版本）,这个是bug吗？还是我的写法有误
![image](https://user-images.githubusercontent.com/26714039/34410267-d3b1ee66-ec09-11e7-833a-27515378b120.png)

![tim 20171228195904](https://user-images.githubusercontent.com/26714039/34410239-a5c07054-ec09-11e7-8c1a-bc7eaebcd80a.png)
![tim 20171228195911](https://user-images.githubusercontent.com/26714039/34410240-a60db3d2-ec09-11e7-8270-40cee38745b1.png)

**Comment by shen-lan** [comment]
怎么解决的？
