### ISSUE TITLE
The [Bug Report]table component, when the height is specified, and the data is empty, the width of the header will be disorderly.


### ISSUE THREAD

**Issue by jjwangel** [iview/iview#2723]
### Environment
操作系统：win10 / 360浏览器 / vue：2.5.2 / iview：2.8.0

### Reproduction link
[https://jsfiddle.net/jjwangel/z6hxj20m/](https://jsfiddle.net/jjwangel/z6hxj20m/)

### Steps to reproduce
table组件，当指定了height，并且数据为空时

### What is expected?
table组件，指定height，并且数据为空时，表头宽度不会改变。

### What is actually happening?
table组件，当指定了height，并且数据为空时，表头宽度会错乱。

**Comment by jjwangel** [comment]
请问有明确的修复时间吗？

**Comment by jjwangel** [comment]
请问有明确的修复时间吗？

**Comment by icarusion** [comment]
The latest version has been fixed
