### ISSUE TITLE
[Feature Request]Range datepicker backwards range selecting

### ISSUE THREAD

**Issue by Loruz** [iview/iview#2731]
### What problem does this feature solve?
Ability to select date range not only if maxDate > minDate but both ways.

### What does the proposed API look like?
After selecting minDate (start date) in range datepicker. markRange and ability to select range should not only work if your maxDate(end date) is bigger than minDate but also if its less. For example if i select February 5, and then hover to February 10 and select it,  I get range for Feb 5 to 10 its ok. But if i select February 5 and then hover to February 2 markRange is not working and if i select February 2 my minDate is reseted and I get new (start date). But i should get range from Feb 2 to Feb 5.

**Comment by SergioCrisostomo** [comment]
I'm ok with this change, @icarusion what do you think?

So basically the range picker would make a internal check for the period and return the minDate and the maxDate regardless of which was chosen first.

**Comment by icarusion** [comment]
yeah, i have discussed with @SergioCrisostomo before, and it was decided to do this.
