### ISSUE TITLE
[Bug Report]Layout layout document code is incorrect, please correct


### ISSUE THREAD

**Issue by aubdiy** [iview/iview#2735]
### Environment
mac/chrome版本 63.0.3239.84（正式版本） （64 位）

### Reproduction link
[https://www.iviewui.com/components/layout](https://www.iviewui.com/components/layout)

### Steps to reproduce
1. 打开文档连接   https://www.iviewui.com/components/layout
2. 找到 “侧边布局”
3. 点击 “Show Code” 按钮
4. 复制 示例代码 到 vue 模板中
5. 启动项目
6. 查看 第4步中 所操作的 页面
7. 样式错乱

问题原因：
里面的源代码中，<Sider> 标签外层 缺少 `<Layout>` 标签

### What is expected?
更新文档，使示例正确

### What is actually happening?
7. 样式错乱

---
里面的源代码中，<Sider> 标签外层 应该有个 `<Layout>` 标签，否则样式是乱的，请更正

**Comment by icarusion** [comment]
@lison16 Please have a look, thanks.

**Comment by lison16** [comment]
@icarusion This problem has been resolved, please update the newest doc

**Comment by icarusion** [comment]
https://github.com/iview/iview-doc/commit/263265f99673113543751e1f2ad6427a95eb0bbb
