### ISSUE TITLE
[Bug Report]iview2.7.4 the use of on-demand loading, why invalid characters in IE 11 SCRIPT1014: error


### ISSUE THREAD

**Issue by camoth** [iview/iview#2747]
### Environment
win10/ie11/vue 2.5.2

### Reproduction link
[http://www.wggj1980.com/login](http://www.wggj1980.com/login)

### Steps to reproduce
打开链接即重现

### What is expected?
帮忙解决

### What is actually happening?
支持按需引入

---
按照官网文档按需引入配置方法，均不支持IE11

**Comment by camoth** [comment]
Solve the problem like the following configuration
```javscript
//  webpack.base.config.js
 {
        test: /iview.src.*?js$/,
        loader: 'babel-loader'
  },
```

```javascript
// .babelrc
[
	"import",
	{
		"libraryName": "iview",
		"libraryDirectory": "src/components"
	}
]
```

**Comment by dgroh** [comment]
Ok, this should be documented in the iView webpack demo...this fixed the issue!

**Comment by agrass-GitHub** [comment]
` vue.config.js
   chainWebpack: config => {
    config.module
      .rule("babel")
      .test(/iview.src.*?js$/)
      .use("babel-loader")
      .loader("babel-loader")
      .end();
  },`

**Comment by cat-kun** [comment]
多谢大佬，问题解决了

**Comment by ZKaiCode** [comment]
我加入该解决方案 但是还是存在【SCRIPT1014: 无效字符】 的错误！！

**Comment by iceuncle** [comment]
thanks very much

**Comment by wangyingjie123** [comment]
我也是vuecli3按需引入的，无法兼容ie

**Comment by Lengluws** [comment]
@vue/cli 按需引入 ie11打开页面一片空白。

**Comment by Ca11MeE** [comment]
thanks

**Comment by pathganker** [comment]
thanks
