### ISSUE TITLE
[Bug Report]Select options 改变，label显示没有变

### ISSUE THREAD

**Issue by neoni123** [iview/iview#2765]
### Environment
windows 10/chrome63/Vue 2.5.13

### Reproduction link
[https://jsfiddle.net/yyrzhm46/179/](https://jsfiddle.net/yyrzhm46/179/)

### Steps to reproduce
①一个select，options 是Data中的List。
②点击按钮，改变List为List2。
③选择select里的值，显示出来的还是List中的label。
注：List和List2中的所有项的value完全一致时，会出现这样的错误，只要有一个不一样就不会。

### What is expected?
显示正确

### What is actually happening?
显示不正确

**Comment by tangsj** [comment]
options  :key值 不要重复用一样的  :key="`${item.value}_${item.label}`"

**Comment by SergioCrisostomo** [comment]
@neoni123 if the solution @tangsj suggested did not work for you please let me know so we can reopen and investigate.
