### ISSUE TITLE
[Feature Request]ColorPicker color selector adds disabled state and sixteen decimal color values manually fill in function


### ISSUE THREAD

**Issue by xwLyc** [iview/iview#2767]
### What problem does this feature solve?
表单中需要选择颜色后，保存成功后，就进入不可选中状态，点击编辑之后，才可以进行选择。类似于input的disabled功能。 

### What does the proposed API look like?
期望选择器，可以设置禁用状态也可以进行手动输入色值功能

**Comment by icarusion** [comment]
#4353
