### ISSUE TITLE
[Bug Report] responsive layout offset bug.


### ISSUE THREAD

**Issue by zwjtheone** [iview/iview#2769]
### Environment
"iview": "^2.7.3", windows.chrome

### Reproduction link
[https://jsfiddle.net/zwjtheone/yyrzhm46/187/](https://jsfiddle.net/zwjtheone/yyrzhm46/187/)

### Steps to reproduce
                <row>
                    <i-col style="background-color: #2B85E4" :xs="{ span: 5, offset: 1 }" :lg="{ span: 6, offset: 0 }">Col</i-col>
                    <i-col style="background-color: #2B85E4" :xs="{ span: 11, offset: 1 }" :lg="{ span: 6, offset: 0 }">Col</i-col>
                    <i-col style="background-color: #2B85E4" :xs="{ span: 5, offset: 1 }" :lg="{ span: 6, offset: 0 }">Col</i-col>
                </row>

### What is expected?
在 xs offset 1 个 栅格，在lg 下不 offset 。

### What is actually happening?
在xs下偏移1.在lg下偏移0.不起作用，会沿用xs偏移量

**Comment by lxmfly123** [comment]
I'm using v3.1, still not fixed.

**Comment by dousybox** [comment]
I have the same problem with 3.4.0

### Environment
any OS / any Browser / vue 2.x

### Reproduction link
[https://run.iviewui.com/preview/oEqDQE8Z](https://run.iviewui.com/preview/oEqDQE8Z)

### Steps to reproduce
Resize the preview window, when the size over the grid `lg` size (default is 1200px).
the xl config `offset:'0'` has no effect, the cofig is just like below:

```javascript
    responsiveFixed: {
      xs: 24,
      md: 12,
      lg: {
        span: 8,
        offset: 16
      },
      xl: {
        span: 6,
        offset: '0'
      },
      xxl: 4
    }
```

### What is expected?
offset:0 has right effect

### What is actually happening?
offset:0 do not work

**Comment by dousybox** [comment]
@icarusion is this problem will be fix in future?
