### ISSUE TITLE
[Bug Report]Value can not be number when option rendered in the form

### ISSUE THREAD

**Issue by 2hz4917** [iview/iview#2771]
### Environment
OS: win10 / Browser: chrome63 /Vue: 2.5.2 /Iview: 2.8.0

### Reproduction link
[https://jsfiddle.net/newrh7o8/](https://jsfiddle.net/newrh7o8/)

### Steps to reproduce
<form-item prop="city" label="city">
        <i-select v-model="formValidate.city" style="width:200px">
              <i-option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</i-option>
        </i-select>
    </form-item>

### What is expected?
Form validation can be correct

### What is actually happening?
Form validation failed

---
v-for渲染的情况下，当option的value为number类型时，会发生验证不成功的现象

**Comment by n0m4dz** [comment]
+1 same here

**Comment by 2hz4917** [comment]
如果返回的value是int，只需要在规则验证对应的规则里添加 type:"number"
