### ISSUE TITLE
table渲染下拉，内容被遮盖

### ISSUE THREAD

**Issue by benjamintshi** [iview/iview#2784]
![_20180110164545](https://user-images.githubusercontent.com/6221737/34766025-1950a0e2-f62e-11e7-91af-a5954bedc91f.png)

`{
            title: '服务器类别',
            key: 'serverTypeId',
            render: (h, params) => {
              return h('div',[
                h('Select', {
                  props: {
                    value: params.row.serverTypeId
                  },
                  on: {
                    input: (val) => {
                      this.tbActiveData[params.row._index].serverTypeId = val;
                    }
                  }
                }, this.getCateTypes(h))
              ]);
            }
          }`

**Comment by shen-lan** [comment]
大兄弟 ，你这样做遇到过下拉选择后 表格页面数据不变的情况吗

**Comment by benjamintshi** [comment]
@shen-lan  没有，数据不变你可以尝试对数组进行sort一下。
