### ISSUE TITLE
[Bug Report] creates a composite input box with the render method, and the content in the slot is not created


### ISSUE THREAD

**Issue by ForBurning** [iview/iview#2792]
### Environment
win7

### Reproduction link
[https://jsfiddle.net/yyrzhm46/191/](https://jsfiddle.net/yyrzhm46/191/)

### Steps to reproduce
JSFiddle

### What is expected?
正确显示

### What is actually happening?
 slot中的内容显示出来

**Comment by icarusion** [comment]
写错了，查看 Vue 文档。
