### ISSUE TITLE
日期时间控件——选择时间时麻烦

### ISSUE THREAD

**Issue by szoyaung** [iview/iview#2794]
DatePicker中使用type="datetime"的时候，选择时间需要多点击一次按钮，很不方便，而且很多时候用户都看不到那个地方有个按钮可以选择时间。

**Comment by gezhigang1005** [comment]
@szoyaung  你好，请问下这个问题你解决了么 ？

**Comment by szoyaung** [comment]
@gezhigang1005 不好意思，好像没有解决吧，忘记了 ~~，后来我用饿了么，不用iview了
