### ISSUE TITLE
如何继续手动上传文件

### ISSUE THREAD

**Issue by duancong** [iview/iview#2796]
绑定 before-upload，并返回false，阻止了文件上传。然后怎么继续手动开始上传文件？

**Comment by xiaohaiH** [comment]
给 upload 设置 ref 然后运行该 ref 下的 uploadFiles 函数, 参数为需要传送的文件,格式是数组

**Comment by duancong** [comment]
@xiaohaiH (this.$refs.file as any).post(this.file);我现在是这么写的，通过一个post函数将文件传过去。这个在官方文档中有没有给出？

**Comment by xiaohaiH** [comment]
嗯嗯,  刚刚在最后一页意见中有看到,   没有, 看源码才发现的

**Comment by xiaohaiH** [comment]
请问, 上传成功后需要展示, 路径后台未返回,怎么才可以查看该文件的本地路径呢?

**Comment by duancong** [comment]
@xiaohaiH 我也是找了很多国内外的资料才找见的，这个应该是常用的，文档中应该写出来。我是在上传的时候通过一个函数把图片base64直接就保存了。

**Comment by xiaohaiH** [comment]
@duancong 请问你是在哪个函数中获取到的呢?  我还没找到方法!!

**Comment by duancong** [comment]
`
public beforeUpload(file: any): boolean {
        this.file = file;
        if ((window as any).FileReader) {
            const fr: any = new FileReader();
            fr.onloadend = (e: any): void => {
                this.avatar = e.target.result;
            };
            fr.readAsDataURL(file);
        }
        return false;
    }
`

**Comment by xiaohaiH** [comment]
@duancong 谢谢你的解答, 已经解决问题了, 感谢
