### ISSUE TITLE
[Bug Report]IOption emits on-select-close on every interaction on page

### ISSUE THREAD

**Issue by allesan** [iview/iview#2798]
### Environment
Linux, Firefox 57, Vue 2.5.13

### Reproduction link
[https://jsfiddle.net/m6mo1the/](https://jsfiddle.net/m6mo1the/)

### Steps to reproduce
Just record events in vue devtools and you will see this event fired multiple times on any click anywhere

### What is expected?
on-select-close emited only in interaction with select dropdown

### What is actually happening?
on-select-close emited is emited in interaction with any element on the page

**Comment by icarusion** [comment]
not $emit

**Comment by allesan** [comment]
Not emit but this event is triggered on every move or click on the page which is slowing down the page/browser.

**Comment by fbjorn** [comment]
Same problem here

**Comment by starier** [comment]
me too

**Comment by RobinJason** [comment]
I put some console.log in select.vue and option.vue, and I found the problem is caused by **v-clickoutside directive**.
It triggered **handleClose Funtion**,then I add an **if condition** in **handleClose Funtion**,like this: 
            handleClose() {
                if (this.visible) {
                    this.hideMenu();
                }
            }
now,it is not appear the problem
