### ISSUE TITLE
The [Bug Report]checkboxGroup is nested, and the outer layer affects the inner layer


### ISSUE THREAD

**Issue by zhangpf1127** [iview/iview#2805]
### Environment
iView2.8.0

### Reproduction link
[https://jsfiddle.net/zhangpf1127/v8o9t62q/](https://jsfiddle.net/zhangpf1127/v8o9t62q/)

### Steps to reproduce
点击里层checkbox，再点击外层checkbox，里层的选项会取消选中

### What is expected?
checkboxGroup互不影响，每组checkboxGroup只控制自己的内容。
另外，仅仅取消了选中状态，里层checkbox的值未发生变化。

### What is actually happening?
外层影响到内层的选中状态

---
多笔订单（checkboxGroup），每笔订单都有多件商品（checkboxGroup），勾选订单中的商品进行批量操作。

**Comment by icarusion** [comment]
不能这样嵌套使用。
