### ISSUE TITLE
table render 渲染问题 传参问题

### ISSUE THREAD

**Issue by jsonformat** [iview/iview#281]
![iview1](https://cloud.githubusercontent.com/assets/18202503/23059891/52913bea-f536-11e6-8e2f-0613e65162d3.png)
----------------------------------------------------------
![iview2](https://cloud.githubusercontent.com/assets/18202503/23059892/5291d76c-f536-11e6-9c52-9549f30e4f9c.png)
这是bug吗, 为什么传过去就变了, return 里面我看了很多栗子也试了写法, 但是还是不行, 有时候还会undefined

**Comment by yanghdx** [comment]
自动转成int值了，  改成 pass(1, '${row.orderId}')，就是加上单引号

**Comment by jsonformat** [comment]
可以的:)
