### ISSUE TITLE
[Feature Request] how to change the corners of all components to right angles


### ISSUE THREAD

**Issue by roshomon** [iview/iview#2810]
### What problem does this feature solve?
使风格切换成Metro的样式；
我已经引用引用带有以下代码的less，但似乎没有效果
@btn-border-radius : 0px;
@btn-border-radius-small: 0px;
@border-radius-base : 0px;
@border-radius-small : 0px;

### What does the proposed API look like?
主题如果有metro，能直接更改一个值最好

**Comment by icarusion** [comment]
自定义主题。
