### ISSUE TITLE
[Feature Request]DatePicker option to set minDate

### ISSUE THREAD

**Issue by allesan** [iview/iview#2814]
### What problem does this feature solve?
Usability would improve with this because there are many cases where one needs to operate with dates in distant future, and with setting this option you would not need to click to get to the month or year you need to input.

### What does the proposed API look like?
Just add one option where can minimal date be set.

**Comment by leixu2txtek** [comment]
``` javascript
<template>
    <Row>
        <Col span="12">
            <DatePicker type="date" :options="options3" placeholder="Select date" style="width: 200px"></DatePicker>
        </Col>
        <Col span="12">
            <DatePicker type="date" :options="options4" placeholder="Select date" style="width: 200px"></DatePicker>
        </Col>
    </Row>
</template>
<script>
    export default {
        data () {
            return {
                options3: {
                    disabledDate (date) {
                        return date && date.valueOf() < Date.now() - 86400000;
                    }
                },
                options4: {
                    disabledDate (date) {
                        const disabledDay = date.getDate();
                        return disabledDay === 15;
                    }
                }
            }
        }
    }
</script>
```


in option prop, you can set disabledDate function to limit

**Comment by SergioCrisostomo** [comment]
@allessan your idea was a good idea and was added. If you read the comments in the linked issue you will see it among the added features. 
Please test it in the next release or in the nightly version. Cheers

**Comment by allesan** [comment]
@SergioCrisostomo thanks!!
