### ISSUE TITLE
The min of the [Bug Report]Slider is not used when the number is decimal


### ISSUE THREAD

**Issue by JoyceBryant** [iview/iview#2825]
### Environment
mac10.13.2/chrome63.0.3239.132/vue任意版本

### Reproduction link
[https://jsfiddle.net/vzhtmxg9/](https://jsfiddle.net/vzhtmxg9/)

### Steps to reproduce
见jsfiddle中，初始化是正常的，只要对滚动条进行拖动，就可以复现

### What is expected?
能够正常使用

### What is actually happening?
滚动条样式和功能均出现问题

---
业务场景是有一个设置项需要使用最小值为0.1的滚动条

**Comment by humengtao** [comment]
min => :min and style is fine but decimal is not work

**Comment by daiyanze** [comment]
的确拖拽的时候没办法拖动到小数点位，不过输入框里的上下键可以实现小数点位移动。
例子： https://jsfiddle.net/df0bog5u/

其实小数的情况可以通过计算来解决，用滑块拖动得到的数字处以1000就能得到百分比，然后再把结果计算映射给像 `<InputNumber/>` 之类的组件就行。
