### ISSUE TITLE
[Bug Report]Col components are wrong in eslint-plugin-vue


### ISSUE THREAD

**Issue by weihongyu12** [iview/iview#2828]
### Environment
vue 2.5.13/eslint-plugin-vue 4.0.0

### Reproduction link
[https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-parsing-error.md](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-parsing-error.md)

### Steps to reproduce
eslint-plugin-vue已经是正式版，在eslint的配置下，运行如下代码
```
<Col>
  <Button>test</Button>
</Col>
```
eslint检查报错
```
3:7  error  Parsing error: x-invalid-end-tag  vue/no-parsing-error
```

### What is expected?
因为col是自闭合标签，希望有有效的方法解决vue/no-parsing-error的问题

### What is actually happening?
error  Parsing error: x-invalid-end-tag  vue/no-parsing-error

**Comment by SergioCrisostomo** [comment]
The linter thinks its the [HTML native `<col>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col) which is a empty element. Did you try using `i-col` in your template?

**Comment by icarusion** [comment]
you can use `i-col`

**Comment by shilx** [comment]
https://github.com/vuejs/vetur/blob/master/docs/linting-error.md#linting-for-template

可以单独关闭标签检查，现在舒服多了~

**Comment by LinXibei** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/13112071/35504066-ecc318ae-051c-11e8-855d-ede418204fed.png)
![image](https://user-images.githubusercontent.com/13112071/35504084-fad530f8-051c-11e8-82c8-7ed0974994ff.png)

I have set `vue/no-parsing-error`, but it's not useful. So how to do next?

**Comment by hua-cyh** [comment]
来自：[vs code 里面 如何 去掉 invalid-end-tag 的lint错误](http://pastebin.com/HEeizYMN)
 //.eslintrc.js
 rules:{
     'vue/no-parsing-error': [2, {
      "x-invalid-end-tag": false
    }]
 }
 //settings 里面的配置：
 "vetur.validation.template": false

**Comment by 1990jtf** [comment]
@hua-cyh niubility,thanks!

**Comment by 13463736868** [comment]
@hua-cyh  厉害了……

**Comment by caryxiao** [comment]
webstorm 里面怎么搞啊，， 设置了"vue/no-parsing-error": [2, { "x-invalid-end-tag": false }]
编译没报错，，， 但是特么编辑器还是报错，心塞

**Comment by Beats0** [comment]
webstorm设置"vue/no-parsing-error": [2, { "x-invalid-end-tag": false }]没问题啊，得重启编译dev才能生效的

**Comment by ChenPt** [comment]
@hua-cyh thx!

**Comment by jizhuozhi** [comment]
Why not design it as the default with an i-prefix likes element start with ele-prefix?  :)

**Comment by PDKSophia** [comment]
设置了"vue/no-parsing-error": [2, { "x-invalid-end-tag": false }]之后不得行，在VSCode设置"vetur.validation.template": false还是不得行。编译没有报错， 但是vscode编译器老报错，看着我很难受啊，怎么解决？

**Comment by ghost** [comment]
> 设置了"vue/no-parsing-error": [2, { "x-invalid-end-tag": false }]之后不得行，在VSCode设置"vetur.validation.template": false还是不得行。编译没有报错， 但是vscode编译器老报错，看着我很难受啊，怎么解决？

设置完vscode 需要重启一次vscode 试试。 我这里设置完不生效，重启后生效了。

**Comment by rlam3** [comment]
I'm getting a similar error 

<img width="584" alt="screen shot 2019-02-21 at 8 08 31 am" src="https://user-images.githubusercontent.com/1154044/53174656-f5267d00-35af-11e9-9d7c-b09eaa1dbe66.png">

I added `"vetur.validation.template": false,` to my settings.json

And added custom rules to eslintrc.js

```
  rules: {
    "vue/no-parsing-error": [2, {
      "x-invalid-end-tag": false
    }]
  }

```

Nothing seems to be working....

**Comment by ZJH9Rondo** [comment]
@ghost 重启vscode即可

**Comment by chengxuzhang** [comment]
> webstorm 里面怎么搞啊，， 设置了"vue/no-parsing-error": [2, { "x-invalid-end-tag": false }]
> 编译没报错，，， 但是特么编辑器还是报错，心塞

重启就没事了
