### ISSUE TITLE
[Feature Request] recommends InputNumber components to support null values


### ISSUE THREAD

**Issue by QJX** [iview/iview#2829]
### What problem does this feature solve?
一个配置可能需要支持空值和数字，如果使用这个组件就没法输入空值，导致无法使用，希望可以加个props来判断是否支持输入空值。

### What does the proposed API look like?
    <InputNumber v-model="number" :min="-30" :max="30" :empty="true" />

**Comment by QJX** [comment]
@icarusion ， Hope this can be priority， thanks！

**Comment by daiyanze** [comment]
@QJX @icarusion `<InputNumber />` only supports numbers now, so inputting `null` would be a type violation. Do you think it would be okay to allow `string` input while setting `:empty="true"`?

My opinion is to set value to `null` and display `null` in `<inputNumber/>` if the given input is not a `number`.

**Comment by QJX** [comment]
@daiyanze, As long as the null values do not show 0, I think ok.

**Comment by QJX** [comment]
@daiyanze，When can solve this problem

**Comment by daiyanze** [comment]
@QJX 
Supporting the null value is somehow breaking a lot of logics of the `<InputNumber />` component from my point of view. However there are many good approaches to make the feature `:empty="true"` function well. At this moment I think we need to discuss and figure out one practical solution. Sorry for the inconvenience.

But I think you may try bind `null` to your output data by somehow using `:disabled` in a smart way.
(At least I think this is doable. Not test it yet  :p)
For example:
```vue
<template>
  <InputNumber :disable="disable" v-model="value" />
</template>
<script>
export default {
  ...
  data () {
    return {
      value: 0,
      disable: false
    }
  },
  computed: {
    output () {
      if (this.disable) {
        return null
      }
      return this.value
    }
  }
}
</script>
```

@icarusion @SergioCrisostomo How do you like the `:empty` feature for `<InputNumber />`?

**Comment by SergioCrisostomo** [comment]
I also don't like a `inputNumber` that accept other _Type_ than number. 
So I'm open for a prop, or `NaN` instead of a `null` because

```
typeof null === "object"
typeof NaN === "number"
```

**Comment by QJX** [comment]
@daiyanze, 饿了吗之前的版本也不支持空值，在2.1的版本已经改过来了，我觉得这个还是有必要支持空值的。
https://github.com/ElemeFE/element/issues/9344

**Comment by daiyanze** [comment]
我觉得element的做法虽然产生`undefined`这种不好用的数据类型，但其实也是一种不错的办法。
按照Sergio的想法来是当把数字删掉的时候，在watch里把`value`变成`NaN`，这样就可以解决输出的数据类型不统一的问题了。
@QJX `NaN` OK不？

**Comment by QJX** [comment]
@daiyanze，如果考虑数据类型，NaN确实比较合理，但是我试了下，如value为NaN，输入框显示的是NaN，如果value为undefined，输入框显示的是空。我觉得value为‘’、undefined、NaN三者中的一种，只要能实现输入框显示为空，都符合需求。

**Comment by daiyanze** [comment]
@QJX 作为输出值，对于InputNumber来讲`blank string`的类型用起来比较别扭。我觉得最终还是以`NaN`为输出结果最好。
刚刚推上去一个PR，希望能在近期内merge掉。

https://github.com/iview/iview/pull/2971

**Comment by QJX** [comment]
@daiyanze 3Q very much. 希望能在这几天发版本加上这个功能。

**Comment by icarusion** [comment]
#3174

**Comment by yangxiyangxi** [comment]
在inputNumber外套用i-form 和Form-item标签，设置默认值，如
![image](https://user-images.githubusercontent.com/25736231/44828276-c0adb600-ac49-11e8-83d7-7b774d2f1437.png)

再设置绑定的值formInline:{
InTotalLimit: null,
passRate:null,
},
就不会再报类型错误了，并且初始值为空
