### ISSUE TITLE
iview级联控件无法手动清空

### ISSUE THREAD

**Issue by huiliangShen** [iview/iview#283]
iView 版本号

0.9.17

操作系统/浏览器 版本号

Win7/ chrome55

Vue 版本号

1.0.26

能够复现问题的在线示例

https://codepen.io/anon/pen/mRYKrZ?editors=1111

复现步骤

开始选中一个地址，然后点击清空，使空间值清空

问题现象，以及你期望的结果是怎样的?

现在无法清空

期望提供清空的正确方法

你估计可能的原因是什么（选填）？

**Comment by icarusion** [comment]
vm.clearSelect()
