### ISSUE TITLE
Menu组件的一个建议

### ISSUE THREAD

**Issue by ChiHai-Chuck** [iview/iview#284]
建议在Menu组件的on-select事件返回值增加返回当前MenuItem上级Submenu的key，在有些时候，需要同时用到MenuItem和上级Submenu的key

**Comment by rijn** [comment]
You can add a delimiter like dash in the key and split it manually.

**Comment by ChiHai-Chuck** [comment]
@rijn 哈哈，我现在就是这样做的，但是感觉不太规范而且略显复杂

**Comment by rijn** [comment]
I suppose that component Menu only has two levels, it's unnecessary to return the path like an array or something. Splitting may be the better answer to this issue. =)

**Comment by waney** [comment]
我居然碰到一个难以启齿的问题，menu的链接路径(路由)是怎么加的。。

**Comment by ChiHai-Chuck** [comment]
可以在事件里用vm.$router控制路由

**Comment by waney** [comment]
@ChiHai-Chuck 我是用2.0分支，vue也是2.0，接收不到事件。

**Comment by rijn** [comment]
@waney Branch 2.0 is under developing.

**Comment by waney** [comment]
@rijn yes

**Comment by waney** [comment]
<Menu active-name="1-1" :open-names="['1']" theme="dark" width="auto" @on-select="clickMenu">
开发中的 Branch 2.0 实际是可以用的 @on-select

**Comment by waney** [comment]
`<Menu active-name="4-1" :open-names="['4']" theme="dark" width="auto" @on-select="clickMenu">`

**Comment by a1292717155** [comment]
我也想问这个怎么做页面跳转,`router-link`不管用

**Comment by rijn** [comment]
`v-link` in `Menu-item`

or `vm.$router` in menu activate-key watcher

**Comment by marlonone** [comment]
@rijn How to use the method `updateActiveKey`

**Comment by isdot** [comment]
@marlonwon use :activeName="yourVariable", change yourVariable

**Comment by icarusion** [comment]
2.0 已更名为 `updateActiveName`
