### ISSUE TITLE
[Bug Report]input enter can cause page overloading


### ISSUE THREAD

**Issue by Jame0527** [iview/iview#2842]
### Environment
vue@2.3.3 iview@2.0.0-rc.17 

### Reproduction link
[https://jsfiddle.net/yyrzhm46/](https://jsfiddle.net/yyrzhm46/)

### Steps to reproduce
modal里边input框聚焦的时候点击enter 

### What is expected?
没有绑定事件应该不会触发任何操作

### What is actually happening?
按下enter的时候导致整个页面重新加载

---
jsFiddle链接地址随便写的 代码如下
    <Modal v-model="modal" width="460" height="100" :mask-closable="false">
       
        <div style="width:100%;padding:0 15px">
            
            <h3 style="height: 30px;line-height:30px" v-show="showType == 3"> 冲正</h3>
            <div class="moneyCont">
               
                <i-form :model="formValidate" :rules="ruleValidate" ref="formValidate" v-show="editMoney">
                    <form-item prop="value" label="输入自定义金额: ">
                        <i-input type="text" name="value" v-model="formValidate.value" style="width: 150px;" @on-change="custormMoney" ></i-input>
                    </form-item>
                </i-form>
                <p v-show="showType == 3">
                    最近充值金额 ￥{{lastCharge}}
                </p>
              
                        
                   
            </div>
        </div>
        
         <div slot="footer">
            <i-button @click="modal=false">取消</i-button>
            <i-button type="primary" @click="confirm">确定</i-button>
        </div>
    </Modal>

**Comment by classLfz** [comment]
@Jame0527 我也遇到了类似的问题，好像是form表单下边只有一个输入框Input的时候，按下enter键会刷新页面。我是执行 `e.preventDefault()` 把事件阻断解决的。

后更：
不好意思，似乎我上边的错了，form标签上加 `@submit.native.prevent` 解决的，文档上有写。
