### ISSUE TITLE
[Feature Request]Table column calculated

### ISSUE THREAD

**Issue by fengerzh** [iview/iview#2843]
### What problem does this feature solve?
For example, column B is the calculated result of column A, if column A content changed, column B should also be automatically changed.

### What does the proposed API look like?
I hope iView table can implement a listener mechanism on column or cell data, once the data changed, the event will cause another column data changed.

```
        {
          title: 'A',
          key: 'A',
        },
        {
          title: 'B',
          key: 'B',
          watch: 'A',
          render: (h, params) => {
            return params.row.A   100;
          },
        },
```

**Comment by fengerzh** [comment]
Maybe it's not a so good idea. I've already found a way to reload the Table. Just call fetchData again to put new data in table source will cause Table to rerender, so this feature may not be so necessary. Thank you!

**Comment by icarusion** [comment]
Thanks, as you said, this function can be solved by business.
