### ISSUE TITLE
[Feature Request]Page Component: Support navigation without 'total' set and provides only 'previous' and 'next' page

### ISSUE THREAD

**Issue by linxj** [iview/iview#2850]
### What problem does this feature solve?
Some backend server don't return data with total count of data. In this case, the client side should be able to navigate with 'previous' and 'next' button, showing the current page number(kind of similar to Bootstrap Pager https://getbootstrap.com/docs/3.3/components/#pagination-pager)

### What does the proposed API look like?
`<Page pager></Page>`

**Comment by icarusion** [comment]
supported in 3.0
