### ISSUE TITLE
Whether the Message component of the [Feature Request]iView can add a global configuration property to set up the Message component that only displays the latest generation at a time


### ISSUE THREAD

**Issue by HHH1994** [iview/iview#2851]
### What problem does this feature solve?
比如一个页面中会用到需要多提示，但是由于用户的重复操作，而导致页面出现了太多的message提示信息

### What does the proposed API look like?
this.$Message.config({
  isSingle:true//是否只显示单个Message
})

**Comment by icarusion** [comment]
暂无此计划。
