### ISSUE TITLE
table render 字符串 疑惑

### ISSUE THREAD

**Issue by jsonformat** [iview/iview#287]
遍历出这段字符窜该怎么做啊
<img width="1115" alt="iview5" src="https://cloud.githubusercontent.com/assets/18202503/23110736/6d21a72c-f75e-11e6-8fb1-382fb8d44485.png">
我试了这样
<img width="499" alt="iview" src="https://cloud.githubusercontent.com/assets/18202503/23110798/f0943944-f75e-11e6-9c13-3972bc3333da.png">
这样
<img width="550" alt="iview1" src="https://cloud.githubusercontent.com/assets/18202503/23110801/fd11f6f2-f75e-11e6-9adb-c1aa29b2c8b3.png">
还是不行, 求解, 谢谢, 这个里面字符窜写起来真是麻烦啊, 到底是为什么
按照官网的事例代码写都不行啊

**Comment by rijn** [comment]
```
v-for = "item in row.expressDetail.list"
```
Please read Vue doc.

**Comment by jsonformat** [comment]
基础的vue用法我还是知道的, 按照iview doc 的写法不行, 
<img width="1258" alt="iview2" src="https://cloud.githubusercontent.com/assets/18202503/23111153/a2ef0612-f761-11e6-90ee-5941cdd4e87f.png">

**Comment by rijn** [comment]
Have you passed `row` to the scope?

**Comment by jsonformat** [comment]
<img width="216" alt="iview0" src="https://cloud.githubusercontent.com/assets/18202503/23111283/81bf2fc0-f762-11e6-9d7d-02b7879f7be5.png">
物流公司已经显示了  row 在作用域

**Comment by rijn** [comment]
I have no idea. It cannot act like this if you have `row` in the scope. =(

**Comment by jsonformat** [comment]
Than before String mosaic hard to understand

**Comment by anykno** [comment]
iview table 的render函数是未完工的，今天遇到了个问题去看了下代码，只是把返回的string，用一个dummy component 编译下，请慎用，容易造成xss 漏洞, 或者自己encode下,  render 应该返回一个 vnode比较好点

**Comment by icarusion** [comment]
更新到 rc.13 后，使用新的 Render 函数
