### ISSUE TITLE
[Feature Request]Table should support v-model

### ISSUE THREAD

**Issue by KrishnaPG** [iview/iview#2880]
### What problem does this feature solve?
When table has "selected" and "expanded" options, data is not bound the user actions. Supply the data as v-model to the table allows, the row data to be kept in sync with the selected, expanded, highlighted etc. options correctly

### What does the proposed API look like?
<i-table v-model="data"

**Comment by icarusion** [comment]
`data` is an array, so the default is two-way binding.

iView `Table` deepCopy a data and not change user's data. You can use some event to change your original data.

**Comment by KrishnaPG** [comment]
Using event to modify the original idea is not correct. For two reasons:

1. Table should be 'data driven'. Not the other way around.
2. When user clicks on 'expand' button, the table expands the row. Then, let us say, we trigger an event to update the data (to set the `_expanded` property true for that row). Then this will cause the data update to redraw the the table again (since data is passed as prop to the table, any change in the data will make the table refresh/redraw).  Are you sure this double rendering is the right way?

The data supplied to the Table should be always kept in sync with the complete state of the table. User should be required to do the juggling around events, keep  modifying the data based on Table events.
