### ISSUE TITLE
使用this.$Modal.confirm呼叫Modal 重置loading失效

### ISSUE THREAD

**Issue by maplehsu** [iview/iview#2888]
我是通过this.$Modal.confirm来显示弹框，在触发onOk的时候来判断校验，如果校验失败，我想重置loading。大家给的方法，在this.$Modal.confirm这种方式里并没有生效，请问有什么解决方法吗？

this.loading = false;
this.$nextTick(() => {
   this.loading = true;
});

![image](https://user-images.githubusercontent.com/4917754/35258769-a5922252-003c-11e8-98b9-8f5f1a0d23a5.png)

**Comment by DntCore** [comment]
@maplehsu  你好！你上面的问题解决了吗？我也是跟你上面的一样使用自定义模态框，无法控制loading
