### ISSUE TITLE
[Bug Report]Spin scrollbar


### ISSUE THREAD

**Issue by h-wanli** [iview/iview#2889]
### Environment
win10

### Reproduction link
[https://www.iviewui.com/new-issue](https://www.iviewui.com/new-issue)

### Steps to reproduce
页面中存在滚动条是,点击下一步,spin出现,这时候滚动滚轮,spin只是页面高度,刚滚动出来的页面没有被spin盖住

### What is expected?
滚动滚动条,spin始终盖住下面页面

### What is actually happening?
滚动滚动条,spin没有盖住下面页面

**Comment by Johnwang69** [comment]
1

**Comment by Johnwang69** [comment]
请问，您是怎么解决此问题的？我的笨方法是：
1. 监听spin的show/hide状态，show时，跳到page顶部。
2. 同时#app容器的max宽高为100vh，overflow为hidden。
3. spin为hide时，去掉上述样式设置。
