### ISSUE TITLE
[Bug Report]各组件存在大量内存泄漏

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#2891]
### Environment
vue2.x

### Reproduction link
[https://github.com/iview/iview](https://github.com/iview/iview)

### Steps to reproduce
各组件内部$on之后在组件注销的时候并未$off

### What is expected?
各组件内部$on之后在组件注销的时候需要$off

### What is actually happening?
并未$off

**Comment by icarusion** [comment]
你真的有测试过吗，有测试数据吗

**Comment by ckpiggy** [comment]
It is interesting that vue will [remove all listener when $destroy](https://github.com/vuejs/vue/blob/f2b476d4f4f685d84b4957e6c805740597945cde/src/core/instance/lifecycle.js#L99-L141).
And the document [mentioned that](https://vuejs.org/v2/api/#destroyed)

**Comment by tivonheng** [comment]
赞同，尤其是table组件，简直不能忍
