### ISSUE TITLE
[Bug Report] appears style bug when using select, TimePicker, DatePicker components in modal


### ISSUE THREAD

**Issue by Shruan** [iview/iview#2897]
### Environment
vue 2.5.3 ; iview: 2.8.0

### Reproduction link
[https://jsfiddle.net/yyrzhm46/213/](https://jsfiddle.net/yyrzhm46/213/)

### Steps to reproduce
在modal中添加多个下拉类型表单，直至页面开始滚动， 打开下拉选项，滚动页面，会发现页面确实存在bug

### What is expected?
能尽快解决modal中的该bug

### What is actually happening?
modal中确实有该bug存在，希望尽快修复

---
目前已发现 存在问题的组件有  select 、 DatePicker、TimePicker
其他下拉类型组件不知道是否同样存在该问题
希望能尽快修复bug

**Comment by icarusion** [comment]
use `transfer`

**Comment by Shruan** [comment]
transfer  is invalid
