### ISSUE TITLE
[Feature Request] new tree selection TreeSelect component


### ISSUE THREAD

**Issue by weihongyu12** [iview/iview#2903]
### What problem does this feature solve?
类似 Select 的选择控件，可选择的数据结构是一个树形结构时，可以使用 TreeSelect，例如公司层级、学科系统、分类目录等等。

### What does the proposed API look like?
参见Ant Desigin [TreeSelect](https://ant.design/components/tree-select-cn/)

**Comment by SergioCrisostomo** [comment]
@weihongyu12 this is already possible with the [Tree component](https://www.iviewui.com/components/tree-en). Can you give a example where it is not the case?

**Comment by weihongyu12** [comment]
Tree component can only support the display, can not be used for drop-down selection box, in most cases, we need to show in a Select component a tree structure of data to represent the hierarchical relationship between data, such as the company department. TreeSelect component is a very effective solution.

Can refer to the [TreeSelect](https://ant.design/components/tree-select-cn/), here is a good reference

**Comment by weihongyu12** [comment]
TreeSelect can be used inside the Form, but the Tree component cannot

**Comment by elvisqi** [comment]
表单的下拉选项中使用树形结构是很普遍的场景，考虑Cascader可以支持部分功能

但在表单中使用，以下两个场景是Cascader 无法满足的：
1、勾选父级节点，如选择组织机构，可以选择一级部门
2、多选，场景太多

![image](https://user-images.githubusercontent.com/3584916/40520890-31f3668e-5ffb-11e8-9315-fb03c81d8ee7.png)

![image](https://user-images.githubusercontent.com/3584916/40520890-31f3668e-5ffb-11e8-9315-fb03c81d8ee7.png)

**Comment by WoolenWang** [comment]
对,我们都迫切地需要这个组件，希望老大们能做出来。

**Comment by negrochn** [comment]
下拉树感觉是很有必要的，建议支持异步加载，以及异步加载时能够设置初始值

开发的时候经常会遇到这样的功能需求

**Comment by icarusion** [comment]
same issue exist
