### ISSUE TITLE
[Bug Report]InputNumber component, suggestion of clearing up


### ISSUE THREAD

**Issue by fekata** [iview/iview#2907]
### Environment
操作系统：mac   浏览器：谷歌     iview：2.9.0    vue: 2.5.9

### Reproduction link
[https://jsfiddle.net/Lzqnnkor/4/](https://jsfiddle.net/Lzqnnkor/4/)

### Steps to reproduce
输入数字，按backspace删除或全选删除内容，然后焦后。

### What is expected?
能不能加一个判断，如果组建存在min属性，文本清空失焦后输入框的值为min的值，否则输入框的值为上一次的值。

### What is actually happening?
文本清空后，始终是上一次的正确值。

---
客户反馈无法清空数字输入框，希望清空输入框然后失焦后，文本框的值为0。

**Comment by daiyanze** [comment]
We suggest to add a new property to InputNumber for supporting `NaN` output. And a new PR for this new feature has been submitted.
Please take a look at this issue. 
#2829 
Thanks.

**Comment by icarusion** [comment]
#3174
