### ISSUE TITLE
Button component ivu-btn:active, .ivu-btn:focus never worked out

### ISSUE THREAD

**Issue by buildJava** [iview/iview#2908]
### Environment
mac/chrome 63.0.3239.108/Vue2.0/iview 2.9.0

### Reproduction link
[https://jsfiddle.net/rwa1x2f2/#&togetherjs=JPLgSQ4ssc](https://jsfiddle.net/rwa1x2f2/#&togetherjs=JPLgSQ4ssc)

### Steps to reproduce
click button component or focus on button component,the button will be surround by a light blue line, when iview 2.8.0 there did not had this problem, I found that on this situation the css [.ivu-btn, .ivu-btn:active, .ivu-btn:focus {
    outline: 0;
} ] never work!

### What is expected?
make the button appear like iview 2.8.0

### What is actually happening?
button surround by a light blue line

**Comment by icarusion** [comment]
check 2.9.0 changelog

**Comment by buildJava** [comment]
is this on purpose?

**Comment by icarusion** [comment]
yes, new features

**Comment by buildJava** [comment]
.....,eeeee, this is not a better appearance for a button component that type = text

**Comment by QJX** [comment]
@buildJava +1
https://github.com/iview/iview/issues/2910
他们不改回来，只能自己覆盖样式了

**Comment by buildJava** [comment]
@QJX 请问如果要覆盖样式的话怎么写呢，我自己增加了样式但是发现不生效呢

**Comment by herton7362** [comment]
@buildJava 他这个不是outline ，也不是border，是设置了一个box-shadow，根据你自己的需求把box-shadow设置为none就可以了

**Comment by xzzh999** [comment]
like this:

     .ivu-btn:focus {
        box-shadow: none;
     }

**Comment by nevermore424** [comment]
@buildJava  我这样写的：
.ivu-btn-my:focus {
  box-shadow: none !important;
}
然后引入自己改完的：
<Button class="ivu-btn-my"

就没了
