### ISSUE TITLE
[Feature Request]Select component Suggest

### ISSUE THREAD

**Issue by BosenY** [iview/iview#2913]
### What problem does this feature solve?
Select component will support both input and selection

### What does the proposed API look like?
support both input and selection

**Comment by SergioCrisostomo** [comment]
@BosenY can you be more clear and give a example that is not supported today?

**Comment by BosenY** [comment]
![2333](https://user-images.githubusercontent.com/16064272/35796484-ae0ab56a-0a97-11e8-83af-bfdb0131dce6.gif)
like this，but I have realized it myself. . .

**Comment by icarusion** [comment]
I think you should use `filterable` or `remote` prop, or you can use `AutoComplete` component.
