### ISSUE TITLE
The [Bug Report] date component cannot prohibit the display of the right scavenging button small icon


### ISSUE THREAD

**Issue by yangdan8** [iview/iview#2915]
### Environment
iview 2.9

### Reproduction link
[https://jsfiddle.net/e78x4wf4/1/](https://jsfiddle.net/e78x4wf4/1/)

### Steps to reproduce
打开以上url后,鼠标移入日期选择框,右侧的清除日期小图标依然可见和可操作

### What is expected?
禁止显示该按钮

### What is actually happening?
设置了clearable="false"其依然显示

**Comment by icarusion** [comment]
@yangdan8 your demo is wrong, you should set:
```vue
<date-picker :clearable="false">
```

but your code is:
```vue
<date-picker clearable="false">
```
