### ISSUE TITLE
[Bug Report]When I use Tabs component in IE 11 Encountered an error message, "findIndex" is not support in IE

### ISSUE THREAD

**Issue by lh900519** [iview/iview#2919]
### Environment
Window 10 / IE11 / Vue 2.5.13 / iview 2.9.0

### Reproduction link
[https://github.com/iview/iview/blob/2.0/src/components/tabs/tabs.vue](https://github.com/iview/iview/blob/2.0/src/components/tabs/tabs.vue)

### Steps to reproduce
```javascript
updateBar () {
    ......
    const index = this.navList.findIndex((nav) => nav.name === this.activeKey);
    .......
}
......
contentStyle () {
    const x = this.navList.findIndex((nav) => nav.name === this.activeKey);
    ......
}
```

### What is expected?
support IE

### What is actually happening?
not support IE

**Comment by Xotic750** [comment]
The polyfill should be packaged by the build routine. Which distribution file are you using, the .js or the .min.js?

**Comment by icarusion** [comment]
We remove some ES6 polyfills in iView new version, you can add on demand.

**Comment by lh900519** [comment]
@Xotic750 Thinks.

**Comment by lh900519** [comment]
@Xotic750 Thanks.
