### ISSUE TITLE
When the [Bug Report]InputNumber defines the precision, the number that is entered after the mouse circle is selected can only be input, and then the cursor is put to the end.


### ISSUE THREAD

**Issue by nickliufc** [iview/iview#2920]
### Environment
chrome 63，vue 2

### Reproduction link
[https://www.iviewui.com/components/input-number](https://www.iviewui.com/components/input-number)

### Steps to reproduce
1、设置inputNumber组件的precision为1或2；
2、在浏览器中，框选输入框内所有数字（或部分数字）；
3、输入数字；

```vue
<InputNumber :step="1" :precision="2"></InputNumber>
```

### What is expected?
希望在失去焦点blur后，再格式化输入的数字为带小数

### What is actually happening?
只成功输入第一个数字，第二个及后面的数字都失败，输入框的内容被即时的格式化为小数点数字；

---
查看源码后，发现，目前是直接对value进行了修改
```vue
            precisionValue () {
                // can not display 1.0
                return this.precision ? this.currentValue.toFixed(this.precision) : this.currentValue;
            }
```
建议将此方法改到blur的事件时发生

**Comment by taojianjian32** [comment]
遇到同样的问题了，解决了吗？

**Comment by Kunkka0229** [comment]
遇到同样问题，解决了吗？看源码value是实时进行toFixed的，能不能加一个节流函数解决呢？

**Comment by hailongma** [comment]
same issue

**Comment by fifteenzhang** [comment]
+1

**Comment by icarusion** [comment]
https://github.com/iview/iview/pull/4315
