### ISSUE TITLE
[Feature Request]Table header and content location (table and content location of the table)


### ISSUE THREAD

**Issue by awhhrn** [iview/iview#2924]
### What problem does this feature solve?
If the table header is centered,the content of the table can be centered, left or right.(表格的表头居中时，表格的内容可以居中，居左或居右)

### What does the proposed API look like?
The header positioning of the table does not affect the content location,separation of location attributes,the property is the control of the entire column.(表格的表头定位不影响内容定位,定位属性分离，algin属性是控制整列的)

**Comment by icarusion** [comment]
You'd better using `render` func to custom the header style.
