### ISSUE TITLE
[Feature Request]ColorPicker color selector


### ISSUE THREAD

**Issue by soloemperor** [iview/iview#2932]
### What problem does this feature solve?
项目中可提供颜色的选择

### What does the proposed API look like?
除了目前已有的选择方式外，还希望可以手动输入颜色的代码
实际使用环境中，若用户需要选择与上一个选项同样的颜色，在颜色选择器上，不容易选择到

**Comment by icarusion** [comment]
可以配合`Input`自己实现。
