### ISSUE TITLE
itable  设置 width 和height ，itable 的 table-body 高度计算有误

### ISSUE THREAD

**Issue by GITleonine1989** [iview/iview#294]
### iView 版本号
1.0.0

### 操作系统/浏览器 版本号

win10/chrome56
### Vue 版本号

1.0.26
### 能够复现问题的在线示例

http://jsbin.com/kuhalusici/1/edit?html,js,output
### 复现步骤
itable  设置 width 和height ，itable 的 table-body 高度计算有误，
### 问题现象，以及你期望的结果是怎样的?
期望table-body的高度 和 table-wrapper 应该只差一个table-header的距离才对，
colums比较少的时候高度计算是正确的
### 你估计可能的原因是什么（选填）？
colums比较多的时候，出现的，可能在colums比较多的时候计算table-header的高度出现了问题

**Comment by zili2000** [comment]
我也遇到类似问题了。楼上解决了吗？
