### ISSUE TITLE
[Bug Report]standalone compiling styles will show extend ' .ion' has no matches

### ISSUE THREAD

**Issue by hefengxian** [iview/iview#2947]
### Environment
node: v8.3.0 lessc: lessc 2.7.3 (Less Compiler) [JavaScript]

### Reproduction link
[https://github.com/iview/iview/blob/2.0/src/styles/common/iconfont/_ionicons-icons.less#L739](https://github.com/iview/iview/blob/2.0/src/styles/common/iconfont/_ionicons-icons.less#L739)

### Steps to reproduce
```bash
lessc index.less iview.css
```
```
extend ' .ion' has no matches
```

### What is expected?
no warning again, and i can't understand this code what for
```less
.@{ionicons-prefix}xbox:before
{
  &:extend(.ion);
}
```

### What is actually happening?
when compiling it show `extend ' .ion' has no matches`

**Comment by icarusion** [comment]
i think it is not an iview issue.
