### ISSUE TITLE
Upload组件在钩子before-upload里面手动给file添加属性, 在:on-success和:on-progress里面能够得到file新添加的属性??

### ISSUE THREAD

**Issue by pollux2015** [iview/iview#2956]
在beforeupload 给file对象添加了一个courseid
在on-success里面返回的file对象为什么没有这个courseid??
不是同一个file对象??

![image](https://user-images.githubusercontent.com/11935278/35613282-9cb7a04c-06a6-11e8-80d4-ca2f216e0c82.png)

**Comment by pollux2015** [comment]
- -!

**Comment by Hsensor** [comment]
这尼玛是一个严重的bug，代码作者自己都只要想用uid，却来坑我们

**Comment by 18876293672** [comment]
> 这尼玛是一个严重的bug，代码作者自己都只要想用uid，却来坑我好坑

**Comment by 18876293672** [comment]
老哥你这个是手动上传吗？能教教我怎么用吗
