### ISSUE TITLE
table render渲染不出来

### ISSUE THREAD

**Issue by zengjingke** [iview/iview#2959]
![_20180131192950](https://user-images.githubusercontent.com/31331515/35620804-32469238-06bd-11e8-87c3-acc86aea098b.png)
![_20180131193013](https://user-images.githubusercontent.com/31331515/35620816-3a6414ea-06bd-11e8-962d-7ed10aa1468c.png)

**Comment by zengjingke** [comment]
直接复制gm demo不报错，但就是渲染不出来

**Comment by wbpmrck** [comment]
我也是同样的问题
