### ISSUE TITLE
Avatar formation


### ISSUE THREAD

**Issue by williambao** [iview/iview#2966]
### Environment
Mac/Chrome 63.0/Vue 2.5.13

### Reproduction link
[https://jsfiddle.net/yyrzhm46/223/](https://jsfiddle.net/yyrzhm46/223/)

### Steps to reproduce
页面中的组件需要从后台api获取用户列表显示. 当有些用户无头像时, 在Avatar里显示昵称第一个字时, 不会显示在中间. 显示偏右

### What is expected?
正确显示在中间位置

### What is actually happening?
偏右

**Comment by icarusion** [comment]
not a bug
