### ISSUE TITLE
[Feature Request]Table will be silently error when data array contains null.

### ISSUE THREAD

**Issue by XXLeeS** [iview/iview#2968]
### What problem does this feature solve?
Sometimes the data we get from 3rd party api may not be clean as expected.
In my case, if the `data` props to `<Table>` component contains `null`, then the component would be silently error.
If there is some error log to tell developer where the problem is, it would be easier to debug.

### What does the proposed API look like?
Some `console.error`.

**Comment by icarusion** [comment]
you should set data to `[]`, maybe you can use `computed`.
