### ISSUE TITLE
The on-change event of [Bug Report]AutoComplete needs to be changed every two times to change once


### ISSUE THREAD

**Issue by xienh** [iview/iview#2972]
### Environment
mac / 谷歌浏览器 / vue / 

### Reproduction link
[https://www.iviewui.com/components/auto-complete](https://www.iviewui.com/components/auto-complete)

### Steps to reproduce
使用AutoComplete自动完成功能，并且打印出value的值。在改变AutoComplete的时候每隔两次value才会变一次

### What is expected?
on-change事件应该每次输入值都会变，或者失去焦点后才会变

### What is actually happening?
on-change事件每隔两次value才会变一次

**Comment by CuteDeng** [comment]
遇到同样的问题
