### ISSUE TITLE
The [Bug Report]Cascader cascaded selection component when active on-change event with search mode the selectedData is empty

### ISSUE THREAD

**Issue by belongwqz** [iview/iview#2974]
### Environment
firefox28/windows7/vue2.5.13/iview2.9.1

### Reproduction link
[https://github.com/belongwqz/data_viewer/blob/master/iview_test.html](https://github.com/belongwqz/data_viewer/blob/master/iview_test.html)

### Steps to reproduce
1、设置filterable属性和on-change事件（接受value, selectedData两个参数）
2、通过搜索（比如“王府井”）选择某一项时触发on-change事件，打印value, selectedData连个值，其中selectedData为0长度array
3、对比不通过搜索（用鼠标逐级选择）方式，打印selectedData为真实值。

### What is expected?
搜索（比如“王府井”）选择时selectedData为正确值而不是0长度的array

### What is actually happening?
搜索选择时selectedData为0长度的array

**Comment by icarusion** [comment]
验证没有问题

**Comment by belongwqz** [comment]
![gif](https://user-images.githubusercontent.com/6919651/35759963-e97df53a-08b7-11e8-9d49-677b96c906f0.gif)
不会吧，有问题的，见上图

**Comment by oushiun** [comment]
@belongwqz @icarusion 针对 filterable 选中后 selectedData 为空有什么解决办法？
