### ISSUE TITLE
[Bug Report]Table can not render customized column

### ISSUE THREAD

**Issue by wbpmrck** [iview/iview#2978]
### Environment
macos 10.11.6 /chrome  63.0.3239.132/ Vue 2.5.10

### Reproduction link
[https://jsfiddle.net/yyrzhm46/229/](https://jsfiddle.net/yyrzhm46/229/)

### Steps to reproduce
just see the demo,the column is escaped,not render properly

### What is expected?
see the button in the column

### What is actually happening?
see the escaped string

**Comment by wbpmrck** [comment]
the demo code is copy from the [iview official doc](https://iview.github.io/components/table),so i also suggest the document to update

**Comment by icarusion** [comment]
Render 用法不对

**Comment by wbpmrck** [comment]
@icarusion 官方文档就是这样写的，你说不对，倒是给出个正确用法啊？
你是来搞笑的吧，还维护开源项目？？！！

**Comment by wbpmrck** [comment]
![doc](https://user-images.githubusercontent.com/1442515/35784503-226f377c-0a53-11e8-917c-7bc3937d3d83.png)

你们文档是这么写的

**Comment by icarusion** [comment]
看清版本
