### ISSUE TITLE
[Bug Report]ColorPicker is invalid in non template/render mode


### ISSUE THREAD

**Issue by tangheng666** [iview/iview#2979]
### Environment
windows10,Chrome 

### Reproduction link
[https://jsfiddle.net/yyrzhm46/232/](https://jsfiddle.net/yyrzhm46/232/)

### Steps to reproduce
引入vuejs文件，引入iviewjs文件，js写好，再写ColorPriker组件后无效

### What is expected?
可以用，和官网一样的效果

### What is actually happening?
无效

---
就是希望可以用，现在是i-colorPirker也不行

**Comment by tangheng666** [comment]
希望得到解决

**Comment by icarusion** [comment]
仔细看 Vue 文档
