### ISSUE TITLE
在编辑器中修改了代码保存后，切换到浏览器出现如下错误，且控件无法点击！

### ISSUE THREAD

**Issue by jarvan4dev** [iview/iview#298]
![image](https://cloud.githubusercontent.com/assets/9948677/23163918/93e350c4-f86f-11e6-8a75-936d070cd5a4.png)

**Comment by jarvan4dev** [comment]
iview: 0.9.17 vue: 1.x

**Comment by icarusion** [comment]
按要求提问

**Comment by rijn** [comment]
Please refresh the page.

**Comment by jarvan4dev** [comment]
@rijn Could you tell what caused this?
