### ISSUE TITLE
When the value of the [Bug Report]Cascader component data is JSON string, the selected label is blank after the search is selected.


### ISSUE THREAD

**Issue by belongwqz** [iview/iview#2983]
### Environment
firefox58/windows7/vue2.5.13/iview2.9.1

### Reproduction link
[https://github.com/belongwqz/data_viewer/blob/master/iview_test.html](https://github.com/belongwqz/data_viewer/blob/master/iview_test.html)

### Steps to reproduce

![iview_exp1](https://user-images.githubusercontent.com/6919651/35835947-9b9fcd1c-0b18-11e8-9d3a-0f543b4382a4.gif)

1、设置data的data为json string，如[{value: '{1:2, 3:4}',label: '王府井'}]
2、搜索关键字（王府井）选中，观察Cascader组件的label
3、显示为空
4、直接点击选择，则label为正确值

### What is expected?
显示为正确的值

### What is actually happening?
空白

**Comment by icarusion** [comment]
No reproduction
