### ISSUE TITLE
poptip在table中使用时，点击一个，以前打开的不会自动 关闭

### ISSUE THREAD

**Issue by youthour** [iview/iview#299]
issue 仅用于提交 bug 或 feature 及 文档错误，其余疑问恕不作答。提问前请先阅读 https://github.com/iview/iview/issues/79 和相关文档后，考虑是否开启issue。
 -->

### 问题现象，以及你期望的结果是怎样的?
poptip在table中使用时，点击一个，以前打开的不会自动 关闭

**Comment by jsonformat** [comment]
点击显示再点击隐藏, 这样设计应该是没问题的
按照你的需求, 你可以使用hover

**Comment by qq447665722** [comment]
发现同样问题,同意楼主,在非table内使用正常的,但在内使用就会
![image](https://cloud.githubusercontent.com/assets/14967427/24742444/d98e6fde-1adc-11e7-91f5-fffa6eb2b011.png)
需要点击取消才能关闭
代码如下
![image](https://cloud.githubusercontent.com/assets/14967427/24742463/f02c6192-1adc-11e7-931e-04f154adf62e.png)

**Comment by zplus** [comment]
问题1:点击的显示的poptip位置错乱。
![image](https://cloud.githubusercontent.com/assets/3666770/24987909/13429c52-2035-11e7-92d2-56e3fbc6391e.png)
问题2:`placement='top'`这样设置会被table隐藏

**Comment by zplus** [comment]
位置错乱（使用版本2.0.0-rc.10）
![image](https://cloud.githubusercontent.com/assets/3666770/24988422/6b3451fa-2038-11e7-8b4f-10b3a3ee7df9.png)
问题2：#121 
`placement='top'`
```css
.ivu-table-body{
    position: static !important;
}
```
![image](https://cloud.githubusercontent.com/assets/3666770/24988484/d5a9d50a-2038-11e7-9c04-72cd9120e1dc.png)

**Comment by icarusion** [comment]
fixed in next version
