### ISSUE TITLE
How do I make card clickable?

### ISSUE THREAD

**Issue by rlam3** [iview/iview#2990]
How do I make card clickable?
I was wondering how to enable a card to be clickable so I can push to a different page. Thanks! 

```js
      <Card
        v-for="item,index in items"
        :key="index"
        style="width:320px"
        v-on:click="handleCard"
        >
```

handleCard is a method I handle inside methods....

**Comment by lulongwen** [comment]
you should be write like this:
 <Card
        v-for="item,index in items"
        :key="index"
        style="width:320px"
        @click.native="handleCard"
        > 

@rlam3
