### ISSUE TITLE
[Bug Report]Table components, asynchronous data and flex layout, table has been calculating the width, can't stop

### ISSUE THREAD

**Issue by jiafulu** [iview/iview#2995]
### Environment
chrome65.0/windows7

### Reproduction link
[https://jsfiddle.net/jiafu55/r7wqrvbc/](https://jsfiddle.net/jiafu55/r7wqrvbc/)

### Steps to reproduce
1.flex layout 
2.asynchronous data
3.The amount of data is less than the fixed height (discontent)

### What is expected?
Hope to solve it as soon as possible

### What is actually happening?
Online wait, not urgent

**Comment by Jame0527** [comment]
try again 

![image](https://user-images.githubusercontent.com/17266789/36008305-adb5b83e-0d81-11e8-8681-4f054e7994b9.png)

**Comment by Jame0527** [comment]
看你名字是中文  直接中文回复吧  你可以在nextTick的时候在给data赋值    应该能解决你现在的问题
this.$nextTick(() => {
    this.data = asynchronous data;
)

**Comment by icarusion** [comment]
No reproduction

**Comment by jiafulu** [comment]
jsfiddle的链接不知道你的为什么不能用，换了个codepen的链接
[https://codepen.io/jiafu/pen/PRbKOJ](url)
**不要用移动端网页和微信看，Firefox不知道有没有问题， 我只发现PC端chrome有问题**

**Comment by jiafulu** [comment]
jsfiddle的链接不知道你的为什么不能用，换了个codepen的链接
https://codepen.io/jiafu/pen/PRbKOJ
**不要用移动端网页和微信看，Firefox不知道有没有问题， 我只发现PC端chrome有问题**
![iview-table](https://user-images.githubusercontent.com/21995695/37574178-fcde6e38-2b59-11e8-8631-de19077da3a1.png)
