### ISSUE TITLE
components目录规范

### ISSUE THREAD

**Issue by jingsam** [iview/iview#3]
>组件在目录components/下，每个组件单独一个目录，目录命名使用小写，入口文件为index.js，导出组件，再由跟入口文件index.js暴露给使用者

我发现每个组件下面的index.js基本上没什么逻辑代码，所以为什么不直接用vue单文件呢？

**Comment by icarusion** [comment]
很多组件还是不一样的，你可以看下 Modal、Message、Notice等。

**Comment by jingsam** [comment]
我看了下只有Model、Message、Notice、loading bar有逻辑代码，但是你这样组织对于有些组件如Button和Button-Group看起来有逻辑一些，所以我对你的目录结构没意见
