### ISSUE TITLE
[Bug Report]Modal multiple call


### ISSUE THREAD

**Issue by de1ck** [iview/iview#3008]
### Environment
win7 vue2.x iview2.x

### Reproduction link
[https://jsfiddle.net/de1ck/rcL83c4a/](https://jsfiddle.net/de1ck/rcL83c4a/)

### Steps to reproduce
```js
	this.$Modal.confirm({
				content: '123',
				onOk() {
					//setTimeout(() => {
						this.$Modal.success({
							content: 'success'
						});
					//}, 500);
				}
			});
```
```
// https://github.com/iview/iview/blob/2.0/src/components/modal/confirm.js#L168
   setTimeout(() => {
                    this.destroy();
                }, 300);
```

### What is expected?
先destroy confirm Modal ，再触发 onOk event

### What is actually happening?
先触发onOk event 再执行destroy event

---
[iview-code](https://github.com/iview/iview/blob/2.0/src/components/modal/confirm.js#L168)
由于confirm 中使用setTimeout 300ms 导致 onOk events 中 使用的Modal 组件也被 destroy 
目前通过 setTimeout >300 ms 避免被一起销毁

**Comment by daiyanze** [comment]
的确，源码里`onOk`是在`destroy`之前执行的。我觉得先`onOk`再`destroy`应该是正确的顺序吧。
@icarusion 
```vue
            ok () {
                if (this.loading) {
                    this.buttonLoading = true;
                } else {
                    this.$children[0].visible = false;
                    this.remove();
                }
                this.onOk();
            },
            remove () {
                setTimeout(() => {
                    this.destroy();
                }, 300);
            },
```

**Comment by icarusion** [comment]
组件使用不当的问题。
提示有 $Message、$Notice，而不都是用 Modal，Modal 较重，原则上只有一次。
非要使用，使用延时。
