### ISSUE TITLE
Carousel在IE下不显示分页器的焦点样式

### ISSUE THREAD

**Issue by ChiHai-Chuck** [iview/iview#301]
### iView 版本号
1.0.0

### 操作系统/浏览器 版本号
IE11

### Vue 版本号
1.0.28

### 能够复现问题的在线示例
https://www.iviewui.com/components/carousel

### 复现步骤
直接用IE浏览器打开官方的Carousel的示例页面即可看到

### 问题现象，以及你期望的结果是怎样的?
在IE浏览器下能显示分页器的焦点样式

**Comment by GITleonine1989** [comment]
这个也可以关了 @icarusion
