### ISSUE TITLE
[Feature Request]textarea cannot set a specific height


### ISSUE THREAD

**Issue by fancyboynet** [iview/iview#3010]
### What problem does this feature solve?
解决想精确自定义textarea的尺寸

### What does the proposed API look like?
```<Input type="textarea" style="height: 100%;"></Input>```

**Comment by fancyboynet** [comment]
In fact, I need the feature to custom the native components' (```input``` and  ```textarea```) style.

**Comment by BosenY** [comment]
You can set it like this: 
```
<Input class="your-textarea" type="textarea"></Input>
<style lang="less">
.your-area{
    .ivu-input{
        height: 150px;
    }
}
</style>

```

**Comment by fancyboynet** [comment]
@BosenY 谢谢反馈，这样虽然是可以，但是个人感觉原来的组件上增加一个style属性可能是不是会对开发者更友好一些呢，万一组件内部实现改了，这种方式有可能就失效了

**Comment by icarusion** [comment]
Temporarily without this plan
