### ISSUE TITLE
How do [Feature Request] bind other events when Modal.confirm () is used?


### ISSUE THREAD

**Issue by fuxiangduan** [iview/iview#3014]
### What problem does this feature solve?
现在除了onOk, onCancel事件之外， 我想绑定keyup.enter事件，该如何操作

### What does the proposed API look like?
在Modal.confirm() 的config中加一个on属性，类型是Object, 可以on: {'keyup.enter': fun1, 'keyup.space': func2}

**Comment by daiyanze** [comment]
可以在Modal中加一个input，在input里直接监听keyup enter。如果你想操作打开的这个Modal，就把Modal对象传到keyup enter的callback里。

**Comment by icarusion** [comment]
暂无此计划。
