### ISSUE TITLE
[Bug Report]Carousel can not correctly in the Modal

### ISSUE THREAD

**Issue by LovelyIsJustice** [iview/iview#3016]
### Environment
WIN10/QQ浏览器极速模式/2.9.1

### Reproduction link
[https://jsfiddle.net/zvbppk6v/2/](https://jsfiddle.net/zvbppk6v/2/)

### Steps to reproduce
在页面A调用组件B，组件B中只有一个modal中带一个Carousel

### What is expected?
调用组件B后显示跑马灯，跑马灯正确显示

### What is actually happening?
跑马灯无法正确显示图片，但是只要改变浏览器的大小，页面立刻显示出来

**Comment by icarusion** [comment]
尝试先用 `v-if` 判断 Modal 打开来解决吧。
