### ISSUE TITLE
The [Bug Report] date component hits the icon pop-up box again after the pop-up is popped out.


### ISSUE THREAD

**Issue by yangdan8** [iview/iview#3017]
### Environment
all

### Reproduction link
[https://jsfiddle.net/eoxof3s4/](https://jsfiddle.net/eoxof3s4/)
![qq 20180208152629](https://user-images.githubusercontent.com/16515026/35960415-8388e844-0ce4-11e8-8879-ab4e17f67045.png)
![qq 20180208152643](https://user-images.githubusercontent.com/16515026/35960416-83ed9a64-0ce4-11e8-9b5a-9d83f1b63051.png)

### Steps to reproduce
第一步,点击输入框
第二步,点击输入框图标

### What is expected?
正确的弹窗位置

### What is actually happening?
位置偏移

**Comment by BosenY** [comment]
@yangdan8  因为你自己例子上写了padding

**Comment by yangdan8** [comment]
与padding无关,请按操作步骤操作一遍就知道了

**Comment by yangdan8** [comment]
新版本2.13.1已经解决了该问题
