### ISSUE TITLE
Collapse 点击同时打开

### ISSUE THREAD

**Issue by jsonformat** [iview/iview#302]
1. 第一个问题点击会同时打开我代码是这么写的:
<img width="399" alt="iview1" src="https://cloud.githubusercontent.com/assets/18202503/23202235/0f0760da-f918-11e6-91a9-52240b3c4da8.png">
<img width="370" alt="iview" src="https://cloud.githubusercontent.com/assets/18202503/23202246/1fb1bbec-f918-11e6-9e60-97f1d825d5f4.png">
效果:
<img width="573" alt="iview2" src="https://cloud.githubusercontent.com/assets/18202503/23202607/b5d7c7e6-f919-11e6-9a65-e03132275da4.png">

2.第二个问题是Modal,会点到下面的Collapse, 让它合起来了, 看的不是太清楚
<img width="1042" alt="iview4" src="https://cloud.githubusercontent.com/assets/18202503/23202354/8ca364da-f918-11e6-8ceb-2ad70a735737.png">
 是我哪里写的有问题吗?

**Comment by icarusion** [comment]
这是 Vue 基础，建议你先好好看看 Vue 文档组件部分

**Comment by jsonformat** [comment]
可以给点具体建议吗
