### ISSUE TITLE
One row of the [Bug Report]table fixed column can't roll


### ISSUE THREAD

**Issue by Jame0527** [iview/iview#3024]
### Environment
mac/chrome

### Reproduction link
[https://jsfiddle.net/yyrzhm46/](https://jsfiddle.net/yyrzhm46/)

### Steps to reproduce
table表格固定列     

### What is expected?
滚动事件应该不限于固定的列和不固定的列

### What is actually happening?
只有不固定的列可以滚动

**Comment by Jame0527** [comment]
给个反馈啊   大神@Aresn

**Comment by Jame0527** [comment]
@iview-bot

**Comment by BosenY** [comment]
你这个例子都没写，而且滚动事件就是滚动不固定的列啊。。

**Comment by Jame0527** [comment]
https://jsfiddle.net/jame_front/owns3jah/9/
可能描述有问题  但是这个问题是存在的 可以看这个例子 当鼠标放在左右两边固定列的时候是没办法滚动的 只有放在中间不固定列的时候才可以滚动
![image](https://user-images.githubusercontent.com/17266789/37068740-222cc95a-21eb-11e8-8719-04493e514ebf.png)
看源码只有body上边有滚动事件  而fixed-left fixed-right 并没有看到滚动事件  因描述不清楚带来的困扰 深感抱歉

**Comment by Jame0527** [comment]
@BosenY  可以看看例子
