### ISSUE TITLE
[Feature Request] Table should be scrolled when there is no data

### ISSUE THREAD

**Issue by alwayszb** [iview/iview#3025]
### What problem does this feature solve?
When there is no data, the table cannot be scrolled, and cannot view all the fields.

### What does the proposed API look like?
When there is no data, the table can still be scrolled and all the fields could be viewed.

**Comment by djh0405** [comment]
+1

**Comment by Acmen-Lu** [comment]
+1

**Comment by Acmen-Lu** [comment]
+1

**Comment by icarusion** [comment]
The description is not clear enough, if there is a problem, please provide online demo.

**Comment by Acmen-Lu** [comment]
11
