### ISSUE TITLE
[Bug Report]Avatar style bug, when Chinese characters changed from 2 to 1

### ISSUE THREAD

**Issue by CoderHanXin** [iview/iview#3028]
### Environment
Windows 10, Chrome  64.0.3282.140, Vue 2.5.13, iView 2.9.2

### Reproduction link
[https://jsfiddle.net/rock3/py8tb9d8/1/](https://jsfiddle.net/rock3/py8tb9d8/1/)

### Steps to reproduce
1.set 2 Chinese characters in Avatar, '张三'
2.change it to '张'
3.'张' is not in center

### What is expected?
Character in the center of Avatar

### What is actually happening?
Element style, transform and left is not changed.

**Comment by daiyanze** [comment]
刚刚提交了一个PR，应该可以解决目前的问题。
#3040

**Comment by icarusion** [comment]
#3033
