### ISSUE TITLE
The depth cloning of the [Bug Report]table component data will greatly affect the performance of the table component


### ISSUE THREAD

**Issue by kuerbb** [iview/iview#3030]
### Environment
window

### Reproduction link
[https://www.iviewui.com/components/table](https://www.iviewui.com/components/table)

### Steps to reproduce
https://www.iviewui.com/components/table

### What is expected?
https://www.iviewui.com/components/table

### What is actually happening?
https://www.iviewui.com/components/table

**Comment by daiyanze** [comment]
能否提供一个在线事例让我们研究一下
