### ISSUE TITLE
The [Bug Report]select drop-down list does not dynamically adjust the location of the drop-down according to its screen position, which is beyond the screen


### ISSUE THREAD

**Issue by hyphenhuang** [iview/iview#3032]
### Environment
win7，Chrome - 65，32位

### Reproduction link
[http://v1.iviewui.com/components/select](http://v1.iviewui.com/components/select)

### Steps to reproduce
官方的demo，自己打开看看就明白了

### What is expected?
下拉应该能够根据select的位置动态显示，比如select比较靠屏幕下方，那么下拉就显示在select的上方

### What is actually happening?
不管什么情况下拉都显示在select的下方，会被屏幕挡住，这个体验不好

**Comment by dean5277** [comment]
这个可以暂时通过render来手动检测位置以及设置placement

**Comment by daiyanze** [comment]
是v1的？

**Comment by icarusion** [comment]
已存在相同问题。
