### ISSUE TITLE
[Bug Report]Avatar delay display is not centered.

### ISSUE THREAD

**Issue by Nabufaces** [iview/iview#3033]
### Environment
Mac/Chrome

### Reproduction link
[https://jsfiddle.net/ucyLoy22/](https://jsfiddle.net/ucyLoy22/)

### Steps to reproduce
查看示例，观看4s即可发现Bug

### What is expected?
Avatar内容延迟加载后也能居中对齐

### What is actually happening?
Avatar内容延迟加载后没有居中对齐

**Comment by daiyanze** [comment]
```<Avatar />```主要是拿来展示图片的，没有单独对文字居中对齐的功能。加上`Avatar`本身大小有限，如果想要再统一行显示大量文字，会导致文字过小不可读。其实你可以给文字加个块级标签，然后布局，不过比较烦人的结果就是文字多了会变小。

举个例子：
https://jsfiddle.net/445jc0yy/

我觉得如果非要像Google那样显示某某人的姓名，最好自己做个稍微大点的圆形组件，毕竟`Avatar`的源代码也就100行。自己动手丰衣足食吧。

**Comment by daiyanze** [comment]
发现是当数据更新时对齐宽度没有同步。
刚刚提交了一个PR，希望可以尽快解决这个问题。
#3040
