### ISSUE TITLE
[Bug Report]ColorPicker. Cannot emit event on user pick color  from persets

### ISSUE THREAD

**Issue by SerhiyGuivan** [iview/iview#3041]
### Environment
"os": "Windows 10", "browser version":  "Google Chrome 64.0.3282.167",  "nuxt": "1.1.1"

### Reproduction link
[https://jsfiddle.net/yyrzhm46/259/](https://jsfiddle.net/yyrzhm46/259/)

### Steps to reproduce
Go to the link https://jsfiddle.net/yyrzhm46/259/ . Click on color-picker. Select color from colors persets.

### What is expected?
Expected emit "on-active-change" or another event

### What is actually happening?
On select color from persets, did not run any event.

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/36656077-7eeebf90-1b01-11e8-891f-17d32eece37c.png)

It looks good here.

**Comment by SerhiyGuivan** [comment]
But when I try to choose color from colors perset It doesn't run console.log

**Comment by fantkolja** [comment]
It seem quit illogical, that when I choose color in the main field 'on-active-change' fires, but if I choose color from presets no event fires at all
