### ISSUE TITLE
The checkbox components of the [Bug Report]safari browser are not the same as other browsers


### ISSUE THREAD

**Issue by QJX** [iview/iview#3042]
### Environment
win7 / safari: 5.1.7(7534.57.2) / Vue: 2.5.13

### Reproduction link
[https://www.iviewui.com/components/checkbox](https://www.iviewui.com/components/checkbox)

### Steps to reproduce
使用safari 浏览器访问https://www.iviewui.com/components/checkbox页面

### What is expected?
打钩图标与其他浏览器一致

### What is actually happening?
打钩图标与其他浏览器不一样，不美观

**Comment by daiyanze** [comment]
你试试使用normalize.css先，估计暂时能解决旧版本浏览器之间的差异。
我这里测试的chrome 64和safari 11的checkbox组件样式都是一致的。
