### ISSUE TITLE
级联选择 bug

### ISSUE THREAD

**Issue by mcmf** [iview/iview#305]
### iView 版本号
1.0.0 

### 操作系统/浏览器 版本号
windows/Chrome 54 

### Vue 版本号
1.0.26

级联选择 value 不能使用数字  初始化不能选中

**Comment by icarusion** [comment]
在线示例

**Comment by mcmf** [comment]
@icarusion 没有在线的    比如说地级三级联动   就按官方例子   

` value2: ['a','b','c'],
            data: [{
                value: 'beijing',
                label: '北京',
                children: [
                    {
                        value: '1',
                        label: '故宫'
                    },
                    {
                        value: '2',
                        label: '天坛'
                    },
                    {
                        value: '3',
                        label: '王府井'
                    }
                ]
            }, {
                value: 'a',
                label: '江苏',
                children: [
                    {
                        value: '5',
                        label: '南京',
                        children: [
                            {
                                value: '6',
                                label: '夫子庙',
                            }
                        ]
                    },
                    {
                        value: 'b',
                        label: '苏州',
                        children: [
                            {
                                value: 'c',
                                label: '拙政园',
                            },
                            {
                                value: '9',
                                label: '狮子林',
                            }
                        ]
                    }
                ],
            }]`

你看 这个 默认的value2  a,b,c 默认选择的  江苏/苏州/拙政园   如果你将 a/b/c 使用 1,2,3 这种  vulue2:[1,2,3]  默认是不会选中的

**Comment by icarusion** [comment]
不支持数字

**Comment by mcmf** [comment]
@icarusion 好多地方都是默认id  pid调用啊  为什么不支持呢   element 就支持的

**Comment by icarusion** [comment]
contribution welcome
