### ISSUE TITLE
The [Bug Report] pop-up box is not in the middle of the IE browser


### ISSUE THREAD

**Issue by h-wanli** [iview/iview#3062]
### Environment
ie11(ie9,ie10)直接报错,调试中

### Reproduction link
[https://www.baidu.com/s?wd=vue%20axios%20%E4%B8%8D%E5%85%BC%E5%AE%B9ie11&rsf=9&rsp=0&f=1&oq=vue%20%2Baxios%20%E5%85%BC%E5%AE%B9&tn=62095104_8_oem_dg&ie=utf-8&rsv_idx=1&rsv_pq=fb13d6ae00026084&rsv_t=d8e2XelLypLRqKZ%2Fa5YP2HqeWxn8JgfJPVrXzZGn1DVTsc896xeJSeA4iKkP66oDAVCG9PwBD5Q&rqlang=cn&rs_src=0](https://www.baidu.com/s?wd=vue%20axios%20%E4%B8%8D%E5%85%BC%E5%AE%B9ie11&rsf=9&rsp=0&f=1&oq=vue%20%2Baxios%20%E5%85%BC%E5%AE%B9&tn=62095104_8_oem_dg&ie=utf-8&rsv_idx=1&rsv_pq=fb13d6ae00026084&rsv_t=d8e2XelLypLRqKZ%2Fa5YP2HqeWxn8JgfJPVrXzZGn1DVTsc896xeJSeA4iKkP66oDAVCG9PwBD5Q&rqlang=cn&rs_src=0)

### Steps to reproduce
任意弹框不居中,将margin:0 auto;去掉就居中了。

### What is expected?
弹框左右居中

### What is actually happening?
弹框在页面右边。

**Comment by icarusion** [comment]
wrong link

**Comment by h-wanli** [comment]
iview admin也不支持ie浏览器.
