### ISSUE TITLE
table very poor performance

### ISSUE THREAD

**Issue by 1002237913** [iview/iview#3064]
### Environment
win10 vue2.5.13 iview2.9.2

### Reproduction link
[https://github.com/1002237913/iview-table-bug.git](https://github.com/1002237913/iview-table-bug.git)

### Steps to reproduce
1.  git clone https://github.com/1002237913/iview-table-bug.git
2.  cd iview-table-bug
3.  npm i 
4.  npm start
5.  First click the Add button in the upper left corner to add 20-30 lines
6.  Enter the data directly in the form's entry box and enter the next one

### What is expected?
When the input is complete, switch the focus to the next input box, the reaction is fast and does not focus

### What is actually happening?
Slow response, and lose input focus

---
The current data casually minor changes will cause the table all re-rendering, and tr dom will not reuse. (See the code below note)

 ```
     makeData () {
                let data = deepCopy(this.data);
                data.forEach((row, index) => {
                    row._index = index;
                    row._rowKey = rowKey  ; // Why does this rowKey need to re-generate one each time?
                });
                return data;
            }
```

**Comment by shubhang93** [comment]
Same thing is happening to me.
On input change the entire table re-renders and the input loses focus

**Comment by T-bag-A** [comment]
encounter the same issue.

**Comment by T-bag-A** [comment]
watch: {
            data: {
                handler () {
                    const oldDataLen = this.rebuildData.length;
                    this.objData = this.makeObjData();
                    this.rebuildData = this.makeDataWithSortAndFilter();
                    this.handleResize();
                    if (!oldDataLen) {
                        this.fixedHeader();
                    }
                    // here will trigger before clickCurrentRow, so use async
                    setTimeout(() => {
                        this.cloneData = deepCopy(this.data);
                    }, 0);
                },
                deep: true
            },
when data is array, can we set deep to false to stop the re-render table?

**Comment by dasnnj** [comment]
遇到同样的问题，请问您解决了吗
