### ISSUE TITLE
The [Bug Report]Cascader component uses both trigger=hover and change-on-select, and hover to any item at the last level triggers the on-change event


### ISSUE THREAD

**Issue by zjzhome** [iview/iview#3068]
### Environment
vue2.5.13

### Reproduction link
[http://runjs.cn/detail/mwptshsp](http://runjs.cn/detail/mwptshsp)

### Steps to reproduce
见Reproduction link

### What is expected?
 hover 只是展开层级而不触发 on-change，用户点击才触发 on-change

### What is actually happening?
hover 除最后一级的其他项都会 on-change

**Comment by icarusion** [comment]
不能同时使用
