### ISSUE TITLE
Cascader 级联选择 禁用后仍然可以选择内容

### ISSUE THREAD

**Issue by huiliangShen** [iview/iview#307]
iView 版本号

0.9.17

操作系统/浏览器 版本号

Win7/ chrome55

Vue 版本号

1.0.26

能够复现问题的在线示例

https://codepen.io/anon/pen/JWjwRV?editors=1111

复现步骤

直接点击禁用的级联控件，就能选择下拉内容，官网示例就可复现

问题现象，以及你期望的结果是怎样的?

不应出现下拉内容才对。 

你估计可能的原因是什么（选填）？

**Comment by rijn** [comment]
It's a bug. I will fix it. Thx
