### ISSUE TITLE
[Feature Request] hopes InputNumber can increase the amount of format function


### ISSUE THREAD

**Issue by Necroogre** [iview/iview#3081]
### What problem does this feature solve?
对于金额输入框，用户希望看到的是千分位格式化后的数值；比如输入100000会自动显示为100,000;
另外希望Inputnumber也能像Input一样支持slot

### What does the proposed API look like?
<InputNumber :moneyFormat="true"></InputNumber>

**Comment by 18334794693** [comment]
@icarusion  当我从2.7.0过渡到2.11.0的时候  首先是布局出了问题，然后金额输入框在使用总是闪动，金额无法实现格式化，还有光标位置问题（利率）
