### ISSUE TITLE
The [Bug Report]select drop-down box component in the Modal pop-up layer causes the drop-down box option to display misplacement after using the super long scroll bar


### ISSUE THREAD

**Issue by Ryson9** [iview/iview#3084]
### Environment
win10/Chrome/vue2.5.2

### Reproduction link
[http://blog.csdn.net/njueyupeng/article/details/79233468](http://blog.csdn.net/njueyupeng/article/details/79233468)

### Steps to reproduce
下拉框在Modal中使用，Modal超长则会导致下拉框选项出现错位的情况，在非Modal情况下则无此问题。

### What is expected?
正确显示

### What is actually happening?
显示错位

**Comment by icarusion** [comment]
Use `transfer` prop.

**Comment by Ryson9** [comment]
不好意思A神，我的英文不太好所以只能写中文了。
不太明白使用transfer属性指的是哪一个组件的属性 我在API文档中没有找到select组件有这一个属性。
望请解答。

**Comment by icarusion** [comment]
Read API of Select doc carefully

**Comment by Ryson9** [comment]
非常感谢， 最终发现查看的api文档为v1版本，已在v2版本中找到并解决此问题。
