### ISSUE TITLE
[Bug Report]daterange is set outside at type=datetimerange: value does not change the selected state of the selected date


### ISSUE THREAD

**Issue by angrytoro** [iview/iview#3085]
### Environment
chrome

### Reproduction link
[https://plnkr.co/edit/2wa4ZaWKOQKvxWatMX8Z?p=preview](https://plnkr.co/edit/2wa4ZaWKOQKvxWatMX8Z?p=preview)

### Steps to reproduce
初始化后，点击click me

### What is expected?
日历显示的已选日期显示正确的时间

### What is actually happening?
已选时间的颜色不会改变

**Comment by icarusion** [comment]
It has been fixed in the next release.
