### ISSUE TITLE
[Feature Request]Hope to add wrap property in textarea

### ISSUE THREAD

**Issue by Smith-Cruise** [iview/iview#3086]
### What problem does this feature solve?
I want `textarea` to support `wrap=off`.

### What does the proposed API look like?
`    <Input v-model="value10" type="textarea" wrap="off"></Input>`

**Comment by icarusion** [comment]
I find `wrap` in `<textarea>` just two value: `hard` and `soft`. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea 

> off:  Like soft but changes appearance to `white-space: pre` so line segments exceeding cols are not wrapped and area becomes horizontally scrollable.

**Comment by Smith-Cruise** [comment]
yes

**Comment by icarusion** [comment]
OK, will add `wrap` in next version.
