### ISSUE TITLE
The [Bug Report]DatePicker component on-change event will respond to three times in some cases


### ISSUE THREAD

**Issue by Ryson9** [iview/iview#3088]
### Environment
win10/chrome/vue2.5.2

### Reproduction link
[https://jsfiddle.net/rjjacrtf/](https://jsfiddle.net/rjjacrtf/)

### Steps to reproduce
时间输入框为可输入状态，选择正确的时间格式，例如：2018-03-02，此时on-change事件会进行一次响应，得到的值也为正确的2018-03-02。
然后在时间输入框中将2018-03-02随意修改为其它字符，导致出现时间格式错误，此时on-change事件会进行三次响应
第一次为1970-01-01，第二、三次为空值

### What is expected?
只响应一次on-change事件且为空值

### What is actually happening?
事件响应三次，第一次为1970-01-01，第二、三次为空值

---
组件使用代码：<date-picker type="date"  @on-change="abc" placeholder="Select date" style="width: 200px"></date-picker>

methods：
abc (s) {
          	console.log(s)
          }

**Comment by icarusion** [comment]
This issue has been fixed in the next version, so be closed.
