### ISSUE TITLE
[Bug Report]Tooltip加在A页面的图标上面，点击进入B页面，然后返回A页面气泡还在，不消失

### ISSUE THREAD

**Issue by ripeBoy** [iview/iview#3110]
### Environment
win10;chrome 64.0.3282.186;vue:2.5.13

### Reproduction link
[https://www.iviewui.com/new-issue](https://www.iviewui.com/new-issue)

### Steps to reproduce
给A页面的图标或者链接上面添加Tooltip，然后点击次图标进入B页面，再从B页面返回A页面时Tooltip不消失（使用了keep-alive缓存）

### What is expected?
从B页面返回A页面时，Tooltip消失

### What is actually happening?
从B页面返回A页面时Tooltip不消失

**Comment by ripeBoy** [comment]
Why is it closed?

**Comment by gjwfiza** [comment]
我也想知道这个问题应该怎样解决
