### ISSUE TITLE
[Bug Report]modal  confirm创建的模态框，启用closable,右上角关闭事件与点击cancel按钮事件执行结果不一致，右上角关闭，应也删除该模态框el节点，否则容易引起界面显示混乱

### ISSUE THREAD

**Issue by yaomingdan** [iview/iview#3111]
### Environment
 无

### Reproduction link
[https://说的很明白了.net/yyrzhm46/](https://说的很明白了.net/yyrzhm46/)

### Steps to reproduce
无

### What is expected?
   不同的comfirm生成的模态框内容不会混乱在一起。

### What is actually happening?
   不同的comfirm生成的模态框内容会混乱在一起。上一次生成的模态框内容，在下一次生成的模态框中可能也会显示在上面。

---
在iview/src/components/modal/confirm.js文件，第28行render函数部分，添加右上角角标点击函数，实现删除整个modal的el节点，类似你们在footer部分cancel函数实现的一样。

**Comment by xiazhe** [comment]
是的, 点右上角关闭是隐藏Modal, 点取消按钮是东DOM 中移除Modal. 

隐藏的情况下会导致想要点击展示另一个Modal 时弹出了之前隐藏的Modal
