### ISSUE TITLE
[Bug Report]Avatar component exception

### ISSUE THREAD

**Issue by myesn** [iview/iview#3123]
### Environment
win10,chrome64

### Reproduction link
[https://www.iviewui.com/components/avatar](https://www.iviewui.com/components/avatar)

### Steps to reproduce
https://www.iviewui.com/components/avatar
打开官网文档，最下面的一个示例，自动调整字符大小，点击 change 按钮 两次 后后页面卡死

### What is expected?
正常显示

### What is actually happening?
页面卡死

**Comment by zengzhongying** [comment]
这个组件确实是有bug的，你无法重现是因为没有将页面缩放比例调整到110%，这个组件出现卡死问题只有在页面缩放比例为110%的时候出现。
