### ISSUE TITLE
[Feature Request]Icon since there are so many icons why domestic BAT Icon is not included in it?


### ISSUE THREAD

**Issue by junmaqiang** [iview/iview#3138]
### What problem does this feature solve?
国内很多人需要用到分享呀, 第三方登录呀, 第三方支付呀 都需要图标支持, 其实需要还是蛮大的!

### What does the proposed API look like?
希望可以增加 支付宝, 微信, 微博, QQ, 等图标

**Comment by junmaqiang** [comment]
![333](https://user-images.githubusercontent.com/1819457/37271934-f0fdbaaa-260f-11e8-891f-40bd9b79f5a7.png)

**Comment by icarusion** [comment]
iView use http://ionicons.com/
