### ISSUE TITLE
The [Bug Report]Slider slider can not get the latest value in the on-change event processing by changing its value by clicking. It's the last value that did not change. (by dragging the bug)


### ISSUE THREAD

**Issue by Maslow** [iview/iview#3139]
### Environment
macOS 10.13 / vue 2.3.3 / chrome 64.0

### Reproduction link
[https://jsfiddle.net/yyrzhm46/399/](https://jsfiddle.net/yyrzhm46/399/)

### Steps to reproduce
访问https://jsfiddle.net/yyrzhm46/399/ ；
打开浏览器控制台；
点击滑块任意位置，改变它的值。  控制台输出的并不是最新的值。

### What is expected?
其它，点击新位置，改变新值后， 在onchange 处理器中能获取最新值。 而不是旧的值。

### What is actually happening?
实际就是获取的是旧值。

**Comment by icarusion** [comment]
```
save (data) {
      console.log(data)
}
```

**Comment by Anjie104** [comment]
如果还需要传入其他的参数怎么解决呢？
[https://jsfiddle.net/yyrzhm46/1794/](https://jsfiddle.net/yyrzhm46/1794/)
