### ISSUE TITLE
webpack打包后的iview.min.js不能给modal附加class

### ISSUE THREAD

**Issue by zhoushiya** [iview/iview#314]
使用unpkg上的iview.min.js却可以正常附加class，自己打包的不可以

**Comment by icarusion** [comment]
按要求提问

**Comment by zhoushiya** [comment]
不好意思，那请问这种情况应该怎么解决呢？我下载了最新的源码，什么都没改，直接打包，也是一样的问题

**Comment by jingsam** [comment]
提供可复现问题的代码

**Comment by zhoushiya** [comment]
没法提供啊，就是下载了这里的源码，然后webpack打包出来的iview.min.js，使用的时候，在modal加上class-name，页面里只显示modal-wrap，没有你加的class-name。

使用官方打包好的是没有问题的，但是我自己打包了几次，都是这问题，源码没有任何修改

**Comment by jingsam** [comment]
帖关键代码

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/09bce8de8399cb19fd8dc625851a6d5d61fb898e

**Comment by zhoushiya** [comment]
解决了，把wrapClasses和maskClasses交换一下位置就可以了。。。css里自己改了一下z-index。。
