### ISSUE TITLE
When the [Bug Report] route jumps back and forth, the form components will be repeatedly rendered


### ISSUE THREAD

**Issue by xiongtongzi** [iview/iview#3140]
### Environment
window 10/谷歌 65.0.3325.146/vue 2.2.6

### Reproduction link
[http://fx.51tgt.com/login](http://fx.51tgt.com/login)

### Steps to reproduce
注册成功之后，回到首页再次注册，上次注册的数据还存在。

### What is expected?
希望路由跳转的时候只渲染一次

### What is actually happening?
组件被重复渲染了

**Comment by icarusion** [comment]
Not a iView problem.
