### ISSUE TITLE
[Bug Report]vue update 2.5.15  render error

### ISSUE THREAD

**Issue by dean5277** [iview/iview#3142]
### Environment
vue2.5.15

### Reproduction link
[http://jsfiddle.net/vg50cmmw/10/](http://jsfiddle.net/vg50cmmw/10/)

### Steps to reproduce
https://jsfiddle.net/vg50cmmw/6/  // vue 2.5.13  render norml display
http://jsfiddle.net/vg50cmmw/10/ // vue 2.5.15  render display error

### What is expected?
正常返回  return value

### What is actually happening?
返回为空  return null

**Comment by icarusion** [comment]
原因不明，给 `render` 加个标签：
```js
render: (h) => {
    h('span', 1)
}
```
