### ISSUE TITLE
[Bug Report] display problem of radio in render function


### ISSUE THREAD

**Issue by stmory** [iview/iview#3143]
### Environment
google浏览器版本 65.0.3325.146（正式版本） （32 位）

### Reproduction link
[https://stmory.github.io/html/index.html](https://stmory.github.io/html/index.html)

### Steps to reproduce
radio点击onchange事件触发但是没有改变样式

### What is expected?
点击radio有变化

### What is actually happening?
点击radio没有变化

---
可能是radiogroup中的updateValue方法中的‘child.currentValue = this.value === child.label’这句的问题？
其中的this.value是否应该为this.currentValue ?谢谢

**Comment by icarusion** [comment]
```
data () {
    return {
        phone: {
            aa: 'apple'
        },
    }
}
```

**Comment by stmory** [comment]
如果我的phone里的数据是后来加载的呢？

**Comment by reef007** [comment]
我遇到了同样的问题，首先是在一个radiogroup组里，点击radio能相应change事件，但是样式没有改变，手动改变v-model的值结果依旧没有变化，附上默认值以后就没有问题了，假如我不想有默认值该怎么做呢
