### ISSUE TITLE
[Bug Report]DatePicker components use daterange type for data bi-directional binding to display exceptions


### ISSUE THREAD

**Issue by Ryson9** [iview/iview#3155]
### Environment
win10/chrome/Vue 2.5.14

### Reproduction link
[https://jsfiddle.net/xeLwumdm/](https://jsfiddle.net/xeLwumdm/)

### Steps to reproduce
使用DatePicker组件daterange类型 需要给组件对应的赋值 每次如果不将绑定的v-model变量重置为空数组则DatePicker组件无法显示v-model绑定上的最新值。

### What is expected?
给v-model数组变量赋值后DatePicker组件对应显示最新数据对应的日期

### What is actually happening?
如果不将v-model数组重置为空则无法对应显示最新数据对应的日期

**Comment by icarusion** [comment]
Vue.js 不能通过索引赋值，否则无法双向绑定，看Vue文档。

**Comment by Ryson9** [comment]
非常感谢大神的指点。
