### ISSUE TITLE
[Bug Report]date-picker(daterange),press button to change year,and the performance is confused.

### ISSUE THREAD

**Issue by photon-phalanx** [iview/iview#3158]
### Environment
win8/ chrome 64.0.3282.186/vue 2.5.2

### Reproduction link
[https://jsfiddle.net/yyrzhm46/430/](https://jsfiddle.net/yyrzhm46/430/)

### Steps to reproduce
e.g. today is 2018.3
select date-picker component (type="daterange")
now it shows like 2018.3  2018.4
Press the next-year button 

### What is expected?
shows like 2019.3 2019.4

### What is actually happening?
2018.3 2019.4

---
the date range always shows one year and a month，and there is no any way to change back，even if press next-month button,the date range still has one year and a month.it is so confused.

**Comment by photon-phalanx** [comment]
I know there is a new property (split-panels) can prevent this problem and it works well.but this default performance maybe can do better.

**Comment by icarusion** [comment]
thanks, i think this is bug.
