### ISSUE TITLE
请教 table rander数据 exportCsv 不行吗 

### ISSUE THREAD

**Issue by mcmf** [iview/iview#316]
如题

**Comment by GITleonine1989** [comment]
请看文档
![image](https://cloud.githubusercontent.com/assets/7582490/23394133/63392c8e-fdc2-11e6-8d42-8e5ac42ab4a4.png)

**Comment by jsOcean** [comment]
@GITleonine1989 代码怎么写，有示例可以参考吗 
![K`_~U673K5}6K@8TG96E7$Y](https://user-images.githubusercontent.com/40814604/60853291-f9d19200-a22d-11e9-90aa-1a145cb8351a.png)
怎么取出里面的name
![image](https://user-images.githubusercontent.com/40814604/60853388-719fbc80-a22e-11e9-875f-38b404242214.png)
这个是我写的代码
