### ISSUE TITLE
[Bug Report]checkbox is conflicting with the input box, and the console is wrong


### ISSUE THREAD

**Issue by Kunkka0229** [iview/iview#3160]
### Environment
mac/chrome/vue2.5.15

### Reproduction link
[https://jsfiddle.net/yyrzhm46/435/](https://jsfiddle.net/yyrzhm46/435/)

### Steps to reproduce
先点击checkbox框，再点击选择时间，控制台报 Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

### What is expected?
期望没有报错

### What is actually happening?
Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

**Comment by icarusion** [comment]
Can't reproduce

**Comment by Kunkka0229** [comment]
https://jsfiddle.net/yyrzhm46/435/       jsfiddle代码也报错
![image](https://user-images.githubusercontent.com/18555531/37500018-0bbe51d4-2902-11e8-9217-723ebb976278.png)

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/37500080-68bf4924-2902-11e8-9384-35002eab2962.png)

**Comment by Kunkka0229** [comment]
抱歉，很奇怪可能是我chrome原因，谢谢
