### ISSUE TITLE
[Feature Request] drag and drop the zoom rotation component


### ISSUE THREAD

**Issue by yippeesoft** [iview/iview#3166]
### What problem does this feature solve?
类似流程图绘制场景。用户可拖拽菱形方形等并可以缩放连接

### What does the proposed API look like?
类似 https://github.com/tigerlove/vue-drag-resize-rotate
而不是类似 Vue.Draggable 只有拖拽排序等。谢谢。

**Comment by icarusion** [comment]
无此计划。
