### ISSUE TITLE
[Bug Report]Select if assigned: key is an error value


### ISSUE THREAD

**Issue by chrisHLY** [iview/iview#3168]
### Environment
Windows7 vue2.0

### Reproduction link
[https://jsfiddle.net/jw4aysk0/12/](https://jsfiddle.net/jw4aysk0/12/)

### Steps to reproduce
第一步点击按钮 Canberra；第二步点击按钮Canberra33；select框中会显示点击按钮Canberra赋值情况，并不会清空执行v-model。

### What is expected?
如果 传了一个错误的值给select中v-model，希望它显示‘请选择’，而不是保留上一次的赋值。

### What is actually happening?
select框中会显示点击按钮Canberra赋值情况，并不会清空执行v-model。

---
比如我之前存储的:key有问题，然后我先拿正确的:key去赋值，然后在拿错误的:key去赋值，这会显示第一次正确赋值的结果，我希望能出现回调函数告诉我这是个错误的:key。

**Comment by icarusion** [comment]
Not a bug.
