### ISSUE TITLE
[Bug Report] is quoted on demand, is wrong on IE and displays blank pages


### ISSUE THREAD

**Issue by QJX** [iview/iview#3169]
### Environment
win7 / ie:all / vue:2.5.16

### Reproduction link
[https://www.iviewui.com/docs/guide/start#%E6%8C%89%E9%9C%80%E5%BC%95%E7%94%A8](https://www.iviewui.com/docs/guide/start#%E6%8C%89%E9%9C%80%E5%BC%95%E7%94%A8)

### Steps to reproduce
按官网的步骤改成按需引用后，chrome、firefox正常，ie报错显示空白页(原先未非按需引用，正常)
报错：Uncaught SyntaxError: Unexpected strict mode reserved word 
用了Modal组件

### What is expected?
IE也能正常

### What is actually happening?
IE报错显示空白页

**Comment by icarusion** [comment]
Not support IE in the future

**Comment by BoleLee** [comment]
+1!!!!!
iview按需引入在安卓4.4.4 webview环境下报错：Uncaught SyntaxError: Use of const in strict mode.
暂时没有找到解决方案，修改为全局引入则正常
问题详细描述：https://segmentfault.com/q/1010000016986305
