### ISSUE TITLE
关于 iView 2.0

### ISSUE THREAD

**Issue by icarusion** [iview/iview#317]
## 即日起 iView 在分支 2.0 下进行对 Vue 2.x 的支持，暂停对 iView 1.x 的更新及 pr 合并，请先不要提交 pr。

**Comment by waney** [comment]
等得急,估计什么时候可以用上第一版

**Comment by lzyscript** [comment]
期待已久

**Comment by waney** [comment]
项目(vue 2)已经开始又想用iview该怎么办.

**Comment by huixisheng** [comment]
@waney  项目急的话可以先用 https://github.com/huixisheng/iview/tree/feature-2.0 做个过度，基本组件已经支持。另外作者已经着手支持Vue2.x

**Comment by xland** [comment]
计划是怎么样的啊？什么时候能完成这项工作？项目可以等一等，但估计等不了太久~
另外这个项目搞的真不错；公司选型打算用，不知道会不会持续维护下去！

**Comment by icarusion** [comment]
Just pay attention to the README.md of branch 2.0

**Comment by xland** [comment]
The README.md of branch 2.0  doesn't  contains the developing plan.....
Please work out a plan, have a heart.
Thank you!

**Comment by waney** [comment]
Waiting for you! @icarusion

**Comment by icarusion** [comment]
@xland [Programming](https://github.com/iview/iview/tree/2.0#programming) contains all components status

**Comment by xland** [comment]
@icarusion 

Haven't done anything yet?~~

 I  see. Thank you!

**Comment by xland** [comment]
更新速度好快，照这个速度，用不了多久就搞定迁移的事情啦

**Comment by Jesn** [comment]
等待2.0

**Comment by Astlvk** [comment]
期待2.0，莫名更喜欢ivew

**Comment by JackZimmer** [comment]
iView is wonderful.I have been adding new components to iView.I hope to share them when the time is right.

**Comment by lifetea** [comment]
@icarusion  2.0能否先放到npm上面。。。

**Comment by icarusion** [comment]
@lifetea 组件完成后放

**Comment by icarusion** [comment]
@JackZimmer welcome

**Comment by waney** [comment]
@lifetea 你可以下载源文件拷贝到\node_modules运行 npm run dev 用啊。

**Comment by waney** [comment]
@lifetea 你可以下载源文件拷贝到\node_modules运行 npm run dist 用啊。

**Comment by xland** [comment]
每天都来看一下这个项目，数了一下，还有11个组件没完成，应该都是比较难搞得了；
加油！

**Comment by liniu** [comment]
非常棒，期待2.0

**Comment by wang22** [comment]
6.0 666

**Comment by Lurkerc** [comment]
加油，2.0出来一定请你喝咖啡。
期待ing

**Comment by 285858315** [comment]
新版有支持 antd mobile 的计划么？

**Comment by hexiaoyun128** [comment]
期待2.0

**Comment by Leega0** [comment]
looking forward to

**Comment by dingyiming** [comment]
https://github.com/iview/iview/projects/2
![t t1k9r 0 k bbhzp 5 248](https://cloud.githubusercontent.com/assets/12537013/23733733/82fce692-04b5-11e7-92fc-82ee63904fea.png)

看样子快好了

**Comment by icarusion** [comment]
@dingyiming 恩，快乐，顺利的话这星期争取搞完

**Comment by corelone** [comment]
ding @icarusion

**Comment by marslabtron** [comment]
@icarusion 希望这周能发布2.0

**Comment by Zhengbledore** [comment]
@icarusion 已报名, 坐等你开讲座

**Comment by yunfengsay** [comment]
希望这周发布, 真是好看

**Comment by icarusion** [comment]
iView 已完成对 Vue.js 2.x 的支持，明天会 release 2.0.0-rc.1

**Comment by xland** [comment]
@icarusion 

iview-cli的2.0选项是否可以先放出来；这样用起来就更方便了

**Comment by icarusion** [comment]
@xland 下周会支持

**Comment by yunfengsay** [comment]
![image](https://cloud.githubusercontent.com/assets/15527378/23784650/368f6e44-059e-11e7-8650-0742fab8176a.png)

在使用slider的时候触发的

还有Input输入框 得不到输入的值
![image](https://cloud.githubusercontent.com/assets/15527378/23784720/8474fb06-059e-11e7-830a-02caf4fb1ecb.png)

**Comment by icarusion** [comment]
@yunfengsay 单独提issues
