### ISSUE TITLE
select 多选错位

### ISSUE THREAD

**Issue by suconghou** [iview/iview#318]
iview  0.9.17

select 多选小对号问题

chrome 下显示正常, firefox 下显示错位

均是最新版本浏览器,iview官方示例也是错位,望尽快修复.

![QQ20170228-161745@2x.png](https://ooo.0o0.ooo/2017/02/28/58b5359e87c2e.png)

![QQ20170228-161706@2x.png](https://ooo.0o0.ooo/2017/02/28/58b5359e8c301.png)

**Comment by icarusion** [comment]
fixed
