### ISSUE TITLE
[Bug Report]分页组件page，current属性绑定了变量，但改变变量的值时，界面不会化。

### ISSUE THREAD

**Issue by jjwangel** [iview/iview#3180]
### Environment
win10，360浏览器，vue2.x

### Reproduction link
[https://jsfiddle.net/jjwangel/yyrzhm46/479/](https://jsfiddle.net/jjwangel/yyrzhm46/479/)

### Steps to reproduce
分页组件page，current属性绑定了变量，但改变变量的值时，界面不会化。

### What is expected?
改变绑定的变量，界面自动更新到对应页码

### What is actually happening?
改变绑定的变量，界面没变化

**Comment by ttivan** [comment]
还是有这个问题啊

**Comment by Suzichen** [comment]
你好，我也遇到了这个问题。请问你是怎么解决的？
