### ISSUE TITLE
[Bug Report]date-picker  - clearable flag doesn't work

### ISSUE THREAD

**Issue by czytelny** [iview/iview#3182]
### Environment
Windows, Vue 2.11.0, most recent Chrome

### Reproduction link
[https://jsfiddle.net/8wboun9s/](https://jsfiddle.net/8wboun9s/)

### Steps to reproduce
clearable flag seems to doesn't work at all 

### What is expected?
when i set :clearable="false" i expect not to see 'clear' button in datepicker

### What is actually happening?
when i set :clearable="false" I'm seeing 'clear' button

**Comment by icarusion** [comment]
When you set it to `false`, it means you do not want to use clear func, so you should set `:clearable="true"` or don't set it, the default value of `clearable` is true.

**Comment by czytelny** [comment]
I set `:clearable="false"` because I don't want to use clear function, so I don't want to see "Clear" button when I expand datepicker. It doesn't work as supposed in my opinion.

**Comment by ruan11223344** [comment]
的确是真的不起作用

**Comment by JustZzzxf** [comment]
it dosen't work actually. The option only hide the clear icon in the input box, while dosen't hide the clear button in the expand drop area.

**Comment by fengjiahao** [comment]
use CSS, that button `display: none;`

**Comment by shengyan4** [comment]
> use CSS, that button `display: none;`

it`s not usefull

**Comment by shengyan4** [comment]
> I set `:clearable="false"` because I don't want to use clear function, so I don't want to see "Clear" button when I expand datepicker. It doesn't work as supposed in my opinion.

how to solve the problem

**Comment by fengjiahao** [comment]
`.ivu-picker-confirm .ivu-btn-default {
    display: none !important;
}`

**Comment by shengyan4** [comment]
> `.ivu-picker-confirm .ivu-btn-default { display: none !important; }`

thank you very much. i have been used this methed and it`s useful .  but it will change all date-picker`style not just some one child-component

**Comment by fengjiahao** [comment]
pay attention to global styles:
`.your-class-name .ivu-picker-confirm .ivu-btn-default { display: none !important; }`
