### ISSUE TITLE
[Bug Report]tabs组件使用v-if指令控制tab-pane显示隐藏问题

### ISSUE THREAD

**Issue by stmory** [iview/iview#3184]
### Reproduction link
[https://jsfiddle.net/stmory/4hhkrsa7/6/](https://jsfiddle.net/stmory/4hhkrsa7/6/)

### Steps to reproduce
有4个标签，当点击按钮控制标签显示隐藏多次时出现标签和内容页面出错的问题

### What is expected?
标签和内容页应该对应

### What is actually happening?
标签和内容匹配有误

**Comment by icarusion** [comment]
给 `Tabs` 设置正确的 value。

**Comment by AricZhu** [comment]
同问，也遇到这个问题了。（Tabs的value设置没问题啊）
