### ISSUE TITLE
The toggleCollapse method of [Feature Request]Layout Sider is recommended to be removed


### ISSUE THREAD

**Issue by wschat** [iview/iview#3186]
### What problem does this feature solve?
既然“侧边栏是否收起，可使用 v-model 双向绑定数据” 那么 我们只需改变 该值的 状态就应该可实现 侧边栏是否收起展开效果，而现在显然是不可以的，如果可以那么toggleCollapse方法的设计是否有点多余

### What does the proposed API look like?
尽量简洁，面向状态 。应该减少使用 $refs 等 操作

**Comment by icarusion** [comment]
@lison16 Please check if u have time.

**Comment by lison16** [comment]
@icarusion ok, let have a look
