### ISSUE TITLE
The [Bug Report]table component column render function can not be rendered if it returns a string directly


### ISSUE THREAD

**Issue by Hishengs** [iview/iview#3199]
### Environment
vue^2.5.14 vue-template-compiler^2.5.14 chrome@64.0.3282.186 node@8.2.1 win7 iview^2.11.0 webpack^3.8.1

### Reproduction link
[https://github.com/Hishengs/iview-bug-report](https://github.com/Hishengs/iview-bug-report)

### Steps to reproduce
1. clone repo
2. npm install & npm run dev

aim file：https://github.com/Hishengs/iview-bug-report/blob/master/App.vue

### What is expected?
can render primitive values

### What is actually happening?
can not render

---
I guessis  vue@2.5.14 's changs for functional component cause，but I can not reappear

**Comment by iamzhangjinpeng** [comment]
I met the same problem.

**Comment by icarusion** [comment]
have to set a node after using Vue.js 2.5.14

**Comment by Hishengs** [comment]
@icarusion is it vue's bug or just intended, can not return primitive values in the new version(^2.5.14)? is that means I have to change all the places I return primitive values in the table column render function if I use vue^2.5.14? thx

**Comment by Hishengs** [comment]
@icarusion is it vue's bug or just intended, can not return primitive values in the new version(^2.5.14)? is that means I have to change all the places I return primitive values in the table column render function if I use vue^2.5.14? thx

**Comment by icarusion** [comment]
The correct way to use the `render` function is to use `h`.

**Comment by Hishengs** [comment]
@icarusion I know that's the correct way, but your answer is not for my question. Sometimes in the render function u just got a computed result which is primitive value, and u just want a text node. If u are not clear if primitive value is not supported any more after vue^2.5.14, just admit it. that will also be helpful.

**Comment by icarusion** [comment]
@Hishengs Maybe you can find something here https://github.com/vuejs/vue/issues/7282
