### ISSUE TITLE
[Bug Report] can't click on the scrollbar of the time selector under IE11


### ISSUE THREAD

**Issue by sayhei** [iview/iview#3203]
### Environment
windows/ie11

### Reproduction link
[https://www.iviewui.com/components/time-picker](https://www.iviewui.com/components/time-picker)

### Steps to reproduce
官网demo就一直有这个问题

### What is expected?
拖动条可以像在chrom上那样可拖动

### What is actually happening?
点击了拖动条选项都消失了

---
这个问题一直存在啊，貌似没人关心啊，现在官网demo依然存在同样问题

**Comment by icarusion** [comment]
Please update to the latest version. If there is any problem, please  a new issue.
