### ISSUE TITLE
[Feature Request]Missing npm installation instructions

### ISSUE THREAD

**Issue by ricky11** [iview/iview#3204]
### What problem does this feature solve?
https://www.iviewui.com/docs/guide/install-en#npm

The docuentation fails to mention the furthur npm installation instructions, instead the page is blank.

### What does the proposed API look like?
Continue to explain the npm installation instruction and how to import the module into vue.

**Comment by icarusion** [comment]
I think you are finding this page https://www.iviewui.com/docs/guide/start-en
