### ISSUE TITLE
[Bug Report]DatePicker sets the start time for second times to update.


### ISSUE THREAD

**Issue by tfwoaini1234** [iview/iview#3220]
### Environment
最新

### Reproduction link
[http://www.meiyou.com](http://www.meiyou.com)

### Steps to reproduce
动态切换绑定的date信息。动态切换后需要第二次点开选择器才会更新起始时间。

### What is expected?
每次更改绑定值，第一次点开就能更新。

### What is actually happening?
每次更改绑定值，第二次点开才能更新。

---
给用户每个服务续费。到期时间不一样。需要动态切换起始时间。但是每次都要第二次点击才会更新。

**Comment by sayhei** [comment]
这个问题还没有解答么

**Comment by gezhigang1005** [comment]
@tfwoaini1234 遇到相同的问题，start-date属性只有的直接写死的情况下有用，使用变量就不行，你的问题解决了么？
