### ISSUE TITLE
[Bug Report]Bug with range datepicker

### ISSUE THREAD

**Issue by Loruz** [iview/iview#3221]
### Environment
Microsoft windows, Firefox, Chrome browsers

### Reproduction link
[https://www.iviewui.com/components/date-picker-en](https://www.iviewui.com/components/date-picker-en)

### Steps to reproduce
Bug appear also in  iview.com components demo site on a range datepicker. Datepicker dates has offset of couple of days when selecting, if Timezone on a computer is from North america. I used (Pacific, Canada - UTC) Strange enough I could reproduce an error on Microsoft windows  enviroment. (I dont know if its linked) but on Mac OS there is no bug no matter what locale or timzone I choose.

### What is expected?
Select dates normally

### What is actually happening?
Datepicker range has offset , and can't event select some of dates, it automatically jumps to different date. (For example i picked March 1st. and datepicker selected February 28.

**Comment by Loruz** [comment]
Sorry for asking, but what  status is  of resolving this bug ? And did you guys manage to reproduce it ?

**Comment by SergioCrisostomo** [comment]
@Loruz didn't have time yet to check it out sorry. Should be checking it tomorrow probably.

**Comment by wangzhiwei3919** [comment]
Mac OS changed  time zero。same trouble。choice 2018-05-21 return 2018-05-20 on date-picker.

**Comment by Steffan-Carlos** [comment]
+1
