### ISSUE TITLE
[Feature Request]InputNumber support updating model on keyup

### ISSUE THREAD

**Issue by ejfrancis** [iview/iview#3222]
### What problem does this feature solve?
When a user types a number via their keyboard into InputNumber, it would be great if the model value could be updated immediately instead of requiring the user to hit the enter button or click outside the input. Sometimes the user might be confused if they type "5" into the input and the UI doesn't reflect that change immediately.

This could be done either by a property with enables updating the model on keyup/keydown automatically (something like `:update-on-keyup='true'`), or by providing a on-keyup and on-keydown event listener so that the person writing the code could handle the change event themselves (something like `@on-keyup='handler'`).

### What does the proposed API look like?
one of the following

```
<InputNumber :update-on-keyup='true'/>
```
```
<InputNumber @on-keyup='handleValueChange' />
```

**Comment by SergioCrisostomo** [comment]
Hi @ejfrancis!
Not sure if I understand correct. Seems to me that the model is already updating on keyboard input: https://jsfiddle.net/L55tdoj7/1/

Let me know if I understand wrong or if the jsFiddle does not reflect your use case.

**Comment by ejfrancis** [comment]
hey @SergioCrisostomo, I realized that I wasn't on the newest version of the library. i updated and it's fixed so I'll happily close
