### ISSUE TITLE
Components such as [Feature Request]Poptip can dynamically change the values of the placement


### ISSUE THREAD

**Issue by alex374** [iview/iview#3223]
### What problem does this feature solve?
长列表元素滚动到不同位置, 希望Poptip弹出的位置不同, 避免元素在窗口顶部和底部时显示不全. 目前的情况是第一次显示在什么位置, 改变placement后依然会显示在第一次显示时的位置.
(Poptip等含placement属性的组件, 在改变placement的值后, 再次打开时, 显示位置变为新的placement值.)

### What does the proposed API look like?
保持不变

**Comment by icarusion** [comment]
Supported in the next version already.

**Comment by alex374** [comment]
Thank you for your support.
