### ISSUE TITLE
Page组件的size位置偏移

### ISSUE THREAD

**Issue by dengyakui** [iview/iview#323]
### iView 版本号
1.0.1

### 操作系统/浏览器 版本号
Chrome 54

### Vue 版本号
1.0.26

初步判断是由于position:fixed导致的，把它勾掉之后，位置就正常了，但是下次再点击还会那样

![image](https://cloud.githubusercontent.com/assets/3945919/23445228/e84eb350-fe74-11e6-9396-e1a40975323d.png)

**Comment by rijn** [comment]
@dengyakui Do you still have this problem now?

**Comment by icarusion** [comment]
Update the latest version
