### ISSUE TITLE
[Bug Report]open-names  problem

### ISSUE THREAD

**Issue by wQueryLoveMm** [iview/iview#3238]
### Environment
mac 版本 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[https://jsfiddle.net/d5k4fzey/9/](https://jsfiddle.net/d5k4fzey/9/)

### Steps to reproduce
首先初始化 num 的值为一个数组，设置属性accordion， 当我点击submenu的时候我希望，num的值是展开的submenu name 的集合，但是结果看有重复的name， 粗略看了下源码 menu.vue 84 行
```javascript

this.openNames.push(name);
  if (this.accordion) {
    let currentSubmenu = {};
    findComponentsDownward(this, 'Submenu').forEach(item => {
      if (item.name === name) currentSubmenu = item;
    });
    findBrothersComponents(currentSubmenu, 'Submenu').forEach(item => {
      let index = this.openNames.indexOf(item.name);
      this.openNames.splice(index, index >= 0 ? 1 : 0);
    });
    this.openNames.push(name);
  }

```
是不是最后一步多push了一下name，我注销掉就能得到我要的结果， 我想问问是不是我理解错了，还是这样设计有别的目的。

### What is expected?
我希望， accordion 模式下，我点击 name 1 的时候 open-names 数组里面只有 1 这个name， 点击2 的时候只有 2，

### What is actually happening?
实际结果是有重复的元素

**Comment by icarusion** [comment]
#3298
