### ISSUE TITLE
[Bug Report]Select component dynamic binding Options

### ISSUE THREAD

**Issue by miomio-xiao** [iview/iview#3241]
### Environment
win10 / chrome 64 / vue 2.5.11 / iView 2.11.0

### Reproduction link
[https://codepen.io/miomio-xiao/pen/QmqBQB](https://codepen.io/miomio-xiao/pen/QmqBQB)

### Steps to reproduce
异步获取options内容，然后覆盖默认值
```js
var App = new Vue({
  template: `
    <i-select v-model="data">
      <i-option v-for="{ name, value } of options"
                :key="value"
                :label="name"
                :value="value">
      </i-option>
    </i-select>
  `,
  data() {
    return {
      data: 0,
      options: [
        {
          name: 'label 1',
          value: 0
        },
        {
          name: 'label 2',
          value: 1
        },
        {
          name: 'label 3',
          value: 2
        }
      ]
    };
  },
  mounted() {
    setTimeout(() => {
      this.options = [
        {
          name: 'new label1',
          value: 0
        },
        {
          name: 'new label2',
          value: 1
        },
        {
          name: 'new label3',
          value: 2
        }
      ];
    }, 1000);
  }
});
App.$mount('#app');
```

### What is expected?
select组件的options更新

### What is actually happening?
select组件下的options还是原来的，但是option组件已经变成新的内容了

---
定位的时候发现，大致可能是这个原因。
1. Select组件先是初始化了一次options
2. Select监听子组件的append跟remove（select.vue :692），而Option组件分别是在mounted跟beforeDestroy内dispatch的事件（option.vue :80）。v-for是需要绑定一个key，这个时候因为Option里面绑定的value值也就是key是相同的，复用后不会重新去生成一个Option，所以不触发mounted钩子，而是会触发updated，导致Select里面的options不会更新。

it is probably the reason.
1. The Select component first initializes the options 
2. The Select listens for the append and remove of the subcomponent, and the Option components dispatch events within the mounted and beforedestroy. v-for is required to bind a key, this time because the bind value in the Option inside the key is the same, multiplexing will not re-generate an Option, so does not trigger the mounted hook, but will trigger the updated,
Causes the options in the Select to not be updated.

**Comment by icarusion** [comment]
The problem is `key`, you should set `:key="name"`
