### ISSUE TITLE
[Feature Request]Select, Dropdown, DatePicker, and other floating layer placement attributes automatically adapt to the screen


### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview#3257]
### What problem does this feature solve?
我在使用栅格系统进行响应式布局时，由于placement属性需要提前指定。而当页面尺寸触发响应式变化时，placement属性没有发生改变，造成浮层溢出

### What does the proposed API look like?
所有placement属性添加自动适应

**Comment by gitzhangfugui** [comment]
这个属性对我布局非常重要，希望能够进行添加，谢谢

**Comment by icarusion** [comment]
Supported in the next version already.

**Comment by gitzhangfugui** [comment]
@icarusion Thank you
