### ISSUE TITLE
[Feature Request] wants modal components to be rendered in a render way and to synchronize API with normal rendering


### ISSUE THREAD

**Issue by duanliang920** [iview/iview#3268]
### What problem does this feature solve?
现在modal的render方式不支持隐藏头部/尾部模块吗？在做后台产品面对一些复杂的情况：希望提供一个base的弹层组件出来，弹层的内容有开发者完全自定义。

### What does the proposed API look like?
在render的配置项通过属性来配置是否显示隐藏：head/footer/all

**Comment by icarusion** [comment]
无此计划。
