### ISSUE TITLE
[Bug Report]DatePicker change the type of datepick between date month and week show or not,  has bug 

### ISSUE THREAD

**Issue by buildJava** [iview/iview#3277]
### Environment
macos / chrome 64.0 / Vue and iview the lastest version

### Reproduction link
[https://jsfiddle.net/yyrzhm46/554/](https://jsfiddle.net/yyrzhm46/554/)

### Steps to reproduce
click the day,week, month, see the datepicker,then  click month, week, day, show what happend, please help me solve the problem, thank you very much

### What is expected?
when we change the type or show-week-numbers attr show the correct datepicker

### What is actually happening?
null

**Comment by bitqiang** [comment]
![image](https://user-images.githubusercontent.com/13163400/38225081-c16c4672-3725-11e8-9900-11f0c29518e6.png)
![image](https://user-images.githubusercontent.com/13163400/38225089-c7f82038-3725-11e8-83df-814edf26d22d.png)
![image](https://user-images.githubusercontent.com/13163400/38225096-d0c9aae2-3725-11e8-94dd-9248d87e193c.png)
Isn't the three picture normal?
In turn, date, week, month
