### ISSUE TITLE
LoadingBar 加载进度条

### ISSUE THREAD

**Issue by StonyShi** [iview/iview#328]
### 复现步骤
使用代码 methods 内：
mockEventData (){
                this.$Loading.start();
                this.$http.post('/user/events').then(function(response){
                    this.$Loading.finish();
                    this.fcEvents = response.body;
                }, function(){
                    this.$Loading.error();
                    this.fcEvents = [];
                });
            }
### 问题现象，以及你期望的结果是怎样的?
Uncaught TypeError: Cannot read property 'appendChild' of null
    at Object.a.default.newInstance (iview.min.js:3)
    at s (iview.min.js:3)
    at o (iview.min.js:3)
    at Object.start (iview.min.js:3)
    at Di.mockEventData (profile:53)
    at Di.mockEventData (vue.min.js:6)
    at Di.data (profile:41)
    at vue.min.js:7
    at Di.t._initData (vue.min.js:6)
    at Di.t._initState (vue.min.js:6)
a.default.newInstance @ iview.min.js:3
s @ iview.min.js:3
o @ iview.min.js:3
start @ iview.min.js:3
mockEventData @ profile:53
(anonymous) @ vue.min.js:6
data @ profile:41
(anonymous) @ vue.min.js:7
t._initData @ vue.min.js:6
t._initState @ vue.min.js:6
Ht.t._init @ vue.min.js:6
Di @ vue.min.js:7
(anonymous) @ profile:31

**Comment by huixisheng** [comment]
建议建个在线的demo。比如 https://jsfiddle.net/ ，http://codepen.io/ 方便定位问题
