### ISSUE TITLE
[Feature Request]the Tree component checked has save as to set 'show-checkbox' props  while use render method to create Checkbox 

### ISSUE THREAD

**Issue by guihuxiansheng** [iview/iview#3282]
### What problem does this feature solve?
when i holp to render Checkbox component to completed my demand，but when i set the children node checked true，the node's parents will be true，but i want to set for my data.

### What does the proposed API look like?
i holp the checkbox should be set as my data set

**Comment by guihuxiansheng** [comment]
我的意思是我的选择框的功能和Tree组件有出入，所以想自己通过render方法去重写node节点，但是当我按照自己的要求去重写的时候，checkbox组件的选中状态和设置show-checkbox属性时的一样，选中子节点父节点也会选中，父节点选中时子节点选中，但是我希望的是checkbox的选中状态完全由自己控制，而不是受到show-checkbox的影响，show-checkbox我是没有设置的

**Comment by guihuxiansheng** [comment]
原有的属性设置里面的方法影响到用户自己设置的render是不是不太好？

**Comment by icarusion** [comment]
无此计划。
