### ISSUE TITLE
[Bug Report]Tree component doesn't work under IE browser via CDN install

### ISSUE THREAD

**Issue by ngxiaoyi** [iview/iview#3283]
### Environment
win10, IE, Vue2.5

### Reproduction link
[https://jsfiddle.net/uc8vb01c/1/](https://jsfiddle.net/uc8vb01c/1/)

### Steps to reproduce
IE打开重现链接即可重现

### What is expected?
正常展示tree组件，和其余浏览器

### What is actually happening?
控制台报错且不显示页面结构

**Comment by icarusion** [comment]
Not an iView bug.
