### ISSUE TITLE
[Bug Report]Tree component sets the selected and unchecked state chaos through the node.checked

### ISSUE THREAD

**Issue by luhuaxin** [iview/iview#3289]
### Environment
w10     chrome - 66.0.3355.4    vue- 5.7.1  

### Reproduction link
[https://jsfiddle.net/luhuaxin/7mjq8gwm/2/](https://jsfiddle.net/luhuaxin/7mjq8gwm/2/)

### Steps to reproduce
multiple click  'parent 1-2'

### What is expected?
'parent 1-2' is checked 

### What is actually happening?
'parent 1-2' is unchecked

**Comment by luhuaxin** [comment]
i found that set the 'checked = false' in init. so can normal display.but this is a bug. because init is false default

**Comment by icarusion** [comment]
Vue.js can not change array by index. Please read Vue.js doc carefully.
