### ISSUE TITLE
[Bug Report]input-number cannot be deleted


### ISSUE THREAD

**Issue by zxzxzxygithub** [iview/iview#3290]
### Environment
mac/chrome/vue 2.0

### Reproduction link
[https://www.iviewui.com/components/input-number](https://www.iviewui.com/components/input-number)

### Steps to reproduce
input-number 输入数字，然后删除数字，然后点击外部任意地方使其失去焦点

### What is expected?
input-number输入框应该是空的

### What is actually happening?
input-number还是原来被删除的数字

**Comment by bitqiang** [comment]
最新的版本已经修复了这个bug。更新到2.11 会正常
