### ISSUE TITLE
[Bug Report]table filterRemote report an error 

### ISSUE THREAD

**Issue by pihc** [iview/iview#3294]
### Environment
mac 10.12.2/chrome  65.0.3325.181/vue ^2.5.9

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
columns definition
```
{
                        title: '订单状态',
                        key: 'order_status',
                        width: 110,
                        filters: [
                            {
                                label: '待支付',
                                value: 1
                            },
                            {
                                label: '已支付',
                                value: 2
                            },
                            {
                                label: '已退款',
                                value: 3
                            },
                        ],
                        filterRemote:function(value,key,column){
                           this.filterColumn(value,key,column);
                        }
```
in methods 
```
filterColumn:function(val,age,column){
               alert(111);
            },
```
chrome console
```
3.js:385 Uncaught TypeError: this.filterColumn is not a function
    at VueComponent.filterRemote (3.js:385)
    at VueComponent.filterOtherData (app.js:30546)
    at VueComponent.boundFn [as filterOtherData] (app.js:1457)
    at VueComponent.handleFilter (app.js:30562)
    at VueComponent.boundFn [as handleFilter] (app.js:1458)
    at VueComponent.handleFilter (app.js:30948)
    at Proxy.boundFn (app.js:1458)
    at click (app.js:44848)
    at invoker (app.js:3256)
    at HTMLButtonElement.fn._withTask.fn._withTask (app.js:3054)
```
I searched many times 
https://github.com/hezhiying/iview/blob/12bcf7bd14d0ca8f098ff7ad293e4f0f2fd8f872/examples/routers/table.vue

### What is expected?
can use

### What is actually happening?
make me crazy

---
sorry! I can not use jsfiddle, because there is a wall,I'm a rookie.please give me some advice. thank you!!

**Comment by denty** [comment]
1

**Comment by BosenY** [comment]
这个最好贴个example，你这个无法复现啊

**Comment by denty** [comment]
@pihc 出现这个问题是作用域的问题,需要改写
var that = this 到 data方法下,而不是return的结构中
`
 data() {
        var that = this;
        return {
            timeFilter: '',
            timeFilterOptions: [
                {
                    label: '按开工时间降序',
                    value: 1
                },
                {
                    label: '按开工时间升序',
                    value: 2
                },
                {
                    label: '按合同金额降序',
                    value: 3
                },
                {
                    label: '按合同金额升序',
                    value: 4
                },
                {
                    label: '按项目进度降序',
                    value: 5
                },
                {
                    label: '按项目进度升序',
                    value: 6
                },
                {
                    label: '按开工时间降序',
                    value: 7
                }
            ],
            filterFunction: (value, row) => {
                this.requestFilter();
            },
            header: [
                {
                    title: '订单号',
                    key: 'orderNo'
                },
                {
                    title: '状态',
                    key: 'status'
                },
                {
                    title: '项目进度',
                    key: 'status',
                    filterMultiple: false,
                    filterRemote(value, key, column) {
                        this.$Notice.open({
                            title: `正在远程过滤${key}`,
                            desc: value,
                            duration: 3,
                            onClose: () => {
                                that.remoteFilter(value, key, column);
                            }
                        });
                    },
...................
`

**Comment by denty** [comment]
@pihc 出现这个问题是作用域的问题,需要改写 var that = this 到 data方法下,而不是return的结构中
<img width="539" alt="2018-04-04 10 31 19" src="https://user-images.githubusercontent.com/4972911/38285802-88032598-37f4-11e8-9f6a-fc264d4b54e0.png">

**Comment by pihc** [comment]
@denty 谢谢你！么么哒😘

**Comment by linkcoder** [comment]
上面的代码看不太懂，能给出一下例子吗
