### ISSUE TITLE
使用懒加载，date-table.vue报错

### ISSUE THREAD

**Issue by tipsxBase** [iview/iview#3295]
SyntaxError: /node_modules/iview/src/components/date-picker/base/date-table.vue:
Unexpected token (78:20)

  76 |                 const dateIsInCurrentMonth = cell.date && tableMonth === cell.date.getMonth();
  77 |                 return {
> 78 |                     ...cell,
     |                     ^
  79 |                     type: time === today ? 'today' : cell.type,
  80 |                     selected: dateIsInCurrentMonth && selectedDays.includes(time),
  81 |                     disabled: (cell.date && disabledTestFn) && disabledTestFn(new Date(time)),

 @ ./node_modules/iview/src/components/date-picker/base/date-table.vue 3:0-106 4:0-119

**Comment by lucaszhu2zgf** [comment]
同样的问题，你用的babel 7？
