### ISSUE TITLE
[Bug Report]some missing api expressions in iview documents 

### ISSUE THREAD

**Issue by alanchenchen** [iview/iview#3302]
### Environment
win10 x64 / chrome 64.0.3282.119/ Vue 2.5.2

### Reproduction link
[https://www.iviewui.com/components/tag#API](https://www.iviewui.com/components/tag#API)

### Steps to reproduce
 1. In the tabel document, the prop row-class-name or className or cellClassName has to be setted without the prop stripe,otherwise the custom class won't work.
 2. In the tag document, it's not easy to know the emit event when user clcik the tag component.The 'on-change' emit event is missing althoght developer can find it from the vue-devtool

### What is expected?
 1. add the tips that using the prop row-class-name must disable the prop stripe in the tabel document
 2. add the emit event 'on-change'  in the tag document

### What is actually happening?
 1. In the tabel document, the prop row-class-name or className or cellClassName has to be setted without the prop stripe,otherwise the custom class won't work.
 2. In the tag document, it's not easy to know the emit event when user clcik the tag component.The 'on-change' emit event is missing althogth developer can find it from the vue-devtool

**Comment by icarusion** [comment]
About Table, you should submit a new issue and provide online demo.
About Tag, no `on-click` or other event.
