### ISSUE TITLE
[Bug Report]Carousel V-model bi-directional binding data post indicator and switch animation problem


### ISSUE THREAD

**Issue by kevin611003** [iview/iview#3310]
### Environment
Win10 x64 1703 / Chrome 64 / Vue2.5.16

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
Carousel双向绑定数据后点击切换箭头，当从最后一个CarouselItem切换到第一个CarouselItem时，动画是反向回滚到第一张。
如果去除Carousel双向绑定则动画正常，但是此时点击非活动指示器时，点击后成为活动指示器的元素样式没有变化，应该是active的样式才对。

### What is expected?
Carousel双向绑定数据后从最后一个CarouselItem切换到第一个CarouselItem时动画不是反向回滚。

### What is actually happening?
Carousel双向绑定数据后从最后一个CarouselItem切换到第一个CarouselItem时动画是反向回滚到第一张。

**Comment by BosenY** [comment]
PC上面轮播图大部分不都是这样实现的么，将translateX的值变为0，这个不是bug啊

**Comment by kevin611003** [comment]
@BosenY 不是说实现方式有问题，而是 Carousel 的 value 双向绑定后有bug。未绑定value时，从最后一个切换到第一个时显动画正常，绑定后的动画是反向回滚到第一张，这样不友好。

**Comment by icarusion** [comment]
fixed in https://github.com/iview/iview/commit/bbf4ee223f7413874392bc259ca53386fc4e0d40
