### ISSUE TITLE
The parent and child nodes of the [Feature Request]tree component should allow contact relationships


### ISSUE THREAD

**Issue by sowork** [iview/iview#3319]
### What problem does this feature solve?
分配菜单的时候，我可以允许用户只选择子菜单，不选择父菜单，前台用户显示的时候将子菜单作为一级菜单显示

### What does the proposed API look like?
* 允许用户点击父节点能够全选，但是也应该允许用户只单个选择某一个节点，不应该强制性要求选择父节点，子节点就必须全部选择，我觉得这个功能是相互冲突的，但是作为用户来讲确实是有时候希望使用全选，又想单个选择某个节点，我不知道该如何设计来解决这个用户的冲突
* 最开始是想使用穿梭框来实现给角色分配，但是菜单这种选择如果使用用户视觉上不直观，无法直观的看到自己需要哪些菜单的显示
* 我曾经想过给CheckBox点击添加三种状态来代表单选、全选、取消选择，觉得这个操作不符合用户的思维
* 我继续创建符合不同角色显示的菜单，然后根据不同角色分配新的菜单，但是这种会导致后台的菜单重复太多,也不太符合
```
=========================
        菜单A
           菜单B
           菜单C
        角色1 想显示菜单A 菜单B
        角色2 想显示菜单B 菜单C
        角色3 想显示菜单A
=========================
```
* 按照目前tree组件提供的功能来说，只有tree的select状态能实现这种功能，CheckBox是无法实现的
我问过一些人设计菜单的思路，他们认为只要选择子菜单就必须选择父菜单，我觉得对于限制性太高
* 如果有能够解决父节点单选不选择子节点，又能全选子节点的方案更好。。。。

**Comment by icarusion** [comment]
Sorry, we will not support this in the meantime.

**Comment by sowork** [comment]
...Both ant and element ui provide this unbinding function

**Comment by yabigal** [comment]
tree树节点怎么可以做到重复点击当前的一个节点，一直是选中的状态？除非选中其他节点，才为不选中状态
