### ISSUE TITLE
The [Bug Report]render function to render select multi selection drop-down box assembly


### ISSUE THREAD

**Issue by fennyFJJ** [iview/iview#3326]
### Environment
win7/google/2.5.9

### Reproduction link
[https://jsfiddle.net/yyrzhm46/623/](https://jsfiddle.net/yyrzhm46/623/)

### Steps to reproduce
https://jsfiddle.net/yyrzhm46/623/

### What is expected?
table中能够渲染出select下拉框组件，并能多选

### What is actually happening?
select不能多选

**Comment by icarusion** [comment]
Wrong demo
