### ISSUE TITLE
The al-cascader of [Bug Report]iview-area is conflicting with the version of iview2.12.0,


### ISSUE THREAD

**Issue by z1126** [iview/iview#3329]
### Environment
win10,Google Chrome 63.0.3239.108,vue 2.5.16

### Reproduction link
[https://github.com/z1126/iview-area-al-cascader/commit/e17d59b8914d8e02ad77f1c04e736e44e63c63ea](https://github.com/z1126/iview-area-al-cascader/commit/e17d59b8914d8e02ad77f1c04e736e44e63c63ea)

### Steps to reproduce
链接中代码，在iview2.12.0中会报TypeError: Cannot read property 'popper' of nul

### What is expected?
不报错，

### What is actually happening?
TypeError: Cannot read property 'popper' of null，导致无法取值，目前只与iview2.12.0有冲突

**Comment by icarusion** [comment]
Please go to iview-area to ask.
