### ISSUE TITLE
Error information on the [Bug Report]show-header console


### ISSUE THREAD

**Issue by suntao9108** [iview/iview#3333]
### Environment
iview 2.12.0

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
添加 :show-header="false" 属性，控制台出现错误信息

### What is actually happening?
现在控制台出现错误

**Comment by zczsunnyboy** [comment]
how to resolve it?
