### ISSUE TITLE
[Bug Report]iview2.12.0 DatePicker type="daterange" choose year and month result error

### ISSUE THREAD

**Issue by fsjdfz** [iview/iview#3345]
### Environment
windows10/Chrome/iview2.12.0

### Reproduction link
[https://jsfiddle.net/fsjdfz/tmppdroq/6/](https://jsfiddle.net/fsjdfz/tmppdroq/6/)

### Steps to reproduce
日期选择器type使用daterange，手动选择年或者选择月。如选择2010年1月
choose 2010-01

### What is expected?
2010年1月，返回选择的年月。
correct results:2010-01

### What is actually happening?
2011年2月，实际返回的年份多了一年月份也多了一个月。
actual result:2011-02

---
https://www.iviewui.com/components/date-picker
官网的demo也有这个bug

**Comment by icarusion** [comment]
Hi, @SergioCrisostomo, in 2.11.0, this is ok, but 2.12.0 is error.
transition of this issue:
https://jsfiddle.net/9sm0xzhr/2/
steps:
- select 2010-01, the date is displayed as `2011-02`.
