### ISSUE TITLE
Is there a bit of an irrational memory footprint under [Bug Report]IE?


### ISSUE THREAD

**Issue by Panhaiwei** [iview/iview#3346]
### Environment
windows10 IE11（11.0.56）

### Reproduction link
[https://www.iviewui.com/docs/guide/install](https://www.iviewui.com/docs/guide/install)

### Steps to reproduce
打开iview官网，打开组件页面，使用win10下的IE11的内存监控工具（CTRL SHIFT U），点击不同组件和不同页面，能够明显发现内存增长，从400M涨到600MCPU占用30%，并且继续操作会造成偶发性的浏览器卡死
![1](https://user-images.githubusercontent.com/13009686/38591182-0acc757e-3d68-11e8-94a7-b5070ce7bb28.png)
![image](https://user-images.githubusercontent.com/13009686/38591199-22a3a8ca-3d68-11e8-9f96-6f8f26f3d675.png)

### What is expected?
内存是否泄露或不合理，能否优化？

### What is actually happening?
优化内存占用

**Comment by Panhaiwei** [comment]
@icarusion 能否给出原因是什么，如果你们不能处理，使用框架的时候可以尽量避免这种问题？

**Comment by marszoolong** [comment]
嗯，最近发现我们的应用有内容泄漏，问题追到了iview的table组件，具体还在调试中

**Comment by iijx** [comment]
嗯，我们的后台也是，刚开始测试时小数据里没问题，，后来数据量大了（目前几万条左右，一页显示20条，每条10来个字段），操作一段时间就会卡死，devtools里发现内存占用过大，页面1个多G。猜测应该时table组件里存在内存泄漏。后来还是将table组件换成了element的table组件。

**Comment by deot** [comment]
#5357 问题依旧没有被解决

**Comment by 592192890** [comment]
我们项目上线后也出现内存泄露了，每两个小时就页面奔溃了，后面也定位到table组件内存泄露，最后只能放弃iview，使用elementUI重写
