### ISSUE TITLE
The [Bug Report]Cascader component searches for bug


### ISSUE THREAD

**Issue by xiaoxin0818** [iview/iview#3352]
### Environment
mac/chrome 65/最新版本

### Reproduction link
[https://jsfiddle.net/w95fjczx/1/](https://jsfiddle.net/w95fjczx/1/)

### Steps to reproduce
数据value为非string类型，如number；
Cascader搜索结果，选择后值不选中；

### What is expected?
Cascader搜索结果，选择值不选中；

### What is actually happening?
Cascader搜索结果，选择值选中；

**Comment by icarusion** [comment]
搜索暂不支持 Number

**Comment by xiaoxin0818** [comment]
并不是搜索number，而是value为非string的，搜索功能有bug
