### ISSUE TITLE
Display error after page set show-sizer property under [Bug Report]tabs


### ISSUE THREAD

**Issue by yl410104303** [iview/iview#3357]
### Environment
macOS 10.13.1/chrome 65/“vue": "^2.5.2”

### Reproduction link
[https://jsfiddle.net/yyrzhm46/676/](https://jsfiddle.net/yyrzhm46/676/)

### Steps to reproduce
1.点击show-sizer改变分页按钮

### What is expected?
显示下拉分页选项

### What is actually happening?
在tabs里没有下拉选项

**Comment by icarusion** [comment]
try to use `transfer` property.
