### ISSUE TITLE
[建议/样式] 移除下拉菜单的 padding

### ISSUE THREAD

**Issue by grandsong** [iview/iview#336]
### 范围：

- Select 选择器
- Menu 导航菜单

### 问题：

CSS中，`.ivu-select-dropdown` 的 `padding: 5px 0` 导致：
当鼠标悬停顶部和底部两个选项时（选项的背景色变深），暴露出这个padding的留白。

我觉得很不美观。

印象中没有哪个有名的组件库（包括 Ant Design ）是这样设计的。

### 方案

去掉`padding: 5px 0`这一行就好。

### iView 版本号

2.0.0-rc-1

（其它信息我认为一律无关，就省略了。）

**Comment by icarusion** [comment]
建议覆盖css

**Comment by grandsong** [comment]
你是说让使用iview的开发者自己另外写css？
这当然总是可行的。但我提交这个issue，出于两个目的：

1. 希望iview本身发生改变。省得大家还要覆盖。
2. 如果你反对，我很想知道这个padding存在的理由是什么？设计的合理性有什么来历或借鉴？

**Comment by icarusion** [comment]
建议看看《写给大家看的设计书》

**Comment by grandsong** [comment]
我是特意先去Ant Design对比过他们的下拉菜单。Ant Design在《设计原则/引言》里特意推荐了《写给大家看的设计书》。显然他们是充分学习了这本书后作出了下拉菜单的设计。但为什么iview的下拉菜单就偏偏这么不一样？

**Comment by icarusion** [comment]
首先，为什么 iView 要和 AntD 一样。
iView 的每一粒像素都是整个设计团队思考过的。
留白是一种美。
下面三个截图分别来自 Twitter、Facebook、Tumblr：
<img width="389" alt="qq20170309-102621 2x" src="https://cloud.githubusercontent.com/assets/5370542/23733374/88e7dba4-04b3-11e7-8f55-45a4c2e99e86.png">
<img width="510" alt="qq20170309-102651 2x" src="https://cloud.githubusercontent.com/assets/5370542/23733386/91a47810-04b3-11e7-9d09-d243c8d7fc49.png">
<img width="336" alt="qq20170309-103051 2x" src="https://cloud.githubusercontent.com/assets/5370542/23733395/9df57182-04b3-11e7-8947-dd38d58c3f5e.png">

**Comment by grandsong** [comment]
OK. 有理有据，令人信服。
