### ISSUE TITLE
iView is not defined???? why

### ISSUE THREAD

**Issue by JabFury** [iview/iview#3361]
I tried to import iView,but it doesn't work!  
this is my main.js
I don't know why iView is not defined? my modules were installed successful

import Vue from 'vue'
import App from './App'
import router from './router'
import store from './store/store'
import iView from 'iview';
import 'iview/dist/styles/iview.css';

Vue.config.productionTip = false;
Vue.use(iView);

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  components: {App},
  template: '<App/>'
})

**Comment by haochencheng** [comment]
@JabFury Will you solve it?i have reached the same issue.

**Comment by GreenMashimaro** [comment]
@haochencheng hi，i have reached the same issue. So, If I modify the import, I can run it.
"import iView from 'iView'"
