### ISSUE TITLE
[Feature Request]iview 的表格的列宽可以自适应宽度吗，不换行，且把所有的文字显示出来，不是为所需求的列定死一个宽度

### ISSUE THREAD

**Issue by Zeronlyou** [iview/iview#3364]
### What problem does this feature solve?
因为有些列必须显示出来，但是换行的话和使用ellipsis属性的显示效果不好，就想在一行里显示，但是定一个比较长的宽度的话，所有表格类似这种需求都要定义一个不同的长宽度，这样就比较麻烦

### What does the proposed API look like?
列的宽度是随着那一列的最长的字段的宽度，所有的文字可以显示在一行里，但不是用定死的宽度来限制它，也不是用ellipsis属性来省略一些文字

**Comment by icarusion** [comment]
3.0 add `tooltip`

**Comment by zhangchunlin** [comment]
@Zeronlyou 这个问题有fix吗? 我试了最新的3.2.1,table的列宽还是不能自适应
