### ISSUE TITLE
[Bug Report]2.13.0 version CDN introduced direct error


### ISSUE THREAD

**Issue by chenym1992** [iview/iview#3366]
### Environment
macos 10.13.4/chrome 65.0.3325.181/vue 2.5.16

### Reproduction link
[http://jsrun.net/eVZKp/](http://jsrun.net/eVZKp/)

### Steps to reproduce
直接在html引入iview 2.13.0js ，看console 报错
Uncaught SyntaxError: Unexpected end of input

### What is expected?
页面正常显示

### What is actually happening?
页面显示不正常
Uncaught SyntaxError: Unexpected end of input

**Comment by dennislan** [comment]
CDN 说，这个锅我不背， 用非压缩版是 OK的。 
我现在引用的是 
`<script src="//unpkg.com/iview/dist/iview.js"></script>`

PS. gitter 还有人在问这个问题

**Comment by kajweb** [comment]
可以先使用这两个
unpkg.com/iview/dist/iview.js
https://unpkg.com/iview@2.12.0/dist/iview.min.js
