### ISSUE TITLE
[Feature Request]Transitions component

### ISSUE THREAD

**Issue by AGPDev** [iview/iview#3377]
### What problem does this feature solve?
iview dont have or i dont find it in doc, component to simple way implement transitions.

### What does the proposed API look like?
https://ant.design/docs/spec/transition

**Comment by icarusion** [comment]
iView has some built-in basic animations that you can look for in source styles, but there is currently no plan to develop a library of animation components specifically.
https://github.com/iview/iview/tree/2.0/src/styles/animation
