### ISSUE TITLE
[Feature Request]Classes for text

### ISSUE THREAD

**Issue by AGPDev** [iview/iview#3379]
### What problem does this feature solve?
https://www.iviewui.com/components/font-en
Here have various rules but dont have class for help use this rules.

### What does the proposed API look like?
here is one example:
https://vuetifyjs.com/en/style/typography

**Comment by icarusion** [comment]
You can use `.ivu-article`.
```html
<div class="ivu-article">
    <h1>try</h1>
</div>
```
