### ISSUE TITLE
[Bug Report]Menu component can't behavior right expand action when manually trigger UpdateOpened() event in iView version 2.13.0

### ISSUE THREAD

**Issue by thisisyr** [iview/iview#3382]
### Environment
Chrome, FireFox, IE10

### Reproduction link
[https://jsfiddle.net/thisisyr/eywraw8t/34157/](https://jsfiddle.net/thisisyr/eywraw8t/34157/)

### Steps to reproduce
1.Click and Expand menu
2.Select one menu item

### What is expected?
Menu stay expanded.

### What is actually happening?
Menu collapse.

---
New version iView component menu('iview/src/Menu/menu.vue') used attirbute openedNames for updateOpened() function.
However, the watcher for openNames(not openedNames) will not triggered when there is no update for value openNames (eg, click submenu in this scenario):(line 121 in 'iview/src/Menu/menu.vue'),
 watch: {
            openNames (names) {
                this.openedNames = names;
            },
That's the reason caused this issue.

**Comment by eeve** [comment]
@icarusion

**Comment by thisisyr** [comment]
Bug Fixed
