### ISSUE TITLE
[建议/官网/内容] 自动增加组件源码文件的链接

### ISSUE THREAD

**Issue by grandsong** [iview/iview#339]
### 问题：

正如你自己所说：（[“目前文档的实例与示例代码分离实现比较重”](https://github.com/iview/iview/issues/79)）。

例如：[组件/Switch 开关](https://www.iviewui.com/components/switch)里，所有"Switch"还是旧的，而又出现了新的"i-button"，显然是向2.0只迈出了一小步的结果。

我起初以为只要稍加猜想和尝试，就能摸索出2.0的i-switch的接口，可惜彻底失败。

直到我查看了源码后才发现，原本的"checked"属性变成了"value"，而且不再需要".sync"后缀。这变化可就大了。

### 方案：

所以，只有源码是最可靠的。

建议：在每个组件的页面的右上角，自动生成链接，以便读者发现文档陈旧时，总可以方便地查看最新源码本身。

比如：`<a src="https://github.com/iview/iview/blob/2.0/src/components/switch/switch.vue" target="_blank">&lt;i-switch&gt;的2.0源代码</a>`

**Comment by icarusion** [comment]
好主意

**Comment by grandsong** [comment]
加油！
