### ISSUE TITLE
[Bug Report]Introduce <Scroll> component on demand, cannot find <Spin> component and <Icon> component

### ISSUE THREAD

**Issue by tlinlin** [iview/iview#3391]
### Environment
windows 10/vue2/chrome

### Reproduction link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
Introduce <Scroll> components on demand

### What is expected?
Can be introduced directly into the scroll

### What is actually happening?
vue.esm.js?efeb:591 [Vue warn]: Unknown custom element: <Spin> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Loader> at node_modules\iview\src\components\scroll\loading-component.vue
       <Scroll> at node_modules\iview\src\components\scroll\scroll.vue
         <Ranking> at src\components\Ranking.vue
           <Content> at node_modules\iview\src\components\layout\content.vue
             <Layout> at node_modules\iview\src\components\layout\layout.vue
               <App> at src\components\Home.vue
                 <App> at src\App.vue
                   <Root>

**Comment by hoset** [comment]
刚刚遇到这个问题，请问大佬如何解决的
