### ISSUE TITLE
Page 分页  组件 IE9,10,11显示异常

### ISSUE THREAD

**Issue by YXDay** [iview/iview#34]
如图
![920a7370-90ad-4c9c-83bf-16facabdff68](https://cloud.githubusercontent.com/assets/9492564/19723116/6d49d2dc-9bac-11e6-9d74-45923c623788.JPG)

**Comment by jingsam** [comment]
谢谢，正在处理这个bug

**Comment by icarusion** [comment]
这个是什么原因呢，看似样式没有应用，很多组件在IE上都有些样式问题

**Comment by jingsam** [comment]
ivu-page-item 这个class没有附着到分页的li元素上

**Comment by jingsam** [comment]
此问题的根源在于在template中使用了ES6语法，例如模板字符串 ```:class="[`${prefixCls}-item`]"```.

在template中的表达式是无法在babel中转换为es5的，意味着只有template中的表达式是浏览器所支持的语法特性时，才能正确地被解析。

此问题到vue2也是无解的，所以要支持IE，必须将这些属性转换为计算属性或者使用字符串拼接。就现在来看，使用字符串拼接的成本小一些。

**Comment by icarusion** [comment]
这样啊，那问题挺严重的，之前忽略了，很多组件都用了字符串模板，我在后面的一个版本批量改一下吧

**Comment by henryzp** [comment]
@jingsam ，它这个组件是基于vue1.x吗？还是2.x？

**Comment by jingsam** [comment]
1.0， 能所有组件完成之后会考虑更新到2.0

**Comment by jingsam** [comment]
@YXDay fixed in #39
