### ISSUE TITLE
[Bug Report]select component, in remote search, when the scroll bar is dropdown, the option data will be refreshed, which leads to no convenient choice.


### ISSUE THREAD

**Issue by zhougangnj** [iview/iview#3401]
### Environment
iview 2.13

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
1、输入字符
2、出现下拉框（带滚动条）
3、拉动滚动条
4、下拉框消失，导致无法选择

### What is expected?
正常选择

### What is actually happening?
有下拉框滚动条时，无法选择

---
帮助文档里的远程搜索样例就能重现

**Comment by icarusion** [comment]
Has been fixed in #3157
