### ISSUE TITLE
[Feature Request]<Select> or <Option> component filter the  CRLF character in textContent

### ISSUE THREAD

**Issue by Kinghts** [iview/iview#3405]
### What problem does this feature solve?
when people use Select component like this:
```
<Select filterable>
        <Option v-for="(item, index) in list" :value="item.id" :key="index" filterable> <!--CRLF here-->
               {{ item.name }}  <!--CRLF here-->
        </Option>
</Select>
```
the render result is confused:  the CRLF characters are inserted into the options, and  the select component's label display a lot of whitespace. 

### What does the proposed API look like?
use the String.trim() method or RegExp to filter the text in <Option>,example:
```
String.trim(textContext)
```

**Comment by SergioCrisostomo** [comment]
Fixed in https://github.com/iview/iview/pull/3579

**Comment by qtttttttttting** [comment]
In version 3.3.3 ,this problem still exist .
