### ISSUE TITLE
对iview的一些建议

### ISSUE THREAD

**Issue by jinjinwa** [iview/iview#341]
希望增加的组件：
1：TreeSelect 树选择组件。 
2：upload 点击上传功能。

iview一些涉及资源 是否考虑像element一样开源出来呢？

**Comment by rijn** [comment]
We have already had Tree and Upload component.

iView is a public open source project. What kind of resource do you want?

**Comment by icarusion** [comment]
Why not carefully read the document first

**Comment by jinjinwa** [comment]
sorry，我描述有问题，我口中说的，是upload的手动上传功能，目前组件提供的是选择文件后自动上传。。另外我指的资源是指 http://element.eleme.io/#/zh-CN/resource ，询问是否会开源类似于这样的资源。
![image](https://cloud.githubusercontent.com/assets/12455937/23644075/58764132-0340-11e7-8321-7eaa18b9ffc3.png) this is TreeSelect  https://ant.design/components/tree-select-cn/

**Comment by icarusion** [comment]
contribution welcome

**Comment by rijn** [comment]
yeah. I think manual upload is important. I will go through this part later.

**Comment by icarusion** [comment]
if you want to do something before upload, you should use `before-upload` hook.

**Comment by jinjinwa** [comment]
想实现手动上传文件，且选择图片文件之后直接预览。upload组件好像没有选择完文件之后的回调函数。before-upload函数在点击上传按钮之后执行的。

**Comment by alwaysc** [comment]
any update?
