### ISSUE TITLE
[Bug Report]Cascader Firefox style error


### ISSUE THREAD

**Issue by taojunnan** [iview/iview#3410]
### Environment
win10/Firefox/2.0

### Reproduction link
[https://jsfiddle.net/sgukxnxj/2/](https://jsfiddle.net/sgukxnxj/2/)

### Steps to reproduce
火狐浏览器下，Cascader 用div包着，div有个样式是position: absolute; 当级联框数据文本过长时，出现文本超出下拉框边界的样式错误

### What is expected?
文本过长时也能在下拉框边界内

### What is actually happening?
文本过长时超出下拉框边界

---
只在火狐浏览器，只有加了css position属性才有这个情况

**Comment by sunbeam-young** [comment]
.ivu-cascader .ivu-cascader-menu-item {
      white-space: nowrap;
}
