### ISSUE TITLE
[Bug Report]Uncaught SyntaxError: Unexpected end of input   

### ISSUE THREAD

**Issue by jiyehang** [iview/iview#3416]
### Environment
360急速浏览器

### Reproduction link
[http://output.jsbin.com/libihed](http://output.jsbin.com/libihed)

### Steps to reproduce
http://output.jsbin.com/libihed

### What is expected?
能修复好

### What is actually happening?
点击没有反应

**Comment by icarusion** [comment]
CDN：unpkg 的 bug，换源。
