### ISSUE TITLE
table 分组表头

### ISSUE THREAD

**Issue by BOOMBowen** [iview/iview#3419]
分组表头 如果是 异步更新 this.columns= [
{title:"测试",align:"center",
                    children:[
                        {title:"测试1",key:"key1"},
                        {title:"测试2",key:"key2"},
                        {title:"测试3",key:"key3"},
                        {title:"测试4",key:"key4"}
                    ]
                }
]
就会报错 You may have an infinite update loop in watcher with expression "columns" ；
是bug还是我数据的问题？

**Comment by uzlov** [comment]
https://github.com/iview/iview/pull/3767

**Comment by dasnnj** [comment]
https://github.com/iview/iview/issues/3472#issuecomment-399395879
