### ISSUE TITLE
iview>table>columns>children

### ISSUE THREAD

**Issue by BOOMBowen** [iview/iview#3420]
if i use 
this.columns= [
  {title:"测试",align:"center",
     children:[
           {title:"测试1",key:"key1"},
           {title:"测试2",key:"key2"},
           {title:"测试3",key:"key3"},
          {title:"测试4",key:"key4"}
    ]
  }
]
for my table 
will warn me 
You may have an infinite update loop in watcher with expression "columns"
Is this a Bug or a wrong?

**Comment by bitqiang** [comment]
我也遇到了，你是怎么解决的呢？
我先暂时回退到2.4.0版本避免了。
@BOOMBowen

**Comment by maggie-chen** [comment]
我是放在了data里面，但是有的浏览器可以，有的浏览器还是不可以。愁
