### ISSUE TITLE
[Bug Report] use the Carousel in the Form, click the button will cause the page to refresh

### ISSUE THREAD

**Issue by insertSweat** [iview/iview#3426]
### Environment
Macos 10.12.4 (16E195) / Chrome 65.0.3325.181 / Vue 2.5.2

### Reproduction link
[https://jsfiddle.net/zhaolin/xh6hrhgt/](https://jsfiddle.net/zhaolin/xh6hrhgt/)

### Steps to reproduce
在Form标签中使用Carousel

### What is expected?
点击切换按钮不刷新页面

### What is actually happening?
点击切换按钮刷新了页面

---
在表单中展示已上传图片

**Comment by sunderls** [comment]
This is because the [arrows and indicators are `<button>`](https://github.com/iview/iview/blob/2.0/src/components/carousel/carousel.vue#L3-L24),
and [default button type is 'submit', so click them will trigger form submit.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)

**Comment by insertSweat** [comment]
thanks, I know it，But I can't fix it so I submit this issue

**Comment by sunderls** [comment]
Ah, here is the pr to fix it https://github.com/iview/iview/pull/3433
