### ISSUE TITLE
[Bug Report] Google browser 44 cannot render calendar pop-up content


### ISSUE THREAD

**Issue by yangdan8** [iview/iview#3428]
### Environment
win10/Chrome 44/Vue 2.5

### Reproduction link
[https://codepen.io/yangdan8/pen/QrWWzZ](https://codepen.io/yangdan8/pen/QrWWzZ)

### Steps to reproduce
鼠标点击输入框

### What is expected?
弹出可选日期

### What is actually happening?
无日期显示

**Comment by yangdan8** [comment]
![qq 20180418114735](https://user-images.githubusercontent.com/16515026/38910892-59fe8e52-42fe-11e8-81f4-735f387dfb6b.png)

**Comment by yangdan8** [comment]
![qq 20180418114735](https://user-images.githubusercontent.com/16515026/38910921-7a8ef3c8-42fe-11e8-9437-0b95fbc5a0f8.png)

**Comment by icarusion** [comment]
升级。
