### ISSUE TITLE
iView安装问题

### ISSUE THREAD

**Issue by sunshinebutterfly** [iview/iview#343]
### iView 版本号
本地环境（mac）1.0.1 
开发环境（linux）1.0.1 

### 操作系统
本地环境、mac
开发环境、linux

### Vue 版本号
1.0.17 

首先说下本地环境，mac下
按照官网步骤安装。得到package.json文件如下

![image](https://cloud.githubusercontent.com/assets/17675931/23615323/fdb916f4-02c0-11e7-85a5-b841c51432cc.png)

安装完成没有问题，本地可以运行

开发环境安装和本地安装方法一样，得到package.json如下
![image](https://cloud.githubusercontent.com/assets/17675931/23615659/1cf944d4-02c2-11e7-87a3-39ad137b2138.png)

然后开发环境报错。 也就是main.js文件的引入 样式表和 iview 找不到
我也不知道是mac ，linux路径的问题还是其他原因

总之对比配置文件后，我发现开发环境并没有 本地环境的那些 变量（红圈内的内容）

我想知道这个问题应该怎么样解决？因为线上系统是放在linux下的

**Comment by jingsam** [comment]
开发环境是什么意思？

**Comment by sunshinebutterfly** [comment]
@jingsam 就是开发人员自己测试项目 部署的一套环境。

**Comment by jingsam** [comment]
npm install iview 啊。为什么要手动从复制到node modules

**Comment by sunshinebutterfly** [comment]
@jingsam 我没有手动复制。我在git的node_modules文件夹下 执行npm install iview --save 难道这样是错的吗？

**Comment by rijn** [comment]
Check your path?

**Comment by sunshinebutterfly** [comment]
@rijn 我知道是路径问题，但是我不知道应该怎么去解决他

**Comment by jingsam** [comment]
在你的项目目录npm install iview -S
