### ISSUE TITLE
[Feature Request]Table does not refresh the data in real time after the data Data is bound


### ISSUE THREAD

**Issue by sports98** [iview/iview#3436]
### What problem does this feature solve?
当我们进行了类似上下顺序排序的操作后，我们更改了data内的数据位置
但页面中并没有达到我们所期望的排序数据。跟踪查看了下
data的数据已经有实际的调整。
页面中没有实时反馈出来

### What does the proposed API look like?
期望能实时的渲染页面

**Comment by David-Tsui** [comment]
代碼
