### ISSUE TITLE
[Bug Report]Conflict between fullscreen and dropdownmenu

### ISSUE THREAD

**Issue by pkuwwt** [iview/iview#3447]
### Environment
Mac/windows, chrome 65, vue2

### Reproduction link
[https://iview.github.io/iview-admin/#/home](https://iview.github.io/iview-admin/#/home)

### Steps to reproduce
  1. Goto https://iview.github.io/iview-admin/#/home
  2. Execute `javascript:document.body.children[0].webkitRequestFullscreen()` in address bar
      or execute `document.body.children[0].webkitRequestFullscreen()` in console.

### What is expected?
  * The dropdown menu show as we click `iview_admin`.

### What is actually happening?
  * The dropdown menu not show. Actually, the CSS property `visibility` will be changed as expected, but soon restored to `none`.

---
Let a specific element  other than `body`  to be fullscreen is a very useful feature provided by HTML. However, due to this issue, we have to hand-code to implement the fullscreen feature. I guess this problem also exists in other browsers.

**Comment by pkuwwt** [comment]
A bug nobody cares after 20 days.

**Comment by icarusion** [comment]
If there is an iview-admin problem, please submit issues into iview-admin project.

**Comment by icarusion** [comment]
So, why not provide on online demo using jsfiddle

**Comment by pkuwwt** [comment]
Fine, I will do it
So, why there isn't any feedback for 20 days?
