### ISSUE TITLE
[Bug Report]Input component loading gif under IE

### ISSUE THREAD

**Issue by xiaomingdexian** [iview/iview#3466]
### Environment
iview 2.13.0  IE9-11

### Reproduction link
[https://github.com/iview/iview/issues/none](https://github.com/iview/iview/issues/none)
![57ec516ecd5c45aca39cd44f256233c2](https://user-images.githubusercontent.com/26076008/39112511-4be65596-470b-11e8-8d81-39d3acac1a48.jpg)

### Steps to reproduce
在chrome下是没有的，请问怎么让它消失？

### What is expected?
无

### What is actually happening?
无

**Comment by xiaomingdexian** [comment]
@icarusion  麻烦再看看，是在编译后出现的

**Comment by peacecup** [comment]
我也遇到了这个问题，看源码逻辑是icon字段如果存在就会有一个过度的loading，在dev下正常，在生产环境出现了问题
