### ISSUE TITLE
The [Bug Report]slider component cannot be dragged


### ISSUE THREAD

**Issue by lhywell** [iview/iview#3468]
### Environment
win7,win10/chrome64,65/vue2.5.2

### Reproduction link
[http://smartdata.b0.upaiyun.com/iview/iview%20-%20slider.html](http://smartdata.b0.upaiyun.com/iview/iview%20-%20slider.html)

### Steps to reproduce
拖动左边的按钮后，右面会自动回到23点，而且再也拖动不了

### What is expected?
左右两个点均可以滑动

### What is actually happening?
右侧滑动不到左侧

**Comment by icarusion** [comment]
Hi, @SergioCrisostomo , could you have a look this problem if you have time, i make a simple example of this bug:
https://jsfiddle.net/yyrzhm46/789/ 
Steps to reproduce:
- drag left dot to `10` or `12`;
- than, the right dot can not drag to left.
