### ISSUE TITLE
【建议】iview字号感觉有点小了

### ISSUE THREAD

**Issue by rongxingsun** [iview/iview#347]
iview字号对现在的显示屏来说普遍感觉小了，所有字体都大2号

**Comment by icarusion** [comment]
https://www.iviewui.com/docs/guide/theme

**Comment by renruijun** [comment]
请问你这个问题解决了吗？字体偏小的问题。我现在也遇到这个问题。。。

**Comment by rongxingsun** [comment]
字体是可以变大，但是感觉整体不是很协调，除非你可以重写css

**Comment by docikaci** [comment]
@renruijun  字体偏小的问题 怎么方便解决呢？
