### ISSUE TITLE
If the [Bug Report]table component is a group header, if the data is given by Ajax, it will cause the browser to die.


### ISSUE THREAD

**Issue by xltxlm** [iview/iview#3470]
### Environment
chrome

### Reproduction link
[https://jsfiddle.net/yyrzhm46/781/](https://jsfiddle.net/yyrzhm46/781/)

### Steps to reproduce
需要搭建本地服务运行。造一个t.json，执行

### What is expected?
正常渲染出表格头

### What is actually happening?
造成浏览器假死

---
如果json数据是直接写死在html代码里面，运行时正常的。

**Comment by oleorz** [comment]
i meet same issue

**Comment by six-gold** [comment]
> i meet same issue

hi, oleorz, have u solve the problem yet? i met the same problem now.
