### ISSUE TITLE
The tooltip component is displayed in the [Bug Report]table header to show the location exception.


### ISSUE THREAD

**Issue by stevenwu2016** [iview/iview#3474]
### Environment
mac/chrome 56/vue 2.5.3

### Reproduction link
[https://jsfiddle.net/steven2018/for9nsLe/25/](https://jsfiddle.net/steven2018/for9nsLe/25/)

### Steps to reproduce
1.鼠标放到第一列的问号处
2.鼠标移动到第二列的问号处

### What is expected?
第二列的提示应该显示在第二列的问号上面

### What is actually happening?
所有列的提示都显示在第一列的上面

---
从iview2.11.0开始这个问题就出现了，应该是在修改table组件的时候造成的

**Comment by David-Tsui** [comment]
這是文件有的東西，加上transfer: true就好了

**Comment by stevenwu2016** [comment]
@David-Tsui 文件里的东西？能具体点吗？这是演示地址：https://jsfiddle.net/steven2018/for9nsLe/29/

**Comment by David-Tsui** [comment]
@stevenwu2016 

https://jsfiddle.net/st880221/yg0frupy/1/

![debug](https://user-images.githubusercontent.com/8610682/39229284-b2968830-4894-11e8-936a-589337030b72.PNG)

**Comment by stevenwu2016** [comment]
@David-Tsui 明白了，多谢了
