### ISSUE TITLE
InputNumber的on-change方法无法监听到最后一个键盘回退操作

### ISSUE THREAD

**Issue by ddqre12345** [iview/iview#3477]
因为我是通过render添加的InputNumber，希望通过on-change来获取当前输入框值，但是似乎监听不到最后一个键盘回退，例如：123，删除3，2时都能监听到，但是删除1无法监听到

**Comment by spenggithub** [comment]
为什么关掉 你们这个bug从2.0就没有解决一直带到了3.0 666
