### ISSUE TITLE
[Bug Report]Scroll not working

### ISSUE THREAD

**Issue by xiaomingdexian** [iview/iview#3478]
### Environment
chrome（57.0.2987.110）

### Reproduction link
[https://www.iviewui.com/components/scroll](https://www.iviewui.com/components/scroll)

### Steps to reproduce
官网上的示例、本地测试都无效(所有事件都无法触发)，我查过issues，之前好像出现过这个问题[#2137](https://github.com/iview/iview/issues/2137)，用自己的和同事的浏览器都试过，都没有效果，请问这个bug是又重现了吗？

### What is expected?
无

### What is actually happening?
无

**Comment by David-Tsui** [comment]
調整distance-to-edge即可 [-20, -20]

**Comment by xiaomingdexian** [comment]
@David-Tsui 这个我也试过了。。也没用啊，请问你使用的是最新版的iview吗

**Comment by SergioCrisostomo** [comment]
Could some of you add a explanation in English? I'm happy to help/fix if I understand the problem :)

**Comment by David-Tsui** [comment]
@xiaomingdexian 對的，2.13版，官網上的是可以用的，只是不好觸發而已，有code嗎?

Yes, I use the latest version of iview; besides, the example in the official site **does work**, just because the minus distance results in that the Scroll component too difficult to trigger.
And could you show part of your code?

**Comment by xiaomingdexian** [comment]
@David-Tsui @SergioCrisostomo Thank you for your responce
I set the distance-to-edge attribute to be [-20, -100].
And it works.
But when I pulled the scrollbar down to the bottom.
It won't emit the callback.
Part of users may use the scrollbar , so I think the component is very nice with a slight flaw

**Comment by wang-mj2016** [comment]
@David-Tsui 一开始不设置要费很大力气才能滑动，加了之后，很容易就滑动了。。感谢，哈哈

**Comment by lzynihao** [comment]
Scroll past the bottom by using mouse wheel
