### ISSUE TITLE
[Bug Report]safiri browser table component performance bug browser card dead


### ISSUE THREAD

**Issue by VicBetter** [iview/iview#3480]
### Environment
safiri 浏览器 11.0.1

### Reproduction link
[https://www.iviewui.com/new-issue](https://www.iviewui.com/new-issue)

### Steps to reproduce
table 表头超过8列时，导致safiri浏览器卡死。测试了多台safiri 浏览器均有该问题

### What is expected?
table组件 在safiri浏览器下  表头超过8项时可以正常使用   

### What is actually happening?
table组件 在safiri浏览器下  表头超过8项时无法使用

---
希望排查一下，什么原因会导致浏览器卡死

**Comment by amazingdudu** [comment]
应该是iview2.9之前的版本有此问题，之后的版本无此问题
