### ISSUE TITLE
[Feature Request]Props footerHide can not be work in Modal instance

### ISSUE THREAD

**Issue by meteorfall** [iview/iview#3481]
### What problem does this feature solve?
When use custom content Modal by "this.$Modal.confirm(.....)" , we need to customize the footer as well.So we need to hide the default footer,But we found the Props footerHide can not work in Modal indatance,it can work in "<Modal hideFooter="true"...></Modal>" 

### What does the proposed API look like?
in sourcecode "confirm.js",I found it render the footerVNodes（Buttons） directly, without consider the props footerHide.

**Comment by icarusion** [comment]
footerHide can not used in $Modal
