### ISSUE TITLE
[Bug Report]menu horizontal multilevel menu style and function exception


### ISSUE THREAD

**Issue by simon07** [iview/iview#3483]
### Environment
chrome

### Reproduction link
[https://jsfiddle.net/neverretreat/yuwv7kvw/](https://jsfiddle.net/neverretreat/yuwv7kvw/)

### Steps to reproduce
1、设置菜单为横向。2、将菜单层级增加为3级。3、将鼠标悬浮于2级菜单上，就可以看出问题了。

### What is expected?
能够正常的展开二级菜单，三级菜单应该在二级菜单的右侧展开。

### What is actually happening?
三级菜单在二级菜单的下面展开，并且二级菜单的样式也是不对的。

**Comment by icarusion** [comment]
横向菜单暂不支持多级
