### ISSUE TITLE
[Feature Request][Suggestion] MenuItem Should Support Using <router-link> Inside it

### ISSUE THREAD

**Issue by BinotaLIU** [iview/iview#3484]
#### Example
Take iView document site for example: https://www.iviewui.com/docs/guide/install  
The source code [src/components/navigate.vue](https://github.com/iview/iview-doc/blob/master/src/components/navigate.vue) handle the `click` event on MenuItem, then use `this.$router.to` to redirect ([L124](https://github.com/iview/iview-doc/blob/master/src/components/navigate.vue#L124)), called `programmatical navigation`.  
In this issue, I will use "fake links" to call them.  

#### Why Not Use Programmatical Navigation?
It is not a good idea to use a programmatical navigation for all links.  
The main reason is: **These fake links will not have native context menu, such as "open in new tab", "open in new window", and so on**.  

#### What I do
Back to the iView document site, I always open multiple pages as once.
If I opened `Form` page, I maight also want to check the `Input` page. Thus, I will want right click on the `Input` link on the page and open it in a new tab.

When I'm implementing the site navigation for my projects, I always just add a `<router-link>` inside it:  
```html
<Submenu name="companies">
    <template slot="title">
        <Icon type="briefcase" />
        Links
    </template>
    <iMenuItem name="all-companies">
        <router-link to="/link-1">
            Link1
        </router-link>
     </iMenuItem>
</Submenu>
```

Unfortunatally, the result is not what we expected:  
![screenshot_7](https://user-images.githubusercontent.com/3190556/39236045-35086ad0-48aa-11e8-8911-9fce1b0f04af.jpg)

The element `a` is smaller then it's parent not. As the result, if we want to open the link, we have to click on the word exactly.  

#### Conclusion
iView should do suggest in the document of MenuItem, to recommend use `<router-link>`, rather then ask developers to write their own on click event handler. Then optimize the style sheet to compact use `<MenuItem>` with `<a>`

### What does the proposed API look like?
Described above.

**Comment by winterJIE** [comment]
<Submenu name="companies">
    <template slot="title">
        <Icon type="briefcase" />
        Links
    </template>
   <router-link to="/link-1">
      <iMenuItem name="all-companies">
            Link1
       </iMenuItem>
    </router-link>
</Submenu>


like this can solve your problem ?

**Comment by BinotaLIU** [comment]
@winterJIE 
This is not a standard html, also most people write code like this.  
`<Submenu>` generate an `ul` element. According to the html standard, `<ul>` should contain neither `<ul>`, `<ol>` nor `<li>` as it's direct child node.  
  
Let's explain in css selector:  
```css
ul > li, ul > ul, ul > ol
```
is a valid structure,  
``` css
ul > a > li
```
is invalid.

**Comment by winterJIE** [comment]
@BinotaLIU   may be iview will support it.  even if i use router-link wrapper menu-item  cause bug as it   https://github.com/iview/iview/issues/3638

**Comment by lc-c** [comment]
```vue
<Menu :active-name="$route.name" theme="dark" width="auto"  @on-select="select">
    <MenuItem name="seller">
        <Icon type="ios-navigate"></Icon>
        <span>首页</span>
    </MenuItem>
    <MenuItem name="sellerRecruit">
        <Icon type="settings"></Icon>
        <span>订单管理</span>
    </MenuItem>
    <Submenu name="3">
        <template slot="title">
            <Icon type="ios-navigate"></Icon>
            <span>商品管理</span>
        </template>
        <MenuItem name="sellerGoods">商品列表</MenuItem>
        <MenuItem name="sellerAddGoods">添加商品</MenuItem>
    </Submenu>
<Menu>


export default {
  methods: {
    select(name) {
        console.log(name);
        this.$router.push({ name });
    },
  }


```

**Comment by calvintwr** [comment]
I got to this thread because I couldn't have the menu highlight the correct navigation item when accessing the page directly using the URL. I.e. When I navigate to some other pages by clicking the navigation, it works, until I refresh the page (or access the page directly via URL), then whichever menu item gets highlighted depends on what the `active-name` value is, which is not a desired behaviours.

I have 2 points:

1) I think in the answer above, there might not be a need for the code to include the #select method. Not sure what it does but `$route.name` already provides the current page name when using the `:to` property as follows:

```
<Menu :active-name="$route.name">
    <MenuItem class="menuItem" name="SomePageName" :to="{name: 'SomePageName'}"
        SomePageName
    </MenuItem>
</Menu>
```


2) Can we include this into the documentation? By default, anyone who is using the iview navigation menu is gonna be using it with vuejs routing. The examples should include one that describes how to use it in a practical vuejs set up.
