### ISSUE TITLE
Table 组件 slot 样式问题无效

### ISSUE THREAD

**Issue by shunchuan** [iview/iview#3495]
iView 版本号
2.8.0

操作系统/浏览器 版本号
Chrome 66.0

Vue 版本号
2.5.13

复现步骤
表标题和固定列同时使用时会导致固定列样式错误

能够复现问题的在线示例（重要）
使用固定列的示例： https://jsfiddle.net/p4o3tzkm/1/  
不使用固定列正常的示例：  https://jsfiddle.net/p4o3tzkm/

问题现象，以及你期望的结果是怎样的?

你估计可能的原因是什么（选填）？
固定列的样式使用绝对位置进行定位
![image](https://user-images.githubusercontent.com/28803269/39283017-a8f3b9f6-493e-11e8-8d03-4d3948d0e791.png)

**Comment by David-Tsui** [comment]
確實是bug，match issue requirements後重發吧
