### ISSUE TITLE
[Bug Report] about the default value of select selectors in Modal components


### ISSUE THREAD

**Issue by kylesean** [iview/iview#3504]
### Environment
win10/chrome 62.0.3202.89 / Vue2.1

### Reproduction link
[https://jsfiddle.net/oaLdbw4y/10/](https://jsfiddle.net/oaLdbw4y/10/)

### Steps to reproduce
1、已渲染好的列表
2、对其中一条数据进行编辑操作
3、编辑操作在加载出的Modal里进行，但是无法获取默认值

### What is expected?
期望编辑操作在select选择器的远程搜索的情况下能获取默认值

### What is actually happening?
无法获取默认值。但是其他的选择器有默认值，去除该远程搜索选择器，单独 `<div>{{变量}}<div>` 能获取到值

---
用于更新数据的操作，但是数据再Modal里嵌套的form里操作，并不是单独打开的页面

**Comment by zhousicong** [comment]
has this issue been fixed?
