### ISSUE TITLE
TimePicker time selector under [Bug Report]IE browser, component exception when pulling scroll bar


### ISSUE THREAD

**Issue by PanHywel** [iview/iview#3509]
### Environment
windows 10 IE11

### Reproduction link
[https://www.iviewui.com/components/time-picker](https://www.iviewui.com/components/time-picker)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/13009686/39354980-7e0f690a-4a3e-11e8-9a67-44fcac90ae8f.png)
在IE浏览器下打开TimePicker时间选择器，并且拖动滚动条下拉选择时间，发现组件会隐藏。

### What is expected?
拖动滚动条后，组件不隐藏

### What is actually happening?
拖动滚动条后，组件会隐藏

**Comment by David-Tsui** [comment]
dulplicate
#3432
