### ISSUE TITLE
[Feature Request] <Select> should support boolean type

### ISSUE THREAD

**Issue by BinotaLIU** [iview/iview#3522]
### What problem does this feature solve?
`<Select>` is now doing a type check, the value need to be either a String, Number, or an Array.  
Sometimes we need to pass a Boolean value. I know that for Boolean value it is better to use checkbox. But `<Select>` provided a better user interface and user experience.  

### What does the proposed API look like?
`<Select>` should support bind Boolean type value.

**Comment by icarusion** [comment]
Select does not apply to Boolean types, you should use Checkbox, Radio, Switch components.
