### ISSUE TITLE
建议Modal对话框on-ok事件的回调方法允许阻塞关闭

### ISSUE THREAD

**Issue by KevinGZ2017** [iview/iview#353]
### iView 版本号
0.9.17

### 操作系统/浏览器 版本号
macOS/Chrome 54

### Vue 版本号
1.0.26

### 问题现象，以及你期望的结果是怎样的?
1.现有Modal对话框组件在点击确定按钮触发回调方法的时候，当方法内不满足某种校验规则的时候无法阻塞关闭Modal对话框
2.通过配置loading=true属性时来阻塞关闭Modal对话框时，确定按钮被锁定，无法再次触发确定按钮的回调函数

**Comment by icarusion** [comment]
可以自定义 footer 的 slot

**Comment by FinchJohnRen** [comment]
> 可以自定义 footer 的 slot

自定义中 render 只能渲染content 部分 不能改变 header 跟footer 内容 所以没有解决办法
