### ISSUE TITLE
When [Bug Report]Tootip slot sets white-space: normal style, it displays for the first time, and the position calculation is incorrect.


### ISSUE THREAD

**Issue by insertSweat** [iview/iview#3549]
### Environment
Macos 10.12.4 (16E195) / Chrome 65.0.3325.181 / Vue 2.5.2 / iview v2.13.1

### Reproduction link
[https://jsfiddle.net/zhaolin/Lbsfne41/](https://jsfiddle.net/zhaolin/Lbsfne41/)

### Steps to reproduce
父元素设置右浮动的时候，给Tootip slot 设置 white-space: normal 样式，初次显示位置不正确，后面再显示就正确

### What is expected?
初次显示位置正常

### What is actually happening?
初次显示位置不正常

**Comment by icarusion** [comment]
Set a `width` to slot.
