### ISSUE TITLE
[Feature Request]How to use dynamic data for expand table

### ISSUE THREAD

**Issue by magixyu** [iview/iview#3555]
### What problem does this feature solve?
I would like to use the below functions:
1. Click the table expand button
2. Send restful request to remote server
3. use the result to render the expanded table.

### What does the proposed API look like?
This is a question.

**Comment by Qsnh** [comment]
u can use `Table` component.And u should bind a event on table expand button,in this button,u can request api to get data,u can render the api data when u get remote data.

**Comment by David-Tsui** [comment]
on-expand, read doc.

**Comment by magixyu** [comment]
Thanks for reply. 
@Qsnh I can get the data but I don't know how to get the data displayed.
@David-Tsui I didn't find any information for the dynamic data for expanded table. Can you provide the link?

**Comment by David-Tsui** [comment]
What you want is your business logic, it may be a feature to be fulfill or not(such demand differs to many developers).
With handling **on-expand** event, you can send your request, row data of table can be updated.
