### ISSUE TITLE
[Bug Report]Tooltip content cant't wrap automaticlly.

### ISSUE THREAD

**Issue by majorcool** [iview/iview#3558]
### Environment
mac osx/chrome66/vue2.0

### Reproduction link
[http://jsbin.com/zeyiror/edit?html,output](http://jsbin.com/zeyiror/edit?html,output)

### Steps to reproduce
Open the jsbin link and hover on the text.

### What is expected?
When the content has too many words, the tooltip content can wrap automaticlly.

### What is actually happening?
When the content has too many words,  the tooltip content don't wrap.

**Comment by David-Tsui** [comment]
Hey bro, this is not a bug. You don't even read the doc.
https://www.iviewui.com/components/tooltip
