### ISSUE TITLE
[Bug Report]Do not click the Reproduction link in Issue preview modal of Issue Helper page, and if you do, then you lost everything you edit.

### ISSUE THREAD

**Issue by majorcool** [iview/iview#3559]
### Environment
mac osx/chrome 66/vue2.0

### Reproduction link
[https://www.iviewui.com/new-issue](https://www.iviewui.com/new-issue)

### Steps to reproduce
1. open https://www.iviewui.com/new-issue
2. write every form item in the page
3. then click the preview button in the bottom of the page
4. then click Reproduction link in the opened modal
5. then go back to the new issue page

### What is expected?
Open a new tab when users click Reproduction link in the preview modal.

### What is actually happening?
I lost everything I edit before, which spent me lots of efforts.

---
It's annoying, frustrating and disappointing that you lost everything when you do some preview after filling out the new issue form.

**Comment by icarusion** [comment]
No history saved, If possible, welcome to https://github.com/iview/iview-doc to contribute code.
