### ISSUE TITLE
[Feature Request] Font Icon extension


### ISSUE THREAD

**Issue by h-wanli** [iview/iview#3568]
### What problem does this feature solve?
公司有很多自定义的字体图标,自带字体图标不够用,希望开一个字体图标扩展的接口,谢谢

### What does the proposed API look like?
可以加两套字体图标文件或者可以直接有办法直接增加新的字体图标,谢谢

**Comment by h-wanli** [comment]
@iview-bot  亲  这个会做扩展吗?会的话我就等一下,如果不会做扩展的话,我就把整套字体图标换成阿里那个图标库,麻烦了,谢谢

**Comment by blackcater** [comment]
I think you can implement a `<Icon>` component for your own font icon.

**Comment by myxingke** [comment]
刚没看 我也提交了个这方便面的要求！我也希望能自定义图标，我通过代码改了能自定义，但我更新每次都要这样，那就很麻烦了！

**Comment by h-wanli** [comment]
@myxingke  你是怎么改的,是自己写的组件还是直接在svg和字体图标上面做的修改?不知道这个自定义要多久可以更新出来   我准备换成阿里的字体库,那个可以自定义

**Comment by myxingke** [comment]
@h-wanli  这个是我提交的issues
https://github.com/iview/iview/issues/3608

修改的源代码 自己加了一个props 调用的时候多个参数而已 很方便！但更希望官方改进，不然升级个版本我就要去打包 麻烦！

**Comment by h-wanli** [comment]
@iview-bot   亲  可以提供字体图标的svg文件吗(文件命名和字体图标名字相同的),从开源的那上面下载的svg名字和字体图标名字不对应,一个个改名字太慢了,还容易出错,谢谢了。
