### ISSUE TITLE
[Feature Request]'s default expand on tree


### ISSUE THREAD

**Issue by pengxuyang** [iview/iview#3569]
### What problem does this feature solve?
tree 控件默认展开所有子节点

### What does the proposed API look like?
需求为一个权限树，所以希望默认展开全部。但是目前的api中只能在children中设置，这样带来了一个不便是 要么后台人员给的数据中包含该属性，要么前端人员拿到数据后遍历添加expand:tree。myabe add 'default_expand' to 'Tree props' is a good idea.

**Comment by icarusion** [comment]
No such plane

**Comment by pengxuyang** [comment]
plan？
