### ISSUE TITLE
[Feature Request]Add the img element to the table component. If the image fails to load, how will the default image be added?

### ISSUE THREAD

**Issue by flowerGu** [iview/iview#3571]
### What problem does this feature solve?
Add the img element to the table component. If the image fails to load, how will the default image be added?table 组件中添加img元素，如果图片加载失败(图片加载失败时，src也是有值的)， 添加默认图片如何实现

### What does the proposed API look like?
on属性中添加error事件中的this指向为null

**Comment by sskaps** [comment]
src中添加判断赋值就行了
