### ISSUE TITLE
When [Bug Report]Select component changes Opions, if Opions number remains unchanged, Select will display problems and can not switch.


### ISSUE THREAD

**Issue by QJX** [iview/iview#3574]
### Environment
all

### Reproduction link
[https://jsfiddle.net/yyrzhm46/813/](https://jsfiddle.net/yyrzhm46/813/)

### Steps to reproduce
点击click按钮后，点下拉框

### What is expected?
下拉列表数据变了，可以正常切换

### What is actually happening?
下拉数据是变了，但是无法切换选项

**Comment by QJX** [comment]
查看源码，原因是options个数不变的情况，不会触发append或remove事件就不会调用debouncedAppendRemove函数

**Comment by QJX** [comment]
如果自己去调debouncedAppendRemove是可以，但是如果select的filterable为true也会有问题

**Comment by icarusion** [comment]
Fixed in next version.

**Comment by songmz2012** [comment]
更新到2.14.0后依然有问题
那个demo上  假如potion的value没变化  只是显示的文案变化的话  下拉时候是有问题的 选择一个option后对应显示的文本还是数据改变前的文本  并不是最新的文本  
new Vue({
  el: '#app',
  data: {
    value: '0',
    options: [['0', 'XXX'], ['1', 'YYY']]
  },
  methods: {
    changeOptions () {
      this.value = '0'
			this.options = [['0', 'AAA'], ['1', 'BBB']]
    }
  }
});

可以拿这一段试一下
