### ISSUE TITLE
[Bug Report]AutoComplete:scrollbar does not work

### ISSUE THREAD

**Issue by zhao-yanan** [iview/iview#3590]
### Environment
Google Chrome 63.0.3239.84

### Reproduction link
[https://www.iviewui.com/components/auto-complete](https://www.iviewui.com/components/auto-complete)

### Steps to reproduce
 Input a long string in the first example in order to show the scrollbar, but when you click this scrollbar, the select-dropdown will disappear， the scrollbar does not work.

### What is expected?
when click the scrollbar, the select-dropdown does not disappear，in order to see the whole message.

### What is actually happening?
 when you click this scrollbar, the select-dropdown will disappear， the scrollbar does not work.

**Comment by icarusion** [comment]
fixed in next version.
