### ISSUE TITLE
[Feature Request]AutoComplete:How to disable the placement by itself

### ISSUE THREAD

**Issue by zhao-yanan** [iview/iview#3591]
### What problem does this feature solve?
Sometime the user want to fix the select-dropdown‘s position, now it cant be fixed. 

### What does the proposed API look like?
placement can provide an optional value: auto

**Comment by icarusion** [comment]
You can set `placement` to `top` or `bottom`, but when the position you set can not display, it will open in another position automatically, it's a feature.
