### ISSUE TITLE
[Feature Request]In the filterable mode of Select component, don't want to click the component defaults to select all content, but can set the focus or select

### ISSUE THREAD

**Issue by klhsb** [iview/iview#3592]
### What problem does this feature solve?
Select组件在filterable模式下，如果单击组件，会选中全部内容；但有时业务需求是不希望全选的。
源码是使用了input标签的select()，代码如下：
```javascript
if (!this.autoComplete) this.$refs.input.select();
```
![qq 20180510101056](https://user-images.githubusercontent.com/24764414/39848664-d00dc444-543a-11e8-8dab-5a040f2cc509.png)

### What does the proposed API look like?
Select组件在filterable模式下，能自定义：单击组件时，是选中全部内容，还是不全选内容。

**Comment by icarusion** [comment]
下个版本已重构 Select ，并默认取消了这种特性。
