### ISSUE TITLE
After [Bug Report]Row sets gutter, the Row setting of the inner layer fails gutter.


### ISSUE THREAD

**Issue by qbrao** [iview/iview#3596]
### Environment
win10/chrome/vue2

### Reproduction link
[https://jsfiddle.net/qbrao/4wek769z/](https://jsfiddle.net/qbrao/4wek769z/)

### Steps to reproduce
1.被嵌套得Row无法设置gutte。列会继承父级的gutter
2. Col内没有东西时候，宽度为0。

### What is expected?
1.期望子Row能设置gutter
2.期望宽度为正常的比例。给col设置一个最小宽度为1px，可以解决这个问题。

### What is actually happening?
1.子Row继承父级的gutter
2.Col内没有东西时候，宽度为0。

**Comment by lIronGirl** [comment]
一开始用的是2.13.1的版本，升级到最新版本后gutter不生效，只能回退到2.13.1版本。请问升级后是需要对这部分做什么特殊处理么？报错 undefined is not a function
