### ISSUE TITLE
Documentation in English

### ISSUE THREAD

**Issue by vinicius73** [iview/iview#36]
Every day we meet very interesting packages for Vue.js
It is natural they are of Asiatic origin, this would be no problem if the documents were in English.

A code and documentation in English, in addition to making it more accessible for use makes it more accessible for contributions.

This helps the package and vue.js that is replaced by a large ecosystem.

**Comment by alexsandro-xpt** [comment]
+1

**Comment by rildomoraes** [comment]
+1

**Comment by icarusion** [comment]
We hope that after the release of 1.0, we can continue to translate into English
