### ISSUE TITLE
我准备在弹窗中做走马灯效果，但是失败了。

### ISSUE THREAD

**Issue by kuteng** [iview/iview#360]
### 复现步骤
我准备在弹窗中做走马灯效果，但是失败了。
### 你估计可能的原因是什么（选填）？
在弹窗隐藏时，加载了“走马灯”，但是那时候因为“弹窗”为“display: none;”的状态，所以计算出来的走马灯width为0px.

**Comment by icarusion** [comment]
Try v-if in Modal's slot
