### ISSUE TITLE
添加ExtractTextPlugin 后 报This dependency was not found:

### ISSUE THREAD

**Issue by wslw** [iview/iview#3600]
我使用vue-cli2.9.1搭建 iview, 在webpack.base.conf.js 添加
`{
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
            use: ['css-loader?minimize', 'autoprefixer-loader'],
            fallback: 'style-loader'
        })
}`
webpack.dev.conf.js 中添加
`new ExtractTextPlugin({
      filename: '[main].css',
      allChunks: true
    }),
`
在 main.js 中添加
`
import iView from 'iview'
import 'iview/dist/styles/iview.css'
Vue.use(iView)
`
启动项目的时候 控制台报
`
This dependency was not found:
* iview/dist/styles/iview.css in ./src/main.js
To install it, you can run: npm install --save iview/dist/styles/iview.css
`

请问 我应该如何解决?

**Comment by DRneilC** [comment]
> 我使用vue-cli2.9.1搭建 iview, 在webpack.base.conf.js 添加
> `{ test: /\.css$/, use: ExtractTextPlugin.extract({ use: ['css-loader?minimize', 'autoprefixer-loader'], fallback: 'style-loader' }) }`
> webpack.dev.conf.js 中添加
> `new ExtractTextPlugin({ filename: '[main].css', allChunks: true }), `
> 在 main.js 中添加
> `import iView from 'iview' import 'iview/dist/styles/iview.css' Vue.use(iView)`
> 启动项目的时候 控制台报
> `
> This dependency was not found:
> 
> * iview/dist/styles/iview.css in ./src/main.js
>   To install it, you can run: npm install --save iview/dist/styles/iview.css
>   `
> 
> 请问 我应该如何解决?

Have you fixed this?
