### ISSUE TITLE
[Bug Report]the button group failure while the button using tooltip

### ISSUE THREAD

**Issue by whwlxl** [iview/iview#3601]
### Environment
macOS10.13.4/chrome 66.0.3359.139 64bit/

### Reproduction link
[https://jsfiddle.net/MikeWay/q56ds51y/5/](https://jsfiddle.net/MikeWay/q56ds51y/2/)

### Steps to reproduce
open url https://jsfiddle.net/MikeWay/q56ds51y/5/ by chrome(66.0.3359.139) 64bit on macOS10.13.4

### What is expected?
fix this bug as soon as possible

### What is actually happening?
the buttons in button group looks like independent button while every button include a tooltip. in the button-group, if some buttons don't use tooltip, the buttons sequence is mistake.

---
we need create some controls-group through the button-group, but the control function is complex, so we want to use the tips description the detial for the control function while the mouse move on the button.

**Comment by icarusion** [comment]
Not supported temporarily
