### ISSUE TITLE
[Feature Request] Be able to change format of panel title in Datepicker when selecting a date

### ISSUE THREAD

**Issue by hgc2002** [iview/iview#3606]
### What problem does this feature solve?
Currently the panel title only allows this kind of texts: 2018年 5月
DatePicker accepts a format but only for the output of the component. What about the title panel?
Why can't we simply put something like 'MM/yyyy' for this? Same thing for the weekday names. 
It could also be a function so we can do lot more interesting things on this.

![imagen](https://user-images.githubusercontent.com/364190/39966378-06b03eb0-56ab-11e8-82a0-c8acda7a0642.png)

Currently the only option available is to use locale in main.js like:
```
import locale from 'iview/dist/locale/en-US'
Vue.use(iView, { locale });
```
### What does the proposed API look like?
format-panel-title
format-weekday-title

**Comment by icarusion** [comment]
No such plane.
