### ISSUE TITLE
HtmlWebpackPlugin 报错

### ISSUE THREAD

**Issue by ckryo** [iview/iview#361]
使用 iview-cli 脚手架搭建项目后， 运行npm run build 报错；
![image](https://cloud.githubusercontent.com/assets/10364500/23742509/0bf28cea-04e8-11e7-94c9-f6616425114f.png)
搜索了很久。不知道什么问题，最后试着在
![image](https://cloud.githubusercontent.com/assets/10364500/23742544/34c12eec-04e8-11e7-8ef4-f813f6d8216c.png)
此处添加了ejs之后。可以编译了。但是编译的文件中
`
htmlWebpackPlugin.files
`
相关的代码无法别编译。全部已原样显示出来了。
请问怎么解决。新手请多指导一下。
（我现在暂时没用hash，虽然不影响对iview的学习和使用，但是我还是想请教大神帮我解答一下学习过程中的困惑）

**Comment by icarusion** [comment]
这里是 iView，请到 iView Cli 提相关问题

**Comment by ckryo** [comment]
iview-cli有人回复吗？
