### ISSUE TITLE
The [Bug Report]Table component transfers an empty array to the data attribute, and the width of the table will be very wide.


### ISSUE THREAD

**Issue by magic373** [iview/iview#3637]
### Environment
win10

### Reproduction link
[http://null.com](http://null.com)

### Steps to reproduce
Table组件 给data属性传一个空数组,表格的宽度就会非常宽
(主要是想实现没内容也会显示表头的内容）

### What is expected?
没内容也有表头啊

### What is actually happening?
无表头，而且宽度巨大！

**Comment by AC-YoY** [comment]
I got this problem too, the attribute 'width' of props 'columns' should be Number, not String

demo here:
https://jsfiddle.net/yyrzhm46/940/
