### ISSUE TITLE
[Bug Report]slider  bug

### ISSUE THREAD

**Issue by Young6-me** [iview/iview#3649]
### Environment
chrome

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
清除slider右边input的值

### What is expected?
slider 可以继续使用

### What is actually happening?
slider 无法使用，且出现报错

---
使用有 输入框的  slider时，清除输入框的值，导致slider无法使用。 （console error：Error in event handler for "on-change": "TypeError: Cannot read property 'toFixed' of null"）

**Comment by LIUYANG132315** [comment]
?

**Comment by SergioCrisostomo** [comment]
@LIUYANG132315 your jsFiddle was empty, please update with a correct example.
