### ISSUE TITLE
iView 已支持 Vue.js 2.x

### ISSUE THREAD

**Issue by icarusion** [iview/iview#365]
目前已发布至 npm，2.0 文档还需一段时间，可以结合下面的日志线索和源码的 examples 来使用。

### Button
需使用 @click.native
### Input
使用 v-model，增加 on-input-change // todo 考虑更名
### RadioGroup
使用 v-model
### Radio
value 改为了 label，使用 v-model，废弃 checked
### Checkbox
使用 v-model
### CheckboxGroup
value 改为了 label，使用 v-model，废弃 checked
### Switch
废弃checked， 改为了 value，使用 v-model
### Badge
class 改为了 className
### InputNumber
使用 v-model
### Progress (名称有警告)
新增 on-status-change 事件
### Upload 
父级不能 computed Upload 的 fileList 了
### Collapse
废弃 activeKey，使用 v-model，key 是保留的，更名为 name
### Carousel
废弃 activeIndex，使用 v-model，v-for="n in slides.length",Vue2的数字循环，是从1开始的
### Tree
废弃 data，改为 value，使用 v-model，key 更名为 name，不能再 template 的prop 上使用 this
### Circle
改名为 iCircle
### Tabs
废弃 activeKey，改用 value，使用 v-model，key 更名为 name
### Slider
支持 v-model
### Dropdown
DropdownItem key 改为 name, Dropdown 的 visible 要使用 @on-visible-change 捕获，不再 sync
DropdownItem 里，this.$parent.$parent 与1.0 有区别
### Menu
MenuItem 和 Submenu 的 key 改为了 name
Menu 的 activeKey 改为 activeName,openKeys 改为 openNames
### Cascader
Caspanel 的 sublist 从 prop -> data
### Select
model 改为 value，支持 v-model
### Page
class 改为 className
### DatePicker
使用 v-model
### LoadingBar
部分 prop 移至 data
### Modal
visible 改为 value，使用 v-model，style 改为 styles，$Modal 的关闭有改动，建议后面在纯 html 模式下测试
### Table
i-table 改为 Table，目前单元格渲染自定义组件还有部分 bug
### Message
notice.vue 的 key 改为了 name，style 改为 styles
notification.vue 的 key 改为了 name，style 改为 styles

**Comment by xqbumu** [comment]
Table

i-table 改为 Table，目前单元格渲染自定义组件还有部分 bug

https://github.com/iview/iview/blob/2.0/src/components/table/cell.vue#L55

当方法返回的template里有router-link时，无法渲染，目前感觉action栏目里的只能放按钮，做点击事件，通过router-link生成的路由跳转暂时没法用。

**Comment by fliu2476** [comment]
太棒了，过段时间用起来，感谢！

**Comment by greyhu** [comment]
对应的CSS没有发布。只能从源码打包？

**Comment by icarusion** [comment]
@greyhu 看文档怎么使用css

**Comment by vanishcode** [comment]
npm安装的iview里的iview.js源码里有Component.options.__file = "/Users/aresn/develop/iview/src/components/icon/icon.vue"
请问是否有影响？

**Comment by arzcl** [comment]
再成熟点，就应用到项目去了，加油

**Comment by Mrlilili** [comment]
2.0 的  Switch组件不能使用，添加组件无效果
···
   <Switch size="large"></Switch>
···

**Comment by hefengxian** [comment]
@Mrlilili 我看一下源码`src/index.js`，是调用方式改了，源码如下
```js
const iview = {
    ...,
    iSwitch: Switch,
   ...
};
```
所以应该用如下的方式调用
```html
<i-switch :value="true">
    <span slot="open">开启</span>
    <span slot="close">关闭</span>
</i-switch>
```
