### ISSUE TITLE
[反馈/官网/样式]官网右侧目录展开被 div.example-code-more:after 的 box-shadow 遮挡

### ISSUE THREAD

**Issue by JayceZhang9602** [iview/iview#366]
### 操作系统/浏览器 版本号
macOS/Chrome 54

### 能够复现问题的在线示例
https://www.iviewui.com/components/grid

### 复现步骤
进入任何同时包含“代码示例”以及"右侧悬浮目录按钮"的页面，页面滚动到示例代码位置时，鼠标 hover 右侧悬浮"目录"按钮使其展开，可以看到部分文字被遮挡。

### 问题现象，以及你期望的结果是怎样的?
现象如图片所示
<img width="279" alt="screen shot 2017-03-10 at 11 33 10 am" src="https://cloud.githubusercontent.com/assets/20334140/23781171/5f0021c4-0586-11e7-9c9e-8dda721227f2.png">

### 你估计可能的原因是什么（选填）？
.example-code-more:after 元素的 z-index 值为1，展开目录 div.catalogue 的 z-index 值未设置
```
.example-code-more:after {
    content: '';
    width: 100%;
    height: 100%;
    position: absolute;
    bottom: 0;
    left: 0;
    z-index: 1;
    box-shadow: inset 0 -15px 30px #fff;
}
```

**Comment by lcx960324** [comment]
Already fixed on commit 0b8b0dd in iview/iview-doc. @icarusion
