### ISSUE TITLE
[Bug Report]Tabs error

### ISSUE THREAD

**Issue by isenlover** [iview/iview#3660]
### Environment
mac/chrome66/2.15

### Reproduction link
[https://jsfiddle.net/yyrzhm46/842/](https://jsfiddle.net/yyrzhm46/842/)

### Steps to reproduce
iview tabpanel's set html children all dispaly:none
so active any tab,no content show

i read source in iview tabs component,found this code【line 250】:

`setTimeout(() => {[...el.children].forEach(child => child.style.display = 'none');}, transitionTime);`

i think it's some problem

### What is expected?
active tab show html content not only text

### What is actually happening?
active tab no html content because iview Tabs set html style "display:none"

---
这应该是一个tab标签激活bug，当激活某个tab后 没有把内容display:none 关掉

**Comment by David-Tsui** [comment]
Please check again.

**Comment by SergioCrisostomo** [comment]
@isenlover We have been doing changes to Tabs for the 2.14 release. It does not have `display: none;` anymore. Please test again and reopen if you still have a problem.

Cheers!

**Comment by isenlover** [comment]
ok i will test in v2.15 future
