### ISSUE TITLE
How does [Feature Request] load iView correctly in Nuxt.js?


### ISSUE THREAD

**Issue by warriorBrian** [iview/iview#3661]
### What problem does this feature solve?
我在官网并没有发现iview在nuxt.js中按需加载的使用方法，请提供下nuxt按需加载组件的方法。谢谢

### What does the proposed API look like?
期望能提供nuxt.js中按需加载组件的方法

**Comment by icarusion** [comment]
这需要你去查看 Nuxt.js 的相关文档。

**Comment by ringgoyao** [comment]
你好，这个问题怎么解决的?@warriorBrian

**Comment by YuArtian** [comment]
iview现在应该是还不支持nuxt的按需加载吧

**Comment by GalinaGao123** [comment]
请问这个问题，有哪位大哥解决了吗 @warriorBrian  @ringgoyao
