### ISSUE TITLE
iView 的组件更名与 Input,  Slider 使用异常

### ISSUE THREAD

**Issue by yunfengsay** [iview/iview#367]
![image](https://cloud.githubusercontent.com/assets/15527378/23784650/368f6e44-059e-11e7-8650-0742fab8176a.png)

在使用slider的时候触发的
复制的官网的代码
https://www.iviewui.com/components/form

还有Input输入框 得不到输入的值
![image](https://cloud.githubusercontent.com/assets/15527378/23784720/8474fb06-059e-11e7-830a-02caf4fb1ecb.png)

还有  i-table 改成了Table   i-input 改成了 Input   
请问哪里能看到2.0的文档呢

**Comment by icarusion** [comment]
提供下代码

**Comment by yunfengsay** [comment]
使用的官网的代码，这是链接

https://www.iviewui.com/components/form

![image](https://cloud.githubusercontent.com/assets/15527378/23785014/69c63174-05a0-11e7-85d8-37b14a40967b.png)

**Comment by icarusion** [comment]
升级到 2.0，很多 API 都变了，查看release

**Comment by WLyKan** [comment]
入门都是看文档，结果文档是过时的，算不算挖坑了 😢

**Comment by ihuguowei** [comment]
现在文档跟进有计划吗？毕竟文档比 release log 更加直观，实例也比较丰富。

**Comment by WLyKan** [comment]
@ihuguowei 
  
release里有说明：

> 目前已发布至 npm，2.0 文档还需一段时间，可以结合下面的日志线索和源码的 examples 来使用。
