### ISSUE TITLE
[Bug Report]Modal-->Tabs-->Table

### ISSUE THREAD

**Issue by cbyniiaii** [iview/iview#3674]
### Environment
Mac

### Reproduction link
[https://jsfiddle.net/ms238nx1/#&togetherjs=C69v1sPC7w](https://jsfiddle.net/ms238nx1/#&togetherjs=C69v1sPC7w)

### Steps to reproduce
click show button

### What is expected?
The table is rendered correctly

### What is actually happening?
The table is not rendered correctly

**Comment by David-Tsui** [comment]
If you are trying to make a quick demo or prototype, then you should notice that "custom element tag" would not be properly parse as you think outside the webpack-loader environment.

Use **lowercase** with **hyphen** instead.
https://jsfiddle.net/du1fkL2q/1/

You can see more example in the docs.
