### ISSUE TITLE
[Bug Report]date-picker components will be reported wrong after using multiple multiple.


### ISSUE THREAD

**Issue by liyapengweb** [iview/iview#3675]
### Environment
Linux 4.13.0-38-generic/chrome  65.0.3325.181/vue 2.2.6

### Reproduction link
[https://jsfiddle.net/yyrzhm46/844/](https://jsfiddle.net/yyrzhm46/844/)

### Steps to reproduce
引用datePicker之后只要绑定v-model，一加载组件就会报错
![_070](https://user-images.githubusercontent.com/25002391/40401744-77691d3a-5e7a-11e8-9c04-a867770362c5.png)

### What is expected?
兼容下model数据类型

### What is actually happening?
虽然不影响功能，但是有报错也是不太好

**Comment by icarusion** [comment]
@SergioCrisostomo When set `v-model`, will throw error
