### ISSUE TITLE
[Bug Report]table component memory leak


### ISSUE THREAD

**Issue by marszoolong** [iview/iview#3677]
### Environment
win7,win10,vue 2.2.6

### Reproduction link
[https://www.iviewui.com/components/table](https://www.iviewui.com/components/table)

### Steps to reproduce
切换页面

### What is expected?
内存会被释放

### What is actually happening?
内存一直累加

---
我们的管理系统采用了iview组件库，用几个小时之后内存会达到 2G以上，经过追踪，发现组件库本身的table就有内存泄漏问题，但我们的系统没有部署在公网，所以没法提供重现链接，只能用iview的官网地址，官网也存在这样的问题

**Comment by Hishengs** [comment]
为什么要关闭这个bug呢？
经过测试，确实连官网本身也存在内存泄漏的问题。（不断切换页面会导致内存上升）
“explained in the documentation” 哪里的文档有解释，烦请告知一下好吗？
如果这个问题确实存在，是否能提供解决办法呢？？
不断地关闭 bug，确实会使得表面看起来很好看（似乎bug很少？）但有一些问题存在的话为什么也要关掉？

**Comment by deot** [comment]
#5357 官方确实在逃避这个问题
