### ISSUE TITLE
利用form 循环渲染列表，其中添加i-input元素报错

### ISSUE THREAD

**Issue by shangga** [iview/iview#369]
![image](https://cloud.githubusercontent.com/assets/14294555/23788063/e3da8b7c-05af-11e7-8a2b-b313baa66ff9.png)

在form中设置v-for ，其中嵌套了一个i-input，始终报错，请问是什么原因造成的呢？
![image](https://cloud.githubusercontent.com/assets/14294555/23788019/a587d622-05af-11e7-9d88-45d4522372b6.png)

**Comment by icarusion** [comment]
按要求提问
