### ISSUE TITLE
[Feature Request]Input and InputNumber can customize type properties


### ISSUE THREAD

**Issue by newpolymerization** [iview/iview#3693]
### What problem does this feature solve?
- Input
- InputNumber
- 两个组件均无法定义 HTML 中的 type 属性，此处造成在手机中无法根据 type 自动变更输入法的键盘，如将 input 的 type 设置为 tel 则可以直接调用数字键盘，在只输入数字的区域更加利于用户体验

### What does the proposed API look like?
```
<Input type='tel'  />
<InputNumber type='tel'  />
```

**Comment by icarusion** [comment]
No such plan
