### ISSUE TITLE
The select component in the iview has a very big problem in render mode in the table

### ISSUE THREAD

**Issue by PERSISTENC** [iview/iview#3697]
在vue项目中用vue-property-decorator插件开发时候  table中render模式使用了select组件  报错[Vue warn]: Error in getter for watcher "dropVisible": "TypeError: Cannot read property 'match' of undefined"
 导致select不能正常显示

**Comment by cys85** [comment]
同样的问题

**Comment by riyueweiyi** [comment]
同遇

**Comment by xiaohaiH** [comment]
请问有人解决了吗?

**Comment by xiaohaiH** [comment]
解决了, 我把生成 Option 的代码放到前面, 然后在遍历一遍, 挨个加上 tag...

**Comment by yinMrsir** [comment]
> 解决了, 我把生成 Option 的代码放到前面, 然后在遍历一遍, 挨个加上 tag...

能贴下代码吗？
