### ISSUE TITLE
<Menu>组件动态生成active、open默认值无效

### ISSUE THREAD

**Issue by waney** [iview/iview#370]
### iView 版本号
2.0.0-rc.2

### 操作系统/浏览器 版本号
Win10/Chrome 56

### Vue 版本号
2.2.2

### 问题现象，以及你期望的结果是怎样的?

通过ajax 从接口获取数据后生成动态菜单的时候遇到<Menu>组件属性( active-name open-names)无效。

`$data = [
      'active' => '/cache',
      'open' => ['/general'],
      'items' => [
        [
          'title' => '常规设置',
          'name' => '/general',
          'icon' => 'gear-b',
          'items' => [
            [
              'title' => '缓存设置',
              'name' => '/cache',
              'icon' => 'ios-keypad'
            ]
          ]
        ]
.....`

`<Menu active-name="menu.active" :open-names="menu.open" theme="dark" width="auto" @on-select="clickMenu">
        <div class="layout-logo-left">Logo</div>
        <template v-for="item in menu.items">
          <Menu-item :name="item.name" v-if="item.items.length < 1">
            <Icon :type="item.icon" :size="iconSize"></Icon>
            <span class="layout-text">{{ item.title }}</span>
          </Menu-item>
          <Submenu :name="item.name" v-else>
            <template slot="title">
              <Icon :type="item.icon"></Icon>
              {{ item.title }}
            </template>
            <template v-for="i in item.items">
              <Menu-item :name="i.name">{{ i.title }}</Menu-item>
            </template>
          </Submenu>
        </template>
      </Menu>`

### 你估计可能的原因是什么（选填）？
可能不能使用VUE#Template-v-for，但是不用<template v-for 又无法得到<Menu-item :name的属性
http://cn.vuejs.org/v2/guide/list.html#Template-v-for
求解！

**Comment by icarusion** [comment]
请给出能够复现问题的在线示例

**Comment by waney** [comment]
@icarusion 无法提供在线例子，就是设置菜单默认打开项无效。
没有任何报错，只是没有默认打开状态。
用图表示如下。
![-1](https://cloud.githubusercontent.com/assets/69211/23790032/52e53a96-05b8-11e7-83de-6e1985d65d1d.jpg)

**Comment by icarusion** [comment]
到jsbin、codepen提供在线示例

**Comment by waney** [comment]
在线示例：https://codepen.io/waney/pen/mWmROj 

@icarusion

**Comment by waney** [comment]
@icarusion 我不知道是我用错了还是怎么，我想实现的是动态获取菜单数组然后在页面上用Menu组件渲染出来。

**Comment by dreamstu** [comment]
https://codepen.io/anon/pen/KWyerq

**Comment by samblabla** [comment]
Menu-item 的 name 你传的是数字型的，active-name默认是字符串型的，你需要把 name 的值转成字符串类型的。
```
<a :href="'/'+url_root+v.url" v-for="(v, index) in menu">
    {{ index=index+'' }}
    <Menu-item :name="index" :key="v">
        <Icon :type="v.ico" v-if="v.ico"></Icon>
        {{ v.name }}
    </Menu-item>
</a>

```

**Comment by ckryo** [comment]
看来很多人都遇到了这个问题。我也是。求解

**Comment by ai116458960** [comment]
不知道解决的了没有 默认激活的问题

**Comment by ckryo** [comment]
动态添加的数据写在`created` 里面就好了。 Vue生命周期的问题，写在`mounted`中确实出不来。

**Comment by zplus** [comment]
同问默认激活的问题，没头绪

**Comment by A-PASSER-BY** [comment]
求解，动态生成的刷新后怎么展开？？

**Comment by Rudy24** [comment]
@ckryo   我的也是动态生成Menu，然后再设置active，open，接口请求是放在created里面，得出的值是有效的，不过Menu还是没有展开

组件---》
Menu :accordion="true" :theme="'dark'" :active-name="activeMenu" :open-names="openName" width="auto"
方法---》
created() {
//获取用户信息
this.getUserInfo();
this.activeMenu = this.getActiveMenu();
this.openName = this.getOpenName();
}

**Comment by abcdGJJ** [comment]
问题解决了吗

**Comment by qingzhoufeihu** [comment]
暂时的解决办法

![1](https://user-images.githubusercontent.com/26052806/38664380-fbaa0d4a-3e6b-11e8-8d09-ce4808b2ec3d.png)
![2](https://user-images.githubusercontent.com/26052806/38664385-fff8113a-3e6b-11e8-9b54-97ef267b5081.png)

**Comment by zx870283980** [comment]
楼上的解决方案也还是不行
