### ISSUE TITLE
[Bug Report]2.14.0 select displays value after setting up value


### ISSUE THREAD

**Issue by wtusmchen** [iview/iview#3705]
### Environment
iview 2.14.0

### Reproduction link
[https://jsfiddle.net/yyrzhm46/862/](https://jsfiddle.net/yyrzhm46/862/)

### Steps to reproduce
更新到2.14后下拉框无法设置选中值，显示undefined

### What is expected?
现在选中的item

### What is actually happening?
显示undefined

**Comment by icarusion** [comment]
@SergioCrisostomo Before version, the logic of `Option` label is:
> The content of the option, read slot default. If not have slot, it will show the `label`. If not have label, show the `value`. Mostly just write slot, but for cumtomized option, this is useful.

@wtusmchen you can set a slot to `Option` to fix now.

**Comment by aleksanderd** [comment]
some more notes...

1) Using the label without slot:
```
<i-option v-for="option in options" :key="option.id" :value="option.id" :label="option.title" />
```
will cause an error:
TypeError: option.componentOptions.children is undefined

2) Using option's slot for markup and attribute label for input's value(worked before) not working now - seems to be the slot's markup just copied to inputs value. label attribute is ignored if slot present? How can I provide different markup for render selected value?

**Comment by aleksanderd** [comment]
also, now remoteMethod called on option select :(
