### ISSUE TITLE
[Bug Report]select is not selected after setting up transfer


### ISSUE THREAD

**Issue by lihaomu** [iview/iview#3708]
### Environment
ivew2.14

### Reproduction link
[https://jsfiddle.net/pp1kao18/](https://jsfiddle.net/pp1kao18/)

### Steps to reproduce
点击每个选项都没用

### What is expected?
无

### What is actually happening?
无

**Comment by luffyzhao** [comment]
pls remove transfer attr

**Comment by leslieSie** [comment]
I guess your iView isn't latest. You should use git clone form official website or github.

**Comment by icarusion** [comment]
#3695
