### ISSUE TITLE
[Bug Report]AutoComplete  don't click other area when  it show

### ISSUE THREAD

**Issue by jianyiwuhen** [iview/iview#3709]
AutoComplete 当你显示出来下拉选项时，如果不选择其中的选项，不会自动隐藏下拉，并且不能点击其他区域，焦点也无法失去
![image](https://user-images.githubusercontent.com/4747106/40543015-254db240-6055-11e8-95d5-5891c4d6af7b.png)

**Comment by icarusion** [comment]
transition:
in AutoComplete, when open a dropdown panel, than click outside, the panel can not hide.

**Comment by zhao-yanan** [comment]
还有两个问题，（1）当显示出来下拉选项且选择了其中一项，这时输入框失去焦点，当此输入框再次获得焦点时，你选择之前选择的那项没有响应，输入框无法再次失去焦点；（2）在官方第二个示例中，选择其中一项后，输入框再次获得焦点时无法显示下拉选项

**Comment by icarusion** [comment]
@SergioCrisostomo I think the problem lies in this line
https://github.com/iview/iview/blob/427b869297e36780c062ebd9a5e6e672bffc4ac8/src/components/select/select.vue#L5

**Comment by huuhait** [comment]
bug no fix
so sad for project .-.

**Comment by wangwei-van** [comment]
bug still exists
