### ISSUE TITLE
<Menu>标签作为h5标签，被vue2忽略了，在页面中无法实例化

### ISSUE THREAD

**Issue by zdfsilence** [iview/iview#371]
![image](https://cloud.githubusercontent.com/assets/2252080/23791668/e1ecf1c4-05be-11e7-9328-c6c2a5bb0064.png)

如上图

**Comment by icarusion** [comment]
大写Menu

**Comment by zdfsilence** [comment]
*不好意思，没看到回复，以为没提交成功，又发了一遍。*

*我确实是大写的Menu*

2017-03-10 18:30 GMT+08:00 Aresn <notifications@github.com>:

**Comment by jingsam** [comment]
不要写在html里面，使用template选项或者自己重新注册下： Vue.component('i-menu', iview.Menu)
