### ISSUE TITLE
[Bug Report]AutoComplete don't click other area when it show

### ISSUE THREAD

**Issue by jianyiwuhen** [iview/iview#3710]
### Environment
mac /chrome/vue:lastest

### Reproduction link
[https://www.iviewui.com/components/auto-complete](https://www.iviewui.com/components/auto-complete)

### Steps to reproduce
随便输入，然后保持下拉，点击其他区域

### What is expected?
点击其他区域能隐藏下拉列表，并可点击其他区域

### What is actually happening?
AutoComplete 当你显示出来下拉选项时，如果不选择其中的选项，不会自动隐藏下拉，并且不能点击其他区域，焦点也无法失去

**Comment by ZhiYiDai** [comment]
我也是

**Comment by icarusion** [comment]
#3709
