### ISSUE TITLE
[Bug Report]iview 2.14.0 Select BUG! BUG! BUG!

### ISSUE THREAD

**Issue by nwtown** [iview/iview#3711]
### Environment
WIN10/chrome 65/  MAC/chrome 65  VUE 2.8.2

### Reproduction link
[HTTP://没有.com](HTTP://没有.com)

### Steps to reproduce
iview 2.14.0 升级后 Select value  String | Number 都出错, value="" 取不到数字. 2.13.0可以.  在表格里面使用, transfer属性加上后选择不了. 

### What is expected?
你说呢.

### What is actually happening?
降级使用.

**Comment by ZhiYiDai** [comment]
升级后我也选择不了  降级后也选择不了 不知道为啥

**Comment by ZhiYiDai** [comment]
https://jsfiddle.net/yyrzhm46/863/

**Comment by attacking** [comment]
重启可行
