### ISSUE TITLE
[Bug Report]possibly related issue when installing via npm

### ISSUE THREAD

**Issue by ducpvt1804** [iview/iview#3718]
### Environment
2.14.0

### Reproduction link
[https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz](https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz)

### Steps to reproduce
npm install iview --save

### What is expected?
200

### What is actually happening?
possibly related issue when installing via npm:
404 Not Found: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/40577251-1d3ad3a4-6135-11e8-9454-ff12ab7c4a3a.png)
