### ISSUE TITLE
[Bug Report]iview NPM can not download async-validator package can not be found


### ISSUE THREAD

**Issue by JaneScript** [iview/iview#3719]
### Environment
nodejs

### Reproduction link
[https://www.iviewui.com/cli](https://www.iviewui.com/cli)

### Steps to reproduce
npm i iview --save

### What is expected?
可以安装

### What is actually happening?
无法安装

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/40577245-0de4d472-6135-11e8-89b2-2482dd65dcf1.png)

**Comment by feidudu1** [comment]
run
```
npm install iview@2.14.0 --save-dev
```
it does not work

**Comment by feidudu1** [comment]
解决办法：
```
npm install https://github.com/yiminghe/async-validator/archive/1.8.2.tar.gz --save-dev
```
