### ISSUE TITLE
menu作为html5标签，被vue2.x过滤了

### ISSUE THREAD

**Issue by zdfsilence** [iview/iview#372]
### iView 版本号
2.0.0-rc.2

### 操作系统/浏览器 版本号
windows/Chrome 55

### Vue 版本号
2.2.2

### 问题现象

<Menu>标签直接写在页面中无法实例化

### 原因

menu作为html5标签，被vue2过滤了。

**Comment by icarusion** [comment]
目前要写在template里

**Comment by zdfsilence** [comment]
恩，这我知道，只是想反馈一下这个问题

2017-03-10 18:49 GMT+08:00 Aresn <notifications@github.com>:

**Comment by icarusion** [comment]
这个我们后面再考虑一下，实在不行所有组件都加前缀i-

**Comment by jingsam** [comment]
用Menu！

**Comment by icarusion** [comment]
它应该是写在 DOM 里的，不是在 template 里，这种情况好像会被过滤掉？

**Comment by jingsam** [comment]
不要写在 html 里面，使用 template 选项或者自己重新注册下： Vue.component('i-menu', iview.Menu)

PS: 都2017年了，为什么还要把模板写到DOM里面啊，DOM解析是最慢的

**Comment by emman47** [comment]
H

**Comment by zdfsilence** [comment]
目前项目小组全是后端，所以直接写在dom里是最简单的，这也是我为什么选iview的原因啊，目前基于vue的ui框架，除了iview别的都要写template里

**Comment by icarusion** [comment]
稍后更新的版本，会把不支持的元素加前缀
