### ISSUE TITLE
Asynchronous creation of [Bug Report]select filterable


### ISSUE THREAD

**Issue by NARUTOne** [iview/iview#3722]
### Environment
2.14.0

### Reproduction link
[https://jsfiddle.net/NARUTOne/a6pmgaf0/](https://jsfiddle.net/NARUTOne/a6pmgaf0/)

### Steps to reproduce
异步创建 设置默认选中选项

### What is expected?
期望bug解决，越来越好

### What is actually happening?
默认值添加不上

---
有时候，默认值提前知道进行赋值了，但是select是异步创建的；

**Comment by leslieSie** [comment]
老哥，这块不是什么Bug 是你对异步不熟悉而已

**Comment by NARUTOne** [comment]
@leslieSie  能简单说下吗？谢谢

**Comment by jackzhcai** [comment]
这个bug什么时候修复呀！

**Comment by august-9426** [comment]
修复了吗？我的(v2.14.3) 还是不行。 之前无论先设置值还是先设置option，都能正常显示label的，现在只能先设置option了？

**Comment by yaomingdan** [comment]
同问，目前只要异步的设置默认值都不显示。

**Comment by Gyyi** [comment]
3.1.1版本似乎还存在这个问题，异步option赋值后没有正确渲染已选项

**Comment by yaomingdan** [comment]
![image](https://user-images.githubusercontent.com/6559625/45865639-c2821980-bdb0-11e8-8d17-e2fd1c2ca122.png)
严格放置option和data的赋值顺序，option在data前就可以解决。

**Comment by nickrogit** [comment]
select加了filterable属性后，option动态ajax填充不成功。
