### ISSUE TITLE
Select component:set v-model value,  method '@on-change' will be implemented immediately

### ISSUE THREAD

**Issue by dean5277** [iview/iview#3725]
### Environment
chrome vue2.5.16

### Reproduction link
[https://jsfiddle.net/ec8tLgtg/](https://jsfiddle.net/ec8tLgtg/)

### Steps to reproduce
When i set ‘Select Component’ v-model value, the value is subset of option list, it immediately executes  @on-change method

### What is expected?
iview version 2.13.1 : Not immediately

### What is actually happening?
iview version 2.14.0:  Immediately

---
2.14.0 demo https://jsfiddle.net/ec8tLgtg/
2.13.1 demo https://jsfiddle.net/dtrnrphp/

**Comment by vidding** [comment]
This bug still exists in 2.14.3

**Comment by llccing** [comment]
@vidding , [https://jsfiddle.net/lcf33123/ec8tLgtg/18/](https://jsfiddle.net/lcf33123/ec8tLgtg/18/), i test it has fixed
