### ISSUE TITLE
[Bug Report]The width attribute in columns of Table originally supports string, percentage, and now it can only be digits.

### ISSUE THREAD

**Issue by Baoyx007** [iview/iview#3726]
### Environment
 mac/chrome/ vue 2.5.16

### Reproduction link
[https://jsfiddle.net/Baoyx007/agdd56x6/1/](https://jsfiddle.net/Baoyx007/agdd56x6/1/)

### Steps to reproduce
Table 的 columns 中的width 属性, 原来是支持 字符串, 百分比的, 现在只能用数字

### What is expected?
Table 的 columns 中的width 属支持 字符串, 百分比和数字

### What is actually happening?
Table 的 columns 中的width 现在只能用数字, 如果不是数字, 整个样式就完全错乱了

---

iview@2.12.0 还是支持的: https://jsfiddle.net/Baoyx007/agdd56x6/1/ , width 可以设置成50%

现在就不支持了: https://jsfiddle.net/Baoyx007/agdd56x6/2/

**Comment by icarusion** [comment]
不支持百分比。
