### ISSUE TITLE
When the BUG mouse of the [Bug Report]2.14.0 menu component passes through, multiple drop-down will occur at the same time.


### ISSUE THREAD

**Issue by DaDaDaDaDaBocai** [iview/iview#3733]
### Environment
win10/谷歌/Vue2.9.3

### Reproduction link
[https://jsfiddle.net/5dpahpaq/](https://jsfiddle.net/5dpahpaq/)

### Steps to reproduce
多个下拉菜单 就会复现

### What is expected?
每个菜单下拉每个菜单的内容

### What is actually happening?
一个菜单会触发另外菜单的下拉

**Comment by DaDaDaDaDaBocai** [comment]
此Bug 在 2.13.1的版本没有出现,更新到最新版出现的问题

**Comment by DaDaDaDaDaBocai** [comment]
复现步骤: 鼠标快速在菜单上移动 直到有一个菜单关不上以后  就会出现错乱了

**Comment by icarusion** [comment]
Caused by #3560
