### ISSUE TITLE
[Bug Report]使用iview-loader,在template中使用i-dropdown报错

### ISSUE THREAD

**Issue by zhangya5847** [iview/iview#3736]
### Environment
Mac／chrome／vue 2.5.16／iview 2.14.0/iview-loader 1.0.0

### Reproduction link
[https://www.iviewui.com/docs/guide/iview-loader](https://www.iviewui.com/docs/guide/iview-loader)

### Steps to reproduce
按照官方推荐安装iview-loader,使用i-dropdown报错,但是使用Dropdown没有报错
main.js
![image](https://user-images.githubusercontent.com/15855773/40610625-bc99fa76-62a5-11e8-91d3-90bfff9606e0.png)
webpack.base.conf.js
![image](https://user-images.githubusercontent.com/15855773/40610667-eae5fa42-62a5-11e8-869a-12306ea74d35.png)
logou.vue
![image](https://user-images.githubusercontent.com/15855773/40610704-0d826540-62a6-11e8-8d48-f2bd4202a7a9.png)

报错信息：

![image](https://user-images.githubusercontent.com/15855773/40611175-db13f590-62a7-11e8-8421-34d4a6967ecf.png)

### What is expected?
不使用iview-loader就可以直接使用

### What is actually happening?
实际在template中使用会报错

**Comment by webproblem** [comment]
这不是问题，在template模板中直接使用Dropdown就好了，非template模板中使用有些组件是需要添加'i-'前缀的，避免与原生的html标签冲突

**Comment by zhangya5847** [comment]
不是问题吗？有一个.vue文件的template模版中用了i-input没有报错，文档中也说明了使用iview-loader设置之后，就可以使用标签的前缀的写法，现在在template中不能使用i-dropdown，这不是问题？？？

**Comment by icarusion** [comment]
iview-loader 只支持默认 template 的写法，即 `<i-dropdown>`
