### ISSUE TITLE
This version of [Bug Report]2.14.0 KAMI will assign errors to select binding objects.


### ISSUE THREAD

**Issue by hr837** [iview/iview#3737]
### Environment
All

### Reproduction link
[https://jsfiddle.net/Duang/90r6ux6y/](https://jsfiddle.net/Duang/90r6ux6y/)

### Steps to reproduce
点击Button ，给select选择器赋值

### What is expected?
2.13.1就不报错

### What is actually happening?
vue会报错

**Comment by icarusion** [comment]
fixed
