### ISSUE TITLE
npm安装的iview源码是否有误？

### ISSUE THREAD

**Issue by vanishcode** [iview/iview#374]
npm安装的iview里的iview.js源码里有Component.options.__file = "/Users/aresn/develop/iview/src/components/icon/icon.vue"
请问是否是bug？
浏览器提示找不到模块（chrome dev，macOS）

**Comment by icarusion** [comment]
还真没注意这个，肯定是有问题的。

**Comment by icarusion** [comment]
@huixisheng

**Comment by vanishcode** [comment]
npm安装的会提示
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Boolean, got String. 
(found in <Radio> at /Users/aresn/develop/iview/src/components/radio/radio.vue)
iview.js里面option路径就是上面那个
好像自己build的没有问题

**Comment by vanishcode** [comment]
十分感谢！
