### ISSUE TITLE
[Bug Report]2.14.0 breaks ssr support

### ISSUE THREAD

**Issue by littlexiang** [iview/iview#3740]
### Environment
2.5.14

### Reproduction link
[https://github.com/iview/iview/search?p=1&q=window&unscoped_q=window](https://github.com/iview/iview/search?p=1&q=window&unscoped_q=window)

### Steps to reproduce
nuxt ssr build fail

### What is expected?
was ok with 2.13.x

### What is actually happening?
got undefined window error

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/4cccdf1fd56d56c576c2020368fa3957801a81e9

**Comment by icarusion** [comment]
Another problem rely on this framework and it will be repaired soon 
https://github.com/Xotic750/v-click-outside-x/issues/2

**Comment by yoyou** [comment]
how resolve question window is not defined ?
I try use `ssr: false` ，but appear other question。
` [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content.`

**Comment by icarusion** [comment]
wait for next version...

**Comment by heibaikn** [comment]
@icarusion  Is there a anther solution  now.

**Comment by icarusion** [comment]
@heibaikn Downgraded to 2.13.1

**Comment by SW-HPA-August** [comment]
Did it fixed?

**Comment by SW-HPA-August** [comment]
+1

**Comment by icarusion** [comment]
fixed

**Comment by westdrug** [comment]
+1
