### ISSUE TITLE
[Bug Report] super large BUG. Select component, you can't select dropdown on the phone


### ISSUE THREAD

**Issue by gudufy** [iview/iview#3741]
### Environment
win10/vue 2/chrome

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
在手机里浏览即可

### What is expected?
能正常选择下拉项

### What is actually happening?
选不了啊选不了

**Comment by gudufy** [comment]
这个链接要好操作些：https://fiddle.jshell.net/owpdc9rh/show/，在手机打开，或电脑浏览器的手机模式里都可以重现

**Comment by SergioCrisostomo** [comment]
@gudufy can you please test https://fiddle.jshell.net/owpdc9rh/1/show/ and tell me if that fixes the problem you reported?

**Comment by swellyang** [comment]
现在怎么样了这个超级大bug。。。，貌似是刚体出来啊？

**Comment by gudufy** [comment]
@SergioCrisostomo https://rawgit.com/SergioCrisostomo/version-files/master/iview-selectoption-touchend.js这个链接在中国无法访问，所以无法查看你提供的示例。

**Comment by gudufy** [comment]
@swellyang 经过测试。2.13.1版的iview没有这个问题

**Comment by icarusion** [comment]
@SergioCrisostomo it works
