### ISSUE TITLE
The latest version of [Bug Report] 2.14 is not available on iPad end select components.


### ISSUE THREAD

**Issue by WananPr1st** [iview/iview#3751]
### Environment
ipad/iview 2.14.1

### Reproduction link
[https://jsfiddle.net/yyrzhm46/870/](https://jsfiddle.net/yyrzhm46/870/)

### Steps to reproduce
iview升级到2.14 form表单引入Select组件  无法选中下拉列表的值

### What is expected?
正确切换下拉列表的值

### What is actually happening?
点击选项无反应

---
可在chrome 模拟ipad复现

**Comment by rousioncal** [comment]
在 select 组件里面添加 :transfer=true 复现

**Comment by icarusion** [comment]
#3741
