### ISSUE TITLE
[Bug Report] Select mouse click bug After update

### ISSUE THREAD

**Issue by ukhack** [iview/iview#3752]
### Environment
win10/chrome 66/vue 2.5.16

### Reproduction link
[https://jsfiddle.net/z8nspvz8/1/](https://jsfiddle.net/z8nspvz8/1/)

### Steps to reproduce
如链接所示，select选项中有label和一个浅灰色的描述。指定:label的情况下，点击选项。浅灰色内容会被置入input框。
通过键盘回车操作不会出现此问题。
这在2.13.1中是没有问题的。

### What is expected?
指定label后点击就只获取label

### What is actually happening?
结果是
slot中的所有文字被置入

**Comment by icarusion** [comment]
#3728
