### ISSUE TITLE
[Bug Report]AutoComplete：if you don't click option or click search icon, it can't hide its options panel automatically and also input box blur

### ISSUE THREAD

**Issue by cunjif** [iview/iview#3760]
### Environment
Windows 10.0.17134 / Chrome  66.0.3359.181(x64) / vue@2.5.16 / iview@2.14.0

### Reproduction link
[https://www.iviewui.com/components/auto-complete](https://www.iviewui.com/components/auto-complete)

### Steps to reproduce
1. 完全自定义Option示例中，先点击输入框，输入框获取输入焦点并且展示Option选项
2. 点击组件以外的浏览器显示区域

### What is expected?
在点击组件以外区域后，Option组件可以自动隐藏，同时输入框失去焦点

### What is actually happening?
组件无反应

---
在Form组件中嵌套了AutoComplete组件作为搜索补全

**Comment by icarusion** [comment]
#3709
