### ISSUE TITLE
[Bug Report]If the select value is 0, it does not come into effect

### ISSUE THREAD

**Issue by leixuesong** [iview/iview#3763]
### Environment
Windows/chrom/vue 2.5.16/iview2.14.0

### Reproduction link
[https://jsfiddle.net/raykaeso/03exvd65/](https://jsfiddle.net/raykaeso/03exvd65/)

### Steps to reproduce
Look at the URL

### What is expected?
London checked

### What is actually happening?
All unselected

**Comment by icarusion** [comment]
#3696

**Comment by leixuesong** [comment]
thanks
