### ISSUE TITLE
After [Bug Report]2.14.0 version select set transfer, no option can be selected.


### ISSUE THREAD

**Issue by attacking** [iview/iview#3765]
### Environment
macOS/chrome66/vue2.5.9

### Reproduction link
[https://codepen.io/yummy/pen/OOewJj](https://codepen.io/yummy/pen/OOewJj)

### Steps to reproduce
如重现链接中所示

### What is expected?
设置transfer属性后不影响功能

### What is actually happening?
无法选择

**Comment by icarusion** [comment]
#3695
