### ISSUE TITLE
[Bug Report]AutoComplete: when you trigger the list, you can't blur if you don't select options.

### ISSUE THREAD

**Issue by wusfen** [iview/iview#3770]
### Environment
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

### Reproduction link
[https://www.iviewui.com/components/auto-complete](https://www.iviewui.com/components/auto-complete)

### Steps to reproduce
1. 输入一个字符
2. 不选择选项，点击文本框外

### What is expected?
文本框取消焦点并隐藏列表

### What is actually happening?
点击文本框外无效果

**Comment by icarusion** [comment]
#3709
