### ISSUE TITLE
After adding elements in [Bug Report]modal slot header, the X clicks on the right do not respond.


### ISSUE THREAD

**Issue by xingzhefeng** [iview/iview#3771]
### Environment
win10,chrome 版本 65.0.3325.181（正式版本） （32 位） vue 2.5.16

### Reproduction link
[https://jsfiddle.net/32647908/05prmzsr/](https://jsfiddle.net/32647908/05prmzsr/)

### Steps to reproduce
上面的jsfiddle

### What is expected?
点击X按钮正确关闭

### What is actually happening?
没有关闭

**Comment by xingzhefeng** [comment]
没下文了吗

**Comment by daiyanze** [comment]
`<Row />`把header整行覆盖掉了，所以 X 按钮无法点击。可能是iView的Row在布局上有点局限性。你试试暂时用别的方式来布局。

**Comment by xingzhefeng** [comment]
非常感谢 直接把Row 去掉了. 里面的col 似乎和 Row 没有多大关系
