### ISSUE TITLE
[Bug Report]June is missing

### ISSUE THREAD

**Issue by parse-code** [iview/iview#3773]
### Environment
Just the demo site

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
Select a date range

### What is expected?
show this month left side and next month right side

### What is actually happening?
Today is 31 May, but the right side show July instead of june
![image](https://user-images.githubusercontent.com/350474/40767970-90d62b38-64e6-11e8-82c7-aec4ad3b7a41.png)

**Comment by David-Tsui** [comment]
邊緣June QQ

**Comment by liuleiweb** [comment]
果然...

**Comment by m430** [comment]
@icarusion I submitted a PR to fix this issue and test it. can u check it and merge it？

**Comment by icarusion** [comment]
@m430 Ok, will check

**Comment by yinyunpan** [comment]
@icarusion  
https://www.iviewui.com/components/date-picker
![image](https://user-images.githubusercontent.com/6118991/41634927-974ba76c-7478-11e8-8905-e00ddac09cb9.png)
![image](https://user-images.githubusercontent.com/6118991/41634944-a67f7894-7478-11e8-93e6-9072bd08b8c5.png)
最新版本v2.14.3里面，这个问题还是存在
31天月份，后面30天月份。

**Comment by icarusion** [comment]
When select date, the interval between the left and right panels has become 2 months,
the current month is 2018.5(left), 2018.6(right), now, the right is 2018.7

![image](https://user-images.githubusercontent.com/5370542/44317626-db6f7600-a464-11e8-9ca9-6f6829ec8813.png)

**Comment by yangdaichun** [comment]
这个问题在最新 的3.0.1 版本上依然存在

**Comment by SergioCrisostomo** [comment]
@yangdaichun can you provide a jsFiddle or other example of the problem?

**Comment by yangdaichun** [comment]
@SergioCrisostomo https://run.iviewui.com/mD4v1Qwe

**Comment by yangdaichun** [comment]
@SergioCrisostomo  刚看到你们的3.1.0的版本里面已经解决了这个bug
![image](https://user-images.githubusercontent.com/12042306/44906104-968dee00-ad46-11e8-8401-ed5385b17909.png)

**Comment by icarusion** [comment]
@yangdaichun https://dev.iviewui.com/articles/1035451247458652160 3.1.0 还没发布
