### ISSUE TITLE
[Feature Request] suggests that Radio components expose name properties to meet certain specific scenarios.


### ISSUE THREAD

**Issue by wy-Jay** [iview/iview#3779]
### What problem does this feature solve?
某些特定场景无法是用RadioGroup，同时处理数据也不够方便。比如在一个弹窗中的table，选中一列使用radio来实现。

### What does the proposed API look like?
<Radio name='XXX' />

**Comment by icarusion** [comment]
有 name

**Comment by wy-Jay** [comment]
![image](https://user-images.githubusercontent.com/13727203/40773164-a4b60de0-64f4-11e8-914b-afd0eeee5d25.png)
