### ISSUE TITLE
[Bug Report]Select remote search function, search option cache problem


### ISSUE THREAD

**Issue by wuchongzi** [iview/iview#3787]
### Environment
2.14.1

### Reproduction link
[https://jsfiddle.net/yyrzhm46/895/](https://jsfiddle.net/yyrzhm46/895/)

### Steps to reproduce
 1. 前提是select已有选中了一个值；
 2. 删除，然后重新输入搜索词，但是不做选择，点击空白，这时select的值还是步骤1的选中的值；
 3. 再次点击select时，这时下拉选项为上一步重新输入搜索词时的选项，需要触发输入才会重新搜索。

### What is expected?
在上面步骤的第3步，再次点击时应该展示的是选中值相关的选项，而不是第2步缓存的选项

### What is actually happening?
第3步的选项是第二步输入搜索词的缓存选项，需要触发一下输入才会重新搜索

**Comment by icarusion** [comment]
#3798
