### ISSUE TITLE
[Bug Report]When selecting components for multiple selections, if the fixed height is applied, the arrow will follow the scroll and choose the content box to be misplaced.

### ISSUE THREAD

**Issue by q381536145** [iview/iview#3794]
### Environment
Windows 7 / Google Chrome版本 66.0.3359.181（正式版本） （32 位）/Vue2.5.13

### Reproduction link
[https://jsfiddle.net/yyrzhm46/900/](https://jsfiddle.net/yyrzhm46/900/)

### Steps to reproduce
Selecting components and rolling scrollbars

### What is expected?
The arrow does not follow the scroll bar, and the selection box is not misplaced.

### What is actually happening?
The arrow moves with the scroll bar, selecting the frame misplacement.

**Comment by icarusion** [comment]
You can not set `overflow` to Select
