### ISSUE TITLE
After [Bug Report]select component initializes data through Ajax, the value of V-model binding cannot be displayed.


### ISSUE THREAD

**Issue by mirrorpal** [iview/iview#3795]
### Environment
mac os / chrome 版本 67.0.3396.62 / vue 2.5.2 iview 2.14.1

### Reproduction link
[https://jsfiddle.net/yyrzhm46/902/](https://jsfiddle.net/yyrzhm46/902/)

### Steps to reproduce
1.通过ajax请求初始化数据
2.给v-modal赋值

### What is expected?
select组件可以赋值成功，select组件显示对应的label值

### What is actually happening?
select组件没有显示对应的label值

**Comment by jackzhcai** [comment]
@icarusion 什么时候能修复这个问题。

**Comment by nickrogit** [comment]
select加了filterable属性后，option动态ajax填充不成功。

**Comment by hsroad** [comment]
> select加了filterable属性后，option动态ajax填充不成功
碰到同样的问题！对这个框架很无语
