### ISSUE TITLE
[Bug Report]Table performance problem data push table inside all lines rerendered


### ISSUE THREAD

**Issue by tangbinqiao** [iview/iview#3797]
### Environment
window7/Chrome/66.0.3359.181/Vue^2.5.2

### Reproduction link
[https://jsfiddle.net/yyrzhm46/903/](https://jsfiddle.net/yyrzhm46/903/)

### Steps to reproduce
我想做一展示股票的table,但是是通过websocket实时刷新的， data push数据的时候Table里面的所有项会重新渲染， 页面会很卡

### What is expected?
只渲染push的那一条数据

### What is actually happening?
所有行都重新渲染了

---
Table实时刷新

**Comment by cdswyda** [comment]
I find the same problem. #3816

**Comment by zhuxi918** [comment]
when i use iview i find if i use the render function if the data change all the function will render so the whole page so slow and the component will stop and wait

**Comment by dasnnj** [comment]
同样的问题，请问您那边解决了吗
