### ISSUE TITLE
Modal组件遮罩位置问题

### ISSUE THREAD

**Issue by xiaoyyang123** [iview/iview#380]
iView 版本号

2.0.0-rc.2

操作系统/浏览器 版本号

windows/Chrome 55

Vue 版本号

2.2.2

问题现象，以及你期望的结果是怎样的?
1.Modal组件，当父级元素的样式有transform属性时，Modal组件的遮罩的fixed定位会失效，变为absolute
```html
<div style="transform: scale(1);">
    <v-button type="primary" @click.native="showModal = true">点击出现</v-button>
    <Modal v-model="showModal" title="新建">
       <p>测试</p>
    </Modal>
</div>
```
早期的bootstrap里面也有这个问题，后来改成了modal直接添加到body下面修复了这个问题

2.Modal组件，控制显示和隐藏用的是v-show指令，这样我点取消之后再打开modal时，之前填写的一些表单信息仍然还会缓存在组件里

**Comment by rijn** [comment]
To answer your second question, you can use `v-if` if you want.

**Comment by xiaoyyang123** [comment]
thanks, the second question is solved, when the first question get solved?

**Comment by icarusion** [comment]
尽量把Modal放置在外面吧，因为它本身与文档其它位置都不相关。

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/713bd3d75dcc6988065b368775e1b8ae36c456fe
