### ISSUE TITLE
When [Bug Report]iview select selector is used, there is bug with infinite update loop.


### ISSUE THREAD

**Issue by chensiyuan12138** [iview/iview#3800]
### Environment
win7 64bit // chrome 64 // vue 2.4.2

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
iview 2.14.1
重新npm最新的环境，然后使用iview的select相关的组件
vue warming：You may have an infinite update loop in a component render function.

### What is expected?
可以正常使用下拉列表

### What is actually happening?
不能出来，控制台报错，生产环境卡死

**Comment by wd603546401** [comment]
遇到了同样的问题，不知道如何解决

**Comment by boyangwang** [comment]
+1 also encountered same problem, with minimal markup:

```
            <Select v-model="banner.lang">
              <Option value="en">en</Option>
              <Option value="zh">zh</Option>
            </Select>
```

**Comment by EstebanFuentealba** [comment]
+1

**Comment by ghost** [comment]
update your vue version

**Comment by wjl660** [comment]
+1

**Comment by qfgyd2004** [comment]
+1

**Comment by jazzysnail** [comment]
I m also encountered same problem, the known solution is to update your Vue version. And then wait for the update of iview.

**Comment by cuiD2488** [comment]
+1

**Comment by hamlet-lee** [comment]
I also encountered this problem.
@jazzysnail Which vue version works? Would you provide some information on why new vue version works?

**Comment by jazzysnail** [comment]
@hamlet-lee The version I used to solve the problem before was 2.5.17, I hope I can help you.

**Comment by hamlet-lee** [comment]
@jazzysnail thanks, I will try

**Comment by mengai123** [comment]
> @hamlet-lee The version I used to solve the problem before was 2.5.17, I hope I can help you.

iview have no 2.5.17, i solve the problem at 2.5.1

**Comment by zhangfanglin** [comment]
@mengai123  This answer helped me
