### ISSUE TITLE
After selecting a option, [Bug Report]select changes the display value of the option, and then checks the select to show the old value.


### ISSUE THREAD

**Issue by hellomrbigshot** [iview/iview#3801]
### Environment
最新版本

### Reproduction link
[https://jsfiddle.net/Yeachan/9gwmqdhp/](https://jsfiddle.net/Yeachan/9gwmqdhp/)

### Steps to reproduce
选中 New York，然后点击按钮，New York 变为 Beijing，选中 London， 选中 Beijing，发现 Beijing 在选中后仍然显示 New York

### What is expected?
显示 Beijing

### What is actually happening?
显示  New York

**Comment by David-Tsui** [comment]
老兄，你只改label沒改value阿
https://jsfiddle.net/cy5z8qmq/1/

如果你要在click也修改當下選中值，自己再去修v-model吧

**Comment by hellomrbigshot** [comment]
@David-Tsui 你没有理解我的意思哦，我指的是选中 New York 后，绑定的是 New York 对应的值，然后选中 London，现在绑定的是 London，之后点击按钮，option 中的 New York 变为 Beijing 了，但是 选中 Beijing 后 Select 显示的仍然是 New York

**Comment by David-Tsui** [comment]
@hellomrbigshot Demo link都擺在那給你點，還說我沒理解，挺微妙呢OWO

**Comment by hellomrbigshot** [comment]
@David-Tsui 感谢哦，我找到解决方法了，应该是更新数据的 option 需要重新 mounted 一遍，选中之后的值才会改变。所以我把 key 绑定到 label 了，这样 label 改了之后那个 option 会重载，这样就没问题了。

**Comment by David-Tsui** [comment]
@hellomrbigshot  哈哈哈 你完全沒聽人說話呢
