### ISSUE TITLE
[Bug Report]Menu navigation menu update open-names shows bug


### ISSUE THREAD

**Issue by Abiel1024** [iview/iview#3807]
### Environment
win10 Chrome65.0.3325.181 最新版本Vue

### Reproduction link
[https://jsfiddle.net/zrrdf392/](https://jsfiddle.net/zrrdf392/)

### Steps to reproduce
改变open-names值，无法将对应的menu展开

### What is expected?
能根据设置的open-names准确的展示

### What is actually happening?
没有准确的打开对应的menu

---
在menu组建中watch了openNames属性的改变，当检测到改变的时候，执行下updateOpened就可以解决这个问题。

**Comment by laichuangchong** [comment]
I had the same problem.

**Comment by Abiel1024** [comment]
@laichuangchong You can modify the source code in node modules, but if you update the node modules it will lose
