### ISSUE TITLE
select 无法渲染默认值 filterable remote clearable 模式下

### ISSUE THREAD

**Issue by huxuebao** [iview/iview#3811]
复现链接： https://jsfiddle.net/q4nq5wq1/3/
select 组件中
    filterable 
    remote 
    clearable
模式下无法渲染默认值

**Comment by shiwuhao** [comment]
@huxuebao 问题解决了吗?我也遇到该问题了

**Comment by 70kg** [comment]
这个怎么解决？

**Comment by buhongjuan** [comment]
怎么解决
