### ISSUE TITLE
[Bug Report]Select components cannot render default values in filterable, remote, and clearable mode

### ISSUE THREAD

**Issue by huxuebao** [iview/iview#3813]
### Environment
win10 Chrome65.0.3325.181 最新版本Vue  iview-2.14.1

### Reproduction link
[https://jsfiddle.net/q4nq5wq1/](https://jsfiddle.net/q4nq5wq1/)

### Steps to reproduce
Select components cannot render default values in filterable, remote, and clearable mode

select 组件 在 filterable，remote，clearable 模式下  无法渲染默认值

### What is expected?
希望解决这个bug谢谢

### What is actually happening?
希望能得到解决

---
谢谢

 @LekisS @dspangenberg @Xotic750 @lepture @yinheli

**Comment by huxuebao** [comment]
怎么没人解决呢？ 这是个bug呀

**Comment by huxuebao** [comment]
这是个bug 希望解决下 @LekisS @dspangenberg @Xotic750 @yinheli @lepture

**Comment by icarusion** [comment]
fixed in #3798
