### ISSUE TITLE
[Bug Report]select in remote&multiple mode, if I want to set the initial display value, that is, set the label attribute as an array, the report type error (official API is that label can be array, string, number)


### ISSUE THREAD

**Issue by wanglyaaa** [iview/iview#3817]
### Environment
windows 64位/chrome 64.0.3282.186/vue 2.5.2

### Reproduction link
[https://jsfiddle.net/pew9g5hp/](https://jsfiddle.net/pew9g5hp/)

### Steps to reproduce
页面初始化时就会报错

### What is expected?
label不报类型错误

### What is actually happening?
label报类型错误

**Comment by cleack5** [comment]
在2.14.3还是有这个bug
