### ISSUE TITLE
是否计划开发可直接在表内编辑的tabel组件

### ISSUE THREAD

**Issue by meteorfall** [iview/iview#382]
是否计划开发可直接在表内编辑的tabel组件

**Comment by YikaJ** [comment]
这个你可以在 ivew 组件外自行实现，参照 antd 的可编辑单元格
[可编辑单元格](https://ant.design/components/table-cn/#components-table-demo-edit-cell)

**Comment by rijn** [comment]
@icarusion I believe this issue can be closed. Thanks. =)
