### ISSUE TITLE
[Bug Report]InputNumber使用precision精度设置时，输入不友好

### ISSUE THREAD

**Issue by gavinfuu** [iview/iview#3820]
### Environment
window chrome 60 

### Reproduction link
[http://jsrun.net/ZSZKp/edit](http://jsrun.net/ZSZKp/edit)

### Steps to reproduce
InputNumber使用precision精度设置时，输入不友好
没等输入完整数部分光标就已经跳至小数位数后面
输入25.26为例

### What is expected?
可以完整舒适的输入25.26

### What is actually happening?
当输入2的时候，光标就已经跳转至2.00后面

**Comment by Xotic750** [comment]
Your reproduction link gives me
![screenshot from 2018-06-05 17-19-05](https://user-images.githubusercontent.com/216041/40985457-753f8f02-68e4-11e8-8069-7657ba4bf8b3.png)

Perhaps you can try on [jsiddle](https://jsfiddle.net/)

Other than that, I am unable to help as I can't read Chinese.

**Comment by qutz** [comment]
[这个可以看我的修改``](https://github.com/iview/iview/pull/3644)

**Comment by gavinfuu** [comment]
@qutz 才用了你的修改，解决了，谢谢你

**Comment by weibingbing5101** [comment]
setValue (val) {
                // 如果 step 是小数，且没有设置 precision，是有问题的
                if (!isNaN(this.precision)) val = Number(Number(val).toFixed(this.precision));
                this.$nextTick(() => {
                    this.currentValue = val;
                    this.$emit('input', val);
                    this.$emit('on-change', val);
                    this.dispatch('FormItem', 'on-form-change', val);
                });
            },

这块的代码还需要判断一下  val的参数是不是null  如果input没值的时候blur 会报 toFixed错误

**Comment by ahuang** [comment]
:formatter="value => `${parseFloat(value.toFixed(2))}`" 
试试这个

**Comment by lidong123** [comment]
> @qutz 才用了你的修改，解决了，谢谢你

怎么解决的呀？
