### ISSUE TITLE
[Bug Report] recommends adding menu components to reduce hours. Mouse suspension displays first level menu and two level menu.


### ISSUE THREAD

**Issue by DaDaDaDaDaBocai** [iview/iview#3825]
### Environment
win10/Google Chrome/Vue 2.9.3

### Reproduction link
[https://jsfiddle.net/m8w57uxa/](https://jsfiddle.net/m8w57uxa/)

### Steps to reproduce
点击缩小菜单 然后悬浮在菜单上
[
![image](https://user-images.githubusercontent.com/25682361/40965009-2a01a6a6-68df-11e8-8ea1-fb21e1b9d25d.png)
](url)

### What is expected?
能够正确显示二级菜单

### What is actually happening?
能够正确显示二级菜单

**Comment by Xotic750** [comment]
Current Vue stable release is v2.5.16, which is also the version your fiddle is using, no idea where you ar getting v2.9.3 from?

> What is expected?
> Can correctly display two level menus
> What is actually happening?
> Can correctly display two level menus

So the result is as expected? Some further explanation is required to be able to understand the problem.

**Comment by icarusion** [comment]
@DaDaDaDaDaBocai if you want to submit an issue with **feature request**, you should select the correct options in https://www.iviewui.com/new-issue
