### ISSUE TITLE
[Bug Report]Tabs uses bug


### ISSUE THREAD

**Issue by Ak-Li** [iview/iview#3826]
### Environment
vue 2.14.1

### Reproduction link
[http://jsrun.net/cSZKp/edit](http://jsrun.net/cSZKp/edit)

### Steps to reproduce
代码所示

### What is expected?
当前tabPane的内容出现

### What is actually happening?
当前tabPane的内容不出现

**Comment by Xotic750** [comment]
I assume you mean iview 2.14.1 as the vue peer dependency is

https://github.com/iview/iview/blob/2.0/package.json#L54  v2.5.2

Your reproduction link gives me 

![screenshot from 2018-06-05 17-05-53](https://user-images.githubusercontent.com/216041/40984622-9d81a560-68e2-11e8-8a0e-00076937afc3.png)

Perhaps you can create a reproduction of he problem on [jsfiddle](https://jsfiddle.net/)

**Comment by Ak-Li** [comment]
my link  : https://jsfiddle.net/lewli/5febpvmz/ 
vue version is 2.5.13

**Comment by Xotic750** [comment]
Thank you for resupplying an example. So if I understand correctly, the Tab content is not showing when changed at mount time, it is only showing after a Tab is clicked, is that correct?

**Comment by Ak-Li** [comment]
This is true for iview version 2.14.1. There is no problem with 2.13. 1 .You can modify the tab in mounted.
