### ISSUE TITLE
当元素层级超过三层，i-table中render自定义i-button的@click无法绑定到函数！

### ISSUE THREAD

**Issue by systoms** [iview/iview#383]
### iView 版本号
1.0.1

### 操作系统/浏览器 版本号
56.0.2924.87

### Vue 版本号
v1.0.28

### 能够复现问题的在线示例

http://yii.mycgi.cn/users/index

### 复现步骤
请点击查看table中button

### 问题现象，以及你期望的结果是怎样的?
问题得到解决

### 你估计可能的原因是什么（选填）？
iview自定义组无法正确解析导致

**Comment by rijn** [comment]
Please provide the source code.

**Comment by systoms** [comment]
http://yii.mycgi.cn/users/index
源码在该地址中。

**Comment by GITleonine1989** [comment]
目测，没有指定 itable 的content属性 。加上试下
![image](https://cloud.githubusercontent.com/assets/7582490/23843939/13b05132-07fa-11e7-9bde-9a1f249a4f9c.png)

**Comment by systoms** [comment]
设置上下文还是无法解决问题！

**Comment by icarusion** [comment]
Table 的 Cell 在 2.0 里还有问题没有解决，详见 project todo

**Comment by systoms** [comment]
这个问题多久才能修复？

**Comment by icarusion** [comment]
再找到好的解决方案后会修复

**Comment by GITleonine1989** [comment]
他用的是v1哦

**Comment by icarusion** [comment]
1.0应该是没有问题的，最好在 jsbin、codepen上提供在线代码

**Comment by systoms** [comment]
我用的就是1.0的，这个问题是不是一直都存在！

我没有用node去编译，而是直接在浏览器里加载的！

**Comment by GITleonine1989** [comment]
我都用在生产环境了，所以肯定不能在这个问题，我看了你的连接，是你标签关闭的不对导致的

**Comment by systoms** [comment]
没有闭合？

**Comment by GITleonine1989** [comment]
自己找找嘛，好几个地方写的不对，自己找出来，比较长记性 ：)

**Comment by systoms** [comment]
http://tool.chinaz.com/htmlcheck.aspx
检测没有问题啊！

**Comment by GITleonine1989** [comment]
关键那不是html标签啊 ，那是自定义的，看下自己代码呗

**Comment by systoms** [comment]
没有找到问题，提示一下呗，我这是业余前端！。。。

**Comment by GITleonine1989** [comment]
http://jsbin.com/?html,output ，copy 过去吧，得亏我下午有点空，你这提问方式的改进一下，不然别人不会看的

**Comment by icarusion** [comment]
地址应该分享错了

**Comment by GITleonine1989** [comment]
咦  等一下 ，我重新建一个

**Comment by GITleonine1989** [comment]
http://codepen.io/anon/pen/NpgxOd 看这个吧 jsbin 今天出问题了？

**Comment by systoms** [comment]
谢谢，我这也是第一次提问！
