### ISSUE TITLE
[Bug Report]When DropDownItem is set to disabled, 'on-click' event can also be emitted.

### ISSUE THREAD

**Issue by FioneraGH** [iview/iview#3830]
### Environment
MacOS 10.13.5, Chrome 67, Vue 2.5.16

### Reproduction link
[https://www.iviewui.com/](https://www.iviewui.com/)

### Steps to reproduce
                if (this.disabled) {
                    this.$nextTick(() => {
                        $parent.currentVisible = true;
                    });
                } else if (hasChildren) {
                    this.$parent.$emit('on-haschild-click');
                } else {
                    if ($parent && $parent.$options.name === 'Dropdown') {
                        $parent.$emit('on-hover-click');
                    }
                }
                $parent.$emit('on-click', this.name);

### What is expected?
Cannot click.

### What is actually happening?
'on-click' event was emitted.

**Comment by Xotic750** [comment]
The link to reproducing your problem takes me to the iview home page. Do you have a link to a [jsfiddle](https://jsfiddle.net) of the problem?

**Comment by icarusion** [comment]
when click a `disabled` DropdownItem, the drop will not hide, but events are always triggered, it's not a bug.
