### ISSUE TITLE
[Bug Report] select component doesn't set initial value

### ISSUE THREAD

**Issue by losadaem** [iview/iview#3834]
### Environment
vue 2.5.16
iview 2.14.1

### Reproduction link
[https://codesandbox.io/s/4w11p7v1wx/](https://codesandbox.io/s/4w11p7v1wx/)

### Steps to reproduce
Use `iOption` name casing inside Vue templates.

### What is expected?
Select component sets initial value.

### What is actually happening?
Select doesn't set the initial value.

---
You can use `iOption` name casing in Vue templates like this :
```
<iOption v-for="item in items" :value="item.value" :key="item.value" :label="item.label"></iOption>
```
But this stops the `Select` component to work properly because the option regexp used doesn't take this naming convention into account :
```
optionRegexp = /^i-option$|^Option$/i;
```

**Comment by David-Tsui** [comment]
Then you should change this title to 

> Select option named "iOption" doesn't set the initial value.

**Comment by icarusion** [comment]
Wrong usage, you should use `<i-option>` or `<Option>`

**Comment by losadaem** [comment]
Maybe you can consider supporting this case naming. I'm prefixing my components to differentiate iView components from the rest. Name casing is commonly used too.

[https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended](https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended)
