### ISSUE TITLE
[Bug Report]Select 错误问题

### ISSUE THREAD

**Issue by jiosers** [iview/iview#3836]
### Environment
window10

### Reproduction link
[https://jsfiddle.net/40ryqfea/1/](https://jsfiddle.net/40ryqfea/1/)

### Steps to reproduce
1.select  加上属性filterable  ，
2.点击选择下拉列表值  选择其他，
3.点击测试按钮   给下拉值绑定值（这个值不要和前面选择的值一样）    

### What is expected?
下拉列表展示应该是全部的下拉列表值  并且下拉选中值显示选中颜色

### What is actually happening?
下拉列表只有当前选中的对象    且当前选中的值对象没有显示选中颜色

---
当前下拉加上了filterable属性过滤，  当我赋值硬性改变它的时候，首先组件处理的是把当前值作为过滤条件去过滤了

**Comment by jiosers** [comment]
good

**Comment by jiaoxueyan** [comment]
http://jsfiddle.net/eqjub56h/8/

**Comment by jiaoxueyan** [comment]
为啥我的中文不可以
