### ISSUE TITLE
[Bug Report]select options show incorrect

### ISSUE THREAD

**Issue by suconghou** [iview/iview#3837]
### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

### Reproduction link
[https://jsfiddle.net/suconghou/9dcxq51o/22/](https://jsfiddle.net/suconghou/9dcxq51o/22/)

### Steps to reproduce
click change ensure options is not empty and then select one ; <br><br><br>
then click change , try to select and see what in the dropdown , do a fews times , you will find the bug .

### What is expected?
select options shows same as v-for list

### What is actually happening?
dropdown options shows not the same as v-for

**Comment by Xotic750** [comment]
You seem to be overwriting `value` of the options with the random numeric value, then when you select an option using `v-model` there is never a matching option value of `Sydney`?

https://jsfiddle.net/9dcxq51o/32/

**Comment by suconghou** [comment]
the dropdown list should show whatever in the cityList , and v-model should not effect the dropdown list,   is it ??

**Comment by Xotic750** [comment]
Yes, I have seen it happen now, like this
![screenshot from 2018-06-06 19-29-18](https://user-images.githubusercontent.com/216041/41054858-e0667cce-69bf-11e8-8dd7-f99afe1612b8.png)

**Comment by suconghou** [comment]
why this issue not solved but be closed ,  The latest version still has problems https://jsfiddle.net/9dcxq51o/38/

**Comment by suconghou** [comment]
https://github.com/iview/iview/issues/3896

**Comment by diego-gonzalez** [comment]
@suconghou I have the same error, did you fix it?

**Comment by suconghou** [comment]
@diego-gonzalez  no , I got another way and avoided the problem

**Comment by h1orz** [comment]
So i am.
