### ISSUE TITLE
[Bug Report] switches Switch, opens and closes the same text.


### ISSUE THREAD

**Issue by suiyunpiaoliu** [iview/iview#3838]
### Environment
Macos High Sierra 10.13.4 chrome  66.0.3359.181

### Reproduction link
[https://jsfiddle.net/yyrzhm46/930/](https://jsfiddle.net/yyrzhm46/930/)

### Steps to reproduce
点击切换switch

### What is expected?
开和关显示不同的文字

### What is actually happening?
开和关显示相同的文字

**Comment by icarusion** [comment]
Unable to reappear
