### ISSUE TITLE
[Bug Report] under IE9, the Table component is wrong, and the ivu-table-hide class is added.


### ISSUE THREAD

**Issue by see311** [iview/iview#3839]
### Environment
win10/ie9/vue2.5.2

### Reproduction link
[https://www.iviewui.com/components/table](https://www.iviewui.com/components/table)

### Steps to reproduce
在ie9中打开官网table示例，或使用vue-cli，单独使用table组件的官网示例代码，

### What is expected?
table兼容ie9，正常显示

### What is actually happening?
所有的table都添加了ivu-table-hide类，opacity为0
[Vue warn]: Error in nextTick: "TypeError: 无法获取未定义或 null 引用的属性“remove”"

found in

---> <Table>
       <HelloWorld> at src\components\HelloWorld.vue
         <App> at src\App.vue
           <Root>

**Comment by icarusion** [comment]
Not suport IE9
