### ISSUE TITLE
[Bug Report]Put a Table in the Panel of the folding panel Collapse, and the Table width is incorrect

### ISSUE THREAD

**Issue by kbyzly2008** [iview/iview#3846]
### Environment
iview version >= 2.13.0

### Reproduction link
[https://jsfiddle.net/kbyzly2008/eywraw8t/67433/)

### Steps to reproduce
1、add a test html page，use iview >= 2.13.0

2、put a Table in the Panel of the folding panel Collapse

3、run code

### What is expected?
The table can be displayed normally

### What is actually happening?
The table displayed bad，width is incorrect

---
iview version 2.12.0 don't has this problem

**Comment by Abiel1024** [comment]
setting width by number instead of string  and delete ‘i-’ in tag  [example](https://jsfiddle.net/8fa7pds4/)

**Comment by kbyzly2008** [comment]
thank you ! i got it
