### ISSUE TITLE
表格导出中文乱码

### ISSUE THREAD

**Issue by Ayerss** [iview/iview#385]
iView 版本号

1.0.1

操作系统/浏览器 版本号

win7     Chrome 56.0

Vue 版本号

v1.0.28

能够复现问题的在线示例

官方案例：https://www.iviewui.com/components/table

复现步骤

点击导出csv文件，下载下的文件中文是乱码的。只能通过修改编码格式成ANSI才正常

问题现象，以及你期望的结果是怎样的?

是否能直接导出ANSI编码的文件

你估计可能的原因是什么（选填）？

导出文件的编码的utf-8格式，未转换成ANSI

**Comment by icarusion** [comment]
按要求提问

**Comment by Ayerss** [comment]
已按格式提问

**Comment by rijn** [comment]
You mean specifying encoding when export csv?

**Comment by Ayerss** [comment]
yes, because the export is utf-8, the default office excel open is garbled, whether the export is ANSI. Save the user to change the code of the steps, or let the developers choose to export the encoding format

**Comment by rijn** [comment]
Ok. We can leave that choice to developer.

**Comment by Ayerss** [comment]
Thank you, hope iView become more perfect.

**Comment by rijn** [comment]
@icarusion I found this library [text-encoding](https://github.com/inexorabletash/text-encoding), but it may be a little bit large to support all the encoding methods. Maybe we can leave a function to users that pass the original text and save returned value.

**Comment by icarusion** [comment]
@rijn I will view it later,thx

**Comment by jingsam** [comment]
我在想如果默认导出ANSI，其他的软件读取会不会乱码。我认为导出utf-8就够了，至于utf-8向其他编码转换，应该由用户来完成

**Comment by icarusion** [comment]
我在 windows 上有测过，除了 ie9，好像都是正常的。前端导出文件这块较难实现太复杂的定制，所以还是建议用户自己修改编码吧
