### ISSUE TITLE
Model 的按钮没有自动获得焦点

### ISSUE THREAD

**Issue by terranc** [iview/iview#386]
在浏览器里alert、confirm等弹出框里的主按钮会自动获得焦点，其后的操作可以『回车』、『空格』触发，这样会加快很多操作效率，比如删除多个而无批量删除的场景下，就不必鼠标频繁左右移动了。
而现在$Model里没有实现，导致习惯『空格』的我。。。。

**Comment by icarusion** [comment]
It doesn't look like a general demand，we just support ESC to close

**Comment by rijn** [comment]
You can customize the footer by yourself. Like put a listener on v-show variable and focus on the button you want.

**Comment by terranc** [comment]
@icarusion 我认为一个好的模态框，既然是为了替换浏览器自带的alert和confirm之类的，为什么不彻底的模拟呢？我觉得作者你可以参考下 Bootstrap modal 、 SweetAlert，甚至 dialog for element-ui 的体验。

**Comment by terranc** [comment]
@rijn 我当然知道可以自定义，那我就不会来提issue了

**Comment by wangchao3012** [comment]
我现在是在 confirm 执行后让确定按钮激活，这个可以实现弹出后按空格或回车提交，希望作者添加此功能
`this .$Modal.confirm({....});
this.$nextTick(() => {
            document
              .querySelector(
                ".ivu-modal-wrap:not(.ivu-modal-hidden) .ivu-modal-confirm .ivu-modal-confirm-footer .ivu-btn-primary"
              )
              .focus();
          });`
