### ISSUE TITLE
[Bug Report]Modal Component feel slow 

### ISSUE THREAD

**Issue by wensonsmith** [iview/iview#3868]
### Environment
Mac Chrome  66.0.3359.181

### Reproduction link
[https://www.iviewui.com/components/modal](https://www.iviewui.com/components/modal)

### Steps to reproduce
Just click show modal , it feels like after 0.3 second ,then show the dialog, if click the close button ,it also feels slow to response . I'm not sure  dose animation cause this? Compare with Element ui dialog ,you will feel the deference of speed.  And Safari / Firefox feel better ,but also not very smooth.

### What is expected?
Speed the modal

### What is actually happening?
the modal feels very slow

**Comment by dingzeng** [comment]
/src/components/modal/confirm.js
```
remove () {
    setTimeout(() => {
        this.destroy();
    }, 300);
},
```

**Comment by icarusion** [comment]
Not a bug, if you want to custom animation, use prop `transition-names`

**Comment by dingzeng** [comment]
```
this.$Modal.confirm({content:'xxx?',onOk:() => { 
    this.$Modal.warning({
        content: 'content'             
    });
}})
```
这样写有个问题，点完确认按钮后，里面的warning一闪而过了
