### ISSUE TITLE
[Bug Report]Version 2.14.2 Select Component could not handle Option Component with Number Type Prop

### ISSUE THREAD

**Issue by laubd** [iview/iview#3872]
### Environment
macos10.13.4/chrome 66.0.3359.181

### Reproduction link
[https://laubd.github.io/iview-bug/dist/](https://laubd.github.io/iview-bug/dist/)

### Steps to reproduce
input 1, wait for the ajax data, when the option change, you should doubleclick the option, the input value first change to the prop 'value', then is the prop 'label' value, and error in Developer Tools, and the remote-method callback show the query is a Number which is can't be.
输入1, 获取数据后, option需要点击2次才可以选到, 然后显示的值先是:value在是:label, 之后就会有(t || "").trim is not a function或者queryProp需要传String, remote-method回调的query打印出来会有number值, 即有可能导致queryProp的问题

### What is expected?
1.should click 1 time to select the value 2.the input value will not change twice 3.no error

### What is actually happening?
1.you shoud click twice to select a value 2.the input will change

---
code: https://github.com/laubd/iview-bug
It seem to only show in runtime or build from runtime.
runtime或者打包出来才会这样, jsfiddle似乎不会出现

**Comment by configSer** [comment]
开发用的是2.10.0，DatePicker 组件不好用了，升级到2.14.3后，Select组件不好用了，取不到默认值，why？
