### ISSUE TITLE
[Bug Report]select remote search


### ISSUE THREAD

**Issue by iuvword** [iview/iview#3876]
### Environment
win10/Chrome 66.0.3359.117

### Reproduction link
https://jsfiddle.net/cqod43e0/6/

### Steps to reproduce
输入 q 控制台console options1 有 50 条数据，可显示的是无匹配数据，
删除 q 下拉框数据出现，随便选择一个，显示为 value 值

### What is expected?
1.选中后能正常显示slot内容或label值
2.后台请求过来数据有多少就显示多少，不需要 关键字匹配option的 slot 进行二次筛选

### What is actually happening?
1.选中某选项时显示的是value（设置label也无效）,而不是文档中写的‘默认会读取 slot，无 slot 时，优先读取该 label 值，无 label 时，读取 value’
2.筛选结果会进行二次筛选

---
用的官网demo修改了一下options1 的 vlaue 加了一个searchkey

**Comment by BoleLee** [comment]
问题：自定义Option模版+远程搜索，搜索有得到数据，但显示无匹配数据；
将Option slot改为简单的只显示某个属性值，则可正常得到搜索的列表；

**Comment by iuvword** [comment]
将Option slot改为简单的只显示某个属性值 这样也不行， 我问题是我希望通过关键字能搜索到商品
如 {name:'苹果',searchKey:'PG'} ,此时 我输入 PG  后台会把苹果返回 但是 option 却不会展示
