### ISSUE TITLE
穿梭框的data属性无法通过异步加载把值动态set进去

### ISSUE THREAD

**Issue by KevinGZ2017** [iview/iview#388]
### iView 版本号
0.9.17

### 操作系统/浏览器 版本号
macOS/Chrome 54

### Vue 版本号
1.0.26

### 问题现象，以及你期望的结果是怎样的?
我通过异步请求去后台获取数据，this.data =  response.data和this.$set('targetKeys', response.data)这两种方式都无法重新渲染穿梭框中的数据

**Comment by icarusion** [comment]
提供在线示例

**Comment by zWingz** [comment]
![image](https://cloud.githubusercontent.com/assets/13031838/23851276/e4e0b210-081d-11e7-9fdf-55eb9b6cb446.png)
你的调用方法错了吧.

**Comment by KevinGZ2017** [comment]
<Transfer
                    :data="data"
                    :target-keys="targetKeys"
                    :list-style="listStyle"
                    :render-format="render"
                    :operations="['向左移动','向右移动']"
                    filterable
                    @on-change="handleChange">
                <div :style="{float: 'right', margin: '5px'}">
                    <i-button type="ghost" size="small" @click="reloadMockData">刷新</i-button>
                </div>
    </Transfer>
    export default {
        data () {
            return {
                data: [],
                targetKeys: [],
                listStyle: {
                    width: '250px',
                    height: '300px'
                }
            }
        },
        ready () {
            setTimeout(() => {
                // 模拟异步加载数据
                var mockData = [
                    { "key": "1", "label": "内容1", "disabled": false },
                    { "key": "2", "label": "内容2", "disabled": true },
                    { "key": "3", "label": "内容3", "disabled": false }
                ]
                this.$set('data', mockData)    // this.data = mockData  这两种方式都不能渲染穿梭框，穿梭框还是没有数据
            }, 5000);
        }
}

**Comment by icarusion** [comment]
查看源码examples，你的写法不对

**Comment by KevinGZ2017** [comment]
examples中的data都是直接赋值的，我现在的data是需要通过异步请求去后台获取数据再放到data上的哦？我不大明白你所说的写法不对是指哪个？

**Comment by zhonggithub** [comment]
哥们是怎么解决的

**Comment by zhonggithub** [comment]
http://codepen.io/anon/pen/yMGbZX?editors=1011

**Comment by ryanzhouff** [comment]
添加`:filter-method="filterMethod"`即可：
// template
```html
<Transfer
   :data="data1"
   filterable
  :target-keys="targetKeys1"
  :render-format="render1"
  :filter-method="filterMethod"
  @on-change="handleChange1"
>
</Transfer>
```
// methods，其他代码省略
```javascript
...
methods: {
  filterMethod (data, query) {
    return data.label.indexOf(query) > -1;
  }
}
...
```
