### ISSUE TITLE
[Bug Report] DatePicker sets wrong the date depending on the browser time zone.

### ISSUE THREAD

**Issue by losadaem** [iview/iview#3881]
### Environment
vue 2.5.16
iview 2.14.1

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
Right now I'm in TimeZone GMT-4 and the time is 16:52 and the date is Wed, June 13 2018.
Click one day in the date picker. For example 12 in my case.

### What is expected?
When I select day 12 the input must be set to 2018-06-12
*Also today must be marked as 13.

### What is actually happening?
When I select day 12 in the DatePicker the input is set to 2018-06-11 
The DatePicker marks today as day 14 what is wrong.

---
<img width="897" alt="screen shot 2018-06-13 at 4 55 46 pm" src="https://user-images.githubusercontent.com/5043618/41377834-4a2c7256-6f2b-11e8-85c3-6ef69865bee0.png">

**Comment by Steffan-Carlos** [comment]
+1

**Comment by leoberdu** [comment]
The same with me. Today is 07/Jul, but the calendar open with 08/Jul.

![image](https://user-images.githubusercontent.com/86506/42415567-6cac610e-8229-11e8-8b03-d2e97d1e8f96.png)

**Comment by Steffan-Carlos** [comment]
Any update on this @icarusion

**Comment by zhichuanduan** [comment]
Is there any solution for this issue in this page cuz all the links is saying that this problem is resolved in this report.

**Comment by zhichuanduan** [comment]
@icarusion

**Comment by hkmsadek** [comment]
hell shit, still no solution for this problem??

**Comment by steele-cjf** [comment]
hi，body，no solution？
