### ISSUE TITLE
组件名和HTML的保留字冲突了

### ISSUE THREAD

**Issue by ccfnever** [iview/iview#389]
### iView 版本号
2.0.0-rc.2

### 操作系统/浏览器 版本号
 macOS/Chrome 56

### Vue 版本号
2.2.1

### 复现步骤
1.直接 npm run dev
2.打开Chrome控制台，会看到两个Vue的报错：
    [Vue warn]: Do not use built-in or reserved HTML elements as component id: Progress 
    [Vue warn]: Do not use built-in or reserved HTML elements as component id: Button 

### 问题现象，以及你期望的结果是怎样的?
貌似不影响使用，但有报错总是不太好。希望修复。
### 你估计可能的原因是什么（选填）？
应该是组件名和HTML的保留字冲突了

**Comment by icarusion** [comment]
update to 2.0.0-rc.3 and use i-
