### ISSUE TITLE
[Bug Report]IE10 select cannot be selected


### ISSUE THREAD

**Issue by xfworld** [iview/iview#3898]
### Environment
win8/ IE10 / Vue 2.5.2

### Reproduction link
[http://localhost:8080](http://localhost:8080)

### Steps to reproduce
界面初始化完成后，界面上的Select无法选中，可以下拉展示

### What is expected?
下拉选项后，可选中

### What is actually happening?
下拉选项后，无法选中

**Comment by Xotic750** [comment]
https://github.com/iview/iview/blob/2.0/package.json#L125

**Comment by xfworld** [comment]
看到了，谢谢@Xotic750

**Comment by trsoliu** [comment]
在main.js里加

var isIE = function() {
	return(window.navigator.userAgent.indexOf("MSIE") >= 1);
}

// 修复iview 在IE10及以下版本不支持dataset属性的问题，兼容transfer-dom.js中使用了dataset的问题
if(isIE() && window.HTMLElement) {
	if(Object.getOwnPropertyNames(HTMLElement.prototype).indexOf('dataset') === -1) {
		Object.defineProperty(HTMLElement.prototype, 'dataset', {
			get: function() {
				var attributes = this.attributes;
				var name = [],
					value = [];
				var obj = {};
				for(var i = 0; i < attributes.length; i++) {
					if(attributes[i].nodeName.slice(0, 5) == 'data-') {
						name.push(attributes[i].nodeName.slice(5));
						value.push(attributes[i].nodeValue);
					}
				}
				for(var j = 0; j < name.length; j++) {
					obj[name[j]] = value[j];
				}
				return obj;
			}
		});
	}
}
