### ISSUE TITLE
提交时候，validate 重复验证的问题

### ISSUE THREAD

**Issue by hualvm** [iview/iview#391]
### iView 版本号

1.x

### 问题现象，以及你期望的结果是怎样的?

注册页面

1，在手机号码输入后，失去焦点的时候（blur） 已经做了异步验证，

2、提交表单的时候又验证了一次

请问，怎么才能在提交的时候不在验证手机号码这个字段

大牛，能写个范例吗？

**Comment by icarusion** [comment]
validateField
