### ISSUE TITLE
When [Bug Report]select OptionGroup filterable is used at the same time, search bug


### ISSUE THREAD

**Issue by javastation** [iview/iview#3910]
### Environment
mac 10.13.4 (17E202) / chrome 10.13.4 (17E202) / vue 2.5.16

### Reproduction link
[https://jsfiddle.net/6p9cykdx/2/](https://jsfiddle.net/6p9cykdx/2/)

### Steps to reproduce
搜索框输入关键字123，无搜索结果，删除搜索关键字后还是没有搜索结果

### What is expected?
删除搜索关键字后，显示所有

### What is actually happening?
删除搜索关键字后，显示无搜索结果

**Comment by nwtown** [comment]
远程搜索也是这样的.

**Comment by icarusion** [comment]
https://github.com/iview/iview/issues/4371
