### ISSUE TITLE
事件监听失效？

### ISSUE THREAD

**Issue by youziyo** [iview/iview#393]
### iView 版本号
2.0.0 rc3

### 操作系统/浏览器 版本号
Windwos 10 Chrome 57

### Vue 版本号
2.2.4

### 能够复现问题的在线示例
http://jsbin.com/xigawoveki/edit?html,js,output

### 复现步骤

不只是i-button，其他标签一样失效

**Comment by rijn** [comment]
#365 Use `click.native` instead.

**Comment by youziyo** [comment]
Do not intend to support @click or v-on:click this method?

**Comment by lihoo55555** [comment]
使用@click.native可以监听到原生事件，被坑了，在你这里找到了答案，3Q

**Comment by rijn** [comment]
@icarusion This issue can be closed.
