### ISSUE TITLE
[Feature Request]colorPicker and Input


### ISSUE THREAD

**Issue by 452486035** [iview/iview#3931]
### What problem does this feature solve?
用户可以通过复制等其他方式直接给颜色选择器赋值，而非通过鼠标在弹出的颜色面板中去选取

### What does the proposed API look like?
期望新增类型（type）和方向（direction）字段

![image](https://user-images.githubusercontent.com/20637933/41705194-dc919f78-756a-11e8-8932-e2249fd6a89f.png)
![image](https://user-images.githubusercontent.com/20637933/41705209-e8fea24c-756a-11e8-8b50-69f8cecba092.png)

**Comment by icarusion** [comment]
#4353
