### ISSUE TITLE
npm dun dev 编译速度好慢

### ISSUE THREAD

**Issue by jeodiong** [iview/iview#394]
iview2.0全部引入
每次都要6000ms-8000ms左右，去掉iview之后两百ms左右,用element 只要1000ms左右

**Comment by jingsam** [comment]
使用编译好的iview.min.js

**Comment by jeodiong** [comment]
看来开发时自定义主题不能使用import '../my-theme/index.less'，知道了

**Comment by jingsam** [comment]
你使用自定义主题的方法是对的，可能时间花在编译less上面，import Vue from ‘vue’默认是导入预编译好的dist/iview.js
