### ISSUE TITLE
After [Bug Report]2.10.0, when select is expanded, when you click on other select or input, the first is to turn off the open select and click on the other elements again to get the focus.


### ISSUE THREAD

**Issue by twoer** [iview/iview#3947]
### Environment
iView 最新版本

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
官方的 demo 页面 可以看看

### What is expected?
和之前一样 select 展开时，点击其他元素，默认关闭当前展开的 select，其他元素自动获取焦点。

### What is actually happening?
2.10.0 之后，select 展开时，点击其他select 或者 input 时，第一次是关闭打开的 select，再次点击 其他元素才能获取焦点。

**Comment by huqiliang** [comment]
3.1.3也有这个问题
