### ISSUE TITLE
Table 表格开启多选功能后（type: 'selection'） 默认选中或者禁止不管用

### ISSUE THREAD

**Issue by tanc123** [iview/iview#395]
Table 表格开启多选功能后（type: 'selection'） 默认选中或者禁用不管用啊

![12](https://cloud.githubusercontent.com/assets/13939679/23883401/a41ebb9e-08a1-11e7-9dd5-da5ac6ab5e87.png)

### iView 版本号
 0.9.10 

### 操作系统/浏览器 版本号
win10/Chrome 54 

### Vue 版本号
1.0.26

**Comment by icarusion** [comment]
iview更新下吧，这是新特性，更新到1.0.1再试试

**Comment by tanc123** [comment]
果然是版本问题的，感谢
