### ISSUE TITLE
[Bug Report]table exportcsv

### ISSUE THREAD

**Issue by wupengFEX** [iview/iview#3959]
### Environment
MAC Chrome

### Reproduction link
[https://jsfiddle.net/63p45qf7/](https://jsfiddle.net/63p45qf7/)

### Steps to reproduce
- render table and some fields are separated by ',', for example: `{"name": "Name1,name1"}`;
- export csv;

### What is expected?
data and fields correspond.

### What is actually happening?
data and fields do not correspond.

**Comment by wupengFEX** [comment]
看了下iview源码，确认不是iview的问题，是csv本身使用逗号进行分列，如果一列的字段中包含逗号，则可以通过加入双引号来解析，如原始字段为`a,b`，则导出之前需要将数据处理为`\"a,b\"`。

**Comment by jiangdi0924** [comment]
@wupengFEX  请问你是如何在导出之前处理的？

**Comment by wupengFEX** [comment]
@jiangdi0924 
```
this.source.map(row => {
    for (let k in row) {
        let item = row[k];
        if (typeof item === 'string' && item.indexOf(',') !== -1) {
            row[k] = '\"' + item + '\"';
        }
    }
})
this.$refs.table.exportCsv({
    filename: 'xx',
    original: false,
    columns: this.columns,
    data: this.source,
});
```
