### ISSUE TITLE
[Bug Report] pulled down from GIT and found some of the icons missing.


### ISSUE THREAD

**Issue by dean5277** [iview/iview#3961]
### Environment
version 2.0

### Reproduction link
[https://www.iviewui.com](https://www.iviewui.com)

### Steps to reproduce
可能是开发版本，但我觉得有几个问题应该提醒一下。
1.从GIT拉下来的工程发觉一部分图标不见了
2._ionicons-font.less 里面Ionicons.ttf 应该改成 ionicons.ttf 因为文件名就是小写的，我刚测试了个环境，编译有问题。

### What is expected?
1.希望已有的图标不要删除，因为很多已经上生产。

### What is actually happening?
如果很多图标没有了，影响和修改的地方不少。

**Comment by icarusion** [comment]
Use `2.x` branch

**Comment by ricpi** [comment]
@icarusion 请问如何切换到2.x branch
