### ISSUE TITLE
Input + Append圆角问题

### ISSUE THREAD

**Issue by ppoffice** [iview/iview#397]
### iView 版本号
2.0.0-rc.2

### 操作系统/浏览器 版本号
Windows 10/Google Chrome 56.0.2924.87(x64)

### Vue 版本号
2.2.1

### 能够复现问题的在线示例
https://codepen.io/anon/pen/BWZgqv

### 复现步骤
见CodePen

### 问题现象，以及你期望的结果是怎样的?
![image](https://cloud.githubusercontent.com/assets/8849362/23886297/d908af8c-08b4-11e7-8e72-4b3fc510ef24.png)
此处应该有圆角

### 你估计可能的原因是什么（选填）？
https://github.com/iview/iview/blob/2.0/src/components/input/input.vue#L6-L8

另外想请问下为什么现在components的name改成`Input`这样了呢？在浏览器里面如果直接使用template渲染的话会被浏览器误以为是`input`。

**Comment by icarusion** [comment]
可以使用 i-input，都支持

**Comment by xiaomizhou66** [comment]
请教一下，这个input组件的圆角怎么覆盖，用important也修改不了圆角，求解。
