### ISSUE TITLE
[Bug Report]date-picker change month Error!

### ISSUE THREAD

**Issue by umiyo** [iview/iview#3973]
### Environment
MacOS/Version 67.0.3396.87 (Official Build) (64-bit)/vue2

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
type为daterange时，切换月份，点击左侧月份为6月，右侧自动切换月份为7月；反过来操作，点击右侧月份为7月，左侧月份被切换为8月

### What is expected?
type为daterange时，切换月份，点击左侧月份为6月，右侧自动切换月份为7月；反过来操作，点击右侧月份为7月，左侧月份被切换为6月

### What is actually happening?
type为daterange时，切换月份，点击左侧月份为6月，右侧自动切换月份为7月；反过来操作，点击右侧月份为7月，左侧月份被切换为8月

---
官网示例即可进行测试，实际项目中使用版本为2.12.0，出现结果为点击6月，显示7月。

**Comment by icarusion** [comment]
## Reproduction link
https://jsfiddle.net/6b7pzowy/

## Steps to reproduce
Select right pane month to 6
## What is expected?
The left pane month is 5
## What is actually happening?
The left pane month is 7
