### ISSUE TITLE
能否将icon作为可选项

### ISSUE THREAD

**Issue by s51983** [iview/iview#399]
iView会默认加载自带的图标库，字体文件100多k。

我有自己定制的iconfont图标库，编辑css文件取消掉icon之后会导致使用图标的iview控件不能正常显示了。

可否将非必须的图标做为可选项，这样方便集成自己的图标库且能节省流量

**Comment by cenkai88** [comment]
icon你可以试下vue-svg-icon，随意定制

**Comment by s51983** [comment]
我用的iconfont，只是想把iview必须用的图标外的图标剥离掉做成可单独引入的文件，这样省流量啊

**Comment by cenkai88** [comment]
@s51983 就是单独引入iconfont的文件呀。。和iview不冲突。https://github.com/cenkai88/vue-svg-icon

**Comment by s51983** [comment]
=. =!! 是我没表达明白么。。
我的意思是iview自带的图标库我用不着啊。。。 放着占流量，全删了之后还影响iview的组件。
我是想把iview里组件里不用的图标删掉。

**Comment by anguer** [comment]
我遇到了相同的问题。。。iconfont 怎么移除。。用不着

**Comment by rijn** [comment]
@icarusion Do we have this plan? How about move `@import "iconfont/ionicons";` to `custom.less`

**Comment by icarusion** [comment]
I designed iview's original intention is a set of front-end solutions, so contains the style design, and some iview components also used a lot of icons, so there is no plan to remove it now.
