### ISSUE TITLE
[Bug Report]Tabs control inside the DatePicker control when CSS has been cut off.


### ISSUE THREAD

**Issue by menkeydyvh** [iview/iview#3995]
### Environment
所有环境

### Steps to reproduce
DatePicker在得到焦点的时候会弹出日期选择，刚好Tabs的布局把显示已外的部分都hidden了 

注意是DatePicker 的日期选择是往上弹的

主要影响的css   .ivu-tabs{
  overflow: hidden;
}

![image](https://user-images.githubusercontent.com/20472494/42120638-6567a120-7c51-11e8-8e64-675c0aaca41f.png)

### What is expected?
当然是期望不被截掉

### What is actually happening?
被截掉了

---
开发能看得懂我的意思把

**Comment by icarusion** [comment]
transfer

**Comment by linkairui** [comment]
问题没有解决吖,同问这个问题

**Comment by yxmg** [comment]
最新的版本依旧有这个问题 `ivu-table-wrapper`也有这样的问题 
@icarusion 能问下加overflow: hidden的原因是什么呢？
tabs、table里放下拉菜单或tooltip的情况不是很常见吗？
