### ISSUE TITLE
table的column中给render函数传入自定义函数时出现异常。

### ISSUE THREAD

**Issue by ulivz** [iview/iview#400]
### iView 版本号
1.0.1

### 操作系统/浏览器 版本号
Chrome 54

### Vue 版本号
1.0.26 

### 能够复现问题的在线示例

https://codepen.io/anon/pen/gmxOyQ

### 复现步骤
打开上述示例就能看到

### 问题现象，以及你期望的结果是怎样的?
这里我写了一个table类，类中有一个“添加按钮”的方法，这个方法实际上是调用了iview内置的render函数，按钮最终被渲染出来了， 但是我传入的方法被立即执行了，通过查看在线示例，我期望的结果应该是我点击之后才触发我传入的函数，但是该方法立即执行了。。。。

**Comment by toxichl** [comment]
自动执行的问题解决了，原因是我传入的这个函数立即执行了，但是就算把函数放入字符串内，会提示上下文不对....

**Comment by rijn** [comment]
Every row has its index, I recommend you use that since bind lambda function to every button in a table will cost too much.

**Comment by icarusion** [comment]
Update to the latest version
