### ISSUE TITLE
[Feature Request]Breadcrumb crumbs support custom click events


### ISSUE THREAD

**Issue by Litor** [iview/iview#4000]
### What problem does this feature solve?
目前该组件只能配置to跳转到路由，很多业务场景点击的时候是需要一些判断逻辑的，然后决定跳还是不跳。

### What does the proposed API look like?
希望可以加一个on-click事件，使用的时候on-click事件和to二者选择配置其中一个就可以了（组件目前的情况是必须配置to，不配置to，显示的就是置灰的状态了）

**Comment by icarusion** [comment]
No such plan

**Comment by Jocluby** [comment]
I want the same function
我也有同样的诉求

**Comment by fidding** [comment]
use @click.native
