### ISSUE TITLE
[Bug Report]The example 'Fixed Sider' inside Layout doesn't scroll down when collapse the submenu

### ISSUE THREAD

**Issue by YiniXu9506** [iview/iview#4004]
### Environment
Google Chrom Version 67.0.3396.99

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
I have attached the link above to run the example in jsfiddle.net

### What is expected?
Both Sider and Content should be able to scroll down when the contents inside both divs are full of the current screen.

### What is actually happening?
Sider cannot be scrolled down when you collapse the submenus. 
When you scroll down the window, the layout of Content and Sider are wired. They are totally separated.

**Comment by lvchaoin** [comment]
same requirement, thank you

**Comment by lvchaoin** [comment]
> ### Environment
> Google Chrom Version 67.0.3396.99
> 
> ### Reproduction link
> https://jsfiddle.net/api/post/library/pure/
> 
> ### Steps to reproduce
> I have attached the link above to run the example in jsfiddle.net
> 
> ### What is expected?
> Both Sider and Content should be able to scroll down when the contents inside both divs are full of the current screen.
> 
> ### What is actually happening?
> Sider cannot be scrolled down when you collapse the submenus.
> When you scroll down the window, the layout of Content and Sider are wired. They are totally separated.

Have you resolved the issue ? thank you
