### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by TimuJiang** [iview/iview#402]
调用 Message,Notice 都会报这个错
### iView 版本号
2.0.0-rc.4 

### 操作系统/浏览器 版本号
 win/electron

### Vue 版本号
2.2.4

![image](https://cloud.githubusercontent.com/assets/7578470/23894912/e65436be-08de-11e7-9f14-bda47a069bb3.png)

**Comment by TimuJiang** [comment]
const notification = new Vue({
        el: div,
        data: _props,
        components: { Notification }
    }).$children[0];

这里是不是有问题

**Comment by icarusion** [comment]
还没在 vue 2.2.4上试过，2.2.1是没有问题的。明天试一下

**Comment by TimuJiang** [comment]
那我切到2.2.1试试先

**Comment by FuShengqi** [comment]
我也遇到了这个问题，版本号："vue": "^2.1.10"，"iview": "^2.0.0-rc.6",

**Comment by fluency03** [comment]
同样的问题

**Comment by icarusion** [comment]
亲测的，2.2.4和2.2.6都没有问题：
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>iview example</title>
    <link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
    <script type="text/javascript" src="https://unpkg.com/vue@2.2.4/dist/vue.js"></script>
    <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>
</head>
<body>
<div id="app">
    <i-button @click="handleOpen">弹窗</i-button>
</div>
<script>
    new Vue({
        el: '#app',
        data: function () {
            return {
                
            }
        },
        methods: {
            handleOpen: function () {
                this.$Message.info('Hello world');
                this.$Notice.success({
                    title: 'Success.'
                });
            }
        }
    })
  </script>
</body>
</html>
```

**Comment by icarusion** [comment]
后面会统一支持 runtime

**Comment by cdmin207078** [comment]
目前我是  通过添加别名来处理的, 不知道这样对不对。
```javascript
resolve: {
    alias: {
      vue: 'vue/dist/vue.js'
    }
  }
```

**Comment by amor520** [comment]
+1
Cannot read property 'add' of undefined

**Comment by fluency03** [comment]
this is still not working on Electron + Vue

**Comment by amor520** [comment]
暂时有什么可以解决的办法吗

**Comment by willnewii** [comment]
同样的问题...   Electron + Vue

**Comment by fluency03** [comment]
可以用 electron 本身的 notification。 

[node-notifier](https://github.com/mikaelbr/node-notifier) 也是一个很不错的选择

**Comment by draco1023** [comment]
同样的问题 v2.0.0-rc.10还没修复

**Comment by zuozhan** [comment]
一样，v2.0.0-rc.10，打包的时候把dist/iview.min.js打包进去是没有问题的，没有压缩的版本还是会报这个错误

**Comment by miaosun009** [comment]
这个问题有解决办法了吗？ 我也遇到同样的问题

**Comment by willnewii** [comment]
@miaosun009 [独立构建-vs-运行时构建](https://cn.vuejs.org/v2/guide/installation.html#独立构建-vs-运行时构建)  按照官网修改为独立构建.

**Comment by miaosun009** [comment]
@willnewii  改成了独立构建，还是提示同样的错误！Electron + Vue+iview

**Comment by miaosun009** [comment]
@willnewii  因为这个问题，整个项目都暂停了，

**Comment by willnewii** [comment]
@miaosun009   你是使用了[electron-vue](https://github.com/SimulatedGREG/electron-vue)吗？你可以参照 [#168](https://github.com/SimulatedGREG/electron-vue/issues/168),我是这样改好的.

还有一种粗暴的方案,直接在node_modules/vue/package.json 修改,不过这没法维护.你可以先这样试试,锁定问题?
`"main": "dist/vue.runtime.common.js"  =>   "main": "dist/vue.common.js"`

**Comment by miaosun009** [comment]
@TimuJiang  你解决问题了吗？

**Comment by miaosun009** [comment]
@willnewii  我式了你那种粗暴的方式，发现还是提示同样的错误！！！，这是什么鬼

**Comment by miaosun009** [comment]
@willnewii  谢谢你， 按照你给我的参考，已经解决了，耗了一天，真感谢你
