### ISSUE TITLE
[Bug Report]table

### ISSUE THREAD

**Issue by iuvword** [iview/iview#4020]
### Environment
win10

### Reproduction link
[https://jsfiddle.net/rxqa690k/20/](https://jsfiddle.net/rxqa690k/20/)

### Steps to reproduce
带有 children 的 columns 在 created 之后修改 就会报错，报错如下
You may have an infinite update loop in watcher with expression "columns"
而且此时只有延迟传入 data 表格才能正常显示

### What is expected?
不会报错

### What is actually happening?
报错

---
当 columns 需要从后台得到的数据获取时，则获取数据后 才能得到 columns ，此时就会报错

**Comment by Xiayanduo** [comment]
发现类似问题，当table 的columns拥有children时 v-if =true ，显示出来浏览器就卡死了

**Comment by David-Tsui** [comment]
同樣問題，dev時僅報錯，build完這error變成直接卡死瀏覽器

**Comment by icarusion** [comment]
#3472
