### ISSUE TITLE
有支持TreeTable或者TreeGrid树形表格组件的计划吗？

### ISSUE THREAD

**Issue by BruceAn1978** [iview/iview#4023]
之前使用的很多UI框架ExtJs，EasyUI，MiniUI等提供树形表格控件，这个控件在后端管理系统中很常用。

Tree组件表现的信息丰富程度较差，往往还需要右侧配合一个Table来辅助展现。而Table组件又无法展示一个树状的数据层级关系。所以树形表格组件就是专门解决这一类需求的。

也有网友开发了第三方的插件来支持，但是后续持续改进和组件的质量都难以保障。

**强烈建议官方考虑添加树形表格组件的功能！
同时希望iview越来越强大！**

**Comment by BruceAn1978** [comment]
这是一个功能需求，请有同样需求的开发者一块顶一下，好让官方早点加入该组件！

**Comment by SoyMeng** [comment]
确实有这个需求

**Comment by BruceAn1978** [comment]
自己顶一下。

**Comment by BruceAn1978** [comment]
up

**Comment by BruceAn1978** [comment]
up

**Comment by BruceAn1978** [comment]
up

**Comment by BruceAn1978** [comment]
up

**Comment by BruceAn1978** [comment]
up

**Comment by whatupwoman** [comment]
up
