### ISSUE TITLE
[Bug Report]When I use iview@2.14.3, the style and component language are not displayed when datepicker components are used in IE9~10.

### ISSUE THREAD

**Issue by xeanyee** [iview/iview#4028]
### Environment
IE9 and IE10

### Reproduction link
[https://github.com/xeanyee/my-demos](https://github.com/xeanyee/my-demos)

### Steps to reproduce
 My code is as follows: run in IE9 or IE10 browser, click datepicker to select and switch language, then select time again to reproduce.

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>iview datepicker</title>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/iview/dist/styles/iview.css">
  <script type="text/javascript" src="https://vuejs.org/js/vue.min.js"></script>
  <script type="text/javascript" src="https://unpkg.com/iview/dist/iview.min.js"></script>
  <script type="text/javascript" src="//unpkg.com/iview/dist/locale/en-US.js"></script>
  <script type="text/javascript" src="https://cdn.bootcss.com/babel-polyfill/6.22.0/polyfill.min.js"></script>
</head>

<body>
  <div id="app">
    <date-picker type="daterange" placeholder="Select date" style="width: 200px"></date-picker>
    <i-button @click="changeLang">{{ langBtn }}</i-button>
  </div>
  <script>
    
    new Vue({
      el: '#app',
      data: {
        langBtn: '切换为英文'
      },
      methods: {
        changeLang: function() {
          this.langBtn == 'en-US'
          iview.lang('en-US')
        }
      }
    })
  </script>
</body>
</html>

### What is expected?
When I use internationalization (en-US.js), I want iView's datepicker components to behave in IE9 and IE10 as well as Google.

### What is actually happening?
1. When I switch the iView component language from Chinese to English, the month that the datepicker component pops up is not correct. The specific performance is that the month shows the Chinese year；
2. When I use datepicker components under IE, the menu options pop-up have scrollbars.

**Comment by Xotic750** [comment]
https://github.com/iview/iview/blob/2.0/package.json#L125

**Comment by Xotic750** [comment]
You could try https://github.com/es-shims/es5-shim
As it has fixes for Date and that may (and that is just a may) allow you to run it on these browsers.

**Comment by xeanyee** [comment]
Oh, that's the way. Although iView is pretty good, I think I can only use other UI components, such as element-ui. Thank you.

**Comment by ClearFish** [comment]
datepicker在繁体的情况下为什么不生效啊
