### ISSUE TITLE
出现vue warn 

### ISSUE THREAD

**Issue by tangolivesky** [iview/iview#403]
### iView 版本号
1.0.1 

### 操作系统/浏览器 版本号
Chrome 54

### Vue 版本号
 2.2.4 

### 问题现象，以及你期望的结果是怎样的?

![qq 20170314193024](https://cloud.githubusercontent.com/assets/3411973/23898660/d281caf8-08ec-11e7-8ba0-eab0c689a32e.png)

**Comment by icarusion** [comment]
2.0.0-rc.4已经修复
