### ISSUE TITLE
sometimes we need endTime < startTime 😕, may be provide an option ?

### ISSUE THREAD

**Issue by Syntaxe3** [iview/iview#4038]
https://github.com/iview/iview/blob/a8e7c029a07fc541fc1e38dc76d270c9dcbc001f/src/components/date-picker/panel/Time/time-range.vue#L143

**Comment by Xotic750** [comment]
Can you provide us with some use case?

**Comment by Syntaxe3** [comment]
just like system updating time from 11:00 pm to 1:00am ?
