### ISSUE TITLE
2.0 的Modal 的bug

### ISSUE THREAD

**Issue by miaosun009** [iview/iview#404]
2.0 的Modal 有bug

` <button @click="modal1=true" class="add-but">
      <Icon type="plus-round"></Icon>
    </button>
    <Modal :value.sync="modal1" title="普通的Modal对话框标题">
      <p>对话框内容</p>
      <p>对话框内容</p>
      <p>对话框内容</p>
    </Modal>`
这样的写法， 弹出一次 关闭了之后就再也弹不出来了

**Comment by icarusion** [comment]
Vue2没有sync，使用v-model

**Comment by lichinlichin** [comment]
v-model能改变使用者初始数据吗？
