### ISSUE TITLE
[Bug Report]同一页面存在多个DatePicker时需点击两次才能触发

### ISSUE THREAD

**Issue by Sasha-XS** [iview/iview#4043]
### Environment
windows10/Chrom 67.0.3396.87/Vue2.5.2

### Reproduction link
[https://jsfiddle.net/w216sdge/66/](https://jsfiddle.net/w216sdge/66/)

### Steps to reproduce
页面存在两个及以上手动触发的DatePicker, 先触发第一个DatePicker的显示，在不关闭也没有点击其他元素的情况下直接点击第二个DatePicker的事件源，第一次点击事件不会触发，需点两次才能触发click事件（更新到2.14版本后出现该问题，官网Demo同样存在）。

### What is expected?
第一次点击事件源能够触发click事件

### What is actually happening?
需点击第二次才能触发click事件

**Comment by icarusion** [comment]
就是这样设计的，去了解 W3C 规范。
