### ISSUE TITLE
[Feature Request]不同类型的Message提示框是否可以自定义外层容器样式

### ISSUE THREAD

**Issue by Sasha-XS** [iview/iview#4044]
### What problem does this feature solve?
现在的Message有success,warning, error等几种类型，但是外层容器的样式名都是一致的，希望至少到ivu-message-notice-content这一层能多一个类名来表示不同类型的Message，方便自定义不同类型Message的容器样式

### What does the proposed API look like?
需求： 不同类型的Message可以自定义不同的样式，现有的用于区别的样式名层级太低不利于修改
支持给不同类型的Message自定义外层容器样式，或者加上用于区别的类名可以自定义样式覆盖原有的样式；

**Comment by icarusion** [comment]
No such plan
