### ISSUE TITLE
[Bug Report]【BUG】 表格组件 固定高度 设置可展开 当多个展开 超出表格高度后 不会出现滚动条 遮挡了展开内容

### ISSUE THREAD

**Issue by showbestriven** [iview/iview#4047]
### Environment
win10 x64

### Steps to reproduce
表格组件 固定高度 设置可展开 当多个展开 超出表格高度后 不会出现滚动条 遮挡了展开内容

### What is expected?
期望结果 表格会出现滚动条

### What is actually happening?
未出现 遮挡住了内容

**Comment by taojunnan** [comment]
同样的问题 请问解决了吗

**Comment by showbestriven** [comment]
@taojianjian32 并没有

**Comment by taojunnan** [comment]
我暂时是这样做的，覆盖iview默认样式
.ivu-table-body{
    overflow-y: auto;
    overflow-x: auto;
}
