### ISSUE TITLE
select选择器选择onchange事件错误多次调用

### ISSUE THREAD

**Issue by umbrellary** [iview/iview#405]
### iView 版本号
2.0.0-rc.4

`<i-option v-for="item in cityList" :key="item" :value="item.value" :on-change="submit(item.value)">{{ item.label }}</i-option>`

submit被调用了cityList.length次

**Comment by icarusion** [comment]
@on-change 是在 select 上的

**Comment by HUANGChaoLi** [comment]
感觉这个on-change的名字让人感觉好迷茫，能不能换成change或者其他的名字呢，因为语义上@change已经是onChange了，如果再加多一个就相当于onOnChange了，感觉不符合直观感受。

**Comment by p2ng** [comment]
应该要支持一个`on-select`事件
默认的表单初始化的时候data改变了，就会触发`on-change`事件，这个很恶心。
要自己业务代码判断当前状态是否为初始化，才能触发`on-change`
@icarusion

**Comment by qinghua5453** [comment]
我也出现多次触发的问题，第一次还ok，第二次下拉 就会两次触发，第一次是无效触发

**Comment by sadenwang** [comment]
塞入数据后会触发on-change事件，太恶心了，很难发现的BUG
