### ISSUE TITLE
[Feature Request]tree组件功能

### ISSUE THREAD

**Issue by orchie** [iview/iview#4050]
### What problem does this feature solve?
希望可以 新功能：

1. 自定义tree的显示名字 ，现在是写死的 “title”。
2. 复选框下 ，可以只选择父节点而不选择任何子节点(取消关联性) 便利性 :现在使用了 “expand” 判断是否可以展开，但事实上可以通过判断是否存在children及 children长度来判断是否可以展开。

### What does the proposed API look like?
参考element-ui，用过element-ui后才接触的iview，然后感觉iview比ele好多了，今天用到tree之后终于发现了iview还是有不足ele的组件的。这个需求是很普遍的，如 https://segmentfault.com/q/1010000012064522/a-1020000012239434 这位给出了遍历改变字段为title的方法， https://www.jb51.net/article/137398.htm 这里提供了将ele的tree改到iview中使用的方法，但还是希望iview可以出这个新功能，3.0也快出了，希望iview越做越好

PS：by english:hope Tree  can like elment-ui 's el-tree ,:smile

**Comment by 5201314999** [comment]
不用render 的话，node 节点根本没api 可以修改node 本身。建议参考jquery ztree的api 。

例如我用了iview tree 基本用法，然后想实现类似element 的模糊搜索展开功能，是不是只有重新修改:data="data1" 这个属性？

还有在某个节点动态增删节点。展开某个节点。这些功能。
