### ISSUE TITLE
[Bug Report]2.14.1 tabs 移除第一个节点时， content 中visibility: hidden未置为 visible （remove first node, content sibling el still hidden）

### ISSUE THREAD

**Issue by Nosnickers** [iview/iview#4052]
### Environment
chrome 67/ vue 2.5.16

### Reproduction link
[https://jsfiddle.net/j0q12fsh/89/](https://jsfiddle.net/j0q12fsh/89/)

### Steps to reproduce
删除第一个节点 (remove first node)

### What is expected?
第二个节点应该显示出来 (second el title shows, but content is hidden)

### What is actually happening?
第二个节点只显示了title，content被隐藏了(second el title shows, AND content shows)

**Comment by Nosnickers** [comment]
2.13.1是好的；项目迁移到2.14.1就出现这个问题了.(Good on 2.13.1)

**Comment by huangzhilin** [comment]
你现在是怎么处理的

**Comment by Nosnickers** [comment]
@huangzhilin 暂时使用的是2.13.1

**Comment by leixu2txtek** [comment]
```javascript
handleRemove(index) {
      const tabs = this.getTabs();
      const tab = tabs[index];

      // 此处 destroy 后 tabpane 下面的dom元素依然存在
      // this.navList 数组长度已经少了一个，但是 getTabs 返回的依然是原始长度
      // 导致 更新显示状态时候索引没有对上
      tab.$destroy();

      if (tab.currentName === this.activeKey) {
        ...
      }
      this.$emit("on-tab-remove", tab.currentName);
      this.updateNav();
    },
```

tab 在 destroy 后 tabpane 下面的dom元素依然存在
this.navList 数组长度已经少了一个，但是 getTabs 返回的依然是原始长度
导致在 updateVisibility 更新显示状态时候索引没有对上

**Comment by silencyXiao** [comment]
我也是遇到类似的问题，页面跳转动态切换tabpanel 之后变成了空白的，更新iview版本到2.14.1之后才出现的，因为2.14.1版本的解决了之前遇到的一些问题，所以更回之前的版本又不行，有没有临时可以处理的方案

**Comment by IceApriler** [comment]
@silencyXiao #4120 我提了个merge.不过你可以先设置一个setTimeout(() => {}, 500)，等500ms或者更长后，再切换pane。

**Comment by IceApriler** [comment]
我排查了一下问题，如下图：
![image](https://user-images.githubusercontent.com/29689307/43260706-cf5c82ba-910c-11e8-9540-5be7768d4eb5.png)

我的console是这样的：
![image](https://user-images.githubusercontent.com/29689307/43260803-0cf68454-910d-11e8-9072-31866c88768d.png)

![image](https://user-images.githubusercontent.com/29689307/43260865-43bbafbe-910d-11e8-8023-d34e8e43413d.png)

我们发现在删除tab和pane后，updateVisibility()获取到的panes不是最新的。我起初以为是因为销毁pane的操作放在了“this.activeKey = activeKey”之后，所以才没有获取最新的panes，如下图：

![image](https://user-images.githubusercontent.com/29689307/43260906-69833b68-910d-11e8-9623-691798c9fb04.png)

但是这样我改成下面这样的代码后，试了试还是不可以，获取到的依然是三个pane，不是最新的。

![image](https://user-images.githubusercontent.com/29689307/43261331-e0b996d6-910e-11e8-97bb-3b9d700ab2fa.png)

所以我觉得是时候使用this.$nextTick()了，如下代码：

![image](https://user-images.githubusercontent.com/29689307/43261143-4dcd5344-910e-11e8-8aa2-36a27f1dc089.png)

然后问题就解决了。
![image](https://user-images.githubusercontent.com/29689307/43261222-8c975c32-910e-11e8-8aa7-a7069edcd835.png)

不过说实话，抛开dom的问题，从语义上也应该如倒数第三章图那样将`this.$emit('on-tab-remove', tab.currentName)` 放在`this.activeKey = activeKey`更新之前。

不过我最后还是有一个问题，就是为什么`this.$emit('on-tab-remove', tab.currentName)` 可以触发销毁pane，别的地方我找了一圈都没有找到相关代码……汗，不知道有没有哪位能解我疑惑？

最后再更新一下，如果为updateVisibility()使用this.$nextTick()后，也可以解决 #4120 的问题。而不再需要添加setTimeout()，如下图，我试了试是可行的：

![image](https://user-images.githubusercontent.com/29689307/43261964-146b8a5a-9111-11e8-8a2a-f7ca701283ec.png)

不过最重要的事，我不知道之前开发人员使用setTimeout()的初衷是什么，所以一时拿不定主意该怎没解决这个问题。如果setTimeout()完全是为了等待获取dom的话，我觉得已经完全被this.$nextTick()替代了。

**Comment by leixu2txtek** [comment]
@IceApriler  实际在点击删除时候，内部仅仅将 tab 销毁了，pane都没有销毁，需要在 on-tab-remove之后处理，但是 这个是一个异步的方法，其实 应该在删除之后再执行updateVisibility 的。

我得出的结论是 调用 updateVisibility 时 ，pane 并没有移除；

我们的场景是 ，循环一个数组生成的 tabs ，删除后，我们手动移除数组项

**Comment by IceApriler** [comment]
@leixu2txtek 是的！谢谢！我发现是在on-tab-remove事件触发后，手动删除的。一直没注意on-tab-remove业务代码。

**Comment by leixu2txtek** [comment]
@IceApriler 这个bug 是因为 将 display 改为 Visibility 导致的

**Comment by icarusion** [comment]
#4296
