### ISSUE TITLE
Tree Component: IE11 error "on-selected"

### ISSUE THREAD

**Issue by dgroh** [iview/iview#4055]
There is an issue with iView Tree Component on IE 11.

That is the error:

> [Vue warn]: Error in event handler for "on-selected": "TypeError: The object does not support property or method" findIndex "

This happens when I select a node in the Tree.

**Comment by dgroh** [comment]
I added babel-polyfill and it fixed the issue

**Comment by gabdsh** [comment]
> I added babel-polyfill and it fixed the issue

Hi. i use vue cli3 , and babel-polyfill is default settings, but i have this error, can you help me?
