### ISSUE TITLE
[Feature Request]this.$Modal.success(config)无法配置弹窗确认按钮的大小

### ISSUE THREAD

**Issue by yeohx** [iview/iview#4063]
### What problem does this feature solve?
class="ivu-btn ivu-btn-primary ivu-btn-large" 只能是默认的ivu-btn-large，config里面没有配置按钮大小的参数

### What does the proposed API look like?
希望能再config里面增加配置按钮大小的选项

**Comment by icarusion** [comment]
No such plan
