### ISSUE TITLE
[Bug Report]TimePicker disabled doesn't work

### ISSUE THREAD

**Issue by lstoryc** [iview/iview#4064]
### Environment
windows 7 /  chrome 67 / Vue v2.5.16

### Reproduction link
[https://jsfiddle.net/p160x5rq/2/](https://jsfiddle.net/p160x5rq/2/)

### Steps to reproduce
如上面链接，样式上已经禁用了，不知道为何点击右侧时间图标后弹出时间选择层，理论所有事件都禁用的

### What is expected?
disabled为true，点击右侧时间图标， 不显示选择时间的层

### What is actually happening?
disabled为true时，点击右侧时间图标，显示了时间选择弹出层

**Comment by leixu2txtek** [comment]
为什么关闭了？

**Comment by lstoryc** [comment]
我自身问题，

**Comment by leixu2txtek** [comment]
问题存在的

**Comment by lstoryc** [comment]
https://jsfiddle.net/p160x5rq/2/  加上 readonly 可解决
