### ISSUE TITLE
[Feature Request]Transfer提供排序功能

### ISSUE THREAD

**Issue by minixu** [iview/iview#4068]
### What problem does this feature solve?
Transfer数据穿梭时可能会对数据有顺序要求，希望可以出一个上下调整顺序的功能， 例如↑↓ 这样的图标跟在每项数据后面，或者直接通过拖拽数据项去调整顺序

### What does the proposed API look like?
Transfer增加一个属性 sort  ，取值为true或者false，true时开启排序功能，出现↑↓跟在数据项后，用来调整数据项的上下顺序。

**Comment by icarusion** [comment]
No such plan
