### ISSUE TITLE
[Feature Request]component page add Page scrollTo events 

### ISSUE THREAD

**Issue by Beats0** [iview/iview#4071]
### What problem does this feature solve?
when click the pageNum, the window can scroll to top or bottom automatic, instead of  stop at the original view position

### What does the proposed API look like?
Property | Description| Type | Default
---|-----| ---|---|
scrollTo | window scroll to top or bottom automatic when click. Optional: top,bottom, Default not set   | String     | -    |

**Comment by icarusion** [comment]
You have to implement it yourself
