### ISSUE TITLE
The [Bug Report] system sets the time zone Canada UTC-4 area, selects a date, and the control displays less than one day.


### ISSUE THREAD

**Issue by lalaxyv** [iview/iview#4078]
### Environment
win10/Google Chrome 63

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
随便选一个日期

### What is expected?
显示正确

### What is actually happening?
系统设置时区 加拿大 UTC-4区 ，选择一个日期，控件显示少了一天。

**Comment by Steffan-Carlos** [comment]
same as #3881

**Comment by SergioCrisostomo** [comment]
This has beed fixed in `v3.1.0`, please reopen if you still see the problem.
