### ISSUE TITLE
[Bug Report]AutoComplete  should display label instead of value (AutoComplete显示不了label，只能显示value）

### ISSUE THREAD

**Issue by TonyLuo** [iview/iview#4090]
### Environment
macos

### Reproduction link
[https://jsfiddle.net/cv67ku4t/2/](https://jsfiddle.net/cv67ku4t/2/)

### Steps to reproduce
https://jsfiddle.net/cv67ku4t/2/

### What is expected?
选中选项后，input里要显示label里，而不是value

### What is actually happening?
选中选项后，input里只能显示value里的内容

**Comment by TonyLuo** [comment]
无人回复，自己顶上去

**Comment by TonyLuo** [comment]
@lison16 @icarusion

**Comment by leixu2txtek** [comment]
最后换成 select 了，确实存在这个问题
