### ISSUE TITLE
[Bug Report]validate (data is numeric), wants to judge the required and digital format, and `is not a string`. If I add type=number to rule, when I fill in the text, I can only hint that it is not empty.


### ISSUE THREAD

**Issue by lpg666** [iview/iview#4093]
### Environment
node 8.11.3 vue-cli2.0

### Reproduction link
[http://www.baidu.com（暂无法发出代码）](http://www.baidu.com（暂无法发出代码）)

### Steps to reproduce
我要检查input不为空和只能是数字

{ required: true, message: '菜单排序不能为空', trigger: 'blur' } 输入数字报`weight is not a string`

{ type: 'number', required: true, message: '菜单排序不能为空', trigger: 'blur' } 输入数字没问题，输入文本却提示`菜单排序不能为空`，提示错误了

{ required: true, message: '菜单排序不能为空', trigger: 'blur' },
{ type: 'number', message: '格式为数字', trigger: 'blur' }
输入数字却提示`菜单排序不能为空`

### What is expected?
提示正确

### What is actually happening?
提示失败

**Comment by aoping** [comment]
这个问题不解决么？
