### ISSUE TITLE
[Bug Report]Select list options cannot have an empty string value

### ISSUE THREAD

**Issue by gkovats** [iview/iview#4095]
### Environment
Firefox 61.1, Chrome 67.03

### Reproduction link
[https://jsfiddle.net/vnkojr9g/7/](https://jsfiddle.net/vnkojr9g/7/)

### Steps to reproduce
See fiddle. We have need to include an initial / default option with an empty string ("") value. When you add this value in an option, selecting it sets model value to undefined.

### What is expected?
Expect that when an option value is "" and it's selected, the model value should be "".

### What is actually happening?
Model value becomes undefined.

**Comment by icarusion** [comment]
Suggest to use `placeholder`

**Comment by vikyd** [comment]
support empty string.  +1

placeholder is not the point.
