### ISSUE TITLE
[Bug Report]table component table-body: key= "row._rowKey" should not be maintained by components. It should be an option.


### ISSUE THREAD

**Issue by xingzheone** [iview/iview#4099]
### Environment
win10 chrome  vue2 

### Reproduction link
[https://stackoverflow.com/questions/43074144/vue-js-input-field-loses-its-focus-after-entry-of-one-character](https://stackoverflow.com/questions/43074144/vue-js-input-field-loses-its-focus-after-entry-of-one-character)

### Steps to reproduce
如果 table row 中有input 则输入后,因为  table-body   :key="row._rowKey"  都会     所以每次都会 re- render 导致焦点丢失,页面抖动.  

### What is expected?
 把 table-body   :key="row._rowKey"  :key 作为选项暴露出来,或直接去掉该key .  我们现在的版本就是自己 
npm run dist iview的. 直接去掉符合预期

### What is actually happening?
如果 table row 中有input 则输入后,因为  table-body   :key="row._rowKey"  都会     所以每次都会 re- render 导致焦点丢失,页面抖动.  

---
如果 table row 中有input 则输入后,因为  table-body   :key="row._rowKey"  都会     所以每次都会 re- render 导致焦点丢失,页面抖动.

**Comment by xingzheone** [comment]
首先祝贺,3.0发布会成功发布 . 这个issues 快半个月了.

**Comment by YuGe** [comment]
Any update? This is really import when the table is long

**Comment by IanSun** [comment]
Closes #3816

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/76ae3e8853e64dc64d138f665b389a1ba4962035
