### ISSUE TITLE
[Bug Report]Select multiple mode updates data without emptying the data that does not exist.


### ISSUE THREAD

**Issue by huanghong1125** [iview/iview#4111]
### Environment
2.14.3

### Reproduction link
[https://jsfiddle.net/yyrzhm46/1527/](https://jsfiddle.net/yyrzhm46/1527/)

### Steps to reproduce
1：select选择1，2，3，4
2：点击Change Data，

### What is expected?
选择的项中只有1

### What is actually happening?
选择的项中有1，2，3，4

**Comment by icarusion** [comment]
change the selected value
