### ISSUE TITLE
[Bug Report]Threre is a big bug in Radio component

### ISSUE THREAD

**Issue by zhoucumt** [iview/iview#4114]
### Environment
mac chrome 67

### Reproduction link
[https://jsfiddle.net/ozkrm8xe/4/](https://jsfiddle.net/ozkrm8xe/4/)

### Steps to reproduce
1.There is two buttons called at1 and at2 in the page after rendered.
2.Click at2 button and then you will see that group1 radios disappeared and the second group appeared.This is ok,but you will find that the first radio is not checked!

### What is expected?
the correct result should be that the radio called '爪哇犀牛' is checkd because in the method at2, I have writed that this.animal = '爪哇犀牛'

### What is actually happening?
the radio is not checked when swtich the v-if

**Comment by oyv1cent** [comment]
[https://jsfiddle.net/ozkrm8xe/14/](https://jsfiddle.net/ozkrm8xe/14/)
maybe this can show why cause this problem, if value haven't change,it will not work.

**Comment by oyv1cent** [comment]
i find the reason that why cause this problem, and i will submit a Pr

**Comment by leixu2txtek** [comment]
https://jsfiddle.net/leixu2txtek/ozkrm8xe/20/

add key property and that it's ok ?
