### ISSUE TITLE
v-ref  [Vue warn]: Failed to resolve directive: ref  (found in <Anonymous> - use the "name" option for better debugging messages.)

### ISSUE THREAD

**Issue by WLyKan** [iview/iview#412]
### iView 版本号
[文档地址](https://www.iviewui.com/components/form)
https://www.iviewui.com/components/form

### Vue 版本号
`"vue": "^2.2.2"`

### 能够复现问题的在线示例

> v-el 和 v-ref 合并为一个 ref 属性了
[详见](https://cn.vuejs.org/v2/guide/migration.html#v-el-和v-ref-替换)

**Comment by icarusion** [comment]
不知所言
