### ISSUE TITLE
[Feature Request] requires Tree control to provide API that eliminates the linkage between parent and child node selection boxes.


### ISSUE THREAD

**Issue by Relucent** [iview/iview#4121]
### What problem does this feature solve?
目前 iveiw  Tree控件 父节点与子节点复选框状态必须是有关系的。

因为存在需要独立控制节点的复选框状态的场景（不能简单用 selected多选来替代，选框和选中含义不同)。所以需要能够提供一种消除复选框联动的机制。

### What does the proposed API look like?

增加一个属性，例如 checkrel
当 checkre==true 时 (默认），节点选择框联动，即勾选父节点选择框子节点自动全选。
当 checkre==false 时，父节点与子节点选择框不联动

**Comment by icarusion** [comment]
No such plan
