### ISSUE TITLE
[Bug Report]iview carousel in model not use

### ISSUE THREAD

**Issue by guopeng-blogs** [iview/iview#4123]
### Environment
liunx/All/vue

### Reproduction link
[https://jsfiddle.net/ChenGuop/y6opxah1/15/](https://jsfiddle.net/ChenGuop/y6opxah1/15/)

### Steps to reproduce
#iview carousel in modal not use
1.modal
2.carousel

### What is expected?
modal show carousel

### What is actually happening?
iview carousel in modal not use

**Comment by llccing** [comment]
@guopeng-blogs 问题已经解决，但是这种方式可能作者不推荐---> [解决](https://jsfiddle.net/lcf33123/tmbcp3g4/)

```js

setTimeout(() => {
    this.$refs.carouselDom.handleResize();
}, 1);

```
handleResize方法是carousel组件的一个方法，这个方法会重新计算组件的宽度，因为modal默认是隐藏的，所以初始时宽度不能计算进去。
因此我的办法就是在展示modal后，在手动初始化carousel组件。
