### ISSUE TITLE
[Bug Report]Modal nesting problem


### ISSUE THREAD

**Issue by qints** [iview/iview#4124]
### Environment
Win7/Chrome 63.0.3239.108 (64)/Vue 2.2.1

### Reproduction link
[https://jsfiddle.net/qints/03sjbo7n/](https://jsfiddle.net/qints/03sjbo7n/)

### Steps to reproduce
先点击按钮，打开一个Modal - 1，再打开一个另外一个Modal - 2，然后点击ESC键一次

### What is expected?
点击ESC键一次，期望只关闭Modal-2，而不关闭Modal-1

### What is actually happening?
两个Modal都被关闭了

**Comment by David-Tsui** [comment]
https://jsfiddle.net/0fqwsLzy/

**Comment by qints** [comment]
This is a solution temporarily，but I think it does not solve the problem in essence. If there have three or more Modal ,I have to control so many Modal's "closable" props.

**Comment by David-Tsui** [comment]
So you are going to make an ad-spam modal cluster, good!
Think about UX, plz.

**Comment by qints** [comment]
I don't want a modal cluster.
I mean you may solve the problem using a better way，instead of control "closable" props.
so programmer can get a better User's experience~
