### ISSUE TITLE
[Bug Report]datePicker component shortcuts chooses to report errors when value () returns to a non standard date.


### ISSUE THREAD

**Issue by ycosine** [iview/iview#4127]
### Environment
masos / chrome 67.0.3396.99

### Reproduction link
[https://jsfiddle.net/cosine886/ezq9tu1w/10/](https://jsfiddle.net/cosine886/ezq9tu1w/10/)

### Steps to reproduce
1.使用datePicker组件的shortcuts功能
2.在shortcuts配置中使用字符串时间格式，例如'YYYY-MM-DD', 'YYYY-MM-DD HH:mm'
3.无法正常使用shortcuts功能，报错。

### What is expected?
期望正常使用shortcuts功能

### What is actually happening?
报错，且无法使用，需要为Date对象标准格式

**Comment by VanMess** [comment]
我在[官网例子](https://www.iviewui.com/components/date-picker)上做了个[小改动](https://jsfiddle.net/fanwenjie/mgqs594d/)，没想到还真触发这个问题了...

甚至试着传进 `format="yyyy-MM-dd"`也还是报错。。。
