### ISSUE TITLE
[Bug Report]TimePicker select question

### ISSUE THREAD

**Issue by lily199299** [iview/iview#4128]
### Environment
Mac  Chrome   vue: "^2.5.2"

### Reproduction link
[https://www.iviewui.com/components/time-picker](https://www.iviewui.com/components/time-picker)

### Steps to reproduce
When I forbid choosing zero,and hide it, firstly,I choose the minutes,But the zero point shows，that's not what I expected

### What is expected?
I want  to select an hour and then a minute，and  tthen I  can choose second

### What is actually happening?
hour minute second ，They have no order

---
当我禁止了0点，并且隐藏它，然后我先选择分钟，默认的选择了0点，我期望的是  先选择小时，才可以选择分钟，然后才能选择秒

**Comment by oyv1cent** [comment]
you can set format's value,and it will return a data without hour
```js
<TimePicker format="HH:mm" placeholder="Select time" style="width: 112px" @on-change="test"></TimePicker>
```

if you want a sequential choice, u can use disabled-hours/disabled-minutes/disabled-seconds to do this
