### ISSUE TITLE
Tabs: TabPane native click event not working

### ISSUE THREAD

**Issue by humoyun** [iview/iview#4135]
I need tabs component and it should be removable, iview tabs has closable prop but it does give any way to customize it, e.g., if 'x' button in tab-pane is clicked it is not giving an option whether to remove or not, currently it removes tab-pane and emits 'on-tab-remove' event. So I tried with native click event on tab-pane, but but it is not working. 

1. iView should give option to control removing rather than removing without giving any way
2. Native event should be supoorted: `@click.native='handleTabPaneRemove'`

**Comment by Humoyun** [comment]
very bad, you are not professional
