### ISSUE TITLE
[Bug Report]Tabs: TabPane native click event not working

### ISSUE THREAD

**Issue by humoyun** [iview/iview#4136]
### Environment
Mac Chrome vue: "^2.5.2"

### Reproduction link
[https://jsfiddle.net/humoyun/p0yL9ojn/](https://jsfiddle.net/humoyun/p0yL9ojn/)

### Steps to reproduce
iView tabs have closable prop but it does not give any way to customize it, e.g., if 'x' button in tab-pane is clicked it is not giving an option whether to remove or not, currently it removes tab-pane and emits 'on-tab-remove' event. So I tried with the native click event on tab-pane, but it is not working.

### What is expected?
I need tabs component to be removable on demand:
iView should give an option to control removing rather than removing without giving any way to control or native event should be supported: @click.native='handleTabPaneRemove'

### What is actually happening?
the native click event is not working on tab-pane of tabs

**Comment by icarusion** [comment]
Wrong link
