### ISSUE TITLE
When [Bug Report]Moda is directly placed on V-for, the V-for rendering is abnormal when the data traversed by V-for is updated.


### ISSUE THREAD

**Issue by wujian-nerc** [iview/iview#4137]
### Environment
window 7 / Chrome 67.0.3396.99 / Vue 2.14.3

### Reproduction link
[https://codepen.io/JaneWu/pen/vaJyVy](https://codepen.io/JaneWu/pen/vaJyVy)

### Steps to reproduce
点击Click me 1

### What is expected?
v-for遍历的数据发生更新时，页面能够正常渲染更新之后的结果

### What is actually happening?
v-for遍历的数据发生更新时，更新之后数据没有被渲染出来

---
1.在v-for外面嵌套一个div，可以解决该问题，点击Click me 2可以查看效果。
2.把Modal放到v-for之前

可能的原因参考文档：
https://blog.csdn.net/tearsknow/article/details/78412227

**Comment by David-Tsui** [comment]
wrong link

**Comment by wujian-nerc** [comment]
@David-Tsui, sorry, reproduction link: [https://codepen.io/JaneWu/pen/vaJyVy ](https://codepen.io/JaneWu/pen/vaJyVy)
