### ISSUE TITLE
[Bug Report]iview wheel assembly is a very strange problem. When rotating, the @click event written in the wheel will alternate.


### ISSUE THREAD

**Issue by H-Sven** [iview/iview#4138]
### Environment
vue2.x

### Reproduction link
[https://segmentfault.com/q/1010000015763627](https://segmentfault.com/q/1010000015763627)

### Steps to reproduce
这是复制自Carousel 走马灯 iview的轮播组件，我在其中一个CarouselItem 中添加了一个div 并且绑定了@click事件，每次轮播到这个CarouselItem 的时候，点击里面的div上的click事件，会出现交替无法点击的情况
希望有大佬试试这个现象，我不确定是我写法上的问题，还是组件自身的问题

### What is expected?
每次都能点击这个@click事件

### What is actually happening?
每次轮播到这个CarouselItem 的时候，点击里面的div上的click事件，会出现交替无法点击的情况

**Comment by IceApriler** [comment]
It is recommended that you use jsfiddle.net to reproduce the problem so that volunteers can solve the problem.

**Comment by H-Sven** [comment]
@IceApriler  

https://segmentfault.com/q/1010000015763627

 您可以点击我的这个链接查看 更详细的说明，这应该是iview自己的bug，希望能够尽快解决这个问题
You can click on this link to see a more detailed description, this should be iview's own bug, I hope to solve this problem as soon as possible.
