### ISSUE TITLE
[Bug Report] asynchronous Select option displays incorrect


### ISSUE THREAD

**Issue by Ludidi** [iview/iview#4139]
### Environment
windows /  Chrome 67.0.3396.62 / vue 2.5.2 / iview 2.14.3

### Reproduction link
[https://jsfiddle.net/v5s2j3h8/98/](https://jsfiddle.net/v5s2j3h8/98/)

### Steps to reproduce
两个问题：
1.下拉选项会从多个变为上一个选择的
重现步骤：点击加载按钮，选中第一个选择框，点击重置按钮，再次选择第一个选择框，只会选择上一次点击的选项
2.第二个联动选项为空，输入空格才会显示
重现步骤：选中第一个选择框，第二个选择后为空，输入字符才会出现

### What is expected?
1.直接显示所有的选项
2.联动选择

### What is actually happening?
1.会显示上一次点击的选项
2.联动选择效果不友好

---
初入vue，可能表达的不太清楚，如有疑问我会尽快回复，也希望自己能够去源码当中解决此问题去学习，希望iview越做越好

**Comment by IceApriler** [comment]
你的代码reset的时候有问题。
```html
<i-select clearable
                  filterable
                  v-model="model1"
                  style="width:200px"
                  @on-change="selectChildren">
```
当你reset的时候会触发selectChildren事件。
```JavaScript
selectChildren (index) {
            console.log(index)
            let that = this;
            that.model2 = '';
            that.arr2 = [];
            setTimeout(function () {
                that.$nextTick(function () {
                    that.arr2 = that.childrenArr[index].children;
                })
            }, 50)
        }
```
这时候，index的值为undefined，继续执行会报错的。请注意看控制台的报错信息。
![image](https://user-images.githubusercontent.com/29689307/43205153-4da880c8-9055-11e8-9392-1b8502c15206.png)

**Comment by Ludidi** [comment]
@IceApriler https://jsfiddle.net/v5s2j3h8/108/  加了个判断不报错了，但是问题还是存在的

**Comment by TingRong-Pu** [comment]
你好  请问你的问题解决了吗？我也遇到了和你一样的问题

**Comment by Ludidi** [comment]
@TingRong-Pu 已经解决，这个属于iview的bug，暂时可以这样解决 https://jsfiddle.net/v5s2j3h8/136/
