### ISSUE TITLE
Slider组件在range模式下行为异常

### ISSUE THREAD

**Issue by ppoffice** [iview/iview#414]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
Windows 10/Google Chrome 56.0.2924.87

### Vue 版本号
2.2.1

### 能够复现问题的在线示例
https://codepen.io/anon/pen/dvVGoZ

### 复现步骤
直接拖动滑块就能复现。

### 问题现象，以及你期望的结果是怎样的?
在CodePen中拖动滑块页面会卡死，在开发环境下拖动滑块会出现滑块跳动现象。
![image](https://cloud.githubusercontent.com/assets/8849362/23952186/8cdb8ba8-09cb-11e7-8649-7423b5876b9e.png)

**Comment by icarusion** [comment]
```html
<Slider v-model="value" range></Slider>
```
