### ISSUE TITLE
[Bug Report] lantern can not switch under IE9


### ISSUE THREAD

**Issue by Stella20161024** [iview/iview#4143]
### Environment
win10，IE9，vue.2.x

### Reproduction link
[https://www.iviewui.com/components/carousel](https://www.iviewui.com/components/carousel)

### Steps to reproduce
直接在IE9下打开走马灯页面，走马灯不会切换

### What is expected?
走马灯可以切换

### What is actually happening?
走马灯可以切换

**Comment by icarusion** [comment]
部分组件不支持部分 IE
