### ISSUE TITLE
引入iview后，项目的布局样式有变动

### ISSUE THREAD

**Issue by G2linkweb** [iview/iview#415]
### iView 版本号

1.0
### 操作系统/浏览器 版本号

Chrome 56
### Vue 版本号

1.0
### 复现步骤
1、npm install iview --save
2、项目引入iview.css
### 问题现象，以及你期望的结果是怎样的?
项目的样式被改变，字体颜色、大小、布局都不一样了。
希望引入组件后，不要对项目本身的样式有太大的影响。

**Comment by icarusion** [comment]
iView 是一整套的前端解决方案，所以连同了 CSS。你的业务 CSS 应当以 iView 为基础构建

**Comment by G2linkweb** [comment]
那我可以给自己的元素添加 CSS 吗，会不会再起冲突而不生效呢

**Comment by icarusion** [comment]
iView 为先，然后你的业务css可以局部覆盖。iView 的 css 都使用 .ivu- 前缀
