### ISSUE TITLE
[Feature Request]hope checkbox component  can support two-dimensional array

### ISSUE THREAD

**Issue by cryingbat** [iview/iview#4150]
### What problem does this feature solve?
chinese：
需求就是当用户点击了全选之后，二维数组的一级二级菜单都被选中，当取消某个一级菜单时，相应的二级菜单不显示。当选中一个一级菜单时，相应的二级菜单显示并且是选中状态。当点击二级菜单取消或者选中时能够打印他的变化
english：
The requirement is that when the user clicks on the selection, the first level two level menu of the two-dimensional array is selected. When a one level menu is cancelled, the corresponding two level menus are not displayed. When the menu is selected at one level, the corresponding two level menu is displayed and selected. When clicking the two level menu is cancelled or checked, it can print his changes.

### What does the proposed API look like?
chinese：
checkbox-group 接受一个二维数组的值，二级菜单支持打印选中的变化
english：
Checkbox-group accepts a two-dimensional array value, and the two level menu supports printing the selected changes.
`arr=[{
   title:'123',
   moudle:[{title:'456'},{title:'456'},{title:'456'}]
},{
    title:'123',
    moudle:[{title:'456'},{title:'456'},{title:'456'}]
},{
    title:'123',
    moudle:[{title:'456'},{title:'456'},{title:'456'}]
}]
`

**Comment by icarusion** [comment]
No such plan
