### ISSUE TITLE
[Bug Report]iview3.0 webpack custom theme error


### ISSUE THREAD

**Issue by TonyLuo** [iview/iview#4156]
### Environment
mac

### Reproduction link
[https://jsfiddle.net/yyrzhm46/](https://jsfiddle.net/yyrzhm46/)

### Steps to reproduce
```less
@import '~iview/src/styles/index.less';
@font-size-base: 14px;
@font-size-small: 14px;
@primary-color          : #2d8cf0;
@warning-color          : #ff9900;
```

### What is expected?
n/a

### What is actually happening?

./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: 

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /Users/tony/dev/vue/vue-admin/node_modules/iview/src/styles/color/bezierEasing.less (line 110, column 0)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-357 13:3-17:5 14:22-365
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by kotoyo1516** [comment]
I come with the same problem

**Comment by BoleLee** [comment]
Me Too!

I have tried [this solution - enabled less option javascriptEnabled](https://github.com/ant-design/ant-motion/issues/44#issuecomment-407498459) and it does not help.
Hope to know the reason and right solution

=========

tried [this solution to change less to less@2.7.2](https://github.com/ant-design/ant-motion/issues/44#issuecomment-404395035) and it can solve the problem.

**Comment by BoleLee** [comment]
It says:
```
// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /usr/src/class_brand/node_modules/iview/src/styles/color/bezierEasing.less (line 110, column 0)
```

**Comment by silverWolf818** [comment]
less版本3.0以上修改less-loalder 在options加入javascriptEnabled: true

**Comment by icarusion** [comment]
也可以降级 Less 到 `^2.7.3`

**Comment by TemaSM** [comment]
Enable option `javascriptEnabled` in your Webpack config, like this (I'm using vue-cli 3.0.0-rc.9):
```javascript
/* config.module.rule('less').oneOf('vue') */
{
  resourceQuery: /\?vue/,
  use: [
    /* config.module.rule('less').oneOf('vue').use('vue-style-loader') */
    {
      loader: 'vue-style-loader',
      options: {
        sourceMap: true,
        shadowMode: false
      }
    },
    /* config.module.rule('less').oneOf('vue').use('css-loader') */
    {
      loader: 'css-loader',
      options: {
        sourceMap: true,
        importLoaders: 3
      }
    },
    /* config.module.rule('less').oneOf('vue').use('postcss-loader') */
    {
      loader: 'postcss-loader',
      options: {
        sourceMap: true
      }
    },
    /* config.module.rule('less').oneOf('vue').use('less-loader') */
    {
      loader: 'less-loader',
      options: {
        sourceMap: true,
        javascriptEnabled: true // <- enable this option
      }
    }
  ]
},
```
package.json: 
```javascript
{
...
"less": "^3.8.0",
"less-loader": "^4.1.0",
...
}
```
`npm i -S less@3.80 less-loader@4.1.0`

**Comment by erik-ruby** [comment]
would be sweet if someone could post exactly what needs to be updated in vue.config.js since in vue cli has abstracted away the webpack config.

**Comment by TonyLuo** [comment]
downgrade less version to be ^2.7.3 in package.json will fix the error
"less": "^2.7.3",

**Comment by SuGod** [comment]
I try to put less down to ^ 2.7.3 appeared new problems
```bash
@checkbox-prefix-cls: ~"@{css-prefix}checkbox";
.checkboxFn();
^
Error evaluating function `fade`: color.toHSL is not a function
      in /project/node_modules/iview/src/styles/components/checkbox.less (line 2, column 0)

```

**Comment by matthew-dean** [comment]
Using `javascriptEnabled` is not the right approach.  It looks like iView is using a hacky Less solution made in ant-design that uses inline Javascript vs. a supported `@plugin` method to add a function to Less. I would rewrite this as a Less `@plugin`.

**Comment by ekntrtmz** [comment]
As @matthew-dean answer states correctly, there is no fast way around this problem. I recommend using the [iview customization tool](https://www.iviewui.com/docs/guide/theme-en#By_tool).

Not elegant but works.

**Comment by M1CK431** [comment]
@erik-ruby 
> would be sweet if someone could post exactly what needs to be updated in vue.config.js since in vue cli has abstracted away the webpack config.

See: https://github.com/ant-design/ant-motion/issues/44#issuecomment-419603946

**Comment by yzb0101** [comment]
记录一下解决方案与思路

## :rotating_light: 错误

> 出现此问题的原因可能是在其他的脚手架中如`vue-cli3`引入了 `iview` 组件库后修改主题导致的，目前（2019-07）`iview` 的 `iview-admin` 使用的是 `^2.7.3`  的 `less` 版本，而 `vue-cli3` ...  已经升级至 `^3.9.0` 的版本，`^3.9.0` 的版本中一个配置项被废弃，导致了 `Inline JavaScript is not enabled`  :warning:。

```bash
error  in ./my-theme/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /Users/bingo/workspace/github/genmd/node_modules/iview/src/styles/color/bezierEasing.less (line 110, column 0)

 @ ./my-theme/index.less 4:14-216 14:3-18:5 15:22-224
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.43.202:9000/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
``` 
认真分析错误后我们可以得出一些结论，从字面意思大概可以理解为不支持 `Inline` Javasript，报错时命中 `./node_modules/less-loader/dist/cjs.js` ，很显然这是 `less-loader` 运行时的一个错误，可以尝试打开 [`lesscss`的官网](http://lesscss.org/usage/)搜索关键字 `Inline` ，搜索得到 `Enable Inline JavaScript (`**Deprecated**`)`，可见这个 `配置` 已经被废弃掉，官方的解决方案为: `Replaced with the @plugin option.`。

## :bulb: 方案

此处提供三种解决方案（希望能帮助大家）:

1. 降低 `less` 和 `less-loader`  的版本，可以参考 `https://github.com/iview/iview-admin/blob/master/package.json`中的版本号码，重新安装依赖。

2. 由于 `Vue CLI` 天生支持 `less` ，可修改它的预处理器的 `less-loader` 的配置，让其支持 `Inline JavaScript`（在我看来不管是出于何种目的，过于依赖”兼容性代码“与废弃的`API`总不太妥，请看第`3`吧）。

vue.config.js

```javascript
const path = require('path')
module.exports = {
    lintOnSave: true,
    css: {
        loaderOptions: {
            less: {
                sourceMap: true,
                javascriptEnabled: true
            }
        }
    }
}
```

3. `Replaced with the @plugin option.` ... 有兴趣和精力的朋友可以尝试一下。

## :books: 参考资料

### Less
> False by default starting in v3.0.0. Enables evaluation of JavaScript inline in .less files. This created a security problem for some developers who didn't expect user input for style sheets to have executable code.
http://lesscss.org/usage/

### Vue CLI3
> 有的时候你想要向 webpack 的预处理器 loader 传递选项。你可以使用 vue.config.js 中的 css.loaderOptions 选项。比如你可以这样向所有 Sass 样式传入共享的全局变量：
https://cli.vuejs.org/zh/guide/css.html#%E5%90%91%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8-loader-%E4%BC%A0%E9%80%92%E9%80%89%E9%A1%B9

### iview 与 iview-admin

https://www.iviewui.com/docs/guide/install

https://github.com/iview/iview-admin/blob/master/package.json

**Comment by puxiao** [comment]
我今天也遇到这个问题了，我什么都不修改，只把电脑中的 node.js 版本由 18.13.0 切换回 16.13.1 就可以了。
