### ISSUE TITLE
[Bug Report]iview3.0 select use for init in the remote mode，label is ineffectiveness

### ISSUE THREAD

**Issue by snailMa** [iview/iview#4159]
### Environment
VUE 3.0

### Reproduction link
[https://run.iviewui.com/hGzd7UjC](https://run.iviewui.com/hGzd7UjC)

### Steps to reproduce
select use for init in the remote mode，label is ineffectiveness

### What is expected?
select use for init in the remote mode，get the option label by the value

### What is actually happening?
label is ineffectiveness

**Comment by chenfengjw163** [comment]
same problem

**Comment by evo34** [comment]
same problem

**Comment by leopard7777777** [comment]
same problem

**Comment by RDeluxe** [comment]
Same problem here. Label is not displayed, even if correctly set.

![firefox_2018-08-03_11-49-20](https://user-images.githubusercontent.com/2767681/43636778-5626a58a-9713-11e8-9b38-474633e00639.png)

**Comment by blackcater** [comment]
same problem

**Comment by BoleLee** [comment]
[#3897](https://github.com/iview/iview/pull/3897)
issue #3897 also report this problem, and it shows that it has been solved. However, I also meet this problem in iview 3.0.0.

**Comment by iamgaohui** [comment]
same problem

**Comment by icarusion** [comment]
The new Select, when set value, the filter method is called, so, the `label` is not usable, just set `value`:
https://run.iviewui.com/nsBepFzV

**Comment by ghost** [comment]
But,  It does not work when multiple, why?

**Comment by ghost** [comment]
Pls check and fix, Thanks.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/4243246/44700608-a98d8d80-aabc-11e8-80f1-20bdd64cea09.png)
