### ISSUE TITLE
After upgrading the iView 3.0.0 with [Bug Report], the title of the menu can not be rendered in the case of CDN referencing the resources of iView.


### ISSUE THREAD

**Issue by lampo1024** [iview/iview#4161]
### Environment
iview 3.0.0

### Reproduction link
[https://jsfiddle.net/api/post/library/pure/](https://jsfiddle.net/api/post/library/pure/)

### Steps to reproduce
官方提供的菜单演示的菜单就是无法渲染的，见JSFiddle：https://jsfiddle.net/api/post/library/pure/

### What is expected?
像iview 2.x版本一样，正确渲染菜单的标题（在以CDN引用的情况下）

### What is actually happening?
升级iview 3.0.0后，在CDN引用iview的资源的情况下，菜单的标题无法渲染

**Comment by icarusion** [comment]
CDN 下使用 `<icon></icon>`，不能用 `<icon />`
