### ISSUE TITLE
[Bug Report]Unable to trigger AutoComplete component

### ISSUE THREAD

**Issue by cnwanyan** [iview/iview#4172]
### Environment
Win10 Chrome68

### Reproduction link
[https://www.iviewui.com/components/auto-complete#DMSL](https://www.iviewui.com/components/auto-complete#DMSL)

### Steps to reproduce
The input cannot trigger the component When I use the Tab key to get the AutoComplete focus

当我使用Tab键获取AutoComplete组件的焦点时，输入无法触发自动补全的功能

### What is expected?
使用Tab键获取焦点后能够触发自动补全的功能

### What is actually happening?
无

**Comment by fantkolja** [comment]
Also faced this issue. Really need it to be fixed.

**Comment by zzmingo** [comment]
+1
