### ISSUE TITLE
[Bug Report] official website anchor anchor component, covered in navigation.


### ISSUE THREAD

**Issue by github-linong** [iview/iview#4181]
### Environment
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

### Reproduction link
[https://www.iviewui.com/components/anchor](https://www.iviewui.com/components/anchor)

### Steps to reproduce
随便往下划划

### What is expected?
组件在导航下面

### What is actually happening?
组件在导航上面

**Comment by github-linong** [comment]
![image](https://user-images.githubusercontent.com/30680461/43504059-777b03fa-9594-11e8-8f45-281b791ad2f5.png)

**Comment by icarusion** [comment]
这不是 bug，是为了演示 affix
