### ISSUE TITLE
[Bug Report]Slider bug

### ISSUE THREAD

**Issue by yaonew** [iview/iview#4193]
### Environment
win10/chrome/3.0

### Reproduction link
[https://run.iviewui.com/OKshu5I5](https://run.iviewui.com/OKshu5I5)

### Steps to reproduce
1.Enter 10 directly in numberinput
2.onchange event print 1

### What is expected?
10

### What is actually happening?
1

---
Direct input numeric onchange returns the value before change.

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/43764915-4737154a-9a61-11e8-8235-c5c6eba5c819.png)
