### ISSUE TITLE
The option option hover style problem for [Bug Report]select


### ISSUE THREAD

**Issue by NAN0916** [iview/iview#4194]
### Environment
mac /Google Chrome68.0.3440.75/vue 2.5.13/iview 3.0.0

### Reproduction link
[https://jsfiddle.net/62hgawfc/](https://jsfiddle.net/62hgawfc/)

### Steps to reproduce
select 定宽 option在hover的时候样式有问题 不是全灰色的 部分灰色 

### What is expected?
option在hover的时候全是灰色 

### What is actually happening?
option在hover的时候只有前面一半是灰色

**Comment by wangxdmm** [comment]
I think it is not good idea to change width to minWidth, if add transfer to the select, and then the drop's width will equal to the body's width if body's width has been set.

**Comment by yaomingdan** [comment]
更新3.0.1后，只能把样式覆盖成.ivu-select-dropdown { width: auto;}，才能使用transfer属性，否则option会铺满屏幕宽度
