### ISSUE TITLE
[Bug Report]the component of AutoComplete, when select a option, why the event of on-change and on-select happend in the some time

### ISSUE THREAD

**Issue by lockontan** [iview/iview#4195]
### Environment
iview@3.0 iview@2.14.3

### Reproduction link
[https://jsfiddle.net/lockonTan/5op9ntud/10/](https://jsfiddle.net/lockonTan/5op9ntud/10/)

### Steps to reproduce
select a option

### What is expected?
they may not happend in the same time

### What is actually happening?
they happend

---
the some problem happend in the component of Select when I used remote search

**Comment by lockontan** [comment]
?

**Comment by ghost** [comment]
: )
