### ISSUE TITLE
The Render function in [Bug Report]Table cannot render custom components, the console reports wrong Unknown custom element.


### ISSUE THREAD

**Issue by no5no6** [iview/iview#4198]
### Environment
3.0.0

### Reproduction link
[https://jsfiddle.net/LittleChild/d3vmt2s4/26/](https://jsfiddle.net/LittleChild/d3vmt2s4/26/)

### Steps to reproduce
表格渲染时出现，这个问题我也看了之前的 issue ，在这次提交已修复了这个问题，https://github.com/iview/iview/commit/64f99c05bbbdeee60cdd71beea7b55b2fc8c8e3c ，但是目前 3.0 版本中又出现了问题。望指点，谢谢。

### What is expected?
 Table 组件可以渲染自定义组件

### What is actually happening?
目前在 Table 组件中，使用 render 渲染自定义组件，会有错误提示组件未注册

**Comment by icarusion** [comment]
https://jsfiddle.net/d3vmt2s4/27/

**Comment by no5no6** [comment]
@icarusion 因为 jsfiddle 不方便复现多个 vue 文件。如果按照例子那么写，等于还是注册了全局组件对吧？我在我项目里用 import 方式引入的自定义组件，然后在当前 vue 文件里用 components 中加载该组件，在 ivew table 组件里使用会报“未注册"错误。
大致代码如下所示：
```
<script>
import TableSelect from xxxx;
export default {
  components: {
    TableSelect,
  },
  data() {
    return {
      columns: [
        {
          title: '选择场景标签',
          render: (h, params) => {
            return h('TableSelect', {
              props: {
                list: this.tagSelectList
              },
              on: {
                changeTag: id => {
                  params.row.selectedStandardTag = id;
                }
              }
            });
          }
        }
      ]
    };
  }
}
</script>
```
