### ISSUE TITLE
[Feature Request]Auto Tabs Height

### ISSUE THREAD

**Issue by sunxyw** [iview/iview#4199]
### What problem does this feature solve?
Tabs height does not change with content.

For example, tab1 height is 700px, tab2 height is 340px.
when I open tab2, the height is also 700px.

### What does the proposed API look like?
Tabs height will change with content.

**Comment by icarusion** [comment]
You can split tab and content

**Comment by hanbaga** [comment]
how to split tab and content @icarusion
