### ISSUE TITLE
[Bug Report]Why the tag component can't trigger or capture click events?

### ISSUE THREAD

**Issue by IceApriler** [iview/iview#4200]
### Environment
mac / chrome / 2.14.3&3.0.0

### Reproduction link
[https://jsfiddle.net/g5qkwt4L/](https://jsfiddle.net/g5qkwt4L/)

### Steps to reproduce
There are 4 tags and 1 button. Tag cannot trigger or capture a click event.
有4个Tag和1个Button，Tag无法触发或捕获点击事件。

### What is expected?
I hope that I can trigger or capture a click event by clicking on the tag component.
我希望点击标签可以触发或捕获一个事件。

### What is actually happening?
Tag cannot trigger or capture a click event.

---
I looked at the source code and found that the tag component prevented the event from continuing to propagate, but I still can't get the event after using the capture.
我查看了源码，发现tag组件阻止了事件继续传播，但是我用了capture后依然无法获取事件，我应该怎么做？

**Comment by David-Tsui** [comment]
@click.native

**Comment by IceApriler** [comment]
@David-Tsui 非常感谢，有用！
