### ISSUE TITLE
[Bug Report]IView is imported as required to compile the error 

### ISSUE THREAD

**Issue by liuleiweb** [iview/iview#4201]
### Environment
iview2.14.3

### Reproduction link
[https://jsfiddle.net/yyrzhm46/1704/](https://jsfiddle.net/yyrzhm46/1704/)

### Steps to reproduce
1. vue-cli安装目录
2.  按照官方文档配置.babelrc 文件， 并在main.js中导入table和button组件
3. 编译报错

ERROR in ./node_modules/iview/src/components/button/button.vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|     <button
|         :type="htmlType"
 @ ./node_modules/iview/src/components/button/index.js 1:0-34
 @ ./src/main.js

ERROR in ./node_modules/iview/src/components/button/button-group.vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|     <div :class="classes">
|         <slot></slot>
 @ ./node_modules/iview/src/components/button/index.js 2:0-45
 @ ./src/main.js

ERROR in ./node_modules/iview/src/components/table/table.vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|     <div :class="wrapClasses" :style="styles">
|         <div :class="classes">
 @ ./node_modules/iview/src/components/table/index.js 1:0-32
 @ ./src/main.js

### What is expected?
编译通过

### What is actually happening?
编译报错

**Comment by llccing** [comment]
webpack配置是什么样的？

**Comment by liuleiweb** [comment]
rules: [
            {
                test: /\.vue$/,
                exclude: /node_modules/,
                loader: 'vue-loader',
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: "babel-loader"
            },
            {
                test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: '/img/[name].[hash:7].[ext]'
                }
            },
            {
                test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: '/media/[name].[hash:7].[ext]'
                }
            },
            {
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: '/fonts/[name].[hash:7].[ext]'
                }
            },
            {
                test: /\.css$/,
                use: [
                    {loader: "style-loader"},
                    {loader: "css-loader"},
                ]
            },
            {
                test: /\.scss$/,
                use: [
                    {loader: "style-loader"},
                    {loader: "css-loader"},
                    {loader: "sass-loader"}
                ]
            }
        ]

**Comment by liuleiweb** [comment]
我这个webpack配置和vue-cli有些区别。 不过vue-cli也是一样。  是需要在webpack配置相关的loader吗

**Comment by llccing** [comment]
如果loader是这样应该没啥问题，可以把demo项目传一下吗

**Comment by liuleiweb** [comment]
额 知道是什么原因了。  这个webpack的配置问题。   {
test: /.vue$/,
exclude: /node_modules/,
loader: 'vue-loader',
},
{
test: /.js$/,
exclude: /node_modules/,
loader: "babel-loader"
},  里面我设置了 exclude: /node_modules/ 影响到了
