### ISSUE TITLE
Add max-height parameter to [Feature Request]Table component


### ISSUE THREAD

**Issue by boolinlin** [iview/iview#4207]
### What problem does this feature solve?
当前可设置：
 height	表格高度，单位 px，设置后，如果表格内容大于此值，会固定表头

解决当表格数据较少时，表格无需占用不必要空间。

### What does the proposed API look like?
max-height	表格的最大高度	string/number

**Comment by wang8254** [comment]
这里有BUG，链接https://run.iviewui.com/qwWDBneF，在组件中同时设置max-height和fixed，有fixed的属性的对应列的水平滚动条，无法点中并拖动
