### ISSUE TITLE
【bug】分页电梯跳转没有事件监听

### ISSUE THREAD

**Issue by senro** [iview/iview#421]
### iView 版本号
 2.0.0-rc.5

### 操作系统/浏览器 版本号
win10/Chrome 56 

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）
https://www.iviewui.com/components/page

### 复现步骤
看官方文档
### 问题现象，以及你期望的结果是怎样的?
文档里没有体现电梯跳转的事件名称
### 你估计可能的原因是什么（选填）？
是否漏掉这个功能的开发

**Comment by rijn** [comment]
`on-change`

**Comment by senro** [comment]
然而on-change并没有监听

发自我的 iPhone

**Comment by icarusion** [comment]
从代码看，是有触发 $emit('on-change') 的，你最好写个在线示例来验证一下

**Comment by senro** [comment]
嗯，在本地必现的bug，可以补个线上重现，不过建议在文档里每个组件都最好有一个用了所有api的例子，这样也便于测试，像element一样

发自我的 iPhone

**Comment by chenchaohong** [comment]
输入框监听是的  keyup  输入页数后敲回车键
"keyup": function keyup($event) {
          if (_vm._k($event.keyCode, "enter", 13)) {
            return null;
          }
          _vm.changePage($event);
        }

**Comment by wufangjian** [comment]
开发中也遇到同样问题!  `show-elevator` 属性无效，求解~
