### ISSUE TITLE
[Bug Report]Modal dialog box in drag and drop mode custom location, click on the head, the dialog box will run around.


### ISSUE THREAD

**Issue by yuansun28** [iview/iview#4213]
### Environment
iview3.0   vue2.5.2

### Reproduction link
[https://run.iviewui.com/XzWgT8YB](https://run.iviewui.com/XzWgT8YB)

### Steps to reproduce
点击header的时候，整个对话框会按照自定义位置的数值进行偏移

### What is expected?
对话框不乱跑

### What is actually happening?
对话框乱跑

**Comment by icarusion** [comment]
拖拽模式不能再设置 style
