### ISSUE TITLE
[Bug Report] cascade selector, dynamic loading change-on-select problem


### ISSUE THREAD

**Issue by Johnson-LYS** [iview/iview#4216]
### Environment
macOs 10.13.5, chrome 70.0.3513.0（正式版本）canary （64 位）, vue 2.5.13, iview 2.x

### Reproduction link
[https://jsfiddle.net/joenlee/jqycknu3/](https://jsfiddle.net/joenlee/jqycknu3/)

### Steps to reproduce
级联选择器异步加载并使用change-on-select时，如果加载子集为空集，并不会更新选中数据。

### What is expected?
期望为更新选中数据应该在加载子集之前或者与加载子集相互独立

### What is actually happening?
子集为空时，无法选择该节点

---
需求：使用级联选择器选择其中的一个节点数据，该数据可能有很多级，但是只需要一个

**Comment by icarusion** [comment]
#4211

**Comment by negrochn** [comment]
这个问题为啥被关了？和#4211是两个问题啊

也遇到了同样的问题，暂时没想到好的规避措施
