### ISSUE TITLE
【bug】ie9的兼容性问题

### ISSUE THREAD

**Issue by senro** [iview/iview#422]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
win10/Chrome 56

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（重要）
https://www.iviewui.com/components/select

### 复现步骤
ie 9下点击下拉框
### 问题现象，以及你期望的结果是怎样的?
ie 9上的下拉框select，点击就会报错
SCRIPT438: 对象不支持“now”属性或方法
iview.js (2594,15)
### 你估计可能的原因是什么（选填）？
ie9的window.performance里没有now方法，希望做下兼容

**Comment by icarusion** [comment]
貌似不影响使用，但不知道哪里用了这个方法，代码里并没有。

**Comment by yibuyisheng** [comment]
@icarusion 现在 poptip 在 IE9 下弹出的位置是错误：https://www.iviewui.com/#/components/poptip 。

![image](https://cloud.githubusercontent.com/assets/2581682/25556884/164d93b0-2d38-11e7-97f8-2ddfa3a392db.png)

**Comment by yibuyisheng** [comment]
@icarusion Tabs控件使用了flex，目测是不准备支持IE9了？
