### ISSUE TITLE
[Feature Request]When the on-change event is triggered by select, oldValue & newValue & selectedIndex is returned.

### ISSUE THREAD

**Issue by spencer-live** [iview/iview#4221]
### What problem does this feature solve?
Better operational for the business.

### What does the proposed API look like?
When the on-change event is triggered by select, oldValue & newValue & selectedIndex is returned.
select 触发 on-change 事件时, 返回oldValue & newValue & selectedIndex .

**Comment by icarusion** [comment]
No such plan
