### ISSUE TITLE
[Feature Request]check-strictly property and on-context-menu event on Tree

### ISSUE THREAD

**Issue by li-xiaoyin** [iview/iview#4222]
### What problem does this feature solve?
Feature：
1. fire on-context-menu event on right click tree. not limited to click node, and support blank area. because the context menu may be defferent on click node and blank area.
2. check-strictly on tree, it means don't cascade check parent (or children) on strictly mode. I commit a pr about this 2 issue and closed myself. I add a check-strictly property at that time and then I fill not convenience, and now i suggest add  a check-strictly-key property, like :check-strictly-key="ctrl", and when press ctrl to check node then don't cascade check parent (or children), it will back to cascade mode when ctrl key up. and also can support a static property like :check-stricty=true

Scene:
1. on-context-menu is general feature in tree control. and most ui lib don't support right click blank and i feel this feature is useful. it can show a global operation menu.
2. I have a tree like file explorer（it just a example）：
Folder A
    File 1
    .....
    File 100
Folder B
and i want to delete File 1 - File 100 and don't delete Folder A on tree. i can not do this in current version because when i check 1-100,  folder be checked too.and only set check-stritly=true is not  convenience too, because i must be check 100 times!, i wang to check Folder A then auto check 1-100 cascade, and then uncheck folder only (by ctrl click).

### What does the proposed API look like?
1. @on-context-menu="e, node => {}" (node will be null when click blank area.)
2. :check-strictly-key="ctrl"
    :check-strictly=true

**Comment by adamma1024** [comment]
老哥，把你这个关了吧，分开提，我现在就需要个check-strictly
