### ISSUE TITLE
[Bug Report]No response when click a Cell (a new component in v3.0.0)

### ISSUE THREAD

**Issue by oxdc** [iview/iview#4226]
### Environment
Linux 4.13.0-38-generic #43-Ubuntu / Version 68.0.3440.84 (Official Build) (64-bit) / iview 3.0.0

### Reproduction link
[https://run.iviewui.com/adIkWDyM](https://run.iviewui.com/adIkWDyM)

### Steps to reproduce
I tried @on-click, @click and even @on-cell-click & @cell-click, but none of them work!

### What is expected?
The custom event handler should be called and a success notification should be visible.

### What is actually happening?
Nothing happened!!

**Comment by MissHoya** [comment]
@click.native

**Comment by icarusion** [comment]
看文档。
