### ISSUE TITLE
分页：总数量不显示

### ISSUE THREAD

**Issue by Ayerss** [iview/iview#423]
### iView 版本号
1.0.1

### 操作系统/浏览器 版本号
window 7/ Chrome 56

### Vue 版本号
1.0.27

### 能够复现问题的在线示例（重要）
无

### 复现步骤
模块分页，参数：total（数据总数）。
总数在项目中是后台返回的数据并绑定到total上
`<Page :total="dataNum" :page-size="10" :show-total="true"  :on-change="pageChange"></Page>`

### 问题现象，以及你期望的结果是怎样的?
我赋值给了this.dataNum数量了，但是实际显示的是  （共条）。总数并没有赋值进去。不知道这是我的写法有问题还是total只能初始化页面时才管用
官方案例上对于分页这块的说明并不多，希望能够补充

**Comment by rijn** [comment]
Please provide online test sample. I used Page component in my own page and it works well.

**Comment by icarusion** [comment]
`on-change` is not a prop, it is a custom event

**Comment by Ayerss** [comment]
我的total类型写错了，写成字符串类型了
