### ISSUE TITLE
[Feature Request] uses the on-row-click event in table to assign a failure to the current row.


### ISSUE THREAD

**Issue by xingdalee** [iview/iview#4232]
### What problem does this feature solve?
page：<Table :row-class-name="rowClassName" @on-row-click="selectMaterielDetail" :columns="materielColumnsList" :data="selectionList"></Table>
methods:
selectMaterielDetail(row, index) {
        row.isSelected = !row.isSelected;
      },
在这里给row赋值isSelected后，在页面重新点击on-row-click 无法获取row中新增的isSelected

### What does the proposed API look like?
能够在on-row-click事件中 获取之前已经赋值的row

**Comment by winpzs** [comment]
这是什么鬼？到现在还没提供选择行？
