### ISSUE TITLE
The [Bug Report]Select component delete key is invalid


### ISSUE THREAD

**Issue by vincentTea** [iview/iview#4238]
### Environment
win10 64bit / Google Chrome 67.0.3396 / vue2.x(目前最新版)

### Reproduction link
[https://www.iviewui.com/components/select#JY](https://www.iviewui.com/components/select#JY)

### Steps to reproduce
只要是可输入的Select组件，输放完之后，改变光标位置，想用delete键删除光标后的内容，都是无效的。
如果选中自己输入的内容，再按delete键，也是无效的。无法删除的。
要删除输入的内容，仅能通过 回退键

### What is expected?
恢复delete键的功能

### What is actually happening?
delete键无法删除键入的内容

**Comment by icarusion** [comment]
Select 是选择器，不能输入。搜索用 `filterable`

**Comment by vincentTea** [comment]
@icarusion Select有个属性，开启【可搜索】，这个时候是能输入的，但在这个时候，delete键会出问题，无法删除输入的内容(光标后，或 选中的输入内容)
