### ISSUE TITLE
i-table 外部套上 <Row> <i-col> 后问题

### ISSUE THREAD

**Issue by ouminghai** [iview/iview#424]
i-table 外部套上 <Row> <i-col> 后 table中的column对象使用render函数，函数绑定的事件将无法使用

### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
 2.2.1

**Comment by icarusion** [comment]
设置 content 了吗？
