### ISSUE TITLE
[Bug Report]select, when choose option, Background color is not covered

### ISSUE THREAD

**Issue by chenLiTeng** [iview/iview#4242]
### Environment
win10  ;   chrome  ;  vue 2.0

### Reproduction link
[https://run.iviewui.com/Q53ZOamc](https://run.iviewui.com/Q53ZOamc)

### Steps to reproduce
1: select option lable content is longer than select width.
2: choose one of option and open again
3: you will see left and right scroll bars appear  and Swipe right；
4: you can't see any word, because option word color become white but backgound color not covered

### What is expected?
fix this bug 

### What is actually happening?
can not say word

**Comment by icarusion** [comment]
fixed in next version
