### ISSUE TITLE
Radio组件绑定值的建议

### ISSUE THREAD

**Issue by xiaoyyang123** [iview/iview#425]
### iView 版本号
 2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）
https://codepen.io/xiaoyyang/pen/MpOEjp?editors=1111

### 问题现象，以及你期望的结果是怎样的?
`Radio`和`RadioGroup`组件使用时，`Radio`组件的`label`值无法绑定`0`和`‘0’`，我看`Radio.vue`里的源码是直接判断label是否存在，这样是否能改善下，因为在开发中很多时候是用1和0来判断是否这两种情况

**Comment by icarusion** [comment]
Thx, we will update soon.

**Comment by xiaoyyang123** [comment]
I come up with this problem in the project frequently, so do other pepple. Could you pls get this issue solved as soon as possible? thanks a lot.

**Comment by icarusion** [comment]
Thanks, but I think contribute maybe a best way to solve issue like this.
