### ISSUE TITLE
When [Bug Report] switches the tabs tab, the content is hidden. Visibility is not consistent with the selected tab page.


### ISSUE THREAD

**Issue by webxiaobai** [iview/iview#4257]
### Environment
win10/谷歌/vue2.x

### Reproduction link
[https://run.iviewui.com/AmQ1sLWN](https://run.iviewui.com/AmQ1sLWN)

### Steps to reproduce
1.点击菜单“消费统计”，自下而上的顺序点击2个（从底部开始，点击2个，也可以是多个），会出现2个tabs标签页，切换标签页，反复切换，内容会消失了。visibility与选中的tabs标签页显示不一致。只有自上而下的顺序（从顶部开始，选任意个），切换标签页，内容不会消失，正常显示。visibility与对应选中的tabs标签页显示一致

### What is expected?
任意点击菜单，出现的tabs标签页，任意切换，内容正常显示。

### What is actually happening?
自下而上的顺序点击2个（从底部开始，点击2个，也可以是多个），会出现2个tabs标签页，切换标签页，反复切换，内容会消失了。

---
个人非常喜欢iview，真爱粉，希望iview越做越好。根据个人在实际开发中遇到的问题，提点个人建议：1：tree组件在ie9上行高（高度）显示不正常，ie10上好像显示的也不是很好。同时建议增加“增删改”功能，单击选中等样式。2：增加table与raido结合产生单选，现在的单选，显示不明显（我通过table的render与radio结合做的）；3：建议增加ctrl 鼠标左键，selection（radio）自动选上；4：增加table-tree功能（目前网上有，但是不好用，希望iview开发者辛苦一下，开发一个完善的）；5：Notice与message控件，开发者对他们的样式可控性差，如背景色，字体大小，页面居中显示，动画效果，使用人员觉得现在的提示不够明显、醒目、“不够明显、醒目（很重要）”。6：鼠标放在table单元格上，没有浮动显示（title的功能，目前我是通过render与Tooltip结合解决的）；7：按需引用，自己试过，总是报错，不太会用，感觉有点复杂，会再研究的。8：我做的项目在ie9上基本无法显示，ie10上显示的非常卡，其中iview占了很大的功劳，建议优化iview在ie上的显示。9:,实际开发中，页面高度往往是可变的，所以table的高度也要随着电脑分辨率发生变化，建议增加高度可变（高度百分比等减去固定高度）

**Comment by icarusion** [comment]
#4052
