### ISSUE TITLE
[Bug Report]Can't use render() to render Cell tag

### ISSUE THREAD

**Issue by choipun** [iview/iview#4258]
### Environment
macOS / vue-cli rc.10 / ivew 3.0.0

### Reproduction link
[https://run.iviewui.com/MTr93bEM](https://run.iviewui.com/MTr93bEM)

### Steps to reproduce
Here is a demo: https://run.iviewui.com/MTr93bEM
when I render the Cellgroup tag's child node Cell, it caught an err "TypeError: t.props.render is not a function"
Hope anybody help me fix this problem

### What is expected?
render the Cell tag by render()

### What is actually happening?
it doesn't work, throw an error

**Comment by RookieZoe** [comment]
fixed. conflict components's name ( The 'Cell' in 'src/components/table/cell.vue')
