### ISSUE TITLE
The [Bug Report] drop-down box has the search filter attribute, and the modal pop-up switch will cause a null condition when it is selected


### ISSUE THREAD

**Issue by moqin** [iview/iview#4261]
### Environment
vue2

### Reproduction link
[https://run.iviewui.com/MxhaElZg](https://run.iviewui.com/MxhaElZg)

### Steps to reproduce
单击数据A下拉，会出现下拉数据，然后随便选择一个，最后单击取消，
接着单击数据B下拉，会出现无数据，然后输入一个B或者随便输入文字然后删除，就可以显示下拉B的数据

### What is expected?
切换后可以直接下拉显示B的数据

### What is actually happening?
切换后可以没有直接下拉显示B的数据

**Comment by moqin** [comment]
解决，注意注释部分

**Comment by icarusion** [comment]
#4300
