### ISSUE TITLE
import iview to Vue2.X cli show errors

### ISSUE THREAD

**Issue by Lisa2015** [iview/iview#4264]
### Environment
Windows7 64byte/ Chrome68/ Vue2.5.16

### Reproduction link
[https://run.iviewui.com/](https://run.iviewui.com/)

### Steps to reproduce
1.` import {Tree, Table} from 'iview'`
`import 'iview/dist/styles/iview.css'`
`Vue.component('Tree', Tree)`
`Vue.component('Table', Table)`

2. 在template页面中引用 `<Table border :columns="columns5" :data="data5"></Table>`

### What is expected?
正常运行,按照官方文档那样显示组件

### What is actually happening?
报错:vue.common.js?e881:3149 Uncaught TypeError: Cannot read property 'size' of undefined

---
不管引用什么组件,都是相同的报错 `:vue.common.js?e881:3149 Uncaught TypeError: Cannot read property 'size' of undefined`

**Comment by Lisa2015** [comment]
按需引入 不能安装  ` babel-plugin-import` 插件,否则会报错: `iview is not defined`.官方文档简直在误导!!

**Comment by Beats0** [comment]
在main.js添加
```js
Vue.prototype.$IVIEW = {}
```
#4165

**Comment by Beats0** [comment]
@Lisa2015 
在main.js添加
```js
Vue.prototype.$IVIEW = {}
```
see #4165

**Comment by Lisa2015** [comment]
thx
