### ISSUE TITLE
Menu组件问题

### ISSUE THREAD

**Issue by spacetimeme** [iview/iview#427]
`<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>Webpack App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/iview@2.0.0-rc.5/dist/styles/iview.css">
    
    <script src="https://unpkg.com/iview@2.0.0-rc.5/dist/iview.min.js"></script>
</head>

<body>
    <div id="app">
        <Menu>
            <Submenu>
                <Menu-group title="使用">
                    <Menu-item key="1-1">文章管理</Menu-item>
                    <Menu-item key="1-2">评论管理</Menu-item>
                    <Menu-item key="1-3">举报管理</Menu-item>
                </Menu-group>
            </Submenu>
        </Menu>
    </div>
    <script>
        new Vue({
            el: '#app',
            data() {},
            methods: {
            }
        })
    </script>
</body>

</html>`
此Html文件代码不显示menu

**Comment by icarusion** [comment]
按要求提问
