### ISSUE TITLE
[Bug Report]Card built-in table cannot use remote filtering.


### ISSUE THREAD

**Issue by hihuangwei** [iview/iview#4270]
### Environment
Windows10 / Chrome/69.0.3497.23 / Vue 2.5.17

### Reproduction link
[https://run.iviewui.com/Efk3WATV](https://run.iviewui.com/Efk3WATV)

### Steps to reproduce
点击Address过滤筛选

### What is expected?
正常

### What is actually happening?
VM41:56 Uncaught TypeError: this.bookTest is not a function

**Comment by icarusion** [comment]
```
filterRemote: (e) => {
  this.bookTest(e)
}
```
