### ISSUE TITLE
Cannot import AutoComplete on demand by using babel-plugin-import

### ISSUE THREAD

**Issue by Mistariano** [iview/iview#4274]
### Environment
MacOS Chrome 68.0.3440.106; vue@2.5.17; iview@3.0.0

### Reproduction link
[https://www.iviewui.com/docs/guide/start-en](https://www.iviewui.com/docs/guide/start-en)

### Steps to reproduce
main.js中使用QuickStart提供的方法按需引用AutoComplete组件:

```
import {AutoComplete} from 'iview'
Vue.component('AutoComplete', AutoComplete)
```

### What is expected?
成功引入AutoComplete组件

### What is actually happening?
浏览器报错：Uncaught TypeError: Cannot read property 'size' of undefined
at VueComponent._default (auto-complete.vue?ff9b:78)

---
问题是此时Vue.prototype.$IVIEW没有定义
我的解决方法是在注册组件前加入`Vue.prototype.$IVIEW = {size: ''}`

**Comment by icarusion** [comment]
下个版本已修复

**Comment by huaipomen** [comment]
目前3.3.3 版本 按需引入并未解决这个问题
