### ISSUE TITLE
[Bug Report] dynamically updates the mode prop error of Menu components.


### ISSUE THREAD

**Issue by feymanlee** [iview/iview#4275]
### Environment
mac os / cheome 69.0.3497.23 beta 

### Reproduction link
[https://jsfiddle.net/gectm4q7/1/](https://jsfiddle.net/gectm4q7/1/)

### Steps to reproduce
vertical 动态切换到 horizontal 的时候或出现 console 会有错误提示

### What is expected?
没有错误

### What is actually happening?
出现错误

---
Vue warn]: Error in callback for watcher "mode": "TypeError: Cannot read property 'update' of undefined"

**Comment by icarusion** [comment]
暂不支持动态切换 mode
