### ISSUE TITLE
The [Bug Report]<Time> component has bug


### ISSUE THREAD

**Issue by hzjswlgbsj** [iview/iview#4277]
### Environment
macOS 10.13.5 (17F77) / Chrome 67.0.3396.99 / vue 2.5.2

### Reproduction link
[https://run.iviewui.com/VfHR7fFd](https://run.iviewui.com/VfHR7fFd)

### Steps to reproduce
在iview3.0.0直接使用<Time>组件，type属性为默认的情况下，正常会显示xxx分钟之前，xx天之前，但是超过一年的时间，的时候年份显示不正确 ，会显示成：49213-08-12 23:33:20 （实际上这个是 2017-08-12 23:33:20 ）

### What is expected?
期望超过一年在type默认情况显示 一年前，两年前。。。 在date模式下显示 2017-08-12

### What is actually happening?
年份不正确49213-08-12 23:33:20 （实际上这个是 2017-08-12 23:33:20 ）

**Comment by icarusion** [comment]
超过一个月，就显示为具体的日期。

**Comment by hzjswlgbsj** [comment]
我知道，但是显示的日期不对哦，看本issue的最后一行的描述@icarusion
