### ISSUE TITLE
iview 的select的@on-open-change方法没反应啊？

### ISSUE THREAD

**Issue by bubuni** [iview/iview#4280]
为什么没反应呢？如何解决？

**Comment by lanshijie** [comment]
我也碰到这个问题了，无从下手，请问楼主最后解决了吗

**Comment by zhy9527** [comment]
请问你解决了吗？我是在本地可以，测试上不触发这个方法
@on-open-change="getByName($event)"

**Comment by wj4901** [comment]
Select的 @on-open-change 是在2.14.0版本加上去了 我用的是2.8.0看了下源码并没有这个特性
解决方法:
1. 升级至最新版本 npm update iview
2.修改源码 在Select组件的watch的 visable事件监听器里面加上  this.$emit('on-open-change', value);
