### ISSUE TITLE
[Feature Request]add appBar Please

### ISSUE THREAD

**Issue by rayfalling** [iview/iview#4283]
### What problem does this feature solve?
i wanna the appBar can solve the problem that menu doesn't have the Title slot and can't fit it-self in mobile and PC.
see muse-ui-appbar
解决menu组件在手机和电脑上自适应的问题，为menu提供标题区域
参考muse-ui的appBar

### What does the proposed API look like?
Menu add the slot of Title

**Comment by icarusion** [comment]
No such plan
