### ISSUE TITLE
关于datepicker日期转换错误

### ISSUE THREAD

**Issue by hushenao** [iview/iview#4290]
第一个图是后台传给我的一个时间，这个时间直接放到datepicker里面的时候就转换成了图2的date，但是时区是错误的，我试过用new Date（）转换的时候是对的，直接用在datepicker上显示的就是错误的
![2018-8-16 8 58](https://user-images.githubusercontent.com/23112269/44209916-73d0d680-a197-11e8-81c4-662bd3f0fde7.jpg)
![2018-8-16 8 58 1](https://user-images.githubusercontent.com/23112269/44209931-7b907b00-a197-11e8-9d5f-1cf80a8a72f8.jpg)

**Comment by dafeifei0218** [comment]
@iview-bot 这个问题都给关掉了？懒得解决吗？还是你有现成的解决方案？

**Comment by dafeifei0218** [comment]
open

**Comment by lulongwen** [comment]
经验心得：
1 使用 value 绑定值，不要使用 v-model
2 使用 @on-change 赋值，就没有这个问题了
