### ISSUE TITLE
[Bug Report] about datepicker component time conversion error


### ISSUE THREAD

**Issue by hushenao** [iview/iview#4291]
### Environment
mac/Chrome/vue2.5.2/iview2.14.2

### Reproduction link
[https://www.cnblogs.com/hushenao/p/9490088.html](https://www.cnblogs.com/hushenao/p/9490088.html)

### Steps to reproduce
后台是java的，直接把java转的标准时间放到datepicker中即可

### What is expected?
时区的转换有问题，虽然已经转换为8时区，但是时间还是0时区的时间

### What is actually happening?
希望得到的是8时区的正确时间

---
希望有一个扩展函数来修正这个转换上的错误，

**Comment by SergioCrisostomo** [comment]
@hushenao there is a fix on master for this (https://github.com/iview/iview/pull/4250). Could you test that? I think this is a duplicated issue already fixed.

**Comment by hushenao** [comment]
@SergioCrisostomo 感谢回复，但还是没有转换成正确的时间
