### ISSUE TITLE
[Bug Report] When reloading the columns parameter using a table control, if the loaded columns are with children, the header is grouped, and the browser (chrome) is stuck


### ISSUE THREAD

**Issue by agzou** [iview/iview#4293]
### Environment
Window7 Chrome 版本 68.0.3440.106（正式版本） （64 位） v2.5.17

### Reproduction link
[https://run.iviewui.com/MrVlmFGO](https://run.iviewui.com/MrVlmFGO)

### Steps to reproduce
初始化一个表格控件,然后重新加载表格的columns属性,当重新渲染的columns是分组表头，即带有children的，浏览器直接卡死，怀疑遍历表头出现死循环

### What is expected?
表格列重新渲染

### What is actually happening?
浏览器直接卡死

**Comment by icarusion** [comment]
#3472
