### ISSUE TITLE
The [Bug Report]Affix pin assembly does not work.


### ISSUE THREAD

**Issue by wlh206** [iview/iview#4299]
### Environment
win7、谷歌

### Reproduction link
[https://run.iviewui.com/Xc1yCUF1](https://run.iviewui.com/Xc1yCUF1)

### Steps to reproduce
请看重现链接

### What is expected?
下来滚动条后，图钉没用固定效果

### What is actually happening?
完全没用效果

**Comment by icarusion** [comment]
https://jsfiddle.net/0af87m94/
