### ISSUE TITLE
[Bug Report]select filterable bug

### ISSUE THREAD

**Issue by chen-ABC** [iview/iview#4300]
### Environment
win10

### Reproduction link
[https://run.iviewui.com/DAf7X6TC](https://run.iviewui.com/DAf7X6TC)

### Steps to reproduce
当select的value与label不一致时
1.选择select第一个选项
2.点击改变按钮,利用data改变select的value
3.再次打开下拉框,option不正确,只出现上次选择选项,而不是全部选项

### What is expected?
再次打开下拉框出现全部选项

### What is actually happening?
只出现上次选择选项,而不是全部选项

**Comment by icarusion** [comment]
#4466
