### ISSUE TITLE
[Bug Report]the anchor component demo page error 

### ISSUE THREAD

**Issue by hi-sunshine** [iview/iview#4302]
### Environment
mac pro/chrome 64/

### Reproduction link
[https://www.iviewui.com/components/anchor#AnchorLink_props](https://www.iviewui.com/components/anchor#AnchorLink_props)

### Steps to reproduce
open the link, and scroll down page, you can find the page disorder

### What is expected?
the page should show rightly

### What is actually happening?
the page show disorder

---
anchor组件的官方示例页面，滚动时，发生显示问题。文字重叠，定位有问题。

**Comment by icarusion** [comment]
此为演示 affix 效果。
