### ISSUE TITLE
The transfer attribute of the modal component does not work in IE10

### ISSUE THREAD

**Issue by Hello-Fuxq** [iview/iview#4303]
### Environment
windows10  IE10  vue 2.5.16

### Reproduction link
[https://run.iviewui.com/KZw7Chld](https://run.iviewui.com/KZw7Chld)

### Steps to reproduce
Modal组件 设置‘transfer’ 属性为false,在IE10中不生效

### What is expected?
‘transfer’ 属性为false时应该包含在内容内，而不是在最外层。

### What is actually happening?
‘transfer’ 属性不起作用

---
随便说下，draggable属性开启后，在IE10中一点击就跑到左上角了，还有在chrome浏览器中拖动时边界没有控制，超出浏览器边界了却依然可以拖动，总之问题相当的多.....

**Comment by icarusion** [comment]
部分组件或功能不支持部分 IE 浏览器。
