### ISSUE TITLE
[Bug Report]Button transitions to "loading" is delayed when there are a lot them

### ISSUE THREAD

**Issue by calvintwr** [iview/iview#4304]
### Environment
Chrome 68, MacOS EI Capitan, Vue 1.0.26, IView 0.9.15

### Reproduction link
[https://jsfiddle.net/h01sp7za/1/](https://jsfiddle.net/h01sp7za/1/)

### Steps to reproduce
Pardon the outdate versions. I don't know how to replicate the issue on iview 3 but it is observed to be the same.

Click on "submit". It takes awhile before it transits into the "loading" animation.

This happens only when there are a lot of rows. Whereas for a few rows, the "loading" animation is immediate.

### What is expected?
It should transit into the "loading" animation immediately.

### What is actually happening?
"loading" animation is delayed.

**Comment by icarusion** [comment]
You should use iView 3 or 2.
