### ISSUE TITLE
记录开发中遇到的情况和BUG

### ISSUE THREAD

**Issue by luckyyyyy** [iview/iview#431]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.4

### Bug:
 * Cascader 级联选择器表单验证问题，必选就算选了也会报没选。
 * Modal 模态框无法再回调时继续弹出一个新的模态框，因为关闭时，会附带模态框实例一起关闭，并且会和后来的Modal状态冲突，比如loading会影响后来的Modal也是loading中。
 * Radio 绑定值是0时出现非预期的情况，#425。
 * MenuItem name绑定值也有类似Radio判断逻辑的问题。

### need to optimize
 * BreadcrumbItem 需要支持vue路由对象，而非字符串。
 * iSwitch 支持宽度控制。
 * Poptip 位置控制应该考虑当前浏览器的窗口，而非一定依赖placement。
 * iInput 缺少autofocus。
 * Modal 遮罩层问题，see #432。

### 建议
 * Menu 建议设置activeName为Submenu下的item时自动展开Submenu。
 * Poptip 希望Popover不要一开始就渲染DOM，也不要破坏原本的DOM结构。
 * 建议z-index动态生成，由于vue官方脚手架使用了cssnano，并且默认优化掉了zindex，导致zindex被重新生成，造成层级混乱。

**Comment by luckyyyyy** [comment]
@icarusion 暂时这些，写不动了，周一继续迁。

**Comment by dean5277** [comment]
BreadcrumbItem 需要支持vue路由对象，而非字符串。
这个需要支持一下，目前刷新页面太影响体验了。

**Comment by icarusion** [comment]
时间比较长了，很多应该都已经更新了，建议再看一下，然后单开 issue 吧。
