### ISSUE TITLE
[Bug Report]Time controls do not translate internationally.


### ISSUE THREAD

**Issue by jianyiwuhen** [iview/iview#4317]
### Environment
mac/chrom/vue 最新版本

### Reproduction link
[https://www.iviewui.com/components/time](https://www.iviewui.com/components/time)

### Steps to reproduce
国际化问题

### What is expected?
能有国际化

### What is actually happening?
没有国际化

**Comment by pentla** [comment]
This problem is caused by Chinese written directly in file.
If words changed to variable (and set all languages), this issue could be solved.

src/components/time/time.js
![2018-09-07 12 59 31](https://user-images.githubusercontent.com/21970208/45197755-eec07500-b29d-11e8-9ec7-9da271565d8b.png)

**Comment by pentla** [comment]
I made a MR,  please check it when you have time.
