### ISSUE TITLE
The [Bug Report] DatePicker date component is constructed using slots, and when you click on other elements after the date is opened, the first element click cannot be triggered, and only the second click can be triggered.


### ISSUE THREAD

**Issue by no5no6** [iview/iview#4327]
### Environment
操作系统mac，vue版本2.5.16，iview版本3.0.0

### Reproduction link
[https://jsfiddle.net/LittleChild/yyrzhm46/1831/](https://jsfiddle.net/LittleChild/yyrzhm46/1831/)

### Steps to reproduce
先点开日历控件，再点击右侧多选按钮

### What is expected?
点开日历空间后，再点击其他元素可以触发其他元素的click事件

### What is actually happening?
点开日历空间后，再点击其他元素不能触发其他元素的click事件

**Comment by icarusion** [comment]
Not a bug, it's a feature
