### ISSUE TITLE
Setting the body width of [Bug Report] causes Drop to be set to transfer= "true" with incorrect bug width.


### ISSUE THREAD

**Issue by yangdan8** [iview/iview#4338]
### Environment
win10 iview3.0.1

### Reproduction link
[https://codepen.io/yangdan8/pen/EejobV](https://codepen.io/yangdan8/pen/EejobV)

### Steps to reproduce
1.按钮
2.点击下拉框

### What is expected?
选项有正确的宽度

### What is actually happening?
下拉项的宽度变成100%

**Comment by icarusion** [comment]
#4329
