### ISSUE TITLE
[Bug Report]select remote search and display


### ISSUE THREAD

**Issue by 1479662779** [iview/iview#4346]
### Environment
mac系统vue2.5.17 chrom浏览器

### Reproduction link
[https://jsfiddle.net/yyrzhm46/1854/](https://jsfiddle.net/yyrzhm46/1854/)

### Steps to reproduce
上面连接 输入“A”直接默认选中回显的那两个值

### What is expected?
能够正常回显

### What is actually happening?
没有正常回显

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.
