### ISSUE TITLE
The width of [Bug Report]3.0.1 version select is incorrect when setting transfer.


### ISSUE THREAD

**Issue by sakura-flutter** [iview/iview#4347]
### Environment
win10 chrome68 iview3.0.1

### Reproduction link
[https://jsfiddle.net/7edxbp2y/](https://jsfiddle.net/7edxbp2y/)

### Steps to reproduce
使用iview3.0.1，select设置为transfer时，且当html body width: 100%时，Option的宽度会占满屏幕宽度。

### What is expected?
Option的宽度与select的宽度相等

### What is actually happening?
Option的宽度会占满屏幕宽度。

---
大致看了下，之前的版本设置为transfer时，Option计算的是width，但是在3.0.1时width丢失变成了min-width，而css的width写了inherit，变成了body的宽度

**Comment by icarusion** [comment]
#4329
