### ISSUE TITLE
页面路由跳转,form表单报错

### ISSUE THREAD

**Issue by SilenceDN** [iview/iview#435]
### iView 版本号
> 1.0.0

### 操作系统/浏览器 版本号
> Chrome 56

### Vue 版本号
> 1.0.26 

###Vue-router版本号
> 0.7.13

### 问题现象，以及你期望的结果是怎样的?
> 侧栏菜单使用menu组件， 当on-select时跳转路由（$router.go），现在是跳转页面间都有form表单（iview的表单验证），路由跳转时页面报错:

```
Uncaught TypeError: Cannot read property 'model' of null
    at FormItem.get (iview.js:11098)
    at FormItem.fieldValue (vue.common.js:216)
```

>直接地址栏回车页面地址是没问题的，就只有路由跳转页面才会报这个，直接导致页面不显示，

**Comment by icarusion** [comment]
不再维护 1.0
