### ISSUE TITLE
[Bug Report]DatePicker is forced to click after setting the disable attribute, which can still evocate the time selection page.


### ISSUE THREAD

**Issue by Leeero** [iview/iview#4351]
### Environment
mac/google/3.0.0

### Reproduction link
[https://run.iviewui.com/p6cZBQWW](https://run.iviewui.com/p6cZBQWW)

### Steps to reproduce
DatePicker 设置disable属性之后强行点击，依然可以唤出时间选择页面

### What is expected?
不能唤出选择页面

### What is actually happening?
设置disable属性之后强行点击，依然可以唤出时间选择页面

**Comment by CielNonam** [comment]
解决了吗

**Comment by Leeero** [comment]
这个BUG貌似还是没被修复吧？为什么被关闭了？
