### ISSUE TITLE
[Bug Report]modal component render bug, unable to render V-for data dynamically.


### ISSUE THREAD

**Issue by jlzm** [iview/iview#4354]
### Environment
windos/ chrome/ vue 3.0 

### Reproduction link
[https://run.iviewui.com/lVF5NCgW](https://run.iviewui.com/lVF5NCgW)

### Steps to reproduce
无法重现，这是一个组件的渲染bug，希望作者能够抽出宝贵的时间修复，无法动态渲染，这个弹出框无意义

### What is expected?
这是一个组件的渲染bug，希望作者能够抽出宝贵的时间修复，无法动态渲染，这个弹出框无意义

### What is actually happening?
这是一个组件的渲染bug，希望作者能够抽出宝贵的时间修复，无法动态渲染，这个弹出框无意义

**Comment by yaomingdan** [comment]
组件没问题，是你的modal都绑定了一个modal显示变量，点击是6个modal全部显示，所以看起来总是第六个显示出来，建议你调试的时候，多看看dom结构。

**Comment by xingdalee** [comment]
https://run.iviewui.com/Aclb0HQ7

**Comment by jlzm** [comment]
谢谢，之前反馈发出后就解决了
