### ISSUE TITLE
3.0.1版本，自定义主题引入基础样式问题

### ISSUE THREAD

**Issue by Zzzzzzchao** [iview/iview#4355]
3.0.1版本，自定义主题引入基础样式报错 
@import '~iview/src/styles/index.less';
报错信息如下
**Module build failed:
// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
in E:\work\vuets\node_modules\iview\src\styles\color\bezierEasing.less (line 110, column 0)**

对比旧版本的代码，发现新版本增加color文件夹下面的less文件报错。
不知道是我引入方式问题，其他原因造成的。
改成main.js 中这样引入
import 'iview/dist/styles/iview.css';
就没问题了。
希望有大佬帮忙解决一下问题。小白敬上！

**Comment by Zzzzzzchao** [comment]
这应是新版本的BUG。

**Comment by fifteenzhang** [comment]
#4156
