### ISSUE TITLE
script引用vue和iview报错

### ISSUE THREAD

**Issue by gray-zeng** [iview/iview#436]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
win7/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）
![image](https://cloud.githubusercontent.com/assets/10265042/24069453/54d64e86-0be3-11e7-8c4c-f028858698ea.png)

### 复现步骤
挂载vue和iview，创建实例后就报错

### 问题现象，以及你期望的结果是怎样的?
![image](https://cloud.githubusercontent.com/assets/10265042/24069408/96108b6a-0be2-11e7-861d-7db2d0616497.png)
而且页面空白，menu根本就没有显示

**Comment by luckyyyyy** [comment]
see https://jsfiddle.net/luckyyyyy/maea4ksz/

**Comment by icarusion** [comment]
i-menu

**Comment by markflyfly** [comment]
我也出现这个问题，这是怎么回事啊

**Comment by grey-zeng** [comment]
在非 template/render 模式下，需使用 i-menu
也就是将之前的Menu改为i-menu来使用就可以了
