### ISSUE TITLE
[Bug Report]Tabs  bug

### ISSUE THREAD

**Issue by lcx123456** [iview/iview#4362]
### Environment
windows 10/ 谷歌 68.0.3440.75/ Vue 2.5.1

### Reproduction link
[https://www.iviewui.com/components/tabs](https://www.iviewui.com/components/tabs)

### Steps to reproduce
tab高度互相影响

### What is expected?
每个tab高度互不影响

### What is actually happening?
如第一个tab高度是1000px，出现滚动条，，，切换第二个tab的时候，高度并没有1000px，但是会被第一个tab高度所影响

**Comment by xdevilj136** [comment]
我也遇到同样的问题  请问有找到解决办法吗？
