### ISSUE TITLE
[Bug Report] Hello, is there a problem with the clearable property clearable of the Select selector component in iView? The little code that the instance code did not delete at the time of verification.


### ISSUE THREAD

**Issue by GeekzzsHappy** [iview/iview#4370]
### Environment
Mac 10.12.5 ， "vue": "^2.5.2",  Safari、Chrome

### Reproduction link
[http://localhost:3000/armlane/entrywaste](http://localhost:3000/armlane/entrywaste)

### Steps to reproduce
把实例代码在Vue中应用单独界面中， 也无法出现 clearable 属性

### What is expected?
希望能帮忙阐述原因，解决问题！

### What is actually happening?
您好，iView中“Select 选择器”组件的“可清空”属性 clearable 是不是有问题？实例代码在验证的时候也没有删除的那个小❌号

**Comment by oyv1cent** [comment]
Reproduction link不要用本地链接，推荐https://run.iviewui.com/
不然是无法知道你所想表达的bug在哪
