### ISSUE TITLE
table组件的render函数中无法使用column和row参数

### ISSUE THREAD

**Issue by xiaoyyang123** [iview/iview#438]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
 2.2.1

### 能够复现问题的在线示例（重要）
https://codepen.io/xiaoyyang/pen/NpXdVY?editors=1111

### 复现步骤
控制台报错

### 问题现象，以及你期望的结果是怎样的?
`table`组件当使用`render`函数时，无法在`render`的组件里使用`row`和`column`参数。

### 你估计可能的原因是什么（选填）？
原因是`Cell.vue`中`compile`方法中，当重新生成一个`component`时，未把`row`和`column`参数添加到该实例上；当`component`实例`new`之后，加上`component.row = this.row;component.column = this.column;`可以解决这个问题

**Comment by icarusion** [comment]
这里的 {{ row }}，这个 row，并不是 render (row) 的里的 row，而是所在作用域的，也就是App，因为 整个 render 字段是一个函数，里面都是字符串。

不过这提示了我，可能会优化一下，因为2.0与1.0编译上有区别了。

**Comment by xiaoyyang123** [comment]
谢谢回答。结合源码，我理解的是`render`里的所有东西最后都是在新生成的`component`里渲染的，它的作用域应该是新的`component`，因为我在`render`里面绑定方法的时候，控制台打出的`this`也是新生成的那个`component`，而不是当前作用域，不知道这样理解是不是对的？现在我如果想在`render`函数中用`row`里面的数据，有没有什么办法？

**Comment by icarusion** [comment]
比如：
'hello' + row.name

**Comment by Tankerx** [comment]
render (row, column, index) {
    return
 `<i-button type="primary" size="small" @click="handleEdit(${row.roleId})" >修改</i-button>
   <i-button type="primary" size="small" @click="handleConfig(${index})" >配置</i-button>
    <i-button type="error" size="small" @click="handleDelete(${index})" >删除</i-button>`;
                        }

这个row里面的数据无法传过去，但是index可以，如果我想用row里面的数据，怎么办？并且我如果先对row里面的数据进行赋值，然后再传一个字符串过去也不行.

**Comment by xiaoyyang123** [comment]
如果你想直接像这样 `handleEdit(row)`传递`row`过去，需要在ivew的table组件下的Cell.vue中`const Cell = component.$mount();`这一行的前面加上 `component.row = this.row;component.column = this.column`

**Comment by Tankerx** [comment]
我加上之后还是不行，是不是要对iView这个文件夹再重新打一次包。这个包怎么打啊。
