### ISSUE TITLE
[Bug Report]Select filterable Can Not Easy to Choose the Single Word Option.

### ISSUE THREAD

**Issue by Skypow2012** [iview/iview#4383]
### Environment
Win10/Chrome68/vue3.0

### Reproduction link
[https://run.iviewui.com/8NY3sAwb](https://run.iviewui.com/8NY3sAwb)

### Steps to reproduce
First I choose the '只', then I want to choose the '扎', so I type the '扎' to the Input, But the filterable is not work.
(I think here not change is for someone want to change the another option, but I in my mind if use the filterable mode, the options need filterable by the input's value)

### What is expected?
The Options Change to The ['扎'], When I input the '扎'.

### What is actually happening?
The Options is not Change to The ['扎'], and when I blur the input, the input return to the '只' again.

---
This ques is show when the input's value is equel to the option's text.

**Comment by Skypow2012** [comment]
I find I can use '扎 '('扎' with the space) to fix this ques, but the user may not realize these like us.

**Comment by StevenLikeWatermelon** [comment]
I think you should not use Chinese in V-model.

**Comment by llccing** [comment]
你的版本
```
<Select v-model="model11" filterable>
        <Option v-for="item in cityList" :value="item.value" :key="item.value">{{ item.label }}</Option>
      </Select>
```

修改后的：key应该用数字而不是中文。即可解决问题。
```
  <Select v-model="model11" filterable>
        <Option v-for="(item, idx) in cityList" :value="item.value" :key="idx">{{ item.label }}</Option>
      </Select>

```
[DEMO](https://run.iviewui.com/yL2lNJMl)，注意key一定要是数字。

**Comment by llccing** [comment]
@icarusion ，官网的demo都是2.0版的例子，这个有准备转3.0的吧

**Comment by icarusion** [comment]
#4273
