### ISSUE TITLE
Table中render方法丢失上下文函数以及临时解决方法

### ISSUE THREAD

**Issue by kelvin8906** [iview/iview#439]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）

        {
          title: '操作',
          key: 'action',
          width: 150,
          align: 'center',
          render (row, column, index) {
            return `<i-button type="primary" size="small" @click.native="setPass(${index})">通过</i-button>
                    <i-button type="warning" size="small" @click.native="setDisabled(${index})">屏蔽</i-button>`;
          }
        }
在webpack打包后，在Table中的render方法在complile的时候没有带上content的真正的context function

### 问题现象，以及你期望的结果是怎样的?
setPass is not defined
期望可以执行上下文函数

### 你估计可能的原因是什么（选填）？
在cell的compile内有这么一个判断，决定是否将函数复制func.name === 'boundFn'，但是webpack在打包后，绑定函数并不是boundFn，而是n（因为被compress）。可以使用func.name === 'boundFn' || func.name === 'n'作为临时解决方案。

**Comment by icarusion** [comment]
不知道是否和 #454 的原因，一会尝试下，感谢

**Comment by icarusion** [comment]
现在可以了，多谢！

**Comment by wangjiezhang** [comment]
IE11下，表格里的按钮添加click事件还是有问题。

**Comment by wangjiezhang** [comment]
希望不要忽略我的问题，我这里一个项目要完工了，就卡在这里了。很急
