### ISSUE TITLE
The example of [Bug Report]menu is inconsistent with jsfiddle and the official website.


### ISSUE THREAD

**Issue by JessenPan** [iview/iview#4397]
### Environment
mac chrome 

### Reproduction link
[https://jsfiddle.net/chL9zpg1/](https://jsfiddle.net/chL9zpg1/)

### Steps to reproduce
在官网的展示里，可以把菜单的名称给展示出来，但是在jsfiddle里却不可以展示。必须写成<icon></icon>才可以.

![官网是这种样式](https://ws1.sinaimg.cn/large/0069RVTdgy1fuqr2rzsojj30s807a74o.jpg)

直接点击jsfiddle确没有显示菜单标题

![jsffidle样式](https://ws4.sinaimg.cn/large/0069RVTdgy1fuqr3z9h5fj313y0lc778.jpg)

改成这样就可以了
![改成闭标签](https://ws2.sinaimg.cn/large/0069RVTdgy1fuqr6hp37fj31bw0n6juj.jpg)

### What is expected?
官网的示例，直接跳转到jsfiddle可以用的。因为jsfiddle是非npm的模式。

### What is actually happening?
实际的结果是官网的样式和jsfiddle不一样

**Comment by icarusion** [comment]
cdn 下不能用封闭标签
