### ISSUE TITLE
select 组件在Modal中显示异常

### ISSUE THREAD

**Issue by Pinary** [iview/iview#44]
![image](https://cloud.githubusercontent.com/assets/16324157/19878713/1aed6e34-a027-11e6-8fd1-8a9abcb3740d.png)

如图所示，我通过屏蔽以下代码解决的，请问作者有没有好的解决方案呢？ 谢谢

![image](https://cloud.githubusercontent.com/assets/16324157/19878735/54a151fe-a027-11e6-801e-5a0c63d33544.png)

**Comment by icarusion** [comment]
已解决，但还没更新到npm，下个版本一起发
