### ISSUE TITLE
能否为Modal对话框提供size属性？

### ISSUE THREAD

**Issue by xland** [iview/iview#440]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
 macOS/Chrome 56

### Vue 版本号
2.2.1

能否为Modal对话框提供size属性？

**Comment by icarusion** [comment]
通过 class-name 或 width 属性，可以任意调整

**Comment by spencer-live** [comment]
+1 希望能增加size属性tiny/small/large/full, 想真自定义再说
