### ISSUE TITLE
When [Bug Report]Table generates multiple header dynamically, it will prompt errors. In the formal environment, browsers will stop responding.


### ISSUE THREAD

**Issue by xieyunjie** [iview/iview#4405]
### Environment
win chrome70 vue2

### Reproduction link
[https://jsfiddle.net/xieyunjie/Lx1y6su3/](https://jsfiddle.net/xieyunjie/Lx1y6su3/)

### Steps to reproduce
https://jsfiddle.net/xieyunjie/Lx1y6su3/
点击genTB按钮就会出现了

### What is expected?
没有出错

### What is actually happening?
测试环境能最终能生成table，但会提示错误。
但在正式环境当中会出现浏览器停止响应，无法生成table

---
fiddle当中的数据例子与官网一致，只是生成table数据的时机不一机而已。

**Comment by 7polo** [comment]
i also have this problem

**Comment by icarusion** [comment]
same issue exist

**Comment by rendq** [comment]
I have same issue. how to resolve it?
