### ISSUE TITLE
模板中组件命名问题

### ISSUE THREAD

**Issue by gera2ld** [iview/iview#441]
### iView 版本号
2.0.0-rc.5

### Vue 版本号
2.2.1

根据[Vue的这个issue](https://github.com/vuejs/vue/issues/2308)，预编译的`.vue`里面的模板是区分大小写的，也就是说，`<Col span="8">`和`<Form :model="formData">`这种组件都是可以识别的，而且不会影响`<col>`和`<form>`的使用。

即使是[通过字符串设置模板](https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats)，或者直接用DOM当作模板，`<col>`也不会因为`<Col>`的定义而被当成组件，这时写成`<i-col>`就好了。

那么问题来了：

1. 为什么组件注册的时候特意把这种类型的组件避开了（index.js里没有这几个），导致模板里面要混着写`<Row>`和`<i-col>`两种语法？而实际上只要把`Col`也注册进去，就可以正常使用`<Col>`了。这样存在什么潜在问题吗？我测试都是没有问题的，但是需要webpack打包，所以没法放到codepen上。
1. 对于直接写在HTML中的模板，浏览器不区分大小写，那为什么不写成`<form-item ...>`，而要写成`<Form-item ...>`这种奇怪的混合形式，有什么讲究吗？

期望：
1. index.js里可以把`Col`、`Form`等组件加上；
1. 文档中统一代码风格。

**Comment by icarusion** [comment]
之前和1.0兼容，这几个组件没有改，稍后集成到文档中时会一一 review 一遍，template 不支持的会加前缀i-

**Comment by BruinY** [comment]
希望能尽快处理这个大小写的问题。为开发工作带来了大量的不必要的工作。

**Comment by SergioCrisostomo** [comment]
We could add `i-` prefix to all components and keep both so far. That would make the API more consistent. 

@icarusionwhat do you think?

**Comment by icarusion** [comment]
You can use [iview-loader](https://www.iviewui.com/docs/guide/iview-loader).

@SergioCrisostomo I've been thinking about this for a long time, and I've talked to some of the developers, and I think, the current component naming method is freedom and be consistent with AntDesign.
