### ISSUE TITLE
[Bug Report] DatePicker displays errors

### ISSUE THREAD

**Issue by sparket42** [iview/iview#4412]
### Environment
OSX 10.13.6 / Chrome 68.0.3440.106、Safari 11.1.2  / Vue 2.5.2 / **iview 3.0.1**

### Reproduction link
[https://run.iviewui.com/qXWDrC2o](https://run.iviewui.com/qXWDrC2o)

### Steps to reproduce
8月31日 04:33(UTC+8)，在DatePicker（type为daterange）中显示两个相邻月份的时候，出现【左边】为【8月】，【右边】为【10月】的情况；
在官方示例（ https://www.iviewui.com/components/date-picker ） 中也出现该情况。**官方示例中，可能第一次显示正常，当多次选中输入框，再取消焦点，再选中输入框的时候，弹出的日历菜单便会出现8月后面是10月的情况**

### What is expected?
能正确显示连续两个月份，【左边】为【8月】，【右边】为【9月】

### What is actually happening?
出现【左边】为【8月】，【右边】为【10月】的情况

**Comment by icarusion** [comment]
#3773
