### ISSUE TITLE
i-table是否能加入合并单元格功能

### ISSUE THREAD

**Issue by seadog16** [iview/iview#442]
### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
i-table是否能加入合并单元格功能？类似colspan属性

**Comment by dean5277** [comment]
这个需求应该大点。

**Comment by dean5277** [comment]
@seadog16  https://github.com/dean5277/iview-table-change

**Comment by icarusion** [comment]
@1249

**Comment by q1005878349** [comment]
同求

**Comment by yunhungo** [comment]
> @seadog16 https://github.com/dean5277/iview-table-change

为什么不合并到 iview 呢？
