### ISSUE TITLE
[Bug Report]InputNumber not being validated in Form

### ISSUE THREAD

**Issue by antonelepfl** [iview/iview#4423]
### Environment
MacOS 10.13.6/Chrome 68.0.3440.106/Vue2.5.17

### Reproduction link
[https://jsfiddle.net/gtnhzjxa/](https://jsfiddle.net/gtnhzjxa/)

### Steps to reproduce
Add InputNumber into a form and try to validate it on blur

### What is expected?
The validation like *required* also work in InputNumbers

### What is actually happening?
The input number is not taking in account the number that is specified

**Comment by weidapao** [comment]
I just send PR to resolve this issus.
Before this,you can use
```
numb: [
{required: true, message: 'asdfadfa', trigger: 'change', type: 'number'}
],
```
@antonelepfl

**Comment by weidapao** [comment]
[PR#4536](https://github.com/iview/iview/pull/4536) @icarusion

**Comment by icarusion** [comment]
fixed already

**Comment by CandySunPlus** [comment]
can you release 2.x version for this hotfix @icarusion
