### ISSUE TITLE
Checkbox-group 在vue2.1.7数据无法绑定？

### ISSUE THREAD

**Issue by Mrlilili** [iview/iview#443]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
Chrome 56

### Vue 版本号
2.1.7

### 能够复现问题的在线示例（重要）
http://codepen.io/Mrlilili/pen/XMzqKb?editors=1010

**Comment by ywc6688** [comment]
iview 2.0.0-rc.17 和vue v2.1.10也是无法绑定。
调用如下图：
![image](https://user-images.githubusercontent.com/10356106/27465721-e0ae0c58-5807-11e7-8525-9259595f73e5.png)

数据一直是 
![image](https://user-images.githubusercontent.com/10356106/27465670-96e54050-5807-11e7-8eb0-9ab4a608a798.png)

页面不管怎么操作，都数据都不变。
而且checkbox要点2次才可以切换选中或取消。

**Comment by dontcallmilanac** [comment]
也遇到了，我在group上加了onchange事件。调试发现能够触发on-change事件，只是每次传入的值均为原值。

**Comment by icarusion** [comment]
更新最新版
