### ISSUE TITLE
Modal组件自定义内容关闭时的问题

### ISSUE THREAD

**Issue by Zake95** [iview/iview#4435]
Moadl组件使用render自定义内容时，如果开启了esc关闭组件，使用esc或者右上角关闭按钮关闭后，该Modal组件只是被隐藏了，并未被销毁，导致其他的操作同样产生自定义Modal组件内容时，还是先前的自定义内容。

**Comment by CrytisMT** [comment]
我也发现这个问题了  到现在3.1.3还没改。。。

**Comment by xxxKimihiro** [comment]
> 我也发现这个问题了到现在3.1.3还没改...

+1
