### ISSUE TITLE
bug report： AutoComplete  on-select event is not work

### ISSUE THREAD

**Issue by kkltmoyu** [iview/iview#4441]
### Environment
操作系统：Win7 x64，浏览器：chrom  68.0.3440.106（正式版本） （32 位），Vue版本：2.5.16，IView版本：3.1.0和2.14.3

### Reproduction link
[https://run.iviewui.com/lltRbnDh](https://run.iviewui.com/lltRbnDh)

### Steps to reproduce
在autocompelete组件中的输入框输入12后，在下拉列表中选择12，无法触发on-select事件，控制台也未输出与select：12

### What is expected?
在输入完全匹配下拉菜单内容的时候也能触发选中后也能触发on-select事件

### What is actually happening?
无法触发on-select事件，控制台也未输出与select：12

**Comment by karkinge** [comment]
Same problem here.
The on-select event is properly fired, but the function provided in the callback does not receive any value.

```
<AutoComplete @on-select="changeAddress" ... />

changeAddress (value, val2) {
    console.log(value, val2)
}
```

When selecting an option, the console output is `undefined, undefined`

**Comment by luotingv1** [comment]
这个bug没人管么

**Comment by kkltmoyu** [comment]
> 这个bug没人管么 @luotingv1 
换组件吧，我用的这个https://github.com/paliari/v-autocomplete

**Comment by 70kg** [comment]
这个真没人管吗

**Comment by Jabbar2010** [comment]
这都快一年了，官方还是不给予回应，真是！对于组件内部而言多么简单的处理...

**Comment by zhangshichuan** [comment]
AutoComplete这个组件真的厉害。只要你页面用了AutoComplete，然后一旦获取焦点，不管你选不选任何东西。都必须点击鼠标２次才能让其他输入框获取焦点
