### ISSUE TITLE
[Bug Report]In package 3.1.0,  typings path in package.json is incorrect .

### ISSUE THREAD

**Issue by SunshowerC** [iview/iview#4444]
### Environment
Mac

### Reproduction link
[https://github.com/iview/iview/blob/2.0/package.json](https://github.com/iview/iview/blob/2.0/package.json)

### Steps to reproduce
npm i -S iview@3.1.0

### What is expected?
declaration files path is `dist/types/*.d.ts`
so `package.json` should be : 
```
"typings": "dist/types/index.d.ts",
```

### What is actually happening?
```
"typings": "types/index.d.ts",
```

---
please change `package.json` or change the path of `types` folder

**Comment by icarusion** [comment]
@yangdan8 @lcx960324 please confirm if have time

**Comment by yangdan8** [comment]
是的,路径指向不正确,已提交pr #4447 
@icarusion

**Comment by yangdan8** [comment]
实例请见以下demo项目
https://github.com/yangdan8/vue-iview-ts
@Weiyu-Chen

**Comment by dmoosocool** [comment]
@yangdan8 
运行你的demo项目, 还是一样报错.
![image](https://user-images.githubusercontent.com/30599141/45072586-31534780-b10e-11e8-8628-6ce973ca55f1.png)

**Comment by yangdan8** [comment]
#4449 合并pr后会正常 @Weiyu-Chen 
@icarusion 帮忙合并一下,谢谢!
