### ISSUE TITLE
select组件中的value类型检测错误

### ISSUE THREAD

**Issue by snowdiva** [iview/iview#445]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 复现步骤
通过vue-resource函数，在ready中初始化data数据，格式类似：
```javascript
export default {
  data () {
    return {
      groupList: []
    }
  },
  ready () {
    this.init()
  },
  methods: {
    init () {
      this.$http.post('url...', postData).then(response => {
        this.groupList = response.body.data.group_list // 这里数组显示正常
      }).response ...// 代码省略
    }
  }
}
```

template代码中引用为：
```
<Form-item>
    <i-select v-model="formInline.group_id" style="width: 100px;" @on-change="showConsole">
        <i-option :value="0">全部分组</i-option>
        <i-option v-for="item in groupList" :value="item.id">{{ item.name }}</i-option>
    </i-select>
</Form-item>
```

cosole报类型检测错误：
```
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String, Number, got Undefined. 
(found in <IOption>)
```

### 问题现象，以及你期望的结果是怎样的?
我设置了一个测试的showConsole检测发现，组件返回值也是一个number类型，但是依然提示错误，其他没有问题。

**Comment by icarusion** [comment]
2.0 没有 ready，是mounted

**Comment by snowdiva** [comment]
补充一下，返回的group_list格式如下：
```
group_list: [
    { id: 1, name: '组一' },
    { id:2, name: '组二' },
    // 以下省略..
]
```

**Comment by snowdiva** [comment]
@icarusion 嗯，忘了说了，mounted，和updated我都试过了，问题同样，报错内容还是类型检测失败，但是数据已经在DOM中渲染出来了，也不影响后续使用。
但是只要触发on-change，就有console的类型检测错误提示。

**Comment by icarusion** [comment]
先把你的示例补完整吧，提供在线示例。
请求用 setTimeout 模拟。

**Comment by snowdiva** [comment]
@icarusion 没有在线空间。。。这两天我看看有空间能借用一下吧，谢谢。

**Comment by icarusion** [comment]
https://codepen.io/anon/pen/BWwVoy
到这里填

**Comment by snowdiva** [comment]
@icarusion 好的，3Q。

**Comment by snowdiva** [comment]
@icarusion 不用vue-router和vue-resource的demo似乎是正常的。

**Comment by snowdiva** [comment]
等我可以复现的时候再说，我换一种初始化数据的方式试试。

**Comment by rijn** [comment]
@snowdiva `vue-resource` will unpack data under some circumstances. Check the response carefully.

**Comment by snowdiva** [comment]
@rijn Thank you very much, I check again carefully before parsing data types

**Comment by larryu** [comment]
I have the same problem here. Exactly the same use case. Any clues about this issue?

iView 版本号

2.0.0-rc.9

操作系统/浏览器 版本号

Windows/IE 11

Vue 版本号
2.1.10

**Comment by larryu** [comment]
PS.  All good on Chrome and Firefox.

**Comment by xuange306** [comment]
首先,你得确定是不是由select引起的,看下是不是使用了Cascader 级联选择器这个组件
其次,data中定义v-model所对应的变量的时候,不要赋默认值为空字符串"", 给赋值为 null.
