### ISSUE TITLE
The [Bug Report]DatePicker component is empty in daterange.


### ISSUE THREAD

**Issue by bao2314483** [iview/iview#4450]
### Environment
3.1.0

### Reproduction link
[https://run.iviewui.com/u16vjzDR](https://run.iviewui.com/u16vjzDR)

### Steps to reproduce
DatePicker组件在daterange下绑定值报错
清空日期也同样报错
错误提示: Cannot read property 'getTime' of null

### What is expected?
处理BUG

### What is actually happening?
处理BUG

**Comment by icarusion** [comment]
fixed in #4473

**Comment by icarusion** [comment]
fixed
