### ISSUE TITLE
[Bug Report]Anchor reported wrong


### ISSUE THREAD

**Issue by skyqinsc** [iview/iview#4452]
### Environment
chrome

### Reproduction link
[https://run.iviewui.com/fIFd46r4](https://run.iviewui.com/fIFd46r4)

### Steps to reproduce
In Chrome Console：

vue.min.js:6 TypeError: Cannot read property 'offset' of undefined
    at o.<anonymous> (anchor.vue:171)
    at Array.<anonymous> (vue.min.js:6)
    at Ke (vue.min.js:6)

### What is expected?
warning

### What is actually happening?
no warning

**Comment by vopdoo** [comment]
实际使用过程中也是报这个错误
```html
<Anchor :affix="false" show-ink>
        <AnchorLink href="#basic_usage" title="Basic Usage"/>
         <AnchorLink href="#static_position" title="Static Position"/>
          <AnchorLink href="#comments" title="评论">
                            <AnchorLink href="#Anchor_props" title="Anchor props"/>
                            <AnchorLink href="#Anchor_events" title="Anchor events"/>
                            <AnchorLink href="#AnchorLink_props" title="AnchorLink props"/>
           </AnchorLink>
</Anchor>
```

![image](https://user-images.githubusercontent.com/42235710/45285497-dce90700-b515-11e8-9564-a0d65febb11f.png)
@icarusion 
页面中只使用一次 但会有 14 次同样的报错，是使用姿势不对么？
