### ISSUE TITLE
[Bug Report]Message is blocked by Modal.


### ISSUE THREAD

**Issue by Feawaris** [iview/iview#4453]
### Environment
iview3.1.0

### Reproduction link
[https://run.iviewui.com/OM0jOgqM](https://run.iviewui.com/OM0jOgqM)

### Steps to reproduce
弹开Modal，连续点击6次以上“完成”按钮，会看到Message都被遮挡

### What is expected?
全局提示Message始终在上方

### What is actually happening?
提示会被挡住

---
每次点击Modal区域，.ivu-modal-wrap的z-index都会加1，到1011后遮挡住了提示

**Comment by yangzhi666** [comment]
而且，不仅仅是message的问题，如果模态框里面有dom结构操作或者基于z-index的实现，也会使得z-index一直小于模态框

**Comment by huashengwang1989** [comment]
Add-on to the referenced and closed issue:

`handleClickModal` also causes the problem.

I managed to hack the modal from outside (without modifying the component) to fix the `z-index` issue, but soon realise that there is a `handleClickModal` method existing which would immediately reset the `z-index` and making the modal behind the mask again once clicked.
