### ISSUE TITLE
[Bug Report]Autocomplete show options only when i click.

### ISSUE THREAD

**Issue by ciriloveloso** [iview/iview#4455]
### Environment
Ubuntu 14, chrome Versão 68.0.3440.106 (Versão oficial) 64 bits, Vue 2.5.17 e Iview 3.01

### Reproduction link
[https://www.iviewui.com/components/auto-complete-en#Customized](https://www.iviewui.com/components/auto-complete-en#Customized)

### Steps to reproduce
click in basic usage sample and TAB key untill Customized sample, press test ( see do not appear )
now click and you will see...
then, it work only when i click..

### What is expected?
when i navegate with TAB key ou Click direct in field should show options to choice

### What is actually happening?
Only when I click direct in field it show options to choice

---
I do not use DATA property
I use @on-search event to find options on web services

**Comment by ciriloveloso** [comment]
my code:

```
<AutoComplete v-model="filter.nome" @on-search="onComplete" @on-select="onSelect" icon="ios-search" tabindex="-1" :class="{'input-style-green': idDelegacia}" element-id="delegaciaCompleteInput" clearable>
  <Option v-for="delegacia in options.delegacias" :value="delegacia.nome" :key="delegacia.id_delegacia">{{ delegacia.nome }}</Option>
</AutoComplete>
```


```
onComplete(value) {
      let me = this
      me.delegacia = null
      if (value && value.length >= 2) {
        DelegaciasAPI.list({ nome: value }, {}, this.paginationDelegacias)
          .then(res => {
            me.options.delegacias = res.data
          })
          .catch(error => me.$Notifica.noticeErro(error.message))
      }
    }
```

**Comment by Daisny** [comment]
我们也是遇到问题了，当粘贴文本进去，然后异步请求搜索结果的话就不会显示下拉菜单~
改成同步的数据请求~~好像就可以~~~~~
或者数组给一个默认值貌似也可以

**Comment by maggiew61** [comment]
https://github.com/iview/iview/issues/4985   I think the author fixed the issue

**Comment by zhangshichuan** [comment]
@maggiew61 How do I sync the fixed updates to my own project? Thank you

**Comment by maggiew61** [comment]
you can uninstall ivew then install iview then the updated iview contains the fixed updates. at least that's how I did it and worked like charm
    On Tuesday, January 15, 2019, 10:39:24 AM GMT+8, 张仕传 <notifications@github.com> wrote:  
 
 
@maggiew61 How do I sync the fixed updates to my own project? Thank you
