### ISSUE TITLE
[Bug Report]datepicker

### ISSUE THREAD

**Issue by baymaxmax** [iview/iview#4456]
### Environment
windows

### Reproduction link
[https://www.iviewui.com/components/date-picker](https://www.iviewui.com/components/date-picker)

### Steps to reproduce
datepicker  type="daterange"  选择一个有31号的月和下一个月（这个月应该是没有31天的月份）随便一天的日期范围（比如8.31-9.20），选好之后再打开面板点击‘上一月’按钮几次（基本上是2次）左右两个面板会变成一个月的

### What is expected?
正常是两个面板是前后两个月

### What is actually happening?
两个面板相同了

---
在ivew官网上Datepicker的例子实验就可以，不需要别的代码了，选择31日和某个跨月的日期是有问题的，iview2就存在，iview3好像改了，但是还有问题

**Comment by SergioCrisostomo** [comment]
@baymaxmax what version are you using? I think this has been fixed in `v3.1.0`
