### ISSUE TITLE
In the [Bug Report]page component, when the total total is 0, the page number current_page does not return the correct value.


### ISSUE THREAD

**Issue by xg-qd** [iview/iview#4457]
### Environment
Window7/Chrome69.0/Vue2.0

### Reproduction link
[https://run.iviewui.com/ptvvKjXg](https://run.iviewui.com/ptvvKjXg)

### Steps to reproduce
1.页数选择大于1
2.清空总数

### What is expected?
当数量为0时，页数应为1

### What is actually happening?
页数为当前选择的页数

**Comment by xg-qd** [comment]
can i fixed this bug

**Comment by icarusion** [comment]
You should update `current`
