### ISSUE TITLE
The [Bug Report] table component "sets a special key_highlight: true for the data item to select the current item by default." Dynamic insertion of highlight: true cannot render


### ISSUE THREAD

**Issue by liucien** [iview/iview#4461]
### Environment
win10 / chrome 68.0.3440.106  /vue:2.5.13

### Reproduction link
[https://jsfiddle.net/yyrzhm46/2013/](https://jsfiddle.net/yyrzhm46/2013/)

### Steps to reproduce
2.x的官方例子改造，直接通过按钮在data1中添加highlight: true      
链接https://jsfiddle.net/yyrzhm46/2013/

### What is expected?
希望能够进行动态渲染

### What is actually happening?
无法进行动态渲染

**Comment by xg-qd** [comment]
this problem case is not by iview components, in fact  vue cannot observer the non-existent property ,you can read this url https://cn.vuejs.org/v2/guide/reactivity.html 。or you can read my test https://jsfiddle.net/guosd/yyrzhm46/2016/

**Comment by liucien** [comment]
谢谢回答，解决一个大问题，原来是跟响应式原理有关
