### ISSUE TITLE
[Bug Report]iview 3.1.0 import iView from'iview'; error reporting


### ISSUE THREAD

**Issue by ZhaoRd** [iview/iview#4463]
### Environment
win10  / 谷歌浏览器 /  3.0.1

### Reproduction link
[https://jsfiddle.net/yyrzhm46/](https://jsfiddle.net/yyrzhm46/)

### Steps to reproduce
注： 重现连接无效

1.  使用 vue创建项目
2. 在main.ts 中引入 iview 模块，import iView from 'iview';  

### What is expected?
1.  vscode 不报错
2.  yarn  server  不报错
3.  使用组件不报错

### What is actually happening?
1.  vscode提示找不到模块
2.  yarn server 报错： Could not find a declaration file for module 'iview'. 'F:/work/vue/vue-alain-iview/node_modules/iview/dist/iview.js' implicitly has an 'any' type.

3.  使用组件报错：Uncaught RangeError: Maximum call stack size exceeded

**Comment by SunshowerC** [comment]
#4444   这是官方纰漏，版本没发布的之前只能自己改 iview 的 node modules 进行修复

**Comment by ZhaoRd** [comment]
@Weiyu-Chen   Ok， TKS!
