### ISSUE TITLE
[Bug Report]Typescript Error : 'XXX' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by SunshowerC** [iview/iview#4465]
### Environment
Mac

### Reproduction link
[https://github.com/iview/iview/blob/2.0/types/loading-bar.d.ts](https://github.com/iview/iview/blob/2.0/types/loading-bar.d.ts)

### Steps to reproduce
In a js file : 
```
import { LoadingBar } from "iview"
LoadingBar.start()  // 'LoadingBar' only refers to a type, but is being used as a value here.
```

### What is expected?
should not throw typescript error.

### What is actually happening?
` 'LoadingBar' only refers to a type, but is being used as a value here.`

---
That is because in the `types/loading-bar.d.ts` , it exports LoadingBar as an `interface`
```
// PS: `declare` keyword is useless here. 
export declare interface LoadingBar {
    // ....
}
```  

It should also export  like that: 
```
export const LoadingBar: LoadingBar
```
***Not only `LoadingBar` show that problem but others like `Notice` and so on.***

**Comment by SunshowerC** [comment]
For those who suffer from this problem, you can simply fix it in your global declaration file : 
```
// declaration file like : global.d.ts
import { LoadingBar } from "iview"
declare module "iview/dist/types/loading-bar" {
    export const LoadingBar:LoadingBar
}
```

**Comment by Baoyx007** [comment]
same problem

**Comment by jo0ger** [comment]
+1

**Comment by ZhengZhouXu** [comment]
+1

**Comment by tempscript** [comment]
+1

**Comment by jiabinxiong** [comment]
import { LoadingBar } from "iview"
declare module "iview/dist/types/loading-bar" {
    export const LoadingBar:LoadingBar
}

Button TimePicker 可认 
Tag 这样做还是报错
33:22 Argument of type 'Tag' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Types of property 'name' are incompatible.
    Type 'string | number | undefined' is not assignable to type 'string | undefined'.
      Type 'number' is not assignable to type 'string | undefined'.
MenuItem 也是
43:27 Argument of type 'MenuItem' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Types of property 'name' are incompatible.
    Type 'string | number | undefined' is not assignable to type 'string | undefined'.
      Type 'number' is not assignable to type 'string | undefined'.

**Comment by icarusion** [comment]
@yangdan8 Please have a look this issue, thank you.

**Comment by zikunrain** [comment]
i am suffering such problem too. and @Weiyu-Chen 's solution does not work for me

**Comment by MichaelGong** [comment]
我创建了一个 iview.d.ts，写入了
```ts
import { Notice, Message, LoadingBar } from 'iview';
declare module 'iview/dist/types/notice' {
  export const Notice: Notice;
}
declare module 'iview/dist/types/message' {
  export const Message: Message;
}
declare module 'iview/dist/types/LoadingBar' {
  export const LoadingBar: LoadingBar;
}
```

**Comment by wizardpisces** [comment]
same problem

**Comment by wizardpisces** [comment]
same problem

**Comment by wizardpisces** [comment]
same problem here, has anyone solved yet?

 recreation step

1. use vue-cli3 with typescript
2. vue add iview 
3. partial import {Button} from 'iview'

16:9 'Button' only refers to a type, but is being used as a value here.
    14 |     
    15 |     components:{
  >16 |         Button
         |         ^
    17 |     },

**Comment by dengying3939** [comment]
> 对于那些遭受此问题的人，您只需在全局声明文件中修复它：
> 
> ```
> // declaration file like : global.d.ts
> import { LoadingBar } from "iview"
> declare module "iview/dist/types/loading-bar" {
>     export const LoadingBar:LoadingBar
> }
> ```

I wrote according to your suggestion, although the editor no longer reports an error, but still reports the same error in the console.

**Comment by yangdan8** [comment]
合并pr后可关闭 @icarusion

**Comment by yangdan8** [comment]
> For those who suffer from this problem, you can simply fix it in your global declaration file :
> 
> ```
> // declaration file like : global.d.ts
> import { LoadingBar } from "iview"
> declare module "iview/dist/types/loading-bar" {
>     export const LoadingBar:LoadingBar
> }
> ```

下个版本需要移除您这里的定义

**Comment by icarusion** [comment]
#4465

**Comment by littleliar** [comment]
@yangdan8 所有的组件都有这个问题, 不是只有 loading-bar

**Comment by elilabes** [comment]
@icarusion this is happening for all components, is there a fix for this that is not going through all components adding an export const etc etc?

**Comment by Baoyx007** [comment]
@icarusion this is happening for all components, is there a fix for this that is not going through all components adding an export const etc etc?

**Comment by FavorPan** [comment]
@icarusion @yangdan8 this is happening for all components, is there a fix for this that is not going through all components adding an export const etc etc?

**Comment by 472647301** [comment]
我是这样使用的
![image](https://user-images.githubusercontent.com/26315702/54744535-30918700-4c02-11e9-8969-e3a4069253e1.png)
![image](https://user-images.githubusercontent.com/26315702/54744557-3edfa300-4c02-11e9-8929-5ffdb63a753a.png)
![image](https://user-images.githubusercontent.com/26315702/54744600-646cac80-4c02-11e9-89ad-b93ba53ac054.png)

**Comment by cklwblove** [comment]
这个问题解决了吗？目前按照上面环境，同样的引用方法，还是会出现问题

**Comment by zhang14725804** [comment]
iview 3.4.1
vue2.6.10
typescript3.4.3
想要在一个公共的ts文件（非component）中增加提示组件
 'Message' only refers to a type, but is being used as a value here.

**Comment by zp18823358143** [comment]
vue-cli3.0+中结合typescript引入  iview，不管是全局引入还是按需引入，弹框类组件都报错，信息如下：
'Message' only refers to a type, but is being used as a value here.

**Comment by dengying3939** [comment]
非常谢谢您的回复，我已经知道该怎么用了
虽然我现在才看到，但还是非常感谢

在 2019-03-21 17:56:08，"秃尾巴的猫" <notifications@github.com> 写道：


我是这样使用的

**Comment by Haixiang6123** [comment]
Now iview is switching its name to 'view-design'. So, now it will be like this:
```
import { Message } from "view-design"
declare module "view-design/dist/types/loading-bar" {
  export const Message:Message
}
```
