### ISSUE TITLE
[Bug Report]select multiple  v-model  bug

### ISSUE THREAD

**Issue by chen-ABC** [iview/iview#4466]
### Environment
windows10  vue2.x  Chrome67

### Reproduction link
[https://run.iviewui.com/DAf7X6TC](https://run.iviewui.com/DAf7X6TC)

### Steps to reproduce
1.先选择第一个选项
2.点击按钮进行date数组push,第6个选项

select组件多选时 直接设置与v-model 绑定的date
date.push(''),按vue v-model说明 数组push方法应该触发视图更新,但是无效

### What is expected?
绑定数据进行 push方法 视图会更新

### What is actually happening?
视图未更新

**Comment by RenShine** [comment]
PR #4575  @icarusion
