### ISSUE TITLE
[Feature Request] Adds option icons and selected icons to select, and adds the display content as "icons," text "or both display functions


### ISSUE THREAD

**Issue by yangdan8** [iview/iview#4469]
### What problem does this feature solve?
可以显示图表加文字是下拉框,或者是单纯的图标选择器

### What does the proposed API look like?
select增加api
dispayMode='icon' | 'text' | 'iconAndText', 默认text
option增加api
icon=''
custIcon=''

**Comment by icarusion** [comment]
Option 是支持 slot 自定义的。
