### ISSUE TITLE
[Feature Request] wants to switch the way to get a document. It is recommended that you change the direct document to this $el. getRootNode () == document, or you can choose which document to use by the user.


### ISSUE THREAD

**Issue by fierflame** [iview/iview#4470]
### What problem does this feature solve?
对iframe内或者其他页面渲染Vue时，可以保证this.$Spin.show()等仅出现在iframe内或其他页面，而不是导入iview的页面

### What does the proposed API look like?
对iframe内或者其他页面渲染Vue时，可以保证this.$Spin.show()等仅出现在iframe内或其他页面，而不是导入iview的页面

**Comment by icarusion** [comment]
No such plan now.
