### ISSUE TITLE
[Bug Report]Modal ZIndex breaks when @zindex-modal is changed in the custom.less file in 3.1.0

### ISSUE THREAD

**Issue by huashengwang1989** [iview/iview#4471]
### Environment
Mac OS X 10.13.6 (17G65), Chrome 68.0.3440.106, Vue 2.8.2

### Reproduction link
[http://no-link-as-not-sure-how-to-reproduce-with-modal-instance-and-less.com](http://no-link-as-not-sure-how-to-reproduce-with-modal-instance-and-less.com)

### Steps to reproduce
I am sorry that I cannot figure out how to reproduce it in JSFiddle, as I failed to make import `less` working there, nor able to use `this.$Modal` for modal instance calls.

This happens for iView 3.1.0 due to the new update on Modal's `z-index`.

1. Follow the steps in "Customize Theme" page and create a `less` file to overwrite iView's default styles, with update on the `@zindex-modal` value, such as change it to `3000`. Import it.

2. If I leave the `z-index` prop unset (for now it's default to 1000), or use modal instance `this.$Modal.confirm(config)`  to call the modal (which have no place to specify it's `z-index`), I will have a modal panel beneath the mask.

### What is expected?
If the `z-index` prop is not set, the modal's mask (`.ivu-modal-mask`) and modal panel (`.ivu-modal-wrap`) should both honor the `@zindex-modal` value from the `less` file. *e.g.* If it is set to `3000`, the mask would have `z-index` to `3000`, and the panel's `z-index` should be `3001` or larger.

### What is actually happening?
Regardless the `@zindex-modal` value, the modal panel's `z-index` is now always 1000 . This may possibly make it beneath the mask (which follows `@zindex-modal` value), resulting in an unusable modal.

The newly updated incremental `z-index` from `1000` for `.ivu-modal-wrap` is hard-coded as an inline style, and this makes overwriting it via CSS rather challenging. The modal component has a new `z-index` prop which can kind of avoid this problem; but if modal instance is used, there is no `z-index` prop for the config.

It would be better if the `@zindex-modal` value from less can be honored, and the `z-index` prop in Modal component should be default to *e.g.* `undefined`, rather than `1000`. If it is `undefined`, the modal's mask and panel can still follow `@zindex-modal` value without inline styles, and if it is specified, it will the follow the specified value.

The Modal instance this $Modal should also follow the above-mentioned way of handling `z-index`, as either both mask and panel follow `@zindex-modal`, or it takes `zIndex` for its config.

**Comment by icarusion** [comment]
$4453

**Comment by icarusion** [comment]
#4453
