### ISSUE TITLE
[Feature Request]Modal need both  mask &  draggable

### ISSUE THREAD

**Issue by adamma1024** [iview/iview#4478]
### What problem does this feature solve?
用户在使用modal的时候，modal本身会遮住部分内容，draggable可以解决，但是draggable 之后遮罩层就没了，用户可修改网页内容。这是不希望的。希望遮罩和拖拽同时存在

### What does the proposed API look like?
Modal need both  mask &  draggable

**Comment by icarusion** [comment]
No such plan.

**Comment by KendallMa** [comment]
and even if mask can be ignored,but when opend one Madal and another Madal you can still click

**Comment by mozhs** [comment]
或许这个指令能帮到你！适用于 iview 2.0，对于 iview 3.0 你也可以考虑自己写兼容指令 https://github.com/iview/iview/pull/4202#issuecomment-450272292

**Comment by allen2001** [comment]
我感觉这个功能还是很有必要
