### ISSUE TITLE
i-table 嵌套表格

### ISSUE THREAD

**Issue by ckryo** [iview/iview#448]
请问 i-table 实现了嵌套表格吗？还是需要自己实现？如果自己实现是否有什么注意事项？
![image](https://cloud.githubusercontent.com/assets/10364500/24130777/870810b2-0e25-11e7-89bc-c5c63dcb6094.png)
类似这个。
https://ant.design/components/table-cn/#components-table-demo-edit-cell

**Comment by icarusion** [comment]
目前还不支持，后面有计划增加此功能

**Comment by icarusion** [comment]
rc.15 supported.
