### ISSUE TITLE
iview中的input框不支持keyup事件吗？

### ISSUE THREAD

**Issue by Peterlhx** [iview/iview#449]
### iView 版本号
 2.0.0-rc.4

### 操作系统/浏览器 版本号

windows 10/Chrome 56

### Vue 版本号
 2.2.4

### 能够复现问题的在线示例（重要）
![image](https://cloud.githubusercontent.com/assets/11450619/24130711/3a1a87e4-0e25-11e7-97b7-4405844cf833.png)

### 问题现象，以及你期望的结果是怎样的?
现在敲击回车没有反应，应该要会执行alert方法才对
### 你估计可能的原因是什么（选填）？
是编译渲染文本框后，丢失了keyup的事件绑定吗？

**Comment by icarusion** [comment]
https://www.iviewui.com/components/input#iInput_events

**Comment by Peterlhx** [comment]
好的，谢谢啊。

**Comment by vikyd** [comment]
借楼说一个坑：

应使用 `@on-keyup="handleKeyup"`，

而非 `@keyup="handleKeyup"` 或 `on-keyup="handleKeyup"`

具体这个 pr：https://github.com/iview/iview/pull/1390
