### ISSUE TITLE
[Bug Report]v2.8.0, select select box fuzzy matching, input full name, unable to match the input data.


### ISSUE THREAD

**Issue by makerhou** [iview/iview#4491]
### Environment
vue2.5.13,window 10, chrome 版本 68.0.3440.106（正式版本） （64 位）

### Reproduction link
[http://v2.iviewui.com/components/select](http://v2.iviewui.com/components/select)

### Steps to reproduce
点击select可搜索功能，输入New York，查看匹配列表

### What is expected?
输入New York，匹配列表中只有New York，可供选择

### What is actually happening?
出现所有数据

**Comment by DebugIsFalse** [comment]
Duplicate of #5216
