### ISSUE TITLE
[Bug Report]iview select

### ISSUE THREAD

**Issue by djkloop** [iview/iview#4495]
### Environment
all

### Reproduction link
[https://run.iviewui.com/NCg0C5fw](https://run.iviewui.com/NCg0C5fw)

### Steps to reproduce
检索过滤功能, 输入全文之后检索不到，必须在后面要加一个空格

### What is expected?
正确显示

### What is actually happening?
不能检索出来

---
官网的例子里面也可以测出来整个bug，
顺带说一下官网上面一排的菜单 教程那个按钮的红点飞了

**Comment by icarusion** [comment]
https://github.com/iview/iview/pull/4598
