### ISSUE TITLE
[Bug Report]select remote mode can not display all background return results.


### ISSUE THREAD

**Issue by iuvword** [iview/iview#4498]
### Environment
win10/Chrome 67.0.3396.87

### Reproduction link
[https://run.iviewui.com/Hw6F7ezI](https://run.iviewui.com/Hw6F7ezI)

### Steps to reproduce
输入 03

### What is expected?
能显示所有options的值

### What is actually happening?
 options.length 为 1， 但显示无匹配数据

---
只能匹配 Option value 和 label 里面有的值，
比如本例子  后台是根据传入的商品编号（no这个字段）来筛选数据，这样就导致了 本来后台返回的有数据 ，而前端显示了无匹配数据

**Comment by oyv1cent** [comment]
https://run.iviewui.com/XxbwGk5c
 value的值会影响筛选结果

**Comment by iuvword** [comment]
我也知道value会影响结果，但是 我选择一个之后需要的值是 商品id ，如果value改成其他的了怎么获取商品id呢？

**Comment by oyv1cent** [comment]
我觉得对于远程搜索模式来说，不应该再进行验证筛选，直接用远程搜索所返回值即可。
但这个需要考虑一下，有空的时候，我去问问作者对这个的看法吧。

**Comment by iuvword** [comment]
恩恩

**Comment by shixianqin** [comment]
@oyv1cent ,非常感谢，远程搜索的 query 字符串需要和 Option 组件的 value 值验证相似，才会把后台返回的结果全部填充到列表上，比如：
我要通过手机号码搜索数据，那么Option 的value属性需要绑定后台返回的列表的手机号码字段值
