### ISSUE TITLE
局部引入如何支持国际化？

### ISSUE THREAD

**Issue by liuyanshi** [iview/iview#450]
文档这里， 是全部引入iview
```
import Vue from 'vue';
import iView from 'iview';
import locale from 'iview/src/locale/lang/en-US';

Vue.use(iView, { locale });
```

局部引入， 并没有引入ivew， 因此下面Vue.use这里也就失去了意义
```
Vue.use(iView, { locale });
```
因此想请教下， 怎么在局部引入的情况下， 怎么进行国际化？

**Comment by icarusion** [comment]
可以参考 vue-i18n 的用法试下。

**Comment by rodgeryuan163com** [comment]
我有一个不入流的方法，我直接引用的编译好的，然后把文件内容改了。。。。反正iview中也没几个需要国际化的字符串。

**Comment by ultraN** [comment]
请问楼主是怎么解决的？

**Comment by westdrug** [comment]
![image](https://user-images.githubusercontent.com/19603222/41590900-c6990bb0-73ea-11e8-9657-a1f08a88a9ed.png)
想到个办法，但切换语言后，组件的语言切换有延迟，点几下才换

**Comment by westdrug** [comment]
`let localeVal = this.$i18n.locale === 'zh-CN' ? zh : en; this.$Locale(localeVal)`
想到个办法，但这样切换后，组件中的变化会延迟，点几下才换
