### ISSUE TITLE
Add Icon to DropdownItem on the left side of [Feature Request]Dropdown


### ISSUE THREAD

**Issue by vopdoo** [iview/iview#4509]
### What problem does this feature solve?
希望在 Dropdown组件中DropdownItem 文本的左侧增加自定义图标，目前虽然可以自己手动增加，但不是很方便
自己增加的图标和文本 感觉没有对齐

### What does the proposed API look like?
DropdownItem 增加一个props 如icon 可以传入指定图标或者自定义图标

**Comment by icarusion** [comment]
No such plan
