### ISSUE TITLE
[Bug Report]TypeScript Error: Parameter 'l' implicitly has an 'any' type

### ISSUE THREAD

**Issue by KangdaOOLin** [iview/iview#4510]
### Environment
操作系统 Macbook / 浏览器 Chrome / Vue 2.5.17 / iview 3.1.0

### Reproduction link
[https://github.com/wenkanglin/iview-bug-reporter](https://github.com/wenkanglin/iview-bug-reporter)

### Steps to reproduce
1. 使用 vue-cli 初始化一个项目，并选择 TypeScript 特性

```shell
vue create my-iview-app
```

2. 安装 iview

```shell
yarn add iview
```

3. 在入口文件 `main.ts` 中引入&使用 iview

```
import Vue from 'vue';
import iView from 'iview';

Vue.use(iView);
```

当然因为目前 types 引入的地址是错误的，所以需要先纠正引入地址的问题。详情查看这个 [issue](https://github.com/iview/iview/issues/4465)

4. 运行 `yarn serve`，然后能看到报错提示

### What is expected?
不会有报错

### What is actually happening?
```
ERROR in /iview-app/node_modules/iview/dist/types/iview.components.d.ts
68:14 Parameter 'l' implicitly has an 'any' type.
    66 | declare const API: {
    67 |     version: string;
  > 68 |     locale: (l) => void;
       |              ^
    69 |     i18n: (fn) => void;
    70 |     install: (
    71 |         Vue: Vue,
ERROR in /iview-app/node_modules/iview/dist/types/iview.components.d.ts
69:12 Parameter 'fn' implicitly has an 'any' type.
    67 |     version: string;
    68 |     locale: (l) => void;
  > 69 |     i18n: (fn) => void;
       |            ^
    70 |     install: (
    71 |         Vue: Vue,
    72 |         opts: {
```

---
这个是因为 `iview.components.d.ts` 这个声明文件，报错地方的参数使用了隐式 any，而 vue-cli 开启 TypeScript 特性，默认是开启了 `noImplicitAny: true` 这个编译选项，所以报错。

所以，初期快速解决的方案就是加上 any 类型声明，来更好的支持 vue-cli。

**Comment by KangdaOOLin** [comment]
Closed because fixed in version 3.1.1

**Comment by cuzox** [comment]
Still having an issue in 3.1.4
