### ISSUE TITLE
[Feature Request] tree control Tree sub node is selected, affecting the parent node selection status.


### ISSUE THREAD

**Issue by pageupdown** [iview/iview#4519]
### What problem does this feature solve?
在生产环境下，可能存在，子节点全部勾选，不需要默认勾选父节点的情况，建议能够做到参数配置，设置是否需要做到默认勾选父节点

### What does the proposed API look like?
期望能够做到参数配置，设置是否需要做到默认勾选父节点

**Comment by debugsw** [comment]
项目遇到同样的问题,建议采纳,更新版本

**Comment by dunkboy** [comment]
我也有这需求

**Comment by icarusion** [comment]
No such plan
