### ISSUE TITLE
[Bug Report]iview3.10:DatePicker data will be false if it is empty array.


### ISSUE THREAD

**Issue by andyliyuze** [iview/iview#4521]
### Environment
iview3.10

### Reproduction link
[https://www.iviewui.com/components/date-picker#KJFS](https://www.iviewui.com/components/date-picker#KJFS)

### Steps to reproduce
 1 <DatePicker v-model="query.daterange" type="daterange" split-panels placeholder="日期范围" style="width: 200px"></DatePicker> 
2 两种情况会报错，第一DatePicker 有值时，当点击清除按钮时会报错。第二 ：DatePicker 数据如果为空数组会报错

### What is expected?
不会报错

### What is actually happening?
报错

**Comment by huanglii** [comment]
If i had set 'split-panels', there will be an exception when i clear the date.
TypeError: Cannot read property 'getTime' of null at o.setPanelDates(vendors.6fb85938881433de1d35.js:30)

The same question at the official website：https://www.iviewui.com/components/date-picker#MBBLD
