### ISSUE TITLE
[Bug Report]datepicker with the type of daterange and prop of  split-panels will console error in one condition

### ISSUE THREAD

**Issue by movechip** [iview/iview#4524]
### Environment
windows10/chrome69.0.3497.92/Vue@v2.5.17/iview@3.1.0

### Reproduction link
[https://run.iviewui.com/bJjxTM34](https://run.iviewui.com/bJjxTM34)

### Steps to reproduce
The type of datepicker is daterange, and it adds the prop of `split-panels` ，first, click the datepicker's input ;second, do nothing, click the blank area to close the datepick's panel; finally, click the blank area to make  the datepicker's input blur, the browser's dev-tool will console the error of vue

datepicker的类型为双面板(daterange)，而且添加了 “不联动(split-panels)” 的属性。首先点击datepicker的input,然后什么也不做，点击空白处使日期选择面板消失，最后点击空白处使input失去焦点，浏览器开发者工具中会有vue的报错信息

### What is expected?
dont console the error

### What is actually happening?
console the error

**Comment by coconilu** [comment]
I also meet this problem
