### ISSUE TITLE
[Bug Report]TimePicker cannot be used under timerange type.


### ISSUE THREAD

**Issue by ghost** [iview/iview#4531]
### Environment
macOS 10.13.6 / chrome 69 /Vue 2.5.17

### Reproduction link
[https://run.iviewui.com/pKINyH9V](https://run.iviewui.com/pKINyH9V)

### Steps to reproduce
点击选择时间

### What is expected?
点选时间显示被选中

### What is actually happening?
没有任何反馈

**Comment by icarusion** [comment]
#4473
