### ISSUE TITLE
[Bug Report]Dropdown style does not work when this dropdown has transfer prop

### ISSUE THREAD

**Issue by buildJava** [iview/iview#4532]
### Environment
MAC OSX Chrome 67.0.3396.99  vue3.1.0

### Reproduction link
[https://run.iviewui.com/uW3dBO3K](https://run.iviewui.com/uW3dBO3K)

### Steps to reproduce
in dropdown style prop we set the max-height:250px does not work

### What is expected?
when it's transfer we could custom it's prop

### What is actually happening?
does not work

**Comment by kornalius** [comment]
+1 Same thing happens for me

**Comment by kornalius** [comment]
Wow! Bad bot. :(
