### ISSUE TITLE
[Bug Report]TimePicker whose type is timerange has serious problem when selecting time

### ISSUE THREAD

**Issue by coconilu** [iview/iview#4539]
### Environment
win10 / Google Chrome 69 (FireFox 61) / Vue 3.1.0

### Reproduction link
[https://run.iviewui.com/icbMmkau](https://run.iviewui.com/icbMmkau)

### Steps to reproduce
设置timepicker的type为timerange，点击该组件就会报错

### What is expected?
正常的是可以选择时间阶段的

### What is actually happening?
报错，控制台显示：e.search is not a function

---
我是把iview从2.x升级到3.x遇到的bug

**Comment by icarusion** [comment]
#4473
