### ISSUE TITLE
Error of minimum column width attribute in [Bug Report] form


### ISSUE THREAD

**Issue by weiyie** [iview/iview#4542]
### Environment
Windows /chrome最新版/iview3.0.0 

### Reproduction link
[https://run.iviewui.com/r0XdEGwF](https://run.iviewui.com/r0XdEGwF)

### Steps to reproduce
给table的column属性设置minWidth属性

### What is expected?
minWidth：100的情况下期望设置minWidth属性的列，最小宽度为100px

### What is actually happening?
minWidth：100的情况下实际设置minWidth属性的列，最小宽度为100 原有宽度

---
table.vue组件中 有一行设置列宽度代码为：

let width = columnWidth (column.minWidth?column.minWidth:0);

**Comment by pangxieju** [comment]
![20180917093615](https://user-images.githubusercontent.com/18155203/45603271-2f1db100-ba5d-11e8-85e9-564e4b1abe22.png)
1、检查节点，发现设置 minWidth 是生效的；
table.vue组件中 有一行设置列宽度代码为：
`
let width = columnWidth (column.minWidth?column.minWidth:0);
`
2、这个行代码是说没有设置最小宽度或者设置最小宽度为 0 的时候，最小宽度在 table 宽度改变的时候 column 最小为 0 （没有设置任何宽度值的情况）

**Comment by weiyie** [comment]
![image](https://user-images.githubusercontent.com/19388725/45603858-2b8c2900-ba61-11e8-9bb3-4cf337c2ba97.png)

![image](https://user-images.githubusercontent.com/19388725/45603869-38a91800-ba61-11e8-9e30-6c6cd15ac736.png)



上面链接的demo宽度  设置了minwidth的列宽度= minwidth+平均值   是设计就这样吗

![image](https://user-images.githubusercontent.com/19388725/45603635-398d7a00-ba60-11e8-8a98-dd6082e96adc.png)

**Comment by pangxieju** [comment]
我不是官方人员，看到的源码和呈现的结果和你说的一样。

**Comment by weiyie** [comment]
@icarusion  大神看下问题。。
