### ISSUE TITLE
The [Feature Request]release version has 2 types folders.


### ISSUE THREAD

**Issue by AlexStacker** [iview/iview#4555]
### What problem does this feature solve?
之前在这个 https://github.com/iview/iview/pull/4438 PR里回复过， 提议说将webpack里的copy操作给去掉，但是官方似乎并没有采纳，而是将package.json里的type指向指到dist/type下面。
我觉得这个做法很非主流，一个是一般情况下大家都是放到包根目录下的，第二个是发布包时npm会将types目录放到包的根目录下，不需要再用webpack copy操作。
而且我在这个PR https://github.com/iview/iview/pull/4447 下有提过，但是现在看不到了，可能是删掉了吧，这样的做法是不是不妥。
现在安装后的npm包有2个types文件，要不要处理一下：
![image](https://user-images.githubusercontent.com/7822744/45734705-0db4f480-bc18-11e8-9037-7939ae0bdc9f.png)

### What does the proposed API look like?
还是建议删除webpack里的copy操作，用包根目录下的types文件

**Comment by icarusion** [comment]
@yangdan8 有时间的话，看一下这个问题吧

**Comment by yangdan8** [comment]
@icarusion 可以这么处理,我稍后修改代码提交,改为主流方式,dist目录下将不再包含types

**Comment by yangdan8** [comment]
见 #4930

**Comment by yangdan8** [comment]
合并pr后可关闭 @icarusion
