### ISSUE TITLE
Invalid attribute settings for [Bug Report]DatePicker editable


### ISSUE THREAD

**Issue by xuzhixiong886** [iview/iview#4559]
### Environment
win7，谷69.0.3497

### Reproduction link
[https://run.iviewui.com/1Q6VK4aG](https://run.iviewui.com/1Q6VK4aG)

### Steps to reproduce
如重现链接所示 设置editable="false"不起作用

### What is expected?
DatePicker组件只能选择 不能输入文本

### What is actually happening?
DatePicker组件输入可以输入

---
DatePicker组件只能选择使用

**Comment by icarusion** [comment]
`:editable="false"`

**Comment by xuzhixiong886** [comment]
Thank you
