### ISSUE TITLE
Date-picker组件多项参数失效

### ISSUE THREAD

**Issue by luckyyyyy** [iview/iview#456]
比如 :editable="false":clearable="false"

### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
 macOS/Chrome 58

### Vue 版本号
2.2.4

### 能够复现问题的在线示例（重要）
https://jsfiddle.net/maea4ksz/1/

**Comment by icarusion** [comment]
你的示例有问题。功能都是正常的。
