### ISSUE TITLE
[Feature Request] [Table component] suggests adding a set icon on the right to integrate the dynamic operation column function.


### ISSUE THREAD

**Issue by NoobJohn** [iview/iview#4568]
### What problem does this feature solve?
当table的列很多时   左右移动可能体验并不直接，也不方便，  如果可以集成自定义显示table列的功能 ，再结合现有的fix 就完美了

### What does the proposed API look like?
传入一个参数  开启此功能   右侧多出一个图标 默认显示当前所有列 (checkbox不显示)     再来个change变动事件 获取当前操作的列

**Comment by icarusion** [comment]
No such plan.
