### ISSUE TITLE
iView UI dropdown item click doesn't work

### ISSUE THREAD

**Issue by hkmsadek** [iview/iview#4572]
I am trying to apply a click event in iView ui. Here is what I am trying

```<DropdownMenu slot="list">
     <DropdownItem @on-click="markAsRead">Mark as read</DropdownItem>
</DropdownMenu>```
The method `markAsRead` doesn't run. how can I make it run? Thank you.

**Comment by EricLi0702** [comment]
Hello
I have one question.
How can I get Dropdown name value in iviewui?
Here is my code.
<Dropdown style="margin-left: 20px" placement="bottom-end"  trigger="click" @on-click="visible()">
                    <a href="javascript:void(0)">
                         {{parent}}
                        <Icon type="ios-arrow-forward" />
                    </a>
                    <DropdownMenu slot="list">
                        <DropdownItem name="爸爸">爸爸</DropdownItem>
                        <DropdownItem name="妈妈">妈妈</DropdownItem>
                        <DropdownItem name="爷爷">爷爷</DropdownItem>
                        <DropdownItem name="奶奶">奶奶</DropdownItem>
                        <DropdownItem name="姥爷">姥爷</DropdownItem>
                        <DropdownItem name="姥姥">姥姥</DropdownItem>
                        <DropdownItem name="家长">家长</DropdownItem>
                    </DropdownMenu>
                </Dropdown>
