### ISSUE TITLE
[Bug Report]iviiew table columns bug

### ISSUE THREAD

**Issue by djkloop** [iview/iview#4576]
### Environment
chrome

### Reproduction link
[https://run.iviewui.com/5YvyVWXT](https://run.iviewui.com/5YvyVWXT)

### Steps to reproduce
Dynamic Complex table header causes the page to die

### What is expected?
Normal operation

### What is actually happening?
Page Stuck dead

---
无

**Comment by icarusion** [comment]
same issue exist
