### ISSUE TITLE
iView 2.0 中文文档已发布

### ISSUE THREAD

**Issue by icarusion** [iview/iview#458]
### 2.0 文档地址：
https://www.iviewui.com/

### 1.0 文档地址：
http://v1.iviewui.com/

如遇问题，欢迎及时反馈！

**Comment by benaheng** [comment]
沙发

**Comment by william807803** [comment]
非常感谢！！！

**Comment by leubao** [comment]
哇，太好了...脚手架什么时候更新啊




原始邮件
发件人:william807803notifications@github.com
收件人:iview/iviewiview@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年3月22日(周三) 14:50
主题:Re: [iview/iview] iView 2.0 中文文档已发布 (#458)


非常感谢！！！
