### ISSUE TITLE
[Bug Report]3.12 version, custom theme "variable coverage" mode (official website method), edit error report


### ISSUE THREAD

**Issue by nickrogit** [iview/iview#4581]
### Environment
win7 64,"vue": "^2.5.9",

### Reproduction link
[https://run.iviewui.com/](https://run.iviewui.com/)

### Steps to reproduce
3.12版本，定制主题时‘变量覆盖’方式（官网方法），编辑报错

### What is expected?
兼容，不报错

### What is actually happening?
asset optimization ERROR  Failed to compile with 1 errors15:07:20

 error  in ./theme/index.less

Module build failed: 

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in E:\WENTI\Web\GIT\b-train\node_modules\iview\src\styles\color\bezierEasing.less (line 110, column 0)

 @ ./theme/index.less 4:14-189 13:3-17:5 14:22-197
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8095 webpack/hot/dev-server ./src/main.js

**Comment by fifteenzhang** [comment]
#4156
