### ISSUE TITLE
[Bug Report]Tag's prop 'checked' does'nt work after initialization

### ISSUE THREAD

**Issue by ljy19891118** [iview/iview#4587]
### Environment
iview 3.0.0

### Reproduction link
[https://run.iviewui.com/E0gN45Jy](https://run.iviewui.com/E0gN45Jy)

### Steps to reproduce
Pls click the button 'Toggle' in page which I provide, the Tag doesn't change at all.

That means, Tag doesn't watch prop 'checked', so that the data named 'ischecked' can't been change outside.

### What is expected?
Tag's prop 'checked' should affect alway the time.

### What is actually happening?
It does'nt work after initialization

---
This problem may cause a annoying result. 
I use v-for to iterative an array to generate some Tags, user could choose some of them, and I use 'checked' to represent the state.
But when I changed anthor array, the Tags with same index will not change the 'checked' state.

**Comment by LingWuYa** [comment]
I have the same question. But I find it runs well sometimes in my program, sometimes it is not work~

**Comment by zenvertao** [comment]
same problem,  i found a pull request commits can fix this bug ... -> https://github.com/iview/iview/pull/2437/commits/f9899b9e0949c0898334eb7b295788f678237cb8

but i don't know why the code lost in the latest branch ?
