### ISSUE TITLE
[Feature Request] recommends setting up loading status for Button in Input formation.


### ISSUE THREAD

**Issue by xiaoch05** [iview/iview#4588]
### What problem does this feature solve?
在Input的带有按钮的组合框中，能够显示按钮loading状态

### What does the proposed API look like?
<Input search button-loading="true" enter-button="BTN"/>

**Comment by icarusion** [comment]
```
<Input v-model="value12">
      <Button slot="append" loading>submit</Button>
    </Input>
```
