### ISSUE TITLE
[Bug Report]Filterable select improper applies filter after reset of value and values params

### ISSUE THREAD

**Issue by pgetta** [iview/iview#4589]
### Environment
Mac os High Sierra, latest Safari, Chrome

### Reproduction link
[https://jsfiddle.net/0bLqo4pj/14/](https://jsfiddle.net/0bLqo4pj/14/)

![filterable_select](https://user-images.githubusercontent.com/8026806/46152257-efcb3d80-c270-11e8-94b3-c6eaaabe98d5.gif)

### Steps to reproduce
* create Filterable select with some values
* select one value from the list (value1)
* reset components v-model to empty string
* change :values array
* click on select component to see the list

### What is expected?
To see the full list from :values property

### What is actually happening?
Component is showing the list which is filtered by previous value (value1) of `value` property

**Comment by icarusion** [comment]
Try to update to the latest version, if also appear this problem, please reopen this issue.

**Comment by pgetta** [comment]
Here is the fiddle with latest version of iview - 3.1.2: https://jsfiddle.net/0bLqo4pj/15/
The issue still exists.

**Comment by pgetta** [comment]
@icarusion could you please reopen the issue? I don't have a rights to do so since you closed it.

**Comment by icarusion** [comment]
3.1.3 will release today, so you can try it later again.
