### ISSUE TITLE
[Bug Report]SELECT control can't set initial value on start, when settting remote mode

### ISSUE THREAD

**Issue by jeffery9876** [iview/iview#4590]
### Environment
vue 2.5 chrome

### Reproduction link
[https://run.iviewui.com/8NXQDaWS](https://run.iviewui.com/8NXQDaWS)

### Steps to reproduce
on open the above link, the select control should have initial value 4 at start. However, it's missing. 

### What is expected?
the select control should have initial value (4) at start

### What is actually happening?
However, it's missing.

---
I'm using the SELECT control as a filter to search table column data, and it is commonly needed to display initial value to end user when they jump to the page with query parameters.

**Comment by icarusion** [comment]
Try to set options when initialized

**Comment by TanyDevp** [comment]
My temporary solution:
https://run.iviewui.com/OUDFDsxh
