### ISSUE TITLE
[Bug Report]page component page number problem


### ISSUE THREAD

**Issue by yanying119** [iview/iview#4599]
### Environment
window10  /  所有浏览器   / vue版本 @2.5.2

### Reproduction link
[https://run.iviewui.com/r8T7ZGA7](https://run.iviewui.com/r8T7ZGA7)

### Steps to reproduce
1、点击第五页
2、点击改变总页数为40
3、点击查看页数

问题：改变了总页数为40，page组件页码变成了4 但是父组件的页码还是5  并没有同步；
原因：page组件里面 watch total的时候 把this.currentPage改变了 但是没有执行changePage方法。导致父级跟page组件的页码不同步的现象

### What is expected?
期望 当总页数改变了  父组件的页面同步发生改变

### What is actually happening?
page组件的页码和父组件页码不同步

---
当列表页有删除操作时，最后一页的数据删除掉了。再次更新数据时会发生 page组件的页码更新了 但是父组件的page没有更新。导致列表页为空

**Comment by stanNo1** [comment]
我也在这个问题的处理办法，但是文档中没找着啊，还是需要自己去处理这种异常？
