### ISSUE TITLE
select组件动态切换options的循环值，无法赋值

### ISSUE THREAD

**Issue by Pinary** [iview/iview#46]
我动态改变select组件的option v-for的数值时， 没有通知select组件更新内部的optionsInstance，
我暂时通过增加一个select属性list， 然后watch list的变化，发现变化则调用this.updateOptions(true) 来强制更新optionsInstance，    但是需要保持 select组件的属性list和option v-for绑定的数据一致来解决

**Comment by icarusion** [comment]
已知问题，有一些组件有同样问题。目前正在思考比价好的监听slot的方法。

**Comment by luckymore** [comment]
`this.updateOptions(true) ` 执行的多了，，浏览器会崩溃哎
