### ISSUE TITLE
[Bug Report]Two datepicker cause bug

### ISSUE THREAD

**Issue by Gyyi** [iview/iview#4619]
### Environment
window7,  Chrome 66, vue 2.0

### Reproduction link
[https://jsfiddle.net/gaoyi/mxjpbf7n/](https://jsfiddle.net/gaoyi/mxjpbf7n/)

### Steps to reproduce
当同时存在两个datePicker组件时， 需要点击两次才能选中时间。

### What is expected?
鼠标点击正常选中日期

### What is actually happening?
当同时存在两个datePicker组件时， 需要点击两次才能选中时间。

---
查看源码发现是v-click-outside-x指令调用了handleClose方法，handleClose内部判断当点击事件不在panel内部发生时，阻止了事件冒泡。
由于页面上存在两个时间组件，导致了此问题。
期待修复

**Comment by icarusion** [comment]
open 要和 confirm 一起使用

**Comment by Gyyi** [comment]
> open 要和 confirm 一起使用
当使用type=‘’datetime”时，confirm是无效的，一定会被重置为true
