### ISSUE TITLE
官方的example，TypeError: loading_bar is undefined，TypeError: notification is undefined

### ISSUE THREAD

**Issue by liuliuliu666** [iview/iview#462]
### iView 版本号
2.0.0-rc.6 

### Vue 版本号
2.2.1

### 复现步骤
运行官方的example，其他示例正常运行，但loading-bar、Message、Notice会报错
### 问题现象，以及你期望的结果是怎样的?
loading-bar异常：TypeError: loading_bar is undefined
Message、Notice异常：TypeError: notification is undefined
### 你估计可能的原因是什么（选填）？
会跟webpack的配置有关系吗

**Comment by icarusion** [comment]
目前这几个组件不支持 runtime，后续会支持。
