### ISSUE TITLE
[Bug Report] When using the custom mode of the DatePicker component, if you use your own clickoutside instructions to control the open state, you'll find that the first click on the outside can't trigger anyway, and the second click will do.


### ISSUE THREAD

**Issue by yokiyokiyoki** [iview/iview#4623]
### Environment
macOS 10.13.2/浏览器 69.0.3497.100（正式版本） （64 位）/vue2.5.17

### Reproduction link
[https://run.iviewui.com/mzVuY7rw](https://run.iviewui.com/mzVuY7rw)

### Steps to reproduce
1.点击DatePicker组件外面
2.第一次触发不了关闭事件

### What is expected?
希望第一次点击组件外部就能触发事件

### What is actually happening?
第一次点击组件外部不能触发事件，第二次才可以

**Comment by FuJingFJ** [comment]
I met a situation like this. If the property OPEN is set, the first cilck of the document except for the DatePicker is miss. I tried both button and input.Set open property, click input, can`t get focus and click button, can`t catch click event. Ihave to click twice to catch the event.
在DatePicker组件设置open属性的时候，点击组件之外的地方，首次点击都被捕获无法触发。比如点击同页面的input或者Button, 第一次点击都无效。第二次点击才可以触发input聚焦或者Button触发事件。

**Comment by ruihua-code** [comment]
遇到了同样的问题，这个组件挺奇怪的
