### ISSUE TITLE
iview2.0.0-rc.6发现Tabs标签页关闭之后下面的pane不会消失的bug

### ISSUE THREAD

**Issue by find-life** [iview/iview#463]
### iView 版本号
2.0.0-rc.6 

### 操作系统/浏览器 版本号
Windows/Chrome 56

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例（重要）
https://www.iviewui.com/components/tabs

### 复现步骤
1.创建一个可以关闭的Tabs
2.点击关闭，如果点击的不是最后一个tab，那么下面的pane不会消失，如果是点击最后一个tab，下面的pane会消失

**Comment by icarusion** [comment]
Vue2 的 `$destroy()` 不会将 DOM 移除。
需手动控制 slot，示例如下，文档稍后更新：
```html
<template>
    <Tabs type="card" closable @on-tab-remove="handleTagRemove">
        <Tab-pane label="标签一" v-if="tab0">标签一的内容</Tab-pane>
        <Tab-pane label="标签二" v-if="tab1">标签二的内容</Tab-pane>
        <Tab-pane label="标签三" v-if="tab2">标签三的内容</Tab-pane>
    </Tabs>
</template>
<script>
    export default {
        data () {
            return {
                tab0: true,
                tab1: true,
                tab2: true
            }
        },
        methods: {
            handleTagRemove (name) {
                this['tab' + name] = false;
            }
        }
    }
</script>
```

**Comment by Hedgehogking** [comment]
手动控制slot的话，如果我不是隐藏，而是把solt的数组删除对应的元素，则会引发另一个问题，就是会删掉两个。https://jsfiddle.net/ve0nLtzd/ 怎么让slot的TabPane跟我的数组同步呢？

> 
    <div id="app">
        <tabs type="card" closable @on-tab-remove="handleTabRemove">
            <tab-pane :label="`标签${n}`" v-for="n in arr">标签{{n}}的内容</tab-pane>
        </tabs>
    </div>
    var Main = {
        data () {
            return {
                tab0: true,
                tab1: true,
                tab2: true,
                arr: [0, 1, 2, 3, 4, 5, 6],
            }
        },
        methods: {
            handleTabRemove (name) {
                this.arr.splice(name, 1);
            	console.log(name, this.arr.length);
                /* this['tab' + name] = false */;
            }
        }
    }
    var Component = Vue.extend(Main)
    new Component().$mount('#app')
