### ISSUE TITLE
[Bug Report] rendering is not normal under non template i-input.


### ISSUE THREAD

**Issue by crazyhl** [iview/iview#4631]
### Environment
mac chrome vue最新版

### Reproduction link
[https://jsfiddle.net/yyrzhm46/2145/](https://jsfiddle.net/yyrzhm46/2145/)

### Steps to reproduce
我在没有使用 template 下写了多个 i-input 最终只能渲染一个 [https://run.iviewui.com/PfyX7cPe](https://run.iviewui.com/PfyX7cPe) 这个网址是 iview run 下的，则渲染正常

### What is expected?
在不使用 template 的情况下 渲染多个 i-input 正常

### What is actually happening?
在非 template 下 i-input 多个只能渲染一个

**Comment by icarusion** [comment]
CDN 用 `</i-input>`

**Comment by crazyhl** [comment]
> CDN 用 `</i-input>`

感谢，可以了
