### ISSUE TITLE
Modal中嵌入Table组件，table无法充满Modal框没有宽度，窗口动一下恢复正常

### ISSUE THREAD

**Issue by MuKamui** [iview/iview#464]
### iView 版本号
 1.0.1

### 操作系统/浏览器 版本号
win10/Chrome 56 
### Vue 版本号
1.0.28

### 问题现象，以及你期望的结果是怎样的?
Modal中嵌入Table组件，table无法充满Modal框没有宽度，窗口动一下恢复正常,在table的render函数里面嵌入Modal然后在Modal里面放入table也是一样，会报错width未定义

### 你估计可能的原因是什么（选填）？
table的宽度计算是放在HandleResize方法的两个nextTick之后去计算，modal打开的时候可能并没有找到table存在DOM里，导致列找不到，看了下报错位置可能是这里的原因，然后当HandleResize调用了后就执行了table的相关操作吧。不知道是不是这个原因

**Comment by icarusion** [comment]
使用 v-if
