### ISSUE TITLE
The [Bug Report]Time component calculates the error I when the interval is more than 30 days.


### ISSUE THREAD

**Issue by zgang** [iview/iview#4651]
### Environment
vue2.0

### Reproduction link
[https://github.com/iview/iview/blob/2.0/src/components/time/time.js](https://github.com/iview/iview/blob/2.0/src/components/time/time.js)

### Steps to reproduce
https://github.com/iview/iview/blob/2.0/src/components/time/time.js
代码第33行

### What is expected?
时间计算正确

### What is actually happening?
时间间隔超过30天时，被放大了1000倍

**Comment by jimmyhsiun** [comment]
我在使用i-time这个控件的时候也遇到了这个问题，大于30天后时间就飞了。

**Comment by Jabbar2010** [comment]
const getDate = (timeStamp, startType) => {
    const d = new Date(timeStamp * 1000); ### //这里多乘了1000
    const year = d.getFullYear();
    const month = getHandledValue(d.getMonth() + 1);
    const date = getHandledValue(d.getDate());
    const hours = getHandledValue(d.getHours());
    const minutes = getHandledValue(d.getMinutes());
    const second = getHandledValue(d.getSeconds());
    let resStr = '';
    if (startType === 'year') resStr = year + '-' + month + '-' + date + ' ' + hours + ':' + minutes + ':' + second;
    else resStr = month + '-' + date + ' ' + hours + ':' + minutes;
    return resStr;
};

**Comment by Jabbar2010** [comment]
什么时候能够修复并发布？
