### ISSUE TITLE
[Bug Report]Select shows placeholder if Option only with value (without slot or label) in iview 3.1.3

### ISSUE THREAD

**Issue by hellomrbigshot** [iview/iview#4662]
### Environment
windows 10/ chrome 69/ iview 3.1.3

### Reproduction link
[https://jsfiddle.net/Yeachan/rtjgv2hz/1/](https://jsfiddle.net/Yeachan/rtjgv2hz/1/)

### Steps to reproduce
choose an option, select only shows placeholder. then choose the same option again, it works.

### What is expected?
it shows the value i choose correctly

### What is actually happening?
it shows placeholder

**Comment by icarusion** [comment]
set slot to Option
