### ISSUE TITLE
[Bug Report]iview table render中，如果配置了 fixed right，那么渲染2次数据

### ISSUE THREAD

**Issue by zyf540860996** [iview/iview#4668]
### Environment
macos 10.13.6 / Google Chrome 版本 69.0.3497.100 / vue版本 2.5.2 / iview版本 3.1.2

### Reproduction link
[http://meiyou.meiyou](http://meiyou.meiyou)

### Steps to reproduce
        {
          title: '操作',
          key: 'action',
          width: 90,
          fixed: 'right',
          render: (h, params) => {
            console.log('----')
            return h('div', '编辑')
          }
        }

fixed: 'right' 设置后， 控制台打印2轮 ----

### What is expected?
只渲染一次

### What is actually happening?
只渲染两次

**Comment by xdmushui** [comment]
这个问题关闭了，是修复了吗？

**Comment by QQOQ** [comment]
我在3.4.2版本也发现这个问题，不知道怎么解决

**Comment by yhhkit80** [comment]
我也发现了这个问题，3.4.2版本。有几个fixed列，就会多渲染几次。为什么问题关闭了啊？

**Comment by QQOQ** [comment]
> 我也发现了这个问题，3.4.2版本。有几个fixed列，就会多渲染几次。为什么问题关闭了啊？

我知道了，这不是bug，是html结构问题

**Comment by fekata** [comment]
也有同样的问题，不知道怎么解决
