### ISSUE TITLE
table无法render问题，报vue.compile is not defined

### ISSUE THREAD

**Issue by Pipikachu** [iview/iview#467]
### iView 版本号

2.0.0-rc.6
### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.1.10 

### 复现步骤

参照官网的实例，在table中加入自定义组件，出错

### 问题现象，以及你期望的结果是怎样的?

命令行爆出 * vue.compile is not defined * 错误，页面无法渲染 

### 你估计可能的原因是什么（选填）？

*table-cell* 组件中使用了 *vue.compile* 但是 *vue* 的默认导出是*dist/vue.runtime.common.js * 里面没有 *compile* 这个全局api, 修改为 *dist/vue.min.js* 即可解决

**Comment by jokerapi** [comment]
修改为 dist/vue.min.js 后页面直接整体报错。

**Comment by icarusion** [comment]
部分组件暂不支持 runtime，后面会更新
