### ISSUE TITLE
[Bug Report]table takes up too much memory or has memory leaks?


### ISSUE THREAD

**Issue by iijx** [iview/iview#4676]
### Environment
mac/chrome 69.0.3497.100/ vue 2.8

### Reproduction link
[https://run.iviewui.com/preview/RveUoCNe](https://run.iviewui.com/preview/RveUoCNe)

### Steps to reproduce
打开重现链接，不需要步骤，直接观察devtools里的内存

### What is expected?
重现链接里table只放了几条数据，运行一段时间后，内存高达2百多兆，目前我们的实际项目table换页，运营人员操作一段时间后经常卡死，table真的存在内存泄漏或者占是内存过大。后来不得不单独把table组件换成了 element里的，方才解决。

### What is actually happening?
不应该有那么大的内存占用

**Comment by chouxiangxiang** [comment]
我也有这个问题

**Comment by qinpeip** [comment]
me too

**Comment by deot** [comment]
@iview-bot You need to incorporate the actual scenario, For example, if you switch table on iview's official website, you will find that the memory is out of control.


Google Chrome | 74.0.3717.0 (正式版本) dev （64 位）
JavaScript | V8 7.4.207

![2019-03-01 19 40 22](https://user-images.githubusercontent.com/18424466/53636782-4b548980-3c5c-11e9-9249-2d5afe32f937.gif)

**Comment by JDEast1029** [comment]
> @iview-bot You need to incorporate the actual scenario, For example, if you switch table on iview's official website, you will find that the memory is out of control.
> 
> Google Chrome | 74.0.3717.0 (正式版本) dev （64 位）
> JavaScript | V8 7.4.207
> 
> ![2019-03-01 19 40 22](https://user-images.githubusercontent.com/18424466/53636782-4b548980-3c5c-11e9-9249-2d5afe32f937.gif)
