### ISSUE TITLE
Tree组件on-select-change事件失效

### ISSUE THREAD

**Issue by javaxiu** [iview/iview#468]
按照文档的配置，增加了一个on-select-change事件
```
<template>
    <Tree :data="baseData" @on-select-change='open'></Tree>
</template>
<script>
    export default {
       methods:{
            open: function(){
                console.log(arguments) 
            }
       },
        data () {
            return {
                baseData: [{
                    expand: true,
                    title: 'parent 1',
                    children: [{
                        title: 'parent 1-0',
                        expand: true,
                        disabled: true,
                        children: [{
                            title: 'leaf',
                            disableCheckbox: true
                        }, {
                            title: 'leaf',
                        }]
                    }, {
                        title: 'parent 1-1',
                        expand: true,
                        checked: true,
                        children: [{
                            title: '<span style="color: red">leaf</span>',
                        }]
                    }]
                }]
            }
        }
    }
</script>
```

出现的问题是，只有点击parent1-1有调用，如果去掉parent1-1，就变成只有parent1-0有调用，看情况应该是需要增加key/name/id之类的来区分。但是文档上没找到，我尝试加了也不行，不知道我是哪里弄错了呢

另外想问一下childern里是否可以增加`<router-link>`，如何用？

**Comment by javaxiu** [comment]
另外，show-checkbox的配置里，:multiple='false' 也是无效的，不管我配置的是true还是false,都不能单选，都是多选的

**Comment by icarusion** [comment]
`multiple ` 跟 checkbox 没关系。
multiple 默认就是 false，开启后，可以点击名称选中，与 checkbox 是两个概念

**Comment by Tankerx** [comment]
我也遇到这个问题了。但是设置multiple之后，他的单选范围只在同一级的节点里面，可以父节点和子节点一起选择，并且用getSelectedNodes获取选中节点的时候，是父节点和子节点一起返回的，这样是否是正确的。因为只想选择一个节点就可以了。on-select-change事件的响应也有问题.

**Comment by icarusion** [comment]
这个是有问题，Tree 组件已经在重构了

**Comment by Tankerx** [comment]
恩恩，知道了，谢谢

**Comment by eeve** [comment]
父节点在半选状态的时候，在某些场景下也算选中的吧？目前在@on-check-change没有半选状态的父节点，可否加一个开关参数来设置此？

**Comment by wyn5111** [comment]
> 按照文档的配置，增加了一个on-select-change事件
> 
> ```
> <template>
>     <Tree :data="baseData" @on-select-change='open'></Tree>
> </template>
> <script>
>     export default {
>        methods:{
>             open: function(){
>                 console.log(arguments) 
>             }
>        },
>         data () {
>             return {
>                 baseData: [{
>                     expand: true,
>                     title: 'parent 1',
>                     children: [{
>                         title: 'parent 1-0',
>                         expand: true,
>                         disabled: true,
>                         children: [{
>                             title: 'leaf',
>                             disableCheckbox: true
>                         }, {
>                             title: 'leaf',
>                         }]
>                     }, {
>                         title: 'parent 1-1',
>                         expand: true,
>                         checked: true,
>                         children: [{
>                             title: '<span style="color: red">leaf</span>',
>                         }]
>                     }]
>                 }]
>             }
>         }
>     }
> </script>
> ```
> 出现的问题是，只有点击parent1-1有调用，如果去掉parent1-1，就变成只有parent1-0有调用，看情况应该是需要增加key/name/id之类的来区分。但是文档上没找到，我尝试加了也不行，不知道我是哪里弄错了呢
> 
> 另外想问一下childern里是否可以增加`<router-link>`，如何用？

>你的问题解决了吗？
>我在tree上加的on-select-change事件失效

**Comment by onlyone1221** [comment]
on-select-change  请问tree中这个方法不执行，，不设置multiple还是多选？？这个是否是bug，修复没有

**Comment by onlyone1221** [comment]
我的是自定义的
