### ISSUE TITLE
[Feature Request]i-checkbox increases the attribute control needs border-bottom


### ISSUE THREAD

**Issue by navykoo** [iview/iview#4680]
### What problem does this feature solve?
当前i-checkbox是封装在i-cell中的，i-cell的css中强制添加了border-bottom. 在非form页面或者单独行需要使用复选框时，这个style不能消除，导致页面风格奇异。

### What does the proposed API look like?
增加一个属性可以控制i-cell风格或者去除i-cell包裹，让用户选择是否包裹

**Comment by icarusion** [comment]
No such plan now.
