### ISSUE TITLE
[Bug Report] can not slide on option finger of mobile terminal select.


### ISSUE THREAD

**Issue by cryingbat** [iview/iview#4684]
### Environment
华为自带浏览器

### Reproduction link
[https://codepen.io/cryingbat/pen/oMdXqo](https://codepen.io/cryingbat/pen/oMdXqo)

### Steps to reproduce
链接有。在移动端打开select选项过多。手指不能滑动，导致下面的选项选择不了

### What is expected?
手指可以滑动

### What is actually happening?
不能滑动

**Comment by maggie-chen** [comment]
我也碰到了这个bug，求官方解决

**Comment by icarusion** [comment]
same issue exist
