### ISSUE TITLE
自定义主题报错

### ISSUE THREAD

**Issue by ckryo** [iview/iview#469]
theme.less
![image](https://cloud.githubusercontent.com/assets/10364500/24236587/7479060e-0fdd-11e7-9434-86c609260309.png)
main.js
![image](https://cloud.githubusercontent.com/assets/10364500/24236527/0aa6c9b4-0fdd-11e7-8ae5-f7157954806b.png)
报错信息
![image](https://cloud.githubusercontent.com/assets/10364500/24236530/14c825a0-0fdd-11e7-8e56-e37565f1b897.png)
配置信息
![image](https://cloud.githubusercontent.com/assets/10364500/24236534/1d983bc0-0fdd-11e7-8760-813d2cd5983e.png)
这个请问怎么解决？ 是webpack配置问题？还是less 使用问题？

**Comment by agangdundan** [comment]
我也碰到了同样的问题，不知道应该如何解决？

**Comment by wintergithub** [comment]
同问，如何处理？

**Comment by ilvsx** [comment]
less-loader 依赖 less ，所以：
`npm install less --save-dev`

**Comment by ilvsx** [comment]
less-loader 依赖 less ，所以：
`npm install less --save-dev`

**Comment by WuPanFeng** [comment]
你这个问题咋解决的。我安装了less 还是不行。

**Comment by Baoyx007** [comment]
改成这样 @WuPanFeng 
```
{
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          use: ['css-loader', 'autoprefixer-loader', 'less-loader'],
          fallback: 'style-loader'
        })
      },
```

**Comment by WuPanFeng** [comment]
@Baoyx007 谢谢。搞定了！
