### ISSUE TITLE
Laravel + Vue + iView

### ISSUE THREAD

**Issue by qinglang1208** [iview/iview#471]
Laravel项目中采用http://laravelacademy.org/post/6791.html 页面的方式加载vue
出现Menu标签没有解析，其它标签正常
`<div class="layout"><menu mode="horizontal" theme="dark" active-name="1"><div class="layout-logo"></div> <div class="layout-nav"><li class="ivu-menu-item"><i class="ivu-icon ivu-icon-ios-navigate"></i>
                        导航一
                    </li> <li class="ivu-menu-item"><i class="ivu-icon ivu-icon-ios-keypad"></i>
                        导航二
                    </li> <li class="ivu-menu-item"><i class="ivu-icon ivu-icon-ios-analytics"></i>
                        导航三
                    </li> <li class="ivu-menu-item"><i class="ivu-icon ivu-icon-ios-paper"></i>
                        导航四
                    </li></div></menu> <menu mode="horizontal" active-name="1"><div class="layout-assistant"><li class="ivu-menu-item">二级导航</li> <li class="ivu-menu-item">二级导航</li> <li class="ivu-menu-item">二级导航</li></div></menu> <div class="layout-breadcrumb"><div class="ivu-breadcrumb"><span><a href="#" class="ivu-breadcrumb-item-link">首页</a> <span class="ivu-breadcrumb-item-separator">/</span></span> <span><a href="#" class="ivu-breadcrumb-item-link">应用中心</a> <span class="ivu-breadcrumb-item-separator">/</span></span> <span><span class="ivu-breadcrumb-item-link">某应用</span> <span class="ivu-breadcrumb-item-separator">/</span></span></div></div> <div class="layout-content">
                内容区域
            </div> <div class="layout-copy">
                2011-2016 © TalkingData
            </div></div>`

**Comment by icarusion** [comment]
![](https://ooo.0o0.ooo/2017/03/23/58d38c16f0c59.png)
