### ISSUE TITLE
[Bug Report]Can't focus input in the dropdown of ColorPicker

### ISSUE THREAD

**Issue by fantkolja** [iview/iview#4718]
### Environment
Chrome 69

### Reproduction link
[https://jsfiddle.net/u70xj9a3/4/](https://jsfiddle.net/u70xj9a3/4/)

### Steps to reproduce
Set :transfer="true" on the ColorPicker component.

### What is expected?
The user should be able to interact with input by manually setting color value.

### What is actually happening?
The user is not able to focus the input with mouse (only pressing TAB key).

**Comment by RookieZoe** [comment]
看了一下，可以确定是 v-click-outside-x 引起的

**Comment by RookieZoe** [comment]
resolved
