### ISSUE TITLE
Menu组件动态绑定mode，改变后报错

### ISSUE THREAD

**Issue by miomio-xiao** [iview/iview#472]
### iView 版本号
2.0.0-rc.6

### 操作系统/浏览器 版本号
windows/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
绑定mode后，手动改变mode的值后报错

[Vue warn]: Error in callback for watcher "mode": 
(found in <Submenu>)
TypeError: Cannot read property 'update' of undefined

**Comment by icarusion** [comment]
示例
