### ISSUE TITLE
[Feature Request] date control adds weekly selector, cycle range selector, month range selector.


### ISSUE THREAD

**Issue by leixu2txtek** [iview/iview#4720]
### What problem does this feature solve?
解决了用户选择 第12周 到第30周，第1月至第8月这种维度选择

目前 element-ui 已经有周选择器了

https://element.eleme.io/#/zh-CN/component/date-picker

![image](https://user-images.githubusercontent.com/5109966/47555098-8442c180-d93d-11e8-9582-8819b7efba5d.png)

### What does the proposed API look like?
```
<DatePicker type="week" placeholder="Select date" style="width: 200px"></DatePicker>
<DatePicker type="weekRange" placeholder="Select date" style="width: 200px"></DatePicker>
<DatePicker type="monthRange" placeholder="Select date" style="width: 200px"></DatePicker>
```

**Comment by icarusion** [comment]
No such plan now.
