### ISSUE TITLE
Modal onOk 可重复执行

### ISSUE THREAD

**Issue by gimjin** [iview/iview#4727]
一般Modal会在删除等严重后果时弹出询问操作者
1，Modal会有一个隐藏动画，此时迅速的按可以重复激活onOk事件，导致数组中的数据被删除多次，或者找不到对象。
2，按钮处于Loading状态下使用this.$Modal.remove()，也会在隐藏动画开始时确定按钮会被激活，可以按多次

**Comment by muzixiaojun** [comment]
我也有这个问题，想知道你有什么方法解决
