### ISSUE TITLE
[Bug Report]AutoComplete currentValue performs two times, second times Val is undefine.


### ISSUE THREAD

**Issue by L-Angel** [iview/iview#4731]
### Environment
Win10/Chrome69.0/3.1.3

### Reproduction link
[http://xxxxxx.com](http://xxxxxx.com)

### Steps to reproduce
选择值之后会触发两次事件

### What is expected?
value值为setOption的值

### What is actually happening?
undefine

![image](https://user-images.githubusercontent.com/8940416/47640020-9b7fea00-db9d-11e8-8c9b-ebfaa1be12ae.png)

**Comment by RookieZoe** [comment]
@L-Angel, checkout issue #4558 and pr #4750.
