### ISSUE TITLE
Table 组件render 的 i-input 输入不顺滑

### ISSUE THREAD

**Issue by seadog16** [iview/iview#474]
### iView 版本号
2.0.0-rc.6

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（重要）

https://codepen.io/anon/pen/RpJWWJ

### 复现步骤
点击输入框输入内容
### 问题现象，以及你期望的结果是怎样的?
每打个字就失焦，加了 lazy 都没用，用原生 input 加 lazy 修饰就没问题。
### 你估计可能的原因是什么（选填）？
i-input 组件 lazy 功能没加进去

**Comment by YikaJ** [comment]
双向绑定的数据改变导致 table 重新 render，所以会失焦。其实有很多解决方案的。

**Comment by yajore** [comment]
这个我在1.0的版本也碰到类似问题，可以参考当时的issue https://github.com/iview/iview/issues/165

**Comment by seadog16** [comment]
我也是用你的方法解决的，但其实希望i-input 能把 lazy 修饰加进去，另外还有 i-select 给 name 属性无效

**Comment by gangdiedao** [comment]
用这个 v-once 必杀技
https://cn.vuejs.org/v2/api/#v-once
