### ISSUE TITLE
[Feature Request] hopes that the table can support setting up a single line expansion, and the other expanded lines will be immediately retracted.


### ISSUE THREAD

**Issue by Akuns** [iview/iview#4741]
### What problem does this feature solve?
因为在一些需求特殊的情况下只需要展开一行就行了。点击当前行，其它已展开的行就自动收起。如果当前页条数很多，一个个展开之后，又得一个个的去点收起！

### What does the proposed API look like?

1. 表格展开里嵌套表格，当前行展开，其它已展开的行立即收起
2. 可以手动控制展开合并

**Comment by icarusion** [comment]
No such plan.
