### ISSUE TITLE
[Feature Request]Progress bar with animated stripes

### ISSUE THREAD

**Issue by volgariver6** [iview/iview#4749]
### What problem does this feature solve?
<Progress :percent="45" status="active" /> 组件看起来不明显，尤其当每隔几秒刷新一次页面时，active的进度条也会被刷新，最好能有个当刷新整个页面时，不会被看出来Progress 进度条也被刷新过，所以建议增加animated stripes
例如：
https://codepen.io/uimax/pen/KgdgGa

### What does the proposed API look like?
<Progress :percent="45" status="striped" />

**Comment by icarusion** [comment]
No such plan.
