### ISSUE TITLE
关于iview中各种事件的绑定，对iview文档的一个小建议

### ISSUE THREAD

**Issue by Peterlhx** [iview/iview#475]
### iView 版本号
2.0.0-rc.6

### 操作系统/浏览器 版本号
win 10/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
![image](https://cloud.githubusercontent.com/assets/11450619/24278416/a96a6e24-107e-11e7-8426-843abe891a00.png)
就新人而言（例如我），对于iview文档中的各种事件绑定一开始很疑惑，例如上图中的on-click事件，文档中没有详细的例子，那我一开始就以为直接用on-click就可以触发点击事件了，但其实是要使用vue中的事件绑定方法v-on或者@才可以。希望能够在文档中对事件绑定有更具体的例子。

**Comment by icarusion** [comment]
看 API 啊，都分3个部分：props、slot、events，events就是自定义事件

**Comment by Peterlhx** [comment]
vue中的api我看了，只是在使用iview中可能会以为on-click是iview自己实现的事件绑定，囧

**Comment by icarusion** [comment]
我是说 iView 文档底下的 API

**Comment by Peterlhx** [comment]
也看了呀，但是并没有个例子指明是具体用法，主要是on-前缀很容易让人以为就是绑定了事件，不需要这样写了：v-on:click或者@on-click。可以在文档中的demo稍微体现一下

**Comment by icarusion** [comment]
不是所有API都有示例的。。。自己写一写啊

**Comment by Peterlhx** [comment]
嗯，在button那个组件示例是有的，谢谢啦~

**Comment by 314432150** [comment]
+1，我也踩坑了……
