### ISSUE TITLE
[Bug Report]Poptip will disapper when you click on itself in IE<=10

### ISSUE THREAD

**Issue by movechip** [iview/iview#4761]
### Environment
Windows 10/IE10/Vue@2.5.17

### Reproduction link
[https://run.iviewui.com/Zxp331Vq](https://run.iviewui.com/Zxp331Vq)

### Steps to reproduce
`iView Run` and `JSFiddle` can't be opened on IE, so get the code of the reshow url to create a new html, then open it in IE10, Poptip will disapper when you click on itself.

### What is expected?
Poptip will not disapper when you click on itself in IE>=9

### What is actually happening?
Poptip will disapper when you click on itself in IE<=10

**Comment by icarusion** [comment]
some components and features do not support IE

**Comment by oldfu741** [comment]
forget IE
----- 原始邮件 -----
发件人：Aresn <notifications@github.com>
收件人：iview/iview <iview@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re: [iview/iview] [Bug Report]Poptip will disapper when you click on itself in IE<=10 (#4761)
日期：2018年11月02日 17点19分

some components and features do not support IE

&mdash;
