### ISSUE TITLE
table render 的按钮点击失效

### ISSUE THREAD

**Issue by malaimoo** [iview/iview#477]
### iView 版本号
2.0.0-rc.6 

### 操作系统/浏览器 版本号
macOS/Chrome 57

### Vue 版本号
 2.2.1

### 问题现象，以及你期望的结果是怎样的?

...
     {
            title: '操作',
            width: 130,
            key: 'deviceNum',
            render: function (row, column, index) {
              return `<i-button type="primary" size="small" @click.native="show(${index})">续期</i-button> <Button type="warning" size="small" @click="show(${index})">删除</Button>`;
            }
          }
...

点击按钮报错：
vue.common.js?e881:560 [Vue warn]: Property or method "show" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <Root>)

VM44472:2 Uncaught TypeError: show is not a function
    at click (eval at makeFunction (eval at <anonymous> (app.js:723)), <anonymous>:2:232)
    at HTMLButtonElement.invoker (eval at <anonymous> (app.js:723), <anonymous>:1660:18)

**Comment by icarusion** [comment]
写的不对，参照文档

**Comment by malaimoo** [comment]
修改成下面的，依然报错啊。。  {
            title: '操作',
            width: 130,
            key: 'deviceNum',
            render: function (row, column, index) {
//              return `<!--<i-button type="primary" size="small" @click="show('sd')">续期</i-button> <Button type="warning" size="small" @click="show(${index})">删除</Button>-->`;
              return `<i-button type="primary" size="small" @click="show(${index})">查看</i-button> <i-button type="error" size="small" @click="remove(${index})">删除</i-button>`;

            }
          }

**Comment by malaimoo** [comment]
要加上下文才可以 :context="self". Thanks！
```
  <Table :context="self" height="300" :columns="columns"
                 :data="devices"></Table>
```
