### ISSUE TITLE
[Bug Report]Select Option component bug


### ISSUE THREAD

**Issue by tanrich** [iview/iview#4771]
### Environment
chrome 69 macos vue2.5

### Reproduction link
[https://run.iviewui.com/fF876795](https://run.iviewui.com/fF876795)

### Steps to reproduce
select 组件选择值之后v-model 同步 getValue，模拟用户取消选择，更新getValue 后，显示效果正常，但 Option 依然处于选中状态。

### What is expected?
Select 选择正确的 selected Option

### What is actually happening?
Select 未选择正确的 selected Option，显示的正确的值

**Comment by icarusion** [comment]
最新的 3.1.5 版本应该是 OK 的
