### ISSUE TITLE
[Feature Request]Query text need be clear when Select component have non-default values

### ISSUE THREAD

**Issue by jimzhaoxiaojun** [iview/iview#4774]
### What problem does this feature solve?
Seclect value must be from options
有时select的值必须从选项中选择，但是选项很多，需要使用搜索进行快速匹配。
这种情况下，搜索文本如果匹配不到选项，那么失去焦点时，需要清空搜索文本。

### What does the proposed API look like?
add 'clear-query-text' in select props，default value 'false'

**Comment by icarusion** [comment]
No such plan.

**Comment by icarusion** [comment]
No such plan.
