### ISSUE TITLE
[Bug Report] used less3.x version in nuxt2.0 version.


### ISSUE THREAD

**Issue by CXX19901120** [iview/iview#4776]
### Environment
macos/chrome/nuxt2.0

### Reproduction link
[https://www.iviewui.com/new-issue](https://www.iviewui.com/new-issue)

### Steps to reproduce
在nuxt2.0版本中使用less3.x版本
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?

### What is expected?
正常使用

### What is actually happening?
在nuxt2.0版本中使用less3.x版本
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?

**Comment by ewxm** [comment]
记录一下解决方案与思路

## :rotating_light: 错误

> 出现此问题的原因可能是在其他的脚手架中如`vue-cli3`引入了 `iview` 组件库后修改主题导致的，目前（2019-07）`iview` 的 `iview-admin` 使用的是 `^2.7.3`  的 `less` 版本，而 `vue-cli3` ...  已经升级至 `^3.9.0` 的版本，`^3.9.0` 的版本中一个配置项被废弃，导致了 `Inline JavaScript is not enabled`  :warning:。

```bash
error  in ./my-theme/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /Users/bingo/workspace/github/genmd/node_modules/iview/src/styles/color/bezierEasing.less (line 110, column 0)

 @ ./my-theme/index.less 4:14-216 14:3-18:5 15:22-224
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.43.202:9000/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
``` 
认真分析错误后我们可以得出一些结论，从字面意思大概可以理解为不支持 `Inline` Javasript，报错时命中 `./node_modules/less-loader/dist/cjs.js` ，很显然这是 `less-loader` 运行时的一个错误，可以尝试打开 [`lesscss`的官网](http://lesscss.org/usage/)搜索关键字 `Inline` ，搜索得到 `Enable Inline JavaScript (`**Deprecated**`)`，可见这个 `配置` 已经被废弃掉，官方的解决方案为: `Replaced with the @plugin option.`。

## :bulb: 方案

此处提供三种解决方案（希望能帮助大家）:

1. 降低 `less` 和 `less-loader`  的版本，可以参考 `https://github.com/iview/iview-admin/blob/master/package.json`中的版本号码，重新安装依赖。

2. 由于 `Vue CLI` 天生支持 `less` ，可修改它的预处理器的 `less-loader` 的配置，让其支持 `Inline JavaScript`（在我看来不管是出于何种目的，过于依赖”兼容性代码“与废弃的`API`总不太妥，请看第`3`吧）。

vue.config.js

```javascript
const path = require('path')
module.exports = {
    lintOnSave: true,
    css: {
        loaderOptions: {
            less: {
                sourceMap: true,
                javascriptEnabled: true
            }
        }
    }
}
```

3. `Replaced with the @plugin option.` ... 有兴趣和精力的朋友可以尝试一下。

## :books: 参考资料

### Less
> False by default starting in v3.0.0. Enables evaluation of JavaScript inline in .less files. This created a security problem for some developers who didn't expect user input for style sheets to have executable code.
http://lesscss.org/usage/

### Vue CLI3
> 有的时候你想要向 webpack 的预处理器 loader 传递选项。你可以使用 vue.config.js 中的 css.loaderOptions 选项。比如你可以这样向所有 Sass 样式传入共享的全局变量：
https://cli.vuejs.org/zh/guide/css.html#%E5%90%91%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8-loader-%E4%BC%A0%E9%80%92%E9%80%89%E9%A1%B9

### iview 与 iview-admin

https://www.iviewui.com/docs/guide/install

https://github.com/iview/iview-admin/blob/master/package.json
