### ISSUE TITLE
能不能统一自定义标签啊.有些不能写i-前缀开头

### ISSUE THREAD

**Issue by xyyiii** [iview/iview#478]
### Vue 版本号

能不能统一自定义标签啊.有些不能写i-前缀开头...
非 template/render 模式下,有些必须用i-前缀.而有些没有
来回切换写,我好蛋疼

**Comment by dzgrief** [comment]
我也希望能统一一下标签命名，所有标签都可以使用 i- 前缀开头，原来大写开头的命名也保留，不然强迫症受不了。。

**Comment by terranc** [comment]
我也是因为大写导致不太想用 iview，因为记忆成本大，而且容易和其他库的标签冲突
