### ISSUE TITLE
The project created by [Bug Report] vue-cli3 globally introduces iView error Uncaught Reference Error: iView is not defined


### ISSUE THREAD

**Issue by asasugar** [iview/iview#4780]
### Environment
window/chrome/vue 2.5.17

### Reproduction link
[http://123.com（假链接）](http://123.com（假链接）)

### Steps to reproduce
```js
import iView from "iview";
Vue.use(iView);
```

### What is expected?
支持全局引入

### What is actually happening?
按需引入可以，全局引入报错

**Comment by asasugar** [comment]
How to deal with it? @iview-bot

**Comment by Dante-dan** [comment]
给一个详细的吧，报错发一下，你具体咋写的。什么地方报错，你引入依赖了嘛

**Comment by asasugar** [comment]
> 给一个详细的吧，报错发一下，你具体咋写的。什么地方报错，你引入依赖了嘛

![65dc0db0-c778-407b-b431-dcbd8d2f47e2](https://user-images.githubusercontent.com/27256120/47992390-bd421980-e127-11e8-907f-849f7e528792.png)

依赖肯定是引入了，按需都可以，

![5a298bb1-010b-4fb6-b737-5d8e7d8a71b2](https://user-images.githubusercontent.com/27256120/47992326-91bf2f00-e127-11e8-80d6-309d291ca94a.png)

**Comment by Dante-dan** [comment]
在`main.js`添加
```javascript
Vue.prototype.$IVIEW = {}
```

**Comment by asasugar** [comment]
> 在`main.js`添加
> 
> ```js
> Vue.prototype.$IVIEW = {}
> ```

不行啊   你可以用vue-cli3创建一下新的项目 全局引入试试

**Comment by asasugar** [comment]
确认了一下，原因是按需引入的插件配置未注释

**Comment by fukai007** [comment]
@xxj95719  & @iview-bot  那 按需加载怎么办, 3.0 会自动处理吗？

**Comment by liubailing** [comment]
import iView from '**iview/dist/iview**';   即可解决

**Comment by cduyzh** [comment]
补充一下，问题应该是楼主用了按需加载，写了一个.babelelrc文件,解决方法就是不用按需加载，如果非要用问题描述采用的写法的话，就把import iView from "iview";改为import iView from 'iview/dist/iview';但是这个跟按需加载理念相违背。
