### ISSUE TITLE
[Feature Request]Why does the "Input" component type attribute do not support the native "number" type?

### ISSUE THREAD

**Issue by ipquit** [iview/iview#4781]
### What problem does this feature solve?
Why does the "Input" component type attribute do not support the native "number" type?

In fact, forcing "type ='number'" also works. The input box can only enter numbers, but it conflicts with other attributes, such as ": MaxLength = 11" and no longer works.

This is especially easy to use when entering a cell phone number or amount, because the information must only be a number, so we don't need to write additional input rules.

I hope to support type='number'in the later version update.

### What does the proposed API look like?
Support ' type="number" ' and no longer conflicts with other attributes.

**Comment by icarusion** [comment]
No such plan.
