### ISSUE TITLE
The type of value in [Feature Request]select component supports object


### ISSUE THREAD

**Issue by LelouchJoshua** [iview/iview#4783]
### What problem does this feature solve?
在一个内容map出来的表单中 需要select返回object类型的数据 发现不支持 想通过使用on-change事件直接将选择的数据更新到data 发现无法传递当前组件的index 所以没法直接赋值

### What does the proposed API look like?
select 支持 object 类型 
on-change 支持 传递参数

**Comment by icarusion** [comment]
No such plan.

**Comment by ruslankonev** [comment]
We need support Object type in select

**Comment by assmdx** [comment]
We need support Object type in select.

**Comment by azhengyongqin** [comment]
We need support Object type in select.
