### ISSUE TITLE
[Bug Report] cascader component, when the input value is searched, the row is selected, and the on-change event does not return selectedData


### ISSUE THREAD

**Issue by duanxuhua** [iview/iview#4786]
### Environment
window/chrome/iview最新

### Reproduction link
[https://run.iviewui.com/yGZCruDd](https://run.iviewui.com/yGZCruDd)

### Steps to reproduce
1。输入111
2。选中选项
3。提示  请选择  表示on-change的selectedData为[],

### What is expected?
返回选中项目数据

### What is actually happening?
返回[]数据

**Comment by guoshuai93** [comment]
v 2.13.1 也有这个问题，尝试本地修复并编译后不成功，最后拿获取到的叶子节点去遍历list，拿到叶子节点的内容。
