### ISSUE TITLE
[Bug Report]  Using the split panel three level nested, middle drag strips style error

### ISSUE THREAD

**Issue by leaper1** [iview/iview#4793]
### Environment
iview 3.14版本

### Reproduction link
[https://run.iviewui.com/1xD95lHH](https://run.iviewui.com/1xD95lHH)

### Steps to reproduce
嵌套使用，比如三级嵌套的mode值依次为： horizontal -> vertical -> horizontal 

### What is expected?
像树形标签一样，可以递归自身，实现多级嵌套。

### What is actually happening?
样式出错

**Comment by icarusion** [comment]
不支持3级
