### ISSUE TITLE
[Bug Report] drop-down component bug


### ISSUE THREAD

**Issue by lifeLikeACode** [iview/iview#4795]
### Environment
window/chrome/vue2.5

### Reproduction link
[https://run.iviewui.com/icBaNtzZ](https://run.iviewui.com/icBaNtzZ)

### Steps to reproduce
请看链接中有文字描述

### What is expected?
期望数据是完整的下拉数据

### What is actually happening?
实际结果是只有当前选中的这一条数据

**Comment by wsx90315** [comment]
可以试试用 on-query-change 
判断query如果為空
就把 v-model 的值清掉

**Comment by lifeLikeACode** [comment]
> 可以试试用 on-query-change
> 判断query如果為空
> 就把 v-model 的值清掉

如果用on-query-change的话 他只清除一半的时候点击其他空白区域也会出现这样的bug  所以不能再query 为空的是后去做判断

**Comment by wsx90315** [comment]
> 如果用on-query-change的話他只清除一半的時候點擊其他空白區域也會出現這樣的bug所以不能再查詢為空的是後去做判斷

嗯嗯 那就没办法用on-query-change了

**Comment by luo772435545** [comment]
遇过过很多次这个问题，在和Modal一起用的时候

**Comment by lifeLikeACode** [comment]
> 遇过过很多次这个问题，在和Modal一起用的时候

请问有好的解决办法吗

**Comment by luo772435545** [comment]
调用一下reset方法就好
