### ISSUE TITLE
When [Bug Report]select opens remote, label is set up, and the default value cannot be displayed.


### ISSUE THREAD

**Issue by cdz620** [iview/iview#4797]
### Environment
mac 10.13.6 / chrome Version 70.0.3538.77 (Official Build) (64-bit) / Vue 2.9.6

### Reproduction link
[https://jsfiddle.net/cdz620/5px4k1fq/](https://jsfiddle.net/cdz620/5px4k1fq/)

### Steps to reproduce
无步骤，初始化后不显示默认值

### What is expected?
显示Alabama

### What is actually happening?
无内容。

---
https://www.iviewui.com/components/select#API
文档中说初始化要始用label显示初始化的值用label。有可能是我用的方式不对，我已经尝试过各种方法，还是没成功显示初始化的值。希望官方补充一个demo。我看其他社区也有很多人问这个问题。

**Comment by songuu** [comment]
在你初始化的时间，可以直接给它赋值为Alabama就行了

**Comment by songuu** [comment]
在你初始化的时间，可以直接给model14赋值为Alabama就行了

**Comment by cdz620** [comment]
@songuu 加了也不行，你可以给个例子吗

**Comment by lingoh** [comment]
恩 是不行 bug ，multiple与 remote下 无法显示默认值

**Comment by allochi** [comment]
Actually, it used to be the case and it got broken long time ago and never fixed. I'm in the mess of it right now, check iView 2.13 which is the last time it used to work.

Not to undermine the good work the iView team are putting into the library, and I'm thankful for using iView for over a year now in my project, but I found myself forced to move away from it because of its unstable behaviour with every update.

**Comment by cdz620** [comment]
@allochi  the same to me.  so now,  which ui framework do you use?

**Comment by sinceow** [comment]
@lingoh 

```html
<Select :remote-method="tempRemoteMethod">
</Select
```

```js
data: {
    tempRemoteMethod: false
},
methods: {
    remoteMethod(){
     //.......
    }
}
```
先把 remote-method 赋为 false, 在设置好默认值后（此时可以正常显示），再 
```js
tempRemoteMethod = remoteMethod
```
重新变成可以远程搜索
会报一个Warning，因为 false 不是 remote-method 的参数类型，但勉强可以用 😭

**Comment by cdz620** [comment]
I have found another two ways to solve this problem:
1. use this component: https://github.com/shentao/vue-multiselect
2. use this component: http://element-cn.eleme.io/#/en-US/component/select

**Comment by webrtcn** [comment]
> @lingoh
> 
> ```
> <Select :remote-method="tempRemoteMethod">
> </Select
> ```
> 
> ```js
> data: {
>     tempRemoteMethod: false
> },
> methods: {
>     remoteMethod(){
>      //.......
>     }
> }
> ```
> 
> 先把 remote-method 赋为 false, 在设置好默认值后（此时可以正常显示），再
> 
> ```js
> tempRemoteMethod = remoteMethod
> ```
> 
> 重新变成可以远程搜索
> 会报一个Warning，因为 false 不是 remote-method 的参数类型，但勉强可以用 😭

大哥，我特地登录过来感谢你的。
各种骚操作都尝试了，差点要去用 饿了么 的UI 库了。
最后试了你的 骚操作，发现果然可行。
经过我的测试，你的方法可行，你把 tempRemoteMethod 设置为 null，可以避免报那个异常。

@cdz620 提供的方式虽然也可以，但是 第一个方案的UI 实在太丑了，而且改样式改的我感觉像怀孕呕吐一样。

感谢，感谢

[https://webrtcn.com](url)

**Comment by skyflysun** [comment]
simply run the remote function once, passing in the default values

不使用骚操作，将默认值带入远程函数运行一遍就可以

example ：https://run.iviewui.com/rUBT1qAZ

**Comment by cdz620** [comment]
@skyflysun 老铁你真厉害

**Comment by BingBlog** [comment]
@allochi 
> Actually, it used to be the case and it got broken long time ago and never fixed. I'm in the mess of it right now, check iView 2.13 which is the last time it used to work.
> 
> Not to undermine the good work the iView team are putting into the library, and I'm thankful for using iView for over a year now in my project, but I found myself forced to move away from it because of its unstable behaviour with every update.

I found this solution: https://run.iviewui.com/rUBT1qAZ. And it works~

**Comment by rainbowsuger** [comment]
> simply run the remote function once, passing in the default values
> 
> 不使用骚操作，将默认值带入远程函数运行一遍就可以
> 
> example ：https://run.iviewui.com/rUBT1qAZ

是数组，没有办法带入执行一次远程搜索函数

**Comment by rainbowsuger** [comment]
> simply run the remote function once, passing in the default values
> 
> 不使用骚操作，将默认值带入远程函数运行一遍就可以
> 
> example ：https://run.iviewui.com/rUBT1qAZ

但是这样可以回显会导致没有办法

> > @lingoh
> > ```
> > <Select :remote-method="tempRemoteMethod">
> > </Select
> > ```
> > 
> > 
> > ```js
> > data: {
> >     tempRemoteMethod: false
> > },
> > methods: {
> >     remoteMethod(){
> >      //.......
> >     }
> > }
> > ```
> > 
> > 
> > 先把 remote-method 赋为 false, 在设置好默认值后（此时可以正常显示），再
> > ```js
> > tempRemoteMethod = remoteMethod
> > ```
> > 
> > 
> > 重新变成可以远程搜索
> > 会报一个Warning，因为 false 不是 remote-method 的参数类型，但勉强可以用 😭
> 
> 大哥，我特地登录过来感谢你的。
> 各种骚操作都尝试了，差点要去用 饿了么 的UI 库了。
> 最后试了你的 骚操作，发现果然可行。
> 经过我的测试，你的方法可行，你把 tempRemoteMethod 设置为 null，可以避免报那个异常。
> 
> @cdz620 提供的方式虽然也可以，但是 第一个方案的UI 实在太丑了，而且改样式改的我感觉像怀孕呕吐一样。
> 
> 感谢，感谢
> 
> [https://webrtcn.com](url)
这样做可以回显，但是远程搜索函数好像不会再执行了

**Comment by skyflysun** [comment]
> > simply run the remote function once, passing in the default values
> > 不使用骚操作，将默认值带入远程函数运行一遍就可以
> > example ：https://run.iviewui.com/rUBT1qAZ
> 
> 是数组，没有办法带入执行一次远程搜索函数

搜索的时候后台不支持数组搜索吗？我这边是麻烦后台支持多个搜索；不然就需要自己把默认值加入的下拉菜单列表
