### ISSUE TITLE
好像缺少常用布局？

### ISSUE THREAD

**Issue by hongliming** [iview/iview#48]
建议文档可以给出一些常用布局的示例代码

**Comment by icarusion** [comment]
https://www.iviewui.com/components/layout

**Comment by jingsam** [comment]
有layout https://www.iviewui.com/components/layout

**Comment by smoook** [comment]
请问一下，使用传统web开发的方式，直接在html中使用iview，布局怎么出错了呢，

**Comment by smoook** [comment]
![1 12 954q1bcr t3vbnz dh](https://user-images.githubusercontent.com/15136490/30528032-869f8572-9c61-11e7-8ecd-fb450b486766.png)
