### ISSUE TITLE
table单选，table默认勾选记录

### ISSUE THREAD

**Issue by KevinGZ2017** [iview/iview#480]
### iView 版本号
0.9.17

### 操作系统/浏览器 版本号
Chrome 56

### Vue 版本号
1.0.26

### 问题现象，以及你期望的结果是怎样的?

1、table中有多选的设置，好像没找到单选的设置？
2、在加载table列表时，我希望能默认能把某条记录勾选中，请问是否有办法实现？

**Comment by icarusion** [comment]
仔细看文档，都有
