### ISSUE TITLE
[Bug Report][compatibility] Component Select doesn't work in IE10

### ISSUE THREAD

**Issue by uranusAdam** [iview/iview#4801]
### Environment
MicroSoft Windows 7/ IE 10 (10.0.9200.17609) / Vue 2.5.17

### Reproduction link
[https://run.iviewui.com/x4yiYTTY](https://run.iviewui.com/x4yiYTTY)

### Steps to reproduce
When I choose an option, the data of select doesn't change.

### What is expected?
the data will change

### What is actually happening?
the data doesn't change

**Comment by icarusion** [comment]
Some components or features not support IE

**Comment by leixu2txtek** [comment]
ie 9 可以不支持，ie10 应该可以支持的吧，一刀切。。不能升级了

**Comment by webliving** [comment]
不能一下子就不支持了吧, 保持一个3.x版本支持提供更新, 4.x 才停止支持呢? 有个过渡版本呢?

**Comment by trsoliu** [comment]
在main.js里加

var isIE = function() {
return(window.navigator.userAgent.indexOf("MSIE") >= 1);
}

// 修复iview 在IE10及以下版本不支持dataset属性的问题，兼容transfer-dom.js中使用了dataset的问题
if(isIE() && window.HTMLElement) {
if(Object.getOwnPropertyNames(HTMLElement.prototype).indexOf('dataset') === -1) {
Object.defineProperty(HTMLElement.prototype, 'dataset', {
get: function() {
var attributes = this.attributes;
var name = [],
value = [];
var obj = {};
for(var i = 0; i < attributes.length; i++) {
if(attributes[i].nodeName.slice(0, 5) == 'data-') {
name.push(attributes[i].nodeName.slice(5));
value.push(attributes[i].nodeValue);
}
}
for(var j = 0; j < name.length; j++) {
obj[name[j]] = value[j];
}
return obj;
}
});
}
}
