### ISSUE TITLE
[Bug Report]Select in Radio does not respone the click event

### ISSUE THREAD

**Issue by buildJava** [iview/iview#4806]
### Environment
Mac/Chrome70/Iview3.1.4

### Reproduction link
[https://jsfiddle.net/5j6pud0q/](https://jsfiddle.net/5j6pud0q/)

### Steps to reproduce
click the select does not work well

### What is expected?
fix the bug dropdown well

### What is actually happening?
can not dropdown

**Comment by trsoliu** [comment]
How to deal with this problem？
