### ISSUE TITLE
上传文件的时候如何添加自定义header

### ISSUE THREAD

**Issue by frincel** [iview/iview#481]
上传文件的时候怎样把自定义header加入？并且，我需要把上传文件组件放在一个form里，上传后显示缩略图预览。表单完成后才一起提交。应该怎么做呢？

**Comment by rijn** [comment]
beforeupload

**Comment by icarusion** [comment]
楼上正解。通过beforeUpload钩子可以拿到 file，然后爱怎么做就怎么做。如果使用 iView 的能力上传，可以 通过 `this.$refs.upload.post(file)`
