### ISSUE TITLE
[Feature Request] Message message prompt, if prompted several times in a short time with the same message content, is it considered to merge messages?


### ISSUE THREAD

**Issue by moqingliang** [iview/iview#4811]
### What problem does this feature solve?
如果我短时间内连续多次调用：this.$Message.error('测试'); 会出现多个提示，界面不友好

### What does the proposed API look like?
希望可以在Message全局配置中 this.$Message.config 增加一个配置项，可以对短时间内提示多次消息内容一样的，做消息合并

**Comment by icarusion** [comment]
No such plan.
