### ISSUE TITLE
The interface name of the [Bug Report] TS type definition has been changed, but the export definition has not been changed, resulting in compilation errors of ts!


### ISSUE THREAD

**Issue by hemiaoio** [iview/iview#4814]
### Environment
any

### Reproduction link
[https://github.com/iview/iview/blob/b7d7c4ad05825b1338480702c87164d126f376d2/dist/types/iview.components.d.ts#L56](https://github.com/iview/iview/blob/b7d7c4ad05825b1338480702c87164d126f376d2/dist/types/iview.components.d.ts#L56)

### Steps to reproduce
any

### What is expected?
TabsPane --> TabPane

### What is actually happening?
TabsPane

**Comment by yangdan8** [comment]
重复bug #4861

**Comment by yangdan8** [comment]
见pr #4929

**Comment by yangdan8** [comment]
合并pr后可关闭 @icarusion

**Comment by icarusion** [comment]
#4809
