### ISSUE TITLE
[Bug Report] Select Component Option cannot pass Form Validator validation after setting Number type in its valu attribute


### ISSUE THREAD

**Issue by xuchangjunjx** [iview/iview#4817]
### Environment
Win7

### Reproduction link
[https://run.iviewui.com/VonSOOCe](https://run.iviewui.com/VonSOOCe)

### Steps to reproduce
1.创建一个Form
2.FormItem 中一个Select ,option的value为数字即可

### What is expected?
期望数字类型可以校验通过

### What is actually happening?
无法通过表单校验

**Comment by icarusion** [comment]
校验规则默认是 string
