### ISSUE TITLE
按钮不正确的显示动画

### ISSUE THREAD

**Issue by usercao** [iview/iview#482]
### 能够复现问题的在线示例（重要）
树形控件 Tree - iView https://www.iviewui.com/components/tree

### 复现步骤
![Image of Yaktocat](http://i1.piimg.com/580149/71f2dde48fd0cde4.png)
### 问题现象，以及你期望的结果是怎样的?
点击leaf后红框处有不正确的显示动画（贴图库图床）
### 你估计可能的原因是什么（选填）？
![Image](http://i1.piimg.com/580149/729d9683c0f4b890.png)

**Comment by icarusion** [comment]
看不懂
