### ISSUE TITLE
[Bug Report]A transfered DatePicker blocks input focus on a transfered ColorPicker

### ISSUE THREAD

**Issue by fantkolja** [iview/iview#4826]
### Environment
Latest Chrome

### Reproduction link
[https://jsfiddle.net/esjznu9x/1/](https://jsfiddle.net/esjznu9x/1/)

### Steps to reproduce
1. Add somewhere in the app the DatePicker component with 'transfer' set to true.
2. Add the  ColorPicker with 'transfer' set to true.
3. Click on the input field in the ColorPicker dropdown.

### What is expected?
The input in ColorPicker should get the focus.

### What is actually happening?
The input can't be focused (only by pressing tab)

---
I've already created a similiar issue (https://github.com/iview/iview/issues/4718), that has been fixed and closed. But the situation described above wasn't handled. 
We should probably check such behavior in other components, that use global mousedown handlers.

**Comment by icarusion** [comment]
Try to update iview

**Comment by fantkolja** [comment]
@icarusion This bug is found in the latest version 3.1.5. You can check it here https://jsfiddle.net/esjznu9x/3/.
