### ISSUE TITLE
[Feature Request] When clicking on the *"icon that comes with the component to close Drawer drawer, provide a way to manually prevent the closure of Drawer


### ISSUE THREAD

**Issue by silencyXiao** [iview/iview#4829]
### What problem does this feature solve?
在编辑或添加内容时，打开一个Drawer组件，当Drawer组件中的表单更改时，关闭抽屉将会弹出提示【存在修改未保存】，点击取消，Drawer是不会被关闭的，但是点击组件自带的“×”图标时会强制关闭；

### What does the proposed API look like?
提供一个类似的方法： this.$refs.drawer.preventClose()

**Comment by icarusion** [comment]
No such plan now.
