### ISSUE TITLE
不支持服务端渲染？检查window抛出错误

### ISSUE THREAD

**Issue by HellMagic** [iview/iview#483]
### iView 版本
2.0.0-rc.6

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.1.10

### 复现步骤
直接从页面刷新的时候出现错误，错误提示"window is not defined in iview/dist/iview.js"
### 问题现象，以及你期望的结果是怎样的?
期望能支持服务端渲染
### 你估计可能的原因是什么（选填）？
没有添加对服务端渲染必要的检测--比如 eg: typeof window === 'undefined'

**Comment by rijn** [comment]
@icarusion This issue can be closed.
