### ISSUE TITLE
The drop-down option of the [Bug Report]Dropdown component will still trigger on-click events after setting the attribute disabled.


### ISSUE THREAD

**Issue by cutpictureboy** [iview/iview#4832]
### Environment
MacOS10.14.1 / Chrome 70.0.3538.77 / Vue 2.5.17

### Reproduction link
[https://run.iviewui.com/ZoQdyhcF](https://run.iviewui.com/ZoQdyhcF)

### Steps to reproduce
点击禁用的下拉选项

### What is expected?
不触发on-click事件

### What is actually happening?
触发了on-click事件

**Comment by icarusion** [comment]
就是这样设计的。
你需要自己判断这个节点是否是 disabled
