### ISSUE TITLE
[Feature Request]AutoComplete option list adds scroll bars to limit length

### ISSUE THREAD

**Issue by cn-src** [iview/iview#4837]
### What problem does this feature solve?
Option list too long.

### What does the proposed API look like?
Has scroll bars.

**Comment by icarusion** [comment]
No such plan.

**Comment by maggiew61** [comment]
some of the styles I set:
.ivu-select-dropdown-list{
  height: 250px !important;  //it deals w/ the list width& height
}
.ivu-select-dropdown{  //it deals w/ the list width& height
  width:220px !important;
  overflow-x: hidden !important;
}
.ivu-select-item{
  font-size:16px !important;
  text-align:left !important;
}
.ivu-input, .ivu-input-default{
  font-size: 16px !important;
}
