### ISSUE TITLE
[Bug Report] Cascade:  switch between same cousins return and display only parent

### ISSUE THREAD

**Issue by Fauny** [iview/iview#4846]
### Environment
Macos Mojave, Chrome 72, Vue 2.5.17

### Reproduction link
[https://jsfiddle.net/qtysdm6k/](https://jsfiddle.net/qtysdm6k/)

### Steps to reproduce
1. select [北京 / 1]
2. switch to [江苏 / 1 ]

### What is expected?
display [ 江苏 / 1 ]
and values : ['jiangsu', 1]

### What is actually happening?
display only parent [ 江苏 ]
and lost child in value: [ 'jiangsu' ]

**Comment by icarusion** [comment]
Do not use same label or value

**Comment by Fauny** [comment]
> Do not use same label or value

This is my app needs,  and,  it's common at large
