### ISSUE TITLE
In [Bug Report] iview. components. D. ts, export {Tabs, TabsPane} from'. / tabs'; change to export {Tabs, TabPane} from'. / tabs';


### ISSUE THREAD

**Issue by MichaelGong** [iview/iview#4861]
### Environment
iview: 3.1.5 环境无关

### Reproduction link
[https://github.com/iview/iview/blob/2.0/types/iview.components.d.ts#L56](https://github.com/iview/iview/blob/2.0/types/iview.components.d.ts#L56)

### Steps to reproduce
typescript 下引入iview时会报错

### What is expected?
export { Tabs, TabsPane } from './tabs'; 修改为 export { Tabs, TabPane } from './tabs';

### What is actually happening?
TabsPane 在tabs.d.ts中不存在

**Comment by yangdan8** [comment]
合并pr后可关闭 @icarusion

**Comment by icarusion** [comment]
#4809
