### ISSUE TITLE
Slider滑块在Ipad上的兼容性问题

### ISSUE THREAD

**Issue by CodeMonkeyXu** [iview/iview#487]
### 复现步骤
在ipad上打开iView官网，试用滑块效果，结果不理想
### 问题现象，以及你期望的结果是怎样的?
拖动滑块时卡顿甚至拖不动，期望能像pc端一样流畅。
### 你估计可能的原因是什么（选填）？
可能是移动端的事件和pc端有区别，没有进行兼容性处理

**Comment by icarusion** [comment]
暂不支持触摸事件
