### ISSUE TITLE
[Feature Request]Tree add check-strictly prop

### ISSUE THREAD

**Issue by adamma1024** [iview/iview#4872]
### What problem does this feature solve?
   >when showcheckbox ， we can’t check all parents and children nodes but only one node.

  >当设置了showcheckbox，我们可以不级联选择 

### What does the proposed API look like?
```javascript
  props:{
    checkStrictly:{
      type:boolean,
      default:false
    }
 }
```

**Comment by dentm** [comment]
没有什么效果，子节点全部选中之后依然会勾选父节点

**Comment by zhoujie-cn** [comment]
没有效果，根本修改不了checkStrictly的值，试过很多次了，只能去dist里面修改
