### ISSUE TITLE
<Cascader>清空数据问题

### ISSUE THREAD

**Issue by ken1987** [iview/iview#488]
### iView 版本号
 2.0.0-rc.5 

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例（重要）
https://codepen.io/anon/pen/KWBKxp

### 复现步骤
1. 在 `<Cascader>` 选择一个值
2. 点击按钮清空
3. 输入框中依然显示 `item 1`

### 问题现象，以及你期望的结果是怎样的?
第三步清空输入框中的值

### 你估计可能的原因是什么（选填）？
建议在源码 `cascader.vue`  增加值为空数组的判断，如果是空数组，清空 `this.selected` ，例如
``` js
{
      ...
        watch: {
            value (val) {
                this.currentValue = val
                if(!val.length){
                   this.selected = [];
               }
            }
       }
      ...
}
```

**Comment by icarusion** [comment]
Thanks a lot.
