### ISSUE TITLE
[Bug Report]select multiple bug

### ISSUE THREAD

**Issue by djkloop** [iview/iview#4883]
### Environment
osx/chrome 最新版/ vue 2.5.17/ iview 3.x

### Reproduction link
[https://run.iviewui.com/drlD9B5B](https://run.iviewui.com/drlD9B5B)

### Steps to reproduce
select改为多选模式的时候，表单验证不能正确验证

### What is expected?
能正确验证

### What is actually happening?
不能正确验证

---
官网例子复制粘贴就能触发

**Comment by victory820** [comment]
city: [
                        { required: true, type: 'Array', message: 'Please select the city', trigger: 'change' }
                    ]
注意看文档

**Comment by djkloop** [comment]
@victory820 3q
