### ISSUE TITLE
[Bug Report]in ts declare files,tabs.d.ts is not match to iview.components.d.ts

### ISSUE THREAD

**Issue by misakamayako** [iview/iview#4886]
### Environment
windows 7 

### Reproduction link
no url to show

### Steps to reproduce
import iview from 'iview'

### What is expected?
no error

### What is actually happening?
[iview.components.d.ts](https://github.com/iview/iview/blob/153455c06c9ac97cecb06093752122995714cd83/dist/types/iview.components.d.ts#L56) is not equal to [tabs.d.ts](https://github.com/iview/iview/blob/153455c06c9ac97cecb06093752122995714cd83/dist/types/tabs.d.ts#L61)

**Comment by misakamayako** [comment]
it's "TabsPane" in iview.components.d.ts,but in tabs.d.ts it's "TabPane"

**Comment by RookieZoe** [comment]
@misakamaiyako @icarusion 
这个我其实在 pr #4809 里面已经修了，改成了 TabPane。。。因为：
1. 在官方文档里面，https://www.iviewui.com/components/tabs，用法就是 TabPane
2. 在 src/components/tabs/pane.vue 里，name 也是 TabPane。

**Comment by Anna-mm** [comment]
@RookieZoe 请问什么时候release 新版本。

**Comment by RookieZoe** [comment]
@Anna-mm 我不是 iview 官方的，具体什么时候 release 我也不是很清楚。。。如果你着急用的话，你可以 fork 一份代码到自己的仓库，然后自己把这个问题修一下，打个标签，然后把使用 iview 的项目的依赖改一下。

**Comment by wizardpisces** [comment]
same problem

**Comment by wizardpisces** [comment]
also tab problem, has anyone ever encounter this?

reproduction step:
1. use vue-cli3 create project with typescript
2. vue add vue-cli-plugin-iview
3. npm run serve

ERROR in 'project_name/node_modules/iview/dist/types/tabs"''  has no exported member 'TabsPane'. Did you mean 'TabPane'?

**Comment by RookieZoe** [comment]
@wizardpisces yep~😂

**Comment by yangdan8** [comment]
同 #4861 #4814 
见pr #4929

**Comment by yangdan8** [comment]
合并pr后可关闭 @icarusion

**Comment by icarusion** [comment]
#4809
