### ISSUE TITLE
在$Modal中调用$Modal会造成第二个modal一闪而过

### ISSUE THREAD

**Issue by s51983** [iview/iview#489]
### iView 版本号
2.0.0-rc.6 

### 操作系统/浏览器 版本号
Chrome 56 

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
在$Modal的onOk中调用另一个$Modal时，第二个弹出的$Modal一闪而过马上关闭。

**Comment by s51983** [comment]
以上问题仅存在于两个实例化的Modal中。

**Comment by icarusion** [comment]
Modal 全局只创建了一个，所以要等第一个消失时再创建第二个。消失有300 ms 延时。

**Comment by icarusion** [comment]
Modal 全局只创建了一个，所以要等第一个消失时再创建第二个。消失有300 ms 延时。
