### ISSUE TITLE
TypeScript TabsPanel 命名出错

### ISSUE THREAD

**Issue by ankyo** [iview/iview#4896]
`
has no exported member 'TabsPane'. Did you mean 'TabPane'?
    54 | export { Switch, Switch as ISwitch } from './switch';
    55 | export { Table, TableColumn, TableRenderCreateElementData, TableColumnRenderParams, TableRenderCreateElementResult, TableColumnRenderHeadParams, TableExportCsvParams } from './table';
  > 56 | export { Tabs, TabsPane } from './tabs';
       |                ^
    57 | export { Tag } from './tag';
    58 | export { Time } from './time';
    59 | export { Timeline, TimelineItem } from './timeline';
No lint errors found
Version: typescript 3.1.6, tslint 5.11.0
`

**Comment by 6peiweb** [comment]
Module '"/Users/liupei/Desktop/cs-fe-ems/Application/node_modules/iview/dist/types/tabs"' has no exported member 'TabsPane'. Did you mean 'TabPane'?
