### ISSUE TITLE
[Feature Request] expects the datepicker date selection component V-model to bind and return to a standard date format such as 2011-12-05


### ISSUE THREAD

**Issue by messikiller** [iview/iview#4897]
### What problem does this feature solve?
目前使用 v-model 绑定后返回的 javascript 日期信息在不同浏览器上有不同的结果，例如 Chrome 上“Sat Nov 24 2018 08:50:57 GMT 0800 (中国标准时间)”，而其他浏览返回“Sat Nov 24 2018 08:50:57 GMT 0800”（无括号），带括号的日期信息直接传递到后端接口后转换时候不太方便，php 的strtotime 函数无法直接转换带括号的日期，之前都是前端绑定value，然后监听 on-change 事件将 $event 赋值给当前变量，总感觉不太方便

### What does the proposed API look like?
v-model 绑定后，返回的值始终是 yyyy-MM-dd 格式

**Comment by icarusion** [comment]
No such plan.
