### ISSUE TITLE
vue2.0+vue-router2.0

### ISSUE THREAD

**Issue by maqunboy** [iview/iview#49]
vue2.0+vue-router2.0  在这种环境可以正常运行么？ 我在本地引用发现总是报  import错误。

**Comment by icarusion** [comment]
暂不支持vue2.0

**Comment by cgkoreyoshi** [comment]
@icarusion 有计划支持VUE 2.0么

**Comment by icarusion** [comment]
未来会新开一个分支支持2.0

**Comment by billbobo** [comment]
应该尽快支持2.0，毕竟2.0正式版都已经发布了，新项目一般都直接上2.0了。

**Comment by transtone** [comment]
未来是什么时候，是否在计划中？

**Comment by icarusion** [comment]
17年会新开一个分支来支持2.0

**Comment by transtone** [comment]
17年！还不如自己 fork 一个来用。

**Comment by ljyf5593** [comment]
@transtone  你可以fork一个出来 然后在pull request到这个项目啊

**Comment by xchz** [comment]
建议2.0用material design

**Comment by yuu2lee4** [comment]
ant design官方马上要出vue2的版本了
