### ISSUE TITLE
2.0根本就不能用cdn的方式来调用

### ISSUE THREAD

**Issue by benaheng** [iview/iview#490]
好多组件都在调用cdn的方式下无法使用,但是1.0的没这些问题

**Comment by icarusion** [comment]
仔细看文档，注意标签的用法

**Comment by benaheng** [comment]
请问我该怎么用?我就是按照文档上写的,哪里不对吗

`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>iview example</title>
    <link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
    <script type="text/javascript" src="http://vuejs.org/js/vue.min.js"></script>
    <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>

</head>
<body>
<div id="app">
    <Form :model="formLeft" label-position="left" :label-width="100">
        <Form-item label="标题">
            <Input v-model="formLeft.input1"></Input>
        </Form-item>
        <Form-item label="标题名称">
            <Input v-model="formLeft.input2"></Input>
        </Form-item>
        <Form-item label="标题名称对齐">
            <Input v-model="formLeft.input3"></Input>
        </Form-item>
    </Form>
</div>
<script>
    new Vue({
        el: '#app',
        data: {
            formLeft: {
                input1: '',
                input2: '',
                input3: ''
            },
        },
        methods: {
          
        }
    })
</script>
</body>
</html>`

**Comment by icarusion** [comment]
![image](https://cloud.githubusercontent.com/assets/5370542/24327194/4b2256b2-11fd-11e7-8920-98279a35f5ae.png)

**Comment by benaheng** [comment]
我建议还是统一为好,或者所有的标签都加一个统一的前缀

**Comment by limodou** [comment]
Form 改为 i-form 是对了。但是下面的Input为什么不用改为i-input呢？这里的规则是什么？

另外想问一下，自已写的vue编译也可以象iview这样用吗？有没有介绍是如何做到的文档？
