### ISSUE TITLE
[Bug Report] select goes up and renders the problem after searching


### ISSUE THREAD

**Issue by Juzisuan965** [iview/iview#4913]
### Environment
macOS/chrome 70.0.3538.102/vue 2.5.17/iview 3.0.0

### Reproduction link
[https://jsfiddle.net/2gp5jqfu/4/](https://jsfiddle.net/2gp5jqfu/4/)

### Steps to reproduce
点击select，输入'c'

### What is expected?
页面渲染正常

### What is actually happening?
页面渲染异常

**Comment by Juzisuan965** [comment]
@icarusion

**Comment by icarusion** [comment]
fixed in #4993
