### ISSUE TITLE
dropdown组件中的on-click该怎么绑定，我试了好几次都报错

### ISSUE THREAD

**Issue by wqzwh** [iview/iview#493]
dropdown组件中的on-click该怎么绑定，我试了好几次都报错，

`<Dropdown @on-click="handClick" style="margin-left: 20px">

        <Button type="primary">
            下拉菜单
            <Icon type="arrow-down-b"></Icon>
        </Button>
        <Dropdown-menu slot="list">
            <Dropdown-item>驴打滚</Dropdown-item>
            <Dropdown-item>炸酱面</Dropdown-item>
            <Dropdown-item disabled>豆汁儿</Dropdown-item>
            <Dropdown-item>冰糖葫芦</Dropdown-item>
            <Dropdown-item divided>北京烤鸭</Dropdown-item>
        </Dropdown-menu>
    </Dropdown>
`

**Comment by icarusion** [comment]
```vue
<template>
    <div>
        <Dropdown @on-click="handleClick">
            <a href="javascript:void(0)">
                下拉菜单
                <Icon type="arrow-down-b"></Icon>
            </a>
            <Dropdown-menu slot="list">
                <Dropdown-item name="1">驴打滚</Dropdown-item>
                <Dropdown-item name="2">炸酱面</Dropdown-item>
                <Dropdown-item name="3" disabled>豆汁儿</Dropdown-item>
                <Dropdown-item name="4">冰糖葫芦</Dropdown-item>
                <Dropdown-item name="5" divided>北京烤鸭</Dropdown-item>
            </Dropdown-menu>
        </Dropdown>
    </div>
</template>
<script>
    export default {
        methods: {
            handleClick (val) {
                console.log(val)
            }
        }
    }
</script>
```

**Comment by gosongs** [comment]
怎么传递额外的参数呢 @icarusion

**Comment by sharmun** [comment]
你好 额外传参的问题解决了吗

**Comment by BerlinChan** [comment]
> @gosongs @sharmun 
传递额外参数

<Dropdown @on-click="handleDropDownClick($event, otherArgu)">
  <i class="icon"></i>
  <DropdownMenu slot="list">
    <DropdownItem name="edit">编辑</DropdownItem>
    <DropdownItem name="delete">删除</DropdownItem>
  </DropdownMenu>
</Dropdown>
</template>

handleDropDownClick: function (name, otherArgu) {
  console.log(name, otherArgu);
}

**Comment by yecao007** [comment]
刚开始也是写成函数，其实是一个event事件，不用传参数或【如要写成函数形式就传$event参数】，只是官方没有给例子，对于新手不好理解
