### ISSUE TITLE
Form组件中包含需要验证的datepicker组件时，datepicker组件没有及时响应验证规则

### ISSUE THREAD

**Issue by xiaoyyang123** [iview/iview#494]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）
https://codepen.io/xiaoyyang/pen/NpBBPL

### 复现步骤
先点击页面上的确定按钮，提示要选择日期，选择日期后验证内容没有及时响应（即错误提示消息）

### 问题现象，以及你期望的结果是怎样的?
选择日期后错误提示应该及时消息

### 你估计可能的原因是什么（选填）？
datepick组件没有传递相应的验证事件给form

**Comment by icarusion** [comment]
貌似 watch 会在 emit 后触发，所以验证时，数据其实还没有改变。Thanks.
