### ISSUE TITLE
MenuSub 确定是这个名字？ 文档显示是SubMenu，并且这个名字报错了

### ISSUE THREAD

**Issue by kingzcheung** [iview/iview#4945]
https://github.com/iview/iview/blob/153455c06c9ac97cecb06093752122995714cd83/types/iview.components.d.ts#L40

还有字义的TabsPane 找不到

**Comment by qm88888888** [comment]
兄弟你最后解决了么

**Comment by kingzcheung** [comment]
放弃这框架了
