### ISSUE TITLE
[Bug Report]radioButton Clicking on an event triggers it twice, how to solve problems?

### ISSUE THREAD

**Issue by xiaoweiQ** [iview/iview#4946]
### Environment
window7, 本 64.0.3282.186（正式版本） （32 位）/Vue3.0.3

### Reproduction link
[https://run.iviewui.com/yCfTFjzd](https://run.iviewui.com/yCfTFjzd)

### Steps to reproduce
点击按钮，在控制台会输出两次'click'

### What is expected?
希望是冒泡的原因导致，并可以通过@click.native.stop得以解决

### What is actually happening?
@click.native.stop还是打印了两次

**Comment by chenjibin** [comment]
为啥不用self修饰符？@click.native.self
