### ISSUE TITLE
[Feature Request] iView form add print function (The form to print)


### ISSUE THREAD

**Issue by xiaoseLibrary** [iview/iview#4947]
### What problem does this feature solve?
现在的报表大多需求开始加入打印功能，目前热门的几个打印实现，在iview表单上实践起来并不是十分方便，即便是可以实现打印，但是打印的样式却十分难以控制。
（Now most of the report requirements began to add printing function, currently a few popular printing implementation, in iview form practice is not very convenient, even if you can achieve the printing, but the printing style is very difficult to control.）

### What does the proposed API look like?
api 和 导出功能的 api 相同就可以

**Comment by icarusion** [comment]
No such plan
