### ISSUE TITLE
[Feature Request] time-picker time selector supports select hours only


### ISSUE THREAD

**Issue by zhe-he** [iview/iview#4952]
### What problem does this feature solve?
某些场景不需要具体到多少分多少秒.
例如我想知道5点到8点的统计数据，而不是5点10分到8点20分的统计数据

### What does the proposed API look like?
`<time-picker format="HH" type="timerange"></time-picker>`

**Comment by zhe-he** [comment]
目前是通过设置禁用0～59分钟来解决的
`<time-picker format="HH:mm" :disabled-minutes="[0,1,2,...,59]" type="timerange"></time-picker>`

**Comment by icarusion** [comment]
You'd better use Select component
