### ISSUE TITLE
[Bug Report] select option is not selected by clicking under ie10, double-click can be selected


### ISSUE THREAD

**Issue by shaomingming008** [iview/iview#4960]
### Environment
win10系统 ie10浏览器 vue版本2.x

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
点击select选择一个选项  

### What is expected?
期望跟其他浏览器一样 单击就可以选中

### What is actually happening?
要双击才能选中

**Comment by Frank-C-Zhang** [comment]
@iview-bot  很好奇为什么IE10里面需要双击才能选中。请问一哈可以怎么解决呢。让其可以单击就可以选中
