### ISSUE TITLE
[Bug Report] The onchange function of the Checkbox Group in the render of the Table component returns the currently selected data, not all the selected data.


### ISSUE THREAD

**Issue by wangxv** [iview/iview#4961]
### Environment
vue :2.5.17

### Reproduction link
[https://run.iviewui.com/preview/QSP6YUi1](https://run.iviewui.com/preview/QSP6YUi1)

### Steps to reproduce
1.选中张一
2.选中张二
3.返回张二

### What is expected?
返回张一，张二

### What is actually happening?
返回张二

**Comment by kiccer** [comment]
遇到相同问题，是啥“使用问题”可以说明吗？

**Comment by kiccer** [comment]
https://run.iviewui.com/nCleDE0Q

**Comment by kiccer** [comment]
最后我自己想办法解决了↓↓↓
https://run.iviewui.com/65nHuUrj
---
不是我说，这个肯定不是使用问题，绝对有BUG！
