### ISSUE TITLE
'iview/dist/types/tabs' has no exported member 'TabsPane'.

### ISSUE THREAD

**Issue by luponZ** [iview/iview#4964]
**reason**
  ts-lint tell me this mistake when i import iView, it maybe cased  by wrong words

**link**
>54 | export { Switch, Switch as ISwitch } from './switch';
> 55 | export { Table, TableColumn, TableRenderCreateElementData, TableColumnRenderParams, TableRenderCreateElementResult, TableColumnRenderHeadParams, TableExportCsvParams } from './table';
> 56 | export { Tabs, TabsPane } from './tabs';

**language**
TS

**Comment by Ross01859** [comment]
![image](https://user-images.githubusercontent.com/25303760/49778036-20822580-fd3e-11e8-9694-a827e39845ec.png)
