### ISSUE TITLE
[bug Report]autoComplete on-select don't be trigger

### ISSUE THREAD

**Issue by wangyongxin11** [iview/iview#4976]
autoComplete组件，当输入的条件完全匹配时，并不会触发，on-change和on-select事件。
例如：
当待选择列表中存在AAA项时，此时如果自己也完全输入AAA时，自动补全下拉过滤到的项目只包含AAA项时，此时选择AAA项目，并不会触发on-select事件

**Comment by kkltmoyu** [comment]
这个bug我之前提过了，https://github.com/iview/iview/issues/4441

**Comment by zhangshichuan** [comment]
我也有这个问题。还有每次触发AutoComplete后，需要点击其他输入框２次才能获取焦点
