### ISSUE TITLE
[Bug Report]AutoComplete bug: query change but dropdown invisible

### ISSUE THREAD

**Issue by zhouqing86** [iview/iview#4985]
### Environment
Chrome

### Reproduction link
[https://www.iviewui.com/components/auto-complete](https://www.iviewui.com/components/auto-complete)

### Steps to reproduce
1.Input "ni", the dropdown will be visible
2.Click the input box, the dropdown will be invisible
3.Input one more character or delete one character from the input box, the dropdown still invisible.

### What is expected?
When the query in input box change, the dropdown should be visible according to your query.

### What is actually happening?
Query in input box change, but dropdown not visible. Need to click the input box once again to make it visible.

**Comment by maggiew61** [comment]
thanks!
