### ISSUE TITLE
Tree组件的Bug文件

### ISSUE THREAD

**Issue by xugege** [iview/iview#499]
### iView 版本号
我使用源码构建

### Vue 版本号
vue2+

### 问题描述
我使用Tree组件，当tree组件的第一级节点之间的距离非常大

###online code
http://sandbox.runjs.cn/show/st5d64tt

**Comment by icarusion** [comment]
support code online

**Comment by xugege** [comment]
@icarusion 
增加线上代码，因为不能上传font文件，所以图标没有正确显示，但是问题可以看见
http://sandbox.runjs.cn/show/st5d64tt
