### ISSUE TITLE
[Bug Report]button right click not work

### ISSUE THREAD

**Issue by mudenglong** [iview/iview#4999]
### Environment
vue 2.5; chrome

### Reproduction link
[https://run.iviewui.com/qZSu76Tv](https://run.iviewui.com/qZSu76Tv)

### Steps to reproduce
use iview button , right click not work ;

### What is expected?
work

### What is actually happening?
not work ; cannot make the modal out

**Comment by MinosIE** [comment]
<input type="button" value="按钮1" @click.prevent="modal1 = true"> 
    <iButton type="primary"  @click.prevent="modal1 = true">Display dialog box</iButton>
这样使用不行吗

**Comment by bruce4code** [comment]
我这样可以跳出来哦～
https://run.iviewui.com/xUpVYiZd

<iButton type="primary"  @click="btnClick">Display dialog box</iButton>
 
methods: {
      btnClick(){
        this.modal1 = true
      }
}

**Comment by icarusion** [comment]
@contextmenu.prevent.native
