### ISSUE TITLE
Page组件分页小于10时，显示异常

### ISSUE THREAD

**Issue by Pinary** [iview/iview#50]
![image](https://cloud.githubusercontent.com/assets/16324157/19921781/7021c514-a11a-11e6-8a12-8f6b1d05ba31.png)

如图所示，此时pageSize=5

**Comment by icarusion** [comment]
page-size要配合page-size-opts一起使用：
```html
<Page :total="100" show-sizer :page-size="5" :page-size-opts="[5,10,15,20]"></Page>
```

**Comment by boboyan** [comment]
.
