### ISSUE TITLE
安装使用问题

### ISSUE THREAD

**Issue by CrazyProgrammer12138** [iview/iview#5000]
根据步骤安装完成之后，再配置.babelrc文件 plugins 得时候，保存就会报错，ReferenceError: iView is not defined；

![Uploading image.png…]()

**Comment by fukai007** [comment]
@CrazyProgrammer12138  
我解决了,vue-cli + iview 去除 babel 的 import 插件 
module.exports = {
  presets: [
    '@vue/app'
  ],
  // "plugins": ["transform-decorators-legacy","@babel/plugin-proposal-class-properties"]
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties",{ "loose": true }],
    // ["import", {
    //   "libraryName": "iview",
    //   "libraryDirectory": "src/components"
    // }]
  ]
}
