### ISSUE TITLE
[Bug Report]When Dropdown set custom trigger and set transfer prop , on-clickoutside will always trigger

### ISSUE THREAD

**Issue by woowalker** [iview/iview#5001]
### Environment
"iview": "^3.1.2",     "vue": "^2.5.2",

### Reproduction link
[https://run.iviewui.com/rBTJQwZa](https://run.iviewui.com/rBTJQwZa)

### Steps to reproduce
1、set trigger type 'custom'
2、set transfer props true

### What is expected?
when click outside ,it trigger 'on-clickoutside', when click inside ,it wont trigger 'on-clickoutside'

### What is actually happening?
'on-clickoutside' always trigger

**Comment by Sapphire2k** [comment]
+1
datetime-picker has the same problem..😣
