### ISSUE TITLE
[Feature Request] tabs add click-back events to customize whether the logic really wants to enter the tab page


### ISSUE THREAD

**Issue by dadianzi** [iview/iview#5009]
### What problem does this feature solve?
能够根据条件判断是否真的要进入该tab，如果条件不符合则tab保持不变。目前的版本点击tab会直接进入，无法判断。

### What does the proposed API look like?
点击后回调方法，根据条件判断返回true 或 false。

**Comment by icarusion** [comment]
No such plan
