### ISSUE TITLE
[Feature Request] InputNumber component placeholder attribute style is not consistent with input and select


### ISSUE THREAD

**Issue by zhangfugui727** [iview/iview#5018]
### What problem does this feature solve?
解决视觉不统一的问题
[https://run.iviewui.com/6yawe8x6](https://run.iviewui.com/6yawe8x6)
![image](https://user-images.githubusercontent.com/30425581/50066426-9aab2200-01f6-11e9-9327-6ef098219123.png)

### What does the proposed API look like?
相同的样式风格

**Comment by zhangfugui727** [comment]
@icarusion 我想问一下，为什么认为调整是无效的，有何考虑吗

**Comment by icarusion** [comment]
@zhangfugui727 要按要求提交 issues，这并不是 feature request，而是 bug report，所以关闭

**Comment by zhangfugui727** [comment]
@icarusion 多谢，浪费您时间了。我开始确认为bug，但是我觉得你们可能认为它是一个调整功能。

**Comment by icarusion** [comment]
恩，重新提交一个吧，issues 数太多，需要规范一下的
