### ISSUE TITLE
表单inline的样式问题

### ISSUE THREAD

**Issue by rongxingsun** [iview/iview#502]
### iView 版本号

2.0.0-rc-6

### 操作系统/浏览器 版本号

Chrome
### Vue 版本号

2.2.1

### 能够复现问题的在线示例（重要）

https://codepen.io/anon/pen/mWGdXx

### 复现步骤
https://codepen.io/anon/pen/zZJYWB

### 问题现象，以及你期望的结果是怎样的?
form表单使用用inline时，有label时，label和标签不在同一行
css重置样式把h1等的margin都设为0了

### 你估计可能的原因是什么（选填）？
form表单inline缺少有label标签时的样式
.ivu-form-inline .ivu-from-item-label {
    float: none;
    display: inline-block;
}
.ivu-form-inline .ivu-form-item-content {
    display: inline-block;
    vertical-align: top;
}
h1等样式重设过于霸道，建议把normalize放在base这后

**Comment by icarusion** [comment]
需设置 `label-width`
