### ISSUE TITLE
[Feature Request] Optimizing ideas for clickoutside custom instructions


### ISSUE THREAD

**Issue by fefuns** [iview/iview#5023]
### What problem does this feature solve?
用到自定义指令v-clicktoutside的时候，都是传入一个函数，比如v-clickoutside="hideSelect"，但是有时候可能页面上有很多的下拉框，那样的话就得写很多对应的方法去关闭某个下拉框，hideSelect1, hideSelect2, hideSelect3，但是实际上里面又只有一句代码而已，methods里面就会显得很臃肿。

### What does the proposed API look like?
能不能让v-clickoutside既支持传入方法，也支持传入简单的表达式。比如 v-clickoutside="showSelect1=false", v-clickoutside="showSelect2=false"，当有复杂情况的时候，依然可以传入一个方法，v-clickoutside="fn"

**Comment by icarusion** [comment]
No such plan
