### ISSUE TITLE
[Feature Request]Add width property to Tag component

### ISSUE THREAD

**Issue by msqar** [iview/iview#5026]
### What problem does this feature solve?
Be able to set a specific width on the tag component so every tag has the same width. Also, the "x" button has to be on position absolute pushed to right side.

### What does the proposed API look like?
Currently, seems like there's no way to change the width and modify the x icon position. Couldn't solve it via CSS/LESS. Simply not applying any property to Tag's children.

**Comment by icarusion** [comment]
No such plan
