### ISSUE TITLE
[Bug Report]the on-change event of the select component can't be triggered by setting a specified value in the list of the option

### ISSUE THREAD

**Issue by cumthyb** [iview/iview#5027]
### Environment
Mac10.14.2 /Chrome71.0.3578.98/vue 2

### Reproduction link
[https://run.iviewui.com/eutQhQk6](https://run.iviewui.com/eutQhQk6)

### Steps to reproduce
点击按钮，按钮Click事件里会改变Select组件绑定的值，

### What is expected?
期望会自动触发Select上的on-change事件

### What is actually happening?
没有自动触发on-change事件(此功能在2.8.0版本正常)；当点击下拉框事会触发

**Comment by icarusion** [comment]
No such plan
