### ISSUE TITLE
[Bug Report]Select组件下拉框中，当选择value为‘ ’(length=1的空字符串)时，label显示的是placeholder

### ISSUE THREAD

**Issue by cumthyb** [iview/iview#5032]
### Environment
mac14/chrome71/vue2

### Reproduction link
[https://run.iviewui.com/ab3ZQI7W](https://run.iviewui.com/ab3ZQI7W)

### Steps to reproduce
选择下拉框中的第一个

### What is expected?
正常显示value为‘ ’ 对应的label

### What is actually happening?
显示的是placeholder

**Comment by icarusion** [comment]
不能为空
