### ISSUE TITLE
对话框标题

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#504]
### iView 版本号
2.4.0

### 操作系统/浏览器 版本号
windows7/Chrome 56

### Vue 版本号
2.2.4

### 问题现象，以及你期望的结果是怎样的?

对话框Modal中，绑定标题:title="modal_title"，在data中，初始化modal_title=''；当调用方法显示对话框时，this.modal_title='添加xxx';this.modal1=true;不显示标题。

**Comment by icarusion** [comment]
按要求提问

**Comment by lvqingan** [comment]
@QiiSyhx
```javascript
if (this.$slots.header === undefined && !this.title) {
    showHead = false;
}
```
看源代码，如果title给的默认值是''后面就不会再显示Head了，所以即使再设置title也没有用，建议你可以随便初始化一个字符，譬如'/'，反正最后也是会被替换掉的

**Comment by icarusion** [comment]
#756
