### ISSUE TITLE
modal组件的动画效果能否支持属性指定而不是写死在组件里

### ISSUE THREAD

**Issue by chenxiaoqi01** [iview/iview#505]
### iView 版本号

2.0.0-rc.6

### 复现步骤
1 目前，modal组件里的动画效果只有淡入淡出
2 modal里template中transition的name能否供外部传入，默认为ease
<transition name="ease">

### 问题现象，以及你期望的结果是怎样的?
可以外部控制模态框出现与消失的动画效果 如 move-up  move-down move-left move-right 等

**Comment by suwonder9** [comment]
我们也希望modal可以外部传入动画效果，因为我们会基于iview的Modal进一步封装符合我们业务需求的组件，比如侧边模态框，但是侧边模态框应该是从侧边弹出的效果，可是现在iview并不支持外部指定效果。无奈只能先这么用着，希望作者能把动画效果放Modal的属性指定，非常感谢。

**Comment by vongo21** [comment]
非常需要这个功能，aside在某些场景下会比modal的试用好一点，无奈现在只能根据modal改装了一个淡入淡出的aside，而不是抽屉式的

**Comment by xiaoyyang123** [comment]
为什么不借助于已有的iview组件自己实现个aside呢，https://codepen.io/xiaoyyang/pen/GWYwyv

**Comment by rijn** [comment]
@icarusion maybe it's better to leave transition property to users?

**Comment by icarusion** [comment]
add prop `transition-names` to Modal.

**Comment by killergxm** [comment]
@icarusion how many types of the transition-names,There is no description in the document

**Comment by Cindy883008** [comment]
怎么实现modal对话框  自定义背景图片 可以外部控制模态框出现与消失的动画效果 如 move-up move-down move-left move-right 等
