### ISSUE TITLE
Can [Feature Request] tree components add a tiled style?


### ISSUE THREAD

**Issue by everhopingandwaiting** [iview/iview#5061]
### What problem does this feature solve?
方便做文件列表管理的操作
tr : ` manager the  files list `

### What does the proposed API look like?
  ```
<Tree type="flat" > </Tree>
```
![tree](https://user-images.githubusercontent.com/6021724/50369954-d66c3000-05d8-11e9-9035-f5c6b8c676cd.png)

**Comment by icarusion** [comment]
No such plan
