### ISSUE TITLE
[Bug Report]Select remote-search Bug

### ISSUE THREAD

**Issue by mr-ray-ai** [iview/iview#5063]
### Environment
win10 Chrome 70  vue 2.5.10

### Reproduction link
[https://run.iviewui.com/cnmrcaSl](https://run.iviewui.com/cnmrcaSl)

### Steps to reproduce
输入L(模拟根据code进行的模糊搜索)  

### What is expected?
可不可以添加一个取消过滤

### What is actually happening?
搜索拿到数据后本地的filterable又根据id和name进行了一次过滤， 导致options无法显示

**Comment by iizhangchao** [comment]
楼主 有解决这个问题么？ @1124219777  我也遇到这个问题

**Comment by mr-ray-ai** [comment]
> 楼主 有解决这个问题么？ @1124219777 我也遇到这个问题

我是单独把写了一个组件，把他远程搜索的功能抽出来用的。。。

**Comment by iizhangchao** [comment]
@1124219777  谢谢，好像暂时只能这样

**Comment by FAKER-A** [comment]
https://run.iviewui.com/WVy0F6rL
曲线救国
