### ISSUE TITLE
When [Bug Report] Select uses Option Group grouping, the V-model value shows undefined


### ISSUE THREAD

**Issue by xiaoxmok** [iview/iview#5073]
### Environment
win10/chrome71.0/vue 2.2.6

### Reproduction link
[https://run.iviewui.com/](https://run.iviewui.com/)

### Steps to reproduce
Select使用OptionGroup分组时，v-model值显示undefined，需要使用:value才行。

### What is expected?
v-model应该能显示当前选中值

### What is actually happening?
v-model没有显示当前选中值

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/57bd5393c55e6f0101e8a2f92b5ae2dff9228ce2
