### ISSUE TITLE
关于menu组件的一个bug

### ISSUE THREAD

**Issue by benaheng** [iview/iview#508]
### 能够复现问题的在线示例（重要）
http://runjs.cn/code/znz4dsxp

### 问题现象，以及你期望的结果是怎样的?

menu参数 active-name="1" 按理说这个值是个数值类型

但是在 
```
items: [
                { id:1,text: '系统' },
                { id:2,text: '内容' }
            ] 
```
中,id也是数值,但是却无法高亮id为1的菜单

如果改成

```
items: [
                { id:"1",text: '系统' },
                { id:"2",text: '内容' }
            ] 
```
就正常了,我觉得active-name和name都该强制转换成字符串.

**Comment by icarusion** [comment]
你该好好补补基础知识了。去看 Vue 文档吧。
