### ISSUE TITLE
[Bug Report] Select In remote search mode, after selecting the item, re-enter the search term, and the option disappears


### ISSUE THREAD

**Issue by icarusion** [iview/iview#5087]
### Environment
iView 3.2.1

### Reproduction link
[https://run.iviewui.com/fMCkKMwa](https://run.iviewui.com/fMCkKMwa)

### Steps to reproduce
1. 输入c，选择一项
2. 再重新键入搜索词，失焦
3. 选项消失

### What is expected?
选项还原

### What is actually happening?
选项消失

---
由 iView 3.2.0 更新后出现的问题

**Comment by JaresZhao** [comment]
Vue.js 2.6.8 + iView 3.2.2 问题依旧存在，建议再次打开这个issue
