### ISSUE TITLE
V-model fails when [Bug Report] asynchronously updates Option of Select components


### ISSUE THREAD

**Issue by feymanlee** [iview/iview#5090]
### Environment
mac os / chrome 72.0.3626.28 / vue 2.5.21

### Reproduction link
[https://run.iviewui.com/bXp3nMBD](https://run.iviewui.com/bXp3nMBD)

### Steps to reproduce
直接运行重现代码即可重现

### What is expected?
v-model 绑定生效

### What is actually happening?
v-model 绑定未生效

**Comment by HungryBird** [comment]
我用了的是最新的版本，但是还是没用...
替换了iview.js还是没用啊

**Comment by woniu3821** [comment]
目前使用的是3.2.2版本，Select用v-for渲染的option列表，验证通过不了
