### ISSUE TITLE
[Bug Report]Select Remote Search Selection Box, Delete Selection Data and Input Unmatched Data to Automatically Display Original Data


### ISSUE THREAD

**Issue by teaxia** [iview/iview#5096]
### Environment
vue 2.5.21

### Reproduction link
[https://www.iviewui.com/components/select#KQK](https://www.iviewui.com/components/select#KQK)

### Steps to reproduce
增加可搜索或远程搜索
选择一个已有选项
删除已有选项进行自定义搜索

### What is expected?
出现用户输入的内容，就算是无匹配数据也是如此

### What is actually happening?
可搜索表现行为：
删除字符没有问题，但是全部删除或者输入自定义字符时，点击空白区域，会自动出现刚刚选择的内容
远程搜索表现行为：
无法删除字符，会自动跳到刚刚选择的内容

---
其实有很多业务逻辑是搜索不到进行增加的。在不选择数据之前直接进行搜索没有问题，不过在先选择数据，然后再进行删除数据搜索就会有问题了

**Comment by teaxia** [comment]
在补充一下
单选加入了clearable可清空以后，确实是可以删除字符串操作的。不过当字符串全部删除或者输入的字符串无匹配时，还是会出现刚刚选择的内容。

**Comment by icarusion** [comment]
#5087
