### ISSUE TITLE
RadioGroup选中错误

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#510]
iview使用方式为非 template/render 模式下
### iView 版本号
2.4.0

### 操作系统/浏览器 版本号
windows7/Chrome 56.0.2924.87

### Vue 版本号
2.2.4

### 复现步骤
HTML代码：
`<Radio-group v-model="searchForm.timestamp" type="button">
                            <Radio label="">不限</Radio>
                            <Radio label="today">今天</Radio>
                            <Radio label="yestoday">昨日</Radio>
                        </Radio-group>`

### 问题现象，以及你期望的结果是怎样的?
radio中有空值时，选择其他选项后，在点击空值选项，会同时选中2个(空值选项以及上一个选择的项目)。

**Comment by icarusion** [comment]
不能为空
