### ISSUE TITLE
[Bug Report] Tree takes too long to update when use render function

### ISSUE THREAD

**Issue by CherishIt** [iview/iview#5101]
### Environment
macOS/Chrome/latest

### Reproduction link
[https://jsfiddle.net/nzrbLxj9/2/](https://jsfiddle.net/nzrbLxj9/2/)

### Steps to reproduce
- When using render func on Tree, it easily becomes laggy.
- Open the jsfiddle link and interact with the tree, it takes several seconds to update.
- When not using render function, it works fine.

### What is expected?
Performance of Tree with large dataset and render func should be improved

### What is actually happening?
Bad performance

**Comment by icarusion** [comment]
you'd better use async load data
