### ISSUE TITLE
[Bug Report] Two questions about the position of the modal box

### ISSUE THREAD

**Issue by fayonline** [iview/iview#5104]
### Environment
macOS Mojave 10.14.2/chrome 71.0.3578.98（正式版本）（64 )/ iview 3.2.1

### Reproduction link
[https://run.iviewui.com/eAoAtxWn](https://run.iviewui.com/GkSdshwO)

### Steps to reproduce
Q1: Drag the mode box to the edge of the browser display area until it is fully covered.
Q2: Close a modal box that has been adjusted, and then open the modal box.

### What is expected?
1. The modal box cannot be dragged beyond the top edge of the screen, and the left, right, and bottom portions can be partially exceeded, but ensure that the header section of the modal box retains a portion of the visible area.
2. Close a modal box that has been adjusted, and then open the modal box, I want the position of the modal box to return to the default position.

### What is actually happening?
1.The modal box can be dragged to the edge of the browser display area until it is covered, but it can't be dragged out again.
2.Close a modal box that has been adjusted, and then open the modal box, the modal box is still in the last set position.

**Comment by zhimng** [comment]
我想很多人都遇到了这个问题，可拖拽部分拖出浏览器可视范围之外确实不是很多人想要的功能，比起自己封装，iview解决了不是更好吗 我应该 at 谁 @icarusion ??
