### ISSUE TITLE
[Bug Report] iView Developer Developer Community is not logged in


### ISSUE THREAD

**Issue by lIAn0110** [iview/iview#5107]
### Environment
windows7, chrome 71.0.3578.98

### Reproduction link
[https://dev.iviewui.com/signin](https://dev.iviewui.com/signin)

### Steps to reproduce
输入正确的账号和密码无法登录

### What is expected?
登录成功

### What is actually happening?
登录失败, 返回错误信息

---
MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

**Comment by icarusion** [comment]
已修复
