### ISSUE TITLE
iView 文档迁移服务器，临时访问地址

### ISSUE THREAD

**Issue by icarusion** [iview/iview#5118]
iView 文档等所有服务正在迁移服务器，请先访问文档临时地址：
http://v3.iviewui.com/ 

迁移成功后恢复 www.iviewui.com、iviewui.com、dev.iviewui.com、run.iviewui.com 的服务，并做通知。

**Comment by lIAn0110** [comment]
原来如此~

**Comment by YJMQN** [comment]
我还以为是服务器崩了呢，吓我一跳

**Comment by wangfpp** [comment]
吓我一跳　　查文档都进不去了

**Comment by 495640129** [comment]
我以为代码有彩蛋，在处理呢。。。

**Comment by icarusion** [comment]
目前
https://www.iviewui.com/ 
https://iviewui.com/
已恢复正常
dev.iviewui.com、run.iviewui.com 正在恢复

**Comment by icarusion** [comment]
全部服务已恢复正常
