### ISSUE TITLE
[Feature Request]使用this.$Modal（Modal instance） config配置中增加z-index参数

### ISSUE THREAD

**Issue by zagang** [iview/iview#5121]
### What problem does this feature solve?
使用this.$Modal.info(config)此类功能时 Modal打开应当显示在最外层。有时Modal会从其他Modal中打开，有时会从Pop tip或者其他途径打开，
例如从poptip中打开的时候，z-index计算会使Modal显示在poptip之后，
建议增加z-index字段，手动设置显示层级

### What does the proposed API look like?
参考之前的即可

**Comment by icarusion** [comment]
No such plan
