### ISSUE TITLE
[Feature Request]The label attribute in the Cascader component contains HTML tags, which are not rendered as HTML tags, but rendered as strings.

### ISSUE THREAD

**Issue by tianlang89757** [iview/iview#5123]
### What problem does this feature solve?
The label attribute in the Cascader component contains an HTML tag that can be rendered correctly as HTML instead of a string, in order to search using the acronym given in the label if the search name is too long. For example: traffic alert <span id='d0000'>ta</span>, span tag transparent display through css

### What does the proposed API look like?
HTML rendering or String rendering through configuration options in Cascader component

**Comment by tianlang89757** [comment]
![Uploading image.png…]()

**Comment by icarusion** [comment]
No such plan

**Comment by BeatMercy** [comment]
I have met same problem with you, and not solved.....
There is a code snippet in cascader.vue(version: 3.2.2)
```
 <div :class="[prefixCls + '-dropdown']" v-show="filterable && query !== '' && querySelections.length">
                        <ul :class="[selectPrefixCls + '-dropdown-list']">
                            <li
                                :class="[selectPrefixCls + '-item', {
                                    [selectPrefixCls + '-item-disabled']: item.disabled
                                }]"
                                v-for="(item, index) in querySelections"
                                @click="handleSelectItem(index)" v-html="item.display"></li>
                        </ul>
 </div>
```

As we can see, 'v-html' is bind to the 'item.display'(which is assigned with 'data.label')
but " v-show="filterable && query !== '' && querySelections.length" turn out that, 
iview do support the feature, but only implement to query search.(￣_￣|||)
