### ISSUE TITLE
建议select组件可返回object

### ISSUE THREAD

**Issue by qq447665722** [iview/iview#513]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
Chrome 56 

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）
建议select组件可返回object.情景需求选择数据时,返回对象供其它组件使用,但不post数据,即使post数据也可重新组装数据

### 复现步骤
![image](https://cloud.githubusercontent.com/assets/14967427/24385054/768c827a-139a-11e7-9939-dc657375b9d4.png)

### 问题现象，以及你期望的结果是怎样的?
select组件value属性可设置/返回为对象

**Comment by rijn** [comment]
It's hard to make it filterable if `value` is an object. Maybe we can add a `filter-key` when user passing an object to `value`.

Before we make a patch, I suggest you first create a key-value map in this problem, and pass key to `value`, name in value to `label`.

**Comment by icarusion** [comment]
I think it is not an universal scene. Maybe you can change you data like `product.id`.

**Comment by youblade** [comment]
很多场景下需要select返回object，如果只能返回value 实在太不灵活了
ps：
1、很多第三方select组件 如vue-multiselect、vue-select2等都支持返回object
2、react下一个著名的UI框架 ant （https://ant.design/index-cn）的select 组件也支持返回object

**Comment by WoolenWang** [comment]
支持一下object的吧,确实有这个需求，不支持的话，就要每个地方都要根据ID来找一个数组内的对象。
蛋疼死了啊

**Comment by WoolenWang** [comment]
> I think it is not an universal scene. Maybe you can change you data like `product.id`.

支持一下object的吧,确实有这个需求，不支持的话，就要每个地方都要根据ID来找一个数组内的对象。
蛋疼死了啊
