### ISSUE TITLE
[Bug Report]format attribute in upload component doesn't work

### ISSUE THREAD

**Issue by TonyLuo** [iview/iview#5130]
### Environment
MacOS/chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Reproduction link
[https://jsfiddle.net/cfr4bhL7/](https://jsfiddle.net/cfr4bhL7/)

### Steps to reproduce
https://jsfiddle.net/cfr4bhL7/

### What is expected?
upload should filter the file type by format attribute 

### What is actually happening?
upload doesn't filter the file type by format attribute

**Comment by misakamayako** [comment]
it works will with your options,if you mean can't select it in selector,you should use prop 'accept ';

**Comment by TonyLuo** [comment]
it should filter the files which extension not in format array, but now it will show all files without filtering.

**Comment by Deadpool957** [comment]
Has the problem been solved?

**Comment by Deadpool957** [comment]
> ### Environment
> MacOS/chrome Version 71.0.3578.98 (Official Build) (64-bit)
> 
> ### Reproduction link
> https://jsfiddle.net/cfr4bhL7/
> 
> ### Steps to reproduce
> https://jsfiddle.net/cfr4bhL7/
> 
> ### What is expected?
> upload should filter the file type by format attribute
> 
> ### What is actually happening?
> upload doesn't filter the file type by format attribute
