### ISSUE TITLE
[Bug Report] Cell jump path cannot resolve vue-router objects


### ISSUE THREAD

**Issue by cnwanyan** [iview/iview#5131]
### Environment
Win10 Chrome71

### Reproduction link
[https://run.iviewui.com/KX2tyYh6](https://run.iviewui.com/KX2tyYh6)

### Steps to reproduce
点击cell

### What is expected?
cell支持vue-router对象并进行正确的跳转

### What is actually happening?
cell 似乎不支持vue-router对象，而文档上写的是支持

**Comment by icarusion** [comment]
to 绑定 Object 时，不能使用 target
