### ISSUE TITLE
[Feature Request] DatePicker time selector adds time selection window restrictions


### ISSUE THREAD

**Issue by psc0606** [iview/iview#5139]
### What problem does this feature solve?
实际使用DatePicker通常包含起始时间和结束时间，默认对输入的起始时间和结束没有限制，用户选择的时间范围可能会很长，导致后端查询压力比较大。需要DatePicker提供类似移动的时间窗口的概念来限制起始和结束时间，用户可选择任意的时间，但时间范围总是受限。

### What does the proposed API look like?
例如dateTimeRange=2d, dateTimeRange=2h等等

**Comment by icarusion** [comment]
No such plan
