### ISSUE TITLE
Menu下拉菜单缓慢展开子菜单

### ISSUE THREAD

**Issue by pengpan** [iview/iview#514]
提个建议
目前使用的Menu菜单展开子菜单，不是稍缓慢展开二十直接展开；这种效果不好看啊

**Comment by pengpan** [comment]
看了下源码，在submenu.vue 文件是用  v-show="opened“ 来控制的啊。这个。。菜单上下没滑动效果啊，求楼主解决；

**Comment by pengpan** [comment]
看到楼主标记了，坐等优化哈。我先这样用着，等优化了再升级；感谢楼主

**Comment by Dinrer** [comment]
通过v-for生成的菜单无法手动展开:open-names属性无效，望解决！
