### ISSUE TITLE
[Bug Report]Select radio remote search matches backspace bug, cannot delete input content


### ISSUE THREAD

**Issue by DongZhouJone** [iview/iview#5142]
### Environment
windows x64,  Chrome 70.0.3538.102, Vue 2.5.7

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
输入关键字a, 选择单个内容，然后删除该单选项，backspace退格无效。 开发环境是正常的，只有切到生成环境才会发生

### What is expected?
期望可以删除单选后的结果，

### What is actually happening?
无法删除，只能通过添加 clearable 属性实现删除

**Comment by icarusion** [comment]
#5087
