### ISSUE TITLE
打包到生产环境时， woff 字体引用问题

### ISSUE THREAD

**Issue by malaimoo** [iview/iview#515]
### iView 版本号
2.0.0-rc.6 

### 操作系统/浏览器 版本号
- macOS/Chrome 57

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?

使用 vue build 之后做网站请求，发现 woff 字体无法获取，调试发现：

真实路径应该是
http://keliupc.mncats365.com/static/fonts/ionicons.05acfdb.woff
浏览器实际加载路径为：
http://keliupc.mncats365.com/static/css/static/fonts/ionicons.05acfdb.woff

导致 woff 字体获取不到。

### 你估计可能的原因是什么（选填）？
我看了下打包完的 css 文件是这样的，

```
url(static/fonts/ionicons.05acfdb.woff) format("woff"),
```
是相对路径，css 所在路径是 /static/css/ 。而加上上面的相对路径，就变成了/static/css/ + static/fonts/ionicons.05acfdb.woff = /static/css/static/fonts/ionicons.05acfdb.woff 导致加载错误。我现在都是手动改的，请问有没有方法解决一下这个问题？

**Comment by icarusion** [comment]
这是你配置问题吧，跟 iView 无关。

**Comment by malaimoo** [comment]
用的 vue-cli 的脚手架，应该是脚手架的 webpack 配置有点问题。Thanks！

**Comment by JuZiSang** [comment]
我用`vue-cli`也遇到这个问题，现在也是手动解决的...有什么其他方法吗？

**Comment by malaimoo** [comment]
@JuZiSang 
在 build/webpack.prod.conf.js 中
```
  module: {
    rules: utils.styleLoaders({
      sourceMap: config.build.productionSourceMap,
      extract: false
    })
  },
```
extract :true 改为 fasle

**Comment by JuZiSang** [comment]
解决了，感谢

**Comment by hegoku** [comment]
@malaimoo 666

**Comment by Tilang** [comment]
@malaimoo 666，字体这个解决了。但是背景图片路径也有问题。`background:url(static/img/login.63c597e.jpg) no-repeat top/1920px 600px`
缺了dist这一层

**Comment by malaimoo** [comment]
@Tilang 不需要 dist 啊，dist 是打包之后的根目录。把 dist 里面的放到服务器目录就行了。

**Comment by 497955191** [comment]
图标路径不对，这么修改配置

**Comment by jiewangzi** [comment]
厉害    解决了

**Comment by jeneser** [comment]
版本信息：
```
{
    "webpack": "^2.3.3",
    "iview": "^2.0.0-rc.12"
}
```
在webpack2中可以配置`publicPath `来解决。如下：

`/build/utils.js`

```
// Extract CSS when that option is specified
// (which is the case during production build)
if (options.extract) {
    return ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader',
        publicPath: '../../'
    });
} else {
    return ['vue-style-loader'].concat(loaders);
}
```

**Comment by long369486562** [comment]
已经解决，不是IVIEW的问题  ，我更改了生产打包 公共资源路径    造成的   ，，更改公共资源路径必须使用绝对路径。。。

**Comment by luo772435545** [comment]
这个问题还是会存在的，比如在vue多页面，但是我页面处于不同文件夹，建议把字体路径根据js引入

**Comment by erwer8363** [comment]
已经解决，感谢
