### ISSUE TITLE
[Bug Report]Cascader Selected content overrides Icon

### ISSUE THREAD

**Issue by zengkun** [iview/iview#5153]
### Environment
mac 10.13.3 / chrome 71.0.3578.98 / vue 2.5.17

### Reproduction link
[https://run.iviewui.com/8RddYg89](https://run.iviewui.com/8RddYg89)

### Steps to reproduce
The width of the selected content exceeds the component width.

### What is expected?
Choose content that does not cover Icon.

### What is actually happening?
Overlay icon for too long selection.

**Comment by zengkun** [comment]
The same problem exists with multiple selection options for Select components.

**Comment by yangdan8** [comment]
#5159

**Comment by icarusion** [comment]
@zengkun Select 多选已在 #4938 解决。
