### ISSUE TITLE
[Bug Report]Select when set filterable, input keyword, leave the focus, and the value is empty

### ISSUE THREAD

**Issue by ptlinyi** [iview/iview#5155]
### Environment
any

### Reproduction link
[https://run.iviewui.com/80aAVDuN](https://run.iviewui.com/80aAVDuN)

### Steps to reproduce
Manually enter "Londo" in the drop-down box, then don't select the drop-down item, and click on the other blanks with the mouse. Now the user seems to think he has chosen the right value, but in fact it is not. This causes a lot of trouble for the end user.

手动在下拉框中输入“Londo”，然后不要选择下拉项目，鼠标点击其他空白处，现在用户看起来以为是选择了正确的值，实际上不是，这在终端用户造成很大的困扰

### What is expected?
如果用户手动输入完全匹配，则失去焦点时自动选择项目值，如果用户输入不完全匹配，失去焦点时显示为空

### What is actually happening?
现在失去焦点时还是保留用户手动输入的内容，但实际上又不是

---
我知道正确的操作方式是什么，但那些小白用户不知道，也不可能找到并教他们怎么正确使用，希望能改成用户心理预想的那样

**Comment by yangdan8** [comment]
添加blur事件清除输入的值好了，需要修改iview源码

**Comment by zhangfan99** [comment]
可以监听on-open-change事件来代替监听blur事件

**Comment by Daniel-yim** [comment]
切换到v3.4.1的时候发现了这个，其实我们有个业务刚好就是要使用这个的。

使用场景：
使用Select组件进行Tag多选，由于数据量太大，所以需要进行关键词筛选Tag标签。

历史实现：
由于Select组件在失去焦点后会保留用户的输入值，通过@on-query-change可以获取到用户的输入值，然后由用户通过Button来触发搜索，回显Options。

新版本后失去焦点，去点击Button的时候，就清空了输入。

修改方式：
修改交互方式，不用点击Button触发搜索，直接在@on-query-change中实现搜索。

是这样使用的么？或者还有其他好的方式么？谢谢啦！
