### ISSUE TITLE
[Bug Report] Form form returned and submitted directly


### ISSUE THREAD

**Issue by tjpulwy** [iview/iview#5162]
### Environment
Vue2.5.2

### Reproduction link
[https://www.iviewui.com](https://www.iviewui.com)

### Steps to reproduce
使用Form组件，提交按钮使用Button，输入表单项后直接回车，表单会直接提交到当前页面并刷新当前页，所有验证也不起作用

### What is expected?
回车直接异步提交

### What is actually happening?
回车表单直接提交到当前页

**Comment by brugnara** [comment]
@tjpulwy maybe you missed the doc where they say to use: `@submit.native.prevent`. Hope this helps.

![image](https://user-images.githubusercontent.com/2781191/50883891-aa7ae800-13e9-11e9-9224-c9f4e12d2ba1.png)
