### ISSUE TITLE
[Bug Report] i-view input box error 

### ISSUE THREAD

**Issue by k3341095** [iview/iview#5164]
### Environment
windows 10 / chrome / iview 3.2.1

### Reproduction link
[https://youtu.be/AOGxKkJIaQI](https://youtu.be/AOGxKkJIaQI)

### Steps to reproduce
i'm korean 
In the input box, you entered 강서구
but vue dev tool only 강서

And as you can see from the video
Other numeric values will not work properly after an error.
Only after you write another letter and erase it again.
Start operation.

Copy paste works normally.

### What is expected?
search error 

### What is actually happening?
search error

**Comment by k3341095** [comment]
https://vuejs.org/v2/guide/forms.html#vmodel-ime-tip

Sorry..
iview's not a problem with vue.js
I think it's a whole problem.
Can you fix it at ivieiw?

**Comment by icarusion** [comment]
in iView version 3.2.1, we update Input experience, maybe you should not use `v-model`, instead of `:value` and `@input`.

**Comment by k3341095** [comment]
<Input :value="order.d_message" @input="test2 = $event" />

I tried.
However, the same problem occurs.
