### ISSUE TITLE
[Bug Report] input box will automatically trigger on-enter event when it returns in the state of Chinese input method in Firefox Browser


### ISSUE THREAD

**Issue by zhanan** [iview/iview#5165]
### Environment
操作系统：win10 / 浏览器版本：63.0 / iview版本：3.2.1

### Reproduction link
[https://run.iviewui.com/wMQIrHFr](https://run.iviewui.com/wMQIrHFr)

### Steps to reproduce
火狐浏览器下，打开链接：https://run.iviewui.com/wMQIrHFr，在input文本框绑定on-enter事件，中文输入法状态下回车会触发on-enter事件。

### What is expected?
期望在中文输入法状态下，回车仅仅是将文本输入到文本框，而不要同时触发on-enter事件，

### What is actually happening?
实际中文输入法状态回车也会自动触发on-enter事件，此现象在登入操作时很不友好，如用户本意想输入验证码但是自动触发回车校验功能十分不友好。

---
google浏览器没有此问题，即中文输入法状态回车仅仅是将文本输入到文本框，而不会同时触发回车事件。

**Comment by icarusion** [comment]
No support
