### ISSUE TITLE
[Bug Report] When using Table to fix the column header,  some non-fixed column headers are too long and no data will be strange in style.

### ISSUE THREAD

**Issue by CaanDoll** [iview/iview#5174]
### Environment
win10 / chrome71 / 2.x

### Reproduction link
[https://run.iviewui.com/ghJ85Kj4](https://run.iviewui.com/ghJ85Kj4)

### Steps to reproduce
Fixed column header, some  non-fixed column headers are long, no data

### What is expected?
Have data consistent with no data style

### What is actually happening?
Inconsistent

---
This is when there is data：https://run.iviewui.com/PWdtpA7f

**Comment by icarusion** [comment]
The correct commit record is:
https://github.com/iview/iview/commit/5c6902379556a6ddb104689e6d4b0191e98f6f60
