### ISSUE TITLE
[Bug Report] select uses the clearable attribute to exceptionally select options when querying remotely


### ISSUE THREAD

**Issue by Gyyi** [iview/iview#5177]
### Environment
chrome 71

### Reproduction link
[https://run.iviewui.com/00zI6I5h](https://run.iviewui.com/00zI6I5h)

### Steps to reproduce
1、输入 c ，并选中 canberra 选项
2、使用clearble提供的删除按钮，删除选中
3、重新点击select，查看下拉选项

### What is expected?
删除已选之后， 下拉选项正常显示

### What is actually happening?
选项只剩下之前被选中的那一个

---
希望未输入关键字时，点击select，也能发起远程请求

**Comment by shizhenbin** [comment]
增加个clear的回调，调用reset（）

**Comment by Gyyi** [comment]
增加clear回调后，问题依然存在。

https://run.iviewui.com/LyNlFAdl

**Comment by Restarnow** [comment]
我知道错了.成熟些就好了。一时冲动 对不起。

**Comment by Restarnow** [comment]
能够加回你 跟你说些话吗。我全部都听你的，因为我是真的很喜欢你

**Comment by Restarnow** [comment]
感觉。还是面对面的好，微信聊很多语气都变了 也容易上头没止住，意思都曲解了。人跟人能认识真的很缘分，有过错认错我才不会如果明天就世界末日，后悔都来不及。

**Comment by Restarnow** [comment]
希望你能看到。这段时间思考了下，我确实有时过于敏感，感觉性格存在很大的矛盾性，一旦否定了自我就容易极端 会攻击别人，感觉自己跟世界格格不入，然后陷在自己的死胡同里。最近深度的剖析自己，全面否定了自己，性格有时候存在很大的问题，但是我对你的喜欢是真心的。或许我大可不必去乱想那么多，顺其自然，忙该忙的事。
