### ISSUE TITLE
[Bug Report] select remote search


### ISSUE THREAD

**Issue by MrtianYs** [iview/iview#5181]
### Environment
windows/chrome71/vue2.5

### Reproduction link
[https://run.iviewui.com/MRhYpdEx](https://run.iviewui.com/MRhYpdEx)

### Steps to reproduce
搜索出内容选中选项，按住backspace，无法删除内容

### What is expected?
删除内容

### What is actually happening?
无法删除内容，内容重新填充

**Comment by icarusion** [comment]
#5087
