### ISSUE TITLE
[Bug Report] Replaces the Option array rendered with v-for, and the value of the V-model of Select is cleared


### ISSUE THREAD

**Issue by HungryBird** [iview/iview#5186]
### Environment
win10

### Reproduction link
[https://run.iviewui.com/OknuXkN2](https://run.iviewui.com/OknuXkN2)

### Steps to reproduce
替换用v-for渲染的Option的数组，Select的v-model会被清空

### What is expected?
Select的v-model不被清空

### What is actually happening?
Select的v-model被清空

**Comment by icarusion** [comment]
#5090
