### ISSUE TITLE
请问表格如何做到【不换行】并【不显示省略号】？

### ISSUE THREAD

**Issue by wingofsky** [iview/iview#519]
有很多业务会出现：
1、在一个单元格内有多行的情况（多行情况下无法做到一目十行）
2、业务部门希望直接在页面内将整行内容复制（所以需要不换行，又不显示省略号）

然鹅。。。renderHeader搞不定。。。。求解

**Comment by rijn** [comment]
覆盖CSS

**Comment by wingofsky** [comment]
好吧。。。。。
