### ISSUE TITLE
[Bug Report] drop-down selection component Select on-change method returns undefined


### ISSUE THREAD

**Issue by Llixuanjin** [iview/iview#5200]
### Environment
window10 / chrome最新版/ vue最新版

### Reproduction link
[https://run.iviewui.com/preview/qedPhHse](https://run.iviewui.com/preview/qedPhHse)

### Steps to reproduce
选择器组件，异步改变Options列表， 然后 重新给v-modal绑定的数据默认值，然后触发了on-change方法，on-change方法返回undefined，不能正确获取到默认值

### What is expected?
给默认值后，触发的on-change方法返回正确的值

### What is actually happening?
实际返回undefined

**Comment by icarusion** [comment]
#5090
