### ISSUE TITLE
[Feature Request] tree increases the semi-selected state


### ISSUE THREAD

**Issue by mark0325** [iview/iview#5202]
### What problem does this feature solve?
在父子严格模式下，多个子级中只有一部选中，此时父级是半选中种状态，当数据再次回显时，无法给父级设置半选中状态，只能设置为选中，这样会导致所有子级 全部选中，如果使用父子非严格，导致用户要勾选多次

### What does the proposed API look like?
checked  增加半选中状态

**Comment by icarusion** [comment]
No such plan now.
