### ISSUE TITLE
部分表单字段校验的回调返回值不是 Boolean

### ISSUE THREAD

**Issue by xiaoyyang123** [iview/iview#521]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
 macOS/Chrome 56 

### Vue 版本号
 2.2.1

### 能够复现问题的在线示例（重要）
https://codepen.io/xiaoyyang/pen/xqaNaN?editors=1111

### 复现步骤
点击确定按钮，控制台打出的是错误信息，而不是布尔值

### 问题现象，以及你期望的结果是怎样的?
文档上写的回调应该是布尔值

**Comment by icarusion** [comment]
这部分文档没有写清楚，validate 返回的是 Boolean，validateField 返回的是错误信息，如果没有错，返回空字符串。
