### ISSUE TITLE
[Feature Request] I hope Modal's instance usage can add footerHide attributes. [I hope that the instance usage of Modal can add the footerHide attribute.]


### ISSUE THREAD

**Issue by yiwen22591** [iview/iview#5210]
### What problem does this feature solve?
方便隐藏Modal的页脚[Convenient to hide the footer of Modal ]

### What does the proposed API look like?
Modal 实例的config添加footerHide属性。[Modal instance config adds footerHide attribute]
eg:
`this.$Modal.info({
    footerHide: true
});`

**Comment by icarusion** [comment]
No such plan
