### ISSUE TITLE
[Bug Report] Select bugs in both Option Group and filter cases


### ISSUE THREAD

**Issue by JackLiuInNC** [iview/iview#5216]
### Environment
最新vue和iview

### Reproduction link
[https://run.iviewui.com/XvEGqsdh](https://run.iviewui.com/XvEGqsdh)

### Steps to reproduce
Select在OptionGroup和filterable同时都有的情况下的，在选择了某一个下拉项之后，再进行下拉选择时，其他的下拉项都进行了过滤。

### What is expected?
未进行过滤输入，只是进行下拉选择，在再次展开下拉框时应该展现所有的下拉项。

### What is actually happening?
只展现了上次选择的一个下拉框，其他下拉项都被过滤了

---
Select在OptionGroup和filterable同时都有的情况下

**Comment by JackLiuInNC** [comment]
@icarusion

**Comment by cismous** [comment]
遇到同样的问题，期待修复!

**Comment by shizhenbin** [comment]
这个问出现的原因是，当你点击下拉选项后，搜索框的搜索value变成了你选择选项对应的值，他会在触发过滤事件。 所以选项只剩下之前选中的那个了。 这边还有一个体验问题： 假如用户选择完之后如果用户还想根据之前的搜索条件过滤，这就没办法实现了， 因为之前搜索的值已经被改变了。
