### ISSUE TITLE
webpack环境tabel组件通过render生成的按钮找不到对应的函数

### ISSUE THREAD

**Issue by s51983** [iview/iview#522]
### iView 版本号
2.0.0-rc.7 

### 操作系统/浏览器 版本号
win10/Chrome 56

### Vue 版本号
2.2.6 + vue-router 2.3.0 + webpack 2.2.0

### 复现步骤
文档tabel组件“自定义列模板”中的代码原样复制到单个vue文件中未经任何修改，经过webpack打包后点击最后一列的按钮报错找不到函数(Uncaught ReferenceError: show is not defined)。

### 问题现象，以及你期望的结果是怎样的?
此问题在直接引用vue、iview文件不使用webpack、vue-router的时候一切正常。

**Comment by icarusion** [comment]
check your setting and code.
