### ISSUE TITLE
[Bug Report]If the search is turned on under the select control and there are multiple controls, there is a problem.

### ISSUE THREAD

**Issue by xzs333** [iview/iview#5221]
### Environment
latest version

### Reproduction link
[https://run.iviewui.com/jcW2sHyS](https://run.iviewui.com/jcW2sHyS)

### Steps to reproduce
The selected content will be centered, the first two options will be problematic, and the last one will be okay because of the problem caused by the change of the option tag line.

### What is expected?
Can solve this problem, or give hints

### What is actually happening?
Can solve this problem, or give hints

---
选中的内容会居中显示，前两个选择会出现问题，最后一个没有问题，原因是option标签换行所导致的问题

**Comment by djspys1** [comment]
Option部分写在一行就没这问题了
https://run.iviewui.com/rjSkFbnv

**Comment by xzs333** [comment]
> Option部分写在一行就没这问题了
> https://run.iviewui.com/rjSkFbnv

我当然知道了，你没有看到我说原因吗？？？处不处理无所谓，要不就加一个说明注释，不允许option换行

**Comment by djspys1** [comment]
> > Option部分写在一行就没这问题了
> > https://run.iviewui.com/rjSkFbnv
> 
> 我当然知道了，你没有看到我说原因吗？？？处不处理无所谓，要不就加一个说明注释，不允许option换行

看了这个组件的源码，如果我没理解错的话，这不是iview引起的，这是vue引起的，select最后显示的数据是vue实例上的textContent，拿到的时候就有空白符和二个像回车符一样的字符。
出现这个空白的话应该是vue的slot部分引起的，他不会处理换行空格
以上是我的推测
