### ISSUE TITLE
[Bug Report] Side menu bar will not be selected when loading


### ISSUE THREAD

**Issue by Avalongs** [iview/iview#5222]
### Environment
windows 7 谷歌浏览器 Vue版本2.5.2 iView版本3.2.1

### Reproduction link
[https://run.iviewui.com/kojRrBUr](https://run.iviewui.com/kojRrBUr)

### Steps to reproduce
进入页面应该默认打开查询并选中员工查询，但是他没有打开

### What is expected?
让他进页面之后默认打开查询并选中员工查询

### What is actually happening?
查询并没有打开

**Comment by djspys1** [comment]
先设置在手动更新
https://run.iviewui.com/q1UN5bxR
