### ISSUE TITLE
[Bug Report]The option of Select doesnt suitable for “transform：scale”

### ISSUE THREAD

**Issue by dwanda** [iview/iview#5238]
### Environment
window7、vue2.9.6

### Reproduction link
[https://jsfiddle.net/ex5ogdu0/2/](https://jsfiddle.net/ex5ogdu0/2/)

### Steps to reproduce
click Select Menu

### What is expected?
It can be ajust by transform:scale

### What is actually happening?
its left and top makes it offset

**Comment by icarusion** [comment]
Not support this usage
