### ISSUE TITLE
[Feature Request] table remotely filters too much data. It is recommended that drop-down loading components be nested in table filters


### ISSUE THREAD

**Issue by zhangtanlin** [iview/iview#5240]
### What problem does this feature solve?
解决了表格使用远程查询数据/筛选数据时下拉框加载速度过慢。

### What does the proposed API look like?
期望能够在iview的表格头部的筛选方法里面添加一个下拉加载的组件，并且在columns里面添加下拉加载调用方法。

**Comment by icarusion** [comment]
No such plan
