### ISSUE TITLE
[Bug Report] InputNumber Detection Maximum and Minimum Problem


### ISSUE THREAD

**Issue by yangdan8** [iview/iview#5243]
### Environment
IView3.2.2

### Reproduction link
[https://jsfiddle.net/6r1wcnL4/](https://jsfiddle.net/6r1wcnL4/)

### Steps to reproduce
打开链接,在输入框无法输入20

### What is expected?
能输入正确的值

### What is actually happening?
输入完第一个字符2后立即被改变为最小值10

**Comment by yangdan8** [comment]
#5244

**Comment by icarusion** [comment]
https://jsfiddle.net/qw6uadcv/

可以先用 `active-change` ，pr 之后我再 check 一下

**Comment by yangdan8** [comment]
那我这个使用的延时触发实现方式可以取消了,用这个active-change应该能满足需求
