### ISSUE TITLE
[Feature Request] Modal support does not display footer


### ISSUE THREAD

**Issue by ijry** [iview/iview#5246]
### What problem does this feature solve?
在一个modal里有多个自定义按钮需求，官方自带的2个不能满足业务需求。

### What does the proposed API look like?
其实modal的普通组件版本是支持的，只需要同样在js方法动态生成的this.$Modal.confirm里参数同样加一个footer-hide。
![f0f772e1-8ead-4964-85f3-25aa0d58eaf3](https://user-images.githubusercontent.com/3102798/51582243-34f13a80-1f06-11e9-9eb4-ac792c00550b.png)

**Comment by icarusion** [comment]
No such plan

**Comment by ijry** [comment]
no need a plan,just copy some code iview self will help much,I cannot do it myselfe because i cannot build ivew form source, it always shou error.

发自我的 iPhone
