### ISSUE TITLE
[Bug Report] tabs closed abnormally


### ISSUE THREAD

**Issue by hyphenhuang** [iview/iview#5247]
### Environment
win7,chorme最新版本,https://www.iviewui.com/components/tabs#KGB基于可关闭这个例子

### Reproduction link
[https://jsfiddle.net/prno0wzh/](https://jsfiddle.net/prno0wzh/)

### Steps to reproduce
tabs设置v-model，默认显示第二个页签，设置为可关闭，运行后，点击关闭标签一。结果标签二也被关闭了，且无法正常显示其他标签内容。

### What is expected?
正常关闭页签，然后能够显示前置的其它页签的内容。

### What is actually happening?
点击关闭标签一。结果标签二也被关闭了，且无法正常显示其他标签内容。

---
1、此现象在包装自定义控件，使用render渲染Tabs的时候，问题尤其严重。tab标签关闭后，标签页的内容还在，只是标题看不到而已，然后之前的第二个页签的内容就变成了第一个页签的内容
2、closable无法动态设置，看源码，没有对closable监视，在watch里添加监视就好了

**Comment by icarusion** [comment]
你的示例写错了，真是浪费时间...
https://run.iviewui.com/jDJDZNFP
