### ISSUE TITLE
引入ivew的样式，再打开cssModule就报错？

### ISSUE THREAD

**Issue by JohnnyWang-Github** [iview/iview#5252]
自己项目的字体文件引入正常，引入iview样式正常，iview的字体文件显示正常

打开cssModule，iview的字体文件就引用不到了，不引入iview的样式又好了

文件路径是正确的

css-loader、url-loader并没有设置 exclude: /node_modules/

![报错](https://pic3.zhimg.com/80/v2-cb36d90b6d7fb122fdf9ecb97db7af8a_hd.jpg)

**Comment by lengfeng1224** [comment]
This is my vue.config.js
module.exports = {
    // https://cli.vuejs.org/zh/config/#devserver-proxy
    productionSourceMap: true,
    css: {
        modules: false,
        loaderOptions: {
            less: {

                javascriptEnabled: true

            }
        }
    },
    runtimeCompiler: true
}

**Comment by lengfeng1224** [comment]
```javascript
module.exports = {
// https://cli.vuejs.org/zh/config/#devserver-proxy
productionSourceMap: true,
css: {
modules: false,
loaderOptions: {
less: {

            javascriptEnabled: true

        }
    }
},
runtimeCompiler: true
}
```

**Comment by lengfeng1224** [comment]
This is my vue.config.js
```javascript
module.exports = {
// https://cli.vuejs.org/zh/config/#devserver-proxy
productionSourceMap: true,
css: {
modules: false,
loaderOptions: {
less: {

            javascriptEnabled: true

        }
    }
},
runtimeCompiler: true
}
```
