### ISSUE TITLE
New manual trigger/poptip component adds manual trigger for [Feature Request] poptip component


### ISSUE THREAD

**Issue by songguoying** [iview/iview#5256]
### What problem does this feature solve?
当poptip的内容是动态加载时，会出现跳动，希望可以在内容加载完成后手动触发poptip组件。/
When the content of the poptip is dynamically loaded, there will be a beating, and it is hoped that the poptip component can be manually triggered after the content is loaded.

### What does the proposed API look like?
可以手动触发poptip。/I can manually trigger poptip.

**Comment by icarusion** [comment]
No such plan
