### ISSUE TITLE
[Bug Report]Dropdown in Table fixed column position display wrong

### ISSUE THREAD

**Issue by mahadoang** [iview/iview#5262]
### Environment
iview v. 3.2.2, chrome all version, Vue 2.x.x

### Reproduction link
[https://jsfiddle.net/Lszr0q21/2/](https://jsfiddle.net/Lszr0q21/2/)
[https://run.iviewui.com/o7lObBl8](https://run.iviewui.com/o7lObBl8)

### Steps to reproduce
1.set Table fix height
2.set first and second column fix left
3.second column render dropdown
4.scrolling the table and mouse over the Product ID

### What is expected?
show dropdown list nearby the row mouse over

### What is actually happening?
the dropdown list display wrong

**Comment by hongqiang12** [comment]
you should add transfer  attribute  in Dropdown

**Comment by mahadoang** [comment]
Thank you.
