### ISSUE TITLE
The tab in [Bug Report] tabs goes through the V-for loop, deletes the tab and adds the tab again, which results in tab confusion.


### ISSUE THREAD

**Issue by JustCK** [iview/iview#5266]
### Environment
windows7 64位操作系统 / chrome版本 71.0.3578.98（正式版本） （64 位）  /  Vue 2.5.16

### Reproduction link
[https://jsfiddle.net/janwardchen/udk2zhqw/1/](https://jsfiddle.net/janwardchen/udk2zhqw/1/)

### Steps to reproduce
使用v-for循环生成tab，删除中间某一两个tab，再新增tab，会出现tab错乱问题：会出现多个tab被同时选中的情况

### What is expected?
tabs中tab删除后，页面正常删除某个tab，新增tab后，tab的values属性对应正常，tab显示正常

### What is actually happening?
tab删除再新增后，tab的value有问题，样式上会出现多个tab同时被选中情况，且tab对应的下方的内容也同时出现

**Comment by guo897654050** [comment]
同,我也遇到了这个问题,tabs设置为card,关闭后再打开,内容会错误

**Comment by LaveyD** [comment]
可以不用tab自带的删除，利用`label`的渲染函数去实现删除
html:
```
<TabPane
              v-for="(data, idx) in datas"
              :key="data.id"
              :label="getLabel(idx)">
  ...
</TabPane>
```

js:
```
getLabel(idx) {
      return (h) => {
        return h('div', [
          h('span', `标签${idx + 1}`),
          h('Icon ', {
            type: 'md-close',
            on: {
              click: (e) => {
                e.stopPropagation();
                this.handleTabRemove(idx);
              },
            },
          }),
        ]);
      };
    },
handleTabRemove(idx) {
  this.datas.splice(idx, 1);
},
```

**Comment by guo897654050** [comment]
找到了个例子,如果用v-for的话,把key改变.
https://codepen.io/aaron0713/pen/ybEoeQ @JustCK

**Comment by JustCK** [comment]
> 找到了个例子,如果用v-for的话,把key改变.
> https://codepen.io/aaron0713/pen/ybEoeQ @JustCK

是的，我也找到了這個解決方法了，謝謝

**Comment by icarusion** [comment]
#5401
