### ISSUE TITLE
[Bug Report] Anchor Use Error Reporting


### ISSUE THREAD

**Issue by HandsomeHan515** [iview/iview#5270]
### Environment
Mac  Chrome74  vue.2.5.2

### Reproduction link
[https://run.iviewui.com/MazkhRBm](https://run.iviewui.com/MazkhRBm)

### Steps to reproduce
```js
<Anchor show-ink>
        <AnchorLink href="#basic_usage" title="Basic Usage" />
        <AnchorLink href="#static_position" title="Static Position" />
        <AnchorLink href="#API" title="API">
            <AnchorLink href="#Anchor_props" title="Anchor props" />
            <AnchorLink href="#Anchor_events" title="Anchor events" />
            <AnchorLink href="#AnchorLink_props" title="AnchorLink props" />
        </AnchorLink>
    </Anchor>
````
### What is expected?
正常使用

### What is actually happening?
不能使用，报错
TypeError: Cannot read property 'offset' of undefined
    at VueComponent.eval (iview.js?0536:4199)
    at Array.eval (vue.esm.js?efeb:1938)
    at flushCallbacks (vue.esm.js?efeb:1857)

**Comment by toryangchen** [comment]
出现同样的问题了, 题主有没有解决?
