### ISSUE TITLE
[Feature Request] TagInput tag input


### ISSUE THREAD

**Issue by daleizi** [iview/iview#5277]
### What problem does this feature solve?
让用户自定义

### What does the proposed API look like?
readonly	是否只读	Boolean	-	false
limit	限制输入的长度	Array	-	-
wordlimit	限制每个tag的文字输入长度	Number	-	50
placeholder	输入提示	String	-	-
type	数据类型	String	Array, String	Array
split	如果数据类型为String,设定的分隔符

**Comment by icarusion** [comment]
No such plan.
