### ISSUE TITLE
[Feature Request] Read-Only Form


### ISSUE THREAD

**Issue by daleizi** [iview/iview#5278]
![snipaste_2019-01-31_16-39-49](https://user-images.githubusercontent.com/19732051/52041972-e0d5fe00-2576-11e9-9d25-ad4cd1341228.png)
### What problem does this feature solve?
只是查看用并不需要编辑

### What does the proposed API look like?
readonly	显示只读文本

**Comment by icarusion** [comment]
No such plan.
