### ISSUE TITLE
[Bug Report] The result includes all options whose value or label matches the number when the select component filters numbers

### ISSUE THREAD

**Issue by zhilinYu** [iview/iview#5281]
### Environment
window/Chrome 68.0.3440.84/Vue 2.5.16

### Reproduction link
[https://run.iviewui.com/OQ2QTBnT](https://run.iviewui.com/OQ2QTBnT)

### Steps to reproduce
1,设置select组件的filterable属性
 set the filterable property of the select component

2,搜索一个数字，出来的结果中包含所有value或label中匹配该数字的项
search a number, the result contains the value and label to match the number of items

### What is expected?
搜索结果中只包含label中匹配该数字的项
includes all options whose label matches the number

### What is actually happening?
搜索结果中包含所有value或label中匹配该数字的项
includes all options whose  value or  label matches the number

**Comment by icarusion** [comment]
same issue exist

**Comment by xiaoxixi6633** [comment]
same issue  exist

**Comment by xiaoxixi6633** [comment]
> @chuchencheng 看不懂你的答案
