### ISSUE TITLE
[Bug Report] Loop option cannot be detected by validator


### ISSUE THREAD

**Issue by a1245582339** [iview/iview#5286]
### Environment
win10，所有浏览器，vue2.6

### Reproduction link
[https://run.iviewui.com/BZEdPagx](https://run.iviewui.com/BZEdPagx)

### Steps to reproduce
option通过遍历渲染出来，rule设置为必选，选择遍历出来的选项

### What is expected?
遍历出来的选项被选择时，表单验证可以通过

### What is actually happening?
rule验证不通过

**Comment by a1245582339** [comment]
刚刚尝试到，value改为字符串就可以通过验证，数字就不通过，希望value可以支持数字

**Comment by icarusion** [comment]
https://run.iviewui.com/0Sl8Pea9

rule 的 默认 type 是 string
