### ISSUE TITLE
[Bug Report] InputNumber sets the Min attribute to 0.1, which makes input decimal 0.1 instead of 0.5 by default.


### ISSUE THREAD

**Issue by hmxhydl** [iview/iview#5293]
### Environment
什么版本都行应该iview3.2.2

### Reproduction link
[https://run.iviewui.com/g1gYA0eM](https://run.iviewui.com/g1gYA0eM)

### Steps to reproduce
InputNumber设置min属性设置为0.1         删除默认值后在InputNumber输入小数会默认变成0.1 不能输入其他小数

### What is expected?
min设置为小数的时候   可以输入其他小数

### What is actually happening?
在输入小数只要输入0   就会变成min的值

**Comment by icarusion** [comment]
try to use `active-change` prop.
