### ISSUE TITLE
[Feature Request] table tags use slots


### ISSUE THREAD

**Issue by yemb** [iview/iview#5295]
### What problem does this feature solve?
  table在3.2.0后增加了slot-scope，当前slot-scope必须在Table标签中使用，如果Table是封装在一个公共组件中，则无法在此公共组件中使用slot-scope，只能用render，
  如果可以在公用组件中封装的table标签中增加插槽功能，在引用公共组件时，就可以根据不同业务通过slot-scope的方式编写组件。

### What does the proposed API look like?
*****************
### 公共组件 Common 中：
```html
<Table
  ……
>
  <slot ……/>
</Table>
```
*********************
### 业务组件 detailTable 中：
```html
<Common
  ……
>
  <template slot-scope="{ row, columns,  index }" slot="xxx">
    // do something
  </template>
</Common>
```

**Comment by icarusion** [comment]
No such plan now.
