### ISSUE TITLE
请教个ant-design样式问题

### ISSUE THREAD

**Issue by giscafer** [iview/iview#53]
iview源码`src/styles/..`目录下的一些ant-design样式文件是怎么构建生成的？`ant-design`官网没找到方式，想获取最新的样式

**Comment by icarusion** [comment]
不能因为antd太火就跑这问啊。( ˇˍˇ )
antd的样式在每个组件目录里，没有独立出来。

**Comment by giscafer** [comment]
直接说从component里边挨个取就好了。。。。
