### ISSUE TITLE
[Feature Request] Table Fixed Header Problem


### ISSUE THREAD

**Issue by shiweiqi19930328** [iview/iview#5301]
### What problem does this feature solve?
目前：
当前iview的table如果想实现固定表头，需要指定一个表格高度。
不足：
为了让用户尽可能的滚动整页，我们的设计是把table自动铺满页面剩余高度，并且固定表头。
目前我是使用js计算高度后赋值给table组件的。
期望：
table的高度跟随父容器自动铺满，我的父容器可以通过css铺满整屏。

### What does the proposed API look like?
Table props中的height可以接收百分比参数，如果是百分比高度参数，则读取父容器高度，并且是跟随resize响应的。

**Comment by icarusion** [comment]
No such plan now.
