### ISSUE TITLE
[Bug Report]Iview table border, not displayed in browser print preview

### ISSUE THREAD

**Issue by zystudios** [iview/iview#5303]
###
![20190218172205](https://user-images.githubusercontent.com/29728228/52940526-c470f880-33a1-11e9-824b-3e085229e2d6.png)
 Environment
any

### Reproduction link
[https://jsfiddle.net/5p63tuwb/](https://jsfiddle.net/5p63tuwb/)

### Steps to reproduce
use iview Table component to create a table
click browser print preview（chrome，safria，ff...）
table border, not displayed in browser print preview.

Many times, we will use the browser's printing function to print the entire web page, especially the pure form of the web page, but I found that the window preview is opened with window.print, iview's table border is partially not displayed.
Of course, this problem may not be iview, but I hope iview can fix it. I use the original table to write it is no problem, which also shows that iview is problematic.

很多时候，我们会使用浏览器的打印功能来打印整个网页，特别是纯表格的网页，但是我发现用window.print 打印预览窗口，iView的表格边框部分没有显示，甚至打印出来也是不显示的

当然，这个问题可能不是iView，但我希望iView可以解决它。我使用原始表格它是没有问题的，这也表明iView是有问题的。

### What is expected?
solve it

### What is actually happening?
table border, not displayed in browser print preview.

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/53775893-0e73e580-3f2f-11e9-957d-5ed9ee4a5fb2.png)
