### ISSUE TITLE
[Bug Report] select drop-down box, click empty, and the V-model binding value returns to undefined


### ISSUE THREAD

**Issue by mopxin** [iview/iview#5305]
### Environment
win10/chrome/3.2.2

### Reproduction link
[https://run.iviewui.com/bXp3nMBD](https://run.iviewui.com/bXp3nMBD)

### Steps to reproduce
select框，点击清空后触发on-change事件，打印出v-model绑定值为undefined

### What is expected?
v-model值为空

### What is actually happening?
v-model值为undefined

**Comment by icarusion** [comment]
wrong example.
