### ISSUE TITLE
[Bug Report] Avatar Switching Text Causes Page Card Death


### ISSUE THREAD

**Issue by yy-pow** [iview/iview#5306]
### Environment
win7、win10/最新版谷歌浏览器/vue 2.0

### Reproduction link
[http://v2.iviewui.com/components/avatar](http://v2.iviewui.com/components/avatar)

### Steps to reproduce
系统文本和其他项目百分比为125%并且浏览器为100%时，Avatar动态绑定值会导致页面卡死崩溃

### What is expected?
正常运行

### What is actually happening?
浏览器卡死崩溃

**Comment by ruofanzeng** [comment]
Avatar组件是谷歌最新版72.0.3626.119（正式版本） （32 位）浏览器使用会导致页面卡死，希望尽快能够解决
