### ISSUE TITLE
对话框怎么了？怎么改都是这个报错！

### ISSUE THREAD

**Issue by chaoLR** [iview/iview#531]
```
<!-- 引入Vue -->
{js href="__STATIC__/vue2.24.js"}
<!-- 引入样式 -->
{css href="__STATIC__/iview/iview.css"}
<!-- 引入组件库 -->
{js href="__STATIC__/iview/iview.min.js"} 
{css href="__STATIC__/lvyangtian/app.css"}
<section>
<div id="app">
    <Button type="primary" @click="modal1 = true">显示对话框</Button>
    <Modal
        v-model="modal1"
        title="普通的Modal对话框标题"
        @on-ok="ok"
        @on-cancel="cancel">
        <p>对话框内容</p>
        <p>对话框内容</p>
        <p>对话框内容</p>
    </Modal>
</div>
</section>
<script>
    new Vue({
		el: '#app',
  		data: {
    		modal1: false,
    		
  		},
  		methods:{
  			ok () {
                this.$Message.info('点击了确定');
            },
            cancel () {
                this.$Message.info('点击了取消');
            }
  		}
  	})
</script>
```
vue2.24.js:564 [Vue warn]: Do not use built-in or reserved HTML elements as component id: Circle 
vue2.24.js:564 [Vue warn]: Do not use built-in or reserved HTML elements as component id: Switch
vue2.24.js:564 [Vue warn]: Error compiling template:
<div :class=maskClasses v-show=visible @click=mask transition=fade></div> <div :class=wrapClasses @click=handleWrapClick> <div :class=classes :style=styles v-show=visible transition=ease> <div :class="[prefixCls + '-content']"> <a :class="[prefixCls + '-close']" v-if=closable @click=close> <slot name=close> <icon type=ios-close-empty></icon> </slot> </a> <div :class="[prefixCls + '-header']" v-if=showHead v-el:head><slot name=header><div :class="[prefixCls + '-header-inner']">{{ title }}</div></slot></div> <div :class="[prefixCls + '-body']"><slot></slot></div> <div :class="[prefixCls + '-footer']" v-if=!footerHide> <slot name=footer> <i-button type=text size=large @click=cancel>{{ cancelText }}</i-button> <i-button type=primary size=large :loading=buttonLoading @click=ok>{{ okText }}</i-button> </slot> </div> </div> </div> </div> 
- Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

**Comment by everyday0error** [comment]
说的很明显啊，组件模板需要一个根节点，你用一个div把你的元素包起来就OK了

**Comment by chaoLR** [comment]
还是不行

**Comment by chaoLR** [comment]
我回答我一早还行的版本 他还是报错

**Comment by chaoLR** [comment]
vue2.2.4问题，可能他偷偷更新了不兼容

**Comment by cdmin207078** [comment]
Message & Notice 都报错了

![image](https://cloud.githubusercontent.com/assets/1762278/24443610/e3944a3c-1495-11e7-8284-eefa4b6783a5.png)

**Comment by animabear** [comment]
@cdmin207078 我也遇到了，调试了下，需要改下webpack配置：

```javascript
alias: {
    vue: 'vue/dist/vue.js'
}
```
