### ISSUE TITLE
[Bug Report] Dropdown's click event does not filter disabeld items


### ISSUE THREAD

**Issue by 63734996** [iview/iview#5315]
### Environment
win10/chrome72

### Reproduction link
[https://run.iviewui.com/RrbuRUd0](https://run.iviewui.com/RrbuRUd0)

### Steps to reproduce
1、点击disabled的下拉选项，仍然会驱动click事件

### What is expected?
disabled的item无法点击，不触发click事件

### What is actually happening?
点击disabled的下拉选项，仍然会驱动click事件

**Comment by icarusion** [comment]
We design this.
