### ISSUE TITLE
[Bug Report] Table's on-sort-change fallback method returns a third value in the order: normal, repeated clicks on the same sort will reappear


### ISSUE THREAD

**Issue by zzhiren** [iview/iview#5324]
### Environment
mac os/chrome/2.x

### Reproduction link
[https://run.iviewui.com/T1MvPLaU](https://run.iviewui.com/T1MvPLaU)

### Steps to reproduce
点击表头排序向下的小箭头两次，第二次的的order返回值不是desc，而是normal

### What is expected?
不管点击向上的小箭头还是向下的小箭头，只能是asc和desc这两个值；而且那个箭头很小，应该不需要区分。关心到用户体验应该不管第几哪个箭头第一次点击返回desc，第二次点击返回asc，第三次点击返回desc，以此类推

### What is actually happening?
。。。

**Comment by liu343832401** [comment]
Are you sure this is a bug?

**Comment by zzhiren** [comment]
column：当前列数据
key：排序依据的指标
order：排序的顺序，值为 asc 或 desc

文档上介绍只会返回 asc 或desc，但是重复点击同一个排序按钮确实会返回 normal，
不知道是不是设计的点击向上箭头只能返回asc，点击向下箭头只能返回desc，如果点击同一个按钮两次则会返回normal，这样就达不到排序的效果了。

就是使用起来实惠出错的，我一般不会注意到向上和向下按钮
