### ISSUE TITLE
Select components should be able to support option with value=""


### ISSUE THREAD

**Issue by eeeecw** [iview/iview#5329]
### What problem does this feature solve?
可以选择空串

### What does the proposed API look like?
<Select v-model="data">
  <Option value="">不限</Option>
  <Option value="number">数字</Option>
  <Option value="alphabet">字母</Option>
  <Option value="chinese">中文</Option>
  <Option value="email">邮箱</Option>
  <Option value="phone">手机</Option>
  <Option value="identityCard">身份证</Option>
</Select>

**Comment by eeeecw** [comment]
<Select v-model="data">
  <Option value="">不限</Option>
  <Option value="number">数字</Option>
  <Option value="alphabet">字母</Option>
  <Option value="chinese">中文</Option>
  <Option value="email">邮箱</Option>
  <Option value="phone">手机</Option>
  <Option value="identityCard">身份证</Option>
</Select>

**Comment by eeeecw** [comment]
```
<Select v-model="data">
  <Option value="">不限</Option>
  <Option value="number">数字</Option>
  <Option value="alphabet">字母</Option>
  <Option value="chinese">中文</Option>
  <Option value="email">邮箱</Option>
  <Option value="phone">手机</Option>
  <Option value="identityCard">身份证</Option>
</Select>
```

>

**Comment by icarusion** [comment]
No such plan.
