### ISSUE TITLE
table column的key可以使用. 来取嵌套内容么？

### ISSUE THREAD

**Issue by leftjs** [iview/iview#533]
这样的方式
![image](https://cloud.githubusercontent.com/assets/8311633/24441079/916fe366-148a-11e7-8200-407dd41576e6.png)
来取这样的数据格式
![image](https://cloud.githubusercontent.com/assets/8311633/24441038/58d51a08-148a-11e7-95ee-dc97d10491f1.png)
请问可以如何优雅的解决这个问题，还是说需要在之前使用lodash对object做flatten?

**Comment by icarusion** [comment]
要转换成iView支持的数据格式
