### ISSUE TITLE
[Bug Report] iview version not updated

### ISSUE THREAD

**Issue by mahmoudzohdi** [iview/iview#5343]
### Environment
windows 10
chrome 72.0.3626.119
vue 2.5.22
iview 3.2.2

### Reproduction link
[https://github.com/iview/iview/pull/5304](https://github.com/iview/iview/pull/5304)

### Steps to reproduce
I created pull request to add new local and fix another local.
the pull request merged but not reflected to iview version.
I tried to install iview again to get the new local that I added but I didn't found my changes 

### What is expected?
the new changes reflected to iview version when I install it 

### What is actually happening?
no changes found

---
I think this issue happened because you pushing the dist folder to repo, but I guess it's better to make dist folder generated automatically on push new code by the CI.

**Comment by didianV5** [comment]
@mahmoudzohdi  , update `distance-to-edge`

```
<template>
  <Scroll :on-reach-bottom="handleReachBottom" :distance-to-edge="[20, 1]">
    <Card
      dis-hover
      v-for="(item, index) in list1"
      :key="index"
      style="margin: 32px 0"
    >Content {{ item }}</Card>
  </Scroll>
</template>
```

**Comment by icarusion** [comment]
you can update again when iView publish a new npm version, you can watch this project, so you will receive an email when released
