### ISSUE TITLE
[Feature Request] When the fields property of the form.vue is empty, validate() should be resolved instead of no response.

### ISSUE THREAD

**Issue by luwanquan** [iview/iview#5350]
### What problem does this feature solve?
In dynamic forms, it is reasonable to have `fields` empty. If there is no `prop`, the result of the check is true, but now because `fields` are empty, validate() does not respond. I have to write additional logic to adapt this situation. Unscientific

### What does the proposed API look like?
``` javascript
// form.vue: 67
validate(callback) {
  return new Promise(resolve => {
    let valid = true;
    let count = 0;
    if (this.fields.length === 0) {
      if (typeof callback === 'function') {
        callback(valid);
      }
    }
    this.fields.forEach(field => {
      ...
    });
  });
}
```

**Comment by luwanquan** [comment]
https://jsfiddle.net/948ud7fn/

**Comment by icarusion** [comment]
It is more flexible for users to trigger
