### ISSUE TITLE
Chrome autofill hide select options

### ISSUE THREAD

**Issue by zinwalin** [iview/iview#5358]
![image](https://user-images.githubusercontent.com/5416196/53690278-66460b80-3dcc-11e9-9e47-4b51ab6ab3e3.png)

as depicted on screenshot, iView select options hided by Chrome autofill, is it possible to hide Chrome autofill?   I tried to set autoComplete attribute to false, but failed.

**Comment by 1008611** [comment]
Chrome autofill hide my input,
i solve it by this：
```
<form action="javascript:void(0)">
                  <InputNumber></InputNumber>
</form>
```
