### ISSUE TITLE
[Bug Report] Scroll infinite scroll cannot trigger on-reach-bottom


### ISSUE THREAD

**Issue by xyydd** [iview/iview#5359]
### Environment
windows10/chrome70.0.3538.110（正式版本） （64 位）/vue2.5.2

### Reproduction link
[https://run.iviewui.com/vI1bu3HV](https://run.iviewui.com/vI1bu3HV)

### Steps to reproduce
使用windows10下的chrome70.0.3538.110（正式版本） （64 位），鼠标滚轴向下滚动，无法触发‘无限滚动’组件的on-reach-bottom

### What is expected?
能触发on-reach-bottom

### What is actually happening?
不能触发on-reach-bottom

**Comment by didianV5** [comment]
修改 :distance-to-edge 

```
<template>
  <Scroll :on-reach-bottom="handleReachBottom" :distance-to-edge="[20, 1]">
    <Card
      dis-hover
      v-for="(item, index) in list1"
      :key="index"
      style="margin: 32px 0"
    >Content {{ item }}</Card>
  </Scroll>
</template>
```
