### ISSUE TITLE
i-table中column执行render时如何绑定自定义事件

### ISSUE THREAD

**Issue by skylas** [iview/iview#536]
### iView 版本号 2

 Vue 版本号 2.2.1

在非 template/render 模式，不使用打包工具情况下直接使用:
无webpack ，无NPM

```
<i-table ref="table" :columns="columns" :data="datas"></i-table>

new Vue({
    el: '#app',
    data: {
        columns:[{ 
          title: '操作', key: 'action', width: 60,
          render : function(row, column, index){
               return '<i-button type="primary" size="small" @click="event">查看</i-button>';
          }
        }],
        datas:[]
    },
});

```
> 请问 @click="event" 如何绑定事件？

运行提示错误：Property or method "event" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option。

**Comment by icarusion** [comment]
看文档

**Comment by skylas** [comment]
你好！已查过所有文档没有相关的案例

**Comment by liuwm91** [comment]
我也遇到这问题了，非template/render模式下不行。

**Comment by sciooga** [comment]
@skylas iview 的 table 现在 BUG 挺多的，你这个情况应该使用 content，并且不能按文档中的 self 直接写在 data 中，而是写在 watch 内
给你写了个示例参考 https://jsfiddle.net/sciooga/rjLn03ta/

**Comment by excellnn** [comment]
@sciooga 单文件的形式还是不行,报错. Uncaught TypeError: Cannot read property '$parent' of undefined

**Comment by CyanChoi** [comment]
data 是一个问题，问题是eventHander是methods里面的。“看文档” 三个字几乎是最差的答案了
