### ISSUE TITLE
select组件远程搜索，选择一个选项后，会重复请求一次

### ISSUE THREAD

**Issue by immissile** [iview/iview#5368]
select组件设置remote模式的时候，在输入框里输入字符串 a ，这时远程请求到数据显示在列表里，选择某一项，加入这一个option的值是 abc ，当选择后，输入框的值变成abc，但同时也会再请求一次，这次请求完全没必要啊，也会造成UI闪来闪去，对比element ui就没这个问题

**Comment by immissile** [comment]
目前只能通过 v-module绑定的值跟remote-method返回的query值对比，如果不一样就return 这样来处理，但是感觉这部分应该框架本身来搞更合适

**Comment by Sunzhuokai** [comment]
this is a bug or a feature？
