### ISSUE TITLE
[Bug Report]Select组件激活后阻止了整个document的点击事件

### ISSUE THREAD

**Issue by lizhancheng** [iview/iview#5369]
### Environment
chrome

### Reproduction link
[https://jsfiddle.net/2n5L9hq3/](https://jsfiddle.net/2n5L9hq3/)

### Steps to reproduce
点击Select，然后点击button

### What is expected?
Select收起，button事件响应

### What is actually happening?
Select收起

**Comment by icarusion** [comment]
we design this.
