### ISSUE TITLE
Table组件在webpack开启混淆后上下文不能正常工作

### ISSUE THREAD

**Issue by s51983** [iview/iview#537]
### iView 版本号
 2.0.0-rc.8

### 操作系统/浏览器 版本号
win10/Chrome 56 

### 版本号
Vue 2.2.6
vue-template-compiler 2.2.6
webpak 2.2.0

### 复现步骤
```
new webpack.optimize.UglifyJsPlugin({
    sourceMap: true,
    compress: {
        warnings: false
    },
    // 混淆
    mangle: false
})
```
设置 mangle 为 false 时 Tabel组件 context 工作正常，render 中的 @click 能正常执行

```
new webpack.optimize.UglifyJsPlugin({
    sourceMap: true,
    compress: {
        warnings: false
    },
    // 混淆
    mangle: true
})
```
设置 mangle 为 true 时 Tabel 组件 context 工作不正常，render 中的 @click 报错 Uncaught ReferenceError: *** is not defined

**Comment by icarusion** [comment]
Table 的编译暂不支持混淆

**Comment by dreamstu** [comment]
+1
