### ISSUE TITLE
[Feature Request]table可否扩展一个支持行合并（td同一类型合并）的功能

### ISSUE THREAD

**Issue by Titans1001** [iview/iview#5379]
### What problem does this feature solve?
这个功能可以在渲染表格的时候，当表头这一字端ismerge为true的时候可以当值相同的时候进行合并，当然不限于一个字段，可以是多字段的行合并

### What does the proposed API look like?
在渲染表格之前先对表格数据进行表头是否合并数据的提炼以及对表格数据提炼出来的多字段数组进行递归排序，然后在渲染表格的时候设置rowspan的值以及隐藏同一级别的值相同的td，而不是不渲染，希望可以为table组件提供这个功能

**Comment by icarusion** [comment]
same issue exist
