### ISSUE TITLE
[Bug Report]Drawer属性before-destroy没有，实际属性应该是before-close

### ISSUE THREAD

**Issue by finnlee87** [iview/iview#5386]
### Environment
iview 3.3.0

### Reproduction link
[https://run.iviewui.com/XFdkSSBf](https://run.iviewui.com/XFdkSSBf)

### Steps to reproduce
无

### What is expected?
before-destroy

### What is actually happening?
before-close

**Comment by icarusion** [comment]
是 before-close，不是 before-destroy
