### ISSUE TITLE
Tree组件能否可以支持pid父子关系的Array格式

### ISSUE THREAD

**Issue by RyanSheng777** [iview/iview#539]
是否可以像Ztree一样，支持带有父子关系的简单 Array 格式
var treeNodes = [                                                                         
    {"id":1, "**pId**":0, "name":"test1"},   
    {"id":11, "**pId**":1, "name":"test11"},   
    {"id":12, "**pId**":1, "name":"test12"},   
    {"id":111, "**pId**":11, "name":"test111"},   
    ......   
];

**Comment by icarusion** [comment]
数据结构参照官网示例
