### ISSUE TITLE
[Bug Report] validation error message disappeared when have multi validation rules with different triggers

### ISSUE THREAD

**Issue by mahmoudzohdi** [iview/iview#5399]
### Environment
windows 10
chrome 72.0.3626.119
vue 2.6.7
iview 3.3.0

### Reproduction link
https://run.iviewui.com/ypLGaZJp

### Steps to reproduce
I have text field with 2 rules
1- required with trigger blur
2- email validation with trigger change

try to write an invalid email and go out of the input

### What is expected?
the error message of email validation keep appearing

### What is actually happening?
the email validation error disappeared because required validation passed

**Comment by icarusion** [comment]
You can use `v-model` instead of `value` and `@on-change`, because in Input component, iView emit a custom event to Form component, if you use `@on-change` to change value, you should emit it by your self. You can view Input code to get more information.

**Comment by mahmoudzohdi** [comment]
@icarusion  I actually using v-model and the issue happens, please check the reproduction link
