### ISSUE TITLE
[Feature Request]下拉框希望增加一个不使用Poper.js的选项

### ISSUE THREAD

**Issue by vincentchenzq** [iview/iview#5402]
### What problem does this feature solve?
我们当前项目在页面上有40个下拉框，看了下源码在dropdown.vue里面使用了poper.js  ,poper.js使用了监听滚动事件，导致ie上非常卡

### What does the proposed API look like?
scroolable:true    // 表示是否让下拉框跟随页面滚动 默认true， 可以改为false

**Comment by icarusion** [comment]
No such plan
