### ISSUE TITLE
[Bug Report]下拉框带搜索功能在ie11如输入new数据多出现滚动条有兼容问题

### ISSUE THREAD

**Issue by d425825121** [iview/iview#5408]
### Environment
win7/ie11/vue2.0

### Reproduction link
[http://bb.zixxxx.com](http://bb.zixxxx.com)

### Steps to reproduce
在ie11input框输入new，在下拉列表会出现滚动条，随意点击滚动条，input框数据会被清空

### What is expected?
ie11点击滚动条时候数据不会被清空，不然用户只能使用鼠标滚动下拉数据

### What is actually happening?
ie11点击滚动条时候数据会被清空

**Comment by d425825121** [comment]
大佬啥时候回复下

**Comment by icarusion** [comment]
![image](https://user-images.githubusercontent.com/5370542/54406325-b00beb80-4714-11e9-9462-17a19d57d233.png)
