### ISSUE TITLE
Button htmlType不能正确解析

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#541]
### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
windows7/Chrome 56
### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）

https://codepen.io/anon/pen/PpxQKo

### 复现步骤
<i-button type="primary" htmlType="submit">Button</i-button>
### 问题现象，以及你期望的结果是怎样的?
问题：htmlType不会被解析,
期望：htmlType解析为 type="submit"
结果：<button type="button" class="ivu-btn ivu-btn-primary" htmltype="submit">  <span>Button</span></button>

**Comment by icarusion** [comment]
`html-type`
