### ISSUE TITLE
[Bug Report]Select OptionGroup 使用filterable后下拉列表显示问题

### ISSUE THREAD

**Issue by xiaoxin0818** [iview/iview#5410]
### Environment
mac/chrome 73.0.3683.67/iview run当前环境

### Reproduction link
[https://run.iviewui.com/9GYxjZLX](https://run.iviewui.com/9GYxjZLX)

### Steps to reproduce
开启filterable，使用Option-group，搜索框输入city1，选择选项city1后，再次打开Select选择框，不能显示其他选项

### What is expected?
开启filterable，使用Option-group，搜索框输入city1，选择选项city1后，再次打开Select选择框，能够显示所有选项

### What is actually happening?
开启filterable，使用Option-group，搜索框输入city1，选择选项city1后，再次打开Select选择框，不能显示其他选项

**Comment by icarusion** [comment]
#5216
