### ISSUE TITLE
[Feature Request] Upload control batch upload function, you need to know how many files have been selected this time


### ISSUE THREAD

**Issue by linning9527** [iview/iview#5424]
### What problem does this feature solve?
现在iView是一次传三张图片，后台接收到三个请求，无法得知这三个是否是同一组的数据（这张图片为同一组的数据，要组合起来）

### What does the proposed API look like?
前端能获取上传的文件总个数，是那一次的？这样后台可以判断出这些数据需要组合起来存储。

**Comment by icarusion** [comment]
No such plan
