### ISSUE TITLE
[Bug Report] Time will display the date after more than 30 days


### ISSUE THREAD

**Issue by alanwang87** [iview/iview#5426]
### Environment
window 10 / Chrome / vue.3.3.3

### Reproduction link
[https://run.iviewui.com/8DtCscIj](https://run.iviewui.com/8DtCscIj)

### Steps to reproduce
<template>
    <div>
        <Time :time="time2" />
    </div>
</template>
<script>
    export default {
        data () {
            return {
                time2: (new Date()).getTime() - 86400 * 3 * 1000*10
            }
        }
    }
</script>

### What is expected?
显示为 xx天前 或者 xx月前 xx年前

### What is actually happening?
02-09 17:03

**Comment by icarusion** [comment]
we design this
