### ISSUE TITLE
[Bug Report]Dragging out of modal causes it to close on mouse release in Chrome

### ISSUE THREAD

**Issue by nj-db** [iview/iview#5427]
### Environment
Windows 10, Chrome 73.0.3683.75

### Reproduction link
[https://www.iviewui.com/components/modal-en](https://www.iviewui.com/components/modal-en) Can be reproduced in the iview Modal examples.

### Steps to reproduce
1. Open modal containing an input control and add test to it.
2. Hilight the text by click and dragging the mouse cursor in the input until mouse is over the modals background mask.
3. Release the mouse button.

### What is expected?
The modal should stay open with the inputs text hilighted.

### What is actually happening?
The modal closes

---
This behavior has only started after Chrome has recently updated to version 73.0.3683.75. This does not happen in IE or Firefox.

**Comment by ckwill90** [comment]
We are experiencing the exact same issue since the Chrome update. Tested on prior version of Chrome this does not happen. Once again, Chrome broke something.
