### ISSUE TITLE
[Feature Request] Select multiple-choice mode for displaying selected options in the selection box and adding event hooks when doing deletion operations


### ISSUE THREAD

**Issue by zhoucumt** [iview/iview#5432]
### What problem does this feature solve?
一直以来都在使用iview,在最近的实际项目中发现了一些bug和功能上不完备的地方（今天已经提了2个bug在issue上了）
多选后，做删除时，希望能给个类似on-remove事件，让用户在操作删除之前可以自定义方法，不能直接就删除了。
实际项目中，遇到的场景是，多选框选择某个数据，然后另一个区域把选择的数据信息完整的展示出来，被选中后提交数据，然后进行查看时，想删除某个数据时，需要根据状态来判断，有的数据不能操作，有的数据虽然可以删除，但是需要通过请求接口的方式来删除。

### What does the proposed API look like?
类似on-change一样，比如on-remove

**Comment by shizhenbin** [comment]
我可能是我理解错了， 多选后做做删除，那不是选择完之后点击删除按钮吗？ 点击删除按钮就可以做想要的操作了， 比如点击删除来个确认删除的弹窗。  难道我理解错了？

**Comment by zhoucumt** [comment]
@shizhenbin   实际的需求中，比如一组数据里面，有10条数据，有的数据的state为0，有的state为1，如果对于state为0的不允许删除，这个时候就需要加个事件钩子，让用户自行进行决定能否删除  @icarusion  另外，能不能尽快解决一下

**Comment by icarusion** [comment]
No such plan

**Comment by zhoucumt** [comment]
@icarusion  这个是合理的需求，并且实际场景也会有这种需求和问题，直接没这种计划，太武断了吧？
