### ISSUE TITLE
Number failure of [Bug Report] Radio component


### ISSUE THREAD

**Issue by yuerzm** [iview/iview#5437]
### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

### Reproduction link
[https://run.iviewui.com/ekwz4AKT](https://run.iviewui.com/ekwz4AKT)

### Steps to reproduce
https://run.iviewui.com/ekwz4AKT

### What is expected?
Number 和 String 效果一致

### What is actually happening?
Number 无法绑定

**Comment by shizhenbin** [comment]
如果是数字的话 label 要改成 :     :label
