### ISSUE TITLE
[Feature Request] Tabs: When type= "card", the top tab bar adapts height


### ISSUE THREAD

**Issue by fralonra** [iview/iview#5438]
### What problem does this feature solve?
目前，当 `Tabs` 组件的 `type` 设置为 `card` 时，上方标签栏高度固定为 32px，当自定义标签页内容时无法自适应，需要手动调整样式。不明白为何要设置为定值。

### What does the proposed API look like?
影响到的类的 `height` 不设置为定值，可改为 `auto`。

**Comment by icarusion** [comment]
No such plan
