### ISSUE TITLE
表格render全都失效

### ISSUE THREAD

**Issue by hlpszy** [iview/iview#544]
### iView 版本号

2.0.0-rc.8
### 操作系统/浏览器 版本号

win/Chrome 56
### Vue 版本号

2.2.1
### 能够复现问题的在线示例（重要）

表格render方法，使用Icon，Button等全都失效了。比如使用Button标签会渲染成原生图标
![image](https://cloud.githubusercontent.com/assets/18546928/24499423/3bdf93ac-1574-11e7-8720-dd52a43faa49.png)

**Comment by icarusion** [comment]
仔细看文档
