### ISSUE TITLE
在from表单验证下拉框校验问题，下拉框数据是动态获取的

### ISSUE THREAD

**Issue by yeshuqin** [iview/iview#545]
### 复现步骤
<Form-item label="选择员工" prop="empId">
            <Select v-model="userItem.empId" clearable class="select-main-width">
              <Option v-for="item in roleList" :value="item.value" :key="item">{{ item.label }}</Option>
            </Select>
          </Form-item>

roleList如果写死了，就没问题，但是ajax获取选取就提示说我没选中，明明选泽了

**Comment by rijn** [comment]
#1420 @icarusion Please close this issue
