### ISSUE TITLE
[Bug Report] When I use command NPM install iView -- save find Error Cannot find name'more'.


### ISSUE THREAD

**Issue by 1093439315** [iview/iview#5457]
### Environment
dev  vsersion 3.3.2

### Reproduction link
[https://run.iviewui.com/bp0rLbAe](https://run.iviewui.com/bp0rLbAe)

### Steps to reproduce
npm install iview --save;
npm run dev;

### What is expected?
no error

### What is actually happening?
throw excetion

![image](https://user-images.githubusercontent.com/18135235/54615133-864a2000-4a98-11e9-9cff-1e5d7092647b.png)
![image](https://user-images.githubusercontent.com/18135235/54615151-8e09c480-4a98-11e9-8760-f75bba1256fe.png)

**Comment by icarusion** [comment]
fixed
