### ISSUE TITLE
[Feature Request] Hello, I want to add a form auto-generation component for iView


### ISSUE THREAD

**Issue by woai3c** [iview/iview#5458]
### What problem does this feature solve?
这个组件的作用是由数据驱动表单生成 不需要手动写表单组件 只需要按照格式给组件传入数据 即可生成表单
这个组件我已经写完了 这里是[DEMO地址](https://github.com/woai3c/vue-generate-form/blob/master/demo.md)
如果您方便的话 请看一下

### What does the proposed API look like?
这个组件非常适合有大量表单需求的系统
```
<div id="app">
        <VueGenerateForm :options="options"/>
        // 或者 <vue-generate-form :options="options"/>
</div>
```

**Comment by icarusion** [comment]
No such plan.
You can publish it as a library.
