### ISSUE TITLE
能否增加InputNumber组件的事件API（例如on-enter，on-focus,on-blur）

### ISSUE THREAD

**Issue by meteorfall** [iview/iview#546]
### iView 版本号

2.0.0-rc.7
### 操作系统/浏览器 版本号

Windows 2008 Chrome 56
### Vue 版本号

2.2.1
### 能够复现问题的在线示例（重要）

无
### 问题现象，以及你期望的结果是怎样的?
InputNumber组件作为Input系列的，能否也emit出和Input一样的 on-enter，on-focus,on-blur事件？因为作为输入框的控制，这些会常用到。

**Comment by rijn** [comment]
That's reasonable.

**Comment by rijn** [comment]
@icarusion Commit has been merged so we can close this issue
