### ISSUE TITLE
[Bug Report]Please do not use the tags (e.g. Col) in the HTML5 specification

### ISSUE THREAD

**Issue by pujiaxun** [iview/iview#5460]
### Environment
macOS

### Reproduction link
[https://github.com/vuejs/eslint-plugin-vue/issues/604](https://github.com/vuejs/eslint-plugin-vue/issues/604)

### Steps to reproduce
use eslint 

use eslint-plugin-vue

### What is expected?
auto format code

### What is actually happening?
wrongly fix `<Col> xxx </Col>`  to `<Col /> xxx </Col>` because it is recognized as an HTML tag `col` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col

**Comment by icarusion** [comment]
you can use `i-col`
