### ISSUE TITLE
[Bug Report] Tooltip's No Line Change Problem for Excessively Long Number Letters


### ISSUE THREAD

**Issue by ybs586924** [iview/iview#5463]
### Environment
windows/谷歌浏览器/vue2.5.10

### Reproduction link
[https://run.iviewui.com/kUVCpI6X](https://run.iviewui.com/kUVCpI6X)

### Steps to reproduce
<template>
    <Tooltip max-width="100" content="5555555555555555555555555555555555">
        <Button>Long Content</Button>
    </Tooltip>
</template>
<script>
    export default {
        
    }
</script>

### What is expected?
在气泡提示中出现换行

### What is actually happening?
在气泡提示中未出现换行，文本超出气泡框。

**Comment by shizhenbin** [comment]
这是业务问题吧，这种提示本身就不适合长文本，一定要的话自己改改样式就行了，不算bug
