### ISSUE TITLE
The on-change event of the [Bug Report] Checkbox Group component cannot receive an array of all options currently selected


### ISSUE THREAD

**Issue by AILINGANGEL** [iview/iview#5471]
### Environment
Darwin Kernel Version 16.7.0/  chrome 72.0.3626.12 (64位)/ vue 3.3.2

### Reproduction link
[https://run.iviewui.com/McEY13pA](https://run.iviewui.com/McEY13pA)

### Steps to reproduce
点击选中多个checkbox选项

### What is expected?
希望点击一个checkbox的时候，当前整个checkbox group中所有选中的选项都alert出来!!!

### What is actually happening?
CheckboxGroup组件的on-change事件只有在使用了v-model双向绑定值的时候才会收到当前所选项的数组,单纯的使用:value或者不使用:value只绑定一个on-change事件只能收到当前点击过的选项，无法收到所有的选项。

**Comment by shizhenbin** [comment]
这个功能没有比加一个v-model方便的吧？ 加参数跟加v-model好像没啥差

**Comment by AILINGANGEL** [comment]
这不是新功能呀。就是说在ChecboxGroup这个组件上如果不使用v-model那么on-change事件接受到的值并不是当前group所有选中的项目,只是你点击的谁就收到谁,如果取消点击谁收到的还是[""]。这是个bug
