### ISSUE TITLE
Property 'LoadingBar' does not exist on type 'IView'. 

### ISSUE THREAD

**Issue by cky917** [iview/iview#5486]
### Environment
Version: typescript 3.3.4000, tslint 5.14.0

### Reproduction link
[https://jsfiddle.net/yyrzhm46/](https://jsfiddle.net/yyrzhm46/)

### Steps to reproduce
```
iView.LoadingBar.start()
```
报错
```
Property 'LoadingBar' does not exist on type 'IView'.
```

### What is expected?
在typescript环境下使用LoadingBar tslint不会报错

### What is actually happening?
 报错 Property 'LoadingBar' does not exist on type 'IView'.

**Comment by xdmushui** [comment]
@cky917 How did you solve this problem?
How did you solve this problem?
![image](https://user-images.githubusercontent.com/3242057/56459893-e18b6d00-63cc-11e9-8711-75075df9044d.png)

**Comment by shichzh** [comment]
@cky917 @xdmushui I have the same question, did you solve this question?

**Comment by xdmushui** [comment]
> @cky917 @xdmushui I have the same question, did you solve this question?

No. I'm manually added some code to iview.
.\node_modules\iview\types\iview.d.ts
`import { PluginFunction } from 'vue';

interface IView extends PluginFunction<any> {
    LoadingBar: any;
}

declare const iView: IView;
export default iView;`

**Comment by zpzxgcr** [comment]
How did it end up?

**Comment by cky917** [comment]
@xdmushui @shihaha  @zpzxgcr  
I resolve this by `Vue.prototype.$Loading.start()`  😂

**Comment by mylvghb** [comment]
import {LoadingBar} from 'iview';
router.beforeEach((to, from, next) => {
    LoadingBar.start(); 
    next();
});

router.afterEach((to, from) => {
    LoadingBar.finish();
});

**Comment by raymod** [comment]
都不会用中文吗！
