### ISSUE TITLE
[Feature Request] Table Component Columns Type Expansion Time


### ISSUE THREAD

**Issue by ifunjoke** [iview/iview#5495]
### What problem does this feature solve?

参考了例子  https://www.iviewui.com/components/table-en#Expandable

实际项目中当设置slot为expand
```
columns:[{
    type: 'expand',
    width: 50,
    slot: 'expand'
}]
```

html模板里实现slot template
```
<Table 
 :data="data" 
 :columns="columns" 
>
    <template slot-scope="{ row, index }" slot="expand">expand test</template>
</Table>
```
最终效果columns `type`为`expand`,`slot`插槽渲染不生效,我个人提议columns列有`slot`属性时候，应该渲染到`Table`组件里与`slot`具名属性对应的`template`模板标签里

### What does the proposed API look like?
columns列有`slot`属性时候，应该渲染到`Table`组件里与`slot`具名属性对应的`template`模板标签里

**Comment by icarusion** [comment]
No such plan
