### ISSUE TITLE
[Feature Request] recommends adding the @btn-font-size-small configuration in the Button less configuration


### ISSUE THREAD

**Issue by beita1991** [iview/iview#5503]
### What problem does this feature solve?
建议在 Button less配置的地方添加 @btn-font-size-small 配置，现在ivuew 项目中 只有 
@btn-font-size          : 12px;
@btn-font-size-large    : 14px;
也就是 small和base 用的都是这一个配置 ，
我的项目需求是 base 用的 14px ，large 用14px ，small 用 12px ，
我这边无法从配置中完成这个需求

### What does the proposed API look like?
添加  @btn-font-size-small 可配置

**Comment by icarusion** [comment]
No such plan.
