### ISSUE TITLE
[Feature Request]Input 的autocomplete 标记增加 new-password

### ISSUE THREAD

**Issue by q397133334** [iview/iview#5504]
### What problem does this feature solve?
创建用户，需要输入用户名密码的地方。无法取消自动填充，采用new-password 可以防止表单填充。

### What does the proposed API look like?
autocomplete="new-password"
取消控制台报错
Invalid prop: custom validator check failed for prop "autocomplete".

**Comment by a497771654** [comment]
autocomplete="on|off"  不就可以禁止自动填充吗？

**Comment by a497771654** [comment]
http://www.w3school.com.cn/html5/att_form_autocomplete.asp

**Comment by q397133334** [comment]
谷歌浏览器 
表单中带有 password的没办法禁止
添加autocomplete="off"（autocomplete其含义代表是否让浏览器自动记录之前输入的值）有时候并不是都有效果
