### ISSUE TITLE
layout中左右布局的情况不好设置三级菜单

### ISSUE THREAD

**Issue by CodeMonkeyXu** [iview/iview#551]
### 复现步骤
没有预留三级菜单，我自己手写了一个三级，但是不好切换效果，需要操作DOM，不符合vue的思想
### 问题现象，以及你期望的结果是怎样的?
希望能改进一下，像Collapse折叠面板一样能嵌套使用
### 你估计可能的原因是什么（选填）？
设计的时候没有预留三级菜单

**Comment by icarusion** [comment]
#557
