### ISSUE TITLE
[Bug Report]iview table tooltip-theme 属性无效

### ISSUE THREAD

**Issue by Guotykaka** [iview/iview#5519]
<Table :columns="columns" :data="data8"></Table>
columns=[
{
          title: "分组描述",
          align: "center",
          tooltip: true,
          "tooltip-theme": "light",
          key: "group_desc"
},
],
这样用在列表中tooltip-theme依然是默认的dark。

**Comment by susiwen8** [comment]
@Guotykaka tooltip-theme写错地方了，它是独立的一个prop,在template这么写
`<Table :columns="columns1" :data="data1" tooltip-theme="dark"></Table>`
columns这么配置
`columns=[ { title: "分组描述", align: "center", tooltip: true, key: "group_desc" }, ]`
