### ISSUE TITLE
[Feature Request]It is recommended that Poptip increase the attribute that disables the click out side close.

### ISSUE THREAD

**Issue by luwanquan** [iview/iview#5525]
### What problem does this feature solve?
When I just want to close Poptip by clicking on a specific place, I want to set a property like Modal's maskClosable to prevent the click out side event of Poptip.

### What does the proposed API look like?
``` javascript
// poptip/poptip.vue  props
maskClosable: {
    type: Boolean,
    default: true
}
```

**Comment by icarusion** [comment]
No such plan
