### ISSUE TITLE
用resetFields清除校验结果时反而再次触发了form表单里multiple的select的change校验事件

### ISSUE THREAD

**Issue by shichzh** [iview/iview#5528]
弹窗里有一个元素会动态增减的form表单如下：

> <Form ref="form100" :model="formValidate">
    <div class="each" v-for="(item, index) in formValidate.interviewRounds" :key="index">
        <FormItem :prop="'interviewRounds.' + index + '.userIds'" :rules="{required: true, type: 'array', message: '请选择XXX', trigger: 'change'}">
            <Select v-model="item.userIds" multiple class="select3">
                <Option v-for="eve in people" :value="eve.id" :key="eve.id">{{ eve.nickname }}</Option>
            </Select>
        </FormItem>
    </div>
</Form>

对于可以动态添加和删除的多选select的校验规则写在了行内：
`:rules="{required: true, type: 'array', message: '请选择XXX', trigger: 'change'}"`

对应的数据结构如下：
```
formValidate: {
    interviewRounds: [{
        round: "",
        startTime: "",
        duration: "",
        userIds: []
    }]
}
```
关闭弹窗时调用`this.$refs['form100'].resetFields();`想要去清空历史数据和校验结果，清空数据后，`formValidate.interviewRounds.userIds`恢复回空数组，反而触发了绑定在select的FormItem上的change校验事件，就又会对表单进行校验，并报“请选择XXX”的红错，
请问该怎么改？

**Comment by luomeijing** [comment]
解决了吗 遇到了同样的问题 捂脸

**Comment by shichzh** [comment]
参考这里：https://segmentfault.com/q/1010000018745241
