### ISSUE TITLE
radio组件RadioGroup的时候,value类型是number, 选中失效

### ISSUE THREAD

**Issue by lxk0301** [iview/iview#5530]
```
<template>

    <RadioGroup v-model="animal">
        <Radio label="1">111</Radio>
        <Radio label="2">222</Radio>
        <Radio label="3">333</Radio>
    </RadioGroup>
</template>
<script>
    export default {
        data () {
            return {
                phone: 'apple',
                animal: 2
            }
        }
    }
</script>

```

#### 当示例代码里面的animal为number类型 :2的时候, `<Radio label="2">222</Radio>`
并未被选中,  可文档里面RadioGroup props的value是可以为number类型的

**Comment by lxk0301** [comment]
问题已解决, 需要使用v-modellabel="1" , 才行

**Comment by rhb4java** [comment]
> 问题已解决, 需要使用v-modellabel="1" , 才行

您好，能详细说说吗？我也是这个问题

**Comment by lxk0301** [comment]
> > 问题已解决, 需要使用v-modellabel="1" , 才行
> 
> 您好，能详细说说吗？我也是这个问题

@ @rhb4java 把  label ='2'  改成 :label='2'(前面加个 冒号  : )
<Radio :label="1">111</Radio>
<Radio :label="2">222</Radio>
