### ISSUE TITLE
穿梭框异步数据加载不出来

### ISSUE THREAD

**Issue by zhonggithub** [iview/iview#555]
重新地址：http://codepen.io/anon/pen/yMGbZX?editors=1011
vue版本：2.0
iview: 最新
chrome: 最新版本
环境：macbook

**Comment by icarusion** [comment]
你的代码直接就报错了

**Comment by zhonggithub** [comment]
重现地址已经修改：http://codepen.io/zzcode/pen/yMGbZX?editors=1111

**Comment by ryanzhouff** [comment]
@zhonggithub 参考[#388](https://github.com/iview/iview/issues/388#issuecomment-443964536)

**Comment by lisimeng0826** [comment]
请问解决了吗？我也遇到了同样的问题，用官方实例，无法动态加载数据
