### ISSUE TITLE
[Bug Report]Tabs组件添加会出现bug

### ISSUE THREAD

**Issue by xkcoding** [iview/iview#5558]
### Environment
系统MacOS、浏览器Chrome、Vue版本 iViewRun 当前版本

### Reproduction link
[https://run.iviewui.com/N6aCC0IM](https://run.iviewui.com/N6aCC0IM)

### Steps to reproduce
一直点击 `添加`  按钮，Tabs组件超过一定数量就会出现bug，很容易复现此bug

### What is expected?
Tabs组件 新增tab，置于最后端，而不是错乱

### What is actually happening?
Tabs组件 无限新增tab，位置不是错乱

**Comment by shizhenbin** [comment]
![image](https://user-images.githubusercontent.com/25336063/55540493-b4b13780-56f5-11e9-9e05-a3af02692c8d.png)

加个index属性就好了

![image](https://user-images.githubusercontent.com/25336063/55540576-dca09b00-56f5-11e9-8331-f3aa9cfddb42.png)

**Comment by shizhenbin** [comment]
@xkcoding

**Comment by xkcoding** [comment]
@shizhenbin 这个应该属于bug
