### ISSUE TITLE
[Feature Request] The drag-and-drop position of the dialog box can be the entire position of the dialog box (currently only the head of the dialog box can be dragged), or the dialog box supports mouse resizing.

### ISSUE THREAD

**Issue by linning9527** [iview/iview#5564]
### What problem does this feature solve?
当对话框比较大的时候，拖拽的头部移出显示界面，无法把对话框拉回显示界面。
在对话框中显示图片，图片较大，控制大小。

### What does the proposed API look like?
开启可拖拽后，拖拽范围是对话框的全部位置；
开启对话框的大小调整，在鼠标移动到对话框四角的时候可改变对话框大小。
`<Modal drag-area="all" change-size="True"></Modal>`

**Comment by icarusion** [comment]
No such plan.
