### ISSUE TITLE
建议：Menu 多级菜单

### ISSUE THREAD

**Issue by Ayerss** [iview/iview#557]
现在官网上menu的响应式缩小后只能1级菜单，https://codepen.io/rijn/pen/qRXWGQ
是否能增加hover后在菜单右侧竖排显示2级菜单。感觉这个需求应该会有吧，还是说其实有这功能只是案例上没有展示出来？
![123](https://cloud.githubusercontent.com/assets/16594262/24543427/41f3daa0-1632-11e7-9329-d1c9b3e1b8bb.jpg)

**Comment by CodeMonkeyXu** [comment]
左右布局时，要实现三级菜单怎么实现嵌套呢

**Comment by lvqingan** [comment]
我也需要这个功能，做成AdminLTE那样的就行

**Comment by xland** [comment]
在很多场景下确实需要多级菜单，想提交代码，但是源码跑不起来，提示缺少gulpfile
#645

**Comment by beyondskyway** [comment]
想知道，现在多级菜单怎么实现？

**Comment by Teddy-Zhu** [comment]
同样需求这样的功能

**Comment by CodeMonkeyXu** [comment]
目前我只能手写了

**Comment by findwisdom** [comment]
自己用JQ 写了一个。。。。

**Comment by easyfrog** [comment]
在做一个编辑器的界面. 会使用到多级菜单.  希望可以加入.. 的确是很常用的一个功能.

**Comment by kude123** [comment]
ant的多级菜单就很好.

**Comment by duandun** [comment]
需要+1

**Comment by zhangyaoFkr** [comment]
+1

**Comment by nextdooroldwang** [comment]
+1 请问这个功能计划更新不，大概什么时候能出。

**Comment by Alice2222** [comment]
很多侧边栏菜单的都三级以上菜单以及响应式的折叠，实现了这种功能 比如metisMenu,饿了么的menu组件等，为啥iview就不关注这种需求？

**Comment by 965498154** [comment]
+1

**Comment by icarusion** [comment]
added in 2.9.0
