### ISSUE TITLE
Functional split of resetFields method for [Feature Request] form validation


### ISSUE THREAD

**Issue by HBaylor** [iview/iview#5573]
### What problem does this feature solve?
“对整个表单进行重置，将所有字段值重置为空并移除校验结果” 这是官方的描述  在使用vuex来管理表单数据的时候 vuex
不允许直接对表单数据新型修改 所以这个字段值置空会让vuex报错

### What does the proposed API look like?
希望有一个单纯的移除校验结果的方法  不改变表单的值

**Comment by icarusion** [comment]
No such plan.
