### ISSUE TITLE
[Bug Report]Slider bind with on-input triggered of value change.

### ISSUE THREAD

**Issue by xqdoo00o** [iview/iview#5609]
### Environment
Windows 10/Chrome 73.0.3683.86/Vue 2.6.10

### Reproduction link
[https://jsfiddle.net/x9n7boqj/](https://jsfiddle.net/x9n7boqj/)

### Steps to reproduce
open the console, each second console a new 'triggered'.

### What is expected?
on-input event not triggered with value changed in vue method, but only with user mouse drag from UI。

### What is actually happening?
on-input event triggered with value changed in vue method.

---
It's a mixin of UI and code logic。
The event defined in UI should only triggered from UI.
If someone change the value with vue method, he never want trigger a method which used in UI.

**Comment by dobbycong** [comment]
I have this problem too, please fix it.
