### ISSUE TITLE
icon在vue项目中不能正常使用

### ISSUE THREAD

**Issue by 354739194** [iview/iview#5610]
已经全局引入iview插件，其他组件都能正常使用，然而icon却无法使用，在项目中占位是0*0，手动赋值给宽高业没有用

**Comment by daGaiGuanYu** [comment]
我之前也是，最后发现 icon 是从 iview 第一版里复制到的图表。可以先看看你的图标是不是从当前版本的 iview 里找的

**Comment by 354739194** [comment]
已经解决了，正是像你说的版本不对导致的，非常感谢


------------------ 原始邮件 ------------------
发件人: "关于"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 下午4:12
收件人: "iview/iview"<iview@noreply.github.com>;
抄送: "建午"<354739194@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [iview/iview] icon在vue项目中不能正常使用 (#5610)




我之前也是，最后发现 icon 是从 iview 第一版里复制到的图表。可以先看看你的图标是不是从当前版本的 iview 里找的
