### ISSUE TITLE
i-table分页无法显示数据

### ISSUE THREAD

**Issue by kcjian** [iview/iview#563]
### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
 2.2.1

### 能够复现问题的在线示例（重要）
[示例](https://codepen.io/anon/pen/NpeQJo)

### 问题现象，以及你期望的结果是怎样的?
iview官方文档的table分页例子,不用nodejs,改成html,数据出不来,点击下一页报错:
this.data.forEach is not a function

**Comment by icarusion** [comment]
你代码写错了。
```js
data () {
    return {
        tableData1: this.mockTableData1()
    }
}
```
