### ISSUE TITLE
通过全局script标签使用iview提示组件未注册

### ISSUE THREAD

**Issue by mosquito1994** [iview/iview#565]
使用的vue和iview都是最新的2.x版本

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>vue_test</title>
  </head>
  <body>
    <div id="app"></div>

	<script src="./static/jquery.min.js"></script>
	<script src="./static/vue.min.js"></script>
	<script src="./static/vue-router.min.js"></script>
	<script src="./static/vuex.min.js"></script>
	<script src="./static/iview.min.js"></script>
  </body>
</html>
```
这里的min.js都是从bootstrap cdn上拿到的 文件路径也没有问题
结合vue-cli实际使用时，本地运行npm run dev，浏览器报错组件未注册
![image](https://cloud.githubusercontent.com/assets/12527771/24576229/9ac76a94-16ea-11e7-9c04-ef36e7ee4da6.png)
但是使用npm run build之后的文件却能正常运行 请问是什么原因？

**Comment by icarusion** [comment]
貌似是你配置问题，查看文档示例里的 script 代码

**Comment by mosquito1994** [comment]
@icarusion  我使用vue-cli build之后的代码是没有问题的 本地跑起来之后vue实例化也是在vue等脚本引入之后才进行的 看文档示例除了没有用vue-cli之外都是正常引入vue、iview就可以的啊
![image](https://cloud.githubusercontent.com/assets/12527771/24576772/ca831d1e-16f4-11e7-9d1a-50e0fd15aaf0.png)

**Comment by docikaci** [comment]
遇到同样的问题 ， cdn 全局引入， 但是提示未注册。。。
