### ISSUE TITLE
带搜索的Select组件交互问题

### ISSUE THREAD

**Issue by starding** [iview/iview#566]
### iView 版本号
2.0.0-rc.8

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.6

### 问题现象，以及你期望的结果是怎样的?

当前带搜索的Select组件交互如下：

1. 搜索关键词，并选中结果
2. 结果会显示在select框中，但再次点击希望切换其他选项时，就会发现这个时候其他选项是隐藏的。

<img width="461" alt="2017-04-01 4 04 38" src="https://cloud.githubusercontent.com/assets/3321046/24576789/fa3f86aa-16f4-11e7-92b2-9f4ab45f7514.png">

也就是说，当select搜索完成后，这个Select组件就**失去了查看待选options的能力**

可对比Elements的交互

<img width="370" alt="2017-04-01 4 05 48" src="https://cloud.githubusercontent.com/assets/3321046/24576804/20aef762-16f5-11e7-9047-8fb44a747ee5.png">

或者Ant Design的
<img width="356" alt="2017-04-01 4 07 19" src="https://cloud.githubusercontent.com/assets/3321046/24576818/55118eca-16f5-11e7-9ea4-14989c31e4e1.png">

### 你估计可能的原因是什么（选填）？

设计上的失误：因为一个失去查看options能力的组件，已经不能称为select了，它更像一个输入框

**Comment by maxid** [comment]
建议增加Asynchronous select组件
https://monterail.github.io/vue-multiselect/#sub-getting-started
