### ISSUE TITLE
vue2.2.2中使用iview 2.0-rc9 tabale组件的render出错

### ISSUE THREAD

**Issue by redskyhack** [iview/iview#567]
### 问题现象，以及你期望的结果是怎样的?
如题，中vue 2.2.2中，使用iview2.0-rc9作为ui组件，在引用table组件时，期望最后一列为操作列，里面放置“查看，修改，添加”三个按钮，并绑定相应的方法，结果按照手册中的示例代码出错：

`render: function(row, column, index) {
                        return '<i-button type="primary" size="small" @click="show(${index})">查看</i-button> <i-button type="error" size="small" @click="remove(${index})">删除</i-button>'
                    } `

### 运行报错：

`[Vue warn]: Error compiling template:
<i-button type="primary" size="small" @click="show(${index})">查看
- invalid expression: @click="show(${index})"`
### 错误定位到：

`var res = _vue2.default.compile(cell.outerHTML);`

不知道什么原因，希望大神解决！

**Comment by icarusion** [comment]
提供在线代码
