### ISSUE TITLE
[Bug Report] Version 3.4.0 and version 3.4.0 merged differently


### ISSUE THREAD

**Issue by liucien** [iview/iview#5690]
### Environment
win10/chrome73.0.3683.103/ iView Run内得vue版本

### Reproduction link
[https://run.iviewui.com/MLLs3Rax](https://run.iviewui.com/MLLs3Rax)

### Steps to reproduce
点击刷新表格对data重新赋值，iview3.4.0以下版本正常，3.4.0版本表格顺序错乱，貌似是display执行了none,但3.4.0以下版本并不会

### What is expected?
与iview3.4.0以下版本执行结果相同

### What is actually happening?
有差异

**Comment by fengguoqing** [comment]
你这个问题应该是v-for的key值引起的，在3.4.0中新增row-key字段，你可以强制生成key，保证正常刷新。
我刚测试过了，可以正常显示了

**Comment by liucien** [comment]
好的，谢谢
