### ISSUE TITLE
能不能实现一个属性定义是圆角还是直角的呢，这样能满足更多的需求

### ISSUE THREAD

**Issue by zhihuihu** [iview/iview#57]
能不能实现一个属性定义是圆角还是直角的呢，这样能满足更多的需求，、
默认就是圆角的

**Comment by icarusion** [comment]
不是所有的组件都是表单类。。。
比如即将发布的 0.9.7 版本，在Button里就支持到了圆角。

**Comment by zhihuihu** [comment]
你的大多数的组件都是圆角的，希望能出现控制直角还是圆角这个属性

**Comment by hmdeng110** [comment]
你可以试试去less主题文件里把圆角值搞成0，编译

**Comment by icarusion** [comment]
组件的意义就是一套规范的设计。我们的设计都是经过设计团队斟酌的，如果你坚持，就目前来看可以自己修改 src/styles/themes/default/custom.less 里的配置，未来我们会提供一个可视化的皮肤编辑器。

**Comment by zhihuihu** [comment]
恩恩，希望你们做的更好，线目前，这些组件满足大多数的需求，O(∩_∩)O谢谢 @icarusion
