### ISSUE TITLE
upload的自定义数据data传递不过去？

### ISSUE THREAD

**Issue by chinavane** [iview/iview#570]
```
 <Upload type="drag" multiple 
      action="http://localhost:3000/uploads/filedata" 
      :data="postData"
      name="avatar" 
      :format="['jpg','jpeg','png']" 
      :max-size="100" 
      :before-upload="handleBeforeUpload"
      :on-success="handleSuccess" 
      :on-format-error="handleFormatError" 
      :on-exceeded-size="handleMaxSize">
```
```
 postData:{
          _id: null //这里改变一定的值
        }
```

**Comment by rijn** [comment]
Remove the underscore.

**Comment by chinavane** [comment]
修改成id也不行。

**Comment by rijn** [comment]
Please provide online fiddle

**Comment by icarusion** [comment]
或许是你后端接收的问题，传数据亲测没有问题。请与后端核查后再提供在线示例。

**Comment by chinavane** [comment]
分析了数据传递模式，是form-data模式，所以在nodejs端不能只以req.params/req.query/req.body的形式进行接收数据，需要利用formidable等模式进行支撑。

**Comment by lichinlichin** [comment]
@icarusion hi~
I need put an uuid of the selected file into postData
so I tried to change the postData in 'before-upload' , but it didn't work
and also I tried to use return promise for setTimeout to set postData, it also failed
did I wrong?
your reply will be highly appreciated!

**Comment by mcxu2333** [comment]
@lichinlichin  same problem with this ;

any fix ?

**Comment by mcxu2333** [comment]
@lichinlichin you should trigger upload with manually.

```javascript
<Upload ref="file" :multiple="true" :action="upload.action" :on-success="success" :before-upload="before" :format="['ppt','pptx','mp4']"><Button type="primary">本地上传</Button></Upload>
```

```javascript

data(){
    files:[]
}

```

```javascript

before(file) {

    this.upload.files.push({
        file: file,
        data: {
            OSSAccessKeyId: this.upload.oss.OSSAccessKeyId,
            Signature: this.upload.oss.Signature,
            policy: this.upload.oss.policy,
            success_action_status: 200,
            key: `image/${localStorage.getItem('shop')}/${uuid()}.${file.name.substr(file.name.lastIndexOf('.') + 1)}`
        }
    });

    return false;
}

```
```javascript

//maybe this trigger with some button @click
uploadFile() {

    for (let f of this.upload.files) {

        this.$refs.file.data = f.data;
        this.$refs.file.post(f.file);
    }
}
```

**Comment by mcxu2333** [comment]
@icarusion 可否考虑 data 属性可以是每个 request 单独定义，因为 同一个上传组件，上传多个文件时候 传递的参数是可能变化的，目前没找到合适的方式来处理这个可变的参数，以上解决方案并不是非常理想

**Comment by zhangchao1** [comment]
your upload compoment support flash upload type?

**Comment by zhangchao1** [comment]
@icarusion

**Comment by kennish** [comment]
@mcxu2333 我也遇到了你描述的问题，上传多个文件时传递，需要给每一个文件添加单独说明，我想的是在before-upload里面去动态改变参数值，但事实是只认第一次的值，请问你解决了吗

**Comment by mcxu233** [comment]
@kennish 这个时间太久已经忘了，抱歉

**Comment by helloleaf** [comment]
this.$refs.file.data = this.data;
这样可以

**Comment by seminelee** [comment]
@helloleaf 但是会报错
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "data"

**Comment by selma-li** [comment]
vue的双向绑定是通过`Object.defineProperty()`来劫持各个属性的`setter`，`getter`。
所以，在这个例子中，当我们要给`data`绑定的对象`postData`增加属性时，子组件监听不到`data`的变化。我们可以用`vm.$set( target, key, value )` 来设置对象属性
`this.$set(this.postData, '_id', 'newVal')`

simple translation:
`postData` is a object. When we add a new property to an observed object, we cannot add it directly. We should use the `vm.$set( target, key, value )` method.
try this
`this.$set(this.postData, '_id', 'newVal')`

**Comment by Otis-Lee** [comment]
请问楼主 解决了吗？我也遇到这样的问题了
