### ISSUE TITLE
项目打包后字体图标丢失

### ISSUE THREAD

**Issue by couldJoker** [iview/iview#573]
### iView 版本号

2.0.0-rc.5
### 操作系统/浏览器 版本号

windows 7/Chrome 56
### 问题现象，以及你期望的结果是怎样的?
项目框架是使用iview的脚手架搭建的，现在使用npm build之后，iview的字体图标都会丢失，错误的原因是路径错误，原生的环境dist目录非常清晰，可以在css中修改引用路径，但iview的环境下我没找到如何修改路径
### 你估计可能的原因是什么（选填）？
css中引用的字体图标文件路径有问题

**Comment by icarusion** [comment]
https://github.com/iview/iview-project

**Comment by luo772435545** [comment]
在多页面中，还是存在这样的问题
