### ISSUE TITLE
分页组件如何设置当前页

### ISSUE THREAD

**Issue by hansen2014** [iview/iview#574]
### iView 版本号

2.0.0-rc.9

### 操作系统/浏览器 版本号

macOS/Chrome 56

### Vue 版本号

2.2.6

### 问题现象，以及你期望的结果是怎样的?
分页组件初始化后，并且选择了页码，如何设置返回第一页。
current = 1 不起作用， 简单来说就是组件刷新。

**Comment by hansen2014** [comment]
<Page :total="totalRow" :current="current"  :page-size="pageSize" @on-change="changePage"></Page> 
设置 current 无效

**Comment by icarusion** [comment]
提供在线示例
