### ISSUE TITLE
[Bug Report]select组件远程搜索-render中使用-有默认值的情况下点击后会值消失

### ISSUE THREAD

**Issue by longPanda** [iview/iview#5748]
### Environment
window10/chrome73.0.3683.103（正式版本） （64 位）/"vue": "^2.5.13"

### Reproduction link
[https://run.iviewui.com/PzbC7rqa](https://run.iviewui.com/PzbC7rqa)

### Steps to reproduce
select组件远程搜索-render中使用-有默认值的情况下点击后会值消失

### What is expected?
有默认值的情况下，点击获取焦点时，再失去焦点时在不选择的情况下值不应该消失

### What is actually happening?
有默认值的情况下，点击获取焦点时，再失去焦点时在不选择的情况下值会消失

---
只在render函数中才会有这个情况

**Comment by coveyz** [comment]
别的情况也会有@@

**Comment by longPanda** [comment]
@coveyz 你也遇到了？

**Comment by coveyz** [comment]
@longPanda  
我是先数据回填 - 然后删除 - 接着填写我要查询的 - 然后 能查到我想要的  - 但是点击之后 拿到的数值 不对

**Comment by coveyz** [comment]
但是 我看  有个大佬 提过这个问题  
官网给出的 答复是  使用者 使用的问题 并不是一个bug

**Comment by longPanda** [comment]
@coveyz 提了好几次，没答复，好郁闷
