### ISSUE TITLE
希望spin 添加fix后，背景色不是全白的，而是带点透明的灰色

### ISSUE THREAD

**Issue by Smith-Cruise** [iview/iview#575]
### iView 版本号
`2.0.0-rc.5 `

### 操作系统/浏览器 版本号
`macOS/Chrome 56 `

### Vue 版本号
` 2.2.1 `

### 能够复现问题的在线示例（重要）
```
<Spin size="large" fix v-if="spinShow"></Spin>
```
### 问题现象，以及你期望的结果是怎样的?
```
希望添加fix后，背景不是全白的且不透明的，而是能够带点透明的灰色，可以参考ElementUI的 Loading加载
因为这样用户的体验更好一点，不然暗色系的网站一用spin，中间一块白的很难受
```

**Comment by eeve** [comment]
```
ivu-spin-fix {
    background-color: rgba(255, 255, 255, 0.5);
}
```

**Comment by microboat** [comment]
`.ivu-spin-fix {
  display: block;
  background-color: rgba(255, 255, 255, 0.6);
  .ivu-spin-main {
    position: absolute;
    left: 50%;
    top: 50%;
    width: auto;
    height: auto;
    transform: translate3d(-50%, -50%, 0);
  }
}
`

**Comment by microboat** [comment]
.ivu-spin-fix {
  display: block;
  background-color: rgba(255, 255, 255, 0.6);
  .ivu-spin-main {
    position: absolute;
    left: 50%;
    top: 50%;
    width: auto;
    height: auto;
    transform: translate3d(-50%, -50%, 0);
  }
}

**Comment by microboat** [comment]
`.ivu-spin-fix {
  display: block;
  background-color: rgba(255, 255, 255, 0.6);
  .ivu-spin-main {
    position: absolute;
    left: 50%;
    top: 50%;
    width: auto;
    height: auto;
    transform: translate3d(-50%, -50%, 0);
  }
}`

**Comment by icarusion** [comment]
fixed already
