### ISSUE TITLE
[Bug Report] tabs nesting error


### ISSUE THREAD

**Issue by kouxiangdong** [iview/iview#5756]
### Environment
window10/ Google Chrome  69.0.3497.100/2 

### Reproduction link
[https://run.iviewui.com/preview/xp6tMLBn](https://run.iviewui.com/preview/xp6tMLBn)

### Steps to reproduce
tabs中一个tab嵌套一个tabs 嵌套tabs的item元素跑到父tabs中items了

### What is expected?
子tabs元素不出现在父tabs元素中

### What is actually happening?
出现了

**Comment by Daniel-yim** [comment]
@kouxiangdong 这个是iview的使用问题，只是文档并没有表述很清楚，具体应用如下：

示例地址：https://run.iviewui.com/bTHSnysk

总的为：
Tabs: 
    name 定义选项卡名称。
    value 为内容面板的name值

Tab-pane:
   name 定义面板名称，供Tab的value属性使用
   label 定义选项卡显示标题
   tab 定义所属的Tabs组件，为Tabs的name

示例摘要如下，也可通过连接查看。谢谢！

<Tabs value="a1" name="tab1">
   <Tab-pane label="翀儿" name="a1" tab="tab1">
         <Tabs value="b1" name="tab2">
             <Tab-pane label="chonger.org" name="b1" tab="tab2">

             </Tab-pane>
             <Tab-pane label="daniel" name="b2" tab="tab2">

             </Tab-pane>
         </Tabs>
    </Tab-pane>
</Tabs>

刚去查了下，找了下最新的官方文档：https://www.iviewui.com/components/tabs 是有介绍的。我有时候看的文档也会是https://iview.github.io， 时常分不清楚为什么有那么多，却不统一。

**Comment by DebugIsFalse** [comment]
#6279
