### ISSUE TITLE
Page:分页控件建议

### ISSUE THREAD

**Issue by xugege** [iview/iview#576]
# 分页控件使用场景
一般分页控件都是放在表格下面，所以分页控件可能一般都是放在页面的最底部，但是分页控件的size下拉选择是向下弹出，往往把页面容器撑大，或者页面容器设置overflow：hidden导致被隐藏

# 建议
 分页控件的弹出做成一个默认向上弹出，同时支持可配置placement

**Comment by icarusion** [comment]
已知问题，后续会优化
