### ISSUE TITLE
[Bug Report]Disable DatePicker but still click and trigger the event and change the value.

### ISSUE THREAD

**Issue by HaihongLiu** [iview/iview#5779]
### Environment
win10,   chrome74.0.3729.131  vue2.5.2 iview2.7.4

### Reproduction link
[https://jsfiddle.net/m4yxjd06/4/](https://jsfiddle.net/m4yxjd06/4/)

### Steps to reproduce
Disable this component using the DatePicker component, disabled="true"

### What is expected?
The color is grayed out, the mouse hover shows the forbidden icon, and the click cannot be clicked.

### What is actually happening?
The color is grayed out, the mouse hover shows the forbidden icon, you can still click, and the click time is triggered, and the time is selected.

---
This problem cannot be reproduced, but it does exist in the project.

**Comment by money4marry** [comment]
i have same problem in my project. 
This problem cannot be reproduced on my computer which browser is chrome 74.0.3729.169（64-bit） but its reproduced on my co-worker's computer which browser is same version.
fyi, i add  a css attribute <"pointer-events: none;"> in that disabled datepicker's wrapper div, can fix my problem for the project.
----------------------------------------------------渣英文，下面是翻译
我遇到了同样的问题，74.0.3729.169（64-bit）我的电脑没复现，但是同事的电脑相同版本也复现了，定位不到问题，暂时在禁用的datepicker最外层容器上加了一行css，<"pointer-events: none;"> 阻止点击事件，暂时解决了我的问题。以供参考

**Comment by HaihongLiu** [comment]
@money4marry  
Thank you very much! The method you provided is really effective, I haven't found a better way yet.
````````````````````````````````````````````````````````````````````````````````
非常感谢，你提供的办法确实有效，暂时还没找到更好的方法。
