### ISSUE TITLE
[Bug Report] ColorPicker component in render or style is affected by the parent (obscured)


### ISSUE THREAD

**Issue by longPanda** [iview/iview#5780]
### Environment
window10/chrome/vue3

### Reproduction link
[https://run.iviewui.com/7Usx6lm1](https://run.iviewui.com/7Usx6lm1)

### Steps to reproduce
在table组件中点击ColorPicker颜色组件样式变形，应该是被父级影响

### What is expected?
正常展示

### What is actually happening?
样式变形，应该是被父级影响

**Comment by msidolphin** [comment]
你可以把transfer属性置为true
