### ISSUE TITLE
建议：menu文档添加响应事件（@on-select）

### ISSUE THREAD

**Issue by hyjfine** [iview/iview#579]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
建议：menu响应事件（@on-select）没有体现在文档上，希望加上，这样新手可以不用看源码就知道怎么写，会比较友好些。

**Comment by DevilTears** [comment]
我看了，半天你们说的@on-select，我还是不知道肿么写

**Comment by hyjfine** [comment]
类似这样
 `<div class="feature-select">
                <Menu mode="horizontal" active-name="1" @on-select="featureSelect">
                    <div class="layout-assistant">
                        <Menu-item name="1" >总览</Menu-item>
                        <Menu-item name="2" >升级</Menu-item>
                    </div>
                </Menu>
 </div>`
