### ISSUE TITLE
[Bug Report] radio on-change event unavailable


### ISSUE THREAD

**Issue by sensengk** [iview/iview#5797]
### Environment
window google56 vue2.6

### Reproduction link
[https://www.iviewui.com/components/radio](https://www.iviewui.com/components/radio)

### Steps to reproduce
引入radio 组件，使用on-change 无效

### What is expected?
radio 组件，使用on-change 生效

### What is actually happening?
radio 组件，使用on-change 无效

**Comment by msidolphin** [comment]
重新不了，你能帖下你的代码吗？

**Comment by DebugIsFalse** [comment]
你多看官网文档这个应该没啥问题
