### ISSUE TITLE
menu 组件 active-name bug

### ISSUE THREAD

**Issue by tkggusraqk** [iview/iview#581]
### iView 版本号
2.0.0-rc.9

### 操作系统/浏览器 版本号
 windows/Chrome 56

### Vue 版本号
 2.2.0 

### 能够复现问题的在线示例（重要）

http://jsbin.com/famaya/1/edit?html,js,output

### 复现步骤
直接运行
### 问题现象，以及你期望的结果是怎样的?
已经重置菜单的activiteName=2,可是还是选择的第1 个

**Comment by icarusion** [comment]
类型不对，要区分数字和字符串

**Comment by oliviazhangjuan** [comment]
解决了吗
