### ISSUE TITLE
Switch、Select组件使用动态model 的 BUG

### ISSUE THREAD

**Issue by deboyblog** [iview/iview#582]
### iView 版本号
 2.0.0-rc.9

### 操作系统/浏览器 版本号
window/Chrome 57

### Vue 版本号
 2.1.10

### 复现步骤
![gif](https://cloud.githubusercontent.com/assets/11410323/24645295/30efae30-194a-11e7-9972-f71535db26f5.gif)

### 问题现象，以及你期望的结果是怎样的?
使用原生checkbox select能正常响应动态改变的model 
但是使用iview不行
当我改变了某一行的 是否更新数据库 这个`Boolean`变量 切换到另外一行 状态没有切换过去 
但是原生的是正常的
只有动态赋予model才会这样
select好像也会有这种问题 但是不知道为什么突然重现不了了(可能我后来加了一个空值选项：无校验)
### 你估计可能的原因是什么（选填）？
缺少相应监听事件

**Comment by deboyblog** [comment]
已解决 是我使用问题 用了$set动态改变就好了 再加上一些判断主动去改

**Comment by briefness** [comment]
具体怎么解决的，代码能粘一下吗

**Comment by deboyblog** [comment]
@briefness 我绑定的 `Modal` 是动态的 你的应用场景和我一致?
我使用了官方的 `$set` 方法
```
/* 
* this.dataArr[index] 是数据源
* updateDB 是更改字段
* 最后一个参数是值
*/
this.$set(this.dataArr[index], 'updateDB', true)
```
