### ISSUE TITLE
The search for the [Bug Report] select component does not support double quotes result by selecting the Select component does not support double quotes result


### ISSUE THREAD

**Issue by zystudios** [iview/iview#5835]
### Environment
chrome74  iview 3.4.2

### Reproduction link
[https://run.iviewui.com/oiAbD2gv](https://run.iviewui.com/oiAbD2gv)

### Steps to reproduce
见demo，please see demo at：https://run.iviewui.com/oiAbD2gv

### What is expected?
支持双引号结果选中
support double quotes in select
### What is actually happening?
无法选中带双引号的结果

Cannot be selected if the returned result has double quotes

**Comment by zystudios** [comment]
2 month has passed.....

**Comment by xiebf** [comment]
5 month has passed.....

**Comment by DebugIsFalse** [comment]
#6349
