### ISSUE TITLE
分页如何设置当前页

### ISSUE THREAD

**Issue by hansen2014** [iview/iview#584]
### iView 版本号

2.0.0-rc.9

### 操作系统/浏览器 版本号

macOS/Chrome 56

### Vue 版本号

2.2.6

### 能够复现问题的在线示例（重要）

http://120.27.239.160
使用 15050150329 / johnhan 登录。
全局基本设置 -> 基本计量单位 -> 选择分页组件非第一页 -> 然后再次点击查询，将current 设置为1，不起作用

### 问题现象，以及你期望的结果是怎样的?
分页组件初始化后，并且选择了页码，如何设置返回第一页。
current = 1 不起作用， 简单来说就是组件刷新。

**Comment by icarusion** [comment]
check your code.
```html
<template>
    <div>
        <Page :total="100" :current="current"></Page>
        {{ current }}
        <Button @click="current = 1">set current</Button>
    </div>
</template>
<script>
    export default {
        data () {
            return {
                current: 2
            }
        }
    }
</script>
```

**Comment by hansen2014** [comment]
@icarusion 我在on-change里添加处理：current随事件页码改变而改变才可以。

**Comment by icarusion** [comment]
Vue2 是单向数据流

**Comment by suyuTech** [comment]
我最近也遇到同样问题、看了代码以后才发现初始化的时候父组件设置了初始current为1之后、没有在监听子组件的on-change的事件中去同步这个当前current，之后、在我试图将页码重置到第一页的时候、发现子组件此时无法得知父组件的意图、父组件current没始终没有改变、自然子组件watch中的current并不能被触发。。。

**Comment by guanly** [comment]
楼主这样的问题应该怎么处理好呢

**Comment by guanly** [comment]
我现在是搜索时采用模拟点击第1页的方法实现的，感觉怪怪的

**Comment by hansen2014** [comment]
@guanly 添加on-change事件处理。
