### ISSUE TITLE
table组件title、footer slot不能正确显示

### ISSUE THREAD

**Issue by hezhiying** [iview/iview#585]
### 复现步骤
<Table>
<div slot="footer">页脚不能显示</div>
<div slot="title">页头不能显示</div>
</Table>
### 问题现象，以及你期望的结果是怎样的?
正确显示
### 你估计可能的原因是什么（选填）？
src/components/table/table.vue
658行
 this.showSlotHeader = this.$refs.title !== undefined;
 this.showSlotFooter = this.$refs.footer !== undefined;
应该改为：
 this.showSlotHeader = this.$slots.title !== undefined;
 this.showSlotFooter = this.$slots.footer !== undefined;

**Comment by icarusion** [comment]
#549
