### ISSUE TITLE
table排序时如果排序值是字符串类型的数字则不能进行正确的排序

### ISSUE THREAD

**Issue by Lurkerc** [iview/iview#586]
### iView 版本号
`2.0.0-rc.9`

### 操作系统/浏览器 版本号
`macOS/Chrome 56`

### Vue 版本号
` 2.2.1 `

### 能够复现问题的在线示例（重要）

该问题无需示例

### 问题现象，以及你期望的结果是怎样的?
table排序时如果排序值是字符串类型的数字则不能进行正确的排序，如：
```js
"12" > "110" // true
```

查看源码：`src/components/table/table.vue:467`
```js
if (type === 'asc') {
    return a[key] > b[key] ? 1 : -1;
} else if (type === 'desc') {
    return a[key] < b[key] ? 1 : -1;
}
```
### 你估计可能的原因是什么（选填）？
字符串比较与数字比较不一样，建议做兼容处理
```js
var a = "12",
    b = "110";
(/^\d+$/.test(a) && +a || a) > (/^\d+$/.test(b) && +b || b) // false
```

**Comment by icarusion** [comment]
可以使用自定义排序
