### ISSUE TITLE
关于tree组件半选状态的问题

### ISSUE THREAD

**Issue by eeve** [iview/iview#587]
父节点在半选状态的时候，在某些场景下也算选中的吧？目前在@on-check-change参数中没有半选状态的父节点，可否加一个开关参数来设置此？

现状：
半选节点没有在on-check-change的参数中

期望
半选节点出现在on-check-change参数中

**Comment by fordongu** [comment]
+1

**Comment by icarusion** [comment]
Add new events in the future.
