### ISSUE TITLE
Top in [Bug Report] this. $Message. config does not take effect


### ISSUE THREAD

**Issue by HankBass** [iview/iview#5870]
### Environment
window chrome vue@2.x

### Reproduction link
[https://run.iviewui.com/d14x4khj](https://run.iviewui.com/d14x4khj)

### Steps to reproduce
config.top = 100;
点击按钮，弹出Message，top的配置不生效

### What is expected?
top配置生效

### What is actually happening?
不生效

---
试了下，好像iview@2.x和iview@3.x的都有这个问题，实例是直接用官网的示例创建的

**Comment by jiawulin001** [comment]
top属性只能通过config函数改变
`
this.$Message.config({
                top:100
              });
`
示例：
https://run.iviewui.com/Lmf1jgpO
