### ISSUE TITLE
table col render不能正确渲染

### ISSUE THREAD

**Issue by bao2314483** [iview/iview#588]
### iView 版本号
 2.0.0-rc.9 

### 能够复现问题的在线示例（重要）
此段代码在rc6版本是能正常显示,到了rc9就不能正常显示了
```
{title: '操作',key: 'action',render (row, column, index){
                    return `<i-button type="primary" size="small" @click="show(${index})">查看</i-button> <i-button type="error" size="small" @click="remove(${index})">删除</i-button>`;
                }}
```
浏览器报错提示:
 Unknown custom element: <i-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)
warn

**Comment by icarusion** [comment]
提供在线示例

**Comment by bao2314483** [comment]
我是直接复制官网的demo来,我第一次发issue 不太会搞在线示例

**Comment by icarusion** [comment]
issue要求里面有

**Comment by bao2314483** [comment]
https://codepen.io/bao22314483/pen/RpOZWw   但是我在线是没有问题的,就是项目里面有问题,我也好纳闷

**Comment by icarusion** [comment]
https://github.com/iview/iview-project
你用这个工程试试看

**Comment by bao2314483** [comment]
我自己试下,重新建个项目试试

**Comment by bao2314483** [comment]
我想问下我之前用npm install iview --save安装了最新版本rc6,然而我今天再次npm install iview --save安装了rc9了,package.json也显示使用rc9,是不是这样就算更新版本成功了?
另外一个问题就是table的slot失效问题
https://codepen.io/bao22314483/pen/RpOZWw

**Comment by icarusion** [comment]
```
npm update iview
```
这样更新。Table slot 的问题已经解决

**Comment by bao2314483** [comment]
试了,还是不行 slot也是不行,你看看https://codepen.io/bao22314483/pen/RpOZWw 这个示例,我是用的是rc9的

**Comment by icarusion** [comment]
下个版本才行啊。。。
