### ISSUE TITLE
Menu指令在Menu-item加上@click无效

### ISSUE THREAD

**Issue by 314833234** [iview/iview#589]
iView 版本号
2.0.0-rc.8

操作系统/浏览器 版本号
macOS/Chrome 56

Vue 版本号
2.2.1

复现步骤
点击Menu-item列无法触发click事件。

你估计可能的原因是什么（选填）？
<template>
    <div>
        
        <Row>
            <Col span="24" style="height: 60px; padding: 0 15px; background-color: #f5f7f9; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5)">
                <a href="javascript:;"><img height="100%" src="../images/logo.png"/></a>
            </Col>
        </Row>
        <div style="display: flex; height: 100%; position: absolute; top: 0; left: 0; padding-top: 60px;">
            
            <Menu :theme="theme" active-name="1"  accordion style="overflow-y: auto">
                <Submenu :name="navItem.menuId" v-for="navItem in navDataList">
                    <template slot="title">
                        <Icon type="stats-bars"></Icon>
                        {{navItem.menuName}}
                    </template>
                    <Menu-group :title="navChildItem.menuName" v-for="navChildItem in navItem.leaves">
                        <Menu-item :name="item.menuId" @click="goToPageRouter(item.menuUrl, item.menuName, item.uuid)" v-for="item in navChildItem.leaves">{{item.menuName}}</Menu-item>
                    </Menu-group>
                </Submenu>
            </Menu>

            
            <div style="position: relative; flex: 1; padding: 10px; box-sizing: border-box; overflow-y: auto; background: rgba(114, 114, 114, 0.2);">
                右侧内容
            </div>
        </div>
    </div>
</template>
<script>
    export default {
        data () {
            return {
                // 页面基础信息
                theme: 'dark',//'light'
                navDataList: [
                    {
                        "uuid": 3427754784898560,
                        "menuId": "HR03000",
                        "parentId": "BD00000",
                        "menuName": "组织人事",
                        "menuUrl": "javascript:void(0);",
                        "iconName": "#xe625;",
                        "menuDesc": null,
                        "isSystem": false,
                        "priority": 1,
                        "leaves": [
                            {
                                "uuid": 5000000012466401,
                                "menuId": "HR03901",
                                "parentId": "HR03000",
                                "menuName": "组织管理",
                                "menuUrl": "javascript:void(0);",
                                "iconName": null,
                                "menuDesc": null,
                                "isSystem": false,
                                "priority": 1,
                                "leaves": [
                                    {
                                        "uuid": 3406062829713408,
                                        "menuId": "HR03100",
                                        "parentId": "HR03901",
                                        "menuName": "组织维护",
                                        "menuUrl": "infoSetId:org_list",
                                        "iconName": null,
                                        "menuDesc": "维护组织基本信息",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 5000000012613953,
                                        "menuId": "HR03102",
                                        "parentId": "HR03901",
                                        "menuName": "组织架构图",
                                        "menuUrl": "",
                                        "iconName": null,
                                        "menuDesc": "组织架构图",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 5000000012615828,
                                        "menuId": "HR03103",
                                        "parentId": "HR03901",
                                        "menuName": "快速维护",
                                        "menuUrl": "",
                                        "iconName": null,
                                        "menuDesc": "快速维护组织人事",
                                        "isSystem": false,
                                        "priority": 20,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 5000000022495712,
                                        "menuId": "HR03104",
                                        "parentId": "HR03901",
                                        "menuName": "多组织管理",
                                        "menuUrl": "infoSetId:multi_org",
                                        "iconName": null,
                                        "menuDesc": "多组织维护",
                                        "isSystem": false,
                                        "priority": 20,
                                        "leaves": []
                                    }
                                ]
                            },
                            {
                                "uuid": 5000000012466402,
                                "menuId": "HR03902",
                                "parentId": "HR03000",
                                "menuName": "职位管理",
                                "menuUrl": "javascript:void(0);",
                                "iconName": null,
                                "menuDesc": null,
                                "isSystem": false,
                                "priority": 1,
                                "leaves": [
                                    {
                                        "uuid": 3406066269044736,
                                        "menuId": "HR03200",
                                        "parentId": "HR03902",
                                        "menuName": "职务维护",
                                        "menuUrl": "infoSetId:job_list",
                                        "iconName": null,
                                        "menuDesc": "维护本企业的职务信息",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 3406066654921728,
                                        "menuId": "HR03300",
                                        "parentId": "HR03902",
                                        "menuName": "职位维护",
                                        "menuUrl": "infoSetId:pos_list",
                                        "iconName": null,
                                        "menuDesc": "维护本企业职位信息",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 5000000012469529,
                                        "menuId": "HR03700",
                                        "parentId": "HR03902",
                                        "menuName": "职务体系图",
                                        "menuUrl": "",
                                        "iconName": null,
                                        "menuDesc": "查看职务体系图",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    }
                                ]
                            },
                            {
                                "uuid": 5000000012466403,
                                "menuId": "HR03903",
                                "parentId": "HR03000",
                                "menuName": "员工管理",
                                "menuUrl": "javascript:void(0);",
                                "iconName": null,
                                "menuDesc": null,
                                "isSystem": false,
                                "priority": 1,
                                "leaves": [
                                    {
                                        "uuid": 3406067091130368,
                                        "menuId": "HR03400",
                                        "parentId": "HR03903",
                                        "menuName": "员工维护",
                                        "menuUrl": "infoSetId:person_list",
                                        "iconName": null,
                                        "menuDesc": "维护本企业员工信息及员工事务处理",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002100039469,
                                        "menuId": "HR03500",
                                        "parentId": "HR03903",
                                        "menuName": "汇报关系图",
                                        "menuUrl": "",
                                        "iconName": null,
                                        "menuDesc": "汇报关系展示",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002100044154,
                                        "menuId": "HR03600",
                                        "parentId": "HR03903",
                                        "menuName": "员工结构分析",
                                        "menuUrl": "",
                                        "iconName": null,
                                        "menuDesc": "员工结构分析",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 5000000012494393,
                                        "menuId": "HR03601",
                                        "parentId": "HR03903",
                                        "menuName": "人员流动分析",
                                        "menuUrl": "",
                                        "iconName": null,
                                        "menuDesc": "人员流动分析",
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    }
                                ]
                            },
                            {
                                "uuid": 5000000133348258,
                                "menuId": "HR03105",
                                "parentId": "HR03000",
                                "menuName": "MQ发送异常列表",
                                "menuUrl": "infoSetId:org_mqfail",
                                "iconName": null,
                                "menuDesc": null,
                                "isSystem": false,
                                "priority": 1,
                                "leaves": []
                            }
                        ]
                    },
                    {
                        "uuid": 3449477278427136,
                        "menuId": "HR06000",
                        "parentId": "BD00000",
                        "menuName": "时间管理",
                        "menuUrl": "javascript:void(0);",
                        "iconName": "#xe626;",
                        "menuDesc": null,
                        "isSystem": false,
                        "priority": 1,
                        "leaves": [
                            {
                                "uuid": 5000000012466404,
                                "menuId": "HR06901",
                                "parentId": "HR06000",
                                "menuName": "业务设置",
                                "menuUrl": "javascript:void(0);",
                                "iconName": null,
                                "menuDesc": null,
                                "isSystem": false,
                                "priority": 1,
                                "leaves": [
                                    {
                                        "uuid": 2000002000031469,
                                        "menuId": "HR06500",
                                        "parentId": "HR06901",
                                        "menuName": "考勤规则",
                                        "menuUrl": "infoSetId:timeSetAttendanceRules",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002000031470,
                                        "menuId": "HR06501",
                                        "parentId": "HR06901",
                                        "menuName": "考勤档案",
                                        "menuUrl": "infoSetId:timeSetAttendanceRecord",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002000031471,
                                        "menuId": "HR06525",
                                        "parentId": "HR06901",
                                        "menuName": "排班管理",
                                        "menuUrl": "infoSetId:timeSetSchedulingManagement",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    }
                                ]
                            },
                            {
                                "uuid": 2000002000196190,
                                "menuId": "HR06512",
                                "parentId": "HR06000",
                                "menuName": "数据处理",
                                "menuUrl": "javascript:void(0);",
                                "iconName": null,
                                "menuDesc": null,
                                "isSystem": false,
                                "priority": 1,
                                "leaves": [
                                    {
                                        "uuid": 2000002000031472,
                                        "menuId": "HR06515",
                                        "parentId": "HR06512",
                                        "menuName": "时间单据",
                                        "menuUrl": "infoSetId:timeDataTimeDocuments",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002000196191,
                                        "menuId": "HR06520",
                                        "parentId": "HR06512",
                                        "menuName": "打卡记录",
                                        "menuUrl": "infoSetId:timeDataClockIn",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002000031473,
                                        "menuId": "HR06504",
                                        "parentId": "HR06512",
                                        "menuName": "假期汇总",
                                        "menuUrl": "infoSetId:timeDataVacationSummary",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002000031474,
                                        "menuId": "HR06517",
                                        "parentId": "HR06512",
                                        "menuName": "考勤明细",
                                        "menuUrl": "infoSetId:timeDataAttendanceDetail",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 2000002000064730,
                                        "menuId": "HR06518",
                                        "parentId": "HR06512",
                                        "menuName": "考勤汇总",
                                        "menuUrl": "infoSetId:timeDataAttendanceSummary",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    },
                                    {
                                        "uuid": 5000000017124533,
                                        "menuId": "HR06527",
                                        "parentId": "HR06512",
                                        "menuName": "汇总查询",
                                        "menuUrl": "infoSetId:timeDataSummarySelect",
                                        "iconName": null,
                                        "menuDesc": null,
                                        "isSystem": false,
                                        "priority": 1,
                                        "leaves": []
                                    }
                                ]
                            }]
                    }
                ],
            }
        },
        methods: {
            /**
             * 导航跳转路由
             * @param url       url
             * @param title     标题
             * @param pageId    页面id
             */
            goToPageRouter: function(id, title, pageId){
                var _this = this;

                // 标题
                _this.title = title;

                // 没有权限
                if(!id){
                    // 没有权限，关闭操作按钮框和面包屑
                    _this.isAuth = false;

                    // 没有infosetId时，则不请求数据，并提示用户没有权限
                    _this.$Message.info('没有权限，请分配权限后再试');

                    // 跳转至404页面
                    _this.$router.go('/404');

                    // 不执行后面逻辑
                    return;
                }

                // 拥有权限，显示操作按钮框和面包屑
                _this.isAuth = true;

                // 跳转路由
                var routerUrl = id.split(':')[1];
                _this.$router.go('/'+ routerUrl);
            }
        }
    }
</script>

**Comment by dean5277** [comment]
@on-select

**Comment by 314833234** [comment]
@on-select只能获取到name值，我现在是要name值。而是直接传入多个值

**Comment by dean5277** [comment]
on-select 主要获取key,获取到key之后就能对应到 data里的数据。

**Comment by 314833234** [comment]
知道可以这样，但是这样感觉会增加代码量，要是能够像click一样，把当前item里面的值传进去，这样会方便很多

**Comment by dean5277** [comment]
list:[{
 index:"1",
 obj:obj
}]

你只是把循环的内容放到data那里而已.
