### ISSUE TITLE
The format attribute of the [Bug Report] upload component is invalid (official demo)


### ISSUE THREAD

**Issue by zystudios** [iview/iview#5899]
### Environment
最新版本

### Reproduction link
[https://run.iviewui.com/GJN27eoM](https://run.iviewui.com/GJN27eoM)

### Steps to reproduce
  <Upload
        ref="upload"
        :show-upload-list="false"
        :default-file-list="defaultList"
        :on-success="handleSuccess"
        :format="['jpg','jpeg','png']"  //属性无效，此为官方demo
        :max-size="2048"
        :on-format-error="handleFormatError"
        :on-exceeded-size="handleMaxSize"
        :before-upload="handleBeforeUpload"

![image](https://user-images.githubusercontent.com/29728228/59184405-a4f41a80-8ba0-11e9-8326-ad4bf5c62a0b.png)

### What is expected?
属性生效

### What is actually happening?
属性无效

**Comment by cisolarix** [comment]
Same issue encountered.

```
<Upload
      multiple
      type="drag"
      action="/api/upload"
      :on-success="onUploadSucess"
      accept="application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/pdf, application/vnd.openxmlformats-officedocument.presentationml.slideshow, application/vnd.openxmlformats-officedocument.presentationml.presentation"
      :format="['pps', 'mp3']"
    >
         <div style="padding: 20px 0">
        <Icon type="ios-cloud-upload" size="52" style="color: #3399ff"></Icon>
        <p>Upload</p>
      </div>
    </Upload>

```

![image](https://user-images.githubusercontent.com/1845040/59590562-e9426600-911e-11e9-8ff5-91cdac7bf530.png)

**Comment by fancyboynet** [comment]
+1

**Comment by lijiahao8898** [comment]
+1
