### ISSUE TITLE
多个Tab下切换Table渲染不正确

### ISSUE THREAD

**Issue by pengpan** [iview/iview#591]
1、页面多个TAB切换，每个选项卡里是一个Table做数据展示；
      显示的时候只有display:true的table宽度渲染正常，当切到另一个Tab页时这个页面的Table宽度没占满屏；F12看了下table 标签有个style=“width：***” 这个没重新计算啊；（还有另一种情况就是左边的菜单栏我这是可以收缩的其实也就是官方的那种控制 col span = 2 或者 span=4；当我在TAB A 收缩菜单栏，然后再切换到TAB B页面再还原菜单栏-->再点击TAB A 这时TAB里的Table组件宽度超长，F12看也是style=“width：***” 这个没重新计算）

求楼主解决，这个问题导致我都得考虑换其他table组件了

**Comment by icarusion** [comment]
使用 `v-if`

**Comment by icarusion** [comment]
先使用 `v-if`，后面统一优化。

**Comment by pengpan** [comment]
刚看下源码Table 组件下有个 handleResize方法，试了下调用这个方法可以解决table 渲染宽度问题；
不过v-if 不能解决问题啊，你们没激活Tab不只是display：none吗，v-if 是直接不加载

**Comment by icarusion** [comment]
需要你手动判断 v-if 的时机

**Comment by pengpan** [comment]
楼主还是很勤快啊  提问题没几分钟就close了

**Comment by icarusion** [comment]
下个版本会优化这个问题

**Comment by pengpan** [comment]
好，感谢楼主！

**Comment by icarusion** [comment]
@pengpan `Tabs` 下错位的问题，能不能给一个代码片段

**Comment by justnowanna** [comment]
@icarusion 请问这个问题修复了吗？我现在是最新版本，还是遇到这个问题

**Comment by justnowanna** [comment]
看到更新日志里面写的修复了，但是感觉并不是这样

**Comment by zhao-ping** [comment]
我也入了这个坑，经过N久的寻找解决方案，最后找到一个比较折中的方法，只要把Tabs切换时的动画禁用掉就不会出现table宽度一直增加的奇葩BUG了
`<Tabs type="card" :animated="false">`

**Comment by maqingbo** [comment]
我的 tab 里面放的不是 table，而是 iframe，加载时 tabs-content 部分直接飘走了~~类似于 transform: translateX(-100%)，然而此时 F12 查看元素，元素的 transform 值并没有变化，最后也是把切换动画禁掉之后才行。

2019-08-01更新：

把切换动画禁掉之后，tab 间的切换变成了 display: none，于是出现了新 bug，未激活的 tab-content 部分表格和 iframe 无法正常渲染，因为没有初始宽高，[相关问题地址](https://github.com/viserjs/viser/issues/55)。最后决定自己写一个 tab 组件....

2019-08-02更新：

找到问题所在了，是因为 iframe 内部使用了 focus 事件，已经聚焦了的元素会跑到屏幕中间，所以不用禁掉动画。目前正在解决 iframe 内部元素 focus 的问题。

2019-08-05更新：

focus 事件其实是可以传一个参数的，

```js
ele.focus({ preventScroll: false })  // 默认 false
```
所以只要监听 scroll 事件就可以了：

```js
window.addEventListener('scroll', function (e) {
  if (e.target.className === 'tableauWrapTabSty ivu-tabs') {
    // console.dir(e.target)
    e.target.scrollLeft = 0
  }
}, true)
```

- [segmentfault 提问](https://segmentfault.com/q/1010000019957736/a-1020000019983052)

**Comment by jecyu** [comment]
针对 flex-grow 的子元素设置 `overflow: hidden` 或者 `width: 0` 也能起效果，这个是 flex 布局的问题。 @maqingbo

**Comment by maqingbo** [comment]
> 针对 flex-grow 的子元素设置 `overflow: hidden` 或者 `width: 0` 也能起效果，这个是 flex 布局的问题。 @maqingbo

谢谢，但是我的 tab-content 部分嵌套的是表格和 iframe，宽高为 0 的情况下无法正常渲染，我回头再看一下。
