### ISSUE TITLE
Cascader 的事件api提供的太少，不够用，能否增加一个

### ISSUE THREAD

**Issue by Ivorzk** [iview/iview#593]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 复现步骤
我使用的是Cascader 自定义solt的功能，在里面我自定自定义显示我想要的数据格式，如图
![Uploading QQ截图20170405175004.jpg…]()

我的下拉箭头是自己定义的，当我展开以后下拉箭头，会旋转180°，当我不选中Cascader 的列表项，直接点击其它空白区域的时候，下拉面板，已经关闭，这个时候，我需要做的就是将下拉箭头也跟着旋转回来，但是Cascader 只提供了on-change 这一个事件句柄，这个事件句柄很显然在这种场景下，应该还有一个点击空白处关闭下拉面板以后的事件句柄，这个能否提供一下，谢谢。
### 问题现象，以及你期望的结果是怎样的?
其实，我不用这个事件句柄，依然可以做到这个功能，只是如果有就更好了！

**Comment by icarusion** [comment]
Add event `on-visible-change`.
