### ISSUE TITLE
[Feature Request]The impact of iView components with drop-down options (select, DatePicker...) on other element events

### ISSUE THREAD

**Issue by wangjiananWJN** [iview/iview#5945]
### What problem does this feature solve?
我希望能准确表达我的问题，iview 的组件，以 select 为例：

![image](https://user-images.githubusercontent.com/31843613/59756564-8edf0c00-92bc-11e9-845d-7ac391a2c038.png)

当下拉框触发显示的时候，必须需要一次鼠标事件使其隐藏，在这之前，会影响、阻止其他任何事件的发生，这种机制可能解决了一些情况下的体验不佳，
但是有些情况下，我是需要下拉框隐藏事件不会阻止我的其他行为的，比如：

![image](https://user-images.githubusercontent.com/31843613/59757016-6f94ae80-92bd-11e9-8fbf-08426a79d78a.png)

点开了第一个下拉框，再点击第二个的时候，必须先执行第一个下拉框的隐藏事件，体验上，第二个select需要点击两次才能触发；

![image](https://user-images.githubusercontent.com/31843613/59757347-26912a00-92be-11e9-9dc6-07a7c18fd6ce.png)

放在模态框中，这个问题可能会更加明显，我点开了下拉框（没有收起），再点击关闭模态框，这个时候我希望关闭模态框和关闭select下拉框是同时发生，但实际情况是需要点击两次，一次关闭下拉框，第二次才能触发模态框的关闭，这种情况iview有没有处理方式，可能我看文档不太仔细，还请指教！

### What does the proposed API look like?
Components with drop-down boxes can operate concurrently with other times when the drop-down boxes are expanded, and a props value can be used to control whether they are in effect or not.

**Comment by tyf914** [comment]
[[Bug Report]同一页面存在多个DatePicker时需点击两次才能触发 #4043](https://github.com/iview/iview/issues/4043)
我也遇到这种问题了, 类似, 搜到了上面这个, 看来作者不会改了, 自己想想办法吧, 哎

**Comment by tyf914** [comment]
还有这个也提了
[Switching between the two drop-down boxes [Bug Report] [Bug Report] will not immediately pop up the drop-down box #5687](https://github.com/iview/iview/issues/5687)

**Comment by tyf914** [comment]
大佬有找到解决办法么?

**Comment by wangjiananWJN** [comment]
@tyf914 如果非要用iview的话，select可以用Dropdown还原，DatePicker组件的话估计要自己写日期面板，发现elementui是不存在这样的问题的，关键公司项目基本都是用iview构建，换ui框架不可能了，而且iview还是有很多优点的，只能自己造吧

**Comment by icarusion** [comment]
我们是刻意为之，这样的交互符合 W3C 规范，可以在 Mac Chrome 浏览器，用多个原生 Select 展开切换看看。
但考虑到国内很多用户的使用习惯，我们会在 iView 4.0 时，增加全局配置来对所有组件的默认收起交互做控制。
