### ISSUE TITLE
[Bug Report]iview 3.2.2 Under the IE browserSelect , Select component initializes the default value error, and the data is also incorrectly reported.

### ISSUE THREAD

**Issue by sweet369Happpy** [iview/iview#5957]
### Environment
window 64/IE 11 /iview3.2.2

### Reproduction link
[https://run.iviewui.com](https://run.iviewui.com)

### Steps to reproduce
1: Code written using the example https://run.iviewui.com/;
2: Assign value to model1 ‘London’;
3: The console reports an error 'Error in mounted hook: "TypeError: The object does not support the "find" attribute or method "";
4：Error [[Vue warn]: Error in nextTick: "TypeError: Object does not support "find" property or method" when changing the value of the drop-down boxError [[Vue warn]: Error in nextTick: "TypeError: Object does not support "find" property or method" when changing the value of the select component

### What is expected?
1: The default value of the initialization select component should be displayed correctly.
2: When changing the value of the select component, it should be switched correctly and the console will not report an error.

### What is actually happening?
1：The console reports an error 'Error in mounted hook: "TypeError: The object does not support the "find" attribute or method "";
2：Error [[Vue warn]: Error in nextTick: "TypeError: Object does not support "find" property or method" when changing the value of the drop-down boxError [[Vue warn]: Error in nextTick: "TypeError: Object does not support "find" property or method" when changing the value of the select component

---
If this problem exists, please ask if the new version has solved the problem?

**Comment by DebugIsFalse** [comment]
es6 to es5 problem
you can try to set babel config
