### ISSUE TITLE
证书有问题啊，chrome都不认了

### ISSUE THREAD

**Issue by istommao** [iview/iview#596]
![image](https://cloud.githubusercontent.com/assets/5070879/24735362/1bd31372-1ab5-11e7-9f94-3af236f27ab3.png)

**Comment by icarusion** [comment]
正在更换中

**Comment by icarusion** [comment]
现在可以了吗

**Comment by icarusion** [comment]
file.iviewui.com 的证书正在更换中

**Comment by istommao** [comment]
![image](https://cloud.githubusercontent.com/assets/5070879/24736548/29c25ece-1abb-11e7-86cc-d02e45ebb089.png)
空白
