### ISSUE TITLE
[Bug Report] Carousel Horselight Abnormality


### ISSUE THREAD

**Issue by iZaiZaiA** [iview/iview#5969]
### Environment
macOS13.6.x / Google Chrome 75.0.3770.100 / Vue 3.7.0

### Reproduction link
[https://run.iviewui.com/hmmf2N0N](https://run.iviewui.com/hmmf2N0N)

### Steps to reproduce
Carousel 在 Drawer 中，不显示内容。

### What is expected?
希望能正常显示

### What is actually happening?
不显示内容，一片空白，CSS背景颜色也无效。

**Comment by demi798** [comment]
@iamzaizai 在drawer组件上使用 v-if 动态切换组件渲染即可解决
