### ISSUE TITLE
upload组件监听不到on-progress事件

### ISSUE THREAD

**Issue by tcshendan** [iview/iview#5976]
upload组件在iview官网中可以监听到on-progress事件， 但是在iview-admin中无法监听

**Comment by ljjandx** [comment]
我也有遇到过这个问题，之前调试iview源码发现原因了，因为用了mock这个工具导致 \iview\src\components\upload\ajax.js中的xhr结果不一致，导致没有触发onprogress方法，目前去掉mock可以解决

**Comment by everhopingandwaiting** [comment]
@ljjandx 这个是必须不用 mock才可以触发吗？ 我 是有部分解决用mock进行了模拟，但是 上传这个是调用的真实后台接口，还是无法触发 on-progress事件

**Comment by tcshendan** [comment]
> @ljjandx 这个是必须不用 mock才可以触发吗？ 我 是有部分解决用mock进行了模拟，但是 上传这个是调用的真实后台接口，还是无法触发 on-progress事件

确实是mock的原因。我去掉了mock后是可以触发on-progress事件的。你可以调试下看下ajax.js里的on-progress有没有触发

**Comment by tcshendan** [comment]
> 我也有遇到过这个问题，之前调试iview源码发现原因了，因为用了mock这个工具导致 \iview\src\components\upload\ajax.js中的xhr结果不一致，导致没有触发onprogress方法，目前去掉mock可以解决

是的，我也通过调试发现了，这个还是很坑的
