### ISSUE TITLE
Form默认FormItem 间隔太大 --优化

### ISSUE THREAD

**Issue by pengpan** [iview/iview#599]
环境：iview 2.0.0-rc.7 vue:2.2.0

问题描述：
Form表单有多个FormItem，默认情况下 
.ivu-form-item{
   margin-bottom: 24px;
}
那开始我觉得这个间距太大了 手动改了
.ivu-form-item{
   margin-bottom: 10px;
}
后来Form校验数据不通过时，错误信息就显示不完整了。必须的把 margin-bottom 改成24px;，所以这希望楼主可以组件里动态的控制这个间距，比如正常情况 10px 、15px，但调用validate 返回false时，组件自动把 margin-bottom 设置为24px；

希望楼主后续可以优化这些细节地方；

**Comment by zixuzhang** [comment]
same
