### ISSUE TITLE
通过按钮，触发tabel的全选方法

### ISSUE THREAD

**Issue by zwzw911** [iview/iview#600]
### iView 版本号
2.0.0-rc.9 

### 操作系统/浏览器 版本号
windows7/FF 52.0.2

### Vue 版本号
 2.2.6 

### 问题现象，以及你期望的结果是怎样的?
Table中全选的功能，只能通过点击表头的check box实现。
期望提供外部方法，以便其他的元素（例如按钮），也能实现全选的功能

**Comment by dean5277** [comment]
官网的demo

 handleCheckAll () {
                if (this.indeterminate) {
                    this.checkAll = false;
                } else {
                    this.checkAll = !this.checkAll;
                }
                this.indeterminate = false;

                if (this.checkAll) {
                    this.checkAllGroup = ['香蕉', '苹果', '西瓜'];
                } else {
                    this.checkAllGroup = [];
                }
            }

**Comment by blue951** [comment]
api中有一个on-select-all事件，如果参数是非空数组说明是取消，否则是全选。  其他api需要改造table插件
