### ISSUE TITLE
[Bug Report]‘暂无数据’在Table内不居中

### ISSUE THREAD

**Issue by 37i3i3** [iview/iview#6015]
### Environment
 iView - 3.4.2

### Reproduction link
[https://run.iviewui.com/fKgmSUkC](https://run.iviewui.com/fKgmSUkC)

### Steps to reproduce
table通过columnData设置若干列，且设置列宽， 使tbody的宽度大于表格宽度；表格无数据，data为空。

### What is expected?
期望：表格没有数据时，不出现横向滚动条，且‘暂无数据’在任何情况下相对表格居中。

### What is actually happening?
实际：table列定宽，内容宽度超过表格宽度，table无数据时，ivu-table-tip的td标签有内联宽度，‘暂无数据’相对ivu-table-tip的td居中，以至于相对表格整体偏右

**Comment by DebugIsFalse** [comment]
你这是使用问题。你看下iview官网示例
