### ISSUE TITLE
表格自定义列模板函数render包含router-link时会报错

### ISSUE THREAD

**Issue by LGerry** [iview/iview#602]
### iView 版本号
2.0.0-rc.9
### 操作系统/浏览器 版本号
win10/Chrome 57

### Vue 版本号
2.2.6
### VueRouter版本号
2.3.0

### 能够复现问题的在线示例（重要）

https://lgerry.github.io/demo/snippet/iview/iview-table-with-vue-router.html
### 复现步骤
表格渲染时就会报错了
### 问题现象，以及你期望的结果是怎样的?
问题现象：操作栏里除了删除按钮还有一个router-link组件，但router-link由于报错没有被渲染
期望结果：希望columns数据项的函数render能够渲染出router-link
### 你估计可能的原因是什么（选填）？
vue-router在子组件中通过其根组件获取router实例，但columns数据项的render函数编译出的组件是孤立的，我是通过指定组件的parent为当前创造出它的组件（即cell.vue）解决的。
``` javascript
//cell.vue methods.compile函数中
const res = Vue.compile(cell.outerHTML);
// todo 临时解决方案
const component = new Vue({
    parent: this, //加了这个就可以了
    render: res.render,
    staticRenderFns: res.staticRenderFns,
    methods: methods,
    data () {
        return $parent._data;
     }
});
```

**Comment by dean5277** [comment]
可以通过事件去跳转。

**Comment by LGerry** [comment]
虽说可以编程式导航，还是觉得这个compile方法不太妥，希望这个临时解决方案能尽快解决

**Comment by icarusion** [comment]
暂不支持 <router-link>

**Comment by xuxiaoxiao312** [comment]
怎么通过事件改变路由呢

**Comment by LGerry** [comment]
@xuxiaoxiao312 应该是这样子：https://codepen.io/anon/pen/wJVEmv
通过监听按钮点击事件，调用router的API
