### ISSUE TITLE
[Bug Report]Modal 对话框的api 'draggable'与  :styles="{top: '200px'}"同时设置，出现的bug;

### ISSUE THREAD

**Issue by Fly-Fly-Fish** [iview/iview#6039]
### Environment
iview 3.4.2

### Reproduction link
[https://run.iviewui.com/preview/hWkjlbTt](https://run.iviewui.com/preview/hWkjlbTt)

### Steps to reproduce
点击Modal可拖动部分；

### What is expected?
modal正常拖动

### What is actually happening?
在设置 :styles="{top: '200px'}" 和属性‘draggable’后点击拖动前会向下位移top的值200px

**Comment by yeheihei** [comment]
+1 同样的问题

**Comment by 9monsters** [comment]
#6201
