### ISSUE TITLE
[Bug Report]select组件使用filterable时出现搜索结果不符问题

### ISSUE THREAD

**Issue by Tracy4ever** [iview/iview#6040]
### Environment
chrome74

### Reproduction link
[https://run.iviewui.com/aeLYvcsC](https://run.iviewui.com/aeLYvcsC)

### Steps to reproduce
输入法一次输入“安徽”两个字，删除“徽”，查看搜索结果

### What is expected?
删除“徽”字后出现包含“安”的搜索结果

### What is actually happening?
显示未搜索前所有选项，不包括“安”的也包含在内

---
实际项目删除“徽”后显示所有选项，不包括“安”的也在内，且optionLabel改成了其他公司名，与showLabel不符合，导致搜索结果奇怪

**Comment by clareli** [comment]
搜索一串数字中的连续几位时，结果基本完全不匹配，期待官方修复

**Comment by clareli** [comment]
当下拉框选项为中文包含数字组合时，例如“教室0028-pxfsdfdf”如果只搜索数字中的某几位，比如‘28’，结果不能准确匹配，希望官方修复这个问题

**Comment by DebugIsFalse** [comment]
请提供一下iview版本号目前3.4.2未出现你说的问题
https://run.iviewui.com/CVRolrNw

**Comment by Tracy4ever** [comment]
> 请提供一下iview版本号目前3.4.2未出现你说的问题
> https://run.iviewui.com/CVRolrNw

上面Reproduction link上的iview版本是3.4.2，奇怪的是我发的链接会有我描述的问题，您发的链接没有出现我描述的问题

**Comment by Tracy4ever** [comment]
您提供的链接也有上述问题，请重新测试，输入“安徽”，删除“徽”，出现不含“安”的搜索结果

**Comment by Tracy4ever** [comment]
> 请提供一下iview版本号目前3.4.2未出现你说的问题
> https://run.iviewui.com/CVRolrNw

您发的连接依然存在上述问题，请重新测试。输入“安徽”，删除“徽”，出现不含“安”的搜索结果

**Comment by Tracy4ever** [comment]
> 请提供一下iview版本号目前3.4.2未出现你说的问题
> https://run.iviewui.com/CVRolrNw

![image](https://user-images.githubusercontent.com/28354034/64766993-79a31200-d579-11e9-805e-fc590349b346.png)

**Comment by Tracy4ever** [comment]
已使用Elment-UI框架解决此问题

**Comment by xlieee** [comment]
可以重写组件的匹配方法

**Comment by Tracy4ever** [comment]
> 可以重写组件的匹配方法

好吧，谢谢，没事，也不是非用iview不可。
