### ISSUE TITLE
[Bug Report]vue cli3 打包时生成的js文件里面有箭头函数

### ISSUE THREAD

**Issue by ChinaMars** [iview/iview#6046]
### Environment
macOS 10.13.6/ie11/vue^2.6.10

### Reproduction link
![image](https://user-images.githubusercontent.com/29267545/61052138-5a72f180-a41d-11e9-95bc-444a6b185afa.png)

### Steps to reproduce
使用vue cli3脚手架按需打包 iview checkbox时，生成的js文件里有箭头函数，倒导ie11语法错误

### What is expected?
按需打包时es6转译成es5

### What is actually happening?
现在vue cli3打包后有es6语法

**Comment by tyuqing** [comment]
这个是因为使用vue-cli3构建时，`babel-loader`会忽略所有`node_modules`中的文件。可以在`vue.config.js`中配置`transpileDependencies`来解决。具体请参考官网配置说明：https://cli.vuejs.org/zh/config/#transpiledependencies
