### ISSUE TITLE
关于iview文档的建议

### ISSUE THREAD

**Issue by ltlwill** [iview/iview#6048]
提个小小的建议，望改进。iview的文档页面体验不好，希望iview的文档页面 左侧导航固定起来，不随右侧文档内容而滚动，每次都得重从头开始滚动页面

**Comment by ltlwill** [comment]
nothing

**Comment by fengluhome** [comment]
你的提议很赞，我费了很大经历优化了一下， 最新访问地址http://iview.talkingdata.com/
