### ISSUE TITLE
[Feature Request]iview文档页面体验改进

### ISSUE THREAD

**Issue by ltlwill** [iview/iview#6049]
### What problem does this feature solve?
提个小小的建议，望改进。iview的文档页面体验不好，希望iview的文档页面 左侧导航固定起来，不随右侧文档内容而滚动，每次都得重从头开始滚动页面

### What does the proposed API look like?
查看组件文档时左侧导航不用每次都从头开始滚动，很麻烦

**Comment by fengluhome** [comment]
已经修复， http://iview.talkingdata.com/
