### ISSUE TITLE
[Bug Report]Tab关闭时，同时会关闭相邻的tab

### ISSUE THREAD

**Issue by taojunnan** [iview/iview#6055]
### Environment
Win10/Chrome74/Vue2.0

### Reproduction link
[https://run.iviewui.com/DeiSaI36](https://run.iviewui.com/DeiSaI36)

### Steps to reproduce
关闭一个tab，如关闭第二个，同时第三个tab也会消失

### What is expected?
关闭一个tab

### What is actually happening?
当前tab被关闭，同时相邻的tab也会消失

**Comment by icarusion** [comment]
加 `key`
