### ISSUE TITLE
button 设置html-type="submit"之后会进行页面跳转

### ISSUE THREAD

**Issue by CarmenHYC** [iview/iview#608]
`<Button html-type="submit" type="success" :loading="loading" @click="submit('formValidate')" long>
    <span v-if="!loading">登录</span>
    <span v-else>正在登录...</span>
</Button>`
button 设置html-type="submit"之后会进行一次页面跳转到/?#/ 再点击才不会提交

**Comment by icarusion** [comment]
provide online code

**Comment by NARUTOne** [comment]
+ 1， 第一次并不会提交，会跳转刷新，  https://codepen.io/NARUTOneFL/pen/BrmJJq?editors=0001

**Comment by NARUTOne** [comment]
已经解决：@submit.native.prevent，请忽略上面嘿嘿
