### ISSUE TITLE
[Bug Report]select 多选框 已选中的item   输入法在中文下  我用键盘的delete键 会把我已选中的item删除

### ISSUE THREAD

**Issue by sohucw** [iview/iview#6082]
### Environment
mac  chrome最新浏览器 vue2.5.6

### Reproduction link
[https://run.iviewui.com/vt6fc1pQ](https://run.iviewui.com/vt6fc1pQ)

### Steps to reproduce
1：先选择 1-2个item
2 切换到中文输入法下   
3 输入 sss  
4 键盘的delete键 一个一个的删除 s

### What is expected?
不删除选中的item 只是删除 输入的拼音 sss

### What is actually happening?
把选择的item删除了

**Comment by sohucw** [comment]
希望作者解决下 感谢！！

**Comment by renhe007** [comment]
+1  求解

**Comment by sohucw** [comment]
求解决 看element-ui组件没有这个问题
