### ISSUE TITLE
请问下table表格组件中是否有点击某个单元格的事件？

### ISSUE THREAD

**Issue by wudisunshine** [iview/iview#609]
### Vue 版本号

比如点击table里面的某个单元格，会出现 一个模态框，把此行的某个数据例如图片展示出来

**Comment by dean5277** [comment]
暂时好像只能用render处理。自己套一个事件。

**Comment by icarusion** [comment]
这种情况应该在 render 里自己绑定事件。

**Comment by sonycamera** [comment]
建议增加单元格点击事件，会方便很多

**Comment by tfzxyinhao** [comment]
在render中可以绑定事件,比如我render出一个div 然后绑定click事件 只能点击文字事触发,如果只有一个字 可点击区域会很小

**Comment by asd8855** [comment]
怎样给table里面的某个单元格，添加悬浮事件和点击事件

**Comment by tfzxyinhao** [comment]
悬浮事件是什么?

**Comment by asd8855** [comment]
类似于hover
