### ISSUE TITLE
[Bug Report]InputNumber组件在form中进行表单验证会误报

### ISSUE THREAD

**Issue by moxao** [iview/iview#6115]
### Environment
win7 / chrome / vue 2.6

### Reproduction link
[https://run.iviewui.com/ekdJPm6R](https://run.iviewui.com/ekdJPm6R)

### Steps to reproduce
直接使用

### What is expected?
正确的验证结果

### What is actually happening?
不管有无内容均报为空

**Comment by msidolphin** [comment]
因为你是数值类型，需要加上type: number

https://run.iviewui.com/Gi8v7VsE

**Comment by DebugIsFalse** [comment]
参照开源的表单验证 async-validator
iview依赖于他开发的，字段定义需要你自己去看下
