### ISSUE TITLE
【Select选择器】遇到转义字符被转义展示在界面上

### ISSUE THREAD

**Issue by p2ng** [iview/iview#613]
### iView 版本号
"iview": "^2.0.0-rc.6"

### 操作系统/浏览器 版本号

win7/Chrome 57.0.2987.133

### Vue 版本号
"vuex": "^2.2.1"

### 能够复现问题的在线示例（重要）

https://codepen.io/fsliangzp/pen/qrGzXX

### 复现步骤
如上链接显示，后端出来的数据确实是这样子的。
`cityList: ['北京', '上海','<广州>']`

### 问题现象，以及你期望的结果是怎样的?
希望展示不要被转义，
`其实通过取{{ model1 }}是没有转义的数据，就是展示的时候被转义了一次`

**Comment by icarusion** [comment]
这是你数据的问题啊

**Comment by p2ng** [comment]
如果是实在改不了后端数据的话，可以用另外一个下拉插件

http://monterail.github.io/vue-multiselect/#sub-custom-option-template

code demo：
https://jsfiddle.net/0Lk6wvcz/

**Comment by thjiang** [comment]
数据中确实有需要"<"、">"的场景啊，这里的XSS用户自己处理就好了吧，感觉是不是没必要强制转义？

**Comment by dmodaii** [comment]
请问你最后是怎么解决的。 这里的  < > 的转义

**Comment by p2ng** [comment]
@dmodaii 
简单的场景有ivue的select，负责的用vue-multiselect
http://monterail.github.io/vue-multiselect/#sub-custom-option-template
