### ISSUE TITLE
[Bug Report]Dropdown 接收了下面 disabled DropItem 的 click 事件

### ISSUE THREAD

**Issue by gaokun** [iview/iview#6135]
### Environment
Macos / Chrome75 / Vue 2.6.10

### Reproduction link
[https://run.iviewui.com/X1td6zVV](https://run.iviewui.com/X1td6zVV)

### Steps to reproduce
见重现链接, 很简单

### What is expected?
Dropdown 不接收 disabled option 的 click事件

### What is actually happening?
点击 Option: 豆汁儿, Dropdown接收到了click事件

**Comment by ddyh0826** [comment]
父级订阅子级了，这样处理下呢？

————————————

onClickOption(name) {
    if(name !== '豆汁儿') return  this.$Message.info(`You clicked ${name}`);
}

**Comment by gaokun** [comment]
@ddyh0826 
这样在低级处理肯定是可以实现的, 
只是觉得框架应该处理这个默认行为

**Comment by gaokun** [comment]
what is the difference between [iview](https://github.com/iview) & [iview-design](https://github.com/iview-design) ?

why a pull request of iview-design could close this issue?

**Comment by gaokun** [comment]
closed pr #6316, coz fixed by another [pr](https://github.com/iview/iview/commit/d7d5bda587e656e78170e89291465e8247f87b1b).

**Comment by DebugIsFalse** [comment]
@jiawulin001 
I think he deal this problem better,but  his coding cannot merge. so I commit to deal

**Comment by gaokun** [comment]
@DebugIsFalse 
Yes, @jiawulin001 's PR made minimum change. You choose his PR, that is fine.

I realized you closed this issue by your own commit, not PR from iview-design.
So my second question is clear.

But I am still confused about there are two **iview** projects in [iview](https://github.com/iview/iview) & [iview-design](https://github.com/iview-design/iview). 
Seems they are connected.
But I don't know what difference between them.
