### ISSUE TITLE
使用tree懒加载时，当callback空数组，树的展开图标怎么隐藏?

### ISSUE THREAD

**Issue by 2017coding** [iview/iview#6139]

**Comment by DebugIsFalse** [comment]
https://run.iviewui.com/VpKedHLj

**Comment by 2017coding** [comment]
> https://run.iviewui.com/VpKedHLj

lazy tree， 开始默认是expand: true, 需要展开的时候，根据返回的数组是否为空，再去设置expand: false, 或者为leaf节点。 但是目前， 当callback数据为空，我没有办法将展开图标隐藏

**Comment by DebugIsFalse** [comment]
暂时你只能覆盖当前数组数据来说把后期会去尽快修复
https://run.iviewui.com/O2YHE1O8

**Comment by 2017coding** [comment]
好的，知道怎么做了，谢谢

**Comment by DebugIsFalse** [comment]
fixed
https://github.com/iview/iview/commit/e61df0d0386899f5b42446104e4fd410dfd8c3e5

**Comment by y1alpha** [comment]
我也遇到这个问题了，请问下楼主是怎么做的呢
