### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by LesterSixNet** [iview/iview#6143]
Carousel
children add  click or other event,
and loop

then loop once click don't trigger

**Comment by DebugIsFalse** [comment]
please use 'https://run.iviewui.com' to provide the example

**Comment by DebugIsFalse** [comment]
> please use 'https://run.iviewui.com' to provide the example



> Carousel
> children add click or other event,
> and loop
> 
> then loop once click don't trigger

Duplicate of #6230
