### ISSUE TITLE
[Bug Report]Tabs 循环渲染时，给key不小心输入了 NaN，导致死循环。

### ISSUE THREAD

**Issue by bitqiang** [iview/iview#6146]
### Environment
任意

### Reproduction link
[https://run.iviewui.com/sogkEHJE](https://run.iviewui.com/sogkEHJE)

### Steps to reproduce
点击重现按钮

### What is expected?
正常渲染，抛弃key

### What is actually happening?
页面死循环

**Comment by DebugIsFalse** [comment]
这是跟vue底层优化性能有关。你可以把它去掉。在编译环境忽略console.warn。建议自己审查保证key的唯一性和正确性
