### ISSUE TITLE
iview Select，使用自定义模板的情况下，搜索结果不准确

### ISSUE THREAD

**Issue by luiui** [iview/iview#6152]
![_Y`8RS {B63GPCZV}VHDN~8](https://user-images.githubusercontent.com/31300993/62433781-76da2380-b768-11e9-825c-d00fbf0078a8.png)

代码：
![图片](https://user-images.githubusercontent.com/31300993/62434056-a89fba00-b769-11e9-9173-448957c4ec93.png)

**Comment by DebugIsFalse** [comment]
Duplicate of #6310
