### ISSUE TITLE
[Bug Report]AutoComplete组件disabled与clearable同用时clearable应该不能清空

### ISSUE THREAD

**Issue by JunYiZzz** [iview/iview#6161]
### Environment
 iView Run版本

### Reproduction link
[https://run.iviewui.com/hMp0SDee](https://run.iviewui.com/hMp0SDee)

### Steps to reproduce
见重现示例

### What is expected?
不能清空

### What is actually happening?
输入值被清空

**Comment by jiawulin001** [comment]
示例是空白的，里面没有任何代码，是不是搞错了  

![image](https://user-images.githubusercontent.com/14244944/62667861-3b379780-b9bc-11e9-8979-08264f45ba13.png)

**Comment by JunYiZzz** [comment]
> 示例

> 示例是空白的，里面没有任何代码，是不是搞错了
> 
> ![image](https://user-images.githubusercontent.com/14244944/62667861-3b379780-b9bc-11e9-8979-08264f45ba13.png)

https://run.iviewui.com/hMp0SDee 我本地和同事的电脑都能打开的 
![image](https://user-images.githubusercontent.com/24381642/62670248-2ca1ae00-b9c5-11e9-8d89-4da9e9bfcccc.png)

**Comment by jiawulin001** [comment]
@JunYiZzz 
嗯嗯，现在看到了，上午我电脑不知道怎么打不开

**Comment by jiawulin001** [comment]
我觉得这个并不是一个问题，clearable属性就是提供清空的功能，如果想在disabled时不能被清理就不应该添加clearable属性，个人看法。

**Comment by JunYiZzz** [comment]
> 我觉得这个并不是一个问题，clearable属性就是提供清空的功能，如果想在disabled时不能被清理就不应该添加clearable属性，个人看法。

试了下 input/select/cascader/datePicker/timePicker 这些输入型的组件在disabled的时候都是不能清空的，我觉得需要统一一下

**Comment by jiawulin001** [comment]
> > 我觉得这个并不是一个问题，clearable属性就是提供清空的功能，如果想在disabled时不能被清理就不应该添加clearable属性，个人看法。
> 
> 试了下 input/select/cascader/datePicker/timePicker 这些输入型的组件在disabled的时候都是不能清空的，我觉得需要统一一下

嗯，如果作者其他的已经是这么处理了，那确实最好统一
