### ISSUE TITLE
[Bug Report]Select 组件Option 嵌套html标签使用会出问题

### ISSUE THREAD

**Issue by sevenCon** [iview/iview#6164]
### Environment
mac Chrome 版本 75.0.3770.142（正式版本） （64 位）

### Reproduction link
[https://run.iviewui.com/mMa5o31A](https://run.iviewui.com/mMa5o31A)

### Steps to reproduce
<Option v-for="item in cityList" :value="item.value" :key="item.value">
          <b>{{ item.label }}</b>
         </Option>里面嵌套的<b>标签去掉功能正常.

### What is expected?
选中的Option嵌套的{{item.label}}能正常在Select显示选中情况

### What is actually happening?
Option嵌套的{{item.label}} 不能正常在Select显示选中情况

**Comment by DebugIsFalse** [comment]
Option中的prop中加上他的label属性就行了,你的代码没有添加label的prop参数
https://run.iviewui.com/yW7kR05a
