### ISSUE TITLE
表单必填红* 可以自行添加么？

### ISSUE THREAD

**Issue by EnoND** [iview/iview#617]
### iView 版本号
2.0.0-rc.9

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 复现步骤
这是个建议或者是问题
### 问题现象，以及你期望的结果是怎样的?
如果自行设定验证方法，其中包含了必填验证，但表单没有统一的添加那个红*  
还有一种情况，一个Form-item 中 有2个input，这样如果想要在统一的label中添加那个红*怎么办，而且每个input还有自己的独特验证，这样就会在下面出现2行留白，就像您官网表单示例中的“选择日期”那个，那个就没有红*，但往往这些都是必填的  
我建议可以尝试prop支持多rules名称，或灵活自定义添加红*

**Comment by dean5277** [comment]
required: true 这个属性不是可以决定出现不出现么

**Comment by skillnull** [comment]
```
<FormItem label="测试" :rules="{required: true}">
       <ul>
               <li>demo</li>
       </ul>
</FormItem>``
```

这种情况即使设置了required: true也是没有星号出现，但是又需要用FormItem的label来让界面统一，有没有什么好的办法自由控制星号显隐藏

**Comment by alonesmall** [comment]
> required: true 这个属性不是可以决定出现不出现么

不行，当我用在form-item内的rules, required: true,还是不会出现红星。
