### ISSUE TITLE
[Bug Report]Modal中放带滚动条的table会有问题

### ISSUE THREAD

**Issue by swordjjjkkk** [iview/iview#6171]
### Environment
win10   /    76.0.3809.100/    2.6.10

### Reproduction link
[https://run.iviewui.com/U4Op89hl](https://run.iviewui.com/U4Op89hl)

### Steps to reproduce
点击添加按钮，出现modal显示正常，关闭modal再点击添加按钮，modal显示异常

### What is expected?
无论如何点击按钮，modal显示正常

### What is actually happening?
第二次点击按钮，modal显示不正常

---
如果改变浏览器大小，比如最大化最小化或者拖动浏览器，下一次modal都能好使，但是什么都不动的话，再下一次又显示不正常

**Comment by swordjjjkkk** [comment]
跟浏览器版本很有关系，我目前测试出来的问题版本是  Chrome版本 76.0.3809.100（正式版本） （64 位）

**Comment by zhouxinnana** [comment]
我也发现有以上问题

**Comment by msidolphin** [comment]
显示异常指的是什么？

**Comment by swordjjjkkk** [comment]
> 显示异常指的是什么？

![image](https://user-images.githubusercontent.com/22972430/62917383-9efffd00-bdce-11e9-87f8-6c876c5ffff5.png)

![image](https://user-images.githubusercontent.com/22972430/62917399-ac1cec00-bdce-11e9-82b3-39d75261852c.png)

**Comment by jingguangyan** [comment]
![image](https://user-images.githubusercontent.com/24221158/64061683-c9481c00-cc10-11e9-82bd-0d77c5089422.png)
简单粗暴的解决办法

**Comment by DebugIsFalse** [comment]
> > 显示异常指的是什么？
> 
> ![image](https://user-images.githubusercontent.com/22972430/62917383-9efffd00-bdce-11e9-87f8-6c876c5ffff5.png)
> 
> ![image](https://user-images.githubusercontent.com/22972430/62917399-ac1cec00-bdce-11e9-82b3-39d75261852c.png)

这是因为第二次弹窗table的宽度重新计算获取不到宽度导致的问题。
可以把table设置成 v-if也能解决
https://run.iviewui.com/AX6qjH86

**Comment by DebugIsFalse** [comment]
可以尝试3.5.1版本已修复这个问题
