### ISSUE TITLE
table 全选后 取消全选  @on-select-all-cancel="handleCancelSelectAll" 函数返回空数组

### ISSUE THREAD

**Issue by Lee981265** [iview/iview#6172]

**Comment by Lee981265** [comment]
handleCancelSelectAll(selection) { console.log(selection)  // 这里返回空数组
                //从已选项中移除当页数据
                this.selected = differenceBy(this.selected, this.tableData, "employeeCode");
            },

**Comment by msidolphin** [comment]
不明白什么意思，取消全选取消的当然是当前页数据

**Comment by Lee981265** [comment]
> 不明白什么意思，取消全选取消的当然是当前页数据
对的，该方法返回应该返回当前页面数据 ，实际上返回的是一个空数组， 期望： 能返回当前页数据而不是空数组

**Comment by msidolphin** [comment]
@Lee981265 但是当页数据不是由你提供的吗？这个数据你是知道的啊
