### ISSUE TITLE
[Bug Report]inputNumber设置precision=2

### ISSUE THREAD

**Issue by liuzeaa** [iview/iview#6174]
inputNumber设置precision=2，输入20，input直接变为2.00，删除.00之后才能重新赋值为20.00

初步分析源码，给出结果：
input事件发生之后就setValue，应该改为keydown才setValue

**Comment by DebugIsFalse** [comment]
version:3.4.2修复了。
下个版本会优化另外两个问题
1.当设置precision光标定位问题
2.输入小数点时不能输入问题
https://github.com/iview/iview/commit/5ece780d09aa0aa2ce3ad73d42ff906b757dae1d
