### ISSUE TITLE
[Feature Request]i-swipeout和i-collapse-item嵌套使用,插槽content未正确匹配

### ISSUE THREAD

**Issue by DavisYao88** [iview/iview#6177]
### What problem does this feature solve?
i-swipeout中嵌套使用i-collapse

### What does the proposed API look like?
` <i-swipeout i-class='i-swipeout-demo-item' actions={this.state.actions} }>
        <view slot='content'>
               <i-collapse name={1}>
                        <i-collapse-item title={} name='name1' i-class='i-collapse-demo-item'>
                            <view slot='content' i-class-content='translation-content-text'>
                                {}
                            </view>
                        </i-collapse-item>
                    </i-collapse>
          </view>
</i-swipeout>`
![image](https://user-images.githubusercontent.com/24189898/62767016-5393d900-bac6-11e9-9781-2c2c730f58d7.png)

**Comment by DebugIsFalse** [comment]
小时小程序的把？不是iview这块的暂时关闭
