### ISSUE TITLE
[Bug Report]编辑表格中的一条数据，验证为必填，当未失去焦点，按ESC取消，则下一次验证规则的提示会显示出来

### ISSUE THREAD

**Issue by lovetomkang** [iview/iview#6183]
### Environment
win10 / chrome 76.0.3809.100 / 2.5.10

### Reproduction link
[https://run.iviewui.com/Ougq99Sq](https://run.iviewui.com/Ougq99Sq)

### Steps to reproduce
如果这个Modal中的表单数据写了验证规则，当选择一行数据编辑时，清空这个必填项，此时焦点还在这个输入框，此时按ESC关闭这个Modal时，虽然调用了resetFileds方法，但是当再次编辑相同行的数据时会出现刚才关闭没有提示出来的验证错误提示

### What is expected?
期望Modal的ESC这个动作的时候，能主动失去焦点，真正执行到resetFileds方法，最终效果就是不会出现这个验证规则的错误提示

### What is actually happening?
表单中的字段有数据，还显示了验证规则的错误提示

**Comment by msidolphin** [comment]
@lovetomkang  我觉得加个延时就好了，这个不是组件的bug  https://run.iviewui.com/V4rjFb7j

**Comment by lovetomkang** [comment]
> @lovetomkang 我觉得加个延时就好了，这个不是组件的bug https://run.iviewui.com/V4rjFb7j
@msidolphin 刚试了一下你给的方案，还是不行哦，感觉就是Modal的ESC动作 好像没有触发表单全部失去焦点，比如我在Firefox 68.0.1 (32 位）这个环境下延时3s都不行，依然会提示错误验证信息

**Comment by msidolphin** [comment]
@lovetomkang 可以尝试在打开模态框的时候对name字段做一次校验https://run.iviewui.com/AbExe5kR

**Comment by a494836960** [comment]
监听  Modal的 on-visible-change 事件， 如果是 关闭，手动清除校验

**Comment by lovetomkang** [comment]
@a494836960 单独判断关闭再清除校验是不行的，无论是open还是close，都直接重置就行了,结果如下https://run.iviewui.com/nvjC53Fx

**Comment by lovetomkang** [comment]
@msidolphin 如果有多个字段，那么需要多次校验的，还是按照 @a494836960  这个方式比较好，监听on-visible-change，感谢两位
