### ISSUE TITLE
[Bug Report]Transfer 控件的全选/取消全选的勾选框点了后不会触发事件：on-selected-change

### ISSUE THREAD

**Issue by huacxl** [iview/iview#6187]
### Environment
chrome 76.0.3809.100

### Reproduction link
[https://run.iviewui.com/SjaThymO](https://run.iviewui.com/SjaThymO)

### Steps to reproduce
点单个选项可以触发进入事件：on-selected-change；但点 全选/取消 框，进行选择后，不会进入事件：on-selected-change：
<Transfer @on-selected-change="alert()"></Transfer>
然后界面点击测试

### What is expected?
因为全选或全取消也改变了项目的选择状态，需也能进入该事件

### What is actually happening?
没进入on-selected-change事件

**Comment by yangkuo1993** [comment]
how to reslove

**Comment by yangkuo1993** [comment]
How to deal with it
