### ISSUE TITLE
[Bug Report]Drawer存在DatePicker显示不完全

### ISSUE THREAD

**Issue by KnightLiJunLong** [iview/iview#6191]
### Environment
Ubuntu16.04/Chrome 68.0.3440.106(正式版本)/vue 2.9.6

### Reproduction link
[https://run.iviewui.com/pZKfE0Ac](https://run.iviewui.com/pZKfE0Ac)

### Steps to reproduce
修改2.0版本中Drawer的DEMO,width=720修改为300

### What is expected?
时间控件上浮,不受Drawer宽度影响

### What is actually happening?
显示不完整

**Comment by msidolphin** [comment]
使用transfer属性
