### ISSUE TITLE
iview2.0文档访问不了，几天了什么情况？

### ISSUE THREAD

**Issue by LWD8** [iview/iview#6195]
![image](https://user-images.githubusercontent.com/28432674/63138566-95180d00-c00d-11e9-9f67-25492ae84385.png)

访问地址：http://v2.iviewui.com/

![image](https://user-images.githubusercontent.com/28432674/63138722-17083600-c00e-11e9-8327-90e7d7bff5a0.png)

这几天上去看一下，一直访问不了，翻墙也不行。

**Comment by LWD8** [comment]
在iview群里问了下，成都的同事可以访问得了。我这边广州的用手机流量访问都不行........地区不能访问了？

![image](https://user-images.githubusercontent.com/28432674/63139326-7a936300-c010-11e9-8597-cc2b4c4abc0f.png)

**Comment by leejaygo** [comment]
2.0版本访问不了了

**Comment by icarusion** [comment]
CDN 服务商的域名备案挂了，现在已经恢复

**Comment by LWD8** [comment]
是的，现在已经可以访问。麻烦了....
