### ISSUE TITLE
[Bug Report]在table中嵌入select,最后一行下拉框的选项会被table覆盖掉 看不到选项

### ISSUE THREAD

**Issue by kingangelAOA** [iview/iview#6199]
### Environment
chrome

### Reproduction link
[https://run.iviewui.com/I9gtC40y](https://run.iviewui.com/I9gtC40y)

### Steps to reproduce
在table中使用slot嵌入select框

### What is expected?
最后一行select下拉选项不会被覆盖

### What is actually happening?
最后一行select下拉选项被覆盖

**Comment by msidolphin** [comment]
使用transfer属性

**Comment by kingangelAOA** [comment]
thanks
