### ISSUE TITLE
[Bug Report]来回切换tabs，会导致表格宽度变成1px（Repeated switching tabs，the width of the table becomes 1px）

### ISSUE THREAD

**Issue by qujingwei** [iview/iview#6203]
### Environment
OS:MacOS   Browser：Chrome 76.0.3809.100  Vue：V2.5.10

### Reproduction link
[https://run.iviewui.com/6eJLmwwM](https://run.iviewui.com/6eJLmwwM)

### Steps to reproduce
来回切换tabs （Repeated switching tabs）

### What is expected?
表格样式正常  （I hope the tableis in good shape.）

### What is actually happening?
The width of the table becomes 1px

**Comment by zhouxinnana** [comment]
I also encountered this problem,The width of the table cannot fill the parent container

**Comment by DebugIsFalse** [comment]
导致这个问题的关键是切换tabs的时候dom隐藏 导致table组件不能正确获取正常的宽度。暂时你可以hack处理一下，自己手动处理一下Table组件重新渲染一次
