### ISSUE TITLE
[Bug Report]表单验证顺序错乱

### ISSUE THREAD

**Issue by swhisky** [iview/iview#6215]
### Environment
chrome

### Reproduction link
[https://run.iviewui.com/CzNpq38n](https://run.iviewui.com/CzNpq38n)

### Steps to reproduce
1:点击保存（结果：提示表单验证不通过）
2:类型选择为【2】（结果：[代表]字段上下分别增加了字段[电话]以及[库存]，但是[代表]的表单验证结果却出现在[电话]上）

### What is expected?
表单验证结果正确。
实际可以通过在切换类型时，手动调用验证或重置验证，但这样的解决办法太不优雅了

### What is actually happening?
表单验证出现顺序错乱

---
如果具有v-if条件判断的[电话]以及[库存]中间无[代表]字段，则表单也能正确验证。

**Comment by DebugIsFalse** [comment]
需要把每个FormItem设置一个唯一的key
原因:如果你设置if 判断 vue自身保留历史的dom结构，数据做了更新，导致组件判断位置出错

**Comment by DebugIsFalse** [comment]
fixed： https://run.iviewui.com/ckxQwgmF

**Comment by swhisky** [comment]
嗯嗯，试过了，可行，已解决。感谢
