### ISSUE TITLE
[Bug Report]多层自定义组件导致顶层validator失效

### ISSUE THREAD

**Issue by LindsyT** [iview/iview#6219]
### Environment
mac

### Reproduction link
[https://www.iviewui.com/components/form](https://www.iviewui.com/components/form)

### Steps to reproduce
封装3层组件：Form > FormItem> DatePicker > iview 的DatePicker
使用$emit('input', value)   v-model方式实现每层的值同步
1、DatePicker 改变值
2、使用$emit('input', value)   v-model方式实现每层的值同步
3、 Form 组件成功拿到最新值，
4、----出问题：使用$refs.CustomForm.validateFiled('prop名')验证

validateFiled()失效，console发现，validateFiled(rule, value, callback)三个参数中的value值始终保持为初始值，不是修改后的Form['prop名']的值

### What is expected?
validateField()中的value能与Form的:model对应字段值一致，正确传递过来进行判断

### What is actually happening?
Form的:model对应字段值已改变，validateField()中的value值确一直保持初始值

---
后台管理系统，使用表单查询数据，为了简便，基于iview的Form封装了一个自定义组件，名为validateForm，入值为，[{input类型, 初始值，验证Rule，}]，validateForm内再使用循环v-for嵌一层封装的validateFormItem（里面是各种Input, select, cascade）

**Comment by DebugIsFalse** [comment]
使用this.$emit是不能触发他的验证规则的，
你可以尝试一下
import Emitter from "iview/src/mixins/emitter";
export default {
   mixins: [Emitter],
}
然后值发生变化的时候执行 this.dispatch("FormItem", "on-form-change", {...});
这样formItem才能接收到
