### ISSUE TITLE
使用carousel进行轮播图自动播放，第二轮出现的图片无法点击？

### ISSUE THREAD

**Issue by changbb** [iview/iview#6230]
在使用iview的carousel进行轮播图使用时，设置了loop，轮播图是可以点击跳转的，但是自动切换的第二轮的时候（这个时候应该是底层自动复制的dom），点击事件就失效了，请问有什么解决办法吗

**Comment by DebugIsFalse** [comment]
如果对外跳转你暂时使用a链接进行跳转把。

**Comment by changbb** [comment]
> 如果对外跳转你暂时使用a链接进行跳转把。
我现在的做法是去了loop属性，不过这确实是个bug,希望以后能解决
