### ISSUE TITLE
menu.d.ts类型导入模块中的MenuSub应该是Submenu吧？？？

### ISSUE THREAD

**Issue by mingyewei** [iview/iview#6232]

**Comment by mingyewei** [comment]
import { Menu, MenuItem } from 'iview'
const Submenu = (Menu as any).Sub
@Component({
    components: {
      Menu,
      MenuItem,
      Submenu
    }
  })
目前只能const Submenu = (Menu as any).Sub获取，不能导入，导入报错找不到模块

**Comment by LuRenJiasWorld** [comment]
我也遇到了一样的问题

**Comment by LuRenJiasWorld** [comment]
我找到的临时解决方法是直接引入整个ViewUI，但问题产生的具体原因可能还需要分析一下。

**Comment by fengluhome** [comment]
请问你当前用的哪个版本？

**Comment by LuRenJiasWorld** [comment]
我所使用的是view-ui v4.0.1，通过直接引入整个ViewUI可以解决问题，增加的体积也不是很大（可能是因为我的页面使用组件比较多），楼主的版本不清楚。

**Comment by mingyewei** [comment]
Type definitions for iview 3.3.1
"iview": "^3.4.2",
