### ISSUE TITLE
在多个Tab项里Table render button的cilick事件报错

### ISSUE THREAD

**Issue by pengpan** [iview/iview#624]
环境：iview 2.0.0-rc.7  vue:2.2.0

问题描述：
1、一个页面有多个TAB项，每个Tab项有一个Table组件，然后在Table组件的某个字段用render函数  如下：

```
{title:'***编号',key:'posNum',render:function(row, column, index){
	return '<i-button type="info" size="small" @click="openPosDetail(' + row.posNum + ')">'+row.posNum+'</i-button>';}},
```

声明：vue 的methods 是加了openPosDetail 方法

然后刷新页面，点击这个字段Vue 提醒：
Property or method "openPosDetail" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
然后也没调到openPosDetail 这个方法；

折腾了好久，也试了多个方式；比如：@click 改成 @click.native  多种都不行；

刚试了下把这个Table 从Tab项摘出来 单独放在页面的某个DIV里，代码啥都不动然后点击该字段，结果可以正常调到openPosDetail 这个方法；

这。。。也太诡异了吧； 

目前在Tab里还没找到其他方法解决，求楼主解释

**Comment by pengpan** [comment]
楼主看前面回复的消息，求加Q  问题演示给你看

**Comment by Kntt** [comment]
借楼提个建议,  columns的参数里增加一个format方法, 常用的currency ,date等, 虽然现在可以用render实现, 总觉得有点大材小用了.  或者是我使用姿势不对, 望楼主解答

**Comment by pengpan** [comment]
是啊，看了源码这个render实现比较费劲啊，其他常用的就是format功能

**Comment by pengpan** [comment]
刚又试了另外情况，只要把Table 从Tab移出来，单独放到HTML的DIV下不管几个Table组件点击都不报错，只要把Table放在Tab组件下就报错；估计这两组件组合的时候不兼容。不知道楼主有没遇到过？

**Comment by icarusion** [comment]
Do you add `context` prop?

**Comment by pengpan** [comment]
刚创建的示例：https://codepen.io/anon/pen/ZegxdQ
点击  编号不会调到 openPosDetail 方法，麻烦看下

**Comment by icarusion** [comment]
`context`

**Comment by pengpan** [comment]
@icarusion context 啥意思哈，麻烦详细说明下 感谢！

**Comment by dryqiao** [comment]
@pengpan 你好，这个问题我也遇到了，怎么解决啊？

**Comment by CyanChoi** [comment]
回答也是不清不楚 这么基础的功能还么修复好
