### ISSUE TITLE
[Bug Report]table slot-scope 中用 datepicker组件修改某行数据会被遮挡

### ISSUE THREAD

**Issue by litoxy** [iview/iview#6241]
### Environment
MAC / CHROME

### Reproduction link
[https://run.iviewui.com/preview/bbWyFSqr](https://run.iviewui.com/preview/bbWyFSqr)

### Steps to reproduce
https://run.iviewui.com/preview/bbWyFSqr

### What is expected?
不被遮挡

### What is actually happening?
datepicker被遮挡

**Comment by DebugIsFalse** [comment]
暂时只能使用样式覆盖iview table样式

**Comment by DebugIsFalse** [comment]
DatePicker添加props的transfer属性，看下文档说明
