### ISSUE TITLE
[Bug Report]在iview 2.14.0版本后及至最新版本，mounted方法中初始化select控件中通过v-model绑定的变量值，不可用

### ISSUE THREAD

**Issue by PassingByThs** [iview/iview#6242]
### Environment
at or after iview 2.14.0

### Reproduction link
[https://run.iviewui.com/L5Vo9nTE](https://run.iviewui.com/L5Vo9nTE)

### Steps to reproduce
1、在iview 2.13.1版本，mounted方法中初始化select控件中通过v-model绑定的变量值，可用
2、在iview 2.14.0版本后及至最新版本，mounted方法中初始化select控件中通过v-model绑定的变量值，不可用

### What is expected?
在iview 2.14.0版本后及至最新版本，mounted方法中初始化select控件中通过v-model绑定的变量值，可用

### What is actually happening?
1、在iview 2.13.1版本，mounted方法中初始化select控件中通过v-model绑定的变量值，可用
2、在iview 2.14.0版本后及至最新版本，mounted方法中初始化select控件中通过v-model绑定的变量值，不可用

**Comment by DebugIsFalse** [comment]
暂时可以这样解决
在mounted上使用
this.$nextTick(()=>{
     this.name = 3;
})
