### ISSUE TITLE
[Bug Report]InputNumber设置min比如设为18  max设为144，这种情况无法输入其他值

### ISSUE THREAD

**Issue by lison16** [iview/iview#6245]
### Environment
mac os / chrome / vue2.6

### Reproduction link
[https://run.iviewui.com/unXXX35I](https://run.iviewui.com/unXXX35I)

### Steps to reproduce
min设为18，max设为144，v-model绑定为18
输入任意值
min和max不是固定是18和144，只要min的前两位大于max的前两位即可，比如18大于14

### What is expected?
期望可以输入任意值

### What is actually happening?
现在如果值为18时，继续输入一位数，比如1，那值就是181，此时181大于144，会被变为144，而如果想输入19这个值，那需要先删掉8，此时就是1，会被变为最小值18

**Comment by DebugIsFalse** [comment]
如果使用 min max使用规则只能设置 props 'active-change' 为 false 来验证

**Comment by lison16** [comment]
ok，设置active-change为false可行
