### ISSUE TITLE
[Bug Report]iview文档Switch错误问题

### ISSUE THREAD

**Issue by yysmk1234** [iview/iview#6248]
### Environment
win/chrome/vue 2.9.6

### Reproduction link
[https://www.iviewui.com/components/switch](https://www.iviewui.com/components/switch)

### Steps to reproduce
文档中的例子给的是Switch 标签，但是源码里面给 的是 iSwitch 标签，而且用 Switch 页面没法渲染，用iSwitch就能正常渲染组件

### What is expected?
文档修改或者源码

### What is actually happening?
暂无

**Comment by DebugIsFalse** [comment]
配置webpack使用iview-loader来解决这个问题。
