### ISSUE TITLE
[Feature Request]在线文档左侧菜单功能建议

### ISSUE THREAD

**Issue by rouyi-tmc** [iview/iview#6257]
### What problem does this feature solve?
在线文档左侧菜单希望能固定起来，而不是跟着整个页面滚动，这样体验很不好

### What does the proposed API look like?
在线文档左侧菜单希望能固定起来，而不是跟着整个页面滚动

**Comment by fengluhome** [comment]
已经修复  http://iview.talkingdata.com/
