### ISSUE TITLE
[Bug Report]Tabs & table 一起使用，column宽度会变化

### ISSUE THREAD

**Issue by cgrddv** [iview/iview#6258]
### Environment
win10 / chrome 76/ vue2.0

### Reproduction link
[https://run.iviewui.com/zDVWEMcs](https://run.iviewui.com/zDVWEMcs)

### Steps to reproduce
切换tab，第三次开始有问题

### What is expected?
列宽不随意变化

### What is actually happening?
列宽被压缩

**Comment by DebugIsFalse** [comment]
是因为tabs设置display属性为none 导致table不能正确的获取宽度
暂时可以这么解决问题 
https://run.iviewui.com/8Gvc3nnM

**Comment by karchinkong** [comment]
> 是因为tabs设置display属性为none 导致table不能正确的获取宽度
> 暂时可以这么解决问题
> https://run.iviewui.com/8Gvc3nnM

我们Layout是以一个tab进行切换页面路由的 那这个的话怎么解决阿 每个页面里面都有table,那我是否只能切换一个方式了?
