### ISSUE TITLE
[Bug Report]Cascader 组件，data中value为非字符串类型时，筛选功能无法正常使用

### ISSUE THREAD

**Issue by musishui** [iview/iview#6259]
### Environment
chrome 76、vue2.x

### Reproduction link
[https://run.iviewui.com/jm52xmOb](https://run.iviewui.com/jm52xmOb)

### Steps to reproduce
筛选输入‘王府井’，删选出后无法点击选中‘北京/王府井’

### What is expected?
可以选中王府井

### What is actually happening?
下拉列表一闪消失，并没有选中点击的项

**Comment by ramocky** [comment]
解决了一下午  在github终于看到了方案....
