### ISSUE TITLE
有点击事件的组件可以支持router-link绑定吗？

### ISSUE THREAD

**Issue by scaupdc** [iview/iview#626]
目前iView上很多组件，如Menu、Button，不能很好地绑定Vue原生路由，且能自动管理自身的active class状态，希望iView可以考虑一下？

**Comment by icarusion** [comment]
通用组件有它的特殊性考虑，所以需要用 编程式导航 来实现路由

**Comment by andyhu** [comment]
@icarusion 编程式导航是什么意思？

**Comment by CRONWMMM** [comment]
@andyhu this.$router.push
