### ISSUE TITLE
[Feature Request]table 勾选的数据顺序和页面展示的顺序不一致

### ISSUE THREAD

**Issue by scarcoco** [iview/iview#6262]
### What problem does this feature solve?
table 勾选的数据顺序和页面展示的顺序不一致

### What does the proposed API look like?
table  希望勾选的数据顺序和表格展示的一致

**Comment by DebugIsFalse** [comment]
请在 https://run.iviewui.com/ 提供示例

**Comment by scarcoco** [comment]
@DebugIsFalse 写了一个简单demo， 顺序是一致的，我在check一下 我们自己的 代码
https://run.iviewui.com/Kwvi7dsK
