### ISSUE TITLE
IE 下 Table 组件无法绑定事件，其他浏览器正常

### ISSUE THREAD

**Issue by sciooga** [iview/iview#627]
### iView 版本号
2.0.0-rc.9

### 操作系统/浏览器 版本号
IE11 等 IE 系

### Vue 版本号
v2.2.0

### 能够复现问题的在线示例（重要）

参考官方示例代码写的 DEMO
https://jsfiddle.net/sciooga/rjLn03ta/

### 复现步骤
Chrome 等浏览器点击表格按钮均能弹出模态框，IE 11 点击时提示函数未定义

### 问题现象，以及你期望的结果是怎样的?
IE 打开直接报错，无法绑定事件，Chrome 等浏览器均正常

**Comment by icarusion** [comment]
文档在 IE 下目前有报错，已更新，下个版本上

**Comment by icarusion** [comment]
文档已更新，在 IE 11 下 Table 组件一切正常。
