### ISSUE TITLE
[Bug Report]table组件，fixed的列里包含Poptip，会被遮挡

### ISSUE THREAD

**Issue by Hotcapsicum** [iview/iview#6271]
### Environment
win10/chrome/Vue3.4 

### Reproduction link
[https://run.iviewui.com/WEhtSWOO](https://run.iviewui.com/WEhtSWOO)

### Steps to reproduce
template模式下，table组件里嵌套Poptip组件，然后该列使用fixed，则Poptip内容会被遮挡

### What is expected?
期望显示完全

### What is actually happening?
被其他列遮挡了

**Comment by Hotcapsicum** [comment]
当前做法是设置 ivu-table-fixed-body { overflow: visible }，则可以使poptip内容显示完全，但是会导致表格其他列（即没有设置fixed 属性的）失去hover效果，也不能被选中

**Comment by DebugIsFalse** [comment]
使用 Poptip的 props添加 transfer
把tip改成body内部的执行
https://run.iviewui.com/yEwwYHJu

**Comment by Hotcapsicum** [comment]
好的，，明白了
