### ISSUE TITLE
[Bug Report]Page  绑定 current 不生效

### ISSUE THREAD

**Issue by swordjjjkkk** [iview/iview#6273]
### Environment
os：win10     /chrome： 76.0.3809.100      / iview： 2.6.10

### Reproduction link
[https://run.iviewui.com/9o2qD5hH](https://run.iviewui.com/9o2qD5hH)

### Steps to reproduce
点击 第三页 ，然后点击 change page index 按钮

### What is expected?
page组件跳转到第一页

### What is actually happening?
page组件的页码没有改变

**Comment by Hotcapsicum** [comment]
<Page :total="100" :current.sync="currentIndex"  show-sizer show-elevator show-total/>
这样就可以了，具体原因可以看文档

**Comment by Hotcapsicum** [comment]
` <Page :total="100" :current.sync="currentIndex"  show-sizer show-elevator show-total/>`

**Comment by swordjjjkkk** [comment]
> ` <Page :total="100" :current.sync="currentIndex" show-sizer show-elevator show-total/>`

好的，谢谢
