### ISSUE TITLE
[Bug Report]点击Modal 中的按钮 跳转到新的页面，新的页面的滚动条不能上下滚动

### ISSUE THREAD

**Issue by Shulong123** [iview/iview#6278]
### Environment
mac / chrome  76.0.3809.132 / vue 3.1.3

### Reproduction link
[http://内部系统不能提供链接.com](http://内部系统不能提供链接.com)

### Steps to reproduce
<Modal v-model="sqlcommandModal" :width="980" :styles="{top: '55px'}">
        <Button type="info" @click="goToSqlRelease">提SQL发布单</Button>
        <Button type="default" @click="cancelSqlCommand">确定</Button>
</Modal>
goToSqlRelease () {
            const route = {
                name: 'newsql',
                title: '新建SQL发布单'
            };
            this.$router.push(route);
            util.routeDyn(this, route)
}

### What is expected?
新的页面滚动条可以正常上下滚动

### What is actually happening?
新的页面滚动条没有显示出来，不能上下滚动

---
我不从Modal 中的按钮跳转页面，新页面是正常的，滚动条可以正常上下滚动

**Comment by Shulong123** [comment]
![image](https://user-images.githubusercontent.com/15952709/65102675-67542880-d9fe-11e9-94f4-17b6024285d6.png)

**Comment by Shulong123** [comment]
![image](https://user-images.githubusercontent.com/15952709/65102727-94084000-d9fe-11e9-9bf2-05fe67464c50.png)

**Comment by DebugIsFalse** [comment]
我看着像是iview-admin需求问题。
你可以自己业务来解决这个问题
当这个页面生命周期结束的时候，来执行让滚动条重新显示

**Comment by DebugIsFalse** [comment]
如果是iview遇到这个问题你可以尝试把路由切换换到延迟里面比如
this.$nextTick(()=>{
     this.$router.push({ path : 'xxx' })
})
