### ISSUE TITLE
table宽度不能自适应

### ISSUE THREAD

**Issue by yinqf** [iview/iview#628]
问题复现示例：https://codepen.io/yinqf/pen/jBjpEd
复现步骤：
1、点击“改变宽度”按钮，会将table上级div的宽带在500px和700px之间切换
2、div宽度变化的时候，table的宽度没有自动适配

期望结果：期望能自动改变table的宽度

**Comment by icarusion** [comment]
已知问题

**Comment by nirvanatao** [comment]
解决了吗

**Comment by WangLei1993** [comment]
看到table.vue当中在`mounted`时有监听处理`on-visible-change`事件，所以可以在父组件监听到宽度有变化时如下调用一下：`this.$refs.table_test.$emit('on-visible-change', true);`

**Comment by sonycamera** [comment]
@WangLei1993 , 我试过你说的这种方法，好像不管用啊，你试过管用吗？
