### ISSUE TITLE
InputNumber设置最大最小值无效官网却正常

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#6289]
### Environment
iview3.5.1,vue最新版本

### Reproduction link
[https://codepen.io/yangdan8/pen/PoYxaWP](https://codepen.io/yangdan8/pen/PoYxaWP)

### Steps to reproduce
输入大于10的数字

### What is expected?
不允许输入大于指定的值

### What is actually happening?
可以输入大于10的值

**Comment by DebugIsFalse** [comment]
在3.5.1版本修改成了只能失去焦点设置最大值最小值
增加:active-change="false"
修改初衷是因为 https://github.com/iview/iview/issues/6245
