### ISSUE TITLE
[Bug Report]远程选择器Select组件 label-in-value bug

### ISSUE THREAD

**Issue by tanrich** [iview/iview#6290]
### Environment
mac os 最新 chrome

### Reproduction link
[https://run.iviewui.com/fql1uRwU](https://run.iviewui.com/fql1uRwU)

### Steps to reproduce
添加 label-in-value 后，搜索选择第一个值，再搜索选择第二个值。第一个选中的选项被自动提换成了第二个，第一个选中项无法保存。

### What is expected?
多次搜索，保存多次搜索选中结果

### What is actually happening?
实际上只保留了最后一次选中结果

**Comment by DebugIsFalse** [comment]
更新版本到3.5.1 已修复这个bug
