### ISSUE TITLE
[Bug Report]form表单多选框换成下拉框多选 重置时提示没有消除

### ISSUE THREAD

**Issue by jack-star** [iview/iview#6301]
### Environment
window10 chrome76.0.3809.132 vue2.6.10

### Reproduction link
[https://run.iviewui.com/Wi7srLhS](https://run.iviewui.com/Wi7srLhS)

### Steps to reproduce
随便选择两个数据重置就可以了

### What is expected?
点击重置，提示消失

### What is actually happening?
没有消失

**Comment by DebugIsFalse** [comment]
根据你说的，我点击充值重置是数据结果清空了

**Comment by jack-star** [comment]
数据清空了，但是提示没有！！！！



------------------ 原始邮件 ------------------
发件人: "debugIsFalse"<notifications@github.com>; 
发送时间: 2019年9月25日(星期三) 上午10:02
收件人: "iview/iview"<iview@noreply.github.com>; 
抄送: "188294634"<188294634@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [iview/iview] [Bug Report]form表单多选框换成下拉框多选 重置时提示没有消除 (#6301)




根据你说的，我点击充值重置是数据结果清空了
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或使该线程静音。
