### ISSUE TITLE
[Bug Report]iView 文档的 Modal width 属性说明与实际不一致

### ISSUE THREAD

**Issue by richex-cn** [iview/iview#6302]
### Environment
iView 3.4.2

### Reproduction link
[https://run.iviewui.com/f56pLj6I](https://run.iviewui.com/f56pLj6I)

### Steps to reproduce
-

### What is expected?
屏幕尺寸小于 768px 时，宽度会变为自动 auto

### What is actually happening?
屏幕尺寸小于 576px 时，宽度会变为自动 auto

**Comment by DebugIsFalse** [comment]
这是使用的问题你可以自己使用width="800"写死，默认如果自己不设置是自动放缩

**Comment by richex-cn** [comment]
> 这是使用的问题你可以自己使用width="800"写死，默认如果自己不设置是自动放缩

我的意思是，官方文档（<https://iviewui.com/components/modal>）当中对于 Modal width 属性的说明与实际表现不一致，应该更正，官方文档写的是 **对话框宽度，对话框的宽度是响应式的，当屏幕尺寸小于 768px 时，宽度会变为自动 auto**，而实际应该更正为 **576px**
