### ISSUE TITLE
百度搜iview，搜索结果第一个是v1版本的文档连接

### ISSUE THREAD

**Issue by hanjunlove** [iview/iview#6303]
如题，今天开始入门iview，用了i-table，发现render不能起作用，对照着文档看了好长时间也不知道哪里出错了，实在没办法加了个群才发现文档看错了。后来发现v1和v3的手册很不一样，希望网站有办法让百度搜索第一个小时的网页能直接跳转到v3版本的使用手册，这样对新手会很友好。

**Comment by lijing666** [comment]
这个你不是应该换个搜索引擎么 有几个程序员还在用垃圾百度的 另外使用任何库和看文档都应该事先确定好版本吧

**Comment by hanjunlove** [comment]
都说了是前端初学者了，用个npm都费劲，npm默认安装就是最新版，谁知道版本不对能有这么大差异，你又不是初学者，你当然知道先看文档版本了。如果觉得这个不是问题，忽略就行，还发给我做甚？另外你就能代表大多数程序员？你不用百度就代表大多数程序员不用百度？你咋恁能？



---原始邮件---
发件人: "lijing666"<notifications@github.com&gt;
发送时间: 2019年9月27日(星期五) 下午4:50
收件人: "iview/iview"<iview@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"hanjunlove"<417280432@qq.com&gt;;
主题: Re: [iview/iview] 百度搜iview，搜索结果第一个是v1版本的文档连接 (#6303)



这个你不是应该换个搜索引擎么 有几个程序员还在用垃圾百度的 另外使用任何库和看文档都应该事先确定好版本吧

**Comment by lijing666** [comment]
就你这素质，哎，给你个建议而已就开骂

**Comment by DebugIsFalse** [comment]
最好是从github入口进 默认收藏这个地址就行了
