### ISSUE TITLE
[Bug Report]split组件max属性无效

### ISSUE THREAD

**Issue by chen-ABC** [iview/iview#6311]
### Environment
window7 谷歌64 vue 2.6.10

### Reproduction link
[https://run.iviewui.com/kfEuVDgN](https://run.iviewui.com/kfEuVDgN)

### Steps to reproduce
1split组件设置max属性为300px
2拖动发现可以超过300px

### What is expected?
max属性生效，无法拖动超过max值

### What is actually happening?
split组件max属性无效，设置最大为300px但是拖动发现可以超过

**Comment by badeggg** [comment]
same problem

**Comment by iSpring** [comment]
iview开发人员都不自己进行下基础测试吗？这代码质量太差了
