### ISSUE TITLE
How make select bigger

### ISSUE THREAD

**Issue by murilolivorato** [iview/iview#6314]
Hello , I have this selection -
![selection](https://user-images.githubusercontent.com/19832238/65763455-d8c86100-e0f9-11e9-9be1-14e4cdd026ac.jpg)

it has 3 sizes  - large, small, default or none .
BUT , I wold like to have one Bigger that the Large one . more bigger .
how can I do it ? I tried to change in css , but I was no success ;
does have any class that I can change in css , to make this selection bigger that the large one ?

**Comment by DebugIsFalse** [comment]
You can use the css change it,
for example
.ivu-select{ color:red!important }

**Comment by shizhenbin** [comment]
add a parent class is good
