### ISSUE TITLE
[Feature Request]Drawer建议增加可配置z-index选项

### ISSUE THREAD

**Issue by aruandme** [iview/iview#6317]
### What problem does this feature solve?
我经常使用Drawer来做数据选择，但当从modal打开Drawer时，虽然modal设置来一个较小的z-index，但测试发现偶尔还会出现打开的Drawer置于modal下层，希望可以为Drawer增加z-index配置项目可自由调节显示层级

### What does the proposed API look like?
Drawer props 增加z-index配置项目 例如z-index="1500"

**Comment by msidolphin** [comment]
@aruandme 这个配置已经有了，但是文档没有补上
