### ISSUE TITLE
iView Table 重大Bug请修改

### ISSUE THREAD

**Issue by jinwmmail** [iview/iview#6319]
1 当某行，在列表中第一列为空值时，这列不显示，这问题我查了好久.
最后我是将从不为空的主键显示在列表中第一列，且在render 中返回""
2 能否加一下隐藏某列的Api?

**Comment by DebugIsFalse** [comment]
建议你写个computed或者filter来过滤实现

**Comment by DebugIsFalse** [comment]
iview 3.2.x出来slot-scope你可以替换掉render渲染
https://run.iviewui.com/50ahQHrs

**Comment by by415304229** [comment]
这个问题依然存在
