### ISSUE TITLE
Grid Flex + Responsive?

### ISSUE THREAD

**Issue by breeswish** [iview/iview#632]
Flex 和 Responsive 无法共存？

是否考虑使用 [Foundation Grid](http://foundation.zurb.com/sites/docs/flex-grid.html)? 既可以处于 Flex 模式也可以处于普通模式，与此同时都支持 Responsive

**Comment by breeswish** [comment]
Sorry, 看上去主要原因是 Flex Grid 在移动端和非 Flex Grid 表现不一致。

**Comment by icarusion** [comment]
Grid Design powered by Ant.Design
