### ISSUE TITLE
upload组件上传导致浏览器崩溃

### ISSUE THREAD

**Issue by zhaodagang** [iview/iview#6320]
使用upload组件，点击上传按钮，弹出文件选择框，选择文件后，导致浏览器崩溃，请问各位大神是什么情况？
经测试发现，chrome 68.0版本正常，chrome 64.0版本崩溃，是浏览器的问题吗？还是内存的问题？

**Comment by DebugIsFalse** [comment]
你最好看下你上传文件的大小问题

**Comment by dake0505** [comment]
> 使用upload组件，点击上传按钮，弹出文件选择框，选择文件后，导致浏览器崩溃，请问各位大神是什么情况？
> 经测试发现，chrome 68.0版本正常，chrome 64.0版本崩溃，是浏览器的问题吗？还是内存的问题？

请问这个问题解决了吗
