### ISSUE TITLE
Form Submit?

### ISSUE THREAD

**Issue by breeswish** [iview/iview#633]
是否有考虑支持拦截 form submit? 现在所有的 example 里 form 都基于 button click（button type != submit），在这种情况下 input 按回车不能实现递交，非常不友好

**Comment by icarusion** [comment]
可以监听 `Input` 的回车事件。

**Comment by breeswish** [comment]
This is a workaround, not a fix.

**Comment by melon** [comment]
在Form组件上增加 @submit.native.prevent="handleSubmit()"， 再在组件内部增加一个<input type="submit" v-show="false">即可回车触发form的submit
