### ISSUE TITLE
Can't set custom theme in iview-nuxt

### ISSUE THREAD

**Issue by folamy** [iview/iview#6332]
Following the recommended step in the doc....
`
plugins/iview.js
import Vue from 'vue'
import iView from 'iview'
import locale from 'iview/dist/locale/en-US' // Change locale, check node_modules/iview/dist/locale
import '../my-theme/index.less'
Vue.use(iView, {
  locale
})

~/my-theme/index.less
@primary-color: #8c0776;

but primary color didnt change

**Comment by DebugIsFalse** [comment]
You can test this method;
create theme/theme.less;
that is the content;
```javascript
@import '~iview/src/styles/index.less';
@primary-color: #8c0776;


```

**Comment by folamy** [comment]
Wow! my bad, I missed the first @import line...
Working now.... Thanks
