### ISSUE TITLE
Switch 组件空格键切换 能 自由配置吗

### ISSUE THREAD

**Issue by Huai-Dc** [iview/iview#6333]
Switch的 空格触发toggle 方法 容易与现有时间造成冲突

**Comment by DebugIsFalse** [comment]
能举个实际例子？

**Comment by Huai-Dc** [comment]
> 能举个实际例子？

我项目有个开关是通过 switch 绑定的 开了之后 document 有绑定keyDown事件  其中space 就有对应的操作  但是 按空格键的时候 switch 的toggle 事件也一并触发了（关掉了本来控制的开关）

**Comment by DebugIsFalse** [comment]
这个描述我不能准确的定位到问题。
本身这是关于业务如果避免这个问题。
比如document上绑定keyDown事件，是不是通过其他方式去避免这个问题？

**Comment by Huai-Dc** [comment]
> 这个描述我不能准确的定位到问题。
> 本身这是关于业务如果避免这个问题。
> 比如document上绑定keyDown事件，是不是通过其他方式去避免这个问题？

我想要的 是不希望自动在Switch这个组件 绑定上  @keydown.space="toggle"  这个事件  如果这个事件绑定一定要存在没办法去掉 或加个开关  我自己重新写一个也没事  并不是什么 bug
