### ISSUE TITLE
Input type为textarea时，粘贴进去比较长的url的时候，总是会自动换行

### ISSUE THREAD

**Issue by kliyadongkingks** [iview/iview#6344]
Input type为textarea时，粘贴进去比较长的url的时候，总是会自动换行
代码：` <Input v-model="urlArea"  :autosize="{minRows: 11,maxRows: 20}" type="textarea" :rows="11" />`
如图：
![iss](https://user-images.githubusercontent.com/31718241/67306686-f686bb80-f529-11e9-9a1f-aa5f9d5dfede.png)
而且空格无法删除，这是怎么回事，望大佬解答。

**Comment by DebugIsFalse** [comment]
你可以强制他不换行
white-space: nowrap;
