### ISSUE TITLE
[Bug Report]Select的filterable模式下，搜索带有转义引号 \" 的选项，会出现选不中的情况

### ISSUE THREAD

**Issue by liuestc** [iview/iview#6349]
### Environment
win10

### Reproduction link
[https://run.iviewui.com/6qq7Qxox](https://run.iviewui.com/6qq7Qxox)

### Steps to reproduce
搜索 年龄  然后选中

### What is expected?
可以被选中

### What is actually happening?
没有被选中

---
可能是转义符号 \ 引起的？如何修复

**Comment by DebugIsFalse** [comment]
need to optimize
