### ISSUE TITLE
cookie加上domain，无法登录

### ISSUE THREAD

**Issue by ydaming** [iview/iview#6350]
请教下，我修改了util.js里面的setToken方法，加上了domain
`
Cookies.set(TOKEN_KEY, token, { expires: cookieExpires || 1, domain: 'xxx.com' })
`
然后登录的时候就报错了
![image](https://user-images.githubusercontent.com/10082597/67778228-db71f980-fa9d-11e9-94c0-f28dc41fc1cb.png)

根据报错，应该是在long.vue路由调整的时候失败了
![image](https://user-images.githubusercontent.com/10082597/67778189-cbf2b080-fa9d-11e9-9025-45b42722d8f2.png)

**Comment by DebugIsFalse** [comment]
这个你应该看下cookie基础原理 你设置去了其他域了，肯定获取不到，
这个跟vue或者iview没啥关系 暂时关闭了

**Comment by ydaming** [comment]
> 这个你应该看下cookie基础原理 你设置去了其他域了，肯定获取不到，
> 这个跟vue或者iview没啥关系 暂时关闭了

是www.xxx.com域的，cookie也是设置成功了，xxx.com设置成功了，访问getUserInfo接口也能拿到cookie，只是在跳转首页的时候，路由报错了
