### ISSUE TITLE
[Bug Report]async-validator 内部报错无法捕获

### ISSUE THREAD

**Issue by scarcoco** [iview/iview#6353]
### Environment
mac

### Reproduction link
[https://run.iviewui.com/uXPauiDq](https://run.iviewui.com/uXPauiDq)

### Steps to reproduce
直接看 DEMO

https://run.iviewui.com/uXPauiDq

### What is expected?
希望能正常捕获错误

### What is actually happening?
没有任何反应

**Comment by DebugIsFalse** [comment]
这是业务解决的问题。
你可以用type: number 检测
如果使用validator这是你自己代码处理问题
https://run.iviewui.com/86A6587W
