### ISSUE TITLE
[Bug Report]table组件表头偶尔出现空白

### ISSUE THREAD

**Issue by kuangyazhou** [iview/iview#6362]
### Environment
vue 2.5.10 iview 3.2.2

### Reproduction link
[https://pan.baidu.com/s/1VPIcT3v1bnbHaMx60KF_Dw](https://pan.baidu.com/s/1VPIcT3v1bnbHaMx60KF_Dw)

### Steps to reproduce
打开弹框后，内部表格偶尔会出现此空白

### What is expected?
避免变空白

### What is actually happening?
偶尔会出现空白表头

**Comment by DebugIsFalse** [comment]
使用最小宽度，不要设置固定宽度
