### ISSUE TITLE
[Bug Report]select下拉框组件展开后点击旁边下拉框不会触发事件，只会收起当前下拉框

### ISSUE THREAD

**Issue by cpa0701** [iview/iview#6363]
### Environment
window/谷歌浏览器/vue@2.6.0

### Reproduction link
[https://run.iviewui.com/iOo2Lp9a](https://run.iviewui.com/iOo2Lp9a)

### Steps to reproduce
1.点击展开当前下拉框
2.点击旁边下拉框
3.之前的下拉框收起，但之后点击的下拉框并未展开

### What is expected?
当前下拉框收起的同时也能响应当前点击事件

### What is actually happening?
当前下拉框收起的同时未能响应当前点击事件

**Comment by DebugIsFalse** [comment]
目前iview是遵循html元素select标准，当点击select不关闭，再点击另外select先是前一个展开关闭，才能再执行当前select装填

**Comment by yannanna0920** [comment]
> 目前iview是遵循html元素select标准，当点击select不关闭，再点击另外select先是前一个展开关闭，才能再执行当前select装填

我遇到个问题 我点击select弹出弹窗 当我关闭弹窗时 它会先收起select展开 然后在点击弹窗的取消或确定才可以操作到 我怎样可以控制下让select的下拉不展开
