### ISSUE TITLE
[Bug Report]label prop of Select component not working

### ISSUE THREAD

**Issue by CherishIt** [iview/iview#6367]
### Environment
mac os chrome

### Reproduction link
[https://run.iviewui.com/0mQQX1uO](https://run.iviewui.com/0mQQX1uO)

### Steps to reproduce
click link to reproduce

### What is expected?
label should work

### What is actually happening?
it's not

**Comment by DebugIsFalse** [comment]
You can remove label and set v-model value;
label is not used for the filterable status。
