### ISSUE TITLE
 Property 'hide' does not exist on type 'Spin'.

### ISSUE THREAD

**Issue by caohuatao** [iview/iview#6380]
315:24 Property 'hide' does not exist on type 'Spin'.
    313 |                     })
    314 |                 }
  > 315 |                 this.$Spin.hide()
        |                        ^
    316 |             }
    317 |         }
    318 | 

typescript 报错  hide和show 方法 在 spin.d.ts 中没有描述

**Comment by colinc74** [comment]
view-design\types\spin.d.ts has no definition for both show() and hide()
