### ISSUE TITLE
iview  table render函数内return后不显示

### ISSUE THREAD

**Issue by WuYuansen** [iview/iview#6381]

**Comment by WuYuansen** [comment]
示例代码：`,{
                        title:'审核状态',width:90,key:'shzt',render(row,column,index){
                            const color = column.row.shzt == 0 ? 'blue' : column.row.shzt == 2 ? 'green' : 'red';
                            const text = column.row.shzt == 0 ? '待审核' : column.row.shzt == 2 ? '通过' : '驳回';
                            return `<tag type="dot" color="${color}">${text}</tag>`;
                        }
                    }`

**Comment by WuYuansen** [comment]
示例代码：

> {
                        title:'审核状态',width:90,key:'shzt',render(row,column,index){
                            const color = column.row.shzt == 0 ? 'blue' : column.row.shzt == 2 ? 'green' : 'red';
                            const text = column.row.shzt == 0 ? '待审核' : column.row.shzt == 2 ? '通过' : '驳回';
                            return `<tag type="dot" color="${color}">${text}</tag>`;
                        }
                    }

**Comment by DebugIsFalse** [comment]
@WuYuansen 给我一份data数据把

**Comment by WuYuansen** [comment]
@DebugIsFalse  我是在本地伪造的数据比如 data(){return{list:[{shzt:0}]}}

**Comment by DebugIsFalse** [comment]
这是你使用的问题你使用的render方法但是没有按照render方法是使写
这是示例
https://run.iviewui.com/DElPY9CD
