### ISSUE TITLE
[Bug Report]modal模态窗 loading 问题

### ISSUE THREAD

**Issue by CasualWzb** [iview/iview#6382]
### Environment
mac10.15.1/chrome78/vue2.5.22

### Reproduction link
[https://run.iviewui.com/](https://run.iviewui.com/)

### Steps to reproduce
重复点击确定，在定时器到期时确定被执行俩次，并且再次点开loading状态会保存。

### What is expected?
防止重复点击

### What is actually happening?
确定被执行俩次并且再次点开loading状态会保存

**Comment by DebugIsFalse** [comment]
我个人觉得
防止重复点击逻辑处理应该放在业务层上去处理
