### ISSUE TITLE
返回上一级页面报错Uncaught TypeError: Cannot read property 'offsetWidth' of undefined，页面没有使用offsetWidth

### ISSUE THREAD

**Issue by 1225717217** [iview/iview#6384]

**Comment by DebugIsFalse** [comment]
这个问题你最好检查一下 不管是iview组件还是自己的vue组件那里绑定了scroll事件 然后在当前页面销毁，解除绑定scroll事件

**Comment by 1225717217** [comment]
好的，谢谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"debugIsFalse"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 下午2:07
收件人:&nbsp;"iview/iview"<iview@noreply.github.com&gt;;
抄送:&nbsp;"無聊"<1225717217@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iview/iview] 返回上一级页面报错Uncaught TypeError: Cannot read property 'offsetWidth' of undefined，页面没有使用offsetWidth (#6384)




这个问题你最好检查一下 不管是iview组件还是自己的vue组件那里绑定了scroll事件 然后在当前页面销毁，解除绑定scroll事件
