### ISSUE TITLE
通过给 columns 数据的项，设置一个函数 render，渲染自定义组件，失效

### ISSUE THREAD

**Issue by mantou-kk** [iview/iview#639]
### 问题现象，以及你期望的结果是怎样的?
最新版本更新后，modal中放table，在table中放入iview组件所有失效
报错如下：
Unknown custom element: <i-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)

**Comment by icarusion** [comment]
provide online code

**Comment by mantou-kk** [comment]
在线代码看不出效果，实际代码是放在了一个组件中，切换回2.0.0-rc.9版本正常;
