### ISSUE TITLE
select组件在Modal组件中下拉列表显示空白的BUG

### ISSUE THREAD

**Issue by PanYX** [iview/iview#640]
### iView 版本号 
2.0.0-rc.8

### 操作系统/浏览器 版本号  
Chrome 55  

### Vue 版本号  
2.2.2

### 能够复现问题的在线示例  
http://js.jirengu.com/yadik/1/edit?html,output

hi icarusion,
我想表达的意思是select组件在Modal组件中，如果Modal组件超出浏览器高度，并且滚动条处于中间偏下的位置时，select组件下拉列表会显示空白

下面的复现步骤增加图片说明：

### 复现步骤
1.modal组件高度超出浏览器高度，而滚动条靠近初始位置，点击select组件能正常工作:
![Uploading 正常显示.jpg…]()

2.当滚动条往下滚动，再次点击select组件，组件下拉列表部分会变空白，继续点击，组件会闪现:
![Uploading 空白状态.jpg…]()

### 问题现象，以及你期望的结果是怎样的?
不管modal组件高度怎样，select组件的显示都不受其影响，正常显示

**Comment by icarusion** [comment]
没看懂，试了没用问题啊

**Comment by PanYX** [comment]
图片上传不成功，我发你admin@aresn.com邮箱吧

**Comment by xugege** [comment]
这个问题修复了，我看在线列子就有问题啊，点开下拉框，下拉选项显示空白，或者会闪烁
