### ISSUE TITLE
级联选择的表单验证依然没修复

### ISSUE THREAD

**Issue by luckyyyyy** [iview/iview#641]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 57

### Vue 版本号
2.2.6

### 问题现象，以及你期望的结果是怎样的?
确认已经更新到rc10 级联选择的表单依然有问题 必填项无法验证 依然false

**Comment by icarusion** [comment]
提供在线示例

**Comment by triunity** [comment]
can‘t work。。。
