### ISSUE TITLE
[Bug Report]List ListItem ListItemMeta 按需引入失败

### ISSUE THREAD

**Issue by ghost** [iview/iview#6419]
### Environment
@vue/cli 4.2.3

### Reproduction link
[https://run.iviewui.com/GPZZkcHz](https://run.iviewui.com/GPZZkcHz)

### Steps to reproduce
使用官网介绍按需引入方法 引入 List,ListItem,ListItemMeta失败
import { List,ListItem,ListItemMeta} from 'view-design'
但是使用 全局使用就不会失败，这是什么问题，还是我的引入方法错误？

### What is expected?
可以使用List组件

### What is actually happening?
无法使用List组件

**Comment by mianhuaqishi** [comment]
![image](https://user-images.githubusercontent.com/20659318/77829474-431b9600-715d-11ea-8219-15b4e7f481f4.png)

const ListItem = List.Item

**Comment by shengyur** [comment]
请问这个问题是如何解决的呀~  试了楼上的用法发现并不行？

**Comment by tcstory** [comment]
```javascript
import { List } from 'view-design'

// 在 vue 的对象里, 这样写
  components: {
    List,
    ListItem: List.Item
  }
```

@shengyur
