### ISSUE TITLE
单独引入某个组建时，table组件中render无法再使用组件。

### ISSUE THREAD

**Issue by waney** [iview/iview#642]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
 macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）
<i-Table :content="this" :columns="appsColumns" :data="list"></i-Table>

不方便做示例，只好直接贴代码了。
`import { iTable, Tag, Poptip } from 'iview'`
`export default {
  name: 'apps',
  components: { iTable, Tag, Poptip },`
.....省略 

appsColumns: [
    { title: '名称', key: 'name' },
    {
          title: '简介',
          key: 'description',
          render (row, column, index) {
            return `<Poptip trigger="hover" title="${row.description.length}个画像" placement="bottom"><i-tag>${row.description.length}</i-tag><div slot="content"><ul><li v-for="item in list[${index}].description" style="text-align: center;padding: 4px">{{ item }}</li></ul></div></Poptip>`
          }
        },

### 问题现象，以及你期望的结果是怎样的?
单独引入某个组建时，table组件中render无法再使用组件。
[Vue warn]: Unknown custom element: <poptip> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)
warn @ vue.esm.js?65d7:558
createElm @ vue.esm.js?65d7:4615
createChildren @ vue.esm.js?65d7:4722
createElm @ vue.esm.js?65d7:4630
patch @ vue.esm.js?65d7:5053
Vue._update @ vue.esm.js?65d7:2033
updateComponent @ vue.esm.js?65d7:2156
get @ vue.esm.js?65d7:2467
Watcher @ vue.esm.js?65d7:2450
mountComponent @ vue.esm.js?65d7:2160
Vue$3.$mount @ vue.esm.js?65d7:7250
Vue$3.$mount @ vue.esm.js?65d7:9299
compile @ iview.js?5654:15287
boundFn @ vue.esm.js?65d7:125
(anonymous) @ iview.js?5654:15311
(anonymous) @ vue.esm.js?65d7:505
nextTickHandler @ vue.esm.js?65d7:454
vue.esm.js?65d7:558
 [Vue warn]: Unknown custom element: <tag> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

### 你估计可能的原因是什么（选填）？
按需引入时能在render中使用组件。

**Comment by mantou-kk** [comment]
我遇到这个问题，10版本更新后就成这样咯，render的东西都失效了

**Comment by waney** [comment]
#639

**Comment by xiaoyyang123** [comment]
just like #651 , I think it can closed.
