### ISSUE TITLE
建议table 的列加入是否显示属性

### ISSUE THREAD

**Issue by miaosun009** [iview/iview#644]
建议table 的列加入是否显示属性
`{
            title: 'ID',
            key: 'id',
            width: 60，
            show:true
          }
`
这样就很方便实现列的现实和隐藏， 虽然现在官方提供了一个案例实现隐藏列，但不是特别完美，

**Comment by 314432150** [comment]
我刚用iview，以前用习惯了bootstrapTable，发现iview的table组件竟然没有控制列显示的属性？请问官方案例在哪个地方，我是通过设置` width:1`和render函数隐藏的。
``` javascript
{
    title: 'ID',
    key: 'ID',
    width: 1,
    render: (h, params) => {}
}
```

**Comment by VivienZhai** [comment]
我受楼上大神的启发，向下面这么写可以隐藏一列 
      {
            title: '角色id',
            key: 'roleId',
            width: 1,
            render: (h, params) => {
              return h('span',{
                style:{
                  display: "none",
                }
              })
            }
          }

**Comment by 8000tank** [comment]
不用加上想隐藏的列，在每行的render按钮中的click事件里，传入的参数（当前行）中，可以直接取到所有列的值

**Comment by NjshawnYue1** [comment]
> ```js
> width: 1,
>     render: (h, params) => {}
> ```

。。。今天用的时候还是没找到隐藏，用下你的就还行
