### ISSUE TITLE
[Bug Report]icon图标不能显示

### ISSUE THREAD

**Issue by taokanghua** [iview/iview#6441]
### Environment
window10 chrome vue2.x

### Reproduction link
[https://run.iviewui.com/xp2Os6z8](https://run.iviewui.com/xp2Os6z8)

### Steps to reproduce
部分icon可以显示  大部分icon都不能显示

### What is expected?
所有图标都能用

### What is actually happening?
希望以后可以改善

---
官网返回顶部 还有左边的菜单栏希望优化一下

**Comment by yangbean4** [comment]
iview的icon中没有person-add
有ios-person-add 如 https://run.iviewui.com/aD9PX8v8

**Comment by kdreaming** [comment]
看一下你用的iview版本和文档的iview是不是一样的，有可能是版本没对应上
http://iview.talkingdata.com/#/components/icon
https://iview.github.io/components/icon
