### ISSUE TITLE
【Badge】徽标数，异步加载数据后错位

### ISSUE THREAD

**Issue by p2ng** [iview/iview#646]
### iView 版本号
2.0.0-rc.6

### 操作系统/浏览器 版本号
win7/chrome 58

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（重要）

https://codepen.io/fsliangzp/pen/QvLyab?editors=1111

### 复现步骤
如例子所示，在模拟延时请求后，标数产生错误

**Comment by icarusion** [comment]
什么错误？

**Comment by CarlosLin** [comment]
一樣碰到這問題

在顯示畫面上 會自動補上兩個class
(ivu-badge-count ivu-badge-count-alone)
導致位置錯誤

**Comment by p2ng** [comment]
![image](https://cloud.githubusercontent.com/assets/7822128/24999832/a2920b18-2071-11e7-86a6-f3cbc1cedde3.png)

@icarusion 
如上代码运行结果。
左三都是模拟异步请求回来，再显示的效果。
右一是静态数据。

数字已经错位啦...跑到`icon`下方

**Comment by lvqingan** [comment]
呵呵，我也遇到过这个问题，有个解决办法：不要把计数的初始值设置为0，而是设置为1

**Comment by okzhu** [comment]
`<Badge :count="list.length || '0' ">*****
</Badge>`
你可以把代码改成这样 在初始化的时候 用 || '0' 这个时候 并不会显示 
而且能达到你想要的效果
