### ISSUE TITLE
[Feature Request]建议新增Carousel组件

### ISSUE THREAD

**Issue by XFX-939** [iview/iview#6461]
### What problem does this feature solve?
Carousel轮播图模板

### What does the proposed API look like?
网页上展示Carousel

**Comment by aoi-umi** [comment]
这个不是吗
https://www.iviewui.com/components/carousel

**Comment by XFX-939** [comment]
谢谢，国内其他组件库把Carousel翻译成轮播图，iview叫走马灯一时没反应过来，哈哈

aoi-umi <notifications@github.com> 于2020年6月8日周一 下午1:39写道：
