### ISSUE TITLE
[Bug Report]input 组件on-change事件返回的data有误

### ISSUE THREAD

**Issue by ranckprogram** [iview/iview#6465]
### Environment
win10 chrome 81 vue2.6.1

### Reproduction link
[https://run.iviewui.com/ZkKUY3AP](https://run.iviewui.com/ZkKUY3AP)

### Steps to reproduce
input中输入值，通过watch 和  on-change 监听获取的值不一样，watch的值正确，但是on-change 监听的值使用只能拿到最后输入的值

### What is expected?
on-change 监听的值 和watch 值一致

### What is actually happening?
on-change 监听的值使用只能拿到最后输入的值

**Comment by ranckprogram** [comment]
![image](https://user-images.githubusercontent.com/22071583/82871017-70b96b80-9f63-11ea-9a53-c5f1f7043efa.png)

**Comment by DebugIsFalse** [comment]
这是思维方式问题，既然你选择了双向绑定了就不需要获取on-change的返回值。
