### ISSUE TITLE
[Bug Report]内存泄露——Select组件

### ISSUE THREAD

**Issue by ghost** [iview/iview#6497]
### Environment
Win10  Google Vue2.0

### Reproduction link
[https://www.iviewui.com/components/select](https://www.iviewui.com/components/select)

### Steps to reproduce
切换A B C 三个SPA页面，未用keep-alive。
A/B/C 三个页面都有Select组件，随着切换的次数增多，内存跟随增多，不会随着组件销毁而释放。

### What is expected?
内存回收

### What is actually happening?
内存一直增长

**Comment by demonray** [comment]
从内存快照看因为popper scheduleupdate的原因，暂时项目里patch解决了
