### ISSUE TITLE
Grid栅格设置gutter属性后，总宽度会大于屏幕宽度

### ISSUE THREAD

**Issue by Peterlhx** [iview/iview#650]
### iView 版本号

2.0.0-rc.7

### 操作系统/浏览器 版本号

windows 10/Chrome

### Vue 版本号

2.2.6

### 能够复现问题的在线示例（重要）

![Uploading QQ截图20170411162352.png…]()

屏幕像素为1920*1080，设置gutter=16后，没有出现间隔，整块的宽度变为1936

### 问题现象，以及你期望的结果是怎样的?
栅格之间出现间隔，并且总宽度不超过屏幕宽度

**Comment by icarusion** [comment]
按要求提问
