### ISSUE TITLE
iview的表格columns项中设置一个render函数，在函数内所有iview组件无法生效

### ISSUE THREAD

**Issue by mantou-kk** [iview/iview#651]
### iView 版本号
 2.0.0-rc.10

### 操作系统/浏览器 版本号
windows10/Chrome 56

### Vue 版本号
 2.2.1

### 能够复现问题的在线示例（重要）
问题出现在vue独立组件中发生，所以在线代码演示不出效果;

### 问题现象，以及你期望的结果是怎样的?

iview的表格columns项中设置一个render函数，在函数内所有iview组件无法生效

### 你估计可能的原因是什么（选填）？
vue.esm.js?d2fe:559 [Vue warn]: Unknown custom element: <i-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)

**Comment by icarusion** [comment]
那我反问一句，iView 文档为什么可以

**Comment by mantou-kk** [comment]
@icarusion 不知道iView是否已经更新了10版本，我返回9版本同样的代码是可以的;

**Comment by icarusion** [comment]
iView 文档当然是最新的了

**Comment by mantou-kk** [comment]
@icarusion 那好吧，麻烦了

**Comment by icarusion** [comment]
所以做好提供完整的仓库

**Comment by waney** [comment]
# #642 @icarusion 是按需引入组件时不行.

**Comment by xiaoyyang123** [comment]
如果是局部引入的，用`Vue.compomemt`可以解决这个问题，例如：
`import Vue from 'vue';`;
`import Button from 'iview/src/components/button';`
`Vue.component('i-button', Button);`
在render函数中就可以使用`<i-button type="primary">confirm<i-button>`；
因为这个`i-button`组件并不是在当前模块中渲染的，你仅仅在当前模块注册是没用的。

**Comment by icarusion** [comment]
所以，这类问题有什么结论了吗？

**Comment by mantou-kk** [comment]
关了吧，麻烦了，非常抱歉！

**Comment by ai116458960** [comment]
import iView from 'iview'
Vue.use(iView)
在table里面依然是注册状态  不知道怎么解决，求楼主指点迷津！

**Comment by tenadolanter** [comment]
有点后悔使用iview了  文档好垃圾
