### ISSUE TITLE
Date-picker验证功能无法正常工作

### ISSUE THREAD

**Issue by PanYX** [iview/iview#652]
### iView 版本号
2.0.0-rc.8

### 操作系统/浏览器 版本号
win7/Chrome 55

### Vue 版本号
2.2.2

### 复现步骤
见例子：http://js.jirengu.com/fefig/2/edit?html,output

### 问题现象，以及你期望的结果是怎样的?
Date-picker验证规则为required时，为空则不通过验证，不为空时通过验证

### 你估计可能的原因是什么（选填）？
相应字段验证规则队列没有及时执行

**Comment by icarusion** [comment]
字段写错了

**Comment by PanYX** [comment]
我看了几遍，没发现有字段写错了啊。。。真写错的话能否告知一下哪写错了？
