### ISSUE TITLE
select 如何绑定动态数组

### ISSUE THREAD

**Issue by jl6278462** [iview/iview#653]
### 代码展示
`<Select placeholder="省" v-model="provinceId" clearable style="width:150px">
          <Option v-for="item in provinceList" :value="item.id">{{ item.shortName }}</Option>
        </Select>`

`mounted(){
      this.initData()
    }`

`    methods: {
      //初始化时获取基本数据
      initData(){
        //获取省列表
        this.$http.put('/api/cnarea/read/list', {
          parentId: 0
        }).then(response => {
          if (response.data.httpCode == 200) {
            this.proviceList = response.data.data;
          } else {
            this.$Message.error(response.data.msg);
          }
        })

      }}`

### 问题现象
ajax请求的数据绑定不了，组件不是做了双向绑定

### 你估计可能的原因是什么（选填）？
未双向绑定，或者只能set设置，亲如果是set赋值应该如何写，能给取个例子吗？急！！！！

**Comment by Jerrrylin** [comment]
老哥你解决了嘛，我的也没有生效在找原因
