### ISSUE TITLE
关于iInput的trim问题

### ISSUE THREAD

**Issue by simple-hui** [iview/iview#655]
### iView 版本号
1.x版本

### 操作系统/浏览器 版本号

windows系统 chrome 57
### Vue 版本号

1.x版本
### 能够复现问题的在线示例（重要）

在vue中的input使用v-model双向绑定可以 增加修饰符v-model.trim=“”，那么在Iview中 使用:value.sync=“” 有没有修饰符的添加

**Comment by icarusion** [comment]
没有
