### ISSUE TITLE
修改一行数据，整个table重新渲染吗

### ISSUE THREAD

**Issue by wolfsilver** [iview/iview#656]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
win7/ Chrome/57.0.2987.133

### Vue 版本号
2.2.2

### 问题现象，以及你期望的结果是怎样的?
修改一行数据，整个table重绘

![gif](https://cloud.githubusercontent.com/assets/2452450/24938479/0a70bf8a-1f6a-11e7-910e-2f47e8c23cbc.gif)

**Comment by htoooth** [comment]
我也碰到这个问题了

**Comment by wolfsilver** [comment]
https://github.com/iview/iview/pull/708

用了一个不完美的方案，需要手动修改绑定的key，数据才会更新
