### ISSUE TITLE
关于menu被table fixed层遮住的问题

### ISSUE THREAD

**Issue by BlueGene89** [iview/iview#657]
我在一个页面用了水平menu及menu group，有下拉菜单，下方有一个table，当table设定了fixed的时候，如果menu下拉菜单内容过长会被table的fixed遮住，导致无法选择菜单。

### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
windows10/Chrome 56

### Vue 版本号
2.2.6

**Comment by icarusion** [comment]
提供在线示例

**Comment by BlueGene89** [comment]
@icarusion 你好，我后面直接将menu的div设了z-index:999 解决了问题
