### ISSUE TITLE
文档是开源的吗？

### ISSUE THREAD

**Issue by zce** [iview/iview#66]
弱弱的问一句，`iview`的[文档](https://www.iviewui.com/)是开源的吗？

**Comment by icarusion** [comment]
因为文档太重，不太方便维护，暂时没有开源。

**Comment by zce** [comment]
OK, Thanks, 多嘴问一句：计划开源吗？

**Comment by icarusion** [comment]
这有啥好开源的😂

**Comment by zce** [comment]
大家可以一起参与嘛，`iview`还是很不错的

**Comment by icarusion** [comment]
因为目前文档分离偏重，计划后面会提供一个更好的方案反馈bug及翻译

**Comment by zce** [comment]
https://www.iviewui.com/docs/guide/standard

> export出的对象使用驼峰命名，比如`Page`、`ButtonGroup`

这里好像就有问题，一个应该是`Pascal`吧

还有，为什么在命名组件时，有的加了`i`前缀，有的又没有加，个人感觉会增加使用者的学习成本

**Comment by icarusion** [comment]
与原生冲突要加前缀

**Comment by zce** [comment]
我知道是因为和原生元素冲突，只是觉得不统一的话对使用者不太友好

**Comment by zce** [comment]
个人愚见 thanks @icarusion

**Comment by icarusion** [comment]
你可以自己加，比如
{ iPage: Page }

**Comment by zce** [comment]
👌
