### ISSUE TITLE
Slider 步长设置小于1无效

### ISSUE THREAD

**Issue by Alan110** [iview/iview#660]
### iView 版本号

2.0.0-rc.9
### 操作系统/浏览器 版本号

macOS/Chrome 57
### Vue 版本号

2.2.2
### 示例代码

```
<Slider v-model="lineheight" style="width:200px" :max="5" :min="1" :step="0.5" class="gutter" ></Slider>
```

### 问题现象，以及你期望的结果是怎样的?

现象 ： step设置为小于1时，默认以1为步长移动.
期望 ： 可以设置小于1的步长

### 你估计可能的原因是什么（选填）？

是否是做了什么最小值的处理？

**Comment by icarusion** [comment]
目前滑动不支持小数，需要自己转换数据。不过可以通过自定义 `tip-format` 给用户提示。你的显示数据是整数，但使用数据可以用 computed 来转换为小数。
