### ISSUE TITLE
tab增加左右滑动的按钮，当tab数量超过父级宽度之后

### ISSUE THREAD

**Issue by excellnn** [iview/iview#661]
### iView 版本号
^2.0.0-rc.9

### 操作系统/浏览器 版本号
ubuntu/chrome 54.0.2840.100 (64-bit)

### Vue 版本号
^2.2.2

### 能够复现问题的在线示例（重要）
https://codepen.io/liuniannan/pen/QvLXeY

### 复现步骤
点击超过7次增加按钮
### 问题现象
tab数量超过父级宽度之后，导致右边超出的tab无法被选取
### 以及你期望的结果是怎样的?
当tab数量超过父级宽度之后，出现可以左右滑动的按钮
### 你估计可能的原因是什么（选填）？
没有做这个功能

**Comment by kumakumasan** [comment]
这个问题确实蛮困扰项目开发；如果能像element那样增加一个左右箭头也行；或者直接让tabs成为多行，都可以接受；

**Comment by x851285009** [comment]
数目很多的TAB应用的场景不是很多吧

**Comment by kumakumasan** [comment]
企业内部系统开发中，经常会需要在不同的表格之间对照数据，这时候就会用到Tab页来切换数据视图。

**Comment by littlexiang** [comment]
`.ivu-tabs-nav-scroll {
    overflow: scroll;
}`
可以先这么凑合一下...
tab非常多的场景 以前我是用icon-button代替模拟, 两行堆叠下来, 也不用左右滑动, 其实更加直观

**Comment by excellnn** [comment]
打开很多tab页的情况还是蛮普遍的，这个功能我觉得是非常必要，毕竟组件开发出来就是要适应不同的情况。

**Comment by icarusion** [comment]
#1031
