### ISSUE TITLE
Table组件中过滤后无数据时报错：Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by WangLei1993** [iview/iview#662]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

Microsoft Windows [版本 6.1.7600]
Chrome 53.0.2785.116 m
### Vue 版本号

2.2.2
### 能够复现问题的在线示例（重要）

暂无创建
### 复现步骤
Tab组件中嵌入Table组件，Table中启用过滤，设定特定过滤条件，造成过滤后Table中无数据，此时切换tab页，引起Table组件调用handleResize方法。
### 问题现象，以及你期望的结果是怎样的?
问题现象：TypeError: Cannot read property 'querySelectorAll' of undefined。
期望结果：筛选数据为空时也不报上述错误
### 你估计可能的原因是什么（选填）？
可能原因：table-body组件中渲染的是过滤后的数据，当过滤后无数据时，tbody 中无tr，自然执行第二个querySelectorAll时引起报错。
解决方法：将`handleResize`中的`if (this.data.length)`更改为`if (this.rebuildData.length)`，这样会根据过滤后的数据情况往下执行，就不会报上述错误。

**Comment by zhangfu-git** [comment]
+1
"iview": "^2.1.0"
进行数据过滤后，获取下页数据。filterMethod返回false时，出现Vue warn]: Error in nextTick: "TypeError: Cannot read property 'querySelectorAll' of undefined"

**Comment by icarusion** [comment]
Update to the latest version.
