### ISSUE TITLE
希望select filterable功能支持option异步加载

### ISSUE THREAD

**Issue by shownoso** [iview/iview#665]
### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
Chrome 56 

### Vue 版本号
 2.1.0

### 问题现象，以及你期望的结果是怎样的?
filterable功能条件下，输入文本时，根据输入文本请求远程数据，修改v-for中的list，达到option更新的目的，但是会因为dropdown隐藏产生input失焦事件，导致输入值被清空，无法得到预期dropdown中option更新的结果。

**Comment by icarusion** [comment]
已知需求
