### ISSUE TITLE
[Bug Report]同页面中存在两种组件Input和Poptip(trigger="click")时，点击出现气泡提示，再点击聚焦到Input，气泡提示未消失

### ISSUE THREAD

**Issue by jinyu-zhixuan** [iview/iview#6656]
### Environment
vue@^2.5.13 实际版本@2.7.10; iview@^2.8.0 实际版本@2.14.3; chrome 106; mac M1

### Reproduction link
[https://run.iviewui.com/SKYfezOu](https://run.iviewui.com/SKYfezOu)

### Steps to reproduce

      1. 点击激活气泡
      2. 点击聚焦到下方输入框
      3. 气泡未消失

### What is expected?
气泡消失

### What is actually happening?
气泡未消失

**Comment by ChenguangWang** [comment]
自己控制显示隐藏，可以使用clickoutside控制消失

**Comment by jinyu-zhixuan** [comment]
感谢
