### ISSUE TITLE
Table 组件的宽度自适应问题，只有在浏览器窗口改变时宽度再会改变。

### ISSUE THREAD

**Issue by sunioio** [iview/iview#666]
Table 组件的宽度自适应问题，只有在浏览器窗口改变时宽度再会改变。比如，左侧菜单如果通过按钮隐藏掉，这时浏览器没变化，只是元素的隐藏，表格的父容器的宽度已经变化。此时 table 宽度不会改变，导致右侧出现空白，

**Comment by icarusion** [comment]
已知问题
