### ISSUE TITLE
组件按需引用时报错

### ISSUE THREAD

**Issue by scaupdc** [iview/iview#667]
"iview": "^2.0.0-rc.9"

main.js中这样引用：
import Button from 'iview/src/components/button';
import Card from 'iview/src/components/card';
import Icon from 'iview/src/components/icon';
import Input from 'iview/src/components/input';
import Menu from 'iview/src/components/menu';
import Table from 'iview/src/components/table';
import Message from 'iview/src/components/message';
import Modal from 'iview/src/components/modal';
import 'iview/dist/styles/iview.css'

Vue.component(Button.name, Button)
Vue.component(Card.name, Card)
Vue.component(Icon.name, Icon)
Vue.component(Input.name, Input)
Vue.component(Menu.name, Menu)
Vue.component(Table.name, Table)
Vue.component(Message.name, Message)
Vue.component(Modal.name, Modal)

编译通过，但运行时报错：
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (eval at <anonymous> (http://localhost:8080/app.js:798:1), <anonymous>:43:38)
    at Object.isReservedTag (eval at <anonymous> (http://localhost:8080/app.js:798:1), <anonymous>:4320:28)
    at Function.Vue.(anonymous function) [as component] (eval at <anonymous> (http://localhost:8080/app.js:798:1), <anonymous>:4000:46)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1210:1), <anonymous>:35:46)
    at Object.<anonymous> (http://localhost:8080/app.js:1210:1)
    at __webpack_require__ (http://localhost:8080/app.js:687:30)
    at fn (http://localhost:8080/app.js:106:20)
    at Object.<anonymous> (http://localhost:8080/app.js:2220:18)
    at __webpack_require__ (http://localhost:8080/app.js:687:30)
    at http://localhost:8080/app.js:784:39

我的package.json如下：
"dependencies": {
    "iview": "^2.0.0-rc.9",
    "vue": "^2.2.6",
    "vue-router": "^2.3.1",
    "vuex": "^2.2.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-component": "^0.9.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.2.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "function-bind": "^1.1.0",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "node-sass": "^4.5.2",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.1.0",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.3",
    "semver": "^5.3.0",
    "url-loader": "^0.5.7",
    "vue-loader": "^11.1.4",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.2.4",
    "webpack": "^2.2.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1"
  }

**Comment by icarusion** [comment]
建议一个一个引用排查问题

**Comment by Foreverofh** [comment]
楼主解决了吗!

**Comment by scaupdc** [comment]
@Foreverofh 暂时没解决，就先导入整个iView用着，回头再查查问题

**Comment by thjiang** [comment]
和楼主一样，试了一下貌似是Card的问题

**Comment by doublemin** [comment]
和楼主一样遇到这个问题

**Comment by rijn** [comment]
Some components are missing props `name`

**Comment by bruce6771** [comment]
在main.js里：
```
import Modal from 'iview/src/components/modal';
import Button from 'iview/src/components/button';
import 'iview/dist/styles/iview.css';    // 使用 CSS
Vue.component('Modal', Modal);
Vue.component('Button', Button);
```
在webpack.base.config.js
```
module: {
    rules: [
      { test: /iview.src.*?js$/, loader: 'babel-loader' },
      { test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ },
```
但是编译出来的文件总尺寸仍有4兆之多
