### ISSUE TITLE
select 显示有问题

### ISSUE THREAD

**Issue by youthour** [iview/iview#669]
### 问题现象，以及你期望的结果是怎样的?
select 组件 ，filterable = true,
当select有默认值时，第一次点击select中内容，如图所示，内容在左上角去了，以后点击就不会了，
每当刷新页面的第一次点击会是这样的。

### 你估计可能的原因是什么（选填）？
![image](https://cloud.githubusercontent.com/assets/18053326/24987715/089a33ba-2034-11e7-8122-0f8acb5d6857.png)

**Comment by miaosun009** [comment]
我也遇到这样的问题，

**Comment by Alecyrus** [comment]
你们解决了吗？

**Comment by Alecyrus** [comment]
查看 #818， 我的问题和你的很类似，可以看看我找到的原因是不是和你一样。@	youthour

**Comment by icarusion** [comment]
#818
