### ISSUE TITLE
Date-picker 在 daterange模式下 confirm 选项无法关闭

### ISSUE THREAD

**Issue by ngloom** [iview/iview#672]
### 能够复现问题的在线示例（重要）

问题代码如下 

      <Date-picker
          type="datetimerange"
          placeholder="起始时间"
          format="yy年MM月dd"
          :confirm=false
      ></Date-picker>

### 问题现象，以及你期望的结果是怎样的?
像type='date'时一样,选择完日期区间后, 组件关闭, value更新.

### 你估计可能的原因是什么（选填）？
daterange模式下没有考虑 confirm参数.

**Comment by icarusion** [comment]
提供在线示例
