### ISSUE TITLE
Date-picker 中confirm模式开启后, 日期数据在用户确认之前就已经更新并触发了on-change事件

### ISSUE THREAD

**Issue by ngloom** [iview/iview#673]
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

        <Date-picker
            type="date"
            :confirm=true
        ></Date-picker>

### 问题现象，以及你期望的结果是怎样的?
![qq20170413-112554](https://cloud.githubusercontent.com/assets/495831/24989016/0dbe8c1c-203c-11e7-86eb-b9f295c42c83.gif)

期望: 用户在确认之前不应触发on-change事件.

**Comment by icarusion** [comment]
是的
