### ISSUE TITLE
Date-picker 在 daterange模式下 confirm 选项无法关闭

### ISSUE THREAD

**Issue by ngloom** [iview/iview#674]
### iView 版本号
2.0.0-rc.10

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/nglooom/pen/RVwJEw

### 问题现象，以及你期望的结果是怎样的?
daterange应与date的行为一致

**Comment by icarusion** [comment]
看文档

**Comment by ngloom** [comment]
@icarusion ,

文档上是这样描述的
![image](https://cloud.githubusercontent.com/assets/495831/24994520/ccd2d024-205d-11e7-9be6-105348a21700.png)

但是  https://codepen.io/nglooom/pen/RVwJEw 这里, 
```
  <div>
    <Date-picker
    type="datetimerange"
    ></Date-picker>
  </div>
```
生成的控件明显带着**确认栏**,

![image](https://cloud.githubusercontent.com/assets/495831/24994598/23d1b4f8-205e-11e7-9359-4603a6eb1cf4.png)


而把type从datetimerange 改成 date之后, 确认栏消失,

![image](https://cloud.githubusercontent.com/assets/495831/24994632/48248dbc-205e-11e7-958c-6c52430b4326.png)

同样的一个控件, 行为不应该是一致的么

**Comment by p2ng** [comment]
@ngloom 我也遇到同样的问题
`<Date-picker v-model="form.createAt" type="datetimerange" placeholder="请选择时间搜索..." :editable="false" @on-change="findProductRelease"></Date-picker>`

`type: datetimerange`模式下，:confirm='false'不起作用的...

我怀疑是文档描述得不清楚...

@icarusion 
要求文档书写易懂...`confirm`只对`type: date`生效等字眼...
