### ISSUE TITLE
Table的多选模式中，取消选择并未触发on-select-change事件

### ISSUE THREAD

**Issue by airuqixue** [iview/iview#679]
### iView 版本号
2.0.0-rc.9

### 操作系统/浏览器 版本号
Chrome 56 

### Vue 版本号
 2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
Table 的多选，没有取消事件。也就是取消了选择后，必须再次选择另外的行才能监听到。

### 复现步骤
Table 中设置列为 selection
选中一行，再取消选中，此时 on-select-change 事件并未触发

### 问题现象，以及你期望的结果是怎样的?
取消选择时，触发 on-select-chagne 事件

**Comment by icarusion** [comment]
按要求提问

**Comment by p2ng** [comment]
@airuqixue 
`on-selection-change`这个方法才是
