### ISSUE TITLE
Date控件类型为daterange并且设为必填时，blur无法触发错误信息的显示

### ISSUE THREAD

**Issue by lvqingan** [iview/iview#680]
### iView 版本号
 2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 59

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[http://jsbin.com/cihohopubu/edit?html,css,js,output](http://jsbin.com/cihohopubu/edit?html,css,js,output)

### 问题现象，以及你期望的结果是怎样的?
现象：无法正确触发blur检测

其他：和其他表单项一样能够在blur的时候正常显示错误信息并执行验证

### 你估计可能的原因是什么（选填）？
daterange的值是数组，不是空字符串，required对空数组的判断可能有问题

**Comment by coujk** [comment]
同求这个问题解决，daterange不能设置必填

**Comment by icarusion** [comment]
校验类型不对
