### ISSUE TITLE
关于Rate events on-change 如何传值。

### ISSUE THREAD

**Issue by waney** [iview/iview#681]
### iView 版本号
 2.0.0-rc.10 

### 操作系统/浏览器 版本号
 macOS/Chrome 56 

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
Rate events #
事件名	说明	返回值
on-change	评分改变时触发	value
[https://www.iviewui.com/components/rate](url)

文档中on-change返回了value，当组件应用在列表时（多个Rate），如何传值，获得如何得到当前Rate 属性或参数。

### 问题现象，以及你期望的结果是怎样的?
我想传递参数，比如ID。

**Comment by SergioCrisostomo** [comment]
@waney can you explain your problem more? Is this what you look for ([jsFiddle](https://jsfiddle.net/Sergio_fiddle/1kbLvtdh/))?

I will close this now. Please re-open if your problem still exists.
