### ISSUE TITLE
select 动态渲染option，选择选项后，校验还是不通过。

### ISSUE THREAD

**Issue by mbc3320** [iview/iview#682]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://runjs.cn/code/osloceth
### 复现步骤
第一个选择框，选择选项了，点击测试校验通过，
第二个选择框，选择选项了，点击测试校验不通过
### 问题现象，以及你期望的结果是怎样的?
![1](https://cloud.githubusercontent.com/assets/5523726/25040287/f2bc55b6-213a-11e7-940b-9269539798fa.png)

测试了一下，如果select的 option是直接写的，校验正常；
但当option是动态渲染的（v-for），校验不生效。

**Comment by CodeMonkeyXu** [comment]
我也碰到了同样的问题，你现在解决了吗？

**Comment by kimvin** [comment]
rule 里增加 type 的设置：
`{ required: true, type: 'number', message: '', trigger: 'change' }`

建议看[https://github.com/yiminghe/async-validator](https://github.com/yiminghe/async-validator)
