### ISSUE TITLE
PAGE 分页组件的 page-size 下拉菜单会出现位置异常！

### ISSUE THREAD

**Issue by sunioio** [iview/iview#684]
### 操作系统/浏览器 版本号
 macOS/Chrome 56

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?

PAGE 分页组件的 page-size 下拉菜单会出现位置异常！上面数据用的table 组件,下面一个div 中放的分页组件，然后就出现这种情况，列表内容越多，距离偏差越大，分页组件放在table 最上面的话上正常的。

![image](https://cloud.githubusercontent.com/assets/17401145/25043671/48981984-2154-11e7-8c15-e48bcf68506c.png)

**Comment by duandun** [comment]
同遇到了这个问题。。。2.0.0-rc.13版本里

**Comment by icarusion** [comment]
Update to the latest version
