### ISSUE TITLE
向 Poptip  传时间值，让其过一段时间之后自动隐藏

### ISSUE THREAD

**Issue by houzw** [iview/iview#685]
### iView 版本号
2.0.0-rc.6

### 操作系统/浏览器 版本号
win 10 64位

### Vue 版本号
2.2.1

### 问题现象，以及你期望的结果是怎样的?
在input上使用 Poptip 或 Tooltip 时，在输入内容时，Poptip 会一直显示。希望能传一个时间值，让提示过一段时间之后自动隐藏

**Comment by icarusion** [comment]
可以用 focus 或 custom 啊
