### ISSUE TITLE
Affix元素与Tabs混合使用导致失效

### ISSUE THREAD

**Issue by littlexiang** [iview/iview#686]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 57.0.2987.133 (64-bit)

### Vue 版本号
2.2.6

### 复现步骤
在多重tabs内使用Affix无法实现吸顶

### 你估计可能的原因是什么（选填）？
由于tabs默认animated动画使用了transform, 所以Affix的position:fixed会相对于tab定位
https://developer.mozilla.org/zh-CN/docs/Web/CSS/position#取值

### 解决办法
对所有上层tabs组件加上:animated="false"

### 建议
如果要实现非常良好的兼容, 可能还是要使用js计算absolute定位的方式

**Comment by Tilang** [comment]
楼主解决这个问题没。按照你这个加了。但是还是没用

**Comment by icarusion** [comment]
You can manually set animated

**Comment by BangKk** [comment]
@Tilang 看下你的父元素是否有overflow: auto;这个属性会导致scroll事件失效。

**Comment by money4marry** [comment]
赞一个，差点自己去重写组件了。我的是TimePicker和Tabs一起用，弹出层会被定位偏移出去，加上这个之后，不开启动画效果，没有transform属性然后定位就正常了。话说position:fixed会受transform这个bug一直都存在，渲染引擎级别的问题。
