### ISSUE TITLE
2.0-rc10 [严重]Select组件当Option达到一定数量后浏览器挂起

### ISSUE THREAD

**Issue by marslabtron** [iview/iview#687]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 56、57 & Windows /Chrome 56 & Linux ...

### Vue 版本号
2.2.1 - 2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
\<Select\>
  \<Option v-for="n in 1000"\>{{n}}\</Option\>
\</Select\>

### 复现步骤
我传入了一个length为300的Array，component挂载的时候浏览器直接卡主很长时间，我传入一个length为1000的Array，浏览器就不响应了。

### 问题现象，以及你期望的结果是怎样的?
建议加入类似clusterize之类的办法来解决这个问题，但是由于filterable的机制需要明确将所有数据加载进来，所以这个问题需要大家一起讨论。

### 你估计可能的原因是什么（选填）？
在Select中加入了两个事件监听，所以每mount一个Option都会触发执行。

**Comment by icarusion** [comment]
这是避免不了的问题，你同时渲染 1000 个 Vue 组件也会卡。所以不要渲染这么多，在你的业务逻辑上优化。

**Comment by BruinY** [comment]
相当暴力的使用模式。难道真的会有这样的业务出现？

**Comment by thtznet** [comment]
下拉值改ajax取数并及分页ajax拉取，就不了，超过20候选词我觉得就应该用搜索而不是直接选取了。

**Comment by starding** [comment]
补充几句

**一些简单的优化尝试**
我试着用v-if控制渲染时机，需要时才渲染option，但依然会卡，200+个数据就不行了（200+个option大概需要3s）。


**select2**
以前使用jQuery时用的select2插件，同样的数据量这个插件优化的更好，几乎感觉不到卡顿现象。看来有必要看一下它是怎么优化的。


**关于搜索**
@thtznet 说的超过20词用搜索，确实这是一个业务上的解决方式，但是有些场景下的搜索有个前提：「搜索人清晰地知道自己想要搜索的关键词」，也就是说搜索起不到列表那样的「教育作用」。
