### ISSUE TITLE
tabs组件默认激活tab-pane时，标签的ivu-tabs-ink-bar位置错误

### ISSUE THREAD

**Issue by nicegonice** [iview/iview#689]
### iView 版本号

^2.0.0-rc.9

### 操作系统/浏览器 版本号

chrome

### Vue 版本号

2.x

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

```
<iTabs v-model="tabActive">
   <iTabsPane label="访问授权" icon="earth" name="visit"></iTabsPane>
    <iTabsPane label="访问授权" icon="earth" name="member"></iTabsPane>
</iTabs>
data () {
   return {
   tabActive: ''
  },
  watch: {
      $route (route) {
        const routerQuery = route.query
        this.tabActive = routerQuery.tabActive
      }
  }
}
```

### 问题现象，以及你期望的结果是怎样的?
每次进来这个组件都是能正确获取到route.query的，而且点击tabs的标签切换的时候，data的tabActive也有跟着改变。但是每次刚进入到这个组件的时候，比如我的tabActive是'member',组件能正确激活member的tabpane，标签显示也跟着激活了，但是标签底部的ivu-tabs-ink-bar没有跟着过来，仍然在另外一个标签

**Comment by swit1983** [comment]
请问一下 你是把路由加载到某一个tab吗？

**Comment by nicegonice** [comment]
不是，只是切换而已
