### ISSUE TITLE
table 列的宽度是否自撑开	

### ISSUE THREAD

**Issue by fengyuchenglun** [iview/iview#690]
当父容器的宽度变大的时候，列的宽度不会自动撑开，页面很丑。
![qq 20170415151231](https://cloud.githubusercontent.com/assets/11927244/25061696/b2688b2e-21ee-11e7-822b-a1722da43b50.png)

看饿了么ui  有个fit属性

**Comment by Alan110** [comment]
table 标签加个 width:100% ，就可以了把

**Comment by fengyuchenglun** [comment]
no  是不行的  table 虽然width 100%  但是里面的列头跟各列的宽度还是固定值

**Comment by yuanjiahui** [comment]
需要触发window的resize事件，table宽度才能更新
可以这样写：
if (document.createEvent) {
          var event = document.createEvent("HTMLEvents");
          event.initEvent("resize", true, true);
          window.dispatchEvent(event);
        } else if (document.createEventObject) {
          window.fireEvent("onresize");
        }

**Comment by YikaJ** [comment]
源码里的自适应是通过 reset 事件进行的，建议暴露出这个接口

**Comment by onlinelemon** [comment]
默默处理好不行么，不建议hack方法，期待官方修复。  
貌似是修改父级宽度，没有对table宽度进行计算赋值  
```<table style="width: 1333px;"></table>```

#### 临时解决方案：
1. 修改父宽后，手动更新/渲染table
2. 修改父宽后，手动触发window的resize事件

**Comment by iamwelk** [comment]
强烈建议表格宽度提供自适应的方式

**Comment by GordonZH** [comment]
希望官方增加表格宽度自适应的方法。现在侧边栏收起时表格右侧会空一大块。

**Comment by chenkongming** [comment]
同遇到这样的问题

**Comment by chenkongming** [comment]
去改iview.js中源码吧，tableStyle这个对象

**Comment by fengyuchenglun** [comment]
感觉要官方提供一下最好

**Comment by chenkongming** [comment]
我刚改了iview.js中的style.width,全部改为100%，有效了。懒得等官方啊，昨晚我改它们写的组件，然后都build不了→_→，不知道他们能不能get到这个issue

**Comment by pollux2015** [comment]
确实有这个需求

**Comment by zhonglianicon** [comment]
希望官网尽快能解决一下这个问题

**Comment by no5no6** [comment]
临时解决方案
```
html:
<Table ref='tableData' :columns="table.columns" :data="table.data" ></Table>

js:
window.onresize = event => {
  this.$refs.tableData.handleResize();
}
```

**Comment by thearabbit** [comment]
Where for `window....`
I tried, but don't work
```js
    mounted() {
        window.onresize = event => {
            this.$refs.tableData.handleResize();
        }
    },
```

**Comment by no5no6** [comment]
Have a try

```
window.addEventListener('resize', ()=>{ 
    this.$refs.tableData.handleResize();
});
```

**Comment by thearabbit** [comment]
I tried, but don't know where to put this?
```js
created(){........},
mounted(){.......},
.....

**Comment by xiaohaiH** [comment]
I tried, but don't know where to put this?
mounted And created All not line
```
        window.onresize = event => {
            this.$refs.tableData.handleResize();
        }
```

**Comment by BingBlog** [comment]
I looked at the table code. I found Table actually is combination of two tables, one for the header, another for the body. This is the reason of the problem.

Use table need set width to every column, otherwise it will automatically set a width. It must keep the width of col in the header the same as in the body. 
![image](https://user-images.githubusercontent.com/22095959/58149614-3fde9080-7c96-11e9-890f-03a0795ee310.png)

 The result of this design make another problem. It is hard to keep the table cell's width flex to the content.

**Comment by spider-liu** [comment]
@BingBlog 我也发现这个问题了，现在想让列宽跟随数据长度自适应，不换行，你这个setCellWidth方法是怎么解决的，改了源码吗

**Comment by MIMI180306** [comment]
@BingBlog 我也发现这个问题了，现在想让列宽跟随数据长度自适应，不换行，你这个setCellWidth方法是怎么解决的，改了源码吗

**Comment by Laev** [comment]
第1步：给Table组件添加一个类名

`<Table class="auto-width"></Table>`

第2步：写样式
```
.auto-width{
        width: calc(100vw - 200px - 92px);
}
```

**Comment by WoolenWang** [comment]
Iview 3.1.0还是没有改好这个问题
![image](https://user-images.githubusercontent.com/3388253/64063037-585d3000-cc21-11e9-9d09-d58628bc3648.png)

**Comment by zhangchengfei5** [comment]
> 

在watch监听显隐的时候加上试试
