### ISSUE TITLE
Table on-row-click 事件如何获取index

### ISSUE THREAD

**Issue by Alan110** [iview/iview#693]
### iView 版本号
2.0.0-rc.9

### 操作系统/浏览器 版本号
macOS/Chrome 57

### Vue 版本号
2.2.2

### 示例代码
```javascript
<Table :columns="eventColumns" @on-row-click="showEvent"  size="small"  :data="curLayer.eventList" class="selectedEventList"></Table>

{
    showEvent(data){
         console.log(data)
    }
}
```

### 问题现象，以及你期望的结果是怎样的?

现象 ： 目前事件只能获取当前行的数据，并且不是原引用，无法使用 Array.indexOf 获取index，目的是希望把这行数据删掉

期望 ： 可以获得当前行的index

**Comment by jinkin1995** [comment]
+1

**Comment by qinghua5453** [comment]
请问 通过你这样的方式 能获取到当前行的数据吗？我当前行都获取不到

**Comment by qinghua5453** [comment]
好坑啊 我在on-row-click 后面的方法名后面加了一个括号，死活获取不到当前行，多谢了。

**Comment by qiancheng1203** [comment]
+1

**Comment by lightforward2314** [comment]
试一下这个
showEvent(data, index){
        console.log(data, index)
}

**Comment by Fettes** [comment]
大白头像可行 官网api有介绍
