### ISSUE TITLE
按需引入bable编译出错

### ISSUE THREAD

**Issue by leileihzao** [iview/iview#694]
我npm install后在main.js里面引入css文件，然后在build->webpack.base.conf.js里面把
{ test: /iview.src.*?js$/, loader: 'babel' },
 { test: /\.js$/, loader: 'babel', exclude: /node_modules/ }
写进去，然后编译就出错了，提示信息：
These relative modules were not found:

* ./build/dev-client in multi ./build/dev-client ./src/main.js
* ./src/main.js in multi ./build/dev-client ./src/main.js

请问各位大神，这是什么情况啊

**Comment by dean5277** [comment]
一般这个是路径错误，exclude的时候用绝对路径试下。
