### ISSUE TITLE
关于form表单校验的问题(深度属性校验 validate deep object properties)

### ISSUE THREAD

**Issue by eeve** [iview/iview#700]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
all

### Vue 版本号
2.2.1

#### template
```html
<div id="app"></div>
```

#### script
```vue
var App = new Vue({
  template: `
    <Form v-model="form" :rules="rule">
      <Form-item label="输入框1" prop="a">
        <Input v-model="form.a" />
      </Form-item>
    </Form>
  `,
  data: function() {
    return {
      form: {
        a: "",
        b: {
          c: "" // 需要校验此属性
        }
      },
      rule: {
        a: {
          required: true,
          trigger: 'blur'
        }
      }
    }
  }
});
App.$mount('#app');
```

https://codepen.io/eeve/pen/QMGpLB

### 问题现象，以及你期望的结果是怎样的?

如何校验一个对象的深度属性，我看 async-validator 的文档写了相关的东西
https://github.com/yiminghe/async-validator#deep-rules

### 你估计可能的原因是什么（选填）？
貌似iview不支持？还是我用法不对，请指教！

# 新的补充：

感谢 @tangj1206 
新的例子：
https://codepen.io/eeve/pen/zdoNVV

**Comment by ozeebee** [comment]
+1

**Comment by Tilang** [comment]
同样的问题。如果提交type:object的深度属性验证，对象里所有的错误提示又都会在所有formItem上都触发。

**Comment by tangj1206** [comment]
同样的问题 亟待解决！！！！！！

**Comment by tangj1206** [comment]
这个问题在一位大神的指导下解决了：
解决办法：
‘a.c’:[{ required: true, message: '不能为空', trigger: 'blur' }]
前面属性有多少层就点多少层（记得加上引号 之前我就是没加引号 语法报错）
