### ISSUE TITLE
Table 增加Loading 状态

### ISSUE THREAD

**Issue by 68387097** [iview/iview#704]
### iView 版本号

2.0.0-rc.10 
### 操作系统/浏览器 版本号

Chrome 56
### Vue 版本号

2.2.1
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

能否Table 增加Loading 状态 类似ant design的Table

**Comment by lvqingan** [comment]
#296

**Comment by focus0802** [comment]
尝试把Spin加在一个父容器里面是可以用的，不过这个就类似于页面级的加载，并不是期望的Table表格数量加载，期望可以补上这个功能😊

**Comment by shenopkss** [comment]
+1

**Comment by hh-in-zhuzhou** [comment]
迫切希望这个啊，像element UI一样，每次写到table的加载动画，就是个梗啊，比较而言，elementUI在table组件上这一点太方便了

**Comment by sadenwang** [comment]
是的，现在loading的时候不友好，速度快的时候一闪而过像刷了页面一样

**Comment by icarusion** [comment]
300bd66
