### ISSUE TITLE
table增加取消选择单行事件，知道取消了哪一行数据

### ISSUE THREAD

**Issue by liaostr** [iview/iview#705]
### 问题现象，以及你期望的结果是怎样的?
table组件提供了选择事件：on-select   可以知道选中哪行数据
但是取消选择只有on-selection-change事件，不知道取消的是哪一行数据
希望能提供取消选择事件，知道取消了哪行数据

### 你估计可能的原因是什么（选填）？
toggleSelect (_index) {
        let data = {}

        for (let i in this.objData) {
          if (parseInt(i) === _index) {
            data = this.objData[i]
          }
        }
        const status = !data._isChecked

        this.objData[_index]._isChecked = status

        const selection = this.getSelection()
        if (status) {
          this.$emit('on-select', selection, JSON.parse(JSON.stringify(this.data[_index])))
        }
        this.$emit('on-selection-change', selection)
      },

**Comment by p2ng** [comment]
@on-selection-change
在多选模式下有效，只要选中项发生变化时就会触发	
selection：已选项数据

这个事件不能跟`@on-select`一样，提供一个`row：刚选择的项数据`参数吗!?
不然我怎么知道我change是哪一行记录!?

**Comment by Hishengs** [comment]
同求，这个功能很有必要

**Comment by areyouse7en** [comment]
很有必要

**Comment by ttflowerboys** [comment]
有必要

**Comment by ttflowerboys** [comment]
必要

**Comment by ttflowerboys** [comment]
要

**Comment by icarusion** [comment]
https://github.com/iview/iview/pull/1314

**Comment by zxzxzxygithub** [comment]
select cancel貌似没有效果，是不是要升级iview才行？

**Comment by ichabodphp** [comment]
有没有一个什么属性或者方法 取消全部已选中的项？

**Comment by qinghua5453** [comment]
on-select-cancel 无效，我升级到^2.14.0 版本了

**Comment by qinghua5453** [comment]
on-selection-change 只有用这个模拟了
