### ISSUE TITLE
Release rc.10 - 关于 Modal - DOMException: Failed to execute 'insertBefore' on 'Node'. 

### ISSUE THREAD

**Issue by fluency03** [iview/iview#707]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Electron

### Vue 版本号
2.2.6

### 示例

```javascript
<template>
  <div>
    <div class="docker-hub-panel">
      <search-panel v-model="searchedImages"></search-panel>
      <login-panel v-model="token"></login-panel>
    </div>
    <br><br>
    <Card v-for="image in searchedImages" class="image-card">
      <!-- ... -->
    </Card>
    <Modal v-model="pullProcessModal" title="Pull Image" @on-cancel="pullProcess = ''">
      <pre class="logs">{{pullProcess}}</pre>
    </Modal>
  </div>
</template>
```

### 问题现象，以及你期望的结果是怎样的?

我把iview更新到rc10之后出现此问题，downgrade 到 rc7后不再有此问题。

在rc10版本下，移除代码里的 Modal 或者把 Modal 移到 Card v-for 内部不再有此问题。 可是这样会给每一个 Card 里面都添加一个 Modal，速度会变慢。

不想把 Modal 放到 Card 里，求解决办法。

### 你估计可能的原因是什么（选填）？

我认为的原因是：在 release rc10中：*Modal 的 DOM 移动到了 body。* 操作不当造成。

**Comment by icarusion** [comment]
提供在线示例
