### ISSUE TITLE
select 当开启 filterable，且有默认值时，第一次不正常

### ISSUE THREAD

**Issue by Running563** [iview/iview#712]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

Chrome 
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/jmbMeQ
### 复现步骤
刷新页面，第一次点击时，不正确，再次点击，则正常。
### 问题现象，以及你期望的结果是怎样的?
select 组件 ，filterable = true,
当select有默认值时，第一次点击select中内容，如图一，只有all选项。 再次点击，才正常，如图二
![image](https://cloud.githubusercontent.com/assets/21331124/25114415/28d23f96-2431-11e7-9076-8422cdfecd9a.png)
![image](https://cloud.githubusercontent.com/assets/21331124/25114421/3804c18c-2431-11e7-836c-584c7b508019.png)

**Comment by starding** [comment]
+1

**Comment by BlueGene89** [comment]
类似的问题，未开启filterable，我的情况是：当模态窗口打开，让select的 v-modal=“data1” 开始选择一项，在模态窗口关闭时将data1=“” 再次打开，发现select仍旧会选择上次窗口打开的那一项，尽管此时窗口打开时data1为“”，应该与模态窗口无关

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/83b73885988cf62e29457e4161f4553712395c67

**Comment by QianWenW** [comment]
+1
