### ISSUE TITLE
filterMethod方法支持远程过滤

### ISSUE THREAD

**Issue by excellnn** [iview/iview#714]
### iView 版本号
2.0.0-rc.10 

### 操作系统/浏览器 版本号
ubuntu / chrome  54.0.2840.100 (64-bit)

### Vue 版本号
^2.2.2
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
无
### 复现步骤
无
### 问题现象，以及你期望的结果是怎样的?
目前table列的filterMethod方法不支持远程过滤．希望可以支持远程过滤

**Comment by icarusion** [comment]
#605
