### ISSUE TITLE
table添加render方法，render里面的组件显示未注册，这是怎么回事

### ISSUE THREAD

**Issue by wqzwh** [iview/iview#716]
iView 版本号

2.0.0-rc.9

操作系统/浏览器 版本号

ubuntu / chrome 54.0.2840.100 (64-bit)

Vue 版本号

2.2.2

控制台报：Unknown custom element: <icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)

`

export default {
    components: {
        Table,
        Icon
    },
    data() {
        return {
            self: this,
            columns7: [{
                title: '姓名',
                key: 'name',
                render(row, column, index) {
                    return `<Icon type="person"></Icon> <strong>${row.name}</strong>`;
                }
            }, {
                title: '年龄',
                key: 'age'
            }, {
                title: '地址',
                key: 'address'
            }, {
                title: '操作',
                key: 'action',
                width: 150,
                align: 'center',
                // render (row, column, index) {
                //     return `<i-button type="primary" size="small" @click="show(${index})">查看</i-button> <i-button type="error" size="small" @click="remove(${index})">删除</i-button>`;
                // }
            }],
            data6: [{
                name: '王小明',
                age: 18,
                address: '北京市朝阳区芍药居'
            }, {
                name: '张小刚',
                age: 25,
                address: '北京市海淀区西二旗'
            }, {
                name: '李小红',
                age: 30,
                address: '上海市浦东新区世纪大道'
            }, {
                name: '周小伟',
                age: 26,
                address: '深圳市南山区深南大道'
            }]
        }
    },
    methods: {
        show(index) {
            this.$Modal.info({
                title: '用户信息',
                content: `姓名：${this.data6[index].name}<br>年龄：${this.data6[index].age}<br>地址：${this.data6[index].address}`
            })
        },
        remove(index) {
            this.data6.splice(index, 1);
        }
    }
}

`

**Comment by yajore** [comment]
render里面返回的是string类型
`<Icon type="person"></Icon> <strong>${row.name}</strong>`

**Comment by ai116458960** [comment]
可能是vue版本太低 我是升级到2.2.6就好了

**Comment by wqzwh** [comment]
已经解决了，在全局注册组件就行

**Comment by Daisny** [comment]
@wqzwh 兄弟咋解决的？在vue实例的components注册？

**Comment by lcx960324** [comment]
在 Table 中遇到组件未注册的问题，请先尝试使用 Table 的 context 属性为其绑定组件作用域。
详见 [Issue 739](https://github.com/iview/iview/issues/739#issuecomment-296525292)

**Comment by icarusion** [comment]
Please update to the latest version
