### ISSUE TITLE
数据较多时，Select组件存在性能问题

### ISSUE THREAD

**Issue by starding** [iview/iview#719]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 57

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

因为单个Select不是很明显，这里多加了几个
https://codepen.io/metaphor/pen/PmZYay

### 复现步骤

如演示

### 问题现象，以及你期望的结果是怎样的?

当渲染几个带有很多Option的Select时，整个页面会卡死。

### 你估计可能的原因是什么（选填）？

Select的设计没太考虑性能问题？我现在只能把Select抽出来成单独的一个组件，类似于单例那样，但仅渲染一个Select其实都略有卡顿。

**Comment by icarusion** [comment]
#687

**Comment by starding** [comment]
囧，忽略我

我的上层代码写的有问题，实测200+数据还是非常ok的
