### ISSUE TITLE
Table 组件自适应

### ISSUE THREAD

**Issue by CarmenHYC** [iview/iview#720]
Table 组件能不能像 Element 那样响应式自适应宽度，溢出可以左右滑动而不是全挤到一起

**Comment by onlinelemon** [comment]
@icarusion 挨个看了一下，Table 组件自适应问题你关闭很多issues，请问解决方案是什么？

**Comment by liekkas** [comment]
@icarusion 同问，目前版本 ^2.0.0-rc.16 还未解决
