### ISSUE TITLE
iview下拉菜单点击出现不能读取属性$parent错误

### ISSUE THREAD

**Issue by lifei6671** [iview/iview#721]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号

Windows10 x64 Chrome  57.0.2987.110 (64-bit)

### Vue 版本号

2.1.6

### 能够复现问题的在线示例

[http://runjs.cn/detail/iirkubcw](http://runjs.cn/detail/iirkubcw)

### 复现步骤

点击下拉菜单提示错误
```
iview.min.js:1 Uncaught TypeError: Cannot read property '$parent' of undefined
```
### 问题现象，以及你期望的结果是怎样的?

正常应该是关闭。

**Comment by 79229788** [comment]
我也遇到了～～～～～～～
发现最外层的dropdown源码中this.$parent.$parent.$parent;已经是最外层却在继续查找，所以肯定报错

**Comment by 79229788** [comment]
我也遇到了～～～～～～～～～～～
