### ISSUE TITLE
Hello，我在使用的过程中发现在Modal中使用Carousel会发生.ivu-carousel-item这个div没有宽度的问题，thx

### ISSUE THREAD

**Issue by AlvinYiDa** [iview/iview#722]

**Comment by lcx960324** [comment]
可以用 jsbin / jsfiddle 提供一下 sample code 吗 谢谢

**Comment by ai116458960** [comment]
我也出现这样的情况了 不知道怎么解决的 求大神帮帮忙

**Comment by CallMEJun** [comment]
@lcx960324 https://jsfiddle.net/xmjr5j1z/

**Comment by lcx960324** [comment]
@CallMEJun 
您提供的示例代码不完整。
不过，您可以尝试将 Modal 的 v-model 同时绑定在 Carousel 的 v-if 属性上，让他们两个一同渲染。

**Comment by CallMEJun** [comment]
@lcx960324 Sorry,之前编辑完忘记保存了，https://jsfiddle.net/xmjr5j1z/4/  这个可以了，而且我发现是非webpack模式下使用Carousel  不管在哪都会没有高度

**Comment by lcx960324** [comment]
@CallMEJun 
您提供的代码中，`.demo-carousel` 并没有给出明确的高度，所以按照 CSS 的规则，高度会与 div 内部的元素自适应，也就是说高度跟您书写在里边的文字是一致的。组件工作是正常的，请您按照自己的需求修改一下 CSS，也可以通过 Carousel 的 height 属性指定高度。
之所以您会感觉没高度，是因为 Carousel 的指示器和切换器是直接浮动在内容之上的，详见 iview 文档示例。

**Comment by Wj0622** [comment]
我认为是，在你弹窗出来之前，他的高度已经计算完毕，所以他的宽为0，所以在弹窗出来后，你在重新调用一下他的方法，重新计算一下宽
![image](https://user-images.githubusercontent.com/22017915/32306888-6a04a9cc-bfb8-11e7-97af-5f45ab29e9a5.png)

**Comment by hexb0307** [comment]
https://jsfiddle.net/xiaoxuexue/xmjr5j1z/8/
首次加载无法显示carousel-item里面的内容，这个问题怎么解决呢，如上面我略作调整的这个例子。

**Comment by hexb0307** [comment]
@icarusion 您好，我最近使用组件发现跑马灯组件首次没法加载出来内容是由于class="ivu-carousel-track higher"宽度为0的原因，这样的问题我怎么解决呢？thx

**Comment by buildJava** [comment]
![image](https://user-images.githubusercontent.com/18717339/35609282-ae5fb53c-0697-11e8-99f6-3f5cb85bdf09.png)
只需要让这gm两个一起渲染就OK了，加上v-if就行

**Comment by zhouchao941105** [comment]
在Carousel上加了个v-if=“list.length”就正常工作了。这个问题也太隐晦了吧？
没搞明白加这个行内样式的意义是什么
![_20181129150958](https://user-images.githubusercontent.com/13476994/49205084-e1241280-f3e8-11e8-9c25-151bcf507ea0.png)

**Comment by chenbimo** [comment]
这个组件有点坑。
