### ISSUE TITLE
在router 的beforeEach中添加LoadingBar不能正常工作

### ISSUE THREAD

**Issue by moodmass** [iview/iview#725]
代码如下
`router.beforeEach((to, from, next) => {
  iView.LoadingBar.start();
  next();
});` 
浏览器控制台报以下错误且项目不能正常运行：
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by icarusion** [comment]
暂不支持runtime
