### ISSUE TITLE
Select组件的建议

### ISSUE THREAD

**Issue by xiaoyyang123** [iview/iview#726]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/xiaoyyang/pen/LyGqVG

### 问题现象，以及你期望的结果是怎样的?
`Select`组件，同时加上`filterable` 和`disabled` 时，`input`框仍然可以输入内容，期望的结果是既不能选择也不能输入

**Comment by lcx960324** [comment]
您可以将被 disabled 的 select 组件的 fliterable 属性设置为 false 来实现。
```
<i-select v-model="id" :filterable="false" :disabled="true">
```
