### ISSUE TITLE
能不能把官网https://www.iviewui.com/ 的源码贴出来

### ISSUE THREAD

**Issue by shengbowen** [iview/iview#73]
想看看，这样单页网站（网址变化的时候，html文件却没有变化）是怎么划分和架设的，我目前纠结于vue只试用于单页应用，但是旧项目有多个网页，不知道用vue如何实现，总不能每个页面起一个vue工作流吧。

**Comment by icarusion** [comment]
https://www.iviewui.com/docs/guide/start#开发模式
