### ISSUE TITLE
tabs的高度能否根据每个tab的高度随着切换重新计算

### ISSUE THREAD

**Issue by chenxiaoqi01** [iview/iview#731]
把tabs放在模态框中显示，可tabs的高度会根据其中tab的最大高度渲染显示。

类似element组件的tabs

**Comment by magixyu** [comment]
same question,:)

**Comment by livesitter** [comment]
2019.03.29 报道
经过2年的时间，依旧没有解决这个问题。。。

**Comment by YoungHF** [comment]
把tabs切换的动画关闭就可以了

**Comment by Xdy1579883916** [comment]
> 把tabs切换的动画关闭就可以了

泪牛满面，流下了感动的泪水，这方法好用

**Comment by chutianjun** [comment]
2022.5.22 ,同样的问题

**Comment by ailaiwuyou** [comment]
关闭动画真好用
