### ISSUE TITLE
table组件的宽度问题还是没有修复啊

### ISSUE THREAD

**Issue by dryqiao** [iview/iview#732]
1、布局直接用的组件里“可收起展开的侧边导航“，侧边导航收起后，右边表格宽度并没有自适应，表格右边会出现一段空白。
2、浏览器宽度缩小时，表格没有自适应，页面会出现横向滚动条，
但是宽度变大时，会自适应

更新日志显示修改了 #591，但是并没有用啊，希望能检查下，谢谢。

**Comment by qq447665722** [comment]
发现同样问题
