### ISSUE TITLE
Transfer 穿梭框动态赋值之后页面没有变化

### ISSUE THREAD

**Issue by tanxuxu** [iview/iview#733]
这个组件在使用中出现了问题，我觉得应该是组件的问题，请看下面的代码。
这样是能改变到数组的值，但是穿梭框没有做出相应的反应，求解，纠结了很久了，是不是因为我没用用集成环境的缘故
`<html>
	<head>
		<title></title>
		<meta charset="UTF-8">
		<script src="http://v1.vuejs.org/js/vue.min.js"></script>
		
		<link rel="stylesheet" href="http://unpkg.com/iview/dist/styles/iview.css">
		
		<script src="http://unpkg.com/iview@1.0.1/dist/iview.min.js"></script>
	</head>
	<body>
		<i-button @click="aa">Default</i-button>
		 <Transfer
        :data="datas"
        :target-keys="targetKeys"
        :render-format="render"
        @on-change="onChange"></Transfer>
    <script>
    	new Vue({
    		el:'body',
            data:function(){
            	return {
            		datas: [
		                { "key": "1", "label": "内容1", "disabled": false },
		                { "key": "2", "label": "内容2", "disabled": true },
		                { "key": "3", "label": "内容3", "disabled": false }
			          ],
			        targetKeys: [] 
            	}
            },
		    methods: {
		        render: function(item) {
		            return item.label;
		        },
		        aa:function(){
		        	this.datas =  [
		                { "key": "1", "label": "内容1", "disabled": false },
		                { "key": "2", "label": "内容2", "disabled": true },
		                { "key": "3", "label": "内容3", "disabled": false }
			          ];
		        },
		        onChange:function (newTargetKeys) {
		            this.targetKeys = newTargetKeys;
		        }
		    }
    	})
    </script>    
	</body>
</html>`

**Comment by icarusion** [comment]
按要求提问
