### ISSUE TITLE
Upload组件 赋值default-file-list绑定的data时异常

### ISSUE THREAD

**Issue by ai116458960** [iview/iview#734]
Upload组件 在方法里面设置default-file-list绑定的data时 会有异常。
异常1：无法显示默认图片
异常2：会导致上传组件失效

**Comment by lavenkin** [comment]
我也遇到这样的问题

**Comment by DevilTears** [comment]
挣扎哦，默认图片显示不了的原因到底是啥

**Comment by Thlq** [comment]
setTimeout(()=> {
                this.defaultList = this.picGet; //将获取到的值赋值到 defaultList 中
                this.$nextTick(()=> { //赋值后马上更新
                    this.uploadList = this.$refs.upload.fileList;
                });
            },1000);

**Comment by Thlq** [comment]
setTimeout(()=> {
                this.defaultList = this.picDefaulList; //将获取到的值赋值到 defaultList 中
                this.$nextTick(()=> { //赋值后马上更新
                    this.uploadList = this.$refs.upload.fileList;
                });
 },1000);
