### ISSUE TITLE
Transfer 穿梭框动态赋值之后，页面没有反应

### ISSUE THREAD

**Issue by tanxuxu** [iview/iview#735]
### iView 版本号
 1.0

### 操作系统/浏览器 版本号
Chrome 56

### Vue 版本号
1.0.28

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/vrg9fqxc/1/
### 复现步骤
点击按钮
### 问题现象，以及你期望的结果是怎样的?
点击按钮，应该页面有反应，赋值上去了
`<html>
	<head>
		<title></title>
		<meta charset="UTF-8">
		<script src="http://v1.vuejs.org/js/vue.min.js"></script>
		
		<link rel="stylesheet" href="http://unpkg.com/iview/dist/styles/iview.css">
		
		<script src="http://unpkg.com/iview@1.0.1/dist/iview.min.js"></script>
	</head>
	<body>
		<i-button @click="aa">Default</i-button>
		 <Transfer
        :data="datas"
        :target-keys="targetKeys"
        :render-format="render"
        @on-change="onChange"></Transfer>
    <script>
    	new Vue({
    		el:'body',
            data:function(){
            	return {
            		datas: [
		                { "key": "1", "label": "内容1", "disabled": false },
		                { "key": "2", "label": "内容2", "disabled": true },
		                { "key": "3", "label": "内容3", "disabled": false }
			          ],
			        targetKeys: [] 
            	}
            },
		    methods: {
		        render: function(item) {
		            return item.label;
		        },
		        aa:function(){
		        	this.datas =  [
		                { "key": "1", "label": "内容1", "disabled": false },
		                { "key": "2", "label": "内容2", "disabled": true },
		                { "key": "3", "label": "内容3", "disabled": false }
			          ];
		        },
		        onChange:function (newTargetKeys) {
		            this.targetKeys = newTargetKeys;
		        }
		    }
    	})
    </script>    
	</body>
</html>`
### 你估计可能的原因是什么（选填）？

是不是不支持这样的写法了，一定要用集成环境，webpack吗

**Comment by hezhengjie** [comment]
我也遇到了这样的问题，Transfer的data和Upload的default-file-list的动态绑定的变量变化之后，没有触发组件的重新渲染。。

**Comment by hezhengjie** [comment]
看代码，之前的版本没有watch data，最新版2.0.0-rc.11，好像修复了这个问题

**Comment by icarusion** [comment]
1.0 不再维护。
