### ISSUE TITLE
关于 Date-picker v-model 输入时间为 UTC 时间问题

### ISSUE THREAD

**Issue by WalterZou** [iview/iview#738]
### 复现步骤
```
<Date-picker type="datetime" @on-change="changeDate" v-model="time" :options="dateOptions" placeholder="选择日期"></Date-picker>

...

changeDate (val) {
  console.log(this.time, val)
}
// 结果为 `2017-04-19T16:00:00.000Z,2017-04-20 00:00:00`
```
结果一个是: v-model 输出UTC 时间，on-change 时间输出为 本地时间
### 问题现象，以及你期望的结果是怎样的?
为什么 v-model 不输出 本地时间，这个在实际业务上更适用

**Comment by lvqingan** [comment]
这块我也觉得有点麻烦，可能是作者更想做得标准化一点，所以v-model绑定的是一个Date对象，让用户自己来决定如何处理日期

我的解决方案是，如果想处理过以后再提交给服务器，可以
```javascript
import dateUtil from 'iview/src/utils/date'
```
然后调用
```javascript
dateUtil.format(this.time, 'yyyy-MM-dd'),
```
或者干脆把时间提交给服务器来处理，譬如PHP的strtotime

**Comment by WalterZou** [comment]
@lvqingan 嗯，这样也是可以的。不过我现在就直接用on-change事件来处理了，还是麻烦一点。如果想要标准化和本地化兼容，建议增加可配置项。

**Comment by icarusion** [comment]
已知需求，后面会做优化

**Comment by justnowanna** [comment]
@icarusion 您好，请问这个什么时候会优化呢？我看了源码里面在`on-change`的时候是做了`format`的，但是在`value`的时候没有做。或者我想知道如何更改源码才能生效，因为现在遇到一个问题，页面里面有8个`Date-picker`，使用`on-change`的话，是不知道当前是改变了哪一个`Date-picker`的，如果去`watch`，就会进入一个死循环，监听到日期变了，再`format`一下日期，又会触发监听，很尴尬的一个局面。希望如果近期不会改的话，我想知道怎么更改源码或者有其他的解决办法吗？我现在更改源码都不会生效。

望答复，谢谢，就不提Issue了。

**Comment by justnowanna** [comment]
@yinheli @lvqingan 能看看吗？

**Comment by lvqingan** [comment]
@justnowanna

![image](https://cloud.githubusercontent.com/assets/2076441/26230938/07b0f33c-3c7f-11e7-9519-f8b56765b030.png)

**Comment by justnowanna** [comment]
@lvqingan 谢谢，可以解决。

**Comment by max-boy** [comment]
我也遇到这个问题，你们如何解决的

**Comment by tyf914** [comment]
目前我的解决办法是：
- 绑定`value`（date对象），使用`on-change`，`on-change`的方法定义时给个形参（比如`date`），方法把这个形参赋给`value`绑定的值。
- 如果有多个`DatePicker`组件，定义一个`key`值，使用`on-open-change`事件改变`key`值，再在`on-change`里赋值给`key`值对应的当前`DatePicker`组件
