### ISSUE TITLE
table表格里面使用render渲染下拉菜单Dropdown，点击下拉菜单的选项时控制台报错‘property '$parent' of undefined’

### ISSUE THREAD

**Issue by swordlight** [iview/iview#739]
### iView 版本号

2.0.0
### 操作系统/浏览器 版本号

windows/chrome
### Vue 版本号

2.0
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/Aresn/pen/BWwVoy
### 复现步骤
render:(row,column,index)=>{
           return `<Dropdown trigger="click">
                                 <Button style="background-color:#39f;color:white;border:none;width:50px;height:30px;border-radius:5px;cursor:pointer;outline:none;">
                                            操作
                                  </Button>
                                   <Dropdown-menu slot="list">
                                            <Dropdown-item @click="editUser(${index})">编辑</Dropdown-item>
                                            <Dropdown-item @click="lockUser(${index})">锁定</Dropdown-item>
                                            <Dropdown-item @click="deleteUser(${index})">删除</Dropdown-item>
                                            <Dropdown-item @click="resetUserPwd(${index})">重置密码</Dropdown-item>
                                   </Dropdown-menu>
                       </Dropdown>`
 }
table表格里面使用render渲染下拉菜单Dropdown，点击下拉菜单的选项时控制台报错‘Uncaught TypeError: Cannot read property '$parent' of undefined’
### 问题现象，以及你期望的结果是怎样的?
是不是有table属性‘context’的关系

**Comment by lcx960324** [comment]
click 事件绑定的 function 如果是当前组件的 function 的话，在使用 Table 时，请使用 context 属性传递当前作用域。
一个可能的实现：
```
<template>
...
<Table :context="self"></Table>
</template>
<script>
export default {
 ...
 data () {
    self: this
}
</script>
```

**Comment by itrenhang** [comment]
我也遇到了同样的问题，加了上下文 还是不好使，报同样的错误

**Comment by itrenhang** [comment]
![image](https://cloud.githubusercontent.com/assets/17876062/25322981/5aae68c0-28ee-11e7-9ac3-d181c57f8379.png)
![image](https://cloud.githubusercontent.com/assets/17876062/25322992/71971b0e-28ee-11e7-80ca-2dc28a81bdd2.png)

**Comment by lcx960324** [comment]
感觉可能是绑定错了上下文，请提供详细一点的代码 @itrenhang

**Comment by kakanjau** [comment]
遇到同样的问题，
模板是这样定义的： 
`<Table stripe :columns='tableHeader' :data='tableData' :context='self' width='100%'></Table>`

script中的 data：
````
data () {
  return {
    self: this,
    page: {
      total: 0,
      size: 20,
      number: 0
    },
    tableHeader: [
      {
        title: '序号',
        width: 100,
        render: (row, col, index) => {
          return index + this.page.size * this.page.number
        }
      }
    ]
  }
}
````

但是在浏览器中调试的时候，看到的this还是当前单元格的

**Comment by lcx960324** [comment]
@kakanjau 
因为箭头函数直接绑定了函数作用域为函数所在的 Object 。
请使用 binding 语法手动指定函数作用域：
```
render: function (row, col, index) {
}.bind(this)
```

**Comment by lcx960324** [comment]
@kakanjau 
抱歉之前给出了错误的答复。
我重新进行了 this 的测定，发现并不会出现 this 绑定错误的情况。所以在使用 arrow function 的时候这段代码应该是可以正常工作的。

**Comment by voskresla** [comment]
i try to run IVIEWUI Table component in a simple (i-table tag) mode like this https://jsfiddle.net/zc2jrowv/9/

But i loose 'context' in render function. how can i save 'this' or give 'i-table' my own methods ?
