### ISSUE TITLE
面包屑的数据动态设置就不会出现分隔符了

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#740]
### 你估计可能的原因是什么（选填）？

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="http://unpkg.com/iview/dist/styles/iview.css">
    <script type="text/javascript" src="http://vuejs.org/js/vue.min.js"></script>
    <script type="text/javascript" src="http://unpkg.com/iview/dist/iview.min.js"></script>
</head>
<body>
    <div id="app">
        <Breadcrumb separator=">">
            <Breadcrumb-item v-for="b in breadcrumb" v-bind:href="b.href">
                {{b.title}}
            </Breadcrumb-item>
        </Breadcrumb>
        <button @click="cha">rererererere</button>
    </div>
    <script>
        new Vue({
            el: '#app',
            data: {
                breadcrumb: []
            },
            methods: {
                cha() {
                    this.breadcrumb = [
                        {
                            href: '/i',
                            title: '父'
                        },
                        {
                            href: '/i/j',
                            title: '子'
                        },
                        {
                            href: '/i/j/k',
                            title: '孙'
                        },
                        {
                            href: '',
                            title: '叶子'
                        }
                    ];
                }
            }
        })
    </script>
</body>
</html>

**Comment by icarusion** [comment]
#742
