### ISSUE TITLE
iview2.0 中面包屑动态赋值后“/”不显示

### ISSUE THREAD

**Issue by Blackloser** [iview/iview#741]
面包屑动态赋值后“/”不显示

**Comment by lcx960324** [comment]
请按照 issue 提交的格式提交一下相信的 issue 谢谢。

**Comment by Blackloser** [comment]
![Uploading QQ图片20170421142719.png…]()
![Uploading QQ图片20170421142751.png…]()
![Uploading QQ图片20170421142756.png…]()
