### ISSUE TITLE
iview2.0 面包屑动态设置值之后“/”不显示

### ISSUE THREAD

**Issue by Blackloser** [iview/iview#742]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
Windows10/Chrome 56 

### Vue 版本号
 2.2.1 

### 复现步骤

![qq 20170421142719](https://cloud.githubusercontent.com/assets/26319882/25265505/0cdfebbe-26a0-11e7-8054-f36665694bef.png)
![qq 20170421142751](https://cloud.githubusercontent.com/assets/26319882/25265506/0cf3ae74-26a0-11e7-9b0d-310e4fc75df4.png)
![qq 20170421142756](https://cloud.githubusercontent.com/assets/26319882/25265507/0cfad56e-26a0-11e7-85cd-51246c8825c9.png)

 “<Breadcrumb  separator="/">
        <Breadcrumb-item  v-for="(item,index) in fileList" :key="item">{{item.fName}}</Breadcrumb-item>
  </Breadcrumb>“

 fileList:[
          {fName:"首页",myClass:""},
        ],

 show(){
          this.fileList.push(
            {fName:"首页",myClass:""},
            {fName:"sss",myClass:""},
            {fName:"sss",myClass:""},
            {fName:"sss",myClass:""},
            {fName:"sss",myClass:""},
            {fName:"sss",myClass:""},
            {fName:"sss",myClass:""},)
      }

### 问题现象，以及你期望的结果是怎样的?

动态赋值候没有“/” 期待动态赋值和直接给值是一样的

### 你估计可能的原因是什么（选填）？
很有可能是因为动态赋值后组件渲染的问题，控制台可以看见加上了“/”那个span标签  但页面上没有。

**Comment by icarusion** [comment]
已修复，下个版本会更新
