### ISSUE TITLE
#651问题延续

### ISSUE THREAD

**Issue by getlinerm** [iview/iview#749]
问题出现在vue独立组件中发生，所以在线代码演示不出效果;

用#651的方法可以解决按需引用下render函数中Button组件的正常使用，
但是在使用Poptip组件的时候：

![20170421182926](https://cloud.githubusercontent.com/assets/24453916/25273919/7f324b7e-26c0-11e7-947a-bcb93b2f5295.jpg)

hover时会报错如下：

![20170421182631](https://cloud.githubusercontent.com/assets/24453916/25273816/12357d52-26c0-11e7-9075-b847f22a8b68.jpg)

### 问题现象，以及你期望的结果是怎样的?
消除报错

**Comment by getlinerm** [comment]
Tooltip同样有此问题，
其他组件正常。

**Comment by icarusion** [comment]
Update to the latest version.
