### ISSUE TITLE
table中poptip无法关闭，发生重叠现象

### ISSUE THREAD

**Issue by dearhulu** [iview/iview#750]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

win7 64/Chrome  57.0.2987.110 (64-bit)
### Vue 版本号

2.2.6
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://js.jirengu.com/qolom/edit?html,output
### 复现步骤
点击test出现poptip后，点击表格的其它部分，poptip无法关闭。这样多点击几个test后，poptip会重叠在一起。
### 问题现象，以及你期望的结果是怎样的?
希望同一时间只能出现一个poptip

**Comment by icarusion** [comment]
已知问题。
