### ISSUE TITLE
disabled或loading状态的button仍然能弹出poptip

### ISSUE THREAD

**Issue by dearhulu** [iview/iview#752]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

win7 64/Chrome 57.0.2987.110 (64-bit)
### Vue 版本号

2.2.6
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://js.jirengu.com/qolom/edit?html,output
### 复现步骤
点击 删除按钮， 确定后将删除按钮disabled了，但点击按钮的周边，还是会弹出poptip,
同样，点击“国际化”按钮，确认后出现loading状态，也还是能点击出现poptip
### 问题现象，以及你期望的结果是怎样的?
建议给poptip添加一个属性，控制其是否可以弹出，如不弹出，让其内部控件执行自己的点击事件

**Comment by icarusion** [comment]
visible

**Comment by dearhulu** [comment]
@icarusion 
visible是没法控制poptip的弹出
http://js.jirengu.com/qolom/edit?html,output
可点击“删除” 按钮 和 “国际化” 按钮测试

**Comment by lcx960324** [comment]
@dearhulu 因为 click 事件绑定在了 Poptip 上，您在 button 上使用了 margin 导致 poptip 大小大于了 button 的大小。如果需要添加边距，请把 margin 属性添加到 poptip 上试一下，或者包裹外层 div 。

**Comment by dearhulu** [comment]
@lcx960324 第二个按钮怎么处理？如何在loading状态下禁止poptip弹出？

**Comment by lcx960324** [comment]
@dearhulu 
第二个您需要在 button 上手动阻止一下 click 事件冒泡。
在 loading 状态的 button 并不会响应 click 事件 （使用了 CSS3 pointer-events 阻止事件响应）但并不会阻止事件冒泡。
为了防止 Poptip 被触发，需要做一层逻辑判断，在 button 上先覆写 CSS 去掉 pointer-events 属性，然后使用 `@click.native` 捕获 Button 的 click 事件，如果 loading 为 true 则阻止事件冒泡。

**Comment by dearhulu** [comment]
@lcx960324 
最好能参考
https://ant.design/components/popconfirm-cn/
用condition判断

**Comment by shishir99111** [comment]
am i the only one here converting chinese texts in Google translate for understanding.
