### ISSUE TITLE
table中的selection列，_disabled默认全部为 true时，全选按钮会被勾选

### ISSUE THREAD

**Issue by dearhulu** [iview/iview#753]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

win7 64/Chrome 57.0.2987.110 (64-bit)
### Vue 版本号

2.2.6
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://js.jirengu.com/qolom/edit?html,output
### 问题现象，以及你期望的结果是怎样的?
另外#752 设置visible无效

**Comment by icarusion** [comment]
@hezhiying 有空的话帮忙看看这个额issue

**Comment by suyuTech** [comment]
我也遇到了这个问题、初步判断在一下代码
可能原因：每行disabed
isSelectAll: function isSelectAll() {
            var isSelectAll = true;
            if (!this.data.length) isSelectAll = false;
            for (var i = 0; i < this.data.length; i++) {
                if (!this.objData[this.data[i]._index]._isChecked && !this.objData[this.data[i]._index]._isDisabled) {
                    isSelectAll = false;
                    break;
                }
            }

            return isSelectAll;
        }

**Comment by hezhiying** [comment]
@icarusion 这个可能是其它人写的帮忙看看

**Comment by MerlinFeng** [comment]
请教下 selection 清空有方法没

**Comment by icarusion** [comment]
Update to the latest version.
