### ISSUE TITLE
select动态绑定options 无法通过表单验证

### ISSUE THREAD

**Issue by dearhulu** [iview/iview#761]
### 操作系统/浏览器 版本号

win7 64/Chrome 57.0.2987.110 (64-bit)
### Vue 版本号

2.2.6
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://js.jirengu.com/xunan/1/edit?html,output
### 问题现象，以及你期望的结果是怎样的?
select选择后，也无法通过表单验证

**Comment by lvqingan** [comment]
我也遇到了这个问题，跟iview没关系，是`async-validator`那边的限制，验证规则里给id加上个`type:'number'`就好了

```javascript
id: [
    { type: 'number', required: true, message: '请选择城市', trigger: 'change' }
]
```

**Comment by justnowanna** [comment]
@lvqingan 
您好，按照你说的加了number也不对呢，帮忙看下呢。
https://jsfiddle.net/galence/mo41cL4d/1/

**Comment by justnowanna** [comment]
@lvqingan 我已经把能精简的都精简了，还是没看出来到底哪里写的不对。。。
https://jsfiddle.net/galence/mo41cL4d/4/

**Comment by justnowanna** [comment]
@lvqingan 研究出来了，谢谢。给后面的人说下，`prop`的值必须跟`v-model`绑定的值一致才行。不好意思，搞了半天。

**Comment by MontageD** [comment]
@lvqingan 大哥你这个办法才是对的，如果prop 跟 v-model绑定值的key不一样就没有效果了
