### ISSUE TITLE
menuitem无法选中的问题

### ISSUE THREAD

**Issue by hojit** [iview/iview#763]
问题的代码
## 代码<Menu :active-name="setActive" theme="dark" width="auto" @on-select="goRoute">
          <Menu-item name="/">首页</Menu-item>
          <Submenu name="1">
                      <template slot="title">
                             <Icon type="ios-navigate"></Icon>
                            平台数据分析
                     </template>
                      <Menu-item name="chart" :index="'/chart/line'">图表展示</Menu-item>
                    <Menu-item name="1-2">数据溢出</Menu-item>
                   <Menu-item name="1-3">导入到处</Menu-item>
         </Submenu>
</Menu>

- 点击submenu里面的menuitem菜单之后，再点击submenu外的首页菜单时，选中状态的样式不激活，必须点击两下才能激活。

**Comment by DebugIsFalse** [comment]
最好能提供在线演示地址
比如这种demo地址  https://github.com/iview/iview/issues/768
