### ISSUE TITLE
Notice 通知里面的内容加事件问题

### ISSUE THREAD

**Issue by itrenhang** [iview/iview#765]
notice 组件现在不支持在内容中加事件，而在使用中，会遇到在description中添加事件的操作，

notice是在全局上创建DOM节点，现在临时解决办法是在全局上写事件，

希望能加上类似 render的函数，来处理事件问题

**Comment by icarusion** [comment]
Notice 的设计是消息通知，有复杂交互应当使用 Modal 等组件。
