### ISSUE TITLE
[DataPicker日期选择器]关于@on-change事件机制

### ISSUE THREAD

**Issue by p2ng** [iview/iview#766]
### iView 版本号
2.0.0-rc.10

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/fsliangzp/pen/gWwaOX

### 复现步骤
业务背景：
选择日期时间。重新调用findProductRelease()后端加载列表数据
1. 选择日期范围(多次操作，观看debugger以及控制台输出)

### 问题现象，以及你期望的结果是怎样的?
1. 从控制台可以看出，`首次的时候获取不到数据（日期时间）`
2. 从第二次选择日期的时候。。。findProductRelease方法内获取的是`上一次选择的数据（日期时间）`

### 你估计可能的原因是什么（选填）？
on-change事件较慢？，导致获取的data数据存在异常？

**Comment by lcx960324** [comment]
建议使用 on-change 时间的事件参数完成该需求。
```
    findProductRelease (date) {
      debugger
      console.log(date[0])
      console.log(date[1])
    }
```

**Comment by p2ng** [comment]
@lcx960324 
`建议使用 on-change 时间的事件参数完成该需求。`
你这个也算是解决方案，
但是`findProductRelease()` 方法是公共的查询入口。查询条件不通过入参来定义的，内部统一取data里面查询form数据来实现。
```
findProductRelease () {
    let param = {}
    param.name = this.form.name // 参数一
    param.age = this.form.age // 参数二
    ...

   do ajax ...
}
```

谢谢回答!~
