### ISSUE TITLE
关于能否提供独立的cvs和excel数据文件导出控件

### ISSUE THREAD

**Issue by BlueGene89** [iview/iview#769]
现在在table有一个导出功能，但是当使用分页api的时候，导出全部的数据就不那么方便了，比如getData(page,rows)这样的api，取得都是当页的，导出的也是当页的。
因此，希望能提供独立的空间，设置导出表格的colums内容和data内容，以及对应的格式，不要仅和table进行强关联
谢谢！

**Comment by icarusion** [comment]
可以自定义导出数据
