### ISSUE TITLE
table组件在Safari下错位

### ISSUE THREAD

**Issue by ihuguowei** [iview/iview#770]
### iView 版本号
2.0.0-rc.10 

### 操作系统/浏览器 版本号
 macOS/Safari 10.1 

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
`table`组件在Safari下错位
https://debug.talkingdata.com/spa/sdk/#/config

![image](https://cloud.githubusercontent.com/assets/3097742/25332149/0ee06bda-2918-11e7-919b-3768be1a0a3d.png)

### 复现步骤
无

**Comment by icarusion** [comment]
https://www.iviewui.com/components/table#多选
文档中并没有错位，最好给出复现示例代码

**Comment by liusome** [comment]
是v-if导致的 @ihuguowei

**Comment by bluest-hu** [comment]
@liusome 离职好久了，已经不记得当初用了什么了～～
