### ISSUE TITLE
Table 数据超过100行6列开始卡，最佳行数列数，是否需要提供smart版table

### ISSUE THREAD

**Issue by shaode** [iview/iview#772]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

Window/Chrome 57
### Vue 版本号

2.2.1
### 复现步骤
table 10列以上50行以上
### 问题现象，以及你期望的结果是怎样的?
提供一个简洁版，零事件或者自定义模板绑定事件，不是自身太多事件
### 你估计可能的原因是什么（选填）？
每行每个单元绑定事件太多导致的

**Comment by stjava** [comment]
是的，我也碰到了这个问题，30行数据，20多列，浏览器卡的动不了，当前页面占用内存高达600M

**Comment by shaode** [comment]
@stjava 你是怎么处理，我准备自己写个简单的

**Comment by stjava** [comment]
@shaode  只展示必要数据，详细数据在详情页面展示

**Comment by stjava** [comment]
@shaode  自己实现了一个简单版的，代码比较low但是  固定功能是实现了
https://github.com/stjava/vue-fixed-table

**Comment by Yougoss** [comment]
我是一个200多行的待办事项的table，服务用个队列推送更新的消息添加到table的data列表里，每次更新都要一秒多。而且如果一次十几，二十条数据一起推送的话，要卡半分多钟，table才有变化，领导又要求不做分页。时间是花在渲染dom上面了么？不太懂前端，有没有大神解释一下为什么

**Comment by aaron0713** [comment]
table渲染数据太多就会很卡
你可以试试用div渲染table数据，我测试过50000+数据同时展示不会卡。
div和table的渲染模式不一样。
agGrid 有个vue的组件，样式不算好看，需要自己调整

**Comment by icarusion** [comment]
数据过多，建议分页。
