### ISSUE TITLE
时间选择器中当选择为daterange时无法对所选时间做出限制

### ISSUE THREAD

**Issue by xiuxingdeshandaiwang** [iview/iview#777]
### iView 版本号
1.0.1

### 操作系统/浏览器 版本号
win10企业版/Chrome 56 

### Vue 版本号
1.0.26

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
http://v1.iviewui.com/components/date-picker#options

### 复现步骤
datepicker中当选择type为daterange时，无法使用disabledDate对所选日期进行限制；
比如：截止日期不超过今天；时间跨度不超过一个月。

### 问题现象，以及你期望的结果是怎样的?
期望作者能够解决这个问题，表示十分感谢

**Comment by icarusion** [comment]
已知问题，但不在对 1.0 维护了。
