### ISSUE TITLE
屏幕宽度较小时，menu导航菜单显示不够友好

### ISSUE THREAD

**Issue by YYQ8023** [iview/iview#779]
### iView 版本号
 2.0.0-rc.11 

### 操作系统/浏览器 版本号
 win10/Chrome 57.0.2987.133

### Vue 版本号
 2.2.6

### 问题现象，以及你期望的结果是怎样的?
![image](https://cloud.githubusercontent.com/assets/22813922/25374959/d4b6c37c-29d1-11e7-946d-85e562caf441.png)

描述：menu导航菜单在屏幕宽度较小时，上下行颜色不一致。如图，上面深色下面白色。
期望：如果屏幕小的时候是分行显示的话，希望颜色可以一致。同时也期望屏幕宽度不够的时候可以变成响应式的，即显示一个按钮,如图（图片来自bootstrap可视化编辑器）：
![image](https://cloud.githubusercontent.com/assets/22813922/25375175/702e26c4-29d2-11e7-8317-ed1b697122db.png)

### 你估计可能的原因是什么（选填）？

可能是CSS问题.

**Comment by icarusion** [comment]
建议使用栅格自己实现响应式
