### ISSUE TITLE
datepicker组件的value值在使用键盘删除时未及时响应

### ISSUE THREAD

**Issue by xiaoyyang123** [iview/iview#781]
### iView 版本号
2.0.0-rc.11

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/xiaoyyang/pen/MmbYyK

### 复现步骤
先选择一个时间，然后用键盘的`backspace`键或`delete`键删除日期，删完后在其它区域点击下，鼠标再次移到输入框上

### 问题现象，以及你期望的结果是怎样的?
已选的日期并没有被删除，鼠标移上去，输入框的时间会闪一下然后消失，并且之前选择的日期不能再次被选中

**Comment by shitouguai** [comment]
使用了2.0.0-rc.17版本 这个问题还是存在  最后只好将editable设置为false来折中解决  不知官方能否修复一下这个问题

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
