### ISSUE TITLE
官网首页背景是怎么实现的

### ISSUE THREAD

**Issue by kunzhijia** [iview/iview#782]
请问iviewui官网首页的动画是用什么实现的，很赞！！

**Comment by lcx960324** [comment]
three.js

**Comment by liuzhibin123** [comment]
@lcx960324  three.js太大了，我看到他们这个很小 应该是做过切割提取。不知道这应该怎么做?

**Comment by TrendAlan** [comment]
例子在这里：https://jsfiddle.net/oep9bnuq/
