### ISSUE TITLE
Page在每次点击不同表格时，想将页码重置

### ISSUE THREAD

**Issue by D3xian** [iview/iview#784]
### Vue 版本号

###问题描述
三个table标签，一个公用的Page分页

 <Table :context="self1" :data="tableData1" :columns="tableColumns1" :border="true" stripe
                 class="TCCbottomTable1" width="1209px"></Table>
          <Table :context="self2" :data="tableData2" :columns="tableColumns2" :border="true" stripe
                 class="TCCbottomTable2" width="1536px"></Table>
          <Table :context="self3" :data="tableData3" :columns="tableColumns3" :border="true" stripe
                 class="TCCbottomTable3" width="1536px"></Table>

 <Page :total=totalNumber :current=currentPage @on-change="changePage($event)" show-elevator
                  :page-size="9"></Page>

export default {
    data () {
      return {
  currentPage: 1,
        totalNumber: 0,
          }
        }
methods:{
   changePage(page)
      {
        pageIndex = page;
        if (treeNodetype === "div_01") {
          if (fuzzyQuery == "") {
            this.searchLivingAndVodData(pageIndex, 9, unitCode, searchType, isContain, this.formItem.caseNumber, this.formItem.causeName, this.formItem.courtName, this.formItem.startDate, this.formItem.endDate, this.formItem.trailStatus, this.formItem.undertakeDepartName, this.formItem.undertakerName, this.formItem.judgeName);
          } else {
            this.tccSearch();
          }
        }
        else if (treeNodetype === "div_02") {
          if (fuzzyQuery == "") {
            this.classicCaseData(pageIndex, 9, unitCode, searchType, isContain, fuzzyQuery, this.formItem.caseNumber, this.formItem.causeName, this.formItem.courtName, this.formItem.startDate, this.formItem.endDate, this.formItem.trailStatus, this.formItem.undertakeDepartName, this.formItem.undertakerName, this.formItem.judgeName);
          } else {
            this.tccSearch();
          }
        }
        else if (treeNodetype === "div_03") {
          if (fuzzyQuery == "") {
            this.trialNoticeData(pageIndex, 9, unitCode, searchType, isContain, fuzzyQuery, this.formItem.caseNumber, this.formItem.causeName, this.formItem.courtName, this.formItem.startDate, this.formItem.endDate, this.formItem.trailStatus, this.formItem.undertakeDepartName, this.formItem.undertakerName, this.formItem.judgeName);
          } else {
            this.tccSearch();
          }
        }
      },
}
}
三个不同表格，一个分页
1.左侧三个tab是三个页面，一个页面用一个表格
假设我点击tab1，渲染第一个表格， 选择了第三页，
点击tab3，渲染第三个表格，但是分页还是选择在第三页，
想强置成1，是不是我也要把分页写三个，然后怎么区分这三个呢

**Comment by zhaotoday** [comment]
@D3xian 
重置 Page 组件的 current 属性为 1 即可。
https://github.com/zhaotoday/vue.js/blob/master/src/app/Articles/List/index.vue#L108

**Comment by D3xian** [comment]
用了这种方法，但是跳转到tab2 页码出现的格式为 1 2 3 2
