### ISSUE TITLE
Menu设置属性accordion,updateOpened方法无法使其他submenu收起来

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#786]
### 你估计可能的原因是什么（选填）？
Menu设置属性accordion,updateOpened方法无法使其他submenu收起来
![Uploading QQ截图6.png…]()
![qq 7](https://cloud.githubusercontent.com/assets/16515026/25417393/5f23cd1c-2a76-11e7-90f5-5cbcdab6f202.png)

**Comment by yangdan8** [comment]
![Uploading QQ截图6.png…]()

**Comment by zhaotoday** [comment]
Menu 貌似是有点问题，可以参考下我的实现：
https://github.com/zhaotoday/vue.js/blob/master/src/app/Layout/index.vue#L23
https://github.com/zhaotoday/vue.js/blob/master/src/app/Layout/components/Sidebar/index.vue#L38
