### ISSUE TITLE
tree 组件多级选中

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#787]
### 操作系统/浏览器 版本号
windowS/Chrome 56

### Vue 版本号
2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/MmbXoO

### 复现步骤
1.二级child2选中，则parent节点半选中状态，三级child1-1-2选中，二级child1无半选中状态
2.取消child1-1-2选中，在选中，没有显示为选中状态
### 问题现象，以及你期望的结果是怎样的?
多级选择，操作下级选项时，上级选项应当自动更新。

**Comment by lcx960324** [comment]
@QiiSyhx 
第一个问题确认是 bug ，正在修复。
第二个问题，麻烦升级一下您的 iView 版本。XD
