### ISSUE TITLE
关于upload组件的一些建议

### ISSUE THREAD

**Issue by boxshadow** [iview/iview#788]
upload组件现在只支持ajax post方法上传文件，很多第三方云存储都需要强制 put方式，这个有在后期考虑 [axios] 这个http库的加入吗
如果只有ajax的post方式，阿里OSS首先就被排除了，或者ajax会增加额外的type提交类型吗

**Comment by lcx960324** [comment]
upload 组件允许手动处理上传请求。
详见文档。

**Comment by boxshadow** [comment]
有官方的支持当然是更好的了
