### ISSUE TITLE
常见Issues及解答，提问前必看

### ISSUE THREAD

**Issue by icarusion** [iview/iview#79]
> 如果您已经在项目中开始使用 iView，可以加入微信进群讨论相关技术问题（加微信号icarusion，注明 iView，注意，目前只接受在企业项目中已经使用 iView 的同学）

针对一些常见的问题，整理如下，请大家不必再重复提问：
#### iView 的脑图是用什么做的？
> MindNode
#### iView 支持Vue2.0吗？
> 已支持 2.0。
#### iView 兼容IE吗？
> 目前支持较好的浏览器是Safari、Chrome、Firefox、Edge，在IE9~11上有部分样式及功能的不兼容，不支持IE8及以下浏览器。
#### 安装报错？
> iView的最佳实践是基于webpack来开发，使用时要做配置，请详细阅读[安装](https://www.iviewui.com/docs/guide/install)和[快速上手](https://www.iviewui.com/docs/guide/start)这两个文档页面。
#### 关于缺少xxx组件相关问题：
> iView的组件开发计划见[Programming](https://github.com/iview/iview#programming)，图片中列举了1.0版本计划完成的所有组件，请先仔细查看图中是否有你需要的组件。
#### 关于文档：
> 由于目前文档的实例与示例代码分离实现比较重，开源维护成本较高，因此暂未开源，我们很快会提供一个更好提供文档反馈的方案。我们也将于2017年初启动英文文档翻译计划。

### 提问说明
- 请尽量描述清楚您遇到的问题及复现过程，配有相关代码，代码请整理好格式。
- 请尽量不要问与 iView 无关的问题。
- 与 webpack 配置等基础问题，建议先到社区阅读相关资料或到相关项目下进行提问。

**Comment by zhenizhui** [comment]
提issues之前好歹看看close issues，

一直watching下来，发现问的最多就是前两个。。

说好的提问的艺术呢？

无力吐槽:flushed:

**Comment by nicholasalx** [comment]
SyntaxError: Unexpected token: name (Affix) [./~/iview/src/index.js:1,0]

这是什么问题???

**Comment by icarusion** [comment]
@nicholasalx 能先仔细阅读下文档吗

**Comment by q215171650** [comment]
大神，我已经用了你们的iview，坐等日期组件和时间控件

**Comment by alicePan** [comment]
@icarusion  感觉这个ui看起来很优雅简洁，虽然还未读过源码，希望早日开发 vue2.0, 也希望有机会能参与其中

**Comment by jerryyan1990** [comment]
今天偶然发现瞬间被吸引了，持续关注！希望赶紧出vue2.0的

**Comment by qq1413186399** [comment]
请问表单校验的api有吗？？？

**Comment by Sum41forever** [comment]
官网下
快速上手 - 点击这两个提示：该域名已过期，不能正常访问，续费后可恢复使用。 

Vue组件
基于Vue构建大型应用

![123](https://cloud.githubusercontent.com/assets/18468976/21834772/dc8b185e-d7f2-11e6-8a72-ce2c632ed1ad.png)

**Comment by jingsam** [comment]
@Sum41forever 那是因为vuejs.org.cn域名过期了，不是iview的问题

**Comment by jy00566722** [comment]
希望支持vue2.0哦。。

**Comment by icarusion** [comment]
@Sum41forever 已更换

**Comment by nicholasalx** [comment]
希望尽快支持vue2.0

**Comment by webKity** [comment]
怒赞一个，不知道啥时候支持vue2.0

**Comment by LancelotLewis** [comment]
能否增加样式模块选择功能，就像bootstrap一样，能够自主选择是否需要“图标”、“按钮”、“走马灯”等等

**Comment by mantou-kk** [comment]
(unknown) [Vue warn]: Error in mounted hook: 
(found in <ICol>)
vue.esm.js?65d7:1453 TypeError: this.$parent.updateGutter is not a function
