### ISSUE TITLE
希望解决下table在使用v-show时的尺寸BUG

### ISSUE THREAD

**Issue by 79229788** [iview/iview#796]
比如在使用table组件时，通过v-show的方式加载组件，则header、footer等等尺寸获取均为0。源码中的获取尺寸的方法，无法获取到隐藏元素的真实尺寸

**Comment by l86110** [comment]
同样遇到这个问题。

**Comment by fordongu** [comment]
这个使用 v-if 试试

**Comment by icarusion** [comment]
Use `v-if` instead
