### ISSUE TITLE
select 选择器 on-query-change  参数bug

### ISSUE THREAD

**Issue by fzc32** [iview/iview#804]
请问大家有没有遇到以下描述情况？怎样解决？
iview : 2.0.0-rc.11
vue: "^2.2.2"
使用on-query-change参数
搜索一次触发二次
第一次结果正确
第二次更改了我搜索的内容（通常返回值为空）

**Comment by fzc32** [comment]
请问是什么原因把我的问题关闭了？下次改进。

**Comment by icarusion** [comment]
按要求提问
