### ISSUE TITLE
Select 在可搜索，有默认值时，手动设置 Option 后，首次展开显示的问题

### ISSUE THREAD

**Issue by lvqingan** [iview/iview#805]
### iView 版本号
2.0.0-rc.11

### 操作系统/浏览器 版本号
macOS/Chrome 59

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[http://jsbin.com/posaqof/edit?html,js,output](http://jsbin.com/posaqof/edit?html,js,output)

### 复现步骤
option列表数据在data里直接初始化，或者直接在模板里写死都没有问题；
但是如果是动态生成option时就会出现该问题

### 问题现象，以及你期望的结果是怎样的?
#712 bug 并没有彻底修复，仍然需要点两次才能看到全部选项

**Comment by icarusion** [comment]
你没用过 npm 吗

**Comment by lvqingan** [comment]
@icarusion 这跟用没用过npm有关系吗？bug复现的实例我也贴了，如果您认为不是bug，那就请您在百忙之中抽空回复一下不是bug的理由，您回复这句我真不明白了

**Comment by icarusion** [comment]
你的代码还在 .11 版本，你要测，就从 github 最新的代码测，npm 还没有发布新版，懂了吗

**Comment by lvqingan** [comment]
@icarusion 好吧，我想我们可能是有误会，因为我是看了.11的更新日志里是写了

> 修复 Select 在单选可搜索模式下，第一次展开选项显示不全的bug。#712

要不我也不会报bug的，sorry啦

**Comment by icarusion** [comment]
看错了issue，看成了 Form。
但你这个是另一个issue，与 #712 场景不一样。

**Comment by icarusion** [comment]
你的问题又多了一层：手动更新 Option。
问题描述不清楚，会浪费很多时间。

**Comment by yeshuqin** [comment]
更新了最新版本还是有这个问题存在

**Comment by qinghua5453** [comment]
请问 select 你们的默认值是怎么做的呢 根据绑定的v-model  中的val来显示的话

**Comment by chaegumi** [comment]
https://github.com/iview/iview/issues/1637  这个原因
