### ISSUE TITLE
 select组件工作不正常【已找到原因】

### ISSUE THREAD

**Issue by Alecyrus** [iview/iview#818]
### iView 版本号
2.0.0-rc.12 

### 操作系统/浏览器 版本号
 WIndows/Chrome 56

### Vue 版本号
2.2.6 

### 复现步骤
把select组件写在modal里面的表单中

### 问题现象，以及你期望的结果是怎样的?

我的布局是modal里有个tab，其中一个tab下面有个Form， select组件在Form中某个form-item中
-Modal
----Tab
-------Form
----------Form-item
-------------Select

这时，点击选择框，则内容出现在左上方。如果在另一个tab内，不写form，直接写select组件，可内容显示位置正常。蜜汁bug

### 在modal里的表单form-item里：select组件内容错位
![在modal里](https://cloud.githubusercontent.com/assets/13865581/25565122/3ab69dde-2df4-11e7-89d1-a0a8e6b8c24b.png)

### 不在modal里，在页面上或者不在form-item下： select组件内容正常出现在下方
![不在modal里](http://o8jhue6cr.bkt.clouddn.com/sdfsdfsdf.jpg)
### 你估计可能的原因是什么（选填）？
原因已发现，点击后，.ivu-select-dropdown添加的属性中position为fixed导致显示位置不正常
如下：
![保留fixed](http://o8jhue6cr.bkt.clouddn.com/1.jpg)

![去除fixed](http://o8jhue6cr.bkt.clouddn.com/2.jpg)

### 建议
建议开发者在select组件内修复

**Comment by Alecyrus** [comment]
#669

**Comment by Alecyrus** [comment]
@icarusion

**Comment by BlueGene89** [comment]
我也打算做一个这样的页面，issue +1

**Comment by liniu** [comment]
确实有这个问题，我也碰到了。iview 2.0.0-rc.12 ,vue 2.3.0, firefox53

**Comment by larryu** [comment]
@BlueGene89 You can re-write the css in your  vue file just like below. This will do the trick. I use this way to avoid the issue.

    .ivu-select-dropdown {
        position: absolute !important;
    }

**Comment by BlueGene89** [comment]
@larryu 谢谢！我暂时先这么用着 期待iview版本更新

**Comment by Alecyrus** [comment]
@BlueGene89   移除只是为了查看原因哈（见我最后两张图）， 你没成功可能是因为 选错组件检查了，要选择dropdown那个框去调试，然后移除position属性，就可以发现可以正常显示了。 根本原因的话，我认为还是form-item组件的原因，导致设置fixed属性反而出现位置错误。

**Comment by Aysnine** [comment]
也遇到同样的问题，在 Tab 里使用时间和日期控间，下拉控件都出现偏差， @larryu 终于解决，蟹蟹 :)

**Comment by Aysnine** [comment]
@Alecyrus 这个问题，修改 position 解决了，新的问题又来了，`placement="top"` 没有效果

**Comment by gggllm** [comment]
添加fixed是poper.js的特性，他会一路想上寻找是否在fixed元素内，是的话就会设置为fixed，以实现共同滚动。所以去掉fixed会导致滚动问题。显然这里的问题是计算错了偏移量，至于为什么会算错，我还没时间去看。

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/595cfa72febd71cc58cb4e880b9c47f151d20347
