### ISSUE TITLE
col 标签和html标签冲突，无法自动补全</col>

### ISSUE THREAD

**Issue by wilfordw** [iview/iview#819]
使用Webstorm 无法补全`<col>`标签，比如`row>col` 展开是`<row><col></row>`，很不方便，而且会显示错误，我没有找到哪里可以忽略这个错误。同时支持补全，请问col有别名吗？

很奇怪 无法上传图片 我只能用文字描述了

**Comment by wilfordw** [comment]
<img width="758" alt="wx20170430-225156 2x" src="https://cloud.githubusercontent.com/assets/6120793/25565418/d31997b2-2df8-11e7-8525-ab3940b2ceef.png">
![test](https://cloud.githubusercontent.com/assets/6120793/25565423/d972dd4e-2df8-11e7-9c4c-40d472f1f851.gif)
补上图片

**Comment by Alecyrus** [comment]
建议你google，这不属于iview的问题吧。我的sublime配合Emmet，正常补全

**Comment by wilfordw** [comment]
@Alecyrus sublime 和 atom 都是可以正常使用的，不过毕竟它们不是ide,只需要对你打的标签进行<tag></tag>包裹就可以了，不用判断是否html内置，而webstorm集成的比较厉害，有些内置的标签该没有关闭</tag>就不给出你，你加了就报错。我总不能为了这一个标签让所有的标签的不支持智能补全把。
我就是google百度不到解决方法才来问的，希望有遇到同样问题的提供一些解决思路，grid布局是我用的最多组件了，刚从atom转到webstorm，不太会配置请见谅

**Comment by wilfordw** [comment]
已解决 是有别名的 <i-col>
