### ISSUE TITLE
能否支持服务器渲染，目前是不能用在服务器渲染中的

### ISSUE THREAD

**Issue by youthour** [iview/iview#820]
### Vue 版本号

能否支持服务器渲染，目前是不能用在服务器渲染中的

**Comment by Alecyrus** [comment]
Vue官方文档里有吧。

**Comment by youthour** [comment]
我的意思是说，vue用的服务器渲染模式，iview.js就会报错，提示 window is not defined.

**Comment by icarusion** [comment]
暂不支持，将来会支持 SSR
