### ISSUE TITLE
Disabled datepicker still can response to click  event.

### ISSUE THREAD

**Issue by larryu** [iview/iview#822]
### iView 版本号
"iview": "^2.0.0-rc.10",

### 操作系统/浏览器 版本号
CentOS7.3/IE11

### Vue 版本号
"vue": "^2.2.6"

### 复现步骤
Even assigned disabled property to datepicker, when you click the calendar icon,
the click event is still fired.

**Comment by larryu** [comment]
No one has this same problem? Same on version rc13.

**Comment by SergioCrisostomo** [comment]
@larryu I think this has been fixed since `rc13`. I can not reproduce it anymore.

Please check this jsFiddle: https://jsfiddle.net/Sergio_fiddle/98e5udgz/ and re-open if you can still find the problem.
