### ISSUE TITLE
filterRemote 报错

### ISSUE THREAD

**Issue by TFous** [iview/iview#824]
报错：Cannot read property 'querySelectorAll' of undefined
例子基本和这个一样：https://github.com/hezhiying/iview/commit/12bcf7bd14d0ca8f098ff7ad293e4f0f2fd8f872

希望有一个更具体的例子，或者可以将this绑定到vue

**Comment by yukunyi** [comment]
我也是这个错误，只要定义了filterRemote就会报上面这个错误

Cannot read property 'querySelectorAll' of undefined

报错代码：
```
const $td = this.$refs.tbody.$el.querySelectorAll('tbody tr')[0].querySelectorAll('td');
```

**Comment by TFous** [comment]
之前用的是老版本，我跟新了就好了，现在是筛选后，checked 无效

**Comment by icarusion** [comment]
@hezhiying

**Comment by hezhiying** [comment]
我测试一下

**Comment by yukunyi** [comment]
新版没这个问题了

**Comment by hezhiying** [comment]
@yukunyi 好的，我刚才测试了也是正常的，有什么问题继续这里沟通

**Comment by TFous** [comment]
@hezhiying  我用的是vuex 操作数据
``` javascript
            <Table
                    stripe
                    border
                    :columns="columns"
                    :data="getOptions.tableData"   // 这里读取的是ivuex 里的数据，filterRemote其实就是操作了vuex
                    @on-row-dblclick="showDetails"
                    @on-selection-change="selectionFn"
            ></Table>
```

筛选出来的结果
![image](https://cloud.githubusercontent.com/assets/8625882/25832828/a9dad8f4-349f-11e7-9996-4536edf6d7b6.png) checked 效果没有

**Comment by hezhiying** [comment]
只是本地过滤的不需要filterRemote，这个只是用做过滤需要远程服务器重新给:data这个数据重新赋值。
@icarusion vuex我不太懂，帮忙看看

**Comment by TFous** [comment]
@hezhiying  我的逻辑就是给data重新赋值，只不过是通过接口获取到数据后，更新到vuex.
