### ISSUE TITLE
表格内容区域适配有问题

### ISSUE THREAD

**Issue by Evoque** [iview/iview#827]
### iView 版本号
2.0.0-rc.5 

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
2.2.1 

### 复现步骤
设置Table的高度，让其显示纵向滚动条， 但是当表格宽度>内容宽度的时候， 会有滚动条的空白，截图如下：
![image](https://cloud.githubusercontent.com/assets/3809046/25645009/fcf02354-2fdc-11e7-9f8b-12627621b971.png)

**Comment by icarusion** [comment]
按要求提问
