### ISSUE TITLE
分页控件显示乱码

### ISSUE THREAD

**Issue by Evoque** [iview/iview#828]
### iView 版本号
2.0.0-rc.5
### 操作系统/浏览器 版本号
macOS/Chrome 56 
### Vue 版本号
 2.2.1 
### 复现步骤
分页控件省略号显示乱码:   
![image](https://cloud.githubusercontent.com/assets/3809046/25645906/829c61f4-2fe5-11e7-80e0-20fb04053283.png)

**Comment by swordlight** [comment]
是啊，这个要怎么解决

**Comment by PassionZale** [comment]
@swordlight @Evoque

![tim 20180802152219](https://user-images.githubusercontent.com/12482130/43568771-166e9b60-9668-11e8-8c61-1952cace5abf.png)


在 page.less 中,你们可以找到这个 ••• 的样式, 但是这个应该是中文下的全角符.

CSS 的 content 对中文支持不是很好, 需要将中文 unicode 编码之后使用.

你们可以在 reset.css 文件顶部加入 @charset "utf-8"; 再使用 "\2022" 覆盖掉 •••

![tim 20180802152554](https://user-images.githubusercontent.com/12482130/43568913-852ce6a6-9668-11e8-9159-c7cbcb616d3f.png)
