### ISSUE TITLE
请问文档是通过工具生成的还是手动维护的？

### ISSUE THREAD

**Issue by mygaochunming** [iview/iview#83]
请问文档是通过工具生成的还是手动维护的？

**Comment by jingsam** [comment]
手动维护

**Comment by mygaochunming** [comment]
这样维护成本岂不是很高？有没有能通过代码注释直接生成api文档的方式？请赐教

**Comment by icarusion** [comment]
如果你只是想知道如何实现，那可以去看相关基于md的webpack loader。
对于iView文档暂时实现较重，后续有别的方案来维护。
