### ISSUE TITLE
table和poptip一起使用时，poptip会被遮住

### ISSUE THREAD

**Issue by xugege** [iview/iview#830]
### iView 版本号
iview2.x

### Vue 版本号
vue2.x

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
http://sandbox.runjs.cn/show/l790frse

### 复现步骤
1.打开，点击上面的删除按钮
2.弹出的poptip会被table遮住

### 问题现象，以及你期望的结果是怎样的?
poptip需要正常显示

### 你估计可能的原因是什么（选填）？
因为poptip的dom对象是嵌入在table-column中的，因为table容器设置了overflow=hidden，所以导致poptip被遮住，所以一般这种弹出提示，一般都是把dom放入到body标签中，避免poptip因为父容器设置了overflow=hidden遮住

### 其他问题
iview中的tooltip,menu,dropdown估计都有这种问题

**Comment by YYQ8023** [comment]
dropdown确实存在相同情况，最新rc14版。求解?

**Comment by YYQ8023** [comment]
我的已经解决，把table的那一列的 fixed属性去掉即可。

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/fcf3cace8e7eee39ff90edc13ee1663b7f8c24c5

In next version, you can add prop `transfer` to Poptip, Tooltip component, it will be transfered to body to fixed this issue.

**Comment by jerexyz** [comment]
add transfer  worked for me

**Comment by lifedever** [comment]
add transfer worked for me

**Comment by limeiwang** [comment]
transfer | 是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果
-- | --
