### ISSUE TITLE
Table全选所在单元格宽度缩小之后，出现省略号

### ISSUE THREAD

**Issue by dean5277** [iview/iview#832]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
win7/Chrome 59.03

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
![image](https://cloud.githubusercontent.com/assets/1802631/25649476/6aba3db8-3008-11e7-8e6c-2a857e66b78a.png)

### 问题现象，以及你期望的结果是怎样的?
其实应该不算BUG，就是感官上不好看。

### 你估计可能的原因是什么（选填）？
全选的th有text-overflow: ellipsis;

**Comment by lcx960324** [comment]
可以自己覆写一下 table的 CSS 改成需要的样式。
