### ISSUE TITLE
modal 在新增表单提交后 关闭功能失效

### ISSUE THREAD

**Issue by ajianisbest** [iview/iview#833]
当外层有modal 外层有<Row type="flex" 时才会发生
移出可正常使用
DEMO https://codepen.io/ajian/pen/VbWOmz

### iView 版本号
2.0.0-rc.12

### 操作系统/浏览器 版本号
macOS

### Vue 版本号
2.2.1

**Comment by icarusion** [comment]
Row 要和 Col 连用
