### ISSUE TITLE
Select组件选项(Option) 过多(>500)时，过慢或者浏览器卡死

### ISSUE THREAD

**Issue by Evoque** [iview/iview#834]
### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
 macOS/Chrome 56

### Vue 版本号
 2.2.1

### 复现步骤
我的列表里有超过2000条的option要下拉选择， 使用Select组件的话，浏览器会直接卡死。 
经过测试，300条左右的时候处理速度明显变慢， 1000条之后就会卡死。 
代码：
```
    <i-Select style="width:200px" filterable placeholder="请选择开发集">
        <i-option v-for="item in businessItems" :value="item.bid" :key="item.bid" :label="item.name">
            <span v-text="item.name"></span>
            <span style="float:right; color:#ccc">bid:{{item.bid}}</span>
        </i-option> 
    </i-Select>
```
### 你估计可能的原因是什么（选填）？
可能是VUE渲染了过多的组件，导致内存占用过多。

**Comment by starmarker** [comment]
这种无解，500条的下拉会死人的！

**Comment by liniu** [comment]
一下子载500条显然太多了，我觉得一次只抓取20条，然后通过搜索的关键字到后台获取，但是i-select 不知道如何实现，因为我重新获取的时候，更新了下拉框的列表，单输入的关键字也被清空了，不知道算不算是bug

**Comment by starmarker** [comment]
@Evoque 2000条的下拉这种本身就很不靠谱.用户去拉2000条数据中选择一条。
我们有这种从大数据量中选择的业务需求的时候都是弹出一个列表，然后列表具有分页搜索功能，从里面选择一个

**Comment by ftqiao** [comment]
https://juejin.im/post/5be534086fb9a049ef2615e2 纯滚动搜索，场景应该不多吧。
当数据量大的时候，这个框应该支持搜索啊

**Comment by MechaGirls** [comment]
使用原生select不会卡啊的

**Comment by findingkim** [comment]
1、在select 加载出来以后将你的businessItems置空。
2、之后监听下拉的展开和收起，展开式赋值，收起时置空。

**Comment by 1124541815** [comment]
我们以前用了大数据表格加载2万条都不卡，下拉也不卡不知道用啥技术做的
