### ISSUE TITLE
on-page-size-change 没有触发

### ISSUE THREAD

**Issue by heboliufengjie** [iview/iview#836]
### iView 版本号
2.0.0-rc.12 

### 操作系统/浏览器 版本号
 搜狗浏览器 7.0.6.22932  高速模式

### Vue 版本号
v2.3.0 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
 例子：
 https://jsfiddle.net/hebo/a5ops08s/4/

### 问题现象，以及你期望的结果是怎样的?
  点击分页，没有触发我想要要的on-page-size-change 函数（没有报错）

**Comment by icarusion** [comment]
on-page-size-change	是切换每页条数时的回调
