### ISSUE TITLE
在IE中，modal浮层水平方向不居中，而是贴在窗口右侧

### ISSUE THREAD

**Issue by gxlmyacc** [iview/iview#84]
如题。

**Comment by gxlmyacc** [comment]
还有一个问题，select组件在ie里下拉框背景会变透明。

**Comment by icarusion** [comment]
IE什么版本

**Comment by gxlmyacc** [comment]
IE11 win10

**Comment by gxlmyacc** [comment]
刚才测试发现因为我想实现垂直居中，所以加了

> .ivu-modal-wrap {
>   display: flex;
>   align-items: center;
>   justify-content: center;
> }
> 
> .ivu-modal-wrap.ivu-modal-hidden {
>   display: none;
> }
> 
> .ivu-modal-wrap .ivu-modal {
>   top: 0px;
> }
结果加了这个以后，modal浮层在ie里就居右了

**Comment by icarusion** [comment]
- IE11中，垂直居中对于flex的支持http://caniuse.com/#search=flex
你可以用别的方法来实现，demo中只是示例。
- Select 组件并没有问题

**Comment by gxlmyacc** [comment]
好吧，只能想想其他办法了。
