### ISSUE TITLE
table组件中render select组件失去focus任然不会收折

### ISSUE THREAD

**Issue by monkeySmoke** [iview/iview#840]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

windows10/Chrome 56
### Vue 版本号

2.2.6 
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/smokeMonkey/pen/rmzvLr
### 复现步骤
点击其中一个select，再点击其他select
### 问题现象，以及你期望的结果是怎样的?
之前被点击的select不会收折
期望的结果：未被选中的select能自动收折

**Comment by ChaiXiangguo** [comment]
me too

**Comment by ChaiXiangguo** [comment]
你有解决吗？原因我找到了，是table组件添加了click.stop事件，导致clickOutside函数没有触发，但是不知道怎么解决

**Comment by monkeySmoke** [comment]
没有，已经弃坑

**Comment by icarusion** [comment]
Use `transfer` prop.
