### ISSUE TITLE
关于带ICON 的Input 组件建议

### ISSUE THREAD

**Issue by IssaTan1990** [iview/iview#842]
现在带ICON 的Input 是使用前置、后置标签实现的，希望实现跟 [Ant Design 在输入框上添加前缀或后缀图标](https://ant.design/components/input-cn/#components-input-demo-presuffix) 一致的input 表现形式。
这种风格主要用于登录表单，现在使用 `slot="prepend"`这种方式实现，那个灰色的阴影很难看，另外在validator 时，展示的边框也很奇怪。
![qq 20170504163940](https://cloud.githubusercontent.com/assets/10755797/25696019/18fc0bba-30e8-11e7-8506-07daf8e2e3f2.png)
这样的form 表单就舒服很多
![qq 20170504164019](https://cloud.githubusercontent.com/assets/10755797/25696039/38b6889a-30e8-11e7-8142-df650cc0ce42.png)
而且 `iView`中左边的`ivu-input-group-prepend` 的 `border-radius`是`6px`，但右边的 `ivu-input` 的 `border-radius` 是 `4px`，这个边角看起来也很奇怪。
我知道这些都是细节问题，而且会带来一定的改动，但 Ant Design 就是细节致胜啊！希望可以考虑。

**Comment by zhouboluo** [comment]
怎么自定义输入框高度？重写样式没有起作用

**Comment by zhaozhe0831** [comment]
我也有同样的需求，期待开发者的反馈。@icarusion

**Comment by BoleLee** [comment]
`<Input v-model="search" @on-click="handleSearch" icon="search" size="large" placeholder="搜索词"></Input>`

通过`icon`形式给`input`添加图标，图标可点击，希望图标可以有`cursor: pointer`效果

**Comment by icarusion** [comment]
fixed after 3.x version
