### ISSUE TITLE
在tabs中，select无法正常显示

### ISSUE THREAD

**Issue by lily920416** [iview/iview#844]
iView 版本号
2.0.0-rc.5 

操作系统/浏览器 版本号
 windows/Chrome 版本 56.0.2924.87

 Vue 版本号
 2.2.1 

能够复现问题的在线示例;
https://codepen.io/anon/pen/vmJvYo

复现步骤
在tabs中，select就不起作用了

 问题现象，以及你期望的结果是怎样的?
希望在tabs中，select能正常显示

**Comment by dryqiao** [comment]
你好，这个问题你怎么解决的？

**Comment by guiyanakuang** [comment]
@lily920416 @dryqiao 
```
.ivu-tabs {
    box-sizing: border-box;
    position: relative;
    overflow: hidden; //这个会隐藏内容高度以外的内容
    color: #657180;
    zoom: 1;
}
```
你的示例上直接对select设置一个高度就好了
```
<Select v-model="model1" style="width:200px;height:300px ">
        <Option v-for="item in cityList" :value="item.value" :key="item">{{ item.label }}</Option>
 </Select>
```

**Comment by icarusion** [comment]
高度不够

**Comment by dryqiao** [comment]
@icarusion 为了下拉框而预留表格行高不合理啊，不操作的时候空在那不好吧

**Comment by xianzhi0520** [comment]
我也是这个问题  这个高度应该是自动的吧 如果固定了  那个地方就空出来了  而且下拉出来的 能不能调整z-index到最顶层呢  这样是不是可以解决
