### ISSUE TITLE
关于Tab控件中条件渲染的问题

### ISSUE THREAD

**Issue by BlueGene89** [iview/iview#847]
### Vue 版本号

我有一个列表页面，列表有编辑按钮，还有一个全局按钮，当传入id时，弹出modal窗口，通过id可以判
断是编辑还是添加，从而控制不同tab的显示与否。
modal窗口控件结构如下：
Modal
    Tabs
        Tab-pane v-if="id > 0"
现在的问题是：
如果先进入添加modal，再进入编辑modal，tab会选项会变动，也就是说v-if从false变为true时会渲染
但是，如果先进入编辑，再进入添加，即v-if的判断从true变为false时，tabs里的v-if渲染条件却不会更着改变
为了确定是控件的原因，在tabs同级下添加div v-if，是可以达到效果的。
所以我不确定这是bug还是这种效果的实现方式不对

**Comment by liekkas** [comment]
同样问题
