### ISSUE TITLE
table组件的filter希望能够添加文本输入后搜索的功能

### ISSUE THREAD

**Issue by starmarker** [iview/iview#849]
### iView 版本号
 iview@2.0.0-rc.11

### Vue 版本号
 2.2.6 

### 问题现象，以及你期望的结果是怎样的?

现在的filter只能在固定的选择项之间做筛选，希望能够有文本框可以自行输入后进行筛选的功能。
另外，renderHeader方法return中不能写vue的事件调用methods中的方法。
能够解决任何一个，都可以让table组件的filter或者搜索功能更灵活！

**Comment by malaimoo** [comment]
确实，这样让用户自己输入筛选会方便很多，希望能加入此功能。 @icarusion

**Comment by angusjiang** [comment]
+1 ,常见的filterBy 怎么可以没有

**Comment by icarusion** [comment]
I suggest you do your own search outside of Table
