### ISSUE TITLE
Request to add TreeSelect component

### ISSUE THREAD

**Issue by VolcanoOves** [iview/iview#850]
### 问题现象，以及你期望的结果是怎样的?
现在有下拉框，没有下拉树形选择框，但是级联选择器可以代替下拉树形选择框，但是阔不阔以增加一个下拉树形多选框，这种在业务系统中非常常见的，但是目前没有，有点桑心...

**Comment by icarusion** [comment]
后面会增加 TreeSelect，建议先用 Tree 和 Dropdown、Input 自己封装

**Comment by VolcanoOves** [comment]
好的！感谢！

**Comment by asd8510678** [comment]
什么时候出TreeSelect

**Comment by WoolenWang** [comment]
TreeSelect啥时候出呢?

**Comment by linjinze999** [comment]
element下个版本就出了，不希望因为一两个常见的组件影响我选择组件库呀，计划时间有吗

**Comment by TonyLuo** [comment]
TreeSelect啥时候出呢?
