### ISSUE TITLE
加入vue-i18n 6.1.1 各种组件会报错

### ISSUE THREAD

**Issue by viyongyong** [iview/iview#854]
iView 版本号 
2.0.0-rc.12

### 操作系统/浏览器 版本号
macOS/Chrome

### Vue 版本号
2.2.6

### 问题现象，以及你期望的结果是怎样的?
[Vue warn]: Error in render function: "TypeError: _vue2.default.locale is not a function"

found in

---> <Modal>

### 你估计可能的原因是什么（选填）？
一个个测试了 加上vue-i18n就用不了了 不知道这个你们解决不 如果不解决就直接关掉吧。 THX

**Comment by icarusion** [comment]
用vue-i18n 5
