### ISSUE TITLE
table中的render按钮的事件使用的上下文bug

### ISSUE THREAD

**Issue by yangdan8** [iview/iview#856]
table中的render按钮的事件,使用的上下文不要图片按钮的self就不能执行,提示函数不存在,而文档提示,默认就是使用的this作为上下文,rc12才出现的bug

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

![qq 20170507000501](https://cloud.githubusercontent.com/assets/16515026/25774136/4b361ffa-32bc-11e7-841e-dd32c08b8315.png)

**Comment by icarusion** [comment]
哪里写默认是 this 了。

**Comment by yangdan8** [comment]
之前不用写self.delete(id)中的self也可以,现在不行了
vue版本2.3
iview版本2.0-rc12
