### ISSUE TITLE
iview官网组件界面 例子框下方显示更多“三角符号” 或 “显示代码” 效果是如何实现的？

### ISSUE THREAD

**Issue by zhangxuehang** [iview/iview#858]
鼠标放到例子框中 ，框会有阴影效果 ，猜测是Card控件。框下面会有三角按钮 或 文字，点击会显示全部。这种鲜果是如何实现的？如何控制Card显示部分 或者是全部？

**Comment by icarusion** [comment]
去看文档代码

**Comment by zhangxuehang** [comment]
组件页面代码都是编译过成html代码，不知是如何使用iview控件做出来的，请指教
