### ISSUE TITLE
2.0 table render中使用input v–model，导致input每次输入时都会失去焦点

### ISSUE THREAD

**Issue by Demon2** [iview/iview#864]

**Comment by yy303023858** [comment]
我也是这样的问题，换成Input-number，但是随之而来的是另一个问题，操作table中的按钮的时候需要点两下，第一下失去焦点，第二下才可以操作

**Comment by chenfengjw163** [comment]
table自定义组件编辑完成之后获取this.$refs.table.rebuildData同步到data中去，放弃table中自定义组件的双向绑定吧
