### ISSUE TITLE
Table组件render Form表单不能验证

### ISSUE THREAD

**Issue by 526479135** [iview/iview#867]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
macOS/Chrome 58

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/syefeng/pen/JNMMMv

### 复现步骤
点击输入框输入内容
### 问题现象，以及你期望的结果是怎样的?
不能做表单验证。想要实现表单验证功能

**Comment by icarusion** [comment]
升级到 rc.13，并使用新的 Render

**Comment by shaomingming008** [comment]
你好  请问解决了吗   怎么解决的  我用的iview最新版

**Comment by github-huge** [comment]
我也遇到这个  问题  怎么解决呀， 求解
