### ISSUE TITLE
iOptionGroup -> OptionGroup

### ISSUE THREAD

**Issue by littlexiang** [iview/iview#87]
文档与实际export名称不一致

**Comment by icarusion** [comment]
本周会release0.9.8，废弃了iOptionGroup，更名为OptionGroup

**Comment by littlexiang** [comment]
强迫症患者还是倾向于所有东西都以i开头好...

**Comment by jingsam** [comment]
以i开头是避免与原生组件冲突的权宜之计，我们推荐采用大写组件标签，这样你就可以很清楚地区分原生组件和自定义组件。在实践中，我们发现<Button>写法在美观度和区分度都高于<i-button>写法。
由于 Vue 2.0 的模板是区分大小写的，所以未来iview升级到2.0会全面消灭前缀写法，统一采用PasalCase写法。
