### ISSUE TITLE
Do not include normalize.css in the iview.css - it should not overwrite the common tags such as html, body

### ISSUE THREAD

**Issue by KrishnaPG** [iview/iview#872]
The css stylesheet (https://unpkg.com/iview@2.0.0-rc.12/dist/styles/iview.css ) is overriding the `html` tag css, which is not correct.

The `iview.css` should only contain the styles that are **specific** to the components and nothing extra.

**Comment by icarusion** [comment]
IView is a complete set of the front end of the solution, so it contains the basic style code.

**Comment by KrishnaPG** [comment]
Clearly iView has no fundamental concept of "modularity" and "reuse" it looks. Good luck with that.

**Comment by cyio** [comment]
想用 robust.css 等别的库，应该允许开发者不引入 normalize
