### ISSUE TITLE
iSelect 加载400多条数据要 17秒，请确认！

### ISSUE THREAD

**Issue by maxid** [iview/iview#873]
### iView 版本号
2.0.0

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[iview-select.html.zip](https://github.com/iview/iview/files/986324/iview-select.html.zip)

### 复现步骤
打开附件中html，点击加载数据按钮

### 问题现象，以及你期望的结果是怎样的?
iSelect 加载400多条数据要 17秒！希望尽快解决
### 你估计可能的原因是什么（选填）？
估计问题的起源是以下位置, updateOption
<img width="953" alt="select-vue-code-snap" src="https://cloud.githubusercontent.com/assets/927429/25847356/692bc0c2-34e8-11e7-8b11-81fc07ef992c.png">

**Comment by guiyanakuang** [comment]
你的问题和我提交 https://github.com/iview/iview/issues/871 应该是同一个原因，测试了一下你的demo，在 https://unpkg.com/iview@2.0.0-rc.8/dist/iview.min.js 下可以很流畅的加载，之后的版本都会卡死

**Comment by maxid** [comment]
@guiyanakuang thks

**Comment by maxid** [comment]
@guiyanakuang rc.8 的 select.vue 中没有 append, remove 两个事件的监听 ... , 已踩了很多坑了 ...

**Comment by icarusion** [comment]
数据较多时，建议使用远程搜索，该功能已完成，会在下个版本发布。

**Comment by starding** [comment]
感觉这中间有个bug，是不是事件循环触发了什么的，之前跟过一下代码，但是没跟出来

**Comment by starding** [comment]
@icarusion  事实上，仅仅200+数据就能让Select组件渲染时长到4，5s。

「建议使用远程搜索」这种交互方式有时候会存在问题，这意味着搜索人必须知道自己搜索的内容大致是什么，假设一个新人来使用这个组件来完成一些功能，而这个新人不知道内容的大致范围的话，就很不友好了。

而完整的select列表可以起到教育作用，即使是一个新人也能很快学到选项的大致内容范围。

**Comment by melon** [comment]
遇到类似的问题，Select组件性能问题比较严重，希望能优化一下~

**Comment by guiyanakuang** [comment]
@starding 消耗的时间随着数据量呈平方级增长，不得不猜测中间进行了两层节点循环，感觉上是有空间优化的

**Comment by melon** [comment]
https://github.com/iview/iview/blob/2.0/src/components/select/select.vue#L596

每个Option被append的时候都触发这个回调是不是消耗太大了，能不能优化成全部Option都添加完成之后再统一触发回调？

**Comment by guiyanakuang** [comment]
@icarusion 刚看了一遍Select.vue的源码，发现性能不佳的主要原因应该是[findChild](https://github.com/iview/iview/blob/2.0/src/components/select/select.vue#L217)使用顺序查找option component，我想如果再维护一个optionInstancesMap对象（key:name, => value:option）保存映射，那么O(n)的查找时间复杂度可以降低到O(1)，一点愚见

**Comment by tylerchen** [comment]
Table组件也同样有这个问题

**Comment by t7er** [comment]
@icarusion  远程搜索怎么选定后显示成value值了而不是label值呢?

**Comment by icarusion** [comment]
@t7er #915

**Comment by lifeforfun** [comment]
建议Select组件加一个 list属性接收option列表代替Option组件循环初始化,这样能节省很大一部分资源占用，另外tabs组件的样式**.ivu-tabs**建议在使用``:animated="false"``的时候不加**overflow:hidden**样式，我这里的出现的问题是此样式将内容里的Select的下拉菜单组件超出隐藏了

**Comment by xjx79** [comment]
这个问题现在有人在解决吗？新版本里面

**Comment by xjx79** [comment]
我现在要展示大概3000多个内容，一下子chrome就卡死了。

**Comment by moyuye** [comment]
这个问题确实严重，几百条就能很卡。有路由的情况下 切换必卡。

**Comment by icarusion** [comment]
在这盖1000楼也解决不了问题，不如看看源码，提出点建设性意见来：）

**Comment by Alan110** [comment]
@icarusion 你这态度有问题啊，你没想过去解决问题吧，就这么搞开源项目的吗。等着别人给你填坑吗

**Comment by icarusion** [comment]
不想在为这种问题烦恼了，一个个负能量满满的问题已经把我搞的心情很差，根本没心情去 fixed。
我希望大家能够善待 GitHub，善待开源。
希望大家能好好学学国外的开发者吧，来看看这个 pr 的质量和态度：
https://github.com/iview/iview/pull/1580 

问题有很多，但需要人，需要时间，一个一个来解决，所以请理解一下吧。

**Comment by Alan110** [comment]
我请你也拿出对国外开发者的态度，国内开发者不是人吗？抽空提出的issue，你怪我们没给出代码。我请问你真的有好好看过上面的人给出的意见吗？有给过哪怕一点关于问题的回复与建议？873 到1653，问题还是问题，没有丝毫进展。至少把问题给定位了，要求不过分吧？不然你们这些管理者是用来干嘛的？看我们每个人重复走了一遍又一遍，原地打转，耍猴吗？谁还愿意来解决问题，管理者自己都不重视问题

我是吃饱了没事干么，在这儿跟你啰嗦，我需要等你修复吗？解决问题，我自己就重写组件了，我干嘛还要花时间给你提issue？连起码的尊重都没有，你如何指望有人来给你修复问题？

我也不想和你多说，我只希望今天所有的对话，能给你敲响警钟。请面对问题，如果你选择无视，i don't care

**Comment by icarusion** [comment]
不想再继续浪费 405 人的时间来接受这些负能量，所以请 @Alan110 兄台，放弃使用 iView，强烈建议你自己开发一套组件库来用，为了社区，拜托了。
