### ISSUE TITLE
Select should accept options as attribute

### ISSUE THREAD

**Issue by KrishnaPG** [iview/iview#874]
Currently, `select` component requires the options to be supplied separate as `Option` child component. This is not convenient when using dynamic components. All components of the UI should accept same/similar parameters for better dynamic component support.

For example, 
````
<component :is='getControlType(schema.type)' v-model="datasource[datapath]" :options='schema.options'></component>
````
One cannot do such as the above (rendering the component dynamically based on the type of data), with the way current `select` element works.

Please consider making the `select` component accept the `options` as attribute, something like below:
````
<template>
  <Select v-model="value" :options="options" >  </Select>
</template>
````

**Comment by icarusion** [comment]
Sorry，we design Select use slot, it looks native.

**Comment by KrishnaPG** [comment]
Vue components are all about "modualiry" and "reusability". If someone wants "native", then no point in using Vue components - one can use the HTML native components directly.
