### ISSUE TITLE
怎么手动关闭Modal按钮的 loading状态

### ISSUE THREAD

**Issue by pakyo-pan** [iview/iview#88]
代码如下：
```js
Modal.info({
    title: '新建账套',
    content: _html,
    loading: true,  // 我想在ajax验证失败后取消loading，验证成功后 Modal.remove();
    onOk () {
        setTimeout(() => {
            console.log(Modal.loading);
            // Modal.remove();
            // Message.info('异步关闭了对话框');
        }, 1000);
    }
});
```
![9f232044-b57a-4f2f-b60d-c2a112f5a943](https://cloud.githubusercontent.com/assets/13342613/20378327/40f4741e-acd0-11e6-9b01-0a0034e1f9f7.png)

如上一个表单，想用Modal来做，验证失败后不关闭Modal并且取消按钮的loading状态，应该如何处理，谢谢各位大大的指点.

**Comment by icarusion** [comment]
实例创建的Modal，即$Modal的使用场景是一般的信息确认，不建议嵌套过多内容。可以使用组件的Modal

**Comment by pakyo-pan** [comment]
好吧，谢谢。我只是觉得实例创建的Modal样式好看一些
