### ISSUE TITLE
Selected text did not update when add new object to the data

### ISSUE THREAD

**Issue by xoit** [iview/iview#880]
### iView 版本号
2.0.0-rc.5

### 操作系统/浏览器 版本号
Linux/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://jsfiddle.net/owns3jah/#&togetherjs=CgfyPgHtSV

### 复现步骤

click new, and add text in input blank, 
then select option just added, data has updated but selected text keep old.
### 问题现象，以及你期望的结果是怎样的?
selected input did not update the label.

**Comment by SergioCrisostomo** [comment]
This is related to how Observables work. Since you only change a property of a array element the changes will not propagate to the Select internals. You can fix this by reseting the array and setting the select value like this: https://jsfiddle.net/gvboutoq/
