### ISSUE TITLE
Form验证number类型错误

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#882]
### iView 版本号
 2.0.0-rc.12

### 操作系统/浏览器 版本号
windows7/Chrome 56

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/anon/pen/PmQKQg

### 复现步骤
在input里面输入一个数字
### 问题现象，以及你期望的结果是怎样的?
验证不通过，需要验证通过

**Comment by lvqingan** [comment]
可能是因为input的fieldValue是string导致的，建议你用InputNumber

**Comment by lvqingan** [comment]
或者你可以把
```
v-model="dataForm.num"
```
改成
```
v-model.number="dataForm.num"
```
但是，这样是把值做了强制转换，框里如果输入`1a`也是能通过的……

**Comment by QiiSyhx** [comment]
换成input-number是可以的

**Comment by rongxingsun** [comment]
加number属性即可
<i-input v-model="dataForm.num" number></i-input>

**Comment by 544751779** [comment]
666
