### ISSUE TITLE
Upload CORS ERROR 上传图片出现跨域问题

### ISSUE THREAD

**Issue by 136446529** [iview/iview#884]
### iView 版本号
2.0.0-rc.11

### 操作系统/浏览器 版本号
macOS/Chrome 56

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

/

### 复现步骤
/

### 问题现象，以及你期望的结果是怎样的?
上传图片时存在跨域问题
(已配置:with-credentials="true")
期望可以判断是否添加了onprogress钩子，选择性配置XMLHttpRequest upload.onprogress, 或者有其他更好的方法
### 你估计可能的原因是什么（选填）？
XMLHttpRequest加入upload.onprogress后，出现了预检测请求，导致cors问题。
修改 iview/src/components/upload/ajax.js
```
// 1.修改XMLHttpRequest同步 #64
xhr.open('post', action, false);
// 出现警告: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

// 2.屏蔽 #33 ~ #40，不处理upload.onprogress

// 修改1/2后就不会出现CORS问题。
```

**Comment by icarusion** [comment]
最好在 server 端配置
