### ISSUE TITLE
定制theme中的animation全部无效

### ISSUE THREAD

**Issue by woshiguabi** [iview/iview#889]
### iView 版本号
2.0.0-rc.11

### 操作系统/浏览器 版本号
Chrome 57

### Vue 版本号
2.3.3

### 复现步骤
install iview-theme 然后build并在入口文件中import

### 问题现象，以及你期望的结果是怎样的?
所有动画效果消失

### 你估计可能的原因是什么（选填）？
iview-theme项目中的animation/index.less与iview项目中文件不一致，运行init重新获取模板也无效。
看了一下iview-theme，应该是因为**init下载的是master分支上1.0.2的styles而本地iview是2.0.0-rc**。
如何确保iview-theme下载的template与当前版本一致？能否加个feature在init时传入当前iview版本？

另: iview的动画效果的class名过于常见，如fade-leave，比较容易与其他样式冲突，建议加上ivu前缀

**Comment by icarusion** [comment]
更新到最新版，如有问题再另开 issue。
