### ISSUE TITLE
Page 分页 bug

### ISSUE THREAD

**Issue by yexiang1994** [iview/iview#891]
### iView 版本号
 2.0.0-rc.5

### 操作系统/浏览器 版本号
 macOS/Chrome 56

### Vue 版本号
2.2.1 

bug示例http://test.suwis.com/suwis_control/dist

问题：page分页，此项目page分页设置到盒子最底端，placement=“bottom”时点击分页显示数量栏，分页数量条会从父亲盒子的顶部出来。placement=“top”时亦是如此，

我的期望：当page设置到父亲盒子最底部时，分页显示数量栏 可以自动识别向上展出，

显示数量栏的盒子class=“ivu-select-dropdown”定位有问题，不应该设置为fixed。应该以class=”ivu-select”为父级设置绝对定位

**Comment by longzhaobi** [comment]
我也有类似问题，设置top时可以往上展示，但会错位，我就自己拿Select组件来设置分页的大小了。

**Comment by shdgit** [comment]
＋1
我设置的 :placement="top" 然而并无效果，还是朝下显示的，求修复。
版本 ： "iview": "^2.0.0-rc.14",
