### ISSUE TITLE
表格列表设置ellipsis后，Hover/Click时显示完整内容

### ISSUE THREAD

**Issue by sonycamera** [iview/iview#895]
### iView 版本号
2.0.0-rc.9

### 操作系统/浏览器 版本号
Linux/Chrome 56

### Vue 版本号
2.2.1

### 复现步骤
这是一个 Feature 增强请求

### 问题现象，以及你期望的结果是怎样的?
目前Table的列设置 ellipsis=true 后，超出单元格宽度的字符以省略号显示，这种情形下有个很常见的要求，就是希望鼠标放上去或点击后，能显示完整的字符。目前要实现这样功能，好像只能(我知道的，不对请纠正) 用render自定义模板，里面设置ellipsis相关css，比较麻烦。

建议：
列属性里增加一个属性，控制 在设置ellipsis后，单元格收到 hover或click事件时是否显示完整的单元格内容。

**Comment by icarusion** [comment]
使用 Tooltip

**Comment by sonycamera** [comment]
Tooltip确实可以显示提示信息，不过不知有什么方便的办法在单元格里显示 省略号？（我找了一圈iView组件，好像除了table里有 ellipsis 属性，其他的没有） 我对CSS不太熟，也不想为这个小功能引入太多的代码，希望有个简单优美的解决方案，谁知道的话提示一下，不胜感激。

**Comment by sonycamera** [comment]
用Tooltip显示不了省略号啊，文字被生硬地截断了， 加了下面的属性也不行：
```
render (row, column, index) {
  return `<Tooltip content="${row.text})">
    <div style="word-break: keep-all; white-space: nowrap; overflow: hidden; text-overflow:ellipsis;">${row.text}</div>
  </Tooltip>`
}
```
Tooltip的宽度没有继承自单元格(我不清楚怎么做到，在Chrome Devtools中给Tooltip加上 “width: inherit" 没用，指定具体数值有作用，如”width: 63px“会起作用）。

试了好多方法都得不到想要的效果：
超过宽度的文本显示省略号，鼠标悬浮（或实现为点击也行）以Tooltip或Poptip形式显示完整文本

@icarusion 能否指导一下？ 谢先!

**Comment by sonycamera** [comment]
加了个”display:block;“属性，总算解决了！ 叨扰了.
