### ISSUE TITLE
menu无法调用updateActiveName和updateOpened

### ISSUE THREAD

**Issue by ckdlbc** [iview/iview#898]
看了源码，$nextTick里没有这两个方法，menu组件里也没有$emit出来

**Comment by ckdlbc** [comment]
自己解决了，用于刷新页面后选中当前页的菜单
具体实现：
```
methods:{
      /* 更新菜单 */
      update (route) {
        this.activeMenu = this.$route.path //选中当前子菜单
        this.$nextTick(() => {  //展开当前子菜单所在的菜单项
          this.$refs.menu.$children.forEach((item) => {
            item.opened = item.active?true:false
          })
        })
      }
   }
```

**Comment by colin851** [comment]
@ckdlbc 我想在列表循环渲染完后更新menu而不是点击更新，这个要怎么个实现呢？

**Comment by doopcl** [comment]
我这里看是有的啊，$nextTick本身是一个类似异步程序执行工具，文档里面是说在nextTick中执行，我这里调用方式如下
`this.$nextTick(()=>{
    this.$refs.left_menu.updateOpened();
});`

**Comment by colin851** [comment]
@doopcl 那我应该是在哪个方法里调用呢，或者说列表循环渲染完后在哪个钩子里写呢

**Comment by colin851** [comment]
@doopcl 
created() {
    this.$nextTick(function(){
      this.$nextTick(()=>{ this.$refs.left_menu.updateOpened(); }); 
    })
![qq 20170515133821](https://cloud.githubusercontent.com/assets/17396706/26043996/1ea2b76e-3974-11e7-9dfb-4c19dc5a64b2.png)

**Comment by doopcl** [comment]
@colin851 
created里面就可以，这里其实和在哪个钩子里面调用没关系。不过我看你直接贴了我的代码，这是不行的，$refs下的left_menu是我自己定义的，定义方式如下：
`<Menu ref="left_menu" :active-name="current" width="auto" :open-names="leftMenuOpenNames" @on-select="leftMenuOnSelect">`
然后才能在Vue实例内this.$refs中获取到。
然后你贴的代码里面调用了两次$nextTick是什么意思？这里感觉上没有必要。

我再多说两句，updateOpened()方法可以理解为是个类似reRender的操作，调用之前还是需要更新一下open-names对应的数据源，然而可能是框架限制，做不到二次更新数据源之后直接在当前tick 
 reRender，所以需要额外调用一次

**Comment by colin851** [comment]
@doopcl 
created() {
    this.$nextTick(() => { 
      this.$refs.left_menu.updateOpened(); 
    });
    console.log('ww')
  },我现在是这样的了  但是我的menu菜单是动态v-for循环出来的（菜单的内容是放到一个数组比如[1,2,3]里），created()的时候只是执行了一次 我再改变数据[4,5,6]列表重新渲染created()里面的就不执行了

**Comment by doopcl** [comment]
@colin851 
我这里菜单的数据也是通过AJAX请求下来的动态数据，然后v-for渲染出来的。基本上和你的情况差不多

这里其实就是一个时序的问题，你在调用updateOpened()时需要确保
1，menu菜单的内容已经渲染完成
2，open-names的数据在menu数据中是可以找的到的
created()  当然是只在视图加载时才执行一次的，所以我上面说这里和在哪个生命周期方法中执行代码并没有绝对关系。而是根据你的业务逻辑，按照正确的时序来执行updateOpened

按照你的举例，当你将menu数据修改为新的[4,5,6]之后，就应该重新设置open-names，之后在下个tick执行updateOpened，以确保调用时，新修改的menu数据已在dom中完成渲染工作。大致代码如下：

`this.menuData = [4,5,6];  //重新设置menu数据
this.openNames = [5]; //重新设置open-names
this.$nextTick(() => {
    this.$refs.menu.updateOpened();
});//设置下个tick更新视图`

以上代码不局限于在某个生命周期方法中执行，也可以放置在比如AJAX callback 中执行

**Comment by colin851** [comment]
@doopcl 
现在我是这样写，暂时解决了我的问题  getNavIndex是我别的组件传到menu组件里的标识，根据这个标识来控制显示哪个menu内容，然后在menu组件里watch getNavIndex的值得变化！ 不知道这样写有没有隐患。谢谢你的耐心解答！！
 watch: {
    getNavIndex: function (val, oldVal) {
      this.$nextTick(() => {
      this.$refs.left_menu.updateOpened();
      this.$refs.left_menu.updateActiveName()
    });
    }
  },

**Comment by zsux** [comment]
updated(){
      this.$nextTick(() => {
        this.$refs.top_menu.updateOpened();
        this.$refs.top_menu.updateActiveName()
      });
    },

**Comment by xifengxx** [comment]
通过对路由route的判断来设置active-name，open-names。
`
<Menu ref="left_menu" :theme="theme2" width="auto" active-name="currentPage" :open-names="openedSubmenuArr" accordion @on-select="changeMenu">
……(省略代码)
</Menu>
……(省略代码)
created() {
    console.log("router detect:", this.$route);
    let path = this.$route.fullPath.match(/^\/(.*)\//);
    this.currentPage = this.$route.name;
    this.openedSubmenuArr = [].concat(path);
    this.$nextTick(() => {
        this.$refs.left_menu.updateOpened();
        this.$refs.left_menu.updateActiveName()
      });
  }
`
