### ISSUE TITLE
开关变化时不能控制状态的变更

### ISSUE THREAD

**Issue by fruitSandwich** [iview/iview#899]
### iView 版本号
2.0.0-rc.10

### 操作系统/浏览器 版本号
windows 10/Chrome  57.0.2987.133

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/fruitsandwich/pen/WjzpRW

### 复现步骤
切换开关状态，触发提示是否变更状态，但此时状态已经发生更改。

### 问题现象，以及你期望的结果是怎样的?
开关变化时触发后不能中断状态的变更。
希望提供外部可以控制状态变更的机制

### 你估计可能的原因是什么（选填）？

Switch 中click事件源码是先改变开关状态再触发一系列事件
```
toggle(){
  if (this.disabled) {
    return false;
  }
  const checked = !this.currentValue;
  this.currentValue = checked;
  this.$emit('input', checked);
  this.$emit('on-change', checked);
  this.dispatch('FormItem', 'on-form-change', checked);
}
```

能否添加一个props 让外部选择自行控制开关状态比如：
```
props:{
  outManage:{
       type:Boolean,
       default:false,
  }
}
//change事件
if (!this.outManage) {
    const checked = !this.currentValue;
    this.currentValue = checked;
    this.$emit('input', checked);
    this.$emit('on-change', checked);
    this.dispatch('FormItem', 'on-form-change', checked);
} else {
    this.$emit('on-change');
    //等等...
}
 <i-switch v-model="m1" out-manage="true" @on-change="change"></i-switch>
change () {
    this.$Modal.confirm({
        title: '切换提示',
        content: '<p>开关状态即将发生更改，是否继续</p>',
        onOk: () => {
            this.m1 = !this.m1
            this.$Message.info(`当前状态是 ${this.m1}`);
        },
    });
}
```

**Comment by starmarker** [comment]
确实，有个before-change就好了,可以执行很多异步的操作，最后返回true就执行改变，返回false就不执行改变。很多时候改变状态我们都要提交数据到后台。现在的解决方式都是不成功再把值置为！on-change的返回值

**Comment by fordongu** [comment]
+1 
确实加个变化前操作比较合理，radio,checkbox都应该加上，不然状态处理太麻烦了

**Comment by pakyo-pan** [comment]
+1

**Comment by areyouse7en** [comment]
+1

**Comment by rijn** [comment]
Hi, guys. Please review this code #1352 and I'm happy with any feedback. If you're good with this update, I will apply these changes to `Radio` and `Checkbox` as well.

**Comment by icarusion** [comment]
https://github.com/iview/iview/issues/2107

**Comment by leixu2txtek** [comment]
然而这个问题还是没有解决？

**Comment by Doduo** [comment]
这个问题解决了吗？

**Comment by ajiansoft** [comment]
所以，还是没有解决吗？

**Comment by leixu2txtek** [comment]
> 所以，还是没有解决吗？

把源码copy 一个 然后自己加就行了

**Comment by MisLink** [comment]
Workaround:

```vue
<i-switch ref="switch"></i-switch>
```

```js
this.$refs.switch.currentValue = statusBefore
```
