### ISSUE TITLE
定制主题变量覆盖报错

### ISSUE THREAD

**Issue by WuPanFeng** [iview/iview#900]
### iView 版本号

2.0.0-rc.12

### 操作系统/浏览器 版本号

Windows 10/Chrome 58

### Vue 版本号

2.2.6

### 问题描述
参考官网【变量覆盖（推荐）】本地配置如下：
###### config.js
         {
                test: /\.less/,
                use: ExtractTextPlugin.extract({
                    use: ['less-loader', 'autoprefixer-loader'],
                    fallback: 'style-loader'
                })
           }
###### main.js

 `import './styles/mytheme.less'`

###### node_modules 模块中less（^2.7.2）和 less-loader（^2.2.3）确认安装。
错误如下：
`ERROR in ./~/less-loader!./~/autoprefixer-loader!./src/styles/mytheme.less
    Module parse failed: E:\ProjectDemo\vue\IVIEW\node_modules\less-loader\index.js!E:\ProjectDemo\vue\IVIEW\node_modules\autoprefixer-loader\index.js!E:\ProjectDemo\vue\IVIEW\src\styles\mytheme.
less Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | .ivu-load-loop {
    |   animation: ani-load-loop 1s linear infinite;
    | }`
我也看了Issues的关于主题的所有问答，都未能解决。指导为盼！幸苦...

**Comment by liaohao1222** [comment]
改一改webpack配置
`{
                test: /\.less/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader?minimize', 'autoprefixer-loader', 'less-loader'],
                    fallback: 'style-loader'
                })
            },`
然后就好了…

**Comment by WuPanFeng** [comment]
@liaohao1222 非常感谢，搞定了。

**Comment by Tian-Hun** [comment]
覆盖变量在main.js中导入mytheme.less后，原来iview的样式没有了

**Comment by Rudy24** [comment]
@liaohao1222 试了下，也不行，还是提示文件找不到

**Comment by xiaomizhou66** [comment]
求解，这个具体的解决办法是什么？
这里说的方法用了没有解决
```json
{
                test: /\.less/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader?minimize', 'autoprefixer-loader', 'less-loader'],
                    fallback: 'style-loader'
                })
            }
```
网上说的这样也没有解决
```json
{
        test: /\.(less|css)$/,
        loader: ['style-loader', 'css-loader', 'less-loader'],
      } 
```
以及这样也没有解决
```json
 {
           test: /\.less$/,
           loader: "style-loader!css-loader!less-loader"
         },
         {
           test:/\.css$/,
           //loader:'css-loader!style-loader'
           loader:'style-loader'
         }
```

**Comment by Rudy24** [comment]
webpack需要配置或者less降级都可以

发自我的 iPhone
