### ISSUE TITLE
模板中使用的"  `  "字符，IE中报错显示无效字符

### ISSUE THREAD

**Issue by HejinWang** [iview/iview#903]
### iView 版本号
 2.0.0-rc.5 

### 操作系统/浏览器 版本号
IE 11  

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例 
 
 https://codepen.io/anon/pen/BWwVoy 
关于模板中使用的"  `  "字符IE中报错显示无效字符。 

 
### 问题现象，以及你期望的结果是怎样的?
关于模板中使用的"  `  "字符IE中报错显示无效字符。
请问有什么解决方法吗？

**Comment by icarusion** [comment]
babel

**Comment by HejinWang** [comment]
我是以静态资源引入的方式使用iview的。  
关于babel?请问如何操作，请原谅我的前端水平？能否给下提示或者关键字。
十分感谢
