### ISSUE TITLE
upload组件 无法读取上传进度报错

### ISSUE THREAD

**Issue by deboyblog** [iview/iview#906]
### iView 版本号
2.0.0-rc.12

### 操作系统/浏览器 版本号
win10/版本 57.0.2987.110

### Vue 版本号
2.3.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
上传组件 无后端 无法重现
### 复现步骤
我封装了一层上传（但是并没有重写相关上传 只是做了一些基础的判断） 
有时候是正常的 后端也正常返回了 
但是有时候会出现 `iview` 在尝试读取进度的时候无法正常读取
![snipaste_20170512_155533](https://cloud.githubusercontent.com/assets/11410323/25988689/836a1368-372b-11e7-816e-f89f4f108763.png)
![snipaste_20170512_155541](https://cloud.githubusercontent.com/assets/11410323/25988694/87b3b78a-372b-11e7-9e92-b375619338fa.png)

### 问题现象，以及你期望的结果是怎样的?

图片尝试过多张 BUG出现不是必然的 有时候同一张图片可以 有时候不行 
但是经常出现 没有进度条  上传完成突然显示出图片的BUG

**Comment by deboyblog** [comment]
已经找到问题了 
是我在 `handleBeforeUpload` 钩子中读取了当前的文件列表（为了展示最新上传进度）
但是同时我监听了这个列表变动 
这时候正在上传的文件也被 `emit` 到父级组件中 接着那个`defaultFileList`又跟着变了 
应该是`upload`组件同样监听了这个列表 导致了莫名的BUG

**Comment by gggllm** [comment]
filelist会反复地改变，导致每次我都得合成一个新的filelist出来，至于为什么filelist会变，我一直以为是组件重新渲染了，defaultList是什么时候变的？我没给这个赋值过，结果也会一直变。
