### ISSUE TITLE
The computed property "fields" is already defined in data.

### ISSUE THREAD

**Issue by houzw** [iview/iview#907]
### iView 版本号
2.0.0-rc.12/13

### 操作系统/浏览器 版本号
win10/Chrome 58

### Vue 版本号
 2.3.3

### 问题现象，以及你期望的结果是怎样的?
加载任意使用了 form 组件的单文件vue组件时控制台显示：
```
 [Vue warn]: The computed property "fields" is already defined in data.

found in

---> <IForm>

```
这些组件在使用 iview rc 6 + vue 2.2.1 时没有问题。
### 你估计可能的原因是什么（选填）？
iview 存在bug，或与vue2.3.x不兼容

**Comment by starmarker** [comment]
你确定没有在data里面定义同样的属性名么？

**Comment by lianqiang** [comment]
升级Vue后出现了同样的问题

**Comment by Ysanwen** [comment]
可能是第三方其他包引入了fields的computed导致，我在采用iview和vee-validate验证时也出现相同问题，解决方式参考https://www.bountysource.com/issues/44865956-integration-v-table-with-vee-validate

**Comment by houzw** [comment]
@Ysanwen 确实，我也是用了vee-validate。解决方案有效，只是没想到在没有使用vee-validate的组件里面，也会报这个错误。
>http://vee-validate.logaretm.com/
```javascript
const config = {
    fieldsBagName: 'vee-fields', // 默认为 fields
  };
  Vue.use(VeeValidate, config);
```

**Comment by luofengda** [comment]
昨天就发现这个问题，然后把form去掉，换成DIV的方式，就可以解决这个提示的问题

**Comment by gengchao123** [comment]
**请问el-form，这个问题怎么解决，初学vue**

**Comment by gengchao123** [comment]
```
 import Vue from 'vue'
  import {Form} from 'element-ui'
  const config = {
    fieldsBagName: 'formfields' // 默认为 fields
  }
  Vue.use(Form, config)
```
请问el-form，这个问题怎么解决，初学vue

**Comment by icarusion** [comment]
@gengchao123 哥们，这里是 iView ，你问错地方了

**Comment by gengchao123** [comment]
@icarusion 换汤不换药，都是基于VUE,大神告知，谢谢啊啊啊
