### ISSUE TITLE
cheboxgroup 出现点击不灵 和无法及时更新值

### ISSUE THREAD

**Issue by yangjy44** [iview/iview#911]
### iView 版本号
 2.0.0-rc.13 

### 操作系统/浏览器 版本号
 win7/Chrome 39 

### Vue 版本号
 2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://www.iviewui.com/components/checkbox

### 复现步骤
进入官网页面，初始化是显示苹果，点击选中西瓜，下面值还是[ "苹果" ]，在点击西瓜（为了去除选中），西瓜选中状态没有改变，点击苹果三次，西瓜选中状态没有

### 问题现象，以及你期望的结果是怎样的?
数据和显示，状态不一致，点击出现状态不变，期望数据一致

### 你估计可能的原因是什么（选填）？
Chrome 39 ，选中checkbox时，触发change事件，change事件触发的时候，this,model 并还未及时得到数据更新，此时又触发了checkbox-group，导致其他checkbox的值也是错误的，change后当前checkbox 的this.model完成更新，这时当前的checkbox 的this.model 和其他checkbox 的this.model 不一致。
这个可能和浏览器版本有关系，才会出现change事件的时候this.model 数据还未更新。
我尝试把change的代码延迟运行，结果是不会出现这个问题（备注：chrome39以上对数字证书支持不好，用户无法升级浏览器）

**Comment by icarusion** [comment]
不对低版本浏览器做支持

**Comment by dahaihu** [comment]
这个问题如何解决的？？？？
更新问题很难受
