### ISSUE TITLE
Table组件的render函数中参数h描述不明

### ISSUE THREAD

**Issue by nelsonnick** [iview/iview#913]
### Vue 版本号

新版本更新了Table组件的render函数，文档中的描述如下：render 函数传入两个参数，第一个是 h，第二个是对象，包含 row、column 和 index，分别指当前单元格数据，当前列数据，当前是第几行。
我看了下面的示例代码，仍然不太明白，这个参数h究竟是个什么东西？具体应该怎么使用？望解答或在文档中进行更进一步的说明。

**Comment by icarusion** [comment]
查看 Vue 文档，Render 函数

**Comment by longzhaobi** [comment]
iview的table数据多了，感觉好卡，希望这个能改善点。
