### ISSUE TITLE
PopTip组件的on对象中定义的ok和cancel不会被执行

### ISSUE THREAD

**Issue by myesn** [iview/iview#914]
### iView 版本号
 2.0.0-rc.13 

### 操作系统/浏览器 版本号
win7
chrome

### Vue 版本号
 2.2.6 

### 复现步骤

`const result = h('div', [
                        h('i-button', {
                            props: {
                                type: 'primary',
                                size: 'small'
                            },
                            style: {
                                marginRight: '5px'
                            },
                            on: {
                                click: () => {
                                    this.jumpToDetail(clientId)
                                }
                            }
                        }, '查看'),
                        h('Poptip', {
                            props: {
                                confirm: true,
                                title:`确认删除 ${clientId} ?`,
                                placement:poptipPlacement
                            },
                            on: {
                                ok:()=>{
                                    console.log('ok')
                                },
                                cancel:()=>{
                                    console.log('cancel')
                                }
                            }
                        },[
                            h('i-button', {
                            props: {
                                type: 'error',
                                size: 'small'
                            },
                            style: {
                                marginRight: '5px'
                            }
                        }, '删除')
                        ])
                    ])`

`
stirng s ="";
string s= "";
`
在table的column中定义render,然后返回以上元素

### 问题现象，以及你期望的结果是怎样的?

PopTip组件的on对象中定义的ok和cancel不会被执行

**Comment by icarusion** [comment]
是`on-ok`，不是 `ok`

**Comment by DF-teenager** [comment]
Hi~  我也遇到了同样的问题，试了很多写法都不生效，请问最后是怎么解决的？ @myesn

**Comment by myesn** [comment]
```
                        h('Poptip', {
                            props: {
                                confirm: true,
                                title:`确认删除 ${clientId} ?`,
                                placement:poptipPlacement
                            },
                            on: {
                                ok:()=>{
                                    console.log('ok')
                                },
                                cancel:()=>{
                                    console.log('cancel')
                                }
                                // ok: () => {
                                //     debugger
                                //     this.deleteClient(clientId,index)
                                // }
                            }
```
@DF-teenager  好像是这样的.

**Comment by DF-teenager** [comment]
我找到原因了~   `on: {
                                        'on-ok': () => {
                                            console.log('ok');
                                        }
                                    }`
Very TKS~   @myesn
