### ISSUE TITLE
Select 在单选 remote 模式下，选中显示为 value 而不是 label

### ISSUE THREAD

**Issue by liniu** [iview/iview#915]
### iView 版本号
 2.0.0-rc.13

### 操作系统/浏览器 版本号
win7 firefox 

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

http://runjs.cn/detail/fbmoy8o8

### 复现步骤

http://runjs.cn/detail/fbmoy8o8 
输入字母a 

### 问题现象，以及你期望的结果是怎样的?

远程模式单选选中后，输入框处显示的value值而不是label，具体看在线实例

### 你估计可能的原因是什么（选填）？
未知

**Comment by areyouse7en** [comment]
是要在下一个版本发布吗？2.0.0-rc.13 还有这个问题

**Comment by icarusion** [comment]
是的

**Comment by lovederh** [comment]
同问~

**Comment by icarusion** [comment]
rc.14已更新，详见更新日志和文档

**Comment by lovederh** [comment]
请问，如何进行回显，修改数据的时候，将select中的value传过来了，但是label没有显示出来！
