### ISSUE TITLE
rc13版中Table组件的render函数如何实现模板功能

### ISSUE THREAD

**Issue by nelsonnick** [iview/iview#916]
### iView 版本号
2.0.0-rc.13 

### Vue 版本号
2.3.3

### 问题现象，以及你期望的结果是怎样的?
新版本升级了Table组件的render函数后，有一个常见需求不知道应该如何实现？
例如，表格最后一列的内容是根据之前列的内容判断而生成的按钮，rc12版本以前的写法为：
```
{
            title: '操作',
            key: 'state',
            align: 'center',
            width: 300,
            render (row, column, index) {
              const states1 = row.state.toString() === '1'
              const states2 = row.state.toString() === '2'
              const states3 = row.state.toString() === '3'
              const states4 = row.state.toString() === '4'
              return `
              <i-button v-if="${states1}" @click="goEdit(${index})">修改</i-button>
              <i-button v-if="${states2}" @click="goInactive(${index})">注销</i-button>
              <i-button v-if="${states3}" @click="goActive(${index})">激活</i-button>
              <i-button v-if="${states4}" @click="goDelete(${index})">删除</i-button>
              `
            }
          }
```
新版本的写法则是：
```
{
            title: '操作',
            key: 'state',
            align: 'center',
            width: 300,
            render: (h, params) => {
              return h('div', [
                h('Button', {
                  on: {
                    click: () => {
                      goEdit(params.index)
                    }
                  }
                }, '修改'),
                h('Button', {
                  on: {
                    click: () => {
                      goInactive(params.index)
                    }
                  }
                }, '注销'),
                h('Button', {
                  on: {
                    click: () => {
                      goActive(params.index)
                    }
                  }
                }, '激活'),
                h('Button', {
                  on: {
                    click: () => {
                      goDelete(params.index)
                    }
                  }
                }, '删除')
              ])
            }
}
```
由于Vue的Render函数建议用JS代替模板功能，也就是说在rc12版本之前所采用的v-if或者v-for的模板将不能再使用。那么用rc13版本，应该如何更优雅的实现rc12之前那样动态的显示标签？当修改、删除、激活、注销这四个按钮对应不同的权限，采用JS的方式逐一判断，并在最后return一个h，写起了实在是太复杂了。

**Comment by yinheli** [comment]
写一个独立的 component 实现。示例如下：

新建一个独立的 vue， 如： `table-actions.vue`

```
<template>
  <div>
    <Button type="primary" @click="doSomething">Click me!</Button>
  </div>
</template>

<script>
  export default {
    props: {
      params: Object
    },

    methods: {
      doSomething() {
        console.debug('doSomething clicked, row data:', this.params)
      }
    }
  }
</script>
```

import 进来

```
import TableActions from './table-actions.vue'
```

之前的数据页， column 的 render 定义为：

```
//...
column: [
  // .....
  {
    title: '操作',
    render(h, params) {
      return h(TableActions, {
        props: {
            params: params
        }
      })
    }
  }

  // .....
]
//...
```

在独立的 component 中想怎么写实现都行。
就是感觉太绕了。和表格数据不在一起，在用 Bus 通过 `$emit`, `$on` 来实现组件之间的通信，好麻烦的。

但是我现在就是在用这种……
不知道其他人？

**Comment by icarusion** [comment]
对于简单的模板，直接使用 Render 就好，复杂的可以使用 JSX

**Comment by lvqingan** [comment]
感觉render改为调用vue.js的render函数后使用难度增大了，能不能考虑使用slot的方式来实现？

**Comment by icarusion** [comment]
@lvqingan 暂无此计划

**Comment by lvqingan** [comment]
刚才试了下JSX，确实比硬写render函数要清晰多了 [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx#usage)

**Comment by yinheli** [comment]
我用 jsx 的时候发现有些 component 没有 `register` 不知道什么原因

**Comment by lvqingan** [comment]
@yinheli 目前只发现Icon没有register，我也不知道什么原因，反正`import {Icon} from 'iview'`就好了

**Comment by sadenwang** [comment]
我也后悔更新了····样式全丢了

**Comment by mcc108** [comment]
#930  这个问题谁能帮忙看看唉，也是处理rc13版中Table组件的render函数时导致了

**Comment by justnowanna** [comment]
@nelsonnick 请问你现在是怎么实现的呢？我也遇到这个问题了，要根据情况判断要显示哪些按钮。

**Comment by lvqingan** [comment]
@justnowanna `return h(...);`之前定义一个数组，用if else判断`params.row`里的值来决定是否push进去

**Comment by justnowanna** [comment]
@lvqingan 额。这样的话dom里面也没有，那就不能在需要的时候再显示了。总感觉render改了复杂了不少。`v-for` `v-model` 这些都不能用了，我这里要做一个表格的行内编辑。。

**Comment by nelsonnick** [comment]
@justnowanna，我又独立写了一个按钮组件，实在是想不到更好的办法了。。。

**Comment by justnowanna** [comment]
![qq 20170517095152](https://cloud.githubusercontent.com/assets/7813730/26135187/7da4ec28-3ae6-11e7-929d-72fe80f7446c.png)

目前是这样解决的，给大家个参考。

https://github.com/iview/iview/issues/934
另外这个有没有人有解决办法的？

**Comment by justnowanna** [comment]
建了一个QQ交流群，大家有时间加一下，有些问题不能提Issue可以在群里问。
416359347 416359347 416359347

**Comment by nelsonnick** [comment]
@yinheli 我有一个新的问题：如果数据表里面有type和state两列内容，后面的操作按钮是根据这两列的内容判断生成的，render里面的params参数，包含的是当前单元格的信息，要么是type，要么是state，不可能都包含。这样的话，哪怕是单独写一个组件也没用啊。

**Comment by justnowanna** [comment]
params包含的是当前行的信息吧，里面有type也有state.

**Comment by yinheli** [comment]
@nelsonnick 你的问题解决了么？我建议通过 Bus 来通信，将整个表格的数据都传递过去。新组件就能处理整个数据（上下文）了

**Comment by nelsonnick** [comment]
@justnowanna 你说得对。我一直以为只包含当前单元格的信息呢

**Comment by nelsonnick** [comment]
@yinheli 已经按照你的方法解决了，多谢多谢！

**Comment by justnowanna** [comment]
@lvqingan 您好，能贴一点table里面的render方法使用jsx的代码吗？我现在使用遇到一个问题，Button组件里面的onClick会自动触发，刷新页面就会触发，没有点击。请问有遇到过吗？
![1112](https://cloud.githubusercontent.com/assets/7813730/26395112/b24d2240-40a1-11e7-923a-75c866e0a622.png)

**Comment by justnowanna** [comment]
发现原因了，不能传递参数，传递参数就会自动执行。没看到jsx哪里写了怎么传递参数的呢

**Comment by justnowanna** [comment]
知道了。给后来看到的说下。
`onClick={this.resendOrder.bind(this, 888)}`, 要这样做，到recat社区找到的。
http://react-china.org/t/onclick/4529/2

**Comment by lvqingan** [comment]
@justnowanna 我觉得这样复杂了，可以这么写
```javascript
onClick={() => {this.renderOrder(params.row.orderId)}}
```

**Comment by liniu** [comment]
用slot的方式来实现更直观一些，人个感觉:)
