### ISSUE TITLE
步骤条动态赋值错误

### ISSUE THREAD

**Issue by Oscarppuccino** [iview/iview#918]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
windows 7/Chrome 52

### Vue 版本号
2.2.2

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/OmEbWq?editors=1111

### 复现步骤

第一次动态赋值OK
第二次改变参数就会乱掉

### 问题现象，以及你期望的结果是怎样的?

希望能够尽快修改，或者提供解决办法

**Comment by Blackloser** [comment]
这是因为动态赋值后  组件样式并没有去动态的改变。。。这边样式属于给死值才会正常显示。。。

**Comment by starmarker** [comment]
这个应该已经mounted之后再改变导致出了问题,实际上我在beforeMount的之后执行change，则没有问题。

**Comment by rijn** [comment]
Probably you need to rerender it after changing values.

**Comment by icarusion** [comment]
把 Vue 和 iView 更新后是可以的，注意 `key` 的用法。
https://codepen.io/Aresn/pen/QqyzZB

**Comment by Blackloser** [comment]
this.$nextTick(()=>{
     this.$refs.XXX.updateChildProps()
})
这样也是可以的 @icarusion
