### ISSUE TITLE
Form-item的验证规则动态改变时，验证视图没有更新

### ISSUE THREAD

**Issue by HarryPoint** [iview/iview#919]
### iView 版本号
 2.0.0-rc.13 

### 操作系统/浏览器 版本号
win64/Chrome 56 

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

<pre><code>
var App = new Vue({
    data() {
        return {
            form: {
                encryption: '',
                key: ''
            },
            rule: {

                encryption: [{
                    required: true,
                    message: '请选择加密方式',
                    trigger: 'change'
                }],
                key: [{
                    required: true,
                    message: '请输入wifi密码',
                    trigger: 'blur'
                }, {
                    type: 'string',
                    min: 8,
                    max: 63,
                    message: 'wifi密码为8~63个字符',
                    trigger: 'blur'
                }]

            }
        }
    },
    methods: {
        handleEncryptionChange(val) {
            if (val == 'none') {
                this.rule.key = [];
            } else {
                this.rule.key = [{
                    required: true,
                    message: '请输入wifi密码',
                    trigger: 'blur'
                }, {
                    type: 'string',
                    min: 8,
                    max: 63,
                    message: 'wifi密码为8~63个字符',
                    trigger: 'blur'
                }]
            }
        },
        handleSubmit(name) {
            this.$refs[name].validate((valid) => {
                if (valid) {
                    this.$Message.success('修改成功！请等待10秒', 10);
                } else {

                    this.$Message.error('表单验证失败!');
                }
            })
        },
        handleReset(name) {
            this.$refs[name].resetFields();
        },
    }
});
App.$mount('#app');
</code></pre>
<code>    template: `
                <Form ref="formValidate" :model="form" :rules="rule" :label-width="90">
                    <Form-item label="加密方式" prop="encryption">
                        <Select v-model="form.encryption" @on-change="handleEncryptionChange">
                            <Option value="none">开放</Option>
                            <Option value="psk">WPA-PSK</Option>
                            <Option value="psk2">WPA2-PSK</Option>
                            <Option value="psk-mixed">WPA/WPA2混合加密</Option>
                        </Select>
                    </Form-item>
                    <Form-item label="wifi密码" prop="key">
                        <Input v-model="form.key" placeholder=""></Input>
                    </Form-item>
                    <Form-item>
                        <Button type="primary" @click="handleSubmit('formValidate')">提交</Button>
                        <Button type="ghost" @click="handleReset('formValidate')" style="margin-left: 8px">取消</Button>
                    </Form-item>
                </Form>
              `
</code>
### 复现步骤
切换加密方式，wifi密码的验证规则改变，但视图显示上并没有实时反映。
1.切换加密方式到除开放外的任意选项。并触发wifi密码框的验证
2.切换加密方式到开放，wifi密码框仍然显示为之前的错误提示，并未改变。
### 问题现象，以及你期望的结果是怎样的?
期望能即时反映出验证规则的修改，或者提供一种钩子函数来适应此种情况

**Comment by icarusion** [comment]
#699
