### ISSUE TITLE
对话框抖动

### ISSUE THREAD

**Issue by qinshenxue** [iview/iview#92]
对话框打开时“隐藏”窗口滚动条，对话框关闭时，窗口滚动条出现，而对话框还没彻底关闭，会向左抖动一下再隐去。

**Comment by icarusion** [comment]
什么浏览器

**Comment by qinshenxue** [comment]
![2](https://cloud.githubusercontent.com/assets/10354498/20467742/a2687308-afc8-11e6-8f65-0e9ab6df5c3e.gif)
应该所有浏览器都有这个问题吧？

**Comment by icarusion** [comment]
https://github.com/iview/iview/blob/master/src/utils/assist.js
这里getScrollBarSize方法就是用来解决这个问题的。你的是什么系统和浏览器？

**Comment by qinshenxue** [comment]
chrome  54.0.2840.99 m 
win7

**Comment by icarusion** [comment]
一会找一个win7的我试试

**Comment by qinshenxue** [comment]
嗯，我还测试了下其他框架（隐藏滚动条），貌似没这个问题。

**Comment by icarusion** [comment]
确实会抖动

**Comment by angusjiang** [comment]
@icarusion  抖动的问题解决了，我这里model 弹框过大的时候，关闭时，抖动更明显的，关闭时的动画能流畅些吗
