### ISSUE TITLE
Table 组件中某一行数据更新 无法触发重新render

### ISSUE THREAD

**Issue by tfzxyinhao** [iview/iview#920]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
windows 8.1 / chrome 58

### Vue 版本号
2.3

### 问题现象，以及你期望的结果是怎样的?
修改了某一行数据后table没有重新render这一行
希望提供一个方法手工触发重新row render

代码: https://jsfiddle.net/8cvqraog/8/

**Comment by icarusion** [comment]
按要求提问

**Comment by tfzxyinhao** [comment]
@icarusion 这个issue能重新开放吗 我已经提供了代码

**Comment by icarusion** [comment]
查看 Vue $set 用法
