### ISSUE TITLE
Tabs关闭异常，页签与正文不对应

### ISSUE THREAD

**Issue by aaron0713** [iview/iview#924]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
windows10 Chrome 57.0.2987.133 (64-bit)

### Vue 版本号
2.3.3

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/aaron0713/pen/ybEoeQ

### 复现步骤
点击按钮【Tab1~6】打开新的六个页签
然后 激活6号页签

### 问题现象，以及你期望的结果是怎样的?
删除1~5任意页签，就会出现问题
1、页签删除异常
2、页签与正文无法对应

希望页签能与页面对应起来，页签删除不会出错。
页签列表内必须是对象
Tabs:[
    {name:"",title:"",url:"",icon:""}
]
name相同的对象不会在Tabs内重复存在，如果已存在，应该激活指定的页签，不会重复创建。

**Comment by icarusion** [comment]
使用 `key`

**Comment by aaron0713** [comment]
使用key也会出现同样的问题。

**Comment by icarusion** [comment]
:key="new Date"

**Comment by aaron0713** [comment]
谢谢
