### ISSUE TITLE
无法用 v-bind 绑定 Modal对话框的 visible 属性

### ISSUE THREAD

**Issue by fuchen** [iview/iview#927]
### iView 版本号
2.0.0-rc.13 

### 操作系统/浏览器 版本号
Windows 10/Chrome 58

### Vue 版本号
2.3.4

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://jsfiddle.net/uyzc2z0a/1/

### 复现步骤 / 问题现象 / 可能的原因
根据文档，Modal 对话框有`visible`属性。但实际上，`visible` 在 `data` 里，而不是 `prop` 里。这样会导致无法使用 `v-bind:visible` 来控制对话框的显示关闭（而只能被迫用`v-model`）。

**Comment by icarusion** [comment]
文档写错了，没有更正过来。
2.0 没有 visible 了，也没有 .sync，受控是 value。

**Comment by icarusion** [comment]
https://github.com/iview/iview-doc/commit/783f20537d8c472400f9724c97ec7441bb74edb8
