### ISSUE TITLE
transform-vue-jsx导致iView构建时报错：UglifyJs无法压缩vendor.js

### ISSUE THREAD

**Issue by mcc108** [iview/iview#930]
### iView 版本号
2.0.0-rc.13

### Vue 版本号
2.2.2

### 能够复现问题的在线示例
`npm run build`过程中出错，无法重现

### 复现步骤
项目通过`vue-cli@webpack`搭建的，因为iView的`2.0.0-rc.13`版本中更新了table的render函数
所以我安装了`transform-vue-jsx`插件以便支持jsx。
然后在`npm run dev`时一些都运行正常，
但是在`npm run build`时，就会出现一下报错：
```
ERROR in static/js/vendor.c3fda59644d305763700.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/._iview@2.0.0-rc.13@iview/src/utils/assist.js:3,0][static/js/vendor.c3fda59644d305763700.js:28308,13]
```
.babelrc配置
```
{
  "presets": [
    "es2015",
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime", "transform-vue-jsx"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
```
其他的配置都是`vue-cli`构建时默认的

**Comment by mcc108** [comment]
原因好像是vendor.js中的es6没有被babel转换为es5。
然而之前iView `2.0.0-rc.10`，没有加入`transform-vue-jsx`插件时运行就没问题

**Comment by mcc108** [comment]
问题解决了。
改变在jsx中需要引入的iView组件方式
* 错误的方式（导致上述错误）：
```
import Poptip from 'iview/src/components/poptip';
```
* 正确的方式：
```
import { Poptip } from 'iview';
```

**Comment by justnowanna** [comment]
@mcc108 您好，能贴一点`table`里面的`render`方法使用`jsx`的代码吗？我现在使用遇到一个问题，`Button`组件里面的onClick会自动触发，刷新页面就会触发，没有点击。请问有遇到过吗？
![1112](https://cloud.githubusercontent.com/assets/7813730/26394829/cdd4e83c-40a0-11e7-99be-f40d9b74297d.png)

**Comment by mcc108** [comment]
@justnowanna 
```jsx
onClick={this.resendOrder(params.row.orderId)}
```
这一句里面的`resendOrder()`会在渲染时就执行，
所以需要将 `{` `}` 中的内容改为一个没有调用的函数形式，大概思路：
```jsx
onClick={() => this.resendOrder(params.row.orderId)}
```
（没测试过上面这样对不对，思路是这样）

**Comment by justnowanna** [comment]
@mcc108 好的，谢谢，就是这样的。
