### ISSUE TITLE
做了个合并单元格和行展开收起的功能

### ISSUE THREAD

**Issue by dean5277** [iview/iview#931]
业务对table的需要比较大，所以自己在iview的基础上新增了table的功能，需取。
不过是基于 2.0.0-rc.12版本的，听说最新版本的render重构了，所以暂时不支持最新的功能，晚点合并下代码再提交下。
https://github.com/dean5277/iview-table-change

**Comment by dean5277** [comment]
已经兼容了rc.1.3

**Comment by lid1987** [comment]
支持，正好需要用到显示子项目，希望可以合并到iview

**Comment by zhouboluo** [comment]
iview中还没有么

**Comment by icarusion** [comment]
updated

**Comment by henjue** [comment]
iview中还没有添加合并单元格功能。。。。。

**Comment by ArvinSpace** [comment]
![image](https://user-images.githubusercontent.com/12440906/43134382-7f9f6c0e-8f74-11e8-9255-bb1e40dc7552.png)
有BUG
