### ISSUE TITLE
表格多表头及最小宽度问题

### ISSUE THREAD

**Issue by couldJoker** [iview/iview#932]
### iView 版本号
 2.0.0-rc.13

### 操作系统/浏览器 版本号
 windows 7/Chrome 57.0.2987.133

### Vue 版本号
2.2.2 

### 问题现象，以及你期望的结果是怎样的?
表格设置最小宽度无效，表格没有多表头，希望和element组件一样

**Comment by rchlz** [comment]
这个issue是被无效关闭了，还是解决了？
