### ISSUE TITLE
带按钮的表格报错

### ISSUE THREAD

**Issue by AyumiKai** [iview/iview#933]
vue版本号2.2.6， iview版本号2.0.0-rc.12，
表格想添加查看和编辑按钮，但是报错，
render: (h, params) => {
            return h('div', [
              h('Button', {
                props: {
                  type: 'text',
                  size: 'small'
                }
              }, '查看'),
              h('Button', {
                props: {
                  type: 'text',
                  size: 'small'
                }
              }, '编辑')
            ])
       }
错误信息是: vue.esm.js?65d7:434 [Vue warn]: Error in nextTick: "TypeError: h is not a function"

**Comment by icarusion** [comment]
rc.13
