### ISSUE TITLE
使用v-show隐藏的table宽度不正常，无法自适应宽度

### ISSUE THREAD

**Issue by justnowanna** [iview/iview#934]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
Win10/Chrome 56

### Vue 版本号
2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

[https://jsfiddle.net/galence/d0boapbz/1/](https://jsfiddle.net/galence/d0boapbz/1/)

### 复现步骤
点击切换两个table的显示和隐藏状态

### 问题现象，以及你期望的结果是怎样的?
默认显示的table是正常能获取到宽度的，而默认隐藏的table则没有正确获取宽度。

### 你估计可能的原因是什么（选填）？
没有获取默认为隐藏的元素的真实宽度

**Comment by justnowanna** [comment]
@icarusion 您好，能不能回答一下呢，或许是我的写法不对？我看更新日志里面写的是已经修复了的

**Comment by yinheli** [comment]
@justnowanna 建议用 v-if 先规避一下

**Comment by justnowanna** [comment]
@icarusion 还有一个问题，table的render会多次被调用，这个是正常的吗？我的表格里面只有一行，但是render被调用了4次。

**render方法：**

![11](https://cloud.githubusercontent.com/assets/7813730/26149336/80c783fc-3b2c-11e7-8c7c-45d11039f9a1.png)

数据：
![22](https://cloud.githubusercontent.com/assets/7813730/26149094/8a1869fe-3b2b-11e7-812f-081e25188e39.png)

结果
![333](https://cloud.githubusercontent.com/assets/7813730/26149270/454a5dcc-3b2c-11e7-8b50-9adeb2bfd3d7.png)

**Comment by justnowanna** [comment]
补充一个在线查看，用的官网的例子。看console里面打印了8次。
https://jsfiddle.net/galence/d0boapbz/3/

**Comment by yinheli** [comment]
@justnowanna 现在是采用兼容老版本的方案，在调用出异常的时候，捕获采用新版本的方案。你的 log 放在了开头，所以都会被调用到。

这个会应该会在后续的更新中，移除对老版本的兼容。

**Comment by wiladog** [comment]
table 组件是否可以把reset方法接口暴露出来，在容器宽度改变时无法进行自适应（窗口或者上级容器变窄时，是无法适应的）

**Comment by rubine413** [comment]
同上，table所在容器宽度变化时table没有自适应, 导致右边出现一段空白

**Comment by yangshaoyu** [comment]
同上设置Table暴露宽度重置接口

**Comment by ZhangShuangV** [comment]
我是通过官网示例layout中的最后一个，通过span来控制表格大小的。但是表格也是出现不能自适应的问题，要么出现空白，要么显示不全。
同上来个table宽度重置接口。

**Comment by Gxiaomin** [comment]
同上，table外层容器宽度变化，表格宽度无法自适应。

**Comment by chaegumi** [comment]
https://github.com/iview/iview/issues/1440

**Comment by icarusion** [comment]
#690
