### ISSUE TITLE
Model弹窗的title动态变化bug

### ISSUE THREAD

**Issue by 404-NF** [iview/iview#935]
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/bWjVgp

### 问题现象，以及你期望的结果是怎样的?

title值是data里的一个键存储的。点击不同按钮会响应一个函数；该函数根据不同按钮计算返回不同的值以变化弹窗的title值；
当data中存储title值的初始值为空时，则无标题显示，后续标题也无法恢复；

经查源码，发现head部分渲染由一个showHead的值控制；该值仅在mounted时计算一次，故无法后续响应

建议showHead的计算由computed控制计算

**Comment by icarusion** [comment]
更新 iView
