### ISSUE TITLE
rc.13版本的Table里的render函数里的this指向有问题

### ISSUE THREAD

**Issue by AyumiKai** [iview/iview#936]
render: (h, params) => {
                            return h('div', [
                                h('Button', {
                                    props: {
                                        type: 'primary',
                                        size: 'small'
                                    },
                                    style: {
                                        marginRight: '5px'
                                    },
                                    on: {
                                        click: () => {
                                            this.show(params.index)
                                        }
                                    }
                                }, '查看'),
                                h('Button', {
                                    props: {
                                        type: 'error',
                                        size: 'small'
                                    },
                                    on: {
                                        click: () => {
                                            this.remove(params.index)
                                        }
                                    }
                                }, '删除')
                            ]);
                        }
这里的this.show并不能找到methods里的show方法,求怎么解决

**Comment by yangdan8** [comment]
我也遇到同样的问题

**Comment by AyumiKai** [comment]
我知道怎么解决这个this的只想问题了，在data方法里把var _self = this 就可以了

**Comment by dean5277** [comment]
了解箭头函数的this

**Comment by qinghua5453** [comment]
请问 你们的this指向问题解决了吗
