### ISSUE TITLE
webpack 运行和编译时 babel 会提示代码超过100KB而取消优化

### ISSUE THREAD

**Issue by ChiHai-Chuck** [iview/iview#94]
[BABEL] Note: The code generator has deoptimised the styling of "E:/lectek/kepureader/node_modules/iview/dist/iview.js" as it exceeds the max of "100KB".

**Comment by jingsam** [comment]
iview.js 不需要babel进行第二次转码，请在webpack设置 `{ test: /\.js$/, exclude: /node_modules/, loader: 'babel' }`
