### ISSUE TITLE
Modal组件里的Table的排序字段click时，tip表示框错位

### ISSUE THREAD

**Issue by larryu** [iview/iview#940]
iView 版本号

2.0.0-rc.13

操作系统/浏览器 版本号

CentOS/Chrome
Windows/IE11

Vue 版本号

2.2.6

能够复现问题的在线示例

复现步骤

把Table组件写在modal里面的表单中

问题现象，以及你期望的结果是怎样的?

我的布局是modal里有个Table，其中一个子段可以排序
-Modal
----Table

这个问题和 https://github.com/iview/iview/issues/818 很类似，可以在自己的css里强制修改position属性解决，但是这只是一个临时的办法，希望iview内部能解决。

**Comment by icarusion** [comment]
#818
