### ISSUE TITLE
Cascader设置了默认值后异步请求次数异常

### ISSUE THREAD

**Issue by lvqingan** [iview/iview#941]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
macOS/Chrome 59

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
[https://codepen.io/anon/pen/ybqZYd](https://codepen.io/anon/pen/ybqZYd)

### 复现步骤
1. Cascader设置v-model的默认值
2. 开启load-data异步加载
3. 显示页面并观察load-data函数调用的次数

### 问题现象，以及你期望的结果是怎样的?
如果是省市区的三层结构，理论上应该两次调用load-data，第一次取省，第二次取市即可
但是目前是触发了6次调用，两次取省，四次取市

**Comment by icarusion** [comment]
https://github.com/iview/iview/commit/03a904529d5cac75faa7cbe0d5c3a61dba7543fa
