### ISSUE TITLE
poptip的样式貌似有bug?

### ISSUE THREAD

**Issue by wuceyang** [iview/iview#945]
![image](https://cloud.githubusercontent.com/assets/1538757/26137863/b39da174-3af7-11e7-93ed-15a611faf7c0.png)
如图，页面样式都是来自于iviewui官网，布局代码也是，但是顶部的poptip被容器遮挡了一部分。尝试给ivu-poptip-popper这个样式增加z-index:9999,还是无法全部显示

**Comment by icarusion** [comment]
应该层级关系吧，建议调整页面布局层级
