### ISSUE TITLE
动态生成的menu无法设置open-names

### ISSUE THREAD

**Issue by abc127890** [iview/iview#947]
动态生成的menu无法设置open-names，已经好多人都提这个问题了 ，为啥还没解决呢

**Comment by leoouc** [comment]
把每个submenu的name设置成全局唯一，如果是这次生成的menu中有个name是1，下次生成也有个是1，那就会有问题，另外要在更新menu时调用
this.$nextTick(() => {
          this.$refs["menu"].updateOpened()
          this.$refs["menu"].updateActiveName()
        })

**Comment by abc127890** [comment]
thank you！可以了。
但是这个有点过于难用了  应该是控制属性就可以了 就好了 ，那样方便很多

**Comment by areyouse7en** [comment]
这样使用很不方便啊，希望改进
