### ISSUE TITLE
Select 选择器 远程搜索 单选的时候 删除输入框的值，鼠标离开后又会自动带着之前选的值

### ISSUE THREAD

**Issue by yangchao313** [iview/iview#951]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
win7/Chrome 56

### Vue 版本号
 2.2.1

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://www.iviewui.com/components/select

### 复现步骤
在远程搜索单选的输入值，然后删除后 鼠标离开

### 问题现象，以及你期望的结果是怎样的?
删除后不显示

**Comment by icarusion** [comment]
`clearable` 是清空。

**Comment by yangchao313** [comment]
用远程搜索的时候 默认值带不出来，必须鼠标点击后离开才能出来

**Comment by icarusion** [comment]
@yangchao313 另开一个issue吧，带上在线示例

**Comment by yangchao313** [comment]
好的

**Comment by pedrohe888** [comment]
这个问题修复好了吗？2.13.1 版本都还在
