### ISSUE TITLE
用远程搜索的时候 默认值带不出来，必须鼠标点击后离开才能出来

### ISSUE THREAD

**Issue by yangchao313** [iview/iview#952]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
win7/Chrome 56

### Vue 版本号
2.2.1

### 复现步骤
http://runjs.cn/detail/tqu5r3zy
### 问题现象，以及你期望的结果是怎样的?
使用正常

**Comment by lvqingan** [comment]
首先，你的例子是有问题的，那个aaaa不应该被显示出来，那是value，不是label
其次，aaaa之所以被显示出来是因为bug #915， rc14里会被修正
最后，个人认为，远程搜索的默认值的问题，得自己在mounted里处理，而不能依赖组件

**Comment by BlueGene89** [comment]
@icarusion 所以是否关于远程搜索，官方能不能给一个比较全面的demo，默认值应该如何处理比较合适

**Comment by icarusion** [comment]
@BlueGene89 iView 的bug，正在解决，下个版本更新。

**Comment by BlueGene89** [comment]
@icarusion thanks，已经用于生产项目了
