### ISSUE TITLE
[feature]关于dropdown的click事件

### ISSUE THREAD

**Issue by mbc3320** [iview/iview#954]
iview提供的dropdown组件，只提供了一个on-click事件，然后根据dropdown-item的name判断点击了哪个按钮，这样，如果把dropdown用在表格的时候，我目前就遇到了一个问题，如图：

![image](https://cloud.githubusercontent.com/assets/5523726/26186049/6bdbb2d4-3bc1-11e7-8c31-49fb929432f9.png)

如果在dropdown绑定一个总处理，然后根据name值判断点击了哪一个选项，但是这个id，该怎么传？
![image](https://cloud.githubusercontent.com/assets/5523726/26186310/3c250e58-3bc3-11e7-8a2c-4a3eda46f1dd.png)

如果操作列用按钮组，当功能很多的时候，就肯定不适合，用dropdown就比较完美解决扩展问题。但是按照目前iview的设计，我确实找不到好的办法处理这个id的问题。

**Comment by lvqingan** [comment]
完全没问题，看我的例子
[https://codepen.io/anon/pen/JNaaEV](https://codepen.io/anon/pen/JNaaEV)

**Comment by icarusion** [comment]
@lvqingan 谢谢回答
