### ISSUE TITLE
table数据有更新时，table不会更新

### ISSUE THREAD

**Issue by QiiSyhx** [iview/iview#955]
### iView 版本号
 2.0.0-rc.13

### 操作系统/浏览器 版本号
windows7/Chrome 56

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/anon/pen/XRPBoZ

### 复现步骤
点击表格的edit按钮，更新列表数据,列表数据status发生改变，但是列表status没有更新为相应状态
### 问题现象，以及你期望的结果是怎样的?
表格数据及时更新

**Comment by lvqingan** [comment]
不用那么复杂啊
```javascript
editLine: function(index){
  this.list[index].status = ! this.list[index].status
}
```
就OK了啊
