### ISSUE TITLE
一个页面多个 Upload 组件的问题

### ISSUE THREAD

**Issue by zanseven007** [iview/iview#956]
如果一个页面存在多个组件，并且是由 v-for 遍历出来的，他们共用一个 handleProgress，handleSuccess 等事件函数，同时上传的时候如何区分函数返回的是哪一个Upload 的值

**Comment by ljwrer** [comment]
handleProgress接收index参数

**Comment by icarusion** [comment]
我唯一的建议就是不要这么做。

**Comment by docikaci** [comment]
同样遇到一个页面有多个上传的需求，而且是for循环出来的， 怎么和数据里的附件列表字段映射？ 
   无解了？  
@zanseven007  最后怎么解决的呢？

**Comment by rijn** [comment]
I would suggest wrapping `Upload` into another component.

**Comment by zanseven007** [comment]
@docikaci 点击的时候加了一个方法，把 index 传了过去存起来，处理数据的时候根据这个 index 来处理，但是可能会有其他问题发生

**Comment by docikaci** [comment]
@zanseven007   放弃了upload组件，写了个方法， 使用原生上传，可以直接传当前item，自由控制。哈

**Comment by wengcd** [comment]
same question
