### ISSUE TITLE
Select 绑定值之后，第一次点击只出现绑定的值对应的下拉，再次点击可以了

### ISSUE THREAD

**Issue by tangolivesky** [iview/iview#957]
### iView 版本号
2.0.0-rc.13 

### 操作系统/浏览器 版本号
 macOS/Chrome 56 

### Vue 版本号
 2.2.1 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/tangolivesky/pen/KmxbmZ

### 复现步骤

1. 点击下拉框，出现选择城市的下拉列表
2. 点击click me , 绑定了一个 chongqin 的值 给 下拉框
3. 点击下拉框，下拉框中只出现了 重庆，其他城市没有了
4. 再次点击下拉框，下拉框中 其他城市又出现了

### 问题现象，以及你期望的结果是怎样的?

很容易误导用户
期望的结果是希望绑定了值之后， 点击下拉框还是出现所有的城市，并且选中了绑定的值对应的城市

**Comment by tangchaoren1** [comment]
这个问题在iview2.14.3版本依然存在，没有修复啊
