### ISSUE TITLE
新版r13的table组件，排序导致新的render函数重复渲染

### ISSUE THREAD

**Issue by xiaocuyu** [iview/iview#958]
### iView 版本号
 2.0.0-rc.13

### 操作系统/浏览器 版本号
Chrome 59 

### Vue 版本号
 2.3.3 

### 能够复现问题的在线示例

https://codepen.io/xiaocuyu/pen/ybxZbW

### 复现步骤

点击排序按钮

### 问题现象，以及你期望的结果是怎样的?

用新版的render函数，渲染的按钮会多次渲染。用旧版的方法则没有这个问题

### 你估计可能的原因是什么（选填）？
重复渲染了

**Comment by itpretty** [comment]
遇到同样问题！还有，通过 render 设定“操作”列后，如果同时设定此列 fixed: "right" 和表格高度，右侧的竖向滚动条会被“操作”列遮住。烦请一并修复，谢谢！

**Comment by icarusion** [comment]
Table 是由不同的几部分组成的，需要计算列宽

**Comment by xiaocuyu** [comment]
那个渲染的问题现在是暂时不能解决是吧

**Comment by icarusion** [comment]
这个问题确实比较严重，我再想想要不要这个版本直接去掉

**Comment by icarusion** [comment]
#934

**Comment by justnowanna** [comment]
@icarusion 
`Render`方法太恼火了，我表格里面只有一行，但是会被多次调用。这个就不说了，关键是第一次调用的时候第一个参数是`row`, 第二次调用的时候第一个参数才变成`h`,第二个参数也存在了。我在`Render`里面处理`params`, 第一次处理就会报错。现在看起来应该是为了兼容旧版本而做的，但是能不能发布一个不兼容旧版本的，旧版本就用rc13之前的不就好了吗？建议不要做兼容旧版，感觉后面容易做乱啊。

**Comment by justnowanna** [comment]
@icarusion 补充在线查看，现在遇到更神奇的事情了，params永远都是column的信息，不返回返回行数据了。

**Comment by justnowanna** [comment]
https://jsfiddle.net/galence/p69go9rc/1/

**Comment by icarusion** [comment]
@justnowanna 
![image](https://cloud.githubusercontent.com/assets/5370542/26242606/9c88acb6-3cbb-11e7-9a9b-0544e5ad7c98.png)

**Comment by justnowanna** [comment]
@icarusion 麻烦您看一下我给的在线示例，在控制台里面打印了8次，每次都是打印的`column`的内容，没有`row`,没有`index`，版本是rc13。我知道你这里说的意思，我觉得是第一次调用的老版本的render,第二次才是调用的新版本的render.所以params的值是不一样的。

**Comment by icarusion** [comment]
@justnowanna 对于旧版本，render的参数是三个，分别为 row、column、index，对于新的render，参数为 h 和 params，params 又包含之前的三个。对于重复调用的问题由兼容所导致，会在下个版本修复。

**Comment by justnowanna** [comment]
@icarusion 好的，谢谢，现在就是一个重复调用的问题，我在`render`里面`format`时间，第一次调用的时候就会报错，第二次调用才正常，导致控制台里面很多错误，另外就是`Date-picker`选择的时间希望能跟`on-change`中的`格式一致就好了，因为现在页面里面涉及到8个`Date-picker`，导致用`on-change`去处理很繁琐，希望能早点发布。
