### ISSUE TITLE
可否在按需使用插件时，样式和字体文件也按需载入？

### ISSUE THREAD

**Issue by ChiHai-Chuck** [iview/iview#96]
目前，项目中只用了iview面包屑和分页器的组件，却需要载入iview全部的样式和字体文件，css的文件体积还算小，但是却需要载入庞大的iconfont字体文件，而这些图标目前项目中是一个都没用到的，使得项目编译后体积暴增了300多kb，而原来也仅仅是只有400多kb的

**Comment by icarusion** [comment]
iView初衷是一整套的中后台解决方案，故暂不支持分离。
你可以自行修改css减少iconfont的使用

**Comment by shen-lan** [comment]
你的css体积多大？
我的chunk-vendors.177f70bf.css 达到了 260kb。。。。
