### ISSUE TITLE
Checkbox非group时，为什么不加上:value="lable"？？

### ISSUE THREAD

**Issue by longzhaobi** [iview/iview#960]
```
<label :class="wrapClasses">
        <span :class="checkboxClasses">
            <span :class="innerClasses"></span>
            <input
                v-if="group"
                type="checkbox"
                :class="inputClasses"
                :disabled="disabled"
                :value="label"
                v-model="model"
                @change="change">
            <input
                v-if="!group"
                type="checkbox"
                :class="inputClasses"
                :disabled="disabled"
                :checked="currentValue"
                @change="change">
        </span>
        <slot><span v-if="showSlot">{{ label }}</span></slot>
    </label>
```

现在我要动态渲染很多Checkbox，不能用CheckboxGroup组件，都是单个，但发现只能通过value或者v-model设置是否选中，不能给input设置value，如果这样，我咋知道我选中的值是多少？

**Comment by longzhaobi** [comment]
我还是先用<input type="checkbox">这种算了，暂时不用checkbox组件

**Comment by longzhaobi** [comment]
```
if(disabled === 'yes') {
  return `<input type="checkbox" disabled="disabled"></input>`
} else {
  if(isAuth === 'yes') {
    return `
      <input type="checkbox" value="${value}" checked="checked"></input>
   `
  } else {
    return `
      <input type="checkbox" value="${value}"></input>
      `
 }
 }
```
还是先改成这个<input type="checkbox"   算了，

**Comment by longzhaobi** [comment]
@icarusion  关了也可以顺便给个解决方法啊！上次看你视频对你映像挺好的，现在怎么这么高傲了，

**Comment by icarusion** [comment]
Issue 不是给你解答疑惑的。

**Comment by icarusion** [comment]
这种问题需要你自己思考，都来这问我，我哪有那么多时间回答这类问题。
issue 是用于处理 bug，你有疑问，可以去 gitter、sf 探讨。
再者，我也没有义务给你回答，你为开源做过什么贡献吗。

**Comment by longzhaobi** [comment]
如果您在开发中遇到任何问题，包括但不限于 iView、JavaScript、Vue、Webpack、Canvas、WebGL、Node.js 等相关技术，可以加入小密圈和我们一对一提问，收到问题后，我们会在 10 ~ 30 分钟内解答。
因为提供高质量的答疑服务，所以我们暂时收费 ￥98/年 。
如果您不愿意付费，仍然可以在 GitHub 提交与 iView 相关的 issues，我们也会逐一解答。

不好意思，我是被最后一句话带过来的，你们应该把最后一句的意思改一改，

https://segmentfault.com/q/1010000009479981

我去sf提了，我就想知道如何给checkbox底层的input设置value值，反正你们代码貌似只有分组时才能设置。

**Comment by icarusion** [comment]
![image](https://cloud.githubusercontent.com/assets/5370542/26236396/bf142e18-3ca2-11e7-8403-96f750f79a7b.png)

**Comment by levivi** [comment]
啧啧啧，issue真的不能用来答疑解惑吗？
