### ISSUE TITLE
label-in-value传入label有问题

### ISSUE THREAD

**Issue by VolcanoOves** [iview/iview#961]
### 问题现象，以及你期望的结果是怎样的?
当在select 增加 label-in-value 属性之后，点击事件传入的 对象 label 后面跟了 \n\t\t\t\t\t  
![image](https://cloud.githubusercontent.com/assets/18513530/26236501/3507be8c-3ca3-11e7-9187-e1ce76ee8254.png)

**Comment by icarusion** [comment]
按要求提问
