### ISSUE TITLE
Select 为disabled状态的时候， filter功能任然可用

### ISSUE THREAD

**Issue by STMU1320** [iview/iview#962]
### 复现步骤
1.初始化的时候将select设为disabled filter为true的状态，并给select控件设置一个value。此时select显示的value值可以改变
2.触发一个事件将select的disabled设置为false， 此时select的初始值会称为filter的条件，点击select输入框仅会出现一条候选item
### 你估计可能的原因是什么（选填）？
select的初始值会称成为了filter的条件

**Comment by SergioCrisostomo** [comment]
@STMU1320 many good improvements have been made since may. 
I think this is fixed, can you please check with current version `2.2` and provide a example if not fixed yet?

使用下面的在线链接可以快速创建示例 
https://codepen.io/anon/pen/KvJJdw

**Comment by icarusion** [comment]
#1547
