### ISSUE TITLE
Transfer组件 [Vue warn]: "style" is a reserved attribute

### ISSUE THREAD

**Issue by Ysanwen** [iview/iview#963]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
macOS/Chrome 56 

### Vue 版本号
2.3.3 

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）
https://codepen.io/anon/pen/xdypjB?editors=1111
### 问题现象，以及你期望的结果是怎样的?
开发模式下,console出现以下警告
![image](https://cloud.githubusercontent.com/assets/17737263/26237537/2081d452-3ca8-11e7-9274-3c0d21c76760.png)
### 你估计可能的原因是什么（选填）？
Transfer组件中定义props时采用了style字段,与vue保留字段冲突.

**Comment by icarusion** [comment]
已解决，会在下个版本更新
