### ISSUE TITLE
Table组件中render Dropdown组件，无法触发Dropdown的on-select事件

### ISSUE THREAD

**Issue by mh0625** [iview/iview#964]
### iView 版本号
2.0.0-rc.13

### 操作系统/浏览器 版本号
macOS/Chrome 58

### Vue 版本号
2.2.6

### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/anon/pen/vmVpXo

### 问题现象，以及你期望的结果是怎样的?
用table组件，table中render渲染 Dropdown，需要给Dropdown添加一个on-select事件触发chagneStatus函数

### 你估计可能的原因是什么（选填）？
添加 on-select 事件的位置不对

**Comment by icarusion** [comment]
如果写正确的话，this 指向的就是当前 Vue 实例

**Comment by mh0625** [comment]
代码修改了，this指向了当前Vue实例，但是 on-select 事件还是没有触发

**Comment by mh0625** [comment]
问题解决了，是我把事件的位置放错了，应该放在Dropdown里，而不是Dropdown-menu；而且事件是on-click，不是on-select
