### ISSUE TITLE
麻烦问下，使用cdn的方式，如果只使用部门功能？

### ISSUE THREAD

**Issue by 544751779** [iview/iview#965]
我们的页面是使用cdn方式，但是只用到了其中表单的部分，怎样我们只加载表单这些东西呢？

**Comment by icarusion** [comment]
你都用 cdn 了，整个 iView 就加载进来了，所以无法按需。

**Comment by 544751779** [comment]
我的意思是，cnd可以下载啊，怎么把cdn下载的东西瘦身一下？  可能我表述的不清晰，我们自己有cdn服务器的。

**Comment by icarusion** [comment]
使用 webpack 做按需加载。
