### ISSUE TITLE
select 组件中设置值 0与'0' 数据类型不统一导致无法选择的问题。

### ISSUE THREAD

**Issue by 544751779** [iview/iview#972]
select 组件中设置值 0与'0' 数据类型不统一导致无法选择的问题。

我们在组件中定义了 string 类型的 '0'和'1' 分别代表两个值， 但是 ajax返回的是int类型的0和1

求解，如何做最优处理？

**Comment by 544751779** [comment]
木人回答。。。

**Comment by huixisheng** [comment]
返回数据的`Number`类型数据强制转换为`String`。或者定义`Select`组件的时候为`Number`

**Comment by sadenwang** [comment]
每次提交前都要转一下，也够麻烦的····帮你顶上去

**Comment by 544751779** [comment]
是的，谢谢帮顶
