### ISSUE TITLE
DatePicker控件type='datetimerange'时，on-change获得的返回值为字符串，并非数组。与daterange和timerange不一致。

### ISSUE THREAD

**Issue by zhuhongwei1989** [iview/iview#973]
### iView 版本号

2.0.0-rc.10
### 操作系统/浏览器 版本号

win7/Chrome 58.0.3029.110
### Vue 版本号

2.2.4
### 能够复现问题的在线示例（bug 相关不提供在线示例将直接 close）

https://codepen.io/zhuhongwei1989/pen/wdQZea
### 复现步骤
步骤1、在第一个datetimerange类型的DatePicker中选择任意范围。
步骤2、在第二个daterange类型的DatePicker中选择任意范围。
### 问题现象，以及你期望的结果是怎样的?
步骤1的on-change事件值是一个字符串
步骤2的on-change事件值是一个数组（换成timerange也是数组）
期望：所有range返回数组。
### 你估计可能的原因是什么（选填）？
调试源代码认为应该是src/components/date-picker/picker.vue中的formattingDate方法最后一个if判断条件中少了一个|| type === 'datetimerange'，导致了datetimerange并未正确的解析返回值为数组。

**Comment by suyuTech** [comment]
是的、遇到同样的问题

**Comment by lvqingan** [comment]
遇到同样问题 @icarusion

**Comment by SergioCrisostomo** [comment]
This seems to have been fixed. Please recheck the problem is gone: https://codepen.io/sergiocrisostomo/pen/yoZOdz

And thanks for reporting!
