### ISSUE TITLE
表格中render Input-number 点击无反应

### ISSUE THREAD

**Issue by lhf1990729** [iview/iview#975]
render: (h, params) => {
                       return h('div', [
                           h('Input-number', {
                               props: {
                                   type: 'primary',
                                   size: 'small',
                                   min:1,
                                   max:9
                               },
                               style: {
                                   marginRight: '5px'
                               },
                               on: {
                                   click: () => {
                                      //  this.show(params.index)
                                      alert(1);
                                   }
                               }
                           }, '')
                       ]);
                   }

可以成功显示，但是点击无任何反应！

**Comment by yundmb** [comment]
我也是

**Comment by rbajaniya** [comment]
Try this
```
on: {
     input: (value) => {
         console.log(value) // console new value 
     }
 }
```

**Comment by rohitbajaniya** [comment]
Try this
```
on: {
     input: (value) => {
         console.log(value) // console new value 
     }
 }
```

**Comment by icarusion** [comment]
要去了解如何在 Render 中使用 `v-model`
