### ISSUE TITLE
这种写法无效了么？

### ISSUE THREAD

**Issue by dean5277** [iview/iview#976]
![image](https://cloud.githubusercontent.com/assets/1802631/26303381/14c4e36a-3f1a-11e7-99b1-7bad6ac425b1.png)

**Comment by Hishengs** [comment]
是的，非常方便的写法，然而不知出于什么考虑被弃用了，改成了vue的render函数

**Comment by BlueGene89** [comment]
还需要注意的是需要把之前 context 去掉 ，文档再仔细看看
