### ISSUE TITLE
tabs 在非第一页嵌套tabs时，当外层tabs切换到有子tabs的时候，蓝色横线不显示

### ISSUE THREAD

**Issue by guanjingkai** [iview/iview#977]
### iView 版本号

2.0.0-rc.13
### 操作系统/浏览器 版本号

macOS/Chrome 59
### Vue 版本号

2.3
### 复现步骤
tabs 在非第一页嵌套tabs时，当外层tabs切换到有子tabs的时候，蓝色横线不显示，但是切换子tabs后显示蓝色横线

tabs的第一页嵌套tabs没问题
### 问题现象，以及你期望的结果是怎样的?

tabs嵌套tabs时 显示蓝色横线

**Comment by GuanJingkai** [comment]
回复下呗

**Comment by wendesun** [comment]
在子组件中调用updateBar方法 ， this.$refs.wordBook.updateBar();    wordBook为tabs组件的ref
