### ISSUE TITLE
Tab pane can't change height automatically to fit it's content

### ISSUE THREAD

**Issue by devindwan** [iview/iview#979]
```json
 {
    "iview": "^2.0.0-rc.11",
    "vue": "^2.2.6"
 }

```

![image](https://cloud.githubusercontent.com/assets/10205466/26314132/8ca07d3e-3f3f-11e7-8cbe-b38e2f417f7e.png)
![image](https://cloud.githubusercontent.com/assets/10205466/26314143/9ac84d6a-3f3f-11e7-8276-277b7340324f.png)

There are some contents with different height, each of them is placed in a `<Tab-pane>`. When changing the tab, all the `<Tab-pane>`s will have the same height. It seems that each `<Tab-pane>` should has it's own height instead of a fixed height to fit it's content.

Online demo: https://codepen.io/devindwan/pen/pPqjKo

**Comment by rijn** [comment]
`Tab` will not adjust height for each tab-pane, but use the highest one as its height.

**Comment by icarusion** [comment]
The answer above is correct

**Comment by prime89** [comment]
i rewrite the `tabs.vue` with `mixins`, change the method `updateVisibility` below:

```js
updateVisibility(index){
                [...this.$refs.panes.children].forEach((el, i) => {
                    if (index === i) {
                        [...el.children].forEach(child => child.style.display = 'block');   //+++
                       // [...el.children].forEach(child => child.style.visibility = 'visible'); 
                        setTimeout(() => focusFirst(el, el), transitionTime);
                    } else {
                        setTimeout(() => {
                            [...el.children].forEach(child => child.style.display = 'none');
                           // [...el.children].forEach(child => child.style.visibility = 'hidden'); 
                        }, transitionTime);
                    }
                });
            }
```

**Comment by NE-SmallTown** [comment]
I think this is not a correct or expected behavior, I watch the ant-design, material-ui,  element-ui, all of them don't have this problem, even though they use different implementation.

**Comment by fuerpeng** [comment]
i also have this problem,i think it's a bug

**Comment by luguangzhen** [comment]
Set tabs :animated="false" can fix this problem.
