### ISSUE TITLE
rc14 h is not a function

### ISSUE THREAD

**Issue by dean5277** [iview/iview#981]
用了最新版本的iview,出现h is not a function

改回rc13 问题没出现

**Comment by dean5277** [comment]
![image](https://cloud.githubusercontent.com/assets/1802631/26337428/3b4f132a-3fab-11e7-9d13-0381f9c80f0c.png)

![image](https://cloud.githubusercontent.com/assets/1802631/26337456/66550d5e-3fab-11e7-858e-0609ed6a23dc.png)

**Comment by dean5277** [comment]
对了下官网文档，写法并没有改变

**Comment by lvqingan** [comment]
如果Table加了context的话，把context去掉

**Comment by dean5277** [comment]
是的，删掉就没问题了，Thank you.
