### ISSUE TITLE
select 默认值设置为null而不是""，重置文字不消除

### ISSUE THREAD

**Issue by JD-Wang** [iview/iview#982]
### iView 版本号

"iview": "^2.0.0-rc.12",

### 操作系统/浏览器 版本号

 macOS/Chrome 57.0.2987.133 (64-bit)

### Vue 版本号

 "vue": "^2.2.4",

### 问题现象，以及你期望的结果是怎样的?
![d650cc1d-3653-4f4d-a8d9-80d44d287d45](https://cloud.githubusercontent.com/assets/11517373/26341482/a75e94ee-3fc6-11e7-94ac-0af96dad4a03.png)
设定： select 的v-model默认值设定为 null 而不为 ""
当使用表单重置 handleReset 方法的时候，重置后v-model的值为null是正确的我想要的，但是显示选择的文字任然留在select框内，这个文字我想清空

### 你估计可能的原因是什么（选填）？
在 /components/select/select.vue 组件内147行， showPlaceholder 方法下，没有判断null格式的，作者是否可以加上为null判断

**Comment by JD-Wang** [comment]
在 /components/select/select.vue 组件内147行， showPlaceholder 方法下，没有判断null格式的，作者是否可以加上为null判断

**Comment by JD-Wang** [comment]
@icarusion 能加null格式吗

**Comment by herton7362** [comment]
我也遇到这个问题了，有的时候select默认值确实是null，而不是“”
