### ISSUE TITLE
Tabel中render使用Date-picker不显示

### ISSUE THREAD

**Issue by yundmb** [iview/iview#983]
### iView 版本号
2.0.0-rc.14

### 操作系统/浏览器 版本号
Chrome 58

### Vue 版本号
2.3.3

return h("div", [
						h("Date-picker", {
							props: {
								type: "date",
								placeholder: "选择日期"
							},
							style: {
								width: "200px"
							},
							v: {
								model: params.row.expiration_date
							}
						}, "")
					], "");

**Comment by chenhaizano** [comment]
可以显示，不过指出一下，在render是不能使用v-model，需要配合 domProps.value 和 on.input

[文档](https://cn.vuejs.org/v2/guide/render-function.html#v-model)

h('Date-picker', {
	props: {
		type: 'date',
		placeholder: '选择日期'
	},
	style: {
		width: '200px'
	},
	domProps: {
		value: '2017-05-20'
	},
	on: {
		input: (value) => {
			console.log(value)
		}
	}
}),

**Comment by yundmb** [comment]
@chenhaizano 不行哦，我试了
