### ISSUE TITLE
iview.js 文件保存到本地引用有乱码问题

### ISSUE THREAD

**Issue by dean5277** [iview/iview#984]
本来是UTF8的，后来看到你们线上的是GBK，所以也改GBK了，但是还是存在乱码问题，链接引用线上的没问题。
其实我是建议用UTF8的。

![image](https://cloud.githubusercontent.com/assets/1802631/26340639/190f69c4-3fc2-11e7-98b7-28493a5d069a.png)

**Comment by dean5277** [comment]
如果保存到本地是UTF8格式，更是乱。

**Comment by icarusion** [comment]
应该都是 UTF-8 才对啊，你是从哪里看到是 GBK 的，确实有人遇到这个问题

**Comment by dean5277** [comment]
![image](https://cloud.githubusercontent.com/assets/1802631/26340757/ae71752a-3fc2-11e7-885d-4a22e5e17f64.png)

**Comment by dean5277** [comment]
![image](https://cloud.githubusercontent.com/assets/1802631/26340805/fa5e2abe-3fc2-11e7-8a2e-257f1ad15a68.png)
保存如果是UTF-8格式

**Comment by icarusion** [comment]
我在本地测试，并没有乱码啊。

**Comment by dean5277** [comment]
原因知道了，CDN直接拷贝下的代码乱码。NPM 下载的dist正常

**Comment by dean5277** [comment]
我是这样想的，官网的连接header头没有设置UTF-8或者服务器设置了类型，其他CDN从你们链接那里抓取，所以都错了。

**Comment by icarusion** [comment]
验证了下，如果是直接保存文件，是正常的，复制粘贴到文件，是乱码。

**Comment by CGerAJ** [comment]
从CDN直接保存文件 显示一部分乱码 一部分不乱码 ………………
