### ISSUE TITLE
vuex mapGetters报语法错误

### ISSUE THREAD

**Issue by xumjs8623** [iview/iview#986]
"vue": "^2.2.6",
"iview": "^2.0.0-rc.13",
"vuex": "^2.2.1",
 
使用iView Cli 创建工程，在根据vuex官方案列写法编写时，报语法错误，是不是es6解析相关依赖有问题。
`
 computed: {
            ...mapGetters([
                num: 'getNum'
            ])
        },
`
![image](https://cloud.githubusercontent.com/assets/12467615/26341544/f774e9b0-3fc6-11e7-9f7c-903c89c872c5.png)

**Comment by xumjs8623** [comment]
安装依赖 babel-preset-stage-2 后解决，希望官方iView Cli  在勾选vuex进行状态管理时 能将这个依赖加上去

**Comment by shenke119** [comment]
加了还是报错 @xumjs8623

**Comment by xumjs8623** [comment]
@shenke119  额，我安装上就好了，这个很久了 ，后来我用了element。。。
