### ISSUE TITLE
checkbox-group 绑定点击事件执行两次

### ISSUE THREAD

**Issue by dean5277** [iview/iview#987]
我不知道是不是BUG
![image](https://cloud.githubusercontent.com/assets/1802631/26344293/afdcafa6-3fd1-11e7-80fc-2b18a0c62622.png)

![image](https://cloud.githubusercontent.com/assets/1802631/26344308/bf11fdd2-3fd1-11e7-9318-35a399203f4e.png)
![image](https://cloud.githubusercontent.com/assets/1802631/26344328/d3e61932-3fd1-11e7-9028-6690faf3cbe8.png)

**Comment by icarusion** [comment]
用法不对，参照文档
