### ISSUE TITLE
请问是否准备提供下拉树,下拉表格,高级选择,多值返回这种控件的支持?

### ISSUE THREAD

**Issue by c5ms** [iview/iview#994]
现在在用IVIEW,体验非常好.
公司在做传统类MIS,CRM等开发,需要很多繁杂的组件.
因为字典码都是键值对的,数据库是冗存的.现在公司的控件(NG)是多值返回的(类似key-model=,data-model=).

现在很希望能有下拉树,下拉表格,弹出选择,精准输入等.
我是想了解下咱们目前是否有类似的计划,如果有的话,我就不去自行封装了.

**Comment by c5ms** [comment]
sorry
, we don't need that ,
It's very easy to use  <Select >and <Tree>

**Comment by xcodebin** [comment]
tree need a method to set value
