### ISSUE TITLE
Date-picker日历组件打开的情况下，点击Table里的某行不能将日历组件收起

### ISSUE THREAD

**Issue by AyumiKai** [iview/iview#996]
iview:2.0.0-rc.13
点击Table组件里的某行数据的时候，触发了on-row-click事件，而不是on-select-close，求怎么解决,期望效果是展开Date-picker组件的情况下，希望能点击到Table的某行，能把Date-picker收起来

**Comment by wydingez** [comment]
我也遇到了   展开date-picker组件时，点击table-body中的元素 没有触发自定义指令clickoutside，希望能解决一下

**Comment by icarusion** [comment]
fixed in next version
