### ISSUE TITLE
Menu 导航菜单没找到 route-link to 的功能

### ISSUE THREAD

**Issue by chenlb** [iview/iview#999]
### iView 版本号
2.0.0-rc.14

### 操作系统/浏览器 版本号
macOS/Chrome 58

### Vue 版本号
2.3.3

### 问题现象，以及你期望的结果是怎样的?

[Menu 导航菜单](https://www.iviewui.com/components/menu) 教程中没找到 route-link 功能。要自己加 route-link 但，多生成了一个 a 标签（可以改成 span）。有什么好的办法用 Menu 导航菜单 支持 route-link 的 to 功能

**Comment by lvqingan** [comment]
编程式导航

**Comment by chenlb** [comment]
明白
